### ISSUE TITLE
CRAFTERCMS-1359: translate sites dashboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#10]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: add resource bundle support:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1359
----------

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/179
