### ISSUE TITLE
[studio-ui] Pencils not visible when enabled for empty bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1000]
Use the empty bp, enable the pencils (in-context editing)

![screen shot 2017-06-21 at 2 43 16 pm](https://user-images.githubusercontent.com/25483966/27401145-73c3d15e-5690-11e7-9fd8-b24f35e9730c.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/457

**Comment by alhambrav** [comment]
Verified.
