### ISSUE TITLE
[studio-ui] Dropdown control does not appear in form when editing

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1001]
The dropdown control does not appear in the form when I try to edit or create a new feature component in the website_editorial bp.

1. Use the website_editorial bp to create a site.  In the "Home Page", go to the features section and click on the pencil to edit the section.  
![screen shot 2017-06-21 at 2 30 29 pm](https://user-images.githubusercontent.com/25483966/27400508-49345406-568e-11e7-8312-f1a260cdff98.png)

2. Click on the "Add" button to add another feature, then select "Create New - Feature"
![screen shot 2017-06-21 at 2 32 01 pm](https://user-images.githubusercontent.com/25483966/27400563-7594abc2-568e-11e7-9cbc-c9cdfb63f8d8.png)

3. Here's the form, notice how there's no dropdown list for the icons:
![screen shot 2017-06-21 at 2 33 51 pm](https://user-images.githubusercontent.com/25483966/27400691-dfdf9604-568e-11e7-9d3c-d5635574bddd.png)

If you're creating a new feature, you will not be able to save the form since you cannot select an icon for the feature.

4. Let's look at the Component - Feature content type, notice in the "Content" section, there's a dropdown list, which was missing in the form
<img width="1101" alt="screen shot 2017-06-21 at 2 36 23 pm" src="https://user-images.githubusercontent.com/25483966/27400779-30c78b8a-568f-11e7-95fa-e7e73aab4617.png">

**Comment by vestrada** [comment]
Studio - PR: https://github.com/craftercms/studio/pull/757

**Comment by vestrada** [comment]
Icon dropdown has wrong datasource info in the form-definition.xml. 

<value>featureicons,featureicons,featureicons,featureIcons</value>

It should be: 

<value>feature_icons</value>

This change will fix only new sites.

**Comment by alhambrav** [comment]
Verified.
