### ISSUE TITLE
[studio-ui] Search screen pagination is below visible page area

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1002]
Please see screenshot:
![screen shot 2017-06-21 at 6 10 12 pm](https://user-images.githubusercontent.com/3931908/27409118-d6206818-56ad-11e7-8f12-d0db8fdafe45.png)

Step to Reproduce
==============
- Use an Editorial BP-based site
- Search for "lorem"
- Set pagination to 3
- Note that pagination can be below visible screen

Can this be adjusted so the user sees the pagination more easily? Ping me if you have questions or multiple proposals to discuss.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/513
