### ISSUE TITLE
[studio] Sync from Repository should remove updated items from approved to go live

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1004]
While syncing from repo, for every item that has changed, we must take it out of workflow (if on a schedule).

The reason for this is:
- I change a file in Studio
- I schedule for publishing
- I edit on disk and commit and sync repo
- File shows edited while still in approved
- The older version of the file (the one I edited in Studio) is published (GOOD)
- The file shows as `live` even though a new edit is in (BAD)

Per our conversation:
- Upon completion of a publish of a file, mark the file as `live` only if the `commit_id` in `copy_to_environment` matches that of `object_state`, otherwise leave the state as is

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/767
