### ISSUE TITLE
[studio-ui] Create New - Features form/ Edit features form too small when launched

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1005]
It would be nice to have the **New Component - Feature** form and the **Component Feature** form bigger when launched so you can see more of the fields that needs to be filled out.

1. In the website_editorial bp, edit the features section by clicking on the pencil

![screen shot 2017-06-21 at 2 30 29 pm](https://user-images.githubusercontent.com/25483966/27439158-40ad6b86-5735-11e7-8a7d-c8f99717fa0c.png)

2. Click on the **Add** button in the **Features** field, then select **Create New - Features**

![screen shot 2017-06-21 at 2 32 01 pm](https://user-images.githubusercontent.com/25483966/27439250-898bf67e-5735-11e7-95e3-bc2e690933aa.png)

OR

Select one of the existing features, then click on the **Edit** button

<img width="940" alt="screen shot 2017-06-22 at 10 33 40 am" src="https://user-images.githubusercontent.com/25483966/27439626-600f5de4-5736-11e7-9a95-0e4470564a02.png">

3.  Notice the form launched is small and needs to be expanded down to see more of the fields (or use the scroll button on the side)

<img width="940" alt="screen shot 2017-06-22 at 10 28 43 am" src="https://user-images.githubusercontent.com/25483966/27439359-c7b3da02-5735-11e7-85b4-2c902ed2b0c8.png">

Here's the form that launches when you edit an existing feature (As described above clicking on the **Edit** button:

<img width="933" alt="screen shot 2017-06-22 at 10 35 18 am" src="https://user-images.githubusercontent.com/25483966/27439697-8ec9176a-5736-11e7-8cbe-1fa199ab302d.png">

**Comment by jdrossl** [comment]
@sumerjabri this is not an enhancement, its a issue in the forms because it only happens from the In-Context-Edit form. It seems like the second form will take the same size as the first one opened.

![screen shot 2017-06-23 at 2 39 12 pm](https://user-images.githubusercontent.com/1236955/27499619-e87bd4e6-5821-11e7-89ef-a86674f449cf.png)

**Comment by sumerjabri** [comment]
@jvega-crafter it seems like a bug in the Form Engine. Please take a look and ping me if you have any questions.

**Comment by vestrada** [comment]
sutdio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/475

**Comment by alhambrav** [comment]
Verified fixed.
