### ISSUE TITLE
[studio-ui] Sidebar nav tree icons does not update until you reload the page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1007]
Using the website_editorial bp, edit an article that is unedited.  Below is a screenshot of an unedited article.  Notice the icons for the page in the Sidebar nav tree and the context nav.  Now edit the article by clicking on **Edit** in the context nav or using the pencils.

<img width="923" alt="screen shot 2017-06-22 at 12 17 36 pm" src="https://user-images.githubusercontent.com/25483966/27444629-f069f210-5744-11e7-808a-1ba61436d699.png">

After editing the article, save it and look at the Sidebar and notice that the article icon in the nav tree does not show that the article is edited (The context nav does show that the page is edited).  You need to reload/refresh the page for the icon in the nav tree to reflect the changes to the page.

<img width="999" alt="screen shot 2017-06-22 at 12 19 25 pm" src="https://user-images.githubusercontent.com/25483966/27444873-ad6b61d2-5745-11e7-9614-1ffadb36ce19.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/471

**Comment by alhambrav** [comment]
Verified fixed.
