### ISSUE TITLE
[studio-ui] Context nav displays "Request Publish" after page has been submitted for publish 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1008]
In the website_editorial bp, edit an article and then click on **Request Publish** in the context nav

<img width="998" alt="screen shot 2017-06-22 at 12 32 17 pm" src="https://user-images.githubusercontent.com/25483966/27445284-27b61a26-5747-11e7-9daa-8b731ed78117.png">

After requesting for publish, notice that the context nav still displays **Request Publish** after just sending the request

<img width="990" alt="screen shot 2017-06-22 at 12 32 31 pm" src="https://user-images.githubusercontent.com/25483966/27445371-81556ce4-5747-11e7-9e5e-1e068e598b73.png">

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/465

**Comment by vestrada** [comment]
I removed it from the content top nav and from the right click content nav.

**Comment by alhambrav** [comment]
Verified fixed.
