### ISSUE TITLE
[studio] Studio not refresh when the user delete a content.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#1011]
Steps:

1. Login to craftercms 3
2. Create a site
3. Expand Pages
4. Expand Home
5. Create new content
6. Delete the new content created or some old content.
7. See the content deleted.
8. Refresh the browser.

Current Behavior:
The content is deleted but the page not refresh.

Evidence: https://www.useloom.com/share/86b4828568f54a7e90ab9acd23cc77bb

Expected Bahavior:
Studio should be refresh when the user delete un contenido because the user can see the content deleted.

**Comment by sumerjabri** [comment]
Can't reproduce.
