### ISSUE TITLE
[studio] publishing dependency calculation error in complex cut-paste scenario

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1013]
# steps to reproduce
1. create a tree of pages
```
A
+-B
   +-C
D
```
3. publish c.  Observe in publish dialog a, b, c is calculated (because they are new)
4. cut a 
5. paste A under D (path is new but we don't get + new indicator)
6. publish C, note that a and b are not calculated
7. Note that publisher pushes these items

# expected
State and UI match publishing behavior.  A, B, C are "new" because they are at a new path

**Comment by dejan-brkic** [comment]
Fixed with resolution of ticket
https://github.com/craftercms/craftercms/issues/1013

**Comment by russdanner** [comment]
verified all the way through publish
