### ISSUE TITLE
[studio-ui] UI loses track of item in preview after cut paste

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1014]
UI loses track of item in preview after cut paste in url, subsequent actions like edit fail

# Steps to reproduce
1. preview a page
2. in the sidebar, cut the page you are looking at in the preview
3. paste it under another page (note path parameter in url does not change)
4. click edit in toolbar, note dialog fails.

# Expected
Workflow toolbar should continue to work

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/474

**Comment by russdanner** [comment]
Where is the merge?

**Comment by russdanner** [comment]
Reviewed
