### ISSUE TITLE
[studio-ui] Context nav says "Processing" but icon displayed is "In Workflow"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1015]
1. Login as an author, then edit any article and then send a request for publish.
2. Login as an admin or publisher or any role with the rights to publish, click on the article requesting publish, then click on **Approve & Publish** in the context nav, then click on the **Submit** button.

<img width="827" alt="screen shot 2017-06-22 at 4 01 47 pm" src="https://user-images.githubusercontent.com/25483966/27453703-5b0e3a20-5765-11e7-82bf-8b087ad5d73f.png">

3. After approving an article for publish, notice the message on the context nav says **Processing** but the icon displayed next to it is the "In Workflow" icon.

<img width="835" alt="screen shot 2017-06-22 at 4 02 09 pm" src="https://user-images.githubusercontent.com/25483966/27453832-c03a8ade-5765-11e7-9e67-00cc127a53bc.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/478

**Comment by alhambrav** [comment]
Verified fixed.
