### ISSUE TITLE
[studio] on publish, notification error values are unexpanded

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1016]
Log:
```[notification.NotificationServiceImpl] | Unable to get notification message from notification configuration for site: java.lang.NullPointerException type: {1} key: {2}, locale {3}.```

# steps to reproduce
1. on clean install, email not set up, editorial blueprint
2. edit a page and publish it
3. note error in logs "[notification.NotificationServiceImpl] | Unable to get notification message from notification configuration for site: java.lang.NullPointerException type: {1} key: {2}, locale {3}."

**Comment by sumerjabri** [comment]
This is no longer reproducible. We redid most of the notification system config and log.
