### ISSUE TITLE
[studio-ui] delete dialog formatting is off when items are nested

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1017]
<img width="1081" alt="screen shot 2017-06-22 at 5 00 05 pm" src="https://user-images.githubusercontent.com/169432/27455913-f8a8b984-576c-11e7-97c5-5174e22f1abe.png">

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/479

**Comment by russdanner** [comment]
Close this an open another ticket?
