### ISSUE TITLE
[studio-ui] certain dialog boxes break preview tools labels

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1019]
<img width="1398" alt="screen shot 2017-06-23 at 10 42 40 am" src="https://user-images.githubusercontent.com/169432/27487290-4fe4e652-5801-11e7-8c8f-3e7741552a42.png">

# steps to reproduce
1. open a page in preview
2. open review tools, note the labels look fine
3. refresh, note the labels look fine
4. click on any context nav operations for the page (approve and publish, schedule, delete, history) Note that the labels in preview tools get reverted to the keys for the string.

**Comment by vestrada** [comment]
studio-ui -> master -> https://github.com/craftercms/studio2-ui/pull/477

**Comment by russdanner** [comment]
reviewed
