### ISSUE TITLE
[studio] workflow cancellation show incorrect dependencies

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1020]
When you create a site from a blueprint, everything gets published.  

If from there you edit a page and schedule it for a publish in the future, only the xml should be in workflow (everything else is live)

Looking at the dashboard, it everything looks correct.  Only the page is listed (note dashboard says to show ALL which means you would see .ftl files if they were going to be pushed.)
<img width="883" alt="screen shot 2017-06-23 at 10 54 39 am" src="https://user-images.githubusercontent.com/169432/27487693-6b1a7cb0-5802-11e7-8cac-bb2e5a9dcd5f.png">

But if you go to edit the home page again, it says there are a million things in workflow that need to be canceled.  

<img width="1019" alt="screen shot 2017-06-23 at 10 38 31 am" src="https://user-images.githubusercontent.com/169432/27487505-eb007f52-5801-11e7-8af0-ee56b60d865e.png">

# expected

Only the content that is going to be "knocked out" of workflow by the action should be listed in the dialog.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/763

**Comment by russdanner** [comment]
reviewed
