### ISSUE TITLE
[studio-ui] Context nav items displayed incorrect when creating a new article

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1021]
The items displayed in the context nav is incorrect when creating a new article.  You need to reload/refresh the page to see the correct context nav items

1. In the website_editorial bp,  click on one of the live articles.  In the image below, I clicked on the article "Top Books For Young Women"

<img width="996" alt="screen shot 2017-06-23 at 11 34 02 am" src="https://user-images.githubusercontent.com/25483966/27489321-1e69f7b4-5808-11e7-85e0-851c0085aed8.png">

2. In the Sidebar, right click on one of the article folder and select **Create New Content**, then select **Page - Article**.  Fill out the required fields then select **Save & Close**.  In the image below, I right-clicked on the folder **1** under the folder **2017**

<img width="992" alt="screen shot 2017-06-23 at 11 36 10 am" src="https://user-images.githubusercontent.com/25483966/27489450-91786baa-5808-11e7-9c0a-a6efab45817e.png">

Notice the context nav after saving and closing the new article form.  The icon displayed is live, and so is the text next to the icon...  It looks like it is still displaying the context nav items for the live page that we were viewing in the first step instead of updating it for the new article we just created that we are now viewing, which, in the image below is the article **test 6**

<img width="990" alt="screen shot 2017-06-23 at 11 44 00 am" src="https://user-images.githubusercontent.com/25483966/27489740-a83f73d2-5809-11e7-9100-75e7063183e5.png">

To see the correct items in the context nav, just reload/refresh the page.

*Note that the same behavior happens if you edit an article. ( View a live page by clicking on one of the live pages from the Sidebar, then right click on an article in the **Sidebar** and select **Edit**.  Save & Close your changes, notice the context nav items listed at the top of the article you just edited.

**Comment by jvega-crafter** [comment]
Tested with @alhambrav and is not reproducible anymore

**Comment by alhambrav** [comment]
Verified.
