### ISSUE TITLE
[studio-ui] put notice of timeout and logo on timeout login dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1024]
Timeout login screen should say "You have been signed out due to inactivity."

Login dialog should display same logo as login screen
<img width="788" alt="screen shot 2017-06-23 at 2 52 56 pm" src="https://user-images.githubusercontent.com/169432/27496406-caf7cb26-5823-11e7-994f-ea43f1f97ca4.png">

**Comment by sumerjabri** [comment]
@russdanner please create a mock up to help us implement.

**Comment by russdanner** [comment]
<img width="387" alt="27496406-caf7cb26-5823-11e7-994f-ea43f1f97ca4" src="https://user-images.githubusercontent.com/169432/27706789-e8ceb3fa-5ce0-11e7-8dd5-1167e29be564.png">

**Comment by russdanner** [comment]
<img width="387" alt="27496406-caf7cb26-5823-11e7-994f-ea43f1f97ca4" src="https://user-images.githubusercontent.com/169432/27707036-e5550106-5ce1-11e7-8ace-c07a103129cf.png">

**Comment by russdanner** [comment]
As with the login screen:

The dialog should use the following url to get the image:
/studio/api/1/services/api/1/server/get-ui-resource-override.json?resource=logo.jpg

and default to the crafter logo if a custom logo is not available

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/484

**Comment by russdanner** [comment]
verified
