### ISSUE TITLE
[studio-ui] Please add a delay before showing the full name of the toolbar in top nav

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1027]
Per our conversation: please add a 1 second delay (configurable) before the text is shown to the right-side top nav items (the icons without text where the text shows when you mouse over). The idea is to make the UI easier to use because over time and use, the text is pointless to those who know it, but it's important to those who don't.

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/472
