### ISSUE TITLE
[studio-ui] Targeting UI needs default button actions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1028]
Please update the targeting UI to `apply` on `Enter` key and `Cancel` on `Escape` key.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/503

**Comment by sumerjabri** [comment]
Choose `guy` and hit enter or escape.
Click outside the drop down, and try enter or escape.

Doesn't work for me.

**Comment by jvega-crafter** [comment]
Fixed - https://github.com/craftercms/studio2-ui/pull/515
