### ISSUE TITLE
[studio-ui] When closing the bulk upload static-asset folder does not refresh 

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1029]
*Note* https://github.com/craftercms/studio/pull/761 must be merge.

1. Create a site using the Editorial BP
2. Right-click on static-assets/images
3. Select bulk upload and choose a single or multiple images from your desktop
4. Close the bulk upload dialog
5. The static-assets folder does not refresh and the user must manually refresh to see the new assets. 

When uploading a single asset using the `upload` option the refresh does happen after the upload is done, same behavior should be expected when closing the bulk upload dialog.

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/470
