### ISSUE TITLE
[studio] Message from NotificationServiceImpl has variables not populated in log

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1031]
The message in the catalina logs looked like this (I don't have the actual log anymore):
```
Unable to get notification message from notification configuration for site: {0} type: {1}...
```

If you look at the NotificationServiceImpl.java file, go to line number 150, 151, notice that  {1}, {2} and {3} is not populated ({0} gets populated by `ex`, which was displaying Null pointer exception)

**Comment by cortiz** [comment]
Solve in craftercms/studio PR #768

**Comment by alhambrav** [comment]
Verified fixed.
