### ISSUE TITLE
[studio-ui] Remove property validation for personalization/targeting

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1035]
Please remove property validation from the targeting system.

Please test by:
* Create a site using Editorial
* Enable debugging in browser (inspect) and select Network
* Click targeting
* Set the name to something new
* See the call to the backend has `username` instead of name

We need the properties to go to the backend unmodified

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/467
