### ISSUE TITLE
[studio-ui] Approve for publish dialog incorrect items displayed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1037]
When batch approving content for publishing with mixed items (some scheduled to go live at a later time and some scheduled to go live now), the dialog seems incorrect when it first launches.

1.  In the website_editorial bp, edit a few of the articles as a content author. Pick one article and request publish at a later time (schedule), for the rest of the edited articles, request publish now.

2. Login as an approver (admin or reviewer, user with publishing rights), from the dashboard, put a checkmark on the articles requesting publish, then click on **Approve & Publish** from the context nav.  Notice the dialog that launches.

![screen shot 2017-06-27 at 4 21 40 pm](https://user-images.githubusercontent.com/25483966/27608804-cc56d404-5b56-11e7-85fb-335fbd5f9215.png)

In order to get the selection for the date and time, you have to click on **Items should go live now**, then click again on **Items go live on a specific date & time**

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/469

**Comment by alhambrav** [comment]
Verified fixed.
