### ISSUE TITLE
[studio-ui] Please change the email me message in the "Request Publish" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1042]
Our existing **Request Publish** dialog displays a checkbox with the caption **Email me when items go live**, but the current functionality of our system is that it sends a notification email when an item has been approved, not when the item goes live.  It would be nice to have the text next to the checkbox match what out system does now, **Email when when items are approved for publish**, or something to that effect. 

<img width="741" alt="screen shot 2017-06-28 at 10 46 15 am" src="https://user-images.githubusercontent.com/25483966/27643545-5ef411e4-5bef-11e7-94f8-240d8169ba20.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/483

**Comment by alhambrav** [comment]
Verified fixed.
