### ISSUE TITLE
[studio-ui] Add clear profile button to targeting

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1043]
Please add a button to the targeting dialog to clear the profile completely.

See screenshot for example:
![screenshot from 2017-06-28 13-47-04](https://user-images.githubusercontent.com/3931908/27652061-582743fe-5c08-11e7-8722-704a1322bb27.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/492
