### ISSUE TITLE
[studio] Make sure Studio accepts a 202 when calling deploy for preview

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1045]
The Deployer call to deploy, `/api/1/target/deploy`, now returns a 202 on success, which means that the deployment request was accepted but processing hasn't finished (basically an asynchronous operation). Make sure Studio accepts this new HTTP response status.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/769

**Comment by avasquez614** [comment]
Tested and verified.
