### ISSUE TITLE
[studio-ui] Very long site name goes outside of the confirmation dialog when deleting a site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1047]
1. Create a site with a very long name (Do a name that is the max 50 characters for site id)
2. Delete/remove the site you just created.  Notice how the site name goes outside of the confirmation dialog

![screen shot 2017-06-29 at 2 28 13 pm](https://user-images.githubusercontent.com/25483966/27704125-85d20e4a-5cd7-11e7-9561-7fa5f799d787.png)

**Comment by vestrada** [comment]
studio-ui -> master -> https://github.com/craftercms/studio2-ui/pull/477

**Comment by alhambrav** [comment]
Verified fixed.
