### ISSUE TITLE
CRAFTERCMS-2036: Submitted schedule item showing different time than selected

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#105]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Crafter installation without alfresco. Timezone configuration is the same for OS/browser, and crafter installation in site-configuration.xml (in my case CST).

- When doing an scheduled request publish I select a time (ex. 3:00 pm), submit the publish request.
-After submitting it shows the activity on the dashboard, and the publish date shows a wrong value (2:00pm, 1 hour before selected), value got directly from service response (/studio/api/1/services/api/1/workflow/get-go-live-items.json):
----------
Original JIRA Comments:
* Dates should be stored in the DB in ZULU time
* Dates sent to client should be in the PROJECT configured time (with timezone indicated)
* Dates in bound from the server should be allowed to come in any timezone as long as timezone is indicated.  If it not we should assume the project time zone.  There is no "right" answer for this.  

* Server time should have no bearing on the use cases
* Currently user browser preference should have no bearing on use cases
----------
Russ, please try out this use case. I still don't see anything wrong. There is no "ghost" hours added when system configured properly. 
----------
Need to test this very robustly
----------
Current Results:

1.Put my computer with timezone EST vrs Crafter Server timezone EST5EDT > Results:  The publish date is correct.
2.Put my computer with timezone CST vrs Crafter Server timezone CST > Results:  I selected the time 9:45 pm to publish and the app shows the time 8:45 pm, an hour less.
3.Put my computer with timezone CEST vrs Crafter Server timezone CEST > Results: I selected the time 11:30 pm to publish and the app shows the time 1:30 am, two hours later.
4.Put my computer with timezone CST vrs Crafter Server timezone EST5EDT > Results: I selected the time 7:00 pm to publish and the app shows the time 5:00 pm, an hour less.
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2036
----------

**Comment by jvega-crafter** [comment]
Tested using derby and mysql, same results
Used Postman to call the services directly

POST - http://localhost:8080/studio/api/1/services/api/1/workflow/submit-to-go-live.json?site=dependencies2&user=author ,  (body = {"sendEmail":true,"schedule":"custom","submissionComment":"","items":["/site/website/about-us/index.xml"],"scheduledDate":"2016-12-2T20:30:00-06:00"} )

Response: "status": 200,

GET - http://localhost:8080/studio/api/1/services/api/1/workflow/get-go-live-items.json?site=dependencies2&sort=eventDate&ascending=false&nocache=Thu%20Dec%2001%202016%2013:14:55%20GMT-0600%20(CST)

Response: ...{ "internalName": "About us", "scheduledDate": "2016-12-02T19:30:00-06:00", ...} ...

Same timezone as sent one (-06:00) but different time

**Comment by jvega-crafter** [comment]
Debugged java code on WorkflowServiceImpl.java - line 160 (submitForApproval)

on line 177 requestObject.scheduledDate = 2016-12-2T20:30:00-06:00
after getScheduledDate call, scheduledDate value = Fri Dec 02 19:30:00 CST 2016

maybe a problem with the SimpleDateFormat timezone?

**Comment by gortizcrafter** [comment]
The tests are completed with heavy escenaries and the conversion for each time zone used is properly.
