### ISSUE TITLE
[studio-ui] Allow Studio JS plugins to load from /config/studio relative to the site

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1051]
Please allow Studio JS plugins to load from any path specified so long as the path is rooted in `/config/studio/extension`.

Plugins to allow include:
* Form Controls
* Form Data Sources
* Sidebar Plugins
* Preview Tools Plugins
* Setting Plugins

Built-in plugins will be loaded mostly as they do today. External plugins will have full path and load off the site config.

We must add a new XML sub-element to modulehook to specify the path (and maybe to specify that it's external).

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1257

**Comment by vestrada** [comment]
Hi Vita :)

To use an external plugin for Controls and Datasources please see take a look to the following api documentation:
https://app.swaggerhub.com/apis/craftercms/studio/3.1.1.12#/plugin/getPluginFile

First the user has to create the folder structure on studio. For example:
![image](https://user-images.githubusercontent.com/11640613/62665755-9e361980-b93d-11e9-9410-b965a0118a0f.png)

In this case the path would be:  ⁨config⁩ ▸ ⁨studio⁩ ▸ ⁨plugins⁩ ▸ ⁨form⁩ ▸ ⁨datasource⁩ ▸ child-content2.js

Then user have to include the new Control or Datasource into site configuration file. Please see the following example:

![image](https://user-images.githubusercontent.com/11640613/62665877-20bed900-b93e-11e9-930a-b427e80abc09.png)

As you can see on the image the difference between these controls and datasources, and the normal controls and datasources is that they come from a new path. So it is important to include `<plugin>` property to the specific element.

Example: 
`<plugin>
   <type>form</type>
   <name>control</name>
   <filename>input2.js</filename>
</plugin>`

This is related with the folder structure that the user already created. So Type is the first level, name second level and filename the name of the file.

Thanks

**Comment by sumerjabri** [comment]
@alhambrav for docs, we can use a control called `mycontrol` or similar to not confuse the reader. Ping me if not clear.

**Comment by vestrada** [comment]
Hi Vita, I made some changes:

APi is the same:
https://app.swaggerhub.com/apis/craftercms/studio/3.1.1.12#/plugin/getPluginFile

I'm going t use new folder and files name for this example:
![image](https://user-images.githubusercontent.com/11640613/62895117-6ba86a00-bd0b-11e9-8cb9-39330cfa081d.png)

In this case the path would be: ⁨config⁩ ▸ ⁨studio⁩ ▸ ⁨plugins⁩ ▸ ⁨control⁩ ▸ ⁨input2⁩ ▸ main.js

Now for site configuration xml see the following example:

![image](https://user-images.githubusercontent.com/11640613/62895422-0a34cb00-bd0c-11e9-95cc-7f6edb49823b.png)

As you can see on the image the difference between these controls and datasources, and the normal controls and datasources is that they come from a new path. So it is important to include `<plugin>` property to the specific element.

Example:
`<plugin> <type>control</type> <name>input2</name> <filename>main.js</filename> </plugin>`

New datasources and plugins needs to use require `CStudioAuthoring.Module`

`CStudioAuthoring.Module.moduleLoaded("input2", CStudioForms.Controls.Input2);`

Prefix for `CStudioAuthoring.Module.moduleLoaded` must be the name of the control as it is in above example.

![image](https://user-images.githubusercontent.com/11640613/62895797-df974200-bd0c-11e9-843e-1ede74b5267d.png)

Thanks, Vero

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/812

**Comment by alhambrav** [comment]
Verified feature is working and added docs
