### ISSUE TITLE
[studio-ui] Change "Cancel" to "OK" on button in notification dialog that component is already in drop zone

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1054]
1. Click on the wrench at the top right to view the **Preview Tools** panel
2. Click on **Page Components**
3. Click on **Browse Features**
4. Select a feature that is already on the screen, say **Two** or **Three**
5. Notice that the notification dialog has a **Cancel** button, do you think it's more appropriate to name the button **OK**? (Maybe change the message too to say: "The component cannot be added, the component is already in **the** drop zone).

![screen shot 2017-06-30 at 11 31 48 am](https://user-images.githubusercontent.com/25483966/27744223-af567d18-5d8c-11e7-9540-ce8c0531b9a2.png)

**Comment by sumerjabri** [comment]
Please change the text to: "The component cannot be added, it is already in the drop-zone." and change the button to OK.

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/491

**Comment by alhambrav** [comment]
Verified fixed.
