### ISSUE TITLE
[studio-ui] Configuration editor doesn't use available space

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1056]
Please have configuration editor use the space available in the browser window to make editing easier.

See screenshot here:
![configuration-editor](https://user-images.githubusercontent.com/3931908/27753638-6ce71604-5db4-11e7-9bf6-c20b6ef8a85d.png)

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/486
