### ISSUE TITLE
[Studio] Delete User API have a empty response.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#1058]
Steps:
1. Create a user with name jane.doe
2. Delete the user created:
 URL:  http://localhost:8080/studio/api/1/services/api/1/user/delete.json
with the Json:
{
  "username" : "jane.doe"
}

Current Behavior: 
The reponse is empty.

Expected Behavior: 
I need that response is : "message": "OK", because the test suite about  APIs is failed when the response is empty in this API (delete user).

NOTE: is urgent for the automation for APIs

<img width="1280" alt="json" src="https://user-images.githubusercontent.com/19412548/27812258-bc55aa34-602a-11e7-8534-01663a0abbd2.png">

**Comment by sumerjabri** [comment]
Delete returns 204 and empty body by design. You should look for 204.
