### ISSUE TITLE
[studio] Editorial BP is missing the drag & drop configuration

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1061]
The xml file `website_editorial/config/studio/preview-tools/` is missing the components configuration:

```
<config>
    <category>
        <label>General</label>
    </category>
</config>
```

That causes an error when the Components panel is opened:

![screen shot 2017-07-05 at 10 16 30 am](https://user-images.githubusercontent.com/1236955/27875818-d6720960-6171-11e7-98b3-b3de2e0d76ab.png)

**Comment by sumerjabri** [comment]
Please test and validate.

**Comment by jdrossl** [comment]
Verified
