### ISSUE TITLE
[studio-ui] Very long user name goes outside of the confirmation and notification dialogs

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1062]
1. Create a new user with a very long user name.  Notice that in the notification dialog that the user has been created that the name goes out of the dialog.

![long-user-name-created-notification](https://user-images.githubusercontent.com/25483966/27877140-8fab728a-6187-11e7-989a-da85aefc403f.png)

2. Delete the user with the very long user name.  Notice that the user name goes outside of the  confirmation dialog.

![long-user-name-delete-confirmation](https://user-images.githubusercontent.com/25483966/27877228-d6d93890-6187-11e7-87d7-382b839588b8.png)

3. Notice the same thing for the notification dialog that the user with a very long user name has been deleted

![long-user-name-deleted-notification](https://user-images.githubusercontent.com/25483966/27877178-adc3ffb2-6187-11e7-9ba1-7cc238341715.png)

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/489

Icons for notification dialogs were wrong. I already fixed them.

I created new ticket for Group dialog issues :
https://github.com/craftercms/craftercms/issues/1081

**Comment by alhambrav** [comment]
Verified fixed.
