### ISSUE TITLE
[studio-ui] Empty feature is added to the drag and drop zone/Features section after cancelling add new feature

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1063]
1. Click the wrench at the top right of Studio to enable the Preview Tools Panel
2. Click on **Page Components**
3. Click and drag **Feature** under **General** into the drag and drop zone, a **New Component Feature** form will launch for you to fill out
4. Cancel the form.  

![screen shot 2017-07-05 at 2 52 04 pm](https://user-images.githubusercontent.com/25483966/27880047-9f822b68-6191-11e7-99ea-543ee00d9b0e.png)

Notice that an empty **Feature** is still placed in the drag and drop zone after cancelling the creation of a new feature.

![screen shot 2017-07-05 at 2 43 23 pm](https://user-images.githubusercontent.com/25483966/27879912-31222e20-6191-11e7-98bd-75c7e10891c3.png)

The empty **Feature** also appears in the **Features** section of the page after clicking the **done**  button in the Components panel.

![screen shot 2017-07-05 at 2 43 39 pm](https://user-images.githubusercontent.com/25483966/27879861-04586332-6191-11e7-80bc-a13f846450e1.png)

It would be nice to not have an empty feature added when cancelling creation of a new feature.

**Comment by vestrada** [comment]
The call to refresh the preview after close the form was wrong. It is fixed.

**Comment by vestrada** [comment]
The call to refresh the preview after close the form was wrong. It is fixed.

master-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/487

**Comment by alhambrav** [comment]
Verified fixed.
