### ISSUE TITLE
[studio-ui] make context nav icon text a tool tip

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1066]
# Reason to change
Minor UX issue is that the icon moves away from your mouse when you hover over it
Major UX issue is that moving between icons is very difficult and the user often misses
https://www.useloom.com/share/ec316f1b71cd4513af174d4e8cbfe1ad

# Suggested correction:
Make the text a tool tip or expand it below the icons in the toolbar

**Comment by sumerjabri** [comment]
try the latest build first

**Comment by russdanner** [comment]
Will do.  This build is from yesterday afternoon.

**Comment by sumerjabri** [comment]
We added a delay, see how that feels

**Comment by russdanner** [comment]
The delay is before the text appears but it does not help the issue when the text is there and you move to the left.  

The second you move off the current icon, the text collapses, the icons to the left pull in and place where the user move the mouse to (the icon to the left) is no longer in the same positon.
