### ISSUE TITLE
[studio-ui] minor targeting ux tweaks

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1068]
# Ux Issues
- Hint makes the ux a little jumpy.  
- No indication to user that they should scroll for additional properties (testing browser is chrome on osx)
https://www.useloom.com/share/e8a3485de3ff4c4d86888d9813a5757a

# Suggested corrections
- Consider moving hint to the right or making it accessible through a click. 
- Add an indicator that you can scroll that turns to a back to top when you hit the bottom of the scroll.

**Comment by sumerjabri** [comment]
It's no longer jumpy.
