### ISSUE TITLE
[studio-ui] Edit on Context Nav not clickable after editing a page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1070]
1. Using a new website_editorial bp, preview one of the articles.
2. Edit the article then click on **Save & Close**
3. Go to the Context Nav and click on **Edit** (Let's you edit the page again) then make changes then click on **Save & Close**
4. Go to the Context Nav again and try to click on **Edit** again.  Notice that **Edit** is not clickable anymore

![screen shot 2017-07-06 at 12 20 40 pm](https://user-images.githubusercontent.com/25483966/27921379-9fe92ae8-6245-11e7-9ad4-1455931b9a3c.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/488

**Comment by alhambrav** [comment]
Verified fixed.
