### ISSUE TITLE
[studio] copy action on pages over depth of 3 does not show children in dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1072]
# reproducing the issue
https://www.useloom.com/share/c5ba62687927445e804043c2fc6ce9d8

# expectation
- service response should include child trees, 
- dialog should show them  
- User should be able to deselect items or levels they do not want to copy

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/776

**Comment by russdanner** [comment]
verified
