### ISSUE TITLE
[studio-ui] Time field in Headless_blog is empty when you click on the up/down arrows

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1077]
1. Create a site using the headless_blog bp
2. Edit one of the Item:Posts, Click on the `Expire Date`, select a date, then click on the time, notice how the time field is empty after clicking :

![screen shot 2017-07-10 at 10 44 56 am](https://user-images.githubusercontent.com/25483966/28023883-29f099dc-655d-11e7-92bb-30b9604c0631.png)

3. You can enter a time manually, notice how it works when you click on the up/down arrows, only the seconds field changes (I don't know though if that is the expected behavior of the time field)

![screen shot 2017-07-10 at 10 50 59 am](https://user-images.githubusercontent.com/25483966/28024080-b26e185c-655d-11e7-81d5-4b71526b59a8.png)

Here's the time field after clicking the up/down arrow next to it:

![screen shot 2017-07-10 at 10 52 03 am](https://user-images.githubusercontent.com/25483966/28024121-d1cb3f18-655d-11e7-951e-4bd3eafe8829.png)

It would be nice if the time field is populated with say 12:00:00 am when the user clicks on the up/down arrows.

Or, another way is, when the user clicks on the date/time fields, the time field gets populated with the current time rounded to 15 minutes, similar to how when you request for publish, when you click on go live on a schedule, it display the current date selected and the current time rounded up to the next 15 minutes, or something like that instead of just being empty.

**Comment by jdrossl** [comment]
@sumerjabri there are two possible solutions for this, let me know which one you think is more appropriate:
- Set a default value for the Expire Date (can be something like 1 or 2 years from the current date)
- Change the date-time control so that selecting a date also sets the time to 12:00 as suggested in the description

**Comment by sumerjabri** [comment]
@jdrossl Let's set a default date of 1 year.

**Comment by alhambrav** [comment]
Verified fixed.
