### ISSUE TITLE
[studio-ui] text wrapping on the icon legend is crowded and could wrap later

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1083]
<img width="1389" alt="screen shot 2017-07-10 at 2 53 59 pm" src="https://user-images.githubusercontent.com/169432/28034741-15d1fd60-6580-11e7-90c2-2ba27d8ac71f.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/510
