### ISSUE TITLE
[docs] Update documentation for command clear to be clean in gradle build system

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1084]
Please update the docs to indicate the new name for the command `clean` instead of `clear`.

Docs: http://docs.craftercms.org/en/3.0/developers/projects/craftercms/

PR: https://github.com/craftercms/craftercms/pull/1078

Please make the update in `master` and we can then merge back to all affected versions.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/296
