### ISSUE TITLE
[studio] Delete is not working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1085]
Using a site created using the website_editorial bp, delete a page.  I will be deleting  **coffee-is-good-for-your-health**, below, you see it in the sandbox repo:
```
➜  anotherawesomesite git:(master) ls sandbox/site/website/articles/2016/6
coffee-is-good-for-your-health
```

In my example, I deleted the page **coffee-is-good-for-your-health**,  look inside the sandbox, and the page is not there as expected
```
➜  anotherawesomesite git:(master) ls sandbox/site/website/articles/2016/6
ls: sandbox/site/website/articles/2016/6: No such file or directory
```
I look inside the published repo, the article is still there (not deleted)
```
➜  anotherawesomesite git:(master) ls published/site/website/articles/2016/6
coffee-is-good-for-your-health
``` 

The same thing is happening when I delete a template, it gets deleted in the sandbox, but not in the published repo.  Here's the sandbox content for the error templates:
```
➜  anotherawesomesite git:(master) ls sandbox/templates/web/errors/
404.ftl 500.ftl
```
Delete the template `500.ftl`
![screen shot 2017-07-10 at 3 27 22 pm](https://user-images.githubusercontent.com/25483966/28035919-4d8787ee-6584-11e7-891f-f2154651de1b.png)

We'll look in the sandbox again:
```
➜  anotherawesomesite git:(master) ls sandbox/templates/web/errors/
404.ftl
```
Then look in the published, the `500.ftl` file is not deleted:
```
➜  anotherawesomesite git:(master) ls published/templates/web/errors/
404.ftl 500.ftl
```

According to Alfonso, the expected behavior is, when something is deleted from the studio authoring environment (`sandbox`), it should also be deleted from the `published`.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/779

**Comment by alhambrav** [comment]
Verified fixed.
