### ISSUE TITLE
[studio] Scripts and Template items returning isComponent property as true instead of isAsset

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#1086]
Script files (.groovy) and template files (.ftl) have the properties isComponent=true and isAsset=false, those items should be labeled as assets in order to render its proper icons.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/783

**Comment by jvega-crafter** [comment]
verified fixed
