### ISSUE TITLE
[studio] delete dialog does not show the full tree of items to be deleted

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1087]
https://www.useloom.com/share/a20286241c334a6cb9ff8aa398a11a21

# steps to reproduce
1. Create a deep tree structure in pages (4-5 levels)
2. Delete the top level object
3. Note that lower levels are not shown (see video)

# expectation
All levels should be shown in dialog so that user knows the impact of the action

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/780

**Comment by russdanner** [comment]
confirmed
