### ISSUE TITLE
[studio-ui] cut operation on components and folders in sidebar gives user no cut indication

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1089]
# reproducing the issue
https://www.useloom.com/share/e4a3ddd8711e4f75b3462f8477645174

Note that page shows a faded text to indicate the item has been cut.  For components and folders, it does not.  

# correction
Show a uniform indication that an item has been cut

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/492

**Comment by russdanner** [comment]
Verified
