### ISSUE TITLE
[studio-ui] assets folder type on side bar gives paste option when it should not

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1090]
# reproducing the issue
https://www.useloom.com/share/9f4bab2a7bc046e0b76976050b314633

Today copy/cut paste is not supported via the UI for asset folder plugin.  (future enhancement)
Paste should not be an option at any time until cut and copy ops are added to the UI

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/493

**Comment by russdanner** [comment]
Verified
