### ISSUE TITLE
[studio-ui] history dialog actions are not visible when browser is not full screen

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1092]
<img width="1047" alt="screen shot 2017-07-11 at 10 56 35 am" src="https://user-images.githubusercontent.com/169432/28074862-b6a4db98-6627-11e7-88c4-99762c36c7f7.png">

**Comment by russdanner** [comment]
Chrome, lasted build, cache cleared :)

**Comment by russdanner** [comment]
Bug shows up when you "squeeze" browser
https://www.useloom.com/share/27e547fe083342a99097f5b894cc6593

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/509

**Comment by russdanner** [comment]
Verified
