### ISSUE TITLE
[studio] Create a DB script to upgrade the DB from 2.5.x to 3.0

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1094]
Create a script to upgrade DB from 2.5.x to 3.0. This is necessary for the whole 2.5.x to 3.0 upgrade process.

**Comment by dejan-brkic** [comment]
@sumerjabri We need to discuss this issue

**Comment by avasquez614** [comment]
Actually now that I'm working on the upgrade steps this is probably not needed, the site is being imported as content and then a sync from repo is done. So you can close it if you want to.
