### ISSUE TITLE
[studio-ui] Inconsistent item icons across dashboards, sidebar and toolbar

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1095]
Steps to reproduce:

0. Create new site with Website Editorial blueprint

1. Create new content (category-landing)
1.1 Populate all required fields
1.2 Place in navigation set to "No"
1.3 Save

2. Switch to dashboards view
3. Select checkbox for newly created item in "My recent activity" dashboard 

ISSUE:
Sidebar icon is showing "Floating page" icon -> OK
Dashboard(s) icon is showing "Navigation page" icon -> WRONG (placeInNav = false)
Toolbar icon is showing "Navigation page" icon -> WRONG (placeInNav = false)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/506

**Comment by dejan-brkic** [comment]
Verified
