### ISSUE TITLE
[studio-ui] Context nav menu available even when there's no item selected from the Dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1097]
It seems that it happens for templates, scripts and static assets, except the pages.

1. In the website_editorial bp, edit a template. In the example I'm going to show, I am editing the file 500.ftl
2. Open the dashboard, put a check mark (select) the 500.ftl file from the **My Recent Activity** widget. Notice that a context nav menu will appear at the top.

![screen shot 2017-07-12 at 3 26 03 pm](https://user-images.githubusercontent.com/25483966/28136180-c87848a6-6716-11e7-8968-4d1d805d7e6a.png)

3. Click on **Edit** in the context nav, then edit and save the template file by clicking on **Update**.  Notice that the check mark on the 500.ftl file is gone in the dashboard, but the context nav menu is still there

![screen shot 2017-07-12 at 3 29 59 pm](https://user-images.githubusercontent.com/25483966/28136322-4beb2032-6717-11e7-9ad0-ec49ba8635ef.png)

Also, (this may be caused by the previous behavior I mentioned above), immediately after the steps above, if you put a check mark on the article "Coffee is Good for Your Health", notice that **Edit** is not available in the context nav menu

![screen shot 2017-07-12 at 3 33 36 pm](https://user-images.githubusercontent.com/25483966/28136439-b8105e44-6717-11e7-82fb-6c701f968808.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/500

**Comment by alhambrav** [comment]
Verified fixed.
