### ISSUE TITLE
[site] Not found http://docs.craftercms.org/en/stable/system-administrators/dev-environment/install-from-zip.html

### ISSUE THREAD

**Issue by uber-rivet** [craftercms/craftercms#1099]
There is a broken link at page http://craftercms.org/downloads/crafter-osx-latest, referenced by *Simple Install Instructions* pointed at http://docs.craftercms.org/en/stable/system-administrators/dev-environment/install-from-zip.html

**Comment by sumerjabri** [comment]
@russdanner it seems the links at craftercms.org are wrong given the new URL structure for docs.

**Comment by sumerjabri** [comment]
@russdanner use this URL on the site (currently the site is broken)
http://docs.craftercms.org/en/latest/getting-started/index.html

**Comment by russdanner** [comment]
Ticket not relevant. Closing
