### ISSUE TITLE
CRAFTERCMS-1360: translate user dashboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#11]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: add resource bundle support:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1360
----------

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/179
