### ISSUE TITLE
[studio-ui] Clicking on "Sites", "Users" and "Help->About" when previewing a site logs you out

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1101]
1. Create a new site using any of the 4 bp.  I am going to use the website_editorial for my screenshots.

2. Click on any of these from the top right: **Sites**, **Users**, **Help**->**About**.  Notice that it will log you out of Studio.

![screen shot 2017-07-13 at 10 55 47 am](https://user-images.githubusercontent.com/25483966/28172692-412ff412-67ba-11e7-84b6-90e1266f1c5b.png)

This only happens when you're previewing a site.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/497

**Comment by alhambrav** [comment]
Verified fixed
