### ISSUE TITLE
[studio] On site delete, call Engine's API to destroy site context.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1103]
When a site is deleted in Studio, call preview Engine's `/api/1/site/context/destroy.json?crafterSite=siteName` so that the context is immediately destroyed and the site resources are cleaned up in Engine.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/786

**Comment by avasquez614** [comment]
Verified
