### ISSUE TITLE
[studio-ui] Freemarker error message shown on login screen and sites screen

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1105]
Screenshots attached
![screen1](https://user-images.githubusercontent.com/4053827/28187115-d59b4f58-681d-11e7-8b9b-79020dfeae2c.png)
![screen2](https://user-images.githubusercontent.com/4053827/28187117-d8dec4e2-681d-11e7-8195-dc417f15a71e.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/497

**Comment by dejan-brkic** [comment]
Confirmed fix
