### ISSUE TITLE
[studio] Oops message displayed when editing a component in the headless bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1108]
This applies to headless blueprints.  I will be using the headless_blog for the screenshots below.

1. Create a new site using the headless_blog bp.
2. Navigate to one of the **Items** in the tree.  I navigated to **items**->**posts**, then right clicked on **Buying a camera** and selected **Edit**

![screen shot 2017-07-14 at 10 11 58 am](https://user-images.githubusercontent.com/25483966/28215796-414e4390-687d-11e7-9278-57a6dd0ec122.png)

3. Edit the post then click on **Save & Close**, notice that the page being previewed has changed to an oops message:

![screen shot 2017-07-14 at 10 16 08 am](https://user-images.githubusercontent.com/25483966/28215869-7f3053ec-687d-11e7-99a8-c91f1abc8653.png)

Here's the error message from the Catalina log:
```
[ERROR] 2017-07-14 10:15:26,097 [http-nio-8080-exec-8] [configuration.ContentTypesConfigImpl] | No content type configuration document found at /config/studio/content-types/pages/config.xml
```

**Comment by sumerjabri** [comment]
@russdanner per our convo, please document your thoughts and assign back to me.

**Comment by russdanner** [comment]
I believe this behavior is the result of a recent update where the preview now refreshes to the current location of the descriptor you are editing.

That is the correct behavior when you are editing a page descriptor.

When you are editing anything else such as a component, a template, a script or really any other non-page asset, the preview should simply refresh it's current url.

**Comment by jvega-crafter** [comment]
As in https://github.com/craftercms/craftercms/issues/1121, the items "isComponent" property is false, I need it to be true (because is component) in order to check and avoid the refresh of the preview

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/506 - UI fix

**Comment by alhambrav** [comment]
Verified fixed.
