### ISSUE TITLE
[craftercms] Update all sub-system names

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1113]
Please update:
```
crafter-profile => profile
crafter-profile-admin-console => profile-admin
crafter-social => social
crafter-social-admin => social-admin
crafter-search => search
crafter-deployer => deployer
```

Please update all related configuration in authoring and delivery to make it all work.

**Comment by cortiz** [comment]
PR 
https://github.com/craftercms/deployer/pull/44
https://github.com/craftercms/engine/pull/160
https://github.com/craftercms/profile/pull/133
https://github.com/craftercms/search/pull/77
https://github.com/craftercms/social/pull/316
https://github.com/craftercms/craftercms/pull/1136
