### ISSUE TITLE
[studio] Publishing can fail silently

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1115]
Per our conversation:
Publishing fails silently with load/concurrent users (items marked as COMPLETED in CopyToEnvironment when they're not really done).

We discussed the plan to recover from commit_ids not found in jgit.

**Comment by dejan-brkic** [comment]
Added more logging when publishing. Added error if studio does not find commit id that needs to be published.
PR:
https://github.com/craftercms/studio/pull/788

**Comment by sumerjabri** [comment]
Breaks with delete: https://gist.github.com/sumerjabri/d6ff100f01a6a5f11368fde663ad51af

**Comment by dejan-brkic** [comment]
Fixed delete issue
PR:
https://github.com/craftercms/studio/pull/789

**Comment by dejan-brkic** [comment]
Fixed delete issue on renamed content
PR:
https://github.com/craftercms/studio/pull/791
