### ISSUE TITLE
[studio-ui] Compare versions does not work as expected

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1118]
1. Using website_editorial. make changes to an article.  In my example, I used the article Coffee is good for your health. Save and close.
2. Do another edit of the article then save and close.
3. Do another edit of the article then save and close.
4. Click on **History** in the context nav
5. Compare the first item to the third item by selecting them and then clicking on the **Compare** button at the bottom left of the screen

![screen shot 2017-07-18 at 12 36 46 pm](https://user-images.githubusercontent.com/25483966/28328871-e8269862-6bb5-11e7-8dcd-90dc7187cdf0.png)

Notice that the differences are not highlighted when you compare:

![screen shot 2017-07-18 at 12 38 19 pm](https://user-images.githubusercontent.com/25483966/28328913-01370576-6bb6-11e7-8d8e-b422a642360b.png)

5. Now compare the second item with the third item (again by selecting them and then clicking on the **Compare** button

![screen shot 2017-07-18 at 12 38 55 pm](https://user-images.githubusercontent.com/25483966/28328949-1ea25c5a-6bb6-11e7-91e0-5f2ac846861d.png)

Notice that this time, the differences are highlighted:

![screen shot 2017-07-18 at 12 39 51 pm](https://user-images.githubusercontent.com/25483966/28328976-36f18e84-6bb6-11e7-9283-94d13674247c.png)

Compare does not seem to work only when comparing the very first item with any other item.

**Comment by jvega-crafter** [comment]
studio PR - https://github.com/craftercms/studio/pull/797
studio-ui PR - https://github.com/craftercms/studio2-ui/pull/512

**Comment by alhambrav** [comment]
Verified fixed.
