### ISSUE TITLE
[studio] Headless bp components does not display icon in the nav tree

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1121]
Create a site using one of the headless bp, open the **Sidebar** and expand the nav tree, notice the components does not have icons displayed next to them:

Headless_store bp:
![screen shot 2017-07-18 at 2 45 25 pm](https://user-images.githubusercontent.com/25483966/28334099-0e659bd8-6bc8-11e7-8bdf-005b5675e79b.png)

Headless_blog bp:
![screen shot 2017-07-18 at 2 48 05 pm](https://user-images.githubusercontent.com/25483966/28334183-5c98e300-6bc8-11e7-97a7-8a1909bc0dd8.png)

**Comment by jvega-crafter** [comment]
@sumerjabri items "isComponent" property is returning false from service. It needs to be true in order to render it properly

**Comment by sumerjabri** [comment]
@dejan-brkic we can discuss when you're ready to tackle this ticket.

**Comment by dejan-brkic** [comment]
This is site configuration issue. Components need to match one of regex patterns in site-config.xml
Example config for headless Blog:
```
<pattern-group name="component">
                <pattern>/site/components/([^&lt;]+)\.xml</pattern>
                <pattern>/site/system/page-components/([^&lt;]+)\.xml</pattern>
                <pattern>/site/component-bindings/([^&lt;]+)\.xml</pattern>
                <pattern>/site/indexes/([^&lt;]+)\.xml</pattern>
                <pattern>/site/resources/([^&lt;]+)\.xml</pattern>
                <pattern>/site/items/([^&lt;]+)\.xml</pattern>
</pattern-group>
```
added `/site/items/([^&lt;]+)\.xml` and icon appears

**Comment by alhambrav** [comment]
Added pattern for items in headless bp.
PR https://github.com/craftercms/studio/pull/811

**Comment by alhambrav** [comment]
Verified.
