### ISSUE TITLE
[studio] Implement CMIS Clone API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1122]
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/clone.html

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/806

**Comment by sumerjabri** [comment]
@jvega-crafter please test and close if verified.

**Comment by jvega-crafter** [comment]
Verified fixed
