### ISSUE TITLE
[studio] Move operation fails to update commit_id for children of moved folder

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1123]
Per our conversation.

Steps
=====
* Create a tree of items
* Move tree of items
* Publish

Publishing fails because the commit_ids associated with the published items is the old commit_id and not the most recent commit_id associated with the move operation that occurred on the parent.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/794

**Comment by dejan-brkic** [comment]
Cherry pick is bringing all files included in commit id -> when publishing 1 file belonging to moved tree, cherry pick will actually publish whole tree.
Possible solution is when moving files perform commit on each moved file separately.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/795

**Comment by sumerjabri** [comment]
@dejan-brkic please drop the log level to debug for the newly added logs dealing with publishing and commit ids.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/796

**Comment by sumerjabri** [comment]
More issues:

* Copy a folder
* Paste it in the same place (to force a name collision)

https://gist.githubusercontent.com/sumerjabri/6e0b243b5a45ed376705a5f4f2d2fb07/raw/a39ba06726497b1d8c3613ca4acc02dc1ca0e29a/gistfile1.txt

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/796
