### ISSUE TITLE
[studio-ui] Copying a folder results in an invalid API call

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1124]
Step to Reproduce
==============
* Create a site using Editorial BP
* Copy a large folder then press Enter to confirm the Copy dialog

The API:
```
	Failed to load resource: the server responded with a status of 404 (404)
	/api/1/profile/set&Wed%20Jul%2019%202017%2014:06:27%20GMT-0400%20(EDT) Failed to load resource: the server responded with a status of 404 (404)
```

Logs are here: https://gist.github.com/sumerjabri/03593d4e1d2c652bd434f88d16865233

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/511
