### ISSUE TITLE
[studio-ui] Cursor is not in the first field when creating a new article page in editorial bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1125]
Using the website_editorial bp create a new site, then create a new article page, notice that the cursor is not in the first field (**Page URL**) all the time when creating a new page 

![screen shot 2017-07-20 at 11 18 53 am](https://user-images.githubusercontent.com/25483966/28430739-97e0f096-6d4f-11e7-8f85-7d87ef0cfcb2.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/517

**Comment by russdanner** [comment]
Verified

**Comment by alhambrav** [comment]
I still see the issue.  Usually after a fresh install of studio (git clone), and creating a new folder to create the new content into.

![screen shot 2017-07-26 at 9 49 39 am](https://user-images.githubusercontent.com/25483966/28625195-791b0928-71e9-11e7-8fe1-117c05e2ca96.png)

Here's a video of the cursor not appearing on the first field using a build from last night (7/25/2017)

https://www.useloom.com/share/01665b707966413bb57442b8bb29bbbb

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/craftercms/issues/1125

**Comment by vestrada** [comment]
@alhambrav Can you verify this ticket?

**Comment by alhambrav** [comment]
@vestrada 
I still see the issue... Just takes a little more time to reproduce.  Try to create a new folder, then new content.

https://www.useloom.com/share/08a82e7465bc4f069a8cce2c35dbb1ba

**Comment by alhambrav** [comment]
I wanted to add that I see the same issue some times too when trying to create a new taxonomy content.
Right click on **Taxonomy** in the Sidebar, then select **New Content**.  Notice the cursor is not in the first field in the form when it launches.

![screen shot 2017-07-26 at 4 07 54 pm](https://user-images.githubusercontent.com/25483966/28641268-a2c33600-721c-11e7-8645-803190229962.png)

It also happens when creating a new component.

**Comment by alhambrav** [comment]
@vestrada 
I still see the issue, and usually immediately after creating a site, then create a folder, then create the new content.  Sometimes the cursor is on the second field, or sometimes on the third field when the form launches.

https://www.useloom.com/share/546bd8e59d5c4a468b6209ca1d2a4d6b

**Comment by alhambrav** [comment]
Verified fixed.
