### ISSUE TITLE
[studio-ui] Keyboard keys don't work in some dialogs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1126]
* Escape keyboard key doesn't cancel "Create Content" dialog (where you choose the content type)
* Escape keyboard key doesn't cancel content entry form
* Enter key doesn't approve (Submit) publish
* Escape key doesn't cancel publish

In general, enter and escape must work on all dialogs.

**Comment by jvega-crafter** [comment]
Added events into the specified dialogs, for the remaining dialogs I'll continue on https://github.com/craftercms/craftercms/issues/877

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/516

**Comment by sumerjabri** [comment]
Still doesn't work for Publish dialog.
