### ISSUE TITLE
[studio-ui] publishing status icon in dialog should reflect the current publishing status

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1127]
<img width="1194" alt="screen shot 2017-07-20 at 2 55 35 pm" src="https://user-images.githubusercontent.com/169432/28433995-cd14e2ac-6d5b-11e7-97a9-cfad6f235cde.png">

**Comment by russdanner** [comment]
Comment in the picture is a little misleading.  If the dialog uses Checkmark (for good/working) and X (for stopped) then the appropriate icon and color should be shown in accordance with the publisher status

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/514

**Comment by russdanner** [comment]
Verified
