### ISSUE TITLE
[docs] Document backup and restore

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1133]
Please document backup and restore as developed in crafter.sh/bat

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/317

**Comment by alhambrav** [comment]
Waiting for ticket https://github.com/craftercms/craftercms/issues/685 to update the restore part of the docs

**Comment by sumerjabri** [comment]
@alhambrav does this change the docs: https://github.com/craftercms/craftercms/issues/1243

**Comment by alhambrav** [comment]
@sumerjabri  The backups already go to a folder named `backups`, and is taken into account in the docs:

Your backup file will be located in `{Crafter-CMS-install-directory}/crafter-{env}/backups/`
