### ISSUE TITLE
[studio] Studio loses track of content type on cut of new items

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1135]
Steps to Reproduce
---------------------------

* Create a site from Editorial BP
* Create a folder under home `test`
* Copy `articles/2016` and paste it in `test`
* Cut `test/2016/12`
* Paste in `test`

Logs show the loss of content type:
```
[ERROR] 2017-07-21 10:52:18,536 [http-nio-8080-exec-4] [content.DmContentLifeCycleServiceImpl] | No script found at /config/studio/content-types/unknown/controller.groovy, contentType: unknown 
```

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/807
