### ISSUE TITLE
[studio-ui] "Oops! The requested page can't be found." when creating a new component in headless bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1137]
Use either the headless store or the headless blog.
Create a new component.  I'll use the headless_store bp for my example.
Create a new items:companies component:

![screen shot 2017-07-21 at 11 48 50 am](https://user-images.githubusercontent.com/25483966/28471278-9be4a56e-6e0a-11e7-8a0a-611efb676f85.png)

Click on **Save and Close**
Notice that it looks like it tries to render the newly created component:

![screen shot 2017-07-21 at 11 49 29 am](https://user-images.githubusercontent.com/25483966/28471312-bd2569a2-6e0a-11e7-8f5f-1c03589aea07.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/519

**Comment by alhambrav** [comment]
Verified fixed.
