### ISSUE TITLE
[studio-ui] Opening page components in mobile preview should expand the iframe to accommodate the panel

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1141]
<img width="1287" alt="screen shot 2017-07-21 at 3 29 32 pm" src="https://user-images.githubusercontent.com/169432/28479269-b42a4a4c-6e29-11e7-948f-3fb3248dd5e1.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/970

**Comment by russdanner** [comment]
Confirmed.  Cool!
