### ISSUE TITLE
[studio] Delete fails under certain circumstances

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1143]
Steps to Reproduce
===============
* Create a site based on Editorial BP
* Create a folder `asdf`
* Cut `articles/2016` and paste in `asdf`
* Publish the contents of `asdf` one by one
* Delete the folder `asdf`

https://gist.github.com/sumerjabri/6e4ca2243002220b4ca368ae16ed6eed

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/805
