### ISSUE TITLE
[studio-ui] Items in tree disappears in the Sidebar after a bulk upload

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1144]
1. Create a new site using the website_editorial bp
2. Navigate to the static-assets folder and expand the `images` folder

![screen shot 2017-07-21 at 3 40 13 pm](https://user-images.githubusercontent.com/25483966/28479745-c9289a00-6e2b-11e7-8876-e8511231b15b.png)

3. Right click on `images` and select `Bulk Upload Assets`, I then drag a bunch of images there.  After clicking on `Done`, notice in the Sidebar that items in the `images` folder are not displayed, but just some space
 
![screen shot 2017-07-21 at 3 37 56 pm](https://user-images.githubusercontent.com/25483966/28479532-c6f17de8-6e2a-11e7-9dfe-1e8f75c0e4ca.png)

4.  Sometimes I need to expand some of the folders for the articles, then expand the folder for "images" then do the bulk upload to reproduce

![screen shot 2017-07-21 at 3 48 46 pm](https://user-images.githubusercontent.com/25483966/28479882-591717fe-6e2c-11e7-9f24-9f4933216b95.png)

 
Here's a video:
https://www.useloom.com/share/fe8628759ecc4c6e855338e9111705ab

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/520

**Comment by alhambrav** [comment]
Verified fixed.
