### ISSUE TITLE
[studio] The featured articles does not appear in the Home page when you first create the site in editorial bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1151]
Create a new site using the website_editorial bp.
Notice that the featured articles section of the Home page is empty.  To see the articles, you need to refresh.

![screen shot 2017-07-24 at 3 14 57 pm](https://user-images.githubusercontent.com/25483966/28540330-fff71f62-7082-11e7-851b-b318159669ec.png)

**Comment by sumerjabri** [comment]
@avasquez614 let's discuss the final approach tomorrow and make a final decision if we do in 3.0 or 3.1

**Comment by alhambrav** [comment]
Verified fixed.
