### ISSUE TITLE
[studio-ui] Preview tool labels do not render properly (transition from keys to values)

### ISSUE THREAD

**Issue by MarkNelson17** [craftercms/craftercms#1152]
# Issue reproduction
https://www.useloom.com/share/be07a097549d4e928d0d0fd2502049c6

# browser
Version 59.0.3071.115 (Official Build) (64-bit)
Automatically update Chrome for all users Learn more

# machine details
  Model Name:	MacBook Air
  Processor Name:	Intel Core i5
  Processor Speed:	1.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  Memory:	8 GB
  Boot ROM Version:	MBA61.0099.B21
  SMC Version (system):	2.13f15

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/522

**Comment by russdanner** [comment]
Verified
