### ISSUE TITLE
[studio] Change default filename for backup

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1154]
When running the backup script, if no filename is specified, the name created for the backup file is
`.yyyy-mm-dd.zip`

Please change it to (for default, if no filename is specified):
`studio-backup-{yyyy-mm-dd-hh-mm-ss}.zip`

with the time listing up to the msec, so in case they run the backup script a few times in a day, there is no conflict in names/ no overwriting.

**Comment by alhambrav** [comment]
Since the script used to backup is located inside the authoring environment, please rename the backup file to:
`crafter-authoring-backup-{yyyy-mm-dd-hh-mm-ss}.zip`

**Comment by jdrossl** [comment]
@sumerjabri @alhambrav the script will be present in both authoring and delivery so I thought `crafter-backup-*` would work for both. The final zip will be in the crafter root folder so authoring and delivery backups will not be mixed. Let me know if the script should change the name based on which env it is.

**Comment by alhambrav** [comment]
@jdrossl Hi!  I was about to file another ticket to name the backup file created in the delivery environment as: `crafter-delivery-backup-{yyyy-mm-dd-hh-mm-ss}.zip`, so yes, we want the name to change based on which env the backup is being created in.

**Comment by alhambrav** [comment]
Verified fixed.
