### ISSUE TITLE
[docs] Verify/update docs on Solutions Active Cache and Solutions RESTful Services

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1155]
Solutions: Active Cache
developers/cook-books/active-cache/cache-a-restful-response.html

Solutions RESTful Services:
developers/cook-books/services/rendered-components-as-json.html
developers/cook-books/services/get-a-list-of-sites.html
developers/cook-books/services/get-site-pages.html

**Comment by avasquez614** [comment]
PR craftercms/docs#316

**Comment by alhambrav** [comment]
Verified.
