### ISSUE TITLE
[studio] Folders appear in My Recent Activity when cut/pasting a tree

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1156]
1. Cut a folder with subfolders.
2. Paste the folder under another folder.

See the attached image. The folders appear as items in My Recent Activity. This is not the case when copy/pasting.

![screenshot from 2017-07-25 16-13-00](https://user-images.githubusercontent.com/1598884/28591623-5f1984fe-7154-11e7-8116-072a38f737dc.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/809

**Comment by avasquez614** [comment]
Verified
