### ISSUE TITLE
[studio] Dependencies with '(' in their name do not get calculated as dependencies for deployment

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1158]
Example filename: Hidden_Valley_Bandstand_-_2017_Volunteer_Org_Chart_(3-13-17).png

# reproducing the error
1. start with fresh editorial blueprint (blueprint does not matter)
2. add a new page based on the section template
3. Upload an image for the page (form has an image picker) with the name: Hidden_Valley_Bandstand_-_2017_Volunteer_Org_Chart_(3-13-17).png
4. save page
5. Go to dashboard and click approve and publish
6. Note the image is not show as a dependency in the approve dialog
7. approve the publish, note the image does not get marked as live
8. View the new pages dependencies, note that the image is calculated but the path looks incorrect.

<img width="1406" alt="screen shot 2017-07-25 at 4 14 59 pm" src="https://user-images.githubusercontent.com/169432/28591861-23e7a086-7155-11e7-9390-fd225a3023d9.png">

**Comment by russdanner** [comment]
The issue applies to 2.5 and 3.0

**Comment by sumerjabri** [comment]
Please create a dependency calculator resolver that uses a different mechanism to calculate deps depending on the asset.

Ping  me if you need help with this.

**Comment by dejan-brkic** [comment]
@sumerjabri We need to discuss few details about implementation.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/828

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/834

**Comment by russdanner** [comment]
This fix does not seem to work for me.  
I tried uploading 2 images to the homepage of editorial and publishing, neither were published as a dependency

Names I tried
coat2(3).jpg
coat2 (2).jpg

**Comment by russdanner** [comment]
https://www.useloom.com/share/2c131ceff66e451bb80e4738af101042

**Comment by dejan-brkic** [comment]
Issue is not code issue but configuration. Resolution involves new dependency resolver and more flexible configuration. You will still need to come up with regular expression and configuration that will solve the problem.

**Comment by russdanner** [comment]
Sumer do we need a new ticket to update blueprints or should we do that here?

**Comment by sumerjabri** [comment]
@alhambrav please update all blueprints to accommodate the new resolver. Please reach out to Dejan for help if you need it.

**Comment by alhambrav** [comment]
Done.
PR https://github.com/craftercms/studio/pull/846

**Comment by russdanner** [comment]
VERIFIED
