### ISSUE TITLE
[studio] Publishing fails on delete

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1159]
Steps to Reproduce
===============
* Create a site using Editorial BP
* Create a folder off the home page `stuff`
* Create two sub-folders under `stuff` called `1` and `2`
* Copy `articles/2016` and paste under `1`
* Copy `articles/2017` and paste under `2`
* Cut `stuff/1/2017` and paste under `2`
* Publish everything under `1` (one file at a time)
* Publish everything under `2` (one file at a time)
* Delete `1`, watch the logs

Logs: https://gist.github.com/sumerjabri/1777ef39c3599cfc8321db23616a74e6

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/809

**Comment by sumerjabri** [comment]
Happened again.
https://gist.github.com/sumerjabri/30500d4025ecde02534941275f45afb3

**Comment by dejan-brkic** [comment]
Use case didn't give publishing error. It exposed a DB error for deleted items in publishing history

PR:
https://github.com/craftercms/studio/pull/816

**Comment by sumerjabri** [comment]
Can't reproduce.
