### ISSUE TITLE
[studio-ui]  Clicking the back button in studio logs user out

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1161]
# reproduce the error
1. sign in
2. click preview on a site
3. click the browser back button
4. observe you are redirected to the login page

Bug exists in 2.x and 3.x fix can go in to any 3.x release.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/535

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/535

**Comment by russdanner** [comment]
VERIFIED

Clicking back directly after login still takes you back to login but that's reasonable.
