### ISSUE TITLE
[craftercms] Rename zip files in bundle

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1165]
Please rename the zip files in the bundle as follows:
``crafter-authoring-cms.zip``              **->** ``crafter-cms-authoring.zip``
``crafter-authoring-cms.zip.md5``      **->** ``crafter-cms-authoring.zip.md5``
``crafter-authoring-cms.tar.gz``          **->** ``crafter-cms-authoring.tar.gz``
``crafter-authoring-cms.tar.gz.md5`` **->** ``crafter-cms-authoring.tar.gz.md5``
``crafter-delivery-cms.zip``                  **->** ``crafter-cms-delivery.zip``
``crafter-delivery-cms.zip.md5``         **->** ``crafter-cms-delivery.zip.md5``
``crafter-delivery-cms.tar.gz``             **->** ``crafter-cms-delivery.tar.gz``
``crafter-delivery-cms.tar.gz.md5``    **->** ``crafter-cms-delivery.tar.gz.md5``

**Comment by cortiz** [comment]
PR #1169

**Comment by alhambrav** [comment]
Verified fixed.
