### ISSUE TITLE
[studio-ui] Cannot edit items under "Taxonomy"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1166]
Using the website_editorial, or headless bps, open the **Sidebar**, navigate to **Taxonomy** and right click on one of the items listed.  Notice that you cannot edit.

![screen shot 2017-07-26 at 4 23 56 pm](https://user-images.githubusercontent.com/25483966/28642036-029f472e-721f-11e7-9aec-73d81c00339a.png)

**Comment by vestrada** [comment]
Hi @dejan-brkic 
Api is sending incomplete information when the content type is taxonomy.
For Example:
- form and formPagePath are empty.
- also contentType should be: /component/taxonomy not taxonomy (/api/1/services/api/1/content/get-content-type.json)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/819

**Comment by alhambrav** [comment]
Verified fixed.
