### ISSUE TITLE
[studio-ui] image crop dialog does not show when image is larger than max height and width

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1168]
# reproducing the issue
1. create a image picker with a max height and width, assign a file from desktop data source
2. Try to upload a larger image.  
3. Note crop dialog does not show
4. Note error on console

<img width="1424" alt="screen shot 2017-07-26 at 4 47 53 pm" src="https://user-images.githubusercontent.com/169432/28643099-b38951da-7222-11e7-8f10-453017c3a56f.png">

# applies to
2.5 only.  I tested 3.x and it works there.

**Comment by jvega-crafter** [comment]
This issue happens in both studio 2.5 and 3, it happens when you upload the image opening the form from the dashboard, if you do it from the preview it works. Fixing in both versions

**Comment by jvega-crafter** [comment]
Studio3: https://github.com/craftercms/studio2-ui/pull/526
Studio2.5: https://github.com/craftercms/studio2-ui/pull/527

**Comment by russdanner** [comment]
Verified
