### ISSUE TITLE
[studio-ui] improve publishing status dialog to auto update

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1170]
# Improvements
- change ok button to "close"
- add an animated monitoring indicator (like a spinner or a Knight Rider :D) 
http://wallpapersafari.com/w/YLKpsD/
- while the dialog is open (or using the poll from the tool bar) update the data in the dialog

# mock up
<img width="465" alt="screen shot 2017-07-26 at 5 42 12 pm" src="https://user-images.githubusercontent.com/169432/28645620-4f8ff74c-722c-11e7-97b4-ee3427408409.png">
Indicaor here doesn't look like what I'm thinking it's just showing the idea.

**Comment by russdanner** [comment]
I think this spinner icon represents the activity the best
http://fontawesome.io/icon/circle-o-notch/

We're not in a wait...
We're not "refreshing" in a process the will ultimately complete.
We're actively monitoring.  We just want to show work

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/534

**Comment by russdanner** [comment]
VERIFIED
