### ISSUE TITLE
[studio] Copy/paste breaks dependency calculation

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1171]
Steps to Reproduce
===============
* Create a site using Editorial BP
* Create a folder under `home` called `1`
* Copy the article `articles/2016/12/Top Books For Young Women` to `1`
* Copy the subtree `articles/2016/6` and paste it under `1/Top Books For Young Women`
* Publish the article `1/Top Books For Young Women/6/Coffee is Good for Your Health`
* Note that in the publish dialog, you'll find all dependencies calculated correctly
* Hit `Submit` to publish the content and note that the file `1/top-books-for-young-women/index.xml` is not published (wrong)

Disk looks like this (my site was called `test`:
```
tree test/published/site/website/1  
test/published/site/website/1
└── top-books-for-young-women
    └── 6
        └── coffee-is-good-for-your-health
            └── index.xml

3 directories, 1 file
```

Dashboard shows:
![copy-paste-dep-error](https://user-images.githubusercontent.com/3931908/28677760-84e41442-72bc-11e7-94ff-3fba8d2d7422.png)

Note that the system *knows* that it didn't publish `Top Books For Young Women` even though it also *new* it should.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/820

**Comment by russdanner** [comment]
Verified
