### ISSUE TITLE
[craftercms] Hamburger icon does not open in delivery

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1173]
Create a site using the website_editorial bp.
Setup delivery by running the init-site.sh script.
Open your browser and go to delivery: `localhost:9080`
Make your browser only wide enough that the left-rail is not displayed on your screen.
Click on the hamburger to open the left-rail.  Notice that the left-rail does not open.

![screen shot 2017-07-27 at 12 32 22 pm](https://user-images.githubusercontent.com/25483966/28681543-d6686a06-72c7-11e7-8aae-9d263a6458b8.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio/pull/821

**Comment by alhambrav** [comment]
Verified fixed.
