### ISSUE TITLE
[studio-ui] When you click on a component item from search results, it tries to render it

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1177]
For now, in the search results, anything that is not a page should not be rendered (not a clickable link maybe?)

Click on the magnifying glass at the top right of Studio.  Enter a search term such as **lo**

![screen shot 2017-07-28 at 2 15 15 pm](https://user-images.githubusercontent.com/25483966/28730730-41609464-739f-11e7-9841-8b8fcec4453a.png)

Click on any of the results that are components, notice that it tries to render it and displays:

![screen shot 2017-07-28 at 2 17 43 pm](https://user-images.githubusercontent.com/25483966/28730856-962e28bc-739f-11e7-9ab1-6cfd81ed426b.png)

**Comment by sumerjabri** [comment]
Only render pages.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/540

**Comment by alhambrav** [comment]
Verified.
