### ISSUE TITLE
[studio-ui] CMIS data source should handle missing slash in destination path

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1179]
<img width="1424" alt="screen shot 2017-07-31 at 9 28 38 am" src="https://user-images.githubusercontent.com/169432/28780495-e95ac66c-75d4-11e7-8f22-4343ff18a2ad.png">

* If the user does not provide a trailing slash, add it.  
* If the user provides a trailing slash, do not // double it up

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/537

**Comment by russdanner** [comment]
Tested with CMIS/Image and it still has issues
https://www.useloom.com/share/c38830d75b594ee2beeb570a04144a01

**Comment by russdanner** [comment]
Please make sure last / in paths are automatically handled correctly with all CMIS pickets

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/552

**Comment by russdanner** [comment]
Please update all CMIS repo data sources with the same logic

**Comment by russdanner** [comment]
VERIFIED.  I see the logic there.  different PR
