### ISSUE TITLE
[studio] 2.5 copy to deploy/copy to environment swallows basic IO exceptions

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1182]
IO issues from source (bad CR, connection drop) or destination (disk full) are swallowed by org.craftercms.studio.impl.v1.deployment.EnvironmentStoreDeployer.deployFile

`https://github.com/craftercms/studio/blob/05430f0ddbcca35da7956e96df7e07e0740100cc/src/main/java/org/craftercms/studio/impl/v1/deployment/EnvironmentStoreDeployer.java`

File copies with basic networking and IO exceptions should be retried once.  If the file cannot be copied fully, it should not be queued for transfer.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/827

**Comment by russdanner** [comment]
Reviewed
