### ISSUE TITLE
[studio-ui] CMIS data source search should be constrained to the path where the data source is pointing

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1186]
User's search should be constrained to the path that the data source is configured with

**Comment by vestrada** [comment]
Hi :)

Reviewing the documentation, It is how the search api works.
Please take a look: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/search.html

If you want some BE changes please talk with Sumer or Russ.

**Comment by russdanner** [comment]
Can't replicate.
