### ISSUE TITLE
[studio-ui] Create CMIS data sources for type image and video

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1187]
Data sources have basic types ITEM, IMAGE, VIDEO. We need a CMIS Datasource for each type. 

This is simple to address. Change the current data source to a base class, create 3 sub classes and override the type property only.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/538

**Comment by russdanner** [comment]
VERIFIED
will open specific tickets for issues
