### ISSUE TITLE
[studio-ui] CMIS data sources should allow form creator to constrain Link and Clone options

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1189]
Add a selectable (drop-down) property (labeled: Allowed Operations) to the CMIS data sources that allow the form creator to choose what kind of linking is allowed:
- Clone and Link
- Clone
- Link

Default it to Clone and Link

Update the UI/Dialog to respect the Allowed Operations selection

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/536

**Comment by russdanner** [comment]
VERIFIED
