### ISSUE TITLE
[studio-ui] Templates can only be selected from the root of /templates

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1191]
Steps to reproduce:

In Site Config try to change the template for a content-type
<img width="416" alt="screen shot 2017-08-03 at 10 50 29 am" src="https://user-images.githubusercontent.com/1236955/28933656-2975a04c-783b-11e7-9430-ccb89d825fc9.png">

In the browse dialog expand the subfolders
<img width="1196" alt="screen shot 2017-08-03 at 10 50 39 am" src="https://user-images.githubusercontent.com/1236955/28933657-2afba5e2-783b-11e7-8044-4b61624bac82.png">

Click a subfolder
<img width="1200" alt="screen shot 2017-08-03 at 10 50 50 am" src="https://user-images.githubusercontent.com/1236955/28933662-2c9b9f4c-783b-11e7-9adf-8a478e753eda.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/537

**Comment by jdrossl** [comment]
Verified
