### ISSUE TITLE
[studio] Deleted image file is listed in the "My Recent Activity" widget with filter set to "Pages"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1196]
Deleted image files should not be listed in the "My Recent Activity" widget in the Dashboard when the filter is set to "Pages".

Upload an image or two in the static-assets/images folder. (In my example images before, I uploaded two images)
Look at the widget "My Recent Activity" in the dashboard, and set the filter to "All", then set the filter to "Pages".  Notice the items listed.

Delete an image you uploaded.
Look at the widget "My Recent Activity" in the dashboard, and set the filter to "All", 

![screen shot 2017-08-09 at 1 02 10 pm](https://user-images.githubusercontent.com/25483966/29134158-cfd1d5b0-7d03-11e7-9727-1e68ec3d1c5c.png)

then set the filter to "Pages".  Notice the items listed.

![screen shot 2017-08-09 at 1 01 52 pm](https://user-images.githubusercontent.com/25483966/29134173-d92b3ffc-7d03-11e7-8831-51b0516fc382.png)

**Comment by jvega-crafter** [comment]
Service call goes like this: 
`http://localhost:8080/studio/api/1/services/api/1/activity/get-user-activities.json?site=editorial&user=admin&sort=eventDate&ascending=false&num=20&filterType=pages&excludeLive=false`

the pages filter parameter is sent, but the response includes non-pages items

<img width="585" alt="screen shot 2017-08-10 at 9 51 11 am" src="https://user-images.githubusercontent.com/18267471/29179384-7d5cea82-7db1-11e7-9a33-744ba2f6a421.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/834

**Comment by alhambrav** [comment]
Verified.
