### ISSUE TITLE
[studio] Items not under "/site" should not have the option to compare and view in the "Version History" screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1197]
Click on an image under the static-assets/images folder to view the file, then click on "History" in the context nav.  Notice that the option to compare and view a certain version is available.  Items not under "/site" should not have the option to compare and view in the "Version History" screen

![screen shot 2017-08-09 at 4 11 39 pm](https://user-images.githubusercontent.com/25483966/29141933-38cabdba-7d1e-11e7-9d4a-2bcd4c033a32.png)

**Comment by vestrada** [comment]
Hi @sumerjabri 

I noticed that content type is "unknow" from "/api/1/services/api/1/content/get-item-versions.json api" as you can see in the below image.
I can validate through the browserUri if it contains "/site" as the ticket says or we can fix the back end. What do you prefer?

<img width="485" alt="screen shot 2017-08-10 at 10 06 25 am" src="https://user-images.githubusercontent.com/11640613/29189195-fb40feea-7dd2-11e7-8e02-262699ca351f.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/834

**Comment by alhambrav** [comment]
Verified.
