### ISSUE TITLE
[craftercms] All WARs should have a crafter- prefix

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1200]
All Crafter wars should have the crafter- prefix on them. Right now they're clashing with pages named /profile, /social, /search etc.

**Comment by sumerjabri** [comment]
:(

All WARs now become `crafter-`

**Comment by cortiz** [comment]
PR https://github.com/craftercms/craftercms/pull/1202

**Comment by avasquez614** [comment]
@cortiz crafter-profile-admin-console should only be crafter-profile-admin

**Comment by cortiz** [comment]
Crafter profile admin name solve in PR's https://github.com/craftercms/profile/pull/137 and https://github.com/craftercms/craftercms/pull/1221

**Comment by avasquez614** [comment]
Verified
