### ISSUE TITLE
[docs] download reference should point to community download page

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1204]
This page: 
http://docs.craftercms.org/en/3.0/getting-started/quick-start-guide.html#installing-crafter-cms-from-the-zip-download

points to 
http://downloads.craftercms.org/craftercms/community/3.0.0/

but should point to:
http://craftercms.org/downloads

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/329

**Comment by russdanner** [comment]
VERIFIED
