### ISSUE TITLE
[docs] add prerequisite installation guidance for Java to getting started

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1205]
This page/section should include a link to a page with basic instructions prior to the install to help the user make sure they have what they need for a successful installation:

http://docs.craftercms.org/en/3.0/getting-started/quick-start-guide.html#installing-crafter-cms-from-the-zip-download

# Installing and verifying pre requisites

## Install Java
  1. Download and install Java JDK 1.8 (either Oracle or OpenJDK).
  2. Ensure that you are running Java 1.8

Run the following command at the command prompt and make sure that the version displayed is Java 1.8:
`java -version
`
   3. Verify that your JAVA_HOME environment variable is set correctly.
Make sure that you have a JAVA_HOME environment variable that points to the root of the JDK install directory.

IMPORTANT: The path specified in your JAVA_HOME variable should not contain spaces.
This means that on Windows the path in your JAVA_HOME environmental variable must use Windows short filename convention based names and must not contain spaces, for example:
JAVA_HOME=C:\Progra~1\Java\jre-1.8.0_65\

**Comment by sumerjabri** [comment]
@alhambrav please make sure this is also present in sys admin section (pre-requisites)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/330

**Comment by russdanner** [comment]
verified.
