### ISSUE TITLE
[studio-ui] Clicking on "Save and Close" or "Save Draft" in in-context edit takes you back to the home page instead of the previous page being previewed 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1206]
In Website_editorial, preview one of the articles.  In the example below, the article "Coffee is good for you health" is being previewed.  Now click one of the in-context edit pencils:

<img width="871" alt="screen shot 2017-08-14 at 1 22 55 pm" src="https://user-images.githubusercontent.com/25483966/29283255-dd1bac34-80f3-11e7-93ce-3003f693f715.png">

Click either the "Save and Close" or "Save Draft" button.  Notice that after the form closes, it takes you back to the home page preview instead of the previous page being previewed, which was the article "Coffee is good for your health"

<img width="1315" alt="screen shot 2017-08-14 at 1 24 26 pm" src="https://user-images.githubusercontent.com/25483966/29283336-5012b610-80f4-11e7-845f-96b243d644aa.png">

Here's a short clip:
https://www.useloom.com/share/0b7da0bfb45343e6bfd411695d970737

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/543

**Comment by alhambrav** [comment]
Verified fixed.
