### ISSUE TITLE
[docs] Create a "Debugging publishing issues" article

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1207]
Create a new article here: http://docs.craftercms.org/en/3.0/system-administrators/index.html

Call it `Debugging Publishing Issues`.

List out typical issues and how to fix them. Make sure to indicate how to reset the publishing queue, and how to reset item state.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/337

**Comment by sumerjabri** [comment]
@dejan-brkic Please update the article: http://docs.craftercms.org/en/3.0/system-administrators/studio/debugging-publishing-issues.html

Please include:
- How to sync `published` from `sandbox` using recursive/accept-theirs git pull
- The API to call to resume publishing

Please also re-read and validate the article and see if it's still what you want it to be.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/369

**Comment by sumerjabri** [comment]
@alhambrav please adjust per our conversation.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/373

**Comment by sumerjabri** [comment]
Please update per our last conversation to match the latest.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/393
