### ISSUE TITLE
[Studio] Windows Inital page state does not match Linux/Osx

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1208]
Steps:
1. Download and use  VM with windows 10 x64 from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ of phisical windows machine

2. Download and install the latest java 8 JDK from oracle page http://www.oracle.com/technetwork/java/javase/downloads/index.html

3. Set the JAVA_HOME environment variable to point the jdk just installed.

4. Download and unzip the crafter authoring bundle from http://downloads.craftersoftware.com/craftercms/community/3.0.0/crafter-cms-authoring.zip

5. Start it by running CRAFTER_HOME/bin/startup.sh (**as an administrator the first time**)
   5.1 Ignore the mongodb issue

6. Once it's up, go to http://localhost:8080/studio

7. Log in and create a site using the editorial blueprint.

8. Once the site is created, the state of the objects is not the same as if it were OSX or Linux, since in those OS all pages/assets/components are in a live state, while on windows they are not.(see screenshots)

Windows:![windowsstateofpages](https://user-images.githubusercontent.com/574641/29288772-40fce9e0-80f7-11e7-8ab7-558053b37b76.png)

Linux:![linuxpagestate](https://user-images.githubusercontent.com/574641/29288784-4efba8b0-80f7-11e7-8721-4d810a8127f6.png)

Logs.
[logs.zip](https://github.com/craftercms/craftercms/files/1223264/logs.zip)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/847
