### ISSUE TITLE
[studio-ui] Context Nav when in the Site Config menu is not displaying correct items

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1214]
The Context Nav is not being refreshed all the time when selecting another item in the Site Config Menu.  It is displaying items not valid for the current item selected in the Site Config Menu.

1. Click on the **Site Config** from the **Sidebar**
2. Click on **Content Types**, notice the Context Nav now displays **Open Existing Type** and **Create New Type**

![screen shot 2017-08-15 at 11 52 29 am](https://user-images.githubusercontent.com/25483966/29323884-3fc8032a-81b0-11e7-9788-2704e568988d.png)

3. Now click on **Groups**, notice that the Context Nav is still displaying **Open Existing Type** and **Create New Type**, which is not valid for the item **Groups**

![screen shot 2017-08-15 at 11 52 51 am](https://user-images.githubusercontent.com/25483966/29323965-979e71f6-81b0-11e7-8d98-dd49391eef82.png)

To clear the context nav, you can click on **Configuration**, then click on **Groups**.
You can try clicking on other items in the Site Config menu that has context nav menu items, then click on another Site Config menu item that does not have context menu options and you'll see the same behavior for most of the Site Config Menu items.

Here's a short clip.

https://www.useloom.com/share/b211665be9cb4d32ac46b9252f333994

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/546

**Comment by alhambrav** [comment]
Verified fixed.
