### ISSUE TITLE
[studio-ui] Save as draft should refresh preview

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1216]
# steps
1. go to preview
2. click edit
3. make a visible edit and click save as draft
3. click the up arrow on form, note that your update is not visible

# expectation
The up arrow exists so that users can save as draft and preview what the content should look like,

# applies to
2.5.x and 3.x

https://www.useloom.com/share/1a1939ba19fc4871935105eba51e024c

**Comment by jvega-crafter** [comment]
2.5.x: https://github.com/craftercms/studio2-ui/pull/545
3.x: https://github.com/craftercms/studio2-ui/pull/544

**Comment by russdanner** [comment]
VERIFIED
