### ISSUE TITLE
[studio] Bulk publishing for /config not working

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1218]
1. Create a site with the editorial blueprint.
2. Go to Site Config > Configuration > Configurations.
3. Add the following lines:
```
        <file>
            <path>/engine/site-config.xml</path>
            <title>Engine Site Configuration</title>
            <description>Site configuration used by Crafter Engine</description>
            <samplePath>/studio/administration/samples/sample-engine-site-config.xml</samplePath>
        </file>
		<file>
            <path>/engine/application-context.xml</path>
            <title>Engine Site Application Context</title>
            <description>Site application context used by Crafter Engine</description>
            <samplePath>/studio/administration/samples/sample-engine-application-context.xml</samplePath>
        </file>
```
4. Reload the page, go to configurations again, and now pick Engine Site Configuration.
5. Put some XML in the file, like this:
<?xml version="1.0" encoding="UTF-8"?>
```
<site>
	<properties>
    	<myprop>Test</myprop>
	</properties>
</site>
```
6. Now go Bulk Operations and deploy /config.

The result is that nothing is deployed, when /config/engine/site-config.xml should have been deployed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/854

**Comment by avasquez614** [comment]
Tested and verified
