### ISSUE TITLE
[studio] Build database version check/update mechanics

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1219]
Per our conversation: Please build a system that does this:
* Check if database is present, if not create it
* Create a method that returns database version
** If tables _meta is present, then check a row with 'version' and 'value' and read that value
** If _meta is not present, then check if users table is present, if so, return 3.0.0
** If not, return 2.5.0
* If version is 3.0.0 update the database to latest via scripts and create _meta and populate it
* If version is 2.5.0, throw an exception and refuse to start

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/834
