### ISSUE TITLE
[studio-ui] There's no notification dialog that a user has been removed from a group

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1226]
It would be nice, to make it consistent, that a notification message is shown after removing users from a group.

1. Click on **Site Config** in the Sidebar
2. Click on **Groups**
3. Click on the pencil icon next to a group, to edit members of the group
4. Remove one of the users in the group by clicking on the trash can icon.
Notice that after clicking on the confirmation dialog that you want to remove the user from the group that it doesn't display a notification message that so and so has been removed from the group.

When you add a user to the group, a notification message is shown on the screen that users has been added to the group

![site-config-groups-users-added-notification](https://user-images.githubusercontent.com/25483966/29435815-848d2946-8376-11e7-9c9c-cdb8c5ce5e44.png)

When you remove a group, a notification message is displayed after confirming that you want to remove a group

![site-config-groups-removed-notification](https://user-images.githubusercontent.com/25483966/29435846-aaa11ee4-8376-11e7-9e92-785207c66985.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/555

**Comment by alhambrav** [comment]
Verified.
