### ISSUE TITLE
[studio-ui] Preview tools panel and tooltips does not use Open Sans for the font

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1228]
Using the Website_editorial bp, click on the wrench at the top right of studio to open the preview tools panel.  Notice the font in the dialog is not Open Sans:

![screen shot 2017-08-18 at 10 59 15 am](https://user-images.githubusercontent.com/25483966/29464586-507545c4-8404-11e7-84b5-91b2b3aa892d.png)

Click on **Page Components**, notice that the font used in the panel is also not Open Sans:

![screen shot 2017-08-18 at 10 27 50 am](https://user-images.githubusercontent.com/25483966/29464530-24a3f166-8404-11e7-8c63-8edb34722b1d.png)

Click on **Browse Features**, after selecting the component you want to add, notice the notification on the top right of the screen does not use Open Sans for the font:

![screen shot 2017-08-18 at 11 01 29 am](https://user-images.githubusercontent.com/25483966/29464716-b4f91f8e-8404-11e7-963b-254bb3aa9329.png)

In the **Sidebar**, hover on any of the folders/items, notice the font used in the tooltip is not Open Sans

![screen shot 2017-08-18 at 11 32 33 am](https://user-images.githubusercontent.com/25483966/29466082-92025b94-8409-11e7-81dc-153ffd1d4553.png)

Clicn on **Approve & Publish** in the context nav, then click on **Items go live on a specific date & time**, notice that the font used by the datetime picker is not Open Sans

![screen shot 2017-08-18 at 11 38 45 am](https://user-images.githubusercontent.com/25483966/29466229-107f20a6-840a-11e7-9307-b7d88f8b1df1.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/550

**Comment by alhambrav** [comment]
Verified.
