### ISSUE TITLE
[studio-ui] Pressing the <esc> key does not cancel placing an existing component in the drag and drop zone

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1229]
Pressing the <esc> escape key should cancel placement of component in the drag and drop zone.

Using the Website_editorial bp, click on the wrench at the top right of Studio to open the Preview Panel Tools.  Click on **Page Components**, then click on **Browse Features**

![screen shot 2017-08-18 at 12 31 17 pm](https://user-images.githubusercontent.com/25483966/29468186-3752d7fc-8411-11e7-8403-9d364f454a89.png)

Select a component from the list, I selected the component "Four".  Notice also that if you press the <esc> escape key from this screen, it does not cancel the form.

![screen shot 2017-08-18 at 12 32 10 pm](https://user-images.githubusercontent.com/25483966/29468373-ee5a7f4a-8411-11e7-98df-aa537b06d746.png)

Now, press the <esc> escape key to cancel, notice that pressing the escape <esc> key does not cancel placement of the component you just selected.

![screen shot 2017-08-18 at 12 39 19 pm](https://user-images.githubusercontent.com/25483966/29468508-92a65efc-8412-11e7-8ebc-2019fdb7b631.png)

Here's a short clip.  I put a comment on the section where I am pressing on the <esc> escape key.

https://www.useloom.com/share/33bcb4dc90cf4d95bdef455d7e14c032

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/559

**Comment by alhambrav** [comment]
Verified.
