### ISSUE TITLE
CRAFTERCMS-2057: configure the XML security provider as the default in the crafter install

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#123]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2057
----------

**Comment by russdanner** [comment]
Reopening this because 2.5.4 DOES NOT have this configured.

**Comment by sumerjabri** [comment]
No longer needed per Russ.
