### ISSUE TITLE
[studio-ui] Datetime picker in the "Approve for Publish" dialog does not go away after pressing the <esc> escape key

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1230]
Datetime picker in the "Approve for Publish" dialog does not go away after pressing the \<esc\> escape key when using Chrome or Firefox web browser.

1. Using the Website_editorial bp, edit any of the pages.  In my example, my home page has been edited.
2. Click on **Approve & Publish** in the context nav
3. Click on **Items go live on a specific date & time**, the datetime picker will appear

![screen shot 2017-08-18 at 2 20 10 pm](https://user-images.githubusercontent.com/25483966/29472044-62296e14-8420-11e7-9001-cb4bcdff3b6e.png)

4. Press the \<esc\> escape key on your keyboard to cancel the **Approve & Publish** dialog.  Notice that the **Approve & Publish** dialog goes away but the datetime picker does not go away.  (This only happens with Chrome and Firefox web browser)

![screen shot 2017-08-18 at 2 20 32 pm](https://user-images.githubusercontent.com/25483966/29472098-8dd8247e-8420-11e7-8b88-d9a250ad9bd6.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/557

**Comment by alhambrav** [comment]
Verified.
