### ISSUE TITLE
[craftercms] Windows 7, 8, 8.1 Might need install a Windows C runtime update.

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1232]
Windows 7,8, 8.1 might need to install this before starting up or mongodb won't startup. (The error is `api-ms-win-crt-runtime-l1-1-0.dll is missing`)

 https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows 
This is optional (if they already have) but it will be good to have it documented

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/338

**Comment by cortiz** [comment]
We should also add Windows Server 2012 R2 , Windows Server 2012  and all Windows Server 2008

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/346
