### ISSUE TITLE
[studio-ui] only previewable content should have a hover state and be clickable on dashboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1235]
<img width="1384" alt="screen shot 2017-08-18 at 4 30 23 pm" src="https://user-images.githubusercontent.com/169432/29477109-ed1ac43c-8434-11e7-938b-5234badbf062.png">

Only pages and previewable static assets should be clickable and have a hover-state on the dashboard.  Items that cannot be clicked should appear in the same color but without a hover (underline and mouse cursor change).

**Comment by vestrada** [comment]
2.5.x: https://github.com/craftercms/studio2-ui/pull/554
master: https://github.com/craftercms/studio2-ui/pull/554

**Comment by russdanner** [comment]
VERIFIED
