### ISSUE TITLE
[studio-ui] editing existing components in sidebar changes hover states

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1236]
# to reproduce
1. Notice the color of the component in the video, it's gray
2. Right click and edit the component
3. Note that the color became blue

https://www.useloom.com/share/594a80611e104fd5884c6304609453f6

**Comment by jvega-crafter** [comment]
I'm not being able to reproduce it, @russdanner can you please confirm that it still happens to you?

**Comment by russdanner** [comment]
Verified
