### ISSUE TITLE
[studio-ui] publishing status dialog activity icon "wobbles" when it spins

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1238]
https://www.useloom.com/share/a7aebdc37da34ba888151fb61ba5a7e4

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/563

**Comment by russdanner** [comment]
Icon size is not a concern.  
Note that the icon moves left-right as it rotates.
https://www.useloom.com/share/e5de1d1c00464bdbb04cea906df2f189

**Comment by vestrada** [comment]
Hi!

I did a research, I found in the fontawesome website a warning that inform that some browsers on some platforms have issues with animated icons resulting in a jittery wobbling effect. Please take a look to the following image:
<img width="1078" alt="screen shot 2017-09-08 at 11 04 45 am" src="https://user-images.githubusercontent.com/11640613/30222852-9957e350-9485-11e7-83a1-acca9c73383f.png">

I made some improvements, it looks better. @russdanner Can you check it and let me know please. Also I attached a video.

https://www.useloom.com/share/e2d12db1193c4fd8b7758910c5f2a7b3

**Comment by russdanner** [comment]
It does look MUCH better.  It also still wobbles slightly :)
I think it's closable for now.  This UI may change as we evolve the level of detail shown. 

Verified.
