### ISSUE TITLE
[studio-ui] CMIS data source requires basic auth to preview image or video

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1241]
# issue
Once an image/video is selected from the browse dialog the user is prompted for basic auth.  
If the user enters username and password things work.  If they don't then the whole selection is canceled. 

<img width="1350" alt="screen shot 2017-08-21 at 12 07 05 pm" src="https://user-images.githubusercontent.com/169432/29528309-97283b9a-8669-11e7-861f-200b582bfe68.png">

if user cancels:
<img width="797" alt="screen shot 2017-08-21 at 12 07 12 pm" src="https://user-images.githubusercontent.com/169432/29528329-a5e29ba8-8669-11e7-8263-644613b5cbb0.png">

# Explanation of issue and fix
https://www.useloom.com/share/bef3c3ab178e45ca9b5a94021af359c5

# to fix
Data sources can build preview URLs and can exchange them at save time with the real value.  A preview URL should be provided that is already authenticated (using config) and can download the asset.

**Comment by sumerjabri** [comment]
@russdanner I don't really agree with this. Let's discuss this issue in person and decide what to do.
