### ISSUE TITLE
[Backup&Restore Process - Improvement] The restore process get stuck and wait for a locked table (./ibdata1) when the restore process is executed and the crafter studio server is up (crafter-authoring-env)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1242]
**Note**
===============
This can be adapted as a new feature or improvement to stop out the restore process when the process detects that the server is UP

**Preconditions**
===============
1) Studio authoring environment should be Up all the execution of this issue
 
**Steps to reproduce:**
===============
1. On your local crafter studio create a new site with Website_editorial BP
2. Go to the folder craftercms/crafter-authoring-env/bin on command line with the next command:
**cd craftercms/crafter-authoring-env/bin**
3. Execute the backup process with the next command:  **./crafter.sh backup yourbackupfile** 
[with authoring-environment Up]
4. Go back to the folder **craftercms/crafter-authoring-env** with the next command:
**cd ..**
5. Find your yourbackupfile.zip file created on step3 and go back to the bin folder **cd bin**
6. Executing the restore process with the command: **./crafter.sh restore craftercms/crafter-auth-env/yourbackupfile2017-08-21-07-32-12.zip**

**Current behavior**
==============
b)  Apparently, the restore process ends with success but it is not because the locked table (See attached file)
a) The restore process get stuck and with for a the locked table ./ibdata1, this because the locked table is already used by the started authoring server (see attached file)
[Crafter-Restore_Error-Trace.txt](https://github.com/craftercms/craftercms/files/1240065/Crafter-Restore_Error-Trace.txt)

**Expected Behavior**
=============
The restore process should fails (and end) and it should indicates that the process can't continue because the server is Up and the table is locked by server

**Comment by sumerjabri** [comment]
@jdrossl Please don't allow restore into a live server. Error out and inform the user that the system can't be restore while it's running.

**Comment by luishernandezmonge** [comment]
Tested scenario: Try to restore into a live server.
Result: Restore process does not allow to restore into a live server.

_Luis-Hernandez:bin luishernandez$ ./crafter.sh restore /Users/luishernandez/Crafter_Project/Crafter_Studio/craftercms/crafter-auth-env/mybackuptest04092017.2017-09-04-07-44-56.zip
Please stop the system before starting the restore process._

**Tested and Verified**
