### ISSUE TITLE
[Backup&Restore Process - Enhancement] Maybe the backup files can be placed on a backups folder on /crafter-authoring(or delivery)-server to get more clear the server structure

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1243]
**Steps to reproduce:**
===============
1. On your local crafter studio create a new site with Website_editorial BP
2. Go to the folder craftercms/crafter-authoring-env/bin on command line with the next command:
**cd craftercms/crafter-authoring-env/bin**
3. Execute the backup process with the next command:  **./crafter.sh backup yourbackupfile** 
[with authoring-environment Up]
4. Go back to the folder **craftercms/crafter-authoring-env** with the next command:
**cd ..**
5. Find your yourbackupfile.zip file created on step3 

**Proposed behavior**
==============
Maybe the backup files can be placed on a backups folder on /crafter-authoring(or delivery)-server, that because you can find it and let more clear the root folder of the crafter environment

**Comment by luishernandezmonge** [comment]
Currently, the backup file is generated on crafter-authoring(delivery)/backups folder but we found the next bug related: https://github.com/craftercms/craftercms/issues/1332. I will test again after resolve 1332

**Comment by luishernandezmonge** [comment]
Currently. I'm not able to verify this because of https://github.com/craftercms/craftercms/issues/685
Also, the backup process is blocked on the next line: **Adding ./backup/mongodb.zip** and after that... nothing happens

**Comment by jdrossl** [comment]
@luishernandezmonge backup/restore feature is fully functional now, please verify

**Comment by luishernandezmonge** [comment]
Currently, it is generating the backup.zip file into the root folder or the environment, e.g: crafter-authoring/

**Comment by juacamar** [comment]
Bu
