### ISSUE TITLE
[studio-ui] Edited/Added Pages, Components and Documents does not show up in the Recent Activity widget when filtered for each item

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1244]
Edited/Added Pages, Components and Documents  does not show up in the **My Recent Activity**
 widget when filtered for each item.

1. Using the Website_editorial bp, edit/add some pages, components, documents.  Go to the dashboard and set the filter for the **My Recent Activity** widget to **All**.  Notice all the items listed in the image below:

<img width="1031" alt="screen shot 2017-08-21 at 11 03 10 pm" src="https://user-images.githubusercontent.com/25483966/29546984-757b4724-86c5-11e7-90a5-8c4d0783762d.png">

2. Set the filter to **Pages**, notice that nothing is listed in the **My Recent Activity** widget

<img width="1037" alt="screen shot 2017-08-21 at 11 09 58 pm" src="https://user-images.githubusercontent.com/25483966/29547885-edd64a66-86ca-11e7-8745-c6d3f668ca88.png">

3. Set the filter to **Components**, notice again that nothing is listed in the **My Recent Activity** widget

<img width="1025" alt="screen shot 2017-08-21 at 11 13 18 pm" src="https://user-images.githubusercontent.com/25483966/29547444-fc688376-86c7-11e7-865b-c2d83372d8b8.png">

4. Set the filter to **Documents**, notice again that nothing is listed in the **My Recent Activity** widget

<img width="1021" alt="screen shot 2017-08-21 at 11 37 49 pm" src="https://user-images.githubusercontent.com/25483966/29547754-052df8c2-86ca-11e7-9b3f-6c7c516e653c.png">

**Comment by dejan-brkic** [comment]
Done

UI:
https://github.com/craftercms/studio2-ui/pull/556
Studio:
https://github.com/craftercms/studio/pull/842

**Comment by alhambrav** [comment]
Verified.
