### ISSUE TITLE
[craftercms] Create an init-site script for Windows in the delivery environment

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1245]
In the `crafter-delivery-env/bin/` folder, We have an `init-site.sh` script, but no `init-site.bat` script for Windows users.

**Comment by cortiz** [comment]
https://github.com/craftercms/craftercms/pull/1257

**Comment by sumerjabri** [comment]
@alhambrav please document

**Comment by alhambrav** [comment]
Documentation located here: http://docs.craftercms.org/en/3.0/site-administrators/setup-site-for-delivery.html

**Comment by alhambrav** [comment]
Verified.
