### ISSUE TITLE
[studio] Rename parent page and publish child doesn't publish parent

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1248]
Steps to Reproduce
===============
* Create a site
* Create a page `1`
* Create a child page `2`
* Create a child of that page called `3`
* Rename `1` to be `11`
* Publish `3`

Note how `2` and `11` are not published.

**Comment by dejan-brkic** [comment]
Can not reproduce with steps described above.
However i can reproduce issue with additional step of publishing all pages after creating and before renaming.
@sumerjabri Can you please confirm that modified steps are causing the issue and that we want to fix it ?

**Comment by sumerjabri** [comment]
@dejan-brkic yes, please add that step and fix

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/854
