### ISSUE TITLE
[studio-ui] new items still use * on dashboard but should not

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1249]
plus icon is the new way we show that an object has never been published.
Dashboard elements still show a * (see image.)  This should behavior should be removed from all dashboard widgets.

<img width="499" alt="screen shot 2017-08-22 at 11 46 53 pm" src="https://user-images.githubusercontent.com/169432/29598049-72ccc32a-8794-11e7-82b3-e1b994a2eb53.png">

**Comment by sumerjabri** [comment]
Now that we have the + on the icon, we don't need the *

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/562

**Comment by russdanner** [comment]
Verified
