### ISSUE TITLE
[studio] "Document" filter in the dashboard should display items based on a configured list of mime types

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1250]
It would be nice to have a config file where we can specify which mime types are considered "documents", so that in the dashboard, when the filter is set to **Documents**, it will list items matching the mime types specified in the config file.

To see how the **Documents** filter works in our current app,
using any of the blueprints, edit some pages, components and upload some zips or docx files.
Open your dashboard, then in the **My Recent Activity** widget, set the filter to **All**.  Notice all the items listed in the widget.

Next, set the filter to **Documents**, notice that there are no items listed in the widget.  In the current app, only items under `/site/documents` will be listed when the filter is set to **Documents**.  (I was expecting the docx or pdf to be listed, but I guess, how do you define what is a document in our current app?)

<img width="1021" alt="screen shot 2017-08-21 at 11 37 49 pm" src="https://user-images.githubusercontent.com/25483966/29619160-519c00ea-87e8-11e7-904a-4ec6d7aeaa2e.png">

So, it would be nice if when in the dashboard, and the filter is set to **Documents**, it will display items defined as documents from a configuration file.

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss design.

**Comment by sumerjabri** [comment]
Can be part of dashboard refactor.

**Comment by sumerjabri** [comment]
No longer an issue with the new dashboards.
