### ISSUE TITLE
org.springframework.dao.DuplicateKeyException is thrown when the user performs (copy folder/change template to section defaults for existing page on folder/delete folder/copy folder again/change template to section defaults again)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1251]
**Preconditions**
===============
1) Should create a site with Website_Editorial BP

**Steps to reproduce:**
===============

1. Go to the Site Dropdown of the site created previously (preconditions)
2. Create a Folder under Pages/Home tree (name: **mytest**)
3. Create a child folder under folder above (name: **big-tree1**)
4. Copy the next pages of the **Home** root folder (and paste those into the **big-tree1**):
Style
Health
Entertainment
5. Publish all on **big-tree1** folder
6. Copy **big-tree1** folder (leave selected all the content)
7. Right click in the **Home** and select paste
8. Go to **big-tree1** just created folder (of Home)
9. Select any of the pages into it (e.g: Style) and right click
10. Select **Change Template**
11. Click on **Yes** of the Change Template Warning
12. Select **Section Defaults** and click on **ok**
13. Leave as default all in the form, and click on **save and close**
14. Notice that the select page of step 9 is not in the folder and there is not an **Section defaults** item
15. Review the log (/tomcat/catalina.out)
16. Delete the folder of step 8
17. Repeat steps: 6, 7 and 8
18. Wait for processing on selected page of step 9 (if there is processing icon on the page)

Note: if that page doesn’t stop processing them delete the folder of step 8 and repeat steps 6, 7 and 8 (watch the attached video)

19. Repeat steps 9, 10, 11, 12, 13 and  14
20. Review the log again

**Current behavior**
==============
Step 14): the select page of step 9 is not in the folder and there is not an **Section defaults** item

Step 15): the next Error is displayed on the log:
_[ERROR] 2017-08-23 10:18:38,520 [http-nio-8080-exec-8] [content.ContentServiceImpl] | Error while executing write and rename for site {} path {} targetPath {} fileName {} content type {}
java.lang.NullPointerException_

Step 20) the next Error is displayed on the log (see attached file for more detail):
_ERROR] 2017-08-23 10:19:30,996 [http-nio-8080-exec-1] [content.DmContentLifeCycleServiceImpl] | No script found at /config/studio/content-types/page/controller.groovy, contentType: page
[ERROR] 2017-08-23 10:19:30,997 [http-nio-8080-exec-1] [content.ContentServiceImpl] | Error while executing write and rename for site {} path {} targetPath {} fileName {} content type {}
org.springframework.dao.DuplicateKeyException: Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:11) Duplicate entry 'test-/site/website/bit-tree1/entertainment/entertainment/index.x' for key 'uq_is_site_path'_

[catalinaout_logerrortrace.txt](https://github.com/craftercms/craftercms/files/1246303/catalinaout_logerrortrace.txt)

Watch the next video: https://www.useloom.com/share/26010be005824776a42113f9462be9ff

**Expected Behavior**
=============
Step 12: studio should not allow user to change template form Page to Component (Section Defaults).
And if it allows it, the just changed items should appears on the correct folder and no errors should be displayed on the log

**Comment by sumerjabri** [comment]
@dejan-brkic we can discuss if needed.

**Comment by dejan-brkic** [comment]
@sumerjabri can we discuss this issue ?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/850

**Comment by luishernandezmonge** [comment]
Testing the scenario:
Currently, no options are displayed when user clicks on change template for Category-Landing Pages of the steps 9,10,11&12. is it the expected on this?

**Comment by sumerjabri** [comment]
@luishernandezmonge The expected behavior is this:
* Users can only change from one type to another compatible type:
** Compatible type means: Page - Page, Component - Component, Section Defaults - Section Defaults

**Comment by luishernandezmonge** [comment]
Ok, according with above... this bug is test&validated
I Will close this
