### ISSUE TITLE
[craftercms] Add craftercms-test-suite to the craftercms bundle

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1253]
Please add https://github.com/craftercms/craftercms-test-suite to the core bundle and allow testing.

`gradle init` should pull this repo along with others.
`gradle test` should check if started, if not, error out and ask the user to `start` first (I'm open to suggestions here) -- this should also tell the user where the test reports are

**Comment by cortiz** [comment]
Partially  fix on #1287 need to talk with @luishernandezmonge to make sure all is ok

**Comment by luishernandezmonge** [comment]
Related to this, I opened the next ticket https://github.com/craftercms/craftercms/issues/1329

**Comment by sumerjabri** [comment]
This is done, we just need to continue fixing/automating.
