### ISSUE TITLE
[Studio - UI] Error link is displayed instead of the left rail component (on the pages) when the all the widgets are removed from the left rail component

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1255]
**Preconditions**
===============
Should create a site with Website_Editorial BP

**Steps to reproduce:**
===============
1.Go to the Site Dropdown of the site created previously (preconditions)
2.Click on the Home Page
3. Expand the Left Panel by clicking on the hamburger menu (on preview)
4. Go to **Components**  section on the site drop down and and expand the **components** three
5. Expand **left-rails** folder and right click -  edit in the **Left Rail with Latest Articles**
      Note: this applies for left rail components used by Pages
6. Remove all the widgets in the node selector field named **Widgets**
7. Click on Save and Close
8. Click on the Home Page
9. Expand the Left Panel by clicking on the hamburger menu (on preview)
10. Review the catalina.out log on tomcat folder
11. Review the section after **Menu**

**Current behavior**
===============
10. Next Error is displayed on the log (see attached file):
_ERROR] 2017-08-24 09:50:44,586 [http-nio-8080-exec-2] [mysite] [freemarker.runtime] | Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> contentModel.widgets.item  [in template "templates/web/components/left-rail.ftl" at line 30, column 12]_

[Catalinaout.errortrace.txt](https://github.com/craftercms/craftercms/files/1249562/Catalinaout.errortrace.txt)

11. Error link(with the error trace when click on it) is displayed instead of the left rail component 
Watch the next video: https://www.useloom.com/share/3c3a2a5d0f554223bd8a8fcd65f4d093

 **Expected Behavior**
===============
 Studio shouldn’t allow to removes all the widgets of the left rail, and also it should not allow to save and close changes

**Comment by alhambrav** [comment]
Studio will allow user to remove all widgets, in case they didn't have any widgets at all.  Added check to only render widgets when it's not empty, if empty, only the nav will be on the left-rail, which should take care of the error message noted in the ticket.

PR https://github.com/craftercms/studio/pull/848

**Comment by luishernandezmonge** [comment]
Tested and Validated
