### ISSUE TITLE
[Studio - UI] Featured Articles section on Homepage shouldn’t have enabled the “In Contextual Edit” option because currently the Edition Form does not displays elements or fields [Website_Editorial BP]

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1256]
**Preconditions**
===============
Should create a site with Website_Editorial BP

**Steps to reproduce:**
===============
1.Go to the Site Dropdown of the site created previously (preconditions)
2.Click on the Home Page
3.Activate the **In Context Edit** option
4.Find the **Featured Articles** and click on the pencil icon on preview of page
5.Review the Edit Form displayed

**Current behavior**
===============
5. Currently the Edition Form does not displays elements or fields, because it is a list of articles of the **Articles** folder below it

Watch the next video: https://www.useloom.com/share/86d51e00e3ce460bb082429c161c655c 

 **Expected Behavior**
===============
 Homepage shouldn’t have enabled the “In Contextual Edit” option

**Comment by sumerjabri** [comment]
Please fix to fully support ICE

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/848

**Comment by luishernandezmonge** [comment]
Currently, this part of the page does not have the "In-Contextual Edit" option (pencil)  for it
