### ISSUE TITLE
[studio-ui] Content type not being saved

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1258]
Steps to reproduce, using Editorial BP:

1. Create a component content type called Test.
2. Add an input called test.
3. Save the content type, dialog appears warning about having no template, click save anyway.
4. Create another component content type called Test 2.
5. Add an input called test.
6. Save the content type, dialog appears warning about having no template, click save anyway.
7. Open another content type, then return to the content type called Test 2.

Observe the input added is no longer there, the content type doesn't seem to be saved. Test content type does appear to be saved, though.

**Comment by avasquez614** [comment]
I can save the content type if I sign out and sign back in, but if I save a content type with no template, and then try to save another content type with not template, the issue comes back. After that I can't save any content type without a template.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/565

**Comment by avasquez614** [comment]
Tested and verified
