### ISSUE TITLE
[studio-ui] Change template fails when changing template from page to section defaults

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1259]
Steps to reproduce:

1. Go to the Site Dropdown of the site created previously (preconditions)
2. Create a Folder under Pages/Home tree (name: mytest)
3. Create a child folder under folder above (name: big-tree1)
4. Copy the next pages of the Home root folder (and paste those into the big-tree1):
5. Style
6. Health
7. Entertainment
8. Publish all on big-tree1 folder
9. Copy big-tree1 folder (leave selected all the content)
10. Right click in the Home and select paste
11. Go to big-tree1 just created folder (of Home)
12. Select any of the pages into it (e.g: Style) and right click
13. Select Change Template
14. Click on Yes of the Change Template Warning
15. Select Section Defaults and click on ok
16. Leave as default all in the form, and click on save and close

In the logs there is a NPE stack trace or message:
"Failed to extract dependencies. Content not found for site: <my_site>, path: <my_path>" 

It is caused by invalid parameters sent by ui.
Example:
site = "craftercms1251"
oldContentPath = "/site/website/big-tree1/health/index.xml"
path = "/site/website/big-tree1/health/health.xml"
fileName = "index.xml"
contentType = "/component/level-descriptor"
createFolders = "true"
edit = null
unlock = "true"
createFolder = true

Issue discovered with https://github.com/craftercms/craftercms/issues/1251 use case

**Comment by jvega-crafter** [comment]
Changing from one type to another is not valid, added proper validation to show only proper types.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/570

**Comment by dejan-brkic** [comment]
Verified
