### ISSUE TITLE
[studio-ui] "Video from CMIS Repo" datasource does not have the "Allowed Operations" property 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1260]
Please add the property "Allowed Operations", to the **Video from CMIS Repo** datasource.

If you look at the properties of the **Image from CMIS repository** datasource, notice that it has the property "Allowed Operations", that gives you the following options:
- Clone and Link
- Clone
- Link

![screen shot 2017-08-25 at 12 37 54 pm](https://user-images.githubusercontent.com/25483966/29723598-414b9064-8993-11e7-898d-73ac8ca58fdd.png)

Now, let's take a look at the datasource **Video from CMIS Repo**, notice that there is no "Allowed Operations" property.

![screen shot 2017-08-25 at 12 37 43 pm](https://user-images.githubusercontent.com/25483966/29723636-621a834a-8993-11e7-9dbb-77bf6521362d.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/567

**Comment by alhambrav** [comment]
Verified.
