### ISSUE TITLE
[studio-ui] Make the datasource naming consistent

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1261]
In our current app, the datasources names are not consistent.  Notice how some of them use capital letters or some of them does not spell out the whole word.  It would be nice if we have a consistent naming convention for datasources.

![screen shot 2017-08-25 at 2 55 55 pm](https://user-images.githubusercontent.com/25483966/29728348-869b758c-89a5-11e7-8c7c-7bbc3506b9ff.png)

Please change the following:

**From (Current names in Studio)**  -> **To (Requested names in Studio)**     
Image Uploaded from Desktop   -> Image Uploaded From Desktop       
Image from repository                  -> Image From Repository                    
Image from CMIS repository        -> Image From CMIS Repository          
File Uploaded from Desktop        -> File Uploaded From Desktop           
CMIS Repo                                    -> CMIS Repository                               
Video Uploaded from Desktop    -> Video Uploaded From Desktop        
Video from Repository                 -> Video From Repository                     
Video from CMIS Repo                 -> Video From CMIS Repository

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/568

**Comment by alhambrav** [comment]
Verified.
