### ISSUE TITLE
[craftercms] Windows Bundle: Authoring Env: MongoDB won't start

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1264]
When building the system on MS Windows Server 2012 R2:
* .\gradlew.bat start

The authoring env complains:
![windows-cant-find-mongodb-authoring](https://user-images.githubusercontent.com/3931908/29834871-184b3e0c-8cbe-11e7-86f6-909dd0dde427.png)

But the delivery works fine.

**Comment by cortiz** [comment]
#1287
