### ISSUE TITLE
[studio] make it easy to start jvm in debug mode

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1268]
# Studio and Engine debug scripts
debug.sh does not work - rather than start the server in debug, it stops the server

```
#!/usr/bin/env bash
CRAFTER_DEBUG_HOME=${CRAFTER_DEBUG_HOME:=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )}

if [[ -s  "$CRAFTER_DEBUG_HOME/crafter.sh" ]]; then
      $CRAFTER_DEBUG_HOME/crafter.sh stop
      exit 0
else
      echo -e "\033[38;5;196m"
      echo "crafter.sh was not found in $CRAFTER_DEBUG_HOME"
      echo -e "\033[0m"
      exit -1
fi

```
# Gradlew
Support debug option in gradlew

**Comment by sumerjabri** [comment]
@cortiz I think we want a flag `-Pdebug=true` for operation `start` to help us run in debug mode. Let me know if you want to discuss.

**Comment by cortiz** [comment]
@sumerjabri PR #1287 solve the original issue, I'll keep this open to remember to add the flag

**Comment by cortiz** [comment]
Flag added in #1377

**Comment by russdanner** [comment]
Confirmed.

Also, this work and should be documented:
`./gradlew start -Pdebug=true`
