### ISSUE TITLE
[studio] Recently Published widget displaying wrong items

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1276]
Steps to reproduce:

0. Create site from editorial BP
1. Go to the Site Dropdown of the site created previously (preconditions)
2. Create a Folder under Pages/Home tree (name: mytest)
3. Create a child folder under folder above (name: big-tree1)
4. Copy the next pages of the Home root folder (and paste those into the big-tree1):
         Style
         Health
         Entertainment
5. Publish previously copied Entertainment
Error -> Recently published widget shows all three newly copied items

**Comment by vestrada** [comment]
Hi @dejan-brkic 
It seems to be a back-end issue.
UI is sending just one item to go-live api. 
UI is getting 3 items from get-deployment-history api to create Recently Published dashboard.
Please see the below images.

<img width="1100" alt="screen shot 2017-08-31 at 4 29 22 pm" src="https://user-images.githubusercontent.com/11640613/29948117-662a810c-8e6a-11e7-9813-263916ef9b6e.png">

<img width="1324" alt="screen shot 2017-08-31 at 4 29 34 pm" src="https://user-images.githubusercontent.com/11640613/29948131-7901fda0-8e6a-11e7-84b1-a7707462cd75.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/851
