### ISSUE TITLE
[studio] Add an API to rename folder

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1277]
Please add an API to rename a folder per spec:

TBD (add spec)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/860

Docs:
https://github.com/craftercms/docs/pull/358

**Comment by sumerjabri** [comment]
API works, docs are correct.

I don't like the POST mechanics. I'll keep it open to discuss on Monday.

**Comment by sumerjabri** [comment]
Also, API is not in the index of APIs (not navigable)

**Comment by sumerjabri** [comment]
@dejan-brkic 

Also, please add the API to the index.rst of the parent folder.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/368
