### ISSUE TITLE
[commmons] Update Mongo driver to 3.5

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1278]
Current version of the Mongo Driver is 2.13. Update to 3.5 requires rework on init scripts.

**Comment by cortiz** [comment]
Need https://github.com/craftercms/commons/pull/101, https://github.com/craftercms/profile/pull/140
 https://github.com/craftercms/social/pull/320

Notes:
	Jongo does not fully support 3.x API of mongodriver
	so lots of warnings will be thrown for using deprecated
	api, this should be fix in Jongo 1.4

**Comment by avasquez614** [comment]
Verified
