### ISSUE TITLE
[studio] Show In-Progress Items is broken

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1282]
Steps to Reproduce
===============
* Create a site using Editorial BP
* Create an article `one` under the folder `/articles`
* Copy `articles/2016` and paste it under `one`
* Publish `articles/one/2016/12/top-books-for-young-women`
* Go to Dashboard
* Click on `Show "In-Progress Items`
* You see `Coffee is Good for Your Health` but not `New ACME Phone Released Today`

`New ACME Phone Released Today` needs to be in the dashboard as an `In-Progress Item`

Additional Steps
=============
* Edit `one` and rename it to `one-moved`
* Go to Dashboard
* You'll note that the `In-Progress Items` include `one-moved` and `Top Books for Young Women` only

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/853
