### ISSUE TITLE
[studio] Publishing fails due to a new type of conflict

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1283]
Per our conversation. Please find logs:
https://gist.github.com/sumerjabri/53123c52bdce6f49d2dff576f9cb97f8
https://gist.github.com/sumerjabri/10fa0214b5b1445cfe26f44e374a98ba

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/851
