### ISSUE TITLE
[studio-ui] Create content should check if content with same path existed

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1284]
Create content APIs should check if:
* Content existed with this name before
* That content that existed before has been either deleted or moved to a new name
* That content has not been published since the move/delete (meaning the delete or move operation that caused the name to become free has not been published)

If the above is true, content creation should fail and the return to the caller information to explain why that content creation cannot proceed until the move/delete operation that affects that name has been published first.

Let's discuss the API spec and implement it. We will also need to spec out the UI/UX of this.

The reason we're doing this is to avoid:
* Create content 1
* Publish 1
* Move content 1 to be 1-moved
* Create content 1
* Publish content 1
* Publish content 1-move <== this deletes 1 (which it shouldn't)

Many more complex scenarios exist that cause much worse outcomes all of which are rooted in allowing the user to create content using a name that has been moved or deleted but not published.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/863

**Comment by sumerjabri** [comment]
The error message currently is unclear. It says cannot create content contact system admin. It needs to explain why. For example: "Content cannot be created because this name/URL was in use by another content item that has been moved or deleted by not yet published."

Also, bigger issue, if you try to save and get the error, try again and it will work but put the content off the root folder!

Please ping me if you need more detail.

**Comment by sumerjabri** [comment]
@jvega-crafter Studio UI seems to reset the destination path on the second submit of content, therefore allowing the user to save. (See my second set of notes.)

Also, the error message needs to be adjust to what I noted in the second set of notes.

Please ping me if you need any guidance.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/642

**Comment by sumerjabri** [comment]
@jvega-crafter please update the error message to be:
```Content $URL, cannot be created because this name/URL was in use by another content item that has been moved or deleted by not yet published.```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/943
