### ISSUE TITLE
[studio-ui] Spinner/state doesn't work for dependencies

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1285]
When publishing items the spinner appears on the items indicating they're being published. However, this doesn't appear on items that are dependencies of other items.

Steps to Reproduce
===============
* Create a site using Editorial BP
* Create an article called `one` under `articles`
* Copy `articles/2017` and paste it under `articles/one`
* Publish the item `articles/one/2017/3/Top Clubs in Virginia`

Note the spinner on the article `Top Clubs in Virginia` but not on the parent `one`. Also note that `one` is indeed published correctly, but the UI doesn't reflect that.

**Comment by vestrada** [comment]
Pr: https://github.com/craftercms/studio-ui/pull/576

**Comment by sumerjabri** [comment]
Steps to Reproduce
===============
* Create a site
* Create a page `1`
* Create a child page `2`
* Create a child of that page called `3`
* Publish 3 <== note that all three have spinners and things look good
* Rename `1` to be `11`
* Publish `3` <== note that all three need publishing, and they all do publish (dependencies are correct), but he UI shows a spinner on 3 only! bug

**Comment by vestrada** [comment]
This is related to: https://github.com/craftercms/craftercms/issues/1433, which is a Back-end issue. I'm going to wait that fix to check above bug.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/651

**Comment by sumerjabri** [comment]
@jvega-crafter per our conversation. Please follow the second set of steps and note that the status doesn't update at all now.

**Comment by vestrada** [comment]
Now this is working good.
Ref: https://github.com/craftercms/craftercms/issues/1502

**Comment by sumerjabri** [comment]
Steps to Reproduce
===============
* Create a site using Editorial BP
* Create an article called `one` under `articles`
* Copy `articles/2017` and paste it under `articles/one`
* Publish the item `articles/one/2017/3/Top Clubs in Virginia`

Note the spinner on the article `Top Clubs in Virginia` but not on the parent `one`. Also note that `one` is indeed published correctly, but the UI doesn't reflect that.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/678
