### ISSUE TITLE
[studio-ui] Show Items In-Progress has shifted listings

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1286]
Items listed in the Dashboard: Items Waiting for Approval with Show In-Progress Items shows items shifted to the right. Please see below:

![items-waiting-shifted](https://user-images.githubusercontent.com/3931908/29991984-16222a98-8f5f-11e7-8e48-fbfaa8512780.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/575
