### ISSUE TITLE
[studio-ui] The change template warning popup is displayed with a non-correct size

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1290]
**Preconditions**
==============
Should create a site with Website_Editorial BP

**Steps to reproduce:**
==============

1. Go to the Site Dropdown of the site created previously (preconditions)
2. Create a Folder under Pages/Home tree (name: mytest)
3. Create a child folder under folder above (name: big-tree1)
4. Copy the next pages of the Home root folder (and paste those into the big-tree1):
-Style
-Health
-Entertainment
8. Publish all on big-tree1 folder
9. Copy big-tree1 folder (leave selected all the content)
10. Right click in the Home and select paste
11. Go to big-tree1 just created folder (of Home)
12. Select any of the pages into it (e.g: Style) and right click
13. Select Change Template
14. Click on Yes of the Change Template Warning
15. Click on Cancel
16. Repeat steps 9, 10, 11, 12, 13 and 14

**Current behavior**
==============
Watch the next video: https://www.useloom.com/share/f1b872997f85474c91f6251efdc0ff68

**Expected Behavior**
==============
Step 16: The change template warning pop-up size should be adjusted every time

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/574

**Comment by luishernandezmonge** [comment]
Verified as Resolved
