### ISSUE TITLE
[studio] Improve CMIS data source error message when cannot connect

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1300]
# Messages as is today:
Wrong username / password gives the user the following.

> Internal server error: org.apache.chemistry.opencmis.commons.exceptions.CmisUnauthorizedException: Unauthorized

Wrong hostnames/ports/urls 

> Internal server error: org.apache.chemistry.opencmis.commons.exceptions.CmisConnectionException: Cannot access "http://localhost:6060/alfresco/api/-default-/public/cmis/versions/1.1/atom/": Connection refused

Path is not found
> Internal server error: org.apache.chemistry.opencmis.commons.exceptions.CmisObjectNotFoundException: Object not found: /sites/digital-assets/approved

# Updates / Improvements
Provide the user with the ID of the repo config and a basic description of the issue without the exception class.  Specifically for connection related messages, do not expose the server/host details to the user.

## Example Exception

> CmisUnauthorizedException: "USE THIS MESSAGE"

## Example error message to user based on Example Exception^

> There was an error while connecting to 'CMIS_REPO_ID_HERE'
>  USE THIS MESSAGE
>

**Comment by sumerjabri** [comment]
Please see updated spec:
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/list.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/search.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/clone.html

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/859

**Comment by russdanner** [comment]
Error message to user still includes Exception and HOST details:

Example:
`Invalid CMIS parameter(s). Invalid CMIS data source configuration (hostname, port number, etc.), please contact your site administrator. org.apache.chemistry.opencmis.commons.exceptions.CmisConnectionException: Cannot access "http://localhost:5060/alfresco/api/-default-/public/cmis/versions/1.1/atom/": Connection refused

`

Remove exception detail `org.apache.chemistry.opencmis.commons.exceptions.CmisConnectionException: Cannot access "http://localhost:5060/alfresco/api/-default-/public/cmis/versions/1.1/atom/": Connection refused` from dialog

**Comment by jvega-crafter** [comment]
Per discussion with @sumerjabri , the error message will be displayed in user selected language, and a "Show More" link will display full server response

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/610

**Comment by russdanner** [comment]
* Update link styles and 
* Use glyph for the expand collapse  + / - may work well instead of the  ascii > and < chars
https://www.useloom.com/share/ceebeed11ae643c5a41c48caf2261acf

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/627

**Comment by russdanner** [comment]
VERIFIED
