### ISSUE TITLE
[studio-ui] Make save/cancel in content type editor consistent style with the rest of the app

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1301]
# Current style
<img width="940" alt="screen shot 2017-09-05 at 1 42 20 pm" src="https://user-images.githubusercontent.com/169432/30074614-2ee56f34-9240-11e7-8aa2-e1427da412ef.png">

# Make consistent with the style used by the form engine and the rest of studio
<img width="1035" alt="screen shot 2017-09-05 at 1 43 43 pm" src="https://user-images.githubusercontent.com/169432/30074678-5e3baad2-9240-11e7-8793-0aafe11a0826.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/593

**Comment by russdanner** [comment]
VERIFIED
