### ISSUE TITLE
[studio-ui] Move save button on config editor to bottom of the screen to 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1302]
# Current UI
<img width="846" alt="screen shot 2017-09-05 at 1 43 35 pm" src="https://user-images.githubusercontent.com/169432/30074732-92fe3ffa-9240-11e7-93fc-d114da9d7939.png">

# Update/improvement
Save button should be moved to the bottom of the screen inside a bar to be consistent with the rest of Studio.  Style this the same way the form engine styles the save/cancel bar at the bottom of a form.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/600

**Comment by russdanner** [comment]
Please put view Sample button back at the top.  

The bar at the bottom should be reserved for COMMAND/COMPLETION style operations (Cancel, Save, etc)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/606

I moved view Sample button back at the top and added cancel btn.

**Comment by russdanner** [comment]
Verified
