### ISSUE TITLE
[studio-ui] Image and video data source should show the image in browse and search

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1303]
https://www.useloom.com/share/5030cba5285b48f3ad25b3f382682df5

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/583

**Comment by vestrada** [comment]
Now you should see the images and videos in browse and search for general browse and CMIS browse.
In the above video you mentioned a small bug in the left tree. I can't reproduce it. Please check it and if you see it again please create a separate ticket.

Thanks, Vero

**Comment by russdanner** [comment]
Verified
