### ISSUE TITLE
[studio-ui] clicking on the current folder (plus) in CMIS browse removes results

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1304]
# steps to reproduce
1. configure afresco data source/image picker
2. open and see available images
3. click on current folder, items disappear

# video of issue
video contains comments about image previews (separate concern) but also shows configuration and the bug
https://www.useloom.com/share/5030cba5285b48f3ad25b3f382682df5

# notes
Returned JSON for AJAX, no errors in console of the browser.
If you "reload" the browser iframe results show up again
`{"items":[{"item_id":"5fdfb555-2369-4c56-8f22-719535c9565b","item_name":"becoins.jpeg","item_path":"/Sites/digital-assets/documentLibrary/approved/becoins.jpeg","mime_type":"image/jpeg","size":5728},{"item_id":"6bcae536-a7e8-4f95-af6e-4176eeecde51","item_name":"bvsc.png","item_path":"/Sites/digital-assets/documentLibrary/approved/bvsc.png","mime_type":"image/png","size":3302},{"item_id":"d91d2f14-be46-4c2e-a9c2-6f2cb8a21806","item_name":"bcoingraph.jpeg","item_path":"/Sites/digital-assets/documentLibrary/approved/bcoingraph.jpeg","mime_type":"image/jpeg","size":10929},{"item_id":"484f53a1-ab17-454d-810f-ca4f07729d0b","item_name":"chipcoin.jpeg","item_path":"/Sites/digital-assets/documentLibrary/approved/chipcoin.jpeg","mime_type":"image/jpeg","size":15657},{"item_id":"c9d19f8b-f247-41f5-8e6c-9f6728d0f089","item_name":"bcoins.jpeg","item_path":"/Sites/digital-assets/documentLibrary/approved/bcoins.jpeg","mime_type":"image/jpeg","size":23791}],"total":5}`

**Comment by russdanner** [comment]
Addition video of behavior

https://www.useloom.com/share/1fdf669f4a6449819d4960fcf7553ddb

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/571

**Comment by russdanner** [comment]
VERIFIED
