### ISSUE TITLE
[studio-ui] Replacing images in the home page or articles does not work in Windows OS/Edge browser

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1306]
Using the Website_editorial bp in Windows OS and using Edge as your browser, edit the home page.
In the hero image section, click on **Replace** -> **Existing Images**

![screen shot 2017-09-05 at 1 33 42 pm](https://user-images.githubusercontent.com/25483966/30074267-ecbe02f2-923e-11e7-9186-69a904f2a994.png)

Pick one of the images presented, for my example, click on **Add & Close** for the `castle-pic.jpg`

![screen shot 2017-09-05 at 1 35 02 pm](https://user-images.githubusercontent.com/25483966/30074350-411e20a2-923f-11e7-9074-d0cc6cdb8dc3.png)

Notice that the hero image is not replaced:

![screen shot 2017-09-05 at 1 36 50 pm](https://user-images.githubusercontent.com/25483966/30074392-63ce52de-923f-11e7-81c3-eddd45bee848.png)

Also, if you click on the radio button, then click on **Add Selection**, it also does not replace the hero image.

**Comment by sumerjabri** [comment]
@jvega-crafter per our conversation, please warn the user if they're using Edge + `localhost` with the warning:
```
Internet Explorer 11+ and Edge are known to have issues when your host name is "localhost".  Please consider using _Google Chrome (Linked)_ instead.
```

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/572

**Comment by sumerjabri** [comment]
@jvega-crafter update:
Please warn the user if they're not using Chrome/Firefox (effectively only supported browsers in 3.0.1) while we work on Edge.

The warning should read:
Crafter Studio currently supports Google Chrome and Mozilla Firefox browsers. Please use one of the supported browser to avoid possible compatibility issues. You can download Google Chrome from {link}.

The trigger for the message should be:
Browser detected not to be Chrome nor Firefox.

Please reach out with any questions.

**Comment by sumerjabri** [comment]
This ticket remains valid. We are now displaying a warning for non-Chrome/Firefox, but we still need to support Edge.

**Comment by alhambrav** [comment]
Verified that a warning message is displayed at the top of the page when using Edge as browser.

<img width="1027" alt="screen shot 2017-09-06 at 4 23 20 pm" src="https://user-images.githubusercontent.com/25483966/30132821-c45654c2-931f-11e7-8caa-7532ad73a8d7.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/717

**Comment by alhambrav** [comment]
Verified the hero image is now replaced using Edge browser in Windows.
