### ISSUE TITLE
[docs] Update `craftercms` README.md with better info on building branches

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1311]
Please update the README.md and related documentation http://docs.craftercms.org/en/3.0/developers/projects/craftercms/ to explain that while building a branch, using -Pcrafter.git.branch=v3.0.0 (example) you need to clone/re-init the codebase.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/350
PR https://github.com/craftercms/craftercms/pull/1324
