### ISSUE TITLE
[studio] CMIS repo service does not return an error when you ask for a listing with an invalid CMIS Repo ID

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1312]
# To reproduce 
Example request with invalid repo ID
> http://localhost:8080/studio/api/1/services/api/1/cmis/list.json?site_id=test&cmis_repo_id=I_DO_NOT_EXIST&path=/Sites/digital-assets/documentlibrary`

Response 200
> {"items":[],"total":0}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/855

**Comment by russdanner** [comment]
Verified
