### ISSUE TITLE
[studio-ui] CMIS browse tree UX should be consistent with and without trailing / in config

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1313]
# Without trailing / (correct)

<img width="1371" alt="screen shot 2017-09-06 at 12 28 53 pm" src="https://user-images.githubusercontent.com/169432/30123175-25276ce4-92ff-11e7-91f9-eb09dec00969.png">

# With trailing /  (incorrect)
<img width="1416" alt="screen shot 2017-09-06 at 12 23 38 pm" src="https://user-images.githubusercontent.com/169432/30123119-e140d0c4-92fe-11e7-9800-0d1fad948188.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/592

**Comment by russdanner** [comment]
Verified
