### ISSUE TITLE
[studio-ui] Improve context nav responsiveness 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1315]
Icons do not wrap in a friendly as the browser window's size decreases (or is smaller than full screen)

https://www.useloom.com/share/8d1b8550a46b4ff08acbf44bbdec3863

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/589

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/591

**Comment by russdanner** [comment]
Verified
