### ISSUE TITLE
[studio-ui] Pressing the <enter> key a second time after selecting the bp in the "Create Site" dialog does not press the "Create" button in Windows

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1317]
Using a Windows system, create a new site by clicking on **Create Site**
Type in a **Site Id**, then use the \<tab\> key to navigate to the next field.
When you're in the Blueprint field, use the \<down arrow\> key to select the bp you want to use.  After selecting the bp to be used, hit the \<enter\> key, which you expect to select the item for the dropdown box.  If you hit \<enter\> again, it does not press the **Create** button on the form as expected.  

To be able to press the **Create** button without using the mouse, you need to press the \<tab\> key to put the focus on the **Create** button, then hit the \<enter\> key.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/579

**Comment by alhambrav** [comment]
@jvega-crafter, it still does not seem to be working for me.  I used the windows 10 VM from Microsoft.  I tried getting a video of the behavior but it doesn't show the dropdown list appearing after pressing the \<enter\> key, 

<img width="1025" alt="screen shot 2017-09-09 at 12 58 34 am" src="https://user-images.githubusercontent.com/25483966/30237285-beb899ba-94fc-11e7-80bc-34a828162293.png">


then the dropdown closing after pressing the \<enter\> key again, 

<img width="1008" alt="screen shot 2017-09-09 at 12 58 57 am" src="https://user-images.githubusercontent.com/25483966/30237286-c9aab1c8-94fc-11e7-9d1a-fbf40d31fe9d.png">


and if you press the \<enter\> key again, it will just keep on going opening and closing the dropdown list if you keep on pressing the \<enter\> key, instead of of the **Create** button being pressed.

**Comment by alhambrav** [comment]
I see the same behavior in Ubuntu using a Chrome browser.

**Comment by jvega-crafter** [comment]
Hi @alhambrav The problem is that select input is a basic html control, and its render and behavior depends on the vendor, so it may change between browsers and even os. Catching events to make a consistent behavior may not work as expected on all of the browsers and could make the code messy.

**Comment by alhambrav** [comment]
Closed.
