### ISSUE TITLE
[studio-ui] In "Site Config -> Configuration", make the configuration file editor take up the whole space when switching to a different configuration 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1318]
In "Site Config -> Configuration", make the configuration file editor take up the whole space when switching to a different configuration .

Click on **Site Config** then **Configuration**
Select a configuration from the dropdown.  In my example, I will select **Site Configuration**

![screen shot 2017-09-07 at 2 25 58 pm](https://user-images.githubusercontent.com/25483966/30178875-89a6afc0-93d8-11e7-9847-bb001523b6ee.png)

Click on the **View Sample** button

![screen shot 2017-09-07 at 2 26 48 pm](https://user-images.githubusercontent.com/25483966/30178899-9c3b6964-93d8-11e7-9445-450f7f08b83d.png)

Now, select another configuration from the dropdown box.  I selected the **Sidebar Configuration**.  Notice the configuration file editor does not take up the whole space after switching the configuration file.

![screen shot 2017-09-07 at 2 30 56 pm](https://user-images.githubusercontent.com/25483966/30179090-30aadaee-93d9-11e7-97fa-aa6bad0f4d83.png)

Here's a short clip of the behavior described above:

https://www.useloom.com/share/f2363aa2344643e8862696b03033c26a

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/577

**Comment by alhambrav** [comment]
Verified fixed.
