### ISSUE TITLE
[studio-ui] Right click on wcm-root-folder or wcm-asset-folder in sidebar should not render 2 separators

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1319]
RIght click should not render the section with 2 sepatators next to eachother.
<img width="605" alt="screen shot 2017-09-07 at 11 29 35 am" src="https://user-images.githubusercontent.com/169432/30188058-6867b0b2-93fa-11e7-94db-bb9e670d2766.png">

# example reproduction
Login and right click as an author.  Without delete, you will see this bug.

**Comment by russdanner** [comment]
We want to make sure that regardless of the permission configuration this does not happen.  To the user, It looks like a bigger issue than it is.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/580

**Comment by russdanner** [comment]
Verified
