### ISSUE TITLE
[craftercms] Don't start MongoDB if the build doesn't include Profile/Social

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1321]

**Comment by cortiz** [comment]
SOLVE PR #1340

**Comment by sumerjabri** [comment]
@cortiz please add a flag:
```
-PstartMongodb=true/false
```
So we can override and force start mongodb if needed.

Please document in README.md for `craftercms`.

**Comment by cortiz** [comment]
Flag added in https://github.com/craftercms/craftercms/pull/1559
