### ISSUE TITLE
[studio-ui] Disable the "User Name" field in the "Edit User" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1323]
Disable the "User Name" field in the "Edit User" dialog, since you cannot change the **User Name**

![screen shot 2017-09-11 at 11 46 52 am](https://user-images.githubusercontent.com/25483966/30283800-21670c68-96e7-11e7-82c9-6e235acb80bc.png)

The current behavior right now is, you can edit it and click on the **Save** button, but there's no message in the dialogs or the tomcat logs on what happened.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/582

**Comment by alhambrav** [comment]
Verified fixed.
