### ISSUE TITLE
[studio-ui] User dialog display at top left of Studio is not consistent 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1327]
1. Login to Studio
2. Click on your user name at the top left corner of Studio.  Notice how the dialog looks like: 

![screen shot 2017-09-12 at 9 57 58 am](https://user-images.githubusercontent.com/25483966/30329853-8a291eb6-97a1-11e7-9597-5b1400e1f8d5.png)

3. Create or preview a site.
4. Click on your user name at the top left corner of Studio again.  Notice how the dialog looks like:

![screen shot 2017-09-12 at 9 57 06 am](https://user-images.githubusercontent.com/25483966/30329921-c06bfdf4-97a1-11e7-8f3b-d0b2263c9bd8.png)

The user name dialog immediately after logging in displays the user's name, in addition to the email address and the **Settings** and **Sign Out** options.  Once you start previewing a site or viewing a dashboard, the user name dialog does not include the user's name in the display anymore.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/584

**Comment by alhambrav** [comment]
Verified fixed.
