### ISSUE TITLE
[studio-ui] Change the notification message when changing passwords

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1328]
In our current system, the notification displayed after changing your password is: (Notification:: Profile Updated.)

![change-passwd-notification](https://user-images.githubusercontent.com/25483966/30331266-58cc2760-97a5-11e7-89a4-bbe58594c525.png)

It would be nice if the message displayed says something like: **Notification:: Password successfully changed** or something to that effect that reflects what was the action done instead of the current message being displayed as mentioned above.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/591

**Comment by alhambrav** [comment]
Verified fixed.
