### ISSUE TITLE
[craftercms] It's necessary to delete all the previously created data on authoring|delivery before run test-suite test cases in the bundle test process

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1329]
**Proposed Behavior**
=================
We need to find the way to delete all the data on the environment used to run the automated test cases of the test-suite framework, so here is the proposed flow when run **gradlew test**:

1. Backup the data of the environment
2. Delete all the data
3. Run the test-suite (automated test cases)
4. Restores all the data from 1 (backup file). 

**Reason**
================
1) When you run ./gradlew test, the data on the environment for previous test executions or users/sites data can provoke that the current tests (on execution) can FAILS
2) All automated test should be executed on a totally cleared environment

**Comment by sumerjabri** [comment]
@cortiz please have Gradle do this:
1. tell the user it's about to test, and therefore it must rename the `data` folder to `data.{YYYYMMDD}-{UUID}` and that it will move it back when done assuming it's not interrupted. Use the color RED.
2. pause for 5 seconds
3. `mv data data.{YYYYMMDD}-{UUID}`
4. run the test
5. ```mv data data.{YYYYMMDD}-{UUID}-test
mv data.{YYYYMMDD}-{UUID} data```
6. tell the user the test data is in mv data data.{YYYYMMDD}-{UUID}-test and they can remove it to save space

**Comment by cortiz** [comment]
@sumerjabri to have better cross OS compatibility I'll leave out the text been red (or I'll have to add a bunch of `if windows xxx else xxx` )
https://github.com/craftercms/craftercms/pull/1582

**Comment by luishernandezmonge** [comment]
Verified as implemented, currently it generates the older backup data, and after test those backed up files are returned to normal
