### ISSUE TITLE
[Backup&Restore Process -Bug] Backup process generates the backup file but returns an exception after write the file

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1332]
**Steps to reproduce:**
===================

1. On your local crafter studio create a new site with Website_editorial BP
2. Go to the folder craftercms/crafter-authoring-env/bin on command line with the next command:
3. cd craftercms/crafter-authoring-env/bin
4. Execute the backup process with the next command: ./crafter.sh backup yourbackupfile 
[with authoring-environment Up]
5. Check the results returned at the end of backup process

**Current Behavior**
===================
The next exception is displayed:
java.io.FileNotFoundException: _/Users/luishernandez/Crafter_Project/Crafter_Studio/craftercms/crafter-authoring/backups/yourbackupfile.2017-09-13-11-42-19.zip (Is a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.craftercms.bundle.utils.actions.Zip.execute(Zip.java:33)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)_

**Expected Behavior**
====================
The backup process should end without problems, also no exceptions should be returned

**Comment by luishernandezmonge** [comment]
Currently. I'm not able to verify this because of https://github.com/craftercms/craftercms/issues/685
Also, the backup process is blocked on the next line: **Adding ./backup/mongodb.zip** and after that... nothing happens

**Comment by jdrossl** [comment]
@luishernandezmonge backup/restore feature is fully functional now, please verify

**Comment by luishernandezmonge** [comment]
Tested and it works ok
