### ISSUE TITLE
Can't Create Site

### ISSUE THREAD

**Issue by jalilyacob** [craftercms/craftercms#1334]
Can't create site this error keep showing.
--------------------------------------------------------
Notification

Unable to create site. Please contact your system administrator.

Error: Internal server error: org.craftercms.studio.api.v1.exception.SearchUnreachableException: Error while creating site: samplesite ID: samplesite from blueprint: website_editorial. Is the Search running and configured correctly in Studio?

**Comment by jalilyacob** [comment]
I'm using Windows.

**Comment by cortiz** [comment]
Hi, when you are running, crafter do you have Solr and Crafter deployer running too ?, the `startup.bat` in the `bin` folder should open those for you (you need to keep them open too)

**Comment by sumerjabri** [comment]
@jalilyacob Please use our community support form to get help with this issue: https://groups.google.com/forum/#!forum/craftercms
Another option is to chat with us on IRC, we're on irc.freenode.net in channel #craftercms
