### ISSUE TITLE
[studio-ui] Forgot password mechanics are broken due to wrong method use

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1336]
Forgot password tries to validate the security token using a POST instead of GET method for `validate-token` method.

See the logs: https://gist.github.com/sumerjabri/465051bc19cd8d159c5dedcb0f4e29ab

See the spec: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/user-management/validate-token.html

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/588
