### ISSUE TITLE
[studio-ui] "Publish Date" and "Last Edit" date displays different time zones in the dashboard 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1337]
Using Website_editorial bp, change the time zone in your system. (I set the time zone to Pacific, for OSX, and Alaskan for the Windows 10 system)

Edit a page, then save it.
Next, publish the page.
Look at the dashboard.  Notice the **Publish Date** and **My Last Edit** date, it looks like the time zones used are different.

OSX
![screen shot 2017-09-18 at 8 12 45 am](https://user-images.githubusercontent.com/25483966/30549375-9bdd7740-9c62-11e7-9b4c-59a529e85b8c.png)

Windows 10
![screen shot 2017-09-18 at 8 04 33 am](https://user-images.githubusercontent.com/25483966/30549468-d74ead62-9c62-11e7-8108-b45b761713db.png)

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/864

Aligned dates from server to be sent in UTC. UI is displaying time in UTC and not local (user) time zone

**Comment by sumerjabri** [comment]
The UI must show time as specified by the site configuration time zone. That configuration is in Site Config > Configuration > Site Configuration |     <default-timezone>EST5EDT</default-timezone>

Please make sure that ALL times reported by the UI are reported as that timezone for the active site. Please remember the server will only store UTC time and only understand UTC time: This means that when you call APIs, you call them with UTC, and when you show time(s) you show in site's time zone.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/613

Dashboards are done. I will back to this ticket when high tickets are finished.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/646

**Comment by vestrada** [comment]
I fixed: dashboards, over on sidebar (tree), history screens, audit.
Publish dialog will be work on: https://github.com/craftercms/craftercms/issues/1439

**Comment by alhambrav** [comment]
Verified fixed.
