### ISSUE TITLE
[engine] Fix warning: [localhost-startStop-1] [resource.ResourceHttpRequestHandler] 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1339]
Start Crafter CMS and watch the tomcat log for the following warning:

```
[WARN] 2017-09-18 08:51:30,043 [localhost-startStop-1] [resource.ResourceHttpRequestHandler] | Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.
```

**Comment by jdrossl** [comment]
@sumerjabri Reviewing Spring [source code](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceHttpRequestHandler.java#L255), the warning will always be displayed if the locations list is empty, we could set a random value to avoid it but I'm not sure if that could cause any exceptions or bugs later. Its probably better to leave it as it is.

**Comment by sumerjabri** [comment]
Will keep as is, thanks!
