### ISSUE TITLE
[studio-ui] "Item Name" and icon in dashboard is not aligned correctly when the "Item Name" is long

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1341]
Some images with a long name is not displayed correctly in the dashboard.  The icon and **Item Name** seems to be mis-aligned.  

Upload an image with a very long name. (Try to use this name for the file if you have a hard time trying to reproduce: `Hidden_Valley_Bandstand_-2017_Volunteer_Org_Chart(3-13-17).jpg` 

Notice how it is displayed in the dashboard.

![screen shot 2017-09-18 at 1 41 53 pm](https://user-images.githubusercontent.com/25483966/30556035-78e7b056-9c77-11e7-8287-e06ddc8e6881.png)

Here's another sample of incorrectly aligned **Item Name**:
![screen shot 2017-09-18 at 2 05 51 pm](https://user-images.githubusercontent.com/25483966/30556954-b14921a2-9c7a-11e7-90d0-94783f7095a4.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/594

**Comment by alhambrav** [comment]
Verified fixed.
