### ISSUE TITLE
Crafter 3.0.x fails to start on OSX using the startup.sh script

### ISSUE THREAD

**Issue by gihyunlee** [craftercms/craftercms#1343]
OS:  OSX 10.12.6
Crafter Version: 3.0.1

I followed the Crafter 3.0.x Quick start guide linked below:

http://docs.craftercms.org/en/3.0/getting-started/quick-start-guide.html

I was unable to start up Crafter using the startup.sh script.  It complained about a missing openssl library (can not load libssl.1.0.0.dylib).

The root cause:
The crafter startup was looking for openssl to be installed in a location used by HomeBrew.

Expected:
Crafter startup should be able to start independent of how a supporting library is installed, or configuration options should be documented.

Workaround:
Uninstall openssl, installed by MacPorts
Install HomeBrew
Install openssl with homebrew.

After installing HomeBrew and reinstalling openssl, I was able to successfully start Crafter.  It would have been nice to have this documented.

**Comment by sumerjabri** [comment]
@alhambrav please update the documentation in the quick-start-guide to match the README.md in craftercms/craftercms to indicate the need for openssl install via `brew`.

See README.md here: https://github.com/craftercms/craftercms/blob/master/README.md step 1.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/359

**Comment by sumerjabri** [comment]
Updated: http://docs.craftercms.org/en/3.0/getting-started/quick-start-guide.html#os-x-extra-prerequisite
