### ISSUE TITLE
[docs] Document best practices on loading content via disk vs search index

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1351]
Please write an article explaining when to use the content directly from the search index (large lists), the potential pitfalls and when to directly load the content via APIs (get full content (all elements) with intact HTML blocks).

Please also note the overhead of loading from the search index if the path is known. Loading from the search index is slower. Also note that, if rendering search results, then it's the opposite: the search index might have enough for you to render without having to iterate over items and load them one by one (quite slow).

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/360
