### ISSUE TITLE
[studio-ui] There is no indication that the current password entered in the account management to change passwords is incorrect

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1352]
It would be nice to have an indication that the current password entered in the account management to change passwords is incorrect.

Click on the user name at the top right of Studio, then click on **Settings**

Change the password for the user.  In the **Current Password** field, enter a wrong password, then fill in the **New Password** and **Confirm Password** field.
Notice when the wrong **current password** is entered and then you click on the **Submit** button, there's no indication that something is wrong in the data entered by the user.

<img width="936" alt="screen shot 2017-09-19 at 4 34 37 pm" src="https://user-images.githubusercontent.com/25483966/30614237-b34ae268-9d58-11e7-9485-894dfe40f3a0.png">

If the new password entered and the confirm password entered does not match, it informs the user that the password does not match.

<img width="938" alt="screen shot 2017-09-19 at 4 31 14 pm" src="https://user-images.githubusercontent.com/25483966/30614097-48f53ae4-9d58-11e7-949a-43c7f73f5cab.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/596

**Comment by vestrada** [comment]
I already fixed the UI, It will show the error message from the server.
But the error message from the server only says: "Unauthorized"
I think error message should be more specific to inform the real error, for example that the **current password** does not match.

**Comment by sumerjabri** [comment]
@alhambrav We can't be too specific in the API from a security lens. Let's discuss.

**Comment by alhambrav** [comment]
Verified Unauthorized is displayed.

**Comment by yacdaniel** [comment]
This should be reopened for 3.1. 
In 3.1 we dont see an error message, and the `change-password` enpoint is returning 500 with this tomcat error log https://gist.github.com/yacdaniel/f575d5a3696e20c316a0b49af31bc067
![imagen](https://user-images.githubusercontent.com/6722074/60728446-8eba4f80-9efd-11e9-9725-7a227c8ae8dd.png)

In 3.0 we have a 401 response and an `Unauthorized` message.
![imagen](https://user-images.githubusercontent.com/6722074/60728674-21f38500-9efe-11e9-8da2-d23875179cdd.png)

**Comment by jvega190** [comment]
hi @dejan-brkic right now in 3.1 the service is returning a 500 error instead of the 401

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1661

**Comment by jvega190** [comment]
verified, @yacdaniel can you please verify/close the ticket? (if valid)

**Comment by yacdaniel** [comment]
Verified fixed.
