### ISSUE TITLE
[studio-ui] There is a typo in the notification message when updating the user profile from account management

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1355]
1. Click on the user name at the top right of Studio, then select **Settings**

![screen shot 2017-09-20 at 10 40 49 am](https://user-images.githubusercontent.com/25483966/30650177-438f994e-9df0-11e7-957f-87db031aa20e.png)

2. Click on the **Update Profile** button

Notice that there is a typo in the notification message when updating the user profile from the account management:

![screen shot 2017-09-20 at 10 34 28 am](https://user-images.githubusercontent.com/25483966/30649986-bff09e3a-9def-11e7-86cf-dfaab791d307.png)

It says **Nofitication** instead of **Notification**

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/598

**Comment by alhambrav** [comment]
Verified fixed.
