### ISSUE TITLE
[profile] ProfileServiceRestClient is unable to upload attachments

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1357]
When trying to upload an attachment to a profile using the rest client, the name of the file will be changed to use a temporary file and this causes an exception in the profile controller.

https://github.com/craftercms/profile/blob/master/client/src/main/java/org/craftercms/profile/services/impl/ProfileServiceRestClient.java#L510

Example

Filename: `avatar.png`
Temp filename: `59c27a3b3004ed9437f04006-avatar.png8392287295987522212attachment`

```
org.craftercms.profile.api.exceptions.ProfileException: File 59c27a3b3004ed9437f04006-avatar.png8392287295987522212attachment if of content Type application/octet-stream which is not allowed
    at org.craftercms.profile.services.impl.ProfileServiceImpl.getAttachmentContentType(ProfileServiceImpl.java:737) ~[classes/:3.0.2-SNAPSHOT]
    at org.craftercms.profile.services.impl.ProfileServiceImpl.addProfileAttachment(ProfileServiceImpl.java:686) ~[classes/:3.0.2-SNAPSHOT]
```

**Comment by avasquez614** [comment]
Tested and verified
