### ISSUE TITLE
[studio-ui] Some items in various dialogs are not translated when the language is changed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1361]
Some items in various dialogs are not translated when the language is changed.
Using the website_editorial bp, change the language by clicking on your user name at the top right of Studio, then select **Settings**
Under **Profile**, change the language from **English** to **Spanish**, then click on the **Update Profile** button.

Here are the dialogs containing items that may need translation:

**Account Management**
![screen shot 2017-09-20 at 10 42 44 am](https://user-images.githubusercontent.com/25483966/30650411-cc795204-9df0-11e7-8a22-5aede16ef674.png)

**My Sites**
![screen shot 2017-09-20 at 10 45 40 am](https://user-images.githubusercontent.com/25483966/30650477-fb34e0f4-9df0-11e7-8d80-f79e007c3a14.png)

**Dashboard Icon Guide**
![screen shot 2017-09-20 at 10 48 23 am](https://user-images.githubusercontent.com/25483966/30650729-af07d2b2-9df1-11e7-8283-a50ce072e913.png)

**About**
![screen shot 2017-09-20 at 10 52 32 am](https://user-images.githubusercontent.com/25483966/30650838-e9eda122-9df1-11e7-91f8-b641a4f77a76.png)

**Users**
![screen shot 2017-09-20 at 12 09 45 pm](https://user-images.githubusercontent.com/25483966/30654735-c6488f24-9dfc-11e7-940a-7151612ae53e.png)

**Create User**
![screen shot 2017-09-20 at 12 07 37 pm](https://user-images.githubusercontent.com/25483966/30654635-7a2b73d6-9dfc-11e7-90fb-1a0d2fac7827.png)

**Publish Status**
<img width="373" alt="screen shot 2017-09-20 at 4 12 16 pm" src="https://user-images.githubusercontent.com/25483966/30665374-c798e2a8-9e1e-11e7-82da-0531197f98be.png">

**Targeting**
<img width="728" alt="screen shot 2017-09-20 at 4 15 29 pm" src="https://user-images.githubusercontent.com/25483966/30665500-2c4741cc-9e1f-11e7-8cdb-de7ed9b92a03.png">

**Edit Form**
<img width="1131" alt="screen shot 2017-09-20 at 4 19 44 pm" src="https://user-images.githubusercontent.com/25483966/30665792-3a11eafe-9e20-11e7-91c0-3a1f7cb2fed9.png">

<img width="1069" alt="screen shot 2017-09-21 at 9 58 10 am" src="https://user-images.githubusercontent.com/25483966/30699739-8be3d0f2-9eb3-11e7-87b1-bcebb03689d1.png">

**History**
![screen shot 2017-09-21 at 10 02 41 am](https://user-images.githubusercontent.com/25483966/30699971-33da138e-9eb4-11e7-9767-871c1225de32.png)

**Dependencies**
<img width="1104" alt="screen shot 2017-09-21 at 10 05 12 am" src="https://user-images.githubusercontent.com/25483966/30700074-83d095e8-9eb4-11e7-98dc-c3717f580e1a.png">

**Create Group**
<img width="553" alt="screen shot 2017-09-21 at 10 56 50 am" src="https://user-images.githubusercontent.com/25483966/30702737-b90abb7e-9ebb-11e7-8563-f0b7926a6b58.png">

**Edit Group**
<img width="898" alt="screen shot 2017-09-21 at 10 58 35 am" src="https://user-images.githubusercontent.com/25483966/30702804-f0fc4cf0-9ebb-11e7-9b2e-02a2cafbc2fc.png">

**Audit Logs**
<img width="896" alt="screen shot 2017-09-21 at 10 59 54 am" src="https://user-images.githubusercontent.com/25483966/30702910-3bc940b2-9ebc-11e7-9665-6323dae4f35d.png">

**Bulk Operations**
<img width="901" alt="screen shot 2017-09-21 at 11 01 50 am" src="https://user-images.githubusercontent.com/25483966/30703000-7a0b3196-9ebc-11e7-9d37-c854f56a1edb.png">

**Create Controller**
<img width="353" alt="screen shot 2017-09-21 at 1 13 03 pm" src="https://user-images.githubusercontent.com/25483966/30709014-c3362710-9ece-11e7-8771-c3bb5ed93b7e.png">

**Create Template**
<img width="346" alt="screen shot 2017-09-21 at 1 15 57 pm" src="https://user-images.githubusercontent.com/25483966/30709128-239c217c-9ecf-11e7-86b3-a572063150dd.png">

**Context Nav - Users, Sites, Help (in Preview/Dashboard)**
<img width="1188" alt="screen shot 2017-09-21 at 1 17 18 pm" src="https://user-images.githubusercontent.com/25483966/30709228-8e8a2240-9ecf-11e7-8493-c9afe76730a5.png">

**Context Nav - Publishing Status, Preview Tools, In-Context Edit, Search (in Preview)**
<img width="1148" alt="screen shot 2017-09-21 at 1 21 08 pm" src="https://user-images.githubusercontent.com/25483966/30709333-da8ac6fe-9ecf-11e7-9eae-ca2a7bcfd2c6.png">

There may be some other items not translated, but the above are what I have found so far.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/602

**Comment by alhambrav** [comment]
**Users**
<img width="993" alt="screen shot 2017-09-25 at 1 41 51 pm" src="https://user-images.githubusercontent.com/25483966/30822725-bd25023e-a1f7-11e7-819d-ef52ed145ca6.png">

**Create Users**
<img width="554" alt="screen shot 2017-09-25 at 1 43 23 pm" src="https://user-images.githubusercontent.com/25483966/30822735-c3d864ae-a1f7-11e7-9ddd-ab7c10bbaa20.png">


**About Us**
<img width="996" alt="screen shot 2017-09-25 at 1 46 15 pm" src="https://user-images.githubusercontent.com/25483966/30822839-2b14911a-a1f8-11e7-8101-df966b6e4dfd.png">


**Create Controler**
(Go to the Sidebar, then expand the "Scripts" folder, right-click on any of the folder and select "Crear Controlador"
<img width="1126" alt="screen shot 2017-09-25 at 1 51 05 pm" src="https://user-images.githubusercontent.com/25483966/30823038-f60e6e2c-a1f8-11e7-80ee-0c5577fd8c6f.png">

**Create Template**
(Go to the Sidebar, then expand the "Plantillas" folder, right-click on any of the folder and select "Crear Plantilla"
<img width="1136" alt="screen shot 2017-09-25 at 1 54 22 pm" src="https://user-images.githubusercontent.com/25483966/30823175-57f5641a-a1f9-11e7-9f29-04698d7aa453.png">

**Context Nav - Dashboard**
Users, Sites, Help, Publish Status and Search is not translated when you hover on the icons
<img width="1139" alt="screen shot 2017-09-25 at 1 57 03 pm" src="https://user-images.githubusercontent.com/25483966/30823338-d9a39946-a1f9-11e7-9d4d-2be7b2ee715a.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/611

**Comment by alhambrav** [comment]
Verified fixed.
