### ISSUE TITLE
[studio-ui] Some texts are cut off when the language is Spanish

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1369]
**Preview Tools Panel**
<img width="1203" alt="screen shot 2017-09-21 at 9 54 40 am" src="https://user-images.githubusercontent.com/25483966/30699559-0efaa610-9eb3-11e7-92c7-6305617dc94d.png">

**Timeout Login Screen**
<img width="366" alt="screen shot 2017-09-21 at 1 07 51 pm" src="https://user-images.githubusercontent.com/25483966/30708815-1b661d1a-9ece-11e7-86f7-7591c754faa8.png">

These are the screens I've found so far, there may be some other screens that doesn't look great when the language is set to Spanish.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/659

**Comment by alhambrav** [comment]
Verified fixed.
