### ISSUE TITLE
[studio-ui] Remove minified CSS from source code

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1372]
Please switch to full. If you'd like to use minified, they must be generated during the build process.

For now, remove all minified CSS and switch to full.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/718

**Comment by sumerjabri** [comment]
I'm still seeing some (also some repetition):
./static-assets/components/cstudio-preview-tools/mods/annotate/dist/drawingboard.nocontrol.css
./static-assets/components/cstudio-preview-tools/mods/annotate/dist/drawingboard.nocontrol.min.css
./static-assets/components/cstudio-preview-tools/mods/annotate/css/drawingboard.nocontrol.css

./static-assets/components/cstudio-preview-tools/mods/annotate/dist/drawingboard.css
./static-assets/components/cstudio-preview-tools/mods/annotate/css/drawingboard.css
./static-assets/components/cstudio-preview-tools/mods/annotate/dist/drawingboard.min.css

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/732
