### ISSUE TITLE
[studio-ui] Move the time zone in the "Approve for Publish" dialog above the date time picker

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1374]
Swap the position of the time zone and the date time picker so that when the user is picking a date, the user can still see what time zone is the time they are picking.  Also, it would be nice to add a hint to the time zone, that the time zone can be changed through the Site Config -> Configuration -> Site Configuration

<img width="785" alt="screen shot 2017-09-25 at 10 00 12 am" src="https://user-images.githubusercontent.com/25483966/30812381-94b7c936-a1d8-11e7-8c88-fe576a2198c3.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/608

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by alhambrav** [comment]
Hi! Forgot to test using user **author**.  Please swap the position of the time zone and date time picker for user author.  

To reproduce, login as user **author**, edit a page and request publish to a later time (schedule).  Notice that the time zone is still below the date time picker:

<img width="1295" alt="screen shot 2017-10-10 at 11 18 56 am" src="https://user-images.githubusercontent.com/25483966/31395138-0a0de4aa-adae-11e7-932e-a197d6697ca3.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/634

**Comment by alhambrav** [comment]
Verified fixed.
