### ISSUE TITLE
[studio-ui] Dashboard is not displaying items correctly after an item has been edited or published

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1375]
Create a site using the website_editorial bp.
Edit the home page and save it.
go to the dashboard and look at the **My Recent Activity** widget.  Notice that it says there is 1 item, but it's not displaying the item:

<img width="1138" alt="screen shot 2017-09-25 at 2 01 29 pm" src="https://user-images.githubusercontent.com/25483966/30823511-64d47440-a1fa-11e7-97a9-71e81f7e8465.png">

Now, publish the changed you just made to the Home Page.
Go back to the dashboard and look at the **Recently Published** widget.  Notice that it is not displaying the Home Page as recently published:

<img width="1131" alt="screen shot 2017-09-25 at 2 06 18 pm" src="https://user-images.githubusercontent.com/25483966/30823740-3fed0254-a1fb-11e7-9a1d-11c09b09da58.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/607

**Comment by alhambrav** [comment]
Verified fixed.
