### ISSUE TITLE
[engine] Create CORS filter and configuration per site

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1376]
Each site should be able to configure the site CORS headers, 
the option should be as part of the site.xml configuration file 

```xml
<cors [enable=true|false]> <!-- This is preferred but if not make the tag enable, defaults false  -->
  <enable>true|false</enable>
<accessControlAllowOrigin>*</accessControlAllowOrigin><!-- or http(s)://host:port/, http://host2:port ... -->
<accessControlAllowMethods>POST, GET, PUT, DELETE</accessControlAllowMethods>
<accessControlMaxAge>3600</accessControlMaxAge><!-- Time in sec -->
<accessControlAllowCredentials>true|false</accessControlAllowCredentials>
```
Each site should have it's own CORS configuration.

You can use https://github.com/craftercms/commons/blob/master/utilities/src/main/java/org/craftercms/commons/web/CORSFilter.java 

(this is used in profile/social) as a reference implementation (or use that class and figure out how to added to the per-site request filter chain.

**Comment by sumerjabri** [comment]
@jdrossl this implementation needs to be backwards compatible

**Comment by jdrossl** [comment]
Sample configuration:
```
<cors enable="true">
    <accessControlMaxAge>3600</accessControlMaxAge>
    <accessControlAllowOrigin>*</accessControlAllowOrigin>
    <accessControlAllowMethods>GET\, POST\, PUT</accessControlAllowMethods>
    <accessControlAllowHeaders>Content-Type</accessControlAllowHeaders>
    <accessControlAllowCredentials>true</accessControlAllowCredentials>
</cors>
```

Commas need to be escaped to prevent splitting when extracting the values.

**Comment by cortiz** [comment]
@sumerjabri we might need to add that to the docs project and in headless BP

**Comment by sumerjabri** [comment]
Docs are updated, pending publishing.
Ticket to update the Headless BPs: https://github.com/craftercms/craftercms/issues/1390

**Comment by sumerjabri** [comment]
@cortiz close if things look good now.
