### ISSUE TITLE
[studio-ui] crafter-component.xml item is displayed on Home even if the hideInAuthoring=true is configured

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1378]
**Preconditions**
============
1) Create a site using any BP

**Steps**
===========
1) Go to the site of preconditions and click on preview
2) Expand Pages/Home structure
3) Review that the crafter-component.xml item is displayed
4) Review the configuration for crafter-component.xml in the repository folder on the server (for the site)

**Current behavior**
=============
3) The **crafter-component.xml** item is displayed
4)Currently, the configuration for the item above is:

**_<?xml version="1.0" encoding="UTF-8"?>
<page>
    <display-template xsi:nil="false">/templates/system/common/component.ftl</display-template>
    <merge-strategy>inherit-levels</merge-strategy>
    <hideInAuthoring>true</hideInAuthoring>
</page>_**

Watch the next video:
https://www.useloom.com/share/c1016c5c40b74991a4558ff6455e23d1

**Expected Behavior**
The item above (**crafter-component.xml**) should not be displayed

**Comment by jvega-crafter** [comment]
Could not reproduce, testing on clean installation

**Comment by luishernandezmonge** [comment]
Currently, I'm not able to reproduce this again, seems like on my environment is some old data that provoke that behavior, I deleted all the crafter-authoring contents (on the folder) and updating, building and deploying again the issue was resolved
