### ISSUE TITLE
[profile] NullPointerException from AbstractProfileRestClientBase.java

### ISSUE THREAD

**Issue by mcgitty** [craftercms/craftercms#1380]
In the `handleRestServiceException` method, the 2nd line inside the else block can cause a NPE, because `e.getErrorDetails()` may be null. This method also needs some cleanup. Here is a suggested version:

    protected void handleRestServiceException(RestServiceException e) throws ProfileException {
        HttpStatus responseStatus = e.getResponseStatus();
        Object detailsObj = e.getErrorDetails();
        if (detailsObj instanceof ErrorDetails) {
            ErrorDetails errorDetails = (ErrorDetails) detailsObj;
            ErrorCode errorCode = errorDetails.getErrorCode();
            String message = errorDetails.getMessage();

            throw new ProfileRestServiceException(responseStatus, errorCode, message);
        } else {
            String message = detailsObj != null ? detailsObj.toString() : e.getMessage();

            throw new ProfileRestServiceException(responseStatus, message);
        }
    }

**Comment by mcgitty** [comment]
Here is one NPE trace:

    java.lang.NullPointerException
	org.craftercms.profile.services.impl.AbstractProfileRestClientBase.handleRestServiceException(AbstractProfileRestClientBase.java:179)
	org.craftercms.profile.services.impl.AbstractProfileRestClientBase.doGetForObject(AbstractProfileRestClientBase.java:149)
	org.craftercms.profile.services.impl.TenantServiceRestClient.getAllTenants(TenantServiceRestClient.java:96)
	org.craftercms.security.utils.tenant.TenantUtils.getTenantNames(TenantUtils.java:31)
	org.craftercms.security.utils.tenant.AllTenantsResolver.getTenants(AllTenantsResolver.java:30)
	org.craftercms.security.processors.impl.LoginProcessor.processRequest(LoginProcessor.java:136)

**Comment by sumerjabri** [comment]
Completed
