### ISSUE TITLE
[studio-ui] top level folders in site-content menu should not show a hover state

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1381]
Applies to 2.5.x only

<img width="652" alt="screen shot 2017-09-27 at 2 11 21 pm" src="https://user-images.githubusercontent.com/169432/30930014-52b2e360-a38e-11e7-84f0-132e440315e1.png">

Behavior is inconsistent with dashboard and other aspects of UI

Do not show the underline when user mouses over the top level folder

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/612

**Comment by russdanner** [comment]
VERIFIED
