### ISSUE TITLE
[studio] Bulk go live - improve algorithm

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1382]
Bulk go live for large site is very slow and inefficient.
Queue by path and single large commit (import) is not efficient for large sites

@sumerjabri 
We need to discuss new design. Tested with ~8.5K files (not big in size) and it took long time to complete it. It was processing repo and publishing on the fly. since it was only one large commit. due to cherrypicking all files got deployed with first item in queue. So it was publishing everything many times while processing bulk go live request

**Comment by sumerjabri** [comment]
Per our conversation: select items where cid unique OR blank.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/877
