### ISSUE TITLE
[studio-ui] There is no tooltip for Static Assets, Templates and Scripts items

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1383]
Using the website_editorial blueprint, open the **Sidebar**
Navigate to the Static Assets folder and expand.
Hover your mouse on one of the content (e.g. image, font, or README.txt).  Notice that no tooltips appear.
Navigate to the Templates and Scripts folder, notice there too that when you hover on an item, there is no tooltip.

<img width="230" alt="screen shot 2017-09-27 at 2 49 07 pm" src="https://user-images.githubusercontent.com/25483966/30931628-38d1079c-a393-11e7-95c5-397b6d3141fc.png">

Here is a sample of an item with tooltip in the website_editorial:

![screen shot 2017-09-27 at 2 53 25 pm](https://user-images.githubusercontent.com/25483966/30931931-032b7aa4-a394-11e7-954d-948087847dfd.png)

It would be nice to have tooltips for items in the site nav.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/664

**Comment by alhambrav** [comment]
Verified fixed.
