### ISSUE TITLE
[studio] Pages, Taxonomy and Component folders display status "In Progress" in the tooltips when there has been no edits in the folder

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1384]
Pages, Taxonomy and Component folders display status "In Progress" in the tooltips when there has been no edits in the folder

Using the website_editorial bp, open the **Sidebar**
Navigate to the Components or Taxonomy folders.
Hover on one of the folders.  notice that the tooltip says the status of the folder is **In Progress** even if there has been no edits on the folder.

![screen shot 2017-09-27 at 3 01 37 pm 2](https://user-images.githubusercontent.com/25483966/30932312-21c65d02-a395-11e7-92bd-4008ba443ba1.png)

Here's a short clip:

https://www.useloom.com/share/31f90b4d1e4b461180f5f61c79ee72aa

**Comment by jvega-crafter** [comment]
@dejan-brkic InProgress property is true on folders even if there are no edits.

<img width="301" alt="screen shot 2017-11-08 at 1 13 17 pm" src="https://user-images.githubusercontent.com/18267471/32570003-7381daa4-c488-11e7-97b9-3e33d4e9eb9e.png">

<img width="706" alt="screen shot 2017-11-08 at 1 14 09 pm" src="https://user-images.githubusercontent.com/18267471/32570020-7cc944da-c488-11e7-8924-75b84540a8a3.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/963

**Comment by alhambrav** [comment]
Verified fixed.
