### ISSUE TITLE
[studio-ui] Remove the text next to the workflow status icon in the top bar in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1386]
Please remove the text (status and the colon) next to the workflow status icon in the top bar in Studio and replace it with a separator bar, like the bar between the Publishing Status and Users when Crafter Admin is logged in.  Please see image below:

<img width="1296" alt="screen shot 2017-09-27 at 4 27 15 pm" src="https://user-images.githubusercontent.com/25483966/30936225-27202100-a3a1-11e7-8957-e31b9d060354.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/626

**Comment by alhambrav** [comment]
Verified fixed.
