### ISSUE TITLE
[studio-ui] Update the status in tooltips to match the workflow status listed in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1387]
Update the status in tooltips to match the workflow status listed in the dashboard.  
Here's a list: 

|Existing Status                 | Status to be displayed (to match dashboard workflow status) |
| ------------------------ | --------------------------------------------------------------|   
| Deleted                            |     Deleted |
| Disabled                           |    Disabled |
| Processing                       |     Processing |
| In Progress                      |     Edited |
| Live                                  |     Live |
| Submitted                       |      In Workflow |
| Scheduled                       |     Scheduled |

The following existing status will be removed:
Submitted for Delete           
Scheduled for Delete          

<img width="405" alt="screen shot 2017-09-28 at 10 06 28 am" src="https://user-images.githubusercontent.com/25483966/30971015-cb10517a-a434-11e7-872f-e9706663b786.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/628

**Comment by alhambrav** [comment]
Hi! I found just one tooltip icon not matching the text listed in the dashboard:
 
Login as user author, edit a page and request the page to be published at a later time.  
Go to the **Sidebar** and navigate to the page just edited.  Hover your mouse over to see the tooltip.  Notice that the icon displayed for status in the tooltip is **In Workflow**, but the text next to it says **Scheduled**

<img width="542" alt="screen shot 2017-10-10 at 10 20 28 am" src="https://user-images.githubusercontent.com/25483966/31392754-1152d5a0-ada8-11e7-8864-97b4c20539d8.png">

Here is a short clip showing the user requesting the page to be published, then looking at the tooltip displayed:

https://www.useloom.com/share/54d3ed2273f8436ea6946c0ec4f8bf8e

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/638

**Comment by alhambrav** [comment]
Verified fixed
