### ISSUE TITLE
[studio-ui] The "p" in "Never published" in the Icon Guide on the dashboard should be upper case

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1388]
The "p" in "Never published" in the Icon Guide on the dashboard should be upper case

<img width="910" alt="screen shot 2017-09-28 at 10 14 18 am" src="https://user-images.githubusercontent.com/25483966/30971519-221e80ee-a436-11e7-9ca9-8e8c6af7fb07.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/660

**Comment by alhambrav** [comment]
Verified fixed.
