### ISSUE TITLE
[studio-ui] Site content pages folder does not update on save 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1389]
APPLIES TO 2.5.x

# Issue:
Site Content Pages folder does not update on content save.  
Internal name and page order changes do not get reflected until user refreshes which makes ordering content very difficult.

https://www.useloom.com/share/ead98f5205294a1c84f9779f31604f6e

# Correct behavior: 
Refresh the level of the tree where the user is editing on save

**Comment by jvega-crafter** [comment]
That scenario (changing nav position) happens in both 3.0 and 2.5.x. I'll fix in both

**Comment by jvega-crafter** [comment]
2.5.x: https://github.com/craftercms/studio-ui/pull/616
3.0: https://github.com/craftercms/studio-ui/pull/615

**Comment by russdanner** [comment]
CONFIRMED
