### ISSUE TITLE
[studio-ui] Change the Show/Hide In-Progress Items Sprinner

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1391]
Please change the spinner displayed for Show/Hide In-Progress Items on the dashboard to be like the Approve and Publish dialog / submit dialog spinners.

The reason is the spinners are not consistent and the size for the Show/Hide In-Progress Items is too small.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/636
