### ISSUE TITLE
[studio] security filter redirects with a / on the context and creates an infinite loop on timeout

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1392]
This only shows up in Firefox.  
You must also use/connect to Alfresco to reproduce the issue

# Steps to reproduce
1. Configure the system with a short timeout and the Alfresco repo
See below are the various files I updated.

```
FF Version: 55.0.3 (64-bit) -- this is the latest firefox but older versions seem to loop as well
URL: http://localhost:8080/studio

Studio WEB.xml
==============================
    <session-config>
        <session-timeout>5</session-timeout>
    </session-config>

Studio server-config.properties
==========================
crafter.deployer.remote.enabled=true
crafter.deployer.server=localhost
crafter.deployer.port=9191
crafter.deployer.target=preview
crafter.deployer.password=admin
studio.db.validationInterval=120

repositoryType=alfresco
securityType=alfresco

#repositoryType=alfresco
#securityType=alfresco
repository.diskImplementation.path=./data/repo

repositoryJob.username=admin
repositoryJob.password=admin
alfrescoUrl=http://localhost:5050/alfresco

environment=local
crafter.engine.search.server.url=http://localhost:8080/crafter-search


Alfresco global properties
========================
authentication.ticket.ticketsExpire=true
authentication.ticket.expiryMode=AFTER_INACTIVITY
authentication.ticket.validDuration=PT5M
authentication.ticket.useSingleTicketPerUser=false


```
2. In Firefox Sign in to Studio and look at the site dashboard
3. WAIT
4. Eventually, you will get a timeout and this will show up in the browser:
<img width="1170" alt="screen shot 2017-09-28 at 12 02 48 pm" src="https://user-images.githubusercontent.com/169432/30977276-13a3d780-a445-11e7-9597-4b850944a7e5.png">

# Other notes
We traced the source of the redirect to the security filter.

**Comment by russdanner** [comment]
Dejan,
Because this shows up in Firefox as a loop it sounds browser related but per testing, the redirect loop is caused by the security filter.  The UI never gets involved.

**Comment by dejan-brkic** [comment]
Can not reproduce it with current SNAPSHOT version. Redirect is working fine on same version of Firefox. I even reduced timeout to 1 min. Please check if it is some environment (or browser) specific condition. Claim that is only on firefox is very suspicious. If it is backend issue (security filter) should be affecting all browsers.

**Comment by russdanner** [comment]
I also built the snapshot version.
This was not easy for me to reproduce either.
Open the page in FF and let it sit all day.  If it doesn't happen to assign it back to me.

Also we must make sure we're attached to alfresco etc for this ticket.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/876

**Comment by russdanner** [comment]
VERIFIED

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/904

**Comment by russdanner** [comment]
VERIFIED
