### ISSUE TITLE
[studio-ui] RTE does not show HANDLES when user single clicks on an image

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1393]
Applies 2.5 and 3

See video to understand issue
https://www.useloom.com/share/afe4a5ca4585460184c97293588bd56e

**Comment by vestrada** [comment]
PR -> 2.5.x -> https://github.com/craftercms/studio-ui/pull/617

**Comment by vestrada** [comment]
PR -> master-> https://github.com/craftercms/studio-ui/pull/618

**Comment by russdanner** [comment]
VERIFIED
