### ISSUE TITLE
[engine] Disable pages should show in Studio in 2.5.x preview

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1394]
This works in 3.0.
It used to work in 2.5 but currently 404s.

# Steps to reproduce
1. In Studio disable a page
2. Preview the page
3. Note the red notice at top of preview ... page is 404'd.  It should show the page in the preview.

**Comment by jdrossl** [comment]
@russdanner are you sure you are using the latest 2.5.7? the fix was applied to both 3 & 2.5.x: https://github.com/craftercms/engine/commit/ab32541c9b06c3191029a611ea6ddde23b00f4ee

I just did a quick test and it is working as expected.

**Comment by russdanner** [comment]
I am using the latest 2.5.x and it does not work as expected

**Comment by russdanner** [comment]
https://www.useloom.com/share/751d0ae63a6e49a28b0799394e8cab99

**Comment by jdrossl** [comment]
@russdanner Can this be cache or some configuration? It is working for me in a clean 2.5.7-SNAPSHOT build: https://www.useloom.com/share/09bdc9145b6d46d39a8979a1790b179d

**Comment by jdrossl** [comment]
@russdanner it is also working as expected in the 2.5.7 release.

**Comment by russdanner** [comment]
VERIFIED
