### ISSUE TITLE
[studio-ui] Right click shows double lines where approve and publish is when item is live

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1395]
<img width="669" alt="screen shot 2017-09-28 at 12 40 20 pm" src="https://user-images.githubusercontent.com/169432/30979035-646ab06c-a44a-11e7-9824-11f03ee2698a.png">

Right click should only show one line when no options in a section are available.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/614

**Comment by russdanner** [comment]
CONFIRMED
