### ISSUE TITLE
[studio-ui] Template editor accessed from content type should show variables

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1397]
Currently, the variables only show up when you access the editor via the preview tools.  
On the content type, you know which form is associated with the template so the variables should show up there.
<img width="764" alt="screen shot 2017-09-28 at 12 52 47 pm" src="https://user-images.githubusercontent.com/169432/30979637-3af1310a-a44c-11e7-8db7-189e2a48d825.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/658

**Comment by russdanner** [comment]
VERIFIED
