### ISSUE TITLE
[studio-ui] Misaligned issues when "Item Name" is long in some dashboards.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#1398]
"Item Name" and icon in Recently Published, Approved Scheduled Items, Items Waiting For Approval" dashboards are not aligned correctly when the "Item Name" is long.
Some images with a long name are not displayed correctly in the dashboard. The icon and Item Name seems to be mis-aligned.
Please check it in major browsers.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/627
