### ISSUE TITLE
[studio-ui] Deleting an item under "Taxonomy" and "Scripts does not remove it from the Sidebar

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1401]
Deleting an item under "Taxonomy" and "Scripts does not remove it from the Sidebar until you refresh the page.

Here's a short clip showing a script created then deleted, notice after deleting the deleted script is still visible in the Sidebar, the same for when a new taxonomy item is created and deleted, the third item in the clip shows how an item should behave when deleted.

https://www.useloom.com/share/f737b1786be4490b8b0d7462a2765716

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/624

**Comment by alhambrav** [comment]
Verified fixed.
