### ISSUE TITLE
[studio-ui] Race condition on loading data sources

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1403]
Applies to 2.5.x and 3.x

# Issue:
In the form engine the following method seems to be the source of the issue:
   `loadDatasources(form);`

This method loads data sources asynchronously and does not wait for all items to load before returning.  This can cause race conditions when forms have many data sources.  

# Correction
Please update the method to make sure all data sources have loaded (or errored on load) before letting the method to return.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/619

**Comment by jvega-crafter** [comment]
2.5.x: https://github.com/craftercms/studio-ui/pull/621 - with update
3.0: https://github.com/craftercms/studio-ui/pull/620

**Comment by jvega-crafter** [comment]
3.0: https://github.com/craftercms/studio-ui/pull/638
2.5.x: https://github.com/craftercms/studio-ui/pull/643

**Comment by russdanner** [comment]
VERIFIED
