### ISSUE TITLE
[docs] There are some APIs not documented for Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1404]
There are some APIs listed in the common-api.js that are not documented.  Here's a link to common-api.js

 https://github.com/craftercms/studio2-ui/blob/master/static-assets/components/cstudio-common/common-api.js

Please document the following: (Here's a list of items I think are not documented, please document the ones that are valid.)

// READ OPS
* retrieveSitesUrl: "/api/1/services/api/1/user/get-sites-3.json"
* getPagesServiceUrl: "/api/1/services/api/1/content/get-pages.json",

// ORDER - READ
* getNextOrderSequenceUrl: "/api/1/services/api/1/content/get-next-item-order.json",

// Configuration Services
* getConfigurationUrl: "/api/1/services/api/1/site/get-configuration.json",

// Workflow
* getGoLiveQueueItemsServiceUrl: "/api/1/services/api/1/workflow/get-go-live-items.json",
* getWorkflowAffectedPathsServiceUrl: "/api/1/services/api/1/workflow/get-workflow-affected-paths.json",
* createWorkflowJobsServiceUrl: "/api/1/services/api/1/workflow/create-jobs.json",
* getWorkflowJobsServiceUrl: "/api/1/services/api/1/workflow/get-active-jobs.json",
* rejectContentServiceUrl: "/api/1/services/api/1/workflow/reject.json",
* getGoLiveServiceUrl: "/api/1/services/api/1/workflow/go-live.json",

// Crop Image
* cropImageServiceUri: "/api/1/services/api/1/content/crop-image.json",

**Comment by dejan-brkic** [comment]
`/api/1/services/api/1/user/get-sites-3.json` -> does not exist
`/api/1/services/api/1/workflow/get-active-jobs.json` -> seems like it is broken

PR:
https://github.com/craftercms/docs/pull/370

**Comment by alhambrav** [comment]
Verified fixed.
