### ISSUE TITLE
[studio] Upload asset should not modify the filename

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1406]
Applies to 2.5.x only

# To reproduce
1. right click on static assets
2. Upload mixed case image
3. note image is lower cases.

# Corrective action
Remove rules that modify file names.  We have determined these rules are not appropriate.

**Comment by sumerjabri** [comment]
@dejan-brkic we fixed this in 3.x, we must do the same for 2.5

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/878

**Comment by russdanner** [comment]
VERIFIED
