### ISSUE TITLE
[studio-ui] Remove "Edit" in the context nav when previewing an image

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1407]
Remove "Edit" in the context nav when previewing an image since it does not do anything right now.

Using website_editorial, open the **Sidebar**, navigate to **static-assets** -> **images**, click on any of the images there and notice the context nav items available.  Click on **Edit**, notice that nothing happens.  Since the **Edit** item does not do anything right now, it would be nice to just take it out of the context nav.

<img width="944" alt="screen shot 2017-10-02 at 9 50 18 am" src="https://user-images.githubusercontent.com/25483966/31080712-836b7982-a757-11e7-8259-5564dc066ef8.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/635

**Comment by alhambrav** [comment]
Verified fixed.
