### ISSUE TITLE
[studio-ui] Publishing status is not updating correctly

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1409]
Steps to Reproduce
================
1. create a site using Editorial BP
2. edit the home page and publish it
3. click on the publishing status, you'll see it showing Idle
4. check that the content is indeed published, it is, but the status stays Idle instead of showing last publish event

Ping me if you need anything.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/654

**Comment by jvega-crafter** [comment]
Updated, status loads on:
- dialog not showing: every 60 seconds
- click: immediately
- dialog open: every 3 seconds

**Comment by jvega-crafter** [comment]
@dejan-brkic when publishing and immediately getting the status it never shows "busy".

**Comment by sumerjabri** [comment]
@jvega-crafter per our conversation today, system processing is very quick now. Publishing can still be queried returning idle, busy, blocked etc.
