### ISSUE TITLE
[studio] Import content doesn't ignore `.keep`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1413]
Steps to Reproduce
===============
* create a site based on Editorial BP
* cd to the site folder /site/website/articles
* cp -r 2017 2018
* cp -r 2017 2019
...
* cp -r 2017 2025
* go to SiteConfig and Sync from Repo
* go to Dashboard, and click on `Show In-Progress Items`
* Note `.keep` <== mistake #1
* Publish these and click on `Show In-Progress Items`, you'll see more <== mistake #2

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/885
(master https://github.com/craftercms/studio/pull/886)
