### ISSUE TITLE
[studio-ui] Disable "Change Password" under "Account Management" for LDAP users

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1414]
Disable "Change Password" under "Account Management" for LDAP users (externally managed users).

It would be nice if the "Change Password" under "Account Management" is disabled for LDAP users since they cannot change their password using Studio.

<img width="1244" alt="screen shot 2017-10-04 at 10 39 14 am" src="https://user-images.githubusercontent.com/25483966/31181912-7abd8830-a8f0-11e7-8b40-5230b6bf08be.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/662

**Comment by alhambrav** [comment]
Verified fixed.
