### ISSUE TITLE
[docs] Document where logs are stored for authoring and delivery

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1416]
Please add an article explaining where logs go and the main log files and advise the sys admin to rotate these logs (don't have to tell them how).

Ping me with any questions.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/366
commit: https://github.com/craftercms/docs/pull/366/commits/d51e7c29eb5729ba998408106eba51308cca45d7
