### ISSUE TITLE
[studio] First time the site-config.xml is edited is never shown in the dashboard

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1418]
First time the site-config.xml is edited the file never shows up in the dashboard, making the user to bulk-publish, after that user can see the site-config.xml in the dashboard.

Steps:
1. Create a site.
2. Click "Site-Config"
3. Click Configuration.
4. Select "Engine Site Configuration" 
5. Make a edit.
6. Go back to the Dashboard.
7. `site-config.xml` will not show up (even is filters are set to all)
8. Build Publish `/cors/config/engine/site-config.xml`
9. After file is publish, it continue to show up in the dashboard.

**Comment by dejan-brkic** [comment]
Issue is addressed by https://github.com/craftercms/craftercms/issues/725
Different milestone on these 2 tickets. Triage needed for timelines.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/899
(master https://github.com/craftercms/studio/pull/899)
