### ISSUE TITLE
[studio-ui] The changes performed on Groups are not saved&displayed when the user clicks on "Groups" again [Site Config - Groups]

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1419]
*Preconditions*
===============
1) Create a site using WebSite Editorial BP

*Steps to reproduce:*
===============
1. Login as Admin and Go to the **Dashboard** page of the site of preconditions
2. Click on **Site Config**
3. Click on **Groups**
4. Select any Group and edit the **_Display Name_** or **_Description_**
5. Click on Save
6. Click on **Back to groups** link
7. Review that the changes are saved
8. Click on **Groups** again
9. Review that the changes performed stills there

*Current behavior*
==============
The changes performed on Groups are not saved&displayed when the user clicks on "Groups" again 
Watch the next video:
https://www.useloom.com/share/5c6d6573ca0f4276aa65f1c40696c26d

*There are not log errors on the tomcat log

*Expected Behavior*
=============
Previous changes should be displayed

**Comment by jvega-crafter** [comment]
Updated edit on groups

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/627

**Comment by luishernandezmonge** [comment]
Verified as Resolved
