### ISSUE TITLE
[studio] Update MariaDB4j fork to allow us to publish it/use it

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1420]
Please update the fork to:
* Statically link libssl for OSX
* Fix the bug that won't let us restore properly
* Use our org.craftercms name space so we can properly release it
* Build and publish so we can continue working

**Comment by cortiz** [comment]
To Used in Studio:

``` <!-- MariaDB -->
        <dependency>
            <groupId>ch.vorburger.mariaDB4j</groupId>
            <artifactId>mariaDB4j</artifactId>
            <version>2.2.3</version>
        </dependency>```
For:
```
  <dependency>
            <groupId>org.craftercms.mariaDB4j</groupId>
            <artifactId>mariaDB4j</artifactId>
            <version>2.2.4-SNAPSHOT</version>
       </dependency>```
