### ISSUE TITLE
[studio] Allow LDAP users to be part of multiple sites

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1424]
Studio allows the LDAP user to have multiple groups but not multiple sites.
Using Apache Directory Studio, I used an LDIF to setup the users.  I have a user, Jane Doe that I want to be part of two sites, `myawesomesite` and `helloworld`.  The user also belongs to two groups, `Admin` and `Editor`. 

```
dn: cn=Jane Doe,ou=Users,dc=example,dc=com
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
cn: Jane Doe
sn: Doe
ou: Admin
ou:Editor
description: 19650324000000Z
employeeNumber: 8
givenName: Jane
mail: john@example.com
o: myawesomesite
o: helloworld
telephoneNumber: 169-637-3314
telephoneNumber: 907-547-9114
uid: jdoe
userPassword:: abc
```
Notice after logging in that the user only has access to the site `myawesomesite`

<img width="1253" alt="screen shot 2017-10-05 at 4 15 35 pm" src="https://user-images.githubusercontent.com/25483966/31250355-8e4f6df2-a9e8-11e7-95ef-2882048bc090.png">

It did add the user jdoe to the `Admin` group, and it created a new group `Editor`

<img width="1240" alt="screen shot 2017-10-05 at 4 20 37 pm" src="https://user-images.githubusercontent.com/25483966/31250567-27fcf708-a9e9-11e7-913e-dd15673b86c1.png">

(I also noticed in the file DbWithLdapExtensionSecurityProvider.java that there's no loop for the `siteIdAttrib` and there is a loop for `groupNameAttrib`, although I did not look at it closely and there may be a loop for the siteId somewhere that I do not know=) )

**Comment by dejan-brkic** [comment]
@sumerjabri We need to discuss this feature. If user belongs to 2 or more different sites, there is no obvious relationship between groups and sites as LDAP attributes. Groups are just attribute values and we can not know which site each group belongs to. Also this is something very dependent on LDAP schema and its implementation onsite.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/902
(master https://github.com/craftercms/studio/pull/903)

**Comment by alhambrav** [comment]
Verified fixed.
