### ISSUE TITLE
[studio - ui] New Page - Article form does not allows to continue and set values because the progress bar blocks the user

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1425]
*Preconditions*
===============

1) Create a Site using Web Site Editorial BP

*Steps to reproduce:*
===============
1. Login as admin and go to the dashboard of the site of preconditions
2. Expand Pages/Home and right click on **articles** folder
3. Click on New Content and Select the Page- Article, later click on OK
4. Wait for the Creation Form and notice that the progress gif does not disappears

*Current behavior*
==============
The progress gif does not disappears and the user is not able create the Page-Article
Watch the next video:
https://www.useloom.com/share/4d22ce93cf9e46eeb4e157da94660ff4

*No errors on the tomcat log

*Expected Behavior*
=============
The progress gif should disappears and let user create the new page

**Comment by luishernandezmonge** [comment]
Same happens on Items/posts (New Item Post) of any site that use the Headless_Blog BP

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/630

**Comment by luishernandezmonge** [comment]
Verified as Resolved
