### ISSUE TITLE
[studio - ui] New Page - Category Landing form does not allows to continue and create the page because the validation message does not allows to save&close even if all the required values are provided

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1426]
*Preconditions*
===============
1) Create a Site using Web Site Editorial BP

*Steps to reproduce:*
===============
1.Login as admin and go to the dashboard of the site of preconditions
2. Expand Pages/Home and right click on Home
3. Click on New Content and Select the Page - Category Landing, later click on OK
4. Wait for the Creation Form and provide valid values for all required fields
5. Click on Save&Close 

*Current behavior*
==============
5. The validation message is displayed even if all the required values are provided

Watch the next video:
https://www.useloom.com/share/34e16329531d44688658dfb00936fbb8

*No errors on the tomcat log

*Expected Behavior*
=============
The validation message should not be displayed because all the fields are fulfilled

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/630

**Comment by luishernandezmonge** [comment]
Verified as Resolved
