### ISSUE TITLE
[studio-ui] Editing an article page in website editorial does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1427]
Using website_editorial, create a new site.
Navigate to one of the article page, then preview it.
Edit the article page either by right clicking on the article in the **Sidebar**, then selecting **Edit** or, by previewing the article, then clicking on **Edit** in the context nav, you can also try to edit using the in-context pencils.
Notice when the edit form displays, there is a spinner.  The spinner does not go away, so you cannot edit the article at all.

<img width="1216" alt="screen shot 2017-10-06 at 12 08 47 am" src="https://user-images.githubusercontent.com/25483966/31262678-c2e8b7d4-aa2a-11e7-9c92-d3436974cad9.png">

Here is a short clip:
https://www.useloom.com/share/dc658ccd36424b24822b43db4c5e014b

**Comment by alhambrav** [comment]
This may be related to ticket https://github.com/craftercms/craftercms/issues/1425?

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/630

**Comment by alhambrav** [comment]
Verified fixed.
