### ISSUE TITLE
[studio] Change the log level used when a user is not found with external security provider (LDAP user)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1428]
Change the log level when user not found with external security provider (LDAP user) to INFO, since it is not fatal to the system.

Setup an LDAP server with some users.  
Setup  LDAP authentication in Studio.
Start Studio and login as Crafter admin (admin).  
Look at the tomcat log, notice the log level that the user admin is not found with the external security provider:

```
[ERROR] 2017-10-06 09:27:56,139 [http-nio-8080-exec-1] [security.DbWithLdapExtensionSecurityProvider] | User admin not found with external security provider. Trying to authenticate against studio database
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/897
(master https://github.com/craftercms/studio/pull/896)

**Comment by alhambrav** [comment]
Verified fixed.
