### ISSUE TITLE
[craftercms] Cannot start crafter, scripts are missing from the bin folder

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1432]
I did a git clone, then did a build and deploy.  I finished building and deploying crafter, but cannot start crafter because the bin folder does not contain any scripts.

Here's the error I got when I tried to start crafter:
➜  craftercms git:(master) ./gradlew start

> Task :start
Running for the first time might take longer while fetching OS dependent requirements.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vita/temp/test2/craftercms/build.gradle' line: 715

* What went wrong:
Execution failed for task ':start'.
> java.io.IOException: Cannot run program "./startup.sh" (in directory "./crafter-authoring/bin"): error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
1 actionable task: 1 executed
➜  craftercms git:(master)

So, I checked the directory, and the scripts are missing from both the authoring and delivery folders
```
➜  craftercms git:(master) ✗ ls -al crafter-authoring/bin
total 448
drwxr-xr-x  5 vita  staff     170 Oct  6 15:21 .
drwxr-xr-x  5 vita  staff     170 Oct  6 15:24 ..
drwxr-xr-x  3 vita  staff     102 Oct  6 15:21 apache-tomcat
drwxr-xr-x  3 vita  staff     102 Oct  6 15:21 crafter-deployer
-rw-r--r--  1 vita  staff  229040 Oct  6 15:21 craftercms-utils.jar
➜  craftercms git:(master) ✗
```

**Comment by sumerjabri** [comment]
@cortiz I get this error too, in my case I can reproduce by removing the `bin` folder (and leave the rest) and ask for a build. This may be different than what's reported in this ticket, but it might help you track this issue down.

**Comment by cortiz** [comment]
Solve in https://github.com/craftercms/craftercms/pull/1512

**Comment by alhambrav** [comment]
Verified fixed.
