### ISSUE TITLE
[studio-ui] Parent page is not published and Root Parent is displayed as processing on publishing a child page (Structure root/parent/child) when trying to publish the child page [The publish is blocked on the parent page]

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1433]
*Preconditions*
===============
1) Create a site using WebSite Editorial

*Steps to reproduce:*
===============
1. Login as **Admin** and go to the preview of the site of preconditions
2. Create a new Page (Category -Landing Page)  named: 1
3. Create a child Page into the page above  (Category -Landing Page)  named: 2
4. Create a child Page into the page step 3  (Category -Landing Page)  named: 3
5. Edit the root page (1) rename it to 11
6. On 3 right click and click on Publish
7. On the publish dialog, unselect all items and only leave as checked the page of step 4
8. Wait for the publish of all the items above

*Current behavior*
==============
8. The child page named: 3 is published, but the other are not published and the root parent page is blocked on processing gif icon (infinite publishing)

Watch the next video:
https://www.useloom.com/share/6920d3ade7fc45168782635c77b96de5

See the log errors:
[LogError.txt](https://github.com/craftercms/craftercms/files/1364154/LogError.txt)

*Expected Behavior*
=============
Studio should publish all the items of above without problems

**Comment by vestrada** [comment]
Hi Dejan, 

Per our conversation it is a backend issue. Thanks.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/890
(master https://github.com/craftercms/studio/pull/889)

**Comment by luishernandezmonge** [comment]
Verified as resolved
