### ISSUE TITLE
[test-suite] Automate opening studio in your browser

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1434]
Automate item 1 in the sanity test automation sheet for OS X, Linux and Windows:

In your browser, load Studio (localhost:8080/studio), 
check that the Studio login screen is displayed for success, any other screen, like site is not set or an error message is a fail

**Comment by luishernandezmonge** [comment]
Already automated for all the Studio UI Test Cases, currently the automated framework checks that at first time.

**Comment by alhambrav** [comment]
Hi!  I think this is already automated, I guess we just need to add this as an entry in the Sanity test.

**Comment by juacamar** [comment]
Done and Added to the testngSanity.xml as an individual test case that verify the login page is displayed and contains all the elements.
PR: https://github.com/craftercms/test-suite/pull/245
