### ISSUE TITLE
[test-suite] Automate logging in to Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1435]
Automate item 2 in the sanity test for OS X, Linux and Windows:

Login using Crafter Admin (admin), 
Check that you can login correctly, if the next screen is the **Sites** screen, it's a success.  Anything other than the **Sites** screen is a failure

**Comment by luishernandezmonge** [comment]
Already automated on the org.craftercms.studio.test.cases.loginpagetestcases.LoginTest test class and integrated to Sanity Test Suite (testngSanityTest.xml)

**Comment by alhambrav** [comment]
Waiting on testngSanityTest.xml file to be available before verifying.

**Comment by luishernandezmonge** [comment]
Juan, please validate and add some work on this for testngsanitytest.xml suite. when it's done ping me back.

**Comment by juacamar** [comment]
Test added in pull request https://github.com/craftercms/test-suite/pull/184 in the structure  testngsanitytest.xml suite, working on the other task this area.

**Comment by alhambrav** [comment]
Verified fixed.
