### ISSUE TITLE
[studio-ui] Inconsistent scheduled publish times displayed for user author and user admin

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1439]
Using the Website_editorial bp, login as user **author**
Edit a page, and request publish at a later time.  In the image below, my local time is 11:48am EDT, and I request a publish time of 12:00pm, EST5EDT in the request publish dialog.
Logout.

<img width="1278" alt="screen shot 2017-10-10 at 11 48 15 am" src="https://user-images.githubusercontent.com/25483966/31396407-4faece86-adb1-11e7-946a-53bf998edda2.png">

Login as user **admin**
Preview the page user **author** requested to be published, and click on **Approve & Publish**.  Notice the time displayed for Item Scheduling is different (It says 4PM) from the requested time by user **author** and both users are in the same time zone.  It looks like the time displayed in the user **admin** dashboard/**Approve & Publish** dialog is in UTC, even though it says the timezone is still EST5EDT, which then delays the time the page will be published, instead of the time the user **author** requested.  Both users are in the same time zone.

<img width="1296" alt="screen shot 2017-10-10 at 11 50 29 am" src="https://user-images.githubusercontent.com/25483966/31396445-6487e2d4-adb1-11e7-8d8f-35bffd4e6c9a.png">

Here's a short clip:
https://www.useloom.com/share/d4533d6835a24b7ab15aae01ee97d736

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/646

**Comment by alhambrav** [comment]
Verified fixed.
