### ISSUE TITLE
[studio-ui] Use the users time zone for displaying times in the tooltips when hovering on an item in the Sidebar

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1440]
Use the users time zone for displaying times in the tooltips when hovering on an item in the Sidebar

The time displayed when you hover on an item in the **Sidebar** is in UTC instead of the users time zone:

<img width="1003" alt="screen shot 2017-10-10 at 2 38 18 pm" src="https://user-images.githubusercontent.com/25483966/31404241-7cd67e50-adc9-11e7-8b9a-5b0ed7a8598c.png">

Here's another look at the time being displayed by the tooltip compared to the time listed on the dashboard:

<img width="1277" alt="screen shot 2017-10-10 at 2 45 51 pm" src="https://user-images.githubusercontent.com/25483966/31404476-2b41062c-adca-11e7-8e4d-f31dd771613f.png">

**Comment by sumerjabri** [comment]
@alhambrav let's discuss
