### ISSUE TITLE
[studio-ui] Reject disappeared from toolbar menu

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1441]
Steps to reproduce
1. create site from editorial BP
2. create author user and add it to the new site
3. logout
4. login as author created in step 2
5. go to site created in step 1
6. edit content
7. request publish for edited conte
8. logout
9. login as admin
10. go to site created in step 1
11. select content edited in step 6 from "items waiting for approval"
12. reject content
Error - can not reject content, there is no Reject link/command/button in toolbar

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/637

**Comment by dejan-brkic** [comment]
Verified
