### ISSUE TITLE
[studio-ui] Clicking Approve & Publish for large lists doesn't have a spinner

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1442]
Clicking on Approve & Publish for large lists takes a long time to bring up the Publish dialog without a spinner, and the user doesn't know what's going on.

Steps to Reproduce
===============
* create a site based on Editorial BP
* cd to the site folder /site/website/articles
* cp -r 2017 2018
* cp -r 2017 2019
...
* cp -r 2017 2025
* git add .; git commit -m "Testing."
* go to SiteConfig and Sync from Repo
* go to Dashboard, and click on `Show In-Progress Items`
* select all, and click Approve & Publish

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/652
