### ISSUE TITLE
[studio] Invalid Date appearing in dashboard

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1443]
Steps to Reproduce
===============
* edit files on disk
* git commit
* sync repo from disk
* go to dashboard
* click on Show In-Progress Items
* Date field shows "Invalid Date"

![invalid-date-issue](https://user-images.githubusercontent.com/3931908/31435119-9036196e-ae4c-11e7-9ca1-c52c49fbe246.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/895
(master https://github.com/craftercms/studio/pull/894)
