### ISSUE TITLE
[studio-ui] Publishing item spinner goes on forever

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1444]
Steps to Reproduce
===============
* edit an item
* go to dashboard
* click on Show In-Progress Items
* select the item
* click Approve & Publish
* see the spinner (per image attached)
* the spinner goes on forever

![pub-spin-forever](https://user-images.githubusercontent.com/3931908/31435610-25beac02-ae4e-11e7-9384-9868e8612822.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/649
