### ISSUE TITLE
[test-suite] Automate creating a site using the Website_editorial bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1445]
Automate item 3 in the sanity test for OS X, Linux and Windows:

Create a site by clicking on **Create Site** in the "Sites" screen, 
Fill in the fields of the **Create Site** dialog, we will be using the website_editorial blueprint e.g.
    Site Id: testeditorial
    Description: Test site to validate the Website_editorial blueprint screens
    Blueprint: Website_editorial
Click on the **Create** button

Check that it allows you to create a site.  No error messages after clicking on the **Create** button, and that it takes you to the preview of the Website_editorial Home Page.

**Comment by luishernandezmonge** [comment]
Already automated on org.craftercms.studio.test.cases.sitespagetestcase.CreateSiteWithWebSiteEditorialBluePrintForSanityTest and integrated to the Sanity Test Suite (testngSanityTest.xml)

**Comment by alhambrav** [comment]
Waiting on testngSanityTest.xml file to be available before verifying.

**Comment by luishernandezmonge** [comment]
Juan, please validate and add some work on this for testngsanitytest.xml suite. when it's done ping me back. @juacamar

**Comment by juacamar** [comment]
Added test case to cover ticket in pull https://github.com/craftercms/test-suite/pull/185

**Comment by alhambrav** [comment]
Verified.
