### ISSUE TITLE
[test-suite] Automate verifying there are no errors in the Home Page of Website_editorial bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1446]
Automate item 4 of the Sanity Test for OS X, Linux and Windows

Once the site is created, check that no errors are displayed on the Home Page (expand the left-rail, and scroll to the bottom of the home page to check that there are no errors on the page (error messages).

Open the left-rail if it's not expanded, scroll to the bottom if the whole left rail is not visible, check that there are no errors listed there.
Check that the **Hero** section of the Home Page has no errors.
Check that the **Features** section Erat lacinia, has no errors.
Scroll to the bottom of the home page, check that there are no errors in the **Featured Articles** section.
Click on **Sidebar** on the top left of the screen to open the **Sidebar** if it's not yet open, check that there are no error messages in the Sidebar

**Comment by luishernandezmonge** [comment]
Juan, please validate and add some work on this for testngsanitytest.xml suite. when it's done ping me back. @juacamar

**Comment by juacamar** [comment]
Added a test case to cover this ticket:
AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage
Also added in the testngSanitytest.xml
PR: https://github.com/craftercms/test-suite/pull/249
