### ISSUE TITLE
[test-suite] Automate checking that there are no errors in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1447]
Automate item number 5 in the Sanity Test in OS X, Linux and Windows:

Click on the dashboard and check that there are no errors.

Open the **Sidebar** by clicking on **Sidebar** at the top left corner, click on **Dashboard**
Check that there are no error messages listed in the dashboard.
The dashboard should have four widgets:
    - Items Waiting For Approval
    - Approved Scheduled Items
    - Recently Published
    - My Recent Activity

The dashboard should also contain the **Icon Guide**

**Comment by luishernandezmonge** [comment]
Juan, please validate and add some work on this for testngsanitytest.xml suite. when it's done ping me back. @juacamar

**Comment by juacamar** [comment]
Test Case added to cover the ticket
AutomateCheckingNoErrorsDisplayedInTheDashboard
https://github.com/craftercms/test-suite/pull/246
Added to testngSanityTest.xml
