### ISSUE TITLE
[test-suite] Automate checking items in Site Config

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1448]
Automate item number 6 in the Sanity Test for OS X, Linux and Windows:
Click  on "Site Config" and check that it displays the "Site Config" menu

Open the **Sidebar**
Navigate to the bottom of the **Sidebar** and click on **Site Config**
Verify that there are no error messages displayed and that the following items are listed:
    - Content Types
    - Configuration
    - Groups
    - Audit
    - Bulk Operations
    - Workflow States
    - Logging Levels
    - Log Console
    - Preview Sync
    - Sync From Repository

**Comment by luishernandezmonge** [comment]
Juan, please validate and add some work on this for testngsanitytest.xml suite. when it's done ping me back. @juacamar

**Comment by juacamar** [comment]
This options are not validated in the automated test case since the options are not longer displayed.
- Preview Sync
- Sync From Repository
Done and Added to the testngSanity.xml.
PR: https://github.com/craftercms/test-suite/pull/245
