### ISSUE TITLE
[craftercms] Allow "test" task to accept arguments to pick which test suite to run

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1449]
It would be nice if we can allow the "test" task to accept arguments to pick which test suite to run.  We currently have three test suites to run, it would be nice to be able to run just one or more or all  test suites.  It would be handy to have when we have more test suites and the user only wants to run certain tests.  Something like:

./gradlew test {test-suite-to-run}

{test-suite-to-run} is one of the following:
src/test/resources/testng.xml,
src/test/resources/testngcomplexscenarios.xml,
src/test/resources/testngAPI.xml

If {test-suite-to-run} is empty, then run all the test suite

**Comment by cortiz** [comment]
Some Reformat some code.

New param name is `crafter.testing.suites` send a list of relative to the `test-suite` project or  full path , multiple files can be send if added the `,` between the paths

**Comment by cortiz** [comment]
New param name is `crafter.testing.suites` send a list of relative to the `test-suite` project or  full path , multiple files can be send if added the `,` between the paths

**Comment by alhambrav** [comment]
Verified fixed.
