### ISSUE TITLE
[studio] Add to audit log entry when a user is added/deleted to/from a site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1452]
Audit does not log changes for when a user is added/deleted to/from a site.

Click on **Site Config** from the **Sidebar**, then click on **Groups**, add a user to one of the groups.
Click on **Audit** on the left hand side of the screen, notice that there's no log that a user was added to the site. 
Delete a user from one of the groups, notice that there's also no log that a user was deleted from the site.

**Comment by sumerjabri** [comment]
@dejan-brkic ping me for help/design as needed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/911

**Comment by alhambrav** [comment]
Verified fixed.
