### ISSUE TITLE
[studio ui] Assets folder plugin to site content dropdown should show a hand icon on hover

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1453]
The behavior of wcm-root and wcm-asset-root plugins should be the same when a user hovers over the top level folder (which is a label)
- There should be no underline
- The mouse cursor should turn to a hand.

![studio-dashboard-previewable-items](https://user-images.githubusercontent.com/169432/31632141-e8709794-b289-11e7-9570-6e5e2343a966.JPG)

Please check C3 to make sure the behavior is consistent there as well.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/647

**Comment by russdanner** [comment]
VERIFIED
