### ISSUE TITLE
[studio] Preview should be able to point to other servers

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1455]
# The issue
Studio has a config in `environment-config.xml` for `preview-server-url`
Today this configuration is ignored by the application.

* When the preview is running in the same container (same url and port) preview works fine.
* If you were to point the preview at a remote server you would likely trigger cross-site scripting concerns from the preview IFRAME.

# A possible solution
* If Studio had a reverse proxy it could point to any server that's configured for its preview.

# The requirement
Allow a Studio project to configure a preview server URL via environment-config.xml that is potentially a remote Crafter Engine (or similar) type server.

**Comment by sumerjabri** [comment]
Done
