### ISSUE TITLE
[studio-ui] content type edit results in icons and editor information missing on dashboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1456]
<img width="1295" alt="screen shot 2017-10-17 at 4 05 47 am" src="https://user-images.githubusercontent.com/169432/31653487-ba54d91c-b2f0-11e7-8855-319e21e966d1.png">

# to reproduce
1. Modify a content type via content type editor
2 Review dashboard, not missing icons and metadata

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/938

**Comment by russdanner** [comment]
VERIFIED
