### ISSUE TITLE
[studio-ui] clicking edit on a form definition on dashboard should open the form editor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1457]
https://www.useloom.com/share/07a590c5a3d04ebe98d84759c69404a0

**Comment by jvega-crafter** [comment]
@russdanner hey! what should happen if the user doesn't have permission to edit the form?

**Comment by sumerjabri** [comment]
@russdanner let's discuss

**Comment by russdanner** [comment]
They should not get the edit button in the first place if they don't have permissions.

**Comment by sumerjabri** [comment]
@russdanner let's discuss

**Comment by sumerjabri** [comment]
Should validate permission based on the path `config/studio/content-types` if r/w then wire directly to form editor, otherwise, don't show the `Edit` link at all.

**Comment by sumerjabri** [comment]
Will address this in FE2.
