### ISSUE TITLE
[studio] Use a system site value  instead of "N/A" for the system siteId in audit log

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1459]
Use a system site value  instead of "N/A" for the system siteId in audit log.  Right now, to check the audit logs for say, a user was created, the site id used to query for it is `N/A`.

**Comment by sumerjabri** [comment]
@dejan-brkic I'm thinking `crafter_global` or `crafter_system` or similar. Think about it and let's chat.

**Comment by dejan-brkic** [comment]
@sumerjabri we already have `studio_root`. Problem here is that `N/A` does not exist in DB, so when user wants to view audit log, it is not possible to view logs with `N/A` value because required filter is site id.

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss when this ticket comes up for work per priority.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/942

**Comment by alhambrav** [comment]
Verified fixed.
