### ISSUE TITLE
[studio-ui] If your an Admin of a site you can't assign groups to other members.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1463]
As an Admin of a site (not the `admin` user), go to Site Config > Groups and then click on Edit/Membership of the Developer group. Then start typing the username on the Add New Members text area. Nothing happens when the member name should appear and the following error is displayed in the JS console: `TypeError: Cannot read property 'filter' of undefined` .

**Comment by jvega-crafter** [comment]
This is a backend issue. Services for user on administrator group (other than admin user) are not working as they're supposed to, for example:

`http://localhost:8080/studio/api/1/services/api/1/user/get-all.json`
returns `{ "message": "Unauthorized" }`

Assigning to @dejan-brkic

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/909
(master https://github.com/craftercms/studio/pull/908)

**Comment by avasquez614** [comment]
Tested and verified.
