### ISSUE TITLE
[studio] java.io.IOException: Unable to delete file: ..\data\repos\sites\mysite\published\.git\objects\pack\pack-bb075f4f811778b553aef226182bdba53c8d804a.pack on Windows when the delete API Call is executed

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1465]
**Preconditions**
===============
1) Create a site through Studio UI or using API Call:
**/studio/api/1/services/api/1/site/create.json**

**Steps**
===============
1) Login as admin using API Call: **/studio/api/1/services/api/1/security/login.json**
2) Try to delete the site of preconditions using the siteId provided and the Delete Site API call:
**/studio/api/1/services/api/1/site/delete-site.json**
3) Go to Studio and login as admin
4) Go to sites page and notice that the site is not there
5) Review that the folder  data\repos\sites\mysite\published still there on the server (crafter-authoring) folder
6) Review the log of studio on **C:\opt\crafter\craftercms\craftercms\crafter-authoring\logs\tomcat**

**Current Behavior**
================
5) The data folder for the site created&deleted does not disappears
6) The next error is displayed on the studio log:
**[INFO] 2017-10-17 19:12:39,633 [http-nio-8080-exec-8] [search.SearchServiceImpl] | Deleted search index for site:mysite. HTTP Status Code: 204 
[ERROR] 2017-10-17 19:12:39,761 [http-nio-8080-exec-8] [git.GitContentRepositoryHelper] | Failed to delete site: mysite at path: ..\data\repos\sites\mysite exception java.io.IOException: Unable to delete file: ..\data\repos\sites\mysite\published\.git\objects\pack\pack-bb075f4f811778b553aef226182bdba53c8d804a.pack** 

[logerror.txt](https://github.com/craftercms/craftercms/files/1392363/logerror.txt)

**Expected Behavior**
===============
step2)  API call should not fail and the site should be deleted totally
step5) The all site data should be deleted

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/914
(master https://github.com/craftercms/studio/pull/913)

**Comment by luishernandezmonge** [comment]
Tested and it works ok
