### ISSUE TITLE
[studio-ui] Remove constraints listed for new password in the "Set Password" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1466]
Remove constraints listed for new password in the "Set Password" dialog.  There are no checks for constraints on passwords for now.

![recover-set-password copy](https://user-images.githubusercontent.com/25483966/31686343-e00ed280-b353-11e7-91c7-39ba034ac325.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/648

**Comment by alhambrav** [comment]
Verified fixed.
