### ISSUE TITLE
[mariadb4j] Please add Travis CI automation

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1467]
Already enabled at Travis CI, only needs the yaml config.

**Comment by cortiz** [comment]
https://github.com/craftercms/MariaDB4j/pull/3

I do not have W perms to that Repo so I can't make the Travis branch with the settings.xml , and probably @sumerjabri need to update the keys.

**Comment by sumerjabri** [comment]
@cortiz access granted

**Comment by cortiz** [comment]
https://travis-ci.org/craftercms/MariaDB4j/builds/303636234
