### ISSUE TITLE
Blueprint / Samples for customer portal

### ISSUE THREAD

**Issue by eastwestageas** [craftercms/craftercms#1470]
I am assessing CrafterCMS as a possible alternative to building our website [https://www.troo.life](url)

We need a java based CMS that can support a customer portal. Customer data would come SOAP Services provided by our current ERP. 

Do you have an available blueprint that does at least the following?
1. Views must still be managed by Crafter CMS.
2. Customer registration/authentication integrated to Crafter Profile.
3. Adding new fields in Crafter Profile (e.g. the customer id used in the SOAP Service)

My best guess is that this would involve groovy scripts from :[http://docs.craftercms.org/en/latest/developers/projects/engine/api/groovy-api.html?highlight=authenticationmanager](url) 

As well as additional rest controllers that the groovy would use to fetch customer data - these controller would be the ones to call the SOAP services.

**Comment by sumerjabri** [comment]
@eastwestageas Please use the forums for questions: https://groups.google.com/forum/#!forum/craftercms
