### ISSUE TITLE
[studio-ui] Studio page not responsive when browser is scrunched

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1477]
Studio page not responsive when browser is scrunched.  

The hamburger icon at the top right of the browser when the browser is scrunched does not display the top bar items when clicked.  

Also, when the **Sidebar** is open, whether you're in preview or in the dashboard, when the browser is scrunched, Studio does not look good with the empty space on the left where the **Sidebar** is supposed to be and the preview/dashboard looks odd, like it's cutoff, with a scrollbar at the bottom.

Here are the steps:

Using the website_editorial bp, open the **Sidebar** and preview the home page so it looks like below:

![screen shot 2017-10-23 at 10 06 11 am](https://user-images.githubusercontent.com/25483966/31893711-38e8fa72-b7da-11e7-97e3-f60357b13fa4.png)

Scrunch your browser to the narrowest that your browser can go, so your page looks like below:

![screen shot 2017-10-23 at 10 06 21 am copy](https://user-images.githubusercontent.com/25483966/31894113-6317d222-b7db-11e7-9cb8-40b8d99d02cb.png)

Ideally, when the browser is scrunched narrow that we cannot see all the items in the **Sidebar** and the preview page, we would want the **Sidebar** to be hidden and just the preview page displayed, since we have the Hamburger Icon at the top right of the browser to display items in the top bar of Studio.  We want it to look something like this:

![screen shot 2017-10-23 at 10 06 54 am](https://user-images.githubusercontent.com/25483966/31894212-b935e7b6-b7db-11e7-8335-33fe9b677252.png)

To open the Sidebar, the user can click on the hamburger at the top right and the hamburger items will take over the page (containing the links to the **Sidebar**, help, sites, etc.), the user can then select **Sidebar** and view the **Sidebar**, something like that.

Here's a short clip showing how the browser looks when scrunched:

https://www.useloom.com/share/52491c24ca664bb69a5cb6e699d1d12f

**Comment by sumerjabri** [comment]
Remove the hamburger as it doesn't work in the current UI. We will add that in the next UI upgrade.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/731

**Comment by alhambrav** [comment]
Verified fixed.
