### ISSUE TITLE
[studio-ui] ICE parameter is not respected when form opens

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1480]
# to reproduce
1. configure a content type repreat group with an ICE group ID
2. include the icegroup tag on the template (example: <@studio.iceAttr iceGroup="promos"/>)
3. click the pencil, note form is not restricted to specific ice tag

https://www.useloom.com/share/d9eadad5610e427297c886426608d2ed

**Comment by russdanner** [comment]
I thought this was specific to repeats but no ICE is being respected

**Comment by jvega-crafter** [comment]
3.0: https://github.com/craftercms/studio-ui/pull/656
2.5.x: https://github.com/craftercms/studio-ui/pull/657

**Comment by russdanner** [comment]
VERIFIED
