### ISSUE TITLE
[studio-ui] following rebrand instructions no longer replaces logo

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1481]
# to reproduce
1. follow these steps: http://docs.craftercms.org/en/3.0/system-administrators/studio/changing-the-studio-logo.html
2. Note that logo is not replaced on login dialogs, sites screen but is replaced on preview screen

**Comment by sumerjabri** [comment]
Please update the instructions so things work.

**Comment by alhambrav** [comment]
Cannot reproduce.  Followed the instructions listed in the doc, and I cannot reproduce using a build from yesterday, 10/25/2017.

Here's the time out screen:

<img width="352" alt="screen shot 2017-10-26 at 6 04 43 am" src="https://user-images.githubusercontent.com/25483966/32054568-c60c0986-ba2c-11e7-82bd-1c33fe3b6aaf.png">

Preview screen:

<img width="796" alt="screen shot 2017-10-26 at 6 05 20 am" src="https://user-images.githubusercontent.com/25483966/32054587-d8cd68d0-ba2c-11e7-9c99-de46e0d5e2ff.png">

Sites screen:

<img width="1305" alt="screen shot 2017-10-26 at 6 06 05 am" src="https://user-images.githubusercontent.com/25483966/32054618-f41ca2c2-ba2c-11e7-8feb-0eae9fb90cc8.png">

Login screen:

<img width="312" alt="screen shot 2017-10-26 at 6 06 53 am" src="https://user-images.githubusercontent.com/25483966/32054641-09a6c7c6-ba2d-11e7-9c22-745defb7bff1.png">

**Comment by russdanner** [comment]
VERIFIED
