### ISSUE TITLE
[studio] Deleting a folder is not logged in the audit log

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1486]
- create a new folder in the site tree, then look at the audit log, you will see an entry for the created folder:
```
admin | /site/website/articles/2017/4 | CREATED | 10-25-2017 11:03:20 am (EST5EDT) | 10-25-2017 11:03:20 am (EST5EDT)
-- | -- | -- | -- | --
```
- delete the folder you just created in the site tree, then look at the audit logs again.  Notice that there is no entry that the folder was deleted.

Notice also that when you create a new article page, then delete that article page, that there is no entry that the folder of the new article page is deleted.

When a new article page is created, you'll see two entries in the audit log for the new article page:
 ```   
admin	/site/website/articles/2017/3/new	CREATED	10-25-2017 11:00:38 am (EST5EDT)	10-25-2017 11:00:38 am (EST5EDT)
admin	/site/website/articles/2017/3/new/index.xml	CREATED	10-25-2017 11:00:38 am (EST5EDT)	10-25-2017 11:00:38 am (EST5EDT)
```

But, when that article page is deleted, there is only one entry in the audit log (it did not log that the folder created when the new article was created was deleted):
```
admin	/site/website/articles/2017/3/new/index.xml	DELETED	10-25-2017 11:01:32 am (EST5EDT)	10-25-2017 11:01:32 am (EST5EDT)
```

Here's a screen capture of the audit log in Studio:

<img width="934" alt="screen shot 2017-10-25 at 11 22 42 am" src="https://user-images.githubusercontent.com/25483966/32007212-e6a87ff0-b976-11e7-9f91-12f94dc613fb.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/958

**Comment by alhambrav** [comment]
Verified fixed.
