### ISSUE TITLE
[studio-ui] Provide ability for author to open form in a separate tab

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1488]
Many users need to be able to open a number of content windows at any time.

Support a similar concept as shown here in gmail:
<img width="526" alt="screen shot 2017-10-25 at 2 24 28 pm" src="https://user-images.githubusercontent.com/169432/32016645-78bf9fd4-b992-11e7-90d8-d5a308609c08.png">

https://www.useloom.com/share/8f6014be9a2746f8ad9d3f67611ce1e5

**Comment by russdanner** [comment]
Forms should not get smaller as they stack up.  We should show some kind of tabbing on the top or left that lets you move between forms in the stack.

**Comment by sumerjabri** [comment]
4.0 SPA approach requires us to re-evaluate the UI and use-case.
