### ISSUE TITLE
[studio] Allow LDAP user to login even when all the siteId's in the user attribute does not exist in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1489]
Allow LDAP user to login even when all the siteId's in the user attribute does not exist in Studio.
Currently, Studio does not allow the LDAP user in when the siteId attributes of the user does not exist in Studio.

In the LDAP server, create a user with a siteId attribute that does not exist in Studio.
Login to Studio using the new LDAP user created above, notice that the user is not allowed to login and shown the following screen (no errors in the tomcat log):

<img width="325" alt="screen shot 2017-10-25 at 3 14 14 pm" src="https://user-images.githubusercontent.com/25483966/32018211-314c8400-b997-11e7-91b7-40257665e80e.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/918

**Comment by alhambrav** [comment]
Verified fixed.
