### ISSUE TITLE
[studio] The session timeout specified in the studio-config-override.yaml file does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1491]
The session timeout specified in the studio-config-override.yaml file does not work.

Add the following line in the `studio-config-override.yaml` file (the default timeout is 60 minutes, change it to 2 minutes):
```
# HTTP Session timeout for studio (value is in minutes).
studio.security.sessionTimeout: 2
```
Stop and then start Studio.  Logout, then log back in to Studio.
Wait for 2 minutes.  Notice that the session does not time out.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/919

**Comment by alhambrav** [comment]
Verified fixed.
