### ISSUE TITLE
[docs] Update Publishing issues article

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1494]
Remove section where pull from sandbox is recommended for fixing publishing issues

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/393

**Comment by sumerjabri** [comment]
Please update with latest:
* NULL commit id
* Deleted files (but present in DB)

**Comment by dejan-brkic** [comment]
Updated
PR
https://github.com/craftercms/docs/pull/397
