### ISSUE TITLE
[studio] Modify publishing job execution algorithm

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1495]
Before requesting publishing batch, job will execute sync database from repository. If found unprocessed commits, job will also execute preview sync.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/936

**Comment by sumerjabri** [comment]
Per our conversation, please change:
gitlog table: remove `verified` and `commit_date` columns.
site table: add `last_verified_gitlog_commit_id` column.

Update algorithm per our conversation.

Update the internal db version 4th number (3.0.2.1).
Add db upgrade mechanics for existing 3.0.2-SNAPSHOT users.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/949
