### ISSUE TITLE
[studio] remove site from permissions-mapping.xml

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1496]
The following tag should be removed from permissions files and should not be respected by studio
```
<permissions>
  <site id="t10"> <!-- REMOVE THIS TAG and ENFORCEMENT OF THIS TAG-->
....
</permissions>

```

The file itself is already scoped inside a project.  The tag is redundant and from time to time when files are copied from project to project this causes "errors"

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/964

**Comment by russdanner** [comment]
VERIFIED
