### ISSUE TITLE
[studio] Add to audit log when an LDAP user is added to a group in a site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1497]
Create a site named `myawesomesite` in Studio.

In your LDAP server, create a user with siteId attribute value of `myawesomesite` and group `Developer` so that when the user logs in to Studio, the user will be added to group `Developer` in the site `myawesomesite`  (I created a user `cbrunato`)

Login to Studio as the LDAP user you created above.  Verify you can preview `myawesomesite`.  Logout.

Login to Studio as `admin`.  Preview `myawesomesite`, click on `Site Config` then click on `Audit`.  Notice that there is no log when the LDAP user was added to the group in the site.

Here is the `Developer` group for `myawesomesite`, notice that the user `cbrunato` is part of the `Developer` group

<img width="1218" alt="screen shot 2017-10-27 at 7 52 49 am" src="https://user-images.githubusercontent.com/25483966/32110277-fbd8e894-baeb-11e7-962b-c184e639ff4e.png">

Click `Audit` and notice that there is no log when the user `cbrunato` was added to the site

<img width="1221" alt="screen shot 2017-10-27 at 7 54 51 am" src="https://user-images.githubusercontent.com/25483966/32110406-4feae19e-baec-11e7-8865-044dd7afb575.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/943

**Comment by alhambrav** [comment]
Hi!  There's no entry in the **Site Config** -> **Audit** of the LDAP user being added to the site. 
 There's an error in the tomcat log when I log in as an LDAP user:
https://gist.github.com/alhambrav/d4f332cc42836df0cc3b590f90f20e31

**Comment by alhambrav** [comment]
Verified fixed.
