### ISSUE TITLE
[studio-ui] Groups screens in Studio are not translated when the language is in Spanish or Korean

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1498]
Create a site in Studio.
Change the language to either Spanish or Korean.
Click on `Site Config` then click on `Groups`.  Notice the screen is not translated for any of the groups screen.

Groups:
Spanish
<img width="1244" alt="screen shot 2017-10-27 at 8 23 50 am" src="https://user-images.githubusercontent.com/25483966/32111774-59b3127e-baf0-11e7-9293-a4585b997082.png">

Korean
<img width="1240" alt="screen shot 2017-10-27 at 8 38 18 am" src="https://user-images.githubusercontent.com/25483966/32112475-3dbedf38-baf2-11e7-882d-67746bed03e7.png">

Create Group:

<img width="1243" alt="screen shot 2017-10-27 at 8 25 16 am" src="https://user-images.githubusercontent.com/25483966/32111783-6328247a-baf0-11e7-994c-b7c3b5310a33.png">

Edit Group:

<img width="1247" alt="screen shot 2017-10-27 at 8 26 07 am" src="https://user-images.githubusercontent.com/25483966/32111832-87f63f3a-baf0-11e7-8109-3593d0c7dc9e.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/666

**Comment by alhambrav** [comment]
Verified fixed.
