### ISSUE TITLE
[studio-ui] Studio does not display all screens in the language selected for certain conditions

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1499]
Login as admin in Studio. 
Create a site using website_editorial.
Click on `admin` at the top right bar and then click on `Settings`
Change the language to Korean or Spanish.  Notice that the items in the screen will now be translated into the selected language.
Click on `Sites` at the top right bar.  Notice that the `Sites` screen is translated into the selected language.
Click on either `Preview` or `Dashboard`.
From the `Preview` screen or the `Dashboard` screen, click on `Users` or `Sites` or the user name `admin` on the top bar.  Notice that the next screen displayed is now in English and not translated into the selected language.

Here's a sample screen:

<img width="1239" alt="screen shot 2017-10-27 at 8 57 22 am" src="https://user-images.githubusercontent.com/25483966/32113483-4cce10d6-baf5-11e7-8e29-04e1168411c2.png">

Here's a short clip showing the behavior:
https://www.useloom.com/share/135914f952a6446183112ec211d742ce

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/666

**Comment by alhambrav** [comment]
Verified fixed.
