### ISSUE TITLE
CRAFTERCMS-1385: Refactor spring context configuration and properties

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#15]
Original JIRA Fix Versions:
2.6.0, Original JIRA Components:
Studio, 
----------
Original JIRA Description: :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1385
----------

**Comment by russdanner** [comment]
Alfonso fixed

**Comment by dejan-brkic** [comment]
Idea of this ticket is not only enabling good and easy overlay context, but also to clean up and rename beans and properties (to add some structure and naming convention)

**Comment by russdanner** [comment]
Move to scheduled and change milestone to 2.6.0 then

**Comment by sumerjabri** [comment]
@dejan-brkic is this still valid?

**Comment by dejan-brkic** [comment]
Since we will port to YAML style config, maybe it is better to close this one and open new one with proper title/description
