### ISSUE TITLE
[studio-ui] RTE does not support valid HTML5 nested anchor

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#1500]
With a markup like this

```
     <a href="#">
            <div class="tile-block-inner" style="">
                <img src="/images/tiles-layout/people.jpg" alt="">
                <div class="tile-block-header">
                    <span>Human Resources <span class="sub">Lorem Ipsum Dolor Sit Amet</span></span>
                </div>
            </div>
        </a>
```
once content form is saved and submitted, the anchor is stripped/removed

Thanks in advance

**Comment by jvega190** [comment]
To enable support for valid HTML5 nested anchor, this configuration needs to be set:
`<validChildren>+a[div|h1|h2|h3|h4|h5|h6|p|#text]</validChildren>` (with the elements to be allowed)
and in the rte control, `Force Root Block p Tag` needs to be disabled

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation, PR in studio is not needed for testing, only configuration mentioned above. Please let me know if you need any details

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
@sumerjabri should we add this to RTE config in docs?

**Comment by sumerjabri** [comment]
@alhambrav, please do

**Comment by alhambrav** [comment]
The above PR https://github.com/craftercms/docs/pull/1299 has the docs on how to enable support for valid HTML5 nested anchor.  Thanks.
