### ISSUE TITLE
[studio-ui] consolidate bulk upload and upload as a single upload option on side bar

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1501]
There's no reason to support both a single file upload and a bulk upload as independent operations on the asset-root side bar plugin.  Remove the single file upload option and rename Bulk Upload to Upload

https://www.useloom.com/share/2f05b28f064c4cc584d71daaa143c7b5

**Comment by sumerjabri** [comment]
@russdanner what I've seen is the addition of "Select files from your computer" "Drag and drop files here" both in the same dialog. I think that would work, we just need to design the experience and then implement it.

**Comment by sumerjabri** [comment]
We built a new uploader.
