### ISSUE TITLE
[studio-ui] its no longer possible to create a template for a new content type

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1503]
go to the content type editor
create a new content type
click the pencil on the template
it should prompt the user for a new template name but it no longer does.

https://www.useloom.com/share/a5d2544b2b5d4c258e20d40ff2ccbe13

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/665

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/675

**Comment by russdanner** [comment]
VERIFIED
