### ISSUE TITLE
[studio] Add parameter filter/check to all services (2.5/3.0)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1506]

**Comment by dejan-brkic** [comment]
2.5.x branch done
PR:
https://github.com/craftercms/studio/pull/925

**Comment by sumerjabri** [comment]
@avasquez614 please test 2.5 while Dejan works on 3.0

**Comment by dejan-brkic** [comment]
3.0 branch done:
https://github.com/craftercms/studio/pull/927

2.5.x updates:
https://github.com/craftercms/studio/pull/928

**Comment by avasquez614** [comment]
Test and verified
