### ISSUE TITLE
[studio] `Published by` is not populated when editing on disk

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1510]
Steps to Reproduce
===============
- Create a site
- Edit files on disk and commit them
- Sync from repo
- Go to dashboard, `Published by` is not populated
![dashboard](https://user-images.githubusercontent.com/3931908/32176875-2bfa0718-bd5f-11e7-9136-9f75b2424434.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/944
