### ISSUE TITLE
[studio-ui] Publishing dialog doesn't complete loading

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1511]
Steps to Reproduce
===============
1. Create a site based on Editorial BP
2. Create an article, called `1` under the folder `articles`
3. Right-click `1` and click `Approve and Publish`
4. the Publish dialog comes up, it starts to load deps and never finishes

**Comment by jvega-crafter** [comment]
This is a duplicate of https://github.com/craftercms/craftercms/issues/1504,
fixed on craftercms/studio-ui#663
