### ISSUE TITLE
[studio] Studio should call preview sync when a config file is saved

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1513]
Right now whenever a file like `config/engine/site-config.xml` is saved, preview sync is not called. Preview sync should be called so the Deployer knows a config file has been updated and then rebuild the context automatically.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/937

**Comment by jdrossl** [comment]
Verified
