### ISSUE TITLE
[studio] Components root folder disappears from the site tree

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1514]
# Steps:

- Delete all folders under `Components`
<img width="165" alt="screen shot 2017-10-30 at 1 18 00 pm" src="https://user-images.githubusercontent.com/1236955/32191091-78421a32-bd75-11e7-8f0d-3d2b60f11993.png">
The root folders still shows up
<img width="141" alt="screen shot 2017-10-30 at 1 18 32 pm" src="https://user-images.githubusercontent.com/1236955/32191144-aa6ca0f4-bd75-11e7-8212-03fa4a46d127.png">

- Reload the page

- Click `Components`, nothing shows up and sometimes the spinner stays forever
<img width="161" alt="screen shot 2017-10-30 at 1 24 04 pm" src="https://user-images.githubusercontent.com/1236955/32191155-b07b1264-bd75-11e7-9690-26f6f92ffd82.png">

**Comment by jvega-crafter** [comment]
@dejan-brkic the foder item normally has a `folder` property as true, but on this scenario it has the property on false

Only components folder:
<img width="453" alt="screen shot 2017-10-31 at 3 50 07 pm" src="https://user-images.githubusercontent.com/18267471/32250812-9abbc4e4-be53-11e7-97f2-dc28cc31b98f.png">

With children:
<img width="450" alt="screen shot 2017-10-31 at 3 51 06 pm" src="https://user-images.githubusercontent.com/18267471/32250813-9ae5940e-be53-11e7-9c05-4efe88d92886.png">

**Comment by dejan-brkic** [comment]
@sumerjabri @russdanner This is not valid use case. User should not be able to delete components folder. Please verify if we want to support this use case.

**Comment by sumerjabri** [comment]
@dejan-brkic the user didn't delete the components folder, they deleted all folders under it and there was no `.keep`

**Comment by dejan-brkic** [comment]
Can not reproduce

```
Studio Version Number: 3.1.1-SNAPSHOT-45408d

Build Number: 45408d52ece705a6a2d24f4aeb9fbaee56195e56
```

**Comment by jdrossl** [comment]
I was also unable to reproduce it
