### ISSUE TITLE
[studio-ui] Content-type listed as unknown for groovy (script) files in tooltip

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1517]
Content-type listed as unknown for groovy (script) files in tooltip:

![screen shot 2017-10-31 at 11 15 13 am](https://user-images.githubusercontent.com/25483966/32231760-e03b969c-be2c-11e7-9f20-93f0984f7de2.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/668

**Comment by alhambrav** [comment]
Verified fixed.
