### ISSUE TITLE
[studio-ui] Asset filenames with a parenthesis in the name has content type listed as unknown and if the name is long, goes out of the tooltip box

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1518]
Asset filenames with a parenthesis in the name has content type listed as unknown and if the name is long, filename goes out of the tooltip box

To see the content type of an asset listed as **unknown**, rename an image to a name with parenthesis, for example **test-image(unknown)**

To see the filename going outside of the tooltip box when you hover your mouse over the image file, create a really long name including a parenthesis in the name, example is **Hidden_Valley_Bandstand_-2017_Volunteer_Org_Chart(3-13-17) copy-bmp**

Here's a screenshot of a very long filename going outside of the tooltip box, and notice that the content-type is listed as unknown:

![screen shot 2017-10-31 at 11 07 21 am](https://user-images.githubusercontent.com/25483966/32231452-fe368716-be2b-11e7-9e23-01ce12ac01b0.png)

Notice that if you remove the parenthesis in the filename,  the content-type is recognized.  Also, for very long filenames, if you remove the parenthesis, it's able to display correctly in the tooltips without going outside of the box.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/709

**Comment by alhambrav** [comment]
Verified that content-type is not shown as **unknown** in tooltip.  

Hi!  It seems like the text still goes outside of the tooltip box.

<img width="594" alt="screen shot 2017-12-06 at 12 37 25 am" src="https://user-images.githubusercontent.com/25483966/33646500-d24e83a2-da1d-11e7-862a-9d70d128bbc2.png">

**Comment by alhambrav** [comment]
Verified fixed.
