### ISSUE TITLE
[studio] Publishing static assets is broken

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1533]
Steps to Reproduce
================
* create a site using Editorial BP
* edit `main.js` under `static-assets/js`
* publish `main.js`

Error: https://gist.github.com/sumerjabri/1952c24c95f8fd27ab962833ebccf7a6

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/930
