### ISSUE TITLE
[studio-ui] Processing spinner does not go away from the page after publishing

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1535]
Create a site in Studio.
Edit a page.
Publish the page.  Notice the spinner on the middle of the page doesn't go away until you refresh the page.

<img width="1398" alt="screen shot 2017-11-03 at 1 51 34 am" src="https://user-images.githubusercontent.com/25483966/32361751-cfb13782-c039-11e7-9868-18157ecb9364.png">

Here's a short clip:
https://www.useloom.com/share/9a24c40dae364d1fa45a6ab190e8c5b1

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/672

**Comment by alhambrav** [comment]
Verified fixed.
