### ISSUE TITLE
[craftercms] init-site.sh has hardcoded values

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1540]
Steps to Reproduce
===============
* From an installed bundle on delivery, run `init.sh` with a remote authoring node
* Produces a warning:
```
bin/init-site.sh: line 7: cd: /opt/crafter/../crafter-authoring: No such file or directory
Creating Solr Core
{"message":"OK"}
Creating Deployer Target
{"message":"OK"}
```

**Comment by cortiz** [comment]
So, The script was okish, 
Issue was that by default the script tries to look for `crafter-authoring folder` to get the site repo, If you send the path as a second it works ok.

PR #1568 I add  a couple of checks before doing the actual work:
* Checks if default path exist, if not ask for the 2 argument for the path.
* Checks that the given path  does exist, if not script will fail.

**Comment by mcgitty** [comment]
Here is a suggestion: https://github.com/craftercms/craftercms/issues/1569
