### ISSUE TITLE
[studio] Authoring and delivery site displays different content when Studio is restored

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1541]
Authoring and delivery site has different content when Studio is restored.  When an authoring backup is restored, the delivery site still displays content before the restore for authoring was done.

Create a site.
Setup site for delivery environment by running the init-site script in the delivery folder.
Edit a page and publish it. (I added `zzz` to the author in Hero title) 
View the site in delivery to check the changes you made in authoring are visible in delivery.
Backup both authoring and delivery by running `./crafter.sh backup`
Edit the page again publish it. (I added `111` to the author in Hero title, so the title is now `HTML5 UP zzz 111`)  Verify changes are pushed to delivery.
Stop the authoring environment.
Restore the authoring environment using the backup file we created earlier.
View the authoring and delivery site.  Notice that the content in delivery is different from the content in authoring.
Here's the authoring:
![screen shot 2017-11-06 at 10 55 58 am](https://user-images.githubusercontent.com/25483966/32450101-5ae49624-c2e1-11e7-9677-eef9183760e2.png)

Here's the delivery:
![screen shot 2017-11-06 at 10 55 52 am](https://user-images.githubusercontent.com/25483966/32450131-74760c1c-c2e1-11e7-908d-656938cd5b0b.png)

**Comment by jdrossl** [comment]
@sumerjabri how should we handle cases like this? If the user only restores authoring delivery will keep polling the repo for changes and it could even face a conflict if an outdated (from the backup) file is published

**Comment by sumerjabri** [comment]
@alhambrav please update the documentation to indicate that the user must do one of:
* restore `delivery` when they restore `authoring`
* re-init `delivery` (delete all data and use `init-site.sh/bat`) for all sites
* manually delete the git repos and clear out the solr cores but keep the deployer configs so they'd re-sync (hardest) <== not sure if we need to document this necessarily because it'll hard to get right unless you know what you're doing

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/394

**Comment by alhambrav** [comment]
Verified.  Added to documentation that user will need to restore or re-init delivery environment when the authoring environment is restored to avoid conflicts.
