### ISSUE TITLE
[studio-ui] Parent folder disappears when child folder is deleted and the studio page is refreshed (user only wants to delete the child folder)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1542]
**Preconditions**
=========
1) Create a site using WebSite Editorial

**Steps**
==========

1. Create a new Folder under Home (named: **Parent** )
2. Create a new child Folder under **Parent** folder of above
3. Delete the child Folder
4. Refresh the all studio page

**Current Behavior**
===========
3. The Parent folder is displayed as fulfill content (+/- icon aside of it)
4. The Parent folder disappears after refresh
Watch the next video:
https://www.useloom.com/share/8dc300035ae24caa90f9926aeac5fc78

**Expected Behavior**
===========
3. The Parent folder should not be displayed as fulfill content (no "+/- " icon  displayed aside of it)
4. The Parent folder should not disappear after refresh

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/948

**Comment by luishernandezmonge** [comment]
Verified as fixed
