### ISSUE TITLE
[studio-ui] Items waiting for approval widget in the dashboard displays the "Publish Date & Time" in UTC instead of the user's time zone

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1545]
Items waiting for approval widget in the dashboard displays the "Publish Date & Time" in UTC instead of the user's time zone

Login as an author and edit a page then request to publish at a later time.  In the example below, the requested publish time is 3:45pm EST5EDT

![screen shot 2017-11-06 at 2 57 33 pm](https://user-images.githubusercontent.com/25483966/32461352-7fd2e75c-c303-11e7-8583-8bc45afdb825.png)

Logout, then login as `admin` in Studio.
Look at the dashboard and notice the time displayed for `Publish Date & Time` in the `Items Waiting For Approval` widget is in UTC instead of the user's time zone, which is EST5EDT (requested time to publish was 3:45PM EST5EDT).

![screen shot 2017-11-06 at 2 57 56 pm](https://user-images.githubusercontent.com/25483966/32461405-bad990c6-c303-11e7-8ef8-f5654cfc81c9.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/674

**Comment by alhambrav** [comment]
Verified fixed.
