### ISSUE TITLE
[studio-ui] There are two "Your session has expired due to inactivity" dialogs when the last screen before inactivity is one of the editing forms

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1548]
Create a site using website_editorial.
Edit a page.  Leave the page in the edit form for the session to time out

![screen shot 2017-11-06 at 4 15 40 pm](https://user-images.githubusercontent.com/25483966/32464383-d21d70a4-c30d-11e7-8383-e9000d89f316.png)

(I set my session time out to 1 minute in the studio-config-override.yaml file)  Notice that there are two "Your session has expired due to inactivity" dialogs that appear when in the edit form.

![screen shot 2017-11-06 at 3 58 41 pm](https://user-images.githubusercontent.com/25483966/32464484-37420134-c30e-11e7-9ee3-4635cb4b4fa6.png)

Here's a relatively short clip, with the timeout set to 1 minute:
https://www.useloom.com/share/a074c5eac50c4b3083b5617c5099c516

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/681

**Comment by alhambrav** [comment]
Verified fixed.
