### ISSUE TITLE
[studio-ui] Static asset with # in file name causes issues

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1550]
Per our conversation: Create a static-asset with a file name containing `#` and UI will show it as deleted.

**Comment by dejan-brkic** [comment]
This is UI bug. Backend sends correct url value for dashboard. When user checks check box in dashboard or right clicks in navigation context url is not handled properly.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/688

**Comment by sumerjabri** [comment]
Still occurring, here is how to reproduce:
* Find an image file on your disk, say a PNG, and rename it to `test#ing.png`
* Create a site
* Go to static assets
* Upload the file `test#ing.png`
* Note that you can't click it to preview it
* Note that you don't see it in Dashboard

Ping me if you need help reproducing the issue.

**Comment by sumerjabri** [comment]
Verified fixed after clearing my cache.
