### ISSUE TITLE
[deployer] Investigate if JSch can be configured to accept ECDSA fingerprints

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1552]
Check if JSch can accept ECDSA fingerprints to avoid having to ssh first with `ssh -o HostKeyAlgorithms=ssh-rsa SERVER_NAME`. For reference check: https://stackoverflow.com/questions/34475366/jsch-unknownhostkey-exception-even-when-the-hostkey-fingerprint-is-present-in-t.

**Comment by jdrossl** [comment]
Verified
