### ISSUE TITLE
[docs] Add documentation to troubleshoot deployments in Delivery

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1555]
* unknown host error -> do ssh with RSA fingerprint
* merging error -> reset hard and delete processed commits

**Comment by avasquez614** [comment]
PR craftercms/docs#389

@alhambrav let me know if there's any issue understanding the doc or there are any grammatical errors.

**Comment by alhambrav** [comment]
@avasquez614 The doc looks good.
