### ISSUE TITLE
[studio] Cancel workflow and reject actions change state of previously published content

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1557]
Applies to 2.5

# steps to reproduce
1. create a simple site
2. publish everything (bulk publish /)
3. once everything is live, as an author make a simple edit to a page
4. submit the edit to workflow
5. cancel the workflow, note all objects, even previously published items are calculated
6. confirm cancel and note live object states are changed to edit

https://www.useloom.com/share/89b8d3900d6e42e39585d602dcc5d02f

Note REJECTING workflow has the same effect

# correct behavior
Only those items which were previously edited should have been calculated for workflow in the first place.  Items that are currently live and have not been edited should not be part of the rejection and thus should have no state transition.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/933

**Comment by russdanner** [comment]
Confirmed
