### ISSUE TITLE
[studio-ui] item selector drop down does not close after adding items via browse

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1558]
applies to 2.5

# reproducing the issue
https://www.useloom.com/share/9d36d0375a5a432ebb6991263d22c2cb

This appears to affect only browse.
The add button drop-down should close after any "add" user action

**Comment by jvega-crafter** [comment]
Also fixed for similar cases on other datasources

**Comment by jvega-crafter** [comment]
3.0: https://github.com/craftercms/studio-ui/pull/679
2.5.x: https://github.com/craftercms/studio-ui/pull/680

**Comment by russdanner** [comment]
VERIFIED
