### ISSUE TITLE
[craftercms] There is a typo in the restore section of crafter.bat

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1562]
When you run `crafter.bat restore <backup_file>`, it says `findst` is not recognized as an internal or external command.  (Should it be `findstr`?)

Line 160:
```
netstat -o -n -a | findst startMongodbr "0.0.0.0:%TOMCAT_HTTP_PORT%"
```

Also, if I fix the typo and run the restore script, the script continues to try to restore the backup file even if Studio is still running. (It stops the script before and tells the user to please stop the system before starting the restore process)

**Comment by jdrossl** [comment]
Fixed in https://github.com/craftercms/craftercms/pull/1567

**Comment by alhambrav** [comment]
Verified fixed.
