### ISSUE TITLE
[studio] Update WorkflowServiceImpl getWorkflowAffectedPathsInternal to return only items that are in workflow

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1563]
getWorkflowAffectedPathsInternal in WorkflowServiceImpl currently returns all dependencies.  Downstream consumers which include the cancel dialog and the cancel workflow action.
Currently:
* The dialog shows all dependencies.
* The cancel workflow operation performs its own filtering.

# expected result
* Dialog should return to the user only those dependency items which are in workflow
* Cancel workflow action should impact only those dependency items which are in workflow

# Related RP
* Updated cancel workflow method to filter items.  
* https://github.com/craftercms/studio/commit/2606378
At the time of this fix, the performance of the dialog was a concern.

**Comment by dejan-brkic** [comment]
This is fixed with new dependency service implementation

**Comment by russdanner** [comment]
Confirmed
