### ISSUE TITLE
[studio-ui] approve and publish should be part of right click on side bar when item is in workflow

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1564]
approve and publish should be part of right click on side bar when item is in workflow
* Assuming user has the rights to approve and publish

<img width="627" alt="screen shot 2017-11-07 at 12 54 17 pm" src="https://user-images.githubusercontent.com/169432/32509667-f720468e-c3bb-11e7-9a67-f00606481e18.png">

It should be in the same position as seen when item is edited and user has rights to approve/publish

<img width="236" alt="screen shot 2017-11-07 at 1 04 34 pm" src="https://user-images.githubusercontent.com/169432/32509715-2ae793b4-c3bc-11e7-8c47-817bd10a171a.png">

**Comment by russdanner** [comment]
please fix for 2.x and 3.x

**Comment by vestrada** [comment]
PR 2.5.x: https://github.com/craftercms/studio-ui/pull/758

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/760

**Comment by russdanner** [comment]
VERIFIED

**Comment by russdanner** [comment]
Confirmed
