### ISSUE TITLE
init-site.sh produces error when run without authoring

### ISSUE THREAD

**Issue by mcgitty** [craftercms/craftercms#1569]
https://github.com/craftercms/craftercms/blob/807b18a0f16d9d1e18dca441d5a36ff4720c5d1d/resources/crafter/init-site.sh#L47

The cd command in line 47 produces this error when the sister folder 'crafter-authoring' does not exist, for example, in a real delivery server:

    ./init-site.sh: line 7: cd: /mnt/crafter/delivery/../crafter-authoring: No such file or directory Creating Solr Core

Line 47 can use this less intrusive version:

    export AUTHORING_ROOT="${DELIVERY_ROOT%/*}/crafter-authoring"

**Comment by cortiz** [comment]
@mcgitty the script  'pre flight' check should verify that the folder exist or that the path is send, there is a type however on that 'pre flight' that was solve on #1571
