### ISSUE TITLE
[studio-ui] timeout login dialog shows multiple times after long idle periods

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1577]
### Expected behavior
* Once the timeout login the user, additional dialogs should not be popped up

### Actual behavior
<img width="1407" alt="screen shot 2017-11-08 at 3 39 49 pm" src="https://user-images.githubusercontent.com/169432/32573242-54659044-c49b-11e7-86c5-6b175730dafa.png">

### Steps to reproduce the problem
* sign in
* make an edit
* wait for the first timeout
* wait for the the next timeout

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
N/A (Chrome/OSX)

**Comment by vestrada** [comment]
This is already fixed.
Ref: https://github.com/craftercms/craftercms/issues/1548

**Comment by russdanner** [comment]
VERIFIED, CANNOT REPRODUCE after 24 hour sit
