### ISSUE TITLE
[studio-ui] Version History for configurations displays "undefined" for the "Version Date and Time" instead of a valid date and time

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1578]
### Expected behavior
Version History for configurations should display a valid date and time for the "Version Date and Time" field.

### Actual behavior
Version History for configurations displays "Version Date and Time"  as **undefined**

### Steps to reproduce the problem
*  Create a site using any bp
*  Open the **Sidebar** and click on **Site Config**
*  Click on **Configuration** and select any configuration listed from the dropdown box
*  Click on **History** at the top, notice the column for "Version Date and Time" displays **undefined**

![screen shot 2017-11-09 at 10 18 20 am](https://user-images.githubusercontent.com/25483966/32612897-70bcc9d2-c537-11e7-80ab-bf96d0d67838.png)

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.2-SNAPSHOT-bcd638
Build Number: bcd63822d17c1965788f1c24587ce63a1cc9f457
Build Date/Time: 11-09-2017 10:05:22 -0500
OS X, Chrome browser

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/685

**Comment by alhambrav** [comment]
Verified fixed.
