### ISSUE TITLE
[studio-ui] User reviewer does not have access to History of pages from the context nav or right click

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1579]
### Expected behavior
User reviewer should have access to History to view (not revert) from the context nav or right click

### Actual behavior
User reviewer does not have access to History of pages from the context nav or right click

### Steps to reproduce the problem
*  Create a site using website_editorial bp
*  Create a reviewer user and add to group reviewer in the site created in the previous step
*  Login as the reviewer user, preview the Home Page, notice the items listed in the context nav, there's no **History** available
*  From the **Sidebar**, right click on **Home** and notice the items listed, there's no **History**

![screen shot 2017-11-09 at 10 36 54 am](https://user-images.githubusercontent.com/25483966/32614019-4ff5e550-c53a-11e7-9d91-ac5ed8e85a62.png)

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-bcd638
Build Number: bcd63822d17c1965788f1c24587ce63a1cc9f457
Build Date/Time: 11-09-2017 10:05:22 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/937

**Comment by alhambrav** [comment]
Verified fixed.
