### ISSUE TITLE
[studio-ui] In-context edit pencils are visible for user Reviewer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1580]
### Expected behavior
In-context edit pencils should not be visible for user Reviewer in preview (In-Context Edit is not available for user Reviewer from the context nav)

### Actual behavior
In-context edit pencils are visible for user Reviewer in preview

### Steps to reproduce the problem
* Create a site using Website_editorial bp
* Create a user Reviewer and add the user to the Reviewer group in the site created above
* Login as user Reviewer, preview the home page or an article, notice the pencils

![screen shot 2017-11-09 at 11 03 10 am](https://user-images.githubusercontent.com/25483966/32615761-965a81f0-c53e-11e7-995c-06d05841c030.png)

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-bcd638
Build Number: bcd63822d17c1965788f1c24587ce63a1cc9f457
Build Date/Time: 11-09-2017 10:05:22 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/683

**Comment by alhambrav** [comment]
Verified fixed.
