### ISSUE TITLE
[studio] Randomize `admin` account password for fresh install

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1583]
Please add a new configuration variable in `studio-config.yaml` that turns the following behavior on/off.

On a fresh install of Studio where the `admin` account doesn't exist, create the account with a random password of 16 characters alpha-numeric, mixed-case, with allowed special characters. Also, throw that password in the logs so the user can locate it.
The log message should contain: `*** Admin Account Password: "{password}" ***` make sure the password doesn't contain the character "

Please reach out with any questions.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/941

**Comment by sumerjabri** [comment]
Please see code review in PR.
