### ISSUE TITLE
[studio-ui] There are 2 separators next to each other rendered for user author when right clicking a folder under components and Home

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1586]
### Expected behavior
Only 1 separator should be rendered after the item **Rename Folder** when right clicking a folder under **components** and **Home**
### Actual behavior
There are 2 separators rendered after the item **Rename Folder** for user author when right clicking a folder under components and Home

### Steps to reproduce the problem
* Create a site using Website_editorial
* Create a user Author and add to the newly created site
* Login as user Author, then navigate to the Home folder, expand it, then right click on the folder **articles**  Notice the items listed after right clicking, there are 2 separators after the item **Rename Folder**

* You can also navigate to **components**, expand the folder, then right click on any of the folders under **components**.  Notice the 2 separators after **Rename Folder**

<img width="925" alt="screen shot 2017-11-13 at 11 21 21 am" src="https://user-images.githubusercontent.com/25483966/32736268-0042c7ac-c865-11e7-8684-7193e428785a.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-5d27af
Build Number: 5d27afa7c659049a8cb3fd830f3bfebb119904a9
Build Date/Time: 11-13-2017 09:26:43 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/693

**Comment by alhambrav** [comment]
Verified fixed.
