### ISSUE TITLE
[studio-ui] User Reviewer is able to access the edit form from the dependencies dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1588]
### Expected behavior
User Reviewer should only be shown a read only of the form from the dependencies dialog like below:

<img width="1388" alt="screen shot 2017-11-13 at 2 17 47 pm" src="https://user-images.githubusercontent.com/25483966/32744432-7b0405e2-c87d-11e7-8cd5-a5e0d6165443.png">

### Actual behavior
User Reviewer is able to access the edit form from the dependencies dialog, although, Studio does not let the user **Save and Close** or **Save Draft**

### Steps to reproduce the problem
* Create a site using Website_editorial
*  Create a user Reviewer
*  Login as user Reviewer
*  Preview the **Home** page.  
*  From the context nav, click on **Dependencies**
*  Select **Is referenced by this item** from the dropdown for **Show content that:**
*  Click on **Edit** on the right hand side of item **Three**, notice that this opens the edit form with buttons at the bottom for **Save and Close**, **Save Draft**, **Cancel**.  The user can edit things in the form but when you click on **Save and Close** or **Save Draft**, nothing happens (User Reviewer is not allowed to make edits).

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/4bda8141033a4f54b70d663ff5334db9

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-5d27af
Build Number: 5d27afa7c659049a8cb3fd830f3bfebb119904a9
Build Date/Time: 11-13-2017 09:26:43 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/689

**Comment by alhambrav** [comment]
Verified the user Reviewer cannot access the edit form.
But, I think it would be nice if the user is shown a read-only form from the dependencies like the first screenshot in the ticket?

Current behavior:  No `Edit` links in the dependencies screen for user reviewer, there's no links at all to view pages/components.

<img width="957" alt="screen shot 2017-11-15 at 2 18 52 pm" src="https://user-images.githubusercontent.com/25483966/32855529-f4d12858-ca0f-11e7-8ac9-2c4936ff492b.png">


Desired behavior: User Reviewer should have a `View` link from the dependencies dialog if an item is viewable, which would display a Read-Only form, or something like that.

@sumerjabri , @russdanner , what do you think should be the expected behavior when user Reviewer looks at the dependencies dialog?  Should the user Reviewer be able to view items that are previewable from the dependencies dialog?

**Comment by russdanner** [comment]
VERIFIED
