### ISSUE TITLE
[studio-ui] User Author should be allowed to create folders under "components" and "static-assets" based on the permissions.xml in Website_editorial bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1589]
### Expected behavior
User Author should be allowed to create folders under **components** and **static-assets** based on the permissions.xml in Website_editorial bp

### Actual behavior
User Author cannot create folders under **components** and **static-assets** 

### Steps to reproduce the problem
*  Create a site using Website_editorial bp
*   Create a user Author
*   Login as user Author
*   Navigate to **components**, and right click on the folder, notice that you only get the items to **View** and **Copy** the folder

Here's a screenshot:

<img width="286" alt="screen shot 2017-11-13 at 2 43 38 pm" src="https://user-images.githubusercontent.com/25483966/32745599-2f1e7c80-c881-11e7-849f-6d680e415a26.png">

Here's a snippet of **permissions.xml** for role **Author** indicating the user should be able to create folders under **components** and **static-assets**

```
<permissions>
  <site id="myawesomesite">
    <role name="author">
      <rule regex="/site/website/.*">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
          <permission>Create Content</permission>
          <permission>Create Folder</permission>
        </allowed-permissions>
      </rule>
      <rule regex="/site/components/.*">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
          <permission>Create Content</permission>
          <permission>Create Folder</permission>
        </allowed-permissions>
      </rule>
      <rule regex="/static-assets/.*">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
          <permission>Create Content</permission>
          <permission>Create Folder</permission>
        </allowed-permissions>
      </rule>
    </role>
```

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-5d27af
Build Number: 5d27afa7c659049a8cb3fd830f3bfebb119904a9
Build Date/Time: 11-13-2017 09:26:43 -0500

**Comment by vestrada** [comment]
Hi @dejan-brkic 

I just checked it, and I found that we are getting a wrong response from permissions api (/api/1/services/api/1/security/get-user-permissions.json).
The result is just read, when we should get: create folder ,read , create content.

**Comment by dejan-brkic** [comment]
This is configuration issue.
```<rule regex="/site/components/.*">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
          <permission>Create Content</permission>
          <permission>Create Folder</permission>
        </allowed-permissions>
      </rule>```
Regular expression `/site/components/.*` does not include `/site/components` folder itself. Includes only its children.
Regular expression like `/site/compnents|/site/components/.*` will include folder and its children.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/954

**Comment by alhambrav** [comment]
Verified.
