### ISSUE TITLE
[studio-ui] Right click on top level folder for "templates" and "scripts" for user author should not display any items

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1590]
### Expected behavior
Right click on top level folder for "templates" and "scripts" or for folders underneath the folders mentioned, for user author should not display any items

### Actual behavior
Right click on top level folder for "templates" and "scripts" or any folder underneath the folders mentioned earlier, for user author displays **No actions available** and Dependencies

Also, **No actions available** is clickable and displays a **404** when you click on it.

### Steps to reproduce the problem
*  Create a site using Website_editorial 
*   Create a user Author and add to site
*   Login as user Author
*  Navigate to **templates** and right click on the folder.  Notice the options displayed.

<img width="526" alt="screen shot 2017-11-13 at 3 06 20 pm" src="https://user-images.githubusercontent.com/25483966/32746658-4f15f664-c884-11e7-9059-c3fcf5c3cee5.png">

* Notice also that **No actions available** is clickable.  Click on it and it displays the following:

<img width="1386" alt="screen shot 2017-11-13 at 3 07 35 pm" src="https://user-images.githubusercontent.com/25483966/32746689-682f28b4-c884-11e7-988f-8e93ba219342.png">

* The same behavior is seen when you right click on the **scripts** folder

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-5d27af
Build Number: 5d27afa7c659049a8cb3fd830f3bfebb119904a9
Build Date/Time: 11-13-2017 09:26:43 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/690

**Comment by alhambrav** [comment]
Verified fixed.
