### ISSUE TITLE
[studio-ui] User Author should be allowed to view scripts and ftl templates

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1592]
### Expected behavior
User Author should be allowed to view scripts and ftl templates when right clicking.  Also, the user should not get the option to Upload and Delete

### Actual behavior
User Author does not get the option to view scripts and ftl templates when right clicking.  When you right click, the user is given the following options for ftl templates and scripts: Upload, Delete, Dependencies

<img width="937" alt="screen shot 2017-11-14 at 12 42 23 am" src="https://user-images.githubusercontent.com/25483966/32765095-f2c45128-c8d6-11e7-9ea5-24f7d8a1b0d4.png">

### Steps to reproduce the problem
* Create a site using website_editorial bp
* Create a user Author and login as Author
* Navigate to the templates folder
* Right click on an ftl template, notice the options displayed for user Author

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-4d6c3a
Build Number: 4d6c3ae87cc1015787014c5c70d11102e0fc180e
Build Date/Time: 11-13-2017 23:45:18 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/691

**Comment by alhambrav** [comment]
Verified fixed.
