### ISSUE TITLE
[studio] It's not clear in the audit logs when a folder is renamed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1593]
### Expected behavior
When a folder is renamed it would be nice if the audit log entry contained text saying the folder was renamed from previous name to new name, or something like that.

### Actual behavior
Rename a folder and look at the audit log, it lists the folder name change as updated and notice there's two entries in the log since there are two pages under the folder that was renamed.  I am also not sure if the articles underneath the renamed folder should be marked as **Edited** since there has been no change in the articles itself, just the folder they were under?

Notice also that previous entries in the audit log containing the old name of a folder gets updated to the new folder name.

### Steps to reproduce the problem
* Create a site using website_editorial
* Navigate to Home -> articles -> 2017.
* Right click on **3** and select **Rename Folder**
* Click on **Site Config** -> **Audit**, notice the new entries when the folder is renamed

<img width="1184" alt="screen shot 2017-11-14 at 1 26 26 am" src="https://user-images.githubusercontent.com/25483966/32766071-48cd0b9c-c8db-11e7-84c3-4c8ceca3c0ca.png">

* Notice also that the articles under the renamed folder are now marked as **Edited**

<img width="324" alt="screen shot 2017-11-14 at 1 39 27 am" src="https://user-images.githubusercontent.com/25483966/32766410-d93f54ea-c8dc-11e7-8092-1e75bf0a79b4.png">

* Another thing, is, if you create a new folder, say **11** under the 2017 folder, then create a new article in the folder named **11**, notice the entries in the audit log

<img width="1185" alt="screen shot 2017-11-14 at 1 12 02 am" src="https://user-images.githubusercontent.com/25483966/32766646-e4354dae-c8dd-11e7-82d9-83bbc681621a.png">

* Now, rename the folder you created from **11** to **November**, look at the audit logs and notice that the previous entry for the folder **11** being created is now updated to the new name **November**

<img width="1182" alt="screen shot 2017-11-14 at 1 12 50 am" src="https://user-images.githubusercontent.com/25483966/32766786-6e175184-c8de-11e7-84f9-3b89277e7f82.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-4d6c3a
Build Number: 4d6c3ae87cc1015787014c5c70d11102e0fc180e
Build Date/Time: 11-13-2017 23:45:18 -0500

**Comment by sumerjabri** [comment]
@dejan-brkic ping me if you need design help for this.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/962

**Comment by alhambrav** [comment]
Verified fixed.
