### ISSUE TITLE
[docs] Please document the ability to randomize the admin password

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1594]
Please add a section in sys admin/security detailing the ability to randomize the admin password in case of a fresh start. The attributes are listed here:
https://github.com/craftercms/studio/pull/941/files

The ticket detailing the design is here:
https://github.com/craftercms/craftercms/issues/1583

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/395
