### ISSUE TITLE
[studio-ui] Workflow icon in Sidebar does not get updated when user author does a "Request Publish", until the user refreshes the browser

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1595]
### Expected behavior
When you Request Publish a page not being previewed, the workflow icon in the Sidebar for the page being published should be updated

### Actual behavior
When you Request Publish a page not being previewed, the workflow icon in the Sidebar for the page being published is not updated until the user refreshes the page

### Steps to reproduce the problem
* Create a site using website_editorial 
* Create a user Author and login as user Author
* Edit a page and save, say the article **Top Clubs In Virginia** (articles/2017/3)
* Preview the **Home** page
* In the Sidebar, navigate to the folder where the article **Top Clubs In Virginia** is (articles/2017/3)
* Right click on the article you just edited and select **Request Publish**, notice that the workflow icon for the article published is still displaying as `Edited` instead of `In Workflow`
* Now, preview the article just published, notice the workflow icon displayed in the context nav is correct `In Workflow`, but the workflow icon in the Sidebar is still `Edited`.

<img width="874" alt="screen shot 2017-11-14 at 11 27 13 am" src="https://user-images.githubusercontent.com/25483966/32791439-0a6e7cf6-c92f-11e7-9ccc-d79500de727c.png">

Here's a short clip showing the behavior:
https://www.useloom.com/share/febb82f6dfcc408aa63dee65e76ab461

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-4d6c3a
Build Number: 4d6c3ae87cc1015787014c5c70d11102e0fc180e
Build Date/Time: 11-14-2017 11:08:39 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/704

This is fixed. Also, after the request publish, the user will be redirect to the page requested publish. This for be consistent with the edit functionality.

**Comment by alhambrav** [comment]
Verified fixed.
