### ISSUE TITLE
[craftercms] `solr.pid` is not created successfully and therefore Gradle thinks its down

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1597]
### Expected behavior
`solr.pid` is created successfully and the system can be stopped/started repeatedly

### Actual behavior
`solr.pid` is not created and therefore Gradle thinks Solr is down and when you stop Studio, Solr remains up and you can't start again after stopping.

### Steps to reproduce the problem
* ./gradlew -Penv=authoring start
* find . -name 'solr.pid'
* Note `solr.pid` doesn't exist

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/sumerjabri/acc38ede8f8600b744d55a8e71ae9141

### Specs: version, OS, browser, etc.
```
Studio Version Number: 3.0.2-SNAPSHOT-4d6c3a
Build Number: 4d6c3ae87cc1015787014c5c70d11102e0fc180e
```

Linux, Chromium

**Comment by cortiz** [comment]
Unable to reproduce
