### ISSUE TITLE
[craftercms] Deploy a single module will delete the other modules

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1599]
### Expected behavior
Deploying a single module should only update the given module
### Actual behavior
Deploying a single module removes all modules but the one needed.
### Steps to reproduce the problem
*  run `./gradlew build deploy -Penv=authoring -PmoduleName=studio`

### Current Workaround
 Do not use the `-PmopduleName=` parameter

**Comment by cortiz** [comment]
@sumerjabri I Agree for now I put out the fire with #1600  and we can make a new feature ticket to have deploy dependencies and an incremental build so if a module hasn't change code skip it so we only build what's new.

**Comment by dejan-brkic** [comment]
Verified
