### ISSUE TITLE
[studio] Add CsrfFilter to Studio

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1601]
Configure Spring Security's CsrfFilter in Studio. The filter should be mapped to API requests the modify resources, like POST, PUT and DELETE. Make sure the CSRF token is returned in a header.

**Comment by sumerjabri** [comment]
@avasquez614 please make sure to update the API docs for all systems (perhaps a common article that crosses all API to indicate approach instead of updating every single API doc).

**Comment by avasquez614** [comment]
Tested and verified
