### ISSUE TITLE
[studio] Direct disk edits meta-data are not in the database

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1602]
Edit content on disk directly and commit it. The dashboards will not show a user detail for that activity and the database will contain `NULL` for first/last names and email.

### Expected behavior
Database should contain the same values in `git log`, and will not match those against the user database (because this can be a non-user or a fake user, they never auth'd against studio).

### Actual behavior
Database meta-data in `item-metadata` are `NULL`.

Proposed solution:
Populate based on git metadata, but indicate that the author hasn't been verified because it's a direct disk edit.

We will also need to update the UI to indicate that.

We will discuss how to indicate both in the database and in the UI that the user is a direct edit user.

**Comment by dejan-brkic** [comment]
Done
PR: https://github.com/craftercms/studio/pull/981
