### ISSUE TITLE
[studio-ui] Change UI to always send CSRF token on API calls

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1603]
UI will need to send CSRF token on every API call now that does a POST, PUT or DELETE. Please refer to craftercms/craftercms#1601.

**Comment by vestrada** [comment]
Waiting for: #1601.

**Comment by sumerjabri** [comment]
@vestrada @jvega-crafter don't wait on #1601 to finish, work on this now and hold off PR until 1601 is completed. Merge locally from Ross's repo and test, and then push over. Waiting may delay your part.

**Comment by jvega-crafter** [comment]
2.5.x: https://github.com/craftercms/studio-ui/pull/694

**Comment by avasquez614** [comment]
Tested and verified
