### ISSUE TITLE
[craftercms] Backup script must run from any path

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1606]
### Expected behavior
Backup will backup only Crafter assets when launched from any path

### Actual behavior
Backup backs up current folder recursively (for mysql/mongodb it seems)

### Steps to reproduce the problem
* Switch to non-craftercms folder
* Provide a long relative path to crafter.sh and ask it to backup
* Note how it backs up non-crafter artifacts

**Comment by jdrossl** [comment]
@sumerjabri can you please verify if the failing environment has all the required binaries? (`/bin/mongodb/bin/mongodump` & `/bin/dbms/bin/mysqldump`) I have been testing and the only case with a similar result is when those are missing.

**Comment by sumerjabri** [comment]
@jdrossl I don't have mongodb enabled (which is valid). MariaDB is always present, as it's part of Studio.

Please make it work if MongoDB is not present (if not present, simply don't back up MongoDB stuff).
