### ISSUE TITLE
[studio-ui] The tag <showRootItem> from the Sidebar Configuration does not seem to be working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1607]
### Expected behavior
When the **\<showRootItem\>** is set to **false** in the Sidebar Configuration, the root folder should not be displayed in the **Sidebar**

### Actual behavior
When you set the **\<showRootItem\>** to **false**, the root folder is still visible in the **Sidebar**

### Steps to reproduce the problem
*  Using website_editorial bp, click on **Site Config**
*  Click on **Configuration** and select **Sidebar Configuration** from the dropdown menu
*  Scroll down to the **Components** section and set the tag **\<showRootItems\>** to **false**
```
<!-- Components -->
<modulehook>
	<name>wcm-root-folder</name>
	<showDivider>true</showDivider>
	<params>
		<label>Components</label>
		<path>/site/components</path>
		<showRootItem>false</showRootItem>
	</params>
</modulehook>
```
* Preview the site or view the Dashboard and open the **Sidebar**, notice the root folder is still visible

<img width="1040" alt="screen shot 2017-11-16 at 11 46 39 am" src="https://user-images.githubusercontent.com/25483966/32904918-80c6a4d0-cac6-11e7-8a66-72964c5d7754.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-444089
Build Number: 44408936246be86d40b1f8d79f928fe4ab56f0a8
Build Date/Time: 11-15-2017 16:22:39 -0500

**Comment by sumerjabri** [comment]
The Sidebar has been rewritten.
