### ISSUE TITLE
[studio-ui] Text goes outside of the right click menu for a static-asset for user reviewer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1608]
### Expected behavior
Text should not go outside the right click menu for an edited/scheduled/in workflow static asset for user Reviewer

### Actual behavior
Text goes outside of the right click menu for a static-asset for user reviewer

<img width="1050" alt="screen shot 2017-11-16 at 3 29 41 pm" src="https://user-images.githubusercontent.com/25483966/32914444-9a269440-cae3-11e7-9105-be6abb88b613.png">

### Steps to reproduce the problem
* Create a site using website_editorial bp and login as user Crafter Admin (admin)
* Edit one of the images under static-assets by uploading an image with the same name as one of the existing images listed.  For my example, I uploaded a file named **book-woman-pic.jpg**, so the file is now edited.
* Create a user Reviewer and login as user Reviewer
* Right click on the edited file.  Notice that the text **Approve & Publish** goes outside of the right click menu box

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-9b78f8
Build Number: 9b78f863a7fb54266e6d88a6084daca75742b888
Build Date/Time: 11-16-2017 13:36:00 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/698

**Comment by alhambrav** [comment]
Verified fixed.
