### ISSUE TITLE
[studio-ui] The tag <showDivider> from the Sidebar Configuration does not seem to be working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1609]
### Expected behavior
A divider line between the pages, components, taxonomy, etc. is shown/hidden using the \<showDivider\> in the Sidebar Configuration or, if the tag is not supported anymore, remove/hide it?

### Actual behavior
Setting the tag \<showDivider\> to **true** or **false** does not do anything in the UI Sidebar.

### Steps to reproduce the problem
* Using website_editorial bp, click on Site Config
* Click on Configuration and select Sidebar Configuration from the dropdown menu
* Scroll down to the Components section and set the tag <showDivider> to **false**
```
<!-- Components -->
<modulehook>
	<name>wcm-root-folder</name>
	<showDivider>false</showDivider>
	<params>
		<label>Components</label>
	        <path>/site/components</path>
		<showRootItem>false</showRootItem>
	</params>
</modulehook>
```
Notice that nothing happens when you look at the Sidebar after saving your changes for the Sidebar Configuration file.

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-9b78f8
Build Number: 9b78f863a7fb54266e6d88a6084daca75742b888
Build Date/Time: 11-16-2017 13:36:00 -0500

**Comment by sumerjabri** [comment]
Let's remove from all BPs as this doesn't exist in the new codebase.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/966

**Comment by alhambrav** [comment]
Verified.
