### ISSUE TITLE
[studio-ui] Do not allow folder renames for root folders in the Sidebar

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1610]
### Expected behavior
Right clicking on root folders (components, taxonomy, static-assets, etc) in the Sidebar should not give the user the option to rename the folder

### Actual behavior
When a user right clicks on a root folder, it gives the user an option to rename the folder

<img width="315" alt="screen shot 2017-11-16 at 1 08 56 pm" src="https://user-images.githubusercontent.com/25483966/32915530-38331ff2-cae7-11e7-9da2-a66461c4f774.png">

### Steps to reproduce the problem
*  Create a site using any of the blueprints available
*  Navigate to a root folder in the **Sidebar**
*  Right click on the root folder (example of a root folder is **static-assets**)
Notice that the user is given the option **Rename Folder**

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-9b78f8
Build Number: 9b78f863a7fb54266e6d88a6084daca75742b888
Build Date/Time: 11-16-2017 13:36:00 -0500

**Comment by sumerjabri** [comment]
@jvega-crafter @vestrada ping Roy when you have an approach to solve this, once you have an approach, ping me for final review and approval.

**Comment by sumerjabri** [comment]
@alhambrav please see if you can resolve this via permissions just like we did https://github.com/craftercms/craftercms/issues/1589

If so, please update all BPs to have the correct permissions to get the behavior we want.

**Comment by vestrada** [comment]
Sumer regarding I talked with Vita, and she told me that with the permissions that we have right now we can't validate "rename folder". If we want to do through permission we have to add a new permission.

The other way is to validate if the item is a root folder, I already have talked with Dejan about it, he told me that item don't have a property with that info.

This will be worked on other release.

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/96778086-61bad600-13a8-11eb-89fc-13efb55ccfb4.png)
