### ISSUE TITLE
[studio] Deleting the Parent wrapper is not deleting the associated child 

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1616]
Create wrapper content type - wrapping a asset file
Add new wrapper content with associated asset file
Publish content
Delete wrapper content

Error: associated asset is not deleted with wrapper content

Expected Behavior:
Associated asset should be deleted when wrapper content is deleted

**Comment by dejan-brkic** [comment]
2.5.x Fixed
PR:
https://github.com/craftercms/studio/pull/950

**Comment by dejan-brkic** [comment]
3.0 Fixed

PR:
https://github.com/craftercms/studio/pull/952

**Comment by russdanner** [comment]
VERIFIED
