### ISSUE TITLE
[Docs] CrafterCMS gradle tool properties (-Pxxx) actual values are in description and not property  

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1618]
Under http://docs.craftercms.org/en/3.0/developers/projects/craftercms/index.html the actual valid properties are under the `Description` header and not under `property` header. 

This can confuse users on which value should be use to the CLI 

### Expected behavior
![goodcli](https://user-images.githubusercontent.com/574641/32964624-722b6342-cb99-11e7-8df1-066ef765b282.png)

### Actual behavior
![wrongclidoc](https://user-images.githubusercontent.com/574641/32964535-322d4724-cb99-11e7-8c33-3ace5b32d104.png)

We could remove the current text under `Property` header since they are variables of the Gradle script.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/396
