### ISSUE TITLE
[studio] "Show In-Progress Item" doesn't show all in-progress items (hides things that start with the same name)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1620]
### Expected behavior
Show all in-progress items

### Actual behavior
Shows partial in-progress items

### Steps to reproduce the problem
* Add/edit files that start with the same path, example: /fonts/slick.svg, /fonts/slick.tff, /fonts/slick.woff
* Click on Show In-Progress Items
* Only one of those files shows up

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.2-SNAPSHOT-813ce6
Build Number: 813ce6664a5d7138f89d3d3564660547132c6ecf
Build Date/Time: 11-17-2017 14:39:02 -0500
Linux, Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/953
