### ISSUE TITLE
[studio-ui] User Publisher should have the option to Approve & Publish instead of Request Publish when right clicking on Scripts and Templates

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1624]
### Expected behavior
User Publisher should have the option to **Approve & Publish** instead of **Request Publish** when right clicking on Scripts and Templates

### Actual behavior
User Publisher gets the **Request Publish** when right clicking on Scripts and Templates

### Steps to reproduce the problem
* Create a site using Website_editorial
* Create a user Publisher
* Edit a script and save, and, edit a template and save
* Logout, then login as user Publisher
* Navigate to Templates/Scripts folder
* Right click on the edited template/script, notice that the right click menu displays **Request Publish** instead of **Approve & Publish**

![screen shot 2017-11-20 at 10 20 15 am](https://user-images.githubusercontent.com/25483966/33025652-904a9ad8-cddc-11e7-96b6-c2f3ca45ab26.png)

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-813ce6
Build Number: 813ce6664a5d7138f89d3d3564660547132c6ecf
Build Date/Time: 11-20-2017 09:42:25 -0500

**Comment by vestrada** [comment]
It was a permission issue.
PR: https://github.com/craftercms/studio/pull/959

**Comment by alhambrav** [comment]
Verified fixed.
