### ISSUE TITLE
[studio-ui] Insert component, layout and stub RTE dropdowns wrap early and do not allow scroll

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1625]
### Expected behavior
* Dropdown should resize the width to match the text.  
* Dropdown should be scrollable after it reaches 80% of the length of the window.

### Actual behavior
![screen shot 2017-10-30 at 10 48 05 am](https://user-images.githubusercontent.com/169432/33035944-e74be8fa-cdfa-11e7-8f3d-562779e7d3a1.png)

### Steps to reproduce the problem
* configure a lot of components to the RTE insert stubs
* Open RTE

Applies to 2.x and 3.x

**Comment by russdanner** [comment]
Relevant styles
```
rteSkin .mceToolbar .mceMenu span.mceText {
... 
}
```

**Comment by vestrada** [comment]
PR - master: https://github.com/craftercms/studio-ui/pull/695
PR - 2.5.x: https://github.com/craftercms/studio-ui/pull/696

**Comment by russdanner** [comment]
VERIFIED
