### ISSUE TITLE
[studio] Folder created when adding new content is not deleted when you delete a page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1626]
### Expected behavior
Folder created when adding new content should be deleted when you delete a page and not appear in the site tree when you refresh the page

### Actual behavior
Folder created when adding new content is not deleted when you delete a page, and when you refresh the page, the leftover folder is visible in the site tree

### Steps to reproduce the problem
*  Create a site using Website_editorial
*  Delete one of the article pages OR Create a new page and then delete the newly created page 
*  Refresh your browser, notice that a folder named after the article you just deleted is visible in the site tree.  In the screenshot below, I created an article titled **new**, then deleted it.  After deleting, I refreshed the browser and noticed the folder **new** is listed in the site tree

![screen shot 2017-11-20 at 2 45 49 pm](https://user-images.githubusercontent.com/25483966/33038239-fba47f04-ce01-11e7-9a55-aecef31f0d37.png)

* Click on **Site Config** then **Audit**.
Notice the entries created when the article was created:
```
admin | /site/website/articles/2016/12/new | CREATED | 11-20-2017 02:43:20 pm (EST5EDT) | 11-20-2017 02:43:20 pm (EST5EDT)
-- | -- | -- | -- | --
admin | /site/website/articles/2016/12/new/index.xml | CREATED | 11-20-2017 02:43:20 pm (EST5EDT) | 11-20-2017 02:43:20 pm (EST5EDT)
```

Then, notice the entries added when the article **new** was deleted.  There are two entries deleting the same file 
```
admin admin | /site/website/articles/2016/12/new/index.xml | DELETED | 11-20-2017 02:44:09 pm (EST5EDT) | 11-20-2017 02:44:09 pm (EST5EDT)
-- | -- | -- | -- | --
admin | /site/website/articles/2016/12/new/index.xml | DELETED | 11-20-2017 02:44:07 pm (EST5EDT) | 11-20-2017 02:44:07 pm (EST5EDT)
```
Also notice, that there is no entry deleting the folder created for the article (**/site/website/articles/2016/12/new**)
 
If you look in the audit logs from the db, the create and delete entries look like this:
```
| 24 | 2017-11-20 14:43:20 | 2017-11-20 14:43:20 | {"user":"admin","id":"/site/website/articles/2016/12/new","contentType":"folder"}                                                  | json           | /site/website/articles/2016/12/new                                                   | anotherawesomesite | CREATED           | folder       | admin        | UI         |
| 25 | 2017-11-20 14:43:20 | 2017-11-20 14:43:20 | {"user":"admin","id":"/site/website/articles/2016/12/new/index.xml","contentType":"page"}                                          | json           | /site/website/articles/2016/12/new/index.xml                                         | anotherawesomesite | CREATED           | page         | admin        | UI         |
| 26 | 2017-11-20 14:44:07 | 2017-11-20 14:44:07 | {"user":"admin","id":"/site/website/articles/2016/12/new/index.xml","contentType":"page"}                                          | json           | /site/website/articles/2016/12/new/index.xml                                         | anotherawesomesite | DELETED           | page         | admin        | UI         |
| 27 | 2017-11-20 14:44:09 | 2017-11-20 14:44:09 | {"user":"admin admin","id":"/site/website/articles/2016/12/new/index.xml","contentType":"page"}                                    | json           | /site/website/articles/2016/12/new/index.xml                                         | anotherawesomesite | DELETED           | page         | admin admin  | REPOSITORY |
```
### Log/stack trace (use https://gist.github.com)
Here's a short clip showing an article being deleted and the folder left behind in the site tree:
https://www.useloom.com/share/65df14d7217e4562be10c80f2f8aaa9b

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-3508fc
Build Number: 3508fc6f0a848e21230f9ccd16f1ee7e48be655b
Build Date/Time: 11-20-2017 14:24:04 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/958

**Comment by alhambrav** [comment]
Verified fixed.
