### ISSUE TITLE
[studio-ui] Edit template from preview fails when template has upper case letters in its file name

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1627]
### Expected behavior
Edit template should use whatever file name is given in the content

### Actual behavior
Edit template action from preview attempts to create a new file with all lower case characters

### Steps to reproduce the problem
* Create a template manually through side bar
* Associate to content type and create an object
* Go to preview and click edit template

**Comment by sumerjabri** [comment]
@russdanner do we want to support mixed-case template names?

**Comment by vestrada** [comment]
Hi @russdanner 

I tried to reproduced this issue in crafter 3 as the ticket said, but I can' reproduced it.

Please watch the following video, and let me know: https://www.useloom.com/share/53c0f1c4b7584942b511b855b89c5e27

**Comment by russdanner** [comment]
VERIFIED CANNOT REPRODUCE
