### ISSUE TITLE
[engine] expire_dt with dates past expiration are not removed from the nav

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1628]
### Expected behavior
Item should be filtered from the navigation automatically

### Actual behavior
Item is not removed

### Steps to reproduce the problem
* create a content page with an expired_dt field before todays date
* make sure the page is set to appear in navigation
* Note that it still shows in navigation

**Comment by jdrossl** [comment]
@russdanner I was not able to reproduce this issue, can you confirm all configuration in the content-type is right?

**Comment by russdanner** [comment]
VERIFIED CANT REPODUCE
