### ISSUE TITLE
[studio-ui] upload image from desktop reports permissions error when path is empty

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1629]
### Expected behavior
If the data source has no value for the path it should throw a user-friendly error to the user asking them to contact their admin.  

`The path field of the data source {DATA SOURCE NAME} for this component is not configured properly. Please contact your administrator.`

### Actual behavior
Use gets message in UI about permissions error
### Steps to reproduce the problem
* create content type with an image picker and upload data source
* don't provide a path in the data source
* Note that when you upload an image the dialog reports permission issue

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/699

**Comment by russdanner** [comment]
VERIFIED
