### ISSUE TITLE
[studio][studio-ui] Support delete content type

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1631]
### Expected behavior
Allow the author to invoke a delete against the content type's folder in the Studio config.

Recommend adding an action here

<img width="1302" alt="screen shot 2017-11-20 at 6 48 11 pm" src="https://user-images.githubusercontent.com/169432/33047427-a4a43682-ce23-11e7-80c0-b2834927f196.png">

Before delete user must confirm the delete via dialog
After confirmed user should be taken to initial state of content type tool (pre-type selection)

### Actual behavior
Today authors/admins cannot delete content types through the studio UI

**Comment by sumerjabri** [comment]
Must have 2 APIs: 
1. get content type information: content type templates, controllers, trigger scripts, content items of this type.
2. delete content type: takes params on what to delete of what was mentioned above

UI tells the user what's dependent on the content type and asks the user to check (checkboxes) what they want to delete, then confirms the deletion indicating what will be deleted, and then finally deletes.

**Comment by sumerjabri** [comment]
Design API and implement it then assign to UI for invocation.

**Comment by jdrossl** [comment]
@sumerjabri @russdanner for the content items, should we display their own dependencies too? or maybe we should trigger the usual delete content dialog to handle those depedencies

**Comment by sumerjabri** [comment]
Per discussion:
- UI will check and alert the user as to the usage of the content type
- Content types that have no instances (can have controller/view) can be deleted
- Backend will only delete content types when there are no instances unless a flag is set, if the flag is set, all content instances are deleted (this is not in the UI in this version)
- Backend will always delete controller/view associated with the type

**Comment by jdrossl** [comment]
@rart the API is ready

**Comment by rart** [comment]
@sumerjabri FYI searching for a content type that doesn't exist throws an internal server error (500) instead of a 404. Same for a site that doesn't exist. Would have expected 404s for both.

**Comment by sumerjabri** [comment]
1) is a bug, route the ticket back to @jdrossl to address
2) we won't do this at this time
3) we will proceed with POST given the routing/proxy tech in-between and similar considerations

**Comment by jdrossl** [comment]
@rart the backend is updated

**Comment by russdanner** [comment]
Hallelujah
Confirmed
