### ISSUE TITLE
[studio-ui] Add urlTransformService example in Groovy and FTL Editor 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1633]
# FTL Example
Label: Transform PATH to URL
${urlTransformationService.transform('storeUrlToRenderUrl', STOREURL)}

# Groovy Example
Label: Transform PATH to URL
urlTransformationService.transform('storeUrlToRenderUrl', STOREURL)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/701

**Comment by russdanner** [comment]
VERIFIED
