### ISSUE TITLE
[crafter - studio] studio.mail.port must be configurable to be used in the API Test Cases

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1634]
### Expected behavior
studio.mail.port should be configurable to allows the automation use a little smtp server for API test cases like the next: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/user-management/forgot-password.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/user-management/set-password.html

And after the test process the port may be returned back to default configuration

### Actual behavior
The api test cases needs that the crafter studio port was configured before run the ./gradlew test. Currently, the api test cases start/stop a fakesmtp server listening the port 2525, but the crafter studio is not configured with that port

### Steps to reproduce the problem
* Go to your craftercms server folder and execute the **./gradlew init self update update build deploy**
* Run the **./gradlew test** proccess and wait for the execution of the API test cases
* The next test cases fails because of the crafter studio configuration: 
  -testForgotPassword
  -testSetPassword
  -testValidateToken 

### Log/stack trace (use https://gist.github.com)
No log

### Specs: version, OS, browser, etc.
Mac OS, Ubuntu, Windows

**Comment by sumerjabri** [comment]
`authoring.studio.smtp.port` env

**Comment by cortiz** [comment]
https://github.com/craftercms/craftercms/pull/1640

**Comment by luishernandezmonge** [comment]
Currently, the ./gradlew build deploy configures the smtp.port to run the api test cases when we use the parameter of above. e.g: ./gradlew build deploy -Pauthoring.studio.smtp.port=2525
