### ISSUE TITLE
[crafter - test suite] the backup data folder (of the test execution) should be deleted after the ./gradlew test process finish

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1635]
### Expected behavior
No backup data folders should be displayed after ./gradlew test process because of the file system space

### Actual behavior
Currently, after the ./gradlew test process the ./gradlew generates a backup folder with the data that the test execution generates, and when the test finish that backup still there on the environment   taking up space in the file system.

### Steps to reproduce the problem
* Go to your craftercms server folder and execute the **./gradlew init self update update build deploy**
* Start the authoring environment and create some Sites on studio, also create a couple of users.
* Stop the authoring environment, and review the **data** folder under **craftercms/crafter-authoring** folder
*Run the **./gradlew test** process and wait for the finish, in the meanwhile go folder of the step above and review that the data of step 2 is located into the other data folder named with the date&time of the execution
* When the **./gradlew test** finish, the backup folder of the step above will renamed to **data**, but another backup folder stills there.

Watch the next video: https://www.useloom.com/share/44bef189bbc94941b43faac0de090299

**Comment by cortiz** [comment]
@sumerjabri As https://github.com/craftercms/craftercms/issues/1329 this is not a issue, its working as expected. Should I revert that ?
cc @luishernandezmonge

**Comment by luishernandezmonge** [comment]
Currently, the ./gradlew build deploy configures the smtp.port to run the api test cases when we use the parameter of above. e.g:  **./gradlew build deploy -Pauthoring.studio.smtp.port=2525**
