### ISSUE TITLE
[studio] Startup fails when CMIS repo impl uses HTTPS endpoint

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1636]
Applies only to 2.x (CMIS repo implementation)

### Expected behavior
Configuring Studio to work with HTTPS should start up and authenticate 

```
INSTALL_DIR/apache-tomcat/shared/classes/crafter/cstudio/extension/server-config.properties
alfrescoUrl=https://{ALFRESCO_SERVER_HOST}:{ALFRESCO_SERVER_PORT}/alfresco

```

### Actual behavior
When using HTTPS results in redirect error
`alfrescoUrl=https://{ALFRESCO_SERVER_HOST}:{ALFRESCO_SERVER_PORT}/alfresco`
Error:
```
Failed to create cstudio folder in /
org.apache.chemistry.opencmis.commons.exceptions.CmisConnectionException: Redirects are not supported (HTTP status code 301): Moved Permanently at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.convertStatusCode(AbstractAtomPubService.java:469)
```
Redirect with HTTP is supported.  With HTTPS it is not.

If you update the config to point to the redirect location (alfresco/) then the authorization API call fails:
`alfrescoUrl=https://{ALFRESCO_SERVER_HOST}:{ALFRESCO_SERVER_PORT}/alfresco/`

### Steps to reproduce the problem
* Configure HTTPS
* Start the server

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/957


Added following properties:
```
# Use https with alfresco
alfresco.useSSL=false
# Keystore location for alfresco SSL certificates
alfresco.keystoreFile=./data/keystore/ssl.keystore
# Keystore password
alfresco.keystorePass=########
# Keystore type
alfresco.keystoreType=JCEKS
```
