### ISSUE TITLE
[studio - API] Get Groups per Site location is not the correct according with documentation 

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1637]
### Expected behavior
The location for the Get Groups per Site should be something like this:
**http://localhost:8080/studio/api/1/services/api/1/group/get-per-site.json?site_id=mysite&start=0&number=25**

### Actual behavior
The location for the Get Groups per Site is: 
**http://localhost:8080/studio/api/1/services/api/1/get/get-per-site.json?site_id=mysite&start=0&number=25**

Notice the **/get/** part

### Preconditions
* A Rest API client should be installed to test the API call
 
### Steps to reproduce the problem
* Start the crafter studio server and create a site named: "mysite"
* Go to your Rest API Client and run the next api call (GET): 
GET http://localhost:8080/studio/api/1/services/api/1/group/get-per-site.json?site_id="mysite"
* Review the location returned

Review the location for this api call here: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/group-management/get-groups-per-site.html

**Comment by sumerjabri** [comment]
@jvega-crafter @dejan-brkic when fixing, please fix back and UI at the same time. (This remains a concern until we fully switch to GitFlow.)

**Comment by dejan-brkic** [comment]
Backend fixed
PR:
https://github.com/craftercms/studio/pull/958

**Comment by luishernandezmonge** [comment]
Verified as resolved
