### ISSUE TITLE
[studio] Refactor the dep calc

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1638]
Per our conversation, please refactor to:
```
build_publish_package(x) {
	array publish_package;

	deps = scan x for dependencies

	for dep in deps {
		if (dep is new || (dep is 'edited' && dep is item_specific)) {
			publish_package.add(dep);
			publish_package.add(build_publish_package(dep));
		}
	}

	return publish_package;
}
```

**Comment by dejan-brkic** [comment]
3.0 Done
PR:
https://github.com/craftercms/studio/pull/958

**Comment by russdanner** [comment]
2.5 TESTING:  New, shared components were not published but should be
https://www.useloom.com/share/b5f37991d627483db2ee9cb71534c9ed

**Comment by dejan-brkic** [comment]
Done
2.5: https://github.com/craftercms/studio/pull/971

3.0: https://github.com/craftercms/studio/pull/972
