### ISSUE TITLE
[studio-ui] Remove "Upload" from right click menu when right clicking on template files(*.ftl) and script files (*.groovy)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1641]
### Expected behavior
When you right click on template files (*.ftl) or script files (*.groovy), the "Upload" option should not be available.

### Actual behavior
"Upload" is available in the right click menu when right clicking on template files (*.ftl) or script files (*.groovy)

### Steps to reproduce the problem
* Create a site using website_editorial 
* Right click on a template files (*.ftl) or a script file (*.groovy), notice the right click menu has **Upload** option available

Template file (*.ftl) right click menu:
<img width="314" alt="screen shot 2017-11-25 at 2 02 44 pm" src="https://user-images.githubusercontent.com/25483966/33233801-084f4b44-d1ea-11e7-827d-d03180a48f69.png">

Script file (*.groovy) right click menu:
<img width="352" alt="screen shot 2017-11-25 at 2 03 11 pm" src="https://user-images.githubusercontent.com/25483966/33233810-34fa48c4-d1ea-11e7-8eb4-00008cd51c99.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-2c1a83
Build Number: 2c1a83f13c4eaacb8a8d0c0b6d5e50efcc01d15b
Build Date/Time: 11-25-2017 12:04:00 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/702

**Comment by alhambrav** [comment]
Verified fixed.
