### ISSUE TITLE
[studio-ui] Add "Dependencies" to right click menu for user Reviewer on scripts, templates and static-assets

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1642]
### Expected behavior
**Dependencies** should be available for user Reviewer when right clicking on static assets, templates and scripts.  **Dependencies** should be available for user author when right clicking on templates and scripts.  All roles should have dependencies available.
 
### Actual behavior
**Dependencies** is not available for user Reviewer when right clicking on static assets, templates and scripts.  **Dependencies** is also not available for user author when right clicking on templates and scripts.

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a user Reviewer and add to the site created site
* Login as user Reviewer, right click on static-assets, templates or scripts.  Notice that there is no **Dependencies** item listed in the right click menu

<img width="321" alt="screen shot 2017-11-25 at 4 14 10 pm" src="https://user-images.githubusercontent.com/25483966/33235174-da8e24fc-d200-11e7-8797-69a16320f5e4.png">

<img width="321" alt="screen shot 2017-11-25 at 4 14 25 pm" src="https://user-images.githubusercontent.com/25483966/33235199-0f0629c8-d201-11e7-828a-e027cb7a0b17.png">

<img width="312" alt="screen shot 2017-11-25 at 4 14 39 pm" src="https://user-images.githubusercontent.com/25483966/33235210-3f871d5a-d201-11e7-8c55-11ef6573ea6f.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-2c1a83
Build Number: 2c1a83f13c4eaacb8a8d0c0b6d5e50efcc01d15b
Build Date/Time: 11-27-2017 09:44:46 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/705

**Comment by alhambrav** [comment]
Verified fixed.
