### ISSUE TITLE
[studio] The URL path displayed is not the complete url after cut and paste a page into a folder (under My Recent Activity widget)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1644]
### Expected behavior
The path displayed under the recent activity widget for the recently cut and pasted page (into folder) 
-The path should be **"/folder/page"**
-The workflow state and icon should be **"Page" and "Never Published"**

### Actual behavior
The path stills be the same that when the page is created, also the workflow for the page is the **"Deleted"** and not **"Page" + "never published"**

### Preconditions
* Create a site using Empty Blueprint
### Steps to reproduce the problem
* Go to the dashboard, and expand the Pages/Home tree
* Create a new Entry page under home
* Create a new folder under home
* Cut the page of step 2
* Paste the page into the folder of step3
* Review the item displayed under the Recent Activity widget on dashboard
watch the next video: https://www.useloom.com/share/211520c1313d4a668eae4af56e8deead

### Log/stack trace (use https://gist.github.com)
```
INFO Messages on tomcat log:

_**[INFO] 2017-11-27 14:37:56,196 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/pages/entry.groovy in content at /site/website/folder/page/index.xml but content does not exist in referenced path for site testing
[INFO] 2017-11-27 14:38:04,376 [studioSchedulerFactoryBean_Worker-2] [site.SiteServiceImpl] | Syncing database with repository for site: testing fromCommitId = 5dee061e013d2f4b442a38c91ddff084bfb6f632
[INFO] 2017-11-27 14:38:04,383 [studioSchedulerFactoryBean_Worker-2] [site.SiteServiceImpl] | Done syncing database with repository for site: testing fromCommitId = 5dee061e013d2f4b442a38c91ddff084bfb6f632 with a final result of: true
[INFO] 2017-11-27 14:38:04,383 [studioSchedulerFactoryBean_Worker-2] [site.SiteServiceImpl] | Last commit ID for site: testing is 71a4dac022d97dba298807e8f032793349a090bc**_
```

### Specs: version, OS, browser, etc.
Mac OS X, Linux

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/969

**Comment by luishernandezmonge** [comment]
Verified as resolved
