### ISSUE TITLE
[studio] Dashboard "My Recent Activity" shows content-type "unknown" when you hover on a folder

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1646]
### Expected behavior
Dashboard widget "My Recent Activity" should not show content-type "unknown" when you hover on a folder.  Maybe it should say "folder"? (I'm not sure what are the content types available...)

### Actual behavior
Dashboard widget "My Recent Activity" shows content-type "unknown" when you hover on a folder

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a new article under one of the folders under **articles**
* Click on the dashboard and look in the **My Recent Activity** widget, hover your mouse over the folder created when you created the new article page.  Notice that it displays **Content Type** as **unknown**

Also, notice the `URL` listed for the article page.  In the dashboard, it displays the URL as `/articles/2016/7/new`, but if you look in the audit log, the url is listed as `/site/website/articles/2016/7/new.xml` ?

<img width="997" alt="screen shot 2017-11-28 at 3 32 58 pm" src="https://user-images.githubusercontent.com/25483966/33342994-e3b77be8-d451-11e7-994c-ec57ef0d511b.png">

Here's the audit log entry for the new article created:
```
+----+---------------------+---------------------+------------------------------------------------------------------------------------------+----------------+---------------------------------------------+---------------+-------------------+--------------+--------------+--------+
| id | modified_date       | creation_date       | summary                                                                                  | summary_format | content_id                                  | site_network  | activity_type     | content_type | post_user_id | source |
+----+---------------------+---------------------+------------------------------------------------------------------------------------------+----------------+---------------------------------------------+---------------+-------------------+--------------+--------------+--------+
|  1 | 2017-11-28 15:31:12 | 2017-11-28 15:31:12 | {"user":"admin","id":"127.0.0.1","contentType":"user"}                                   | json           | 127.0.0.1                                   | studio_root   | LOGIN             | user         | admin        | UI     |
|  2 | 2017-11-28 15:31:38 | 2017-11-28 15:31:38 | {"user":"admin","id":"admin > Admin","contentType":"user"}                               | json           | admin > Admin                               | myawesomesite | ADD_USER_TO_GROUP | user         | admin        | UI     |
|  3 | 2017-11-28 15:32:23 | 2017-11-28 15:32:23 | {"user":"admin","id":"/site/website/articles/2016/7/new","contentType":"folder"}         | json           | /site/website/articles/2016/7/new           | myawesomesite | CREATED           | folder       | admin        | UI     |
|  4 | 2017-11-28 15:32:24 | 2017-11-28 15:32:24 | {"user":"admin","id":"/site/website/articles/2016/7/new/index.xml","contentType":"page"} | json           | /site/website/articles/2016/7/new/index.xml | myawesomesite | CREATED           | page         | admin        | UI     |
+----+---------------------+---------------------+------------------------------------------------------------------------------------------+----------------+---------------------------------------------+---------------+-------------------+--------------+--------------+--------+
```

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-28-2017 15:25:43 -0500

**Comment by vestrada** [comment]
Ui is just showing the information from "/studio/api/1/services/api/1/activity/get-user-activities.json" api. It is related with Back end.

**Comment by alhambrav** [comment]
Verified fixed.
