### ISSUE TITLE
[studio-ui] There is no space between "Scripts" and "Site Config" in the Sidebar

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1647]
### Expected behavior
There should be a space between **Scripts** and **Site Config**

### Actual behavior
There there is no space between **Scripts** and **Site Config**

### Steps to reproduce the problem
* Create a site using any of the blueprints
* Open the **Sidebar**
* Look at the **Scripts** and **Site Config**, notice there is no space in between them

<img width="252" alt="screen shot 2017-11-27 at 3 39 51 pm" src="https://user-images.githubusercontent.com/25483966/33288211-727a405a-d389-11e7-80b1-69ed3fb1d344.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-28-2017 15:25:43 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/703

**Comment by alhambrav** [comment]
Verified fixed.
