### ISSUE TITLE
[studio-ui] Show In-Progress Items is slow for large sets

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1650]
### Expected behavior
Either show a spinner or be faster.

### Actual behavior
UI locks up (or takes way too long)

### Steps to reproduce the problem
* Create a site using Editorial BP
* On disk, `cd crafter-authoring/data/repos/sites/{SITE}/sandbox/site/website/articles`
* Execute: `for i in `seq 1 30`; do cp -r 2017 new-articles-$i; done; git add .; git commit -m "Added new articles for testing."`
* Wait until Studio picks up the changes (~10 seconds)
* Click on Show In-Progress Items
* Click on "Select All" to select all items:
** Note how slow it is, and note that the action bar at the top takes a while to load too
** Try to unselect all, it will hang

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Linux, Chromium
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-28-2017 21:29:55 -0500

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/706
