### ISSUE TITLE
[studio] Renaming a folder is not listed in the "My Recent Activity" widget in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1652]
### Expected behavior
Renaming a folder should be listed in the "My Recent Activity" widget in the dashboard

### Actual behavior
Renaming a folder is not listed in the "My Recent Activity" widget in the dashboard

### Steps to reproduce the problem
* Create a site using website_editorial
* Go to the **Sidebar** and navigate to one of the article folders
* In the example below, the folder **6** under "articles/2016/", is renamed to "June"
* Go to the dashboard.  Notice that there is no log in the **My Recent Activity** of the folder rename

<img width="1403" alt="screen shot 2017-11-29 at 12 00 40 pm" src="https://user-images.githubusercontent.com/25483966/33388164-2b5cf4fe-d4fd-11e7-90e6-8189dddce387.png">

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing a folder being renamed and a look in the dashboard, where the **My Recent Activity** widget is empty.  A new content is then added, then a look in the dashboard, and you can see that the new content is listed under the **My Recent Activity** widget, but no log for the folder rename

https://www.useloom.com/share/9a8b3278d43345d09f0552c64069dfba

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-29-2017 10:19:55 -0500

**Comment by vestrada** [comment]
Ui is just showing the information from "/studio/api/1/services/api/1/activity/get-user-activities.json" api. It is related with Back end.

**Comment by dejan-brkic** [comment]
Can not reproduce with latest develop build (commit id: 22847f7cdd2bf035ce0fdcd17a4b70e429d46ef3)

**Comment by alhambrav** [comment]
Verified issue is not reproducible with latest develop build.
