### ISSUE TITLE
[studio-ui] Renamed/new folder should display an edited (pencil) icon in the Sidebar

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1653]
### Expected behavior
Renamed/new folder should display an edited (pencil) icon in the Sidebar

### Actual behavior
Renamed/new folder does not display an edited (pencil) icon in the Sidebar

### Steps to reproduce the problem
* Create a site using website_editorial
* Open the **Sidebar** and navigate to one of the article folders
* Rename one of the article folders, notice that the renamed folder does not display a pencil on it (which would be nice because it would be easy to see that it hasn't been published)
* You can also create a new folder under one of the article folders, notice that the new folder also does not display a pencil on it (edited icon)

<img width="434" alt="screen shot 2017-11-29 at 1 08 24 pm" src="https://user-images.githubusercontent.com/25483966/33391333-a65e9442-d506-11e7-9636-b16357a5e1eb.png">

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-29-2017 10:19:55 -0500

**Comment by rart** [comment]
Per discussion with Sumer we're rolling back this fix which in turns fixes #4493

**Comment by sumerjabri** [comment]
@yacdaniel it's now working for me. Have a look.

**Comment by yacdaniel** [comment]
Verified this change was rolled back in  `4.0.0-SNAPSHOT`
