### ISSUE TITLE
[studio] Error when renaming a folder with different case (from "november" to "November")

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1654]
### Expected behavior
Renaming a folder with the same name but different case (from "november" to "November") should not produce errors.

### Actual behavior
Error when renaming a folder with the same name but different case (from "november" to "November")

### Steps to reproduce the problem
* Create a site using website_editorial
* Open the **Sidebar** and navigate to the articles folders
* Create a new folder "december"
* Now try to rename the newly created folder to "December" by right clicking and selecting **Rename Folder**, notice that the **Rename Folder** dialog folder does not go away.  Also, look at the tomcat log and notice the error message there

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/5101e0fffa25b4b0b5cee49e14c41f53

Here's a short clip:
https://www.useloom.com/share/e7dac2d857b947a0b5d3bd116745f813

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-29-2017 10:19:55 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/969

**Comment by alhambrav** [comment]
Verified fixed.
