### ISSUE TITLE
[studio] Publishing bugs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1656]
Per our meeting. The bugs:
1. Process site even if publishing is disabled
2. Don't insert an item into `item_metadata` if in `publish_request` and not found in `item_metadata`; if item is not found in `item_metadata`, log the error and stop the publisher for this site
3. Don't allow duplicate entries in `publish_request` (de-dupe on site, environment, path, commit_id and state='READY_FOR_LIVE')
4. Don't allow publishing of folders (ignore/don't add to `publish_request`)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/967
