### ISSUE TITLE
[studio-ui] Do not allow user Author and Reviewer to "Edit" static-assets, templates and scripts from the "Dependencies" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1661]
### Expected behavior
User Author and Reviewer should not be given a link to "Edit" static-assets, templates and scripts from the "Dependencies" dialog.  They should just be given a **View** link instead in the "Dependencies" dialog.

(It would be nice for user Reviewer and user Author to get a **View** link for previewable static-assets, scripts and templates in the Dependencies dialog)

<img width="1231" alt="screen shot 2017-12-01 at 9 10 10 am" src="https://user-images.githubusercontent.com/25483966/33486381-cf7c24f8-d677-11e7-9bd2-b4510dc233a0.png">

### Actual behavior
The user Author and Reviewer gets the **Edit** link  from the dependencies link for templates, scripts

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a user Author and user Reviewer
* Login as user Author
* Open the **Sidebar** and navigate to the articles
* Right click on an article and click on **Dependencies**, notice that for scripts and templates, the user Author is given an **Edit** link and no link at all for static-assets.  (It would be nice to give the author a **View** link from the Dependencies dialog for previewable static-assets, scripts and templates)
* Logout and login as user Reviewer.
* Open the **Sidebar** and navigate to the articles
* Right click on an article and click on **Dependencies**, notice that for scripts, templates and static-assets, no link is given to the user in the Dependencies dialog.  (It would be nice for user Reviewer to get a **View** link for previewable static-assets, scripts and templates)

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-SNAPSHOT-cb71a7
Build Number: cb71a720818783bbf5adb9ec9211ae238780f037
Build Date/Time: 11-30-2017 10:56:38 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/716

**Comment by alhambrav** [comment]
Verified fixed.
