### ISSUE TITLE
[test-suite] It would be nice to be able to start and stop the test suite gracefully

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1662]
### Expected behavior
It would be nice to be able to start and stop the tests gracefully, so that when you stop the script, the webdriver/selenium is also stopped OR sites created by the test are not left behind in Studio.
I'm not sure how best to do this, but something like `./gradlew test start`, then give back the prompt to the user and maybe have the output displayed on another window? (or something like that), then when the user stops the test in the middle `./gradlew test stop`, cleanup can be performed if it's possible?

### Actual behavior
When running the tests, if you want to stop it in the middle, you have to terminate the test script, which leaves the webdriver/selenium test still running OR, leaves sites created by the test in Studio 

### Steps to reproduce the problem
* On the command line, run
```
gradlew.bat test
```
* Let the test run for a few minutes, then stop the test by pressing \<ctrl\> + c
* Notice that in Windows, the webdriver is still running after terminating the script, in OS X, the webdriver stops running, but sometimes there are leftover sites created by the test in Studio after you stop the test in the middle.

### Specs: version, OS, browser, etc.
OS X OS, Windows OS - Chrome browser

**Comment by yacdaniel** [comment]
Fixed by using the Jenkins server to start/stop test execition.
