### ISSUE TITLE
[docs] Make the "Danger" admonition more noticeable (pop out?) 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1663]
### Expected behavior
Make the **Danger** admonition pop out more than **Warning** or **Note** admonitions, and make other admonitions distinguishable from one another maybe?

### Actual behavior
The **Danger** admonition looks like a **Note** or **Warning** or **Important** admonition

Here's the **Danger** admonition:
<img width="876" alt="screen shot 2017-12-01 at 10 40 25 am" src="https://user-images.githubusercontent.com/25483966/33490294-b1f7169c-d684-11e7-8c41-89e6d19257fa.png">

Here's the **Note** admonition:
<img width="858" alt="screen shot 2017-12-01 at 10 50 30 am" src="https://user-images.githubusercontent.com/25483966/33490536-83a6ec3a-d685-11e7-8a69-f446874a7d34.png">

Here's the **Warning** admonition:
<img width="830" alt="screen shot 2017-12-01 at 10 51 14 am" src="https://user-images.githubusercontent.com/25483966/33490594-a767ddaa-d685-11e7-94c8-df794a7a0ccb.png">

### Steps to reproduce the problem
* 
* 
*

**Comment by rart** [comment]
Hi, @alhambrav, thanks for your feedback. We've added some changes to address your comments and hope you'll find the docs more readable now. Changes should be out by next build. Happy crafting :)

**Comment by alhambrav** [comment]
Hi, @rart.  Thanks for the heads up on the updates.  The changes look good, but, I was wondering, if we can make the color highlight for **Danger** different than the **Note** or **Warning** admonition?  Thanks again!

**Comment by rart** [comment]
@alhambrav I don't think so but if you provide a link to an instance of each distinct type I can look into in.

**Comment by alhambrav** [comment]
@rart Hi!  Here's a link to a page that has the **Danger** and **Warning** admonition instance:
http://docs.craftercms.org/en/3.0/system-administrators/upgrade/index.html
Thanks for looking into it!

**Comment by rart** [comment]
I don't see anything but a "Danger" on the page that you shared but comparing with [another page where I found a "note"](http://docs.craftercms.org/en/3.0/system-administrators/setup-site-for-delivery.html), there does seem to be a markup hint on the type usable for styling. Do you know of any type other than "danger", "warning" and "note"?

**Comment by rart** [comment]
Done. Danger and warning now have exclamation icons and red and orange colours respectively. Notes or any other kind that show up will render in teal with an eye icon. Should be distinct enough now :)

**Comment by alhambrav** [comment]
Beautiful! 
Verified fixed.
