### ISSUE TITLE
[docs] It would be nice if entries in the sidebar are more distinguishable.

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1664]
### Expected behavior
It would be nice if entries in the sidebar are more distinguishable.  

### Actual behavior
When the titles are long and it wraps, it's hard to tell whether the next line is the next entry or a continuation from the previous line.

Notice the entries under **Crafter Social** in the image below.   

<img width="1334" alt="screen shot 2017-12-01 at 11 31 55 am" src="https://user-images.githubusercontent.com/25483966/33492565-65446b04-d68b-11e7-85fd-2540261e74ea.png">

 It looks like the entries for that heading is the following:
* Crafter Social System
* Administration
* Crafter Social Admin Console
* UI

Here is the actual entries for **Crafter Social**
* Crafter Social System Administration
* Crafter Social Admin Console UI

### Steps to reproduce the problem
* 
* 
*

**Comment by rart** [comment]
Hi, @alhambrav, thanks for your feedback. We've added some changes to address your comments and hope you'll find the docs more readable now. Changes should be out by next build. Happy crafting :)

**Comment by alhambrav** [comment]
Verified fixed.
