### ISSUE TITLE
[CrafterCMS] Change Maven to gradle

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1665]
Change the build tool chain to Gradle

Reasons in favor of Gradle:

* Better Dependency Management 
* Smaller and more Readable build files.
* More Flexible Build files
* Better Integration with code quality tools (PMD, checkstyle)
* More usefully plugins (License Header update/check)
* Still compatible to upload in Maven Repo.
* Faster (Robotize) deployments (all done in the same build script (no bash))

More reasons :
https://www.youtube.com/watch?v=6lM8meY9LJ4

**Comment by sumerjabri** [comment]
Won't pursue in the near term.
