### ISSUE TITLE
[craftercms] The solr.zip and apache-tomcat.zip files are not downloaded when authoring&delivery folders are present, the downloads folder is deleted and try deploy again

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1666]
### Expected behavior
The zip files should be downloaded because the deploy fails

### Actual behavior
The zip files are not downloaded and the ./gradlew deploy fails.

### Steps to reproduce the problem
* git clone https://github.com/craftercms/craftercms.git
* cd craftercms
* ./gradlew init build deploy
* verify that the crafter-authoring and crafter-delivery folders are there
* delete downloads folder
* ./gradlew build deploy

### Log/stack trace (use https://gist.github.com)
Log errors:
FAILURE: Build failed with an exception.

* Where:
Script '/Users/luishernandez/Crafter_Project/craftercms_server/craftercms/environments.gradle' line: 212

* What went wrong:
Execution failed for task ':deliveryEnvironment'.
> Cannot expand ZIP '/Users/luishernandez/Crafter_Project/craftercms_server/craftercms/downloads/solr-6.4.1.zip' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 18s
2 actionable tasks: 2 executed

### Specs: version, OS, browser, etc.

**Comment by cortiz** [comment]
Solve in #1670

**Comment by luishernandezmonge** [comment]
Verified as fixed
