### ISSUE TITLE
Do not use `AbstractTask.execute()`

### ISSUE THREAD

**Issue by Vampire** [craftercms/craftercms#1668]
I'm not using your project, I just stumbled upon it because of a Stackoverflow question.
I've seen you call `AbstractTask.execute()` in your build script multiple times.
This is a pretty big no-go.
`AbstractTask.execute()` is an internal method that is only callable because of the duck-typing of Groovy.
It must not be called, if you call this directly, you might execute tasks multiple times, there will no dependency tasks run before, up-to-date checks will not properly work and so on.
I strongly recommend you restructure your build to use proper Gradle way of doing things instead of calling internal methods that are not meant for direct calling.
If you don't want to, just close this issue, but I really strongly recommend you change this.

**Comment by cortiz** [comment]
Removed all executed call and refactor most of the build to use dependencies and not `execute`

https://github.com/craftercms/craftercms/pull/1708
