### ISSUE TITLE
[craftercms] Bundle tool should allow users to choose what kind of archive they want to use.

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1669]
### Expected behavior
`crafter.bundle.archive=tar|zip` should be added so user can choose the output archive, 
if not send, the default value should be `both` (tar & zip).

**Comment by cortiz** [comment]
Partially solve in https://github.com/craftercms/craftercms/pull/1708
using `delivery_bundle_tar`, `delivery_bundle_zip` ,`authoring_bundle_tar` or `authoring_bundle_zip`
@sumerjabri  do we still want to do `crafter.bundle.archive=tar|zip` ?

**Comment by sumerjabri** [comment]
@cortiz @alhambrav let's document it as you have it and decide afterward.

**Comment by cortiz** [comment]
Param Added in PR https://github.com/craftercms/craftercms/pull/1711

**Comment by sumerjabri** [comment]
@alhambrav please validate and close if done.

**Comment by alhambrav** [comment]
Verified.
