### ISSUE TITLE
[studio-ui] bulk upload fails due to missing X-XSRF-TOKEN token

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1672]
### Expected behavior
bulk upload should work

### Actual behavior
nothing uploads when you bulk upload
post response from the server is;
`<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-XSRF-TOKEN'.</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.20</h3></body></html>`

### Steps to reproduce the problem
* attempt bulk upload

### Log/stack trace (use https://gist.github.com)
None

### Specs: version, OS, browser, etc.
Chrome

**Comment by russdanner** [comment]
It looks like it's part of the cookie
Cookie:XSRF-TOKEN=00941d3b-1d9f-473b-bf58-4acfdba2bd30;
Maybe because the form is multi-part the server is looking at the request differently

**Comment by jvega-crafter** [comment]
3.0: https://github.com/craftercms/studio-ui/pull/710

**Comment by jvega-crafter** [comment]
2.5.x: https://github.com/craftercms/studio-ui/pull/711

**Comment by sumerjabri** [comment]
Verified.
