### ISSUE TITLE
[studio-ui] Content-type config.xml file does not let you save <delete-dependencies> 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1673]
### Expected behavior
Changes made in Content-type config.xml file should be saved when the **Update** button is pressed (Adding \<delete-dependencies\>) .

### Actual behavior
Content-type config.xml file does not save changes made

### Steps to reproduce the problem
* Create a site using website_editorial or empty bp
* Open the **Sidebar** and click on **Site Config**
* Click on **Content Types** and then click on **Open Existing Type**
* Select one of the content types, for the example below, the empty bp is used and the **Entry** content type was clicked.
* Add the following to the **Configuration** "config.xml"
```
<delete-dependencies> 
    <delete-dependency> 
        <pattern>(^/static-assets/docs/.*)</pattern> 
        <remove-empty-folder>false</remove-empty-folder> 
    </delete-dependency> 
</delete-dependencies> 
```
* Click on **Update**, then after it goes back to the content type dialog, click on **Save**
* Now, go back to the Properties Explorer panel, **Configuration** property and click on the pencil icon next to config.xml again to view the file. Notice that the changes you saved earlier is gone.

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/50e1099548374ea3a5e01991ac14049d

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.2-a8afa1
Build Number: a8afa188dc381af4d744a267fc4278efa2e700a3
Build Date/Time: 12-06-2017 00:22:03 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/720

**Comment by alhambrav** [comment]
Verified fixed.
