### ISSUE TITLE
[docs] The example on "Rendered Page Components as JSON" does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1674]
### Expected behavior
The example on "Rendered Page Components as JSON" in the cook-books should work

### Actual behavior
The example on "Rendered Page Components as JSON" does not work

### Steps to reproduce the problem
* Try the example listed here: http://docs.craftercms.org/en/3.0/developers/cook-books/services/rendered-components-as-json.html
* Notice the response:
```
{"message":"startup failed:\nsite:/scripts/rest/get-rendered-components.get.groovy: 84: Can't have an abstract method in a non-abstract class. The class 'CapturingResponseWrapper$1' must be declared abstract or the method 'boolean isReady()' must be implemented.\n @ line 84, column 48.\n   t = new ServletOutputStream() {\n                                 ^\n\nsite:/scripts/rest/get-rendered-components.get.groovy: 84: Can't have an abstract method in a non-abstract class. The class 'CapturingResponseWrapper$1' must be declared abstract or the method 'void setWriteListener(javax.servlet.WriteListener)' must be implemented.\n @ line 84, column 48.\n   t = new ServletOutputStream() {\n                                 ^\n\n2 errors\n"}
``` 

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.3-SNAPSHOT-316a18
Build Number: 316a18df487b763f557368ba70d1907475166cfd
Build Date/Time: 12-06-2017 11:41:45 -0500

**Comment by avasquez614** [comment]
PR craftercms/craftercms#1674

**Comment by alhambrav** [comment]
Verified.
