### ISSUE TITLE
[docs] Document `craftercms` cloning from `develop` if developer otherwise `master`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1677]
Please update docs (in docs and in `craftercms/README.md` as appropriate) to indicate that developers who want to contribute should clone the `develop` branch, otherwise they'd get `master` where they can build/release/bundle.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/craftercms/pull/1679
PR https://github.com/craftercms/docs/pull/412
