### ISSUE TITLE
[studio] Hide/Show "In-Progress" Items button items displayed is inconsistent after we sort the items by **Last Edited By**

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1681]
### Expected behavior
**Hide/Show "In-Progress" Items** button items displayed should be the same after we sort the items by **Last Edited By**

### Actual behavior
**Hide/Show "In-Progress" Items** button items displayed is inconsistent after we sort the items by **Last Edited By**

### Steps to reproduce the problem
* Create a site using website_editorial
* Create some articles and request publish one, schedule another one
* Go to the **Dashboard** and look at the widget **Items Waiting For Approval**
Notice the number of **Pages** listed (In my example clip below, I have **2** pages listed)
* Click on the **Show "In-Progress" Items** button, notice the number of **Pages** listed, toggle the button again and again, notice the number of **Pages** listed (In my example clip below, I have **8** pages listed)
* Click on **Last Edited By** to sort, then click it again
* Click on the **Show/Hide "In-Progress" Items**, notice the number of **Pages** listed, toggle the button again and notice the number of **Pages** listed again. (When I toggle the button, the number of pages switches from **3** to **2**, instead of the **8** to **2** before clicking on the **Last Edited By**.

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/79bde028f6c34e7484b5221f85345881

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-22847f
Build Number: 22847f7cdd2bf035ce0fdcd17a4b70e429d46ef3
Build Date/Time: 12-11-2017 09:13:56 -0500

**Comment by jvega-crafter** [comment]
It seems like a backend issue, when calling service with `sort=userLastName` param it returns less items than when calling it with `sort=eventDate`

Call with `sort=userLastName`
`/studio/api/1/services/api/1/workflow/get-go-live-items.json?site=test&sort=userLastName&ascending=false&includeInProgress=true`
Response: 

<img width="475" alt="screen shot 2017-12-13 at 10 49 11 am" src="https://user-images.githubusercontent.com/18267471/33950989-68b46e62-dff3-11e7-9a86-5dad5216e386.png">



Call with `sort=eventDate`
`/studio/api/1/services/api/1/workflow/get-go-live-items.json?site=test&sort=eventDate&ascending=false&includeInProgress=true`
Response:

<img width="477" alt="screen shot 2017-12-13 at 10 52 10 am" src="https://user-images.githubusercontent.com/18267471/33951100-b2026236-dff3-11e7-9c3b-df81ad8a7932.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/984

**Comment by alhambrav** [comment]
Verified fixed.
