### ISSUE TITLE
[studio] The Rename Folder action throws some errors when folder name is same that other or null

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1683]
### Expected behavior
A validation dialog should be displayed on the Rename Folder dialog to notify that the provided name is not valid or null

### Actual behavior
Studio does not display validation and the dialog continues displayed without errors, and errors are displayed on the tomcat log

### Preconditions
* Create a site using WebSite Editorial

### Steps to reproduce the problem
1. Go to preview of site of above
2. Expand site content
3. Click on components
4. Create a new folder named: test
5. Right click on folder of above and select Rename Folder action
6. Provide the next name: **articles-widget** and click on Rename
7. Clear the folder name and click on Rename
watch the next video: https://www.useloom.com/share/2e81b9acb21f41d1aaef2a9cfecd9582

### Log/stack trace (use https://gist.github.com)
Step 6 and 7 log:
[On_Null_Name_log.txt](https://github.com/craftercms/craftercms/files/1549409/On_Null_Name_log.txt)

### Specs: version, OS, browser, etc.
Mac OSX, Ubuntu

**Comment by sumerjabri** [comment]
Per our conversation, we need better error reporting.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/986

**Comment by luishernandezmonge** [comment]
Verified as resolved
