### ISSUE TITLE
[studio-ui] Page URL field is taking in count twice for required fields on the "# of # field requirements" label (Create&Edit forms)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1684]
### Expected behavior
Page URL should be taken as only one required field according with content type design

### Actual behavior
Page URL field is taking in count twice for required fields

### Preconditions
* Create two sites using Empty Blueprint and WebSite Editorial

### Steps to reproduce the problem
* Login and go to the preview of website editorial site
* Try to create a new Page - Category Landing page
* Review the "Page Properties" section on the create form
* Notice that the displayed label says "3 of 4 field requirements are invalid" (Close the form)
* Go to Site Config/Content types/Open Existing Type
* Select the Page - Category landing 
* Review all the required fields for Page Properties section of the content type (there are only 3 required fields)
* Go to the preview of Empty bp site
* Try to create a new Entry page
* Review the "Page Properties" section on the create form
* Notice that the displayed label says "2 of 3 field requirements are invalid" (Close the form)
* Go to Site Config/Content types/Open Existing Type
* Select the Page - Category landing 
* Review all the required fields for Page Properties section of the content type (there are only 2 required fields)
* Delete all the fields except the Page URL field
* Save the content type and go to the preview the site
* Try to create a new Entry page
* Review the "Page Properties" section on the create form
* Notice that the displayed label says "1 of 2 field requirements are invalid"

### Log/stack trace (use https://gist.github.com)
Watch the next video:  https://www.useloom.com/share/36945f29404a4cf9b90bf76ff433f84f

### Specs: version, OS, browser, etc.

**Comment by jvega-crafter** [comment]
@luishernandezmonge Page URL is not being taking in count twice, if you fill the field it will only decrease by 1 the invalid requirements counter. It seems like total of requirements is being miscalculated

**Comment by jvega-crafter** [comment]
@luishernandezmonge by default, PageURL control (filename) has 2 requirements: 
1. The field is required
2. The Path must be valid
Form section counter checks for all requirements on each field, in this case there are two requirements on the PageURL input, that's why the single field adds 2 requirements

**Comment by luishernandezmonge** [comment]
According with the comment above this bug is not valid.
