### ISSUE TITLE
[studio-ui] Add element IDs to support the Test Suite

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1685]
Please add element IDs to the UI in support of the Test Suite per our conversation. Here is the final list as of 2017-12-11: https://docs.google.com/spreadsheets/d/1to-rNt6ubgkI39MP5ux9Ilw9lV1T3dtMtd6c5v8v3ac/edit#gid=0

The sheet is now read-only to new requests, but it's writable to the UI team to make notes in the `yellow` cells.

Please ping me if you have any questions or concerns.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/734

**Comment by sumerjabri** [comment]
@luishernandezmonge please validate and close/reopen as needed.

**Comment by luishernandezmonge** [comment]
Starting implementing new ID's on the test framework. Currently, some of the test cases fails because this.

**Comment by luishernandezmonge** [comment]
Done with the implementation and fix of all the IDs and test cases related to this new IDs provided by UI guys. I will close this ticket for now
Status=Implemented on test-suite latest version
