### ISSUE TITLE
[docs] Please add support for code-block directive option "emphasize-lines"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1686]
### Expected behavior
`code-block` lines with option **emphasize-lines** should be highlighted or something 

### Actual behavior
There is no difference when the option **emphasize-lines** is used in the code-block directive.

### Steps to reproduce the problem
In the docs, 
http://docs.craftercms.org/en/3.0/site-administrators/studio/users-groups/putting-it-all-together.html
if you look at the *.rst file, the option **emphasize-lines** is used, but there is no highlighting/bolding or something to emphasize the lines indicated in the html.
```
#. Add your new group and role in the editor

   .. code-block:: xml
       :linenos:
       :emphasize-lines: 18,19,20

       <role-mappings>
         <groups>
           <group name="Admin">
               <role>admin</role>
           </group>
```

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/craftercms-sphinx-theme/pull/2

**Comment by alhambrav** [comment]
Verified.
