### ISSUE TITLE
[studio-ui] Error in Tomcat log when replacing hero image in Windows OS

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1687]
### Expected behavior
There should be no errors in Tomcat log when replacing hero image in Windows OS

### Actual behavior
Error in Tomcat log when replacing hero image in Windows OS

### Steps to reproduce the problem
* Using a Windows machine and Edge browser or Chrome browser, create a site using website_editorial
* Click on **Edit** for the Home Page
* Go to the hero image section in the edit form, and click on the **Replace** button.
* Select an existing image and click on **Add & Close**
* Save your changes.  The page will reload with the new image you selected for the Home Page, but. notice in the Tomcat log the error messages that 
```
GET http://localhost:8080/studio/api/1/services/api/1/content/get-items-tree.json?site=myawesomesite&path=/site/website/index.xml&depth=1&order=default&nocache=Tue%20Dec%2012%202017%2010:33:43%20GMT-0800%20(Pacific%20Standard%20Time)&nocache=Tue%20Dec%2012%202017%2010:33:43%20GMT-0800%20(Pacific%20Standard%20Time) failed
```
* Note also that there are errors too when selecting **Upload Images** after clicking on the **Replace** button right next to the hero image

### Log/stack trace (use https://gist.github.com)
Here's the error log generated when Edge browser was used (existing images):
https://gist.github.com/alhambrav/d3c14bfe502871be53cca9e10e4f1712

Here's the error log generated when Chrome browser was used (existing images):
https://gist.github.com/alhambrav/0d32d84f1668f3f37d5f46f396795402

### Specs: version, OS, browser, etc.
Windows OS, Edge browser and Chrome browser
![screen shot 2017-12-12 at 1 55 55 pm](https://user-images.githubusercontent.com/25483966/33902812-3a68805c-df44-11e7-98c2-d15a39928149.png)

**Comment by dejan-brkic** [comment]
This seems like UI issue and it happens only when editing in preview (not if editing page when dashboards displayed). Cause of the error message in logs is http requests being aborted (canceled) by client sides.

**Comment by vestrada** [comment]
Jose and I tried to reproduce the issue, but we can't reproduce it. Vita can you confirm if this issue is still happening?

We can't see the error messages in Tomcat log.

Thanks :)

**Comment by alhambrav** [comment]
Hi!
Error still appears in the Tomcat log.  I can't get the studio version through the about screen. (I have to double check if Help dropdown does not really work, then I'll file a ticket.)
The error appears when you click on **Edit** from the context nav when previewing the home page.
Thanks.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/738

**Comment by alhambrav** [comment]
Verified fixed.
