### ISSUE TITLE
[studio] Tomcat log message "Found reference to *.groovy in content at /site/*index.xml but content does not exist in referenced path for site "

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1688]
### Expected behavior
I'm not sure what the expected behavior should be, but the message is a little concerning even if it's just an INFO.  

### Actual behavior
Tomcat log message "Found reference to \*.groovy in content at /site/*/index.xml but content does not exist in referenced path for site "

### Steps to reproduce the problem
* Create a site using website_editorial
* Edit the Home page
* Notice the tomcat logs as listed below.  If you look at the index.xml file, there's no mention of the reference to missing file?  If you also look at the dependencies using Studio, I don't see the reference to the missing file the message is saying.
* You can also edit the articles and see a similar message in the Tomcat log after saving your changes

### Log/stack trace (use https://gist.github.com)

```
[INFO] 2017-12-12 14:24:56,671 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/components/feature.groovy in content at /site/components/features/sapien-veroeros.xml but content does not exist in referenced path for site myawesomesite
[INFO] 2017-12-12 14:24:56,681 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/components/feature.groovy in content at /site/components/features/quam-lorem-ipsum.xml but content does not exist in referenced path for site myawesomesite
[INFO] 2017-12-12 14:24:56,689 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/components/left-rail.groovy in content at /site/components/left-rails/left-rail-with-latest-articles.xml but content does not exist in referenced path for site myawesomesite
[INFO] 2017-12-12 14:24:56,698 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/components/articles-widget.groovy in content at /site/components/articles-widget/latest-articles-widget.xml but content does not exist in referenced path for site myawesomesite
[INFO] 2017-12-12 14:24:56,728 [http-nio-8080-exec-7] [dependency.RegexDependencyResolver] | Found reference to /scripts/components/contact-widget.groovy in content at /site/components/contacts/contact-widget.xml but content does not exist in referenced path for site myawesomesite
```
### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-22847f
Build Number: 22847f7cdd2bf035ce0fdcd17a4b70e429d46ef3
Build Date/Time: 12-12-2017 13:00:19 -0500

**Comment by dejan-brkic** [comment]
@sumerjabri This is related to following ticket:
https://github.com/craftercms/craftercms/issues/1408

It is not error. It is only information that content type controller was not found and it won't be added as dependencies. Possible solution would be to reduce message level to debug or completely remove it.

**Comment by sumerjabri** [comment]
@dejan-brkic let's drop it to debug and add text to explain what it's doing. Ping me if you want to discuss messaging options.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/993

**Comment by alhambrav** [comment]
Verified fixed.
