### ISSUE TITLE
[studio] Static-asset in a scheduled page to be published that has been cut and pasted remains as Scheduled even if the containing page has reverted to edited/new

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1692]
### Expected behavior
Static-asset in a page should revert to state of containing page.

### Actual behavior
Static-asset in a scheduled page to be published that has been cut and pasted remains as Scheduled even if the containing page has reverted to edited/new.

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a new article under one of the folders, make sure that you upload a new image for the article
* Schedule the new article to be published the next day
* From the **Sidebar**, cut the article from above and paste into a different folder.
* Go to the **Dashboard**, notice that the page we cut and pasted has reverted to **New**, but the image in the article is still **Scheduled**

### Log/stack trace (use https://gist.github.com)
Here's a short clip that shows when the scheduled page is cut and pasted into another folder, and the containing page reverts to **New** while the image in the page remains in **Scheduled**

https://www.useloom.com/share/28c799b441c74df4970f044c1cebfd99

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-86835f
Build Number: 86835f59b86874a1d272692b465f25d720984ca8
Build Date/Time: 12-12-2017 22:48:23 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/985

**Comment by alhambrav** [comment]
Verified fixed.
