### ISSUE TITLE
[studio] Items in the approved scheduled items widget disappears

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1694]
### Expected behavior
Items listed in the approved scheduled items widget should not disappear after cutting and pasting a page scheduled for publish

### Actual behavior
Items listed in the approved scheduled items widget disappears after cutting and pasting a page scheduled for publish (Workflow cancelled for the page that was cut and pasted)

### Steps to reproduce the problem
* Create a site using website_editorial
* Edit two articles and schedule both for publish the next day
* Open the **Dashboard** and notice the items listed in the **Approved Scheduled Items** widget (It should contain the two articles we scheduled for publish)
* From the **Sidebar**, right click on one of the scheduled article, then select cut
* Paste the article we just cut into another folder
* Refresh your browser, notice that the widget **Approved Scheduled Items** is now empty

<img width="1381" alt="screen shot 2017-12-13 at 4 34 20 pm" src="https://user-images.githubusercontent.com/25483966/33963687-c893ebe8-e023-11e7-9068-037fb6ca1e2f.png">

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/b04b4e509e71451b8fe8237b08b3cbc6

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-86835f
Build Number: 86835f59b86874a1d272692b465f25d720984ca8
Build Date/Time: 12-12-2017 22:48:23 -0500

**Comment by vestrada** [comment]
Hi @dejan-brkic 
This issue seems to be back-end. When we follow the above steps (cut and paste a scheduled item), the scheduled-items api (studio/api/1/services/api/1/deployment/get-scheduled-items.json) gets a 500 status.

**Comment by dejan-brkic** [comment]
Issue was side effect of #1692 

PR:
https://github.com/craftercms/studio/pull/985

**Comment by alhambrav** [comment]
Verified fixed.
