### ISSUE TITLE
[studio-ui] picking an image causes form to collapse

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1695]
### Expected behavior
form should not resize after image is selected

### Actual behavior
https://www.useloom.com/share/44acc74ac7fe435c90aae5d6302d2f5c

### Steps to reproduce the problem
* Open a form via pencil that contains an image picker 
* upload or select an image via browse  

### Specs: version, OS, browser, etc.
Build Number: 8b470db42b85167cf3b15eac0d9b1eca80aa1988
Build Date/Time: 12-12-2017 22:34:07 -0500
Chrome

**Comment by sumerjabri** [comment]
@russdanner kindly copy/paste Studio's version from `Help > About` and paste it along with your OS and browsers used in the last field of the ticket template titled "Specs: version, OS, browser, etc."

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/724

**Comment by russdanner** [comment]
VERIFIED
