### ISSUE TITLE
The delete dialog should display all items that will be deleted when cascade on delete is enabled

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1699]
### Expected behavior
The delete dialog should display all items that will be deleted 

### Actual behavior
The delete dialog does not  display all items that will be deleted when cascade on delete is enabled

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a new article under one of the article folders, make sure to upload an image from desktop
* Go to **Site Config**, then click on **Content Types** -> **Open Existing Types**
* Select **Page - Article** from the list
* In the **Properties Explorer** on the right hand side of the form, click on **Configuration**, a pencil should appear to the right of **config.xml**
<img width="407" alt="screen shot 2017-12-14 at 11 44 29 am" src="https://user-images.githubusercontent.com/25483966/34003820-48c475a8-e0c4-11e7-936f-7a3f9d1e1c0e.png">

* Click on the pencil to edit the **config.xml**, we will configure the content type **Page - Article** to cascade on delete.  Add the following to the file:
```
<delete-dependencies>
	<delete-dependency>
		<pattern>(^/static-assets/images/page/.*)</pattern>
		<remove-empty-folder>true</remove-empty-folder>
	</delete-dependency>
</delete-dependencies> 
```
* **Update** and then **Save** the changes to the content type
* Click on the site name next to the logo to return to the **Dashboard** of your site
* From the **Sidebar**, right click on the article you just created, and select **Delete**.  Notice the delete dialog shown does not display all of the items that will be deleted.

<img width="562" alt="screen shot 2017-12-14 at 11 48 29 am" src="https://user-images.githubusercontent.com/25483966/34004044-d92541b8-e0c4-11e7-9470-4c268284fde0.png">

Here's the dependencies for the article that will be deleted in the image below.  Notice the image file which was not mentioned in the image above that will be deleted (delete dialog)

<img width="1208" alt="screen shot 2017-12-14 at 11 55 03 am" src="https://user-images.githubusercontent.com/25483966/34004343-a557b536-e0c5-11e7-8bf0-02563a3a916a.png">

* Notice the items listed as deleted in the dashboard after deleting the article
<img width="852" alt="screen shot 2017-12-14 at 11 56 00 am" src="https://user-images.githubusercontent.com/25483966/34004468-f76d42fa-e0c5-11e7-9df1-c1d6119ce041.png">

 
### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/a13788118b004d00aaab5c5bec0ff22e

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-dbcb3e
Build Number: dbcb3eabeefcfb50ef370153fd2f13dfd1e83d87
Build Date/Time: 12-14-2017 09:52:19 -0500

**Comment by sumerjabri** [comment]
It will be fixed by the new publisher.
