### ISSUE TITLE
[studio] Folder cut and paste does not work (2.5)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1703]
Applies to Crafter 2.5.x

### Expected behavior
User should be able to cut and paste folders with content

### Actual behavior
Folder cut and paste does not work

### Steps to reproduce the problem
* Create a site using the empty bp
* Create two folders under **Home**.  Right click on **Home**, select **New Folder**, name the folder **a**.  Right click on **Home** again, select **New Folder**, name the folder **b**
* Create content under the two newly created folders, name the page under folder **a** as **foo** and name the page under folder **b** as **bar**, such that we have **a/foo** and **b/bar**
<img width="340" alt="screen shot 2017-12-15 at 1 10 13 pm" src="https://user-images.githubusercontent.com/25483966/34054503-54a58a9e-e199-11e7-97ec-9ec43ea0ef47.png">

* Right click on folder **a** and select **Cut**
* Right click on folder **b** and select **Paste**, notice that folder **a** has disappeared from the site tree, under the **Home** folder, but it's also not under folder **b** 

<img width="330" alt="screen shot 2017-12-15 at 1 11 41 pm" src="https://user-images.githubusercontent.com/25483966/34054565-95ae3b80-e199-11e7-8494-0bc4c92b9287.png">

* Refresh your browser.  Notice that folder **a** is back under folder **Home**

<img width="333" alt="screen shot 2017-12-15 at 1 13 36 pm" src="https://user-images.githubusercontent.com/25483966/34054631-d467c0f8-e199-11e7-9ab0-b5ed25ae682a.png">

Look at the Tomcat log and notice the errors.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/485391d409361565e8404617613d1d97

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Crafter CMS 2.5.12

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/987

**Comment by alhambrav** [comment]
Hi!  Cut and paste is working, but I see an error message in the Tomcat logs.
Here's the steps I did, which is the same as listed above:
### Steps to reproduce ###
* Create a site using the empty bp.
* Under home, create two folders, **g** and **h**
* Create content in each of the newly created folders
* From the site tree, right click on folder **g**, then select **Cut**
* From the site tree again, right click on folder **h**, then select **Paste**
* The folder and its contents gets cut and pasted, but this error message is in the Tomcat log after cutting and pasting:
 
https://gist.github.com/alhambrav/2ab211322523a229734a9e4d19a32baa

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/989

**Comment by alhambrav** [comment]
Verified fixed.
