### ISSUE TITLE
[studio] Content type "unknown" for deleted folder when you mouse over in the Dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1704]
### Expected behavior
Content type should not be "unknown" for deleted folder when you mouse over in the Dashboard

### Actual behavior
Content type "unknown" for deleted folder when you mouse over in the Dashboard

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a folder under one of the articles folders (In the example, folder **2018** was created under **articles**
* From the **Sidebar**, right click on the folder just created and select **Delete**
* Open the **Dashboard** and go the **My Recent Activity** widget.
* Mouse over on the folder we just deleted, notice that the tooltip displays the content type as **unknown**

<img width="1046" alt="screen shot 2017-12-15 at 1 38 24 pm" src="https://user-images.githubusercontent.com/25483966/34055594-e5d2210e-e19d-11e7-8f9e-ac3802272052.png">

### Specs: version, OS, browser, etc.
OS X, Chrome OS
Studio Version Number: 3.0.4-SNAPSHOT-69d09d
Build Number: 69d09d8dd098a39efbe3cb4a21d4f1e1142cf93b
Build Date/Time: 12-15-2017 03:52:15 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/996

**Comment by alhambrav** [comment]
Verified fixed.
