### ISSUE TITLE
[studio] Move folder shows wrong audit

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1706]
### Expected behavior
Move operation should be shown properly in audit log regardless of content type

### Actual behavior
Moved folder is recorded as REPOSITORY delete operation in audit log

### Steps to reproduce the problem
Per convo with Sumer

**Comment by dejan-brkic** [comment]
@sumerjabri I was not able to reproduce what we saw in database on troubleshooting. At least not using UI only. However moving folders directly on repository generates DELETE + CREATE in audit log. I think we need to discuss move operation directly on repository and how to incorporate it in studio audit log.

**Comment by sumerjabri** [comment]
If the operation on disk is to move, git will log it as delete and create. If the operation uses `git mv`, then we'll get a move.
