### ISSUE TITLE
[studio] Studio API Delete Site call valid without logging in

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1710]
### Expected behavior
Delete Site API call should be inaccessible unless logged in, and user has permissions to delete sites

### Actual behavior
Any REST call to the studio delete site will delete the site if the site is present

### Steps to reproduce the problem
* Create Site
* Using REST Client of choice, send POST request to http://localhost:8080/studio/api/1/services/api/1/site/delete-site.json
     * body contains the field `siteId` with the name of created site
     * send a request (403 Error) to obtain the `XSRF-TOKEN` cookie, and put it in the header of the request under the label `X-XSRF-TOKEN`
     * re-send request
* Without logging in, the site should be deleted

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.4-SNAPSHOT-42c450
Build Number: 42c450dd7b490570b3474c00a9c28eb33516330d
Build Date/Time: 12-18-2017 11:18:31 -0500

**Comment by sumerjabri** [comment]
@dejan-brkic please also check if this is in 2.5.x

**Comment by dejan-brkic** [comment]
Done 3.0
PR:
https://github.com/craftercms/studio/pull/991

**Comment by dejan-brkic** [comment]
2.5.x is ok

**Comment by RLChris-Lim** [comment]
Tested, working as intended now
