### ISSUE TITLE
[studio] Remove empty folder tag in cascade on delete does not work in 2.5.x

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1713]
### Expected behavior
The parent folder of item deleted, should be deleted when the `remove-empty-folder` tag is set to true for 2.5.x

### Actual behavior
The parent folder of item deleted, is not deleted when the `remove-empty-folder` tag is set to true for 2.5.x

### Steps to reproduce the problem
* Modify the file `/cstudio/config/sites/SITENAME/content-types/page/entry/config.xml` and add the following:
```
<delete-dependencies>
    <delete-dependency>
        <pattern>(^/static-assets/images/pages/.*)</pattern>
        <remove-empty-folder>true</remove-empty-folder>
    </delete-dependency>
</delete-dependencies>
```
* Start Studio
* Create a site using the `empty` bp
* Create a new `entry` page, add an image using the RTE and notice where the image uploaded is placed in the static-assets:
* Delete the newly created page, refresh your browser and notice that the folder containing the uploaded image is not deleted

When an image was inserted in the body using the RTE, the new file uploaded was placed in the following:
`/static-assets/images/pages/6793/679323f9-fa20-7665-1d10-e8a04a723332/new1.png`
Notice after deleting the page `mine`, the folder `679323f9-fa20-7665-1d10-e8a04a723332` (parent folder of `new1.png`) was not removed.

Here's a short clip of 2.5.x behavior of `remove-empty-folder`
https://www.useloom.com/share/b3fa9952d65d4cc5960f061d24eca3c1

For 3.0 behavior, please note the following:
When an image was inserted in the body using the RTE, the new file uploaded was placed in the following:
`/static-assets/images/pages/4ef9c300-59cc-76a0-d22d-287ba66455ca/new1.png`
Notice after deleting the page `new`, the folder `4ef9c300-59cc-76a0-d22d-287ba66455ca` was also deleted. The tag `remove-empty-folder` seem to be working okay in 3.0 when set to true/false

Here's a short clip of 3.0 behavior of `remove-empty-folder`:
https://www.useloom.com/share/0777159da51d47de955446956173448a

### Specs: version, OS, browser, etc.
OS X, chrome browser
2.5.13 snapshot (latest studio code as of 12/19/2017)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/995

**Comment by alhambrav** [comment]
Verified fixed.
