### ISSUE TITLE
[studio] Studio API calls not checking for authorization

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1714]
### Expected behavior
API REST calls that have a 401 Unauthorized status in the documentation should return such when not logged in

### Actual behavior
API calls do not correspond with their listed documentation, in which a 401 Unauthorized error cannot be returned because the user is always authorized to use the API calls regardless of being logged out
#### Calls Affected:
**Site Manage API**
Get Site
Get Sites per User
**Audit API**
Get Audit Log
**Repository Management API**
Sync from Repository

### Steps to reproduce the problem
* Create Site
* Using REST Client of choice, send request as described in the api documentation
     * send a request (403 Error) to obtain the `XSRF-TOKEN` cookie, and put it in the header of the request under the label `X-XSRF-TOKEN`
* Requests will behave as if the user was logged in with full permissions, regardless of logged in or out

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.4-SNAPSHOT-42c450
Build Number: 42c450dd7b490570b3474c00a9c28eb33516330d
Build Date/Time: 12-18-2017 11:18:31 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/992

**Comment by RLChris-Lim** [comment]
Tested and Verified fixed
