### ISSUE TITLE
[docs] Document headers based authentication for Studio

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1715]
Please document headers based authentication and how it can be made to work with mod_mellon/SAML 2.0.

Ping Dejan and Alfonso for help as needed. Dejan on config, and Alfonso on mod_mellon.

Related ticket: https://github.com/craftercms/craftercms/issues/1645

Related doc: http://docs.craftercms.org/en/3.0/site-administrators/engine/engine-site-security-guide.html

Ping me if you need clarity on this task.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/434

**Comment by sumerjabri** [comment]
Please update to show how this is used to implement SAML2-based SSO in Studio.

**Comment by sumerjabri** [comment]
Please add to the article that you can remove the `logout` button by removing logout menu item from contextual-navigation-config.xml. We will add the feature to automatically remove logout for SSO users in 3.1.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/443, commit https://github.com/craftercms/docs/pull/443/commits/efa66cc2870bf9111fefa0a85f1dfd6abe6a58fd
