### ISSUE TITLE
[craftercms] Failed running "./gradlew -Penv=delivery bundle"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1716]
### Expected behavior
Running "./gradlew -Penv=delivery bundle" should generate `crafter-cms-delivery.tar.gz` and `crafter-cms-delivery.zip`

### Actual behavior
Build failed when running "./gradlew -Penv=delivery bundle"

### Steps to reproduce the problem
*  Run the following:
```
./gradlew -Penv=authoring bundle
```
* Notice that a `bundles` folder is created containing the following files: `crafter-cms-authoring.tar.gz` and `crafter-cms-authoring.zip`
* Run the following to generate the delivery bundle:
```
./gradlew -Penv=delivery bundle
```
Note the failed build message below.

### Log/stack trace (use https://gist.github.com)
```
➜  craftercms git:(develop) ./gradlew -Penv=delivery bundle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vita/temp/test5/craftercms/build.gradle' line: 578

* What went wrong:
A problem occurred evaluating root project 'craftercms'.
> Could not get unknown property 'authoring_start' for root project 'craftercms' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
➜  craftercms git:(develop) ./gradlew -Penv=authoring bundle

BUILD SUCCESSFUL in 3m 23s
2 actionable tasks: 2 executed
➜  craftercms git:(develop) ls bundles
crafter-cms-authoring.tar.gz crafter-cms-authoring.zip
```

### Specs: version, OS, browser, etc.
OS X, Chrome OS
Studio Version Number: 3.0.4-SNAPSHOT-3b00dc
Build Number: 3b00dc4def191a290753964a24c7f63504238e05
Build Date/Time: 12-19-2017 10:55:02 -0500

**Comment by cortiz** [comment]
https://github.com/craftercms/craftercms/pull/1720

**Comment by cortiz** [comment]
PR is https://github.com/craftercms/craftercms/pull/1722

**Comment by cortiz** [comment]
PR is https://github.com/craftercms/craftercms/pull/1722

**Comment by alhambrav** [comment]
Verified fixed.
