### ISSUE TITLE
[gradlew update] Test-suite repo is not updated when run the ./gradlew update

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1719]
### Expected behavior
The test-suite repo should be updated as well

### Actual behavior
The test-suite repo is not updated

### Steps to reproduce the problem
* Go to your terminal and move to your craftercms folder repo
* Run the next command: ./gradlew self update update
* Notice that the test-suite repo is not updated
Watch the next video:
https://www.useloom.com/share/c145a4eed37c415083c8d9b25934ecfb

### Specs: version, OS, browser, etc.
Linux, Mac OS

**Comment by cortiz** [comment]
https://github.com/craftercms/craftercms/pull/1722

**Comment by luishernandezmonge** [comment]
Also, seems like the ./gradlew init does not clone the test-suite repo

**Comment by cortiz** [comment]
Can you recheck with the PR merge
Also make sure, that you do `selfupdate` and *then* `the init`

**Comment by luishernandezmonge** [comment]
Tested with steps of comment of above, and it works ok. Will close this issue
