### ISSUE TITLE
[studio-ui] It would be nice to use some font awesome icons for the play/pause in the Log Console

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1723]
### Expected behavior
It would be nice to use some font awesome icons for the play/pause in the Log Console.
When you click on **Log Console**, it could display the **fa-caret-right** for play, when the logger is not running(paused), then, when the user clicks on the **fa-caret-right** icon(running/playing), it will now display the **fa-pause** icon, signifying when you click on it the logger will be paused.

### Actual behavior
In the **Log Console**, we have the text **Play/Pause** on the top left to play and pause logging, and is a little confusing right now because I can't tell if it's in play or pause when there are no logs scrolling through.

### Steps to reproduce the problem
* Create a site using website_editorial
* Click on **Site Config**, then click on **Log Console**

<img width="1264" alt="screen shot 2017-12-21 at 10 18 12 am" src="https://user-images.githubusercontent.com/25483966/34261859-90f3bb3a-e638-11e7-8017-4791f410083e.png">

### Log/stack trace (use https://gist.github.com)
None

### Specs: version, OS, browser, etc.
OS X, Chrome browser
Studio Version Number: 3.0.4-SNAPSHOT-6104b9
Build Number: 6104b9aba60641868c3fbb34f04722480c5fe76a
Build Date/Time: 12-21-2017 08:26:47 -0500

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/735

**Comment by alhambrav** [comment]
Verified fixed.
