### ISSUE TITLE
[studio] Studio API 'Publish Sites' returns 401 unauthorized for wrong requests

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1724]
### Expected behavior
API REST call for `Publish Sites` should return a 404 when the site in the parameters is not found, and a 400 when there are invalid parameters.

### Actual behavior
Requests that should return either a 404 or a 400 instead return 401 unauthorized

### Steps to reproduce the problem
* Create Site
* Log in as an admin user using the REST API
* Attempt to use the Publish Status call ( `/studio/api/1/services/api/1/publish/status.json` ) with invalid parameters, or using a `site_id` parameter that doesn't correspond with any existing site

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.4-SNAPSHOT-6104b9
Build Number: 6104b9aba60641868c3fbb34f04722480c5fe76a
Build Date/Time: 12-20-2017 10:26:45 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/997

**Comment by RLChris-Lim** [comment]
Tested + Verified
