### ISSUE TITLE
[studio] Integrate Studio with remote git repos

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1725]
Per our conversation, please support site creation with remote repos.
Fields to add to site/project creation:
Upstream Remote Git repository
URL
Username
Password
Either:
	Clone remote project to local repository
	Push local repository to remote project

Blueprint is only required if local or push to remote is chosen.

The API for site creation must get updated also to support these optional parameters. Please update the API docs first, send me a PR and then proceed to update the API impl + backend work.

When creating the site based on a remote repo, please be sure to optimize.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1003

Docs:
https://github.com/craftercms/docs/pull/432

**Comment by sumerjabri** [comment]
@RLChris-Lim please test the API and validate that it works. Please ping me or Dejan if you need help.

**Comment by RLChris-Lim** [comment]
Tested + verified
(last related bugfix https://github.com/craftercms/craftercms/issues/1756)
