### ISSUE TITLE
[studio-ui] Update site creation dialog and API calls

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1726]
```
Fields to add to site/project creation:

Link to upstream remote Git repository (expand collapse), if expanded:

Upstream Remote Git repository
URL
Username
Password
Options (radio buttons)
	Clone remote project to local repository
	Push local repository to remote project

Choose blueprint (enabled if: no remote or remote is push_to)
```

Please wait for the API to get updated in the docs.

Ping me for details/as needed.

**Comment by vestrada** [comment]
Waiting for a BE fix.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/742

**Comment by sumerjabri** [comment]
Please update the field names as follows:

- Name -> Remote Git Repository Name (example: origin)
- URL -> Remote Git Repository URL
- Username -> Remote Git Repository Username (if required)
- Password -> Remote Git Repository Password (if required)
- Clone remote project to local repository -> Create site based on remote git repository
- Push local repository to remote project -> Create site based on a blueprint then push to remote bare git repository

Also, please make sure the browser's password auto-fill doesn't mistakingly fill the username/password fields of the studio user in the site creation username/password fields.

**Comment by rart** [comment]
1. Is there difference between setting up a github vs a bitbucket vs some other git repo hosting? I wonder if the host should be a field that would allow the UI to adjust th form based on that.
2. Are we not gonna support token auth? I was thinking the UI would have a single selection for auth type offering “username & password” or “token”

**Comment by sumerjabri** [comment]
1) we're trying to keep this generic, so it should support any valid git repo URL (and we will fix/tweak over time)
2) At this time we're supporting username/password, github allows you to create additional key/pass pairs for third-party applications that you can use/revoke with limited access to specific repos/operations

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/745
