### ISSUE TITLE
[studio] Add new Studio Id field in the database

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1727]
Please add a new column to the `_meta` table indicating the ID of this Studio. This is a UUID that identifies this Studio database. It's created once and will only be created again if the database is dropped.

Please add an internal service call to retrieve this ID.

**Comment by sumerjabri** [comment]
We must also weave this into lm.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1262
