### ISSUE TITLE
[studio] Publishing is slow for large data-sets

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1730]
# Expected behavior
Publishing content is not slower than dep-calc

# Actual behavior
Publishing takes too long

# Steps to reproduce the problem
* Create a site using Editorial BP
* On disk:
```
cd crafter-authoring/data/repos/sites/{SITE}/sandbox/site/website/articles
for i in `seq 1 30`; do cp -r 2017 new-articles-$i; done; git add .; git commit -m "Added new articles for testing."
```
* Wait until Studio picks up the changes (~10 seconds)
* Click on Show In-Progress Items
* Click on "Select All" to select all items:
* Publish

## Log/stack trace (use https://gist.github.com)
N/A

#   Specs: version, OS, browser, etc.
Linux, Chromium
Studio Version Number: 3.0.3-ca5b62
Build Number: ca5b6267450cbbd3639ef27af0b0b160ee40716e
Build Date/Time: 12-28-2017 12:34:48 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1006
