### ISSUE TITLE
[studio] Studio API 'Delete Content' not functioning

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1731]
### Expected behavior
API REST call for `Delete Content` should take 2 parameters as detailed in the documentation, and successfully delete content when called

### Actual behavior
Call returns a 500 Unknown error with `No signature of method` error

### Steps to reproduce the problem
* Create Site
* Create any content
* Log in as an admin user using the REST API
* Attempt to use the Delete Content call ( `/studio/api/1/services/api/1/content/delete-content.json` ) with valid parameters for site and path of content

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/RLChris-Lim/3ed2c9c9921372980170ebd56b06887e

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.4-SNAPSHOT-7d7cdd
Build Number: 7d7cdd079c2d13d1e8a31436d2136347c36a73fd
Build Date/Time: 12-28-2017 08:42:59 -0500

**Comment by sumerjabri** [comment]
@dejan-brkic please remove from code and docs as this is no longer used/viable.

**Comment by dejan-brkic** [comment]
Done
PR:
docs: https://github.com/craftercms/docs/pull/433
studio: https://github.com/craftercms/studio/pull/1004

**Comment by sumerjabri** [comment]
@RLChris-Lim reopen if you still see issues
