### ISSUE TITLE
[studio-ui] form jumps incorrectly on repeat group operations

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1732]
### Expected behavior
When user adds, moves or deletes a form repeat group section they should stay on/with that repeated section.

### Actual behavior
https://www.useloom.com/share/2976f200caf7499291dca45f5fffab51

### Steps to reproduce the problem
1. Create a form with a repeat group
2. open form
3. perform repeat group operations

### Log/stack trace (use https://gist.github.com)
N/A

### Specs: version, OS, browser, etc.
Studio Version Number: 3.0.4-SNAPSHOT-7d7cdd
Build Number: 7d7cdd079c2d13d1e8a31436d2136347c36a73fd
Build Date/Time: 12-28-2017 22:21:46 -0500

Applies to 2.x 3.x

**Comment by jvega-crafter** [comment]
3.0.x: https://github.com/craftercms/studio-ui/pull/736
2.5.x: https://github.com/craftercms/studio-ui/pull/737

**Comment by russdanner** [comment]
Still able to reproduce

Studio Version Number: 3.0.3-8b470d
Build Number: 8b470db42b85167cf3b15eac0d9b1eca80aa1988
Build Date/Time: 01-11-2018 19:49:31 -0500
