### ISSUE TITLE
[studio-ui] The Folders Icons disappears after child content is published

### ISSUE THREAD

**Issue by juacamar** [craftercms/craftercms#1737]
### Expected behavior
The Folders Icons should not disappear after child content is published. 

### Actual behavior
The Folders Icons disappears after child content is published. 

### Preconditions
Create a site using WebSite Editorial

### Steps to reproduce the problem

1. Go to preview of site of above
2. Expand site content
3. Create a new folder named: test
4. Right-click on the Articles folder and select Copy Folder action
5. Paste the recently copied content on the recently created folder named test.
6. Expand the test folder and the folders inside.
7. Approve and publish the content on the "6" and "7" folders.

### Log/stack trace (use https://gist.github.com)
Watch the next video:
https://www.useloom.com/share/406ec82ffedc40f1b660f9a731093e21
No errors in the logs

### Specs: version, OS, browser, etc.
Mac OSX

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/739

**Comment by juacamar** [comment]
Bug verified and closed as fixed using:
Studio Version Number: 3.0.4-SNAPSHOT-73112f
Build Number: 73112f7be1908f4dbd410431b007dfcddb8c8980
