### ISSUE TITLE
[studio] Ignore global git ignore

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1738]
Please configure jgit to not honor global git ignore for Studio repos.

Per Slack convo.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1001

**Comment by sumerjabri** [comment]
Documenting our decision: We decided to respect the global git ignore and inform developers of this.

@alhambrav Please add a note to the docs that global git ignore is honored. Please ping me for details.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/438, commit https://github.com/craftercms/docs/pull/438/commits/0cc7d28ab39eaaab71bd2510053efcf16ad558b6
