### ISSUE TITLE
[studio-ui] Default (home) page is broken on first load when authentication with headers is used

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1740]
### Expected behavior
On first load studio ui displays `sites` page (`http://localhost:8080/studio/#/sites`)

### Actual behavior
Redirect correctly but page display is broken
![broken](https://user-images.githubusercontent.com/4053827/34541932-8a2fdfde-f0da-11e7-9468-f3bee02b8f3c.png)

### Steps to reproduce the problem
* Configure authentication headers provider
```
studio.security.type: headers
# Authentication via headers enabled
studio.authentication.headers.enabled: true
# Authentication header for secure key
studio.authentication.headers.secureKeyHeaderName: secure_key
# Authentication headers secure key that is expected to match secure key value from headers
# Typically this is placed in the header by the authentication agent, e.g. Apache mod_mellon
studio.authentication.headers.secureKeyHeaderValue: secure
# Authentication header for username
studio.authentication.headers.username: username
# Authentication header for first name
studio.authentication.headers.firstName: firstname
# Authentication header for last name
studio.authentication.headers.lastName: lastname
# Authentication header for email
studio.authentication.headers.email: email
# Authentication header for groups: comma separated list of sites and groups
#   Example:
#   craftercms1645,Author,anothersite,Author
studio.authentication.headers.groups: groups
```
* start studio
* use Google Chrome Extension: ModHeader to add authentication headers
* open ``http://localhost:8080/studio/` 

#### Browser
Google Chrome

**Comment by dejan-brkic** [comment]
Related to https://github.com/craftercms/craftercms/issues/1645

**Comment by jvega-crafter** [comment]
The user info is not set from model the first time it loads the page, so it can't properly load page, if you reload it does get the user info.
Debugged groovy file of page `entry.groovy`. When loading dashboard fails getCurrentUser() call returns `null`:
`def currentUser = SecurityServices.getCurrentUser(context)`, so
`def profile = SecurityServices.getUserProfile(context, currentUser)` can't get user info, and the profile can't be set on the model, and freemarker template can't load user info, that's the reason why page load fails.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1002

**Comment by sumerjabri** [comment]
@alhambrav please validate as part of SAML/header auth

**Comment by alhambrav** [comment]
Verified.
