### ISSUE TITLE
[car-builder] Build the CAR Builder

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1741]
CAR Builder should be a command line application that receives a folder with the plugin content and a plugin.xml, filters and processes the files, and generates a zip with a .car extension. Flow of the compilation process for the CAR is shown in https://github.com/craftercms/car-builder/blob/develop/resources/architecture/Plugin%20Compilation.png.

**Comment by sumerjabri** [comment]
Pending validation.

**Comment by sumerjabri** [comment]
Superseded by https://github.com/craftercms/craftercms/issues/6204
