### ISSUE TITLE
[studio] db error during content-type updates

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1742]
### Actual behavior
After a content-type is changed (add a new form section & a control) when the `Save` button is clicked an error is returned.

![screen shot 2018-01-03 at 1 45 27 pm](https://user-images.githubusercontent.com/1236955/34570059-42b3a1a8-f130-11e7-8e0c-9f1a01d326be.png)

### Steps to reproduce the problem
There is no way to reproduce manually, it appears completely random during execution of the test-suite

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/jdrossl/02030600df2fbc24e5101c335255bc6d

**Comment by sumerjabri** [comment]
This should be fixed now. We made changes to protect against the race-condition that causes this. Please validate.

**Comment by jdrossl** [comment]
I ran the test suite in the 3.1 branch and the error didn't happen, but since it was completely random I don't know if we can be sure.

**Comment by sumerjabri** [comment]
The underlying issue should be fixed, and this is no longer reproducible. Closing.
