### ISSUE TITLE
[commons] StringToDateConverter shouldn't use a singleton SimpleDateFormat Instance

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1743]
SimpleDateFormat is not thread safe so it could cause concurrency issues. Use an instance per call or use Apache Common's FastDateFormat.

**Comment by luis-rivet** [comment]
Hi, guys, I want to know when this ticket will be resolved because I'm doing a load test and a good amount of them are failing because of it, with this solved I can deliver more accurate results
Thanks in advance

**Comment by avasquez614** [comment]
Hi @luis-rivet, the code is being pushed shortly

**Comment by avasquez614** [comment]
Fixed in craftercms/commons#117
