### ISSUE TITLE
[craftercms] The gradlew test stops to display the log messages send by test cases 

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1749]
### Expected behavior
The gradlew should not stops to displays log messages until the end of the execution.

### Actual behavior
After a time (6mins aprox) the gradlew stops to display the log messages send by each test cases and verbose of testNG. However, the automation continues executing in background.
And for the test process seems like it is stuck.
See the next image:
![screen shot 2018-01-09 at 4 28 08 pm](https://user-images.githubusercontent.com/16946208/34746607-3c4da07e-f55a-11e7-9080-10204dec080c.png)

### Steps to reproduce the problem
* Go to your craftercms folder and run the next commands:

1. .\gradlew.bat selfupdate
2. .\gradlew.bat init
3. .\gradlew.bat update
4. .\gradlew.bat -P"authoring.studio.smtp.port=2525" build deploy

* Run the test using the next command:
1. .\gradlew.bat test
*  Check and notice that the gradlew stops to display the log messages

Notes: I run it with maven and all the test cases log messages are displayed all the execution time 

#### Version
Crafter 3.0.3 and develop branch

#### OS
Windows Server 2012 R2, also for Windows 10 version

#### Browser
Chrome

**Comment by sumerjabri** [comment]
@luishernandezmonge did you happen to click on the shell? that can freeze the log/scroll.

**Comment by luishernandezmonge** [comment]
After run the ./gradlew test, I do nothing

**Comment by cortiz** [comment]
https://github.com/craftercms/craftercms/pull/1776

**Comment by luishernandezmonge** [comment]
Verified as fixed
