### ISSUE TITLE
[studio-ui] Form jumps to top on resize as user is scrolling

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1752]
### Expected behavior
Form should not jump on the user after scroll.  

### Actual behavior
https://www.useloom.com/share/184e3b0ce08a4e61a34639b57bb4b6eb
### Steps to reproduce the problem
*  open/click edit in cotnext nav a long form like an article in the editorial site
* while form is expanding scroll down.  
* observe form jumps back up to top

#### Version
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-11-2018 20:34:16 -0500

#### OS
osx
#### Browser
chrome

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/744
