### ISSUE TITLE
[studio] SSO in Studio with Alfresco repo not working anymore

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1754]
Before 2.5.11 it was possible to login through SSO in Studio with an Alfresco repository. The SSO username was being extracted through a header and then passed on to Alfresco in all calls. Now it doesn't seem to work, and might be related to the introduction of `org.craftercms.studio.impl.v1.web.filter.StudioAuthenticationFilter`. From a brief reading of the code, `isAuthenticated` should return true, the problem might be with `isSessionExpired`.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1008

**Comment by avasquez614** [comment]
Tested and verified
