### ISSUE TITLE
[studio] Create Site from Git Repo issues

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1756]
### Expected behavior
1) If an internal server error is encountered when trying to create a site using a git repo (clone or push), it should delete all the site artifacts properly
2) If the site created is to be pushed to a repository, if that push fails (due to repo already having content, or otherwise), either an error message should be thrown, or site should not be created, or something

### Actual behavior
1) There remains a sandbox folder under `crafter-authoring/data/repos/sites/SITE_NAME/sandbox` which will prevent creation of other sites with the same name, with the error `Destination path "sandbox" already exists and is not an empty directory`
2) Site is created, and http response is 201, even if the push is not successful

### Steps to reproduce the problem
1) Easiest way to throw internal server error is to attempt to call the create site API with `clone` for the `create_option` field (with valid parameters otherwise for creating a site from a remote) using a repository that does not follow the structure needed for a liferay site (empty repository will also work)
2) Create site with `push` for `create_option` field, and use an existing repo that is not empty, and site should be still successfully created

### Log/stack trace (use https://gist.github.com)
1) https://gist.github.com/RLChris-Lim/52d1c1bb73ff679a34c17a91afa85542

#### Version
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-12-2018 10:14:37 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1010

**Comment by RLChris-Lim** [comment]
Additional Bug, encountering internal server error 500 when doing the following:

1. create website via. cloning to remote repository
2. delete the website on crafter studio
3. try to create website via. pull from same remote repository, using the same site id previously used
(this will throw server error while trying to create)

https://gist.github.com/RLChris-Lim/a13642c17b57be02d20687ae42f0c5ac

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1014

**Comment by RLChris-Lim** [comment]
Tested + Verified
