### ISSUE TITLE
[docs] Update Exporting/Importing a Site doc to use the new method

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1757]
http://docs.craftercms.org/en/3.0/system-administrators/studio/exporting-importing-site.html. Update it to use the new way of exporting/importing sites, where Studio can pull an existing Git repository and create a site from it.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/458

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/462 ,commit https://github.com/craftercms/docs/pull/462/commits/a411fabbc8487875a23519035e9687130339a4f6

**Comment by avasquez614** [comment]
Verified
