### ISSUE TITLE
[studio] Create Site with Git Repo code quality

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1758]
Code revisions
1. debug logs for happy case for `createSitePushToRemote` (logger exists for clone, but not push)
2. `createSiteCloneRemoteGitRepo` and `createSitePushToRemote` return booleans regarding whether they are successful or not, but method that calls them, `createSiteWithRemoteOption` doesn't use them, and only returns void.  the groovy script doesn't make use of it either, so as long as the `createSiteWithRemoteOption` returns properly, the response will always be "OK"

**Comment by sumerjabri** [comment]
Please add debug logs for happy path.
Please add exceptions/flow back to the API to support the exceptions detailed in the spec: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/site/create-site.html

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1012

**Comment by RLChris-Lim** [comment]
verified change
