### ISSUE TITLE
[studio-ui] User should not be able to logout when a user is signed in through sso

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1762]
### Expected behavior
User should not be able to logout when a user is signed in through sso

### Actual behavior
When testing header based authentication using modheader (headers modified), I am able to logout of Studio

### Steps to reproduce the problem
* modify the studio-config-override.yaml file to enable headers, then stop and start Studio
* open the tool to modify headers (i.e., modify headers chrome extension), and enter the following:
    `secure_key` for the name, then `secure` for the value
    `username` for the name, then `admin` for the value
    `firstname` for the name, then `admin` for the value
    `lastname` for the name, then `admin` for the value
    `email` and `admin@example.com` for the value

* After modifying the headers, then in your browser, point it to `localhost:8080/studio/#/site`, which should take you to the `sites` screen
* Try to logout, by clicking on the username on the top right of Studio, then select **Sign out** 
Notice that the user is signed out of the system.

It would be nice if **Sign out** is hidden from the user when the user is signed in to Studio through sso ( do not allow user to logout if user is signed in through sso)

#### Version
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-12-2018 10:45:51 -0500
#### OS
Mac OS
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
Depends on: https://github.com/craftercms/craftercms/issues/2397

@vestrada When that ticket is completed, you should be able to know if the user is Externally Managed SSO which means don't render the logout button.

**Comment by sumerjabri** [comment]
This ticket is replaced by: https://github.com/craftercms/craftercms/issues/2450
