### ISSUE TITLE
[studio] Studio API call for Post Activity mismatched parameters

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1763]
### Expected behavior
REST API call to Post Activity should allow for activity to be posted

### Actual behavior
Parameters do not line up between `ActivityServiceImpl` and `ActivityServices` groovy postActivity Call, and postActivity is unable to be run

### Steps to reproduce the problem
* Any valid REST call to `/studio/api/1/services/api/1/activity/post-activity.json`

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/RLChris-Lim/1c772760bdacfa033c7f72b392be67f5

### Specs
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-12-2018 10:14:37 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1011

**Comment by RLChris-Lim** [comment]
tested and verified
