### ISSUE TITLE
[studio] Remove unused APIs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1765]
# Remove the APIs
`/api/1/services/fixldp`
`/api/1/services/api/1/content/diff-content`
`/api/1/services/api/1/content/copy-content`
`/api/1/services/api/1/content/move-content`
`/api/1/services/api/1/server/get-server-info`
`/api/1/services/api/1/workflow/get-active-jobs`
`/api/1/services/api/1/site/import-site`
`/api/1/services/api/1/site/check-links`
`/api/1/services/util/cipher/hash-password`
`/api/1/services/util/time/convert-time`
`/api/1/services/api/1/site/get-canned-messages`
`/api/1/services/monitoring-status`
`/api/1/services/api/1/deployment/get-deployment-queue`
`/api/1/services/api/1/deployment/get-sync-target-queue`
`/api/1/services/api/1/deployment/get-deployment-jobs`
`/api/1/services/api/1/deployment/get-deployment-endpoints`
`/api/1/services/api/1/deployment/cancel-deployment`
`/api/1/services/api/1/workflow/submit-to-delete`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1017
