### ISSUE TITLE
[docs] Document APIs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1766]
`/api/1/services/api/1/box/upload` - ask Jose Ross
`/api/1/services/api/1/site/monitor-content` - ask Russ
`/api/1/services/api/1/aws/elastictranscoder/transcode` - ask Alfonso and Jose Ross
`/api/1/services/api/1/aws/s3/upload` - ask Jose Ross
`/api/1/services/api/1/site/write-configuration` - ask Dejan

**Comment by alhambrav** [comment]
`/api/1/services/api/1/site/write-configuration` is already documented

PR https://github.com/craftercms/docs/pull/442, commit https://github.com/craftercms/docs/pull/442/commits/a29a725eafc5e29ce8d30ce877a6b8eca9ef87d3
