### ISSUE TITLE
[docs] Studio API Request Publishing docs wrong parameters listed

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1769]
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/workflow/submit-to-go-live.html
`site` listed 4 times

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/438, commit https://github.com/craftercms/docs/pull/438/commits/bf464763421141e08083d6b88dab16468db245d8

**Comment by RLChris-Lim** [comment]
docs fixed
