### ISSUE TITLE
[craftercms] Add new gradle task to run the scripts on src/test-suite for pretest check out

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1770]
### Request
The new task should execute the next scripts on src/test-suite (according to with the platform where it will be executed):
-initialSetupCheckForTestScript.sh
-initialSetupCheckForTestScript.bat

### How it would work
* Go to craftercms folder and we need to execute the pretest check (environment setup check) before the execution of automated test framework (**here we need new task of gradle**)
 Note:
According to with the following ticket, we need the pre-test task:
https://github.com/craftercms/craftercms/issues/1431

**Comment by cortiz** [comment]
@sumerjabri / @luishernandezmonge  there is a small problem with these:
I can make the run but since it's already running in a  Gradle task I need to discard any output since I'll have issues with the redirection of outputs that already are redirect (mostly because its a gradle task running gradle tasks from CLI)

There are 2 options:
1. discard any output
2. Make the scripts redirect it's outputs to File.

**Comment by sumerjabri** [comment]
@cortiz have it redirect to a `logs` folder with a `test-suite` subfolder
Make sure `logs` is in .gitignore of `craftercms`
Make sure `logs` and `logs/test-suite` are auto-created.
Make sure to overwrite the logs every run (so the logs can't grow) since these logs are transient in nature.

**Comment by cortiz** [comment]
Added the new task as `selftest`

**Comment by luishernandezmonge** [comment]
Checked on my side.
However, I will assign this to vita to double check and get feedback on this.
@alhambrav Please, can you check this ticket?

**Comment by alhambrav** [comment]
@luishernandezmonge checked on my side too, OS X is okay, in Windows, the command line window used to launch the gradlew selftest is closed at the end of the test (as I mentioned in our conversation)

**Comment by luishernandezmonge** [comment]
I'm working on this now

**Comment by luishernandezmonge** [comment]
Added the fix on the next PR: https://github.com/craftercms/test-suite/pull/291 @alhambrav  Please, can you test this again?

**Comment by alhambrav** [comment]
@luishernandezmonge Verified okay on Windows and OS X.

**Comment by luishernandezmonge** [comment]
Verified as fixes and implemented, according with comment of above
