### ISSUE TITLE
[studio-ui] There's an extra icon between Video and Page Order in the controls

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1774]
### Expected behavior
There should be no extra icon between Video and Page Order in the controls when editing a content type

### Actual behavior

There's an extra icon between Video and Page Order in the controls when editing a content type
![screen shot 2018-01-16 at 9 37 53 am](https://user-images.githubusercontent.com/25483966/34994450-81098ad8-faa1-11e7-87d8-e29c339578c2.png)

### Steps to reproduce the problem
* Create a site using any of the bp's
* Click on **Site Config** from the **SIdebar**
* Click on **Content Types**
* Click on **Open Existing Type**, select any
* Go to the **Controls**, and scroll to **Video**, notice the extra icon immediately after **Video**, I'm not sure if there's supposed to be another control there that's just missing the label or if the icon is not supposed to be there at all.

#### Version
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-16-2018 09:31:37 -0500
#### OS
Mac OS
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/747

**Comment by alhambrav** [comment]
Verified fixed.
