### ISSUE TITLE
[CrafterCMS] Add support of Maven Release plugin

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1785]
Add support for all projects (that uses maven) to use the maven release (or maven git-flow release plugin) to remove the manual step in the build-release process. This should remove the need of find-replace the pom versions. also, check that all projects that use CrafterCMS uses variables and not hardcoded version numbers.

**Comment by sumerjabri** [comment]
Added for v4. Still needs to be tested.

**Comment by sumerjabri** [comment]
Completed
