### ISSUE TITLE
[studio-ui] publishing is stopped in the database but it's not indicated in the UI

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1786]
### Expected behavior
Publishing status icon in studio should be red and dialog should indicate that publishing is stopped

### Actual behavior
Icon does not change
When publishing was working, it was changing from idle to orange (deploying)
When publishing stopped, icon did not switch to stopped status

<img width="709" alt="screen shot 2018-01-22 at 9 48 20 am" src="https://user-images.githubusercontent.com/169432/35226621-d9de2b48-ff59-11e7-9482-bda953b83dc5.png">

### Steps to reproduce the problem
* disable publishing  

### Log/stack trace (use https://gist.github.com)
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-15-2018 21:03:10 -0500

**Comment by jvega-crafter** [comment]
Publishing status icon is refreshed every 60 seconds when dialog is not open, is you click on icon it will refresh inmediately, and while open it will refresh every 3 seconds according to this ticket https://github.com/craftercms/craftercms/issues/1409, per discussion with Sumer

**Comment by sumerjabri** [comment]
@jvega-crafter Publishing was disabled for hours and it never went red.

**Comment by jvega-crafter** [comment]
Tried with new publishing page (start/stop) and it works, also manually calling api as in docs

http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/start.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/stop.html,

Status icon shows status directly from service, is it returning proper status? (`/studio/api/1/services/api/1/publish/status.json?site_id=site`)

**Comment by russdanner** [comment]
VERIFIED
