### ISSUE TITLE
[studio] Don't stop publishing for duplicate key exceptions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1789]
Per our conversation, the publisher stops if it encounter's duplicate key exception during git_log table updates. This can happen when content is being written during the publisher's duty cycle.

If you run into a duplicate key exception, log the error, and the entry as unprocessed so it would be picked up in the next cycle.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1015
