### ISSUE TITLE
[studio] studio dashboard showing folder objects

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1791]
### Expected behavior
Folders cannot be acted on from the dashboard and should not be shown 

### Actual behavior
<img width="1159" alt="screen shot 2018-01-22 at 3 40 51 pm" src="https://user-images.githubusercontent.com/169432/35253827-61377d78-ffb5-11e7-86e9-1fc6b43cb2f6.png">

### Steps to reproduce the problem
1. Create a new folder in static assets
2. upload a item in the folder
3. change my recent activity to show all

### Log/stack trace (use https://gist.github.com)
N/a

#### Version
Studio Version Number: 3.0.4-SNAPSHOT-96266f
Build Number: 96266fc3bdc591a154e4eb9b4218f9dc9153193c
Build Date/Time: 01-15-2018 21:03:10 -0500

**Comment by jvega-crafter** [comment]
When retrieving info from recent-activity (`/studio/api/1/services/api/1/activity/get-user-activities.json`) folders are returned, screenshot attached

![screen shot 2018-01-24 at 10 51 16 am](https://user-images.githubusercontent.com/18267471/35345294-e0f132da-00f4-11e8-9696-915e95f172d3.png)

**Comment by sumerjabri** [comment]
@jvega-crafter I spoke to Russ and for now, please hide folders from the dashboard.

**Comment by jvega-crafter** [comment]
done, https://github.com/craftercms/studio-ui/pull/750

**Comment by russdanner** [comment]
VERIFIED
