### ISSUE TITLE
[test-suite] Generate a test result file for the script for the initial setup of sanity test

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1792]
### Expected behavior
A test result file of the script run for the initial setup of sanity test would be nice. 

### Actual behavior
Results can be viewed only on the command line where the script is run as part of the step-by-step output, so, say you did a few more things in the command line, then wanted to check the results of the initial setup of sanity test, you may not be able to see it since your terminal window has a set number for the buffer.

### Steps to reproduce the problem
* Run the script for the initial setup of sanity test

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-185754
Build Number: 185754002e81ef9d2c0599e72ff531132981ce14
Build Date/Time: 01-23-2018 09:31:33 -0500
#### OS
OS X

**Comment by luishernandezmonge** [comment]
I'm working on this for Linux/Mac (First priority)

**Comment by luishernandezmonge** [comment]
Done for both scripts (Windows script and Linux/Mac script).
PR: https://github.com/craftercms/test-suite/pull/277
@alhambrav Please, let me know your feedback when you are able to review the changes.

**Comment by alhambrav** [comment]
Verified.
