### ISSUE TITLE
[Studio] Fix the API to make it compliant with the spec

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#1793]
### Expected behavior
Get publisher's status api should response with the correct message, for example: "Last successful publish was for item: {item_path} on {yyyy-MM-dd'T'HH:mm'Z'}" http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/status.html

### Actual behavior
The api response is not compliant with the spec.
Example: 
{"status":"idle","message":"Idle"}
 
### Steps to reproduce the problem
* Create a site using any of the bp's
* On preview page click on the Publish Status Icon
* Go to network in the browser inspector
* See the api response (http://localhost:8080/studio/api/1/services/api/1/publish/status.json?site_id={site_id})

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-185754

Build Number: 185754002e81ef9d2c0599e72ff531132981ce14

Build Date/Time: 01-23-2018 11:24:32 -0600
#### OS
Mac OS

#### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1023
