### ISSUE TITLE
[studio-ui] long internal names bleed over tool tip

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1795]
### Expected behavior
Tooltip should expand to a reasonable length (150 characters) and then force the text to wtap

### Actual behavior
Text overruns tool tip 
<img width="476" alt="screen shot 2018-01-23 at 3 45 32 pm" src="https://user-images.githubusercontent.com/169432/35299873-b7d1aaa6-0054-11e8-9fb7-4397c5874b0e.png">

### Steps to reproduce the problem
* Create a content item with a very long internal name  
* Hover over item on dashboard and side bar

#### Version
 Applies to 2.x and 3.x

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/751

**Comment by jvega-crafter** [comment]
Fix is already on 3.0.x, applied on 2.5.x

**Comment by russdanner** [comment]
VERIFIED

**Comment by russdanner** [comment]
This fix does not work in Firefox

**Comment by vestrada** [comment]
PR:
3.1.x -> https://github.com/craftercms/studio-ui/pull/1023
3.0.x -> https://github.com/craftercms/studio-ui/pull/1024
2.5.x -> https://github.com/craftercms/studio-ui/pull/1025

Image:

![image](https://user-images.githubusercontent.com/11640613/50307272-8fa5fb00-045d-11e9-990d-873891b642bd.png)

**Comment by russdanner** [comment]
Confirmed
