### ISSUE TITLE
[studio] Create a new DependencyService impl per new interface

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1797]
Please implement the DependencyService as spec'd in the new interface `DependencyService`.

Please implement the publishing dependencies in compliance with https://github.com/craftercms/craftercms/issues/1638

Please make sure the scanner is compliant with: https://gist.github.com/sumerjabri/5a057925d0102fa58dbb22e431fba272

Ensure that upserting deps is shallow (direct scan only). No deep scans.

Also, all operations are against the db except upserts.

Ping me for more context and guidance.

**Comment by dejan-brkic** [comment]
2.5.x:
https://github.com/craftercms/studio/pull/1021

**Comment by dejan-brkic** [comment]
Done

**Comment by dejan-brkic** [comment]
3.0.x Done
PR:
https://github.com/craftercms/studio/pull/1056
