### ISSUE TITLE
[studio-ui] Delete view (and possibly other popups too) show on top of session timeout login view backdrop

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#1798]
<img width="798" alt="screen shot 2018-01-27 at 4 56 03 pm" src="https://user-images.githubusercontent.com/3928341/35473600-155717e8-0383-11e8-90b1-63e03982944f.png">

**Comment by sumerjabri** [comment]
Modal dialogs should be grayed out when the session expiration dialog appears.
