### ISSUE TITLE
[studio] API calls provide inconsistent information about the same item: get-items-tree.json, get-item.json, dashboard widget calls

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#1799]
### Expected behavior
Coherent information between all calls that refer to a particular content item / asset.

### Actual behavior
Same content item presents different values for, at least: `isContainer`, `container` and `numOfChildren` properties on `get-items-tree.json` vs `get-item.json`.

Dashboard widget calls are consistent with get-item, where `isContainer` is false and `numOfChildren` is 0 regardless of the real value.

### Steps to reproduce the problem
* Perform a request containing the same item to each of the mentioned API calls
* Compare the outputs

For example:
- `/studio/api/1/services/api/1/content/get-item.json?site=launcher&path=/site/website/index.xml` vs
- `/studio/api/1/services/api/1/content/get-items-tree.json?site=launcher&path=/site/website/index.xml&depth=1`
- Results in:
![screen shot 2018-01-28 at 9 57 33 am](https://user-images.githubusercontent.com/3928341/35480607-27d355f0-0412-11e8-8a8e-b8f5be6b03c2.png)

### Specs
```
$ git branch                              
master

$ git remote get-url --all origin         
https://github.com/craftercms/craftercms

$ git log --oneline -1 | awk '{print $1}'
4eb71a1
```

### Note / PS
- Is there a fundamental difference between `get-item.json` vs `get-items-tree.json`? 
  - What's the reason for the two different calls?
- At plain sight looks like `get-items-tree.json` is `get-item.json` with an ability to fetch children — enforcing depth parameter. In other words, `get-item.json` with an added optional depth — with the above mentioned inconsistencies fixed — would produce the same result.

**Comment by rart** [comment]
`get-item-versions.json` returns an item consistent with `get-item.json`
- Wrong numOfChildren
- Wrong isContainer

**Comment by dejan-brkic** [comment]
Not an issue. All 3 are different API calls and therefore have different information populated. They are all using same transport object (java class) as a response. Not all properties are being populated, nor needed by UI. That is why information is inconsistent.

**Comment by rart** [comment]
I disagree. Information for a given object should be consistent. 
Not critical as long as we don’t have to release UI4 with this API, though.
