### ISSUE TITLE
[studio] Unused properties from studio-config.yaml

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1801]
Seems that properties `studio.security.urlsToInclude`, `studio.security.urlsToExclude` and `studio.security.exceptionUrls` are not being used.

**Comment by sumerjabri** [comment]
@dejan-brkic I think we should make those work instead of removing them.

Please remove any hardcoded URLs and instead use what's in the config.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1037

**Comment by sumerjabri** [comment]
@dejan-brkic see my notes above
