### ISSUE TITLE
[studio] Header based authentication error

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1802]
### Expected behavior
When a new user logs in using SAML authentication, user should be able to get into the sites page (password should not be required by Studio)

### Actual behavior
When a new user logs in using SAML authentication, the user is not logged in to Studio (redirected to Login screen) and there is an error in the tomcat log.

### Steps to reproduce the problem
* Setup header based authentication in Studio by enabling it in the studio-config-override.yaml file
* Login to Studio (IdP will ask for your credentials, SP should redirect you to Studio sites page. Use an account that will be logging in to Studio for the very first time)  Notice that you are redirected to the login screen of Studio and if you look at the tomcat logs, there are errors.
You can also just set the headers using the **Modify Headers** extension in chrome, (user should be a new user to Studio) to reproduce the error.

### Log/stack trace (use https://gist.github.com)
(Please note that I have added some debug messages for myself to check that the headers are being sent correctly, all my messages begin with `vita::`

https://gist.github.com/alhambrav/b32bc3ad153a20e252d6c9e747119ec4

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-9836de
Build Number: 9836de067ed16a7105fe94b93f36caab090b583b
Build Date/Time: 01-29-2018 12:17:59 -0500
#### OS
Linux
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1022

**Comment by alhambrav** [comment]
Verified fixed.
