### ISSUE TITLE
[studio] 2.5.x publish dialog shows previously published items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1810]
### Expected behavior
Get publishing dependencies should only contain items that need to be published

### Actual behavior
All dependencies are shown regardless of state

### Steps to reproduce the problem
* publish an item that points to a template "A"
* Not since the item and template A have not been published before both should be listed
* publish another item that ports to the same template
* Note template A shows up as a dependency but it is previously published and should not
https://www.useloom.com/share/1c7f956d5707461383d5ce999486be95

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1024

**Comment by russdanner** [comment]
VERIFIED
