### ISSUE TITLE
[studio] 2.5.x duplicate is not duplicating dependencies

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1812]
### Expected behavior
When an item is duplicated or copy pasted it must duplicate it's item-specific references.

### Actual behavior
https://www.useloom.com/share/e29ef07ddfd248f48710d536f79d8422

### Steps to reproduce the problem
* Copy paste item with item-specific dependencies
* Duplicate item with item-specific dependencies

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1026

**Comment by russdanner** [comment]
CONFIRMED
