### ISSUE TITLE
[studio] Target created when create site is called is not deleted when the create site api fails. (Create site based on a blueprint then push to remote bare git repository)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1814]
### Expected behavior
Cleanup should be performed when a site is rolledback/deleted when there is an error in the create site api (Create site based on a blueprint then push to remote bare git repository)

### Actual behavior
Target created when create site is called is not deleted when the create site api fails. (Create site based on a blueprint then push to remote bare git repository)
```
[ERROR] 2018-02-01 02:40:31,454 [http-nio-8080-exec-10] [site.SiteServiceImpl] | Error while rolling back/deleting site: site1 ID: site1 from blueprint: empty. This means the sites preview deployer target is still present, but the site is not successfully created.
```

### Steps to reproduce the problem
* Create a bare git repository
* In your Studio, create a site, and click on  **Link to upstream remote Git repository**, fill in the fields **Remote Git Repository Name (Example: origin)**, **Remote Git Repository URL**,  and select **Create site based on a blueprint then push to remote bare git repository**, select any blueprint.  Do not put in a username and password (to make the create site fail)
* A notification will appear:
<img width="562" alt="screen shot 2018-02-01 at 1 53 21 am" src="https://user-images.githubusercontent.com/25483966/35667625-63051df6-06fc-11e8-978c-430888b08053.png">

Look at the tomcat log and notice the error messages.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/0363a3f8fd4500ce9f14d8d98f06a6ab

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-f1cfb4
Build Number: f1cfb4f517001e16a4712407c777b5b257da2db1
Build Date/Time: 01-31-2018 11:12:48 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
This is expected behavior. The message is generated as a failed attempt to delete target on deployer after site creation failed. Delete target failed once, there is no much sense trying to delete it again. That is why there is a message in the log.

**Comment by sumerjabri** [comment]
@dejan-brkic let's find out why delete target failed and fix/file a deployer bug.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1040

**Comment by alhambrav** [comment]
Verified fixed.
