### ISSUE TITLE
[studio] Unable to create site (Create site based on remote git repository) when using ssh for the repository url

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1815]
### Expected behavior
User should be able to create a site (Create site based on remote git repository) when using ssh for the repository url.

### Actual behavior
Unable to create site (Create site based on remote git repository) when using ssh for the repository url.

### Steps to reproduce the problem
* * In your Studio, create a site, and click on  **Link to upstream remote Git repository**, fill in the fields **Remote Git Repository Name (Example: origin)**, **Remote Git Repository URL** (using ssh),  and select **Create site based on remote git repository**.  I have the private key in the computer being used.
<img width="562" alt="screen shot 2018-02-01 at 3 46 18 am" src="https://user-images.githubusercontent.com/25483966/35669272-87d962bc-0702-11e8-8f49-60f83bf1643e.png"> 
* A notification will appear with the message, **Unable to create site. Please contact your system administrator.
Error: Remote repository not found**
* Notice the error logs in the tomcat logs

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/ab2d8baad8d75cf390dad9126f2028b3

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-f1cfb4
Build Number: f1cfb4f517001e16a4712407c777b5b257da2db1
Build Date/Time: 01-31-2018 11:12:48 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@avasquez614 Per our conversation yesterday, please explain what this means and how to fix and then I'll assign to someone else.

**Comment by avasquez614** [comment]
This is because the key is in ECDSA format and JGit by default only accepts RSA. Deployer has a code that configures the SSH session so that it is flexible and uses any key format according to the current keys present. The classes are under https://github.com/craftercms/deployer/tree/master/src/main/java/org/craftercms/deployer/utils/git. They're generic enough so it might be a good idea to move them to commons and make both Deployer and Studio use them.

**Comment by cortiz** [comment]
Solve on PR https://github.com/craftercms/studio/pull/1033 

Do notice that user needs to fill the username and password fields too.

**Comment by sumerjabri** [comment]
@cortiz what if the user is using key-based authentication, why will the user need a username/password?

**Comment by cortiz** [comment]
@sumerjabri  That really depends on how we implement it, users might need the password of the Private key to unlock it. Also, do we what store that kind of credentials (private ssh-keys)

**Comment by alhambrav** [comment]
Verified.  Closing this ticket and will open a new one to get key-based authentication supported.
