### ISSUE TITLE
[studio] Javadoc warning messages when building Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1816]
### Expected behavior
No warning messages when building Studio would be nice.

### Actual behavior
There are Javadoc warning messages when building Studio

### Steps to reproduce the problem
*  Build craftercms.  Watch the output when building Studio, notice the Javadoc warning messages.

### Log/stack trace (use https://gist.github.com)
7 warnings
[WARNING] Javadoc Warnings
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/repository/ContentRepository.java:341: warning - @return tag has no arguments.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/repository/ContentRepository.java:353: warning - @return tag has no arguments.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/repository/ContentRepository.java:363: warning - @return tag has no arguments.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/service/aws/S3Service.java:25: warning - @return tag has no arguments.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/service/dependency/DependencyDiffService.java:35: warning - @return tag has no arguments.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v1/service/dependency/DependencyService.java:74: warning - @param argument "paths" is not a parameter name.
[WARNING] /Users/vita/temp/test5/crafter_cms_temp/craftercms/src/studio/src/main/java/org/craftercms/studio/impl/v1/service/dependency/DependencyDiffServiceImpl.java:42: warning - @return tag has no arguments.

### Specs
Studio Version Number: 3.1.0-SNAPSHOT-f1cfb4
Build Number: f1cfb4f517001e16a4712407c777b5b257da2db1
Build Date/Time: 01-31-2018 11:12:48 -0500
#### OS
OS X
#### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1049

**Comment by alhambrav** [comment]
Verified fixed.
