### ISSUE TITLE
[studio-ui] Default (home) page is broken on first load of new user when authentication with headers is used

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1817]
### Expected behavior
On first load, with a new studio user, studio ui displays `sites` page (`http://localhost:8080/studio/#/sites`)

### Actual behavior
Redirect correctly but page display is broken
![screen shot 2018-02-01 at 10 31 16 am](https://user-images.githubusercontent.com/25483966/35687051-b8e9ba30-073b-11e8-98f4-82d092aa0b3d.png)

### Steps to reproduce the problem
* Configure authentication headers provider
```
studio.security.type: headers
# Authentication via headers enabled
studio.authentication.headers.enabled: true
# Authentication header for secure key
studio.authentication.headers.secureKeyHeaderName: secure_key
# Authentication headers secure key that is expected to match secure key value from headers
# Typically this is placed in the header by the authentication agent, e.g. Apache mod_mellon
studio.authentication.headers.secureKeyHeaderValue: secure
# Authentication header for username
studio.authentication.headers.username: username
# Authentication header for first name
studio.authentication.headers.firstName: firstname
# Authentication header for last name
studio.authentication.headers.lastName: lastname
# Authentication header for email
studio.authentication.headers.email: email
# Authentication header for groups: comma separated list of sites and groups
#   Example:
#   craftercms1645,Author,anothersite,Author
studio.authentication.headers.groups: groups
```
* start studio
* use Google Chrome Extension: ModHeader to add authentication headers, add a user who is not yet in the Studio db
* open `http://localhost:8080/studio/`

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-a4d4d0
Build Number: a4d4d0fa05ea5c624f4b774cff780a003353cee2
Build Date/Time: 02-01-2018 09:20:13 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1035

**Comment by alhambrav** [comment]
Verified fixed.
