### ISSUE TITLE
[studio-ui] 2.5.x dialog for dependencies displays wrong file after API updates.   

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1818]
### Expected behavior
Assuming the new API response is what we want, the dialog must be updated accordingly.
Currently clicking a page and asking for dependencies displays the wrong object.

### Actual behavior
<img width="1417" alt="screen shot 2018-02-01 at 11 38 28 am" src="https://user-images.githubusercontent.com/169432/35690903-1b26d9b8-0745-11e8-9248-f76ce050d3a8.png">

### Steps to reproduce the problem
* create a page with an image dependency
* right click on it in the site nav and ask for dependencies
* see incorrect dialog

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/756

**Comment by russdanner** [comment]
VERIFIED
