### ISSUE TITLE
[studio] 2.5.x dependencies is referenced by returns the object itself

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1819]
### Expected behavior
Asking what objects contain a reference to object A should not result in a response that contains object A.

### Actual behavior
https://www.useloom.com/share/0cd117d93aac41229a4986dad04d4467

### Steps to reproduce the problem
* create a page the contains a reference to an image 
* open the dependencies for the page
* switch the drop-down to "refers to this item"
* note the incorrect response

**Comment by dejan-brkic** [comment]
This is fixed by UI fix for dependencies dialog. However, UI is still using wrong service call for dependencies in dependencies dialog. It is using get-dependencies (workflow dialogs - gets all dependencies) instead of get-simple-dependencies (returns direct dependencies)

**Comment by jvega-crafter** [comment]
Changed to `get-simple-dependencies`

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/759

**Comment by russdanner** [comment]
This is mostly fixed.  The only issue is that the item itself is still showing.  That doesn't make any sense.  The item does not reference itself.

<img width="1115" alt="screen shot 2018-02-05 at 10 19 41 pm" src="https://user-images.githubusercontent.com/169432/35840232-ee8dc610-0ac2-11e8-8004-0e40ad6b2b08.png">

This issue can be downgraded and fixed in a future release

**Comment by jvega-crafter** [comment]
Hi @russdanner, I can't reproduce the same item showing, https://www.useloom.com/share/1c68a18476564dc1b054ec388c360dbf
I'm still going to add a validation if the service returns itself as dependency

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/761

**Comment by russdanner** [comment]
CONFIRMED. 
Previous test failures seem related to data.  New content objects do not show this.
