### ISSUE TITLE
[studio] 2.5.x duplicate does not properly update item specific references on duplicate

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1823]
### Expected behavior
Studio should duplicate item specific references AND update references in the item on duplicate

### Actual behavior
Duplicate the references but leaves the references to the old item in place
https://www.useloom.com/share/811f8527e43448ce9b1ed74378e93db7

### Steps to reproduce the problem
* save an item with item-specific dependencies
* duplicate that item
* note new item specific dependencies will have been created but the references in the item itself point to the original item's item-specific dependencies.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1029

**Comment by russdanner** [comment]
VERIFIED
