### ISSUE TITLE
[studio] 2.5.x publish of rename leaves original item in environment-store

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1824]
### Expected behavior
rename should remove the original path item and leave only the new path

### Actual behavior
Old path is being left
https://www.useloom.com/share/f712748a0e4f42fbbbcc7d8c3edee3f0

### Steps to reproduce the problem
* Publish an item, check environment store for item 
* Rename the item, no change in store as expected
* Publish the renamed item, new path shows up but old object is not removed

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1028

**Comment by russdanner** [comment]
VERIFIED
