### ISSUE TITLE
[studio] rename does not properly preview sync item

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1825]
### Expected behavior
when an item is renamed it should be removed from preview and the new item should be saved/indexed

### Actual behavior
Old name is preview sync'd
New object is not
Opening the newly named item and saving causes preview sync but form does not close
subsequent saves work as expected
note the original item is NEVER removed from preview
https://www.useloom.com/share/4ddc6ef90d514b2dbc5d35a35823a635

### Steps to reproduce the problem
* Demonstrated in video

**Comment by russdanner** [comment]
Observed in ORACLE+ALfresco
I did not see it in DISK+DERBY but makes me wonder.. this does not seem like it should be store-specific although it appears to be

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1030

**Comment by russdanner** [comment]
VERIFIED
