### ISSUE TITLE
[studio - ui] Studio crashes when user tries to upload an .ova file through the bulk upload

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1831]
### Expected behavior
The file should be uploaded without crashing the studio ui and without problems

### Actual behavior
Studio crashes and the **Aw, snap!** pag is displayed instead of the preview page
watch the next video:
https://www.useloom.com/share/46b34488f836449b8f632035947028b1

### Steps to reproduce the problem
* Go to Studio and login as admin
* Create a site
* Go to preview and expand **Sidebar**
* Expand **Static Assets**
* Right click on **static-assets** and click on **bulk upload assets**
* Drag and drop a file with ova extension (if you does not have it... generate it with the next command 
**mkfile -n 3g test-file.ova** )

### Log/stack trace (use https://gist.github.com)
No log errors for this issue

#### Version
Crafter build:
3.0.5-SNAPSHOT-aafae6
Build Number: aafae6fe97e970ccc7df28dd21690b0a2fedcf6d
#### OS
Env: Mac/Windows/Linux
#### Browser
Web Browser: Chrome

**Comment by luishernandezmonge** [comment]
Same happens if we use .zip files (around 3gb size)

**Comment by sumerjabri** [comment]
@jdrossl this is not file type related, just very large files dropped into the bulk-uploader. Ping me to discuss as needed.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/762

**Comment by luishernandezmonge** [comment]
Verified as resolved
