### ISSUE TITLE
[studio] 2.5.x delete dependencies does not cascade when nested

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1833]
### Expected behavior
If you an object A that forces another object B to get deleted, B's item-specific dependencies should also be deleted.
 
Examples 
1. delete a folder that contains a page that has item-specific images
2. delete a page that points to a component that has item specific images
3. any variation or depth of the above examples: 
page has an item specific component which has an item specific component which has an item specific component which has item specific images

### Actual behavior
B's dependencies are not deleted
Note the last comment in the video references "deploy dependencies" but i meant to say "delete dependencies"
https://www.useloom.com/share/72a029746142414d901e45b5392953bd

### Steps to reproduce the problem
* create a folder 
* in the folder create a page with item specific images
* delete the folder
* note the item specific images are left un-touched

**Comment by russdanner** [comment]
Note the last comment in the video references "deploy dependencies" but i meant to say "delete dependencies"

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1043

**Comment by russdanner** [comment]
Confirmed
