### ISSUE TITLE
[studio-ui] Session expired dialog does not appear when in the "Sites" screen.

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1835]
### Expected behavior
Session expired dialog should appear when in the **Sites** screen

### Actual behavior
Session expired dialog does not appear when in the "Sites" screen.  When you try to click any of the buttons/options in the **Sites** screen, it will then take you to the login dialog

### Steps to reproduce the problem
* Login to Studio 
* Leave your screen in the **Sites** screen until the Studio session times out.  You can shorten the timeout by adding in the `studio-config-override.yaml` file the following(notice the timeout set is 5 minutes, the default session timeout is 60 minutes):
```
# HTTP Session timeout for studio (value is in minutes).
studio.security.sessionTimeout: 5
```
* Notice that the session expired dialog does not appear at all and if you try to click on any of the buttons/options in the **Sites** screen, a login dialog will appear.  This also happens with the **About** screen

#### Version
Studio Version Number: 3.0.5-SNAPSHOT-aafae6
Build Number: aafae6fe97e970ccc7df28dd21690b0a2fedcf6d
Build Date/Time: 02-05-2018 05:59:18 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/765

**Comment by alhambrav** [comment]
Verified fixed.
