### ISSUE TITLE
[studio-ui] There's an empty notification dialog when the Studio session times out in Site Config -> Publishing screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1836]
### Expected behavior
There should be no empty notification dialog when the Studio session times out. (Or, is there supposed to be a notification but the dialog is empty?)

### Actual behavior
There's an empty notification dialog when the Studio session times out in the **Bulk Publish** screen

<img width="1360" alt="screen shot 2018-02-06 at 12 03 44 am" src="https://user-images.githubusercontent.com/25483966/35842904-37aa6794-0ad3-11e8-89ce-9e095412c6c7.png">

Also, notice that even when you click on the **Close** button of the notification dialog, the notification dialog does not go away.  

### Steps to reproduce the problem
* Login to Studio 
* Open the **Sidebar** then click on **Site Config**.  Click on **Publishing**, then leave your screen until the Studio session times out.  You can shorten the timeout by adding in the `studio-config-override.yaml` file the following(notice the timeout set is 5 minutes, the default session timeout is 60 minutes):
```
# HTTP Session timeout for studio (value is in minutes).
studio.security.sessionTimeout: 5
```
* Notice that the session expired dialog will appear and there's an empty notification dialog behind the login dialog.  After logging in, if you click on **Close** in the notification dialog, the dialog does not go away
 
#### Version
Studio Version Number: 3.0.5-SNAPSHOT-aafae6
Build Number: aafae6fe97e970ccc7df28dd21690b0a2fedcf6d
Build Date/Time: 02-05-2018 05:59:18 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/763

**Comment by alhambrav** [comment]
Verified fixed.
