### ISSUE TITLE
[docs] Upgrades need own section

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1844]
Per our conversation, please create an upgrades section under sys-admin and move existing upgrade related articles there.
Please prepare to have minor upgrade instructions to list the various nuances an upgrade may indicate.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/456
PR https://github.com/craftercms/docs/pull/457

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/466

**Comment by sumerjabri** [comment]
Please merge: system-administrators/upgrade/notes-on-upgrading-to-3-0.html
into: system-administrators/upgrade/upgrading-to-craftercms-3-0.html after the first warning to explain the main changes in the repo structure and where the configuration is now stored.

The "notes" need to be part of the upgrade document.

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/467

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/471
