### ISSUE TITLE
[docs] Restructure release notes

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1845]
Per our conversation, please restructure the release notes by:

1. Moving all 2.5 release notes to the 2.5 doc branch such that 3.0 only contains 3.0.x
2. Put a note at the top of the page indicating that for other release notes, please visit your release's release notes page and link to http://docs.craftercms.org

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/453
PR https://github.com/craftercms/docs/pull/454

**Comment by sumerjabri** [comment]
Per our conversation, please change the page title to "Release Notes" so it fits well with the rest of the navigation.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/465 commit https://github.com/craftercms/docs/commit/9b08261a8340a3d246172490726f97da19a5558d
