### ISSUE TITLE
[studio-ui] Static assets folders are not refreshed after delete an image item when file name contains dots and spaces

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1848]
### Expected behavior
The static assets folders should be refreshed and the just deleted item should disappears  
### Actual behavior
The static assets folders are not refreshed and the deleted item stills there
Watch the next video:
https://www.useloom.com/share/fb0d27783a2e4170923296b8a8495efe

### Steps to reproduce the problem
* Go to Studio and login as admin
* Create a site
* Go to preview and expand Sidebar
* Expand Static Assets
* Right click on static-assets and click on bulk upload assets
* Drag and drop an image file (use an existent image with the next name: "Screen Shot 2018-02-05 at 9.49.07 AM.png"
* Go to the just uploaded image and right click, later select Delete and delete it.
*Wait and review the static-assets folder and noticed that the image stills there

### Version
Crafter build:
Studio Version Number: 3.0.5-SNAPSHOT-589074
Build Number: 58907486bfac1946353aad13f9f3b964571fdf93
### OS
Env: Mac/Windows/Linux
### Browser
Web Browser: Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/768

**Comment by luishernandezmonge** [comment]
Verified as resolved
