### ISSUE TITLE
[studio-ui] side bar listeners are not being removed after edit

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1850]
## Steps to reproduce the problem
https://www.useloom.com/share/edad92ea63cb4e5792d119bf263c7be2

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-deb89f
Build Number: deb89f9cd1051b6e914a4e25772496da4d73ea50
Build Date/Time: 01-26-2018 15:33:46 -0500

#### Browser
Chrome

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/767

**Comment by russdanner** [comment]
VERIFIED
