### ISSUE TITLE
[studio-ui] context nav edit button does not alway re-enable itself on save

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1851]
# Expected behavior
I should be able to edit/save/REPEAT as many times as I want

### Steps to reproduce the problem
https://www.useloom.com/share/3d630a814cb249e2a49f1ff291e6a0c2

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-deb89f
Build Number: deb89f9cd1051b6e914a4e25772496da4d73ea50
Build Date/Time: 01-26-2018 15:33:46 -0500

#### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/766

**Comment by russdanner** [comment]
VERIFIED
