### ISSUE TITLE
[studio] Studio API Group Management adding 404 Site not Found error

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1852]
### Expected behavior
API calls with site id included in REST parameters should return 404 site not found error

### Actual behavior
404 site not found error missing in various api calls

### Applicable to Group Management API calls:
* add user to group
* delete group
* get group
* get groups
* get users per group
* remove user from group
* update group

**Version**
Studio Version Number: 3.0.5-SNAPSHOT-589074
Build Number: 58907486bfac1946353aad13f9f3b964571fdf93
Build Date/Time: 02-07-2018 12:47:53 -0500

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1050

**Comment by RLChris-Lim** [comment]
https://gist.github.com/RLChris-Lim/d0bb3fc268eadc2b09544a78e374d480

All working except for Update Group, both 404 Group not found, and 404 Site not found throwing 500 server error instead

**Comment by dejan-brkic** [comment]
Works fine with the following build
```
Studio Version Number: 3.0.8-SNAPSHOT-1749ac

Build Number: 1749ac6ba29558d397cd48a4d853473fba19fd21

```

**Comment by RLChris-Lim** [comment]
Verified
