### ISSUE TITLE
[studio-ui] folders created in sidebar require refresh before the show

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1855]
### Expected behavior
Folder should show in IA after closing the dialog

### Actual behavior
https://www.useloom.com/share/459db26d479640bfbc094c4b713c6857

### Steps to reproduce the problem
* in the sidebar open pages, right click, create folder on Home page 
* create a folder
* note it does not show up.  Refresh, it's there

#### Version
Studio Version Number: 3.0.5-SNAPSHOT-d686d2
Build Number: d686d27de39190d7d515af2bbef0b4d3c6d92a6c
Build Date/Time: 02-09-2018 01:55:07 -0500

#### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/770

**Comment by russdanner** [comment]
VERIFIED
