### ISSUE TITLE
[studio] Key-based authentication fails when creating a site with link to remote repository

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1857]
### Expected behavior
Key-based authentication should be supported when creating a site with link to remote repository

### Actual behavior
Key-based authentication does not work for creating a site with link to remote repository.

### Steps to reproduce the problem
* Make sure the needed ssh keys are setup.
* Log in to Studio, in your **Sites** screen, click on **Create Site** 
* Fill in the **Site Id** and **Description**, then click on **Link to upstream remote Git repository**
* Once **Link to upstream remote Git repository** is expanded, fill in the **Remote Git Repository Name** and **Remote Git Repository URL**, then in **Options**, click on **Create site based on remote git repository**
* Click on the **Create** button, you'll get a **Notification** dialog saying:
```
Unable to create site.  Please contact your system administrator.
Error: Remote repository not found
```

Look in your tomcat log and notice the error messages there.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/d9e577da7d7678f1833c0aeb5ae9f8a2

#### Version
Studio Version Number: 3.0.5-SNAPSHOT-d686d2
Build Number: d686d27de39190d7d515af2bbef0b4d3c6d92a6c
Build Date/Time: 02-09-2018 09:47:27 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
@sumerjabri We need to discuss this feature

**Comment by sumerjabri** [comment]
Per our conversation, please wire to the new addRemote.

**Comment by dejan-brkic** [comment]
Added as a part of resolution for ticket #1979

**Comment by alhambrav** [comment]
Verified fixed.
