### ISSUE TITLE
[studio] Write Content Studio API issue uploading file

### ISSUE THREAD

**Issue by RLChris-Lim** [craftercms/craftercms#1859]
### Expected behavior
Call to `/studio/api/1/services/api/1/content/write-content.json` using file upload in the request should be successful

### Actual behavior
The content is not being written to the crafter site properly

### Steps to reproduce the problem
* Create a site in crafter
* make a call to `write-content.json` multipart request, file upload using a REST client
	* `http://docs.craftercms.org/en/3.0/developers/projects/studio/api/content/write-content.html`
	* Option 3 File upload
	* Include file attachment ( https://gist.github.com/RLChris-Lim/2f54d8df8345e27986e6d9596fb2bf05 as an example file )

### Log/stack trace (use https://gist.github.com)
catalina log - https://gist.github.com/RLChris-Lim/6fb4201976df0fa4782ed104fa689990
JSON response - https://gist.github.com/RLChris-Lim/4e2db5b3b6b3618e122fd19faef0ddc0

#### Version
Studio Version Number: 3.0.5-SNAPSHOT-589074
Build Number: 58907486bfac1946353aad13f9f3b964571fdf93
Build Date/Time: 02-07-2018 12:47:53 -0500

#### Notes:
Using multi-part file upload seems to work in studio, but not for the API call directly

**Comment by jdrossl** [comment]
@RLChris-Lim can you please verify if the request has the file as the last item in the form? this required by the changes made to handle large files. I tested it with insomnia and it works, if that's the case I will add a note in the documentation for the API.

**Comment by RLChris-Lim** [comment]
@jdrossl the file is the last (and only) item in the form
Screenshot - https://puu.sh/zkc87/92dad344e7.png

The call I'm using is 
`http://localhost:8080/studio/api/1/services/api/1/content/write-content.json?site=mysite&path=/site/website/&phase=onSave&fileName=index.xml&contentType=/page/entry&unlock=true`

**Comment by jdrossl** [comment]
@RLChris-Lim that is also an issue, when the request is multipart all values should be part of the body, that is how Studio has been sending all uploads.
