### ISSUE TITLE
[studio] Windows - Bulk upload does not work when using MS Edge, studio returns an org.craftercms.engine.exception.ScriptException

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1866]
### Expected behavior
The selected items should be uploaded without problems

### Actual behavior
Studio does not allows to click the done button and the upload dialog stucks on the upload process
Watch the next video: https://www.useloom.com/share/f5a430b386aa4e458d9b67f9b8d6d8cb

### Steps to reproduce the problem
* Go to Studio and login as admin
* Create a site
* Go to preview and expand Sidebar
* Expand Static Assets
* Right click on static-assets and click on bulk upload assets
* Drag and drop a file to the upload dialog
* Review the studio log

### Log/stack trace (use https://gist.github.com)
Log Exception here:
https://gist.github.com/luishernandezmonge/025f29b1e4540b2a1703e3ce51965e35

#### Version
Studio Version Number: 3.0.6-SNAPSHOT-850e41
Build Number: 850e41d5373909e3f1725f01d074e8e51d6d4bc3
#### OS
Windows 10
#### Browser
MS Edge
Microsoft Edge 41.16299.15.0

**Comment by jvega190** [comment]
After several tests I found that there's a difference in IE/Edge, it sends the whole path of filename property when getting info from input of file. Recommended solution is using this
http://commons.apache.org/proper/commons-fileupload/faq.html#whole-path-from-IE
Already discussed with @jdrossl and it worked. All uploads should have this change.

**Comment by luishernandezmonge** [comment]
Verified as resolved.
