### ISSUE TITLE
[plugin-maker] Indicate required missing information when packaging plugin

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1867]
### Expected behavior
When I haven't entered all the required properties in the manifest of the plugin, an error messages should appear with the ones that are missing.

### Actual behavior
An error message is shown (Missing required information from manifest file) but not which info is missing.

### Steps to reproduce the problem
* Create a dummy plugin (`./gradlew newPlugin -PpluginName=helloworld -PpluginId=org.craftercms.plugins`)
* Package the plugin (`./gradlew packagePlugin -PpluginPath=plugins/helloworld`)

**Comment by sumerjabri** [comment]
Pending validation.
