### ISSUE TITLE
[studio] delete is never published

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1869]
### Expected behavior
When a user deletes and object in sandbox, a delete should be performed in published

### Actual behavior
Delete operation is never propagated to published

### Steps to reproduce the problem
* delete a page or component from your site
* note it is never deleted in published
 

#### Version
```Studio Version Number: 3.0.6-SNAPSHOT-82bbb0
Build Number: 82bbb05631638a2054117bd4e7622ebee5daf886
Build Date/Time: 02-12-2018 09:42:01 -0500``

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1048

**Comment by russdanner** [comment]
VERIFIED
