### ISSUE TITLE
[studio-ui] Tomcat log returns the next error: SystemId Unknown and the compare iframe is displayed behind the History dialog

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1871]
### Expected behavior
The compare frame should be displayed over the History dialog and no error should be displayed on the log

### Actual behavior
Tomcat log returns the next error: SystemId Unknown; Line #1; Column #150; A relative path pattern was expected.
Also, the compare iframe is displayed behind the History dialog
Watch the next video:
https://www.useloom.com/share/f6ebc8d883614acfba5de17e1d9b2216

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a new site using WebSite Editorial BP
* Go to preview and expand Sidebar
* Edit the home content and save the changes
* Click on home content and click on History navigation bar option
* Check a couple of versions and click on compare
* Review that the compare frame is displayed behind the history dialog
* Review the tomcat log

#### Version
Studio Version Number: 3.0.7-SNAPSHOT-f853eb
Build Number: f853ebe059d2090b451aa5fa8d71ade786532847
#### OS
Mac OSx, Windows 10
#### Browser
Google Chrome, FireFox, Edge

**Comment by dejan-brkic** [comment]
Error in tomcat log is not produced by the backend. It is result of usage of the library for comparing content.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/774

**Comment by russdanner** [comment]
VERIFIED
