### ISSUE TITLE
[studio-ui] Tooltip for "Actions" in the History dialog is behind the History dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1872]
### Expected behavior
The tooltip for "Actions" in the History dialog should be in front.

### Actual behavior
Tooltip for "Actions" in the History dialog is behind the history dialog.  When you mouse over on the icon for **View** (eye), it looks like there is no tooltip.  Mouse over on the other **Actions** icons and you can see the tooltip behind the history dialog.

### Steps to reproduce the problem
* Create a site using website_editorial.
* Edit the Home page and save.
* Click on **History** from the context nav or right click on the Home page from the **Sidebar** and select **History**
* Mouse over on the icons under **Actions**, notice that the tooltip is behind the history dialog.

![screen shot 2018-02-15 at 9 59 15 am](https://user-images.githubusercontent.com/25483966/36263319-faa6ec66-1237-11e8-8b4f-43e83a6c7de9.png)

#### Version
Studio Version Number: 3.0.8-SNAPSHOT-46d0fa
Build Number: 46d0faa53a2ae70f27cf5fa154d2e98c7121adfc
Build Date/Time: 02-15-2018 09:27:46 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
It was fixed on: https://github.com/craftercms/craftercms/issues/1798
