### ISSUE TITLE
[studio] Please fix warning messages for AwsProfileManagerImpl when building Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1875]
### Expected behavior
It would be nice to have no warning messages when building studio

### Actual behavior
There are a couple of warning messages for AwsProfileManagerImpl when building studio

### Steps to reproduce the problem
* Build Studio  

### Log/stack trace (use https://gist.github.com)
```
[WARNING] /Users/vita/temp/test5/craftercms/src/studio/src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsProfileManagerImpl.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/vita/temp/test5/craftercms/src/studio/src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsProfileManagerImpl.java: Recompile with -Xlint:unchecked for details.
```
#### Version
Studio Version Number: 3.0.8-SNAPSHOT-46d0fa
Build Number: 46d0faa53a2ae70f27cf5fa154d2e98c7121adfc
Build Date/Time: 02-15-2018 09:27:46 -0500

#### OS
OS X

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1057

**Comment by alhambrav** [comment]
Verified fixed.
