### ISSUE TITLE
CRAFTERCMS-2124: edit and other nav menu controls remain disabled after publish in preview

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#188]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2124
----------

**Comment by vestrada** [comment]
Closed
