### ISSUE TITLE
[craftercms] crafter.bat fails if there is a space in the path

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1881]
### Expected behavior
crafter.bat should run without issues if there is a space in the bundle path

### Actual behavior
crafter.bat script fails with an error

### Steps to reproduce the problem
*  Create a folder with a space in the name
*  Unzip the Crafter bundle in that folder
*  Try to run `startup.bat`

#### OS
Windows (any)

**Comment by sumerjabri** [comment]
This overlaps with: https://github.com/craftercms/craftercms/issues/2062

**Comment by jdrossl** [comment]
Opened an issue for Solr https://issues.apache.org/jira/browse/SOLR-12351

**Comment by jdrossl** [comment]
The issue for MariaDB4j seems to be related with the library used for running the commands that is part custom and part Apache Commons Exec. I tried to update the code to change the quote handling provided by the lib without any luck

**Comment by sumerjabri** [comment]
Docker.
