### ISSUE TITLE
[craftercms] Init-site.bat script cannot find repository path

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1882]
### Expected behavior
Running `init-site.bat mysite` should be able to get the repository path and run on a fresh install.  Also, it would be nice to fix the typo in the error message: `does not exist or cannot to read` to something like `does not exist or cannot read`

### Actual behavior
Running `init-site.bat mysite` gives you the following error:
```
Repository path \myawesomesite\published for site \"myawesomesite\" does not exist or cannot to read
```
Running it again then gives you the following error:
```
Repository path crafter-authoring\data\repos\sites\myawesomesite\published for site \"myawesomesite\" does not exist or cannot to read
```

### Steps to reproduce the problem
* Do a fresh install of craftercms in Windows OS.
* Create a site(`myawesomesite`).  Make sure delivery is running.
* Run the init-site.bat program using the site you created in the previous step. Notice the error message (`init-site.bat myawesomesite`)
* Run the init-site.bat program again and notice the error message....

Eventually, the script will work, I'm not sure when.  Looking at the error messages, I am not sure if this has anything to do with the batch file variables being expanded at parse or something else causing some of the variables to be empty?

#### Version
Studio Version Number: 3.0.8-SNAPSHOT-46d0fa
Build Number: 46d0faa53a2ae70f27cf5fa154d2e98c7121adfc
Build Date/Time: 02-15-2018 09:27:46 -0500
#### OS
Windows OS
#### Browser
Chrome browser

**Comment by cortiz** [comment]
Solve in 
https://github.com/craftercms/craftercms/pull/1890/

**Comment by alhambrav** [comment]
Verified fixed.
