### ISSUE TITLE
[docs] Revise and update the reindexing document

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1886]
Please revise and update the reinexing documentation to ensure it's still correct and works as described: http://docs.craftercms.org/en/3.0/system-administrators/reindexing-content.html

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/470

**Comment by sumerjabri** [comment]
@avasquez614 please update and assign back to me.

**Comment by avasquez614** [comment]
I made the changes, just waiting for @alhambrav to approve them.
