### ISSUE TITLE
[docs] Update/expand on the article "Reindexing Content Without Disrupting Service in Production"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1891]
Update/expand on the article "Reindexing Content Without Disrupting Service in Production".
The current article contains steps that are very general, such as the first step listed:
```
-------------------------------
Step 1: Prepare a re-index core
-------------------------------

The first step is to prepare an additional empty core on Solr where you can index the content.
```

It would be nice if the step can be expanded, by adding a little bit more description on how to do the step or point to somewhere where the user can figure out the steps that needs to be done.

(The article has been removed from the docs for now, but can be edited under:
`system-administrators/activities/reindexing-content-in-prod.rst`, PR https://github.com/craftercms/docs/pull/470)

**Comment by avasquez614** [comment]
Duplicate of craftercms/craftercms#1886

**Comment by avasquez614** [comment]
PR craftercms/docs#498

**Comment by alhambrav** [comment]
Verified.
