### ISSUE TITLE
[studio] reverting content on a live item does not change the state to in-progress

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1893]
### Expected behavior
when a user reverts an item that's published it should move to an in-progress state

### Actual behavior
https://www.useloom.com/share/7b13f1bf975a47c4afa67d0cc62327e8

### Steps to reproduce the problem
* put an item in published state
* open history, revert item to the previous state
* note item is in live state after revert

#### Version
2.5

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1053

**Comment by russdanner** [comment]
Confirmed

**Comment by russdanner** [comment]
This bug also exists in 3.0.19
https://www.useloom.com/share/8ca23a37dddb4fc8bb79b78982c71593

**Comment by dejan-brkic** [comment]
Done
3.1:
https://github.com/craftercms/studio/pull/1386

3.0:
https://github.com/craftercms/studio/pull/1387

**Comment by russdanner** [comment]
Confirmed
