### ISSUE TITLE
[test-suite] Automate copy/paste of large trees

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1894]
Please automate ID 1 in **Studio - Content** - Copy/paste large trees
Steps:
Setup before beginning the test:
* Site using Editorial BP,  setup the site for delivery

Create the large tree:
* Copy articles/2017 and paste it under article/2016
* Paste again under the newly pasted folder
* Paste again under the next newly pasted folder
* Keep pasting on the next newly pasted folder until you've done it at least 10 times.  Below is an example of how your site tree will look like:

![screen shot 2018-02-27 at 10 18 26 am](https://user-images.githubusercontent.com/25483966/36739751-b888e908-1bae-11e8-9c3a-69de30f7ba15.png)

Steps:
Copy and paste then publish:
1) Copy the articles/2016 folder
2) Paste it under articles/2017
3) Publish (To publish from UI, you can go to Site Config, click on Publishing, then click on the "Bulk Publish" tab.  For the path, enter `/site/website/articles` to publish the large tree we copied and pasted)

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
Added to the testng.xml suite file, already automated.

**Comment by alhambrav** [comment]
Verified.
