### ISSUE TITLE
[test-suite] Automate copy/paste of content with specific and shared components

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1896]
Please automate ID 3 in **Studio - Content** - Copy/paste content with specific and shared components

**Setup**
* Site using Editorial BP
Create content with specific components:
* Create a new article page under folder article/2017/3, make sure to upload an image from your desktop, then save your changes

Create the large tree:
* Copy articles/2017 and paste it under article/2016
* Paste again under the newly pasted folder
* Paste again under the next newly pasted folder
* Keep pasting on the next newly pasted folder until you've done it at least 10 times

**Steps:**
Copy and paste then publish: 
1) Copy the articles/2016 folder 
2) Paste it under articles/2017 
3) Publish (To publish from UI, you can go to Site Config, click on Publishing, then click on the "Bulk Publish" tab. For the path, enter /site/website/articles to publish the large tree we copied and pasted)

**Expected Output**
1) Check there are no errors when doing the copy 
2) Check there are no errors when pasting, verify from the Sidebar site tree is as expected.  Verify that ten copies of the uploaded image in the new article created are in the static-assets/page/images (There should be a total of 20 copies of the uploaded image, ten from when the tree was created, and another ten after pasting) 
3) Go to the delivery site and check that pasted content is accessible. Here's an example URL of one of the newly copied and pasted article: ""http://localhost:9080/articles/2017/2016/2017/2017/2017/2017/2017/2017/2017/2017/1/men-styles-for-winter""."

**Comment by luishernandezmonge** [comment]
@alhambrav Please,  can you provide more details on this about the steps, preconditions, expected results and postconditions for this ticket related to test case?

**Comment by alhambrav** [comment]
@luishernandezmonge Done. Please see the update above.

**Comment by luishernandezmonge** [comment]
Starting working on this.

**Comment by luishernandezmonge** [comment]
Added to testing.xml suite in the next PR: https://github.com/craftercms/test-suite/pull/316

**Comment by alhambrav** [comment]
@luishernandezmonge For the expected output number 2, 
```
Verify that ten copies of the uploaded image in the new article created are in the static-assets/page/images (There should be a total of 20 copies of the uploaded image, ten from when the tree was created, and another ten after pasting)
```
please check the number of image files (say, check the number of testimage.jpg), not just the number of items found in the `static-assets/page/images` tree, just in case our blueprint is changed and default images are under `static-assets/page/images`.

To test it, modify the blueprint by adding the following file like so: 
`page/images/anotherimagefortest.jpg` under
`craftercms/src/studio/src/main/webapp/repo-bootstrap/global/blueprints/website_editorial/static-assets`
Build and deploy Studio and run the test again.  With the existing test-case code, the test will fail because it will find 22 items instead of 21 items.

**Comment by luishernandezmonge** [comment]
@alhambrav added changes of above to the PR: https://github.com/craftercms/test-suite/pull/318.
Please, check when it is done. Thanks.

**Comment by alhambrav** [comment]
Verified.
