### ISSUE TITLE
[studio-ui] Save as draft unlocks content

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1897]
### Expected behavior
Save as draft should maintain lock

### Actual behavior
Save as draft unlocks content
https://www.useloom.com/share/50151985886e42db8291a20ffce0bb1d

### Steps to reproduce the problem
* open a content item
* save as draft
* note item is unlocked but should not be

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-6f88a6
Build Number: 6f88a63c4bf53e1c6619933295225abbcd1f96e9
Build Date/Time: 02-21-2018 11:57:44 -0500

**Comment by sumerjabri** [comment]
Confirmed with Russ that it's not a bug.
