### ISSUE TITLE
[studio-ui] Pasting a large tree takes a while without an indication what is happening

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1902]
### Expected behavior
It would be nice to have a spinner or something when pasting a large tree until it appears in your sidebar tree. (Some indication that Studio is doing something)

### Actual behavior
Pasting a large tree takes a while without an indication what is happening, then suddenly your sidebar tree is updated with the new items you pasted. (The user might think the paste did not work or something...

### Steps to reproduce the problem
* Using the website_editorial bp, copy the `2017` folder and paste it into the `2016` folder
* Do a paste again under the new pasted folder
* Do this at least ten times to create a large tree
![screen shot 2018-02-26 at 2 41 10 pm](https://user-images.githubusercontent.com/25483966/36691580-c3105e34-1b03-11e8-9e60-a685cdbfd435.png)
* Copy the `2016` folder under `articles`
* Create a new folder under `articles` (in the clip that follows, I created a folder named `copies` under `articles`) and paste the `2016` folder you just copied.  Notice that it looks like it is doing nothing after clicking on `Paste`, and then the folder you pasted will appear in the **Sidebar** tree after a few moments.  It would be nice if there's an indication that Studio is doing something, like a spinner or something else

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing when the large tree is copied, then pasted, and then a little while after, the sidebar tree is updated with the pasted content.
https://www.useloom.com/share/2fe7bb079f014c8f8ed9d32a4a9f796e

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-f9d28a
Build Number: f9d28a92ef77166120a5d1a319be5bab1bcad757
Build Date/Time: 02-26-2018 10:54:26 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
Please add a spinner.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/783

**Comment by alhambrav** [comment]
Verified fixed.  
There's a spinner next to the folder where you're pasting.
