### ISSUE TITLE
[studio-ui] Disable the `Publish` button in the Bulk Publishing screen while bulk publishing is being performed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1903]
### Expected behavior
In the `Bulk Publishing` screen, the `Publish` button should be disabled after clicking on the button until the bulk publishing is done.

### Actual behavior
In the `Bulk Publishing` screen, the `Publish` button is still clickable after clicking on the button until the bulk publishing is done.  Notice in the clip provided, I am able to click on the button while bulk publishing is still being performed.

### Steps to reproduce the problem
* Using website_editorial bp, create a large tree like in https://github.com/craftercms/craftercms/issues/1902
* Go to **Site Config** , click on **Publishing** then click on the **Bulk Publish** tab
* Enter the path to publish, then click on the `Publish` button.  Click on the `Publish` button.  Click on the `Publish` button again.  It would be nice if the user is not allowed to click the `Publish` button while bulk publishing is being performed.

### Log/stack trace (use https://gist.github.com)
https://www.useloom.com/share/4fb4af838abe40ef8e59c32f9d97fb71

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-f9d28a
Build Number: f9d28a92ef77166120a5d1a319be5bab1bcad757
Build Date/Time: 02-26-2018 10:54:26 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/780

**Comment by alhambrav** [comment]
Nice that the publish button has been disabled.
Please add a spinner after saying yes to the bulk publish warning and before the notification that bulk publish precess has been started (around 0:40 seconds in the clip below). 

After the **Publish** button is disabled, Studio is doing something but user does not know what, until the notification pops up.  So, a spinner after saying yes to the bulk publish warning and before the notification that bulk publish process has been started would be nice.

Here's a short clip:
https://www.useloom.com/share/67a8a8ca53b24b539c8e231a54713f62

**Comment by jvega190** [comment]
Spinner added! https://github.com/craftercms/studio-ui/pull/782

**Comment by alhambrav** [comment]
Verified fixed.
