### ISSUE TITLE
[engine] Profile ticket timeout results in error 500 instead of login page

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1904]
### Expected behavior
When the Crafter Profile ticket expires the user should be redirected to the login page again.

### Actual behavior
Crafter Engine is rendering the 500.ftl template with the exception: `org.craftercms.security.exception.AuthenticationSystemException: No profile found for ticket 'abc'`

### Steps to reproduce the problem
* Login to a site using crafter profile
* Wait for the ticket to expire
* Reload the page

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/jdrossl/a04aee71a69eedb0990b7128fc11ff08

#### Version
3.0.7-5c21b6

#### OS
MacOS 10.13.3

#### Browser
Chrome 64.0.3282.167

**Comment by sumerjabri** [comment]
@avasquez614 please validate and close.

**Comment by sumerjabri** [comment]
Validated
