### ISSUE TITLE
[craftercms] Failed to delete site on windows the java.io.IOException is returned on the tomcat log and crafter leaves published folder behind 

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1905]
### Expected behavior
The site data folders should be deleted completely and the users should be able to use the same site name for other sites in the future.

### Actual behavior
The delete site action returns the next error in the log:
Failed to delete site: siteGetUserPerSiteAPITest at path: ..\data\repos\sites\siteGetUserPerSiteAPITest exception java.io.IOException: Unable to delete file: ..\data\repos\sites\siteGetUserPerSiteAPITest\published\.git\objects\pack\pack-1f180ba7ae17a9810d3f5a54045a72f9a2216d03.pack 

Also, when the user tries to create a new site using the old name (just deleted), studio returns an error when create the site. It is because the crafter leaves published folder behind after delete site.

Watch the next video:
https://www.useloom.com/share/50128a4a429947939774e37cd576e284

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site
* Go to sites page and delete the site of above
* Review the studio log on crafter-authoring/logs/tomcat
* Try to create a new site using the same name used on site of above
* Notice that studio returns an error on a notification dialog.
* Review the studio log on crafter-authoring/logs/tomcat

### Log/stack trace (use https://gist.github.com)
Log Error:
https://gist.github.com/luishernandezmonge/61580e0902aad0f9846c8a3335b29729

Studio notification error when create a new site using old site name:
![notification](https://user-images.githubusercontent.com/16946208/36698854-9c4ca3b8-1b10-11e8-841d-ce5ae213fc4b.JPG)

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-f9d28a
Build Number: f9d28a92ef77166120a5d1a319be5bab1bcad757
Build Date/Time: 02-26-2018 10:26:48 -0800
#### OS
Windows 10
#### Browser
Chrome, Edge

**Comment by dejan-brkic** [comment]
@sumerjabri we had this issue reported before, a regular user (not tests). Windows does not release file handles so we can not clean up properly on delete site.

**Comment by luishernandezmonge** [comment]
Verified as resolved.
