### ISSUE TITLE
[studio-ui] Please add pagination in dashboard widgets

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1906]
### Expected behavior
In the dashboard widgets, pagination would be nice so if there's more data to be displayed, the user can access it. (Say, I published 25 pages, if I look in the dashboard widget **Recently Published**,  I have it set to **Show** `10`, it would be nice to have a way to view the 11th to 25th recently published items.

### Actual behavior
There's no pagination support in the dashboard widgets

### Steps to reproduce the problem
* Using website_editorial, edit at least 6 pages
* Go to the dashboard and scroll to the **Recently Published** widget
* In the **Show** field, enter `5`, notice that there is no way to view the next items as pagination is not supported

<img width="1001" alt="screen shot 2018-02-27 at 11 57 21 am" src="https://user-images.githubusercontent.com/25483966/36742592-12d93e42-1bb6-11e8-9838-ddad22125c9b.png">

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-6cc192
Build Number: 6cc1929d82361033a1bf5f843462b5db5e4b4eb2
Build Date/Time: 02-27-2018 09:36:57 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
Part of dashboard refactoring.

**Comment by sumerjabri** [comment]
Completed in new Dashboard.
