### ISSUE TITLE
[studio] Make `sandbox` branch configurable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1907]
Please make the sandbox branch configurable (right now it's set to `master`).

This means a yaml config, and change of the publishing process to be able to publish from non-master.

This will help us create many studios for different envs running on `develop` as opposed to `master` which will help with DevOps workflow.

Ping me if you need to discuss.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/1909
https://github.com/craftercms/studio/pull/1059
