### ISSUE TITLE
[studio-ui] "undefined" text in My Recent Activity widget in dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1908]
### Expected behavior
There should be no "undefined" text in the **My Recent Activity** widget 

### Actual behavior
"undefined" in **My Recent Activity** widget in dashboard appears when a new item is created

### Steps to reproduce the problem
* Using website_editorial bp, open the **Sidebar**
* Click on the Dashboard
* Right click on any of the folders under **articles** and select **New Content** in the **Sidebar** (ex. `articles/2017/2` folder)
* Fill out the required fields then save and close the form.  Notice in the **My Recent Activity** widget that thee's a text **undefined** underneath the widget title

It looks like every time you create new content under one of the folders in **articles**, another `undefined` text is added right underneath the widget title.
Copying and pasting also appends another `undefined` text underneath the widget title.
Creating a new folder also appends another `undefined` text underneath the widget title.

![screen shot 2018-02-27 at 2 16 37 pm](https://user-images.githubusercontent.com/25483966/36749496-efad32a8-1bc8-11e8-9f1c-00dfadba2d1b.png)

Please see the short clip below showing the `undefined` text.

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/5e7dd52a98a94ca1bccdbb1262377bc2

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-6cc192
Build Number: 6cc1929d82361033a1bf5f843462b5db5e4b4eb2
Build Date/Time: 02-27-2018 09:36:57 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@alhambrav did you be any chance have two versions running? Please try to reproduce with a fresh incognito browser session.

**Comment by alhambrav** [comment]
@sumerjabri 
I can reproduce it with a fresh incognito browser session (I closed all my other browsers with Studio running and opened a new incognito browser window).  I just had to make sure that it's displaying **All** instead of just **Pages** or **Components** or **Documents**

![screen shot 2018-02-27 at 4 16 26 pm](https://user-images.githubusercontent.com/25483966/36755310-d01cd4c8-1bd9-11e8-86f1-11ac92a1db34.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/784

**Comment by alhambrav** [comment]
Verified fixed.
