### ISSUE TITLE
[studio] When duplicating content, items inside content are not duplicated

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1910]
### Expected behavior
When duplicating content, items inside content should be duplicated

### Actual behavior
When duplicating content, item inside content are not duplicated

### Steps to reproduce the problem
* Using website_editorial bp, edit one of the articles.
* Replace the image with an uploaded image and save.  Below is the new image uploaded:
![screen shot 2018-03-01 at 10 09 36 am](https://user-images.githubusercontent.com/25483966/36852060-d6bbdcec-1d38-11e8-80ea-e78bcf1c5f79.png)

* From the **Sidebar**, right click on the edited article and select **Duplicate**.  This will open the form for your duplicate article for editing
* Notice the duplicate article page url has been appended some characters **a5b55f81**  
![screen shot 2018-03-01 at 9 54 31 am](https://user-images.githubusercontent.com/25483966/36851512-60a28ef8-1d37-11e8-9a31-dcc7697af5c6.png)
* Scroll down to the image section, notice that the image in the duplicate article is pointing to the image from the original article instead of its own copy of the image
![screen shot 2018-03-01 at 9 54 42 am](https://user-images.githubusercontent.com/25483966/36851631-a46dfe60-1d37-11e8-9d44-a435c0197502.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing an edited article being duplicated.  The edit in the article was to replace the existing image with an uploaded image:
https://www.useloom.com/share/1e1fc6eb64204a688b8069d1994ed79e

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-a3c9b8
Build Number: a3c9b8dbe868df649bfca2800801a5082ac0f829
Build Date/Time: 03-01-2018 09:28:47 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by alhambrav** [comment]
Update: I modified the content type so the path where the image uploads to is : `/static-assets/page/images/{objectId}/`
(The `studio-config.yaml` file Regex pattern for item specific dependencies is left as the default values: `studio.configuration.dependency.itemSpecificPatterns: /site/components/page/.*,/static-assets/page/.*`)

I created a new article and uploaded an image, then did a duplicate of the new article:
The image is still not duplicated in the duplicated article and still pointing to the original one.

![screen shot 2018-03-05 at 11 45 25 am](https://user-images.githubusercontent.com/25483966/36988070-d7c5d31e-206b-11e8-8ecb-8f5bdbebaa3c.png)

![screen shot 2018-03-05 at 11 47 43 am](https://user-images.githubusercontent.com/25483966/36988074-dcfbd496-206b-11e8-9945-79c4eff2e2b4.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1060

**Comment by alhambrav** [comment]
Verified fixed.
