### ISSUE TITLE
[studio-ui] Content-type config.xml file does not let you save <copy-dependencies>

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1911]
### Expected behavior
Changes made in Content-type config.xml file should be saved when the Update button is pressed (Adding <copy-dependencies>) .

### Actual behavior
Content-type config.xml file does not save changes made

### Steps to reproduce the problem
* Create a site using website_editorial or empty bp
* Open the **Sidebar** and click on **Site Config**
* Click on **Content Types** and then click on **Open Existing Type**
* Select one of the content types, for the example below, the empty bp is used and the **Entry** content type was clicked.
* Add the following to the **Configuration** "config.xml"
```
<copy-dependencies> 
    <copy-dependency> 
        <pattern>(^/static-assets/images/page/.*)</pattern> 
        <target>/static-assets/images/page</target> 
    </copy-dependency> 
</copy-dependencies>
``` 
* Click on **Update**, then after it goes back to the content type dialog, click on **Save**
* Now, go back to the Properties Explorer panel, **Configuration** property and click on the pencil icon next to config.xml again to view the file. Notice that the changes you saved earlier is gone.

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/0443a64408e44170a7ec4657a688609d

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-a3c9b8
Build Number: a3c9b8dbe868df649bfca2800801a5082ac0f829
Build Date/Time: 03-01-2018 09:28:47 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
This is UI issue. UI is sending XML configuration without previously updated content

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/786

**Comment by alhambrav** [comment]
Verified fixed.
