### ISSUE TITLE
[studio-ui] My Recent Activity widget does not display the same number as indicated on the widget title

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1914]
### Expected behavior
The number listed next to the **My Recent Activity** widget should be the same as the number of items displayed in the widget

### Actual behavior
**My Recent Activity** widget does not display the same number as indicated on the widget title

### Steps to reproduce the problem
* Create a site using website_editorial
* Click on the dashboard, and notice the number displayed next to the **My Recent Activity** widget
<img width="813" alt="screen shot 2018-03-02 at 12 36 58 pm" src="https://user-images.githubusercontent.com/25483966/36913063-af62d9be-1e16-11e8-978f-82e491ace80c.png">

* From the **Sidebar**, right click on one of the article folders and select **New Content**.  Fill in the required fields and upload an image from your desktop.  Save it.
* Look at your dashboard **My Recent Activity** widget.  Notice the number displayed next to the widget title(5) and the number of items displayed in the widget itself(only 2 items listed) does not match.

<img width="808" alt="screen shot 2018-03-02 at 10 27 43 am" src="https://user-images.githubusercontent.com/25483966/36911760-8b6efd7a-1e12-11e8-9007-c025ba738230.png">

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-a3c9b8
Build Number: a3c9b8dbe868df649bfca2800801a5082ac0f829
Build Date/Time: 03-02-2018 08:49:11 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/785

**Comment by alhambrav** [comment]
Verified fixed.
