### ISSUE TITLE
[studio] Cut and Paste operation returns the org.springframework.dao.DuplicateKeyException when try to cut articles/2016 folder (with a 2017 child) and paste into 2017 folder, and after that studio hangs on the bulk publish requests (on Windows)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1915]
### Expected behavior
Craftercms should not have problems with cut&paste process for same name folders because it should have different ids, and the bulk publish should not broke after that.

### Actual behavior
After the cut&paste step craftercms returns the exception of the log file:
_[ERROR] 2018-03-02 11:49:34,847 [http-nio-8080-exec-4] [clipboard.ClipboardServiceImpl] | Paste operation failed for item {0} to dest path `{1}, isCut: {2} org.springframework.dao.DuplicateKeyException:_

**Critical**
And when the user tries to perform the bulk publish for the path on articles, crafter hangs totally even for the other sites.

Watch the next video: https://www.useloom.com/share/2fdb9ba817b74caeba1cd25b85c8dc93
### Steps to reproduce the problem
* Go to studio and create a site using WebSite BP
* Expand **Articles** folder on **Pages/Home**
* Copy **Articles/2017** folder
* Paste folder of above into **Articles/2016** folder
* Cut **Articles/2016** folder and paste it into the **Articles/2017** folder
* Review the studio log (the error is displayed on this but the end user does not notice it)
* Go to **Site Config** 
* And try to perform a bulk publish for the path **/site/website/articles**
* Click on publish
* On the **Warning: Bulk Publish** dialog click on Yes.
* Notice that the application hangs there
* Refresh and try to create a new site
* Go to new site and perform a little change on any page
* Try to perform a bulk publish for the new site on the path /
* Notice that the application hangs there again

### Log/stack trace (use https://gist.github.com)
Studio log from Windows:
https://gist.github.com/luishernandezmonge/60d3fdd9b895622773aca9ac5ae999bd

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-a3c9b8
Build Number: a3c9b8dbe868df649bfca2800801a5082ac0f829
Build Date/Time: 03-02-2018 07:26:46 -0800
#### OS
Windows
#### Browser
Chrome, Edge

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1061

**Comment by luishernandezmonge** [comment]
Verified as resolved
