### ISSUE TITLE
[docs] Fix setup site for delivery

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1916]
http://docs.craftercms.org/en/3.0/system-administrators/activities/setup-site-for-delivery.html

* `[site's published repo git url] is the site’s published repository git url. (optional)` should say [site's published repo git url] is Git URL to the published repository of the Studio server/installation (e.g. /opt/crafter/authoring/data/repos/sites/mysite/published) (optional).
* Should be explained that when using an SSH URL,  it's recommended to either use username/password authentication or public/private key authentication.
* Section:
```
Here is a sample git url using ssh:

ssh://[user@]host.xz[:port]/path/to/repo/
or alternatively for ssh:

[user@]host.xz:path/to/repo/
```
Should instead say:
```
The SSH Git URL format is: ssh://[user@]host.xz[:port]/path/to/repo/ (sections between [] are optional)

Example #1: ssh://server1.example.com/path/to/repo
Example #2: ssh://jdoe@server2.example.com:63022/path/to/repo
```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/481

**Comment by avasquez614** [comment]
Verified
