### ISSUE TITLE
[craftercms] Failed to delete the database for site org.craftercms.studio.api.v1.exception.SiteNotFoundException is returned when user tries to delete a site on Mac/Linux

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1919]
### Expected behavior
The site should be deleted without database exceptions and after that there should not be problems using the same siteid for other sites.

### Actual behavior
The next exception is displayed on the tomcat log:
_[ERROR] 2018-03-05 10:33:22,944 [http-nio-8080-exec-10] [site.SiteServiceImpl] | Failed to delete the database for site:mjo
org.craftercms.studio.api.v1.exception.SiteNotFoundException
	at org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.deleteSiteDependencies(DependencyServiceImpl.java:423)_

Also, after that the user can't use the same siteid for other new sites.
Watch the next video:
https://www.useloom.com/share/4e00ed0fe3cc432586741192b4940995

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site using any BP. (take note of the sited provided)
* Wait for couple of secs and delete the site.
* Review the tomcat log, notice that there is an error.
* Go to studio and try to create a site using the same name of above.

### Log/stack trace (use https://gist.github.com)
Log error:
https://gist.github.com/luishernandezmonge/0abfd671f4f4fc7ce37c562461dce9e0

On create site error (last step)
<img width="651" alt="screen shot 2018-03-05 at 10 44 51 am" src="https://user-images.githubusercontent.com/16946208/36987564-421910dc-2062-11e8-9fbd-0924a720d4a8.png">
#### Version
Studio Version Number: 3.0.9-SNAPSHOT-337374
Build Number: 337374565729d5f22248714a061054b5ba4adc0f
Build Date/Time: 03-05-2018 08:32:45 -0600
#### OS
Mac OSx and Linux Ubuntu
#### Browser
Chrome

**Comment by luishernandezmonge** [comment]
However, if you check on the folder crafter-authoring/data/repos/sites the site folder is removed from that folder.

**Comment by luishernandezmonge** [comment]
Find here the exception returned on the last step when try to create other site with same name:
https://gist.github.com/luishernandezmonge/b736a85353cd9cf218f002b755422aa6

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1062

**Comment by luishernandezmonge** [comment]
Verified as resolved.
