### ISSUE TITLE
[studio-ui] "My Recent Activity" widget in dashboard does not seem to be working right

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1920]
### Expected behavior
The number of items listed in the **My Recent Activity** widget should be growing up to the number indicated in the **Show** field as things are edited/added/deleted in the site.  Also, depending on the number of recent activities and the number in the **Show** field in the dashboard, the number of items displayed should adjust accordingly.

### Actual behavior
**My Recent Activity** widget in dashboard does not seem to be working right.  Instead of the list growing up to the number indicated in **Show** field as things are edited/added/deleted, the number of items displayed becomes less.  Also, when changing the number in the **Show** field, the number of items displayed does not seem to correspond to the number in the **Show** field.

### Steps to reproduce the problem
* Create a site using website_editorial bp
* Open the dashboard, take note of the number of items in the **My Recent Activity** widget (In my example image, I edited the content type **Page - Article** so there's 2 items listed in the **My Recent Activity** widget)
![screen shot 2018-03-05 at 2 49 06 pm](https://user-images.githubusercontent.com/25483966/36996477-f38274fe-2084-11e8-8e44-fe8d633da940.png)

* Edit one of the articles (In the image, **Top books for young women** is edited.  Notice the items displayed in the **My Recent Activity** widget (The number in the widget seems to be correct)
![screen shot 2018-03-05 at 2 55 23 pm](https://user-images.githubusercontent.com/25483966/36996672-6221b0c8-2085-11e8-97b2-3d9118ee33cb.png)

* Create a new folder **1** under **articles/2016**.  Notice the number of items listed in the widget. (No change to the number of items in the widget...)
![screen shot 2018-03-05 at 2 58 11 pm](https://user-images.githubusercontent.com/25483966/36996784-a97c3a6a-2085-11e8-9bc1-baf7258f8677.png)

* Create new content under the newly created folder and upload an image from desktop.  Notice the number of items listed in the widget (The number of items in the widget increases which sounds right...)

![screen shot 2018-03-05 at 3 00 38 pm](https://user-images.githubusercontent.com/25483966/36996960-21c996ac-2086-11e8-80e8-3acbda85d1e7.png)
* Create another folder **2** under **articles/2016** and again notice the number of items listed in the widget after adding the new folder (the number is now less...)
![screen shot 2018-03-05 at 3 02 56 pm](https://user-images.githubusercontent.com/25483966/36997033-5a375a60-2086-11e8-9713-9f6e3e77d648.png)

* Copy the folder **articles/2017** then paste it under the folder **articles/2016** and again notice the number of items listed in the widget after performing the copy/paste (The number stays the same... should it be growing?)
![screen shot 2018-03-05 at 3 05 07 pm](https://user-images.githubusercontent.com/25483966/36997122-9f73d108-2086-11e8-86e0-de790e2b33c7.png)

* Change the number in the **Show** field to **4** and notice again the number of items displayed in the **My Recent Activity** widget (Expecting 4 items listed in the widget and only 1 item is displayed...)
![screen shot 2018-03-05 at 3 06 15 pm](https://user-images.githubusercontent.com/25483966/36997174-c7d426c0-2086-11e8-830a-3de7a0add331.png)

* Change the number in the **Show** field to **10** (we should have enough activities for at least 10) and notice again the number of items displayed in the widget (It should display 10 items, but here it's only displaying 4...)
![screen shot 2018-03-05 at 3 11 17 pm](https://user-images.githubusercontent.com/25483966/36997406-87d248d0-2087-11e8-9c3f-d519d9ea6a50.png)

 

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/6f1c767467af41a4bc3d8f0423d1ab93

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-337374
Build Number: 337374565729d5f22248714a061054b5ba4adc0f
Build Date/Time: 03-05-2018 14:03:27 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
The problem is that the service is returning folders, and is not supposed to, folders are omitted and not shown in widget. So the service returns for example, 6 folders, and only 4 elements of other content types (those are the ones shown).
 
<img width="754" alt="screen shot 2018-03-06 at 10 02 47 am" src="https://user-images.githubusercontent.com/18267471/37043396-2385f3be-2126-11e8-8e5e-4ef564d4d945.png">

**Comment by jvega190** [comment]
The same problem described before is happening (folders returning from the service). How should we proceed with this?

**Comment by sumerjabri** [comment]
@jvega190 How about showing the folders but disabling the selector and actions. So you can't select a folder nor interact with it. Also, if you select all/select none it still has to select everything except folders and work as expected. What do you think?

**Comment by jvega190** [comment]
@alhambrav worked as described in previous comment, please let me know if you need something

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/810

**Comment by alhambrav** [comment]
Verified fixed.
