### ISSUE TITLE
[studio] BoxException: Unable to read box configuration file

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1923]
### Expected behavior
Uploading a file to box using the API should work (Response: Status 200 OK)

### Actual behavior
Uploading a file to box using the API gives me: HTTP 500 Internal Server Error:
{"hasError":true,"errors":["Upload of file failed: Unable to read box configuration file"]}

### Steps to reproduce the problem
* Using the website_editorial bp, create a site
* Configure the Box profile from **Site Config** -> **Configuration** -> **Box Profiles** (using either \<privateKey\> or \<privateKeyPath\> gives the same error)
* Send an api request to upload, notice the response (I am using ARC client to send the request) 
![screen shot 2018-03-06 at 11 30 21 am](https://user-images.githubusercontent.com/25483966/37044580-d8b1be98-2131-11e8-88a9-55ac0c014fd0.png)

Look at your tomcat log and notice the error message:
```
 [ERROR] 2018-03-06 11:17:17,821 [http-nio-8080-exec-10] [impl.GroovyScript] | Upload of file 708213662.mp4 failed
org.craftercms.studio.api.v1.exception.BoxException: Unable to read box configuration file
```

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/836dfe4b169a4a08d07f354419a42766

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-90de69
Build Number: 90de6980ef239739bb6d2b6151601a1b35c10272
Build Date/Time: 03-06-2018 11:11:09 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by cortiz** [comment]
@alhambrav  We remove this service since we don't use anymore (we use the box widget for uploading)

**Comment by alhambrav** [comment]
Ok.  Closing the ticket since we now use the box widget for uploading files.
