### ISSUE TITLE
[studio] Creating a site based on a remote git repo doesn't show items as published

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1924]
### Expected behavior
When creating a site based on a remote git repo, it should automatically publish and show items as live.

### Actual behavior
When creating a site based on a remote git repo, items appear as new/edited and essentially unpublished.

### Steps to reproduce the problem
* Create a site based on a remote git repo (ping me for an example URL)
* Open the Sidebar and see item states

### Log/stack trace (use https://gist.github.com)
N/A (logs clean)

#### Version
Studio Version Number: 3.0.9-SNAPSHOT-386575
Build Number: 38657585afff32902a9941308922e123d9466e7f
Build Date/Time: 03-06-2018 15:04:00 -0500

#### OS
Linux, Ubuntu 16.04

#### Browser
Chromium

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1066
