### ISSUE TITLE
[studio-ui] Content type displayed on mouse over in dashboard for config files is "Unknown"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1928]
### Expected behavior
It would be nice to display the content type of configuration files as "configuration" and content type files as "content type" (like what is in the audit table for content type) in the dashboard when hovering the mouse over on an item in the "My Recent Activity" widget.
 
### Actual behavior
Content type displayed on mouse over in dashboard for config files is "Unknown" for both configuration files and content type files.

### Steps to reproduce the problem
* Create a site using either empty or editorial bp
* Edit an existing content type by clicking on **Site Config** -> **Content Types** -> **Open Existing Type** then select a content type template name and modify and save it.
* Go to the dashboard and scroll down to the "My Recent Activity" widget
* Mouse over on the item **config.xml** or **form-definition.xml**, notice that the content type listed in the tooltip is **Unknown**

<img width="887" alt="screen shot 2018-03-07 at 2 39 27 pm" src="https://user-images.githubusercontent.com/25483966/37114138-7b61cd34-2215-11e8-8a55-5b4d97596a07.png">

The same behavior is observed when modifying one of the configuration files (Click on **Site Config** -> **Configuration**, then select any of the configuration files from the dropdown box and modify and save it.  Go to the dashboard and mouse over on the item, it also displays unknown)

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/c90c8ee10baf44bebcdd952a101453f9

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-a7e860
Build Number: a7e860de3bee814293d02941bc632a5a4b678f25
Build Date/Time: 03-07-2018 10:37:09 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1090

**Comment by alhambrav** [comment]
Verified fixed.
