### ISSUE TITLE
[studio] Provide REST API for Push and Pull of a named remote repository and branch 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1929]
### Expected behavior
The external user should be able to authenticate against Studio and use the API to initiate a push or pull on a  name remote for a site for a given repository[sandbox | publsihed] and branch

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss and plan.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1074

**Comment by dejan-brkic** [comment]
PR merged with ticket #1930

**Comment by russdanner** [comment]
List remotes does not seem to work against sandbox
https://www.useloom.com/share/4d4cc1078bd341a7831190a18d08ad17

**Comment by sumerjabri** [comment]
@dejan-brkic please adjust the list remotes API per our conversation.

**Comment by russdanner** [comment]
VIA API: CONFIRMED

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1080
