### ISSUE TITLE
[Studio] Provide Rest API to allow a remote to be added / removed to a site repository

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1930]
Provide Rest API to allow a remote to be added/removed to a site repository [sandbox | published]

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss and plan.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1074

**Comment by russdanner** [comment]
VIA API: CONFIRMED
