### ISSUE TITLE
[engine] Delivery does not resolve a previous published page for a site that is already published to delivery through init-site script (Windows + Edge)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1931]
### Expected behavior
The page should be resolved without problems and the delivery should be rendered without problems for the site provided.

### Actual behavior
There are two things to resolve:
* The published page is not resolved by delivery
* The render for the site provided is not displayed correctly

Watch the next video:
https://www.useloom.com/share/381a50a94269497294a59c4311826a26
See the next image:
![deliveryviewonedge](https://user-images.githubusercontent.com/16946208/37119912-c2811092-220d-11e8-949c-c3c0e36db9b3.JPG)

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site named **test**
* Go to delivery folder on your local: **craftercms/crafter-delivery/bin**
* Run the **init-site.bat test**
* Wait for a minute.
* Go back to studio and create a new page on the site of above, named **hitest**
* Publish the page of above.
* Wait for a minute.
* Go to delivery on the edge webbrowser using:
**http://localhost:9080/?crafterSite=test**
* Review the that delivery does not display the site properly.
* Try to resolve your page previously created using: **http://localhost:9080/hitest**

### Log/stack trace (use https://gist.github.com)
No log errors for this issue
#### Version
Studio Version Number: 3.0.10-SNAPSHOT-a7e860
Build Number: a7e860de3bee814293d02941bc632a5a4b678f25
Build Date/Time: 03-07-2018 09:02:03 -0600
#### OS
Windows 10
#### Browser
Edge

**Comment by luishernandezmonge** [comment]
Seems like the issue is related to a cookie (not set) on Edge.
See the next image: 
![edgecookiescapture](https://user-images.githubusercontent.com/16946208/37157933-ef278310-229e-11e8-8913-efa77c29f388.JPG)

**Comment by jdrossl** [comment]
@luishernandezmonge looks like Edge is ignoring the cookie because of the domain being set as `localhost`, if you use `127.0.0.1` instead everything works as expected.

**Comment by luishernandezmonge** [comment]
Verified as fixed, now using http://172.0.0.1:9080/... instead http://localhost:9080/... it works OK.
