### ISSUE TITLE
[studio] Update empty and editorial bp upload image repository path in content types to match default regex for item specific dependency

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1933]
### Expected behavior
It would be nice that when a page with an uploaded image is duplicated or copied, the image is also duplicated, without having to edit the content type or overriding the default regex pattern for item specific dependencies when using the empty or website_editorial bp.

### Actual behavior
When you copy/duplicate a page with an uploaded image, the image is not copied.
The repository path for the uploaded image does not match the regex pattern for item specific dependencies (`/static-assets/page/.*` from the studio-config.yaml file)

### Steps to reproduce the problem
* Using website_editorial bp, create a new article and upload an image from your desktop 
* From the **Sidebar**, right click on the newly created article and click on **Duplicate**
* Save and look at the **Sidebar** under **static-assets** to verify that the image was also duplicated.

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-a7e860
Build Number: a7e860de3bee814293d02941bc632a5a4b678f25
Build Date/Time: 03-07-2018 10:37:09 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/1067

**Comment by sumerjabri** [comment]
Please do the same for the headless blueprints.
