### ISSUE TITLE
[studio-ui] Don't move the form when selecting

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1934]
### Expected behavior
Forms shouldn't move when clicking into an RTE, repeat group, checkboxes, etc.

### Actual behavior
Forms move, such that if you double-click, the second click will hit something not intended on the form. Or single click on a checkbox and the form shifts under your mouse, etc.

### Steps to reproduce the problem
* Create a form with an RTE
* Double-click into the RTE, watch it jump
* Create a form with checkboxes, single click and the form shifts
* ...

#### Version
3.0.x

#### OS
Linux

#### Browser
Chromium

**Comment by jvega190** [comment]
@sumerjabri What happens it that rte has a behavior, when clicking inside on an rte it expands up to the size of the current form, shows the top bar, and fits into current view, that's the reason why is moves. Also, when clicking outside of it it will go back to its initial height (configured on content-type), so it moves elements under in the form.
With checkboxes, from what I tested, when clicking on them without previously clicking on rte they don't move, but if you previously clicked on a rte and then click on a checkbox then the rte will collapse, causing the checkbox to move (if it's after the rte). 
Please let me know if you need more explanation to see how are we going to proceed with this ticket

**Comment by jvega190** [comment]
Changes according to conversation:
- Requirements label on form fields, move to the side of the field title.
- RTE, no move when focusing on rte, only when pasting.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/796
