### ISSUE TITLE
[test-suite] Automate testing dependency calculation for what refers to an item

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1936]
Please automate ID 4 in **Studio -> Content**, test dependency calculation for what refers to an item

Setup:
* Site using Editorial BP
* Create a new article page under articles/2016/6 and upload an image from your desktop (new)

Steps:
1. Navigate to the Home page and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
2. Navigate to the Style category landing page and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
3. Navigate to the article page Women Styles for Winter and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
4. Navigate to the new article page and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
5. Navigate to the Search Results page and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
6. Navigate to the components/articles-widget/Latest Articles Widget and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
7. Navigate to the components/headers/Header and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
8. Navigate to the components/features/four and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
9. Navigate to the components/left-rails/Left Rail with Latest Articles and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
10. Navigate to the static-assets/images/book-woman-pic.jpg and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
11. Navigate to templates/web/pages/article.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
12. Navigate to templates/web/pages/category-landing.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
13. Navigate to templates/web/pages/home.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
14. Navigate to templates/web/pages/search-results.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
15. Navigate to scripts/pages/category-landing.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
16. Navigate to scripts/pages/home.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
17. Navigate to scripts/pages/search-results.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
18. Navigate to scripts/pages/site-map.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
19. Navigate to static-assets/css/font-awesome.min.css.css and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
20. Navigate to static-assets/css/ie8.css and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item
21. Navigate to static-assets/js/jquery.min.js and view it's dependencies, from the drop-down box in the dependencies screen, select Refers to this item

Expected Output:
1. No dependencies
2. No dependencies
3. No dependencies
4. No dependencies
5. No dependencies
6. Item: Left Rail with Latest Articles    /site/components/left-rails/left-rail-with-latest-articles.xml
7. Item: (need to check if it's correct name is empty...)    /site/website/crafter-level-descriptor.level.xml
8. No dependencies
9. Item: Home    /site/website/index.xml
   Item: Search Results    /site/website/search-results/index.xml
10. Item: Top Books For Young Women    /site/website/articles/2016/12/top-books-for-young-women/index.xml
11. Item: Men Styles For Winter    /site/website/articles/2017/1/men-styles-for-winter/index.xml
    Item: Women Styles for Winter    /site/website/articles/2017/2/women-styles-for-winter/index.xml
    Item: Top Romantic Valentine Movies    /site/website/articles/2017/2/top-romantic-valentine-movies/index.xml
    Item: 5 Popular Diets for Women    /site/website/articles/2017/3/5-popular-diets-for-women/index.xml
    Item: 10 Tips to Get a Six Pack    /site/website/articles/2017/2/10-tips-to-get-a-six-pack/index.xml
    Item: Top Clubs In Virginia    /site/website/articles/2017/3/top-clubs-in-virginia/index.xml
    Item: New ACME Phone Released Today    /site/website/articles/2016/7/new-acme-phone-released-today/index.xml
    Item: Top Books For Young Women    /site/website/articles/2016/12/top-books-for-young-women/index.xml
    Item: Coffee is Good for Your Health    /site/website/articles/2016/6/coffee-is-good-for-your-health/index.xml
    Item: new    /site/website/articles/2016/6/new/index.xml
12. Item: Style    /site/website/style/index.xml
    Item: Health    /site/website/health/index.xml
    Item: Technology    /site/website/technology/index.xml
    Item: Entertainment    /site/website/entertainment/index.xml
13. Item: Home    /site/website/index.xml
14. Item: Search Results    /site/website/search-results/index.xml
15. Item: Item: Style    /site/website/style/index.xml
    Item: Health    /site/website/health/index.xml
    Item: Technology    /site/website/technology/index.xml
    Item: Entertainment    /site/website/entertainment/index.xml
16. Item: Home    /site/website/index.xml
17. Item: Search Results    /site/website/search-results/index.xml
18. No dependencies 
19. No dependencies
20. Item: 404.ftl    /templates/web/errors/404.ftl
    Item: 500.ftl    /templates/web/errors/500.ftl
    Item: article.ftl    /templates/web/pages/article.ftl
    Item: home.ftl    /templates/web/pages/home.ftl
    Item: search-results.ftl    /templates/web/pages/search-results.ftl
    Item: category-landing.ftl    /templates/web/pages/category-landing.ftl
21. Item: 404.ftl    /templates/web/errors/404.ftl
    Item: 500.ftl    /templates/web/errors/500.ftl
    Item: article.ftl    /templates/web/pages/article.ftl
    Item: home.ftl    /templates/web/pages/home.ftl
    Item: search-results.ftl    /templates/web/pages/search-results.ftl
    Item: category-landing.ftl    /templates/web/pages/category-landing.ftl

**Comment by luishernandezmonge** [comment]
Test case added to the next PR: https://github.com/craftercms/test-suite/pull/317.
Test this test case when PR is done.

**Comment by alhambrav** [comment]
Please add  a check on the text displayed in the Dependencies screen, i.e. `Dependencies shown for: Home` for the home page, `Dependencies shown for: Style` for the Style category landing page, and so on and so forth for all the other items where we are checking dependencies. Thank you.

**Comment by luishernandezmonge** [comment]
Ok, will start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Added checks of above to the test case. Please check when the next PR is done: https://github.com/craftercms/test-suite/pull/319

**Comment by alhambrav** [comment]
Verified.
