### ISSUE TITLE
[test-suite] Automate testing dependency calculation for what an item refers to

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1937]
Please automate ID 5 in **Studio -> Content**, Test dependency calculation for what an item refers to (Is referenced by this item)

**Setup**:
* Site using Editorial BP
* Create a new article page under articles/2016/6 and upload an image from your desktop (new)

**Steps**:
1. Navigate to the Home page and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
2. Navigate to the Style category landing page and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
3. Navigate to the article page Women Styles for Winter and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
4. Navigate to the new article page and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
5. Navigate to the Search Results page and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
6. Navigate to the components/articles-widget/Latest Articles Widget and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
7. Navigate to the components/headers/Header and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
8. Navigate to the components/features/four and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
9. Navigate to the components/left-rails/Left Rail with Latest Articles and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
10. Navigate to the static-assets/images/book-woman-pic.jpg and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
11. Navigate to templates/web/pages/article.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
12. Navigate to templates/web/pages/category-landing.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
13. Navigate to templates/web/pages/home.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
14. Navigate to templates/web/pages/search-results.ftl and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
15. Navigate to scripts/pages/category-landing.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
16. Navigate to scripts/pages/home.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
17. Navigate to scripts/pages/search-results.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
18. Navigate to scripts/pages/site-map.groovy and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
19. Navigate to static-assets/css/font-awesome.min.css.css and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
20. Navigate to static-assets/css/ie8.css and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item
21. Navigate to static-assets/js/jquery.min.js and view it's dependencies, from the drop-down box in the dependencies screen, select Is referenced by this item

**Expected Output**:
1. Item: Three    /site/components/features/sapien-veroeros.xml
   Item: home.ftl    /templates/web/pages/home.ftl
   Item: Two    /site/components/features/quam-lorem-ipsum.xml
   Item: home.groovy    /scripts/pages/home.groovy
   Item: Left Rail with Latest Articles    /site/components/left-rails/left-rail-with-latest-articles.xml
   Item: strawberries.jpg    /static-assets/images/strawberries.jpg
2. Item: category-landing.groovy    /scripts/pages/category-landing.groovy
   Item: category-landing.ftl    /templates/web/pages/category-landing.ftl
3. Item: article.ftl    /templates/web/pages/article.ftl
   Item: winter-woman-pic.jpg    /static-assets/images/winter-woman-pic.jpg
4. Item: article.ftl    /templates/web/pages/article.ftl
   Item: 13280450785_0f23ab346b_o copy.jpg    /static-assets/page/images/f33fec95-3acb-f1e5-de96-f9e6e9519921/13280450785_0f23ab346b_o copy.jpg (this will depend on the image you uploaded, but the important part here is that the image is copied to folder /static-assets/page/images/{random-characters}/your_image.jpg)
5. Item: search-results.groovy    /scripts/pages/search-results.groovy
   Item: Left Rail with Latest Articles    /site/components/left-rails/left-rail-with-latest-articles.xml
   Item: search-results.ftl    /templates/web/pages/search-results.ftl
6. Item: latest-articles.groovy    /scripts/components/latest-articles.groovy
   Item: articles-widget.ftl    /templates/web/components/articles-widget.ftl
7. Item: header.ftl    /templates/web/components/header.ftl
8. Item: feature.ftl    /templates/web/components/feature.ftl
9. Item: Latest Articles Widget    /site/components/articles-widget/latest-articles-widget.xml
   Item: left-rail.ftl    /templates/web/components/left-rail.ftl
   Item: Contact Widget    /site/components/contacts/contact-widget.xml
10. No dependencies
11. Item: jquery.min.js           /static-assets/js/jquery.min.js
    Item: jquery-ui.min.js    /static-assets/js/jquery-ui.min.js
    Item: skel.min.js    /static-assets/js/skel.min.js
    Item: util.js    /static-assets/js/util.js
    Item: main.css    /static-assets/css/main.css
    Item: main.js    /static-assets/js/main.js
    Item: ie9.css    /static-assets/css/ie9.css
    Item: html5shiv.js    /static-assets/js/ie/html5shiv.js
    Item: jquery-ui.min.css    /static-assets/css/jquery-ui.min.css
    Item: ie8.css    /static-assets/css/ie8.css
    Item: placeholder.png    /static-assets/images/placeholder.png
    Item: respond.min.js    /static-assets/js/ie/respond.min.js
12. Item: jquery.min.js           /static-assets/js/jquery.min.js
    Item: jquery-ui.min.js    /static-assets/js/jquery-ui.min.js
    Item: skel.min.js    /static-assets/js/skel.min.js
    Item: util.js    /static-assets/js/util.js
    Item: main.css    /static-assets/css/main.css
    Item: main.js    /static-assets/js/main.js
    Item: ie9.css    /static-assets/css/ie9.css
    Item: html5shiv.js    /static-assets/js/ie/html5shiv.js
    Item: jquery-ui.min.css    /static-assets/css/jquery-ui.min.css
    Item: ie8.css    /static-assets/css/ie8.css
    Item: placeholder.png    /static-assets/images/placeholder.png
    Item: respond.min.js    /static-assets/js/ie/respond.min.js
13. Item: jquery.min.js           /static-assets/js/jquery.min.js
    Item: jquery-ui.min.js    /static-assets/js/jquery-ui.min.js
    Item: skel.min.js    /static-assets/js/skel.min.js
    Item: util.js    /static-assets/js/util.js
    Item: main.css    /static-assets/css/main.css
    Item: main.js    /static-assets/js/main.js
    Item: ie9.css    /static-assets/css/ie9.css
    Item: html5shiv.js    /static-assets/js/ie/html5shiv.js
    Item: jquery-ui.min.css    /static-assets/css/jquery-ui.min.css
    Item: ie8.css    /static-assets/css/ie8.css
    Item: placeholder.png    /static-assets/images/placeholder.png
    Item: respond.min.js    /static-assets/js/ie/respond.min.js
14. Item: util.js    /static-assets/js/util.js
    Item: main.js    /static-assets/js/main.js
    Item: ie9.css    /static-assets/css/ie9.css
    Item: html5shiv.js    /static-assets/js/ie/html5shiv.js
    Item: jquery-ui.min.css    /static-assets/css/jquery-ui.min.css
    Item: respond.min.js    /static-assets/js/ie/respond.min.js
    Item: jquery.min.js    /static-assets/js/jquery.min.js
    Item: jquery-ui.min.js    /static-assets/js/jquery-ui.min.js
    Item: skel.min.js    /static-assets/js/skel.min.js
    Item: main.css    /static-assets/css/main.css
    Item: handlebars.min-latest.js    /static-assets/js/handlebars.min-latest.js
    Item: ie8.css    /static-assets/css/ie8.css
    Item: search.js    /static-assets/js/search.js
15. No dependencies
16. No dependencies
17. No dependencies
18. No dependencies
19. No dependencies
20. No dependencies
21. No dependencies

**Comment by luishernandezmonge** [comment]
@alhambrav Please, can you add more details on this ticket?

**Comment by alhambrav** [comment]
@luishernandezmonge Done.  Please see updated ticket.  Also, ticket 1936 has been filled out.

**Comment by alhambrav** [comment]
Please add  a check on the text displayed in the Dependencies screen, i.e. `Dependencies shown for: Home` for the home page, `Dependencies shown for: Style` for the Style category landing page, and so on and so forth for all the other items where we are checking dependencies. Thank you.

**Comment by luishernandezmonge** [comment]
@alhambrav done and added to testng.xml suite on next PR: https://github.com/craftercms/test-suite/pull/320

**Comment by alhambrav** [comment]
Verified.
