### ISSUE TITLE
[studio-ui] Viewing dependencies of a new article page with an uploaded image displays dependencies of image instead of page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1938]
### Expected behavior
When viewing the dependencies screen for a page (new article page with uploaded image, or otherwise), the title should display the article page title, like in the image below (`Dependencies shown for: New ACME Phone Released Today`), since we are trying to view dependencies on the article page 

![screen shot 2018-03-12 at 3 15 12 pm](https://user-images.githubusercontent.com/25483966/37304649-8cc08088-2608-11e8-95f3-a98bf8aeaa55.png)

### Actual behavior
When viewing the dependencies screen for a newly created article page with an uploaded image, the title is displaying the image name instead of the article page title (it looks like it is also showing dependencies for the image for `Refers to this item`) See image below:

![screen shot 2018-03-12 at 2 59 57 pm](https://user-images.githubusercontent.com/25483966/37304088-fe555734-2606-11e8-8780-72205bdf77b0.png)

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a new article page and upload an image (From the **Sidebar**, create a new article page under articles/2016/7, upload an image from your desktop)
* From the **Sidebar**, right click on the new article created and click on **Dependencies**, notice in the dependencies screen that it's displaying dependencies for the image instead of the page (See image above: `Dependencies shown for: 9403317911_4e6acc4ae3_o.jpg`)

Please note that this happens when the repository path for uploaded images is `/static-assets/page/images/{objectId}/`  
Also, it looks like the `Is referenced by this item` is displaying the correct dependencies for the article page even if the title says it's displaying dependencies for the image

### Log/stack trace (use https://gist.github.com)
Here's a short clip, first showing the repository path for uploaded images (`/static-assets/page/images/{objectId}/`), then a new article is created with an uploaded image.  Finally, dependency is viewed for the newly created article
https://www.useloom.com/share/f96d63e9bd8b4090bcd757ca38efdefc

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-99012f
Build Number: 99012f00951416b5f4da8fdb814f4a3c8f775cb8
Build Date/Time: 03-12-2018 14:35:21 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Can not reproduce the issue with the same build. Tried all browsers (chrome incognito too)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/791

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by yacdaniel** [comment]
This is happening in `3.1.6-SNAPSHOT` steps are the same as described in ticket, ping me if needed.

**Comment by yacdaniel** [comment]
@sumerjabri please prioritize/schedule.

**Comment by yacdaniel** [comment]
Verified fixed.
