### ISSUE TITLE
[studio-ui] Add the ability to specify the path where a component will be created from a form.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1939]
On an item selector (e.g in Editorial blueprint, Home Page > Features), when clicking on Add and then Create New, there should be some way to specify the exact path where the component will be created. This could be an option of the content type.

**Comment by sumerjabri** [comment]
Path, where assets are ultimately stored, are controlled in the content model design and help keep the system consistent over time. Furthermore, the storage destination designed in the model dictates how those assets are handled during a duplicate event (duplicate the asset or duplicate the reference to the asset). Finally, the content model designer decides where different assets uploaded via different controls go (for instance icons, images, RTE related assets, etc.).

Please review the macros available to you in the design of storage destination as that may address the need.
