### ISSUE TITLE
[studio-ui] Add the ability to specify the path where an image will be placed when uploading from a form

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1940]
When using an image picker with the option of uploading the image from the desktop, it would be good to have the option of specifying the path where the image will be uploaded.

**Comment by sumerjabri** [comment]
Path, where assets are ultimately stored, are controlled in the content model design and help keep the system consistent over time. Furthermore, the storage destination designed in the model dictates how those assets are handled during a `duplicate` event (duplicate the asset or duplicate the reference to the asset). Finally, the content model designer decides where different assets uploaded via different controls go (for instance icons, images, RTE related assets, etc.).
