### ISSUE TITLE
[studio-ui] Dependencies in publish dialogs show as [object,object]

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1941]
### Expected behavior
Dependencies should list when expanded

### Actual behavior
[object, object] is displayed where dependencies should be shown

### Steps to reproduce the problem
* Create a page and associate a new image with it
* Approve an publish
* Expand the deployment dependencies in the dialog and note the [object, object]

<img width="743" alt="screen shot 2018-03-13 at 11 29 05 am" src="https://user-images.githubusercontent.com/169432/37351759-29ee40ee-26b2-11e8-892b-796d472042de.png">

#### Browser
Studio Version Number: 3.0.9-SNAPSHOT-90de69
Build Number: 90de6980ef239739bb6d2b6151601a1b35c10272
Build Date/Time: 03-06-2018 10:26:27 -0500

#### Version
Chrome

**Comment by dejan-brkic** [comment]
Fixed BE issue with the wrong result set
PR:
https://github.com/craftercms/studio/pull/1069

[object, object] display is UI issue

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/790

**Comment by russdanner** [comment]
VERIFIED
