### ISSUE TITLE
[studio-ui] forward user to login if validate token returns 0, 401, 301 or 302 then redirect to login 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1942]
### Expected behavior
0, 401, 301, 302 should log the user out. Either the session has expired or SSO or something else is playing with the request

### Actual behavior
401 logs the user out. 301 and 302 report like network errors 

Current code:
Common API:~7959
` if(response.status == 401){ ... }
`

Example Zero response code (server responds 302 but ajax lib reports 0)
<img width="304" alt="screen shot 2018-03-13 at 3 56 18 pm" src="https://user-images.githubusercontent.com/169432/37366631-5e0e3242-26d7-11e8-8484-bd38add6d986.png">

Applies to 2.x and 3.x

**Comment by vestrada** [comment]
PR - 3 : https://github.com/craftercms/studio-ui/pull/794
PR = 2.5.x: https://github.com/craftercms/studio-ui/pull/795

**Comment by russdanner** [comment]
CONFIRMED
