### ISSUE TITLE
[studio-ui] Preview of image in bulk upload not working anymore

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1943]
Steps:

1. Create site from editorial.
2. Use Bulk Upload to upload images to /static-assets/images.

Result:

The images are uploaded but the previews are broken. 

![screenshot from 2018-03-13 16-53-53](https://user-images.githubusercontent.com/1598884/37369562-d777d644-26df-11e8-91d0-c2f6e6744d7d.png)

Please let me know if this is a server-side related issue since several changes on image upload/processing were made recently.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/793

**Comment by avasquez614** [comment]
Tested and verified
