### ISSUE TITLE
[studio] Copy-dependencies does not seem to be working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1944]
### Expected behavior
When you perform a copy, item expected to be copied to a certain directory should be copied as specified in the `config.xml` of content type.

### Actual behavior
Copy-dependencies does not seem to be working.  When you perform a copy, item expected to be copied to a certain directory is not copied.

### Steps to reproduce the problem
* Create a site using website_editorial
* Click on **Site Config** -> **Content Types** -> **Open Existing Type**, then select **Page - Article**
* In the **Properties Explorer**, go to **Configuration**, click on the pencil next to **config.xml** to edit, then add this to the file:

```
<copy-dependencies>
	<copy-dependency>
		<pattern>/static-assets/images/.*</pattern>
		<target>/static-assets/images/page/</target>
	</copy-dependency>
</copy-dependencies>
```
* **Save** your changes and go back to the **Sidebar**
* Create a folder `page` under `/static-assets/images`
* Navigate to `articles/2016/12` and right click on `Top Books for Young Women` and select **Copy**
* Paste the article you copied to another folder
* Navigate to `/static-assets/images/page/`, notice that the image in the article is not copied in the folder and what you see is just a folder with a random letter name beginning with a dash
![screen shot 2018-03-14 at 10 27 39 am](https://user-images.githubusercontent.com/25483966/37408414-6e499430-2772-11e8-8854-0af12dd823f1.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/4f655ae28fe94ee48648e9b4567b3a69

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-70e9d3
Build Number: 70e9d3bf541d1a8549587c0ce9863ea1b61f9597
Build Date/Time: 03-14-2018 09:48:09 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1075

**Comment by alhambrav** [comment]
Verified fixed.
