### ISSUE TITLE
[studio] Extract the actual group name for an LDAP user using regex.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1946]
It's very common for LDAP directories like OpenLDAP and Active Directory to have `memberOf` attributes in user entries that contain the groups the user is a member of, example:

`memberOf: cn=Crafter_Author,ou=groups,dc=example,dc=com`

Studio needs to extract the actual group name from the attribute value. The easiest way seems to be by regex:

`cn=Crafter_([a-zAZ]+),ou=groups,dc=example,dc=com`

So in the case of the example, Studio would iterate through the `memberOf` attributes, match against the regex and then use the group 1 as the group name for the site.

This should be configurable, with a property for the regex and another one for the regex group that contains the actual group name.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1071
https://github.com/craftercms/craftercms/pull/1953

**Comment by avasquez614** [comment]
Group extraction works, but noticed that it seems to be a required property now. I think the property should be commented in YAML by default or have an empty value, and indicate that's optional:

```
# LDAP groups attribute name regex (optional, if not specified all attribute values are used)
#studio.security.ldap.userAttribute.groupName.regex: cn=Crafter_([a-zA-Z]+),.*
# LDAP groups attribute match index (optional if regex is not specified)
studio.security.ldap.userAttribute.groupName.matchIndex: 1
```

The example, regex was also wrong (my typo). It should be [a-zA-Z]+.

Finally, the code that does the matching should check if the groupName regex exists or is empty:

```
String regex = studioConfiguration.getProperty(SECURITY_LDAP_USER_ATTRIBUTE_GROUP_NAME_REGEX);
if (StringUtils.isNotEmpty(regex)) {        
	Pattern pattern = Pattern.compile(regex);
	Matcher matcher = pattern.matcher(groupAttributeValue);
	if (matcher.matches()) {
	    int index = Integer.parseInt(studioConfiguration.getProperty(SECURITY_LDAP_USER_ATTRIBUTE_GROUP_NAME_MATCH_INDEX));
	    return matcher.group(index);
	}
	return StringUtils.EMPTY;
} else {
	return groupAttributeValue;
}
```

**Comment by dejan-brkic** [comment]
LDAP is optional security provider. There is no sense indicating that property is optional because it will only be used if LDAP is used.
Additionally, this is the ticket addresses only specified use case as described. More general approach for the group name value extraction will be addressed in another ticket.

**Comment by russdanner** [comment]
If the absence of the new property causes existing instances to break we should smartly handle that situation either a default or whatever else makes sense.

**Comment by sumerjabri** [comment]
We will change the default regex to something like: (.*) with group 1 which should be backward compatible. Dejan to test and submit the final values.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1073

**Comment by avasquez614** [comment]
Tested and verified
