### ISSUE TITLE
[studio-ui] Studio allows to user perform double click on Yes when delete site and a 'Failed to delete search index for site org.craftercms.studio.api.v1.exception.ServiceException' exception is returned

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1948]
### Expected behavior
Studio should not allow to perform the double click, after first click the button should be disabled.

### Actual behavior
Studio allows to user perform double click when delete site and a  exception is returned.
Watch the next video:
https://www.useloom.com/share/9cb1dbb715fc480cb6a653c9dec66e42

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site
* Go back to sites page, and click on delete icon for the site of above.
* Double click on the Yes button of the delete dialog.
* Check the studio log.

### Log/stack trace (use https://gist.github.com)
Log error: https://gist.github.com/luishernandezmonge/a7a8891db069c851b60ce547ba336313

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-70e9d3
Build Number: 70e9d3bf541d1a8549587c0ce9863ea1b61f9597
Build Date/Time: 03-14-2018 14:53:07 -0700

#### OS
Windows 10 and Mac OSx

#### Browser
Edge, Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/800

**Comment by luishernandezmonge** [comment]
I'm still able to reproduce it, currently I have the next log error(on mac):
https://gist.github.com/luishernandezmonge/71e8f30e29e1da6568235a8b2b93b37b

Version:
Studio Version Number: 3.0.10-SNAPSHOT-26769e
Build Number: 26769ee4c793265c6e4407c73c39c640e93a3d43
Build Date/Time: 03-22-2018 16:09:58 -0600

**Comment by jvega190** [comment]
@luis-rivet I'm not being able to reproduce it (tested in chrome, firefox, edge), can you provide more details please?

**Comment by luishernandezmonge** [comment]
@jvega190 Same scenario as above, perform quick double click on site deletion dialog, and later check the studio log. Will check this again ASAP.

**Comment by luishernandezmonge** [comment]
Just checked, and seems like it is working ok. I will close this ticket.
