### ISSUE TITLE
[craftercms] Add studio.db.socket to studio-config-override.yaml

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1949]
The following property should be part of `studio-config-override.yaml` since it needs to be modified when ports are modified too:

```
# Socket path for the embedded database
studio.db.socket: /tmp/MariaDB4j.33306.sock
```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/craftercms/pull/1966

**Comment by avasquez614** [comment]
Verified
