### ISSUE TITLE
[studio] "Error getChildren invoked for a file for site" error is displayed when try to delete a content page.

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1954]
### Expected behavior
No errors should be displayed on the log when try to delete an item. Also the dependencies should be calculated as well.

### Actual behavior
The  "Error getChildren invoked for a file for site" error is displayed when try to delete a content page.
Watch the next video:
https://www.useloom.com/share/0b91fc9cd62b439eac1efc304ce84a1e

### Steps to reproduce the problem
*  Go to studio and login as admin
* Create a site using Website Editorial bp
* Go to preview page and create a new content page under Home
* Click on the new content page and click on Delete option of top nav
* Check the log
* Click on Style content and click on Delete option of top nav
* Check the log
* Create a new page article on the articles folder
* Click on the new article and click on Delete option of top nav
* Check the log

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/edb92f5f96cdbcb31df891f64bbbf275

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-70e9d3
Build Number: 70e9d3bf541d1a8549587c0ce9863ea1b61f9597
Build Date/Time: 03-15-2018 07:35:30 -0700
#### OS
Windows, Mac OSX and Linux
#### Browser
Edge, Chrome

**Comment by dejan-brkic** [comment]
The log is misleading. The message is generated when trying to get children for a file during dependency calculation for delete. Changed log message and lowered log level

PR:
https://github.com/craftercms/studio/pull/1076

**Comment by luishernandezmonge** [comment]
Verified as resolved.
