### ISSUE TITLE
[studio] "Error executing REST script at /scripts/rest/api/1/dependency/get-dependencies.post.groovy" error is displayed on the log and the text "Unable to load dependencies" is displayed on the delete dialog when user tries to delete a content page with an uploaded image

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#1955]
### Expected behavior
* Dependencies list should be loaded correctly on the delete dialog.
* No errors should be present on the log when try to delete the article.

### Actual behavior
The "Error executing REST script at /scripts/rest/api/1/dependency/get-dependencies.post.groovy" error is displayed on the log and the text "Unable to load dependencies" is displayed on the delete dialog when user tries to delete a content page with an uploaded image.

Watch the next video:
https://www.useloom.com/share/0b91fc9cd62b439eac1efc304ce84a1e

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site using Website Editorial bp
* Go to preview page and create a new article page under articles folder (using an uploaded image on the **Image** field)
* Click on the new article and click on Delete option of top nav
* Notice that the next text is displayed on the dependencies list on delete dialog:
    **Unable to load dependencies. Try again**
* Check the log

### Log/stack trace (use https://gist.github.com)
Log error
https://gist.github.com/luishernandezmonge/b206d7d9fedfce3955fec76d2a044249
#### Version
Studio Version Number: 3.0.10-SNAPSHOT-70e9d3
Build Number: 70e9d3bf541d1a8549587c0ce9863ea1b61f9597
Build Date/Time: 03-15-2018 07:35:30 -0700
#### OS
Windows, Mac OSX and Linux
#### Browser
Edge, Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1077

**Comment by luishernandezmonge** [comment]
Verified as resolved.
