### ISSUE TITLE
[studio-ui] In box-file-upload when the list of files selected is empty, the first file the user choose is shown as undefined.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#1956]
### Expected behavior
All the files should have the correct name when the user choose it.

### Actual behavior

In box-file-upload when the list of files selected is empty, the first file the user choose is undefined.

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a content type with a box-file-upload control.
* Choose the first file. You will see that it will be undefined.

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-99012f
Build Number: 99012f00951416b5f4da8fdb814f4a3c8f775cb8
Build Date/Time: 03-12-2018 14:35:21 -0400

#### OS
OS X

#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/797

**Comment by jdrossl** [comment]
Verified
