### ISSUE TITLE
[Deployer] init-site.sh should support HTTP GIT URL (also user/password)

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1959]
### Expected behavior
init-site.sh should support the use of HTTP git URL's and also support secure HTTP URLs.
Allow the user's to set the username/password 

### Actual behavior
This error message 
```
Repository path https://github.com/hlim/test.git for site "test" does not exist or cannot to read
```

### Steps to reproduce the problem
``` bash
 ./init-site.sh test https://github.com/cortiz/sample.git
```

**Comment by avasquez614** [comment]
Duplicated of craftercms/craftercms#1983
