### ISSUE TITLE
[studio-ui] Some styles from studio are affecting guest site.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#1960]
### Expected behavior
FA Icons styles from the client should work.

### Actual behavior
Some Icon styles from studio are affecting guest site.

### Steps to reproduce the problem
* Create a site using website_editorial
* Use Fa icons in the client site.

#### Version

Studio Version Number: 3.0.10-SNAPSHOT-99012f
Build Number: 99012f00951416b5f4da8fdb814f4a3c8f775cb8
Build Date/Time: 03-12-2018 14:35:21 -0400

#### OS

OS X

#### Browser
Chrome browser

**Comment by jdrossl** [comment]
Verified
