### ISSUE TITLE
[studio-ui] No options for request publish and deleted appear as author when multiple edited files are selected

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1961]
### Expected behavior

When I select multiple pages, components or images as an author in Recent Activity, that are shown as edited, options for Request For Publish and Delete appear in the top menu bar.

### Actual behavior
When I select multiple pages, components or images as an author in Recent Activity, that are shown as edited, **no** options appear in the top menu bar.

### Steps to reproduce the problem

* Login to Studio as an author (not as an admin)
* Create a site using the editorial bp
* Edit several pages or components (or upload several images).
* Select the pages or components you recently edited.
* Notice that nothing appears in the top menu bar.

![screenshot from 2018-03-19 16-54-06](https://user-images.githubusercontent.com/1598884/37621807-6fd927ac-2b96-11e8-9b65-1385ce3c9bea.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/799

**Comment by avasquez614** [comment]
Tested and verified
