### ISSUE TITLE
[studio] Uploaded images without extension are shown as folders

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1962]
### Expected behavior

When you upload an image without extension it should be shown as a generic file.

### Actual behavior

When you upload an image without extension it's shown as a folder.

### Steps to reproduce the problem

* Login to Studio.
* Create a site based on editorial.
* Upload an image under Static Assets > images.
* See how the image is shown as a folder.

![screenshot from 2018-03-19 18-11-48](https://user-images.githubusercontent.com/1598884/37625139-199a0194-2ba1-11e8-8f8b-7fcc08de0ba3.png)

**Comment by jvega190** [comment]
@avasquez614 when item has no extension it returns with folder properties (contentType, folder)

![screen shot 2018-03-21 at 2 34 18 pm](https://user-images.githubusercontent.com/18267471/37735992-4af1d918-2d15-11e8-9615-bf56038e90c0.png)

**Comment by sumerjabri** [comment]
Backend bug, moved it to Dejan. This becomes a non-issue with the new API.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1078

**Comment by avasquez614** [comment]
Tested and verified
