### ISSUE TITLE
[studio-ui] Add view history to static-assets

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1976]
### Expected behavior
The user should be able to view the history of a static-asset

### Actual behavior
View history is not available as a menu item for static-assets in the Sidebar, only on the Dashboard

### Steps to reproduce the problem
* Create a site based on Editorial BP
* Right-click a static-asset (like an image or CSS)
* `History` is not a menu item

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Any

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/803
