### ISSUE TITLE
[social] user's  default placeholder portrait does not look fine

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#1978]
### Expected behavior
placeholder image should look fine

### Actual behavior
Image has gap in the on the right side
https://github.com/craftersoftware/social/blob/master/server/src/main/webapp/resources/silhouette.png
More noticeable when using border radius
<img width="205" alt="screen shot 2018-03-26 at 8 32 07 am" src="https://user-images.githubusercontent.com/813023/37912674-3d03efc6-30d0-11e8-8f42-171d55a453ef.png">

### Steps to reproduce the problem
Any crafter social version, with user with no image already set

### Log/stack trace
no logs needed 

#### Version
any
#### OS
any
#### Browser
any

**Comment by sumerjabri** [comment]
Updated for 3.1.7 and 3.2.0.
