### ISSUE TITLE
CRAFTERCMS-2134: Studio does not indicate that you are trying to create an existing site.

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#198]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Description/Steps Template

PRECONDITIONS:
1. N/D

REPRODUCIBILITY LEVEL: Always

STEPS:
1. GO to: http://localhost:8080/studio#/login
2. Type the valid credentials to login. 
3. Click on “Create Site” button.
4. Create a site with the following data:
Site Name= test
Site ID= test
Description = test
Blueprint = pluton
5. Click on “Create” button
6. Open the combo and select “All sites” option.
7. Click on “Create Site” button.
8. Create a site with the following data:
Site Name= test
Site ID= test
Description = test
Blueprint = pluton
9. Click on “Create” button

CURRENT RESULT:
Studio does not indicate that you are trying to create an existing site(same data) and display the following message in the step 9 “Oops! A server error has occurred and we were unable to fulfill the request.
Please try again. If the error persists, contact the administrator of the site.” 

EXPECTED RESULT:
The app should display a validation when the “site name” and “site Id” are same that for another existing site.

:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2134
----------

**Comment by vestrada** [comment]
Hi Dejan, Per our conversation this ticket should first be work in back-end.

**Comment by dejan-brkic** [comment]
Added service to check if site already exists:

api/1/services/api/1/site/exists.json?site=<SITEID>

**Comment by vestrada** [comment]
Completed
