### ISSUE TITLE
[studio] Please add new macro for create date

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1980]
Please add three new macros that are based on the create-date of an item. The macros are:
* {yyyy}: the 4 digit year of the create date
* {mm}: the 2 digit month of the create date
* {dd}: the 2 digit day of the create date

**Comment by dejan-brkic** [comment]
@alhambrav @sumerjabri Can you please add more description on requested feature

**Comment by dejan-brkic** [comment]
Macros for paths are resolved in data sources (UI). Backend just receives already prepared path. This is UI ticket.

**Comment by alhambrav** [comment]
Verified.
