### ISSUE TITLE
[test-suite] Automate rename via form (page.xml move name (rename))

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1985]
Please automate rename via form (page.xml move name (rename)) ID 26 in **Studio -> Content**.  

**Setup:**
1) Create a site using Empty BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Entry" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "Home" and select "New Content"
13) Select "Entry" and click on the "Ok" button in the "Choose Content Type" screen
14) Put "foo" in the "Page URL" field
15) Put "foo" in the "File Title" field
16) Fill in the rest of the required fields in the form and save your changes

Here's how your dashboard **My Recent Activity** will look like after creating the new content:
<img width="922" alt="screen shot 2018-03-28 at 2 49 01 pm" src="https://user-images.githubusercontent.com/25483966/38049841-400254c4-3297-11e8-8dd9-1464bb1a893a.png">

**Steps:**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Settings" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard

**Expected Output:**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Previous or Dashboard)
9) The URL should contain "page=/bar.html"
10) The "My Recent Activity" widget should contain the following:
    Item Name: foo    Edit: Edit    URL: bar.xml

Here's how your dashboard **My Recent Activity** will look like after after renaming via form:
<img width="915" alt="screen shot 2018-03-28 at 2 50 48 pm" src="https://user-images.githubusercontent.com/25483966/38049919-74985328-3297-11e8-96e5-4ade65412df8.png">

Here's a short clip of the test performed manually:
https://www.useloom.com/share/e616dc990e574fafa3ff37756dc7cf8e

Please modify the steps as necessary to accommodate automated test development (this is mostly the gist of what needs to be tested).

**Comment by luishernandezmonge** [comment]
I will start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav already added to testing.xml test suite, please check it.

**Comment by alhambrav** [comment]
Verified.
