### ISSUE TITLE
[studio] Switching to a different branch and then bulk publishing doesn't work

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1986]
### Expected behavior

If I switch to a branch in sandbox that is not master, and I then bulk publish, all the changes of that branch should be published to live.

### Actual behavior

If I switch to a branch in sandbox that is not master, and I then bulk publish, I get an error.

### Steps to reproduce the problem

* Stop Studio
* Go to the sandbox repo and create a branch based on master (e.g. `env-dev1`).
*  In the `studio-config-overrides.yaml`, add the property to switch to the branch (`studio.repo.siteSandboxBranch: env-dev1`)
* Start Studio.
* Wait for Studio to sync the database. Everything looks good at this point.
* Got to the Site Config and do a Bulk Publish.

The result is that publishing fails and stops completely.

### Log/stack trace (use https://gist.github.com)

https://gist.github.com/avasquez614/7569810f362d95351cfb34ab8e0bf352

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1083

**Comment by avasquez614** [comment]
Tested and verified
