### ISSUE TITLE
[studio] Allow creating a site from remote repo branch

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1987]
Add the ability in Studio to create a site from a branch of a remote repository. Would be great also if you could have the _option_ of only cloning that single branch and avoid retrieving the history of all the other branches (like `git clone -b <branch> --single-branch <url>`).

**Comment by dejan-brkic** [comment]
Done
Docs:
https://github.com/craftercms/docs/pull/503

PR:
https://github.com/craftercms/studio/pull/1094

**Comment by avasquez614** [comment]
Tested and verified
