### ISSUE TITLE
[studio-ui] Error creating a site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1988]
### Expected behavior
There should be no errors when creating a site

### Actual behavior
There is an error message when you create a site

### Steps to reproduce the problem
* Create a site using any bp 
* Notice the error message on your screen (no error message in the logs)

![screen shot 2018-03-29 at 10 26 30 am](https://user-images.githubusercontent.com/25483966/38094422-b288e72a-333b-11e8-8a9c-09e50630a787.png)

* Click **Close** and refresh your browser, your site is there but we're not sure if it's missing something because of the error message

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-9c4fa0
Build Number: 9c4fa01e6a791e0d691416ee60e32238133a726a
Build Date/Time: 03-29-2018 10:22:05 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1084

**Comment by alhambrav** [comment]
Verified fixed.
