### ISSUE TITLE
[studio] Audit log older entries (content) get updated 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1989]
### Expected behavior
Audit log older entries (content) should not be updated 

### Actual behavior
Audit log older entries (content) get updated 

### Steps to reproduce the problem
* Using the Empty bp, create a new "Entry" page called "foo"
* Go to **Site Config** and click on **Audit**, notice the entries
<img width="1133" alt="screen shot 2018-03-28 at 3 12 14 pm" src="https://user-images.githubusercontent.com/25483966/38051919-b102a506-329d-11e8-9b51-6e7dd33d8a99.png">

* Go back to Preview or the Dashboard, from the **Sidebar** right click on `foo` and click **Edit**
* Click on the **Edit** button next to the **Page URL** field and click **Ok** on the warning message
* Change the **Page URL** to `bar` then click on **Save and Close**
* Go to **Site Config** and click on **Audit**, notice the entries
<img width="1133" alt="screen shot 2018-03-28 at 3 13 00 pm" src="https://user-images.githubusercontent.com/25483966/38052174-5d7ccc62-329e-11e8-8244-77fb113c3972.png">

### Log/stack trace (use https://gist.github.com)
Here's a short clip performing the steps listed above:
https://www.useloom.com/share/b47404b500c6446daaf9de627fd1b0ae

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-9aa984
Build Number: 9aa9847493899da07648414dc44e008d3d696a95
Build Date/Time: 03-28-2018 09:44:19 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1092

**Comment by alhambrav** [comment]
Verified fixed.
