### ISSUE TITLE
[craftercms] There's an error running the restore script

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1991]
### Expected behavior
There should be no errors when running the restore script

### Actual behavior
There's an error running the restore script and the error messages are not the same for OS X and Linux.  Below are the errors seen on both OS X and Linux, for Windows, only the exception occurs:

```
Restoring deployer data
Error: Unable to access jarfile craftercms-utils.jar
```

```
Waiting for studio to start
Running sync for site mysite
Calling 'http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json' with body: { "site_id":"mysite" }
java.io.IOException: Server returned HTTP response code: 401 for URL: http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.craftercms.bundle.utils.actions.ApiPost.execute(ApiPost.java:41)
	at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
```

### Steps to reproduce the problem

**OS X**
* Using OS X, create a site using website editorial
* Backup your authoring using the backup script by running:
```
➜  crafter-authoring git:(develop) ./bin/crafter.sh backup
```
* Stop authoring then restore from the backup you created
```
➜  crafter-authoring git:(develop) ./bin/crafter.sh restore ./backups/crafter-authoring-backup.2018-03-29-11-20-53.zip
```
Notice the error message:
```
Restoring deployer data
Error: Unable to access jarfile craftercms-utils.jar
```

**Linux (Ubuntu)**
* Using OS X, create a site using website editorial
* Backup your authoring using the backup script by running:
```
➜  crafter-authoring git:(develop) ./bin/crafter.sh backup
```
* Stop authoring then restore from the backup you created
```
➜  crafter-authoring git:(develop) ./bin/crafter.sh restore ./backups/crafter-authoring-backup.2018-03-29-11-20-53.zip
```
Notice the error message:
```
Restoring deployer data
Error: Unable to access jarfile craftercms-utils.jar
```
Also notice the mysql db error (for more of the log for linux, please see gist in the Log/stack trace below)
```
Installing MariaDB/MySQL system tables in '/home/vita/temp/craftercms/crafter-authoring/data/db' ...
/home/vita/temp/craftercms/crafter-authoring/bin/dbms/bin/mysqld: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
```

***Windows***
* Using Windows, create a site using website editorial
* Backup your authoring using the backup script by running:
```
C:\temp>C:\temp\craftercms\crafter-authoring\bin\crafter.bat backup
```
* Stop authoring then restore from the backup you created
```
C:\temp>C:\temp\craftercms\crafter-authoring\bin\crafter.bat restore C:\temp\craftercms\crafter-authoring\backups\crafter-authoring-backup-2018-03-29-15-06-54.zip
```
Notice the exception after restore is completed:

```
"Waiting for studio to start"
Waiting for   0 seconds, press CTRL+C to quit ...
"Running sync for site 'mysite'"
"Restore completed"
C:\temp\craftercms\crafter-authoring\bin>Calling 'http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json' with body: { "site_id":"mysite" }
java.io.IOException: Server returned HTTP response code: 401 for URL: http://localhost:8080/studio/api/1/services/api/1/repo/sync-from-repo.json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.craftercms.bundle.utils.actions.ApiPost.execute(ApiPost.java:41)
        at org.craftercms.bundle.utils.BundleUtils.main(BundleUtils.java:46)
```

### Log/stack trace (use https://gist.github.com)
OS X Restore error:
https://gist.github.com/alhambrav/2a24e35a398ba12875e8c66f66f7d9bc

Linux Restore error:
https://gist.github.com/alhambrav/9e03ff0bf9c32f3dcf3d598b7f04884b

Windows Restore error:
https://gist.github.com/alhambrav/b02360f2f795cc0f6f0fb7dd6d3efff4

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-58b4f4
Build Number: 58b4f47f15c02dd0db9338b3f0b5503a53a66f14
Build Date/Time: 03-29-2018 14:29:53 -0400
#### OS
OS X, Linux(Ubuntu), Windows

**Comment by jdrossl** [comment]
@alhambrav I was not able to replicate the `Error: Unable to access jarfile craftercms-utils.jar` message, but the 401 exception is fixed and tested on all platforms.

**Comment by avasquez614** [comment]
@jdrossl make sure you're running the script outside `bin`, if you run it directly in `bin` it doesn't fail

**Comment by jdrossl** [comment]
@avasquez614 I did it from outside the folder too, it worked the same

**Comment by avasquez614** [comment]
Did you try it in all OS and in a clean installation from the Crafter CMS develop branch?

**Comment by jdrossl** [comment]
@avasquez614 yes all tests were clean installs, could this be some specific configuration of the environment?

**Comment by avasquez614** [comment]
No, this happened ni a RHEL server, in my Ubuntu 16.04 and in Vita's Mac. In both 3 cases there was no specific environment configuration. I'll try again right now in my machine.

**Comment by avasquez614** [comment]
@jdrossl Tried it again right now, and did exactly this:

* Cloned from craftercms develop branch.
* Started authoring.
* Created site from editorial.
* Stopped authoring
* Ran `./bin/crafter.sh backup`
* Ran `./bin/crafter.sh restore backups/crafter-authoring-backup.2018-04-02-18-58-24.zip`

Got the following errors:

```
Restoring deployer data
Error: Unable to access jarfile craftercms-utils.jar
Installing MariaDB/MySQL system tables in '/home/alfonso/code/craftercms-develop/crafter-authoring/data/db' ...
/home/alfonso/code/craftercms-develop/crafter-authoring/bin/dbms/bin/mysqld: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory

```

**Comment by avasquez614** [comment]
Please check you don't have MySQL installed in the OS you're using to test.

**Comment by jdrossl** [comment]
Issues with 401 & jar file are fixed for all platforms.

The mysql issue only happens on ubuntu but it seems to be related to specific versions, I'm testing with 16.10 and the error is not showing in the log.

@avasquez614 @sumerjabri should we investigate more about this? it seems that even with the error mysql works as expected

**Comment by avasquez614** [comment]
Yeah I would say we should investigate more, since 16.04 is the current LTS and is probably the version being used in a lot of Ubuntu servers.

**Comment by alhambrav** [comment]
@jdrossl  I tried doing a restore and it's asking me for a username and password.  I asked Alfonso, and he mentioned that we don't need to call the API to sync, and that the API call is the one asking for the username and password.  Previously, when you run the restore script, it does not ask you for a username or password.  Thanks.

**Comment by jdrossl** [comment]
@sumerjabri can you confirm if the call to sync can be removed?

**Comment by sumerjabri** [comment]
@jdrossl Sync is no longer required, Studio syncs automatically now.

**Comment by sumerjabri** [comment]
@jdrossl @avasquez614 agreed. Don't start it, ask the user to do it like this: "Restore complete, you may now start the system."

**Comment by jdrossl** [comment]
@alhambrav we need to wait for the release of our version of MariaDB4j to complete testing

**Comment by alhambrav** [comment]
Verified fixed.
