### ISSUE TITLE
[studio-ui] RTE toolbar does not appear when you tab into RTE field in the form

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1992]
### Expected behavior
RTE toolbar should appear when you tab into RTE field in the form

### Actual behavior
RTE toolbar does not appear when you tab into RTE field in the form

### Steps to reproduce the problem
* Create a site using the Empty bp
* Right click on "Home" select "New Content"
* Select "Entry" and click on "Ok"
* If the cursor is not on the first field **Page URL**, click on the field
* Fill in the **Page URL** field, then hit the <tab> key on your keyboard to move your cursor to the next field
* Fill in the field and tab to the next one until you get to the field **Body**
* Notice that when you tab into the field **Body**, which is an RTE, and start typing text, the RTE toolbar is not available at the top.  You have to use your mouse to click on the RTE, then the RTE toolbar will appear

![screen shot 2018-03-29 at 3 40 36 pm](https://user-images.githubusercontent.com/25483966/38109941-d1944ff2-3367-11e8-9001-aa50058eaff1.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/0bc14e7ce3dc41e8a1dfb1c730f0def6

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-58b4f4
Build Number: 58b4f47f15c02dd0db9338b3f0b5503a53a66f14
Build Date/Time: 03-29-2018 14:29:53 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/807

**Comment by alhambrav** [comment]
Verified fixed.
