### ISSUE TITLE
[studio] Add to audit log when a site is deleted/created

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1993]
### Expected behavior
Audit log should contain entries when creating or deleting a site
 
### Actual behavior
Audit log does not contain entries when creating or deleting a site

### Steps to reproduce the problem
* Create a site using any of the bp
* Look at the audit table in the db, notice there is no entry for when the site created in the previous step was created
* In Studio, delete the site you created
* Look at the audit table in the db, notice that there is no entry for when you deleted the site

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-58b4f4
Build Number: 58b4f47f15c02dd0db9338b3f0b5503a53a66f14
Build Date/Time: 03-29-2018 14:29:53 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
done
PR:
https://github.com/craftercms/studio/pull/1093

**Comment by alhambrav** [comment]
Verified.
