### ISSUE TITLE
[engine] Dump cache stats API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1999]
Please create an API doc spec for a new API to dump cache statistics.
Please build the API once the doc is approved.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 Ehcache offers a lot of statistics, do you think we should include all of them? http://www.ehcache.org/apidocs/2.9/net/sf/ehcache/statistics/FlatStatistics.html
Also asking for sizes in bytes can cause an out of memory exception so I think is best to keep them out.

**Comment by sumerjabri** [comment]
Let's start with:
```
cacheHitRatio
cacheHitCount
cacheMissExpiredCount
cacheMissNotFoundCount
cacheMissCount
```

The first will tell us how effective the cache is.
The second will show how busy the cache is.
The third will tell us if the cache size is too small.
The fourth will tell us if we need better cache warming techniques
The last will summarize the third & fourth and balance the second

**Comment by avasquez614** [comment]
Verified fix
