### ISSUE TITLE
[studio-ui] Cannot paste a page under a page when <content-as-folder> is set to false

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2001]
### Expected behavior
User should be able to paste a page under a page when \<content-as-folder\> is set to false

### Actual behavior
Cannot paste a page under a page when <content-as-folder> is set to false

### Steps to reproduce the problem
*  Create a site using the empty bp
* Click on **Site Config -> Content Types -> Open Existing Type**, then select **Page - Article**
* In the **Properties Explorer**, go to **Configuration**, click on the pencil next to `config.xml` to edit, then edit the <content-as-folder> value to **false**
```
<content-as-folder>false</content-as-folder>
```

* Save your changes and go back to the **Sidebar**
* Create two new **Entry** page named 'foo' and `bar` 
* Right click on `bar` and select **Cut**
* Right click on `foo` and paste, notice there's no **Paste** option when you right click on page `foo`
![screen shot 2018-03-30 at 10 37 55 am](https://user-images.githubusercontent.com/25483966/38141545-9af37258-3406-11e8-9e0e-8b652b623592.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/c579b351bd2a41afb7b42f1ddafb70f4

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-1dcd84
Build Number: 1dcd84d219ac76efe13cbcfda0ccf19f55ef032a
Build Date/Time: 03-30-2018 10:28:03 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by alhambrav** [comment]
Russ will verify if this feature is still valid.

**Comment by russdanner** [comment]
You should be able to paste one page under another.

Verified this still does not work.

<img width="340" alt="screen shot 2018-05-10 at 1 09 55 am" src="https://user-images.githubusercontent.com/169432/39853270-32605144-53ef-11e8-9461-672783e4de10.png">

**Comment by yacdaniel** [comment]
Verified fixed.
