### ISSUE TITLE
[studio] Images copied into the static assets/page/images are not displayed correctly (extension lost) and the folders are not displayed as folders when the user copy a tree with content with specific and shared components (uploaded image)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2003]
### Expected behavior
The copied content should generates some folders with the name of the image of below, and into each folder the test image should be displayed correctly.

### Actual behavior
The image created for the copy is not a jpg anymore and the respective folder are not displayed as folder, see the next image:
<img width="511" alt="screen shot 2018-04-02 at 9 32 24 am" src="https://user-images.githubusercontent.com/16946208/38205297-5970fe9a-3663-11e8-9b32-21516ae5c317.png">

Watch the next video:
https://www.useloom.com/share/a923aaae8fbb4c4c946cd5cc66fca390

### Steps to reproduce the problem
* Site using Editorial BP
* Create content with specific components:
Create a new article page under folder article/2017/3, make sure to upload an image from your desktop, then save your changes
* Copy articles/2017 and paste it under article/2016
* Paste again under the newly pasted folder
* Paste again under the next newly pasted folder
* Keep pasting on the next newly pasted folder until you've done it at least 10 times
* Expand the next tree: Static Assets/static-assets/page/images, and check the content into it.

### Log/stack trace (use https://gist.github.com)
No log errors.

#### Version
Studio Version Number: 3.0.10-SNAPSHOT-5e94a3
Build Number: 5e94a3af9909399675da09b7f3c98869aabfbbd3
Build Date/Time: 04-02-2018 07:16:04 -0600
#### OS
Mac OSx & Windows10
#### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1091

**Comment by luishernandezmonge** [comment]
Verified as fixed.
