### ISSUE TITLE
[test-suite] Automate Cut Paste to folder (page.xml move to folder)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2005]
Please automate Cut Paste to folder (page.xml move to folder)  ID 27 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Entry" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag \<content-as-folder\> to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "Home" and select "New Folder", name the folder "a-folder"
13) Right click on "Home" and select "New Content"
14) Select "Entry" and click on the "Ok" button in the "Choose Content Type" screen
15) Put "foo" in the "Page URL" field
16) Put "foo" in the "File Title" field
17) Fill in the rest of the required fields in the form and save your changes

Here's how your dashboard **My Recent Activity** will look like after creating the new content:
<img width="834" alt="screen shot 2018-04-03 at 10 27 41 am" src="https://user-images.githubusercontent.com/25483966/38255411-b9eea5d0-3729-11e8-82fa-5f456d17b845.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Cut"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard

**Expected Output**
5) "foo" should now be located under "a-folder" in the "Sidebar" site tree
```
    Home
    a-folder
      foo
```
Here's a screenshot of the Sidebar:
<img width="171" alt="screen shot 2018-04-03 at 10 48 20 am" src="https://user-images.githubusercontent.com/25483966/38256551-9020d13a-372c-11e8-9964-bb53f1539f64.png">

6) The "My Recent Activity" widget should contain the following:
    Item Name: foo    Edit: Edit    URL: /a-folder/foo.xml

Here's how your dashboard **My Recent Activity** will look like after the cut and paste:
<img width="827" alt="screen shot 2018-04-03 at 10 46 43 am" src="https://user-images.githubusercontent.com/25483966/38256473-5b753912-372c-11e8-90b6-22f92aec761c.png">

Here's a short clip of the test performed manually:
https://www.useloom.com/share/66c78f2414db4347aa6c0272dceb0161

Please modify the steps as necessary to accommodate automated test development (this is mostly the gist of what needs to be tested).

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Added to testing.xml test suite in the next PR: https://github.com/craftercms/test-suite/pull/327

**Comment by alhambrav** [comment]
Verified.
