### ISSUE TITLE
[studio] Pull from remote and push to remote api calls should be in the audit log

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2014]
### Expected behavior
Pull from remote and push to remote api calls should be in the audit log

### Actual behavior
Pull from remote and push to remote api calls are not logged in the audit log

### Steps to reproduce the problem
* Push content to remote using push to remote api call
* Pull content from remote using pull from remote api call
* Look at the audit log, there's no entry for either the push or pull api calls

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-ee06c1
Build Number: ee06c19f542b04366806a57f5988f536ef2f9bf4
Build Date/Time: 04-05-2018 10:11:11 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1099

**Comment by alhambrav** [comment]
Verified fixed.
