### ISSUE TITLE
[test-suite] Automate Copy Paste to folder (page.xml copy to folder)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2015]
Please automate Copy Paste to folder (page.xml move to folder) ID 29 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Entry" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "Home" and select "New Folder", name the folder "a-folder"
13) Right click on "Home" and select "New Content"
14) Select "Entry" and click on the "Ok" button in the "Choose Content Type" screen
15) Put "foo" in the "Page URL" field
16) Put "foo" in the "File Title" field
17) Fill in the rest of the required fields in the form and save your changes

Here's how your dashboard **My Recent Activity** will look like after creating the new content:
<img width="753" alt="screen shot 2018-04-05 at 10 42 45 am" src="https://user-images.githubusercontent.com/25483966/38373021-310087c0-38be-11e8-8f6f-f4fe86b4a399.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Copy"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard

**Expected Output**
5) "a-folder" should contain "foo" in the "Sidebar" site tree and should look something like this:
```
    Home
    foo
    a-folder
       foo
```
Here's a screenshot of the Sidebar:
<img width="176" alt="screen shot 2018-04-05 at 10 18 00 am" src="https://user-images.githubusercontent.com/25483966/38371573-c581734a-38ba-11e8-8b19-df6ec2a959b6.png">

6) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /a-folder/foo.xml
    Item Name: foo    Edit: Edit    URL: /foo.xml
```

Here's how your dashboard My Recent Activity will look like after the copy and paste:
<img width="751" alt="screen shot 2018-04-05 at 10 18 18 am" src="https://user-images.githubusercontent.com/25483966/38371599-d9a803ac-38ba-11e8-80b5-2b93c8dae05b.png">

Here's a short clip of the test performed manually:
https://www.useloom.com/share/7a85d83a755b4681a30c8584ea353f1c

Please modify the steps as necessary to accommodate automated test development (this is mostly the gist of what needs to be tested).

**Comment by luishernandezmonge** [comment]
@alhambrav Done, ready to check this.

**Comment by alhambrav** [comment]
Verified.
