### ISSUE TITLE
[deployer] Add support for a git push processor

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2017]
Please add a new processor that can push to a remote git repo. The idea is that the deployer can then propagate the deployed content to remote repos.

**Comment by marosivanco** [comment]
Implemented the GitPushProcessor, but i am unable to push. Do I need any rights to push a feature branch?

**Comment by sumerjabri** [comment]
@marosivanco send us a pull-request with the code and we'll review/merge. Please review these docs before you send the PR:
https://github.com/craftercms/craftercms/blob/master/CODE_OF_CONDUCT.md
https://github.com/craftercms/craftercms/blob/master/CONTRIBUTING.md
https://github.com/craftercms/craftercms/blob/master/GIT_WORKFLOW.md

You'll need to fork the repository:
https://github.com/craftercms/deployer

The code should live along with the other processors:
https://github.com/craftercms/deployer/tree/master/src/main/java/org/craftercms/deployer/impl/processors

Thank you for contributing!

**Comment by marosivanco** [comment]
Permission denied. Any idea?:

    > git push --set-upstream origin feature/2017
    ERROR: Permission to craftercms/deployer.git denied to marosivanco.
    fatal: Could not read from remote repository.

    > git remote -v
    origin  ssh://git@github.com/craftercms/deployer.git (fetch)
    origin  ssh://git@github.com/craftercms/deployer.git (push)

**Comment by cortiz** [comment]
Yes, you don’t have permissions to write into craftercms/deployer , you need to fork it, then push your branch and the do the pull request as explain by Sumer

**Comment by sumerjabri** [comment]
Completed: https://github.com/craftercms/deployer/blob/master/src/main/java/org/craftercms/deployer/impl/processors/GitPushProcessor.java
