### ISSUE TITLE
[studio] list-remote api call returns empty "push_url" 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2018]
### Expected behavior
list-remote api call should not return an empty "push_url"
 
### Actual behavior
list-remote api call returns empty "push_url" 

### Steps to reproduce the problem
* Create a bare git repo, create a site in Studio
* Add remote using the add-remote api call
* List the remote using the list-remote api call ( I am using the Chrome browser app ARC to send the api calls) Notice the `push_url` in the response is empty:
```
200 OK  6.70 ms
{
"remotes": [
  {
"name": "origin",
"url": "ssh://vita.alhambra@localhost/Users/vita.alhambra/temp/repo/test_repo.git",
"fetch": "+refs/heads/*:refs/remotes/origin/*",
"push_url": ""
}
],
"message": "OK"
}
```
* From the command line, clone the remote repo and list the remotes, notice the output for `push_url` is not empty:
```
➜  tmp git:(master) git remote show origin
* remote origin
  Fetch URL: ssh://vita.alhambra@localhost/Users/vita.alhambra/temp/repo/test_repo.git
  Push  URL: ssh://vita.alhambra@localhost/Users/vita.alhambra/temp/repo/test_repo.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-ee06c1
Build Number: ee06c19f542b04366806a57f5988f536ef2f9bf4
Build Date/Time: 04-05-2018 10:11:11 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1095

**Comment by alhambrav** [comment]
Verified fixed.
