### ISSUE TITLE
[studio-ui] Escape key should trigger cancel form actions

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#2025]
### Expected behavior
Pressing escape when viewing any form in studio should be equivalent of hitting the "cancel" button

### Actual behavior
Nothing happens

### Steps to reproduce the problem
* Open a form - edit a script
* Press escape
* Lament missed expectation

#### Version 
3.0

#### OS
mac

#### Browser 
chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/809

**Comment by sumerjabri** [comment]
@luishernandezmonge please validate and close/reopen.

**Comment by luishernandezmonge** [comment]
Already performed checking and test on some of the studio dialogs, find bellow the results:
-CreateSite dialog Ok
-NewUser dialog Ok
-DeleteUser dialog Ok
**-DeleteSite dialog (confirmation) No Esc action**
-EditForm Ok
**-Normal Upload dialog No Esc action**
-History dialog Ok
-Create Folder dialog Ok
-Delete dialog Ok
**-Rename Folder dialog No Esc action**
-Dependencies dialog Ok
-Bulk upload dialog Ok
**-Change Template Warning No Esc action**
**-View Form No Esc action**
-Schedule dialog Ok
-Approve & Publish dialog Ok
-Targeting dialog Ok
-Edit template Ok
-Edit Controller Ok
**-Workflow Cancellation dialog No Esc action**
-Create Content Select Content type dialog Ok
-Create Form Ok
-Create Controller dialog Ok
-Create Controller Code dialog Ok
**-Create Template No Esc action on just displayed dialog**
-Create Template Code dialog Ok
-Publish status dialog Ok
-Site Config/Content types Open Existing/Choose Content type dialog Ok
**-Site Config/Content types Create New type dialog No Esc action**
-Site Config/Groups New Group dialog Ok
-Site Config/Groups Delete Group dialog Ok
-Site Config/Audit Ok
-Site Config/Publishing/Bulk Publish Warning dialog Ok
-Site Config/Publishing/Bulk Publish Notification Ok
-Site Config/Remote Repos/New Repo Ok
-Site Config/Remote Repos/Delete Repo Ok

Please, notice that in some of the dialogs of above when does not have ESCAPE action, please check those. @jvega190

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/812

**Comment by luishernandezmonge** [comment]
Verified as implemented
