### ISSUE TITLE
[studio-ui] Confirmation dialog box for "delete" item is awkward

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#2026]
### Expected behavior
A confirmation box with more user-friendly content. For example:
Selection Deleted
The selection is being deleted and will disappear shortly.
OK
### Actual behavior
Submittal Complete
Item(s) has been pushed for delete. It will be deleted shortly.
OK
### Steps to reproduce the problem
* Create an item
* Delete the item
* Observe awkward yet perfectly accurate confirmation box. This extreme precision is basically confusing and unimportant for business users. You can document what's actually going on behind the scenes, but be more user-friendly (and grammatically correct) in the default behaviour. A smaller dialog box would look better too. Enter key listener for the OK button would be even better.

#### Version
3.0
#### OS
Mac
#### Browser
Chrome

**Comment by russdanner** [comment]
Agree: Please use the following language:
```
Selection Deleted
The selection is being deleted and will disappear shortly.
```

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/813

**Comment by luishernandezmonge** [comment]
Verified as implemented.
