### ISSUE TITLE
[test-suite] Automate Copy Paste to folder with Collision and Duplicate

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2028]
Please automate Copy Paste to folder with Collision and Duplicate (page.xml copy to folder with existing object with the same name) ID 31 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Entry" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "Home" and select "New Folder", name the folder "a-folder"
13) Right click on "Home" and select "New Content"
14) Select "Entry" and click on the "Ok" button in the "Choose Content Type" screen
15) Put "foo" in the "Page URL" field
16) Put "foo" in the "File Title" field
17) Fill in the rest of the required fields in the form and save your changes
18) Right click on "foo" and select "Copy"
19) Right click on "a-folder" and select Paste, you should have the following tree:
```
        Home
        foo
        a-folder
            foo
```
<img width="188" alt="screen shot 2018-04-09 at 9 16 09 am" src="https://user-images.githubusercontent.com/25483966/38499878-e2d7c2ae-3bd6-11e8-8340-b94583bdb031.png">

Here's how the dashboard for "My Recent Activity should look like:
<img width="842" alt="screen shot 2018-04-09 at 9 17 13 am" src="https://user-images.githubusercontent.com/25483966/38499915-001e03be-3bd7-11e8-8bd1-3338065ddf5a.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Copy"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard

**Expected Output**
5) "a-folder" should contain "foo{some-random-chars}" in the "Sidebar" site tree and should look something like this:
```
    Home
    foo
    a-folder
      foo
      foo {some-random-chars}
```
<img width="208" alt="screen shot 2018-04-09 at 9 17 56 am" src="https://user-images.githubusercontent.com/25483966/38499976-1ee66502-3bd7-11e8-8fbf-4c738e8999c0.png">

6) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo {some-random-chars}    URL: /a-folder/foo {some-random-chars}.xml
    Item Name: foo    Edit: Edit          URL: /a-folder/foo.xml
    Item Name: foo    Edit: Edit          URL: /foo.xml
```
<img width="840" alt="screen shot 2018-04-09 at 9 18 27 am" src="https://user-images.githubusercontent.com/25483966/38499991-2ab92fc2-3bd7-11e8-9468-7bfa2bb0788e.png">

Please modify the steps as necessary to accommodate automated test development (this is mostly the gist of what needs to be tested).

**Comment by luishernandezmonge** [comment]
@alhambrav Done, Please validate this.
