### ISSUE TITLE
[studio-api] Can't create site from remote repo on linux with ssh key

### ISSUE THREAD

**Issue by signo-** [craftercms/craftercms#2029]
### Expected behavior
According to [Create Site API](http://docs.craftercms.org/en/3.0/developers/projects/studio/api/site/create-site.html) I should be able to create a new site based off a remote repository using a curl request.

### Actual behavior
Linux:
Running the reproduction steps I am unable to create a site. The following error message is what I get instead: `{"message":"Remote repository not found"}`
    
Site creation works fine via username/password with HTTPS url and git repository can be cloned without any issue using ssh url.

MacOS:
    The reproduction steps allow me to create a site via ssh. It should be noted however that site creation works even if remote_private_key is omitted. It looks like when run locally it is using the systems ssh key (Which isn't an issue per say, just probably worth noting in the docs)

### Steps to reproduce the problem
* Start crafterCMS locally on port 8080
* Run the following command to get a JSESSIONID
```
JSESSIONID="$(curl \                                                                                                                                                                         
    -d '{"username":"admin","password":"admin"}' \
    --cookie "XSRF-TOKEN=A_VALUE" \
    --header "X-XSRF-TOKEN:A_VALUE" \
    --header "Content-Type: application/json" \
    -v -X POST http://localhost:8080/studio/api/1/services/api/1/security/login.json \
    2>&1 | sed -n "s/^.*JSESSIONID=\s*\([a-zA-Z0-9]*\).*$/\1/p")"

```
* Run the following command to create a new site based off a git repo. Update/replace the env vars to match local setup.
```
curl -X POST   http://localhost:8080/studio/api/1/services/api/1/site/create.json   --cookie "JSESSIONID=$JSESSIONID; path=/; domain=localhost; HttpOnly; XSRF-TOKEN=A_VALUE;"   -H 'Cache-Control: no-cache'   -H 'Content-Type: application/json'   -H 'X-XSRF-TOKEN: A_VALUE'   -d '{
        "use_remote":true,
        "remote_name":"origin",
        "remote_url":"$REMOTE_URL_SSH",                                                         
        "authentication_type":"key",
        "create_option":"clone",
        "site_id":"setkey",
        "remote_private_key":"$SOME_KEY"}'
```

### Log/stack trace (use https://gist.github.com)
None that I have found. If there's a file you need the output of let me know.

#### Version
Same version for both mac and linux tests. Only difference was mac version was downloaded from website for mac test and linux version was downloaded for linux test.

```
Studio Version Number: 3.0.8-cc7614

Build Number: cc7614f44b7700abe6a4618fbeaa359212228033

Build Date/Time: 02-20-2018 11:20:42 -0500

```
#### OS
Linux
#### Browser
N/A

**Comment by signo-** [comment]
If you need any other testing or information on the issue let me know!

**Comment by sumerjabri** [comment]
@signo- You need to use 3.0.10 onwards for that API to work (see issue https://github.com/craftercms/craftercms/issues/1857)

To download 3.0.10: http://craftercms.org/downloads

Or you can build from source if you prefer.

**Comment by signo-** [comment]
@sumerjabri, Thanks for the info, don't know how I missed that bug! We ran these tests last week so it looks like we did it just before that build was released...
