### ISSUE TITLE
[crafter-cms] Provide a file permission approach that is consistently applied and configured across all components of Crafter CMS

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2032]
### Expected behavior
Provide a consistent approach and configuration for files written by Crafter components (Studio, Solr, Deployer etc) with sensible defaults

### Actual behavior
Today each component defines the filesystem level permissions its files are written with.  Some components write slightly different permissions for files with similar purposes.
* Deployer are all 644 
* Tomcat they are 640
* Delivery content is  755

**Comment by jdrossl** [comment]
@russdanner @sumerjabri the permissions of the files created by the JVM by default will follow the system `umask` setting (in mac its `022`), Tomcat was setting a different value so after the PR all files should have the same permissions. If you think its better to define our own value let me know what it should be and I can add it to all startup scripts.

**Comment by russdanner** [comment]
Confirmed
