### ISSUE TITLE
[test-suite] Automate Cut Paste to folder (page move to folder)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2035]
Please automate Cut Paste to folder (page move to folder)  ID 34 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Right click on "Home" and select "New Folder", name the folder "a-folder"
3) Right click on "Home" and select "New Content"
4) From the "Choose Content Type" screen, select "Entry"
5) Put "foo" in the "Page URL" field
6) Put "foo" in the "File Title" field
7) Fill in the rest of the required fields in the form and save your changes

<img width="971" alt="screen shot 2018-04-10 at 2 19 50 pm" src="https://user-images.githubusercontent.com/25483966/38575791-46f62840-3cca-11e8-877e-d37fe2338f28.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Cut"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard, make sure that `All` is selected in the `My Recent Activity` widget

**Expected Output**
5) "a-folder" should contain "foo" in the "Sidebar" site tree and should look something like this:
```
    Home
    a-folder
      foo
```

6) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /a-folder/foo
    Item Name: foo    Edit:         URL: /site/website/foo
    Item Name: foo    Edit: Edit    URL: /foo     
```

<img width="975" alt="screen shot 2018-04-10 at 2 20 45 pm" src="https://user-images.githubusercontent.com/25483966/38575845-62c1d4ac-3cca-11e8-896a-3bea691f44d9.png">

Please modify the steps as necessary to accommodate automated test development (this is mostly the gist of what needs to be tested).

**Comment by luishernandezmonge** [comment]
Start working on this

**Comment by luishernandezmonge** [comment]
@alhambrav Done, Please check.

**Comment by alhambrav** [comment]
Verified.
