### ISSUE TITLE
[test-suite] Automate Copy paste to folder (page copy to folder)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2037]
Please automate Copy paste to folder (page copy to folder) ID 34 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Right click on "Home" and select "New Folder", name the folder "a-folder"
3) Right click on "Home" and select "New Content"
4) From the "Choose Content Type" screen, select "Entry"
5) Put "foo" in the "Page URL" field
6) Put "foo" in the "File Title" field
7) Fill in the rest of the required fields in the form and save your changes
<img width="664" alt="screen shot 2018-04-11 at 7 50 16 am" src="https://user-images.githubusercontent.com/25483966/38615066-63334fae-3d5d-11e8-8078-99f607a15e02.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo"
4) Right click on "foo" and select "Copy"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard, make sure in the `My Recent Activity` widget that `All` is selected

**Expected Output**
5) "a-folder" should contain "foo" in the "Sidebar" site tree and should look something like this:
```
    Home
    foo
    a-folder
        foo
```

6) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /a-folder/foo
    Item Name: foo    Edit: Edit    URL: /foo       
```
<img width="665" alt="screen shot 2018-04-11 at 7 53 35 am" src="https://user-images.githubusercontent.com/25483966/38615118-88ae43f6-3d5d-11e8-88d1-19dd476516d0.png">

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, PR: https://github.com/craftercms/test-suite/pull/334

**Comment by alhambrav** [comment]
Verified.
