### ISSUE TITLE
[test-suite] Automate Copy Paste to folder with Collision and Duplicate (ID 38)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2038]
Please automate Copy Paste to folder with Collision and Duplicate (page copy to folder with existing object with the same name)  ID 38 in **Studio -> Content**.

**Setup**
1) Create a site using Empty BP
2) Right click on "Home" and select "New Content"
3) Select "Entry" and click on the "Ok" button in the "Choose Content Type" screen
4) Put "foo" in the "Page URL" field
5) Put "foo" in the "File Title" field
6) Fill in the rest of the required fields in the form and save your changes
7) Right click on "Home" and select "New Folder", name the folder "a-folder"
8) Right click on "foo" and select "Copy"
9) Right click on "a-folder" and select "Paste" you should have the following tree:
```
   Home
   foo
   a-folder
      foo  
```
<img width="888" alt="screen shot 2018-04-11 at 10 06 00 am" src="https://user-images.githubusercontent.com/25483966/38622535-61977ed6-3d71-11e8-8c25-d97b81d660de.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "foo" ("foo" on the same level as "Home")
4) Right click on "foo" and select "Copy"
5) Right click on "a-folder" and select "Paste"
6) Click on the Dashboard, make sure in the `My Recent Activity` widget that `All` is selected

**Expected Output**
5) "a-folder" should contain "foo {some-random-chars}" in the "Sidebar" site tree and should look something like this:
```
    Home
    foo
    a-folder
       foo
       foo {some-random-chars}
```
<img width="180" alt="screen shot 2018-04-11 at 11 02 21 am" src="https://user-images.githubusercontent.com/25483966/38625158-d91d1de8-3d77-11e8-8f98-33e5626fb567.png">

6) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo {some-random-chars}   Edit: Edit     URL: /a-folder/foo-{some-random-chars}
    Item Name: foo                                         Edit: Edit     URL: /a-folder/foo
    Item Name: foo                                         Edit: Edit     URL: /foo
```
<img width="889" alt="screen shot 2018-04-11 at 10 30 18 am" src="https://user-images.githubusercontent.com/25483966/38623323-60ae0204-3d73-11e8-8989-bf1b5b449ee4.png">

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by alhambrav** [comment]
Verified.
