### ISSUE TITLE
[test-suite] Automate file rename then publish (file.xml->rename->publish)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2043]
Please automate file rename then publish (file.xml->rename->publish) ID 40 in **Studio -> Content**.

**Setup**
1) Create a site using Editorial BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Page - Article" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "articles/2016/12" and select "New Content"
13) Select "Page - Article" and click on the "Ok" button in the "Choose Content Type" screen
14) Put "foo" in the "Page URL" field
15) Put "foo" in the "Internal Name" and "Title" field
16) For "Categories", select "Entertainment"
17) Upload an image in the "Image" field
18) Fill in the rest of the required fields in the form and save your changes
19) From the Sidebar, navigate to "articles/2016/12/foo"
20) Right click on "foo" and select "Approve & Publish"
21) Select "Items should go live now" in the "Selected Item Scheduling" field then click on "Submit"
22) Setup your site for delivery by running the init-site script

Here's how your "My Recent Activity" widget should look like after completing the setup steps:
<img width="986" alt="screen shot 2018-04-16 at 9 42 51 am" src="https://user-images.githubusercontent.com/25483966/38813079-03b4f688-415c-11e8-8d7b-e90af5dece87.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "articles/2016/12/foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard
11) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Approve & Publish"
12) Select "Items should go live now" then click on "Submit"
13) Wait for a minute or so to make sure publishing is done
14) In your browser, go to "localhost:9080?crafterSite=siteName", where `siteName` is the name given on the site we're working on and then click on "Entertainment" from the left-rail
15) Click on the article "foo"

**Expected Output**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Preview or Dashboard)
9) The URL should contain "page=/articles/2016/12/bar.htm"
10) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: bar.xml
```
<img width="988" alt="screen shot 2018-04-16 at 9 44 41 am" src="https://user-images.githubusercontent.com/25483966/38813122-2907b2f4-415c-11e8-807d-2ec7edb4adee.png">

11) The "Approve for Publish" dialog should open
12) The "Approve for Publish" dialog should close
13) In your dashboard, the "Recently Published" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /bar.xml
```
<img width="992" alt="screen shot 2018-04-16 at 9 47 48 am" src="https://user-images.githubusercontent.com/25483966/38813140-34246a92-415c-11e8-8142-cd4f28c27329.png">

15) The page just published should be viewable on the delivery side, with the url `http://localhost:9080/articles/2016/12/bar.html`

**Comment by luishernandezmonge** [comment]
@alhambrav Done, ready to check.

**Comment by alhambrav** [comment]
Verified.
