### ISSUE TITLE
[studio-ui] Make "Item Name" and "Last Edited By" non-clickable in dashboard widgets "My Recent Activity" and "Items Waiting For Approval"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2045]
### Expected behavior
**Item Name** and **Last Edited By** in dashboard widgets should not be clickable (Should not be able to sort)
 
### Actual behavior
**Item Name** and **Last Edited By** in dashboard widgets are clickable but does not seem to be helpful/working, so, it would be nice to make it non-clickable in the dashboard widgets. 

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a new article page
* View the dashboard, please make **Item Name** and **Last Edited By** in the widgets ("My Recent Activity" and "Items Waiting For Approval") non-clickable

![screen shot 2018-04-16 at 3 47 04 pm copy](https://user-images.githubusercontent.com/25483966/38831767-6913fd4e-418e-11e8-81a3-bab372ac3f74.png)

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-c60600
Build Number: c606005796a3600f65984d389b81fbcc8c2a9793
Build Date/Time: 04-16-2018 14:30:02 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Pr: https://github.com/craftercms/studio-ui/pull/815

**Comment by alhambrav** [comment]
Verified fixed.
