### ISSUE TITLE
[test-suite] Automate file rename then publish (page->rename->publish)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2046]
Please automate file rename then publish (page->rename->publish) ID 41 in **Studio -> Content**.

**Setup**
1) Create a site using Editorial BP
2) Open the Sidebar if it's not yet open
3) Expand "Pages"
4) Right click on "articles/2016/12" and select "New Content"
5) Select "Page - Article" and click on the "Ok" button in the "Choose Content Type" screen
6) Put "foo" in the "Page URL" field
7) Put "foo" in the "Internal Name" and "Title" field
8) For "Categories", select "Entertainment"
9) Upload an image in the "Image" field
10) Fill in the rest of the required fields in the form and save your changes
11) From the Sidebar, navigate to "articles/2016/12/foo"
12) Right click on "foo" and select "Approve & Publish"
13) Select "Items should go live now" in the "Selected Item Scheduling" field then click on "Submit"
14) Setup your site for delivery by running the init-site script
<img width="990" alt="screen shot 2018-04-17 at 9 26 12 am" src="https://user-images.githubusercontent.com/25483966/38873163-1f1289d2-4223-11e8-8d22-c2e54bf13824.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "articles/2016/12/foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard
11) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Approve & Publish"
12) Select "Items should go live now" then click on "Submit"
13) Wait for a minute or so to make sure publishing is done
14) In your browser, go to `localhost:9080?crafterSite=siteName`, where `siteName` is the name given on the site we're working on and then click on "Entertainment" from the left-rail
15) Click on the article "foo"

**Expected Output**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Preview or Dashboard)
9) The URL should contain "page=/articles/2016/12/bar"
10) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /articles/2016/12/bar
```
<img width="990" alt="screen shot 2018-04-17 at 9 27 14 am" src="https://user-images.githubusercontent.com/25483966/38873267-57b42c46-4223-11e8-945b-7584842b8d78.png">

11) The "Approve for Publish" dialog should open
12) The "Approve for Publish" dialog should close
13) In your dashboard, the "Recently Published" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /articles/2016/12/bar
```
<img width="995" alt="screen shot 2018-04-17 at 9 36 54 am" src="https://user-images.githubusercontent.com/25483966/38873386-a454f54e-4223-11e8-9387-c38739daf11c.png">

15) The page just published should be viewable on the delivery side, with the url 
```
http://localhost:9080/articles/2016/12/bar
```

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, PR: https://github.com/craftercms/test-suite/pull/338

**Comment by alhambrav** [comment]
Verified.
