### ISSUE TITLE
[studio] No log in tomcat when you get an error pushing to remote in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2047]
### Expected behavior
Error messages should be logged in tomcat when there is an error when push to remote is sent from Studio

### Actual behavior
There are no error messages in the tomcat when there is an error in Studio sending a push to remote.  Log level for push to remote for errors seems incorrect.

### Steps to reproduce the problem
* Create a remote repo in github
* In Studio, create a site based on a remote git repository
* Edit the Home page and save your changes.
* Go to **Site Config** and click on **Remote Repositories**
* Click on the **Push** icon to push to remote your changes, notice the error message displayed by Studio
![screen shot 2018-04-17 at 11 40 32 am](https://user-images.githubusercontent.com/25483966/38880629-2d0967d4-4234-11e8-8a71-bdf5f8d39f74.png)

* Look in your tomcat log, there are no error messages about the error displayed by Studio, it would be nice to see the error log here when there's an error pushing to remote

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-c60600
Build Number: c606005796a3600f65984d389b81fbcc8c2a9793
Build Date/Time: 04-16-2018 16:14:59 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1098

**Comment by alhambrav** [comment]
Verified fixed.
