### ISSUE TITLE
[studio-ui] Push to remote and pull from remote does not seem to be working from Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2048]
### Expected behavior
User should be able to push to remote or pull from remote from Studio

### Actual behavior
There are errors when doing a push to remote or pull from remote from Studio UI (**Site Config** -> **Remote Repositories**

### Steps to reproduce the problem
* Create a remote repo in github 
* In Studio, create a site based on a remote git repository
* Edit the Home page and save your changes.
* Go to Site Config and click on Remote Repositories
* Click on the Push icon to push to remote your changes, notice the error message displayed by Studio. (Note there's no log in tomcat, ticket already filed for that) 
![screen shot 2018-04-17 at 11 40 32 am](https://user-images.githubusercontent.com/25483966/38888643-52e4b7ae-424a-11e8-906a-7171409e5b86.png)

* Click on the Pull icon to pull from remote, notice the error message on Studio and look at the tomcat log 
![screen shot 2018-04-17 at 2 19 59 pm](https://user-images.githubusercontent.com/25483966/38888685-713c8420-424a-11e8-9bd1-ce7117be24dd.png)

Please note that from the command line, push and pull works fine.

### Log/stack trace (use https://gist.github.com)
Here's the tomcat log when the Pull icon is clicked from Studio:
https://gist.github.com/alhambrav/fe87b93f27f4e97eb9b010e05ee98583

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-c60600
Build Number: c606005796a3600f65984d389b81fbcc8c2a9793
Build Date/Time: 04-16-2018 16:14:59 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
This is not backend issue. 
The actual issue is caused by UI sending repository URL instead of a branch name. By default, repository URL is populated when clicking on push or pull icon. If a user does not change value, the issue is reproduced.

**Comment by alhambrav** [comment]
Updated label to [studio-ui] from [studio].

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/816

**Comment by alhambrav** [comment]
@vestrada I am still getting the errors.  Here's a short clip of a site created based on a remote git repository and then performing a push and pull:
https://www.useloom.com/share/0e3f75e8893e466f8d0ebd18a68dff3e

Here's the error screen I get when I click on `Pull`:
![screen shot 2018-04-23 at 11 05 20 am](https://user-images.githubusercontent.com/25483966/39135125-3f19098c-46e6-11e8-93c5-6beb84bdf705.png)

Here's the error log for the pull error:
https://gist.github.com/alhambrav/c0875703a29683d2073e0b67aaeb52e4

Here's the error screen I get when I click on `Push`:
![screen shot 2018-04-23 at 11 07 29 am](https://user-images.githubusercontent.com/25483966/39135258-8fb5646c-46e6-11e8-8502-a6c8b8c0ff2e.png)

Here's the error log for the pull error:
https://gist.github.com/alhambrav/23e313eae932c20a90816c217efcc147


Studio Version Number: 3.0.11-SNAPSHOT-4d7b74
Build Number: 4d7b745911f0f8a03d4f397666519bde25535c6a
Build Date/Time: 04-23-2018 10:59:22 -0400

**Comment by vestrada** [comment]
Per conversation with @dejan-brkic , the user must type the branch into the input, UI doesn't has the information to know where the user want to pull or push.

**Comment by dejan-brkic** [comment]
Added remote branch to db metadata 

PR:
https://github.com/craftercms/studio/pull/1104

**Comment by dejan-brkic** [comment]
BE updates done
PR:
https://github.com/craftercms/studio/pull/1108

**Comment by sumerjabri** [comment]
@vestrada 

- we need the create dialog to request an optional `branch`
- pushing/pulling will show a dialog that holds the available `branches` based on http://docs.craftercms.org/en/3.0/developers/projects/studio/api/repo/list-remote.html as a dropdown of possible branches

Ping me if you have questions.

**Comment by vestrada** [comment]
Hi!
- remote_branch and single_branch was added to create site.
- pushing/pulling is showing a dialog that holds the available branches.

PR: https://github.com/craftercms/studio-ui/pull/829

**Comment by sumerjabri** [comment]
@vestrada please use the words: ```Branch defaults to 'master' when blank```

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/834

**Comment by alhambrav** [comment]
Verified.
