### ISSUE TITLE
[test-suite] Automate file rename, rename again then publish (file.xml->rename->rename->publish)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2049]
Please automate file rename, rename again then publish (file.xml->rename->rename->publish) ID 42 in **Studio -> Content**.

**Setup**
1) Create a site using Editorial BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Page - Article" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "articles/2016/12" and select "New Content"
13) Select "Page - Article" and click on the "Ok" button in the "Choose Content Type" screen
14) Put "foo" in the "Page URL" field
15) Put "foo" in the "Internal Name" and "Title" field
16) For "Categories", select "Entertainment"
17) Upload an image in the "Image" field
18) Fill in the rest of the required fields in the form and save your changes
19) From the Sidebar, navigate to "articles/2016/12/foo"
20) Right click on "foo" and select "Approve & Publish"
21) Select "Items should go live now" in the "Selected Item Scheduling" field then click on "Submit"
22) Setup your site for delivery by running the init-site script

Here's how your dashboard "My Recent Activity" widget should look like at this point:
<img width="969" alt="screen shot 2018-04-19 at 11 57 11 am" src="https://user-images.githubusercontent.com/25483966/39003448-e2e3030e-43c8-11e8-9297-079849dfd899.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "articles/2016/12/foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard
11) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Edit"
12) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
13) Click "Ok" on the Warning message
14) Change the "Page URL" from "bar" to "baz"
15) Click on the "Save and Close" 
16) From the Sidebar, click on the page "foo" to preview
17) Click on the Dashboard 
18) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Approve & Publish"
19) Select "Items should go live now" then click on "Submit"
20) Wait for a minute or so to make sure publishing is done, click on the dashboard
21) In your browser, go to "localhost:9080?crafterSite=siteName", where `siteName` is the name given on the site we're working on and then click on "Entertainment" from the left-rail
22) Click on the article "foo"

**Expected Output**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Preview or Dashboard)
9) The URL should contain "page=/articles/2016/12/bar.html"
10) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/bar.xml
    Item Name: foo.xml  Edit: Edit    URL: /articles/2016/12/foo.html  
```
<img width="976" alt="screen shot 2018-04-19 at 12 00 21 pm" src="https://user-images.githubusercontent.com/25483966/39003661-4829e480-43c9-11e8-9104-6a9934daaed6.png">

11) Form for editing page "foo" should open
12) A warning message should appear after clicking on "Edit"
13) The "Page URL" field should now be editable and not grayed out
15) Page should return to previous view (Preview or Dashboard)
16) The URL should contain "page=/articles/2016/12/baz.html"
17) The "My Recent Activity" widget should contain the following:
```
    Item Name: bar.xml  Edit: Edit    URL: /articles/2016/12/bar.html
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/baz.xml
    Item Name: foo.xml  Edit: Edit    URL: /articles/2016/12/foo.html  
```
<img width="980" alt="screen shot 2018-04-19 at 12 01 52 pm" src="https://user-images.githubusercontent.com/25483966/39003754-8958e8f2-43c9-11e8-9720-7f5185d8ee06.png">

18) The "Approve for Publish" dialog should open
19) The "Approve for Publish" dialog should close
20) In your dashboard, the "Recently Published" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /baz.xml
```
<img width="989" alt="screen shot 2018-04-19 at 12 02 58 pm" src="https://user-images.githubusercontent.com/25483966/39003804-a3aa623a-43c9-11e8-9955-59101b24e8e5.png">

21) The page just published should be viewable on the delivery side, with the url http://localhost:9080/articles/2016/12/baz.html

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, please validate.

**Comment by alhambrav** [comment]
I am getting errors when I run the test.  Here's the log: https://gist.github.com/alhambrav/4b49ecf7ea836e0b047c09d7c6831f5c

**Comment by luishernandezmonge** [comment]
Start working on the fix for this.

**Comment by luishernandezmonge** [comment]
@alhambrav Fixed on PR: https://github.com/craftercms/test-suite/pull/341

**Comment by alhambrav** [comment]
Verified.
