### ISSUE TITLE
[studio] Use "API" instead of "UI" in "source" column in the audit table for items done through APIs

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2053]
### Expected behavior
It would be nice if `source` for items done through APIs  is listed as `API` instead of `UI`

### Actual behavior
`source` for items done through APIs is listed as  `UI`

### Steps to reproduce the problem
* Create a site using any bp
* Look at the `source` column in the `audit` table in the db, notice that the `source` column is filled with `UI` for actions performed through APIs

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-4d7b74
Build Number: 4d7b745911f0f8a03d4f397666519bde25535c6a
Build Date/Time: 04-20-2018 12:02:27 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
The system needs to use _META to know the version, update the version and during the update, switch existing "UI" to become "API" for backward compatibility.

Ping me to discuss the other type, "Git" or "Disk" so we can agree on a name.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1108

**Comment by alhambrav** [comment]
Verified fixed.
