### ISSUE TITLE
[studio-ui] redirect on timeout properly when SSO enabled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2054]
### Expected behavior
When SSO is enabled, and the user information is not available in the session headers, Studio should redirect to the login page. The login page should then receive the headers (this is required for some SSO implementations), which then redirects the user to the site selection screen.

### Actual behavior
Studio shows the login dialog when the SSO user has timed-out. (We shouldn't ever show the login dialog while in SSO.)

### Steps to reproduce the problem
* Enable SSO
* Set SSO timeout to 2 minutes
* Go to dashboard and wait for the timeout
* Repeat steps on preview page (note dialog)

**Comment by sumerjabri** [comment]
@dejan-brkic there might be some backend work to do here. Please support Vero as needed.

**Comment by vestrada** [comment]
The redirection to home page if the authentication type is "headers" is done

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/819
Fixing system validation.

**Comment by sumerjabri** [comment]
@vestrada @dejan-brkic assigning back to you as you work through the remaining issue Vero indicated over Slack

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/821
@dejan-brkic the redirect from "login" to "sites" when headers are active is done. Per our conversation please continue with the issue with validate session api.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1106

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1107
