### ISSUE TITLE
[studio-ui] Copy/cut/paste/duplicate is not available for items not under components or site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2057]
### Expected behavior
Copy/cut/paste/duplicate should be available for items under static-assets, scripts and templates 

### Actual behavior
When you right click on an item under `static-assets`, Copy/Cut/Paste/Duplicate is not available.

### Steps to reproduce the problem
* Create a site using any bp
* Navigate to `static-assets`
* Right click on any item under `static-assets`, notice that there is no option to Copy/Cut/Paste/Duplicate.   Try the same on items under `scripts` or `templates` and the behavior is the same
![screen shot 2018-04-24 at 1 29 38 pm](https://user-images.githubusercontent.com/25483966/39203742-b76698f4-47c3-11e8-838a-fa7dc30fc53c.png)

![screen shot 2018-04-24 at 1 29 50 pm](https://user-images.githubusercontent.com/25483966/39203746-bb0da2ea-47c3-11e8-856a-d62299756efc.png)

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-b9ee09
Build Number: b9ee09c2eca9c27d37ea7cb28d948f2a6520240f
Build Date/Time: 04-24-2018 13:11:56 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/828

**Comment by vestrada** [comment]
Everything is added. You can check all. The only thing missing is to fix the refresh functionality of the sidebar after duplicate. I already created a ticket for this:
https://github.com/craftercms/craftercms/issues/2108

**Comment by alhambrav** [comment]
Verified fixed.
