### ISSUE TITLE
[studio] There is no audit log when a user submits/approves/rejects publishing

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2058]
### Expected behavior
It would be nice to have an audit log when a user submits/approves/rejects publishing

### Actual behavior
There is no audit log when a user submits/approves/rejects publishing

### Steps to reproduce the problem
* Create a user `author` in Studio
* Create a site using empty or website_editorial bp and add user `author` to the newly created site
* Login as user `author` and edit a page
* Do a `Request Publish` from your edited page
* Logout and then login as user `admin`
* Go to **Site Config** and click on **Audit**, notice that there is no log of the request publish
* Go to the dashboard, approve the request for publish 
* Go to **Site Config** and click on **Audit**, notice that there is no log of the approval for publish

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-e796b0
Build Number: e796b0f425e123ecbda9d22e75eb799d85c49449
Build Date/Time: 04-25-2018 11:51:41 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1111

**Comment by alhambrav** [comment]
@dejan-brkic I don't see a log in the audit log when a user rejects a request for publish. Please add a log that request for publish has been rejected by a user.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1116

**Comment by alhambrav** [comment]
Verified fixed.
