### ISSUE TITLE
[test-suite] Automate file -> rename -> publish -> rename -> delete

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2061]
Please automate file -> rename -> publish -> rename -> delete, ID 44 in **Studio -> Content**.

**Setup**
1) Create a site using Editorial BP
2) Click on "Site Config" -> "Content Types" -> "Open Existing Type"
3) Select "Page - Article" and click "Ok" from the "Choose Content Type" screen
4) In the "Properties Explorer", click on the "Configuration" field 
5) Click on the pencil next to "config.xml"
6) Change the value of the tag "\<content-as-folder\>" to "false"
7) Click on "Update"
8) Click on "Save" in the content type screen
9) Click on the site name next to the Crafter logo on the top left of the screen to return to the dashboard
10) Open the Sidebar if it's not yet open
11) Expand "Pages"
12) Right click on "articles/2016/12" and select "New Content"
13) Select "Page - Article" and click on the "Ok" button in the "Choose Content Type" screen
14) Put "foo" in the "Page URL" field
15) Put "foo" in the "Internal Name" and "Title" field
16) For "Categories", select "Entertainment"
17) Upload an image in the "Image" field
18) Fill in the rest of the required fields in the form and save your changes
19) From the Sidebar, navigate to "articles/2016/12/foo"
20) Right click on "foo" and select "Approve & Publish"
21) Select "Items should go live now" in the "Selected Item Scheduling" field then click on "Submit"
22) Setup your site for delivery by running the init-site script
<img width="776" alt="screen shot 2018-04-26 at 9 51 00 am" src="https://user-images.githubusercontent.com/25483966/39310024-5e70af8a-4937-11e8-8f79-6c58f50faffd.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "articles/2016/12/foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard
11) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Approve & Publish"
12) Select "Items should go live now" then click on "Submit"
13) Wait for a minute or so to make sure publishing is done
14) In your browser, go to "localhost:9080?crafterSite=siteName", where `siteName` is the name given on the site we're working on and then click on "Entertainment" from the left-rail
15) Click on the article "foo"
16) Back to Studio, click on the dashboard
17)from the Sidebar, right click on the page "articles/2016/12/foo" and select "Edit"
18) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
19) Click "Ok" on the Warning message
20) Change the "Page URL" from "bar" to "baz"
21) Click on the "Save and Close" 
22) From the Sidebar, click on the page "foo" to preview
23) Click on the Dashboard 
24) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Delete"
25) Click on the "Delete" button to delete the selected items on the Delete dialog, then click "OK" on the notification dialog that selection is being deleted
26) Click on the Dashboard

**Expected Output**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Preview or Dashboard)
9) The URL should contain "page=/articles/2016/12/bar.html"
10) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/bar.xml
    Item Name: foo.xml  Edit: Edit    URL: /articles/2016/12/foo.html  
```
<img width="779" alt="screen shot 2018-04-26 at 9 51 55 am" src="https://user-images.githubusercontent.com/25483966/39310082-86ee64f2-4937-11e8-8fd3-add834bfe743.png">

11) The "Approve for Publish" dialog should open
12) The "Approve for Publish" dialog should close
15) The page just published should be viewable on the delivery side, with the url http://localhost:9080/articles/2016/12/bar.html
16) In your dashboard, the "Recently Published" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /bar.xml
```
<img width="780" alt="screen shot 2018-04-26 at 10 18 53 am" src="https://user-images.githubusercontent.com/25483966/39311564-43109a44-493b-11e8-8bdf-19dd9368aac8.png">

17) Form for editing page "foo" should open
18) A warning message should appear after clicking on "Edit"
19) The "Page URL" field should now be editable and not grayed out
21) Page should return to previous view (Preview or Dashboard)
22) The URL should contain "page=/articles/2016/12/baz.html"
23) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/baz.xml
    Item Name: bar.xml  Edit: Edit    URL: /articles/2016/12/bar.html
    Item Name: foo.xml  Edit: Edit    URL: /articles/2016/12/foo.html  
```
<img width="776" alt="screen shot 2018-04-26 at 9 58 50 am" src="https://user-images.githubusercontent.com/25483966/39310478-78a09144-4938-11e8-8390-a07a4a48918c.png">

24) The "Delete" dialog should open
25) The page should return to previous view (Preview or Dashboard)
26) In your dashboard, the "My Recent Activity" widget should contain the following:
```
    Item Name: baz.xml    Edit: Edit    URL: /articles/2016/12/baz.html
    Item Name: bar.xml    Edit: Edit    URL: /articles/2016/12/bar.html
    Item Name: foo.xml    Edit: Edit    URL: /articles/2016/12/foo.html
```
<img width="779" alt="screen shot 2018-04-26 at 10 03 24 am" src="https://user-images.githubusercontent.com/25483966/39310690-166b8190-4939-11e8-898c-63d9c931b74a.png">

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, please verify.

**Comment by alhambrav** [comment]
Verified.
