### ISSUE TITLE
[test-suite] Automate page -> rename -> publish -> rename -> delete

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2064]
Please automate page -> rename -> publish -> rename -> delete, ID 45 in **Studio -> Content**.

**Setup**
1) Create a site using Editorial BP
2) Open the Sidebar if it's not yet open
3) Expand "Pages"
4) Right click on "articles/2016/12" and select "New Content"
5) Select "Page - Article" and click on the "Ok" button in the "Choose Content Type" screen
6) Put "foo" in the "Page URL" field
7) Put "foo" in the "Internal Name" and "Title" field
8) For "Categories", select "Entertainment"
9) Upload an image in the "Image" field
10) Fill in the rest of the required fields in the form and save your changes
11) From the Sidebar, navigate to "articles/2016/12/foo"
12) Right click on "foo" and select "Approve & Publish"
13) Select "Items should go live now" in the "Selected Item Scheduling" field then click on "Submit"
14) Setup your site for delivery by running the init-site script

<img width="848" alt="screen shot 2018-04-27 at 9 54 10 am" src="https://user-images.githubusercontent.com/25483966/39366103-f7b8552a-4a00-11e8-92a3-726d233f6023.png">

**Steps**
1) Login as admin user and open the site created in the setup
2) Open the Sidebar if it's not yet open
3) In Pages, navigate to "articles/2016/12/foo"
4) Right click on "foo" and select "Edit"
5) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
6) Click "Ok" on the Warning message
7) Change the "Page URL" from "foo" to "bar"
8) Click on the "Save and Close" 
9) From the Sidebar, click on the page "foo" to preview
10) Click on the Dashboard
11) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Approve & Publish"
12) Select "Items should go live now" then click on "Submit"
13) Wait for a minute or so to make sure publishing is done
14) In your browser, go to "localhost:9080?crafterSite=siteName", where `siteName` is the name given on the site we're working on and then click on "Entertainment" from the left-rail
15) Click on the article "foo"
16) Back to Studio, click on the dashboard
17)from the Sidebar, right click on the page "articles/2016/12/foo" and select "Edit"
18) In the "Page Properties" section, click on the "Edit" button next to the "Page URL" field
19) Click "Ok" on the Warning message
20) Change the "Page URL" from "bar" to "baz"
21) Click on the "Save and Close" 
22) From the Sidebar, click on the page "foo" to preview
23) Click on the Dashboard 
24) From the Sidebar, right click on the page "articles/2016/12/foo" and select "Delete"
25) Click on the "Delete" button to delete the selected items on the Delete dialog, then click "OK" on the notification dialog that selection is being deleted
26) Click on the Dashboard

**Expected Output**
4) Form for editing page "foo" should open
5) A warning message should appear after clicking on "Edit"
6) The "Page URL" field should now be editable and not grayed out
8) Page should return to previous view (Preview or Dashboard)
9) The URL should contain "page=/articles/2016/12/bar"
10) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo      Edit: Edit       URL: /articles/2016/12/bar
    Item Name: foo      Edit: Edit       URL: /articles/2016/12/foo  
```
<img width="852" alt="screen shot 2018-04-27 at 9 55 10 am" src="https://user-images.githubusercontent.com/25483966/39366300-88730fb0-4a01-11e8-8f22-233c5a524389.png">

11) The "Approve for Publish" dialog should open
12) The "Approve for Publish" dialog should close
15) The page just published should be viewable on the delivery side, with the url http://localhost:9080/articles/2016/12/bar
16) In your dashboard, the "Recently Published" widget should contain the following:
```
    Item Name: foo    Edit: Edit    URL: /articles/2016/12/bar
```
<img width="852" alt="screen shot 2018-04-27 at 9 58 46 am" src="https://user-images.githubusercontent.com/25483966/39366322-9bd338f0-4a01-11e8-8b9a-4f200921af16.png">

17) Form for editing page "foo" should open
18) A warning message should appear after clicking on "Edit"
19) The "Page URL" field should now be editable and not grayed out
21) Page should return to previous view (Preview or Dashboard)
22) The URL should contain "page=/articles/2016/12/baz"
23) The "My Recent Activity" widget should contain the following:
```
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/baz
    Item Name: bar      Edit: Edit    URL: /articles/2016/12/bar
    Item Name: foo      Edit: Edit    URL: /articles/2016/12/foo  
```
<img width="852" alt="screen shot 2018-04-27 at 10 00 26 am" src="https://user-images.githubusercontent.com/25483966/39366410-d78da312-4a01-11e8-88b0-89a07773126d.png">

24) The "Delete" dialog should open
25) The page should return to previous view (Preview or Dashboard)
26) In your dashboard, the "My Recent Activity" widget should contain the following:
```
    Item Name: baz    Edit: Edit    URL: /articles/2016/12/baz
    Item Name: bar    Edit: Edit    URL: /articles/2016/12/bar
    Item Name: foo    Edit: Edit    URL: /articles/2016/12/foo
```
<img width="853" alt="screen shot 2018-04-27 at 10 01 37 am" src="https://user-images.githubusercontent.com/25483966/39366478-0555f966-4a02-11e8-85fa-01093516b11a.png">

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done on PR: https://github.com/craftercms/test-suite/pull/344, please check it after merge.

**Comment by luishernandezmonge** [comment]
Will check this failure cause. Thanks!

**Comment by luishernandezmonge** [comment]
@alhambrav fix added to PR: https://github.com/craftercms/test-suite/pull/347

**Comment by alhambrav** [comment]
Verified.
