### ISSUE TITLE
[studio] api/1/services/api/1/activity/post-activity.json api call returns an "org.craftercms.engine.exception.ScriptException: No such property: UI for class: org.craftercms.studio.api.v1.service.activity.ActivityService$ActivitySource" exception

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2071]
### Expected behavior
The api call for post-active shouldn't return exceptions on the log, and it should returns a 200ok response.

### Actual behavior
The api call is returning a 500 response code, and also it is returning the next log exception:

**_org.craftercms.engine.exception.ScriptException: No such property: UI for class: org.craftercms.studio.api.v1.service.activity.ActivityService$ActivitySource_**

### Steps to reproduce the problem
On your rest client run the next steps:
* Run the login api call using X-XSRF-TOKEN token on the header (api call> http://localhost:8080/studio/api/1/services/api/1/security/login.json)
* Create a site on Studio and take note of the siteID (siteID=test).
* Run the get user api call> /api/1/services/api/1/activity/post-activity.json?site=test&user=admin&path=/site/website/index.xml&activity=UPDATED&contentTypeClass=pages
* Review the response returned for the api call of above.
* Review the tomcat log on the crafter-authoring folder.

### Log/stack trace (use https://gist.github.com)
Log error: https://gist.github.com/luishernandezmonge/c53dd5c3e4620d7de3da5b424972718c

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-609801
Build Number: 609801bb44e24ba635d706f5d1455caddef8d7b4
Build Date/Time: 04-27-2018 10:05:28 -0600
#### OS
Mac OSX
#### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1114

**Comment by luishernandezmonge** [comment]
Verified as resolved.
