### ISSUE TITLE
[studio-ui] Reject Publish does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2072]
### Expected behavior
Reject Publish should work

### Actual behavior
Reject Publish does not work

### Steps to reproduce the problem
* Create a site using website_editorial
* Create an `author` user
* Login as user `author`
* Edit a page and `Request Publish`
* Login as the admin again
* Go to the dashboard and reject the request for publish. Select a reason from the drop-down box.  Notice there's no message that appears in the box and also notice the error message in the tomcat log:
```
[ERROR] 2018-04-30 07:11:35,669 [http-nio-8080-exec-4] [rest.RestScriptsController] | Script not found at /scripts/rest/api/1/site/get-canned-message.get.groovy
```  
<img width="562" alt="screen shot 2018-04-30 at 7 11 42 am" src="https://user-images.githubusercontent.com/25483966/39424833-8dd2eb82-4c46-11e8-9d52-f5be733e5b28.png">

Notice the error message displayed
<img width="563" alt="screen shot 2018-04-30 at 7 11 02 am" src="https://user-images.githubusercontent.com/25483966/39424874-b95b726a-4c46-11e8-929f-949325a91d77.png">

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/74852b25ec27fbaaf01c763d0194fde8

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-9293dd
Build Number: 9293ddf2241cb933adb75ede9dd1be542b50a44e
Build Date/Time: 04-30-2018 00:23:26 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
UI:
https://github.com/craftercms/studio-ui/pull/826
BE:
https://github.com/craftercms/studio/pull/1112

**Comment by alhambrav** [comment]
Verified fixed.
