### ISSUE TITLE
[studio] Cannot create a site based on a remote repo

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2073]
### Expected behavior
User should be able to create a site based on a remote repository

### Actual behavior
Cannot create a site based on a remote repository. 

### Steps to reproduce the problem
* Create a site based on a remote repository in Studio.  Notice the error message in the dialog:
 
![screen shot 2018-04-30 at 10 04 08 am](https://user-images.githubusercontent.com/25483966/39431168-df950ca4-4c5d-11e8-8843-a3b644aa796d.png)

Also, notice that there is no error log in the tomcat.

### Log/stack trace (use https://gist.github.com)
Here's a short clip trying to create a site based on a remote repo but fails:
https://www.useloom.com/share/662acc117eef4cdb892fc2cac28705e3

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-9293dd
Build Number: 9293ddf2241cb933adb75ede9dd1be542b50a44e
Build Date/Time: 04-30-2018 09:58:00 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done. Fixed with #1997
PR:
https://github.com/craftercms/studio/pull/1113

**Comment by alhambrav** [comment]
Verified fixed.
