### ISSUE TITLE
[studio-ui] Tooltip when mouse is over action icons in History appears behind the dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2074]
### Expected behavior
Tooltip when mouse is over action icons in History should appear on top of the dialog

### Actual behavior
Tooltip when mouse is over action icons in History appears behind the dialog

### Steps to reproduce the problem
* Create a site using website editorial
* Preview a page, either an article or the home page
* Click on `History` from the context nav
* Mouse over on any of the `Actions` icons, notice that the tooltip appears behind the dialog (When your mouse is over the eye or the papers icon, you can't even tell if anything is happening because the tooltip is behind the dialog. You can only tell that it is behind the dialog when you mouse over on the revert icon.)

![screen shot 2018-04-30 at 2 57 31 pm](https://user-images.githubusercontent.com/25483966/39444869-20c617e4-4c87-11e8-9f53-359a3e6746dd.png)

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-48ccfd
Build Number: 48ccfd18bbc1607a8885917ef28e5f37d31552c6
Build Date/Time: 04-30-2018 14:35:08 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/833

**Comment by alhambrav** [comment]
Verified fixed.
