### ISSUE TITLE
[studio] Item dependency not updated when reverting

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2075]
### Expected behavior
Item dependency should be updated when reverting

### Actual behavior
Item dependency not updated when reverting

### Steps to reproduce the problem
* Create a site using website_editorial
* Navigate to `articles/2016/7/New ACME Phone Released Today` and click to preview
* Click on `Dependencies` from the context nav and select Show content that: `is referenced by this item`.  Notice the items listed as dependencies
![screen shot 2018-04-30 at 3 24 03 pm](https://user-images.githubusercontent.com/25483966/39445894-8c192c4a-4c8a-11e8-8300-f357fc76ab52.png)
* Click on `Edit` from the context nav. scroll down to the section `Content`
* Click on the `Replace` button in the `Image field` and select `Upload Images`. Upload an image and click on `Save and Close`
 * Click on `Dependencies` from the context nav and note the dependencies listed in `is referenced by this item`.  The photo dependency has been updated to the uploaded photo.
![screen shot 2018-04-30 at 3 26 33 pm](https://user-images.githubusercontent.com/25483966/39445998-f7bae060-4c8a-11e8-9c8b-19cdd5677463.png)
* From the context nav, click on `History`
* Revert to the initial commit (to go back to the original image).  In the preview page, you should see the original image (photo of cellphone)
![screen shot 2018-04-30 at 3 28 13 pm](https://user-images.githubusercontent.com/25483966/39446091-4372bbcc-4c8b-11e8-998c-e4577f2c5396.png)
* Click on `Dependencies` from the context nav and note the dependencies listed in `is referenced by this item`  The picture displayed in the preview is the cellphone, but the photo listed as dependency is the uploaded image. (Should the dependency been updated to the cellphone photo when it was reverted?)
![screen shot 2018-04-30 at 3 19 39 pm](https://user-images.githubusercontent.com/25483966/39445710-f2a37a70-4c89-11e8-8c74-5fb2e165e0ba.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/6512c137db194cdb8bca210cbb12a8de

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-48ccfd
Build Number: 48ccfd18bbc1607a8885917ef28e5f37d31552c6
Build Date/Time: 04-30-2018 14:35:08 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1115

**Comment by alhambrav** [comment]
Verified fixed.
