### ISSUE TITLE
[studio] Change message when publishing is stopped

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2077]
### Expected behavior
Change message when publishing is stopped in the `Publishing` screen in `Site Config` to something like: `User admin disabled publishing for site on ...` (Maybe @sumerjabri  can give better wording for the message)

### Actual behavior
Message displayed when publishing is stopped: `User myadmin stopped the site on  05-01-2018 12:31:23 pm`

![screen shot 2018-05-01 at 12 47 53 pm](https://user-images.githubusercontent.com/25483966/39482656-e51939ee-4d3d-11e8-9e4a-9777218db985.png)

### Steps to reproduce the problem
* Create a site using any bp
* Go to `Site Config`, then `Publishing`
* Go to the `Status` tab and click on the `Stop` button, notice the message displayed

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-5f78fa
Build Number: 5f78fa57f64e3f81798c1ceb059309501a2b01d3
Build Date/Time: 05-01-2018 07:08:08 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Hi @sumerjabri and @alhambrav , This message comes from the api.
Please see the "Publish Status" response:
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/status.html

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1135

**Comment by alhambrav** [comment]
Verified fixed.
