### ISSUE TITLE
[studio] Get permissions call on dashboard results in redundant requests to Alfresco

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2078]
### Expected behavior
Only call alfresco for permissions when needed

### Actual behavior
Alfresco is receiving a individual request  from Crafter Studio for every item on the site dashboard (including when items are repeated)

#### Version
2.x

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss design options.

**Comment by russdanner** [comment]
Confirmed
