### ISSUE TITLE
[studio] Implement new calculate dependencies API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2080]
Please implement: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/dependency/calculate-dependencies.html

**Comment by dejan-brkic** [comment]
3.x
PR:
https://github.com/craftercms/studio/pull/1119

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1122
