### ISSUE TITLE
[studio] Please implement new API publish items

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2081]
Please implement new API: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/publish-items.html

**Comment by dejan-brkic** [comment]
Done 3.x
PR:
https://github.com/craftercms/studio/pull/1121

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1124
