### ISSUE TITLE
[studio-ui] Update the print dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2082]
In order to improve the print dialog performance, we're going to implement several enhancements.
![print-dialog](https://user-images.githubusercontent.com/3931908/39536582-04426b02-4e05-11e8-912e-d95fd75e2a6d.png)

1. When the dialog loads, don't call the backend at all, simply show a list of the files selected by the user with + to expand dependencies
2. Add a new button called "Show All Dependencies," if clicked, call the API: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/dependency/calculate-dependencies.html with all the selected files and populate the UI data-structures with all deps (flat list under every item) and expand all
3. If the user clicks on + for an item, and the UI data-structure is already populated, expand
4. If the user clicks on + for an item, and the UI data-structure is not populated, call the API http://docs.craftercms.org/en/3.0/developers/projects/studio/api/dependency/calculate-dependencies.html with that single item in the request
5. Change the button Close to Cancel, if the user clicks cancel, cancel out as you do today
6. If the user clicks Submit, call the new API: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/publish-items.html with the updated list of selections (the user can unselect one of the top files (original list) but cannot unselect a dependency)

Ping me for any questions.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/827

**Comment by jvega190** [comment]
2.5.x https://github.com/craftercms/studio-ui/pull/835
