### ISSUE TITLE
[studio] Add parent as a dep for items

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2083]
Per our conversation, please:
* add the parent of an item to the list of deps for that item.
* make sure to handle move, duplicate, paste, and similar item actions

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1122

**Comment by sumerjabri** [comment]
Seems that the parent can be a folder in the current impl. Please fix or ping me to discuss.

**Comment by dejan-brkic** [comment]
3.0.x
PR:
https://github.com/craftercms/studio/pull/1127

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1126

**Comment by russdanner** [comment]
Confirmed
