### ISSUE TITLE
[studio] Implement new publishing mechanics

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2084]
Implement new publishing mechanics per our conversation:
* Drop git walking for primary parent and instead use the DB exclusively after finishing #2083 
* Remove items to be published from any existing workflows
* Add new items based on DB query into a new publish package in the queue without computing heavy objects

**Comment by dejan-brkic** [comment]
Done 3.x
PR:
https://github.com/craftercms/studio/pull/1121

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1124

**Comment by russdanner** [comment]
@sumerjabri @dejan-brkic 
After build on 2.x I think we have an issue with parent calculation:

<img width="941" alt="screen shot 2018-05-08 at 6 48 10 pm" src="https://user-images.githubusercontent.com/169432/39787052-600739e0-52f1-11e8-9e11-c4740ee0e988.png">

Some of these paths do not point to actual objects.
/templates/web
/site

# version
Manifest-Version: 1.0
Implementation-Title: Crafter Studio
Implementation-Version: 2.5.16-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: rdanner
Build-On: 1525816022200
Implementation-Build: a82a44f8c6ac4b727e8429db3467ec55047033a2
Implementation-Vendor-Id: org.craftercms
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_101
Implementation-Vendor: CrafterCMS

**Comment by dejan-brkic** [comment]
3.0.x
PR:
https://github.com/craftercms/studio/pull/1127

**Comment by dejan-brkic** [comment]
2.5.x
PR:
https://github.com/craftercms/studio/pull/1126

**Comment by russdanner** [comment]
Confirmed
