### ISSUE TITLE
[test-suite] Automate: Verify that the application show the sites page complete with or without sites created. (logos, titles, all links, buttons). 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2087]
Please automate ID 1 in **Studio -> Sites**: Verify that the application show the sites page complete with or without sites created. (logos, titles, all links, buttons).

**Setup**
Authoring environment is running

**Steps**
1) Login as Admin
2) Go to sites page
3) Review all the elements on page
4) Click on the "Create Site" button, and provide valid values (select the Empty bp)
5) Click on "Sites"
6) Review all the elements on the page
7) Delete the site of preconditions and reload the sites page

**Expected Output**
3) The next elements are displayed on the sites page (no site listed):
-Sites [label]
-Create Site button
-Sites per page input
6) The next elements are displayed on the sites page:
-Sites [label]
-Create Site button
-Sites per page input
-Sites table with
 Sitename   Preview (link)  Dashboard (link) Delete icon (trash can)

**Comment by luishernandezmonge** [comment]
start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done on PR: https://github.com/craftercms/test-suite/pull/345. Please validate after merge.

**Comment by alhambrav** [comment]
Verified.
