### ISSUE TITLE
[studio-ui] Sites per page input value is not remembered from the "Sites" screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2088]
### Expected behavior
"Sites per page" input value should be remembered from the "Sites" screen when you preview a site then return to the "Sites" screen

### Actual behavior
Sites per page input value is not remembered from the "Sites" screen

### Steps to reproduce the problem
* Create 4 or more sites in Studio
* From the "Sites" screen, change the "Sites per page" input value to "3" (It looks like it defaults to 15?)
![screen shot 2018-05-02 at 3 07 00 pm](https://user-images.githubusercontent.com/25483966/39543932-85102b2e-4e1a-11e8-9f41-fd9f8156ef73.png)
* Click on "Preview" on one of the sites in the list
* Click on "Sites" from the context nav to return to the "Sites" screen.  Notice that the "Sites per page" input value has changed back to "15" instead of the "3" we put in earlier 

![screen shot 2018-05-02 at 3 08 42 pm](https://user-images.githubusercontent.com/25483966/39543994-ba7ba220-4e1a-11e8-8798-82841ef79527.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the behavior:
https://www.useloom.com/share/80d8535bda31483c9e556e92bbeab1eb

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-5f78fa
Build Number: 5f78fa57f64e3f81798c1ceb059309501a2b01d3
Build Date/Time: 05-02-2018 07:08:18 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/966

**Comment by alhambrav** [comment]
Verified fixed
