### ISSUE TITLE
[studio-ui] Setting Populate Expression property on date-time form engine control has no effect

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2091]
### Expected behavior
**Currently supported expressions** should be applied to the default value of the date control.
```[+ or -][number][days or weeks or years]```

#### Current Function that evals/applies the expression
Current coded evaluation is quite simple and does not support compound expressions:
```	doDatePopulateExpression : function (currentDate) {
		var daysInWeek=7;
		var modifier=1;

		if(this.checkPopulateDateExpisValid()){
			var action=this.populateDateExp.substring(0,1);
			var value = this.populateDateExp.match(/\d+/gi)[0];
			var type = this.populateDateExp.match(/((days)|(weeks)|(years))/gi);
			if(action=='-'){
				modifier=modifier*-1;
			}
			if(type=="years"){
				currentDate.setFullYear(currentDate.getFullYear()+(modifier*value))
			}else if (type=="weeks"){
				currentDate.setDate(currentDate.getDate()+(modifier*value*daysInWeek))
			}else if(type=="days") {
				currentDate.setDate(currentDate.getDate()+(modifier*value));
			}
			console.log(currentDate)
		}
		return currentDate;
	},
```

### Actual behavior
Expression has no effect

### Steps to reproduce the problem
* Configure a date time field in a form 
* Set the populate expression in the control Eg: -7days
* open the form, note it has no effect (there is no modified value on the default date)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/848

**Comment by russdanner** [comment]
Operators are not respected.
White space causes functionality to fail
https://www.useloom.com/share/6e94614ca6d94f7aa86f2ddc88bdf216

**Comment by vestrada** [comment]
Does it need to support white spaces. 
In the above comment you wrote: [+ or -][number][days or weeks or years].
There is no spaces, Can you be more specific?
Or do we just ignore white spaces?

**Comment by russdanner** [comment]
Confirmed
