### ISSUE TITLE
[studio-ui] Filters and results template scripts for the search/config.xml does not seem to be working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2093]
### Expected behavior
Filters and results template scripts for the search/config.xml should work

### Actual behavior
Filters and results template scripts for the search/config.xml does not seem to be working, such as image, css, javascript, etc.

### Steps to reproduce the problem
* Create a site using website_editorial bp
* Click on the magnifying glass icon at the top right of Studio to perform a search
* Enter say "book" in the keywords, it looks like it only finds pages using the `default` filter, setup in Studio `config/studio/search/config.xml`
```
<config>
	<filters>
		<filter>
			<name>default</name>
			<label>Default</label>
			<default>true</default>
		</filter>
	</filters>

	<resultTemplates>
		<template>
			<type>*</type>
			<name>default</name>
		</template>
	</resultTemplates>
</config>
```
* Change the filter used to say, `images`, by changing the context value in your browser from `default` to `images`.
```
http://localhost:8080/studio/search?site=anothersite&s=book&context=image&keywords=book&sortBy=relevance&selection=-1&mode=act&ipp=20&page=1&searchId=65621dfb-f8cd-5198-68ca-ed1aed4af7a5&searchId=6ba4bc09-2ed5-50e4-a6d4-d4f1b31d1874
```
* I'm expecting it to find the `book-woman-pic.jpg` and the results showed this:
<img width="1416" alt="screen shot 2018-05-03 at 4 19 22 pm" src="https://user-images.githubusercontent.com/25483966/39600765-c7f94c62-4eed-11e8-984a-ded8308a591f.png">

Notice how the results page looks like, shows pagination for multiple pages, but, there's nothing in the results, etc.

The filters and results scripts are located in studio-ui in: `static-assets/components/cstudio-search/filters`  and `static-assets/components/cstudio-search/results`

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-5f78fa
Build Number: 5f78fa57f64e3f81798c1ceb059309501a2b01d3
Build Date/Time: 05-02-2018 07:08:18 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Hi @alhambrav, @sumerjabri and @dejan-brkic 
I found that the search api is responding with an error:

`{"objectList":[],"query":"crafterSite:\"test5\"  AND (localId: (\"book\" OR *book* OR (book)) OR internal-name: (\"book\" OR *book* OR (book)) OR title: (\"book\" OR *book* OR (book)) OR _text_main_: (\"book\" OR *book* OR (book))) AND cm:content.mimetype:image/* ","searchFailed":true,"error":"org.craftercms.search.exception.SearchException: [test5] Search for query q=crafterSite%3A%22test5%22++AND+%28localId%3A+%28%22book%22+OR+*book*+OR+%28book%29%29+OR+internal-name%3A+%28%22book%22+OR+*book*+OR+%28book%29%29+OR+title%3A+%28%22book%22+OR+*book*+OR+%28book%29%29+OR+_text_main_%3A+%28%22book%22+OR+*book*+OR+%28book%29%29%29+AND+cm%3Acontent.mimetype%3Aimage%2F*+&rows=20&start=0&sort=score+desc failed: [null] {\"message\":\"Error from server at http://localhost:8694/solr: org.apache.solr.search.SyntaxError: Cannot parse 'crafterSite:\\\"test5\\\"  AND (localId: (\\\"book\\\" OR *book* OR (book)) OR internal-name: (\\\"book\\\" OR *book* OR (book)) OR title: (\\\"book\\\" OR *book* OR (book)) OR _text_main_: (\\\"book\\\" OR *book* OR (book))) AND cm:content.mimetype:image/* ': Encountered \\\" \\\":\\\" \\\": \\\"\\\" at line 1, column 219.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\\"+\\\" ...\\n    \\\"-\\\" ...\\n    <BAREOPER> ...\\n    \\\"(\\\" ...\\n    \\\"*\\\" ...\\n    \\\"^\\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\\"[\\\" ...\\n    \\\"{\\\" ...\\n    <LPARAMS> ...\\n    \\\"filter(\\\" ...\\n    <NUMBER> ...\\n    \"}"}`

Image:
<img width="294" alt="screen shot 2018-05-11 at 10 41 34 am" src="https://user-images.githubusercontent.com/11640613/39936660-64fef5f8-550a-11e8-81b4-84cf6aae3ee6.png">

I checked the search documentation api (https://docs.craftercms.org/en/3.0/developers/projects/studio/api/content/search.html) and the request parameters we are using are good. Please take a look:

<img width="727" alt="screen shot 2018-05-11 at 10 50 59 am" src="https://user-images.githubusercontent.com/11640613/39936760-d0ee6c58-550a-11e8-846e-d3f428cf7734.png">

**Comment by jdrossl** [comment]
@avasquez614 @sumerjabri the ui is sending parameters that were used when the search service worked with alfresco, currently, it works with solr and there is no way to query for images (or any other file type that is not indexed). How should we handle this issue?

**Comment by sumerjabri** [comment]
@jdrossl remove what we no longer support.

**Comment by jdrossl** [comment]
@vestrada I think most work will be on the ui side right? like removing those form for different contexts and making sure that parameter no longer can be used.

The service actually doesn't know anything about those extra parameters that used by the ui.
