### ISSUE TITLE
[studio-ui] Rename folder doesn't do lowercase 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2094]
### Expected behavior

The renaming folder dialog should convert the letters to lowercase like the create folder dialog. 

### Actual behavior

The renaming folder dialog doesn't convert the letters to lowercase.

### Steps to reproduce the problem
* Create a site with any blueprint.
* Create a folder.
* Right-click and select Rename Folder.
* Try putting some letters in upper-case.

Observe how the letters are not converted.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/831

**Comment by avasquez614** [comment]
Tested and verified
