### ISSUE TITLE
[studio-ui] Publish Status dialog is not fully displayed when the browser is not wide enough

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2096]
### Expected behavior
Publish Status dialog should be fully displayed when the browser is not wide enough and the `Sidebar` is open

### Actual behavior
Publish Status dialog is not fully displayed when the browser is not wide enough and the `Sidebar` is open
<img width="805" alt="screen shot 2018-05-04 at 7 30 18 am" src="https://user-images.githubusercontent.com/25483966/39625782-0c2c78b2-4f6d-11e8-9074-2b5573ff6932.png">

### Steps to reproduce the problem
* Create a site using any bp
* Open the `Sidebar`
* Click on the `Publishing Status` icon from the top right of Studio. 
* Try to make the browser width narrower.  Notice that the narrower it gets, the Publishing Status dialog is partially behind the `Sidebar`

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/a7745b7585cc41abbf996bf961e2c8fa

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-5f78fa
Build Number: 5f78fa57f64e3f81798c1ceb059309501a2b01d3
Build Date/Time: 05-02-2018 07:08:18 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/849

**Comment by alhambrav** [comment]
Verified fixed.
