### ISSUE TITLE
[search]  xxe vulnerability in solr 6.4.1

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2097]
Solr version 6.4.1 XXE
http://seclists.org/oss-sec/2018/q2/22

# Description:
The details of this vulnerability were reported to the Apache Security mailing list. 

This vulnerability relates to an XML external entity expansion (XXE) in the
`&dataConfig=<inlinexml>` parameter of Solr's DataImportHandler. It can be
used as XXE using file/ftp/http protocols in order to read arbitrary local
files from the Solr server or the internal network. See [1] for more details.

# Mitigation:
Users are advised to upgrade to either Solr 6.6.3 or Solr 7.3.0 releases both
of which address the vulnerability. Once upgrade is complete, no other steps
are required. Those releases disable external entities in anonymous XML files
passed through this request parameter. 

If users are unable to upgrade to Solr 6.6.3 or Solr 7.3.0 then they are
advised to disable data import handler in their solrconfig.xml file and
restart their Solr instances. Alternatively, if Solr instances are only used
locally without access to public internet, the vulnerability cannot be used
directly, so it may not be required to update, and instead reverse proxies or
Solr client applications should be guarded to not allow end users to inject
`dataConfig` request parameters. Please refer to [2] on how to correctly
secure Solr servers.

**Comment by avasquez614** [comment]
We'll upgrade to 6.6.3 in 3.0.11 and then to 7 in 3.1.x

**Comment by avasquez614** [comment]
Tested and verified
