### ISSUE TITLE
[test-suite] Automate: Verify that the application allows to cancel the create site process.

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2099]
Please automate ID 3 in **Studio -> Sites**: Verify that the application allows to cancel the create site process.

**Setup**
Authoring environment is running

**Steps**
1) Login as Admin
2) Go to sites page
3) Click on create site button and provide valid values (select the Empty Blue print on this)
4) Click on Cancel 

**Expected Output**
4) The Create site dialog is closed and the site is not created

**Comment by luishernandezmonge** [comment]
@alhambrav Done, please check.

**Comment by alhambrav** [comment]
Verified.
