### ISSUE TITLE
[studio-ui] Change help text for "Site Id" in Create Site 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2100]
### Expected behavior
Help text for `Site Id` in Create Site should say something like the following: 
```
(Max length: 50 characters, consisting of: lowercase letters, numbers, dash (-) and underscore ( _) )
```
since the `Site Id` field allows dashes and underscores too

### Actual behavior
Help text for `Site Id` in Create Site says the following: 
```
(Max length: 50 characters, lowercase, no spaces or special characters)
```

### Steps to reproduce the problem
* Login to Studio
* Click on `Create Site`
* Notice the `Site Id` help text
![screen shot 2018-05-04 at 12 33 51 pm](https://user-images.githubusercontent.com/25483966/39639690-71db7e7c-4f97-11e8-97f7-66856c75b6f8.png)

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-5f78fa
Build Number: 5f78fa57f64e3f81798c1ceb059309501a2b01d3
Build Date/Time: 05-02-2018 07:08:18 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/845

**Comment by alhambrav** [comment]
Verified.
