### ISSUE TITLE
[studio] create unique constraint on remotes names for a given site

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2101]
### Expected behavior
You should not be able to add multiple remotes with the same name to a given site

### Actual behavior
It's possible to end up with 2+ remotes in the db with the same site/remote name
Later pull/push API calls respond with a SQL error:

`{"message":"Internal server error: \norg.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2"}`

### Steps to reproduce the problem
* Call the add-remote API twice with the same site/remote combination

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1130

**Comment by russdanner** [comment]
Confirmed
