### ISSUE TITLE
[studio-ui] Add RTE plugin for inserting static asset links

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2102]
Add a TinyMCE plugin that allows the user to upload, browse and select a static asset like a PDF or a Word document and insert a link to it into an RTE field.

**Comment by russdanner** [comment]
Updating the timeline on this ticket to better support installations leveraging external storage.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1282

**Comment by yacdaniel** [comment]
Verified.
