### ISSUE TITLE
[studio-ui] Get rid of the RTE plugins that don't work

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2103]
There are several TinyMCE plugins under https://github.com/craftercms/studio-ui/tree/master/static-assets/components/cstudio-forms/controls/rte-plugins that are suspected not to work (like insert-linkBrowse.js). Please test all plugins and make sure to get rid of those that don't and are not necessary.

**Comment by sumerjabri** [comment]
Completed and documented.
