### ISSUE TITLE
[test-suite] Automate verification that the application shows each validations of the fields for the create site process

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2106]
Please automate ID 4 in **Studio -> Sites**: Verify that the application shows each validations of the fields for the create site process

**Setup**
Authoring environment is running

**Steps**
1) Login as Admin
2) Go to sites page
3) Click on create site button and provide the next values:
-Leave empty the siteID field and go to Description
4) Enter the next value for siteId:  TestingUPPERCASE AND SPACES
5) Delete the value above and enter the next value for siteID: testing!!$%
6) Expand the `Link to upstream remote Git repository` 
7) Click on the "Remote Git Repository Name" field and leave empty, then click on the next field
8) Click on the "Remote Git Repository URL" field and leave empty, then click on the next field
9) In the "Authentication Type" field, select "Basic"
10) Click on "Remote Git Repository Username" and leave empty, then click on another field
11) Click on "Remote Git Repository Password" and leave empty, then click on another field
12) In the "Authentication Type:" field, select "Remote Git Repository Token"
13) Click on the "Remote Git Repository Token" field and leave empty, then click on another field
14) In the "Authentication Type:" field, select "Remote Git Repository Private Key"
15) Click on the "Remote Git Repository Private Key" and leave empty, then click on another field

**Expected Output**
3) The siteID required validation is displayed
4) The siteID field converts the value to nonspaces and lower case letters
5) The siteID does not allow to set other characters after letters
7) The "Remote Git Repository Name" required validation is displayed
8) The "Remote Git Repository URL" required validation is displayed
10) The "Remote Git Repository Username" required validation is displayed
11) The "Remote Git Repository Password" required validation is displayed
13) The "Remote Git Repository Token" required validation is displayed
15) The "Remote Git Repository Private Key" required validation is displayed

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added to PR: https://github.com/craftercms/test-suite/pull/347

**Comment by alhambrav** [comment]
Verified.
