### ISSUE TITLE
[studio-ui] Publishing Status icon in context nav does not seem to be working correctly

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2107]
### Expected behavior
Publishing Status icon should reflect the actual publishing status, example, items are in queue, or publishing, etc.

### Actual behavior
Publishing Status icon in context nav does not seem to be working correctly

### Steps to reproduce the problem
We'll follow the steps listed in ticket https://github.com/craftercms/craftercms/issues/1730
* Create a site using Editorial BP
* On disk: 
```
cd crafter-authoring/data/repos/sites/{SITE}/sandbox/site/website/articles
for i in `seq 1 30`; do cp -r 2017 new-articles-$i; done; git add .; git commit -m "Added new articles for testing."
```
* Wait until Studio picks up the changes (~10 seconds)
* Click on Show In-Progress Items in the `Items Waiting For Approval` widget in your dashboard
* Click on "Select All" to select all items:
* Publish, note the `Publishing Status` icon at the top right corner of Studio. (It doesn't change at all... I was expecting it to change color/status since it takes a while to publish all 180 articles)

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-55e772
Build Number: 55e772c3aa89cd48a1f6a8be383db77769327ce3
Build Date/Time: 05-07-2018 09:59:35 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
- we must add a new state, `in queue` or similar which reflects how many packages are in the queue (perhaps the number of files per package too)
- while the system is publishing from the queue (dep-calc, or put in `published`) we must set the state to busy with an indication as to which package we're busy with
- idle should report the last published package id and number of files published
- the dashboard should list the package id somewhere to tie things together

**Comment by vestrada** [comment]
Status api is being called more often to see the changes. 
Dejan please continue with the ticket.

Thanks

**Comment by alhambrav** [comment]
For this item: 
```
idle should report the last published package id and number of files published
```
Hi @dejan-brkic  - Please add the number of files in the last published package.  Thanks!


Hi @sumerjabri 
Regarding the list above, I would like to get your thoughts on the following:

For this item:
```
* `while the system is publishing from the queue (dep-calc, or put in published) we must set the state to busy with an indication as to which package we're busy with`
```
I don't see the icon for Publishing change to busy when the system is publishing from the queue ( I was expecting to see the icon change to orange? Is that the correct indication that the system is busy?)  I do see that the status indicates the publish package it is working on.  I published 540 files for later and watched the status when it started publishing the items.   Thanks! Here's a short clip: https://www.useloom.com/share/68ca118e19384b478ead84a5a1868fbf
Just to clarify my question, should the Publishing Status icon change to orange when items in the queue start getting published, or is the current behavior correct?

For this item:
```
* the dashboard should list the package id somewhere to tie things together
```
How did you want the dashboard to look like with the package id somewhere?  Should it be another column in the `Recently Published` and the `Approved Scheduled Items` widget?  Or, should the package id appear with the `URL` or something else?

For this item, just an FYI:
```
* we must add a new state, in queue or similar which reflects how many packages are in the queue (perhaps the number of files per package too)
```
I am able to see the new state `Queued`, Dejan mentioned that we can only detect something in the queue, but will not be able to list how many packages are in the queue

Thank you!

**Comment by russdanner** [comment]
Publish status icon accurately reflects idle and stopped but does not show orange when in process.

**Comment by vestrada** [comment]
@dejan this is a BE bug.

**Comment by dejan-brkic** [comment]
Fixed
PR:
https://github.com/craftercms/studio/pull/1179

**Comment by sumerjabri** [comment]
@dejan-brkic please add the package id to the dashboard API as we discussed.

**Comment by alhambrav** [comment]
Hi @dejan-brkic -  Please also remember to add the number of files in the last published package in the idle report.
Thanks!

**Comment by dejan-brkic** [comment]
Added packageId property in the response for `Scheduled & Approved` dashboard

**Comment by vestrada** [comment]
Package Id Column was added to Approved Scheduled Items dashboard.

**Comment by alhambrav** [comment]
Verified.
