### ISSUE TITLE
[studio-ui] Refresh functionality of the sidebar after duplicate in static assets is closing the parent.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2108]
### Expected behavior
Refresh should keep open the whole sidebar.

### Actual behavior
Refresh side bar after duplicate in static assets is closing the parent.

### Steps to reproduce the problem
* Create a site using any bp
* Navigate to static-assets
* Right click on any item under static-assets, click on duplicate option.
* You will see that the refresh is not working good.

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-b9ee09
Build Number: b9ee09c2eca9c27d37ea7cb28d948f2a6520240f
Build Date/Time: 04-24-2018 13:11:56 -0400

#### OS
OS X

#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/967

**Comment by sumerjabri** [comment]
It doesn't refresh for me at all. I click duplicate and nothing changes. I have to reload the page to see the duplicate.

**Comment by vestrada** [comment]
Hi @sumerjabri 

It is being hard to replicate this issue. Please watch the following video:

https://www.useloom.com/share/82e4f93d0981466ebe8d1a1af0ce7fa1

Please let me know if this is still happening to you.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1057

**Comment by sumerjabri** [comment]
Please clean up the code as we discussed.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1061

**Comment by vestrada** [comment]
Per conversation with Sumer this will be worked later.

**Comment by jvega190** [comment]
@sumerjabri this ticket seems to be done, I see a comment in the last related PR saying `We should make this a MIME type and make the MIME types a constant`. Is that what is pending for this one?

**Comment by sumerjabri** [comment]
@jvega190 yes, I think that's it.

**Comment by jvega190** [comment]
@sumerjabri should this be assigned to @yacdaniel for validation?

**Comment by sumerjabri** [comment]
The sidebar has been replaced. Closing.
