### ISSUE TITLE
[studio-ui] Can't tell if anything is happening when you click on "Show All Dependencies" button on Approve for Publish dialog 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2110]
### Expected behavior
It would be nice if the `Show All Dependencies` button is disabled after clicking (while it's performing things until all dependencies are displayed on the dialog) and some sort of spinner visible so the user knows something is happening, when it finishes showing all dependencies, the button can be enabled again (spinner gone)

### Actual behavior
Can't tell if anything is happening when you click on "Show All Dependencies" button on Approve for Publish dialog.  After clicking the button, the user cannot tell if anything is happening or what. 

### Steps to reproduce the problem
* Create a site using website_editorial
* Edit a few of the articles
* Go to the dashboard `My Recent Activity` widget and select all edited files
* Click on `Approve & Publish` from the context nav
* Click on the `Show All Dependencies` button, notice that it does not seem to do anything.  It would be nice if the button is disabled while it's doing its thing until all dependencies are shown and maybe even a spinner, then the button enabled after it's done displaying all the dependencies.

You can try creating a lot of articles, then get to the `Approval for Publish` dialog, expectation is it will take a while to display all dependencies, but, it doesn't look like anything happened after clicking the button.
Here's the steps for creating lots of articles:
* Create a site using Editorial BP
* On disk:
```
cd crafter-authoring/data/repos/sites/{SITE}/sandbox/site/website/articles
for i in `seq 1 30`; do cp -r 2017 new-articles-$i; done; git add .; git commit -m "Added new articles for testing."
```
* Wait until Studio picks up the changes (~10 seconds)
* Click on `Show In-Progress Items` from the `Items Waiting For Approval` widget in the dashboard
* Click on "Select All" to select all items
* Click on `Approve & Publish` from the context nav
* Click on the `Show All Dependencies` button.

<img width="891" alt="screen shot 2018-05-07 at 2 44 59 pm" src="https://user-images.githubusercontent.com/25483966/39718795-5b299360-5205-11e8-8510-eff2aaa54838.png">

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-55e772
Build Number: 55e772c3aa89cd48a1f6a8be383db77769327ce3
Build Date/Time: 05-07-2018 13:44:03 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by russdanner** [comment]
Additionally: 
Please move the show dependency button to the left side of the dialog (at the same level) 
The default selection should be on the submit button.

**Comment by jvega190** [comment]
3.0 https://github.com/craftercms/studio-ui/pull/830
2.5.x pending

**Comment by alhambrav** [comment]
Verified fixed.
