### ISSUE TITLE
[test-suite] Automate Verification that the application allows to delete the site created.

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2117]
Please automate  ID 5 in **Studio -> Sites**: Verify that the application allows to delete the site created.

**Setup**
1) Create a site using Web Site Editorial BP

**Steps**
1) Login as Admin
2) Go to sites page
3) Click on Delete icon on the right side of site created on preconditions and confirm the deletion

**Expected Output**
3) Site should be deleted from the sites list

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added on PR: https://github.com/craftercms/test-suite/pull/349

**Comment by alhambrav** [comment]
Verified.
