### ISSUE TITLE
[studio-ui] "Remote branch to pull" displayed is incorrect when pushing or pulling

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2118]
### Expected behavior
'Remote branch to pull' displayed should display branches returned by backend when pushing or pulling from the `Remote Repositories` in `Site Config`

### Actual behavior
'Remote branch to pull' displayed is incorrect when pushing or pulling from the `Remote Repositories` in `Site Config`

### Steps to reproduce the problem
* Login to Studio, click on the `Create Site` button
* Fill in the `Site Id` field
* Fill in the `Remote Git Repository Name` field
* Fill in the `Remote Git Repository Url` field
* Leave the `Remote Branch` field empty
* Fill in the Authentication type field and the corresponding fields required.
* In the `Options` field, select `Create site based on remote git repository`
* Click on the `Create` button  (Site will now be created)
* From the `Sidebar`, click on `Site Config` then click on `Remote Repositories`
* Click on the `pull` icon, notice the branch listed
* Click on the `push` icon, notice the branch listed

<img width="1352" alt="screen shot 2018-05-09 at 2 17 23 pm" src="https://user-images.githubusercontent.com/25483966/39832004-1045e282-5394-11e8-9171-5bdcc8e75c4a.png">

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/b107082510a3409b8a54ab0f9f4d50ca

#### Version
Studio Version Number: 3.0.11-SNAPSHOT-199be0
Build Number: 199be0e22e6e326c18a3f5ce7daa80c939dfc2a0
Build Date/Time: 05-09-2018 10:01:09 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/837

**Comment by alhambrav** [comment]
Verified fixed.
