### ISSUE TITLE
[studio-ui] form save and cancel buttons disappear after changing form size

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2119]
### Expected behavior
form controls should not disappear

### Actual behavior
for controls disappear
https://www.useloom.com/share/16d547e791e2420098d9d04ed1a9d5bb

### Steps to reproduce the problem
* open a form 
* use the lower right to change the size of the form
* scroll the form and then wait for a few seconds - the controls will disappear

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/838

**Comment by russdanner** [comment]
CONFIRMED
