### ISSUE TITLE
[studio-ui] Read-only forms should hide edit buttons

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#2120]
### Expected behavior
When viewing content in read-only mode, the rendered content form should not have any edit controls on it - they are confusing.

### Actual behavior
Edit controls appear. When pressed, they have no effect

### Steps to reproduce the problem
* right-click on a content item in the sidebar
* choose view
* some edit controls appear.

#### Version
Studio Version Number: 3.0.7-ff9c02

Build Number: ff9c027483e4c8991ae5c762384e16b42ff6f55f

Build Date/Time: 02-14-2018 17:48:39 -0500

<img width="1319" alt="screenshot 2018-05-10 08 12 23" src="https://user-images.githubusercontent.com/2083963/39869443-8828eda2-542b-11e8-80f2-a579f35d358f.png">

#### OS
mac
#### Browser
chrome

**Comment by dejan-brkic** [comment]
This is UI issue

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/871

**Comment by russdanner** [comment]
Confirmed
