### ISSUE TITLE
[studio] Cannot switch between assets being edited

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#2121]
### Expected behavior
When editing one asset, it should be possible to set it aside and start working on another one, and jump back and forth between them easily.

### Actual behavior
It is possible to minimize an asset being edited and open a new one, edit it, and then return back to the first asset, but it's not possible to swap back and forth between them.

### Steps to reproduce the problem
* open an asset and edit it
* click on the minimize / rollup icon in the bottom right-hand corner of the asset
* open a second asset and work with it
- try to return back to the first one without closing the second one

If the UI can maintain the state of 2 content items, it should be possible to swap between them...

#### Version
Studio Version Number: 3.0.7-ff9c02

Build Number: ff9c027483e4c8991ae5c762384e16b42ff6f55f

Build Date/Time: 02-14-2018 17:48:39 -0500
#### OS
mac
#### Browser
chrome

**Comment by sumerjabri** [comment]
Ticket to address this feature in the existing UI: #1488. Per my earlier comment, we'll address this fully in the UI.

**Comment by sumerjabri** [comment]
Replaced by https://github.com/craftercms/craftercms/issues/6206
