### ISSUE TITLE
[test-suite] Automate verification that the application allows to filter the number of sites displayed per page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2124]
Please automate ID 6 in **Studio -> Sites**: Verify that the application allows to filter the number of sites displayed per page

**Setup**
Create multiple sites using any BP (at least 4 test cases)

**Steps**
1) Login as Admin
2) Go to sites page
3) Set a valid value on the Sites per page input, E.g: 2
4) Review the list of sites and the number of them
5) Review the pagination 

**Expected Output**
3) The values should still be on the input when you leave the element
4) The number of sites displayed should match with the number provided on sites per page in the previous step
5) The pagination feature should be displayed with elements like < and > buttons

**Comment by luishernandezmonge** [comment]
@alhambrav Done, please check.

**Comment by alhambrav** [comment]
Verified.
