### ISSUE TITLE
[studio]  Unexpected error while executing deployment to environment store when publishing

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2125]
### Expected behavior
When an item or a scheduled item is published, there should be no errors in the logs

### Actual behavior
There is an error in the log when an item or a scheduled item is published, and then publishing is disabled

### Steps to reproduce the problem
* Create a site using website_editorial
* Edit one of the pages and save
* Publish the page, notice the error message in the tomcat log.  Publishing is also disabled after the error.

The same thing happens when scheduling publish.  Once the item is published, you get the error in the logs

```
[ERROR] 2018-05-10 15:38:30,914 [studioSchedulerFactoryBean_Worker-9] [job.DeployContentToEnvironmentStore] | Unexpected error while executing deployment to environment store for site "site3", number of items "1"
```

### Log/stack trace (use https://gist.github.com)
Here's the full log of the error:
https://gist.github.com/alhambrav/fcc4c0a24805f10b49e388850443cbf8

#### Version
Studio Version Number: 3.0.12-SNAPSHOT-59a6bd
Build Number: 59a6bd21d32f7dc86382e304891da8cf45422e81
Build Date/Time: 05-10-2018 14:32:42 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1133

**Comment by alhambrav** [comment]
Verified fixed.
