### ISSUE TITLE
[test-suite] Automate verification that the pagination on the sites list works properly

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2127]
Please automate ID 7 in **Studio -> Sites**: Verify that the pagination on the sites list works properly

**Setup**
1) Create multiple sites using any BP (at least 5 sites)

**Steps**
1) Login as Admin
2) Go to sites page
3) Set the `Sites per page` to `6`.
4) Review the pagination
5) Set the `Sites per page` to `2`.
6) Review the pagination
7) Click on any button of pagination, e.g: < or > or 2 Number

**Expected Output**
4) There should be no pagination since the number of site is less than the number in the `Sites per page` field
6) The following pagination should be listed: `|<|1|2|3|>|`
7) The pagination should display the next/previous/number page with the other sites and marked as selected the current page

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added to the next PR: https://github.com/craftercms/test-suite/pull/351

**Comment by alhambrav** [comment]
Verified.
