### ISSUE TITLE
[test-suite] Automate verification that the application allows to go to the preview page for a site when Preview link is clicked

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2128]
Please automate ID 8 in **Studio -> Sites**: Verify that the application allows to go to the preview page for a site when Preview link is clicked

**Setup**
1) Create a site using Web Site Editorial BP

**Steps**
1) Login as Admin
2) Go to sites page
3)Click on Preview link of the site recently created

**Expected Output**
3) Studio should redirects to the preview page for the site

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added to PR: https://github.com/craftercms/test-suite/pull/352

**Comment by alhambrav** [comment]
Verified.
