### ISSUE TITLE
[test-suite] Automate verification that the application allows to go to the dashboard page for a site when Dashboard link is clicked

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2129]
Please automate ID 9 in **Studio -> Sites**: Verify that the application allows to go to the dashboard page for a site when Dashboard link is clicked

**Setup**
1) Create a site using Web Site Editorial BP

**Steps**
1) Login as Admin
2) Go to sites page
3)Click on Dashboard link of the site recently created

**Expected Output**
3) Studio should redirect to the dashboard page for the site

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added to PR: https://github.com/craftercms/test-suite/pull/353

**Comment by alhambrav** [comment]
Verified.
