### ISSUE TITLE
[studio] It would be nice to be able to view what is in a publish package

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2133]
### Expected behavior
It would be nice to be able to view what is in a publish package without having to go to the database.

### Actual behavior
When you look at the Audit logs of published items from **Site Config**, it lists only the package id and not what items are inside the package  

### Steps to reproduce the problem
* Create a site using website_editorial
* Modify two articles, say `Men Styles For Winter` and `Women Styles for Winter` and save the changes
* Publish the two articles
* Go to **Site Config** -> **Audit**, notice the entry when the articles were published.  It lists the package id in the `Content`, but you can't tell what items are in the package.

<img width="1181" alt="screen shot 2018-05-14 at 3 36 53 pm" src="https://user-images.githubusercontent.com/25483966/40019305-da2a938a-578c-11e8-97cf-f57baff96c6c.png">

#### Version
Studio Version Number: 3.0.12-SNAPSHOT-86b9d6
Build Number: 86b9d65008887a0fe2dfa085127d68ed66442515
Build Date/Time: 05-14-2018 13:55:05 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
The publish/audit dashboard API should help here.

**Comment by sumerjabri** [comment]
The new dashboard and publishing queue fixes this.
