### ISSUE TITLE
[studio-ui] Adding a remote repository to a site, then pushing to the remote does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2134]
### Expected behavior
Adding a remote repository to a site (a bare git repo), then pushing to the remote should work.

### Actual behavior
Adding a remote repository to a site, then pushing to the remote does not work

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a bare git repo
* Go to **Site Config** -> **Remote Repositories**
* Click on **New Repository**, fill in the fields using the bare git repo created in the previous step
* Click on the **Push** icon, notice that it does not do anything and there is nothing in the logs too, to indicate if something went wrong or some other thing.

If the remote repo is bare, the branches of the remote will be null, we should return the default configured branch for Studio, so when the user clicks on the **Push** icon, it should list that configured branch

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the remote being added then trying to push:
https://www.useloom.com/share/30fad0f95104492896751f0fe39bcf3a

#### Version
Studio Version Number: 3.0.12-SNAPSHOT-86b9d6
Build Number: 86b9d65008887a0fe2dfa085127d68ed66442515
Build Date/Time: 05-14-2018 13:55:05 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@dejan-brkic ping me if you need any clarification.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1140

**Comment by alhambrav** [comment]
Verified fixed.
