### ISSUE TITLE
[studio] Create site from existing remote repository causes NPE

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2135]
### Expected behavior
User should be able to create a site from an existing repository

### Actual behavior
<img width="742" alt="screen shot 2018-05-14 at 6 21 01 pm" src="https://user-images.githubusercontent.com/169432/40026532-b9eede20-57a3-11e8-976a-c1a118d939a3.png">

### Steps to reproduce the problem
* try to create site based on a site from Github or other remote repository

### Log/stack trace (use https://gist.github.com)
No entry in the log

#### Version
Studio Version Number: 3.0.11E-d175a2
Build Number: d175a2e7ed157b148a31e16ca83053549ae90f53
Build Date/Time: 05-10-2018 17:22:04 -0400

#### OS
N/A
#### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1137

**Comment by russdanner** [comment]
CONFIRMED
