### ISSUE TITLE
[studio] Item_state and item_metadata tables are completely empty after rebuild DB API call

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2136]
### Expected behavior

After calling /api/1/services/api/1/repo/rebuild-database.json, the `item_state` and `item_metadata` tables should have all the existing files in Git.

### Actual behavior

The `item_state` and `item_metadata` tables are completely empty.

### Steps to reproduce the problem
* Create a site with editorial.
* Do a couple edits.
* Call `/api/1/services/api/1/repo/rebuild-database.json` (https://docs.craftercms.org/en/3.0/developers/projects/studio/api/repo/rebuild-database.html).
* Go to Site Config > Worflow States. You will see the page completely empty.
* In the command line, login into mysql and do a `SELECT *` for both `item_state` and `item_metadata`.

Notice how both tables are completely empty.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1138

**Comment by avasquez614** [comment]
Verified fix
