### ISSUE TITLE
[test-suite] Automate verification that application allows to create a site based on a blueprint then push to remote git repository

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2137]
Please automate ID 10 in **Studio -> Sites**: Verify application allows to create a site based on a blueprint then push to remote git repository

**Setup**
1) Create a bare repository testRepo.git
    To create a bare repository on disk: `$ git init --bare {repo_name}`
    example:
``` 
           $ cd `/Users/vita/myrepos/
           $ git init --bare testRepo
``` 

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" with the URL to the bare repo created (It should look something like this: `/Users/vita/myrepos/testRepo/`)
7) In the "Authentication Type:" select "None"
8) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
9) In the "Blueprint" field, select "Website_editorial"
10) Click on the "Create" button

We will now try to create a site using a repo that is not bare, we will use the repo used in the previous steps:

11) Go back to the `Sites` screen by clicking on the `Sites` icon at the top right of Studio
12) Click on "Create Site"
13) Fill in the "Site Id" field
14) Click on the "Link to upstream remote Git repository" to expand
15) Fill in the "Remote Git Repository Name" with "origin"
16) Fill in the "Remote Git Repository URL" with the URL to the repo used in step #6 (It should look something like this: `/Users/vita/myrepos/testRepo/`)
17) In the "Authentication Type:" select "None"
18) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
19) In the "Blueprint" field, select "Website_editorial"
20) Click on the "Create" button
 

** Expected Output**
2) `Create Site` dialog opens
4) "Link to upstream remote Git repository" is expanded (you see more fields to be filled in)
10) The "Create Site" dialog closes and the site created is in Preview
12) `Create Site` dialog opens
14) "Link to upstream remote Git repository" is expanded (you see more fields to be filled in)
20) A notification dialog should appear with the following message:
```
Unable to create site.  Please contact your system administrator.
Error: Remote repository not bare
```
<img width="563" alt="screen shot 2018-05-11 at 11 45 15 am" src="https://user-images.githubusercontent.com/25483966/39933390-d66e1542-5510-11e8-91f0-6627319dc29a.png">

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav added to PR https://github.com/craftercms/test-suite/pull/354

**Comment by alhambrav** [comment]
Verified.
