### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site based on a remote git repository - Authentication type: none

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2138]
Please automate ID 11 in **Studio -> Sites**: Verify that the application allows to create a site based on a remote git repository - Authentication type: none

**Setup**
1) Create a site using empty bp with SiteId "site1", take note of the path to the sandbox repo

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" with the URL to the sandbox repo of "site1" from the Setup step
7) In the "Authentication Type:" select "None"
8) In the "Options:" field, select "Create site based on remote git repository"
9) Click on the "Create" button

**Expected Output**
9) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done on PR: https://github.com/craftercms/test-suite/pull/355

**Comment by alhambrav** [comment]
Verified.
