### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site with Link to upstream remote git repository - Authentication type: basic

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2139]
Please automate ID 12 in **Studio -> Sites**: Verify that the application allows to create a site with Link to upstream remote git repository - Authentication type: basic

**Setup**
1) Setup a remote git repository, for example, you can create a repository in your Github account, and use that for the tests.  Follow the instructions here: https://help.github.com/articles/create-a-repo/ for creating a repo in your github account
2) Setup via a configuration file or command line prompt values for the: 
    (1) Remote Git Repository URL
    (2) Remote Git Repository Username
    (3) Remote Git Repository Password

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" 
7) In the "Authentication Type:" select "Basic"
8) Fill in the "Remote Git Repository Username"
9) Fill in the "Remote Git Repository Password"
10) In the "Options:" field, select "Create site based on remote git repository"
11) Click on the "Create" button

**Expected Output**
11) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
@alhambrav Done, you should configure your 
Remote Git Repository URL value
Remote Git Repository Username value
and Remote Git Repository Password value on the next properties on test-suite/src/test/resources/ExecutionConstants.properties file:
**crafter.gitrepository.url=yourgitrepourl
crafter.gitrepository.username=yourgitusername
crafter.gitrepository.password=yourgitpassword**

Changes added to PR: craftercms/test-suite#356

**Comment by luishernandezmonge** [comment]
Added on PR: https://github.com/craftercms/test-suite/pull/357

**Comment by alhambrav** [comment]
@luishernandezmonge There is an error when running the test.  Please take a look at the output attached and let me know if you see anything that I may have missed.

https://gist.github.com/alhambrav/dd6762c8c06a152f4abc116db5b74b0c

**Comment by luishernandezmonge** [comment]
already added a fix for this on https://github.com/craftercms/test-suite/pull/359, but currently we have an issue related to delete site: https://github.com/craftercms/craftercms/issues/2186

**Comment by alhambrav** [comment]
@luishernandezmonge Hi! The test case runs without failures, but, if I enter the incorrect git password, I was expecting the test to fail since it will not be able to login to the remote repo and would then not be able to create a site, and the test says that it passed.  I am changing the values in `test-suite/src/test/resources/ExecutionConstants.properties`, let me know if you see anything I missed.  Please check that the test fails when the username/password/git url is incorrect.  Thanks!

**Comment by alhambrav** [comment]
Verified.  To check if test will fail with incorrect credentials, a private repo is needed.
