### ISSUE TITLE
CRAFTERCMS-2153: RTE config rteStyleSheets tag cannot be empty 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#214]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Hi,

Looks these throws javascript errors and makes to not render content form properly =>

<rteStylesheets></rteStylesheets>
or even when tag is not present in the RTE configuration XML

seems the javascript is always looking for list items inside that tag, as you can see in the following piece of code 

		for(var i=0; i<rteConfig.rteStylesheets.link.length; i++) {
			var item = rteConfig.rteStylesheets.link[i];
			if(!item.appliesToChannel 
					|| (!channel && item.appliesToChannel == "default")
					|| (channel && item.appliesToChannel.indexOf(channel) != -1 )) {				
				stylesheets += ", " + item.url;
			}
		}

This code is not checking if its array or if its empty array with no stylesheets set, also is messing up more because also the service looks returning wrong empty array value as rteStylesheets: "", instead of just rteStylesheets: [],  that behaviour is causing to validate "link" as an array when it is not (is validating the link string native function  :)  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/link )

thanks,:
----------
Original JIRA Comments:
file: rte.js -> method _getCurrentStyleSheets
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2153
----------

**Comment by asotog** [comment]
will check this one, noticed this on my machine too
