### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site with Link to upstream remote git repository - Authentication type: Remote Git Repository Token

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2141]
Please automate ID 13 in **Studio -> Sites**: Verify that the application allows to create a site with Link to upstream remote git repository - Authentication type: Remote Git Repository Token

**Setup**
1) Setup a remote git repository, for example, you can create a repository in your Github account, and use that for the tests.  Follow the instructions here: https://help.github.com/articles/create-a-repo/ for creating a repo in your github account and create a token for your account by following these instructions: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

2) Setup via a configuration file or command line prompt values for the: 
    (1) Remote Git Repository URL
    (2) Remote Git Repository Token

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL"
7) In the "Authentication Type:" select "Remote Git Repository Token"
8) Fill in the "Remote Git Repository Token"
9) In the "Options:" field, select "Create site based on remote git repository"
10) Click on the "Create" button

**Expected Output**
10) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
Working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, you should configure your Remote Git Repository URL value and Remote Git Repository Token value on the next properties on test-suite/src/test/resources/ExecutionConstants.properties file:
**crafter.gitrepository.url=yourgitrepourl
crafter.gitrepository.token=yourgitrepotoken**

Changes added to PR: https://github.com/craftercms/test-suite/pull/356

**Comment by luishernandezmonge** [comment]
Added on PR https://github.com/craftercms/test-suite/pull/358

**Comment by alhambrav** [comment]
Waiting on ticket https://github.com/craftercms/craftercms/issues/2186 to verify

**Comment by alhambrav** [comment]
@luishernandezmonge Hi! The test case runs without failures, but, if I enter the incorrect git token, I was expecting the test to fail since it will not be able to login to the remote repo and would then not be able to create a site, and the test says that it passed.   I am changing the values in `test-suite/src/test/resources/ExecutionConstants.properties`, let me know if you see anything I missed.  Please check that the test fails when the token/git url is incorrect.  Thanks!

**Comment by sumerjabri** [comment]
Maybe it's a public repo? If the repo is public, the token won't be needed.

**Comment by alhambrav** [comment]
Verified. Private repo required to check if test will fail when credentials are incorrect.
