### ISSUE TITLE
[studio] Site Id after delete a site with link to remote bare repo cannot be used again to create a new site even if we deleted the previous site and remote repo folder. 

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2147]
### Expected behavior
User should be able to use the same SiteID and repo name (folder) when try again to create the site using remote repo folder (bare) because the previous site and repo folder is deleted.

### Actual behavior
User is not able to use the same SiteID and repo name (folder) when try again to create the site using remote repo folder (bare).

Watch the next video of the bugs steps and reproduction:
https://www.useloom.com/share/262d831f7805411bb07beaa46fefa9d9

Exception:
https://gist.github.com/luishernandezmonge/3112ab233ac5d71019d4a7664a58b94a

### Preconditions
* Go to any folder like the craftercms  folder and execute the next command to create a bare repo:
**git init --bare testingrepository**
take note about the repo location on the response (Something like this: 
Initialized empty Git repository in _/Users/luishernandez/Crafter_Project/craftercms_server/craftercms/testingrepository2/_ )

### Steps to reproduce the problem
1. Click on Create Site
2. Fill in the Site Id with **_testate_**
3. Click on Link to upstream remote Git repository
4. Fill in the Remote Git Repository Name with origin
5. Fill in the Remote Git Repository URL with the repo location of preconditions, e.g: **_/Users/luishernandez/Crafter_Project/craftercms_server/craftercms/testingrepository2/_**
6. Select Create Site based on a blueprint...
7. Click on the Create button.
8. Wait for a couple of mins and go back to sites page, later delete the previous created site.
9. Go to your folder of preconditions, e.g: **_/Users/luishernandez/Crafter_Project/craftercms_server/craftercms_** and delete the folder of the remote repo.
10. Repeat steps: 1 to 7 and noticed that the notification dialog is displayed with a SQL Exception as the next:
<img width="1439" alt="screen shot 2018-05-16 at 2 39 14 pm" src="https://user-images.githubusercontent.com/16946208/40147356-9715cba0-5926-11e8-94cc-a8701a78f123.png">

### Log/stack trace (use https://gist.github.com)
No log errors on tomcat log.
No entity on the database after delete the site on the step 8.

#### Version
Studio Version Number: 3.0.12-SNAPSHOT-d83ece
Build Number: d83ece5e19cdb3a16ceddb22b9a13c26b2034d7b
Build Date/Time: 05-16-2018 15:34:57 -0600
#### OS
Mac OSx, Linux
#### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1141

**Comment by luishernandezmonge** [comment]
Verified as Resolved.
