### ISSUE TITLE
[studio-ui] User is not able to select root page (index) of a given path with item form selector in browse mode

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2149]
### Expected behavior
If user specifies a data source pages with a browse path of /site/website or /site/website/foo they need a way (previously supported) to select the root item.  

### Actual behavior
The root item does not show up in the browse 

### Steps to reproduce the problem
https://www.useloom.com/share/6bebdf4dee694df8858e91160651703c
#### Version
Studio Version Number: 3.0.12-4abd8e
Build Number: 4abd8ef70d26c053521cac16d3d0c113465af499
Build Date/Time: 05-16-2018 12:22:33 -0400]

#### OS
N/a

#### Browser
N/a

**Comment by vestrada** [comment]
Hi,

Root item is added. Please see the following images:

![image](https://user-images.githubusercontent.com/11640613/40669271-c813a2e8-6323-11e8-8b52-bde9648e2556.png)

------

![image](https://user-images.githubusercontent.com/11640613/40669363-032e9824-6324-11e8-810b-f60e0825381b.png)

PR: https://github.com/craftercms/studio-ui/pull/839

**Comment by russdanner** [comment]
Confirmed
