### ISSUE TITLE
[studio] Extract the site name from the standard LDAP attribute memberOf

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2150]
Add the ability in Studio to specify a regex to extract the `siteId` from LDAP, but besides extracting the site extract the group names specific for that site too. E.g. 
For LDAP attribute `memberOf: crafter_editorial_Admin`
You could have a Studio configuration like this:
```
studio.security.ldap.userAttribute.siteId: memberOf
studio.security.ldap.userAttribute.siteId.regex: crafter_([a-zAZ]+)_([a-zAZ]+)
studio.security.ldap.userAttribute.siteId.matchIndex: 0
studio.security.ldap.userAttribute.siteId.groupName.matchIndex: 1
```
Studio would then add the user to the editorial site with the group Admin.
Default properties would be:
```
studio.security.ldap.userAttribute.siteId: crafterSite
studio.security.ldap.userAttribute.siteId.regex: .*
studio.security.ldap.userAttribute.siteId.matchIndex: 0
studio.security.ldap.userAttribute.siteId.groupName.matchIndex: 1
```
`studio.security.ldap.userAttribute.groupName` and `studio.security.ldap.userAttribute.groupName.regex` can still be used for backwards compatibility and in the case that you just want to specify groups for all sites.

**Comment by jrosler** [comment]
I just wanted to add some color commentary as well. The intent is that we don't want to have the customer extend the person object. In my case, where I'd like this, the customer has Active Directory and doesn't have open attributes and doesn't want to extend the schema, but does want to manage their users and groups in AD. So, having this implemented in groups only does half of what we need. It'd be cool to update the docs too. I don't see the groupName updates out at https://docs.craftercms.org/en/3.0/system-administrators/security/configure-ldap.html right now.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/2167
https://github.com/craftercms/studio/pull/1144

**Comment by avasquez614** [comment]
@dejan-brkic fix works, only comment is the values in the `studio-config-override.yaml`:

# LDAP site ID attribute name regex
# studio.security.ldap.userAttribute.siteId.regex: cn=Crafter_([a-zAZ]+),.*
# LDAP site ID attribute match index
# studio.security.ldap.userAttribute.siteId.matchIndex: 0
...
# LDAP groups attribute name regex
# studio.security.ldap.userAttribute.groupName.regex: cn=Crafter_([a-zAZ]+),.*
# LDAP groups attribute match index
# studio.security.ldap.userAttribute.groupName.matchIndex: 1

Shouldn't `studio.security.ldap.userAttribute.siteId.matchIndex` be 1 too?

**Comment by jrosler** [comment]
Personally, if I was going to create the groups and manage the sites, I'd probably do something more like <site>-<group>, so you might have people in mysite-author or mysite-reviewer. That way, you just need to manage the users in a LDAP group. I'd then have the sample regex handle that scenario for matching siteId to the first arg and groupName to the second one.

**Comment by avasquez614** [comment]
Updated description with new requirements.

**Comment by avasquez614** [comment]
Verified
