### ISSUE TITLE
[studio-ui] image picker fails update due to slow preview deployment

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2153]
### Expected behavior
image pricker should not fail image "selection" if the data source responds that the write was successful.

### Actual behavior
User uploads image
Data source reports success
Image picker tries to preview image, can't and fails the value update
User has to upload again

Checking the requests for the image you see it was a 404
Send the same request in a second or two and it's a 200

### Steps to reproduce the problem
* shut off preview deployer
* upload an image
 
#### Version
2.5.16

#### OS
n/a

#### Browser
n/a

**Comment by vestrada** [comment]
Per our conversation, the preview will show "unavailable" stylish text instead and it will accept the path to the real image.

**Comment by russdanner** [comment]
Please change text from "No Image Available" to "Image preview unavailable"

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/846

**Comment by russdanner** [comment]
Confirmed
