### ISSUE TITLE
[studio] Publish commits API is not working

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2159]
### Expected behavior
Publish specific commits from the repository using publish commits API:
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html

### Actual behavior
Error message in logs and publisher is disabled

### Steps to reproduce the problem
* Create a site from editorial blueprint
* perform edits directly on the file system and commit all changes
* Call publish commits API to publish commit from previous step
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html
* Publisher errors out and stops

#### Browser

**Comment by russdanner** [comment]
Confirmed
