### ISSUE TITLE
CRAFTERCMS-2155: Site component datasource fails to load due to a missing service call

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#216]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Site Component datasource is not loading and site-component.js is getting a 404 error from /api/1/site/context/id.json. The service URL is defined as below in the code:

	getContextIdUrl: "/api/1/site/context/id.json",
:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2155
----------

**Comment by russdanner** [comment]
Fixed

**Comment by hlim** [comment]
Fix confirmed.
