### ISSUE TITLE
[search] Certify 2.5.x Crafter CMS with Solr 6

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2160]
Certify that Crafter CMS 2.5.x will operate properly with the latest Solr 6.x

#### Version
2.5.16+

**Comment by avasquez614** [comment]
Putting here some comments:

* The `crafterSearch` core needs to be created manually.
* The deployer config preview has to be changed to specifically use the `crafterSearch` index.
* Studio search is not working right now because it's expecting to use the default core.
