### ISSUE TITLE
[studio] publish commit API site parameter should be site_id to match other apis

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2165]
### Expected behavior
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html

### Actual behavior
n/a
### Steps to reproduce the problem
n/a

### Log/stack trace (use https://gist.github.com)
n/a

#### Version
3.0.13

#### OS
n/a
#### Browser
n/a

**Comment by sumerjabri** [comment]
Please fix to match docs.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/544
https://github.com/craftercms/studio/pull/1146

**Comment by russdanner** [comment]
Confirmed
