### ISSUE TITLE
[test-suite] Automate verification of bulk upload assets

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2166]
Please automate  ID 46 in **Studio -> Content**  Verify Content: Bulk upload assets, folder containing nested folders and files is working

**Setup**
1) Create a site using Editorial BP
Prepare items to be bulk uploaded consisting of the following:
2) On disk, create a folder "bulk_image".  The "bulk_image" folder should contain nested folders and files
3) On disk, create a folder "bulk_txt". The "bulk_txt" folder should contain nested folders and files
4) On disk, create a folder "bulk_scripts". The "bulk_scripts" folder should contain nested folders and files.  
5) On disk, create a folder "bulk_templates". The "bulk_templates" folder should contain nested folders and files
6) On disk, create a folder "bulk_fonts". The "bulk_fonts" folder should contain nested folders and files
7) On disk, create a folder "bulk_js". The "bulk_js" folder should contain nested folders and files
8) On disk, create a folder "bulk_css". The "bulk_css" folder should contain nested folders and files  

Here's a sample:
![screen shot 2018-05-21 at 2 48 17 pm](https://user-images.githubusercontent.com/25483966/40324316-256a2148-5d06-11e8-9960-b60876e5941d.png)

The bulk items should be setup similar to the large trees in some of the test cases in our test suite
.  I used items already in the blueprint and sort of created the large trees.

**Steps**
1) Login to Studio and preview the site created in the setup
2) Open the Sidebar and navigate to "static-assets"
3) Expand the "static-assets" folder
4) Right click on "css" and select "Bulk Upload Assets"
5) Drag the folder "bulk_css" prepared in the setup to the bulk upload dialog
6) Click "Done"
7) Check the tomcat log
8) Back to the Sidebar, right click on "fonts" and select "Bulk Upload Assets"
9) Drag the folder "bulk_fonts" prepared in the setup to the bulk upload dialog
10) Click "Done"
11) Check the tomcat log
12) Back to the Sidebar, right click on "images" and select "Bulk Upload Assets"
13) Drag the folder "bulk_images" prepared in the setup to the bulk upload dialog
14) Click "Done"
15) Check the tomcat log
16) Back to the Sidebar, right click on "js" and select "Bulk Upload Assets"
17) Drag the folder "bulk_js" prepared in the setup to the bulk upload dialog
18) Click "Done"
19) Check the tomcat log
20) Back to the Sidebar, right click on "static-assets" and select "Bulk Upload Assets"
21) Drag the folder "bulk_txt" prepared in the setup to the bulk upload dialog
22) Click "Done"
23) Check the tomcat log
24) Back to the Sidebar, navigate to "templates" and expand it
25) Right click on the "templates" folder and select "Bulk Upload Assets"
26) Drag the folder "bulk_templates" prepared in the setup to the bulk upload dialog
27) Click "Done" 
28) Check the tomcat log
29) Back to the Sidebar, navigate to "scripts" and expand it
30) Right click on the "scripts" folder and select "Bulk Upload Assets"
31) Drag the folder "bulk_scripts" prepared in the setup to the bulk upload dialog
32) Click "Done" 
33) Check the tomcat log

**Expected Output**
4) The bulk upload dialog should open
5) Items inside the folder being uploaded should start appearing in the bulk upload dialog
6) The bulk upload dialog should close
7) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
8) The bulk upload dialog should open
9) Items inside the folder being uploaded should start appearing in the bulk upload dialog
10) The bulk upload dialog should close
11) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
12) The bulk upload dialog should open
13) Items inside the folder being uploaded should start appearing in the bulk upload dialog
14) The bulk upload dialog should close
15) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
16) The bulk upload dialog should open
17) Items inside the folder being uploaded should start appearing in the bulk upload dialog
18) The bulk upload dialog should close
19) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
20) The bulk upload dialog should open
21) Items inside the folder being uploaded should start appearing in the bulk upload dialog
22) The bulk upload dialog should close
23) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
25) The bulk upload dialog should open
26) Items inside the folder being uploaded should start appearing in the bulk upload dialog
27) The bulk upload dialog should close
28) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```
30) The bulk upload dialog should open
31) Items inside the folder being uploaded should start appearing in the bulk upload dialog
32) The bulk upload dialog should close
33) There should be no errors in the tomcat log and the last entry should be something like this:
```
[INFO] 2018-05-21 14:21:55,054 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Done syncing database with repository for site: mysite fromCommitId = ce8f440f4cc72be84deaeb56f3e1e6d7014124d3 with a final result of: true
[INFO] 2018-05-21 14:21:55,082 [studioSchedulerFactoryBean_Worker-9] [site.SiteServiceImpl] | Last commit ID for site: mysite is 91e1d09970acbd1f65fd5491ebc1894c193f219d
```

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by russdanner** [comment]
Hi Luis,
A great start here would be to test the back end API.  If it's difficult to test the browser's support, perhaps we can start with the API instead.

**Comment by luishernandezmonge** [comment]
@alhambrav Added to PR: https://github.com/craftercms/test-suite/pull/359, please verify this.

**Comment by alhambrav** [comment]
Verified.
