### ISSUE TITLE
CRAFTERCMS-2156: RTE overflows after a certain width

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#217]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Please see attached. The RTE is setup with 825px. If RTE width is wider than the allowed area, it should render below the label, center-aligned. :
----------
Original JIRA Comments:
RTE should always try to center itself in the form.  The label should move on top of the RTE when the RTE takes up too much space
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2156
----------

**Comment by asotog** [comment]
will start work on this

**Comment by asotog** [comment]
was able to troubleshoot it by changing the rte configuration to width 100% and adding max width from rte initialization based on the configured width PR here https://github.com/craftercms/studio2-ui/pull/98
