### ISSUE TITLE
[studio] Rejecting/Canceling workflow for one item does not cancel workflow for all the other items in the publish package

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2171]
### Expected behavior
Rejecting/Canceling workflow for one item should cancel workflow for all the other items in the publish package

### Actual behavior
Rejecting/Canceling workflow for one item does not cancel workflow for all the other items in the publish package

### Steps to reproduce the problem
* Create a site using website_editorial
* Create a user author
* Login as user author and edit 3 articles.
* Open the dashboard and select all 3 edited articles from the `My Recent Activity` widget
* Click on `Request Publish` from the context nav
* Logout user author
* Login as user admin
* Go to the dashboard 
* Select one item from the `Items Waiting For Approval` widget
* Click on `Reject` from the context nav, notice that only the item rejected goes back to the `Edited` workflow state

<img width="1389" alt="screen shot 2018-05-22 at 11 15 48 am" src="https://user-images.githubusercontent.com/25483966/40372155-1fcb1524-5db2-11e8-895e-91592f41a830.png">

The same thing happens when an author requests for publish multiple articles.  After requesting publish and the author chooses to edit one of the items in the request, workflow is not cancelled for all the other items included in the `Request Publish` (publish package)

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing publish package not cancelled after item is rejected:
https://www.useloom.com/share/53a4966dfb8a48a38238990beec125d9

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-a214ce
Build Number: a214ce90002b304bc639c83b8e86d1674e1a183e
Build Date/Time: 05-22-2018 07:31:44 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@russdanner please validate requirements and the fact that we're pursuing this in 3.0.x. If acceptable, please assign to Dejan, if not, assign to me with your comments.

**Comment by sumerjabri** [comment]
@russdanner please validate as this might be covered in package publishing. If not, we can move to 3.2

**Comment by russdanner** [comment]
This is not covered and needs to be addressed

**Comment by sumerjabri** [comment]
We must extend the experience/UI to allow the user to view the whole Workflow Package and approve each item before the package can move forward.
The back can support this but must extend API to allow this experience.

**Comment by sumerjabri** [comment]
This will be addressed by the new publisher.
