### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site with Link to upstream remote git repository - Authentication type: Remote Git Repository Private Key

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2174]
Please automate ID 14 in **Studio -> Sites** - Verify that the application allows to create a site with Link to upstream remote git repository - Authentication type: Remote Git Repository Private Key

**Setup**
1) Create a bare git repository in your local directory.  We will be using localhost for this test. 
To create a bare repository on disk: $ git init --bare {repo_name}
example:
```
           $ cd `/Users/vita/myrepos/
           $ git init --bare testRepo
```
For windows:
```
        > cd C:\Users\IEUser\repos
        > git init --bare testRepo
```
For more info on bare repositories, see: https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-init
2) Setup your ssh keys.  
To generate ssh keys:
```
    $ ssh-keygen -b 4096 -t rsa
```
We will use your private key to access the repository you created earlier via ssh. For more info on generating your ssh keys, see https://www.ssh.com/ssh/keygen/
3) Setup via a configuration file or command line prompt values for the following:
    (1) Remote Git Repository URL
    (2) Remote Git Repository Private Key

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" with the ssh git URL to the bare repo created in the setup (It should look something like this: `ssh://vita@localhost/Users/vita/temp/myrepos/testRepo3` and on windows, should look something like this: `ssh://IEUser@localhost:/Users/IEUser/repos/testRepo`)
7) In the "Authentication Type:" select "Remote Git Repository Private Key"
8) Fill in the "Remote Git Repository Private Key"
9) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
10) In the "Blueprint" field, select "Website_editorial"
11) Click on the "Create" button

**Expected Output**
11) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav did you have any idea of how the **Remote Git Repository URL** value will look like for windows case? I mean, I'm already configured my local ssh on windows and it works ok executing **ssh username@localhost** on terminal. But when I try to do this test case manually, it fails creating and pushing to the repo:

examples:
- with
 **ssh://username@localhost/c:\Users\username\myrepos\mytestbare\**
**ssh://username@localhost\\c:\\Users\\username\\myrepos\\mytestbare**
**ssh://username@localhost\c:\Users\username\myrepos\mytestbare**
Studio returns:
_Unable to create site. Please contact your system administrator.
Error: Remote repository not found_
- with
 **ssh://username@localhost:c:/Users/username/myrepos/mytestbare/** 
and
**ssh://username@localhost:c:\Users\username\myrepos\mytestbare\**
Studio returns:
_Unable to create site. Please contact your system administrator.
Error: Internal server error: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command_

**Comment by luishernandezmonge** [comment]
@alhambrav I'm not really sure if this scenario can be reproduced on a windows side + OpenSSH. I'm searching and researching for something similar on windows and I found nothing related. I tested my ssh connection and it works ok. But when I try to create the site pushing to bare repo, it does not work.
Please validate if this scenario can be reproducible on windows? and if it is please specify steps for windows site, if not, we need to find the way to omit this on windows executions.

**Comment by alhambrav** [comment]
**Note**
Accessing the repo on the drive in Windows does not work yet, so this test case will fail when run.

@luishernandezmonge Please submit a pull request for your changes for now.  We will leave this ticket open and investigate some more on how to access the repo in windows to get the test case to run properly in windows.

**Comment by alhambrav** [comment]
@luishernandezmonge 
Test Steps have been updated for the windows example for localhost.
Here's a summary:
1. Create a bare repo
 ```
> cd C:\Users\IEUser\repos
> git init --bare testRepo
```
You now have a repo located in `C:\Users\IEUser\repos`
2. Create a site in Studio and use the following git url:
`ssh://IEUser@localhost:/Users/IEUser/repos/testRepo`

If you get an error about the `git-upload-pack`, make sure that the `bin` folder containing that command is in your `Path` environment variable.  For my setup, I had to add the following to my `Path` environment variable: `C:\Program Files\Git\mingw64\bin`

**Comment by luishernandezmonge** [comment]
@alhambrav this work ok with configuration of above for windows 10 enterprise edition since build 17134 has installed and configured OpenSSH by default (already test it), but... my question is... how about the other supported windows versions (on https://docs.craftercms.org/en/3.0/system-administrators/requirements-supported-platforms.html#supported-platforms): Windows 7 does not have openSSH and the Windows Server versions have a limitation with the Edge & IE explorer web driver for Selenium (Microsoft web driver does not support windows server builds).

I think that currently this automated works ok on a fully configured (with openSSH) windows 10 enterprise build 17134.  and the update of the steps mentioned on your comments is already merged on test-suite.

**Comment by luishernandezmonge** [comment]
@alhambrav I'm tested on windows 7 Enterprise version from Microsoft page (last build SP1) and the OpenSSH is installed by default and it works ok. Will continue checking scenario and let you know when you can test this ticket on test-suite.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, ready for review.

**Comment by alhambrav** [comment]
@luishernandezmonge 
What properties do I need to fill in for this test?

Is it possible to put comments in the ExecutionConstants.properties file?  I think it would be clearer to new users what the properties listed are for if there are comments.  If it's not possible to have comments in multiple lines, maybe just give a good description at the top of the file on what the properties below are used for.

Also, it would be nice to group together properties, example:
```
#Tue Jun 19 10:27:27 CST 2018
#Add meaningful description on purpose of property below
crafter.api.smtpport=2525
crafter.numberofattemptsforelementdisplayed=4

crafter.defaulttimeout=35

#Studio credentials
crafter.username=admin
crafter.password=admin

#API credentials
crafter.api.password=admin
crafter.api.username=admin

#Bulk upload
crafter.bulkupload.amountoftestfolderstogenerate=3
crafter.bulkupload.amountoflastlinestoreadonlog=75
crafter.bulkupload.syncprocesstimeout=3000

general.currentsiteid=testsitehixwm

#Remote repository fields
crafter.gitrepository.remotegiturl=none
crafter.gitrepository.remotegiturlforaddrepositorytosite=none
crafter.gitrepository.localrepositoryname=testrepository
crafter.gitrepository.token=none
crafter.gitrepository.password=none
crafter.gitrepository.localsshprefix=none
crafter.gitrepository.url=none
crafter.numberofattemptsforlogfileupdate=4
crafter.gitrepository.username=none
```

**Comment by luishernandezmonge** [comment]
@alhambrav only you need to fill this property:
crafter.gitrepository.localsshprefix=none with something like this **ssh://youruser@localhost**
note: test-suite will automatically create a repository folder under **UserHomeDirectory/craftercms_testrepos/testreponame**
So, the rest of the ssh://youruser@localhost:/pathtobare is provided by test suite on execution.

**Comment by alhambrav** [comment]
Verified.
