### ISSUE TITLE
[studio] support publishing to lower environments as waypoints on the path to Live

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2176]
### Expected behavior
Many organizations have 1 or more environments (in addition to preview) that they use to proof work and with their team and co-workers outside of the web group.  Crafter Studio should allow a author to publish to one of these environments.  

The content is not live until it makes it to Live.
Deploying to live will also deploy to the preceding environment(s)

### Actual behavior
N/A

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A
#### Version
3.x

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/2182
https://github.com/craftercms/studio/pull/1149

**Comment by sumerjabri** [comment]
We will only support 1 intermediate environment. This will help us tool the system better in the future as we track if items have been staged or not. Supporting an arbitrary number of intermediate environments, while attractive in its flexibility, will not allow for extended tooling yields little benefit to users.

**Comment by russdanner** [comment]
Confirmed

**Comment by sumerjabri** [comment]
Code has been changed, must re-test.

**Comment by russdanner** [comment]
All tests so far check out except deploying on a schedule to staging leaves the object in scheduled status. That doesn't make sense.  Status should change to in progress again after publish (the the schedule and the workflow are over)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1158

**Comment by russdanner** [comment]
Confirmed
