### ISSUE TITLE
[docs] List available macros for Data Sources

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2179]
https://docs.craftercms.org/en/3.0/developers/content-modeling.html?highlight=macros. The `Item Specific Dependency` section mentions certain macros that can be used in the `Repository Path` of `Upload Images`, like  like `yyyy`, `mm` and `dd`. Please make sure all the macros that are available to Data Sources are listed, either on the Data Sources section of this page or on the specific page for each Data Source.

**Comment by russdanner** [comment]
Currently supported macros

`            processPathsForMacros: function(path) {
                var model = this.form.model;

                if(path.indexOf("{objectId}") != -1) {
                    path = path.replace("{objectId}", model["objectId"]);
                }

                if(path.indexOf("{objectGroupId}") != -1) {
                    path = path.replace("{objectGroupId}", model["objectGroupId"]);
                }

                if(path.indexOf("{objectGroupId2}") != -1) {
                    path = path.replace("{objectGroupId2}", model["objectGroupId"].substring(0,2))
                }

                /* Date macros */
                var currentDate = new Date();
                if(path.indexOf("{year}") != -1) {
                    path = path.replace("{year}", currentDate.getFullYear());
                }

                if(path.indexOf("{month}") != -1) {
                    path = path.replace("{month}", ("0" + (currentDate.getMonth() + 1)).slice(-2));
                }

                if(path.indexOf("{parentPath}") != -1) {
                    path = path.replace("{parentPath}", CStudioAuthoring.Utils.getQueryParameterByName("path").replace(/\/[^\/]*\/[^\/]*\/([^\.]*)(\/[^\/]*\.xml)?$/, "$1"));
                }

                if(path.indexOf("{yyyy}") != -1) {
                    path = path.replace("{yyyy}", currentDate.getFullYear());
                }

                if(path.indexOf("{mm}") != -1) {
                    path = path.replace("{mm}", ("0" + (currentDate.getMonth() + 1)).slice(-2));
                }

                if(path.indexOf("{dd}") != -1) {
                    path = path.replace("{dd}", ("0" + (currentDate.getDate())).slice(-2));
                }
`

**Comment by russdanner** [comment]
ObjectID is a GUID
objectGroupId is the first 4 chars of the ObjectID
objectGroupId2 is the first 2 chars of the ObjectID

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/547

**Comment by avasquez614** [comment]
Verified
