### ISSUE TITLE
CRAFTERCMS-2158: New indicator gets removed after edit in new site

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#218]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: * Create a site from blueprint
* Note pages show with '*' indicator
* Edit the page
* Note '*' indication is removed even through object has never been deployed and should still have the indication
* Refresh page and indicator shows.  
:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2158
----------

**Comment by russdanner** [comment]
Vero this has to do with the auto update of the icon in the tree etc....  it goes away and then on refresh is added back

**Comment by vestrada** [comment]
Closed
