### ISSUE TITLE
[studio-ui] Error cropping image on upload

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2183]
### Expected behavior
There should be no error when cropping an image on upload

### Actual behavior
There is an error `No such property: result for class: crop-image_get` when cropping an image on upload

### Steps to reproduce the problem
* Create a site using headless_blog 
* Navigate to `items/authors`
* Right click on `Joe Bloggs (Guest)` then click on `Edit` 
* In the `Photo` field, click on the `Replace` button and select `Upload Images`
* Select an image from your desktop and click on the `Upload` button
* The `Crop Image` dialog should appear, click on the `Crop` button, notice the notification dialog that pops up saying: `No such property: result for class: crop-image_get`
<img width="387" alt="screen shot 2018-05-30 at 9 54 34 am" src="https://user-images.githubusercontent.com/25483966/40724891-21a11f6c-63f0-11e8-8231-f88abb85c6ca.png">

Notice the error in the tomcat log too. 

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/b5b3f5f482614a709fac5bf6965baa95

Here's the error message in the tomcat log:
https://gist.github.com/alhambrav/9fe9f68ef1760a22d1e8b142a31d8fc5

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-30-2018 09:17:56 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Hi Dejan,
This is a BE ticket.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1153

**Comment by alhambrav** [comment]
Verified fixed.
