### ISSUE TITLE
[studio-ui] Inconsistent box/scroll bar for the "Site Config" -> "Configuration" sample and configuration box

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2184]
### Expected behavior
It would be nice to have consistent scroll bars/box size for the configuration and the sample box.

### Actual behavior
Inconsistent scroll bars/box size for the "Site Config" -> "Configuration" sample and configuration box.  The scroll bar used for the configuration box is the scroll bar for the whole browser, while the sample box has it's own scroll bar

### Steps to reproduce the problem
* Create a site
* Click on **Site Config** -> **Configuration**
* Select any of the configurations available from the dropdown.  For our example, I have selected **Sidebar Configuration**.  Notice that the configuration box has a scroll bar, but, when you scroll, it's the browser scroll bar that moves.  Notice also that the line numbers goes out of the configuration box.

<img width="1287" alt="screen shot 2018-05-30 at 10 26 27 am" src="https://user-images.githubusercontent.com/25483966/40726714-51c21c60-63f4-11e8-8311-2f7a229d82ca.png">

* Click on the `View Sample` button.  Notice how the sample box has it's own scroll bar that actually moves and the box is a fixed size, while the configuration box displays the whole configuration in one big box (sample and configuration box are different sizes)

<img width="1287" alt="screen shot 2018-05-30 at 10 20 29 am" src="https://user-images.githubusercontent.com/25483966/40726987-e95b18f6-63f4-11e8-997f-ad6a6e8e438e.png">

It would be nice to make things consistent in the `Configuration` screen

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the configuration box and sample and trying to scroll:
https://www.useloom.com/share/54c5c77785d446049edbd0d9592be774

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-30-2018 09:17:56 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/858

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/867

**Comment by vestrada** [comment]
Hi @alhambrav 

Can you check this? Please let me know.
Thanks :)

**Comment by alhambrav** [comment]
Verified fixed.
