### ISSUE TITLE
[studio] RTE does not allow saving HTML Unicode UTF-8 followed by the words "site" or "path"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2185]
### Expected behavior
RTE should allow saving all characters

### Actual behavior
RTE does not allow saving HTML Unicode UTF-8 followed by the words "site" or "path".  It also doesn't allow saving saving "site" or "path" in between tags such as: `<span class="na">path</span>`

### Steps to reproduce the problem
* Create a site using the empty bp
* Edit the `Home` page by clicking on `Edit` in the context nav
* In the body, click on the `Edit Code` icon on the RTE bar and copy/paste the following:
    - `<span class="na">path</span>`
* Click on the `Save and Close` button, notice the error message notice and the error message in the logs
<img width="381" alt="screen shot 2018-06-01 at 6 48 47 am" src="https://user-images.githubusercontent.com/25483966/40837342-35ff654e-6568-11e8-9393-3f892e45431f.png">

* Here's another example.  Copy and paste the following:
`<a href="/studio/preview/#/?page=/api/1/services/pokemon.json&amp;site=poledex">http://localhost:8080/studio/preview/#/?page=/api/1/services/pokemon.json&amp;site=poledex</a>` 

<img width="379" alt="screen shot 2018-06-01 at 7 00 33 am" src="https://user-images.githubusercontent.com/25483966/40837757-83eaaae2-6569-11e8-9378-4e3022d1b66f.png">
 
* You can also try the following and see error messages too:
    - `<p>path</p>`
    -  `<p>I will display &permil;site</p>`
    - `<p>I will display &ldquo;site&rdquo; quotes.</p>`
    - or try any of the other HTML Unicode UTF-8 followed by the words "site" or "path"

### Log/stack trace (use https://gist.github.com)
Error for the first example:
https://gist.github.com/alhambrav/1e859436b59ab12846f6246ef5cfd5bb
Error for the second example:
https://gist.github.com/alhambrav/f64ab0eb3d1e5e694d66a99ce0aaba8c

Here's a short clip:
https://www.useloom.com/share/6051712e247e4b39aa87620ea1688b36

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-31-2018 10:56:13 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Hi Dejan,
Per our conversation this will be worked on BE

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/1152

**Comment by alhambrav** [comment]
Verified fixed.
