### ISSUE TITLE
[studio-ui] Delete site is not working, studio hangs on Deleting site progress animation (something wrong on API call)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2186]
### Expected behavior
Studio should deletes the site without problems on with the api calls.

### Actual behavior
The site is not deleted and studio hangs on Deleting site progress animation (something wrong on API call).
The next is returned on the api call response:
**{"message":"Invalid parameter(s): [site_id]"}**
 
Watch the next video:
https://www.useloom.com/share/ab7330d6023742728a8e8f310381e1c1

**Note:** Same happens with api call using rest client like insomnia, see the next image:
<img width="1323" alt="screen shot 2018-06-01 at 9 28 58 am" src="https://user-images.githubusercontent.com/16946208/40849093-443e6554-657e-11e8-8f5b-5c5456264921.png">

### Steps to reproduce the problem
* Create a couple of sites using any Blueprint or from remote repo
* Go to sites list and try to delete one of the sites created
* Open your developer console on the Network tab and review the post request and response for delete-site.json call.

### Log/stack trace (use https://gist.github.com)
No errors on log

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 06-01-2018 08:31:03 -0600
#### OS
Mac OSx
#### Browser
Chrome

**Comment by alhambrav** [comment]
@dejan-brkic, I think there is a typo in the `delete-site.post.groovy` file, line number 39 and line number 41, which I think should say `siteId` instead of just `site`.

**Comment by dejan-brkic** [comment]
@alhambrav yes you are right. This API was one of few that actually did not follow any naming convention, so I made a typo.

**Comment by vestrada** [comment]
Hi!

This is a back-end ticket. UI is sending the correct information according to documentation (https://docs.craftercms.org/en/3.0/developers/projects/studio/api/site/delete-site.html)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1150

**Comment by luishernandezmonge** [comment]
Verified as resolved.
