### ISSUE TITLE
[studio-ui] An extra level is created when creating a new page, first doing a "Save Draft" then "Save and Close"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2188]
### Expected behavior
No extra levels should be created when creating a new page, first doing a `Save Draft` then `Save and Close`
 
### Actual behavior
An extra level is created when creating a new page, first doing a `Save Draft` then `Save and Close`

### Steps to reproduce the problem
* Create a site using the empty bp 
* Open the Sidebar and right click on `Home`
* Select `New Content`, then select `Entry`
* Fill in the required fields in the form, I'll name the page `foo`
* Click on `Save Draft`, a notification will pop up that `Draft Save Completed`.  Notice also the location of your new content in the Sidebar:
<img width="1196" alt="screen shot 2018-06-01 at 10 21 10 am" src="https://user-images.githubusercontent.com/25483966/40845762-a5785a4e-6585-11e8-83d9-81e8c5f767b0.png">
* Now, click on `Save and Close`, notice there's still a draft page in the Sidebar, and your content is saved one level below where you created the content
<img width="1204" alt="screen shot 2018-06-01 at 10 23 06 am" src="https://user-images.githubusercontent.com/25483966/40845921-14a72ca6-6586-11e8-9241-bd447ac9c303.png">

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the steps described above:
https://www.useloom.com/share/8f2e16bbac21443082a32ae4460a150a

The above clip also shows where the new content is supposed to be if you don't save a draft first before saving it.

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-31-2018 10:56:13 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/844

**Comment by alhambrav** [comment]
Verified fixed.
