### ISSUE TITLE
[studio] Rejecting an item in the Approved Scheduled Items list removes the scheduled state but the item remains in list

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2190]
### Expected behavior
Item/workflow should be canceled when an item is rejected.
As a result,
 the items should be removed from the approved scheduled list

### Actual behavior
Item(s) stay in the approved scheduled list after being rejected:
<img width="1114" alt="screen shot 2018-06-04 at 3 45 42 pm" src="https://user-images.githubusercontent.com/169432/40937985-6df5a3ac-680e-11e8-948b-237b7820c4e1.png">

### Steps to reproduce the problem
* sign in an author, edit and item and request a publish on a later date 
* sign in as admin and approve it
* Make an edit to an approved item OR reject it (both routes must work)
* Note the workflow is not cancelled and the items remain on the scheduled dashboard

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-30-2018 17:34:26 -0400

#### OS
n/a
#### Browser
n/a

**Comment by dejan-brkic** [comment]
This use case works as expected:
* sign in an author, edit, and item and request a publish at a later date
* sign in as admin and approve it
* Make an edit to an approved item and save (if not saved it will not cancel workflow)

The other use case is canceling workflow (states), but it is not removing the item from publishing queue
* sign in an author, edit, and item and request a publish at a later date
* sign in as admin and approve it
* reject it

@russdanner @sumerjabri 
The real question is if the second use case is a valid use case (item is already approved, why rejecting after being approved)?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1151

**Comment by russdanner** [comment]
Confirmed
