### ISSUE TITLE
[studio-ui] approval dialog should indicate when selected items have different publish items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2191]
### Expected behavior
Users need a clear warning when they have selected multiple items for approval from the waiting for approval items dashboard that have different requested publish dates.

"The items you have selected for approval were submitted with different requested publish dates."

### Actual behavior
The dialog shows an error that says the user must select a date.

### Steps to reproduce the problem
* Login as author and submit several items, each scheduled on a different day
* Login as admin and select all items, click approve for publish
* Note dialog does not clearly indicate to the user that there is an issue

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-30-2018 17:34:26 -0400

#### OS
N/a
#### Browser
N/a

**Comment by vestrada** [comment]
@russdanner :
- Which text you want instead of: "Please select date and time"?
![image](https://user-images.githubusercontent.com/11640613/41875045-eda9779e-7886-11e8-93de-41719899b115.png)
- Is it a good scenario that the user can select a specific date for items with different requested dates?

**Comment by russdanner** [comment]
I think you should leave the existing message because it's an accurate error that the user must correct.  The problem is they dont know why the got it.

I think we should add a warning in the dialog that says:
"The items you have selected for approval were submitted with different requested publish dates/times."

**Comment by russdanner** [comment]
<img width="978" alt="screen shot 2018-06-25 at 5 13 32 pm" src="https://user-images.githubusercontent.com/169432/41876374-951e9a7c-789b-11e8-8bba-836dbfb8580a.png">

**Comment by russdanner** [comment]
Confirmed
