### ISSUE TITLE
[studio-ui] Approvers should be able to sort approval queue by publish date

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2192]
### Expected behavior
Publish date time in Items waiting for Approval should be sortable

### Actual behavior
The column is not sortable

### Steps to reproduce the problem
N/a

### Log/stack trace (use https://gist.github.com)
N/a

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-8f3578
Build Number: 8f35782f1f4e5dd31353e1994597ba91a9a15e6c
Build Date/Time: 05-30-2018 17:34:26 -0400

#### OS
N/a

#### Browser
N/a

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/854

**Comment by russdanner** [comment]
Confirmed
