### ISSUE TITLE
[studio-ui] Validation is not the correct when all values are provided for creation of New Page-Category Landing page and the category dropdown is left as default

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2196]
### Expected behavior
No validation dialog should be displayed because the Category dropdown has a default value selected.

### Actual behavior
The validation dialog is displayed even if all the values are provided and the Category dropdown is left as default.

Watch the next video:
https://www.useloom.com/share/6a695bc9f3f84c948e0432acf693910e

### Steps to reproduce the problem
* Create a site using website editorial BP
* Go to dashboard and expand Pages/Home
* Right click and try to create a New Page - Category Landing page.
* Provide all required values on inputs click on "Save and Close"
**Notice that the validation dialog is displayed because of the Category dropdown does not change of value (this is not correct because it already have a default value selected)**

### Log/stack trace (use https://gist.github.com)
No log errors on this.

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-06-2018 10:29:36 -0600
#### OS
Mac OSx, Linux, Windows10
#### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/847

**Comment by luishernandezmonge** [comment]
Verified as resolved.
