### ISSUE TITLE
[studio-ui] spinner status on items deployed to staging is never removed

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2198]
### Expected behavior
spinner over the file should be removed once the operation has completed

### Actual behavior
I think the spinner is waiting for the state to change to live.  It never does - an item in staging is not live.

### Steps to reproduce the problem
* configure staging environment  
* deploy item to staging
* note on dashboard and sidebar spinner is never removed.

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/852

**Comment by russdanner** [comment]
Spinner never goes away for me even in incognito
https://www.useloom.com/share/2149fa62e88b4913a79db75fac19128b

Studio Version Number: 3.0.14-SNAPSHOT-97cb72
Build Number: 97cb72fde437ba2ec8b11d55425c90713309ec64
Build Date/Time: 06-12-2018 21:39:54 -0400

**Comment by russdanner** [comment]
Confirmed
