### ISSUE TITLE
[studio-ui] approved scheduled items should include an environment column

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2199]
### Actual Behavior
"Approved Scheduled Items" dashboard doesn't show the environment that the item has been approved for.

### Expected behavior
"Approved Scheduled Items" dashboard should add a column that shows the environment that the item is approved for. See screenshot (the `Server` column should be replaced with `Environment`).

<img width="1055" alt="screen shot 2018-06-08 at 2 58 04 pm" src="https://user-images.githubusercontent.com/169432/41175889-979c7a7a-6b2c-11e8-9d01-db6b0c91eb23.png">

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
@vestrada @dejan-brkic Change "Server" to "Environment" and use the git branch to help populate that field.

**Comment by sumerjabri** [comment]
@dejan-brkic please update the API to return the `environment` then assign to @vestrada to wire into the UI.

**Comment by sumerjabri** [comment]
@dejan-brkic please also send PR/update for docs to be up to date including the examples: https://docs.craftercms.org/en/3.0/developers/projects/studio/api/deployment/get-scheduled-items.html

**Comment by dejan-brkic** [comment]
Added environment property to get scheduled items response
PR:
https://github.com/craftercms/docs/pull/552
https://github.com/craftercms/studio/pull/1155

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/851

**Comment by russdanner** [comment]
Confirmed
Also confirmed that once approved the environment can be modified
