### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site with Link to upstream remote git repository(gitlab, etc) - Authentication type: Remote Git Repository Private Key

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2200]
Please automate ID  15 in **Studio -> Sites** - Verify that the application allows to create a site with Link to upstream remote git repository(gitlab, etc.) - Authentication type: Remote Git Repository Private Key

**Setup**
1) Setup your ssh keys.  We will use your private key to access the repository we will create on the next step. For more info on generating your ssh keys, see https://www.ssh.com/ssh/keygen/
2) Create a private bare repo in gitlab/github and setup your keys.  See https://help.github.com/articles/connecting-to-github-with-ssh/ or https://docs.gitlab.com/ee/gitlab-basics/create-your-ssh-keys.html
3) Setup via a configuration file or command line prompt values for the following:
    (1) Remote Git Repository URL
    (2) Remote Git Repository Private Key

**Steps**
1) Login to Studio and go to the "Sites" screen 
2) Click on "Create Site" 
3) Fill in the "Site Id" field 
4) Click on the "Link to upstream remote Git repository" to expand 
5) Fill in the "Remote Git Repository Name" with "origin" 
6) Fill in the "Remote Git Repository URL" with the URL in the setup
7) In the "Authentication Type:" select "Remote Git Repository Private Key" 
8) Fill in the "Remote Git Repository Private Key" 
9) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
10) In the "Blueprint" field, select "Website_editorial"
11) Click on the "Create" button
We'll now create a site based on the remote repo we just created:
12) Click on the "Sites" icon at the top right of Studio
13) Click on "Create Site"
14) Fill in the "Site Id" field 
15) Click on the "Link to upstream remote Git repository" to expand 
16) Fill in the "Remote Git Repository Name" with "origin2" 
17) Fill in the "Remote Git Repository URL" with the URL in the setup 
18) In the "Authentication Type:" select "Remote Git Repository Private Key" 
19) Fill in the "Remote Git Repository Private Key"
20) In the "Options:" field, select "Create site based on remote git repository"
21) Click on the "Create" button 

**Expected Output**
11) The "Create Site" dialog closes and the site created is in Preview
21) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added on PR: https://github.com/craftercms/craftercms/issues/2200

**Comment by luishernandezmonge** [comment]
For this you should set your repository url on the next property:
crafter.gitrepository.remotegiturl=git@gitlab.com:youruser/yourrepo.git

And copy the content of your private key (generated for github or gitlab) into the file:
src/test/resources/RemoteGitPrivateKeyContent.txt

**Comment by alhambrav** [comment]
Verified.
