### ISSUE TITLE
[studio] Support per site staging environment support and configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2201]
### Expected behavior
Each site in Crafter Studio should be able to activate and label live and staging publishing environments.

### Current behavior
Today staging is a system-wide setting where all sites either have a staging endpoint or not.  

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1162

**Comment by russdanner** [comment]
@alhambrav To configure this
================
In your studio config/studio/site-config.xml add
```
<sandbox-branch>master</sandbox-branch>

<published-repository>
   <staging-environment>staging</staging-environment>
   <live-environment>live</live-environment>
</published-repository>
```

**Comment by russdanner** [comment]
@dejan-brkic can you double check the site-config in the blueprints? I added a review comment on one of them (it applies to all of them)

also, can you provide additional basic instructions on how to enable/disable if I've missed anything in my previous comment?

**Comment by dejan-brkic** [comment]
Properties that also need to be enabled
```
# Use the legacy environment-config.xml config file (for backward compatibility),
# if true, environment configuration listed in this file will not be considered
studio.configuration.site.environmentConfig.enabled: true
# If not using environment-config.xml, environments are configured here
# Git repository branch for the `live` environment, default "live"
studio.repo.published.live: live
# Git repository branch for the `staging` environment, default "staging"
studio.repo.published.staging: staging
```

If `studio.configuration.site.environmentConfig.enabled` is set to false, site-config values will be used. If not found in site-config.xml, the configuration will default to other 2 properties from YAML (studio wide configuration)

All blueprints have updated site-config.xml

**Comment by russdanner** [comment]
Merged code/configuration allows the user to re-label the staging end live environment per site but does not support "activation/deactivation" of the staging waypoint per site.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1182

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1183

**Comment by russdanner** [comment]
Once enabled this seems to function as specified but in order to enable for a site (or any number of sites) you must first change a YAML property:
```studio.configuration.site.environmentConfig.enabled: false```

Why do we need this property?

**Comment by russdanner** [comment]
Also, there may be an interplay between this feature and the branch per site feature.  See comment on ticket:
https://github.com/craftercms/craftercms/issues/2207

I noticed my recently published dashboard shows publishes  for a date prior to site creation date and for a branch

<img width="1378" alt="screen shot 2018-07-17 at 10 29 06 am" src="https://user-images.githubusercontent.com/169432/42824320-9b6bc4b8-89ad-11e8-8c3b-dd43de7140f8.png">

**Comment by dejan-brkic** [comment]
Backward compatibility. By default, staging environment did not exist so we need a switch that will turn on/off that feature and it is a global switch. 

A possible side effect of using different sandbox branch name than `master`. `Published` repo is a clone of the sandbox, so it might have an extra branch which is considered as a publishing environment when reading git log

**Comment by sumerjabri** [comment]
@dejan-brkic why not assume that it's off unless the XML in `site-config.xml` says it's on? Wouldn't that be the same and we don't need the YAML config?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1185
https://github.com/craftercms/craftercms/pull/2285

**Comment by russdanner** [comment]
To configure (per site, via the sidebar -> site config -> configuration tool:
/config/studio/site-config.xml

```
    <published-repository>
        <enable-staging-environment>true</enable-staging-environment>
        <staging-environment>qa</staging-environment>
        <live-environment>live</live-environment>
    </published-repository>
```

**Comment by russdanner** [comment]
Confirmed
