### ISSUE TITLE
[studio-ui] Items Waiting For Approval dashboard should include a server column

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2204]
### Expected behavior
 Items Waiting For Approval dashboard should include an `environment` column

<img width="1062" alt="screen shot 2018-06-11 at 12 25 12 pm" src="https://user-images.githubusercontent.com/169432/41244329-bc67bf0c-6d72-11e8-9a8a-40aab8c6cfe0.png">

### Actual behavior
The `environment` column does not currently exist

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
On Hold!

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/863

**Comment by vestrada** [comment]
Hi, 

UI is using submittedToEnvironment property to show the environment information. 
I'm always getting null as value from the api.
Dejan please check it.

Thanks, Vero

**Comment by russdanner** [comment]
Per discussion, the label was changed from Server to Environment
Confirmed
