### ISSUE TITLE
[test-suite] Automate verification that the application allows to add a remote repository for the site and to push and pull from the remote repo

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2205]
Please automate ID 58 in **Studio -> Site Config** - Verify that the application allows to add a remote repository for the site and to push and pull from the remote repo

**Setup**
1) Setup your ssh keys.  We will use your private key to access the repository we will create on the next step. For more info on generating your ssh keys, see https://www.ssh.com/ssh/keygen/
2) Create a private bare repo in gitlab/github and setup your keys.  See https://help.github.com/articles/connecting-to-github-with-ssh/ or https://docs.gitlab.com/ee/gitlab-basics/create-your-ssh-keys.html
3) Setup via a configuration file or command line prompt values for the following:
    (1) Remote Git Repository URL
    (2) Remote Git Repository Private Key
4) In Studio, create a site using empty bp

**Steps**
1) Preview the site created in the setup and open the Sidebar and click on "Site Config"
2) Click on "Remote Repositories"
3) Click on the "New Repository" button
4) Fill in the "Remote Git Repository Name" with "origin" 
5) Fill in the "Remote Git Repository URL" with the URL in the setup
6) In the "Authentication Type:" select "Remote Git Repository Private Key" 
7) Fill in the "Remote Git Repository Private Key" 
8) Click on "Create" button
9) Make some changes in Studio and save the changes
10) Open the Sidebar and click on "Site Config"
11) Click on "Remote Repositories"
12) Click on the up arrow icon (push) to push our site/changes to the remote repo
13) Click the Ok button in the Push dialog
14) Click on the down arrow icon (pull) to pull changes from the remote repo
15) Click the Ok button in the Pull dialog
16) Click on the trash can icon to delete the remote repo
17) Click on the Yes button in the confirmation dialog

**Expected Output**
2) List/empty list of remotes for the repo is displayed containing the following columns:
```
    Name    URL    Fetch    Push URL
```
8) The newly added repo should be listed in the "Repositories"
11) List of remotes for the repo is displayed containing our previously added repo with the following columns:
```
    Name    URL    Fetch    Push URL
```
12) The Push dialog opens
13) A notification that the push was successful should appear
14) The Pull dialog opens
15) A notification that the pull was successful should appear
16) A confirmation dialog should appear
17) A notification that the repo was deleted should appear

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav added to PR: https://github.com/craftercms/test-suite/pull/364 on the test suite: **testing_StudioSiteConfig.xml**.
You should configure the next property:
**crafter.gitrepository.remotegiturlforaddrepositorytosite=yourgitlaburl**
and set your private key content into the **RemoteGitPrivateKeyContent.txt file**.

**Comment by alhambrav** [comment]
Verified.
