### ISSUE TITLE
[studio] update get-go-live-items API to include target environment for items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2206]
### Expected behavior
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/workflow/get-go-live-items.html
API response should indicate which environment an item has been submitted for

### Actual behavior
API currently does not indicate the environment

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
Both docs and code must be updated.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1168
https://github.com/craftercms/docs/pull/562

**Comment by russdanner** [comment]
Confirmed
