### ISSUE TITLE
[studio] allow sandbox branch configuration per site

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2207]
### Expected behavior
Admin should be able to configure the active branch of the sandbox on a per-site basis

### Actual behavior
Today, the configuration is studio installation wide.

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-08-2018 09:50:34 -0400

#### OS
Any

#### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1160

**Comment by russdanner** [comment]
In discussing the configuration of this vita and I came up with a number of questions we would like to discuss with you.  In short:
- If the config is in the XML.  That may present a challenge to manage/merge because that branch indication checked in and potentially flowed with the site.
- When you create a site based on a remote you indicate branch but then you need to go modify the XML.
- It seems like this gets managed in multiple places (backend and xml)
- You shouldn't be able to switch branches once the site is created so putting it in the XML does make that much sense

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss. At a high-level:
* Sandbox default branch will be set at site creation time, once and for all
* That branch name will be stored in the database

**Comment by dejan-brkic** [comment]
@sumerjabri I guess we need to add the parameter to create-site API? Also, UI needs another field on the create site form?

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/docs/pull/572
https://github.com/craftercms/studio/pull/1178

**Comment by russdanner** [comment]
When I create a site as from a remote as the branch and save a file the branch is set to: "studio.repo.siteSandboxBranch"

When I do: git branch I get
```  Feature/feature-y
* studio.repo.siteSandboxBranch
```
I think there is a property/variable that's not being replaced.

https://www.useloom.com/share/a433824fce74407b9b41feb36a5e99e3

**Comment by russdanner** [comment]
Not sure how this is related but I must be somehow.  I noticed on my dashboard that some branch items are showing up as "published"

I just created the site today (07/17) so they could not be published on 07/02
<img width="1378" alt="screen shot 2018-07-17 at 10 29 06 am" src="https://user-images.githubusercontent.com/169432/42823850-97607a68-89ac-11e8-8ff5-21d2894797b4.png">

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/1186

**Comment by russdanner** [comment]
On hold for testing until UI allows specification in Create site to provide a branch label

**Comment by russdanner** [comment]
Confirmed all create and all basic content operations
