### ISSUE TITLE
[studio-ui] change server column heading in Recently Published dashboard to environment

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2209]
### Expected behavior
Change Server column heading in Recently Published dashboard to "Environment"

### Actual behavior
The column is currently labeled "Server"

### Steps to reproduce the problem
N/a

### Log/stack trace (use https://gist.github.com)
N/a

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-11-2018 11:53:52 -0400

#### OS
N/a
#### Browser
N/a

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/851

**Comment by russdanner** [comment]
Confirmed
