### ISSUE TITLE
[studio-ui] Please add a spinner when you add a remote repo to a site or when pushing or pulling, from the Remote Repositories in Site Config

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2210]
### Expected behavior
There should be a spinner when you add a remote repo to a site or when pushing or pulling, from the Remote Repositories in Site Config, since in some cases, it takes a while for the operation to finish and the user does not know if there's anything happening at all. Also, when you click on **Remote Repositories**, it would be nice to have a spinner while the system is getting the list of remotes so the user also knows there's something happening.

### Actual behavior
There is no spinner when you add a remote repo to a site or when pushing or pulling, from the Remote Repositories in Site Config.  Also, when you click on **Remote Repositories**, there is no  spinner until the list of remotes appears (if there are remotes for the site) 

### Steps to reproduce the problem
* Create a site using empty or website_editorial bp
* Open the **Sidebar** and click on **Site Config**
* Click on **Remote Repositories**
* Click on **New Repository**
* Preview your site again
* From the Sidebar, click on **Site Config**
* Click on **Remote Repositories**, notice that there's a period of time when nothing is happening in the UI, then the list of repo's appear.  It would be nice to have a spinner there too.

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/18dad38116d84686913b880da60b5e7c

Notice especially when the push icon was clicked, there was a period where nothing happened until the notification that the push was successful.  It would be nice to have a spinner appear when pulling, pushing or adding remote, just in case the operation takes a while to finish, so the user is aware that something is happening

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-bb5185
Build Number: bb518515b875d7784bb698317a7d0d3f36e2cbe0
Build Date/Time: 06-11-2018 10:24:01 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/856

**Comment by alhambrav** [comment]
Verified fixed.
