### ISSUE TITLE
[studio-ui] template code example insert variable from repeat inserts two dots

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2212]
### Expected behavior
variable syntax should contain one dot, not two in the inserted example:
wrong:
`${contentModel..locations.item[0].phone}`

correct:
`${contentModel.locations.item[0].phone}`
### Actual behavior
https://www.useloom.com/share/c10506aac92c440da07799de58c2f734

### Steps to reproduce the problem
* create a content type with a repeat group that contains a field 
* open the template for that type and insert the content variable for that field
* see two dots in the variable name

#### Version
Studio Version Number: 3.0.13-b96d72
Build Number: b96d728383059b76a86e4181cdcc122843241e56
Build Date/Time: 05-20-2018 22:22:27 -0400

#### Browser
n/a

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/877

**Comment by russdanner** [comment]
Confirmed
