### ISSUE TITLE
[studio-ui] create content type should only allow alpha numeric characters

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2213]
### Expected behavior
Only allow alphanumeric characters in the name field of the create content type dialog

### Actual behavior
the display label field in the dialog auto-populates the type name but today it allows some characters like : and - (possibly others) to be added to the name.  

Only allow alpha numeric characters.  

Motivation:
Other characters trip up the script engine when looking for the matching controller and/or make it impossible for an inline debugger to find the related groovy class

### Steps to reproduce the problem
* go to site config
* click content types
* create new
* Enter a display label, note today it allows : (colon) to be passed through (and possibly other characters)

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.13-b96d72
Build Number: b96d728383059b76a86e4181cdcc122843241e56
Build Date/Time: 05-20-2018 22:22:27 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/881

**Comment by russdanner** [comment]
Confirmed
