### ISSUE TITLE
[studio-ui] Add tab on publish screen to support publish by commit id

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2214]
### Expected behavior
Provide a tab on publish screen in site-config that allows site admin to publish with commit IDs.  

provide a text area that allows comma separated commit IDs and comment to be submitted to the publish commits API using https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html

### Related tickets
#2217 

### Actual behavior
N/A

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
N/A

#### OS
N/A

#### Browser
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/883

**Comment by vestrada** [comment]
Hi @dejan-brkic ,

As we talked, commit api: https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html is giving an environment error. `{"message":"Environment not found"}`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1195

**Comment by russdanner** [comment]
Works when publishing to Live but fails on publish to staging

<img width="1163" alt="screen shot 2018-08-06 at 5 36 20 pm" src="https://user-images.githubusercontent.com/169432/43742323-85c4f222-999f-11e8-81a0-0e0fad0e8326.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1200
