### ISSUE TITLE
[test] Validate refresh event on sidebar

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2215]
Please validate the refresh event on the side bar. Check the following steps:

### Steps to reproduce the problem
* Create a new site.
* Check if the side bar update the item you have changed in the following scenarios:
- Create Content
- Create folder
- Rename Folder
- Edit Content
- Cut/copy and paste and item
- Duplicate an item
- Publish one or more items
- Scheduled
- Unlock
- Upload

### Log/stack trace (use https://gist.github.com)

N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-97cb72
Build Number: 97cb72fde437ba2ec8b11d55425c90713309ec64
Build Date/Time: 06-12-2018 09:29:13 -0600

#### OS
OS X

#### Browser
Chrome

**Comment by luishernandezmonge** [comment]
Checked the next scenarios:
-New Content (creation).
-Edit Content (edition).
-Request Publish (from other user = author).
-In Schedule.
-Published single content.
- Folder creation.
-Nested folders with contents.
-Deletion.
-Duplicate.
- Copy/Paste single content.
- Cut/Paste single content.
- Copy/Paste content with childs.
- Cut/Paste content with childs.
- Locked for edit
- Publish content with edited childs.
- Publish child on a edited parent
     -Parent (Edited) 
        -Child
          -Folder
              -New Child (New content) <- Publish this does not work because of the dependencies.

@vestrada

**Comment by luishernandezmonge** [comment]
Verified with all scenarios of above.
