### ISSUE TITLE
[studio] site config updates do not get pick up by studio until restart

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2216]
### Expected behavior
Studio should pick up updates to site config immediately. For example, change or add a content type.

### Actual behavior
All site config changes are invisible to studio until restart because due to a caching issue.

### Steps to reproduce the problem
* create a site
* create a content type
* type to open existing types, see type is not shown in list
* restart server
* open existing types, see type is shown in list

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
2.5.18

#### OS
N/A

#### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1157

**Comment by russdanner** [comment]
Confirmed
