### ISSUE TITLE
[studio] add field for comment to publish commit ID API

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2217]
### Expected behavior
Caller of API should have the option to send a comment when requesting a publish via the API
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/commits.html

### Actual behavior
API does not accept publish at this time

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Any

#### OS
N/A

#### Browser
N/A

**Comment by dejan-brkic** [comment]
Docs:
https://github.com/craftercms/docs/pull/570

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1177

**Comment by russdanner** [comment]
Confirmed
