### ISSUE TITLE
[engine] improve context and class loading with groovy and spring development

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2224]
Today changes to nested groovy classes often require a context rebuild in order to get picked up.  Ideally, Crafter CMS could detect a development change that would require a context rebuild and handle that seamlessly for the developer.

### Example: 
A rest controller imports a class written in groovy and uses it.  The user changes the class but not the rest script. The updated class changes are not seen until after a context rebuild (or a change to the rest controller)

**Comment by sumerjabri** [comment]
@russdanner please elaborate the ticket per our conversation with AV

**Comment by sumerjabri** [comment]
@russdanner please re-test as this should be done via the deployer already (preview and regular).

**Comment by avasquez614** [comment]
Not really an issue right now

**Comment by russdanner** [comment]
Re-closing and opening as new ticket due to support the new ticket structure.
