### ISSUE TITLE
[studio-ui] RTE configuration of style sheets fails if only one style sheet is listed

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2225]
### Expected behavior
RTE configurations should work properly with 0 to n (any) number of configured style sheets

### Actual behavior
When only one style sheet is configured a css reference with href="undefined" is inserted in to the head of the RTE DOM.

### Steps to reproduce the problem
*  start a project based on empty blueprint
*  edit rte configuration in sidebar/site config
*  make sure the following rteStylesheets element only contains one style sheet. Example:
```
 <rteStylesheets> <!-- This informs the RTE to use the CSS files -->
            <link>
                <loadFromPreview>true</loadFromPreview>
                <url>/static-assets/css/style.css</url>
            </link>
        </rteStylesheets>
```
* Edit the home page
* Enter the RTE and using the browser inspect the RTE element.  Open the head of the dom.
* Note the CSS reference is mal formed.

It looks like the RTE JS is not interpreting the JSON configuration response correctly when only one link element is defined.

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-4838ba
Build Number: 4838bae0b3586ea0edabb4e8d57e3b1019f4e04e
Build Date/Time: 06-14-2018 14:17:47 -0400

#### OS
Any
#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/950

**Comment by russdanner** [comment]
Confirmed
