### ISSUE TITLE
[studio] dependency resolution error causes create site to fail

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2228]
### Expected behavior
Malformed paths should generate warnings/errors in the log and warnings to the user but should not fail the action.

### Actual behavior
Encountering bad content such as  `/static-assets/documents/someproduct/*` bubbles up an exception and terminates the user's actions.  In this case, a create site.

### Steps to reproduce the problem
working on a simple test case

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/russdanner/382c88b03650d19d7710cdb075b7e0da

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-4838ba
Build Number: 4838bae0b3586ea0edabb4e8d57e3b1019f4e04e
Build Date/Time: 06-14-2018 14:17:47 -0400

#### OS
Any

#### Browser
N/A

**Comment by russdanner** [comment]
Working on a simple test case.

**Comment by dejan-brkic** [comment]
Can not reproduce the error, but added try/catch block to prevent erroring out
PR:
https://github.com/craftercms/studio/pull/1167

**Comment by russdanner** [comment]
Confirmed
