### ISSUE TITLE
[studio] document how to override logging levels

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2229]
# Step 1:
Copy apache-tomcat/webapps/studio/WEB-INF/classes/log4j.xml to apache-tomcat/shared/classes/crafter/studio/extension/log4j-override.xml and add the following:

# Step 2
add the following lines:
```
<logger name="CLASS | PACKAGE">
      <level value="DEBUG | INFO | WARN | ERROR" />
</logger>
```
## Example
```
<logger name="org.craftercms.studio.impl.v1.service.deployment.job.DeployContentToEnvironmentStore">
      <level value="error" />
</logger>

```
# Step 3
Restart Crafter Studio

**Comment by russdanner** [comment]
Full blog also provided to Vita via slack

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/567

**Comment by russdanner** [comment]
Confirmed
