### ISSUE TITLE
[docs] MELLON_secure_key not needed for SAML SSO

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2230]
https://docs.craftercms.org/en/3.0/system-administrators/security/configure-headers-based-auth.html. The documentation specifies `RequestHeader set secure_key "secure" env=MELLON_secure_key`. The `env=MELLON_secure_key` part is not required and is actually causing issues, so the line should be instead `RequestHeader set secure_key "secure"`.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/557 and https://github.com/craftercms/docs/pull/558

**Comment by avasquez614** [comment]
Verified
