### ISSUE TITLE
[studio-ui] jsession and anchor tags break preview tools

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2232]
### Expected behavior
;jsession and #someanchor should be allowed on the URL and should not break preview tools

### Actual behavior
It looks like Studio is interpreting text that follows ; and # as part of the page URI and thus not correctly identifying the page to tools in preview such as the in-context editing and the drag and drop
<img width="1362" alt="screen shot 2018-06-20 at 10 59 21 am" src="https://user-images.githubusercontent.com/169432/41666858-822ed448-7479-11e8-9cff-8da6bd9fe2c1.png">

<img width="1370" alt="screen shot 2018-06-20 at 10 58 53 am" src="https://user-images.githubusercontent.com/169432/41666902-9b8ed19a-7479-11e8-8978-53149d47697b.png">

### Steps to reproduce the problem
* add #something to the page parameter in the browser in preview
* open preview tools, then go to page components
* note the error displayed.
* repeat for ;JSESSION=BLAH  (you don't need a real session ID to replicate the error)

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-4838ba
Build Number: 4838bae0b3586ea0edabb4e8d57e3b1019f4e04e
Build Date/Time: 06-14-2018 14:17:47 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/940

**Comment by russdanner** [comment]
Confirmed
