### ISSUE TITLE
[studio] make git commit author field value and commit message formats configurable 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2233]
Git commits include an author field and a commit message.  Today Studio enforces a specific format for both the author field and commit when a user writes content via studio.  Make these formats configurable.

# Existing commit message format
```
commit abcNOTAREALCOMMITID82c1c6099b81 (HEAD -> master) 
Author: Joe Smith <joe@email.com> 
Date: Wed Jun 20 16:02:31 2018 +0000 
Wrote content /site/website/reference-materials/search-compare/index.xml
```
# Example alternative author and message format
```
commit abcNOTAREALCOMMITID82c1c6099b81 (HEAD -> master) 
Author: jd298p joesmith <joe@email.com> 
Date: Wed Jun 20 16:02:31 2018 +0000 
user jd298p wrote content /site/website/reference-materials/search-compare/index.xml
```
# Additional notes
* While different sites of any given install can have different up streams, I feel that this setting can be made Studio wide.
* Alternative example is just an example, other formats may be required
* Publish commit message is already configurable today with the following YAML property
```
studio.repo.published.commitMessage: "Publish event triggered by {username} on {datetime} via {source}.\n\nPublish note from user: \"{message}\"\n\nCommit ID: {commit_id}\n\nPackage ID: {package_id}"
```

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss if this is possible, and if so, how to do it.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1170

**Comment by russdanner** [comment]
Confirmed
