### ISSUE TITLE
[studio] After mariaDB4j version upgrade studio does not start due to DB not starting

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2237]
### Expected behavior
Studio starts normally

### Actual behavior
Studio does not start even after rebuilding whole authoring environment

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/dejan-brkic/ea9477e298266769e05532bc445986be

#### Version
```
Manifest-Version: 1.0
Implementation-Title: Crafter Studio
Implementation-Version: 3.0.15-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: dejanbrkic
Build-On: 1529701699999
Implementation-Build: b8dc5a961109d6c2da7cd0c41bfcd558df41f8ee
Implementation-Vendor-Id: org.craftercms
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_51
Implementation-Vendor: CrafterCMS
```

#### OS
Mac OS X

#### Browser

**Comment by jdrossl** [comment]
@dejan-brkic what is the exact version of macOS you are running?

**Comment by alhambrav** [comment]
Hi! I am getting the same error as Dejan when I try to do a fresh install off `develop`

Steps:
Run the following commands:
```
 > git clone https://github.com/craftercms/craftercms.git -b develop
 > ./gradlew init build deploy
 > ./gradlew start
```
Tail the tomcat log after starting and watch the logs.  Notice the error messages for the database.  Notice also the error on line number 2 `failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: studio.repo.basePath=../data/repos`

The catalina server starts up but when I try to access Studio in my browser, it gives me `No Site is Set!`

Here's the log: 
https://gist.github.com/alhambrav/b9d5bdeb8d73187a039ab4fbc1eea984

My macOS version is: High Sierra Version 10.13.3 (17D47)

**Comment by jdrossl** [comment]
@alhambrav fix is merged, you should be able to start studio now

**Comment by dejan-brkic** [comment]
Seems it is fixed. My environment is dirty due to applied workaround. I have reverted workaround, but not sure it was enough.
