### ISSUE TITLE
[studio] catch exception if dependency on ContentServiceImpl.contentExists in dependency resolver

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2239]
### Expected behavior

Catch and report exceptions in this method:
`org.craftercms.studio.impl.v1.service.dependency.RegexDependencyResolver.resolve(RegexDependencyResolver.java:79)
`

That are a result of this method call:
`org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.contentExists(ContentServiceImpl.java:159)
`

An ERROR log message should say that:
Dependencies in File {current file being scanned} could not be resolved for path {path that failed exist} due to the following error: {error}

### Actual behavior
Exceptions with contentExists exceptions are not caught during dependency resolution operation and the operation (site import, write operation) fails as a result.
 
### Steps to reproduce the problem
in progress:  https://github.com/craftercms/craftercms/issues/2228

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/russdanner/382c88b03650d19d7710cdb075b7e0da

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-4838ba
Build Number: 4838bae0b3586ea0edabb4e8d57e3b1019f4e04e
Build Date/Time: 06-14-2018 14:17:47 -0400

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
@dejan-brkic the proposed approach here is to catch exceptions, report them, and continue to import the files into the system. What's being asked is to have a repo with problems, but, have a report in the logs that shows the problems for a person to manually fix and repair.

Ping me if you have concerns.

**Comment by dejan-brkic** [comment]
Can not reproduce the error, but added try/catch block to prevent erroring out
PR:
https://github.com/craftercms/studio/pull/1167

**Comment by russdanner** [comment]
Confirmed
