### ISSUE TITLE
[studio-ui] Move "Log Console", "Logging Levels" to a global section in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2240]
### Task
Move "Logging Levels" to the Main Menu since this affect Studio only.
Add a "Log Console" to  the Main Menu for Studio logs (not Engine) -- if BE doesn't support that, open a ticket for that

**Comment by sumerjabri** [comment]
Please connect with me to discuss this effort in detail. This is not simple and requires having 2 log consoles, one global for Studio, and one per site for the site. Log levels per site and configuration is global and we must add Engine config, not just Studio.

**Comment by sumerjabri** [comment]
@alhambrav I checked with the others and it seems that it will log site-specific things only, if that's not the case, it's a bug.

We won't be moving it up because it's supposed to work as spec'd (per site logging).

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1100
studio: https://github.com/craftercms/studio/pull/1540
video-center: https://github.com/craftercms/video-center-blueprint/pull/24

**Comment by jvega190** [comment]
Studio logs API pending

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1542 - Updated config file for global menu items

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1107 - Studio Log working with new API, permissions for Logging levels and Log Console pending

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1555 - permissions updated

**Comment by yacdaniel** [comment]
Verified.
