### ISSUE TITLE
[studio] Support SITE_GROUP in the groups header when using header based authentication

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2244]
Right now, when using header based authentication, site/group membership is handled through the `groups` header and needs to be specified as SITE,GROUP,SITE,GROUP... Please add support in Studio for adding a regex through configuration that will allow specifying site/group membership as SITE_GROUP,SITE_GROUP... and still be backwards compatible. Also, if a user comes with a group that is not recognized, just ignore the group. 

Please talk with Sumer for more details.

**Comment by sumerjabri** [comment]
No longer required as we're changing the way group membership to site auth mapping. New feature to be added in 3.1
