### ISSUE TITLE
[studio] Even when a user is an Admin in one site and and Author in another, the Site Config will appear on the site he's an Author

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2249]
### Expected behavior

If a user is an `Admin` in site A, and an `Author` in site B, the Site Config should not appear in the sidebar of the user in site B.

### Actual behavior

If a user is an `Admin` in site A, and an `Author` in site B, the Site Config currently appears in the sidebar of the user in site B.

### Steps to reproduce the problem

* Login as admin
* Create a user
* Create a site
* Create another site
* Add the user as an `Admin` of the first site
* Add the user as an `Author` of the second site
* Login as the user
* Go to the dashboard of the second site

Observe that the Site Config appears in the sidebar.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1188

**Comment by avasquez614** [comment]
Verified
