### ISSUE TITLE
[studio-ui] Add item-list="true" attribute to Item Selector and Repeating Group controls

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2250]
Please add a `item-list="true"` to the elements that are created by Item Selectors and Repeating Groups, e.g.:

```
<features item-list="true">
    <item>
        <value>Quam lorem ipsum</value>
        <key>/site/components/features/quam-lorem-ipsum.xml</key
        <include>/site/components/features/quam-lorem-ipsum.xml</include
        <disableFlattening>false</disableFlattening>
    </item>
    <item>
        <key>/site/components/features/sapien-veroeros.xml</key><
        <value>Sapien Veroeros</value><include>/site/components/features/sapien-veroeros.xml</include>
        <disableFlattening>false</disableFlattening>
    </item>
</features>
```

Engine needs this to always return a JSON list for Item Selectors and Repeating Groups even if they just contain one item, when converting the DOM to JSON for REST services.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/865

**Comment by avasquez614** [comment]
@vestrada sorry just a tiny change, can you change it from `list=true` to `item-list=true`? Thanks.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/866

**Comment by avasquez614** [comment]
Verified
