### ISSUE TITLE
[studio-ui] Create Repository dialog does not go away after clicking on the "Create" button

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2255]
### Expected behavior
Create Repository dialog should go away after clicking on the "Create" button

### Actual behavior
Create Repository dialog does not go away after clicking on the "Create" button after an error creating, then fixing the error and creating again

### Steps to reproduce the problem
* Create a site using website_editorial bp, create two bare repos too in your drive by running `git init --bare testRepo`
* Open the Sidebar and click on **Site Config**
* Click on **Remote Repositories**
* Click on the **New Repository** button and fill in `Remote Git Repository Name (Example: origin)` with `origin` and `Remote Git Repository URL` with the URL to the first bare repo you created on your disk
* Click on the **New Repository** button again and fill in `Remote Git Repository Name (Example: origin)` with `origin` again and `Remote Git Repository URL` with the URL to the second bare repo you created on your disk .  You should get an error message here that the `Remote Git Repository Name` already exists
* Fix the `Remote Git Repository Name` by filling it in with `origin2`, then click on the `Create` button.  Notice that it adds the repository, but the `Create Repository` dialog does not go away.
* Try clicking on the `Cancel` button and notice that the dialog still does not go away

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/db01350f9c2f4779bce813fe6b1609d7

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-619ded
Build Number: 619dedd65460e9353e09795f0fbcd317f7b3d065
Build Date/Time: 06-28-2018 14:01:57 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/861

**Comment by alhambrav** [comment]
Verified fixed.
