### ISSUE TITLE
[studio] Error in logs when scheduling for publish a request

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2257]
### Expected behavior
There should be no errors in the logs when an approver schedules for publish an item

### Actual behavior
There's an error in the logs when an approver schedules for publish an item.

### Steps to reproduce the problem
* Login as user author and edit a file and request publish for a later time
* Login as a user with publishing rights (In the short clip below, the approver is a user `admin`)  and approve the request for publishing at a later time.  Watch the logs and notice the error
`[freemarker.runtime] | Error executing FreeMarker template`

### Log/stack trace (use https://gist.github.com)
Here's the error:
https://gist.github.com/alhambrav/088f2a1f512aad5e65ca4c3b56fbe610

Here's a short clip of the steps:
https://www.useloom.com/share/2fdc3fa3ba3e4be3920b52f982dd296d

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-619ded
Build Number: 619dedd65460e9353e09795f0fbcd317f7b3d065
Build Date/Time: 06-29-2018 10:21:56 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1173

**Comment by alhambrav** [comment]
Verified fixed.
