### ISSUE TITLE
[studio] creating site based on remote repo with non master branch fails

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2259]
### Expected behavior
creating a site based on a remote's branch should work

### Actual behavior
https://www.useloom.com/share/3b87cb3818d0403380b0d0929d335724

### Steps to reproduce the problem
* create a remote repo with a valid branch
* create a site based on that remote/branch
* note error (see video)

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/russdanner/4fbee4d30e69aab61bdb9cd087b4dd7a

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-a8e1df
Build Number: a8e1df3afa14a2041ab86ac64d36f6ca608bebd7

#### OS
Any

#### Browser
Any

**Comment by dejan-brkic** [comment]
Can not reproduce.
By examining stack trace, the error was not related to repository operations. The error was caused by preview deployer, either not running or not configured properly (studio was not able to connect)

**Comment by russdanner** [comment]
Confirmed
