### ISSUE TITLE
[studio] recently published dashboard does not sort correctly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2260]
### Expected behavior
The recently published dashboard should be sorted in descending chronological order and grouped by date.  Other factors such as server or publisher should not factor into the sort 

### Actual behavior
![recently-published-dashboard-collapsed](https://user-images.githubusercontent.com/169432/42113217-816381bc-7bb8-11e8-8dc7-8e1290238aec.png)

### Steps to reproduce the problem
* publish multiple files on different days by different authors 

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-a8e1df
Build Number: a8e1df3afa14a2041ab86ac64d36f6ca608bebd7
Build Date/Time: 06-28-2018 20:18:02 -0400

#### OS
Any

#### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1172

**Comment by russdanner** [comment]
Hi Dejan,

Just taking a quick look at the code here.  It looks like this functionality is driven off of Git Log.  In my mind that would already be "sorted."  I see we build up some data structures and sort them.  I'm just wondering if there is more going on here than is needed (assuming the data from git log comes back in the order we want (latest edit/commit first)

**Comment by dejan-brkic** [comment]
Functionality is driven by git log per branch (environment) so it is sorted for the branch, not the whole result set. That is why sorting at the end is needed.

**Comment by russdanner** [comment]
Roger that.

**Comment by russdanner** [comment]
Confirmed
