### ISSUE TITLE
[test-suite] Automate verification that save draft works

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2262]
Please automate ID 48 in **Studio -> Content** - Verify save as draft works

**Setup**
Create a site using the website_editorial bp

**Steps**
1) Open the Sidebar
2) Right click on /articles/2016/12
3) Select New Content
4) In the Choose Content Type dialog, select "Page - Article" and click on the "Ok" button
5) Fill in all the required fields in the edit form
6) Click on the "Save Draft" button
7) Click on the arrow up symbol on the bottom right of the screen
8) Click on the "Cancel" button in the minimized edit form
9) Click on "Edit" in the context nav
10) Click on the arrow up symbol on the bottom right of the screen
11) Click on the "Save and Close" button on the minimized edit form

**Expected Output**
2) Right click menu should appear
3) Choose Content Type dialog should appear
4) Edit form should open
6) Notification should appear that "Draft Save Completed"
7) Orange bar across the top of Preview should appear indicating that the "Content was saved as DRAFT..."
   In the Sidebar, the newly created article should have a lock on it.  Also, the article should be located under /articles/2016/12
<img width="1429" alt="screen shot 2018-07-02 at 2 56 33 pm" src="https://user-images.githubusercontent.com/25483966/42181275-532d7ba2-7e08-11e8-9364-39ee19ce8988.png">

8) The icon in the context nav for the new article created should have a lock on it
<img width="1429" alt="screen shot 2018-07-02 at 3 03 41 pm" src="https://user-images.githubusercontent.com/25483966/42181566-3d5d3b40-7e09-11e8-9b77-b821ae2ab45e.png">

9) Edit form should open
10) Edit form should be minimized at the top
11) The orange bar across the preview should disappear
    In the Sidebar, the lock icon on the new article should also disappear, the same with the icon on the context nav

Here are some tickets related to **Save Draft**
* https://github.com/craftercms/craftercms/issues/2188
* https://github.com/craftercms/craftercms/issues/1977

**Comment by luishernandezmonge** [comment]
@alhambrav Done, added to PR: https://github.com/craftercms/test-suite/pull/366

**Comment by alhambrav** [comment]
Verified.
