### ISSUE TITLE
[docs] upgrading/importing large sites can lead to a session timeout

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2264]
### Expected behavior
Update the documentation to provide a tip for very large sites:
Very large sites may take a long time to import and can in some cases last longer than the user session timeout settings.  To increase the session time follow the following instructions:

in your TOMCAT/webapps/studio/WEB-INF/web.xml

Change the value 75 in the following config to 180 (3 hours)
``` 
<session-config>
  <session-timeout>1440</session-timeout>
 </session-config>
```
In your TOMCAT/shared/classes/crafter/studio/extension/studio-config-override.yaml
Change/add: this value (60 -> 180 again 3 hours)
```studio.security.sessionTimeout: 180```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/583

**Comment by russdanner** [comment]
Confirmed
