### ISSUE TITLE
[studio-ui] Please add to TinyMCE initialization all available out of the box plugins

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2266]
### Expected behavior
Please add to TinyMCE initialization all available out of the box plugins

### Actual behavior
There are available TinyMCE out of the box plugins not initialized, so when a user tries to configure the RTE with those plugins not initialized, it doesn't work

### Steps to reproduce the problem
* Create a site using empty or website_editorial 
* Open the **Sidebar** and click on **Site Config**
* Click on **Configuration** then click on the dropdown box and select **RTE Configuration**
* Inside the `<toolbarItems2></toolbarItems2>` tag, add `media` (we want to be able to add videos in the RTE) then click on the **Save** button
* Go back to Preview and click on **Edit**, notice that the spinner does not go away and you can't click on any of the fields in the edit form because it is trying to load the media button in the RTE toolbar
<img width="1334" alt="screen shot 2018-07-05 at 7 44 06 am" src="https://user-images.githubusercontent.com/25483966/42321530-4fed6a94-8027-11e8-90bc-0a1609969972.png">

Please initialize plugins found here: `src/studio-ui/static-assets/modules/editors/tiny_mce/plugins`

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-e14cea
Build Number: e14cea30e04d3518e2fff33bd7bf4a8ecc64201e
Build Date/Time: 07-05-2018 11:45:37 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
From discussion with Vita and Russ, I initialized only those that wont' affect rte behavior/look. Vita has a list of initialized plugins so it can be properly documented

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/902

**Comment by jvega190** [comment]
3.0.x: https://github.com/craftercms/studio-ui/pull/903

**Comment by alhambrav** [comment]
Verified.
