### ISSUE TITLE
[studio-ui] add environment to tool tip when item is in workflow or scheduled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2271]
### Expected behavior
Tool tip should indicate what environment a item is in approval or sheduled for
<img width="368" alt="screen shot 2018-07-06 at 1 43 08 pm" src="https://user-images.githubusercontent.com/169432/42393049-0488bcfa-8123-11e8-88d9-5e861b0c18e2.png">

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-ff6bde
Build Number: ff6bde003de5b8440809d2f75e5e9db2c473b7a9
Build Date/Time: 07-06-2018 12:53:20 -0400

#### OS
Any

#### Browser
Any

**Comment by russdanner** [comment]
Also I noted that scheduled is not bolded.  All of the labels on the tool tip should be styled the same.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/949

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss API changes as needed to include the necessary property

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1046

**Comment by russdanner** [comment]
Confirmed
