### ISSUE TITLE
[studio-ui]  options on right click options of wcm-assets-folder dont work when using multi-path configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2281]
### Expected behavior
right click options should function correctly 

### Actual behavior
selecting a right click menu option loads the preview with a 404 (undefined)

### Steps to reproduce the problem
* set up content so that you have multiple roots to use
```
/static-assets/images
/static-assets/images/folder-a
/static-assets/images/folder-a/my-image.jpg

/static-assets/images/folder-b
/static-assets/images/folder-b/your-image.jpg
```
* configure the static assets plugin to use the multiple paths in the side bar config
```
<!-- Static Assets -->
<modulehook>
	<name>wcm-assets-folder</name>									
	<params>
		<label>Static Assets</label>
		<path>/static-assets/images/folder-a</path>
		<path>/static-assets/images/folder-b</path>
		<showRootItem>true</showRootItem>
		<onClick>none</onClick>
	</params>
</modulehook>
```
* Open the folders, right click on one of the images and choose an option (cut, history etc), note 404 in preview. 

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
3.0.13 - 3.0.15
Replicated in:
Studio Version Number: 3.0.15-SNAPSHOT-d62cff
Build Number: d62cff05198955c0ccc924267702b62e94b14dc4

Build Date/Time: 07-17-2018 09:49:21 -0400
#### OS
Any

#### Browser
Any

**Comment by russdanner** [comment]
See video:
https://www.useloom.com/share/aeb42047ab424faf9f5f2df07a97ae62

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/880

**Comment by russdanner** [comment]
Confirmed
