### ISSUE TITLE
[studio-ui] RTE Channel Plugin shows an incorrect list of channels

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2282]
### Expected behavior
Channel select drop-down should show the configured channels

### Actual behavior
<img width="1310" alt="screen shot 2018-07-17 at 4 03 42 pm" src="https://user-images.githubusercontent.com/169432/42842504-5fbabb58-89db-11e8-89ca-3b9b7c79a086.png">

### Steps to reproduce the problem
*  configure RTE to display channel selector

include the plugin
<img width="1039" alt="screen shot 2018-07-17 at 4 04 19 pm" src="https://user-images.githubusercontent.com/169432/42842565-8b81e8b0-89db-11e8-8f70-18ee9aa57f1d.png">

add it to the toolbar
<img width="1409" alt="screen shot 2018-07-17 at 4 04 14 pm" src="https://user-images.githubusercontent.com/169432/42842637-b7c8a706-89db-11e8-9ed0-c6e5989a1ed3.png">

* In the content type/form definition, configure channels in the rte
<img width="1432" alt="screen shot 2018-07-17 at 4 04 00 pm" src="https://user-images.githubusercontent.com/169432/42842683-dc17cfec-89db-11e8-9d36-40b1767ab7ea.png">

 

### Log/stack trace (use https://gist.github.com)
N/A
#### Version
Studio Version Number: 3.0.15-SNAPSHOT-d62cff
Build Number: d62cff05198955c0ccc924267702b62e94b14dc4
Build Date/Time: 07-17-2018 09:49:21 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/935

**Comment by russdanner** [comment]
Confirmed
