### ISSUE TITLE
[studio] NPE on publish at PublishingManagerImpl.java line 212

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2283]
### Expected behavior
Error should be handled or if valid error condition, an explicit error explaining the issue should be provided in the log rather than null pointer.

### Actual behavior
See Stack, NPE is thrown on PublishingManagerImpl.java line 212
Publisher is stopped

### Steps to reproduce the problem
```
if (itemMetadata.getCommitId().equals(item.getCommitId())) {
```
Unknown.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/russdanner/b2b9c81e0908f5d5c257122d27d417e3

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-a4f6cd
Build Number: a4f6cdca74f6d2c7d1a9390abdc82778c94c7eed
Build Date/Time: 07-18-2018 11:37:48 -0400

#### OS
Any

#### Browser
Any

**Comment by russdanner** [comment]
@sumerjabri If, by looking at the code it can be determined that this is an edge case then 3.0.16.
I am not sure what I did not create the mismatch or null data seen on line 212.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1187

**Comment by russdanner** [comment]
Confirmed.
Note: With this check in place it's possible that the state will not transition until the next edit on the item.

Also note:  Existing ystems previously encountering this error/blocked by this error will not continue when publishing is enabled.
