### ISSUE TITLE
[studio-ui] Items approved and scheduled for publish is listed in the `Items Waiting For Approval` widget in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2287]
### Expected behavior
Items approved and scheduled for publish should not be listed in the `Items Waiting For Approval` widget in the dashboard (since the items are already approved)

### Actual behavior
Items approved and scheduled for publish is listed in the `Items Waiting For Approval` and the `Approved Scheduled Items` widget in the dashboard

![screen shot 2018-07-19 at 3 01 15 pm](https://user-images.githubusercontent.com/25483966/42964372-d461fd56-8b64-11e8-95ae-c13cac252478.png)

### Steps to reproduce the problem
* Create a site using website_editorial bp
* Create a few new articles
* Schedule one of the newly created articles to be published at a later time.  Open the dashboard and in the  `Items Waiting For Approval` widget, click on the `Show "In-Progress" Items` button. Notice that your scheduled item appears in both the `Items Waiting For Approval` and `Approved Scheduled Items` widget in the dashboard (see image above).

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/bf6532d7ae5c4c78815cc608831b4312

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-539636
Build Number: 539636db63c4b78473dc5a2e075cd11da64ae89d
Build Date/Time: 07-19-2018 09:52:40 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1189

**Comment by alhambrav** [comment]
Verified fixed.
