### ISSUE TITLE
[studio-ui] add Sandbox Branch field to Create Site Dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2289]
### Actual behavior
Add Sandbox Branch field to Create Site Dialog
* maintain consistency with current dialog box styles
<img width="619" alt="screen shot 2018-07-19 at 5 31 26 pm" src="https://user-images.githubusercontent.com/169432/42971521-a901d9b8-8b7a-11e8-8b81-bbe173df8693.png">

Send Sandbox Parameter as part of Create API
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/site/create-site.html

### Related Tickets
https://github.com/craftercms/craftercms/issues/2207

### Steps to reproduce the problem
N/A

#### Version
N/A 

#### OS
Any
#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/878

**Comment by russdanner** [comment]
Confirmed default and supplied values
