### ISSUE TITLE
[studio-ui] Update UI to add a global menu

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2290]
Add a new Global Menu to manage users, groups, sites, and marketplace (soon).

This menu is visible only to the admin account, for all other users, it's the old Sites panel. You'll need to use the new APIs, https://app.swaggerhub.com/apis/craftercms/studio/2.

Here is what it should look like:
![img_20180717_102142](https://user-images.githubusercontent.com/3931908/43006020-957e09a6-8c02-11e8-906c-8b9959fb473b.jpg)

Ping me to discuss as needed.

**Comment by vestrada** [comment]
On Hold

**Comment by vestrada** [comment]
Linking: https://github.com/craftercms/craftercms/issues/2427
