### ISSUE TITLE
[studio-ui] Allow users of the code editor to save and continue working

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2296]
### Expected behavior

- Make actions for code editing consistent with actions for content editing.
- Save as draft saves the file but does not unlock it.
- Code editor should continue to take over the whole screen
- Add the "hide" button and associated behavior (See button on content forms) in the right hand portion of the code editor command bar which allows the editor to be hidden or "rolled up" so that the user can see what is under the dialog (typically to look at a preview.)  
- Save as draft and Save an close should refresh the preview

<img width="1438" alt="screen shot 2018-07-20 at 2 35 51 pm" src="https://user-images.githubusercontent.com/169432/43019454-0ada0902-8c2b-11e8-8665-95ba6d25a8e6.png">

### Actual behavior
The editor/developer has two buttons today: Update and Cancel, both result in the editor being closed.  
The editor/developer has no way to save and continue (Save as Draft) 

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
All

#### OS
N/A

#### Browser
N/A

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/2342

**Comment by russdanner** [comment]
Confirmed
