### ISSUE TITLE
[studio-ui] clicking escape in code editor should not close the editor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2297]
### Expected behavior
Clicking escape while in the code editor should not close the code editor.  

### Actual behavior
Escape key closes the editor
https://www.useloom.com/share/4376796638bc45799ee7d44db8021c53

### Steps to reproduce the problem
* Open the code editor
* Click escape
* Note the editor closes without warning to the user

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-814d9c
Build Number: 814d9ce264e548b607048ffe1d496a4aed3c0ae4
Build Date/Time: 07-19-2018 16:09:50 -0400

#### OS
Any

#### Browser
Any

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/917
3.0.x: https://github.com/craftercms/studio-ui/pull/918

**Comment by sumerjabri** [comment]
Verified
