### ISSUE TITLE
[studio-ui] Provide visibility and administration over open items in the publishing queue on the admin console

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2299]
**Is your feature request related to a problem? Please describe.**
Administrators need a way to see the items in the publishing queue and administer them

**Describe the solution you'd like**
Functionality should include:
* Add a tab on the publishing administration tool for publishing queue
* Filter by state (Only open work should show by default)
* Queue should be filtered by the site automatically
* Ability to set the CANCEL a publish if it's not in a COMPLETED or CANCELLED state.

Columns to include:
- Scheduled Date 
- State   
- Content type   
- Content Path        
- Environment  
- Username  
- Submission Comment

**Comment by russdanner** [comment]
Assigned to Russ to further detail feature.

**Comment by russdanner** [comment]
@rart Please design UI

**Comment by russdanner** [comment]
Related to: https://github.com/craftercms/craftercms/issues/2471

**Comment by russdanner** [comment]
DUPLICATE

**Comment by sumerjabri** [comment]
Closing dupe
