### ISSUE TITLE
CRAFTERCMS-2170: Duplicated content upon template change or content creation.

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#230]
Original JIRA Fix Versions:
2.5.2, 2.5.1.1, Original JIRA Components:
Studio, 
----------
Original JIRA Description: When changing the template of a content, it creates a duplicate content with the same name under the content being changed.

\_my_content
  \_my_content

This happens once you save/close the content and sometimes even on simply creating a brand new content.:
----------
Original JIRA Comments:
Can you give specific steps for the developer to follow?
----------
Also:  Are you saying the item is duplicated in the tree visually or do you see a duplicated of data in the repository?
----------
Finally: What are the details of the environment?

What repo?
What browser?

----------
Steps to reproduce it:

1) right click on a content
2) change template item click
3) change a few fields in the content
4) click save
5) refresh the page

Then observe that you have the same content created under itself.
----------
The repo is alfrescoext and the browser chrome windows.

And the item is indeed duplicated in the repo.
----------
Issue can not be reproduced with latest build of 2.5.x branch.
----------
Ticket is logged for 2.5.0, not 2.5.x (currently 2.5.1)
Customer is able to replicate.  
Let's not close until issue is fully understood and explained or fixed.

Speak to Carlos, Nic if needed.
----------
Fix version is marked as 2.5.2 and 2.5.1.1, a.k.a 2.5.x branch. As stated when ticket marked as "cannot reproduce" in 2.5.x branch issue does not exist any more. Should be confirmed by Carlos and Nic and then close ticket if they can confirm. If not, than revisit/redefine use case because the one given in description is not reproducing issue (might be content or content type dependent)
----------
Implementation-Version: 2.5.1-SNAPSHOT 
Implementation-Build: d1e6265aeb41be2beffe9b00a9904701a97244d6
Build-On: 1468463128195 (GMT: Thu, 14 Jul 2016 02:25:28.195 GMT)
----------
Hey Carlos,

Are you saying that build 2.5.1-SNAPSHOT has this problem or doesn't have this problem?
----------
No that's the current version.

We're investigating an upgrade.
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2170
----------

**Comment by russdanner** [comment]
Talk to Carlos, this ticket is difficult to reproduce.

**Comment by vestrada** [comment]
Fixed
