### ISSUE TITLE
[studio-ui] approval dialog calculate all dependencies fails due to bad site id parameter

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2301]
### Expected behavior
dialog should pass proper valid parameters to the REST service
`
/studio/api/1/services/api/1/dependency/calculate-dependencies.json
`

### Actual behavior
The service call rejects request due to invalid param

<img width="925" alt="screen shot 2018-07-23 at 11 19 28 am" src="https://user-images.githubusercontent.com/169432/43086246-e6cee590-8e6a-11e8-89eb-0e97c47e503e.png">

### Steps to reproduce the problem
* create a site 
* edit a page
* click publish
* click calculate all dependencies

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-497817
Build Number: 49781735656c60cf5f795abcc6f5f38775c499bd
Build Date/Time: 07-23-2018 09:58:33 -0400

#### OS
All

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/879

**Comment by russdanner** [comment]
Confirmed
