### ISSUE TITLE
[studio] "Unauthorized" response is returned by some API calls when non valid site id is provided or even when non valid site_id parameter is provided (On negative scenarios)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2303]
### Expected behavior
On step 4: The response should be:
404 with message { "message" : "Site not found"}
On step 5: The response should be:
400 with message { "message" : "Invalid parameter(s)" }

Note:
This issue happens for the next api calls:
*   /studio/api/1/services/api/1/group/delete.json Delete Group
*  /studio/api/1/services/api/1/group/get-per-site.json Get Groups per Site
*  /studio/api/1/services/api/1/group/users.json Get User per Group
*  /studio/api/1/services/api/1/group/remove-user.json Remove User from Group

### Actual behavior
"Unauthorized" response is returned by some API calls when non valid site id is provided or even when non valid site_id parameter is provided (negative scenarios).
{
	"message": "Unauthorized"
}

Watch the next video:

### Steps to reproduce the problem
* Create a new site through studio with name **mytest**
* Go to your rest api client and create the next POST query:
http://localhost:8080/studio/api/1/services/api/1/security/login.json with json body:
{
	"username":"admin",
	"password":"admin"
}
and using valid X-XSRF-TOKEN
*  Execute the query of above
* Create a new GET query for Get groups per Site:
http://localhost:8080/studio/api/1/services/api/1/group/get-per-site.json?number=10&site_id= mytestnonvalid&start=0

Notice the site not found scenario
Notice that this request returns:
{
	"message": "Unauthorized"
}

* Create a new GET query for Get groups per Site:
http://localhost:8080/studio/api/1/services/api/1/group/get-per-site.json?number=10&site_idnonvalid= mytest&start=0

Notice the non valid parameter scenario
Notice that this request returns:
{
	"message": "Unauthorized"
}

We have problems on site_id validations for negative scenarios.
### Log/stack trace (use https://gist.github.com)
No log error trace on tomcat log
### Specs
Crafter studio api
#### Version
Studio Version Number: 3.0.15-SNAPSHOT-d4e9f1
Build Number: d4e9f168179630ec61df67fafe1396181ab8373d
Build Date/Time: 07-23-2018 13:05:59 -0600
#### OS
Linux, Mac, Windows
#### Browser
--

**Comment by luishernandezmonge** [comment]
@dejan-brkic Please, can you provide a full list of what API1 calls are deprecated, just to check and let them out of 3.1.1 test-suite.

**Comment by dejan-brkic** [comment]
Group services:
- /studio/api/1/services/api/1/group/add-user.json
- /studio/api/1/services/api/1/group/create.json
- /studio/api/1/services/api/1/group/delete.json
- /studio/api/1/services/api/1/group/get.json
- /studio/api/1/services/api/1/group/get-all.json
- /studio/api/1/services/api/1/group/get-per-site.json
- /studio/api/1/services/api/1/group/remove-user.json
- /studio/api/1/services/api/1/group/update.json
- /studio/api/1/services/api/1/group/users.json

User services:
- /studio/api/1/services/api/1/user/create.json
- /studio/api/1/services/api/1/user/delete.json
- /studio/api/1/services/api/1/user/disable.json
- /studio/api/1/services/api/1/user/enable.json
- /studio/api/1/services/api/1/user/get.json
- /studio/api/1/services/api/1/user/get-all.json
- /studio/api/1/services/api/1/user/get-per-site.json
- /studio/api/1/services/api/1/user/status.json
- /studio/api/1/services/api/1/user/update.json

**Comment by luishernandezmonge** [comment]
thanks, will remove all of this from the test suite file for 3.1 test-suite version. And close this ticket.
