### ISSUE TITLE
[studio-ui] bulk publish should allow user to specify the environment they want to push to 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2306]
### Expected behavior
User should be able to bulk publish to both live and staging

<img width="1115" alt="screen shot 2018-07-26 at 2 02 34 pm" src="https://user-images.githubusercontent.com/169432/43279860-3508eb92-90dd-11e8-8357-3d62e37ce3bc.png">

Only show environments that are active for the given site.
Default the environment drop down to the first environment listed

### Actual behavior
Bulk publish assumes live

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-497817
Build Number: 49781735656c60cf5f795abcc6f5f38775c499bd
Build Date/Time: 07-23-2018 13:30:23 -0400

#### OS
Any
#### Browser
All

**Comment by sumerjabri** [comment]
@russdanner please set priority on this issue

**Comment by russdanner** [comment]
Confirmed
