### ISSUE TITLE
[studio-ui] Cannot see the whole username in the Submitted By column value in the Reject dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2311]
### Expected behavior
It would be nice if `Item` values and `Submitted By` values are left aligned in their column and that the `Item` value does not overrun the `Submitted By` column.  It would be nice to have a scroll bar or something also to be able to see the whole username so if a lot of users have very similar beginnings in the username, approver will still be able to distinguish.

### Actual behavior
The `Item` values and `Submitted By` values are not left aligned in their column such that the `Item` value overruns the `Submitted By` column and you can't see the whole value for the `Submitted By` column

![screen shot 2018-07-31 at 11 27 07 am](https://user-images.githubusercontent.com/25483966/43469932-54c1d80a-94b5-11e8-895d-cf90421e8e70.png)

### Steps to reproduce the problem
* Create a site using website_editorial and create a user author
* Sign in as user author and edit a page and request publish
* Sign in as user admin and reject the publish request from user author.  Notice the Reject dialog looks as mentioned in the Actual Behavior above.

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-292fdc
Build Number: 292fdcfcc52f0eca4f3cd545af0478c448c5969f
Build Date/Time: 07-31-2018 02:25:00 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/885

**Comment by alhambrav** [comment]
Verified fixed.
