### ISSUE TITLE
[studio-ui] Status in context nav for "Home" page is not updated when "Pages" is not expanded right after creating site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2312]
### Expected behavior
Status in context nav should be updated for "Home" page  when "Pages" is not expanded right after creating site

### Actual behavior
Status in context nav for "Home" page is not updated when "Pages" is not expanded right after creating site

![screen shot 2018-07-31 at 11 56 27 am](https://user-images.githubusercontent.com/25483966/43471564-439e91cc-94b9-11e8-9323-2285564b1d22.png)

### Steps to reproduce the problem
* Clear your cache
* Create a site using website_editorial 
* Click on `Edit` in the context nav to edit the `Home` page and make changes then save it
* Notice the icon on the context nav for the `Home` page is not updated

### Log/stack trace (use https://gist.github.com)
Here's a short clip: 
https://www.useloom.com/share/283ddfca458b408682b6bffd2540db0c

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-292fdc
Build Number: 292fdcfcc52f0eca4f3cd545af0478c448c5969f
Build Date/Time: 07-31-2018 02:25:00 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/888

**Comment by alhambrav** [comment]
Verified fixed.
