### ISSUE TITLE
[studio-ui] clicking the home page from the dashboard does not preview properly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2313]
### Expected behavior
clicking the home page in any dashboard should take user to preview for the home page

### Actual behavior
clicking the home page in any dashboard takes the user to a broken preview due to bad url ?page= instead of ?page=/

https://www.useloom.com/share/4d6b5a0a3f7e490692b35f72aedb0e5f

### Steps to reproduce the problem
* edit the home page, save and close
* click on page from site content menu, see that it previews properly
* go to the dashboard
* click on home page in recent activity, see that it does not preview properly
* not this is the case with all dashboards, including go live queue/show in-progress items

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
2.5.19

#### OS
Any
#### Browser
Any

**Comment by vestrada** [comment]
PR - 2.5.x: https://github.com/craftercms/studio-ui/pull/887

**Comment by russdanner** [comment]
Confirmed
