### ISSUE TITLE
[craftercms] Upgrade Spring version to 4.3.18

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2319]
Upgrade Spring dependencies to version 4.3.18 in modules:

* Commons Utilities
* Commons Validation
* Core
* Crafter Profile Admin
* Crafter Profile Security Provider
* Crafter Profile Server
* Crafter Search API
* Crafter Search Batch Indexer
* Crafter Search Integration Test
* Crafter Search Server
* Crafter Social Server

**Comment by jdrossl** [comment]
@avasquez614 Spring version in the Deployer is defined by Spring Boot, after applying https://github.com/craftercms/craftercms/issues/2320 it will use Spring 5.0.8

**Comment by avasquez614** [comment]
@jdrossl please update Engine's version too

**Comment by avasquez614** [comment]
Verified
