### ISSUE TITLE
[deployer] Switch to a threadpool model instead of thread per target

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2326]
Today we start a thread per deployment target. Given that the thread can get stuck as it connects over SSH and never recovers. A target may get stuck. Additionally, this means a pretty heavy use of threads for a system with a large number of threads and a large number of Engines.

We should switch to:
1. Thread pool with configurable threads (up and max) (think Tomcat)
2. Threads compete for work and can "lock" a target as they operate on it
3. There may be more targets than threads, and threads will continue to work against the queue util the work is completed for that period
4. If a piece of work is scheduled before the prior invocation is completed, the new work is ignored (drop a period) -- not doing that can result in a backlog we cannot recover from

**Comment by avasquez614** [comment]
@jdrossl start working on points 1-4 and we will discuss later points 5 and 6

**Comment by jdrossl** [comment]
I found a small bug while working on this feature: https://github.com/craftercms/craftercms/issues/2408

**Comment by jdrossl** [comment]
Points 1-4 have been implemented

**Comment by avasquez614** [comment]
1-4 verified

**Comment by sumerjabri** [comment]
Break into two tickets, half here and close, half in a new ticket for a later release.

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/2451
