### ISSUE TITLE
[craftercms] Run git gc once in a while on authoring and delivery repos.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2329]
Running `git gc` seems to increase the performance of repos. It might be good idea to make Studio and the Deployer run this command once in a while to clean up the authoring and delivery repos.

**Comment by russdanner** [comment]
Is it possible to back port this to 3.0.x?

**Comment by sumerjabri** [comment]
@jdrossl I think we can do this:
- Studio: Run based on a cron, default config is Sunday at 3AM local timezone. Runs against all `sandbox`/`published`
- Deployer: Run based on a cron, default config is Sunday at 3AM local timezone. Runs against all target repos.

Ping me to discuss more as needed.

**Comment by avasquez614** [comment]
Verified
