### ISSUE TITLE
[studio-ui] Add a footer to show the entitlement description

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2335]
Studio should include a footer that is visible at all times.

The content of the footer is a small HTML string that needs to be printed from freemarker with the following code: `${applicationContext.get("crafter.entitlementValidator").getDescription()}`

**Comment by vestrada** [comment]
On hold

**Comment by jdrossl** [comment]
The needed changes have been merged in both 3.0.x & 3.1

**Comment by vestrada** [comment]
PR: 
3.0.x: https://github.com/craftercms/studio-ui/pull/892

3.1.x: https://github.com/craftercms/studio-ui/pull/893
