### ISSUE TITLE
[studio-ui] portions of preview are hidden at certain responsive breakpoints

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2336]
### Expected behavior
The full site should be previewable regardless of the breakpoint

### Actual behavior
As the context menu starts to wrap portions of the site/preview get hidden behind the menu
https://www.useloom.com/share/992ed96a47ec45da96dae492fdd6fa62

### Steps to reproduce the problem
* Open a site 
* Squeeze the browser viewport 

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-fb10b6
Build Number: fb10b69ddd975289c0da703ebc6c65aa3dea3055
Build Date/Time: 08-07-2018 15:57:46 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/889

**Comment by russdanner** [comment]
Confirmed
