### ISSUE TITLE
[studio] Sidebar does not update on author initiated state changes without a refresh

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2337]
### Expected behavior
Side bar should attempt to update item status after author takes and action that changes state:
Write (edit, revert, duplicate, paste)
Delete
Submission to workflow

### Actual behavior
https://www.useloom.com/share/6893ee7b0ea040438b75e0c38ace99b7

### Steps to reproduce the problem
* open side bar  
*  right click and edit content
*  save content
* Note (if in preview) context nav updates but side bar does not
* Refresh, note states change

#### Related
Dependencies also do not update.  If you have a form and in that form you link to another control, it's possible for an author to use the top level page they edited to navigate to and edit the other control.  The user's expectation is that both the top all of the items that are edited and saved would update in the sidebar without a refresh.

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-fb10b6
Build Number: fb10b69ddd975289c0da703ebc6c65aa3dea3055
Build Date/Time: 08-07-2018 15:57:46 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
Hi Russ
I'm not able to reproduce: https://github.com/craftercms/craftercms/issues/2337
Please take a look to this video: https://www.useloom.com/share/4057f4617f464428ac2fbe9db331c888

I'm using the latest Studio Version: 3.0.17-SNAPSHOT-bb4002

Please verify if this is still happening to you.

**Comment by russdanner** [comment]
Confirmed
https://www.useloom.com/share/617aa399daa14cc9996e0ba8c0fc6cb1
