### ISSUE TITLE
[engine] Add simple URL rewrite rules (like Apache HTTPd mod_rewrite) per site

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2341]
Provide a mechanism to specify rewrite rules similar to Apache HTTPd mod_rewrite per site. Have the rules manageable in Studio.

Consider using Tuckey http://tuckey.org/urlrewrite/

**Comment by sumerjabri** [comment]
@alhambrav Please test and validate as you document.

**Comment by alhambrav** [comment]
Started validating.  Does not seem to work right now or I may have an incorrect config.  There's a ticket to enable debugging https://github.com/craftercms/craftercms/issues/2498

**Comment by alhambrav** [comment]
Verified.
