### ISSUE TITLE
[studio] Compare history is broken

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2357]
### Expected behavior
You can compare prior versions to current or to each other.

### Actual behavior
Comparing anything causes HTTP 500, see logs.

### Steps to reproduce the problem
* Create any site
* Click on the history of any page
* Click on the `Compare to Current` button

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/sumerjabri/89b4af5a405f59b0e81826fa2ba571fc

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-4b096f
Build Number: 4b096f0b69e76dd7c29481ecb1b592027be46bbc
Build Date/Time: 08-14-2018 16:53:52 -0400

#### OS
Ubuntu Linux

#### Browser
Chromium

**Comment by sumerjabri** [comment]
This is related to the dep upgrades.

**Comment by russdanner** [comment]
The fix is:
Studio source file:
`/default-site/scripts/libs/HTMLCompareTools.groovy`

Line 26:
`"<xsl:template match=\"//\">" +`

Must be changed to:
`"<xsl:template match=\"/\">" +`

This can be changed in the war file manually as a workaround.  The path to the file is:
`apache-tomcat/webapps/studio/default-site/scripts/libs/HTMLCompareTools.groovy`

**Comment by yacdaniel** [comment]
Reproducible in: 
```
Studio Version Number: 3.1.0-SNAPSHOT-203e40
Build Number: 203e40a4ed71883151486c8c9a41caa9654d2082
Build Date/Time: 04-05-2019 08:20:44 -0600
```
Log: https://gist.github.com/yacdaniel/1248708511f41e9c8968984d11e93242

**Comment by dejan-brkic** [comment]
Cannot reproduce it 
```
Studio Version Number: 3.1.0-SNAPSHOT-3e248b

Build Number: 3e248b0cf3ef13cf24e471809236e995c35b51bf
```

**Comment by yacdaniel** [comment]
@dejan-brkic did you try it in Linux? in Mac seems ok.

**Comment by dejan-brkic** [comment]
Tested on `ubuntu 18.04` cannot reproduce

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1558

**Comment by jdrossl** [comment]
@dejan-brkic how is this dependency not needed in any other environment? just for curiosity

**Comment by dejan-brkic** [comment]
No idea. Compare history is using `daisydiff.jar` which is added as binary. I checked `jar` file and does not contain a class that is causing the error (`ClassNotFoundException`). In my mind, it shouldn't work in any environment.

**Comment by avasquez614** [comment]
@dejan-brkic @jdrossl here's the jar, it's included directly: https://github.com/craftercms/studio/tree/develop/src/main/webapp/WEB-INF/lib. Is it possible that it's no being copied for some reason in that env? If we found a Maven dependency that can be used instead then maybe we can remove the library from WEB-INF.

**Comment by yacdaniel** [comment]
I am able to reproduce it in the QA machine running in AWS `Ubuntu 16.04.6 openjdk version "1.8.0_191"` and also my personal pc (`archlinux openjdk version "1.8.0_212"`)

**Comment by jdrossl** [comment]
@avasquez614 that's what caught my attention, the missing class is not from `daisydiff.jar`, so it looks like it is somehow provided from the OS, tomcat or something else

**Comment by avasquez614** [comment]
Weird... @dejan-brkic is right. The missing class is used by Daisydiff. It should fail in all environments. Well we need to find a new library anyway later.

**Comment by yacdaniel** [comment]
Verified fixed.
