### ISSUE TITLE
CRAFTERCMS-2176: 'Recently Published' doesn't render 'Publisher' column properly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#236]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: Please see attached. It should display the last column with a proper column title. :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-2176
----------

**Comment by hlim** [comment]
<img width="329" alt="screen shot 2016-11-15 at 5 09 41 pm" src="https://cloud.githubusercontent.com/assets/4325885/20326345/54637c50-ab56-11e6-97f5-15d485f55044.png">

**Comment by asotog** [comment]
took this

**Comment by hlim** [comment]
the fix confirmed
