### ISSUE TITLE
[engine] some characters are not supported as parameters in REST services

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2360]
### Actual behavior
`{ / } |` characters in parameter values causes a 404 

Example:
`http://localhost:8080/api/test.json?p1=foo\bar`

### Steps to reproduce the problem
* create a REST script e.g:` /scripts/rest/test.groovy` with content `return "hello"` 
* invoke the API with a parameter: `http://localhost:8080/api/test.json?p1=foo\bar`
* Note response is a 400

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
All

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
Tomcat 8+ has increased security that does not allow characters outside the standard to be processed.  If you look at your log files you will note that there is an error saying as much:

From catalinia.out:
```
org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
```

Further reading can be found here:
https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters

`| { \ } `

and other characters outside the RFC 7230 and RFC 3986 must be escaped.
