### ISSUE TITLE
[studio] enhance authentication requirements configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2364]
### Expected behavior
Allow an administrator to specify/configure rules for studio passwords for accounts managed by Studio

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-4c989c
Build Number: 4c989c7cb50201155c988637a6db453257b7a1cc
Build Date/Time: 08-02-2018 14:57:36 -0400

#### OS
Any

#### Browser
All

**Comment by sumerjabri** [comment]
Please add a regex to limit/configure what valid passwords can be in Studio YAML config.
Please enforce in the back, and work with UI to have them honor the same rules, and be able to handle the exceptions.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1647

**Comment by russdanner** [comment]
I will confirm this but I will open another ticket to add a user message in the same YAML file for the response. The error message going back to the user should be able to tell them what the requirements are which must be supplied by the person who wrote the rules.

"User password does not fullfill requirements" is not a user-friendly response.
