### ISSUE TITLE
[studio] Preview URL should be exclusively managed and set in environment.xml

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2368]
### Expected behavior
The previewAppBaseUri value should be exclusively supplied by  `/config/studio/environment/environment-config.xml` based on the value of the `preview-server-url` tag

### Actual behavior
Studio makes the preview server URL available to it's UI in the StudioAuthoringContext object.
The value for the preview server url `(previewAppBaseUri: "https://SOME.SERVER")` is provided by a groovy file `/default-site/scripts/libs/EnvironmentOverrides.groovy`  See line 17+

```
if(result.previewServerUrl.equals("\${previewUrl}")){

     if(80 == request.serverPort ||  443 == request.serverPort) {
          result.previewServerUrl=request.scheme+"://"+request.serverName
     }
     else {
				 
         result.previewServerUrl=request.scheme+"://"+request.serverName+":"+request.serverPort
     }
}
```

The previewAppBaseUri value should be exclusively driven by  `/config/studio/environment/environment-config.xml` which can be different per site.

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
All

#### OS
All

#### Browser
All

**Comment by dejan-brkic** [comment]
Done
PR:
3.0.x: https://github.com/craftercms/studio/pull/1222
3.1.x: https://github.com/craftercms/studio/pull/1223

**Comment by russdanner** [comment]
Confirmed
