### ISSUE TITLE
[studio] creating a site based on blueprint and pushing to remote fails

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2369]
### Expected behavior
Operation should succeed 

### Actual behavior
Operation fails with exceptions
See Logs (linked)

### Steps to reproduce the problem
* Creart bare repo in remote
* Using basic credentials, push a new blueprint to the remote
** Remote name is origin, sandbox branch is master, remote branch is master

### Log/stack trace (use https://gist.github.com)
BIT BUCKET
https://gist.github.com/russdanner/1717dfce032198626e3686ab89c397c0

GITHUB
https://gist.github.com/russdanner/282a77346446b66c50f7ad003b85609a

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-f2a0f6
Build Number: f2a0f66fedb3f3d5b50fd17b81338ac25aa7fad0
Build Date/Time: 08-22-2018 12:47:29 -0400

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
@luishernandezmonge please add this to the automation suite

**Comment by dejan-brkic** [comment]
Done
PR:
3.1: https://github.com/craftercms/studio/pull/1220
3.0.x: https://github.com/craftercms/studio/pull/1219

**Comment by russdanner** [comment]
Confirmed
