### ISSUE TITLE
[documentation] create how to guides for integration with github, gitlab and bitbucket

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2370]
### Expected behavior
Create how-to guides from the blogs on integrating sites with remotes
- creating sites from a remote
- creating a site from blueprint and push to remote
- adding a remote
- pushing and pulling to and from a remote

https://blog.craftercms.org/2018/08/21/integrating-crafter-cms-with-bitbucket-for-better-devops/
https://blog.craftercms.org/2018/08/14/integrating-crafter-cms-with-github-for-better-devops/
https://blog.craftercms.org/2018/03/17/integrating-crafter-cms-with-gitlab-for-better-devops/

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/641
PR https://github.com/craftercms/docs/pull/643

**Comment by russdanner** [comment]
Confirmed
