### ISSUE TITLE
[test-suite] Automate verification of create site after a failed create site with link to upstream remote git repository

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2371]
Please automate ID 18 in **Studio -> Sites** - Verify that the application allows to create a site with link to upstream remote git repository after a failed create site with link to upstream remote git repository

**Setup**
1) Setup a remote bare git repository, for example, you can create a repository in your GitHub/GitLab account, and use that for the tests.  Follow the instructions here: https://help.github.com/articles/create-a-repo/ for creating a repo in your github account
2) Setup via a configuration file or command line prompt values for the: 
    (1) Remote Git Repository URL
    (2) Remote Git Repository Username
    (3) Remote Git Repository Password

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" with an incorrect URL to the bare repo created to make the create site fail
7) In the "Authentication Type:" select "Basic"
8) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
9) In the "Blueprint" field, select "Website_editorial"
10) Click on the "Create" button
11) Close the error dialog
12) Click on "Create Site"
13) Fill in the "Site Id" field
14) Click on the "Link to upstream remote Git repository" to expand
15) Fill in the "Remote Git Repository Name" with "origin"
16) Fill in the "Remote Git Repository URL" with the URL to the bare repo created
17) In the "Authentication Type:" select "Basic"
18) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
19) In the "Blueprint" field, select "Website_editorial"
20) Click on the "Create" button

**Expected Output**
10) The "Create Site" should fail and an error dialog should appear
20) The "Create Site" dialog closes and the site created is in Preview

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
@alhambrav Already done and added to the testng_StudioSites.xml suite.

**Comment by alhambrav** [comment]
Verified.
