### ISSUE TITLE
[test-suite] Automate verification that the application allows to create a site based on a bp and push to upstream remote git repository (GitLab, etc) - Authentication type: basic

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2373]
Please automate ID 13 in **Studio -> Sites** - Verify that the application allows to create a site based on a bp and push to upstream remote git repository (GitLab, etc) - Authentication type: basic

**Setup**
1) Setup a remote bare git repository, for example, you can create a repository in your Gitlab account, and use that for the tests.  Follow the instructions here: https://help.github.com/articles/create-a-repo/ for creating a repo in your github account or here: https://docs.gitlab.com/ee/user/project/repository/ for creating a repo in your GitLab account
2) Setup via a configuration file or command line prompt values for the: 
    (1) Remote Git Repository URL
    (2) Remote Git Repository Username
    (3) Remote Git Repository Password

**Steps**
1) Login to Studio and go to the "Sites" screen
2) Click on "Create Site"
3) Fill in the "Site Id" field
4) Click on the "Link to upstream remote Git repository" to expand
5) Fill in the "Remote Git Repository Name" with "origin"
6) Fill in the "Remote Git Repository URL" with the URL to the bare git repo in Gitlab, etc.
7) In the "Authentication Type:" select "Basic"
8) Fill in the "Remote Git Repository Username"
9) Fill in the "Remote Git Repository Password"
10) In the "Options:" field, select "Create site based on a blueprint then push to remote bare git repository"
11) In the "Blueprint" field, select "Website_editorial"
12) Click on the "Create" button

**Expected Output**
12) The "Create Site" dialog closes and the site created is in Preview

**Comment by yacdaniel** [comment]
PR Develop: https://github.com/craftercms/test-suite/pull/405
PR Support 3.0.x: https://github.com/craftercms/test-suite/pull/406

**Comment by alhambrav** [comment]
Verified.
