### ISSUE TITLE
[studio] java.lang.OutOfMemoryError error when uploading a large file

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2374]
### Expected behavior
There should be no out of memory error when uploading a large file

### Actual behavior
There's a  java.lang.OutOfMemoryError error in the logs when uploading a large file

### Steps to reproduce the problem
* Create a site in Studio 
* Navigate to `static-assets` and right-click to upload a large file (I uploaded a ~900MB file)
* Notice the file is in the Sidebar.  Look in the logs and notice the out of memory error message (please see the stack trace below)

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/b498bf1cdfd5ebc9e72a89a6755cbabd

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-ddbb78
Build Number: ddbb788986e85e3f9d34245c8f70e9c916655915
Build Date/Time: 08-22-2018 14:11:11 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
This is related to: https://github.com/craftercms/craftercms/issues/1828

**Comment by russdanner** [comment]
This happened as part of the dependency calculation.

```
at org.craftercms.studio.impl.v1.service.dependency.RegexDependencyResolver.resolve(RegexDependencyResolver.java:65)
org.craftercms.studio.impl.v1.service.dependency.DependencyServiceImpl.upsertDependencies(DependencyServiceImpl.java:96)
```

Dependency calculator should not load entire files at a time to scan.

@vita What was the file name?

**Comment by sumerjabri** [comment]
- Determine content type per dep extract
- Decide if we must extract
- Extract if yes

+ happy path logging please

**Comment by alhambrav** [comment]
Verified fixed.
