### ISSUE TITLE
[studio] Add support for WebDAV data source and picker

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2375]
As we've done for S3 and Box, we need a new data source and picker for WebDAV.

Please create a new API and associated configuration mechanics to support uploading assets to a WebDAV share, and a picker to pick URLs from a WebDAV.

The picker will result in a URL that points to the WebDAV asset and will not copy it locally.

The picker will be configurable to know where the WebDAV repo is, and configurable in the base-URL to be used when generating the final asset URL.

Ping me for more context and design options.

**Comment by sumerjabri** [comment]
@jdrossl please make sure to send PR to 3.0.x too.

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/910
studio: https://github.com/craftercms/studio/pull/1276

**Comment by jvega190** [comment]
Filters for images and videos pending

**Comment by sumerjabri** [comment]
@jvega190 please add to 3.0 as well

**Comment by sumerjabri** [comment]
@jvega190 Assign to me for testing once you're done with 3.0

A new ticket is added for filtering: https://github.com/craftercms/craftercms/issues/2481
