### ISSUE TITLE
[studio] dependency calculator configuration should be explicit about the kinds of static assets it scan

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2376]
### Expected behavior
Some files should not be scanned for dependencies:
- executables
- video and audio
- zips and other archives
- text files .txt
- readmes
- etc

The last item on the list (etc) is the issue.  The list of types of files which should not be scanned cannot be known.  Therefore, each blueprint should describe the list of file types that should be scanned.

Example: Almost every website blueprint should scan common web assets (CSS, JS, etc)

Example 2: Angular and react apps should scan .hbs and other template files

Update existing blueprints to explicitly list the types of static-assets that make sense to scan
CSS, JS, HTML, XML 

### Actual behavior
Objects in current blueprints are all configured to blindly scan all static assets
`/static-assets/([^&lt;"'\)]+)`

### Steps to reproduce the problem
NA

### Log/stack trace (use https://gist.github.com)
NA

#### Version
Tested with:
Studio Version Number: 3.1.0-SNAPSHOT-f2a0f6
Build Number: f2a0f66fedb3f3d5b50fd17b81338ac25aa7fad0
Build Date/Time: 08-22-2018 12:47:29 -0400

2.x and 3.0.x 

#### OS
NA

#### Browser
NA

**Comment by sumerjabri** [comment]
Static asset resolver must be configured with the correct patterns:
```
        <item-type>
            <!-- name of type -->
            <name>asset</name>
            <!-- how to identify items of this type -->
            <includes>
                <!-- path pattern regexes (multiple) -->
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.css</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.js</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.html</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.xml</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.json</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.scss</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.sass</path-pattern>
                <path-pattern>/static-assets/([^&lt;"'\)]+)\.hbs</path-pattern>
            </includes>
            <!-- how to find dependencies in these items -->
            <dependency-types>
                <dependency-type>
                    <name>asset</name>
                    <includes>
                        <!-- path patterns to look for (multiple) -->
                        <pattern>
                            <find-regex>/static-assets/([^&lt;"'\)]+)</find-regex>
                        </pattern>
                    </includes>
                </dependency-type>
            </dependency-types>
        </item-type>
```

**Comment by russdanner** [comment]
Confirmed
