### ISSUE TITLE
[documentation] add lowercase rewrite rule to production installation example for Crafter Engine

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2382]
Crafter Studio forces all URL paths names to be lower case so that you have a consistent naming pattern on the server for the files.

This allows you to do is to add a rewrite rule on the web server that takes all inbound URLs and lower cases them before proxying them to Crafter Engine.

With the rewrite rule in place, the URL the user sees can be any case 

```
RewriteCond %{REQUEST_URI} !^/static-assets/.*$ [NC]
RewriteCond %{REQUEST_URI} !^/api/.*$ [NC]
RewriteMap lc int:tolower 
RewriteRule ^/(.*)$ /${lc:$1} 
```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/618 and https://github.com/craftercms/docs/pull/619

**Comment by russdanner** [comment]
confirmed
