### ISSUE TITLE
[studio] Rename DAO to TO and mapper to DAO

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2385]
For https://github.com/craftercms/studio/pull/1218/files

Per our code review, rename DAO to TO and *mapper to DAO.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1237

**Comment by sumerjabri** [comment]
@avasquez614 validate please

**Comment by avasquez614** [comment]
Verified
