### ISSUE TITLE
[studio] Code clean up after API2 is stable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2388]
Clean up:
src/main/java/org/craftercms/studio/api/v2/service/security/GroupService.java

Remove:
```
    List<String> getSiteGroups(String siteId);
    List<String> getGlobalGroups();
```

and similar unused methods.

**Comment by dejan-brkic** [comment]
All unused method already removed with other tickets

**Comment by sumerjabri** [comment]
I still see this:
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/security/GroupServiceImpl.java#L133

and this:
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/api/v2/service/security/GroupService.java#L126

**Comment by dejan-brkic** [comment]
These methods are used by other services.
