### ISSUE TITLE
[studio] Remove magic numbers and simplify impl

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2391]
Remove magic numbers from `createSite` API calls where the magic numbers are the org-id.
Don't instantiate the empty list, instead use the empty list provided by collections (same line of code).

And this: https://github.com/craftercms/studio/pull/1225/files#diff-3b55adc021a2f6759d3fbcff26d521edR698

https://github.com/craftercms/studio/pull/1225/files#diff-26335eb6094aa4d2123a30a82cfa5e2eR360

 and similar

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1256

**Comment by sumerjabri** [comment]
I had also requested you don't instantiate empty lists, instead use the empty list provided by collections. Here is an example: https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java#L518

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1259

**Comment by dejan-brkic** [comment]
New PR:
https://github.com/craftercms/studio/pull/1260
