### ISSUE TITLE
[studio] Cannot startup studio from develop fresh install - error in logs

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2394]
### Expected behavior
Studio should startup properly (give you the login screen) and there should be no error in the logs during startup

### Actual behavior
When studio starts up, the user sees the `No Site is set` screen and when you look at the logs, there is an error

### Steps to reproduce the problem
* Do a fresh install of crafter: `git clone https://github.com/craftercms/craftercms.git -b develop`
* Build, deploy and start the installation
* Watch the logs after starting, notice the error message
```
[ERROR] 2018-08-28 10:22:05,617 [localhost-startStop-1] [context.ContextLoader] | Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseInitializer' defined in class path resource [crafter/studio/database-context.xml]: Invocation of init method failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Could not connect: Unknown database 'crafter')
```
(see the log below for the full stacktrace)
* In your browser, enter `localhost:8080/studio`, notice the no site is set screen

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/af9b7c1195d1cae2ce14d5b726895de8

#### Version
latest develop
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1221

**Comment by alhambrav** [comment]
Verified fixed.
