### ISSUE TITLE
[studio] Fix failing test cases

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2395]
### Expected behavior
Test cases should succeed during a standard build

### Actual behavior
Several test cases fail to execute. These are related to retired API 1 services that have been replaced with API 2 services.

### Steps to reproduce the problem
* Build Crafter Studio from scratch without disabling testing

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
3.1.0-SNAPSHOT

#### OS
Any

#### Browser
N/A

**Comment by dejan-brkic** [comment]
I didn't find any tests failing
```
Studio Version Number: 3.1.0-SNAPSHOT-e70393

Build Number: e70393346c0001a235f45db64372cc6c7fac4a58
```
