### ISSUE TITLE
[studio] Error creating a site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2396]
### Expected behavior
User should be able to create sites without errors

### Actual behavior
When you create a site from the sites screen, the user gets a notification that crafter is `Unable to create site. Please contact your system administrator.`

### Steps to reproduce the problem
* From a fresh install of crafter, create a site
* Notice the error message in Studio
![screen shot 2018-08-28 at 3 08 53 pm](https://user-images.githubusercontent.com/25483966/44745010-840c7e00-aad4-11e8-830f-a5a76529e120.png)

*Click `Close` on the notice.  Refresh your browser, notice that even if you got the notification that it was unable to create the site, your site is still listed in the `Sites` screen.
![screen shot 2018-08-28 at 3 13 47 pm](https://user-images.githubusercontent.com/25483966/44745225-23317580-aad5-11e8-8ade-d9915925ff36.png)

* Look at the logs and notice the error message

```
[ERROR] 2018-08-28 15:04:55,106 [http-nio-8080-exec-2] [site.SiteServiceImpl] | Error while creating site: site2 ID: site2 from blueprint: empty. Rolling back.
org.springframework.dao.DuplicateKeyException:
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:12) Duplicate entry '1-1' for key 'PRIMARY'
Query is: INSERT INTO `group_user` (user_id, group_id) VALUES

            (?, ?), parameters [1,1]
```

See below for the complete stacktrace.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/d615bd772942a2da853898273a2d2939

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-56db2d
Build Number: 56db2d704bf4e24e135a39b177f0f1a4496fda45
Build Date/Time: 08-28-2018 14:55:17 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1225

**Comment by alhambrav** [comment]
Verified fixed.
