### ISSUE TITLE
[studio-ui] User is undefined when in preview or dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2403]
### Expected behavior
Valid user should be listed on top right of Studio when in preview or dashboard

### Actual behavior
User is listed as undefined on top right of Studio when in preview or dashboard

### Steps to reproduce the problem
* Create a site in Studio
* On the top right, click on the dropdown arrow.  Notice that the user listed is `undefined`
![screen shot 2018-08-29 at 11 58 01 am](https://user-images.githubusercontent.com/25483966/44799973-44e93600-ab83-11e8-9d35-5da184efba72.png)

User is listed as undefined when in Preview or the Dashboard

* Click on `Sites` on the top right, and it displays the correct user. 

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-a3aca7
Build Number: a3aca7c7e602c60e9f634a038e1d8b4e3259466e
Build Date/Time: 08-29-2018 11:28:06 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@vestrada another case of switching to the new API

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/894

**Comment by alhambrav** [comment]
Verified fixed.
