### ISSUE TITLE
[studio] Implement the new User API to get logged in user

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2406]
Please see updated spec and implement Get User in /user API.
https://app.swaggerhub.com/apis/craftercms/studio/2

**Comment by sumerjabri** [comment]
Supercedes: #2397

**Comment by avasquez614** [comment]
@vestrada please verify. With this new API you can identify when a user is logged in through SSO and disable the logout button.

**Comment by vestrada** [comment]
Verified:

![image](https://user-images.githubusercontent.com/11640613/45451762-46455300-b699-11e8-8c1d-03c7fb0803e6.png)

The UI will be worked on: https://github.com/craftercms/craftercms/issues/2450
