### ISSUE TITLE
[studio-ui] Cannot create a user

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2407]
### Expected behavior
We should be able to create a user

### Actual behavior
Cannot create a user.  In the Create User dialog, you just get a red bar at the bottom and no entry in the logs on what happened.

### Steps to reproduce the problem
* Login to Studio
* Click on Users at the top right and create a new user
* Notice the empty red bar at the bottom of the Create User dialog after you click on `Save`.  Look in the logs and notice there's no entry at all about what went wrong
![screen shot 2018-08-30 at 11 27 56 am](https://user-images.githubusercontent.com/25483966/44865402-3c126600-ac50-11e8-8b29-db00cc7fa4f5.png)

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-bc6a43
Build Number: bc6a43b4ec7ef9b163f0b2128866606f396a91ad
Build Date/Time: 08-30-2018 12:27:56 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@vestrada please switch to the new API: https://app.swaggerhub.com/apis/craftercms/studio/2

**Comment by dejan-brkic** [comment]
UI using old (deprecated) API

**Comment by sumerjabri** [comment]
Verified fixed.
