### ISSUE TITLE
[studio] Requests to the deployer are always duplicated

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2408]
### Expected behavior
When a file is changed Studio should only request a deploy one time.

### Actual behavior
All requests to the deployer are sent twice.

### Steps to reproduce the problem
* Open a file in Studio and save
* Check the log for the deployer, there are two deployments for the same site

#### Version
3.0.x, 3.1.x

#### OS
macOS

#### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1245

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss how to best approach this when working on 3.2.x

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1657

**Comment by jdrossl** [comment]
Verified
