### ISSUE TITLE
[search] Estimate AWS CloudSearch integration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2409]
- Estimate what it would take to augment Search to allow the caller to specify a _provider_.
- Given the arch: Studio uses local Solr, Studio preview deployer will push `published` to CloudSearch via Search, and delivery will use CloudSearch. Estimate updates to Search to make it happen.

**Comment by avasquez614** [comment]
After some investigation and a discussion with @sumerjabri, it was decided that pursuing ElasticSearch integration is better since the required effort is similar to the CloudSearch integration and AWS' support of ElasticSearch is better.

**Comment by sumerjabri** [comment]
Closing this in favor of AWS ES
