### ISSUE TITLE
[studio] Make sure optional parameters in User/Group API controllers are optional

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2412]
Per the API spec (https://app.swaggerhub.com/apis/craftercms/studio/2), required parameters show with a red `* required`. The ones that don't are all optional parameters.

Please make sure that User and Group API controllers have optional parameters annotated as optional, e.g. `@RequestParam(value = "offset", required = false)`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1232

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1235

**Comment by dejan-brkic** [comment]
Fixed
PR:
https://github.com/craftercms/studio/pull/1235

**Comment by avasquez614** [comment]
Verified
