### ISSUE TITLE
[studio] replace legacy fields in crafter content models that use hyphens with camel case

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2413]
### Expected behavior
Replace legacy fields in crafter content models that use hyphens with camel case
```
file-name => fileName
internal-name => internalName
redirect-url => redirectUrl
```
### Actual behavior
Some users use these legacy fields as examples which makes FTL programming more difficult

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
All

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
Won't pursue.
