### ISSUE TITLE
[studio] Update auth mechanics to match the new group structure

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2416]
Update the system such that upon LDAP or Headers (SSO) auth:
- Upsert the groups of the user into the global org
- Upsert the user membership into those groups (don't remove from old groups because someone may have added them manually)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1236

**Comment by sumerjabri** [comment]
@alhambrav please validate

**Comment by alhambrav** [comment]
Verified.
