### ISSUE TITLE
[docs] Update docs for new LDAP/Headers configuration and create an upgrade guide

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2417]
Please update the LDAP/Headers configuration and instruction on how to set those up. @avasquez614 and @dejan-brkic can help explain.

Please update the 3.0 to 3.1 upgrade guide with this information.

**Comment by sumerjabri** [comment]
@alhambrav please remember to update ADFS and related articles.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/600

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/621
