### ISSUE TITLE
[studio] items are not deleted in stage on delete

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2418]
### Expected behavior
Deletes should be pushed to both live and staging

### Actual behavior
In 3.0.x delete is an immediate deploy to live.  When staging is enabled, the delete takes place on live but not staging.

### Steps to reproduce the problem
* Create an a page
* Publish it to staging
* Publish it to live
* Delete the item
* Not that it still exists in staging

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.16-SNAPSHOT-4c989c
Build Number: 4c989c7cb50201155c988637a6db453257b7a1cc
Build Date/Time: 08-02-2018 14:57:36 -0400

#### OS
Any

#### Browser
Any

**Comment by dejan-brkic** [comment]
Can not reproduce it
```
Studio Version Number: 3.0.17-SNAPSHOT-6a16db

Build Number: 6a16dbcfe2f541b8461685982797a321d2d3ae6f
```

**Comment by russdanner** [comment]
Confirmed
