### ISSUE TITLE
[studio-ui] Site Config -> Groups is empty and cannot create new group

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2419]
### Expected behavior
`Groups` under `Site Config` should contain the default groups for a Crafter Site, and user should be able to create a new group

### Actual behavior
`Groups` under `Site Config` is empty and user is unable to create a new group

### Steps to reproduce the problem
* Create a site using any of the bp
* Open the `Sidebar` and click on `Site Config`
* Click on `Groups`, notice it is empty
<img width="1437" alt="screen shot 2018-08-31 at 3 58 25 pm" src="https://user-images.githubusercontent.com/25483966/44933521-58d59900-ad37-11e8-8859-aebeefd73bdd.png">
* Click on the `New Group` button and fill in the required fields, notice the message that user is `Unauthorized`
<img width="565" alt="screen shot 2018-08-31 at 3 59 12 pm" src="https://user-images.githubusercontent.com/25483966/44933553-7c98df00-ad37-11e8-9be1-b8164a8f88fc.png">

This sounds similar to ticket https://github.com/craftercms/craftercms/issues/2407.  Please switch to the new API: https://app.swaggerhub.com/apis/craftercms/studio/2

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-2d4c7a
Build Number: 2d4c7ab82979677de29907b5638d51d241c47425
Build Date/Time: 08-31-2018 09:39:08 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@alhambrav in 3.1 groups are managed at the organization level (with a single org at this time). Sites shouldn't have groups at all.

Related to: https://github.com/craftercms/craftercms/issues/2420
