### ISSUE TITLE
[docs] Support multi-version API documentation and support OAS 3

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2421]
For Studio (initially), we must have a mechanism in the docs to show API1 calls that are still active and used (everything except `user` and `group` API) as v1 and add a v2 with link to where the API docs are hosted:
https://app.swaggerhub.com/apis/craftercms/studio/2

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/595
