### ISSUE TITLE
[studio] Filter recently published by configured branches

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2422]
### Expected behavior
Recently published is reported on based on the two branches (names are configurable):
- live
- staging

### Actual behavior
Recently published is reported on based on all branch - master. This can be confusing if you have more than the configured branches.

### Steps to reproduce the problem
* Create additional branches in `published`
* Make changes to that branch
* See recently published dashboard, you'll see these changes

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Any 3.1.x

#### OS
Any

#### Browser
Any

**Comment by sumerjabri** [comment]
@avasquez614 Please test and validate.

**Comment by sumerjabri** [comment]
@alhambrav please test and validate.

**Comment by alhambrav** [comment]
@sumerjabri  @dejan-brkic , when publishing to staging, is the status of the page supposed to change to `published` or it should be left in the `edited` state (which is the current behavior)? 

Also, I noticed when you publish a few pages to staging or even just one page to staging, all the edited pages gets published to staging with the status icon still depicted as edited in the `Recently Published` widget in the dashboard, as described below:

1. Create a site based on website_editorial
2. Edit multiple pages
3. Setup the staging branch
4. From the dashboard, select multiple pages, then from the context nav (top), click on `Approve and Publish`
5. Publish to staging, then notice in the `Recently Published` widget in the dashboard that all the pages edited, not just the ones selected and published to staging are listed and marked as published to staging.

Here's a short clip showing when I published to staging: https://www.useloom.com/share/abf419fd9d454e1a86bdabc919e51937

When you publish  a page to live, it is reflected correctly in the dashboard `Recently Published` widget and the icon status also displays published.

**Comment by dejan-brkic** [comment]
@sumerjabri Problem here is the way how we create new environment branches. They are created from the sandbox branch from the head. This means whenever a new environment is added, because of git operations, the new environment will have all commits since the beginning of time for the site and all of them will appear as "published" in  `Recently Published` dashboard. We have to either accept this as know issue or rethink adding new environments.

**Comment by dejan-brkic** [comment]
Possible solutions:
1. Create a new environment (published repo branch) as an orphan branch (copy content and commit, losing full git log history)
2. Tag `sandbox` initial commit and create published branches from that tag

Both approaches have downsides.

**Comment by sumerjabri** [comment]
@dejan-brkic please follow solution #1

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1649

**Comment by alhambrav** [comment]
Verified only published items to live appears in the `Recently Published` widget in the dashboard.
