### ISSUE TITLE
[studio] Can't login to studio using admin valid credentials, the login API call returns 401 response

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2425]
### Expected behavior
User should be able to login as admin user.

### Actual behavior
Can't login on studio, the api call for security/login returns 401 response even if admin credentials are the correct.

Watch the next video:
https://www.useloom.com/share/c27108dadfa741808da268ff547a2adf

and on API call test:
{
	"message": "Unauthorized"
}
for api call: http://localhost:8080/studio/api/1/services/api/1/security/login.json
### Steps to reproduce the problem
* Update your environment and go to studio
* Try to login as admin, using valid credentials.
* Click on Login
* Review the api call on the Network console of the webbrowser (chrome case)

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/f88dddcbed863edf1a1fce93731725af

#### Version
craftercms 3.0.17

#### OS
Mac OSX, Linux
#### Browser
Chrome

**Comment by sumerjabri** [comment]
@dejan-brkic I can't tell if it's really 3.0.17 or 3.1.0

Let's figure this out quick.

**Comment by dejan-brkic** [comment]
Found the problem. In the latest create DB script I have changed `admin` user to `sysadmin` per new groups and organization mechanics. `sysadmin` is a new superuser belonging to `system_admin` group

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1239

**Comment by luishernandezmonge** [comment]
Verified as fixed.
