### ISSUE TITLE
[studio] Error in logs when starting authoring

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2426]
### Expected behavior
There should be no errors in the logs when starting authoring

### Actual behavior
There's an error in the logs when starting authoring, so when you start Studio, you get a `No Site is Set` and some other errors in the logs

### Steps to reproduce the problem
* Clone craftercms `git clone https://github.com/craftercms/craftercms.git -b develop` 
* Init, build and deploy
* Start authoring and watch the logs `./gradlew start`  
Notice the error:
```
[ERROR] 2018-09-05 09:55:13,838 [localhost-startStop-1] [context.ContextLoader] | Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cstudioLdapSecurityProvider' defined in class path resource [crafter/studio/studio-security-context.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'userMapper' of bean class [org.craftercms.studio.impl.v2.service.security.DbWithLdapExtensionSecurityProvider]: Bean property 'userMapper' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
```
Below is the whole stack trace of the error

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/ddc7623694696f6c51615bcc5492c30f

#### OS
OS X

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1239

**Comment by alhambrav** [comment]
Verified fixed.
