### ISSUE TITLE
[studio] Update API 2 spec for delete

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2429]
API 2 deletes for users and groups delete a collection of user/groups in a single API operation. Update the API spec by removing the 207 Multi Status response on success and instead indicate a 204 Deleted.

**Comment by sumerjabri** [comment]
@avasquez614 it's still a bulk operation, but it's atomic

**Comment by avasquez614** [comment]
@sumerjabri updated the ticket accordingly.

**Comment by jdrossl** [comment]
@avasquez614 @sumerjabri does the same apply for `DELETE /groups/{id}/members`?

**Comment by avasquez614** [comment]
@jdrossl yes, remove group members is also done in a single operation.

**Comment by avasquez614** [comment]
Verified
