### ISSUE TITLE
[studio-ui] Users are created disabled by default

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2431]
### Expected behavior
By default, users are created enabled.

### Actual behavior
Users default to disabled.

### Steps to reproduce the problem
* Create a user
* Edit the user
* See the `Enabled` flag set to false

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-d980c2
Build Number: d980c27f6378cfe76a50eb9ae6e8bc580630f5a2
Build Date/Time: 09-05-2018 17:10:47 -0400
```

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/899

**Comment by sumerjabri** [comment]
Verified
