### ISSUE TITLE
[test-suite] Create test cases for API v2.0.x

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2432]
https://app.swaggerhub.com/apis/craftercms/studio/2.0.2

**Comment by luishernandezmonge** [comment]
Start working on this.

**Comment by luishernandezmonge** [comment]
Implemented on the next PR: https://github.com/craftercms/test-suite/pull/386 for api2 2.0.6 version.

**Comment by luishernandezmonge** [comment]
Already implemented on develop.
