### ISSUE TITLE
[studio] "Report a bug" text should be on the same line in licensing notice

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2433]
### Expected behavior
but the full text "report a bug" on the same line (instead of wrapping the text on `bug`)

### Actual behavior
<img width="638" alt="screen shot 2018-09-05 at 10 56 39 pm" src="https://user-images.githubusercontent.com/169432/45132530-57ed9e80-b15f-11e8-99c9-b53eefc34fe9.png">

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-cd5717
Build Number: cd5717fae00fe56905a7879374cd8f2cf2ccc4f7
Build Date/Time: 09-05-2018 22:47:27 -0400

#### OS
All

#### Browser
Any

**Comment by sumerjabri** [comment]
Resizing the preview port solves it.
