### ISSUE TITLE
[studio-ui] Form drop down doesn't show selected item for some data-sources

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2436]
### Expected behavior
If an item in a drop-down is selected from a repo-based XML data-source and is present in the descriptor, it must show up as selected in the form engine drown-down menu

### Actual behavior
An item in a drop-down is selected from a repo-based XML data-source and is present in the descriptor, but it doesn't show up as selected in the form engine drown down menu. Instead, the drop-down menu shows nothing as selected, and looking at the HTML source, nothing is shown in that field.

### Steps to reproduce the problem
* Create a content type with a drop-down backed by a repo XML source
* Create an item based on that type
* Open saved content and see drop-down as empty

#### Version
3.0.16 and 3.1.0-SNAPSHOT

#### OS
Any

#### Browser
Any

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/897
3.0.x: https://github.com/craftercms/studio-ui/pull/898
