### ISSUE TITLE
[studio] Update API 2 spec for addGroupMembers, disableUser and enableUser

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2438]
Just like in https://github.com/craftercms/craftercms/issues/2429, addGroupMembers, disableUser and enableUser methods are bulk but do everything in a single DB operation. Please update the API spec so that they return `200 OK` instead of `207 Multiple results`.

**Comment by jdrossl** [comment]
@avasquez614 should those operations still return the affected entities or just the `ApiResonse`?

**Comment by avasquez614** [comment]
They should return the affected entities.

**Comment by avasquez614** [comment]
Although there's a ticket already to fix that: https://github.com/craftercms/craftercms/issues/2437

**Comment by avasquez614** [comment]
Verified
