### ISSUE TITLE
[studio-ui] Inside the site preview, there's no way to return to the Global Menu

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2439]
### Expected behavior

In the top menu, in the dashboard or preview, there should be a button that returns the user to the Global Menu.

### Actual behavior

Right now, there's only a Sites button that returns the user to the old Sites Menu.

### Steps to reproduce the problem
* Login to Studio
* Go to the Preview of a site
* See as top menu doesn't have a button for Global Menu and instead has one for Sites

**Comment by sumerjabri** [comment]
Ticket: https://github.com/craftercms/craftercms/issues/2290 covers this use-case, see diagram. The top menu will update throughout the site to show the right menu items.

Will assign anyway to make sure it's done right.

**Comment by avasquez614** [comment]
Verified
