### ISSUE TITLE
[studio] API2 - Delete /groups call does not delete the specified group (stills there when execute GET request)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2442]
### Expected behavior
The group should be deleted and that specific group should not be listed on the GET call (after delete)
### Actual behavior
The group is not deleted after execute the DELETE call.
Watch the next video: 
https://www.useloom.com/share/96698cf653444463b5be1aa1a8fe3fe9

### Steps to reproduce the problem
* Create a group using api2 call
* Execute the Get all groups api2 call
* Execute the next DELETE group call:
**http://localhost:8080/studio/api/2/groups?id=YOURGROUPID**

* Execute the Get all groups api2 call again

### Log/stack trace (use https://gist.github.com)
--
#### Version
craftercms API2:
https://app.swaggerhub.com/apis/craftercms/studio/2.0.3#/groups/deleteGroup
#### OS
Mac OSx
#### Browser
--

### Notes
Notice that same scenario happens on studio.
Studio Version Number: 3.1.0-SNAPSHOT-ef3488

**Comment by dejan-brkic** [comment]
Already fixed with this ticket:
https://github.com/craftercms/craftercms/issues/2427

**Comment by luishernandezmonge** [comment]
Verified as resolved
