### ISSUE TITLE
[studio] Global Menu API2 fails due to failed upgrade

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2443]
### Expected behavior
Global menu should render successfully after an upgrade.

### Actual behavior
Global menu fails to render after an upgrade.

### Steps to reproduce the problem
* In Studio 3.0.15, create a site
* Move the `data` folder to a 3.1.0-SNAPSHOT bundle
* Startup and login, see failed menu

### Log/stack trace (use https://gist.github.com)
```
[ERROR] 2018-09-10 10:37:15,419 [http-nio-8080-exec-1] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/ui/views/global_menu.json failed with response: ApiResponse{code=1000, message='Internal system failure: Unable to read global menu config @ /configuration/global-menu-config.xml', remedialAction='Contact support', documentationUrl=''} 
org.craftercms.studio.api.v2.exception.ConfigurationException: Unable to read global menu config @ /configuration/global-menu-config.xml
```

#### Version
3.1.0-SNAPSHOT upgraded from 3.0.15

#### OS
Any

#### Browser
Any

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 @dejan-brkic what would be a good solution for this issue? do we create a default config if its not present or do we add some logic to upgrade the repo content instead of only the db?

**Comment by sumerjabri** [comment]
Add the missing config file when upgrading. Other updates maybe required regardless.
