### ISSUE TITLE
[studio-ui] Global menu has inconsistent placement of tools

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2447]
### Expected behavior
Global menu tools (sites, users, groups, etc) should show up in the same location and be consistent.

Try to make everything align top-left.

### Actual behavior
Sites tool appears top/right
Users tool appears slightly lower and to the left
Groups tool appears lowest and most to the left

### Steps to reproduce the problem
* Login
* See the Global Menu

### Log/stack trace (use https://gist.github.com)
![image](https://user-images.githubusercontent.com/3931908/45308014-80bebc80-b4ee-11e8-91c0-6d97f700125c.png)
![image](https://user-images.githubusercontent.com/3931908/45308025-89af8e00-b4ee-11e8-86f0-9e58fa4a8487.png)
![image](https://user-images.githubusercontent.com/3931908/45308031-9207c900-b4ee-11e8-95ab-a2b0bc1a1779.png)

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-85a223
Build Number: 85a2235be41fca970def3160058396363374f4fc
Build Date/Time: 09-10-2018 10:08:48 -0400
```

#### OS
Linux/Ubuntu 16.04

#### Browser
Chromium

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/933
