### ISSUE TITLE
[studio] Cannot login as LDAP user

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2448]
### Expected behavior
User should be able to login as an LDAP user

### Actual behavior
There is an error in the UI when trying to login as an LDAP user
![screen shot 2018-09-10 at 11 40 39 am](https://user-images.githubusercontent.com/25483966/45308008-7dc3cc00-b4ee-11e8-9dee-b35f1bd953db.png)

### Steps to reproduce the problem
* From a fresh install of Crafter, try to login as an LDAP user
* Notice the message displayed on the UI (see above) and the info message in the tomcat log:
```
[INFO] 2018-09-10 11:39:27,504 [http-nio-8080-exec-1] [core.LdapTemplate] | No results found for search, base: ''; filter: '(uid=admin)'.
[INFO] 2018-09-10 11:39:27,505 [http-nio-8080-exec-1] [security.DbWithLdapExtensionSecurityProvider] | User admin not found with external security provider. Trying to authenticate against studio database
[INFO] 2018-09-10 11:39:27,554 [http-nio-8080-exec-1] [security.SecurityServiceImpl] | User admin logged in from IP: 127.0.0.1
[INFO] 2018-09-10 11:39:31,316 [http-nio-8080-exec-2] [security.SecurityServiceImpl] | User admin logged out from IP: 127.0.0.1
[INFO] 2018-09-10 11:39:36,593 [http-nio-8080-exec-5] [xml.XmlBeanDefinitionReader] | Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
[INFO] 2018-09-10 11:39:36,614 [http-nio-8080-exec-5] [support.SQLErrorCodesFactory] | SQLErrorCodes loaded: [DB2, Derby, H2, HDB, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase]
```

* I tested the LDAP user on version 3.0.15, and I am able to login, then I tried using the develop branch and the same LDAP user cannot login to Studio.  The info message in the tomcat does not appear all the time when trying to login as an LDAP user 

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-85a223
Build Number: 85a2235be41fca970def3160058396363374f4fc
Build Date/Time: 09-10-2018 11:29:46 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1253
https://github.com/craftercms/craftercms/pull/2449

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1254

**Comment by alhambrav** [comment]
Verified fixed.
