### ISSUE TITLE
[studio-ui] Make the signout link configurable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2450]
In support of SSO, the signout link under the user menu (top right) should be configurable.

Today, this is hardcoded to logout the user from Studio. We want this link to be configurable for SSO users to help log them out of the SSO solution (the links will be provided by the SSO vendor).

We must allow DB users and SSO users to log out. This means the link is configured per type of user-auth.

The system should also be configured to remove the signout link if the user is SSO and the admin doesn't want them to have the ability to sign out.

Ping me to decide on a design and approach for this.

**Comment by sumerjabri** [comment]
This ticket replaces: https://github.com/craftercms/craftercms/issues/1762

**Comment by sumerjabri** [comment]
This is dependent on https://github.com/craftercms/craftercms/issues/2470

**Comment by sumerjabri** [comment]
@vestrada this is ready for you now.

**Comment by sumerjabri** [comment]
@avasquez614 please validate

**Comment by vestrada** [comment]
@alfonso let me Know when the change is ready to validate it too :)

**Comment by avasquez614** [comment]
@vestrada A little change in the approach:

1. We should check if the user is logged in through SSO.
2. If it's logged in, the API `/user/logout/sso/url.json` (ticket craftercms/craftercms#2500) should be called to get the URL for SSO logout. If it's null, logout is disabled for the user.
3. For logout, first we logout the user of our system, so we still call `/api/1/services/api/1/security/logout.json`. After that, you redirect the SSO logout returned by `/user/logout/sso/url.json`.

Ping me if you have questions.

**Comment by avasquez614** [comment]
@vestrada the API /user/logout/sso/url.json` is ready

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/931

**Comment by vestrada** [comment]
@avasquez614 please verify it.

**Comment by sumerjabri** [comment]
@avasquez614 please verify

**Comment by avasquez614** [comment]
Verified
