### ISSUE TITLE
[studio] User removed from a group (via LDAP) is not removed in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2452]
### Expected behavior
User removed from a group (via LDAP) should be removed in Studio

### Actual behavior
User removed from a group (via LDAP) is not removed in Studio

### Steps to reproduce the problem
* In your LDAP server, create a user `A` who's part of groups `donkey` and `monkey`
* Login to Studio using the newly create user `A`, verify that user `A` is part of groups `monkey` and `donkey` in `Groups`.  Logout of Studio.
* In your LDAP server, modify user `A`, by removing membership to group `monkey`
* Login to Studio as user `A`, check group memberships that user `A` only belongs to group `donkey`.  Notice that user `A` is still a member of group `monkey`

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-e70393
Build Number: e70393346c0001a235f45db64372cc6c7fac4a58
Build Date/Time: 09-10-2018 15:07:22 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
@alhambrav We decided to only add and not remove, and the reasoning is:
The admin may decide to manually add the user to groups to grant them rights, and by constantly syncing the groups to what LDAP/SSO mandates, we would be disrupting that activity and constantly reverting the user back to a default that might not be required.

In most situations, the user will come in with a rarely changing set of groups that are relevant to Studio, and once configured, the Admin will assign to Studio managed groups for more fine-grained roles.
