### ISSUE TITLE
[studio-ui] Switch to use /api/2/user API calls

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2454]
Because of recent permission changes, APIs under `/api/2/users/...` can only be called by the `system_admin`. In order to get the current user's info and the user's sites, please use `/api/2/user` and `/api/2/user/sites` respectively. 

Ping me if you have any questions about the APIs.

**Comment by sumerjabri** [comment]
@vestrada please note this is specifically for those two API calls. Getting the current user (logged in user), and getting the sites visible to the current user.

**Comment by vestrada** [comment]
Waiting BE fixes to verify UI Changes.
