### ISSUE TITLE
[documentation] Update the write-content rest API documentation  examples

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2457]
### Expected behavior
https://docs.craftercms.org/en/3.0/developers/projects/studio/api/content/write-content.html

API Examples should indicate POST rather than GET
<img width="725" alt="screen shot 2018-09-11 at 3 06 23 pm" src="https://user-images.githubusercontent.com/169432/45381786-534c3e80-b5d4-11e8-9678-04c13ce787d4.png">

Add example for multi-part upload (image / document upload example)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/596 (3.0)
PR https://github.com/craftercms/docs/pull/598 (master)

**Comment by russdanner** [comment]
Confirmed
