### ISSUE TITLE
[documentation] improve explaination of the token

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2458]
### Expected behavior
Add a section up front that talks about the session and the XSRF token

- Log in API call establishes a session which is provided per J2EE in a JSESSION cookie.  Future calls must send this cookie.
- Login API sends a header and a cookie CSRF/XSRF token value which must also be sent in subsequent calls.  The value is arbitrary and is dictated by the caller.  Strong values are more secure than predictable weak ones.

### Actual behavior
The current text is part of the authentication step.  
```
The next thing you will notice, we are passing a cookie “XSRF-TOKEN” and a header “X-XSRF-TOKEN”. The value passed for these are arbitrary. They must match and they must be passed in all future PUT and POST API calls. These are used to protect against certain cross-browser scripting attacks. If you are using Studio APIs as part of a web client you want to make sure these values are randomly generated.```

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/597 (3.0)
PR https://github.com/craftercms/docs/pull/599 (master)

**Comment by russdanner** [comment]
Confirmed
