### ISSUE TITLE
[studio-ui] Timeout/re-login dialog doesn't appear on top of the global menu

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2463]
### Expected behavior
Timeout dialog must appear regardless of view

### Actual behavior
Timeout dialog doesn't appear (hidden beneath?) the global menu view

### Steps to reproduce the problem
* Set timeout to a minute
* Login as admin
* Wait a minute 

### Log/stack trace (use https://gist.github.com)
![image](https://user-images.githubusercontent.com/3931908/45391046-9d8ee900-b5ef-11e8-85fe-d43f4a535bf8.png)

#### Version
3.1.0-SNAPSHOT

#### OS
Linux/Ubuntu 16.04

#### Browser
Chromium

**Comment by jvega190** [comment]
Problem was with angular-bootstrap version, causing some modals to not show sometimes. Updated to latest possible version (fully compatible) for our angular version. Updated $modal (deprecated) to $uibModal (again, fully compatible), and dropdown to uib-dropdown. Tested rest of angular site and everything is working

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/930
