### ISSUE TITLE
[studio-ui] Change user api to get roles api in isReviewer method

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2468]
### Expected behavior
We should use new "get roles" API.

### Actual behavior
 isReviewer method is getting error in Preview page. We need to update the API.

### Steps to reproduce the problem
* Create a new site using a blue print
* Go to preview page
* Open console on the browser inspector.

#### OS
Mac

#### Browser
Chrome

**Comment by sumerjabri** [comment]
All role-based functions must check with the new roles API.
