### ISSUE TITLE
[studio-ui] Main Menu tool remains selected even if not booted

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2469]
### Expected behavior
Main Menu tools should not be selected if not booted

### Actual behavior
Main Menu tools show as selected even if the tool is not booted

### Steps to reproduce the problem
* Login as Admin
* Click on `Users`
* Click on the top left Crafter logo
* See the `Users` tool showing selected but the user management tool is not running (unselect on a fresh load of the Main Menu)

### Log/stack trace (use https://gist.github.com)
![image](https://user-images.githubusercontent.com/3931908/45509458-a1447c00-b765-11e8-8c8a-f6b97b24f4b8.png)

#### Version
3.1.0-SNAPSHOT

#### OS
Any

#### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/932

**Comment by sumerjabri** [comment]
# Steps to reproduce the problem
- Login as Admin
- Click on Users
- Click on the top right hamburger menu
- See the Users tool showing selected but the user management tool is not running (unselect on a fresh load of the Main Menu)

We must find a more general way to fix these issues.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1030
