### ISSUE TITLE
[studio] Add Publishing Queue tab to Site Config > Publishing

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2471]
### Expected behavior
Add a new tab on Site Config > Publishing tool
* Allow the user to see the publishing queue for that site as publishing packages
* Provide filters for:
  * Environment
  * State (multi-select)
  * path (simple regex `/SOME/PATH/*`)
* Filtering shows packages where one or more items in the package match and matched items within the package are highlighted
* Default the filter to items that are `READY_FOR_LIVE` and all environments
  * This shows a list of packages that are ready to go live, typically they'd be one
* Allow the user to select packages and execute an action
  * Only packages in `READY_FOR_LIVE` state can be selected
  * The only action available is to cancel publishing
  * The cancel action shows the user a warning dialog and displays the package contents to tell the user all those items within the package will be canceled

Columns to include:
- Scheduled Date
- State
- Content type
- Content Path
- Environment
- Username
- Submission Comment

**Comment by sumerjabri** [comment]
@avasquez614 Please define and design the necessary APIs to do this and then route to UI to build

**Comment by russdanner** [comment]
Related to https://github.com/craftercms/craftercms/issues/2299
Tickets are duplicate. This ticket should be kept.

**Comment by sumerjabri** [comment]
@rart please design the UX for 3.1 (React OK if it fits, think it through)

**Comment by rart** [comment]
<img width="1200" alt="publishing-queue-v3" src="https://user-images.githubusercontent.com/3928341/62894888-032eac80-bd4e-11e9-8856-b6644ac1ff46.png">

*  An initial API call would return the base package information.
    * Package id
    * Scheduled date
    * Username
    * State
    * Environment
    * Comment
* The UI presents a button per package to retrieve the package's files on demand. Pressing this button would call the supporting API to fetch the files and render them inline upon successful retrieval.

* Each package has it's own dropdown confirm action button that allows users to Cancel that item. The dropdown would have a Cancel and Confirm actions. There's a bulk cancel all which gets revealed upon selecting items on the list using the checkboxes.
<img width="275" alt="publishing-queue-confirmation" src="https://user-images.githubusercontent.com/3928341/62896262-f52e5b00-bd50-11e9-8c6d-ae2b3c9aec9d.png">

* Filters would be done in a similar fashion to the search page (dropdown panel)
<img width="444" alt="publishing-queue-filters" src="https://user-images.githubusercontent.com/3928341/62896286-06776780-bd51-11e9-94f3-579a78278ebc.png">

**Comment by rart** [comment]
@sumerjabri @dejan-brkic status of APIs please?

**Comment by sumerjabri** [comment]
Depends on: https://github.com/craftercms/craftercms/issues/3429

**Comment by sumerjabri** [comment]
@vestrada wait for #3429 to complete the API spec (it'll be in OAS 3 spec and published to SwaggerHub) and then you may begin working on the communication layer of this.

**Comment by yacdaniel** [comment]
@rart please check the missing features:


- Default the filter to items that are READY_FOR_LIVE and all environments
  - This shows a list of packages that are ready to go live, typically they'd be one

- Allow the user to select packages and execute an action
   - Only packages in READY_FOR_LIVE state can be selected
   - The only action available is to cancel publishing
   - The cancel action shows the user a warning dialog and displays the package contents to tell the user all those items within the package will be canceled

**Comment by yacdaniel** [comment]
@rart an issue:
if I have visible packages files and I use any filter then the list of packages is updated but the packages files don't
![Publishing_Queue_Filters](https://user-images.githubusercontent.com/6722074/67596474-01a63b00-f726-11e9-8574-051e39ff0570.gif)

**Comment by yacdaniel** [comment]
@yureii00 please add a refresh button, same as we have in the `Status` tab. This will be useful when we are looking at the queue and a package(s) is updated. 

Also, look at this issue:
When you use the `Fetch Package Files` and then change filters or move to another page and the newly listed packages haven't used the `Fetch Package Files`, this button will stay in the fetching state and you can click it to fetch the new files.
![Publishing issue](https://user-images.githubusercontent.com/6722074/68149316-58b8c680-ff03-11e9-8987-9d1d9144e256.gif)

**Comment by yacdaniel** [comment]
Verified!
