### ISSUE TITLE
[studio-ui] Edit and save of page content in preview does not update context nav workflow

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2474]
### Expected behavior
workflow in toolbar should update without requiring a refresh of the browser

### Actual behavior
user has to refresh to see the udated icon status and workflow options

### Steps to reproduce the problem
* create site editorial blueprint
* go to preview
* edit home page via edit button, save
* Not context nav does not update

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.17-SNAPSHOT-6a16db
Build Number: 6a16dbcfe2f541b8461685982797a321d2d3ae6f
Build Date/Time: 09-10-2018 22:28:01 -0400

#### OS
Any

#### Browser
Any

**Comment by vestrada** [comment]
Ok, please let me know.
Thanks :)

**Comment by russdanner** [comment]
These are the files that are different between the two blueprints:
```
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   config/studio/site-config.xml
	modified:   site/website/index.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	static-assets/js/git-based.gif```

**Comment by russdanner** [comment]
This cannot be reproduced reliably.  The issue is cookie cache related.  Chrome was used for the test.

I am able to reproduce this locally ONLY with a specific site ID "editorial" where the issue was first witnessed when not using a private browsing.  I do not believe the site ID to be significant other than perhaps the cookies for that site ID are somehow involved.  

Clearing browser content cache (for all time) has no positive effect.
Clearing browser cookies cache corrected the issue.  

I am no longer able to replicate the issue to investigate the issue more specifically.  

Closing the issue until a more specific set of steps for causing the issue can be determined.  At that time we'll look more surgically at specific cookies.

If you experience this issue, "clearing" your browser's cookies will correct the matter.

**Comment by russdanner** [comment]
Also worth noting:
I have used the same site ID across many installations of Crafter CMS on various versions without ever clearing my cookies.
