### ISSUE TITLE
[studio-ui] "Create User" dialog doesn't report errors to the user

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2476]
### Expected behavior
When the backend fails to create a user, the frontend should show an error and show the exception. (Just like we do on failure to create a site.)

### Actual behavior
When creating a user, if the backend fails, the frontend says the passwords don't match and doesn't let the user know that the creation failed.

### Steps to reproduce the problem
See my message to you.

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
3.0.17-SNAPSHOT and 3.1.0-SNAPSHOT (see my message)

#### OS
Any

#### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/912

**Comment by alhambrav** [comment]
Verified fixed
