### ISSUE TITLE
[studio] Add support for asset-type filtering to WebDAV

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2481]
Depends on: https://github.com/craftercms/craftercms/issues/2479

Add multiple-data sources that filter by:
- Image
- Video
- Item

Similar to what we did for CMIS.

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/921
3.0.x: https://github.com/craftercms/studio-ui/pull/922
