### ISSUE TITLE
[studio-ui] visual defect on check mark column of dashboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2483]
### Expected behavior
The visual defect should not be present

### Actual behavior
<img width="692" alt="screen shot 2018-09-17 at 1 28 39 pm" src="https://user-images.githubusercontent.com/169432/45639386-e2969d80-ba7d-11e8-9a01-7838ab225e9e.png">

resizing the window does not seem to impact or improve the issue

### Steps to reproduce the problem
* add content to your workflow dashboard via content edits, publishes, scheduled publishing etc
* look at the dashboard

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.17-SNAPSHOT-8f4ea9
Build Number: 8f4ea9a1571cdb58b65c997d34931343552d2fb2
Build Date/Time: 09-15-2018 12:10:06 -0400

#### OS
Any

#### Browser
Chrome: Version 69.0.3497.92 (Official Build) (64-bit)
Does not happen in Firefox

**Comment by jvega190** [comment]
3.0.x: https://github.com/craftercms/studio-ui/pull/915
3.1: https://github.com/craftercms/studio-ui/pull/916

**Comment by russdanner** [comment]
Confirmed
