### ISSUE TITLE
[studio] Cannot login to Studio using headers authentication

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2484]
### Expected behavior
Users should be able to login to Studio using headers for authentication

### Actual behavior
There is an error when you try to login to Studio using headers for authentication

### Steps to reproduce the problem
* Setup your Studio for headers based authentication
* In your browser, access Studio, notice the 500 error in your browser and the error message in the logs

### Log/stack trace (use https://gist.github.com)
Here's the stacktrace:
https://gist.github.com/alhambrav/aaf344d887a679461d5f77cef1b75d9f

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-6a4f78
Build Number: 6a4f78c2fe2a8b613f31bda103deaa5ee9ce7a6f
Build Date/Time: 09-17-2018 13:48:29 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1280

**Comment by alhambrav** [comment]
Verified fixed.
