### ISSUE TITLE
[studio] In some API calls scenarios the api2 does not returns the right response codes (404, 200 and 400 scenarios).

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2487]
### Expected behavior
All the listed API2 Call should returns 404 for resource not found when id does not exist
### Actual behavior
The next api calls does not returns 404 (expected) response code:

**Groups**
PATCH /studio/api/2/groups  Update Group  >> Returns 200ok
GET /studio/api/2/groups/{id} Get Group >> Returns 500
GET /studio/api/2/groups/{id}/members Get Group Members >> Returns 200ok
POST /studio/api/2/groups/{id}/members Add Member to Group >> Returns 200ok
DELETE /studio/api/2/groups/{id}/members Remove Member from Group >> Returns 200ok (Same for  400 response scenario)

**Users**
PATCH /studio/api/2/users Update User >> Returns 200ok
GET /studio/api/2/users/{id}/sites/{site}/roles >> Returns 200ok

**User**
GET /studio/api/2/user/roles/{site} (for 200ok scenario) >> Returns 404
Notice the latest is for positive scenario 200 (We expects 200 but it returns 404), maybe the url of the documentation is not the correct.

### Steps to reproduce the problem
* Run any of the methods of above using non-existent id, e.g:
For Get Group use the next call:
**http://localhost:8080/studio/api/2/groups/0**

Notice that the group = 0  does not exist and we expect the 404 response code
### Log/stack trace (use https://gist.github.com)
--
#### Version
API2 2.0.6
**https://app.swaggerhub.com/apis/craftercms/studio/2.0.6**
#### OS
Mac OSx
#### Browser
--

**Comment by luishernandezmonge** [comment]
**http://localhost:8080/studio/api/2/users/0/sites** same for this call (currently it returns 200 when we expects 404 Not Found.

**Comment by luishernandezmonge** [comment]
@avasquez614 
Currently, we have some automated test cases failed around the unexpected response codes. Please, can you check manually the next calls (and scenarios) and let me know if I'm wrong or there is something missing.
Find below the failed:
[ERROR]   UpdateUserAPI2Test.testUpdateUserResourceNotFound:75 expected [404] but found [200]

We user something like this:
URL: PATCH http://localhost:8080/studio/api/2/users

Body: 
{firstName=TestUpdated, lastName=Test, password=testerfhgjt, externallyManaged=true, id=0, email=test@test.com, enabled=true, username=testerfhgjt}

Using an existent username but non existent user id on the body.

**[ERROR]   GetUserSitesAPI2Test.testGetUserSites:61 expected [200] but found [404]**
_We use something like this:_
URL: `GET http://localhost:8080/studio/api/2/users/1/sites`
Notes:
Userid =1 for admin user.

**[ERROR]   GetUserSiteRoleAPI2Test.testGetUserSiteRoleBadRequest:80 expected [400] but found** [404]
_We use something like this:_
URL: `GET http://localhost:8080/studio/api/2/users/1nonvalid/sites/testsite/roles`
Notes:
non-valid user id and the site exists.

**[ERROR] GetCurrentAuthenticatedUserSiteRolesAPI2Test.testGetCurrentAuthenticatedUserSiteRoles:62 expected [200] but found [404]**
_We use something like this:_
URL: `GET http://localhost:8080/studio/api/2/user/roles/testsie`
Notes:
logged in as admin user id and the sited exists.

**Comment by luishernandezmonge** [comment]
Also I checked the documentation to compare all the scenarios and expected Response codes and those of above does not match.

**Comment by avasquez614** [comment]
@luishernandezmonge about UpdateUserAPI2Test.testUpdateUserResourceNotFound, it's fine that it returns 200. The username can also be used as an ID, so you can also update just using the username. If it's not clear in the documentation let me know.

I'll check the other issues.

**Comment by avasquez614** [comment]
GetUserSiteRoleAPI2Test.testGetUserSiteRoleBadRequest, it also seems ok, the call accept user ID or username, and `1nonvalid` is not an invalid username.

**Comment by luishernandezmonge** [comment]
@avasquez614 About UpdateUserAPI2Test.testUpdateUserResourceNotFound, i will work on this manually and later i will automate it using non-valid id and username to check (thanks).
And about testGetUserSiteRoleBadRequest, did you have any idea of what we can do to provoke the 400... I used the "%" but we have some issues with that scenario on automation, we need other scenario.
And how about the other positive scenarios?:
testGetUserSites **expected [200] but found [404]**
testGetCurrentAuthenticatedUserSiteRoles **expected [200] but found [404]**

**Comment by avasquez614** [comment]
@luishernandezmonge 
* testGetUserSites expected [200] but found [404]: it's a bug I'm currently fixing
* testGetCurrentAuthenticatedUserSiteRoles expected [200] but found [404]: The API URL is wrong: it's studio/api/2/user/sites/SITENAME/roles. In the case of admin user, it will return 200 with an empty list of roles because all permissions of admin are implicit: he/she can do anything.

**Comment by luishernandezmonge** [comment]
@avasquez614 thanks, I will work on fix for the second that you mentioned, and for the first I will update after Today's morning test-suite execution and check it manually.

**Comment by luishernandezmonge** [comment]
@avasquez614 checked fix for bug of above and it is fixed, also I update my testcase for the second scenario.
So, all failed scenarios looks ok, and this ticket is fixed. I will close this.
