### ISSUE TITLE
[studio] Recently published dashboard does not show deployment history for single publishing environment

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2489]
### Expected behavior
Recently published dashboard shows deployment history

### Actual behavior
Recently published dashboard does not show deployment history for single publishing environment

### Steps to reproduce the problem
* create a site from editorial blueprint
* edit a page and publish it
* recently published dashboard stays empty even after reload

#### Browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1285

**Comment by sumerjabri** [comment]
@avasquez614 please verify

**Comment by avasquez614** [comment]
Verified
