### ISSUE TITLE
[studio-ui] Multiple calls to Group API instead of one when rendering the main menu

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2492]
### Expected behavior
API should be called once

### Actual behavior
API is called three times

### Steps to reproduce the problem
* Login as Admin
* Turn on the browser debugging
* Click on the Groups tool
* See the call log

### Log/stack trace (use https://gist.github.com)
<img width="1437" alt="ui_requests" src="https://user-images.githubusercontent.com/3931908/45760570-5fe61d80-bbf8-11e8-8f18-265793873810.png">

#### Version
3.1.0-SNAPSHOT

#### OS
Ubuntu 16.04, Mac OS X

#### Browser
Chromium / Chrome

**Comment by sumerjabri** [comment]
@dejan-brkic please verify

**Comment by dejan-brkic** [comment]
Verified
