### ISSUE TITLE
[studio-ui] correct spelling issue SiteConfig on user management page

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2494]
### Expected behavior
Site Config is two words, not one (SiteConfig)

### Actual behavior
<img width="1237" alt="screen shot 2018-09-19 at 11 41 37 am" src="https://user-images.githubusercontent.com/169432/45764704-4bf2e980-bc01-11e8-81e9-d33014b8a6aa.png">

#### Version
Studio Version Number: 3.0.16-739bc7
Build Number: 739bc75ad46c6ee3210d0a0919184748656cb723
Build Date/Time: 08-09-2018 12:24:03 -0400

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/923

**Comment by russdanner** [comment]
Confirmed
