### ISSUE TITLE
[studio-ui] documentation button under help in context nav goes to invalid documentation link

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2496]
### Expected behavior
Documentation site should load

### Actual behavior
Button loads URL: https://docs.craftercms.org/en/3.0/
URL is missing index.html
User gets S3's 404

### Steps to reproduce the problem
* log in to Studio 
* click help
* click documentation

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.17-SNAPSHOT-5e8acf
Build Number: 5e8acf27a697e7a6a52f4156a5c390a3538c6687
Build Date/Time: 09-19-2018 16:41:26 -0400

**Comment by sumerjabri** [comment]
@vestrada make the URL: https://docs.craftercms.org

**Comment by vestrada** [comment]
PR: 3.1: https://github.com/craftercms/studio-ui/pull/926
PR: 3.0: https://github.com/craftercms/studio-ui/pull/927

**Comment by russdanner** [comment]
Confirmed
