### ISSUE TITLE
[engine] Add debugging for URL Rewrite

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2498]
Set up the logging of Tuckey in Engine to `slf4j`.

**Comment by alhambrav** [comment]
@avasquez, I don't see any debug messages right now when I enable debugging...   You mentioned that line 48 should be:
```
private static final Logger logger = LoggerFactory.getLogger(UrlRewriteFilter.class);
```
It works after that.  Thank you!

**Comment by alhambrav** [comment]
Verified fixed.
