### ISSUE TITLE
[studio] Error in the logs when logging in thru db when headers authentication is enabled

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2499]
### Expected behavior
There should be no error message in the logs when logging in thru the db when header auth is enabled

### Actual behavior
There's an error in the logs when logging in thru the db when header auth is enabled

### Steps to reproduce the problem
* From a fresh install, enable headers authentication by setting it up in the `studio-config-override.yaml` file
* In your browser, access Studio (`localhost:8080/studio`) 
* Log in as `admin`, again, notice the error messages in the logs 

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/alhambrav/383adf4847f7ea480da5de8d5250bc26

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-8204af
Build Number: 8204af62e23eae2955074283cf5204f8c3bd78d9
Build Date/Time: 09-21-2018 07:43:59 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1291

**Comment by alhambrav** [comment]
Verified fixed.
