### ISSUE TITLE
[studio] Implement API that returns logout URL of SSO solution

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2500]
Implement `/api/2/user/sso/logout` API that should return the URL the user should be redirected to after local logout, so he/she can be logout from the SSO solution (SSO logout should always be done after local logout). The API should return a null/empty String when SSO logout is disabled for the user.

**Comment by avasquez614** [comment]
@vestrada please test

**Comment by vestrada** [comment]
Verified
