### ISSUE TITLE
[studio-ui] Please update text in Users screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2503]
### Expected behavior
Text in user screen should say something like:
```
To add a user to a group, please use Groups from the main menu.
```
### Actual behavior
Text in user screen displays the following (groups are not in SiteConfig tools anymore):
```
To add a user to a group/site, please use the SiteConfig tools within the site.
```
### Steps to reproduce the problem
* Login to Studio
* Click on `Users` from the main menu and notice the text

<img width="1249" alt="screen shot 2018-09-25 at 8 12 46 am" src="https://user-images.githubusercontent.com/25483966/46013697-01f38300-c09b-11e8-9bf1-2675a4bf50b9.png">

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-843f65
Build Number: 843f656b69a00448aa7686ed491e309b139c59fb
Build Date/Time: 09-24-2018 09:42:05 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/934

**Comment by alhambrav** [comment]
Verified fixed.
