### ISSUE TITLE
[studio-ui] Build a new Drag and Drop UI experience

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2504]
Watch this video: https://www.useloom.com/share/6195bcc692994ea5bb4942e2d6ecf87a

Implement the features described in the video relevant to D&D. Ping me for details.

This is dependent on: https://github.com/craftercms/craftercms/issues/2485

When dragging an asset (image, video, etc):
- The controls that can accept the asset will highlight. For example, video player will accept a video asset.
- The drop-zones that can accept components that are compatible with the asset, will highlight, and Studio should create a component “on the fly” when that asset is dropped. If there's more than one compatible component, a popup will appear, letting the user pick the one he/she wants to use. For example, when dragging a video and dropping it in a drop-zone, Studio will create a video player component with the video URL.

**Comment by sumerjabri** [comment]
* 90% done

## Still todo:
* letting the user pick the widget he/she wants to use for the dropped item in case of multiple options

**Comment by rart** [comment]
@sumerjabri close? We can open more specific tickets as needed for feature requests.

**Comment by sumerjabri** [comment]
Yes, this is largely done.
