### ISSUE TITLE
[docs] Document new data sources: S3, WebDAV

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2507]
Much like the docs for Box and CMIS we need to document WebDAV and S3.

S3 is still minimal, so won't be as elaborate as WebDAV and Box. It will fully fleshed out once this ticket is completed: https://github.com/craftercms/craftercms/issues/2508

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/602

**Comment by alhambrav** [comment]
PR: https://github.com/craftercms/docs/pull/604

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/613
