### ISSUE TITLE
[studio] Add S3 form control, picker and datasource

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2508]
Much like we did for WebDAV, we need to add a similar structure for S3:
- Data source with filtering (image, video, item)

**Comment by jdrossl** [comment]
on hold for feedback about the permissions needed for the new service

**Comment by avasquez614** [comment]
Permissions will be added through ticket craftercms/craftercms#2570

**Comment by avasquez614** [comment]
@jdrossl permissions were added, please proceed with the datasources

**Comment by jdrossl** [comment]
@avasquez614 this should go to someone from UI now

**Comment by avasquez614** [comment]
@vestrada we need the datasources for S3, similar to the WebDav ones. The backend services are ready: `/aws/s3/list` and `/aws/s3/upload` (see https://app.swaggerhub.com/apis/craftercms/studio/2.0.10). Please reach out to @jdrossl if there are any questions regarding the backend.

**Comment by sumerjabri** [comment]
Sumer to work on remote resource access spec.

**Comment by avasquez614** [comment]
@vestrada the S3 service now returns the URLs as `/remote-assets/s3/...`. If you save that URL you should now be able to preview the files. Be sure to update Commons and Engine to the latest and ping me for any questions.

**Comment by vestrada** [comment]
studio -> https://github.com/craftercms/studio/pull/1377

**Comment by vestrada** [comment]
studio-ui -> https://github.com/craftercms/studio-ui/pull/998

**Comment by avasquez614** [comment]
Verified
