### ISSUE TITLE
[studio-ui] RTE image gets lost after code edit when in some cases

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2509]
### Expected behavior
RTE should never drop an image reference when switching to code view.

### Actual behavior
When the user starts to insert an image via browse but cancels and then inserts an image via upload and then goes to browse, the image tag is dropped from the code.
https://www.useloom.com/share/213666e1385f4edaa3ec5dfbec13e90a

### Steps to reproduce the problem
* open editorial blueprint
* edit an article
* put the curser in between two paragraphs
* insert image by browse for existing.  Don't pick an image.  Cancel.
* insert an image via upload
* switch to code view and note the image is gone

#### Version
2.x and 3.x
`
Studio Version Number: 3.0.17-SNAPSHOT-5e8acf
Build Number: 5e8acf27a697e7a6a52f4156a5c390a3538c6687
Build Date/Time: 09-19-2018 16:41:26 -0400`

#### OS
Any

#### Browser
Chrome

**Comment by jvega190** [comment]
3.1.x: https://github.com/craftercms/studio-ui/pull/946
3.0.x: https://github.com/craftercms/studio-ui/pull/947
2.5.x: https://github.com/craftercms/studio-ui/pull/948

**Comment by russdanner** [comment]
Confirmed
