### ISSUE TITLE
[studio] User added to system_admin group does not have access to sites

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2513]
### Expected behavior
User added to system_admin group should have access to sites
### Actual behavior
User added to system_admin group does not have access to sites

### Steps to reproduce the problem
* Login to Studio as user `admin`
* Create a site
![screen shot 2018-09-26 at 3 37 46 pm](https://user-images.githubusercontent.com/25483966/46104961-c0e69600-c1a2-11e8-8aea-ff21f6e3586c.png)

* Create a new user
* Add the new user to group `system_admin`
![screen shot 2018-09-26 at 3 39 11 pm](https://user-images.githubusercontent.com/25483966/46105010-e5db0900-c1a2-11e8-9dc5-a689ebe70458.png)

* Logout of Studio
* Login to Studio as the new user, notice that the site created by user `admin` is not listed for user `mary`, who is part of the `system_admin` group
![screen shot 2018-09-26 at 3 43 52 pm](https://user-images.githubusercontent.com/25483966/46105101-2a66a480-c1a3-11e8-9867-324d9fdab428.png)

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-55fc91
Build Number: 55fc91f4ed151432a3619cd9ac4848b9afb236d0
Build Date/Time: 09-26-2018 13:10:24 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1294

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1295

**Comment by alhambrav** [comment]
Verified sites created by admin is listed for other system_admin user.

**Comment by alhambrav** [comment]
Oops.. PR for changes hasn't been accepted.. Will check when changes are accepted.

**Comment by alhambrav** [comment]
Verified fixed.
