### ISSUE TITLE
[studio] System admin users cannot access sites from the `Sites` screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2514]
### Expected behavior
System admin users should be able to access sites from the `Sites` screen

### Actual behavior
System admin users cannot access sites from the `Sites` screen

### Steps to reproduce the problem
* Login as user `admin`
* Create a user and add the user to the `system_admin` group
* Create a site
* Logout user `admin`
* Login as the new user, go to `Sites`
![screen shot 2018-09-27 at 10 52 12 am](https://user-images.githubusercontent.com/25483966/46154572-779a5300-c243-11e8-8e00-a65c08fc7901.png)

* Click on `Preview` or `Dashboard`, notice the error message and notice also that the user does not have the global menu.  There are no errors in the tomcat log.

![screen shot 2018-09-27 at 10 52 22 am](https://user-images.githubusercontent.com/25483966/46154578-7a954380-c243-11e8-869e-d5eeae8692e6.png)

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the later steps in reproducing the problem:
https://www.useloom.com/share/e81fec0eef3c4b898e6ae9597d3d8801

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-eca233
Build Number: eca2336f2943482c7aab16a0f59253b46bcb9eac
Build Date/Time: 09-27-2018 10:20:41 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by avasquez614** [comment]
@vestrada I'm not completely sure yet but this might be an UI bug. When I log in as the other `system_admin`, the http://localhost:8080/studio/api/2/ui/views/global_menu.json API and the http://localhost:8080/studio/api/2/user/sites?limit=15&offset=0 API are returning the correct data. You can see all the sites. But when you click on the Preview/Dashboard of one, you get redirected to a page called http://localhost:8080/studio/#/sites?siteValidation=editorial2, and that's when we see the error Vita is pointed out. 

Can you check if this is a bug in the UI?

**Comment by sumerjabri** [comment]
@dejan-brkic to be handled via #2513

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1295

**Comment by alhambrav** [comment]
Verified fixed.
