### ISSUE TITLE
[studio] Headless blueprints preview does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2515]
### Expected behavior
Headless blueprints preview should work

### Actual behavior
Headless blueprints preview does not work

### Steps to reproduce the problem
* Create a site using the headless_blog bp
* Click on `Item Explorer` to preview
* In the preview, click on `Authors`.  Notice there are no authors listed but if you look in the Sidebar, there should be some authors.
![screen shot 2018-09-27 at 1 17 53 pm](https://user-images.githubusercontent.com/25483966/46163176-70317480-c258-11e8-9941-72b6da7a2e05.png)
* Try the api call to list the authors: `http://localhost:8080/api/1/author/list.json`, notice that the items returned is `0`
```
{
total: 0,
items: [ ]
}
```
* Click on `Posts` in the preview and notice also that it returns `0`
![screen shot 2018-09-27 at 1 36 08 pm](https://user-images.githubusercontent.com/25483966/46163852-56912c80-c25a-11e8-823d-f5f0afdf3170.png)

* Create another site using the headless_store bp
* Click on Catalog to preview.  Notice in the preview that no items are listed.
![screen shot 2018-09-27 at 1 37 10 pm](https://user-images.githubusercontent.com/25483966/46163953-a66ff380-c25a-11e8-8fdb-1aa906f14a97.png)
* Try the api call to list the company: `http://localhost:8080/api/1/company/list.json`, notice that it returns `0` items
```
{
total: 0,
items: [ ]
}
```

* There are no errors in the tomcat log, just INFO about the query.  It seems like the query for the list is not working (0 items returned).  See below for the INFO messages

### Log/stack trace (use https://gist.github.com)
```
[INFO] 2018-09-27 13:17:14,923 [http-nio-8080-exec-8] [security.SecurityServiceImpl] | User admin logged in from IP: 127.0.0.1
[INFO] 2018-09-27 13:17:34,464 [http-nio-8080-exec-2] [myblog] [headless.SearchHelper] [/scripts/rest/1/author/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fauthor%22&sort=name_s+desc&start=0&rows=10&q=*%3A*
[INFO] 2018-09-27 13:34:22,688 [http-nio-8080-exec-1] [myblog] [headless.SearchHelper] [/scripts/rest/1/author/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fauthor%22&sort=name_s+desc&start=0&rows=10&q=*%3A*
[INFO] 2018-09-27 13:35:38,597 [http-nio-8080-exec-8] [myblog] [headless.SearchHelper] [/scripts/rest/1/post/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fpost%22&sort=createdDate_dt+desc&start=0&rows=10&q=*%3A*
[INFO] 2018-09-27 13:37:04,346 [http-nio-8080-exec-8] [mystore] [headless.SearchHelper] [/scripts/rest/1/company/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fcompany%22&sort=name_s+asc&start=0&rows=10&q=*%3A*
[INFO] 2018-09-27 13:37:04,347 [http-nio-8080-exec-9] [mystore] [headless.SearchHelper] [/scripts/rest/1/category/list.get.groovy] | Running query: fq=file-name%3A+%22categories.xml%22&fq=content-type%3A%22%2Ftaxonomy%22&q=*%3A*
[INFO] 2018-09-27 13:37:04,348 [http-nio-8080-exec-7] [mystore] [headless.SearchHelper] [/scripts/rest/1/tag/list.get.groovy] | Running query: fq=file-name%3A+%22tags.xml%22&fq=content-type%3A%22%2Ftaxonomy%22&q=*%3A*
[INFO] 2018-09-27 13:37:04,350 [http-nio-8080-exec-3] [mystore] [headless.SearchHelper] [/scripts/rest/1/product/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fproduct%22&sort=createdDate_dt+desc&start=0&rows=5&q=*%3A*
[INFO] 2018-09-27 13:39:02,993 [http-nio-8080-exec-7] [mystore] [headless.SearchHelper] [/scripts/rest/1/company/list.get.groovy] | Running query: fq=content-type%3A%22%2Fcomponent%2Fcompany%22&sort=name_s+asc&start=0&rows=10&q=*%3A*
```
#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-eca233
Build Number: eca2336f2943482c7aab16a0f59253b46bcb9eac
Build Date/Time: 09-27-2018 10:20:41 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by jdrossl** [comment]
Not able to reproduce, this could have been a temporary issue with solr not indexing content

**Comment by alhambrav** [comment]
Cannot reproduce issue.  Closing the ticket.
