### ISSUE TITLE
[studio] Create a React JS empty blueprint

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2518]
The purpose of this blueprint is to give React JS developers a good starting point with everything they need to build their own React JS application.

**Comment by sumerjabri** [comment]
The blueprint is here: https://github.com/craftercms/react-blueprint.git

**Comment by sumerjabri** [comment]
@russdanner let me know when you feel this is ready to be published to the marketplace.

**Comment by russdanner** [comment]
It seems to be missing the XB communication hooks. See error at the bottom of preview

![image](https://github.com/craftercms/craftercms/assets/169432/1290bd44-48ab-4852-aa39-736d3bc7db2a)

**Comment by phuongnq** [comment]
Added XB

![2023-10-11_14-50](https://github.com/craftercms/craftercms/assets/2996543/8ba0d2e8-a60f-4218-b9bf-ac2e166a94e0)

**Comment by russdanner** [comment]
Confirmed
