### ISSUE TITLE
[studio-ui] "Add new members" field does not suggest/autocomplete entries on a newly created group on a fresh install

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2520]
### Expected behavior
"Add new members" should suggest/autocomplete entries on a newly created group after a fresh install

### Actual behavior
"Add new members" does not suggest/autocomplete entries on a newly created group and does not accept typing in the whole email address so you can't add a user on a newly created group after a fresh install

### Steps to reproduce the problem
* From a fresh install of Crafter CMS, Login as user admin
* Create a site, for my example, I used `myawesomesite` using the website_editorial bp 
* Create a new user, `jane`
* Create a new group `myawesomesite_author`
* Add the user `jane` to the new group by typing in `jane@example.com` in the `Add new members` field.  Notice that the `Add new members` field does not autocomplete after typing in `jane`.  Also, evein if you type in `jane@example.com`, you still cannot add user as the `Add members` button is disabled.   
![screen shot 2018-09-28 at 10 03 09 am](https://user-images.githubusercontent.com/25483966/46213175-e7711200-c305-11e8-840d-d6d99809e167.png)

If you inspect in the browser, I see the following error:
```
TypeError: Cannot read property 'length' of undefined
    at Scope.$scope.validateTag (admin.js?version=53c43040f77293e5036c9808618bcb1f6bcd795c:1064)
    at fn (eval at compile (angular.js?version=53c43040f77293e5036c9808618bcb1f6bcd795c:14086), <anonymous>:4:296)
    at destination.(:8080/studio/anonymous function) (http://localhost:8080/studio/static-assets/libs/angular/angular.js?version=53c43040f77293e5036c9808618bcb1f6bcd795c:9603:44)
    at ng-tags-input.min.js:1
    at g (ng-tags-input.min.js:1)
    at Object.i.add (ng-tags-input.min.js:1)
    at Object.i.addText (ng-tags-input.min.js:1)
    at ng-tags-input.min.js:1
    at ng-tags-input.min.js:1
    at ng-tags-input.min.js:1
```
Notice the warning message in the tomcat log as listed below.  

### Log/stack trace (use https://gist.github.com)

```
[WARN] 2018-09-28 10:02:34,333 [http-nio-8080-exec-6] [support.DefaultHandlerExceptionResolver] | Failed to bind request element: org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "undefined"
```

Here's a short clip showing the steps described above.
https://www.useloom.com/share/06139adcee1e438988113f0baea50d88

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-eca233
Build Number: eca2336f2943482c7aab16a0f59253b46bcb9eac
Build Date/Time: 09-28-2018 09:47:08 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/938

**Comment by alhambrav** [comment]
Verified fixed
