### ISSUE TITLE
[studio-ui] Notification (or warning) is not displayed when user try to delete the system_admin group

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2523]
### Expected behavior
the user should not be able to delete the system_admin group (this is ok), but a notification should be displayed to let user knows that the operation is not allowed.

### Actual behavior
studio apparently allows to delete the group but it doesn't, and no notification is displayed to let user know that user can't delete that group.

### Steps to reproduce the problem
* Go to studio and login as admin
* Go to groups management and try to delete the **system_admin** group

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/7e6a47d1cd15e072facb18b7c6040c44

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-c1bbd0
Build Number: c1bbd0c8416f90804b0f1bfca5bf93db44dca5b1
Build Date/Time: 10-02-2018 09:36:42 -0600
#### OS
Mac OSx
#### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/942

**Comment by luishernandezmonge** [comment]
Verified as resolved
