### ISSUE TITLE
[studio-ui] no error text is displayed when user try to delete the admin user on the notification.

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2524]
### Expected behavior
Error text should be displayed on the notification when user try to delete admin user.

### Actual behavior
No error cause or text is displayed on the notification.

See the next image:
<img width="1435" alt="screen shot 2018-10-02 at 11 10 19 am" src="https://user-images.githubusercontent.com/16946208/46364694-c8d78780-c633-11e8-86d6-0fb14358d6b5.png">

### Steps to reproduce the problem
* Go to Studio as admin and go to users management
* Try to delete the **admin** user
* Wait for the notification and review the **Error** element
#### Version
Studio Version Number: 3.1.0-SNAPSHOT-c1bbd0
Build Number: c1bbd0c8416f90804b0f1bfca5bf93db44dca5b1
Build Date/Time: 10-02-2018 09:36:42 -0600
#### OS
Mac OSx
#### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/941

**Comment by luishernandezmonge** [comment]
Verified as resolved
