### ISSUE TITLE
[studio-ui] Login page is displayed with gray mask after try to login with non valid password

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2527]
### Expected behavior
A notification or error should be displayed to indicate that the password is not correct
### Actual behavior
No notification or error is displayed and the login page is displayed with gray mask.

Watch the next video:
https://www.useloom.com/share/8984301ce9c9495bb86c2669cd54d3d9

### Steps to reproduce the problem
* Go to login and try to login with:
User: admin
Password: 1

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-81a231
Build Number: 81a2314d301115b4f7147063a0e839ecb02508a5
Build Date/Time: 10-03-2018 09:24:59 -0600
#### OS
Mac OSx
#### Browser
Chrome

Note:
Notice that on the network console the api call to login returns 200ok and it should returns an error response code.
http://localhost:8080/studio/api/1/services/api/1/security/login.json

**Comment by vestrada** [comment]
Yes, As Luis has already commented, The API is returning 200 even if the user isn't logged in.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1305

**Comment by dejan-brkic** [comment]
New PR
https://github.com/craftercms/studio/pull/1307

**Comment by luishernandezmonge** [comment]
Verified as resolved
