### ISSUE TITLE
[studio-ui] User is not edited after click on Save (400 bad request on Network console) 

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2528]
### Expected behavior
The user should be edited without problems.

### Actual behavior
The user is not edited and a 400Bad Request error is returned on the web browser network console for the PATCH call

Watch the next video:
https://www.useloom.com/share/dab17f6de7dd495f86f3d09b36144327

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a new user
* Open the network console (of the web browser)
* Try to edit the user (change the email, last name, even the reset password fields)
*Review the network console (check the users patch request)

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/ed5f9e886faa034fa209a844ac412a95

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-81a231
Build Number: 81a2314d301115b4f7147063a0e839ecb02508a5
Build Date/Time: 10-03-2018 09:24:59 -0600
#### OS
Mac OSX
#### Browser
Chrome

**Comment by dejan-brkic** [comment]
This is UI issue. It is sending json which is not according to API spec
```
{"groups":[{"group":{"authority":null,"id":9,"name":null,"desc":null},"recordLastUpdated":"2018-10-03T20:46:21+02:00"}],"authorities":[{"authority":null,"id":9,"name":null,"desc":null}],"accountNonExpired":true,"accountNonLocked":true,"credentialsNonExpired":true,"id":9,"username":"craftercms2528","password":"craftercms2528","firstName":"craftercms2528","lastName":"craftercms2528 1","email":"brlestija@gmail.com","externallyManaged":false,"enabled":true}
```

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/943

**Comment by luishernandezmonge** [comment]
Verified as resolved.
