### ISSUE TITLE
CRAFTERCMS-891: Support GIT repo natively from inside engine

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#253]
Original JIRA Fix Versions:
2.6.0, Original JIRA Components:
Engine, 
----------
Original JIRA Description: Allow Engine to be configure with one or more SCM repositories which it can use to automatically check out code and content from

Each repository should be individually configured and should map to a tenant:
----------
Original JIRA Comments:
must talk to russ and sumer before starting.

----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-891
----------

**Comment by sumerjabri** [comment]
Not relevant at this time.
