### ISSUE TITLE
[studio] API1 login returns the incorrect Response code when try to execute the 401 Response code scenario

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2530]
### Expected behavior
API1 should returns 401 for the call, and not 500 RC

### Actual behavior
The api returns 500response code for the purposed scenario, and we expects 401 Bad Credentials

See the next image for the request and response:
<img width="1326" alt="screen shot 2018-10-03 at 11 42 42 am" src="https://user-images.githubusercontent.com/16946208/46428548-7b295080-c701-11e8-8d36-65e99c8a94f4.png">

### Steps to reproduce the problem
* Go to your rest client and execute the next POST request:
http://localhost:8080/studio/api/1/services/api/1/security/login.json with body
{
	"username":"adminnon",
	"password":"adminnon"
}
notice that the user does not exists

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-81a231
Build Number: 81a2314d301115b4f7147063a0e839ecb02508a5
Build Date/Time: 10-03-2018 09:24:59 -0600
#### OS
Mac OSx
#### Browser
Chrome

Note: look the api1 documentation for the expected code on that scenario:
https://docs.craftercms.org/en/3.1/developers/projects/studio/api/security/login.html

**Comment by sumerjabri** [comment]
@dejan-brkic shouldn't this return a deprecation/no longer valid response?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1303

**Comment by alhambrav** [comment]
Verified fixed.
