### ISSUE TITLE
[studio] API1 Start/Stop publisher call returns 401 even if user is logged and the site exists

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2531]
### Expected behavior
API1 calls should return 200ok response.

### Actual behavior
API1 calls returns 401 response even if user is logged and the site exists.

Watch the next video:
https://www.useloom.com/share/53b4e2e58fe5462dae14b43df6179c13

### Steps to reproduce the problem
*Create a new site and take note for the siteId
* In your rest client app, run the login api1 call to login as admin
* In your rest client app, run the next api call request for start publisher call:
http://localhost:8080/studio/api/1/services/api/1/publish/start.json
 with body: 
{
	"site_id":"test"
}
and header:
X-XSRF-TOKEN= 3f7af051-06a5-43ce-9881-dcce515bf45a

*Repeat the call scenario of above for the stop publisher call: 
http://localhost:8080/studio/api/1/services/api/1/publish/stop.json
same body and same headers

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-81a231
Build Number: 81a2314d301115b4f7147063a0e839ecb02508a5
Build Date/Time: 10-03-2018 09:24:59 -0600
#### OS
Mac OSX
#### Browser

**Comment by dejan-brkic** [comment]
@sumerjabri Is this valid use case. We are using a http session to maintain user logged in. Rest client does not necessarily need to keep track of http session as the browser does.

**Comment by luishernandezmonge** [comment]
@dejan-brkic @sumerjabri The rest client is already sending the JSESSIONID cookie set after logged in.
```
> POST /studio/api/1/services/api/1/publish/start.json HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/6.0.2
> Cookie: JSESSIONID=EE5AC5A77CC3A30E49D776EA7132AE2F; XSRF-TOKEN=3f7af051-06a5-43ce-9881-dcce515bf45a
> Content-Type: application/json
> X-XSRF-TOKEN:  3f7af051-06a5-43ce-9881-dcce515bf45a
> Accept: */*
> Content-Length: 21
| {
| 	"site_id":"test"
| }
* upload completely sent off: 21 out of 21 bytes
```
And it stills returning 401 RC.

Watch the next video:
https://www.useloom.com/share/43ae0e74322e48828b09b489be859aec

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1319

**Comment by luishernandezmonge** [comment]
Verified as Resolved
