### ISSUE TITLE
[core/engine] Read from remote repositories

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2535]
Enable, via configuration, Core to read from:
- HTTP end-points
- HTTPS end-points

This should result in Crafter Core and Crafter Engine being able to fully operate diskless. This should help us fit nicely in containers and eventually serverless.

We will start by supporting S3/CloudFront with clear or signed URLs.

**Comment by avasquez614** [comment]
@sumerjabri:  I think we need to discuss more this ticket. The main problem of supporting HTTP/HTTPS endpoints is that the protocol doesn't allow for directly listings, which Crafter Core/Engine requires. There also other problems with supporting S3 with pre-signed URLs, like that they are temporary and you need to generate one per item.

So right now I think the best approach is to support S3 connections through the SDK itself. You will just need the credentials and Engine would be able to read directly from S3 using Amazon protocols. It might be even faster than using pre-signed URLs.

Also it seems we need to add a processor in the Deployer to push to S3.

**Comment by sumerjabri** [comment]
Agreed on using the SDK to access S3.

Let's meet and make final decisions.
