### ISSUE TITLE
[studio-ui] studio/diff call returns 500 when user try to compare two versions of a content page (History versions comparison)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2540]
### Expected behavior
The comparison dialog should be displayed properly.

### Actual behavior
The comparison dialog is displayed with the next error:
HTTP Status 500 – Internal Server Error
Type Status Report
Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Watch the next video:
https://www.useloom.com/share/416cde37b70345ec81f030a6c94ce17a

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a site (using Website Editorial bp)
* Edit one of the content pages, e.g: Styles
* Click on Styles again and click on the **History** contextual nav option
* Check two versions displayed and click on Compare.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/99c5383df6f081e9937513ccc50ee161

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-b8f3d5
Build Number: b8f3d5c7f16dc637ab86d6d07fc5b6763eb3181d
Build Date/Time: 10-04-2018 14:33:24 -0600
#### OS
Mac OSx
#### Browser
Chrome

**Comment by avasquez614** [comment]
It seems the problem is with the nex Saxon dependency we introduced recently, it doesn't seem to like what the `scripts.libs.HTMLCompareTools` is doing:

```
Caused by: java.lang.NullPointerException
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:310)
	at org.outerj.daisy.diff.html.HtmlSaxDiffOutput.generateOutput(Unknown Source)
	at org.outerj.daisy.diff.html.HtmlSaxDiffOutput.generateOutput(Unknown Source)
	at org.outerj.daisy.diff.html.HTMLDiffer.diff(Unknown Source)
	at org.outerj.daisy.diff.output.Differ$diff.call(Unknown Source)
	at scripts.libs.HTMLCompareTools.diff(HTMLCompareTools.groovy:123)
	... 91 more
```

@jdrossl I need you help figuring out what's happening

**Comment by jdrossl** [comment]
@avasquez614 turns out saxon sets itself as default without any way to disable it, I found a couple of options to fix it but we need to talk about it tomorrow

**Comment by alhambrav** [comment]
Verified fixed.
