### ISSUE TITLE
[studio] Headers authentication does not work using modheaders

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2546]
### Expected behavior
Headers authentication should work using modheaders

### Actual behavior
Headers authentication does not work using modheaders

### Steps to reproduce the problem
* Setup studio for headers authentication by editing your `studio-config-override.yaml` file
* Setup modheaders in your chrome://extensions for the headers required
* Restart your Crafter CMS install
* In your browser, go to Studio `localhost:8080/studio` notice that instead of redirecting you inside of Studio, it brings you to the Studio login dialog

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-3ca04f
Build Number: 3ca04f5e14a1e45919db2c3889ac1ea5eab9a60e
Build Date/Time: 10-08-2018 10:26:34 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1314

**Comment by alhambrav** [comment]
Verified fixed.
