### ISSUE TITLE
[studio] GET /studio/api/2/users/{id}/sites returns 404 when using user ID values for {id}

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2547]
### Expected behavior
GET /studio/api/2/users/{id}/sites should work when using user ID (integer) values for {id}

### Actual behavior
GET /studio/api/2/users/{id}/sites returns 404 when using user ID (integer) values for {id}

### Steps to reproduce the problem
* Login to Studio
* Using a rest client, or a browser, send a GET http://localhost:8080/studio/api/2/users/1/sites  (use the user ID number)
Notice the API returns 404
![screen shot 2018-10-08 at 4 09 11 pm](https://user-images.githubusercontent.com/25483966/46631140-8c64c980-cb14-11e8-8c73-7a136e658d72.png)

Now send a GET http://localhost:8080/studio/api/2/users/admin/sites  (using the username this time).  Notice that the API works
![screen shot 2018-10-08 at 4 11 11 pm](https://user-images.githubusercontent.com/25483966/46631212-cc2bb100-cb14-11e8-8813-bef97cf64614.png)

### Log/stack trace (use https://gist.github.com)
Here's the error log:
https://gist.github.com/alhambrav/a4394ab860f778b7fb20bacd7a3c0ece

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-3ccd17
Build Number: 3ccd17ecec8b7aac836ecfcbea6425155a235be5
Build Date/Time: 10-08-2018 15:47:03 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Cannot reproduce with
```
Studio Version Number: 3.1.0-SNAPSHOT-a26f94

Build Number: a26f9410f697f1b1397b2a2a2b1452a148a5a4af

Build Date/Time: 10-10-2018 19:20:59 +0200
```

**Comment by alhambrav** [comment]
Verified cannot reproduce in version:
```
Studio Version Number: 3.1.0-SNAPSHOT-a26f94
Build Number: a26f9410f697f1b1397b2a2a2b1452a148a5a4af
Build Date/Time: 10-10-2018 10:15:49 -0400
```
