### ISSUE TITLE
[studio] There's no log when a database user enters an invalid username/password

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2548]
### Expected behavior
Please log failed logins both in the logs and audit table.  Also, authentication chain failures should be logged in DEBUG

### Actual behavior
There's no log when a database user enters an invalid username/password 

### Steps to reproduce the problem
* Start Studio (in my setup, I have headers, ldap and db authentication enabled)
* Login as user:`admin` and enter an incorrect password.  Notice that Studio displays `Invalid username or password`
![screen shot 2018-10-08 at 4 20 19 pm](https://user-images.githubusercontent.com/25483966/46631806-7bb55300-cb16-11e8-8793-fca69879381d.png)

Look in the logs, and there's no entry about the invalid username or password:
```
[WARN] 2018-10-08 16:20:13,911 [http-nio-8080-exec-2] [access.StudioAuthenticationTokenProcessingFilter] | Unable to authenticate user (null) using authentication headers.
[INFO] 2018-10-08 16:20:13,928 [http-nio-8080-exec-2] [core.LdapTemplate] | No results found for search, base: ''; filter: '(uid=admin)'.
[INFO] 2018-10-08 16:20:13,928 [http-nio-8080-exec-2] [security.LdapAuthenticationProvider] | User admin not found with external security provider.
```

Please log failed logins both in the logs and audit table.  Also, authentication chain failures should be logged in DEBUG
 
#### Version
Studio Version Number: 3.1.0-SNAPSHOT-3ccd17
Build Number: 3ccd17ecec8b7aac836ecfcbea6425155a235be5
Build Date/Time: 10-08-2018 15:47:03 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment]
3.0 <== log in audit and in regular logs
3.1 <== change auth chain to `debug`, login in audit and log in regular logs

**Comment by dejan-brkic** [comment]
3.1.0:
PR:
https://github.com/craftercms/studio/pull/1324

**Comment by dejan-brkic** [comment]
3.0.x
PR:
https://github.com/craftercms/studio/pull/1326

**Comment by alhambrav** [comment]
Verified fixed.
