### ISSUE TITLE
[docs] Provide an example of how to upload assets to S3 from Studio and access them in Engine 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2550]
Provide an example of how to use the S3 upload control to do the following:

- Upload assets like images and documents to an S3 bucket.
- Make those assets available in the site (make Engine generate public URLs that will allow access to them).

**Comment by avasquez614** [comment]
@alhambrav doc for 3.0 is done, we should wait for 3.1 S3 changes to add the 3.1 doc

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/676

**Comment by avasquez614** [comment]
Verified
