### ISSUE TITLE
[docs] Provide an example of how to upload documents to Box from Studio and access them in Engine

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2551]
Provide an example of how to use the Box upload control to do the following:

- Upload assets documents to Box.
- Make those documents available for download from the site (make Engine generate public URLs that will allow access to them).

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/697

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/699

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/831

**Comment by avasquez614** [comment]
Verified
