### ISSUE TITLE
[docs] Provide an example of how to upload/transcode videos to AWS from Studio and access them in Engine

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2552]
Provide an example of how to use the AWS video upload control to do the following:

- Upload and transcode a video to AWS
- Make those videos available in the site (make Engine generate public URLs that will allow access to them).

**Comment by alhambrav** [comment]
Will wait for ticket https://github.com/craftercms/craftercms/issues/2959

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/800

**Comment by avasquez614** [comment]
Verified
