### ISSUE TITLE
[studio] Audit log for create site logs the OS user instead of the Studio user who created the site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2553]
### Expected behavior
Audit log for create site should log the Studio user as the user who created the site instead of the OS user 

### Actual behavior
Audit log for create site logs the OS user instead of the Studio user who created the site

### Steps to reproduce the problem
* Log in as user `admin` 
* Create a site
* Log in to the db and look at the audit logs, notice the entries for all the files created when create site was performed by user `admin`

### Log/stack trace (use https://gist.github.com)
```
| 1428 | 2018-10-09 09:50:06 | 2018-10-09 09:50:06 | {"user":"Vita","id":"/templates/web/components/articles-widget.ftl"}                                                            | json           | /templates/web/components/articles-widget.ftl                                        | site1        | CREATED       | page         | vita | REPOSITORY |
| 1429 | 2018-10-09 09:50:06 | 2018-10-09 09:50:06 | {"user":"Vita","id":"/templates/web/components/contact-widget.ftl"}                                                             | json           | /templates/web/components/contact-widget.ftl                                         | site1        | CREATED       | page         | vita | REPOSITORY |
```
#### Version
Studio Version Number: 3.1.0-SNAPSHOT-3ccd17
Build Number: 3ccd17ecec8b7aac836ecfcbea6425155a235be5
Build Date/Time: 10-09-2018 09:28:08 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1321

**Comment by alhambrav** [comment]
Verified fixed.
