### ISSUE TITLE
[deployer] GitPullProcessor doesn't use the remote URL on pull

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2557]
The `GitPullProcessor` only uses the `remoteRepo.url` on clone. For pulling, it always uses the default remote, `origin.` Make the processor always pull from `remoteRepo.url`, since there are use cases where you need to pull from a different remote than `origin`.

**Comment by jdrossl** [comment]
@avasquez614 jgit only supports providing a remote name to execute the pull, we could update the configuration to add a new remote and update the value before doing the pull to make sure the url will always match the target's url. Let me know what you think about this solution.

**Comment by avasquez614** [comment]
@russdanner Deployer now will add a remote for `remoteRepo.url`. If you specify `remoteRepo.name` then the remote will have that name. If not, the URL of `origin` will be changed to be the `remoteRepo.url`.

**Comment by russdanner** [comment]
Confirmed
