### ISSUE TITLE
[craftercms] Error when starting the authoring and delivery applications (Java 11)

### ISSUE THREAD

**Issue by armandojaga** [craftercms/craftercms#2559]
Java 11 removed some of the dependencies that crafter relies on. (javax.xml.bind [JAXB], see http://openjdk.java.net/jeps/320)

### Expected behavior
The applications starts without any issues

### Actual behavior
An error is thrown at startup

### Steps to reproduce the problem
* Install java 11 (http://openjdk.java.net/projects/jdk/11/), make sure it's the default version (run `java -version`
* Download and uncompress Crafter Authoring (https://downloads.craftercms.org/3.0.17/crafter-cms-authoring.zip)
* run the startup script `startup.bat`

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/armandojaga/3aa5f120f6202a7d592f69621cd0f8e9

#### OS
Windows 10 Professional 

#### Browser
-

**Comment by avasquez614** [comment]
Hi Armando,

We right now just support Java 8, as stated in our doc: https://docs.craftercms.org/en/3.1/system-administrators/index.html. We'll provide support for Java 9 and higher on later versions, it's on our roadmap.

**Comment by armandojaga** [comment]
Thanks for the reply Alfonso, 

may I suggest updating that documentation then, it says that Java versions supported are 1.8+.

Regards

**Comment by avasquez614** [comment]
Hi Armando,

There's actually a note that says the following:

```Note
Crafter CMS is not yet compatible with Java 1.9. We are working on updating our code to make sure we are 100% compatible with the newest Java version.```

**Comment by armandojaga** [comment]
Thanks for the clarification

**Comment by kenneth-bolivar-castro** [comment]
@avasquez614 is there any ETA?  Or some kind of roadmap to be aware what's status?
cc: @armandojaga

**Comment by sumerjabri** [comment]
@kenneth-bolivar-castro Our roadmap is here: https://docs.craftercms.org/en/3.1/roadmap/index.html

We don't get into that level of detail in the roadmap, but you can track what's in releases via GitHub tickets, here: https://github.com/craftercms/craftercms/issues

To track this particular issue, we created the ticket: https://github.com/craftercms/craftercms/issues/2565

For an ETA, expect this to be completed in the first half of 2019.
