### ISSUE TITLE
[studio-ui] add a data source for uploading video from desktop to webDAV

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2568]
### Expected behavior
Add a data source for uploading video from desktop to webDAV

User experience should be the same as other desktop upload data sources.
Reminder: Include macro processing on path.

**Comment by vestrada** [comment]
3.1 - >PR: https://github.com/craftercms/studio-ui/pull/957

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/958

**Comment by vestrada** [comment]
studio -> PR: https://github.com/craftercms/studio/pull/1335

**Comment by russdanner** [comment]
Confirmed
