### ISSUE TITLE
[studio-ui] add data source for uploading image from desktop to webDAV 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2569]
### Expected behavior
Add a data source for uploading image from desktop to webDAV

User experience should be the same as other desktop upload data sources.
Reminder: Include macro processing on path.

**Comment by vestrada** [comment]
3.1 -> PR: https://github.com/craftercms/studio-ui/pull/955

**Comment by vestrada** [comment]
3.0 -> PR:  https://github.com/craftercms/studio-ui/pull/956

**Comment by vestrada** [comment]
studio -> PR: https://github.com/craftercms/studio/pull/1335

**Comment by russdanner** [comment]
Confirmed
