### ISSUE TITLE
Clear publishing submission comment from previous publishing request

### ISSUE THREAD

**Issue by nrdufour** [craftercms/craftercms#257]
An author would like to see the publishing submission comment textfield being cleared from previous publishing requests.
At the moment it's being populated by the last one.

You could avoid the auto-completion of the form with autocomplete="off", or using some javascript.

**Comment by russdanner** [comment]
CopyField is present

**Comment by russdanner** [comment]
Seen on customer project.  Carlos can show you. 

Looks like a back end issue to me, possibly related to Copy/Pasted/Duplicated items.

**Comment by dejan-brkic** [comment]
This looks like duplicate issue.
#268
Already fixed.

**Comment by cortiz** [comment]
@russdanner Looks like adding  autocomplete="off" in the selection box its a good idea, I do agree with @dejan-brkic Main issue is solve #268
