### ISSUE TITLE
[studio] Add permissioning to S3 services

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2570]
The new API 2 S3 services need permission checking, in specific:

* The list API needs to check for the `Read from S3` site permission.
* The upload API needs to check for the `Write to S3` site permission.

Permission checking should be performed by using the `@HasPermission` annotation.  These permissions need to be defined in the permission mappings of each site, so blueprints have to be updated and existing sites need to be upgraded to have these permissions.

**Comment by avasquez614** [comment]
Please verify

**Comment by jdrossl** [comment]
It looks like this condition is always false https://github.com/avasquez614/studio/blob/05bb7b1f907e376f7f0438a1aa9c514eb847267b/src/main/java/org/craftercms/studio/permissions/PermissionResolverImpl.java#L61

**Comment by avasquez614** [comment]
Verified
