### ISSUE TITLE
[studio] browse webdav-video-browse-data and  webdav-image-browse-datasource should process macro paths

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2571]
### Expected behavior
browse webdav-video-browse-data and  webdav-image-browse-datasource should process macro paths. See section on macros for data source https://docs.craftercms.org/en/3.0/developers/content-modeling.html  

User should be able to use paths that include macros as part of the data source configuration 

### Actual behavior
Macros are not expanded by data source

### Steps to reproduce the problem
* configure webdav datasource with macros in path 
* Use the form, note macros are not expanded
<img width="802" alt="screen shot 2018-10-11 at 5 28 48 pm" src="https://user-images.githubusercontent.com/169432/46888982-1f14a980-ce30-11e8-9f2b-e14686dae834.png">

#### Version
Studio Version Number: 3.0.18-SNAPSHOT-c8e62a
Build Number: c8e62a59720fe0fbe8ac5809d6fc690d3b05ee83
Build Date/Time: 10-12-2018 09:44:26 -0400

#### OS
Any

#### Browser
All

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/959
3.0.x: https://github.com/craftercms/studio-ui/pull/960

**Comment by russdanner** [comment]
Confirmed
