### ISSUE TITLE
[studio-ui] Rename WebDav datasources to be consistent with other datasources

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2576]
Rename the WebDav datasource labels to have the following names (to maintain consistency with previous datasources):

* Image From WebDav Repository
* Image Uploaded to WebDav Repository
* Video From WebDav Repository
* Video Uploaded to WebDav Repository
* File From WebDav Repository
* File Uploaded to WebDav Repository

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/961

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/962

**Comment by avasquez614** [comment]
Verified
