### ISSUE TITLE
[studio] Allow for external MariaDB configuration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2579]
Allow, via configuration, for Studio to connect to a remove MariaDB (single or cluster). This is the first step in implementing Studio 3 clustering.

Configuration is stored in studio-config-override.yaml and is commented out by default. We will continue to boot using the embedded MariaDB by default.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1346
