### ISSUE TITLE
The Dropdown form control fails to load the existing value

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#258]
Dropdown is configured with the following options:

![screen shot 2016-11-04 at 12 02 12 pm](https://cloud.githubusercontent.com/assets/4325885/20012848/49e5ab90-a287-11e6-99f0-8bbc0b93f4de.png)

but when the form opens it's not loading the existing value

![screen shot 2016-11-04 at 12 01 39 pm](https://cloud.githubusercontent.com/assets/4325885/20012870/6ae50430-a287-11e6-8345-1bb99630ca41.png)

and displays as a required value is missing.

**Comment by asotog** [comment]
will take care of this one

**Comment by hlim** [comment]
the fix confirmed
