### ISSUE TITLE
[studio-ui] Studio logo image is broken on site configuration  

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2582]
### Expected behavior
Studio logo image shouldn't be broken.

### Actual behavior
Studio logo image is broken on site configuration  

![image](https://user-images.githubusercontent.com/11640613/47161381-26fc9f80-d2af-11e8-8b92-ca4df380c9a4.png)

### Steps to reproduce the problem
* Create a new site using a BP
* Go to Site configuration page
* See the broken logo at the top of the page

#### OS
Mac

#### Browser
chrome

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/964

**Comment by russdanner** [comment]
Confirmed
