### ISSUE TITLE
[studio-ui] Typo in "Service" field for AWS Video Upload control

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2584]
### Expected behavior
"Service" field for AWS Video Upload control should list the second option as "MediaConvert"

### Actual behavior
There's a Typo in "Service" field for AWS Video Upload control, it lists the second option as "MediaConver" instead of "MediaConvert"

<img width="350" alt="screen shot 2018-10-19 at 11 45 11 am" src="https://user-images.githubusercontent.com/25483966/47229076-d2cbeb00-d394-11e8-8042-8aca13e38982.png">

### Steps to reproduce the problem
* Create a site in Studio using website_editorial bp
* Add in the control for AWS Video Upload, by going to **Site Config** -> **Configuration** -> **Site Config Tools** and add the following:
```
<control>
    <name>aws-video-upload</name>
    <icon>
        <class>fa-film</class>
        <stackedclass>fa-amazon</stackedclass>
    </icon>
</control>
```
Save your changes.
* Open a content type, say the **Page - Article**
* Add in the AWS Video Upload control to the **Content** section of the form
* Click on the newly added control in the form and notice the Properties Explorer panel, under **Properties**, in the **Services** field, click on the dropdown, **MediaConver** is listed instead of **MediaConvert**

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-406a18
Build Number: 406a1804432167a1f2cd466f7e70304da964f53d
Build Date/Time: 10-19-2018 11:02:58 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/968

**Comment by alhambrav** [comment]
Verified fixed.
