### ISSUE TITLE
[studio] remove environment-configuration file 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2586]
### Expected behavior
Move useful properties found in a sites `/config/studio/environment/environment-config` in to `/config/studio/site-config`

**Comment by russdanner** [comment]
Please leave this with me for not.  The ticket needs to be expanded to include details about what properties to keep.

**Comment by russdanner** [comment]
Once ticket: https://github.com/craftercms/craftercms/issues/2587
 is fully functional we can move all of the following properties from `/config/studio/environment/environment-config.xml` to `/config/studio/site-config.xml`

```   <preview-server-url>http://localhost:8080</preview-server-url>
   <preview-engine-server-url>http://localhost:8080</preview-engine-server-url>
   <graphql-server-url>http://localhost:8080</graphql-server-url>
   <authoring-server-url>http://localhost:8080/studio</authoring-server-url>
   <live-server-url>http://localhost:9080/?crafterSite={siteName}</live-server-url>
   <open-sidebar>false</open-sidebar>
   <publishing-targets>
      <target>
         <repo-branch-name>live</repo-branch-name>
         <display-label>Live</display-label>
      </target>
   </publishing-targets>```

**Comment by russdanner** [comment]
Front end is doing it's job but back end does not save to the proper location
https://www.loom.com/share/04c29af12604476dadfa4556427d11b5

**Comment by dejan-brkic** [comment]
Can not reproduce.

```
Studio Version Number: 3.1.2-SNAPSHOT-0971d7

Build Number: 0971d726eb1b1e1041091f23202b0d90324ef7f2
```

If configured environment does not exist it will save configuration to default location.

**Comment by russdanner** [comment]
Closing this ticket as it is no longer relevant / has been superseded by other tickets
