### ISSUE TITLE
[studio] Support active-environment/multi-environment configuration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2587]
In support of multi-env, the admin can create a set of configuration files that are the exact same as the default without the content type definitions. These are created under the folder structure:

`/config/studio/env/{ENV}`

`{ENV}` == the environment name.

Add a new property in studio-config-override.yaml will carry this environment name:
`environment: {ENV}`

This is commented out by default.

The admin will create the folder, copy all config there, override the configs they want per env, and set the property.

Implement the API spec'd here: https://github.com/craftercms/craftercms/issues/2585 which returns this value to the UI.

Override the LoadConfig API call such that it looks for this ENV, if specified, it injects the string `/env/{ENV}` into the path of the config, thereby overriding the config location to match the env.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1396

**Comment by sumerjabri** [comment]
@alhambrav please validate and document this new feature. @russdanner has most of the context, but I have some too and happy to sync up when you're ready.

**Comment by russdanner** [comment]
Functionality does not appear to be active
https://www.loom.com/share/b719c8b0f45d459eb740ab599cf28fa7

**Comment by dejan-brkic** [comment]
Done
PRs:
https://github.com/craftercms/studio/pull/1614
https://github.com/craftercms/studio-ui/pull/1187
https://github.com/craftercms/video-center-blueprint/pull/38

**Comment by rart** [comment]
This fix seems to caused issues when the env configuration is tweaked. Specifically with `127.0.0.1`, there are some behavioural differences that break preview.

On `overlayhook.ftl` the `authoringServer` value behaves inconsistently with different values (default vs customised - in this instance with loopback)

<img width="1920" alt="Screen Shot 2019-07-18 at 4 17 50 PM" src="https://user-images.githubusercontent.com/3928341/61469200-1765d080-a97f-11e9-996e-9b2b623023a1.png">

@dejan-brkic

**Comment by dejan-brkic** [comment]
Done
PR:
BE https://github.com/craftercms/studio/pull/1675
UI https://github.com/craftercms/studio-ui/pull/1243

**Comment by rart** [comment]
After updating and testing, the `hostOrigin` param value on `overlayhook.ftl` is still set to a resulting value equals to `authoringServer + / + studioContext`. The hostOrigin should not contain the studioContext for guest to work correctly.

**Comment by rart** [comment]
Pushed the fix on #1248.

**Comment by russdanner** [comment]
Config file is not written to the proper location for set environment
https://www.loom.com/share/c89afc5a81f64f91b94af82938403de6

Test performed in version:
```
Studio Version Number: 3.1.1-SNAPSHOT-917471
Build Number: 917471786ee424e680bb2ff7fcdae81104112fd6
Build Date/Time: 08-05-2019 10:00:42 -0400
```

**Comment by russdanner** [comment]
Correction.
This ticket is CONFIRMED.
You must have the other environment files and folders added and committed. Studio will use them if they are there.  IF NOT, default location is used. All of this is CONFIRMED.
