### ISSUE TITLE
[studio-ui] Add the name of the environment to the Configuration section of Site Config

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2588]
See the API spec'd out: https://github.com/craftercms/craftercms/issues/2585

See the ticket: https://github.com/craftercms/craftercms/issues/2586 for context

We need to add the env (if not null) on the configuration editing tool in Site Config such that the user can know what env they're modifying.

Ping me for more detail as needed.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/978

**Comment by sumerjabri** [comment]
BE should be done now. I'm not seeing the ENV.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1183

**Comment by vestrada** [comment]
@dejan API is always responding: `environment: null`.

**Comment by dejan-brkic** [comment]
It works fine. Returns null only if an active environment is not set in `studio-config-override.yaml`

**Comment by sumerjabri** [comment]
@vestrada if `null`, it means the system doesn't have an env override, so you hide the tool. Can you do that?

Also, do you know how to test with env overrides? Edit `studio-config-override.yaml`:
```
# The active environment for multi environment configuration, e.g. qa, prod, dev
studio.configuration.environment.active: dev
```

**Comment by vestrada** [comment]
@sumer, Above change was already done.

<img width="346" alt="Screen Shot 2019-06-19 at 2 39 17 PM" src="https://user-images.githubusercontent.com/11640613/59798784-34d04d80-92a0-11e9-92eb-177f03a0ddf7.png">

I just tested it, and it is working.

**Comment by sumerjabri** [comment]
@russdanner please validate.

**Comment by russdanner** [comment]
The environment shows. This ticket is complete.  
That said, setting the environment seems to have NO EFFECT on how the configuration files are written/read.

https://www.loom.com/share/04c29af12604476dadfa4556427d11b5

Confirmed

**Comment by russdanner** [comment]
Re-opening this ticket.
Saving config does not read or save properly because UI does not pass the active environment to the API.  See example POST BODY on write API. Note that although UI shows DEV as requested by ticket it leaves this environment variable null and as a result the backend updates the default configuration rather than the dev configuration.

```
{"siteId":"editorial","module":"studio","path":"environment/environment-config.xml","environment":"","content": "XML CONTENT HERE"}
```

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1250

**Comment by russdanner** [comment]
Confirmed.
POST sends environment. File is not written on Backend.
