### ISSUE TITLE
[studio-ui] Leaving content type page without saving does not prompt user to save changes

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2590]
### Expected behavior
Users should be prompted when leaving a page that has changes

### Actual behavior
Leaving content type page without saving does not prompt user to save changes

### Steps to reproduce the problem
* Create a site using website_editorial 
* Go to **Site Config** -> **Content Type**
* Open an existing content type, say **Page - Article**
* Edit the form by adding a control
* From the Sidebar, click on **Configuration**, or any of the other items in the sidebar, you can also try clicking on **New Content Type**.  Notice that when you left the content type page, there was no prompt to save changes

This is also present in 3.0

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/aa8b91e2c6f54d27ab0652df1a4ea806

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-406a18
Build Number: 406a1804432167a1f2cd466f7e70304da964f53d
Build Date/Time: 10-19-2018 11:02:58 -0400
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/969

**Comment by alhambrav** [comment]
Verified fixed.
