### ISSUE TITLE
[studio-ui] Create a Main Menu Clustering tool

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2594]
Create a new tool in the main menu called `Clustering`

The tool will list the cluster members when it loads, and allow the user to delete cluster members. This is similar to the tool that lists remote repos.

The API we will use is under `/cluster` and described in detail here:
https://app.swaggerhub.com/apis/craftercms/studio

This ticket depends on https://github.com/craftercms/craftercms/issues/2593

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/979

**Comment by sumerjabri** [comment]
Depends on https://github.com/craftercms/craftercms/issues/2608

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/1368

**Comment by sumerjabri** [comment]
@vestrada please note:

- The API changed to remove `create` and `update` (POST and PATCH) cluster members. Cluster members can only be listed or deleted now. The reason being that Studio can now add itself to a cluster, and the configuration is managed in Studio's YAML config. Also, it can be removed automatically, but we'll allow admins to remove nodes should they want to (they'll rejoin if they're still active).
- Based on the above, please remove the ability to create and update a cluster member, keep only delete.
- Please note the changes to the fields, we now have a new field called `localIP` which we must show. Gone is the node name/etc. It's now just the local IP.
- Please note that we only want to show the columns:
  - ID
  - Local IP
  - State
  - Git URL
  - Git Remote Name
  - Git Auth Type

Please ping me if you have any questions.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/999

**Comment by vestrada** [comment]
Hi Dejan per our conversation I can't check this ticket. Please verify it and let me know. 

Thanks, Vero

**Comment by sumerjabri** [comment]
@vestrada Please do the following:
- Remove the ID column
- Remove the dialog that shows up if you click the ID (that whole dialog needs to be deleted from the code)
