### ISSUE TITLE
[studio-ui] Box File Upload control property "Enable Upload" does not seem to be working

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2596]
### Expected behavior
The `Upload` option should not be available in the box widget when you have the `Enable Upload` property of the box file upload control unchecked

### Actual behavior
Box File Upload control property "Enable Upload" does not seem to be working.  When you look at the form, there is no difference whether you have the `Enable Upload` property checked or unchecked.  In both cases, the `Upload` option is available from the box widget

### Steps to reproduce the problem
* Create a site using website editorial
* Add in the box file upload control to your `Site Config Tools` configuration file by opening your Sidebar, then click on `Site Config` -> `Configuration` -> `Site Config Tools`
```
                <control>
                    <name>box-file-upload</name>
                    <icon>
                        <class>fa-square-o</class>
                        <stackedclass>fa-upload</stackedclass>
                    </icon>
                </control>
```
* Fill out the `Box Profiles` configuration file, by opening the dropdown box at the top and then selecting `Box Profiles`
* Open the content type `Page- Article` and add to the form the new control we added.
* Click on the new control in the form and in the Properties Explorer, make sure the property `Enable Upload` is unchecked.  Save your changes.

<img width="1165" alt="screen shot 2018-10-25 at 5 08 44 am" src="https://user-images.githubusercontent.com/25483966/47490982-cf62b480-d817-11e8-96ac-aec8867200c9.png">

* Edit one of the articles by clicking on the site name at the top or the Crafter logo, then Open the Sidebar, navigate to one of the articles, right click on the article and click on `Edit`. 
* Scroll down to the area in the form where we added the box control.  Click on the `+` in the box widget, notice `Upload` is available
<img width="827" alt="screen shot 2018-10-25 at 5 09 44 am" src="https://user-images.githubusercontent.com/25483966/47491285-8d863e00-d818-11e8-905c-4877c30f753d.png">

* Now, let's check the checkbox for the `Enable Upload` property of the box file upload control by opening the `Page - Article` content type, click on the box control in the form, then in the `Properties Explorer`, scroll to the `Enable Upload` property and check the checkbox.
* Once again, edit an article
* Scroll down to the area in the form where we added the box control.  Click on the `+` in the box widget, notice `Upload` is available. (I can't tell the difference when you have the `Enable Upload` property checked or unchecked`)

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-d183f9
Build Number: d183f9223a89d2579492de9bb5119020f5e94d3f
Build Date/Time: 10-24-2018 04:22:45 -0400
```
also:
```
Studio Version Number: 3.0.18-SNAPSHOT-c83d09
Build Number: c83d093236093940482d6fc2b3c719e46344278a
Build Date/Time: 10-25-2018 11:11:59 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/972

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by ajeet0805** [comment]
I have implemented the same but not woking

**Comment by sumerjabri** [comment]
@ajeet0805 join us on Slack and share your Tomcat logs and configuration/use-case so we can try to help. Slack is here: https://tinyurl.com/5ykw6a2w
