### ISSUE TITLE
[studio-ui] webdav desktop dialog is too short and cuts off buttons

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2597]
### Expected behavior
The dialog box for WebDAV upload should be big enough in all screen break points to display all buttons and other UI elements
!

### Actual behavior
The dialog box for WebDAV upload is too short and cuts off buttons due to style sheet issues
[screenshot](https://user-images.githubusercontent.com/169432/47526777-ccdf7980-d86e-11e8-8de8-46bc44b63844.png)

### Steps to reproduce the problem
1. Setup WebDAV profile. 
2. Modify content type for img-WebDAV-repo with image-picker selecting from it. 
3. Edit an entry with image-picker 
4. Add image 
5. Browse on the existing folder (an assumption that there's existing content) 
6. Right-click a folder 
7. Click on "Upload" to see modal with incorrect display
8. See dialog box in all breakpoints

### Log/stack trace (use https://gist.github.com)
N/A

#### OS
Any

#### Browser
Any

**Comment by jvega190** [comment]
3.1: https://github.com/craftercms/studio-ui/pull/973
3.0.x: https://github.com/craftercms/studio-ui/pull/974

**Comment by russdanner** [comment]
Confirmed
