### ISSUE TITLE
User's session doesn't refresh after being inactive for long time

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#260]
User was inactive for a while after logging in and returning back to studio was generating the following error in the log

[INFO] 2016-10-17 13:28:35,398 [http-bio-7070-exec-8] [auth.AuthChallengeProcessor] | basic authentication scheme selected
[INFO] 2016-10-17 13:28:35,398 [http-bio-7070-exec-8] [httpclient.HttpMethodDirector] | No credentials available for BASIC 'Alfresco'@localhost:8080

and studio was not loading (too many redirects error in the browser) until the user was logged into Alfresco again. Restarting studio instance itself didn't resolve the problem.

Alfresco is configured to time out after 1 hr.

**Comment by russdanner** [comment]
Fixed

**Comment by hlim** [comment]
Confirmed the fix.
