### ISSUE TITLE
[studio-ui] Update get-user-roles API1 to roles API2 spec

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2603]
Preview section in studio is using: http://localhost:8080/studio/api/1/services/api/1/security/get-user-roles.json. Please update it with roles api2 spec. 
https://app.swaggerhub.com/apis/craftercms/studio/

**Comment by vestrada** [comment]
Hi Alfonso,

Per our conversation:
- When the user logged is admin, Roles API2 (/studio/api/2/users/me/sites/{site}/roles) is responding different than Roles API1 (/studio/api/1/services/api/1/security/get-user-roles). Please see the following example:

**Roles API2**: {"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"**roles**":[]}

**Roles API1**: {"**roles**":["author","admin","publisher","developer","reviewer"]}

- Sidebar configuration is using: admin role

![image](https://user-images.githubusercontent.com/11640613/47806218-cf265580-dcfe-11e8-9707-935e1385e88d.png)

- Remember what we talked about reviewers.

**Comment by avasquez614** [comment]
@vestrada the API 2 is now returning all roles for sysadmin

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/977

**Comment by vestrada** [comment]
Verified.
