### ISSUE TITLE
[studio-ui] warn user when deleting a dependency is in use

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2604]
### Expected behavior
The system should warn the user if they try to delete a dependency that is used in one or more locations.

- The dialog should contain a list of items that have other objects that refer to them.  
- If the dialog contains a single object it should be automatically expanded to show all of the items that refer to it.  
- If the dialog contains multiple objects, the lists should be collapsed and authors can expand them to see what items are referred to.  
- Authors should be able to click edit next to each item (in order to easily modify the dependency)

<img width="529" alt="screen shot 2018-10-31 at 12 48 35 pm" src="https://user-images.githubusercontent.com/169432/47805246-3a772400-dd0d-11e8-8f7e-ffc191e441b3.png">

Continue removes the user to the delete confirmation
Cancel cancels the delete
After each edit, the list should be updated to show the latest dep calc

### Actual behavior
Today users can delete dependencies and no warning is given.  This can lead to broken experiences

### Steps to reproduce the problem
* Create a page 
* Upload an image to the page and save
* Publish the page and the image
* Delete the image

**Comment by sumerjabri** [comment]
Check the dep API for all items selected to make sure nothing depends on them.

**Comment by rart** [comment]
@sumerjabri @russdanner The new dialog, which uses API2, shows "dependant items". Isn't that what this ticket is about? Is there anything additional to do?

<img width="970" alt="image" src="https://user-images.githubusercontent.com/3928341/94662515-c84c5700-0308-11eb-9dc5-54f0ccae3e31.png">

@jvega190 I see two calls to `/studio/api/2/content/get_delete_package` going out as the delete dialog opens. Please check the reason for the first call, which seems to have no paths sent — looks suspicious.

**Comment by russdanner** [comment]
Confirmes
