### ISSUE TITLE
[docs] Document authentication chaining

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2605]
We already have detailed docs for configuring individual authentication mechanisms, but it seems that we lack one document that wraps those up and explains chaining, see here: https://github.com/craftercms/craftercms/issues/2529

Should be a short document, perhaps a nice diag with it, that shows how the chaining works and links to the detailed config mechanics per mechanism.

Ping me if you need any more detail.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/636
