### ISSUE TITLE
[docs] Document clustering

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2607]
Document how to create and manage a Studio cluster.

Step 1: This is relevant: https://github.com/craftercms/craftercms/issues/2579 <= this is the first step as we must have a MariaDB cluster which is either done via AWS RDS or some other solution, we should provide links.

Step 2: Use the UI to cluster Studio. Should include screenies.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/702
