### ISSUE TITLE
[studio] Update clustering to the latest API2 spec

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2608]
Please update clustering api, see the spec: 
https://app.swaggerhub.com/apis/craftercms/studio/

**Comment by dejan-brkic** [comment]
```Studio Version Number: 3.1.0-SNAPSHOT-a5380e

Build Number: a5380eb6be7823e03e6b5986f32a76c5c40e726b```

works fine

**Comment by vestrada** [comment]
Hi Dejan,

The apis are not follow the error handler of the spec. I'm not getting the correct structure in the response.
https://app.swaggerhub.com/apis/craftercms/studio/

![image](https://user-images.githubusercontent.com/11640613/47930323-3c69f000-de91-11e8-88e1-93447e5737ee.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1356

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/1368

**Comment by sumerjabri** [comment]
@dejan-brkic per our conversation and the new spec: https://app.swaggerhub.com/apis/craftercms/studio

Please remove create/update APIs since Studio will now self-provision/add itself to a cluster and updating Studio happens via config to the node being added to the cluster.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1374

**Comment by vestrada** [comment]
I'm going to close this ticket because the api specifications change. 
And I'm not able to create clusters yet.
