### ISSUE TITLE
[blueprints] improve preset documentation for aws

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2609]
### Expected behavior

Documentation in the example XML ({REPOSITORY_ROOT}/sites/SITENAME/config/studio/aws/aws.xml) and on the doc site (https://docs.craftercms.org/en/3.0/site-administrators/studio/aws-profiles-configuration.html) should mention that the preset IDs are supplied by AWS.

**Comment by alhambrav** [comment]
For 3.0:
PR https://github.com/craftercms/docs/pull/634
PR https://github.com/craftercms/studio/pull/1357

For 3.1
PR https://github.com/craftercms/docs/pull/635
PR https://github.com/craftercms/studio/pull/1359

**Comment by russdanner** [comment]
Confirmed
