### ISSUE TITLE
Opening and closing site dropdown generates a js error in console

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#261]
1) Open the browser's inspector
2) Go to a site dashboard
3) Open the site dropdown
----------------------------------------------------------------------------------------
wcm-root-folder.js?version=1fbbe9d…:152 Uncaught TypeError: thisComponent.blur is not a function(…)(anonymous function) @ wcm-root-folder.js?version=1fbbe9d…:152P @ utilities.js?version=1fbbe9d…:11

**Comment by asotog** [comment]
checking why this is calling an undefined function

**Comment by asotog** [comment]
`this` (inside event listener) is not the same as thisComponent, seems bug introduced, some time seems was working fine with `this` pointing to the DOM element

**Comment by vestrada** [comment]
Per conversation with Hyangghee I can't reproduce this issue.
