### ISSUE TITLE
[studio-ui] Component Preview Panel is not available from Preview Tools

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2611]
### Expected behavior
Component Preview Panel is not available from Preview Tools

### Actual behavior
Component Preview Panel is not available.  When you expand the preview tools panel, the component preview is not available

![screen shot 2018-11-06 at 12 08 58 pm](https://user-images.githubusercontent.com/25483966/48081038-1c05a280-e1bd-11e8-8673-27e9d9884b41.png)

### Steps to reproduce the problem
* Start Studio on develop
* Create a site using any bp
* Preview the home page 
* Click on `Preview Tools` on the top right, notice that **Page Component** is missing from the panel
* Open your preview panel configuration ( **Site Config** -> **Configuration** -> **Preview Panel Configuration**) and notice that there should be a components panel

Here's a portion of the preview panel configuration indicating the components should be in the panel:
```
<panel>
    <modules>
        <module>
            <moduleName>ice-tools-panel</moduleName>
            <title>inContextEditing</title>
        </module>

        <module>
            <moduleName>component-panel</moduleName>
            <title>pageComponents</title>
        </module>

        <module>
            <moduleName>medium-panel</moduleName>
            <title>publishingChannel</title>
            <config>
.
.
.
```
I don't see any errors in the tomcat log and no errors too when I inspect the browser.

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-88f151
Build Number: 88f151b4616542e8dbd4a2f62742dd0e62a00745
Build Date/Time: 11-06-2018 11:38:36 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
Hi @alhambrav ,

I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/11640613/48163111-631a9300-e2a4-11e8-8ecd-fe4b0606ca04.png)

**Comment by alhambrav** [comment]
Closing the ticket.  Cannot reproduce using the following version:
```
Studio Version Number: 3.1.0-SNAPSHOT-bd1f08
Build Number: bd1f08882d3ae9bb0d2c3f9e9d0107cd6a5b8c3e
Build Date/Time: 11-07-2018 17:38:53 -0500
```
