### ISSUE TITLE
[studio-ui] Component preview panel does not support macros in 3.0

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2612]
### Expected behavior
Component preview panel should support macros in paths

### Actual behavior
Component preview panel does not support macros in paths

### Steps to reproduce the problem
* Create a site using website_editorial
* Open the Sidebar, click on `Site Config`, click on `Configuration` then from the dropdown, select `Preview Component Configuration` 
* Add the macro `{objectId}` to the path for the category general
```
<category>
        <label>General</label>
        <component>
            <label>Feature</label>
            <type>/component/feature</type>
            <path>/site/components/features/{objectId}</path>
        </component>
    </category>
```
* Save your changes and preview the Home page
* Click on the wrench (Preview Tools) at the top right of Studio to open the Preview Tools Panel
![screen shot 2018-11-06 at 11 58 34 am](https://user-images.githubusercontent.com/25483966/48088920-39dd0280-e1d1-11e8-9bcd-68207bc60cf9.png)

* Expand `Page Components`
* Click and drag `Feature` under `General` to the drag and drop zone, notice that the form for the component is empty
![screen shot 2018-11-06 at 2 08 45 pm](https://user-images.githubusercontent.com/25483966/48088115-1c0e9e00-e1cf-11e8-9cbd-f0130aa3507f.png)

Don't know yet if the problem also exists for the develop branch.  Will check when ticket https://github.com/craftercms/craftercms/issues/2611 is resolved.

### Log/stack trace (use https://gist.github.com)
Here's a short clip showing the steps listed above: 
https://www.useloom.com/share/5f13dbe5d0d74b6d8841bc9231c6efad

#### Version
Studio Version Number: 3.0.19-SNAPSHOT-c4a68e
Build Number: c4a68e4b869ea9e0a326cb7fb9e3e322c0498bce
Build Date/Time: 11-05-2018 14:10:00 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by vestrada** [comment]
3.1 - > PR: https://github.com/craftercms/studio-ui/pull/980

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/981

**Comment by alhambrav** [comment]
Hi! Assigning back to you to fix `category` as discussed.  Thanks!

**Comment by vestrada** [comment]
3.1 - > PR: https://github.com/craftercms/studio-ui/pull/982

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/983

**Comment by alhambrav** [comment]
Verified fixed.
