### ISSUE TITLE
[studio] Add support for multiple SSO logout url when we have multiple headers authentication provider configured 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2614]
### Expected behavior
Add support for multiple SSO logout url when we have multiple headers authentication provider configured.
 It would be nice to be able to specify an SSO logout url for each headers authentication provider configured in the authentication chain.

### Actual behavior
There's only one configuration setting for the SSO logout url, so, if you have multiple headers authentication provider setup in your authentication chain, there's no way to specify an SSO logout url for each headers authentication provider.

Here's the current configuration for the SSO logout url:
```
# Enable/disable logout for headers authenticated users (SSO)
# studio.authentication.headers.logout.enabled: false
# If logout is enabled for headers authenticated users (SSO), set the endpoint of the SP or IdP logout, which should
# be called after local logout. The {baseUrl} macro is provided so that the browser is redirected back to Studio
# after logout (https://STUDIO_SERVER:STUDIO_PORT/studio)
# studio.authentication.headers.logout.url: /mellon/logout?ReturnTo={baseUrl}
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1585
https://github.com/craftercms/craftercms/pull/3130

**Comment by alhambrav** [comment]
Verified and docs updated PR commit: https://github.com/craftercms/docs/pull/761/commits/dbb18c38e46beb3309b20f7fa9d4409a855f2567
