### ISSUE TITLE
[studio-ui] preview-server url should be read from a single location

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2617]
### Expected behavior
Any aspect of Studio that needs to look up the preview server location should do so from a single location.

To be consistent with other configuration tickets: 
Please remove the preview-server tag in `config/studio/site-config.xml` as a source of the preview server location/URL for a given site and use the one in `config/studio/environment-config/environment.xml` as the sole source of truth. There should no longer be any blueprints/code that uses `config/studio/site-config.xml`

### Actual behavior
Preview window uses:  `config/studio/site-config.xml`
Other components like the form engine use `config/studio/environment-config/environment.xml`

#### Version
Studio Version Number: 3.0.18-SNAPSHOT-c83d09
Build Number: c83d093236093940482d6fc2b3c719e46344278a
Build Date/Time: 10-26-2018 11:42:55 -0400

**Comment by vestrada** [comment]
studio -> 3.0 - > https://github.com/craftercms/studio/pull/1373

**Comment by vestrada** [comment]
studio-ui -> 3.1 - > https://github.com/craftercms/studio-ui/pull/996

**Comment by vestrada** [comment]
studio-ui -> 3.0 - > https://github.com/craftercms/studio-ui/pull/997

**Comment by vestrada** [comment]
Hi Dejan, 
This is for you :)

**Comment by dejan-brkic** [comment]
3.0: https://github.com/craftercms/studio/pull/1439

3.1: https://github.com/craftercms/studio/pull/1440

**Comment by russdanner** [comment]
studio.configuration.site.defaultPreviewUrl should be hard coded to port 8080.
Update default value for this parameter to:
`studio.configuration.site.defaultPreviewUrl: ^https?://localhost:8080/?`

**Comment by russdanner** [comment]
Workaround:

The easiest workaround to this bug is to use 1<preview-server>http://127.0.0.1:9090/</preview-server>1 in your site's environment configuration.

The other workaround is to edit `CRAFTER/bin/apache-tomcat/shared/classes/crafter/studio/extension/studio-config-override.yaml`
Add the following line and restart your Crafter Studio Server
studio.configuration.site.defaultPreviewUrl: `^https?://localhost:8080/?`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1446

**Comment by russdanner** [comment]
Confirmed
