### ISSUE TITLE
[studio-ui] studio guest JS library should respect the preview server location configuration when initializing

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2618]
### Expected behavior
If the preview server is configured to a different hostname, port or protocol the guest JS library should set up the message bus accordingly.

### Actual behavior
Guest JS library assumes the preview server is the same hostname, port and protocol of the studio server.

#### Version
Studio Version Number: 3.0.18-SNAPSHOT-c83d09
Build Number: c83d093236093940482d6fc2b3c719e46344278a
Build Date/Time: 10-26-2018 11:42:55 -0400

**Comment by russdanner** [comment]
The guest script initializes the communication by assuming that the preview server is located at the same protocol, host and port as the authoring server.  This assumption is invalid.  Using studio configuration it's possible to point to a preview server running on an entirely different server.  The guest script should initialize the communication bus properly according to the configuration.

**Comment by vestrada** [comment]
PR -> 3.1 -> https://github.com/craftercms/studio-ui/pull/994

**Comment by vestrada** [comment]
PR -> 3.0 -> https://github.com/craftercms/studio-ui/pull/995

**Comment by vestrada** [comment]
Dejan please add the BE changes to 3.0
Thanks

**Comment by dejan-brkic** [comment]
Done in PR: 
https://github.com/craftercms/studio/pull/1370
(ticket 2632)

**Comment by russdanner** [comment]
This does not appear to work properly yet
<img width="1436" alt="screen shot 2018-11-30 at 1 31 06 pm" src="https://user-images.githubusercontent.com/169432/49307802-4ee14480-f4a4-11e8-90a0-38a9fa7145cc.png">

The example above:
- React app running on NodeJs PORT 3000
- Studio configured to preview it.  Environment Configuration:
```
<environment-config>
    <preview-server-url>http://localhost:3000</preview-server-url>
    <authoring-server-url>http://localhost:8080/studio</authoring-server-url>
    <live-server-url>http://localhost:9080/?crafterSite={siteName}</live-server-url>
    <open-sidebar>false</open-sidebar>
    <publishing-targets>
        <target>
            <repo-branch-name>live</repo-branch-name>
            <display-label>Live</display-label>
        </target>
    </publishing-targets>
</environment-config>
```

**Comment by vestrada** [comment]
Hi!
 The CORS policy issue we were having for fontawesome is fixed.
 Remenber to use: 
`<script src="http://localhost:8080/studio/static-assets/libs/requirejs/require.js"
              data-main="http://localhost:8080/studio/overlayhook?site=NOTUSED&page=NOTUSED&cs.js"></script>`

**Comment by russdanner** [comment]
Confirmed!
NIIIICE. :D
