### ISSUE TITLE
[studio-ui] sort configurations in site config panel alphabetically

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2621]
Sort configurations in site config panel alphabetically

<img width="1255" alt="screen shot 2018-11-09 at 2 09 41 pm" src="https://user-images.githubusercontent.com/169432/48282985-32b03180-e429-11e8-89e1-7480aac2f3a3.png">

**Comment by sumerjabri** [comment]
@russdanner these are sorted based on how they're listed in the master configuration which can be modified by the user if required.

This default order is by utility and frequency of use for a typical user.

- Do you still want us to sort it alphabetically?
- When we merge these into a single YAML file with sections, sorting will mean little. (ETA 3.2)

**Comment by russdanner** [comment]
Feedback from a number of users is:
- When directed by documentation or someone helping them to work with a specific file, then the alpha sort would help. Without grouping or familiarity, it comes off as a jumbled list.  

I think the solution for 3.2 is much better than sorting the list -- and I think we can hold off on this for now.

**Comment by russdanner** [comment]
Feedback from a survey of users is:
When directed by documentation or someone helping them to work with a specific file, then the alpha sort would help. Without grouping or familiarity, it comes off as a jumbled list.

I think the solution for 3.2 is much better than sorting the list.  

In the meantime, a sorted list may be slightly easier.  Looking at the titles, does it make sense to group them 

Authoring: Sidebar ConfigurationAuthoring: Site Configuration

**Comment by russdanner** [comment]
When I enable the requirements and the message and then use the UI to reset my password I do not get the detailed description and I have this error in the log.

<img width="1393" alt="Screen Shot 2019-10-28 at 1 34 21 PM" src="https://user-images.githubusercontent.com/169432/67702325-e9355b00-f987-11e9-8ef7-e07f255bd3a4.png">

```
[ERROR] 2019-10-28T13:34:17,965 [http-nio-8080-exec-10] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/users/me/change_password failed with response: ApiResponse{code=6003, message='User password does not fullfill requirements', remedialAction='Use password that will fullfill password requirements', documentationUrl=''}
org.craftercms.studio.api.v2.exception.PasswordRequirementsFailedException: null```

**Comment by russdanner** [comment]
When I enable the requirements and the message and then use the UI to reset my password I do not get the detailed description and I have this error in the log.

<img width="1393" alt="Screen Shot 2019-10-28 at 1 34 21 PM" src="https://user-images.githubusercontent.com/169432/67702325-e9355b00-f987-11e9-8ef7-e07f255bd3a4.png">

```
[ERROR] 2019-10-28T13:34:17,965 [http-nio-8080-exec-10] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/users/me/change_password failed with response: ApiResponse{code=6003, message='User password does not fullfill requirements', remedialAction='Use password that will fullfill password requirements', documentationUrl=''}
org.craftercms.studio.api.v2.exception.PasswordRequirementsFailedException: null```
