### ISSUE TITLE
[docs] Document the new RTE control (TinyMCE5)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2627]
Please see the new RTE control and play with it. Next, please do:

1. Make sure it's in all defautl BPs
2. Document it (you can reach out to JVega for more information)
3. Please work on a document on how to upgrade/switch your site from the old RTE to the new RTE

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/685

**Comment by alhambrav** [comment]
commit https://github.com/craftercms/docs/pull/757/commits/e23ee6a547fd74ae014ff419a1fd8a0f0e9eec37

**Comment by sumerjabri** [comment]
Verified fixed.
