### ISSUE TITLE
[studio] Add VideoCenter 2 to the list of default blueprints

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2628]
Please add VC2 https://github.com/craftercms/video-center-blueprint to be part of what ships out of the box with 3.1

**Comment by sumerjabri** [comment]
clone into global/blueprints

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1451

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/2806
https://github.com/craftercms/studio/pull/1454

**Comment by dejan-brkic** [comment]
Done
PRs:
https://github.com/craftercms/craftercms/pull/2962
https://github.com/craftercms/studio/pull/1511
https://github.com/craftercms/video-center-blueprint/pull/15
