### ISSUE TITLE
Dashboard widgets attach "/" at the end of the browserUri when loading preview

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#263]
All dashboard widgets attach '/' at the end of browserUri for preview URL as in the example code below:

'<a class="anchorRow' , (item.disabled == true ? ' dashboard-item disabled' : '') , '" ', (item.previewable == true) ? 'href="/studio/preview/#/?page='browserUri'/&site='CStudioAuthoringContext.site'"' : '', ' class="', (item.previewable == true ? 'previewLink' : 'non-previewable-link'), '">',

This breaks preview of file contents like /some-folder/file.html. The system should not modify browserUri upon generating preview URLs.

**Comment by asotog** [comment]
working on this one

**Comment by asotog** [comment]
PR merged https://github.com/craftercms/studio2-ui/pull/98

**Comment by hlim** [comment]
the fix confirmed.

**Comment by hlim** [comment]
Still see the error - checking if the code is merged properly

**Comment by asotog** [comment]
crafter code is fixed, error we are seeing is because some extension code not updated on our side
