### ISSUE TITLE
[studio] Add the new RTE to all bps

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2631]
### Expected behavior
It would be nice to have the new RTE available from all the blueprints.  Please add the new RTE to all bps. 

### Actual behavior
The new RTE is not available from the blueprints.  You'll have to add it in the `Site Config Tools` configuration file of your site

### Steps to reproduce the problem
* Create a site using any bp
* Open an existing type by going to `Site Config` -> `Content Types` -> `Open Existing Type` -> `Page - Article`
* Look at the controls available, `Controls`.  Notice that the new RTE is not available

<img width="435" alt="screen shot 2018-11-19 at 2 10 58 pm" src="https://user-images.githubusercontent.com/25483966/48729189-fccb3400-ec04-11e8-8748-2306caec84e7.png">

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-9ee18c
Build Number: 9ee18c318bb74bb8b0e74f90f595ba6a651f1171
Build Date/Time: 11-19-2018 08:04:52 -0500
#### OS
OS X
#### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1365

**Comment by alhambrav** [comment]
@jvega190, the new RTE does not seem to be working correctly out of the box...  Unless I'm missing a setting/configuration?

I added the new RTE to a content type (`Page - Article` content type) 

<img width="1392" alt="screen shot 2018-11-28 at 1 11 21 pm" src="https://user-images.githubusercontent.com/25483966/49172486-37248780-f30f-11e8-9aa9-92f2958321dc.png">

and edit an existing article, I get this:
<img width="1399" alt="screen shot 2018-11-28 at 12 49 06 pm" src="https://user-images.githubusercontent.com/25483966/49171868-823d9b00-f30d-11e8-8dcc-f1c37f3c6bc5.png">

From the screenshot above, it looked like it was looking for `templates`... So, I then added `templates` to the RTE configuration (taken from the sample):
```
<templates>
            <template>
                <title>Test template 1</title>
                <content>Test 1</content>
            </template>
            <template>
                <title>Test template 2</title>
                <content>Test 2</content>
            </template>
        </templates>
```

and this is what I get:

<img width="1389" alt="screen shot 2018-11-28 at 1 08 31 pm" src="https://user-images.githubusercontent.com/25483966/49172342-c8472e80-f30e-11e8-8217-e972f44597e1.png">

**Comment by alhambrav** [comment]
Issue fixed in ticket https://github.com/craftercms/craftercms/issues/2803.
Verified.
