### ISSUE TITLE
[studio] Update overlayhook.ftl and services to provide authoring server information

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2632]
### Expected behavior
Update the overlayhook.ftl and back end services to provide the following information:
document.domain = "${cookieDomain}";

The following code snippet shows the final state of the overlayhook.ftl
Commented code is cleaned up and the event fired on require guest JS has been updated to pass new values pertaining to the authoring server to the guest

 ```js
requirejs.config({
    baseUrl: '/studio/static-assets/scripts',
    paths: {
        'libs': '/studio/static-assets/libs/',
        'jquery': '/studio/static-assets/libs/jquery/dist/jquery',
        'jquery-ui': '/studio/static-assets/libs/jquery-ui/jquery-ui',
        'amplify': '/studio/static-assets/libs/amplify/lib/amplify.core',
        'noty': '/studio/static-assets/libs/notify/notify.min',
        'cache': '/studio/static-assets/libs/js-cache/cache'
    }
});

require(['guest'], function (guest) {
    guest.init({
      authoringServer: "${envConfig.authoringServer!''}", // example: http://localhost:8080
      studioContext: "${envConfig.studioContext!''}",         // example:  studio 
      studioStaticAssets: "static-assets"                 
    });
});
```

New variables will be required
 authoringServer: "${envConfig.authoringServer!''}", // example: http://localhost:8080
 studioContext: "${envConfig.studioContext!''}",         // example:  studio 

# Related ticket
https://github.com/craftercms/craftercms/issues/2618

#### Version
Studio Version Number: 3.0.18-SNAPSHOT-c83d09
Build Number: c83d093236093940482d6fc2b3c719e46344278a
Build Date/Time: 10-26-2018 11:42:55 -0400

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1366

**Comment by russdanner** [comment]
Confirmed
