### ISSUE TITLE
[docs] Move Security Policies to the top level in 3.0/master

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2633]
Please move this article:
https://docs.craftercms.org/en/3.1/system-administrators/activities/security/security-policies.html

To be under a new top-level category called `Security`. If someone were to click on Security, they get the article right away (it's not a landing page that leads to the article).

The reason is: it's not a System Admin related activity/concern, it's a product level policy.

Another approach would be to have a top-level `Policies` and put that under it, but we only have this at the moment.

Ping me if you have questions or concerns.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/647 and https://github.com/craftercms/docs/pull/648
