### ISSUE TITLE
[studio-ui] edit code item from dashboard leaves edit button disabled after save

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2635]
## Describe the bug
When a user edits code (JS,CSS,Template,Groovy etc) from the dashboard via the edit button on the dashboard widget and hits save they cannot click the same edit button to re-open the form.  The edit button/link is disabled.  A refresh is required to re-enable the button.

## To Reproduce
1. Edit a groovy script so that it appears on your dashboard in recent activiy
2. Using the edit button on the dashboard, edit the file again
3. Save
4. Try and edit again (you cant.)

## Expected behavior
User should be able to edit as many times as they like.  The link should be enabled after save.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.0.17-SNAPSHOT-5e8acf
Build Number: 5e8acf27a697e7a6a52f4156a5c390a3538c6687
Build Date/Time: 09-19-2018 16:41:26 -0400

Applies to .18 as well

### OS
N/A

### Browser
Chrome

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/992

**Comment by vestrada** [comment]
3.0.X -> PR -> https://github.com/craftercms/studio-ui/pull/993

**Comment by russdanner** [comment]
Confirmed
