### ISSUE TITLE
[profile] query-profiles throws a deserialization error when Crafter Profile service responds improperly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2638]
## Describe the bug
Using the following code (groovy script in REST controller on Engine) a deserialization is thrown:

```java
import org.craftercms.profile.api.SortOrder;

// script is not currently working this is debugging
def TENANT="YOURTENANTNAME"
try {
    def profiles=profileService.getProfilesByQuery(TENANT,'{}',"username",SortOrder.ASC,0,Integer.MAX_VALUE,null)
}catch(Throwable ex){
    logger.error("error getting profiles",ex)
}
```

## To Reproduce
1. Configure a Profile tenant and link to Crafter Engine site
2. Create a RESTful groovy GET script with the above code
3. Remove the Profile war
4. Using a browser to execute the REST call
5. See error in logs

## Expected behavior
The error should indicate the nature of the issue 
Examples:
- Profile server responded with 500 error
- Profile server is not reachable

## Screenshots
N/A

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
https://gist.github.com/russdanner/c1482ea8c2cf668d385ef787841e3550

### Version
Version Number: 3.0.16-SNAPSHOT-4c989c
Build Number: 4c989c7cb50201155c988637a6db453257b7a1cc
Build Date/Time: 08-02-2018 14:57:36 -0400

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614  I don't think this is a valid use case, why would someone remove the Profile war? it sounds more like a configuration/setup issue
