### ISSUE TITLE
[studio-ui] Side bar and content menu isn't refreshed after save draft and cancel.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2639]
## Describe the bug
When the user save as draft the form engine, and then try cancel the form, the side bar and context menu is not refreshed. The icon of item is a padlock describing that the item is lock, bit it's not.

## To Reproduce
1. Create a site using a BP
2. Go to preview and select home
3. Click on edit.
4. Click on save draft
5. Click on cancel

## Expected behavior
When the user save as draft the form engine, and then try cancel the form, the side bar and context menu should be refreshed.

## Screenshots
https://www.useloom.com/share/267a5424744c4fd8ac059a61d7a78c1a

### Version
Studio Version Number: 3.1.0-SNAPSHOT-e2d080
Build Number: e2d080da5cf524e563d4e94597cde81153159fc7
Build Date/Time: 11-22-2018 10:51:17 -0600

### OS
Mac

### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1053

**Comment by vestrada** [comment]
Hi Yac

Can you review this ticket :)

**Comment by yacdaniel** [comment]
Sure :v:

**Comment by yacdaniel** [comment]
Verified fixed.
