### ISSUE TITLE
[studio] Upgrade sites/blueprints to add the new RTE

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2643]
Add a new upgrade job/mechanism to add the new RTE to existing sites/blueprints. See this PR as an example:
https://github.com/craftercms/studio/pull/1365

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1464

**Comment by avasquez614** [comment]
@yacdaniel after asking Sumer, this ticket should be done, we don't need to upgrade the RTE v2 in the content types. Please verify

**Comment by yacdaniel** [comment]
@dejan-brkic we have a duplicated body content, one using old rte and the other with the new one. Content Type Template: `Component - Feature` from `Website_editorial`
<img width="678" alt="screen shot 2019-02-07 at 6 53 07 pm" src="https://user-images.githubusercontent.com/6722074/52452688-b69db680-2b09-11e9-944f-7109369eb69c.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1467

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1516

**Comment by sumerjabri** [comment]
@yacdaniel please verify and close if okay

**Comment by yacdaniel** [comment]
Verified fixed.
