### ISSUE TITLE
[studio] Add the Video Center Blueprint to the main build

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2645]
Please add the new video center to the collection of available blueprints during the gradle build process.
The BP is here: https://github.com/craftercms/video-center-blueprint.git

**Comment by jdrossl** [comment]
@sumerjabri do you mean we should clone the repo and add it to the global repo? Is this a duplicate of https://github.com/craftercms/craftercms/issues/2628

**Comment by sumerjabri** [comment]
@jdrossl 
- yes, it's a dupe
- yes, clone into global/blueprints
