### ISSUE TITLE
[studio] Add ability to upgrade site content to the Upgrade Manager

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2646]
Add the necessary mechanics and documentation (to `README.md` and regular `Sphinx-Doc`) to allow to run upgrade mechanics against the content of a site.

This is in support of the new `remote-assets` proxy mechanism that needs to be weaved into existing sites to support remote indexing and related features.

**Comment by sumerjabri** [comment]
@alhambrav please validate and document. This is an essential feature moving forward (3.1 and beyond). Please make sure that all of the upgrade manager and its mechanics are documented.

Documentation can link to the projects `.md` docs and provide context if that's easier.

**Comment by alhambrav** [comment]
Validated. Documentation here: https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/add-to-upgrade-scripts.html
