### ISSUE TITLE
[studio] Add `remote-assets` proxy to existing sites that use Box

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2647]
Use the new Upgrade Manager feature that upgrades site content to upgrade existing sites that use Box to use the new proxy mechanism.

The new feature in Upgrade Manager can be tracked here: https://github.com/craftercms/craftercms/issues/2646

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 I'm not sure if we can do this, because to build the new url we need to know the profileId and it is not part of the xml files

**Comment by sumerjabri** [comment]
The general approach is to interrogate the model, find the Box URLs, scan the content for those elements and update them.

**Comment by sumerjabri** [comment]
@alhambrav ping me to help you create a site based on a Box BP. Then have the new Studio upgrade it and see if the remote-assets proxy is added correctly.

**Comment by alhambrav** [comment]
Verified remote-assets proxy is added correctly
