### ISSUE TITLE
[studio-ui] add time only control

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2649]
**Is your feature request related to a problem? Please describe.**
There is no form control that saves a time value by itself.  The date-time picker has an option to hide the date portion of the user input.  This defaults to the current date.  

Example (field with show time property as true and show date property as false:
saved value: 2018-11-27T23:43:31.000Z

**Describe the solution you'd like**
Create a time control that requires only time values and saves only time values.

**Describe alternatives you've considered**
- Using the current control, if the Show Date property is false, do not save the date.  The concern here is the impact to existing users.

**Comment by vestrada** [comment]
video center: https://github.com/craftercms/video-center-blueprint/pull/35
studio: https://github.com/craftercms/studio/pull/1598
studio-ui: https://github.com/craftercms/studio-ui/pull/1165

**Comment by russdanner** [comment]
Confirmed

Time is stored as the default/site config timezone OR with timezone field if configured on control.  Example: 
```
	<myTime>05:37:06</myTime>
	<myTime_tz>America/Phoenix</myTime_tz>
```

**Comment by sumerjabri** [comment]
@vestrada please make sure there is ALWAYS a timezone in the resulting XML

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1180

**Comment by yacdaniel** [comment]
Verified.
