### ISSUE TITLE
[studio] The box-file-upload control should save a /remote-assets/box style URL

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2652]
The `box-file-upload` should create a `<url>` element that contains a remote asset type URL for the uploaded file, like `/remote-assets/box/{profile}/{fileId}` (see https://github.com/craftercms/craftercms/issues/2629). If the control itself can't do it, an API should be added to provide this URL (see https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/aws/s3/AwsS3ServiceImpl.java#L143 for reference).

**Comment by jdrossl** [comment]
@vestrada the control needs to include a new field `url` that can be obtained from the service `/api/1/box/url.json?site=a&profileId=b&fileId=c`

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1002

**Comment by avasquez614** [comment]
Verified
