### ISSUE TITLE
[docs] Add documentation for the new Search updates

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2654]
We need to add guides on the following topics:
- Upgrade notes for Solr 7 (3.0.x to 3.1.x & 3.0.20 to 3.0.21)
  - Steps to recreate cores and reindex data in authoring & delivery
- Upgrade notes for 3.0.x to 3.1.x
  - Solr cores in authoring need to be renamed to use the `-preview` suffix
- Steps to start Solr in the bundles (ready) and create site that use Solr (depends on https://github.com/craftercms/craftercms/issues/2757)
- Steps to migrate a site from Solr to Elasticsearch ([ready](https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/migrate-site-to-elasticsearch.html))
- Using the Elasticsearch API from Groovy
- Using the Elasticsearch REST API

**Comment by jdrossl** [comment]
@alhambrav All PRs have been merged now, let me know if you have any questions

**Comment by jdrossl** [comment]
@alhambrav we can start working on this ticket now

**Comment by alhambrav** [comment]
Verified.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 @alhambrav for the Solr changes I created this small guide, I'm not sure if we should just add it to the docs or create a script for it https://gist.github.com/jdrossl/7af86aff38a3b79dac9adcadb6570c93

**Comment by avasquez614** [comment]
I think add it to the docs. We need to be careful with production re-indexing though, look at this guide: https://docs.craftercms.org/en/3.1/system-administrators/activities/reindexing-content-in-prod.html. So maybe change the instructions to take into account production re-indexing.

**Comment by sumerjabri** [comment]
@jdrossl please document the steps as you have. No need to script per @avasquez614 .

**Comment by alhambrav** [comment]
Verified.
