### ISSUE TITLE
[studio] remote pull API should allow merge options

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2655]
**Is your feature request related to a problem? Please describe.**
Pulling a remote via the UI or API may result in a merge conflict.  

**Describe the solution you'd like**
Callers need an option to indicate what should be done with a conflict.  
- No action 
- Email administrator (stretch)
- Accept theirs, 
- Keep mine

Add options to API and pull dialog.  
API parameter should be optional.  Behavior without parameter should be as-is.

**Comment by sumerjabri** [comment]
Related/overlaps with: https://github.com/craftercms/craftercms/issues/3070

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/1644

**Comment by dejan-brkic** [comment]
UI needs to send parameter for sending merge option for `Pull From Remote` API. Possible values are `none` (default), `ours`, `theirs`

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1227

**Comment by russdanner** [comment]
CONFIRMED
