### ISSUE TITLE
[studio-ui] Inserting images into RTE via WebDav does not work

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2657]
## Describe the bug
Inserting images into RTE via WebDav does not work.
* No markup is inserted at all
https://www.useloom.com/share/1994314facc244249012e701dfc2d29a

## To Reproduce
1. Configure webdav endpoint
2. In form add wedav image data source, link to an RTE
3. Attempt to insert image, it does not.
4. In RTE view HTML, note nothing is inserted (no image tag or path)

## Expected behavior
RTE should insert a image tag and path

## Screenshots
https://www.useloom.com/share/1994314facc244249012e701dfc2d29a

## Logs
N/A

### Version
Software version if applicable (copy paste from Help > About).
Studio Version Number: 3.0.18-SNAPSHOT-c83d09
Build Number: c83d093236093940482d6fc2b3c719e46344278a
Build Date/Time: 10-26-2018 11:42:55 -0400

### OS
Any

### Browser
Chrome

**Comment by vestrada** [comment]
3.1.x -> PR: https://github.com/craftercms/studio-ui/pull/1000

**Comment by vestrada** [comment]
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1001

**Comment by russdanner** [comment]
Confirmed
