### ISSUE TITLE
Upgrade to log4j2

### ISSUE THREAD

**Issue by zac-poe** [craftercms/craftercms#2658]
Crafter logging is presently backed by log4j, which does not offer all modern logging capabilities available in the newer log4j2.

An upgrade to log4j2 would offer new appenders, formatting capabilities, and considerable logging performance improvements. Additionally, log4j community support has concluded, so there will not be any version upgrades or development expansions with that core logger.

This request is a desired capability for all Crafter executables where such an upgrade is possible (engine, studio, deployer, databases, solr, bundled webservers).

Alternatively, Logback would also be a modern upgrade providing many of the same capabilities and improvements.

**Comment by avasquez614** [comment]
Verified
