### ISSUE TITLE
[sutdio-ui] S3 browse datasources should not have a Type field

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2664]
The S3 browse datasources:

- `S3-repo`
- `image-S3-repo`
- `video-S3-repo`

Should not have the `Type` field. The type parameter should be sent according to the DS type, eg. `type=image` or `type=video`.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1004

**Comment by avasquez614** [comment]
Verified
