### ISSUE TITLE
[studio-ui] Request Publish form is not clickable for user in site_author group

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2666]
## Describe the bug
When a user is a member of the site_author group and the user edits a page and click on Request Publish the form that popups is not clickable although with the keyboard it works.

## To Reproduce
1. With admin account create a site from any BP
2. Create a user and assign it to the site_author group
3. Sign out from admin and Sign in with the user in the site_author group 
4. Edit the site and click Request Publish

## Expected behavior
Request Publish form is clickable. 

## Screenshots
Video demo: https://www.useloom.com/share/2b74ba50dfb24cde86a7805ac2940ed4

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-f78674
Build Number: f786749e5092110d99e7abd1554e0ca543317d50
Build Date/Time: 11-30-2018 15:23:34 -0600

### OS
MacOS

### Browser
Chrome, Firefox

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1005

**Comment by yacdaniel** [comment]
Verified fixed.
