### ISSUE TITLE
[studio] Don't publish packages that don't exist in local repo

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2678]
In a clustered env, it's normal to have a publish package in the database (along with item meta-data), but not have the content on disk yet. In that case, the publisher must go back to sleep and another publisher in the cluster or this publisher can pick that work up when content is ready.

The algorithm can be:
- Wake up and grab the package from the queue by setting the state of the package to `Processing`
- If one or more items in the package don't exist on disk with the exact commit_id as in the package, reset the status of the package to `Ready_for_Live` and go back to sleep

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1392
