### ISSUE TITLE
[studio] If a commit is marked as don't process, the db-syncer/publishing thread shouldn't process

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2679]
In support of clustering, and as a general feature, if a commit has a comment containing:
`STUDIO: NO PROCESSING`

The publishing thread/disk sync'er must not update the database and simply add the commit_id to git_log and continue without processing.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1385
