### ISSUE TITLE
In some cases crafter publish dialog pulls old comments

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#268]
Does not appear to be a front end issue or caching.

**Comment by russdanner** [comment]
Need to get more details before we can assign this.

Schedule -> Commit -> Publish -> Edit -> Republish -> See original commit message in dialog, should be blank.

**Comment by dejan-brkic** [comment]
Resetting workflow properties on deployment
PR #388

**Comment by cortiz** [comment]
craftercms/studio#338
