### ISSUE TITLE
[studio] Clustering sandbox sync'er must merge with a special comment

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2680]
Clustering sandbox sync'er must add the comment to cluster merges:
`STUDIO: NO PROCESSING`

The purpose to avoid double processing of content as the content has already been processed by another cluster node.

To achieve this, `git fetch` first, and then use `git merge` with a comment including the above string and auto-commit which causes the cluster nodes to avoid processing this type of commit.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1388
