### ISSUE TITLE
[studio] Add new API 2 spec for CMIS

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2683]
Add API v2 spec (OAS) for CMIS:

* `/cmis/list`: lists the children under a folder in a CMIS repo
* `/cmis/search`: queries the CMIS repo for items based on a query statement.
* `/cmis/clone`: clones an item from the CMIS repo into Studio.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1596

**Comment by avasquez614** [comment]
Verified
