### ISSUE TITLE
[studio-ui] Sidebar (nav tree) is not updated after editing a static-asset when in Preview

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2685]
## Describe the bug
Sidebar (nav tree)is not updated after editing a static-asset when in Preview for both master and 3.0

## To Reproduce
1. Create a site using website_editorial
2. Go to Preview by clicking on `Home`  from the `Sidebar`
3. In the `Sidebar`, right click `/static-assets/js/main.js` and select `Edit`
![screen shot 2018-12-06 at 9 25 24 am](https://user-images.githubusercontent.com/25483966/49590074-eaf1cc80-f938-11e8-985c-ce724ec11e05.png)
(You can edit any of the css or js files to test)
4. Make some changes then click on the `Update` button to save.  Notice on the `Sidebar` that the icon for `main.js` does not indicated edited 
![screen shot 2018-12-06 at 9 28 00 am](https://user-images.githubusercontent.com/25483966/49590241-5f2c7000-f939-11e8-94d9-8795f773bf66.png)

5. Either refresh your browser or click on the `Dashboard`, notice that the icon for `main.js` now indicates it is edited.
![screen shot 2018-12-06 at 9 29 57 am](https://user-images.githubusercontent.com/25483966/49590327-9c90fd80-f939-11e8-8073-f40e4cc9a21c.png)

## Expected behavior
The `Sidebar` nav tree should be updated without having to refresh whenever edits have been made to `static-assets`

## Screenshots/Videos
Here's a short clip showing the Sidebar nav tree not updated when editing an item in static-asset when in Preview:
https://www.useloom.com/share/6b039dcc8c984bbab287fdb743c16c42

The clip shows the following:
1. When in Preview, and you edit a static-asset item, the Sidebar is not updated
2. Then it goes on to show when in the Dashboard and you edit a static-asset item, the Sidebar is updated
3. Finally shows again that when in Preview and you edit a static-asset item, the Sidebar is not updated

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.0.19-SNAPSHOT-0d3eab
Build Number: 0d3eabd5042974c3d9c55752baff29dafd5a351b
Build Date/Time: 12-06-2018 01:34:09 -0500

Please note the issue is also in master.

### OS
OS X

### Browser
Chrome Browser

**Comment by vestrada** [comment]
3.1.x -> PR: https://github.com/craftercms/studio-ui/pull/1007

**Comment by vestrada** [comment]
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1008

**Comment by alhambrav** [comment]
Verified fixed
