### ISSUE TITLE
[engine] Navigation sets more than one item as active

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2686]
## Describe the bug
When the path of two pages starts with the same value both appear as active in the dynamic navigation

## To Reproduce
1. Create two pages and add them to the dynamic nav with the following paths
- `/test`
- `/test2`
2. Go to page `/test2`

## Expected behavior
Only one item should be marked as active

## Screenshots
<img width="141" alt="screen shot 2018-12-06 at 4 34 22 pm" src="https://user-images.githubusercontent.com/1236955/49616715-5fe3f700-f977-11e8-89a9-633cc0d7ff21.png">

### Version
3.0.x, 3.1.x

### OS
MacOS 10.13.6

### Browser
Chrome

**Comment by avasquez614** [comment]
PR https://github.com/craftercms/engine/pull/221 and https://github.com/craftercms/engine/pull/222

**Comment by jdrossl** [comment]
Verified on both versions
