### ISSUE TITLE
Form Section should have the availability to close/open depending if any of it's child has content

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#269]
Form Section should have the availability to close/open depending if any of it's child has content 
so if a Form section is empty and a _open if content is set_ option is set true, form section should open , if the  _open if content is set_ option is set true and any of it's child do not have content it should close, Default Open should have higher priority than  _open if content is set_

**Comment by russdanner** [comment]
Backlogging this ticket until a future release.  It will not fit in 2.5.2 at this time.
