### ISSUE TITLE
[studio] Don't fail if DB initialization fails to connect

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2690]
Currently, if the DB init script fails to connect to the database, Studio won't come up. Let's change that and assume that perhaps the DB is ready for us and the failure to connect/init isn't indicative of total DB failure.

The situation comes up when there is a cluster and one of the nodes already initialized the DB or when connecting to DB as a service where DB init is not necessary.

**Comment by sumerjabri** [comment]
@alhambrav please validate and close.

**Comment by alhambrav** [comment]
Verified.
