### ISSUE TITLE
[studio] Cluster garbage collection and inactive indication

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2691]
Per our conversation, please add a mechanism to indicate if a node is no longer active and a mechanism to remove the inactive nodes after a configurable period of time.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1431
https://github.com/craftercms/craftercms/pull/2781

**Comment by sumerjabri** [comment]
@alhambrav please validate

**Comment by alhambrav** [comment]
Verified.
