### ISSUE TITLE
[studio-ui] Cluster table members is not responsive

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2692]
## Describe the bug
The members table in Cluster is not responsive

## To Reproduce
1. Add a member to the cluster.
2. Go to Main Menu -> Cluster.
3. Narrow the width browser screen until you notice the missing text at the right in the table.

## Expected behavior
The cluster members table is responsive

## Screenshots
![screen shot 2018-12-10 at 5 13 54 pm](https://user-images.githubusercontent.com/6722074/49767684-1ceb9180-fc9f-11e8-8c25-d4e458d7e683.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-bff8d4

Build Number: bff8d49bf32ac545a5d966fbad95ab4b2c4dd897

Build Date/Time: 12-10-2018 14:31:33 -0600

### OS
MacOS

### Browser
Firefox/Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1029

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.0-SNAPSHOT-11947d
