### ISSUE TITLE
[studio-ui] Missing translations in cluster and others sections.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2693]
## Describe the bug
There are some missing translations in clustering. Checking the locale files I noticed there are other strings not translated  in [Spanish](https://github.com/craftercms/studio-ui/blob/develop/static-assets/scripts/resources/locale-es.json) nor [Korean](https://github.com/craftercms/studio-ui/blob/develop/static-assets/scripts/resources/locale-kr.json) 

## To Reproduce
1. Login using Spanish or Korean
2. Go to Cluster

Others translations missing: 
support/3.0.x and develop branch:
- dashboard -> sites -> SITE_ERROR
- dashboard -> create -> CREATE_ERROR
- admin -> repositories -> REPOSITORIES_PER_PAGE

develop branch:
 - admin -> clustering -> ID, LOCAL_IP, STATE.

## Expected behavior
Strings translated

## Screenshots
Cluster
<img width="823" alt="screen shot 2018-12-11 at 10 05 18 am" src="https://user-images.githubusercontent.com/6722074/49813089-53bbb900-fd2c-11e8-8a57-91041adbc5dc.png">

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
3.0.x, 3.1

### OS
Any.

### Browser
Any.

**Comment by vestrada** [comment]
3.1.x -> PR: https://github.com/craftercms/studio-ui/pull/1021

**Comment by vestrada** [comment]
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1022

**Comment by yacdaniel** [comment]
Verified fixed in ` 3.1.0-SNAPSHOT-eaa094` and `3.0.19-SNAPSHOT-92f298`
