### ISSUE TITLE
[studio] Add clustering menu mechanics via the upgrade manager to existing sites

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2696]
Upgrading Studio doesn't add the clustering menu to the administrator. Please use the upgrade manager to add that menu to the list of menu items available to the admin.

The menu lives here `data/repos/global/configuration/global-menu-config.xml`

@avasquez614 knows about the menu items
@jdrossl knows about the upgrade manager

Remember to use XSLT to add the missing menu item and not overwrite the file.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1399

**Comment by sumerjabri** [comment]
@yacdaniel @alhambrav please make sure that older installations of Studio get the menu item to manage clusters.

**Comment by alhambrav** [comment]
Verified cluster menu is in the upgraded Studio.
