### ISSUE TITLE
[studio] Don't start and stop embedded database in clustered environment

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2698]
## Describe the bug
Presently, we start with the embedded database in case of a clustered environment, and then we shut that down. This is done because of some dependencies.

## To Reproduce
1. Start the system in a clustered mode
2. Note how the embedded database is started and then stopped

## Expected behavior
We shouldn't start the embedded DB at all while running in a cluster.

## Screenshots
N/A

## Logs
N/A

### Version
3.1.0

### OS
Any

### Browser
Any

## Additional context
Nothing more.

**Comment by dejan-brkic** [comment]
Already fixed.
It is needed to set:

```
export SPRING_PROFILES_ACTIVE=crafter.studio.externalDb
```

in `crafter-setenv.sh` inside `crafter-authoring/bin` folder

**Comment by sumerjabri** [comment]
@alhambrav please document accordingly. Please note this may also be possible via an `env` variable, check with @avasquez614 
If not possibel via env, we want to add that to simplify the process.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/760
