### ISSUE TITLE
[studio] Error message in the logs when starting the second node

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2700]
## Describe the bug
There's an error message in the logs when starting the second node: 

`[git.GitContentRepositoryHelper] | error getting the sandbox repository for site: mysite`

## To Reproduce
1. Setup a database 
2. Setup a Studio on one machine for clustering  (1st node) and create a site
3. On another machine, Setup a Studio for clustering (2nd node)
4. Look at the tomcat logs of the 2nd node in the cluster and notice the error message

## Expected behavior
There should be no error in the logs when starting the 2nd,3rd, etc node in the cluster, or better messaging/error handling.  

Some more info on the error message, according to @dejan-brkic , 

`error messages are ok, it is lower level service (repository) complaining it can not find repository (site content not replicated yet)`

It would be nice though to not have an error in the logs.

## Screenshots
N/A

## Logs
https://gist.github.com/alhambrav/87b29f4783fcf96f64dda879009e89e7

### Version
Develop branch

### OS
Windows 10

### Browser
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1586

**Comment by alhambrav** [comment]
Verified fixed.
