### ISSUE TITLE
[studio-ui] Drag and Drop bugs

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2706]
##Describe the bug:
Drag and Drop:

- Drag and drop an element from one zone to another zone from the same component is getting error.
- It looks like Studio is interpreting text that follows ; and # as part of the page URI and thus not correctly identifying the page to tools in preview such as the in-context editing and the drag and drop.
- When the page has a lot of nesting droppable zones, studio breaks. 

## To Reproduce
1. Go to a BP that contains DnD
2. Click on preview tools icon
3. Choose component option.
4. Play with DnD

##Expected behavior
Dnd should work good.

##Version
3.0.x, 3.1

##OS
Any.

##Browser
Any.

**Comment by sumerjabri** [comment]
@vestrada please explain the issue better. This is too brief and vague.

**Comment by vestrada** [comment]
Verified by Jose Ross and Russ
