### ISSUE TITLE
[studio] cms search pagination label does not match result count

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2710]
## Describe the bug
In CMS search within Crafter Studio, the label that shows the result count (1-20) does not match the number of results shown on the page.

## To Reproduce
1. open the editorial site in studio
2. click on the cms search icon
3. search for "et" note 27 results and 2 pages
4. go to second page, studio says viewing 21-27 but shows the last 20 results

## Expected behavior
The label should be consistent with what shows.

Ideally, the paging would feel natural.  Page 1 contains 1-20 and Page 2 contains 21-27
If the search engine forces a page to contain 20 results the label should be consistent with it.

## Screenshots
https://www.useloom.com/share/81de149bf7354867842e54d7c4ab0bb6

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
N/A

### Version
Software version if applicable (copy paste from Help > About).
Studio Version Number: 3.0.19-SNAPSHOT-a24189
Build Number: a24189bd9699e07bcadd3788ca3eb03663a1539d

Build Date/Time: 11-30-2018 12:51:27 -0500
### OS
What OS did you use to produce the bug.
Any

### Browser
What browser did you use to produce the bug.
Any

**Comment by vestrada** [comment]
This is a BE ticket.

**Comment by dejan-brkic** [comment]
Not Studio BE issue. The studio does not provide search CMS feature. This is either UI sending bad params or Engine/Crafter Search creating the wrong query.

**Comment by dejan-brkic** [comment]
Further testing showed that seems like `page` parameter is mapped to offset (incrementing value for `page` is shifting search result by one result

**Comment by sumerjabri** [comment]
@dejan-brkic who should fix this?

**Comment by russdanner** [comment]
<img width="1389" alt="screen shot 2018-12-28 at 12 27 03 pm" src="https://user-images.githubusercontent.com/169432/50523207-cb177980-0a9c-11e9-8d4a-ca62773d447c.png">

**Comment by russdanner** [comment]
It looks like this is a backend issue to me since there are 9 items in the response

<img width="1417" alt="screen shot 2018-12-28 at 12 37 24 pm" src="https://user-images.githubusercontent.com/169432/50523311-66a8ea00-0a9d-11e9-9c5f-64615745afea.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1420
https://github.com/craftercms/studio/pull/1421

**Comment by russdanner** [comment]
Confirmed
