### ISSUE TITLE
[studio-ui] request publish and approve publish dialogs should not allow a submit until dialog is fully loaded

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2711]
## Describe the bug
The submit button is enabled before the dialog has had a chance to fully load.  This allows authors to submit for publishing with missing information which causes other errors.

## To Reproduce
Note this is a race condition which is hard to reproduce
1. Select many items for publishing (to create more server work)
2. Approve and publish
3. Note that the submit button is enabled immediately

## Expected behavior
Do not enable the submission button unless:
- all items and dependencies have loaded and the drop down for environments is populated

## Screenshots
N/A

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Software version if applicable (copy paste from Help > About).
2.5.19

### OS
What OS did you use to produce the bug.
Any

### Browser
What browser did you use to produce the bug.
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1018

There was a timing issue with channel dropdown, it is done. Load Items was working good.
Please test it and let me know.

Thank, Vero

**Comment by russdanner** [comment]
Confirmed
