### ISSUE TITLE
[studio-ui] remove history option on folders 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2712]
## Describe the bug
The history dialog does not currently work on folders. Access to it should be removed.
- don't show it in the context nav when a folder is selected
- don't show it in the right-click in the wcm-root or asset-root folders plugins for the side bar

## To Reproduce
N/A

## Expected behavior
History option should not be available for folders.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.0.19-SNAPSHOT-a24189
Build Number: a24189bd9699e07bcadd3788ca3eb03663a1539d
Build Date/Time: 11-30-2018 12:51:27 -0500

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1027

**Comment by russdanner** [comment]
Confirmed
