### ISSUE TITLE
[studio] Cluster is not adding members

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2716]
## Describe the bug
The cluster is not adding members correctly. 

## To Reproduce
1. Setup a mariadb in node a, modify studio-config-override.yaml using basic auth for cluster and `gradlew -Penv=authoring start`
2. Modify studio-config-override.yaml with the db in node a, using basic auth for cluster and `gradlew -Penv=authoring start`
3. Check Catalina logs in both nodes, everything seems fine during startup
4. Access studio in both nodes and go to cluster

## Expected behavior
Cluster members should be there

## Logs
node a startup https://gist.github.com/yacdaniel/e9a8397303eeaa23bacd592de4530501

### Version
Studio Version Number: 3.1.0-SNAPSHOT-718cbe

Build Number: 718cbec455c6ca96e990df4fa0d15eb222440623

Build Date/Time: 12-14-2018 09:08:38 -0600

### OS
Linux

### Browser
Chrome

## Additional context
In crafter db the cluster table has 0 rows.
Even with no cluster members listed I created a site in node a and node b started to show the following error: 
https://gist.github.com/yacdaniel/a8a621a228ceaa35c64421a8093796f7

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1404

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.0-SNAPSHOT-66576e
