### ISSUE TITLE
[docs] Update documentation on using ssh for authentication

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2717]
Update documentation on using ssh for authentication in **Site Creation with Remote Repositories**

There are various ways to connect to Studio using ssh.  It would be nice to expand on the different ways available.  

Also make a note that when you generate your keys, we require **rsa** for the public key algorithm.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/654
PR https://github.com/craftercms/docs/pull/655

**Comment by alhambrav** [comment]
Fixes for ticket: https://github.com/craftercms/craftercms/issues/2753
PR https://github.com/craftercms/docs/pull/656
PR https://github.com/craftercms/docs/pull/657

**Comment by russdanner** [comment]
Confirmed
