### ISSUE TITLE
[studio] Cluster- after creating a site in node a, node b does not sync.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2718]
## Describe the bug
Using a cluster with 2 nodes, the node in b is not able to sync the site created in node a

## To Reproduce
1. Set up and start the studio cluster with 2 members using 
    `studio.clustering.sandboxSyncJob.interval: 2000`
2. Create a site in node a
3. Go to Sites in node b

## Expected behavior
The site in node a should be created in node b afer the time defined in `studio.clustering.sandboxSyncJob.interval` 

## Logs
catalina log in node b https://gist.github.com/yacdaniel/80e87e4470383e49c9a47da23c11df7c

### Version
Studio Version Number: 3.1.0-SNAPSHOT-66576e
Build Number: 66576edfd691a4613d7c339f14e1426c2f1072b0
Build Date/Time: 12-17-2018 08:29:42 -0600

### OS
Linux

### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1406

**Comment by yacdaniel** [comment]
Verified fixed in  3.1.0-SNAPSHOT-c4c15c
