### ISSUE TITLE
[craftercms] Switch default search engine to ElasticSearch

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2725]
## Bundles & Gradle
- Bundles will include ES by default and will only start ES by default.
- Users that require Solr, must pass a flag to `crafter.sh` (or Gradle) to request launching Solr.
- A new flag will be added to not launch ES.

**Comment by sumerjabri** [comment]
Please validate @alhambrav

**Comment by alhambrav** [comment]
Verified.
