### ISSUE TITLE
[sdk-js] Switch to Engine search controller

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2726]
Switch the JS SDK to use Engine's search API as opposed to Crafter Search.

**Comment by jdrossl** [comment]
The new Search API will just take any JSON and return the ElasticSearch response without any changes, official docs for reference https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

**Comment by sumerjabri** [comment]
https://github.com/craftercms/craftercms/issues/2900
