### ISSUE TITLE
[docs] Document Elasticsearch integration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2729]
With Elasticsearch as the default search engine, we must reflect that in our documentation. We continue to support Solr, and must also continue to keep that documented and up to date, but find a good mechanism to document both, with Elasticsearch being the default/first and links to Solr.

New search architecture is:
![elasticsearch support](https://user-images.githubusercontent.com/3931908/50164050-b4f50680-02af-11e9-8b54-0c2d5e5ba9ca.png)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/718

**Comment by sumerjabri** [comment]
Verified.
