### ISSUE TITLE
Studio: Duplicate operation is broken when content-as-folder is set to false

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#273]
When a page has content-as-folder set to false and the user uses the Duplicate option the new item is displayed as .xml and the original file is missing.

Before Duplicate:
<img width="250" alt="screen shot 2016-11-14 at 9 44 50 am" src="https://cloud.githubusercontent.com/assets/1236955/20271068/1cbcc1ba-aa4f-11e6-8490-2d70e4e89cc1.png">

After Duplicate:
<img width="252" alt="screen shot 2016-11-14 at 9 45 08 am" src="https://cloud.githubusercontent.com/assets/1236955/20271069/1cc58e30-aa4f-11e6-99c2-be923a828fa0.png">

Repo Content:
![screen shot 2016-11-14 at 9 51 32 am](https://cloud.githubusercontent.com/assets/1236955/20271287/f5be411e-aa4f-11e6-97ca-2424db440827.png)

**Comment by dejan-brkic** [comment]
Duplicate issue
#298
