### ISSUE TITLE
[craftercms]  Error building, socket file path is too long

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2730]
## Describe the bug
Error building, socket file path is too long for MariaDb

## To Reproduce
1. Clone craftercms
2. ./gradlew init build deploy
3. ./gradlew start, watch the logs and notice the error as listed below

## Expected behavior
There should be no error when building

## Screenshots
N/A

## Logs

```
[ERROR] 2018-12-18 10:33:57,123 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld: 2018-12-18 10:33:57 140735524565888 [ERROR] The socket file path is too long (> 103): /Users/vita/temp/test5/craftercms/crafter-authoring/bin/apache-tomcat/temp/MariaDB4j.33306.sock
[ERROR] 2018-12-18 10:33:57,123 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld: 2018-12-18 10:33:57 140735524565888 [ERROR] Aborting
[INFO] 2018-12-18 10:33:57,123 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld:
```

### Version
Develop branch

### OS
OS X

### Browser
N/A.

## Additional context
N/A

**Comment by avasquez614** [comment]
@dejan-brkic this is my fault, I changed the MariaDB socket file to be on Tomcat's temp directory. Can you change it back to `/tmp` like before? Thanks

**Comment by alhambrav** [comment]
Verified fixed.
