### ISSUE TITLE
[studio] Error when inserting a record in audit table if user tries to sign in with empty username

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2732]
## Describe the bug
If a user tries to sign in without a username studio fails to save the record in the audit table

## To Reproduce
1. Start authoring and go to Sign In page
2. Add a password and kept the username empty
3. Click sign in
4. Check Catalina log

## Expected behavior
Audit table has the row with the attempt of Sign In with no username and no traceback/error in logs

## Logs
https://gist.github.com/yacdaniel/8a5791fb6b9da90dd2651c735a8d5508

### Version
Studio Version Number: 3.1.0-SNAPSHOT-c4c15c
Build Number: c4c15cfee4ff7091bd5dcc346b08a1bdf2aa170c
Build Date/Time: 12-18-2018 15:17:46 -0600

### OS
Linux

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1413

**Comment by yacdaniel** [comment]
Verified fixed in  3.1.0-SNAPSHOT-eaa094
