### ISSUE TITLE
[studio] Error in authoring log: Failed to load value for key studio.clustering.node.registration

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2733]
## Describe the bug
Error in the log after authoring has started:  `Failed to load value for key studio.clustering.node.registration
`
## To Reproduce
1. Clone develop branch then `gradlew init build deploy`
2. Start authoring and check Catalina log when the startup is complete.

## Expected behavior
There should be no errors after authoring has completed the startup

## Logs

>[ERROR] 2018-12-18 22:33:32,411 [studioSchedulerFactoryBean_Worker-3] [util.StudioConfigurationImpl] | Failed to load value for key studio.clustering.node.registration
[ERROR] 2018-12-18 22:33:37,411 [studioSchedulerFactoryBean_Worker-6] [util.StudioConfigurationImpl] | Failed to load value for key studio.clustering.node.registration
[ERROR] 2018-12-18 22:33:42,411 [studioSchedulerFactoryBean_Worker-7] [util.StudioConfigurationImpl] | Failed to load value for key studio.clustering.node.registration
[ERROR] 2018-12-18 22:33:42,411 [studioSchedulerFactoryBean_Worker-9] [util.StudioConfigurationImpl] | Failed to load value for key studio.clustering.node.registration

### Version
Studio Version Number: 3.1.0-SNAPSHOT-c4c15c
Build Number: c4c15cfee4ff7091bd5dcc346b08a1bdf2aa170c
Build Date/Time: 12-18-2018 16:01:02 -0600

### OS
Any

### Browser
Any

## Additional context
Cluster is not configured. No modifications were made to `studio-config-override.yaml`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1407

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.0-SNAPSHOT-959310
