### ISSUE TITLE
[studio] Enable override format for all commit message types

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2734]
## Describe the bug
Some commit message formats are not overridable.  
This creates an issue for organizations that have rules about git message format/structure 

Example:
https://github.com/craftercms/studio/blob/fb660a20fad545c5303fec085b36640ea3518a4b/src/main/java/org/craftercms/studio/impl/v1/repository/git/GitContentRepository.java
Line: 340
```
commitId = helper.commitFile(repo, site, emptyFilePath.toString(), "Created folder site: " +
                    site + " path: " + path + FILE_SEPARATOR + name, helper.getCurrentUserIdent());
```

Line: 368
```                
commitId = helper.commitFile(repo, site, pathToCommit, "Delete file " + path,
                        StringUtils.isEmpty(approver) ? helper.getCurrentUserIdent() : helper.getAuthorIdent(approver));
```
Line:476
```
 .setMessage("Moving " + fromPath + " to " + toPath + (StringUtils.isNotEmpty(newName) ?
                                    newName: StringUtils.EMPTY))
```

Line:518
```
.setCommitter(helper.getCurrentUserIdent())
.setMessage("Copying " + fromPath + " to " + toPath)```
```

Line: 909
```
git.commit().setMessage(INITIAL_COMMIT).call();
```

## To Reproduce
N/A

## Expected behavior
Examples are not an exhaustive list of commit operations and associated messages in GitLog.  All operations that create a commit should use a configurable message format.

## Screenshots
N/A

## Logs
N/A

### Version
Software version if applicable (copy paste from Help > About).
Studio Version Number: 3.0.19-SNAPSHOT-4b2e16
Build Number: 4b2e16844382f4ea8055f9585790c5ee49253202
Build Date/Time: 12-14-2018 13:10:06 -0500

### OS
What OS did you use to produce the bug.
All

### Browser
All

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1408

**Comment by dejan-brkic** [comment]
3.0.x
PR:
https://github.com/craftercms/studio/pull/1409

**Comment by russdanner** [comment]
Confirmed.

It would be nice if these were organized together without interruption and put under a single heading in the YAML file.

This cleanup Cron is just kinda hanging out in the middle of the other messages which makes me wonder if I got them all or if there are others I need to go digging for.

```
# The cron expression used on scheduled cleanup of repositories
studio.repo.cleanup.cron: '0 0 3 ? * SUN'
```

```
# Sandbox repository write commit message
studio.repo.sandbox.write.commitMessage: "User {username} wrote content {path}"
# Published repository commit message
studio.repo.published.commitMessage: "Publish event triggered by {username} on {datetime} via {source}.\n\nPublish note from user: \"{message}\"\n\nCommit ID: {commit_id}\n\nPackage ID: {package_id}"
# The cron expression used on scheduled cleanup of repositories
studio.repo.cleanup.cron: '0 0 3 ? * SUN'
# Create new repository commit message
studio.repo.createRepository.commitMessage: "Create new repository."
# Create sandbox branch commit message
studio.repo.createSandboxBranch.commitMessage: "Create {sandbox} branch."
# Initial commit message
studio.repo.initialCommit.commitMessage: "Initial commit."
# Blueprints updated commit message
studio.repo.blueprintsUpdated.commitMessage: "Blueprints updated."
# Create folder commit message
studio.repo.createFolder.commitMessage: "Created folder site: {site} path: {path}"
# Delete content commit message
studio.repo.deleteContent.commitMessage: "Delete file {path}"
# Move content commit message
studio.repo.moveContent.commitMessage: "Moving {fromPath} to {toPath}"
# Copy content commit message
studio.repo.copyContent.commitMessage: "Copying {fromPath} to {toPath}"
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1422
https://github.com/craftercms/studio/pull/1423

**Comment by russdanner** [comment]
Confirmed
