### ISSUE TITLE
Crafter Studio - Page name not showing up on authoring form

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#274]
Authoring form suppose to show page name in the header of the authoring form, seems like a javascript issue, when using the content of the service response

Possible BUG in code =
Response XML does not exist, because `content` is a DOM object, so should be handled different, or maybe in other cases responseXML is defined but clearly when content already exists responseXML is not because the previous description
```
if (content.responseXML) {
    var internalNameArr = "";
    try{
        internalNameArr = content.responseXML.getElementsByTagName("internal-name");
        form.definition.pageName = (internalNameArr.length <= 0) ? "" :
            (YAHOO.env.ua.ie) ? internalNameArr[0].text :
                internalNameArr[0].textContent;
    } catch(err) {
        form.definition.pageName = "";
    }
} else {
    form.definition.pageName = "";
}
```
Page name is undefined when trying to render it
```
if (formDef.pageName) {
    $('.page-header h1 .name').text(formDef.pageName);
}              
```

**Comment by asotog** [comment]
code change https://github.com/craftercms/studio2-ui/pull/97

**Comment by asotog** [comment]
code change #https://github.com/craftercms/studio2-ui/pull/97

**Comment by russdanner** [comment]
Reviewed and merged pull request.

**Comment by russdanner** [comment]
Re-open for testing
