### ISSUE TITLE
[studio] Delete site in cluster must propagate

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2743]
When deleting a site in a cluster, the Studio receiving the request deletes the site from disk, but other cluster members don't.

Let's discuss options.

One idea:
- Mark site as deleted
- Delete site from disk if it's marked as deleted in DB during the sync cycle

Downside: can't re-create the site with the same name.

The reason to keep the DB entry with that site name is: consider an old node that has sync'd in the past being brought back into the cluster, it will have the site on disk, but not in DB and it won't know. Also consider the same example with the node coming back online with an old git repo but the same site id re-created.

One enhancement is to add a site_id that's a UUID instead of our site_id today, and having a site name. This implies sites can exist with the same name within one organization.

Much to discuss.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1442

**Comment by sumerjabri** [comment]
@yacdaniel to validate and then include in the test plan.

**Comment by yacdaniel** [comment]
@dejan-brkic I did the following:
1. create site in A
2. delete site in A
3. create site with the same site id in step 1.
I'm able to see the site in A, but not in B. Stacktrace from B: 
https://gist.github.com/yacdaniel/ee0e3769f099a1e6eef381f1cf341d35

**Comment by yacdaniel** [comment]
Verified fixed.
