### ISSUE TITLE
[craftercms] Delivery not supported by crafter.sh tomcat status

### ISSUE THREAD

**Issue by zac-poe** [craftercms/craftercms#2745]
## Describe the bug
The script crafter.sh provides `status` and `status_tomcat` options. However, these options are internally supported only by Studio, and not by delivery. This is inconsistent with the start/stop tomcat options which will start/stop the webserver for either studio or delivery.

## To Reproduce
1. Start a crafter delivery instance
2. Execute crafter.sh status, observe there is incomplete success output for uptime, status, and version
3. Execute crafter.sh status_tomcat, observe there is incomplete success output for uptime, status, and version

## Expected behavior
When `status` or `status_tomcat` is run for delivery, the webserver status is titled as "Studio" and it has no output for uptime, status, and version.

When the webserver is not running, output states that Crafter Studio is not running.

## Screenshots
Taken from a running delivery instance:

`$ /opt/crafter/bin/crafter.sh status_tomcat`
> \------------------------------------------------------------
> Crafter Studio status
> \------------------------------------------------------------
> PID
> 23123
> uptime:
> Status:
> Version:

### Version
Crafter 3.0.x

### OS
Linux & MacOS

**Comment by jdrossl** [comment]
@sumerjabri I'm not sure about the right solution for this issue, I would do this:
- replace `status_tomcat` with `status_engine` & `status_studio`
- make `status` skip `status_studio` & `status_mariadb` when the studio.war is not present

let me know what do you think

**Comment by sumerjabri** [comment]
Sounds good.
