### ISSUE TITLE
Studio Contextual Navigation doesn't reflect changes made to the configuration file

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#275]
The site has the following configuration for Contextual Nav:

------------------------------------------------------------------------------------------
<app-context-menu>
    <context>
        <name>default</name>
        <left>
            <menuItem>
                <item><modulehook>wcm_logo</modulehook></item>
                <item><modulehook>wcm_dropdown</modulehook></item>
                <item><modulehook>wcm_content</modulehook></item>
                <item><modulehook>admin_console</modulehook></item>
            </menuItem>
        </left>
        <right>
            <menuItem>
                <item><modulehook>ice_tools</modulehook></item>
                <item><modulehook>preview_tools</modulehook></item>
            </menuItem>
        </right>
        <modules>
            <module><moduleName>wcm_logo</moduleName><value>wcm_logo</value></module>
            <module><moduleName>wcm_dropdown</moduleName><value>wcm_dropdown</value></module>
            <module><moduleName>wcm_content</moduleName><value>wcm_content</value></module>
            <module><moduleName>admin_console</moduleName><value>admin_console</value></module>
            <module><moduleName>preview_tools</moduleName><value>preview_tools</value></module>
            <module><moduleName>ice_tools</moduleName><value>ice_tools</value></module>
        </modules>
    </context>
</app-context-menu>

------------------------------------------------------------------------------------------

However, Studio UI continues to display the search box and 'Logout' link in the navigation. 

<img width="1689" alt="screen shot 2016-11-14 at 2 49 42 pm" src="https://cloud.githubusercontent.com/assets/4325885/20280225/9e5a36e2-aa79-11e6-9754-ba7f485b5bb9.png">

Removing 'wcm_logo' also continued to display the logo in UI.

**Comment by russdanner** [comment]
I think this is a dupe...

**Comment by hlim** [comment]
found this: https://github.com/craftercms/craftercms/issues/69 but it's moved to backlog.

**Comment by russdanner** [comment]
Yep that's it.  We should kill one of these and if needed prioritize the ticket higher if it's a blocker for you.

**Comment by hlim** [comment]
I am ok with killing the old one, and keep this as major please.

**Comment by russdanner** [comment]
Bug, bug+critical or bug+blocker are the new categories. We'll mark it critical

**Comment by asotog** [comment]
going to check this one @jvega-crafter

**Comment by russdanner** [comment]
This still not working.  Moving it back to scheduled.

**Comment by asotog** [comment]
PR sent https://github.com/craftercms/studio2-ui/pull/107
