### ISSUE TITLE
[docs] Fix RSA key documentation in Site Creation with Remote Repositories

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2753]
In the `Site Creation with Remote Repositories` document (https://docs.craftercms.org/en/3.0/system-administrators/studio/create-site-with-link-to-remote-repo.html), there's a line that says:

`When a trust relationship has been established between your machine and the machine hosting your remote repo, you can set the authentication type to None.`

This is kind of confusing. What is a trust relationship and how do you get one? I think it might be better to indicate that if you put the key in the default RSA key path in the Crafter Studio server (`~/.ssh/id_rsa`), then you can use authentication None.

Also, there's another line that says: `Save the key using the default filename (id_rsa and id_rsa.pub)`. These names are not mandatory, with Studio any name public/private key name can be used, as long they're RSA. Only when you want to use authentication `None` is when you need to use the default `id_rsa` name.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/656
PR https://github.com/craftercms/docs/pull/657

**Comment by avasquez614** [comment]
@vita In line: `Set the authentication type to None in the Create Site screen, if you put the key in the default RSA key path in the Crafter Studio server (~/.ssh/id_rsa.pub)`, it should be `~/.ssh/id_rsa`. When authentication is None, the default private key `~/.ssh/id_rsa` should be in the Studio server and `~/.ssh/id_rsa.pub` in Github/GitLab/Bitbucket.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/670
PR https://github.com/craftercms/docs/pull/671
