### ISSUE TITLE
[studio-ui] Catalog Studio UI events, and list publishers and subscribers

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2756]
Per our conversation, please:
- Create a catalog of all events transmitted in the system
- Enumerate the publishers (emitters) of these events
- Enumerate the subscribers (listeners) of these events

This will help us move forward with an event bus async mechanics and prepare us to use WebSocket to the backend.

**Comment by rart** [comment]
Closing as agreed via 3.2 ticket review sheet.
