### ISSUE TITLE
[studio-ui] Refactor Create Site dialog

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2757]
Please refactor the Create Site dialog to be as shown in the attached design.
[Studio 3_ Create Site.pdf](https://github.com/craftercms/craftercms/files/2761762/Studio.3_.Create.Site.pdf)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1045

**Comment by avasquez614** [comment]
@yacdaniel please test and verify

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1047

**Comment by yacdaniel** [comment]
Tested and verified.
