### ISSUE TITLE
[studio] Update site creation & cluster sync logic

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2759]
Studio needs to be updated for the new search changes:

**Site Creation**
- Remove all code related to create/delete the search index (this will be handled by the deployer now #2724)
- Add in the db a new field for the site `search_engine`, the value will come from the UI (#2757) and it should be added to the create target call and be optional. This will default to `ElasticSearch`, and the other valid value is `CrafterSearch` which in turn will route to `Solr`

**Cluster Sync**
- When syncing a new site, the value of the new db field `search_engine` needs to be added to the create target call and the create search index call needs to be removed

This is needed to implement #2723

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1425

**Comment by dejan-brkic** [comment]
@sumerjabri This is already completed and it is waiting to be tested and closed

**Comment by jdrossl** [comment]
Works fine for a local instance, in clustering it is always using ElasticSearch.

Steps to reproduce:
- Create a cluster with two instances running Solr
- Create a site using the API:
```
.../studio/api/1/services/api/1/site/create.json
{
  "site_id" : "my-site",
  "description" : "My very first site!",
  "blueprint" : "empty",
  "search_engine": "CrafterSearch"
}
```
- The local node uses Solr as expected, but the remote node will create the index in ElasticSearch

Local node:
```
curl http://127.0.0.1:9201/_cat/indices
yellow open my-site-authoring PTiaWLJFS7S640d-gyoeqQ 5 1 9 0 76.9kb 76.9kb
```

Remote node:
```
curl http://127.0.0.1:9201/_cat/indices
yellow open my-site-authoring -I-FSYueRxiWDYBr1VVmpA 5 1 0 0 1.1kb 1.1kb
yellow open my-site           KbybTxZ0TOWYTPuN7x7UUw 5 1 0 0 1.1kb 1.1kb
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1460

**Comment by jdrossl** [comment]
Verified
