### ISSUE TITLE
[studio] Cluster: Member removal is not stopping sync

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2765]
## Describe the bug
When a cluster member is removed from the Cluster menu, the removed members still get updates, remote branch still present in the sandbox. 

## To Reproduce
1. Have two members in Cluster, with a site synced between them.
2. From the Cluster menu, remove the second node(node b).
3. Go to Studio in the remaining member of the cluster (node a), edit and save the site.
4. Note down the last commit id  (git log) in the node a sandbox for the site you previously edited
5. Wait the seconds defined in clustering.sandboxSyncJob.interval
6. Go to the site sandbox in the node b and check the last commit id(git log)
7.  Check commit id, is the same value as the commit id in node a. 

## Expected behavior
Node b shouldn't receive sandbox updates after is removed from the cluster.

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-11947d
Build Number: 11947d463b28ebdc6148ccc301ca990bfa09fa70
Build Date/Time: 12-31-2018 07:17:25 -0600

### OS
Any

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1426

**Comment by yacdaniel** [comment]
depends on https://github.com/craftercms/craftercms/issues/2811

**Comment by yacdaniel** [comment]
Verified fixed.
