### ISSUE TITLE
[studio] Invalid site dialog when creating site from remote

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2768]
## Describe the bug
A `"SITE" is an invalid site` is shown when `Creating a site based on a remote git repository`. There's no error stacktrace so the site seems to be created successfully from the logs

## To Reproduce
1. On site creation dialog, try `Create site based on remote git repository`  with `Remote Git Repository Token` authentication.

## Expected behavior
The site should be created and you should be redirected to it's preview. Instead, a `"SITE" is an invalid site`  popup appears, and logs show no error.

## Screenshots
![image](https://user-images.githubusercontent.com/1598884/50575143-acc7bb80-0dc5-11e9-9bf8-27fc70ea9f99.png)

**Comment by dejan-brkic** [comment]
Can not reproduce the issue

```
Studio Version Number: 3.0.19-SNAPSHOT-92f298

Build Number: 92f2983aa6aea62b115e0636a124abdfbd2f6b44
```

I can replicate either successful site creation or authentication failure with a different error message. Please provide a stack trace and detailed steps to reproduce including how the authentication token is generated

**Comment by avasquez614** [comment]
Sorry, this happened because I pulled a 3.1.x site in 3.0.x. Shouldn't Studio at least provide a stack trace or a popup error that indicates that you're trying to pull a new site into an old Studio? Or do you think this not a use case we will ever see? @dejan-brkic @sumerjabri

**Comment by avasquez614** [comment]
Closing. We already discussed on handling this through the site descriptor YAML.
