### ISSUE TITLE
[studio-ui] Error in logs when clicking on the search icon from the context nav

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2770]
## Describe the bug
There is an error in the tomcat log and errors when you do inspect on your browser, when you click on the search icon from the context nav

## To Reproduce
1. Create a site using any bp
2. Once your new site loads, right click on your chrome browser and select inspect
3. Click on the search icon on the context nav (top right of your browser)
![screen shot 2019-01-02 at 12 56 02 pm](https://user-images.githubusercontent.com/25483966/50604750-f54aac00-0e8d-11e9-8f07-46e02f4d3b7b.png)

4. Look at the Tomcat log and notice the error: `GET http://localhost:8080/studio//static-assets/themes/cstudioTheme/images/treeview-loading.gif failed
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.`

Look at your browser console and notice the errors there too
![screen shot 2019-01-02 at 12 41 51 pm](https://user-images.githubusercontent.com/25483966/50604300-7dc84d00-0e8c-11e9-9796-4526bc6f31d2.png)

## Expected behavior
There should be no errors in the logs or browser inspect when you click on the search icon

## Logs
**Tomcat Log**
https://gist.github.com/alhambrav/14b670a44637c24277fa74350c57cb42

**Browser Inspect**
```
Uncaught ReferenceError: $ is not defined
    at search?site=mysite&s=&includeAspects=cstudio-core%3ApageMetadata|cstudio-core%3AdocumentMetadata&selection=-1&mode=act&ipp=20&page=1&presearch=false&firstTime=true&searchId=b5aef9de-c8c4-2adc-01e2-8b7033f3e1a7:48
(anonymous) @ search?site=mysite&s=&includeAspects=cstudio-core%3ApageMetadata|cstudio-core%3AdocumentMetadata&selection=-1&mode=act&ipp=20&page=1&presearch=false&firstTime=true&searchId=b5aef9de-c8c4-2adc-01e2-8b7033f3e1a7:48
search?site=mysite&s=&includeAspects=cstudio-core%3ApageMetadata|cstudio-core%3AdocumentMetadata&selection=-1&mode=act&ipp=20&page=1&presearch=false&firstTime=true&searchId=b5aef9de-c8c4-2adc-01e2-8b7033f3e1a7:142 GET http://localhost:8080/studio/static-assets/components/cstudio-search/filters/javascript.js?version=50050ded778bc2f002e9ebf712d73567ea42ce05 net::ERR_ABORTED 404
search?site=mysite&s=&includeAspects=cstudio-core%3ApageMetadata|cstudio-core%3AdocumentMetadata&selection=-1&mode=act&ipp=20&page=1&presearch=false&firstTime=true&searchId=b5aef9de-c8c4-2adc-01e2-8b7033f3e1a7:144 GET http://localhost:8080/studio/static-assets/components/cstudio-search/filters/css.js?version=50050ded778bc2f002e9ebf712d73567ea42ce05 net::ERR_ABORTED 404

GET http://localhost:8080/studio/static-assets/components/cstudio-search/filters/javascript.js?version=50050ded778bc2f002e9ebf712d73567ea42ce05 net::ERR_ABORTED 404
```

### Version
Studio Version Number: 3.1.0-SNAPSHOT-11947d
Build Number: 11947d463b28ebdc6148ccc301ca990bfa09fa70
Build Date/Time: 01-02-2019 11:39:56 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
From the Tomcat log, the error said: `[ERROR] 2019-01-02 12:35:14,807 [http-nio-8080-exec-5] [impl.DefaultExceptionHandler] | GET http://localhost:8080/studio//static-assets/themes/cstudioTheme/images/treeview-loading.gif failed
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.`.  From a quick google search: https://stackoverflow.com/questions/48453980/spring-5-0-3-requestrejectedexception-the-request-was-rejected-because-the-url,  maybe try sending the GET request without the double slash before static-assets?

**Comment by alhambrav** [comment]
Hi @sumerjabri ! This issue is also in 3.0.x.  Here's the version where I'm seeing the same thing:

Studio Version Number: 3.0.19-SNAPSHOT-a86b67
Build Number: a86b67c5c8bb888f9cb1152b7728040df7e1fa43
Build Date/Time: 01-09-2019 14:42:35 -0500

I have tried a fresh clone of 3.1 today, 1/11/2019 and I didn't see the issue anymore when I click on the search icon.

Thanks.

**Comment by vestrada** [comment]
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1041

**Comment by vestrada** [comment]
3.1.x -> PR: https://github.com/craftercms/studio-ui/pull/1042

**Comment by alhambrav** [comment]
Verified fixed.
