### ISSUE TITLE
[studio] Error pushing to remote repo from Studio: No signature of method

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2771]
## Describe the bug
There's an error when pushing to remote repo from Studio: No signature of method

## To Reproduce
1. Create a site with a link to an upstream remote git repository
2. Edit a page in your site and save
3. Click on `Site Config` from the `Sidebar` then click on `Remote Repositories`
4. Click on the push icon (up arrow) next to the remote repo you want to push code to, an error dialog pops up with the following message:
![screen shot 2019-01-02 at 2 14 24 pm](https://user-images.githubusercontent.com/25483966/50608084-6ba0db80-0e99-11e9-8ac0-013598f32877.png)

```
No signature of method: javax.servlet.http.HttpServletResponseWrapper.setStatus() is applicable for argument types: (org.springframework.http.HttpStatus) values: [500] Possible solutions: setStatus(int), getStatus(), setStatus(int, java.lang.String)
```

## Expected behavior
User should be able to push to remote repo without errors

## Logs
https://gist.github.com/alhambrav/f52ed5e1133648639ab3fecb018ff1bf

### Version
Studio Version Number: 3.1.0-SNAPSHOT-11947d
Build Number: 11947d463b28ebdc6148ccc301ca990bfa09fa70
Build Date/Time: 01-02-2019 11:39:56 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Duplicate.
Already reported here:
https://github.com/craftercms/craftercms/issues/2740

**Comment by alhambrav** [comment]
Verified fixed.
