### ISSUE TITLE
[studio] Cannot create site using git repository token authentication with GitLab personal access token

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2772]
## Describe the bug
Cannot create site with link to remote repo when using git repository token authentication and a GitLab personal access token

## To Reproduce
1. Setup a personal access token in your GitLab account
2. In the Sites screen of Studio, Click on `Create Site`
3. Fill in the `Site Id` field then click on `Link to upstream remote Git repository`
4. Select `Remote Git Repository Token` for the authentication type and fill in the rest of the required information
5. Notice the message in the logs and the notification given in Studio
<img width="566" alt="screen shot 2019-01-03 at 7 07 19 am" src="https://user-images.githubusercontent.com/25483966/50637245-2cb96700-0f27-11e9-9188-6912c18a9fbe.png">

## Expected behavior
User should be able to create a site with link to a remote repository using a GitLab personal access token as authentication

## Logs
https://gist.github.com/alhambrav/4e0f8f94e4560726c00cbd8039f2a3b1

### Version
Studio Version Number: 3.1.0-SNAPSHOT-afe9af
Build Number: afe9affa15b6427165063b4be6ac190e7361b497
Build Date/Time: 01-03-2019 06:57:10 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
If you select `Basic` for the authentication type and enter your GitLab personal access token as the password, I am able to create a site.
I am able to clone from the command line using my GitLab personal access token: `git clone https://gitlab-ci-token:{mypersonalaccesstoken}@gitlab.com/user/repo5.git`
I am also able to create a site using my GitHub personal access token.

**Comment by alhambrav** [comment]
Here's an article I found that I'm not sure may be helpful? 
 It looks like JGit authentication is a little different depending on the provider used.  In the article, it used GitHub and GitLab as an example: https://www.codeaffine.com/2014/12/09/jgit-authentication/

**Comment by dejan-brkic** [comment]
@sumerjabri 
GitLab uses token instead of a password. It requires username also. To support access to GitLab using tokens, we will need to make username mandatory when using tokens. Currently, it is not mandatory (and add remote repo dialog has only token input).
Making this change, github will not be affected. It allows access both with username/token or just token.

**Comment by dokuboyejo** [comment]
Any update on the issue...currently facing the same

**Comment by sumerjabri** [comment]
@dokuboyejo we're not planning on tackling this in the near-term, the ticket remains scheduled for a future release.
