### ISSUE TITLE
[studio] Audit log for files created during create site logs the OS user instead of the Studio user who created the site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2773]
## Describe the bug
Audit log for files created during create site logs the OS user instead of the Studio user who created the site

## To Reproduce
1. Log in as user `admin`
2. Create a site
3. Go to `Site Config` and click on `Audit`.  Notice the `User` in the logs for the files created when the site was created is the OS user instead of `admin`

## Expected behavior
Audit log for create site should log the Studio user as the user who created the files when the site was created instead of the OS user

## Logs

```
User | Content | Type | Created | Modified
-- | -- | -- | -- | --
vita | /templates/web/navigation2/nav-macros.ftl | CREATED | 01-03-2019 09:40:56 am (EST5EDT) | 01-03-2019 09:40:56 am (EST5EDT)
vita | /templates/web/pages/article.ftl | CREATED | 01-03-2019 09:40:56 am (EST5EDT) | 01-03-2019 09:40:56 am (EST5EDT)
```

### Version
Studio Version Number: 3.1.0-SNAPSHOT-afe9af
Build Number: afe9affa15b6427165063b4be6ac190e7361b497
Build Date/Time: 01-03-2019 06:57:10 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by alhambrav** [comment]
Reopening the ticket.  I just noticed that there are still some files where the user logged is the OS user instead of the Studio user logged in when the files were created.

```
Studio Version Number: 3.1.0-SNAPSHOT-674b31
Build Number: 674b310566b8479651a0135b108608d17328a78c
Build Date/Time: 01-23-2019 14:05:16 -0500
```

![screen shot 2019-01-23 at 2 48 22 pm](https://user-images.githubusercontent.com/25483966/51632772-0ed79480-1f1e-11e9-8246-00fd2dd38663.png)

If you scroll through some more of the audit logs, there are files here and there with the file where the user logged is the OS user instead of the Studio user logged in when the files were created:

![screen shot 2019-01-23 at 2 48 10 pm](https://user-images.githubusercontent.com/25483966/51633040-bead0200-1f1e-11e9-95b4-bb409da4a36a.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1450

**Comment by alhambrav** [comment]
Hi!
There's still one file that does not list the Studio user as the user who created the file for all the sites I tried creating (`config/studio/studio_version.xml`):

![screen shot 2019-01-24 at 10 13 02 am](https://user-images.githubusercontent.com/25483966/51687583-d8068a80-1fc0-11e9-8725-b45cef9862ae.png)

**Studio Version Used:**
```
Studio Version Number: 3.1.0-SNAPSHOT-19f728
Build Number: 19f728d738e07d1ad33d343bf58adb2ef927cfdf
Build Date/Time: 01-24-2019 09:56:01 -0500
```

**Comment by dejan-brkic** [comment]
`studio_version.xml` is updated by Upgrade Manager. As shown on the screenshot, all other files are `CREATED`.

**Comment by alhambrav** [comment]
@sumerjabri  Please see previous comments.  Should we leave the file `config/studio/studio_version.xml` as updated by the OS user , or should we fix it to also log the Studio user as the one who performed the update?  Thank you.

**Comment by alhambrav** [comment]
I spoke with Sumer and we will leave that one file `config/studio/studio_version.xml` alone.  Closing the ticket now.
