### ISSUE TITLE
Cut and Pasted page items don't appear in the site content list

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#278]
Repo: Alfresco (with repoType= alfrescoext)
Content type with content-as-folder=false

Content 2 and 4 are the ones cut & pasted from another area while Content 5 was created directly into the folder. 

<img width="699" alt="screen shot 2016-11-15 at 1 29 09 pm" src="https://cloud.githubusercontent.com/assets/4325885/20318402/218b97a4-ab38-11e6-9b93-d9187476ff3c.png">

<img width="269" alt="screen shot 2016-11-15 at 1 29 06 pm" src="https://cloud.githubusercontent.com/assets/4325885/20318382/11f40222-ab38-11e6-8985-c1259fe3a133.png">

Alfresco has all 3 contents in the folder, however, Preview filesystem is missing content 2 and content 5.

**Comment by russdanner** [comment]
Only critical because it impacts a customer who still uses contentAsFolder=false

**Comment by dejan-brkic** [comment]
Pull request #395 and #396

**Comment by russdanner** [comment]
Im going to leave this one in test for the moment.

Merged

**Comment by hlim** [comment]
the fix confirmed
