### ISSUE TITLE
[studio-ui] Site Dashboard  List of items to show is not being updated when input value changes.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2780]
## Describe the bug
The list of items to show in Site Dashboard is not being updated when the input value changes.
## To Reproduce
1. Create a site with Editorial BP
2. Go to the site and made a few changes(~3) and then approve some of them. 
3. Go to the Site Dashboard
4. Change the show input value in Recently Published and My Recent Activity to 1.
5. Check list in both sections

## Expected behavior
List of items is updated with the number in the Show input box.

## Screenshots
https://www.useloom.com/share/066ec1ddf82148dfa3d667f756cc340f

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.0.19-SNAPSHOT-dfceab
Build Number: dfceab7fa75166ef1ad8bb92537e8e0863f3b64d
Build Date/Time: 01-07-2019 11:25:48 -0600

Studio Version Number: 3.1.0-SNAPSHOT-0070fd
Build Number: 0070fd807cfe43daf2941625fcc83908c20fca3c
Build Date/Time: 01-07-2019 08:58:06 -0600

### OS
Linux, Mac

### Browser
Chrome

## Additional context
If you create/edit content from the Site Dashboard, after saving the content, the number of items to show is updated.

**Comment by vestrada** [comment]
3.1.x -> PR: https://github.com/craftercms/studio-ui/pull/1037
3.0.x -> PR: https://github.com/craftercms/studio-ui/pull/1038

I added blur event.

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.x and 3.0.x.
