### ISSUE TITLE
[docs] Add docs for Linux requiring libncurses5 for restoring a backup

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2784]
## Describe the bug
Restoring a backup requires libncurses5 to complete successfully. The restore process finish without errors nor warnings. The content in `crafter-authoring/data` is restored succesfully but the `crafter` database is not restored at all.

## To Reproduce
1. Create a backup
2. Restore the backup in a Linux system without ncurses5 installed
3. Start studio

## Expected behavior
Restore successful 

## Screenshots
N/A

## Logs
Without ncurses the restore output is:
```
Restoring DB
------------------------------------------------------------------------
/home/yacdaniel/craftercms30/crafter-authoring/bin/dbms/bin/mysql: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
------------------------------------------------------------------------
Stopping DB
```
With ncurses installed the restore output is:
```
Restoring DB
------------------------------------------------------------------------
2019-01-09 20:29:57.103  INFO 26558 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-01-09 20:29:57 7fd0ffcb1b00 [Info] InnoDB: the file format in the system tablespace is now set to Barracuda.
------------------------------------------------------------------------
Stopping DB
```

### Version
Studio Version Number: 3.0.19-SNAPSHOT-44919d
Build Number: 44919db3d34386424000b0b57650a262622c5666
Build Date/Time: 01-08-2019 00:53:01 -0600

### OS
Linux

### Browser
N/A

## Additional context
Not completely sure but looks like macOS comes with ncurses installed.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/665, commit https://github.com/craftercms/docs/pull/665/commits/d10b304e2ec31354663dab11bda1ff857dcb8aaf
PR https://github.com/craftercms/docs/pull/666

**Comment by yacdaniel** [comment]
Verified fixed.
