### ISSUE TITLE
Custom option doesn't work in Publishing Channel when 'Web' is the only option configured

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#279]
Updated Publishing Channel configuration as below: 

<img width="1078" alt="screen shot 2016-11-15 at 1 58 04 pm" src="https://cloud.githubusercontent.com/assets/4325885/20319439/16590246-ab3c-11e6-821b-b542473e4587.png">

However, the UI doesn't display 'Web' option any more and entering custom width and height doesn't change anything in Preview.

<img width="275" alt="screen shot 2016-11-15 at 2 01 22 pm" src="https://cloud.githubusercontent.com/assets/4325885/20319453/256c619c-ab3c-11e6-935a-8c5705c227d0.png">
<img width="280" alt="screen shot 2016-11-15 at 2 01 30 pm" src="https://cloud.githubusercontent.com/assets/4325885/20319457/2b362da6-ab3c-11e6-96f1-1e2c93bb9813.png">

**Comment by asotog** [comment]
will be checking this
