### ISSUE TITLE
[craftercms] Shell scripts are not updated with ./gradlew clean build deploy -Penv=authoring command

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2790]
## Describe the bug
Updating code after ES feature added, ES does not start causing create site to fail 

## To Reproduce
1. edit shell script in 'craftercms' project
2. run `./gradlew clean build deploy -Penv=authoring`
3. script inside `crafter-authoring` is not updated

## Expected behavior
`./gradlew clean build deploy -Penv=authoring` updates binaries and shell scripts

## Logs
https://gist.github.com/dejan-brkic/09d00a4896e2f3f7c8d3e6bd9f1e9cfd

### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-de6e2e

Build Number: de6e2e13056e3f6eec774d76d4454c74a7550ba6
```

### OS
Mac OS X, Ubuntu linux

### Browser
What browser did you use to produce the bug.

**Comment by sumerjabri** [comment]
@dejan-brkic did you do:
`./gradlew selfupdate` before anything else?

**Comment by dejan-brkic** [comment]
I guess it can be reproduced in 3.0.x also. It is not related to ES itself.

**Comment by jdrossl** [comment]
@dejan-brkic did you try with `./gradlew upgrade`? I think `deploy` will have issues if the `crafter-authoring` folder already exists and it will only upgrade the war files

**Comment by dejan-brkic** [comment]
Sorry typo in steps:
```
1. pull from community (all projects)
2. `./gradlew selfupdate`
3. `./gradlew clean upgrade`
4. `./gradlew clean build deploy -Penv=authoring`
5. `./gradlew start -Penv=authoring 
```

**Comment by jdrossl** [comment]
@sumerjabri I'm not able to reproduce this issue, I also asked Vita to help me test and it works as expected for her too. This is how I'm testing it:
```
git clone -b develop https://github.com/craftercms/craftercms.git
cd craftercms
git checkout 05345adadff826abbcde6348a9ddea52e429a636 (go back to a commit before the merge of ES)
cat resources/crafter/crafter.sh | grep Elastic (should not return anything)
./gradlew init build deploy -Penv=authoring (generate crafter-authoring without ES support)
git checkout develop  
cat resources/crafter/crafter.sh | grep Elastic (should return a lot of matches)
./gradlew upgrade -Penv=authoring (update crafter-authoring with ES support)
ls crafter-authoring/bin (there should be a folder named elasticsearch)
cat crafter-authoring/bin/crafter.sh | grep Elastic (should return a lot of matches)
```

**Comment by sumerjabri** [comment]
Can't reproduce.
