### ISSUE TITLE
[studio-ui] Add an attribute to controls that use remote datasources

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2791]
Please update the image & video datasources & controls to add an attribute in the descriptor XML to indicate if the selected file is remote (s3, box or cmis)

Example:
An image picker that uses an s3 datasource should look like this: `<hero_image remote="true">/remote-assets/s3/s3-default/DtfqoT3XcAAFccG.jpg</hero_image>`

Local datasources can remain unchanged or set the attribute to `remote="false"`

This is required to complete https://github.com/craftercms/craftercms/issues/2723

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1043

**Comment by jdrossl** [comment]
Verified
