### ISSUE TITLE
[craftercms] Refactor backups to be Groovy scripts

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2793]
Right now, mantaining the backup/restore functions in `crafter.sh` and `crafter.bat` is really difficult because of all the differences between Unix bash and Windows bat languages. Please refactor this functionality to be Groovy scripts so it is easier to mantain.

**Comment by sumerjabri** [comment]
We will support Windows via Docker and therefore these issues are no longer relevant.
