### ISSUE TITLE
[studio-ui] Design approach to flatten storage of item specific content objects

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2795]
**Is your feature request related to a problem? Please describe.**
Item-specific content objects associated by the form engine and drag and drop should be flattened and stored into their parent object (rather than being stored as an externally referenced object.)  

The approach should nest as deep as is necessary.
Example: 
```
A page has a section component 
  +which has row components 
     +which has a column layout component
          + which has components in each column.
```

Today Item specific content is associated/linked via two mechanisms in the UI:
- The form engine via Item Selector + Child Content Data Source
- Drag and drop in the preview

This feature will simplify versioning, publishing, delete, copy/duplicate, move operations and indexing.  It will also make on-disk operations.

**Comment by sumerjabri** [comment]
Done, resulting tickets:
https://github.com/craftercms/craftercms/issues/2884
https://github.com/craftercms/craftercms/issues/2885

**Comment by sumerjabri** [comment]
Completed
