### ISSUE TITLE
[studio] Files created for a new site is not logged in the audit logs all the time

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2798]
## Describe the bug
Files created for a new site is not logged in the audit logs all the time.  It's not consistent when you create a site when the files created for the site is logged in audit or not.... (I create site1, I see no audit logs for the files created on site creation, just an entry for the create_site.  I then create site 2, I see the files created for the site in the audit logs, I create site 3, I see no logs, I create site 4, I see no logs, so on and so forth... I couldn't see if maybe there's a pattern on when it creates a log for all the files created.)

## To Reproduce
1. Create a site using any bp
2. Open the `Sidebar` and click on `Site Config` then `Audit`
3. Notice the logs if it lists files when the site was created or not
4. Go back to the main menu
5. Repeat steps 1-4 a few times
6. You can also check the audit logs in the database, here's an example (Notice for site `store2`, the files created during site creation is logged and for site `hello2`, there's none):
```
| 425 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/static-assets/images/products/toy-plane.jpeg"}                                                            | json           | /static-assets/images/products/toy-plane.jpeg                                        | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 426 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/static-assets/js/crafter-support-1-0-0.js"}                                                               | json           | /static-assets/js/crafter-support-1-0-0.js                                           | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 427 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/static-assets/js/jquery.core.js"}                                                                         | json           | /static-assets/js/jquery.core.js                                                     | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 428 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/templates/system/common/craftercms-common.ftl"}                                                           | json           | /templates/system/common/craftercms-common.ftl                                       | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 429 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/templates/system/common/craftercms-geo-lib.ftl"}                                                          | json           | /templates/system/common/craftercms-geo-lib.ftl                                      | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 430 | 2019-01-22 11:32:19 | 2019-01-22 11:32:19 | {"user":"admin admin","id":"/templates/web/catalog.ftl"}                                                                               | json           | /templates/web/catalog.ftl                                                           | store2       | CREATED       | page         | admin admin  | REPOSITORY |
| 431 | 2019-01-22 11:32:44 | 2019-01-22 11:32:44 | {"user":"admin","id":"hello2","contentType":"site"}                                                                                    | json           | hello2                                                                               | studio_root  | CREATE_SITE   | site         | admin        | API        |
```

## Expected behavior
The audit log should be consistent.  If we are going to log files created during site creation, it should be logged each and every time a site is created.

## Screenshots
I have 2 screenshots of the audit logs for 2 sites and notice one has a log of the files created when the site was created and the other one does not

**Files created during site creation are logged:**
![screen shot 2019-01-22 at 12 11 00 pm](https://user-images.githubusercontent.com/25483966/51552603-f2b0f600-1e3e-11e9-84d7-097ac05e1cc1.png)

**No log of files created during site creation:**
![screen shot 2019-01-22 at 12 10 39 pm](https://user-images.githubusercontent.com/25483966/51552666-1411e200-1e3f-11e9-8095-8c9e9f1f7ea4.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-f21f07
Build Number: f21f07ab3d1f4d40ed5ba949bacb22a02b340f73
Build Date/Time: 01-22-2019 11:16:37 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1448

**Comment by alhambrav** [comment]
Verified fixed.
