### ISSUE TITLE
[all] Upgrade Jackson Databind to 2.9.8

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2799]
Upgrade to com.fasterxml.jackson.core:jackson-databind@2.9.8.

**Comment by dejan-brkic** [comment]
3.1:
https://github.com/craftercms/engine/pull/234
https://github.com/craftercms/social/pull/342
https://github.com/craftercms/test-suite/pull/403

**Comment by dejan-brkic** [comment]
3.0:
https://github.com/craftercms/test-suite/pull/404
https://github.com/craftercms/social/pull/343
