### ISSUE TITLE
CRAFTERCMS-1517: Shouldn't preview a content when a content is not previewable

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#28]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: 1) Create or edit a content type
2) Go to the content type's configuration folder and update config.xml
3) Change <previewable>true</previewable> to false
4) Save the change
5) Go to the site dropdown and click any content of the content type

The content shouldn't display preview:
----------
Original JIRA Comments:
Hi,

I worked on the UI part, All items that come from backend as no previewable aren't clickable (to see the preview). However for some reason when I follow the steps described in the ticket description, I'm not seem the config.xml changes in the backend.

Dejan Can you check this.

Thank, Vero
----------
non-previewable contents are still clickable. 
----------
talk to me before doing this ticket.

I think we can make components previewable.  So more stuff is previewable
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1517
----------

**Comment by vestrada** [comment]
Per Conversation con dejan.  This issue is about item cache. 
If you restart tomcat you will see the changes reflected on the item. 
This will be fix on back end.
