### ISSUE TITLE
The Datetime control still shows the required mark when a value is pre-populated

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#280]
1) Create a datetime control field with the following settings:

<img width="518" alt="screen shot 2016-11-16 at 11 39 50 am" src="https://cloud.githubusercontent.com/assets/4325885/20356092/817ee1d4-abf1-11e6-836e-65566e589f1b.png">

2) Open the form to create a new content
<img width="346" alt="screen shot 2016-11-16 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/4325885/20356121/95196b38-abf1-11e6-833a-03c190eedaba.png">

it should not show the required mark since the value is pre-populated.

**Comment by russdanner** [comment]
This bug has returned... donno why but it keeps resurfacing.

**Comment by asotog** [comment]
will check this one, already reproduced it on clean instance

**Comment by asotog** [comment]
PR sent https://github.com/craftercms/studio2-ui/pull/108
