### ISSUE TITLE
elasticsearch does not start correctly in windows.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2802]
## Describe the bug
ElasticSeach fails to starts, sites cannot be created. 

## To Reproduce
1. Clone develop branch
2. `gradlew.bat -Penv=authoring init build deploy`
3. `gradlew.bat -Penv=authoring start`
4.  Create a site in studio

## Expected behavior
ElasticSearch starts correctly and sites can be created without errors.

## Logs
https://gist.github.com/yacdaniel/f593ba32daa5cbdf4dd29cbe754517af

### Version
Develop 3.1

### OS
Windows

### Browser
Any

**Comment by sumerjabri** [comment]
We won't be directly supporting Windows starting 3.1. Instead, Windows installs will run via Docker.
