### ISSUE TITLE
[studio-ui] RTE v2 does not work

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2803]
## Describe the bug
Changed RTE control to use configuration for RTE v2 (`rteTinyMCE4`)

## To Reproduce
1. Create site from editorial blueprint
2. Click on Site Config from Sidebar menu
3. Click on Content Types from Sidebar
4. Click on Open Existing action from toolbar
5. Select Home page content type
6. Edit all RTE controls and set `rteTinyMCE4` as configuration
7. Save content type
8. Go to the site dashboard
9. Edit home page
10. Error: Edit form spinner spins forever

## Expected behavior
Edit form loads normally for RTE v2

## Screenshots
![error_sh](https://user-images.githubusercontent.com/4053827/51758602-5b5dd400-20c6-11e9-92b2-d275faab1d61.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Software version if applicable (copy paste from Help > About).

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1044
studio: https://github.com/craftercms/studio/pull/1456

**Comment by dejan-brkic** [comment]
Verified
