### ISSUE TITLE
[studio-ui] child-content data source should allow user to decide if add or browse options are enabled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2808]
**Is your feature request related to a problem? Please describe.**
A user configuring a content type and using the child-content data source should be able to determine if the user should be able to create a new item, browse for an existing item or both.  Currently, the data source assumes both options are always enabled.

**Describe the solution you'd like**
Add a boolean property (defaulted true): Enable Create New 
Add a boolean property (defaulted true): Enable Browse Existing
 
**Describe alternatives you've considered**
Currently, the user must supply paths for the repository and a browse path.  I considered using the absence of value in these properties as an indication of the behavior.  This would break existing users.  Further, a toggle allows the administrator to temporarily disable a behavior without removing the configuration.

**Additional context**
<img width="1309" alt="screen shot 2019-01-28 at 2 04 22 pm" src="https://user-images.githubusercontent.com/169432/51859689-bf221000-2305-11e9-90a2-500d15867cab.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1161

**Comment by russdanner** [comment]
Confirmed. 
But if there is only one data source option available (add or browse) the user should not need to click add then click the option.  Click add should go right to the configured action.

**Comment by russdanner** [comment]
CONFIRMED
