### ISSUE TITLE
[studio-ui] Make CMIS datasources consistent with WebDav and S3 datasource

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2812]
**Is your feature request related to a problem? Please describe.**
WebDav and S3 have datasources for uploading and for browsing, for files, images and videos, but for CMIS, we don't have a datasource for uploading.  It would be nice to make CMIS datasources consistent with S3 and WebDav

**Describe the solution you'd like**
Make CMIS datasources consistent with WebDav and S3 datasource, so we'd have something like the following for CMIS:
* File from CMIS Repository
* Image from CMIS Repository
* Video from CMIS Repository
* File Uploaded to CMIS Repository
* Image Uploaded to CMIS Repository
* Video Uploaded to CMIS Repository

**Describe alternatives you've considered**

**Additional context**

**Version**
Studio Version Number: 3.1.0-SNAPSHOT-19f728
Build Number: 19f728d738e07d1ad33d343bf58adb2ef927cfdf
Build Date/Time: 01-24-2019 09:56:01 -0500

**Comment by vestrada** [comment]
Waiting for: https://github.com/craftercms/craftercms/issues/2863

**Comment by vestrada** [comment]
PR 3.1 -> https://github.com/craftercms/studio-ui/pull/1153

**Comment by vestrada** [comment]
studio -> 3.1 : https://github.com/craftercms/studio/pull/1587

**Comment by vestrada** [comment]
studio -> 3.0: https://github.com/craftercms/studio/pull/1588

**Comment by vestrada** [comment]
VC: https://github.com/craftercms/video-center-blueprint/pull/33

**Comment by vestrada** [comment]
Hi Dejan,

I'm getting `Unauthorized ` error from the api.
Please check it.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1596

**Comment by alhambrav** [comment]
Verified.
