### ISSUE TITLE
[studio-ui] Refactor Studio search page

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2815]
Please refactor the Studio search page to match the attached design: 
[Studio 3_ Search Results Page.pdf](https://github.com/craftercms/craftercms/files/2813651/Studio.3_.Search.Results.Page.pdf). Sync with @jdrossl to understand how to use the new search API.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1065

**Comment by avasquez614** [comment]
Verified
