### ISSUE TITLE
[docs] Clarify context root and application in REST API Docs

### ISSUE THREAD

**Issue by zac-poe** [craftercms/craftercms#2816]
**Is your feature request related to a problem? Please describe.**
Although context roots are available in the Crafter manual REST API docs (#2310), they are easy to miss on the root pages, especially for new users who may be browsing through the endpoints. Additionally, it is difficult for new users to know which applications (and therefore which ports) some of the APIs belong to.

**Describe the solution you'd like**
If the individual REST APIs for the services referenced a context root, potentially in the `Resource Information` section, they could simply link back to the root page for each API service which does contain the respective context root information.

For example, have https://docs.craftercms.org/en/3.0/developers/projects/studio/api/user-management/get-user.html reference a context root as a link back to https://docs.craftercms.org/en/3.0/developers/projects/studio/api/index.html#crafter-studio-api where that value is clear to the user.

Additionally, these pages should clarify to which application the service belonged, and therefore which ports should be referenced.

For example, https://docs.craftercms.org/en/3.0/developers/projects/deployer/api/target-management/deploy-target.html could reference the host application as a link to the parent page https://docs.craftercms.org/en/3.0/developers/projects/deployer/index.html#crafter-deployer where additional text or diagram linking could be added highlighting that this is a separate application from the tomcat Crafter CMS webserver and reference that it can be accessed through ports defined on https://docs.craftercms.org/en/3.0/developers/projects/craftercms/index.html#authoring-default-ports

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/688 and https://github.com/craftercms/docs/pull/687

**Comment by sumerjabri** [comment]
@zac-poe looksee if we addressed in the latest docs. If so, please close, otherwise assign to me with what's missing/wrong.

**Comment by zac-poe** [comment]
looks great, thanks!
