### ISSUE TITLE
Host Header Poisoning can allow JavaScript execution (XSS)

### ISSUE THREAD

**Issue by Jeffsecblog** [craftercms/craftercms#2817]
## Describe the bug
Host Header poisoning allows for XSS or Javascript Injection. 

## To Reproduce
1. Go to '/studio'
2. intercept the request via a proxy such as Burp or Zap. 
3. Change the **host** header and forward the request.
  3.1. The following was submitted in place of the header *" };alert(document.cookie);{var ketchup="*
4. await the execution of your JavaScript. 

## Expected behavior
application should sanitize the provided **host** header to prevent the acceptance of Javascript code. 

 

### Original Request
![Original request](https://user-images.githubusercontent.com/25588587/52148835-89946400-2630-11e9-97bd-90390d46febf.PNG)
### Edited Request
![Edited reqeust](https://user-images.githubusercontent.com/25588587/52148851-93b66280-2630-11e9-9373-2f70268eba36.PNG)
### Poisoned Response
![poisoned-response](https://user-images.githubusercontent.com/25588587/52148865-9fa22480-2630-11e9-826e-bde0b78bcc13.PNG)
### Script Execution
![XSS execution](https://user-images.githubusercontent.com/25588587/52148243-adef4100-262e-11e9-8293-62f3167ae620.PNG)

### Version
Software version if applicable (copy paste from Help > About).
3.0.20
### OS
What OS did you use to produce the bug.
RedHat Enterprise Linux 7
### Browser
What browser did you use to produce the bug.
Firefox
## Additional context
I stood up a server in AWS and installed a default instance of Crafter CMS to reproduce the bug found. 

I used the developer console in Firefox to massage the code until i could get executable JS code.

**Comment by avasquez614** [comment]
@dejan-brkic work with @jvega190 or @vestrada if you need help

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1471

**Comment by dejan-brkic** [comment]
3.0.x
PR:
https://github.com/craftercms/studio/pull/1472

**Comment by yacdaniel** [comment]
Verified fixed in 3.0.x and 3.1, host is sanitized and JavaScript is not executed.
