### ISSUE TITLE
[studio] stacktrace in cluster member a logs when site is created in cluster member b

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2818]
## Describe the bug
Site created in `cluster member a`, is able to sync site to `cluster member b`, but a stactrace is shown in `cluster member b` logs, also a message with ERROR level in `cluster member a` is preset. 
This errors in logs doesn't happen al the time. 

## To Reproduce
1. Have 2 authoring cluster to add as cluster members. Set MariaDB server in `cluster member a`. I'm using cluster basic auth.
2. Create a site in `cluster member a`
3. Check catalina log in both members

## Expected behavior
No errors in log

## Logs
[cluster member a](https://gist.github.com/yacdaniel/728ebab472c97645506489b8842b71ce)
[cluster member b](https://gist.github.com/yacdaniel/54c8e78f2b6d046db2ce5373f15c0dac)

### Version
Studio Version Number: 3.1.0-SNAPSHOT-82b409
Build Number: 82b409100f4d20eb951493764a44c020ecd9119b
Build Date/Time: 02-01-2019 13:09:07 -0600

### OS
Linux

### Browser
What browser did you use to produce the bug.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1477

**Comment by yacdaniel** [comment]
Verified fixed.
