### ISSUE TITLE
[craftercms] deployer can't create target NumberFormatException: For input string: "mail.port"

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2827]
## Describe the bug
Deployer is not able to create a target

## To Reproduce
1. Clone develop branch
2. `./gradlew init build deploy start`
3. Go to studio and create a site

## Expected behavior
Site created without problems

## Logs
https://gist.github.com/yacdaniel/b57ea080e30abe20234b26f2c9d976bf

### Version
Studio Version Number: 3.1.0-SNAPSHOT-fb3974
Build Number: fb39743dbff5ef0d2fa66fc989025997344efe0d
Build Date/Time: 02-05-2019 10:58:21 -0600

### OS
Linux

### Browser
What browser did you use to produce the bug.

**Comment by avasquez614** [comment]
@yacdaniel I was missing a PR from being merged, please verify the error is not happening again

**Comment by yacdaniel** [comment]
Verified fixed.
