### ISSUE TITLE
[docs] Add Elasticsearch detailed guides

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2830]
The following guides need an Elasticsearch counterpart:
* https://docs.craftercms.org/en/3.0/system-administrators/activities/debugging-search.html

**Comment by avasquez614** [comment]
@alhambrav work with @jdrossl if you need help

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/717

**Comment by sumerjabri** [comment]
@avasquez614 please verify.

**Comment by avasquez614** [comment]
@alhambrav I think there are some issues still:

1. This section: https://docs.craftercms.org/en/3.1/system-administrators/activities/debugging-search-elasticsearch.html#configure-crafter-studio-crafter-deployer-url doesn't seem to be necessary, the previous section already tells you how to change the Deployer port. 
2. https://docs.craftercms.org/en/3.1/system-administrators/activities/debugging-search-solr.html doesn't seem to appear in the left sidebar.
3. The reindexing guides (https://docs.craftercms.org/en/3.1/system-administrators/activities/reindexing-content.html and https://docs.craftercms.org/en/3.1/system-administrators/activities/reindexing-content-in-prod.html) are still only for Crafter Search/Solr, we need them for Elasticsearch too

**Comment by alhambrav** [comment]
Item number 1 is fixed, PR https://github.com/craftercms/docs/pull/728
Item number 2 is, there's a link to the debugging-search-solr in the debugging-search-elasticsearch article 
Item number 3, I created a ticket for creating the articles for reindexing content for elasticsearch ticket: https://github.com/craftercms/craftercms/issues/3080

**Comment by avasquez614** [comment]
Verified
