### ISSUE TITLE
[studio-ui] update cluster menu with the change in local address

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2834]
## Describe the bug
In cluster `localIp` was changed to `localAddress` Please update the ui to have the new label and the proper response value

## To Reproduce
1. Have studio as a cluster member
2. Go to Cluster menu

## Expected behavior
`Local Ip` renamed to `Local Address` and information with Local Address value present.

## Screenshots
![screen shot 2019-02-07 at 10 00 43 am](https://user-images.githubusercontent.com/6722074/52424309-57b34f80-2abf-11e9-9405-4d13b58356bd.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT.

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1050

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1051

**Comment by yacdaniel** [comment]
Verified fixed.
