### ISSUE TITLE
[studio] Add " blueprint folder name" property to available_blueprints API

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2835]
Please Add " blueprint folder name" property to available blueprints API, so we can use it to create a new site.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1465

**Comment by vestrada** [comment]
Verified

**Comment by dejan-brkic** [comment]
Reopened to design better solution for this

**Comment by dejan-brkic** [comment]
UI:
https://github.com/craftercms/studio-ui/pull/1071

BE:
https://github.com/craftercms/studio/pull/1503
