### ISSUE TITLE
[studio] Error when content-monitoring.groovy job tries to run

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2836]
## Describe the bug
An exception is thrown when content-monitoring.groovy job tries to run

## To Reproduce
1. clone init build deploy develop branch
2. set your machine time to 11:50(to give studio enough time to startup and creation of a site)
3. start authoring `./gradlew -Penv=authoring start`
4. create a site from any BP
5. check catalina logs at 12:00

## Expected behavior
No exception when `content-monitoring.groovy` job runs

## Logs
https://gist.github.com/yacdaniel/d16cff53d04c811588f673236938a607

### Version
Studio Version Number: 3.1.0-SNAPSHOT-67244f
Build Number: 67244fc1454b604b5e0768589de8526ecce08c65
Build Date/Time: 02-07-2019 14:23:12 -0600

### OS
Linux/Mac

### Browser
What browser did you use to produce the bug.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1466

**Comment by yacdaniel** [comment]
Looks like content-monitoring runs but there is an error in `search`
https://gist.github.com/yacdaniel/8015817a4eb5566134afa40e5a18d23d

**Comment by jdrossl** [comment]
Depends on https://github.com/craftercms/craftercms/issues/2850

**Comment by yacdaniel** [comment]
In the `Site Configuration` from WebsiteEditorial BP the last `monitor` tag is
```
        <monitor>
            <name>Content Expiring In Two Months</name>
            <query>expired_dt:[now+60d/d TO now+6d/d]</query>
            <paths>
                <path>
                    <name>All Site</name>
                    <pattern>/site/.*</pattern>
                    <emailTemplate>contentExpiringSoon</emailTemplate>
                    <emails>twomonths@localhost</emails>
                    <locale>en</locale>
                </path>
            </paths>
        </monitor>
``` 
There is a typo in the value `TO now+6d/d` Could be `TO now+64d/d`? If we consider the one month monitor that has 
```

**Comment by yacdaniel** [comment]
Verified fixed.
