### ISSUE TITLE
[studio-ui] TinyMCE4: overlap in Insert menu

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2840]
## Describe the bug
Depending on the screen size and/or TinyMCE4 position in the edit form, the Insert menu could overlap some of the options

## To Reproduce
1. Create a site from Website_editorial BP
2. Edit Home page
3. Play with the position of the edit form

## Expected behavior
No overlap of options in the Insert menu

## Screenshots
<img width="1421" alt="screen shot 2019-02-08 at 9 51 40 am" src="https://user-images.githubusercontent.com/6722074/52489201-3ddd3f80-2b87-11e9-83e4-f242739c46e5.png">

https://www.useloom.com/share/ecf40ebfaba24b10871361b0a4475b37

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
CMS v3.1.0-SNAPSHOT

### OS
Mac

### Browser
Chrome/Firefox

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1072

**Comment by yacdaniel** [comment]
Verified fixed, no overlap using TinyMCE 5.
