### ISSUE TITLE
[docs] Update images to include Elasticsearch

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2841]
All images that include Crafter Search and/or Solr need to be updated to reflect that Elasticsearch is the default now

For example: https://docs.craftercms.org/en/3.1/_images/detailed.png

**Comment by avasquez614** [comment]
@alhambrav work with @jdrossl if needed

**Comment by alhambrav** [comment]
Images for the architecture has been updated: https://docs.craftercms.org/en/3.1/developers/architecture.html
Images for debugging search has been updated:
https://docs.craftercms.org/en/3.1/system-administrators/activities/debugging-search-elasticsearch.html
