### ISSUE TITLE
[studio-ui] TinyMCE 4 Configuration doesn't have a sample config

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2842]
## Describe the bug
The RTE(TinyMCE4) Configuration doesn't have a config sample.

## To Reproduce
1. Create a site from any BP and go to the site preview or dashboard
2. Open the Sidebar and click Site Config
3. Click Configuration
4. Select RTE (TinyMCE4) Configuration
5. Click View Sample

## Expected behavior
View Sample opens a new slide with a sample of the RTE config

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/52508861-9c241580-2bbb-11e9-9d69-a1cd586195fe.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-636b28
Build Number: 636b28d40343975c6f3bd5e6d5753f819ef66c2b
Build Date/Time: 02-08-2019 09:08:06 -0600

### OS
Any

### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1072

**Comment by yacdaniel** [comment]
Verified fixed using TinyMCE 5, all BP have a config sample.
![image](https://user-images.githubusercontent.com/6722074/54364657-f426bf80-4632-11e9-891e-f4a2f8835930.png)
