### ISSUE TITLE
[studio-ui] Existing RTE content disappears when clicking on "Add Another" in Articles using RTE (TinyMCE 5)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2843]
## Describe the bug
Existing RTE content disappears when clicking on "Add Another" in Articles.

## To Reproduce
1. Create a site using website_editorial bp
2. Preview an article and edit it (For example, `5 Popular Diets for Women`, click on `Edit` from the context nav, or right click on the article from the Sidebar and select `Edit`)
3. Scroll down to `sections` (the RTE)
4. Click on `Add Another` to add another section to the article.  Notice that the existing section disappears and instead you have two empty sections

## Expected behavior
Existing RTE content should not disappear when clicking on "Add Another" in Articles.

## Screenshots
4. 
![screen shot 2019-02-11 at 11 57 30 am](https://user-images.githubusercontent.com/25483966/52579549-5ef69800-2df4-11e9-9947-532b6a8cb8c6.png)

Existing content gone:
![screen shot 2019-02-11 at 11 59 00 am](https://user-images.githubusercontent.com/25483966/52579951-4e92ed00-2df5-11e9-99d5-2560cc798ce1.png)

## Logs
Here's a short clip:
https://www.useloom.com/share/43a2eb20b7f4485c80525c345f94ce41

### Version
Studio Version Number: 3.1.0-SNAPSHOT-636b28
Build Number: 636b28d40343975c6f3bd5e6d5753f819ef66c2b
Build Date/Time: 02-11-2019 08:20:48 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by alhambrav** [comment]
Adding to the ticket here, all existing content disappears when you click on any of the links at the top of the repeating control: `Add Another`, `Move Up`, `Move Down`, `Delete` 

Here's a short clip showing the behavior:
https://www.useloom.com/share/bf08fd2204884df9882660d702c3f5ae

Version:
Studio built from fresh clone: 3/13/2019

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1075

**Comment by alhambrav** [comment]
Verified fixed
