### ISSUE TITLE
[studio-ui] Images inserted through RTE (TinyMCE 5) in Articles are not rendered in preview

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2844]
## Describe the bug
Images inserted through RTE (TinyMCE 5) in Articles are not rendered in preview.  It seems like the location where the image is being retrieved is incorrect.

## To Reproduce
1. Create a site using website_editorial bp
2. Preview an article and edit it (For example, `Top Romantic Valentine Movies`, click on `Edit` from the context nav, or right click on the article from the Sidebar and select `Edit`)
3. Scroll down to `sections` (the RTE) click to begin editing
4. Go to the end of the section text and click on `Insert` -> `Image`
5. Click on the button next to `Source` and select `Existing Images`, then select `castle-pic.jpg`
6. Save your changes and notice the image is not displayed in preview.
7. Do an inspect of your browser and notice the 404 errors when trying to get the castle-pic.jpg file. Notice the url it's using to get the image:
```
GET http://localhost:8080/articles/2017/static-assets/images/castle-pic.jpg 404
```
Should it be getting the image from: `http://localhost:8080/static-assets/images/castle-pic.jpg` instead?

## Expected behavior
Images inserted through RTE (TinyMCE 5) in Articles should be rendered in preview

## Screenshots
Here's the Form showing the image inserted through the RTE:
![screen shot 2019-02-11 at 12 58 30 pm](https://user-images.githubusercontent.com/25483966/52583160-ee07ae00-2dfc-11e9-8e41-c918ad6bdf4b.png)

Here's the preview of the page:
![screen shot 2019-02-11 at 1 37 50 pm](https://user-images.githubusercontent.com/25483966/52585611-3fb33700-2e03-11e9-8d3a-54d3edacaa61.png)

## Logs
Here's a short clip:
https://www.useloom.com/share/655e4b04faf8456da849168c0fa292d6

### Version
Studio Version Number: 3.1.0-SNAPSHOT-636b28
Build Number: 636b28d40343975c6f3bd5e6d5753f819ef66c2b
Build Date/Time: 02-11-2019 08:20:48 -0500
### OS
OS X
### Browser
Chrome Browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1075

**Comment by alhambrav** [comment]
Verified fixed
