### ISSUE TITLE
[studio-ui] Notification is not displayed when user try to remove last member from system_admin group

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2845]
## Describe the bug
There is no notification popup when the user tries to remove the last member from `system_admin` group  

## To Reproduce
1. Go to groups menu
2. Click the edit icon next to the `system_admin` group
3. Click the trash icon next to the only user:`admin`, in the group
4. Click yes in the Confirmation popup

## Expected behavior
A notification popup appears with the result of the operation.

## Screenshots
https://www.useloom.com/share/376dd9e0f56c45faa127c22dc5839746 

## Logs
https://gist.github.com/yacdaniel/d90e2e311ef260f147ac4d617d242f31

### Version
Studio Version Number: 3.1.0-SNAPSHOT-636b28
Build Number: 636b28d40343975c6f3bd5e6d5753f819ef66c2b
Build Date/Time: 02-11-2019 09:06:01 -0600

### OS
Mac

### Browser
Chrome/Firefox

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1049

**Comment by yacdaniel** [comment]
Verified fixed. A notification appears when the user tries to remove the last member of the `system_admin` group. 
![imagen](https://user-images.githubusercontent.com/6722074/52805176-a4f96900-304b-11e9-8e3e-165f431099ff.png)
