### ISSUE TITLE
[studio-ui] search in users is not working

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2846]
## Describe the bug
Search box in the Users menu is not working

## To Reproduce
1. Go to the Users Menu and create a couple of users to test the search bar
2. Search for an user

## Expected behavior
Searching works

## Screenshots
https://www.useloom.com/share/fbb4b6969111423ebbd1117ecf06fc18

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-636b28
Build Number: 636b28d40343975c6f3bd5e6d5753f819ef66c2b
Build Date/Time: 02-11-2019 09:06:01 -0600

### OS
Mac

### Browser
Chrome/Firefox

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1048

**Comment by yacdaniel** [comment]
Verified fixed.
