### ISSUE TITLE
[studio-ui] improve usability of CMIS Data source with human readable paths in picker

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2852]
**Is your feature request related to a problem? Please describe.**
Today the CMIS data source combined with an item selector allows the author to select and link to files in the CMIS repository. The labels provided to the user are CMIS node refs.  These usable/friendly to an author.  A friendly, human-readable path would be more valuable.

**Describe the solution you'd like**

Change Line 82 of studio code:
`/static-assets/components/cstudio-forms/data-sources/CIMS-repo.js` 
to: 
`control.insertItem(uri, item.browserUri, fileExtension);`

Current code is:
 `control.insertItem(uri, uri, fileExtension);`

**Describe alternatives you've considered**

**Additional context**
https://www.useloom.com/share/24953e62e27448959dacfbde2b5fa01f

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1055

**Comment by russdanner** [comment]
Confirmed
