### ISSUE TITLE
[studio] Wrong name property in headless_store BP descriptor.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2857]
## Describe the bug
BP Descriptor for headless_store has the property `blueprint.name` with value `Headless Blog Blueprint`

## To Reproduce
1. Chek BP name descriptor for headless_store https://github.com/craftercms/studio/blob/e94f2c82fe971808d69f3eeb8192fe0992eeed30/src/main/webapp/repo-bootstrap/global/blueprints/headless_store/descriptor.yaml#L9

## Expected behavior
The name should be `Headless Store Blueprint`

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-e94f2c
Build Number: e94f2c82fe971808d69f3eeb8192fe0992eeed30
Build Date/Time: 02-14-2019 08:37:35 -0600
### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by dejan-brkic** [comment]
Done:
PR:
https://github.com/craftercms/studio/pull/1503

**Comment by yacdaniel** [comment]
Verified fixed.
