### ISSUE TITLE
Issue with SVG Image previews

### ISSUE THREAD

**Issue by hhettiarachchi** [craftercms/craftercms#2859]
We have noticed an issue where SVG images are not being previewed in crafter when they are configured to store in AWS S3.

1. Configure the S3 bucket as per the documentation.
2. Upload an SVG as an image to be stored in S3.
3. Check that there will be no preview generated. 
## Expected behavior
SVG's should preview.

I've tested this with 3.0.18 and reason for this seems to be that crafter doesn't set the metadata when objects are being uploaded to the S3. It is just setting *application/octet-stream* in the metadata instead of image/(type). If this is manually set in the S3 bucket, the image will be previewed, but every time when crafter does a change to the image it just re-write the metadata with content type: application/octet-stream

**Comment by jdrossl** [comment]
@yacdaniel please verify that the fix is working, let me know if you need any help setting up the aws profile

**Comment by yacdaniel** [comment]
Fix in 3.1 looks good, 3.0 depends on https://github.com/craftercms/craftercms/issues/2912 to verify it.

**Comment by yacdaniel** [comment]
Verified fixed in 3.0. 
@hhettiarachchi the next release of 3.0.x will have the fix in place.
