### ISSUE TITLE
[deployer] Missing content-type header in S3 uploads

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2860]
S3 uploads need to set the right content-type header for all uploads or this could affect assets used from CloudFront

Reference issue https://github.com/craftercms/craftercms/issues/2859

**Comment by jdrossl** [comment]
@yacdaniel please verify that the fix is working, let me know if you need any help setting up a serverless delivery

**Comment by yacdaniel** [comment]
Verified fixed,  content-types are ok in S3.
