### ISSUE TITLE
[studio-ui] sign-out from site fails in Firefox v63+

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2862]
## Describe the bug
User is not logged out properly fully when clicking sign-out in the context nave of a site using Firefox version 63 and up.

## To Reproduce
1. Log in to Crafter Studio
2. Click on a site to preview it
3. Click sign-out in the context nav
4. Note user is taken to the sites screen with no sites listed rather than to sign-in screen.

## Expected behavior
User should be taken to the sign-in screen when signed out

## Screenshots
https://www.useloom.com/share/2f623fc353c84854aa6aa4560dd8b11e

## Logs
N/A

### Version
2.5.19
2.5.20 Snapshot

### OS
Observed in windows and MacOSX

### Browser
Firefox 63.x+

**Comment by vestrada** [comment]
Hi Russ,
With the new war 2.5.20 I'm not seeing the issue.
MAC - FF 65 as you can see in the following Video:
https://www.useloom.com/share/ddb5ae8281c243a9bb3b0d5fe954c668
https://screencast.com/t/CcP0ZYPXv9aC
Win10 - FF 65 as you can see in the following Video:
https://www.useloom.com/share/4d81904193584b3b8e428927afec1b29

Seen the video it can be this api: /studio/api/1/services/api/1/user/logout.json or this variable: CStudioAuthoringContext.authoringAppBaseUri in logout.js, but I can't reproduce it.

**Comment by russdanner** [comment]
This can be reproduced in 2.5.19 with Chrome and FF
https://www.useloom.com/share/3f78e99fdd424af99b39eb9519c7e48e

**Comment by russdanner** [comment]
This bug only occurs when you are using Alfresco as the repository.  The issue is on the backend.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1536

**Comment by russdanner** [comment]
Confirmed
