### ISSUE TITLE
[studio] Implement new API to upload assets to CMIS

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2863]
We need to create a new api to allow studio to upload assets (including images, videos..) to CMIS

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1482

**Comment by dejan-brkic** [comment]
3.0.x
https://github.com/craftercms/studio/pull/1484

**Comment by sumerjabri** [comment]
@vestrada please validate and close if good.

**Comment by jdrossl** [comment]
@dejan-brkic We need to change the upload to avoid using the `CommonsMultipartResolver`, it causes a conflict with existing AWS uploads that use a streaming approach to support large files. You can take a look at this one for reference: https://github.com/craftercms/studio/blob/master/src/main/java/org/craftercms/studio/controller/rest/v2/aws/AwsS3Controller.java#L95

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1602

**Comment by vestrada** [comment]
Waiting for the last merge to test.

**Comment by vestrada** [comment]
Hi, checking it. Seems like the API is not responding with the item information.
An example of this is AWS-S3 that is responding: 
"item": {
    "name": "string",
    "url": "string",
    "folder": true
  }

Dejan can you add it?

Thanks :)

**Comment by vestrada** [comment]
Also this CMIS upload API is  not on documentation yet.
https://app.swaggerhub.com/apis/craftercms/studio/3.1.0.0

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1606

**Comment by vestrada** [comment]
@dejan when the api is uploading a a file that already exist, It responds with wrong information.
Also Clone from repo is reponding with: `HTTP Status 500 – Internal Server Error`.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1615

**Comment by vestrada** [comment]
verified
