### ISSUE TITLE
[studio][studio-ui] only inactives cluster nodes should have the option to be removed from cluster

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2864]
Currently, we can remove any cluster node at any time.
We need to change this to only the cluster nodes that are declared inactive should have the UI option to be removed from the cluster.

**Comment by sumerjabri** [comment]
@dejan-brkic to do the backend enforcement
@vestrada to do the front-end

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/1483

**Comment by dejan-brkic** [comment]
State value for inactive members is `INACTIVE`

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1058

**Comment by yacdaniel** [comment]
Verified fixed, only inactive cluster members have the option to be removed from the cluster
![imagen](https://user-images.githubusercontent.com/6722074/54842329-49984780-4c97-11e9-8c86-1c6250bd87be.png)

**Comment by yacdaniel** [comment]
@rart on 4.0.0, all the cluster nodes show the option to delete, but only nodes with `state: "INACTIVE"` should display the option.

![image](https://user-images.githubusercontent.com/6722074/126659466-27fe20bb-c671-4bb6-877e-9d7186f4f822.png)

**Comment by rart** [comment]
@sumerjabri, other than the `clusters[n].state === 'INACTIVE'` is there a permission we should check to show the delete option?

**Comment by yacdaniel** [comment]
![image](https://user-images.githubusercontent.com/6722074/130496175-f30be9fa-312e-463c-9511-5e7e4cf0a220.png)
Verified fixed.
