### ISSUE TITLE
[studio-ui] the new create site dialog should open and place the user at the beginning of it

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2865]
Currently, the new create site dialog opens and the user is positioned at the middle of the dialog.
https://www.useloom.com/share/a5304a4f271f42ca973c8de210b0621d

To improve user experience it would be nice if the user is placed at the beginning of the new create site dialog.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1056

**Comment by yacdaniel** [comment]
Verified fixed.
