### ISSUE TITLE
[studio] Cannot create site on mac when authoring and delivery is started at the same time

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2868]
## Describe the bug
Cannot create site on mac when authoring and delivery is started at the same time

## To Reproduce
1. Clone craftercms `$git clone https://github.com/craftercms/craftercms.git -b develop`
2. Build and deploy `$./gradlew init build deploy`
3. Start craftercms, both authoring and delivery `$./gradlew start`
4. Login to Studio
5. Create a site using any bp, notice the message on the browser.  The tomcat logs does not have any errors, check the deployer logs and there's an error there

## Expected behavior
User should be able to create a site when both authoring and delivery is started at the same time

## Screenshots
![screen shot 2019-02-21 at 2 13 54 pm](https://user-images.githubusercontent.com/25483966/53195113-f624d200-35e2-11e9-9544-57fb9bbf264c.png)

## Logs
Check the deployer logs and see the following message:
https://gist.github.com/alhambrav/3555ee3a9d4c8a2793643f0bafe421cd

### Version
Studio Version Number: 3.1.0-SNAPSHOT-3712a4
Build Number: 3712a4d4f9054c918b881c1e5d0c70953387f87f
Build Date/Time: 02-21-2019 12:15:20 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
It seems like this only happens on OS X.  I asked @yacdaniel to try it too and he said it only happens on OS X for him.

**Comment by dejan-brkic** [comment]
This is deployer/Elastic search issue. By starting only authoring after issue is reproduced, studio is able to create site. Most probably there is some conflict between two instances of ES on same mac machine.

**Comment by jdrossl** [comment]
@alhambrav I was not able to reproduce this issue, can you please provide me the full elastic search log

**Comment by alhambrav** [comment]
Verified fixed.
