### ISSUE TITLE
[studio-ui] Create a global audit viewing tool

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2869]
Please copy the audit viewer that's in the site/bp to the global (main) menu at the same level as clustering etc.

The tool will add the ability to filter by site.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1062

**Comment by vestrada** [comment]
studio PR: https://github.com/craftercms/studio/pull/1489

**Comment by sumerjabri** [comment]
We don't want to remove the audit capability from sites, we just want to add a global audit which lets you audit all, and limit the site audit to just events related to that site.

Ping me to discuss further.

@dejan-brkic review the above and let me know if you see problems.

**Comment by vestrada** [comment]
Done. studio PR is updated. The only change is the global menu configuration.

**Comment by vestrada** [comment]
studio-ui -> PR: https://github.com/craftercms/studio-ui/pull/1063

**Comment by sumerjabri** [comment]
Please have the tool start without a set site. Also, please add the global/default site to the list of selectable sites.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1067

**Comment by vestrada** [comment]
Hi @dejan-brkic 

Please continue with the api2 fixes.
- Site_id shouldn't be required.
- users and actions is not working

![image](https://user-images.githubusercontent.com/11640613/53823117-b80aa500-3f36-11e9-84bc-0e895f6382fa.png)

Thanks :)

**Comment by vestrada** [comment]
Timezone is pending.

**Comment by dejan-brkic** [comment]
Actions (array) need to be passed in one of the following ways:
`http://localhost:12345?values=firstValue,secondValue,thirdValue`
or
`http://localhost:12345?values=firstValue&values=secondValue&values=thirdValue`

PR:
https://github.com/craftercms/studio/pull/1498

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1070

**Comment by vestrada** [comment]
All changes are done. I'm using UTC for as the Timezone. If Russ decide to use other, we can create a new ticket for that.

**Comment by sumerjabri** [comment]
@vestrada Please add:
- Studio's root site as an option and call it `System` so we can see system activities
- Source column (to show the source of the activity), see API response (it has that)

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/2924

**Comment by sumerjabri** [comment]
BE ready.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1102

**Comment by sumerjabri** [comment]
We will need:

```Also, please add the global/default site to the list of selectable sites.```

That's a fixed "site" that's always present in the dropdown as the first site. You can call it: "System"

**Comment by sumerjabri** [comment]
Verified.
