### ISSUE TITLE
'Save & Close' and 'Save Draft' should refresh preview to the page saved

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#287]
Content type is set to 'content-as-folder=false'

1) go to a page preview
2) while in preview, create a content from the site dropdown
3) click 'Save Draft'

The preview screen will stay in the first page while it should refresh to the new page with the draft info bar.

4) click 'Save & Close'

The preview screen will stay the same while it should refresh to the new page without the info bar.

**Comment by russdanner** [comment]
I cannot replicate this in the latest build

**Comment by russdanner** [comment]
Chrome or Firefox anyway

**Comment by hlim** [comment]
You will need to be on another page first. Confirmed it can be reproduced with content-as-folder=true content type as well.

**Comment by russdanner** [comment]
I will change this to an enhancement request and put it in the backlog.

That's not the current spec for the application - and needs to be thought out before we change the behavior

**Comment by vestrada** [comment]
Completed
