### ISSUE TITLE
[studio] Update role-access to the audit service

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2870]
When invoking the access service, change the role-based access to allow the audit records to be returned if:

- The actor is the `global admin`, OR
- The actor has the `admin` role on the requested site

**Comment by dejan-brkic** [comment]
Docs updated:
https://github.com/craftercms/studio/pull/1486

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1490

**Comment by sumerjabri** [comment]
@yacdaniel please validate and make sure Studio honors the permissions as spec'd out in the API docs on SwaggerHub and as detailed in the ticket.

Ping me if you need any help.

**Comment by yacdaniel** [comment]
Verified fixed.
