### ISSUE TITLE
[studio-ui] Cleanse/escape the logs before displaying them in the site log viewer

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2871]
## Describe the bug
The logs displayed in the log view in Site Config are not escaped and can cause viewing errors or worse.

## To Reproduce
1. Go to `Site Config`
2. Click on `Log Console`
3. Create an action that causes Engine to dump unescaped logs

## Expected behavior
Logs are escaped/cleansed.

### Version
3.0 and 3.1

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1059

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/1060

**Comment by sumerjabri** [comment]
Doesn't look good on Linux Chrome
![image](https://user-images.githubusercontent.com/3931908/53527495-2245c480-3ab5-11e9-81d3-737a057265c5.png)

**Comment by yureii00** [comment]
I tested it with the newest version on Studio-UI, and I was no able to reproduce.

Ubuntu 18 04 Chrome.
<img width="1174" alt="Ubuntu 18 04 Chrome" src="https://user-images.githubusercontent.com/10813283/62900400-4588c700-bd17-11e9-9675-0c02c1fbc7e0.png">

Ubuntu 18 04 Chromium.
<img width="1140" alt="Ubuntu 18 04 Chromium" src="https://user-images.githubusercontent.com/10813283/62900408-49b4e480-bd17-11e9-8181-be6e20629468.png">

**Comment by sumerjabri** [comment]
UI looks terrible if there is an exception in the logs:

![image](https://user-images.githubusercontent.com/3931908/65077635-5c9b8400-d969-11e9-9101-77d60de7c28c.png)

Try to rebuild the context on a site and see. `http://localhost:8080/api/1/site/monitoring/log.json`

**Comment by yureii00** [comment]
I was able to reproduce the issue

**Comment by sumerjabri** [comment]
@yureii00 ping me and we can reproduce it together.

**Comment by sumerjabri** [comment]
Verified.
