### ISSUE TITLE
[craftercms] Provide a consistent monitoring API across all modules

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2875]
Provide a consistent set of monitoring APIs that return the same information across all Crafter CMS modules:

* Studio
* Engine
* Deployer 
* Profile
* Social

There should be 3 different monitoring APIs, one for each of the following monitoring aspects:

* Memory (used, max)
* Status (startup date time, uptime)
* Version (Crafter version, OS version, JVM version, etc)

You should use the models provided in commons under https://github.com/craftercms/commons/tree/master/utilities/src/main/java/org/craftercms/commons/monitoring, and refactor/enhance them as necessary. OAS documentation is expected for the Studio APIs.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 can we chat about this ticket? I think we need to first define the API to see what changes are needed in commons and then implement it everywhere. And maybe we could also consider using a library that provides something for this? Spring Boot comes with an awesome framework built-in https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

**Comment by avasquez614** [comment]
Verified
