### ISSUE TITLE
[studio] Clustering - Errors when creating a site from a third node in the first and second nodes

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2881]
## Describe the bug
When creating a site from a third node, there are errors from the first two nodes trying to sync the new site being created in the third node from each other

## To Reproduce
1. Setup 2 nodes, in each node, create a site (node A , sitea1 and node B, siteb1)
2. Start up a third node, then create a site (node C, sitec1)
3. Watch the logs for the first two nodes and notice the error messages listed there while the site in the third node is being created

Node C (192.168.1.15):
Create site `sitec1`....

Notice the logs for node A and node B

Node A (192.168.1.3):
```
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://osboxes@192.168.1.14/home/osboxes/temp/craftercms/crafter-authoring/data/repos/sites/sitec1/sandbox: fatal: '/home/osboxes/temp/craftercms/crafter-authoring/data/repos/sites/sitec1/sandbox' does not appear to be a git repository
```

Node B (192.168.1.14):
```
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://vita.alhambra@192.168.1.3/Users/vita.alhambra/temp/test5/craftercms/crafter-authoring/data/repos/sites/sitec1/published: fatal: '/Users/vita.alhambra/temp/test5/craftercms/crafter-authoring/data/repos/sites/sitec1/published' does not appear to be a git repository
```

The logs for the 3 nodes are below.

## Logs
Node A: https://gist.github.com/alhambrav/4a15326cd523cf3854f3438521be2f79
Node B: https://gist.github.com/alhambrav/b3216c438cd2637621dec7cfc7d4407e
Node C: https://gist.github.com/alhambrav/561c1c844e72657e4080ceaede784744

### Version
Studio Version Number: 3.1.0-SNAPSHOT-33b0a2
Build Number: 33b0a23e68002b7ebd49838dfe347955587a34d0
Build Date/Time: 02-27-2019 10:40:16 -0500

### OS
Node A: OS X
Node B: Ubuntu
Node C: Ubuntu

### Browser
Chrome browser for all 3 nodes

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1495

**Comment by alhambrav** [comment]
Hi! There are still errors in the logs when creating a site in the third node.

Node A: 192.168.1.3 (First node up, site created `sitea`)
Node B: 192.168.1.18 (Second node up, site created `siteb`)
Node C: 192.168.1.15 (Third node up, site created `sitec`)

**Version**
Studio Version Number: 3.1.0-SNAPSHOT-640b78
Build Number: 640b78d072cc507ab75ba36b1d402154c7e52b54
Build Date/Time: 03-05-2019 13:24:03 -0500

Node A logs after creating "sitec" on node C: https://gist.github.com/alhambrav/64503714875382b7cc58c9d5fbc2e91f
Node B logs after creating "sitec" on node C:
https://gist.github.com/alhambrav/4fea5122e5933affb6ec74a1983b6f7e
Node C logs after creating "sitec" on node C:
https://gist.github.com/alhambrav/b26240614d8e486c4ffa93b05a59ba0a

**Comment by dejan-brkic** [comment]
These errors are expected because the cloning site to all nodes has to propagate.

**Comment by alhambrav** [comment]
Verified fixed.

Will create another ticket for the 
```
[ERROR] 2019-03-05T14:10:32,174 [Studio_Clustering_Thread_Pool5] [cluster.StudioNodeSyncPublishedTask] | Error while updating published repo for site sitec 
```
