### ISSUE TITLE
[studio-ui] Create Site Dialog Issues

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2883]
## Describe the bug
- The wizard navigation buttons are at the bottom of the dialog and the user must scroll down to the bottom of the page to navigate.
- The wizard final step has an arrow for the next step.
- There is no `back` button.

## To Reproduce
1. Go to create site
2. Click through the wizard

## Expected behavior
- Move the wizard navigation to a fixed spot within the page and add a scrollbar to scroll through the options.
- Flatten the right edge of the last step.
- Add a `back` button that takes you back to exactly where you were.

## Screenshots
N/A

## Logs
N/A

### Version
3.1.0-SNAPSHOT

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1064

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1068

**Comment by sumerjabri** [comment]
Verified.
