### ISSUE TITLE
[studio-ui] Add Embedded  Content Datasource

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2884]
Related to: #2795 

Create a new DS in the form engine, called Embedded Content, which should be similar to Child Content except it will be used to create the inline components and should have only the following property:
* **Content Type**: the content type to use by default when creating the content.

Other requirements:
* The DS must add the attribute `inline=”true”` to indicate that this is a inline/included item.
* When inlining the component, the `key` tag must be empty, the `disableFlattening` tag should not be added and the `component` root element should replace the `include` tag.

```
<foo item-list="true">
  <item inline=”true”>
    <key></key>
    <value>blah</value>
    <component>
      <foo>blah<foo>
    </component>
  </item>
</foo>
```

**Comment by vestrada** [comment]
New API for this ticket: https://github.com/craftercms/craftercms/issues/2938

**Comment by rart** [comment]
@sumerjabri @avasquez614 I'm wondering if "Embedded child content" makes for a better name than "item-specific child content"?

**Comment by sumerjabri** [comment]
Agreed. Let's rename to Embedded Content.

I don't think we should do Embedded Child Content because it's not child anymore.

**Comment by yacdaniel** [comment]
@rart please find a new icon for this data source, when ready assign back to me to test it and we can send it to BE to add it into the upgrade manager pipeline.

**Comment by rart** [comment]
@yacdaniel 
- `fa-share-alt` for _Shared content_
- `fa-share-alt` for _Embedded content_
fyi @alhambrav

**Comment by yacdaniel** [comment]
Verified.
