### ISSUE TITLE
[studio-ui] History Dialog's diff tool should be able to show XML trees with depth greater than 1

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2885]
Depends on https://github.com/craftercms/craftercms/issues/2884
Related to: #2795 

Including item-specific components inside their parents will produce XML trees of unlimited depth. Right now, the diff tool used to compare versions of a file only works for a depth of 1. The diff tool should be enhanced to display diffs of trees, that can be expanded/collapsed.

**Comment by avasquez614** [comment]
On hold, need to discuss with @sumerjabri

**Comment by jdrossl** [comment]
@rart do you have any updates for this?

**Comment by sumerjabri** [comment]
@russdanner is this needed for 3.2.0? This is a significant effort on the front and back.

**Comment by sumerjabri** [comment]
@jdrossl See if the following will work:
* Updating the XLST to generate deeply nested HTML prior to sending it to the diff tool
* Don't change anything else

If the above works, this ticket is complete.

**Comment by jdrossl** [comment]
@sumerjabri @rart I was able to change the XSLT & a bit of code to support multiple levels but the UI needs to be adapted, we can even design the view from scratch and generate a better HTML & CSS

![Screenshot from 2021-03-26 11-03-36](https://user-images.githubusercontent.com/1236955/112686734-0c459200-8e3c-11eb-8920-43c0efd4984e.png)

**Comment by sumerjabri** [comment]
@rart see if there is anything needed on the UI side, the BE is merged already.
