### ISSUE TITLE
[search] Upgrade Solr to 7.7.0

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2886]
Please upgrade Solr to version 7.7.0

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 there is already `7.7.1`, should we use that instead?

**Comment by avasquez614** [comment]
Yes please

**Comment by russdanner** [comment]
Changes to be aware of:
https://lucene.apache.org/solr/guide/7_0/major-changes-in-solr-7.html

**Comment by avasquez614** [comment]
Verified
