### ISSUE TITLE
[studio] FileNotFoundException: Unable to access classpath:crafter/engine/extension/log4j-override.xml when starting Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2888]
## Describe the bug
FileNotFoundException: Unable to access classpath:crafter/engine/extension/log4j-override.xml when starting Studio

## To Reproduce
1. Clone craftercms $git clone https://github.com/craftercms/craftercms.git -b develop
2. Build and deploy &./gradlew init build deploy
3. Start craftercms $./gradlew -Penv=authoring start
4. See the error in the tomcat log:

```
ERROR StatusLogger Unable to access classpath:crafter/engine/extension/log4j-override.xml
 java.io.FileNotFoundException: Unable to load the resource [classpath:crafter/engine/extension/log4j-override.xml] using the thread context class loader or the current class's class loader
```

## Expected behavior
There should be no errors in the logs when starting craftercms

## Logs
https://gist.github.com/alhambrav/fe0a8868561666ae3989e88191fe7815

### Version
Studio Version Number: 3.1.0-SNAPSHOT-acc893
Build Number: acc893eaefcf759a762b0879e27366823a3d5b22
Build Date/Time: 03-01-2019 08:32:41 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by jdrossl** [comment]
This issue will be fixed with https://github.com/craftercms/studio/pull/1492

**Comment by alhambrav** [comment]
Verified fixed.
