### ISSUE TITLE
[craftercms] AccessControlException - access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.dynalink.support")

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2889]
## Describe the bug
AccessControlException - access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.dynalink.support") when starting Studio

## To Reproduce
1. Clone craftercms $git clone https://github.com/craftercms/craftercms.git -b develop
2.  Build and deploy &./gradlew init build deploy
3.  Start craftercms $./gradlew -Penv=authoring start
4. See the error in the tomcat log:

```
AccessControlException - access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.dynalink.support")
```

## Expected behavior
There should be no errors in the logs when starting Studio

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
https://gist.github.com/alhambrav/72ec87d6a817885ef175c883429126de

### Version
Studio Version Number: 3.1.0-SNAPSHOT-acc893
Build Number: acc893eaefcf759a762b0879e273
Build Date/Time: 03-01-2019 08:32:41 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by avasquez614** [comment]
@alhambrav I can't reproduce this issue with the a new clone of the latest `develop` branch.

**Comment by alhambrav** [comment]
Verified could not reproduce with today's build 3/4/2019
