### ISSUE TITLE
Change made in code mode doesn't get saved upon clicking 'Save & Close'

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#289]
1) Go to preview of a content that has in-context editing enabled on a page
2) Click the pencil to edit the field
3) Click 'Edit Code'
4) Make a few changes and click 'Save & Close'

The change will be lost unless switched to WYSIWYG mod and saved.

**Comment by asotog** [comment]
not able to reproduce this on clean crafter studio, will check further
