### ISSUE TITLE
[craftercms] Test Serverless mode on AWS EKS

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2892]
- Provision EKS
- Provision AWS Elasticsearch for Search
- Build and test sites using this setup, and work to load the system and see it scale
- Document your work for this to become a cookbook
- See if it's possible to produce a CloudFormation that we can publish

**Comment by avasquez614** [comment]
@sumerjabri testing is done, will create tickets for Docker/Kubernetes cookbooks and for possibly creating a Terraform deployment for Kubernetes.
