### ISSUE TITLE
[studio] global-permission-mapping is not being updated for old installations. 

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2893]
## Describe the bug
[studio] global-permission-mapping is not being updated for old installations. 

## To Reproduce
1. Go to '.. global-permission-mapping.xml' it doesn't contain audit_log permission.

## Expected behavior
audit_log permission should be working in old installations.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1496

**Comment by sumerjabri** [comment]
@yacdaniel please verify and close if working.

**Comment by yacdaniel** [comment]
Hi @dejan-brkic `global-menu-config.xml`is not being updated and the global menu `Audit` is not shown in the UI after an upgrade. 

`global-permission-mappings-config.xml` is being updated and the `audit_log`entry was added successfully.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1517

**Comment by yacdaniel** [comment]
Verified fixed.
