### ISSUE TITLE
[craftercms] ./gradlew deploy duplicates properties in elasticsearch.yaml

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2894]
## Describe the bug
Properties being duplicated
```
# Disable cluster discovery
discovery.type: single-node
```
## To Reproduce
Run multiple times:
./gradlew clean build deploy -Penv=authoring -PmoduleName=studio

**Comment by jdrossl** [comment]
This issue will be fixed as part of the refactor for the `deploy` task
