### ISSUE TITLE
[search] Add copyField/copyTo capability in the search engines

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2899]
**Is your feature request related to a problem? Please describe.**
Content models that specify _html currently signal the search indexing to strip the HTML formatting for the field.  This is useful for better search, search results and other use cases where markup is problematic. However, being able to retrieve the field with markup is also useful i.e. displaying the content in a component.

**Describe the solution you'd like**
Enable the search processor to copy content from one field to another (similar to copyTo tag in Solr)
Support wild cards: *_html copied to *_mkup 

Solr example:
` <copyField source="*_html" dest="*_mrkup"/>`

**Describe alternatives you've considered**
Automatically copy content for users when you see *_html.  This impacts existing implementations.

**Additional context**
None.

**Comment by sumerjabri** [comment]
@russdanner are you asking for this to be enabled in Solr and ES?

@avasquez614 read through and let's discuss to figure out options. This might help us with GraphQL.

**Comment by russdanner** [comment]
RE Solr & ES: Yes. 
I think this is useful regardless of the underlying storage or index mechanism.

**Comment by sumerjabri** [comment]
@russdanner Useful or required? My reading here is that you're requiring this for 3.0 (and hence Solr).

**Comment by russdanner** [comment]
For 3.0.x / Solr: this is required.
For ES it looks like it would also be required.

Content is stored (and returned) as it sent in during the write/update.  Using the OOTB charfilters on the analyzers only effects the index.

**Comment by sumerjabri** [comment]
@jdrossl please ping Alfonso or me if you need help understanding this ticket.
This should also help with GraphQL implementation and avoid us having to load content.

Please make sure that what we index and store in the index has been processed by Core to honor inheritance. This is an important point, so let's discuss if that's not the case.

**Comment by russdanner** [comment]
Confirmed
Also including a screen shot of a query to illustrate for future readers:
<img width="1274" alt="Screen Shot 2019-04-01 at 9 55 21 AM" src="https://user-images.githubusercontent.com/169432/55333020-7224fc00-5464-11e9-8158-2d82c859788e.png">
