### ISSUE TITLE
[sdk-js] Update to use the new search service

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2900]
Update the search API in SDK JS to use ES instead of Solr for 3.1 and update VC2 to the latest.

**Comment by jvega190** [comment]
https://github.com/craftercms/craftercms-sdk-js/pull/30

**Comment by jvega190** [comment]
[video-center]: https://github.com/craftercms/video-center-blueprint/pull/16

**Comment by jvega190** [comment]
https://github.com/craftercms/craftercms-sdk-js/pull/313

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/20 - Search query updates
