### ISSUE TITLE
[studio-ui] Add highlight to Sidebar

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2901]
Please add the ability to highlight an item in the Sidebar. Please ensure that:

1. The highlighted item is stored in the `cookie` that holds the state of the Sidebar
2. The highlighted item is scrolled to be the vertical center of the Sidebar
3. If the `cookie` has null for the highlighted item, then nothing is highlighted and no scrolling occurs (today's behavior)
4. Clicking or selecting an item to preview (like a page or an asset) will cause the highlight to be set

Ping me if you have any questions or concerns.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1171

**Comment by sumerjabri** [comment]
Please fix the issues we discussed.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1184

**Comment by sumerjabri** [comment]
I still see issues:
1. Try it with the preview version of Studio (before this fix), then upgrade and try again without clearing cookies or cache
2. Click around in `static-assets/images`, the highlight won't change as the images change. It seems that you assign the highlight based on how you got there, not what's being shown on the screen. We should discuss the design of the code. Ping me.

**Comment by sumerjabri** [comment]
Verified.
