### ISSUE TITLE
[studio] Error when editing a page javax.script.ScriptException

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2905]
## Describe the bug
There's an error in the logs when you edit a page: 
```
Error while executing content lifecycle script for mysitea:/site/website/index.xml
javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 18: unable to resolve class scripts.libs.CommonLifecycleApi
```

## To Reproduce
1. Optional: Setup Studio for clustering (one node only)
2. Create a site using website_editorial bp
3. Edit the home page and save your changes
4. Look at the logs and notice the error listed

## Expected behavior
There should be no errors in the logs when editing a page

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
https://gist.github.com/alhambrav/b1460a5ed55cae5d61e101f78dee041f

### Version
Studio Version Number: 3.1.0-SNAPSHOT-640b78
Build Number: 640b78d072cc507ab75ba36b1d402154c7e52b54
Build Date/Time: 03-05-2019 05:30:42 -0500

### OS
What OS did you use to produce the bug.
OS X

### Browser
What browser did you use to produce the bug.
Chrome browser

## Additional context
The error appears when editing a page whether Studio is setup in a cluster or not.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1497

**Comment by alhambrav** [comment]
Verified fixed.
