### ISSUE TITLE
[studio-ui] Content Type: Help field doesn't load the tinymce editor

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2906]
## Describe the bug
The basic field Help for a Content Type can't be filled because TinyMCE is not loading. 

## To Reproduce
1. Create a site from Website Editorial BP
2. Go to Site Config, Content Types and open the `Page - Article` Content Type
3. Click the `Page URL` control in the `Page Properties` section
4. Click `Help` in the Properties Explorer section at the right of the screen.

## Expected behavior
When `Help` is clicked the dialog that appears `Filed Content`, should have the tinymce editor

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/53812613-80ddc900-3f21-11e9-86f4-3cd872bffa19.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Creafter CMS v3.1.0-SNAPSHOT

### OS
Linux/Mac

### Browser
Chrome / Firefox

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1066

**Comment by yacdaniel** [comment]
Verified fixed ![image](https://user-images.githubusercontent.com/6722074/53835968-59542400-3f54-11e9-8633-7d9666308e8b.png)
