### ISSUE TITLE
[studio-ui] It would be nice for the cursor to be in the `Site Id` field in the Basic Information screen of the create site dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2907]
## Describe the bug
There's no cursor in any of the fields in the `Basic Information` screen of Create Site

## To Reproduce
1. Login to Studio 
2. Click on `Create Site`
3. Select a blueprint
4. In the `Basic Information` screen, notice there's no cursor in any of the fields.  It would be nice for the cursor to be on the `Site Id` field when the user gets to the `Basic Information` screen

## Expected behavior
It would be nice for the cursor to be in the `Site Id` field in the Basic Information screen of the create site dialog

## Screenshots
![screen shot 2019-03-05 at 10 30 31 am](https://user-images.githubusercontent.com/25483966/53817119-ce166680-3f32-11e9-8a71-39d9aa69d462.png)

Here's a short clip creating a site showing there's no cursor when you get to the `Basic Information` screen of `Create Site`:
https://www.useloom.com/share/eb15ce84ac624e01bd64fa584e7e8640

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-640b78
Build Number: 640b78d072cc507ab75ba36b1d402154c7e52b54
Build Date/Time: 03-05-2019 09:36:35 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1083

**Comment by alhambrav** [comment]
Verified fixed.
