### ISSUE TITLE
[studio] Clustering - Error in the logs when creating a site named the same as a site that has been deleted

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2908]
## Describe the bug
Error in the logs when creating a site named the same as a site that has been deleted

## To Reproduce
1. On server A, setup studio for clustering and create a site using website_editorial, `sitea`
2. On another server, server B,  setup studio for clustering and create a site using website_editorial, `siteb`
3. Wait until the two nodes are synced
4. Stop craftercms on one of the servers, say server A.
5. On server B, delete `sitea`, then create a new site named `sitea` using the empty bp
6. Start server A and notice the logs for both node A and node B

## Expected behavior
There should be no errors in the logs

## Logs
Here's the log for server A after coming back up: https://gist.github.com/alhambrav/70b734b83b3370f892c9eb562646e323
Notice the errors in the middle of the log, but it looks like it was able to recover

Here's the log for server B after server A comes back up: https://gist.github.com/alhambrav/5a63371522a671181ac8dc8f1429a3f8
Notice the error saying: Error while updating published repo for site sitea

### Version
Studio Version Number: 3.1.0-SNAPSHOT-640b78
Build Number: 640b78d072cc507ab75ba36b1d402154c7e52b54
Build Date/Time: 03-05-2019 09:36:35 -0500

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1499

**Comment by alhambrav** [comment]
Verified fixed.
