### ISSUE TITLE
[craftercms] Add WebAppRootListener to all modules that are using webAppRootKey in web.xml

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2909]
## Describe the bug
After switching to log4j 2, due to change of configuration `webAppRootKey` context parameter is not resolved because it was implicitly set by `Log4jConfigListener`

## Additional context
```
<listener>
        <listener-class>org.springframework.web.util.WebAppRootListener</listener-class>
    </listener>
```

## Reference
https://github.com/craftercms/craftercms/issues/2905

**Comment by jdrossl** [comment]
`profile` & `social` use servlet 3.0 and `deployer` uses Spring Boot so the configuration is not done manually for those
