### ISSUE TITLE
[docs] Add a guide to override search facets in the site configuration

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2915]
Add a detailed guide to show:
- How to add new facets
- How to override the default facets

**Comment by alhambrav** [comment]
Assigning to Alfonso, I'm not sure how to check the part: How to override the default facets

**Comment by avasquez614** [comment]
Discussed it with Vita, the documentation seems ok since it explains with detail how facets are added, even though it doesn't explain how to override it, which doesn't seem necessary anyway.
