### ISSUE TITLE
[studio] audit api 2 returns 500 when query with nonexisting site_id

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2916]
## Describe the bug
Studio returns an HTTP Status 500 when audit API 2 is called with a nonexisting `site_id`

## To Reproduce
1. Start authoring and `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=79C6CE0108BFA83222C92ACA5FF0103F" -H "X-XSRF-TOKEN:A_VALUE" -H  "accept: application/json" -X GET http://localhost:8080/studio/api/2/audit?site_id=non_existing`
2. Check response and catalina logs

## Expected behavior
No HTTP 500 Internal Server Error response, maybe a `Resource not found 404`? 

## Logs
https://gist.github.com/yacdaniel/3dcbc9349770ecb028b08f60a9755486

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
Mac

### Browser
What browser did you use to produce the bug.

## Additional context
Also when we query with a non valid `user` :
`curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=79C6CE0108BFA83222C92ACA5FF0103F" -H "X-XSRF-TOKEN:A_VALUE" -H  "accept: application/json" -X GET http://localhost:8080/studio/api/2/audit?user=fakeuser`
the response is empty logs:
```
{"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"total":0,"offset":0,"limit":0,"auditLog":[]}
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1501

**Comment by yacdaniel** [comment]
Verified fixed. HTTP Response Code of 404 is returned when `site_id` is nonexisting in Studio.
