### ISSUE TITLE
[studio] provide consistency for user who do the action in audit log

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2918]
## Describe the bug
There are some actions that are saved with a different user in the audit log.

## To Reproduce
1. Create a user 
![imagen](https://user-images.githubusercontent.com/6722074/53984013-10c87200-40de-11e9-8ddc-d199ef9e77ab.png)

2. Add the user in the `system_admin group`
![imagen](https://user-images.githubusercontent.com/6722074/53984101-3e152000-40de-11e9-827d-69c259f9536b.png)

3. Create a site using empty BP

4. From Remote Repositories in Site config add a new Repository and push site

5. Go to the remote repo and do a small change to `site/website/index.xml
` and pull changes from the Remote Repositories page

6. Go to Main Menu Audit log and check

![imagen](https://user-images.githubusercontent.com/6722074/53984832-c0521400-40df-11e9-9471-e6fb668aba0d.png)

`CREATED` action uses the First Name + Last Name while `CREATE_SITE` the User Name

When pulls and updated a file it uses the git username
![imagen](https://user-images.githubusercontent.com/6722074/53985018-39ea0200-40e0-11e9-982b-bf696c02f07d.png)

![imagen](https://user-images.githubusercontent.com/6722074/53985122-79b0e980-40e0-11e9-86fd-d429d37f3a80.png)
UI only allows to filter for Users that exist in db.

## Expected behavior
same user for the differents actions so it would be clear in logs

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by sumerjabri** [comment]
This is expected. The disk user (direct commits in Git) can't be authenticated. They're a machine user, not a Studio user and therefore will show up in our audit as the identity that's provided by Git.

We do store the source of the activity in the audit, it's called `source`. The UI is currently not showing that and there is a ticket in to fix that and make sure it's visible.

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/2869 see comments around `Source` column.
