### ISSUE TITLE
[docs] Update the monitoring APIs in all products

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2923]
The monitoring APIs for 3.1 have changed across all products.
Studio has the docs on SwaggerHub and therefore need only _remove_ the old v1 monitoring APIs.

**Comment by jdrossl** [comment]
@sumerjabri for studio do we just remove it or do we leave a note pointing to the new one?

**Comment by sumerjabri** [comment]
Please put a note that:
"This API is only available in the new API, for more information, please visit: https://app.swaggerhub.com/apis/craftercms/studio"

**Comment by sumerjabri** [comment]
@yacdaniel Please validate

**Comment by yacdaniel** [comment]
Verified fixed.
