### ISSUE TITLE
[studio] Audit API when called by the global admin don't return global results

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2924]
## Describe the bug
The new Audit API doesn't return events in studio_root for the global admin

## To Reproduce
1. As admin, go to the audit tool in the main menu
2. Note no global events are listed

## Expected behavior
For a global admin, the audit API call should show the system/studio_root events.

## Screenshots
N/A

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
3.1.0-SNAPSHOT

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Can not reproduce with build:
`503a92f389b409e93e22db60dc8da052f1869f7d`

```
Manifest-Version: 1.0
Implementation-Title: Crafter Studio
Implementation-Version: 3.1.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: dejanbrkic
Build-On: 1552318846644
Implementation-Build: 503a92f389b409e93e22db60dc8da052f1869f7d
Implementation-Vendor-Id: org.craftercms
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_51
Implementation-Vendor: CrafterCMS
```

Best way to verify is to create a new environment and just log in. Switch to Audit Log screen. It will show only one record (user log in)
