### ISSUE TITLE
[docs] Update the Audit API v1

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2925]
The audit APIs for 3.1 has changed. Please double check with Dejan if API1 works at all.

If API1 is dead, then please put a note that:
"This API is only available in the new API, for more information, please visit: https://app.swaggerhub.com/apis/craftercms/studio"

If not, put a note indicating that 1 is deprecated and they should use 2.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/700
