### ISSUE TITLE
[studio-ui] Editing Engine Site Config then deleting all contents and saving the config in Studio causes errors in site-config.xml

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2931]
## Describe the bug
Editing Engine Site Config then deleting all contents and saving the config in Studio causes errors in site-config.xml

## To Reproduce
1. Create a site using any bp
2. Click on `Site Config` -> `Configurations` -> `Engine Site Configuration`
3. Notice that the config file is empty, type in some characters then delete everything so it looks like when you first opened the config file
4. Save the config file and notice the errors in the logs:
```
Caused by: org.xml.sax.SAXParseException; systemId: site:/config/engine/site-config.xml; lineNumber: 1; columnNumber: 1; Premature end of file.
```
5. Preview `Home` and notice the error in your browser
<img width="1288" alt="screen shot 2019-03-11 at 3 01 13 am" src="https://user-images.githubusercontent.com/25483966/54105641-0c37de00-43aa-11e9-8aba-4262e708ac1a.png">

## Expected behavior
There should be no errors when you save the engine site config file empty

## Screenshots
Here's a short clip:
https://www.useloom.com/share/cb6f8598a5b04dbea3b1dc998934e75e

## Logs
Here's the logs/stack trace (use https://gist.github.com).
https://gist.github.com/alhambrav/e20222ac4d4d2f58b86b6184652ef325

### Version
Software version if applicable (copy paste from Help > About).
3.0.x and 3.1

3.1 snapshot built 3/8/2019

Studio Version Number: 3.0.21-SNAPSHOT-dd243e
Build Number: dd243ebb01da86fb1ef695897b28bf09e6732b91

### OS
What OS did you use to produce the bug.
OS X

### Browser
What browser did you use to produce the bug.
Chrome browser

**Comment by dejan-brkic** [comment]
@sumerjabri @alhambrav This error is generated by the preview engine. Studio allows users to save the configuration. Even if it is an empty file. Then preview tries to load engine site configuration and errors because it is not a valid XML file.
Possible solutions:
- in the studio, we validate configuration files before writing and show error
- make engine more robust in case of invalid configuration file
Maybe we need to do both because developers can edit configuration files directly in repo

**Comment by sumerjabri** [comment]
@alhambrav please add a valid XML file to all BPs so the act of opening/saving doesn't cause the issue (unless someone deliberately clears the file).

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/1561
PR https://github.com/craftercms/video-center-blueprint/pull/28

**Comment by sumerjabri** [comment]
Verified.
