### ISSUE TITLE
[studio-ui] Shrinking window width doubles toolbar size and overlaps preview frame

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#2932]
## Describe the bug
Shrink browser window with until toolbar renders as two rows. The second row is overlapping preview frame. 

## To Reproduce
1. Create a new site from empty blueprint
2. Shrink browser with until toolbar is rendered as two rows

## Expected behavior
Toolbar does not overlap preview frame

## Screenshots
![screen1](https://user-images.githubusercontent.com/4053827/54149268-0ab3f780-4436-11e9-959d-3cd3a4f15689.png)
![screen2](https://user-images.githubusercontent.com/4053827/54149278-0daee800-4436-11e9-99e4-aff084776736.png)

### Browser
Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1293

**Comment by dejan-brkic** [comment]
Verified
