### ISSUE TITLE
[studio] add/remove user from group is not being logged in audit

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2933]
## Describe the bug
The add/remove user to group action is not being logged in the audit

## To Reproduce

1. Add a new user and then add the user to any of the pre-existing groups
2. Remove the just added user from the group
3. Go to Audit main menu and check the filter by action `Add user to group` and `Remove user from group`

## Expected behavior
Actions of add/remove user from group is logged in audit or `Actions`

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
Linux
What OS did you use to produce the bug.

### Browser
Firefox

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1506

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/54548298-33277e80-496d-11e9-8c63-9d368360148d.png)
