### ISSUE TITLE
[docs] Document how to add search facets and search by meta-data to Crafter Studio

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2934]
Please document how to add additional search by/facets to Studio's internal search.

Please reach out to @jdrossl for guidance.

Related to: https://github.com/craftercms/craftercms/issues/2724

**Comment by jdrossl** [comment]
@sumerjabri is this the same as https://github.com/craftercms/craftercms/issues/2915?

**Comment by sumerjabri** [comment]
Closing as dupe.
