### ISSUE TITLE
[studio] Blueprint screenshots are missing/too big

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2936]
## Describe the bug
Two problems:
- One of the headless blog screenshot might have a typo in the path, therefore, can't be shown in the UI. 
- The Editorial BP screenshots are too long and look weird in the Create Site dialog

## To Reproduce
1. Click Create Site
2. Scroll to Headless Blog Blueprint and check screenshots
3. Scroll to the Editorial BP and scan through the screenshots (note how they're so long, the navigation arrows are well below normal

## Expected behavior
The Screenshots look good.

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/54307320-fdf7e680-4590-11e9-9fbe-e416097c6340.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT.

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by sumerjabri** [comment]
@dejan-brkic ping me if you need help with any of this.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1509

**Comment by yacdaniel** [comment]
Verified fixed. All screenshots are present and with a smaller size.
![image](https://user-images.githubusercontent.com/6722074/54539334-901a3900-495b-11e9-8abd-d5373cb718b0.png)
