### ISSUE TITLE
[studio] API2 response failures

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2937]
## Describe the bug
Some API2 are failing 

## To Reproduce
Try the followings API2
1. Create a user POST /users `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -H  "Content-Type: application/json" -d '{"username":"yaqui223","password":"yaqui","firstName":"yac","lastName":"hurtado","email":"yac2@yac2","enabled":true}' -v -X POST http://localhost:8080/studio/api/2/users` Request response is 500 but user is created  [Catalina log](https://gist.github.com/yacdaniel/d609d1902bd7f5bd07b439af8384a9d0)
2. Create a group and then try to delete it 
DELETE /groups `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json"  -v -X DELETE http://localhost:8080/studio/api/2/groups\?id\=10`  [Catalina log](https://gist.github.com/yacdaniel/4f62ea9850bf60392a0a89b2cb58d34b) Request reponse is 500 with message: 
```
  "response": {
    "code": 1000,
    "message": "Internal system failure: Unknown database error",
    "remedialAction": "Contact support",
    "documentationUrl": ""
  }
```  

3. Update the admin user PATCH /users `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json"  -X PATCH -H "Content-Type: application/json" -d '{"id":1,"username":"admin","password":"string","firstName":"string","lastName":"string","email":"string","enabled":true,"externallyManaged":true}' http://localhost:8080/studio/api/2/users` Request response is 500 but user is updated [Catalina log](https://gist.github.com/yacdaniel/ddd611a259dec589da83896370fbc7b1)
4. Try to delete a user DELETE /users `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -v -X DELETE http://localhost:8080/studio/api/2/users\?username\=yaqui` Request response is 500 but user is deleted [Catalina log](https://gist.github.com/yacdaniel/ebb3639602b21f9ca228163d71bada21)

## Expected behavior
API's working and Response codes are the expected

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
Mac

### Browser
Firefox

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1508

**Comment by yacdaniel** [comment]
Verified fixed, API2 responses codes are OK, no errors in Catalina logs.
