### ISSUE TITLE
[studio] Create new api to get a specific child content.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2938]
**Is your feature request related to a problem? Please describe.**
We need to find a specific child content from a xml.

**Describe the solution you'd like**
The new api should has as a parameter: the parent location, the name of the field, and the file name, to get the specific component that UI needs.

**Comment by sumerjabri** [comment]
We need to have a better design for this. I'm going to close this ticket and create new ones based on a comprehensive design.
