### ISSUE TITLE
[studio-ui] It would be nice to have consistent time zones for global and site audit log entries 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2940]
**Is your feature request related to a problem? Please describe.**
The global audit log from the main menu displays entries in UTC while the site audit log in `Site Config` displays entries using local time EDT

**Site Audit Log:**
![Screen Shot 2019-03-14 at 2 19 41 PM](https://user-images.githubusercontent.com/25483966/54381699-c490ab00-4664-11e9-9fee-6b0752763513.png)

**Global Audit Log:**
![Screen Shot 2019-03-14 at 2 24 14 PM](https://user-images.githubusercontent.com/25483966/54381856-23562480-4665-11e9-83a0-2382d1757588.png)

**Describe the solution you'd like**
It would be nice to have consistent time zones used for displaying global and site audit log entries 

**Version**
Crafter CMS v3.1.0-SNAPSHOT

**OS**
OS X

**Browser**
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1118

Per Russ recommendation studio is remembering the timezone option that the user has chosen.

**Comment by yacdaniel** [comment]
Verified fixed

![timezoneAudit](https://user-images.githubusercontent.com/6722074/56161275-61a57300-5f86-11e9-8340-44186f0c5504.gif)
