### ISSUE TITLE
[studio-ui]  Audit time zone

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2941]
**Is your feature request related to a problem? Please describe.**
It will be easier for people to track down problems/activity in a distributed authoring scenarios.

**Describe the solution you'd like**
Please use the time zone of the client and give an option to select a different time zone.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1074

**Comment by sumerjabri** [comment]
Please refactor per new `Audit` service.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1102

**Comment by sumerjabri** [comment]
Verified.
