### ISSUE TITLE
[studio] Audit log shows the same date for `Modified` and `Created` after editing a page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2942]
## Describe the bug
Audit log shows the same date for `Modified` and `Created` after editing a page

## To Reproduce
1. Create a site using website_editorial
2. Click on `Site Config` -> `Audit` and note the date/times listed for all files (Should be the same as the site was just created)
![Screen Shot 2019-03-15 at 9 30 50 AM](https://user-images.githubusercontent.com/25483966/54435470-ef334000-4706-11e9-9794-ffb7fc38e178.png)

3. Go to the `Home` page and edit
4. Go back to the audit logs to check the dates for the `Home` page (`/site/website/index.xml`)
![Screen Shot 2019-03-15 at 9 32 06 AM](https://user-images.githubusercontent.com/25483966/54435380-bbf0b100-4706-11e9-9029-397b4c0d4dc0.png)

## Expected behavior
Created date of a page should not change after editing the page

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Software version if applicable (copy paste from Help > About).

### OS
Crafter CMS v3.1.0-SNAPSHOT

### Browser
OS X

## Additional context
I checked the audit table in the db, and it does have same date for modified_date and creation_date

**Comment by dejan-brkic** [comment]
Not an issue.
Every action is one entry in the audit log. The problem here is the old DB model where we have created and modified columns and they refer to audit entry. We don't edit audit entries anymore, so the right thing to do would be dropping `modified date` both from UI and DB.

@sumerjabri we can discuss this before making the final decision.

**Comment by sumerjabri** [comment]
Discussed with Dejan and agreed on a new design to have a better audit service and backing database.

**Comment by sumerjabri** [comment]
Closing in favor of: https://github.com/craftercms/craftercms/issues/2967
