### ISSUE TITLE
[studio-ui] It would be nice to have a message/dialog shown on what happened when doing a "Publish by Commit Id" 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2943]
## Describe the bug
When publishing by commit ID, after clicking on the ``Publish`` button, there's no indication in the ui on what happened, whether it was successful or not.

## To Reproduce
1. Create a site using website_editorial
2. Edit the `Home` page (/site/website/index.xm) from the command line or anywhere other than Studio
3. From the command line, commit your changes
```
$ cd crafter-authoring/data/repos/sites/mysite/sandbox/site/website
$ git add .
$ git commit
```
4. Get the commit id after doing the above
```
$ git log
commit f47c9a5bae4184e7b5ff2cb03b90b8ff86adec37 (HEAD -> master)
Author: myuser <myuser@example.com>
Date:   Fri Mar 15 10:09:57 2019 -0400

    edited home page outside of studio

commit 1121d1b90d7b3131025932b6a0f0269d918caa11
Author: admin admin <evaladmin@example.com>
Date:   Fri Mar 15 09:31:57 2019 -0400
```
The commit id I need to publish by commit id is `f47c9a5bae4184e7b5ff2cb03b90b8ff86adec37`

5. Go back to Studio and click on `Site Config` -> `Publishing`
6. Click on the `Publish by Commit ID(s)` tab
7. Paste the commit id from step 4, then click on the `Publish` button.  Notice that a spinner appears after clicking on `Publish` but there is no indication on what happened with the operation.  

## Expected behavior
It would be nice to have a message/dialog shown on what happened when doing a "Publish by Commit Id" , like a `Finished publishing` or `Failed publishing` or something just to let the user know that something did happen. (There is a spinner after clicking on `Publish`, but a message on what happened would be nice)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
Here's a short clip showing steps 5 - 7:
https://www.useloom.com/share/29aa4196850c4c9fbbd7254a0c2f4c7f

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
OS X

### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1156

**Comment by alhambrav** [comment]
@jvega190 
I see a notification dialog after publishing by commit id, but it's displaying the variable name?
![Screen Shot 2019-05-13 at 2 45 54 PM](https://user-images.githubusercontent.com/25483966/57646166-f7382080-758d-11e9-9e23-6176a29ebea8.png)

**Version**
Studio Version Number: 3.1.1-SNAPSHOT-c0a876
Build Number: c0a8763559d20fe86b5dee5e68365506de43a9bd
Build Date/Time: 05-13-2019 14:18:05 -0400

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1162

**Comment by alhambrav** [comment]
Verified fixed.
