### ISSUE TITLE
[studio-ui] Add ability to save a content type without a view template

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2944]
**Is your feature request related to a problem? Please describe.**
Developers of headless content items and other content types that do not have a Freemarker template find the dialog that warns them about the template frustrating.  

**Describe the solution you'd like**
Allow the developer to indicate that the content type does not have a template.
Suggest a check box on the property sheet and ideally the ability to check a box on the dialog "Do not warn users about templates for this content type in the future."

**Describe alternatives you've considered**
A work around developers use is to assign everything to the same empty freemarker template

**Context**
Do not remove the dialog. This dialog is useful and important for pages and components backed with templates.  Developers are just looking for a way to acknowledge that the warning is not relevant for the type.

**Comment by sumerjabri** [comment]
@jvega190 add a checkbox in the property sheet in the form engine under the template field indicating that a template is not required for this:
```
No template required.
```

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1206
studio: https://github.com/craftercms/studio/pull/1645

**Comment by russdanner** [comment]
This does not show up in my existing component (created before 3.1.x)  See example Product here:
https://github.com/russdanner/react-cart-dnd

**Comment by russdanner** [comment]
Is that an upgrade engine question?

**Comment by jvega190** [comment]
@russdanner this needs work in upgrade manager

**Comment by jvega190** [comment]
form definitions updated in all bps
studio: https://github.com/craftercms/studio/pull/1689
videocenter: https://github.com/craftercms/video-center-blueprint/pull/48

**Comment by russdanner** [comment]
Confirmed
