### ISSUE TITLE
[studio][studio-ui] Add sort order configuration to wcm-root-folder sidebar plugin 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2945]
**Is your feature request related to a problem? Please describe.**
The default order is good for pages in general but content authors want folders sorted in a different way for some use cases.  Example:  Blogs and Press releases are often stored under dated folders.  The default sort is alpha-numeric  ascending. This creates a structure that looks like this:
```
/site/website/press-releases/
+ 2017
       + 01
       + 02
       + 03
       + 04...
+ 2018
       + 01
       + 02...
+ 2019
       + 01...
       + 02 ...
```
For these use cases it's more helpful and convenient for the folders to be sorted in the other direction where the latest years and months are first.  EX:
```
/site/website/press-releases/
+ 2019
       + 04
       + 03
       + 02
       + 01...
+ 2018
       + 02
       + 01...
+ 2017
       + 02...
       + 01 ...
```

**Describe the solution you'd like**
Add sort configuration to the module configuration for wcm-root-folder sidebar plugin.
Support the following sort orders:
- No configuration: Default (backward compatibility)
- Alpha ascending (A-z)
- Alpha descending (Z-a)
 
Add parameter
`<sortOrder>default | asc | desc</sortOrder>`

* No sortOrder implies default
* Module currently supports multiple paths.  All included paths would sort according to the configuration supplied.

Example:
```
<modulehook>
  <name>wcm-root-folder</name>                                    
    <params>
       <label>Press Releases</label>
       <path>/site/website/press-releases</path>
       <sortOrder>desc</sortOrder>
       <showRootItem>true</showRootItem>
       <onClick>preview</onClick>
     </params>
</modulehook>
```

**Describe alternatives you've considered**
Sumer also suggested a sort-by configuration with options (date, pretty-name) 
I am not sure we have date information on folders. Need to discuss.

**Additional context**

**Comment by russdanner** [comment]
@rart This can be merged in to the newer effort.

**Comment by sumerjabri** [comment]
This will fold into the new translation capable sidebar browsing tool.

**Comment by rart** [comment]
@sumerjabri what's the status of backend?

**Comment by sumerjabri** [comment]
@rart 
See my comments earlier:
This will fold into the new translation capable sidebar browsing tool.

The translation capable backend is getChildrenByPath/Id which is targetted for 3.1.7, API definition is already in OAS so you can build your code to that and stub it.

**Comment by rart** [comment]
Closed in favour of https://github.com/craftercms/craftercms/issues/3851
