### ISSUE TITLE
[studio-ui] Add a refresh button on the Cluster page 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2946]
**Is your feature request related to a problem? Please describe.**
It would be nice to have something like a refresh button on the Cluster page .  In the current version, the info in the Cluster page does not get updated unless you click on the other main menu items first, then click back to `Cluster`, or you do a full page refresh and click back to `Cluster` 

**Describe the solution you'd like**
A refresh button that will refresh the info in the `Cluster` page would be nice, like the image below:

![Screen Shot 2019-03-15 at 11 58 36 AM](https://user-images.githubusercontent.com/25483966/54451331-0420cb00-4729-11e9-8b5e-c5444094425e.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1115

**Comment by vestrada** [comment]
Hi @alhambrav 
Please confirm it is working good, I'm not able to test it.

Thanks, Vero

**Comment by yacdaniel** [comment]
Verified.
