### ISSUE TITLE
[studio-ui] Add "Create" button in the context nav

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2947]
**Is your feature request related to a problem? Please describe.**
Authors who write blogs, press releases, events and other similar types of content want to be able to quickly create their content with as few clicks as possible.

Most of this content is organized in dated folder structures. Today an author has to open the sidebar, then the top level folder and then browse down through the dated structure before starting to create new content.  If the folders don't exist they have to make them.

**Describe the solution you'd like**
Add a button in the top level context navigation (icon is a _+_, the text is "Create") that opens a drop-down of configured content types. The style here is similar to the pencil and other tools on the right-hand side of the content nav, but it's positioned after the workflow actions.

If no types are configured the button should not show.

Configuring the content type for the button should be done at the content type and has two components:
* Checkbox: Include content type in "Quick Create"
* Path Expression: Quick Create Path
** Path expression should support macros currently supported by data sources today:

{objectId} | Inserts a GUID
{year} | Inserts the current year (4 digit year)
{month} | Inserts the current month (2-digit month of the year)
{yyyy} | Inserts the current year (4 digit year)
{mm} | Inserts the current month (2-digit month of the year)
{dd} | Inserts the current day (2-digit day of the month)

These configuration should be set in the content type property sheet of the form engine and the values are stored in the config.xml for the type.

**Describe alternatives you've considered**
Configure the button in its own configuration similar to the way components are wired in drag and drop today (but plan to change.)

**Comment by sumerjabri** [comment]
@vestrada @rart API is out: https://app.swaggerhub.com/apis/craftercms/studio/3.1.1.3

Implementation to follow.

**Comment by vestrada** [comment]
PR: 
VideCenter: https://github.com/craftercms/video-center-blueprint/pull/39
Studio: https://github.com/craftercms/studio/pull/1621
Studio-ui: https://github.com/craftercms/studio-ui/pull/1192

**Comment by sumerjabri** [comment]
Updates to requirements:
- Always show Quick Create
- If the user clicks on Quick Create, and the server returns an empty list, then show the message:
  - `Nothing is configured for Quick Create. Please ask your Site Administrator to configure some content-types to be quick-creatable.`

**Comment by vestrada** [comment]
PR:
studio-ui: https://github.com/craftercms/studio-ui/pull/1199
studio: https://github.com/craftercms/studio/pull/1635
videocenter: https://github.com/craftercms/video-center-blueprint/pull/41

**Comment by russdanner** [comment]
Confirmed
