### ISSUE TITLE
[studio-ui] Add ability to create custom macros for studio data source and quick create path configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2948]
**Is your feature request related to a problem? Please describe.**
Today data sources support a predefined set of macros that can be used to configure file paths.  Administrators would like the ability to plugin in their own macros.  Example: `/site/products/{productId}/skus`  

**Describe the solution you'd like**
They want to define the macro and then be able to script what it's behavior is.

**Describe alternatives you've considered**

Add a configuration to studio that allows admins to define a macroID/moniker (e.g. productId) and then map it to a client site object that meets an interface and will do the resolution.  This configuration/resolver needs to live in the studio project and move with the project.

**Additional context**
* Today macros are resolved client side.  
* A client side macro resolution can rely on a backend service.

**Comment by malnajdi** [comment]
@russdanner have you implemented a work around to this feature ? Can you give a guide to where/which file should be modified to include such feature ?

**Comment by rart** [comment]
@sumerjabri @russdanner can we skip config and go by convention? 
For instance, all custom "macro ids" — i.e. the ones the system doesn't understand today — would get resolved by calling `/scripts/quick_create/{macroId}.macro.groovy`

**Comment by sumerjabri** [comment]
By convention:
`/scripts/macros/{macroId}.groovy`

Build an example for others to use:
`/scripts/macros/foo.groovy` which returns `bar`

Put this example in all blueprints.

Make it so if the script fails, the UI tells the user what to do:
```
Macro not found, please create a Groovy script in `/scripts/macros/{use the id they used}.groovy` and have it return the value required.
```
The content modeler will then create the macro and things should flow correctly.

**Comment by rart** [comment]
@malnajdi would you be able to provide some examples of how you'd use this?

**Comment by sumerjabri** [comment]
@jdrossl please build a new API (spec first for us to review) that runs a Groovy macro using Engine's capability. We will use Studio's Engine, not the Preview Engine. We will then move the Groovy capability to Commons (not in this ticket, but in a future ticket).

These macros will live here:
`/config/studio/macros/{macro}.get.groovy`

The API will be something like:
`/studio/api/2/macro/{macro-name}.json` with params

Ping me for more information and background.

**Comment by malnajdi** [comment]
> @malnajdi would you be able to provide some examples of how you'd use this?

Well i want to be able to add in the quick create of a page either:

1. the path will include the local needed `[ar,en,pr]` and by that a quick create will appear for each local.
2. i should have the ability to have a + sign in the quick add field in the page content type where i can add n number of paths based on the activated locals.
3. or as you suggested enable the quick create path to accept a macro where we can return a result from a function to make it more dynamic [Disadvantage: Not everyone is a developer, some people uses crafterCMS for it's simplicity where they have very low programming skill. html and basic css]

Note: i think the system should reject any local that is not configured for the site to use.

**Comment by sumerjabri** [comment]
This will be addressed via plugins, see this ticket: https://github.com/craftercms/craftercms/issues/4390
