### ISSUE TITLE
[studio] Add ability to require certain content to be deployed to staging (alone) before it can be deployed to live

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2950]
**Is your feature request related to a problem? Please describe.**
Today staging is a way point to live. If you deploy to live, content will automatically go to staging.  You can also deploy to staging alone and then later deploy to live.

Today, there is nothing that forces a author to stop at staging first.  For some content, this is important.  The ability to go straight to live without first stopping in staging should not be allowed.

**Describe the solution you'd like**
When a user tries to deploy a commit check to see if that commit is in staging.  If it's not, do not allow them to select the live option.

Support configuration that allows an admin to determine which paths this rule should be enforced on.  Not all content requires the same process rigor.

The same error should be applied at the API.  If you attempt a publish to live via the API and any of the paths are a match, the publish should fail if the commits do not already exist in staging.

**Comment by sumerjabri** [comment]
This will be implemented as part of the new workflow engine.
