### ISSUE TITLE
Provide user with ability to see and act on publish history for a content item

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2951]
**Is your feature request related to a problem? Please describe.**
The history dialog does not clearly indicate which version in the history has been published.  Authors want to be able to look at the publishing history for individual content, compare them, revert them etc.

**Describe the solution you'd like**
The publish history in the dashboard, publish dialog, etc. must indicate the version of the item that was published. Additionally, looking at the item history, it should show a numeric version number and indicate if that version was ever published.

The above implies adding a new version number field to the item table and publish_request etc.

We must discuss the approach some more and design a solid approach for this.

**Comment by sumerjabri** [comment]
The closest we can get is to indicate the current `staged` and `live` versions when listing history.

CC @rart
