### ISSUE TITLE
[studio-ui] Add GraphiQL to Site Config

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2952]
Add GraphiQL to the menu in Site Config, it should use the endpoint `/api/1/site/graphql` from the configured preview server.

GraphiQL: https://github.com/graphql/graphiql

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1079
studio: https://github.com/craftercms/studio/pull/1520

**Comment by jvega190** [comment]
video-center2: https://github.com/craftercms/video-center-blueprint/pull/18

**Comment by jdrossl** [comment]
Verified
