### ISSUE TITLE
[javascript sdk] Automatically include dependencies for top level Crafter JS SDK services

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2953]
**Is your feature request related to a problem? Please describe.**
Developers have to to manually include packages for dependencies for top level services to use the javascript SDK
		Added these
			  "dependencies": {
			    "@craftercms/content": "^1.0.0",
			    "@craftercms/search": "^1.0.0",

			But needed to add these to run

			    "@craftercms/utils": "^1.0.0",
			    "@craftercms/classes": "^1.0.0",
			    "@craftercms/models": "^1.0.0",	

**Describe the solution you'd like**
Make it easier to import Crafter services by automatically importing them

**Describe alternatives you've considered**
1. Document the need to import all of the services that need to be imported.
2. Provide a Crafter CLI that builds the scaffolding.

**Comment by sumerjabri** [comment]
Publish SDK.

**Comment by russdanner** [comment]
```
{
  "name": "server-node",
  "version": "1.0.0",
  "description": "This is a node server test app",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@craftercms/content": "^1.1.2",
    "express": "^4.16.3",
    "express-http-proxy": "^1.5.1",
    "url-search-params-polyfill": "^5.0.0",
    "xmlhttprequest": "^1.8.0"
  },
  "proxy": {
    "/api": {
      "target": "http://localhost:8080"
    },
    "/static-assets": {
      "target": "http://localhost:8080"
    }
  }
}```


Confirmed
