### ISSUE TITLE
[studio] Add data source support to remote repository folders in the Sidebar

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2957]
**Is your feature request related to a problem? Please describe.**
Content managers that manage assets in blob storage

**Describe the solution you'd like**
Allow an administrator to map remote folders in repos like S3, Box, CMIS and others so that content authors can manage the content in those stores.

Key operations are:
* CRUD
* Folder create/rename/delete (if supported by store)
* Bulk upload
* See dependencies

**Describe alternatives you've considered**
Authors use external interface to manage content in remote repos storage.

**Additional context**
N/A

**Comment by sumerjabri** [comment]
@rart please review and let's discuss a visual design, then API, then work on front/back.

**Comment by sumerjabri** [comment]
This issue will fold into bucket storage and publishing ticket: https://github.com/craftercms/craftercms/issues/3744
