### ISSUE TITLE
[studio-ui] Selected Items object is not cleared when dashboard items are unchecked by state refresh

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2958]
## Describe the bug
Crafter Studio uses a javascript data structure called `CStudioAuthoring.SelectedContent` to maintain awareness of what items are selected in preview (the current page) and on the dashboard (the checked-boxed items)

This data structure is not properly maintained on the dashboard when users perform actions that cause states to change/icons to refresh.  When the check marks are removed after icon update, the associated item remains in the data structure.

If an author later selects a different content object and publishes (or performs another action) they are acting on the item they selected and the item(s) that were left in the data structure.

## To Reproduce
1. Edit two content items so they appear on the recent activity dashbaord
2. On the dashboard, select and delete one of the items.
3. After icon updates and checkbox is removed from dashboard, open console and print the contents of the following object:  `CStudioAuthoring.SelectedContent`  See video.  Note that the items is still shown in the array
4. select the other edited object.
5. Print the `CStudioAuthoring.SelectedContent` object in the console again. Note there are now (erroneously) 2 objects in the array

## Expected behavior
If the UI removes selected items from the dashboard it must also remove them from the `CStudioAuthoring.SelectedContent` data structure.

This must happen every time items are cleared. Example use cases:
- select a single item and publish it, delete it etc
- select multiple objects
- select items on the dashboard, then find the same item in the sidebar and publish it

## Screenshots
https://www.useloom.com/share/137a7b7f321b48f19d960e72c5d11f65

## Logs
N/A

### Version
2.5.19, 2.5.19E

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
PR: 2.5.x: https://github.com/craftercms/studio-ui/pull/1076

**Comment by vestrada** [comment]
PR: 3.0.x -> https://github.com/craftercms/studio-ui/pull/1077

**Comment by vestrada** [comment]
PR 3.1.x -> https://github.com/craftercms/studio-ui/pull/1078

**Comment by vestrada** [comment]
Hi @yacdaniel can you verify this issue in 2.5, 3.0 y 3.1. Thanks :)

**Comment by yacdaniel** [comment]
Hi @vestrada I found that if I have several edits, approve some of them in the dashboard and then play with the `Show/Hide Live Items` selecting items, the `CStudioAuthoring.SelectedContent`has wrong data
demo:
![show hide live items dashboard](https://user-images.githubusercontent.com/6722074/54925181-67ea8700-4ed3-11e9-81b7-fb62b69eda50.gif)

**Comment by vestrada** [comment]
3.1.x -> https://github.com/craftercms/studio-ui/pull/1084

**Comment by vestrada** [comment]
3.0.x -> https://github.com/craftercms/studio-ui/pull/1085

**Comment by vestrada** [comment]
2.5.x -> https://github.com/craftercms/studio-ui/pull/1087

**Comment by vestrada** [comment]
3.0.x -> https://github.com/craftercms/studio-ui/pull/1092

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1093

**Comment by yacdaniel** [comment]
Verified fixed in `2.5.x`, `3.0.x` and `3.1`.
