### ISSUE TITLE
[studio-ui] Add support for aws uploading/transcoding video data source

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2959]
**Is your feature request related to a problem? Please describe.**
The current datasource for S3 Video Upload does not support transcoding, it just uploads the video using the S3 file upload api.  It would be nice to have a datasource for uploading/transcoding using the AWS Media Convert

**Describe the solution you'd like**
It would be nice to have a datasource for uploading/transcoding video using media convert 

**Describe alternatives you've considered**

**Additional context**

**Version**
Crafter CMS v3.1.0-SNAPSHOT

**Comment by sumerjabri** [comment]
@jdrossl this is a 3.1.1 feature, just adding it to your queue now, please work on 3.1.0 priorities first.

**Comment by jdrossl** [comment]
@sumerjabri some things to consider:
- The service is currently in API1, do we want to move it to API2?
- The service right now doesn't generate an URL, I'm not sure if we can obtain the final URLs for all outputs
- I think the video-picker control expects a single URL from all datasources

**Comment by jdrossl** [comment]
@jvega190 the new API is ready

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1202

**Comment by jvega190** [comment]
Update BPs with new control pending

**Comment by jvega190** [comment]
studio - blueprints updated
https://github.com/craftercms/studio/pull/1643

**Comment by alhambrav** [comment]
Verified.
