### ISSUE TITLE
[studio] Please fix typos and add units to clustering configuration

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2960]
## Describe the bug
There's a typo in the cluster syncers section of the `studio-config-override.yaml` file and it would  also be nice to add units to description of `studio.clustering.sandboxSyncJob.interval` and `studio.clustering.publishedSyncJob.interval`
There's also a typo in one of the messages in the logs:
`Invaid site UUID. Local copy will not be deleted`

## To Reproduce
1. Clone craftercms and build and deploy
2. Open the `studio-config-override.yaml` file and go to line 181, there's a typo, `incativity`.  Also notice lines 174 and 176, it would be nice to note the units used
3. To reproduce the second typo, I'm not sure how to reliably reproduce it for now.  I was running 3 nodes in a cluster... I'm not sure how to reproduce, but 2 of the nodes are vms and the 3rd is my mac... I left it running and I guess computer went to sleep or maybe vm shutdown or something, but when I returned I saw the message in the logs about the node being removed from the cluster and will not be syncing:
```
Cluster member 192.168.1.18 is removed from cluster.  Not syncing with other members
```
and the following message with a typo appeared after logging in again:
```
Invaid site UUID. Local copy will not be deleted
```

## Expected behavior
It would be nice to have the typos fixed and the units for the cluster syncers listed in the yaml file

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Crafter CMS v3.1.0-SNAPSHOT

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1513

**Comment by alhambrav** [comment]
Verified fixed.
