### ISSUE TITLE
[docs] Document how to run on Windows using Docker

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2961]
Starting 3.1, Windows support will happen via Docker. Please document and update to remove references to .bat/old style of running on Windows.

Also, please remove references to .zip files in the bundles since it'll all be .tar.gz.

**Comment by avasquez614** [comment]
@alhambrav There are several changes need on the Quick Start:

1. Change Windows prerequisites to use the prerequisites defines in the Docker Compose Crafter CMS project.
2. Add a note in the installing from bundle and installing from gradle sections to indicate that it doesn't apply to Windows.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/714

**Comment by avasquez614** [comment]
Verified
