### ISSUE TITLE
[engine] Allow doing queries to indexes with a suffix

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2966]
Depends on #2965.

Engine right now does search queries using the site name as the index name. Allow specifying a suffix (or format) through configuration to resolve the actual index name when Deployer creates an index with a custom name. This suffix/format should be at least a global config property, but it might be possible to specify it also through the site config.

**Comment by jdrossl** [comment]
@avasquez614 adding the property to site config sounds dangerous, any author could break the search or use the wrong index

**Comment by avasquez614** [comment]
well the authors can't change site config, only Developers and Admins. But for now being a global property is enough

**Comment by avasquez614** [comment]
Verified
