### ISSUE TITLE
[studio] Refactor the audit service

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2967]
Per the new design, please refactor the audit service.

- Create a new API spec in OAS and send a PR
- Create the backing DB code to migrate existing tables to the new structure
- Implement new internal API and external REST API

**Comment by dejan-brkic** [comment]
API Doc:
PR:
https://github.com/craftercms/studio/pull/1518

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1530

**Comment by sumerjabri** [comment]
@yacdaniel please test API (automate) and test front-end when that's completed: https://github.com/craftercms/craftercms/issues/2869

Please remember that there is another audit tool in Site Config per site (in addition to the new Global Audit).

**Comment by yacdaniel** [comment]
@dejan-brkic there are operations that are not triggering an entry log:
 - Revert
![revertOperation](https://user-images.githubusercontent.com/6722074/55966838-655b9180-5c36-11e9-866e-c5834b656e65.gif)
 - Start/Stop Publisher
![startStopPublisher](https://user-images.githubusercontent.com/6722074/55967032-d00ccd00-5c36-11e9-84d6-aefdb158d6c2.gif)
- The Enable/Disable. Can we clarify about what enable/disable: a page, a user? I tried with both, enable/disable pages/user and did not worked.
![enableDisable](https://user-images.githubusercontent.com/6722074/55967390-7953c300-5c37-11e9-9f1a-dff808a5450d.gif)

**Comment by yacdaniel** [comment]
@dejan-brkic i setup a cluster, logged and added an user in one on the nodes, the audit response has `"clusterNodeId":null`, I tried with different types of operations and the result is the same.
![clusterAudit](https://user-images.githubusercontent.com/6722074/56002441-9f04ba80-5c7f-11e9-9e77-247374d35fc1.gif)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1566

**Comment by yacdaniel** [comment]
Verified.
