### ISSUE TITLE
[studio-ui] Refactor the audit UI screens

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2968]
Please refactor the audit UI tools to conform to the new API:
https://app.swaggerhub.com/apis/craftercms/studio

There are two APIs:
- `/audit` which gets the list of audit records like before, but note the new data model
- `/audit/id` which gets a specific audit record with full details

You'll list the audit table like before but will show a set of new columns. There will also be an "Additional Info" column that contains additional operation parameters, this will be collapsed per record by default, and it can be opened by the user by clicking on a expand/collapse widget in the row. This `expand` operation will cause the call to the second API to get that additional information (which is not available by default to be faster).

Let's meet and discuss what is shown and how to sort/display.

This ticket is pending the API design and publish.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1102

**Comment by vestrada** [comment]
Hi Dejan:
I saw some API Issues:

-> Operations Filters is not working.
-> Dates Filters is not working.
-> Sort date is not working (You can test it from the column).
-> get specific audit api is not responding with the parameters
-> User Name property is empty
-> Site name property is empty

**Comment by dejan-brkic** [comment]
Done
PR:
UI: https://github.com/craftercms/studio-ui/pull/1105
BE: https://github.com/craftercms/studio/pull/1546

**Comment by dejan-brkic** [comment]
Vero

There are some operations missing from the drop down. Here is full list of operations:
```

LOGIN
LOGIN_FAILED
LOGOUT
CREATE
UPDATE
DELETE
MOVE
REVERT
ENABLE
DISABLE
ADD_MEMBERS
REMOVE_MEMBERS
ADD_REMOTE
REMOVE_REMOTE
PUSH_TO_REMOTE
PULL_FROM_REMOTE
REQUEST_PUBLISH
APPROVE
APPROVE_SCHEDULED
REJECT
PUBLISH
STOP_PUBLISHER
START_PUBLISHER
REMOVE_CLUSTER_NODE
```
`Parameters` is an array of objects. UI is not parsing it correctly that is why it does not show up.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1109

**Comment by sumerjabri** [comment]
@vestrada 
Please change the language:
![image](https://user-images.githubusercontent.com/3931908/56153615-a03a2e00-5f84-11e9-815e-91ee8a6c70d1.png)
to: "There are no additional parameters."

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1124

**Comment by sumerjabri** [comment]
Verified.
