### ISSUE TITLE
[studio-ui] Add the option for Solr disabled/hidden when creating a site based on a bp for 3.1

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2969]
**Is your feature request related to a problem? Please describe.**
For the latest 3.1 in develop, when creating a site using Solr for search engine, bps that has ES queries will give a bunch of errors in the logs and an error when you preview the page in Studio.

**Describe the solution you'd like**
It would be nice to have the option for Solr as search engine disabled/hidden when creating a site based on a bp for bp's with ES queries by adding a flag in the yaml file for blueprints. (I think it's the `craftercms-plugin.yaml` file?) so new users playing around with creating sites will not get the error

**Describe alternatives you've considered**

**Additional context**

**Comment by sumerjabri** [comment]
We need to add a new field in the `craftercms-plugin.yaml` to indicate the search engine supported by the blueprint, and then return that to the UI. The UI will then limit/honor the search engine choice by the BP.

**Comment by sumerjabri** [comment]
@dejan-brkic please note this is 3.1.1, so after all 3.1.0 ticks.

**Comment by sumerjabri** [comment]
@vestrada Please remove the search engine choice from the dialog. It will be automatically decided by the backend.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1112

**Comment by alhambrav** [comment]
Verified.
