### ISSUE TITLE
The app not allow to duplicate the global entry tree.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#297]
Environment template

Device: MacBook Pro

OS: El capitan.

Browser: Chrome, Firefox, Safari.

Environment: Local Environment Crafter 2.5.2

Description/Steps Template

PRECONDITIONS:
1. N/D

REPRODUCIBILITY LEVEL: Always

STEPS:
1. GO to: http://localhost:8080/studio#/login
2. Create a new site.
3. Go to “Preview”.
4. Select the “Global Entry”.
5. Click on “Duplicate”option in the menu.
6. In the new window type a name of the “Global Entry” to duplicate.
7. Click on “Save and Close”
8. Find the “Global Entry” duplicated.

CURRENT RESULT:
The app not allow to duplicate the global entry tree.

EXPECTED RESULT:
The app should be duplicated all content, folder, etc properly.

Evidence: http://www.screencast.com/t/m3mPmACTu

**Comment by russdanner** [comment]
I dont understand why this is a bug....

**Comment by russdanner** [comment]
You can duplicate any object in the tree.
Also this bug doesn't indicate what site blueprint you are working with... which is pluton.
The pluton site is NOT part of the product.  It is just a site that is installed in to the product.

**Comment by russdanner** [comment]
Closing as not an issue for now.
