### ISSUE TITLE
[engine] Issue with log4j2 config reload

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2971]
## Describe the bug
When a change is made to the logging configuration at 
`bin/apache-tomcat/shared/classes/crafter/engine/extension/logging.xml` 
engine shows the following error: 
`ERROR Attempted to append to non-started appender circularQueueLogAppender`

It looks like the `circularQueueLogAppender` doesn't follow the log4j2 lifecycle as expected.

### Version
3.1

**Comment by jdrossl** [comment]
This was fixed in https://github.com/craftercms/engine/pull/249

**Comment by avasquez614** [comment]
Verified
