### ISSUE TITLE
[engine] Support SAML2 authentication without Profile

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2972]
Remove the dependency on Profile for SAML2 authentication.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 what does it mean to support SAML2 without Crafter Profile? because right now we use the headers to lookup/create the corresponding profile.

**Comment by avasquez614** [comment]
That is the part we need to discuss. We need to probably add Spring Security, remove the code that calls the Profile Security Provider directly and make a proxy to the Security Provider from Spring Security. The general idea is that when the SAML2 authentication comes the user is automatically authenticated and a `User` or `Authentication` instance is provided for reference.

**Comment by avasquez614** [comment]
Verified
