### ISSUE TITLE
[studio] Creating a site from VC blueprint doesn't work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2974]
## Describe the bug
Creating a site based on VC fails due to an upgrade manager failure.

## To Reproduce
1. Create a site based on VC BP
2. See error

## Expected behavior
- The site should be created successfully
- The site should have YouTube content like https://vc.craftercloud.io

## Screenshots
N/A

## Logs
https://gist.github.com/sumerjabri/c8dfcf7a98368df36ed324fb57ebf902

### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-75b50a
Build Number: 75b50a9c5040f7e261622e366010dfa98f7a4836
Build Date/Time: 03-21-2019 09:37:11 -0400
```

### OS
Ubuntu 18

### Browser
Chrome

## Additional context
N/A

**Comment by jdrossl** [comment]
This was fixed in https://github.com/craftercms/studio/pull/1524

**Comment by dejan-brkic** [comment]
Verified
