### ISSUE TITLE
[studio] Site creation failure rollback doesn't remove Git repos

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2975]
## Describe the bug
Failure in the upgrade manager doesn't rollback site creation properly. It seems that the Git repos on disk are not removed.

## To Reproduce
1. Create a site that fails during the upgrade manager execution, like VC
2. See it fail
3. Create a site using Empty with the same name

## Expected behavior
Rollback should clean things up properly

## Logs
```
[WARN] 2019-03-21T10:16:41,348 [http-nio-8080-exec-6] [impl.ViewNotResolvedExceptionHandler] | Resource '/{{media.screenshot.url}}' not found 
[ERROR] 2019-03-21T10:16:58,719 [http-nio-8080-exec-6] [site.SiteServiceImpl] | Error while creating site: vc ID: vc from blueprint: org.craftercms.blueprint.empty. Rolling back. 
java.lang.IllegalStateException: Repository already exists: /home/sumer/code/crafter/craftercms/crafter-authoring/data/repos/sites/vc/sandbox/.git

```

### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-75b50a
Build Number: 75b50a9c5040f7e261622e366010dfa98f7a4836
Build Date/Time: 03-21-2019 09:37:11 -0400
```

### OS
Ubuntu 18

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1531

**Comment by sumerjabri** [comment]
Verified.
