### ISSUE TITLE
[studio] Error when upgrading

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2977]
## Describe the bug
When you upgrade your develop branch, you get an error:
```
java.io.FileNotFoundException: class path resource [crafter/studio/upgrade/3.1.0.5/sample-form-control-rte-setupt-tinymce5.xml] cannot be opened because it does not exist
```
I think because of a typo in the `pipelines.yaml` file on lines 277 and 278
```
path: /config/studio/administration/samples/sample-form-control-rte-setupt-tinymce5.xml
file: crafter/studio/upgrade/3.1.0.5/sample-form-control-rte-setupt-tinymce5.xml
```
where, `setupt` should be `setup`?

If you stop and start craftercms after the error above, you get a different error:
```
Caused by: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: ALTER TABLE `cluster` CHANGE COLUMN `local_ip` `local_address` VARCHAR(40) NOT NULL
.  Cause: java.sql.SQLSyntaxErrorException: (conn:12) Unknown column 'local_ip' in 'cluster'
Query is : ALTER TABLE `cluster` CHANGE COLUMN `local_ip` `local_address` VARCHAR(40) NOT NULL
```

## To Reproduce
1. Checkout craftercms from a prior date, I used Oct 4, 2018 and create a site
2. Upgrade craftercms to the latest 
```
$ ./gradlew selfupdate
$ ./gradlew init
$ ./gradlew -PoverwriteConfig=true upgrade
```
3. Start Studio, notice the error in the logs `./gradlew -Penv=authoring start` , see logs **(1)** below
4. Stop craftercms and start again.  Notice the error in the logs looks different from the previous error, see logs **(2)** below

## Expected behavior
There should be no errors

## Logs
**(1)** https://gist.github.com/alhambrav/05078ae80571f2cacdcdfa06d1ec201d
**(2)** https://gist.github.com/alhambrav/77fd2d24d840855fd22bfe8c6d9d5309

### Version
3.1-SNAPSHOT

### OS
OS X

### Browser
What browser did you use to produce the bug.

## Additional context
Is it possible for the second set of errors, that since it has already done parts of the upgrade up until it reached the failure during the first run, that when you try to upgrade again (when you start up Studio again), that you have a partially upgraded stuff already so it couldn't do the things it already did when it first failed and reports a failure?  
What happens to the things already upgraded, when during an upgrade an error happens (things already finished then an error happens)? Is it rolled back?  Thanks!

**Comment by dejan-brkic** [comment]
Can not reproduce it

```
Studio Version Number: 3.1.0-SNAPSHOT-3e88c1

Build Number: 3e88c1e7b4fa79b7ca0e2569eb59196bff02c603
```

**Comment by alhambrav** [comment]
Verified typo has been fixed and no error.
