### ISSUE TITLE
[studio-ui] add configuration to enable drag-drop of components without form open

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2978]
**Is your feature request related to a problem? Please describe.**
Today every drag-drop in preview opens a form, regardless if there are required fields or sensible defaults to a component.  Drag and drop is nicer when the user does not need to work with a form immediately on drop.  

**Describe the solution you'd like**
Allow the the administrator to indicate in the configuration that the form should not be opened (and the component should be rendered immediately) on drag-drop instead of opening a form in the preview-components XML.

Example Configuration:

```
<config>
   <category>
      <label>General</label>
      <component>
                <label>Web Canvas</label>
                <type>/component/quote</type>
                <path>/site/components</path>
                 <openFormOnInsert>false</openFormOnInsert>
      </component>
   </category>
</config>
```
If this tag is present and is false in the component block, do not open the form. Refresh the preview immediately.
`<openFormOnInsert>false</openFormOnInsert>`

If this tag is true or is not present, open the form.

**Describe alternatives you've considered**
The form engine could evaluate its state and if no fields are required it, based on a hint that it was called from a drag-drop operation it could immediately close itself.  Due to the IFRAME implementation of the form engine, this would cause a weird user experience in which the user would see the form engine's container. 

 I think it's better at this time to leave this decision in the hands of the administrator.  If they know the component has sensible default values and behaviors they can set the flag.

**Comment by yureii00** [comment]
This components needs a specific content type, with auto-filename.
The internal-name is usually a required field unless it has a default value.
How is going to be handle the internal-name for each drag and drop component?

**Comment by russdanner** [comment]
Hi @yureii00 
The values to internal name (and all field controls for that matter) will be set by defaults in the field configuration in the form definition.

**Comment by sumerjabri** [comment]
@yureii00 @rart please discuss the approach/solution with me when ready for review.

**Comment by sumerjabri** [comment]
@russdanner let's discuss this and its relation to Page Builder.

**Comment by sumerjabri** [comment]
PageBuilder obviates this.
