### ISSUE TITLE
[studio-ui] "Create site" dialog ux enhancements

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2979]
## Describe the bug
Update create site dialog to address the following UX issues and minor bugs:

1. Change the first tab label (Blueprint) to (Choose a Blueprint),
1a. Anything we can do to make it obvious that the BP selector scrolls without relying on the scrollbar to show is a win.  Some browsers don't show the scroll unless the user tries to scroll the region (See video)
2. When a user clicks the option to create a site from a remote, remove the BP selection area
3. Remove the preview images in the blueprint carousel and replace them with "dots." This shows the user that there are multiple previews and lets them randomly access them without the issues associated with tiny image previews.
4. On the repository screen radio buttons are cut off (See video)
5. On the review screen use the friendly name for the BP, not the ID.

## Screenshots
https://www.useloom.com/share/35cbb7e289eb4d5d8377c5c77d7afc7f

### Version
Studio Version Number: 3.1.0-SNAPSHOT-528d1d
Build Number: 528d1dd83f93b4470398d77ad373ce8ee52276a8
Build Date/Time: 03-21-2019 14:13:17 -0400

### OS
MacOSX 

### Browser
Chrome

**Comment by sumerjabri** [comment]
@vestrada Please remove the lower thumbnails. Just keep the main image, the dots, and the right/left arrows. That should be enough.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1090

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio/pull/1527

**Comment by vestrada** [comment]
Video-center -> PR: https://github.com/craftercms/video-center-blueprint/pull/21

**Comment by sumerjabri** [comment]
Please move the screenshots to the blueprints and wire per Dejan's guidance.

**Comment by vestrada** [comment]
@dejan-brkic please make your changes in BE.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1537

**Comment by russdanner** [comment]
- Please put the dots for the other images below the border of the preview image.  These blend in to the pictures and in some cases are almost invisible.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1103

**Comment by russdanner** [comment]
Confirmed.
