### ISSUE TITLE
Copy and Paste pages with content-as-folder false not working properly

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#298]
1) create a page, that has `<content-as-folder>true</content-as-folder>` in content type `config.xml`
2) then, create a child page inside it, that has `<content-as-folder>false</content-as-folder>` in content type `config.xml`
3) try to copy/paste the same child page inside the same folder, weird behaviour starts to happen

Before pasting:
<img width="408" alt="screen shot 2016-11-29 at 2 49 54 pm" src="https://cloud.githubusercontent.com/assets/813023/20728404/304ebe9a-b643-11e6-9efd-4b12c5e6348b.png">

After pasting
<img width="231" alt="screen shot 2016-11-29 at 2 50 10 pm" src="https://cloud.githubusercontent.com/assets/813023/20728400/2a360bc6-b643-11e6-921a-0645c4cabce1.png">

Implementation-Vendor: CrafterCMS
Implementation-Title: Crafter Studio
Implementation-Version: 2.5.2-SNAPSHOT
Implementation-Vendor-Id: org.craftercms
Implementation-Build: 7faefe11c44cac7e9a9e1b546887c011f5606f62

**Comment by russdanner** [comment]
For the record... weird behavior is a terrible description of a problem.

**Comment by russdanner** [comment]
It looks like it assumes or turns it in to an index.xml.  
This will need further investigation before it can be assigned.  Not clear at the moment if backend or front end.  I would guess back-end but that's just a guess.

**Comment by russdanner** [comment]
Gus, can you try what's discussed in this ticket and look on the file system to see what is happening to the actual file.  My assumption is that it is being moved to a /index.xml

**Comment by asotog** [comment]
The weird behaviour:  is that it seems turning the new pasted item into index.xml, i checked the front-end flow, it is just calling:

Copy:
POST http://localhost:8080/studio/api/1/services/api/1/clipboard/copy-item.json?site=tests
PAYLOAD
{"item":[{"uri":"/site/website/en/parent-test/child-test.xml"}]}

Paste:
http://localhost:8080/studio/api/1/services/api/1/clipboard/paste-item.json?site=tests&parentPath=/site/website/en/parent-test/index.xml&nocache=Wed%20Nov%2030%202016%2009:41:37%20GMT-0600%20(CST)


<img width="917" alt="screen shot 2016-11-30 at 9 45 14 am" src="https://cloud.githubusercontent.com/assets/813023/20759171/c029c8ea-b6e1-11e6-8db4-748e41908bc7.png">

**Comment by gortizcrafter** [comment]
Sure, let me check.!

**Comment by russdanner** [comment]
Ok, Thanks AJ!  Thats def a backend issue as I was guessing.

**Comment by gortizcrafter** [comment]
I see this bug with Alejandro and the behavior only is present in version 2.5.2, In the pass version 2.5.1 the bug isn't present.

**Comment by dejan-brkic** [comment]
fixed issue PR #409 #410
