### ISSUE TITLE
[studio-ui] Search UI bugs and UX enhancements

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2981]
## Describe the bug
Correct the following UI bugs:
1. Clicking enter in search box after typing keyword returns no results/clears results
2. Clicking the search button on search box after typing keyword returns no results/clears results
3. Updating filters (e.g. Width) when no values set result in NAN being placed in the input
4. It seems like you can confuse the SelectedItems object that drives the context bar so that it thinks multiple items are selected.  I don't have exact steps for this but whenever you unselect and item manually or clear the results/update the results you must make sure this state object is correct (matches what the user sees as selected.)

Make the following UX enhancements
1. When are no results do not show select all.
2. Clearly demarcate the area between the search parameters and the results.  Keywords, sorts/filters are search parameters. Counts, select all are part of the results.  Don't show result information when there are no results to show.
3. If there is an error on the backend, clear the current results and tell the user with a simple message that "There was an issue completing your search, please contact the Administrator if this issue persists."
4. Change the eyeball icon on images/videos to a magnify icon
5. Move the "clear al"l on filters inside of each filter, it's confusing on the heading area. 
6. Consider making filters a tab and having the user "Add a filter" then configure it.  Then a X on the filter to remove it makes sense. 
7. The check boxes on the items are too light - it's not clear that they are checkboxes.

## Screenshots
https://www.useloom.com/share/770e821f1f4e41e695234e3c94cb80ab

### Version
Studio Version Number: 3.1.0-SNAPSHOT-528d1d
Build Number: 528d1dd83f93b4470398d77ad373ce8ee52276a8
Build Date/Time: 03-21-2019 14:13:17 -0400

### OS
OSX

### Browser
Chrome

**Comment by sumerjabri** [comment]
@jdrossl content is not being searched. I'm adding you in case it's a backend concern.

**Comment by jdrossl** [comment]
@jvega190 the issue in the backend it's fixed now

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1080

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1081 - langBundle updated for error message on API fail

**Comment by russdanner** [comment]
Confirmed
