### ISSUE TITLE
[studio] Add filtering to Audit service by date and primary target value

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#2982]
For the API
https://app.swaggerhub.com/apis/craftercms/studio/2.0.21#/audit/getAuditLog

Please add the ability to:
- filter by site id (it's there, but needs to be better documented and explain that it's optional for super admin)
- filter by site name
- filter by date range
- filter by regex for the primary target value
- filter by origin
- filter by username
- filter by operation
- filter by cluster node id
- sort by:
  - date
- sort order: ASC, DESC

Think of allowing the UI to filter by a user doing an action around a date against a path.

**Comment by dejan-brkic** [comment]
Update docs
PR:
https://github.com/craftercms/studio/pull/1521

**Comment by sumerjabri** [comment]
@dejan-brkic I made many changes to this ticket. Let's discuss on Monday.

I removed many of the sort by, and I added more filter bys. I also changed the model in the design document and highlighted the new changes.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1530

**Comment by sumerjabri** [comment]
@yacdaniel please validate.

**Comment by yacdaniel** [comment]
Verified.
