### ISSUE TITLE
[search] Create Site with Elastic fails due to casting error during indexing operation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2983]
## Describe the bug
I created a site from an existing Git repository which failed to create due to an indexing failure caused by a casting exception.

## To Reproduce
1. Go to create a site based on a remote
2. Use the following repository: https://github.com/russdanner/react-cart.git
3. Create the site, see error/roll back in UI
4. See exception in logs

## Expected behavior
Create site should succeed

## Logs
```
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at org.craftercms.studio.impl.v2.service.search.internal.SearchServiceInternalImpl.processSearchHit(SearchServiceInternalImpl.java:314) ~[classes/:3.1.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.service.search.internal.SearchServiceInternalImpl.lambda$processResults$4(SearchServiceInternalImpl.java:376) ~[classes/:3.1.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_101]
```
### Version
Studio Version Number: 3.1.0-SNAPSHOT-528d1d
Build Number: 528d1dd83f93b4470398d77ad373ce8ee52276a8
Build Date/Time: 03-21-2019 14:13:17 -0400

### OS
ANY

### Browser
ALL

**Comment by russdanner** [comment]
I was not able to create the site based on the steps show above.
I got the following error and no error in the log.  As a developer trying to create from a remote, I cannot tell what the issue is or how to fix.  

If the site cannot be created for a legitimate reason the system must give the developer/admin enough information to correct the issue.

Error:
Error: Internal server error: org.craftercms.studio.api.v1.exception.SiteCreationException: Error while creating site: reactcart ID: reactcart as clone from remote repository: origin (https://github.com/russdanner/react-cart.git). Rolling back.

**Comment by jdrossl** [comment]
The issue is caused by the upgrade manager `org.craftercms.studio.api.v2.exception.UpgradeNotSupportedException: Site 'cart' from 3.0.x can't be automatically upgraded`, it will be fixed with https://github.com/craftercms/craftercms/issues/3005

**Comment by jdrossl** [comment]
@russdanner the changes needed are now merged and you should be able to create the site using the repo without any changes

**Comment by russdanner** [comment]
Confirmed
