### ISSUE TITLE
[studio-ui] Sign in from login screen causes app to jump around momentarily

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2984]
## Describe the bug
sign in from sign in screen causes app to jump around momentarily

## To Reproduce
1. open studio and sign in
2. note UI jumps/resizes in a way that is not user friendly
3. sign out and repeat to see it do it again

## Expected behavior
Sign in should take the user directly to the sites dashboard without resizing the screen.
The issue may be the sites dashboard and not the sign-in itself.  I can't tell.

## Screenshots
https://www.useloom.com/share/8c7d46c838eb406da9bf1506a0e24031

### Version
Studio Version Number: 3.1.0-SNAPSHOT-528d1d
Build Number: 528d1dd83f93b4470398d77ad373ce8ee52276a8
Build Date/Time: 03-21-2019 14:13:17 -0400

### OS
OSX

### Browser
Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1097

**Comment by russdanner** [comment]
This can still be reproduced
https://www.useloom.com/share/228d6724adba4ea8b74b7e78cab06b20

**Comment by russdanner** [comment]
Studio Version Number: 3.1.0-SNAPSHOT-08e8d6
Build Number: 08e8d6cc66776b6fd11d7f38e2bec24bce09d497
Build Date/Time: 03-28-2019 19:04:26 -0400

**Comment by jvega190** [comment]
Not being able to reproduce, asked QA and not being able to reproduce it either. @russdanner please let me know if this is still reproducible for you in current build

**Comment by russdanner** [comment]
Not reproducible in this build:
Studio Version Number: 3.1.0-SNAPSHOT-3e248b
Build Number: 3e248b0cf3ef13cf24e471809236e995c35b51bf
Build Date/Time: 04-08-2019 09:41:02 -0400
