### ISSUE TITLE
[studio-ui] TinyMCE5 RTE stores fully qualified URL on insert image

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2987]
## Describe the bug
[studio-ui] TinyMCE5 RTE stores fully qualified URLs (to the preview server) in the content on insert image.  Deploying this content to a non-preview environment will result in broken images.

## To Reproduce
1. Open editorial site
2. Go to to the content type editor, edit the home page and add a data source to hero text
3. Go to preview, edit the hero text and insert an image, save
4. View frame source and see fully qualified URL in markup (It's also in the XML at the model layer.)

## Expected behavior
Either the data sources must insert a preview URL that is cross environment friendly (a relative url or a S3 bucket URL etc)
OR
The RTE must give the data source the chance to clean up the preview version of the URL prior to saving the content. On the old RTE the data sources got an event that was fired on before save in the form engine where they could modify the HTML in the editor (and clean up.)

### Version
Studio Version Number: 3.1.0-SNAPSHOT-528d1d
Build Number: 528d1dd83f93b4470398d77ad373ce8ee52276a8
Build Date/Time: 03-21-2019 14:13:17 -0400

### OS
All

### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1091

**Comment by russdanner** [comment]
Verified
