### ISSUE TITLE
Logging Level tools should allow you to set levels Engine as well

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2989]
**Is your feature request related to a problem? Please describe.**
The logging level tool on the Site Config panel of Crafter Studio should make it easy to set logging levels of Crafter Engine (in addition to studio.)

**Describe the solution you'd like**
Add a tabs for Crafter Studio and Crafter Engine.  This gives an approach where we can add other services later as their configuration is pulled in to and deployed from Studio.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/2086

**Comment by sumerjabri** [comment]
This seems to be a dupe of the ticket mentioned above. Re-eval.
