### ISSUE TITLE
[studio-ui] GraphiQL looks like it's shared between all the sites in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2990]
## Describe the bug
GraphiQL looks like it's shared between all the sites in Studio. 

## To Reproduce
1. Create two sites using the website_editorial bp `site 1` and `site 2`
2. Preview `site 1` and click on `Site Config` -> `GraphiQL`
3. Enter a query
```
{
    # query for content-type '/page/article'
    page_article {
      total # total number of items found
      items { # list of items found
        # content-type fields that will be returned 
        # (names are based on the content-type configuration)
        title
        author
        date_dt
      }
    }
  }
```
4. Preview `site 2` and click on `Site Config` -> `GraphiQL`
5. Notice that there's already a query in GraphiQL for `site 2`, which is the exact query we entered in `site 1`
6. Delete the query in GraphiQL in `site 2`
7. Go back to preview `site 1` and click on `Site Config` -> `GraphiQL`
8. Notice the query we entered for `site 1` in step 3 is gone.

It looks like GraphiQL is shared by all sites in Studio

## Expected behavior
There should be a separate instance of GraphiQL for each site in Studio

## Screenshots
Here's a short clip:
https://www.useloom.com/share/176ef97156cb438cb15f70ed21619d99

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-d43dc5
Build Number: d43dc5dbf88c42cb45d060457a8a1048c7cfd896
Build Date/Time: 03-22-2019 07:02:05 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1086

**Comment by alhambrav** [comment]
Verified fixed
