### ISSUE TITLE
[search] Max bytes length exceeded when rte has a lot of text

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2991]
## Describe the bug
There's a message in the elasticsearch logs that max bytes length exceeded when the RTE has a lot of text.

## To Reproduce
1. Create a site using website_editorial bp
2. Edit one of the articles
3. Click on the RTE and copy all existing text in the RTE
4. Paste the text you copied multiple times in the RTE, so you end up with more than 6000 words, then save your changes
5. Open the elasticsearch.log file and notice the error:
```
org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length;
```
6. Notice also that when you get this message, and go to `Site Config` -> `GraphiQL` and query for the number of articles:
```
{
    # query for content-type '/page/article'
    page_article {
      total # total number of items found
      items { # list of items found
        # content-type fields that will be returned 
        # (names are based on the content-type configuration)
        title
        author
        date_dt
      }
    }
  }
```
You'll get 8 instead of 9 articles, and no error message in the tomcat log

## Expected behavior
There should be no exceptions in the log when entering a large number of text in the RTE and I guess, GraphiQL should return the correct number of articles in the site all the time

## Screenshots
Here's a short clip showing how I copied and pasted text in the RTE.  It also shows using GraphiQL to query how many articles are there before editing one of the articles (shows 9 articles), and after editing one of the articles to contain more than 6000 words in the RTE, where GraphiQL now returns only 8 articles:
https://www.useloom.com/share/0a9dd430bb0442c5b508f8b200ef7acd

## Logs
https://gist.github.com/alhambrav/75eea2f7c7223997ddd696ce7d10e5cf

### Version
Studio Version Number: 3.1.0-SNAPSHOT-d43dc5
Build Number: d43dc5dbf88c42cb45d060457a8a1048c7cfd896
Build Date/Time: 03-22-2019 13:00:53 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by jdrossl** [comment]
Also happens in Solr so it is also for 3.0.x

**Comment by alhambrav** [comment]
Verified fixed
