### ISSUE TITLE
[studio-ui] RTE (TinyMCE 5) unsaved content edits disappear when you click on the options for repeating control

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2992]
## Describe the bug
RTE (TinyMCE 5) unsaved content edits disappear when you click on the options for repeating control

## To Reproduce
1. Create a site using website_editorial
2. Edit one of the articles
3. In the repeating control group containing an RTE, click on `Add Another`
4. Enter some text in the new RTE, then click on `Add Another` on the RTE you're working on
5.  Notice the text you just entered disappeared.  Content you just typed also disappears when you click on `Move Up` or `Move Down`
6. Open another article for editing
7.  Edit a section of the article by adding some text, then click on `Add Another`
8. Notice the text you just entered disappeared

## Expected behavior
Text entered should remain (not disappear) when clicking on `Add Another` or `Move Up` or `Move Down`

## Screenshots
Here's a short clip:
https://www.useloom.com/share/bf5170dc49e14818a5edd26ccc381853

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-d43dc5
Build Number: d43dc5dbf88c42cb45d060457a8a1048c7cfd896
Build Date/Time: 03-22-2019 13:00:53 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1088

**Comment by alhambrav** [comment]
Verified text does not disappear when clicking on any repeating group control option
