### ISSUE TITLE
[studio-ui] "Approve & Publish" option not available for user with publisher rights

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2994]
## Describe the bug
"Approve & Publish" option not available for user with publisher rights

## To Reproduce
1. Login as user `admin` to Studio and create a site using website_editorial 
2. Create a user, say `jane` and add to group `site_author`
3. Logout user `admin`
4. Login as user `jane` (user in group `site_author`)
5. Edit a page and save, then click on `Request Publish` from the context nav, the edited page should display the in-workflow icon in the context nav and the Sidebar
6. Logout user `jane` (user in `site_author` group) and Login user `admin`
7. From the Sidebar, right click on the page requested for publish by user `jane`, notice there's no option to `Approve and Publish`
8. Preview the page user `jane` requested for publish, notice there's no option to `Approve and Publish` in the context nav

## Expected behavior
The `Approve and Publish` link should appear for users with publisher rights for items that are in workflow

## Screenshots
<img width="1162" alt="Screen Shot 2019-03-25 at 7 48 45 AM" src="https://user-images.githubusercontent.com/25483966/54917683-b21f3880-4ed2-11e9-99dd-1a555200f119.png">

No option to approve and publish when right clicking item in-workflow:
<img width="692" alt="Screen Shot 2019-03-25 at 7 51 20 AM" src="https://user-images.githubusercontent.com/25483966/54917849-19d58380-4ed3-11e9-8c9f-992f22108df6.png">

## Logs
Here's a short clip:
https://www.useloom.com/share/0d06f1d147b44edaaba718c6a4950439

### Version
Studio Version Number: 3.1.0-SNAPSHOT-d43dc5
Build Number: d43dc5dbf88c42cb45d060457a8a1048c7cfd896
Build Date/Time: 03-22-2019 13:00:53 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1095

**Comment by alhambrav** [comment]
Verified fixed.
