### ISSUE TITLE
[studio-ui] Validate `Default Type` for datasources

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2996]
When configuring a datasource with a specific type, Studio should validate the value or offer a list of the existing content-types to select one.

<img width="437" alt="Screen Shot 2019-03-25 at 2 22 48 PM" src="https://user-images.githubusercontent.com/1236955/54951647-cb8fa700-4f09-11e9-8234-4f88b92ffc5a.png">

**Comment by sumerjabri** [comment]
Replaced by FE2
