### ISSUE TITLE
[studio-ui] Queries in GraphiQL disappears when you click on other "Site Config" items then come back

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2997]
## Describe the bug
Queries in GraphiQL disappears when you click on other "Site Config" items then come back, and items at the top from other `Site Config` items are still visible when you go to GraphiQL after visiting other `Site Config` items, such as `Content Types`

## To Reproduce
1. Create a site using the Headless_store bp
2. From the `Sidebar` click on `Site Config` then `GraphiQL`
3. Type in a query
```
{
 # query for content-type '/component/product'
    component_product (offset: 0, limit: 10) {
      total # total number of items found
      items { # list of items found
        # content-type fields that will be returned 
        # (names are based on the content-type configuration)
        name_s
        price_d
        company
      }
    }
}
```
![Screen Shot 2019-03-26 at 10 46 56 AM](https://user-images.githubusercontent.com/25483966/55006690-87a5ac00-4fb4-11e9-9f32-af0152e251b5.png)

4. Click on `Content Types`
![Screen Shot 2019-03-26 at 10 47 33 AM](https://user-images.githubusercontent.com/25483966/55006729-98562200-4fb4-11e9-9609-ba46384ee8ec.png)

5. Click on `GraphiQL, notice the query you entered has disappeared and notice too at the top that items for `Content Type` is still displayed at the top
![Screen Shot 2019-03-26 at 9 56 36 AM](https://user-images.githubusercontent.com/25483966/55002843-ac4a5580-4fad-11e9-82a5-9d4b450fb47d.png)

## Expected behavior
The query you typed in GraphiQL should be still be there when you click back and GraphiQL shouldn't display items at the top that are for the other `Site Config` menu items

## Logs
Here's a short clip:
https://www.useloom.com/share/8026a1d802d941b3be35f691ddfb0a68

### Version
Studio Version Number: 3.1.0-SNAPSHOT-5d3ba7
Build Number: 5d3ba752aa2107c420fc23891b7b0108068aa379
Build Date/Time: 03-26-2019 09:38:15 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1101

**Comment by alhambrav** [comment]
Verified fixed.
