### ISSUE TITLE
[studio-ui] RTE (TinyMCE 5) repeating group control sections issues

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2998]
## Describe the bug
RTE (TinyMCE 5) Images and media inserted disappears when you click on repeating group control options. 
Also, after inserting a table in a section, if you move that section with the table up, notice the section below the moved section now has the table options instead of the section with the table

## To Reproduce
1. Create a site using website_editorial
2. Edit one of the articles
3. Scroll down to the RTE section, and click on `Add Another`
4. Click on `Insert` -> `Image` from the RTE menubar
5. Click on the button next to the `Source` field, then select `Existing Images`
6. Select any image, then click `Add and Close` then `Save`
7. Click on `Add Another`, notice that the image we inserted in the previous step disappeared
8. Click on `Insert` -> `Table` then select table size from the RTE menubar
9. Click on `Move Up`, notice the table options are still in the previous position of the section with the table, and there's no way to make it go away until you save changes and re-edit the article
![Screen Shot 2019-03-26 at 2 55 10 PM](https://user-images.githubusercontent.com/25483966/55025564-8a65c880-4fd7-11e9-8b5a-df30bbd39ed0.png)

## Expected behavior
Images and media should not disappear from the RTE when clicking any of the repeating group control options (`Add Another`, `Move Up` or `Move Down`).  The table option should also not appear in sections without a table in the RTE

## Logs
Here's a short clip:
https://www.useloom.com/share/091e2500286f4cb2b774b1f7b8f2d651

### Version
Studio Version Number: 3.1.0-SNAPSHOT-5d3ba7
Build Number: 5d3ba752aa2107c420fc23891b7b0108068aa379
Build Date/Time: 03-26-2019 12:35:16 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1091

**Comment by alhambrav** [comment]
Verified fixed.
