### ISSUE TITLE
The Schedule feature is not working properly when setting minutes ahead

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#300]
1. Go to Studio
2. Go to the dashboard and Click on the Site Content dropdown 
3. Create a new content 
4. After creation, click on the just created content page on the pages structure 
5. Click on the “Schedule” option at the preview top navigation bar 
6. Provide valid values and schedule the content to be published in a couple of minutes 
7. Click on “Submit” button 

You will notice it push the content instantly, instead of publishing until the configured time

**Comment by dejan-brkic** [comment]
Can not reproduce issue with steps described above

**Comment by gortizcrafter** [comment]
The is reopened because is present.

See the video : https://www.screencast.com/t/rQvVLwv8E

**Comment by jvega-crafter** [comment]
I made some tests and noticed that timezone is being sent in request, and it only works fine if server is in the same timezone as the client, publishing content in a couple of minutes ahead (of current time). I found 3 scenarios, here the results:

- server: EST5EDT / client: CST -06:00 - current time = 10:13:00
- service: http://localhost:8080/studio/api/1/services/api/1/workflow/go-live.json?site=pluton&user=admin 
- scheduledDate: "2017-1-16T10:15:0-06:00" - w/timezone 
- RESULT: inmediately live - **SCENARIO 1**

--------------------------------

- server: EST5EDT / client: EST5EDT - current time = 11:12:00
- service: http://localhost:8080/studio/api/1/services/api/1/workflow/go-live.json?site=pluton&user=admin 
- scheduledDate: "2017-1-16T11:15:0-05:00"
- RESULT: scheduled - live in time - **SCENARIO 2**

--------------------------------

- server: CST / client CST -06:00 - current time = 10:40:00
- service: http://localhost:8080/studio/api/1/services/api/1/workflow/go-live.json?site=pluton&user=admin 
- scheduledDate: "2017-1-16T10:45:0-06:00"
- RESULT: scheduled - live in time - **SCENARIO 2**

--------------------------------

- server: EST5EDT / client: +06:00 - current time = 22:28:00
- service: http://localhost:8080/studio/api/1/services/api/1/workflow/go-live.json?site=pluton&user=admin
- scheduledDate: "2017-1-16T22:30:0+06:00"
- RESULT: scheduled - **SCENARIO 3** - didn't go live at selected time (after selected it was still in "scheduled")

**Comment by jvega-crafter** [comment]
On WorkflowServiceImpl.java, line 1037, it calls a method that creates the item to be submitted, sending the scheduledDate (correct one) and a format (using CStudioConstants.DATE_PATTERN_WORKFLOW), after this line the date changes so it causes the publish to fail

**Comment by dejan-brkic** [comment]
Fixed formatting issue
PR #491

**Comment by gortizcrafter** [comment]
Tests:

Server = EST vrs Client = CST
Server = EST vrs Client = EST
Server = CST vrs Client = CST
server = EST5EDT vrs client = +06:00 

 The behaviors are fine.
