### ISSUE TITLE
[studio-ui] Create site dialog: push site to remote. Fields doesn't show validations messages

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3000]
## Describe the bug
In the section `Additional Developer Options` when the checkbox `Push the site to a remote Git repository after creation`  is checked the fields `Remote Git Repository Name` and `Remote Git Repository URL`  doesn't show validations messages when their inputs are empty.

## To Reproduce
1. Click Create Site button
2. Select any BP
3. Set the `Site Id` and click `Additional Developer Options` button
4. Click the checkbox `Push the site to a remote Git repository after creation`
5. Click the `Remote Git Repository Name` input then the `Remote Git Repository URL` input and finally the `Remote branch` input
4. Notice that there were no validations messages when the inputs were left empty

## Expected behavior
Validation message errors when the inputs were left empty.

## Screenshots
In the video, I compare creating a site with the option `Use a remote Git repository instead of a built-in blueprint` were the validations are in place.
https://www.useloom.com/share/8d7e7a680d7549849625212b084d3501

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
3.1.0-SNPASHOT

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1104
I also fixed: Username for token.

**Comment by vestrada** [comment]
https://github.com/craftercms/studio-ui/pull/1111

**Comment by yacdaniel** [comment]
Verified fixed.
