### ISSUE TITLE
[studio-ui] Sandbox branch input missing when site created from BP and then pushed to remote repo

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3003]
## Describe the bug
When a site is created from any BP and the checked the option of push to remote, the `Sandbox Branch` input is missing.

## To Reproduce
1. Click Create Site button
2. Select any BP
3. Set the Site Id and click Additional Developer Options button
4. Click the checkbox Push the site to a remote Git repository after creation
5. Notice that there is no `Sandbox Branch` input

## Expected behavior
`Sanbox Branch` input present in Additional Developer Options.

## Screenshots
Old Create Site dialog had `Sandbox Branch` independitly if you create a site from remote repo or if the site is created from a BP and then push to remote repo
<img width="819" alt="Screen Shot 2019-03-27 at 10 31 43 AM" src="https://user-images.githubusercontent.com/6722074/55095002-09610c80-507d-11e9-8dcb-19949080d598.png">
In Basic Developer Options the `Sandbox Branch` is present
<img width="996" alt="Screen Shot 2019-03-27 at 10 50 38 AM" src="https://user-images.githubusercontent.com/6722074/55095768-55608100-507e-11e9-9471-f8b0d7dfbbdb.png">
In Additional Developer Options the `Sandbox Branch` is not present
<img width="928" alt="Screen Shot 2019-03-27 at 10 53 37 AM" src="https://user-images.githubusercontent.com/6722074/55095966-aa03fc00-507e-11e9-8352-14c5d02f6346.png">

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
3.1.0-SNAPSHOT

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1106

**Comment by yacdaniel** [comment]
Verified fixed.
