### ISSUE TITLE
[studio] Upgrade Manager: Support upgrading sites from 3.0.18 to 3.1.0

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3005]
Please support upgrading sites from 3.0.18+ to 3.1.0. While it's impossible to know for sure a site is 3.0.18+, we will assume this while performing the upgrade.

**Comment by jdrossl** [comment]
Missing actions:
- Add rte-tinymce5 in `/config/studio/config-list.xml`
- Remove rte-tinymce4 references?
- Add S3 datasources & GraphiQL, Remove Groups & Logging Levels in `/config/studio/site-config-tools.xml`
- Add `/config/studio/form-control-config/rte-setup-tinymce5.xml`
- Add S3 permissions in `/config/studio/permission-mappings-config.xml`
- Document that content monitor queries need to be updated if moving to ES

**Comment by sumerjabri** [comment]
@jdrossl yes, remove `rte-tinymce4` references.

**Comment by russdanner** [comment]
Confirmed
