### ISSUE TITLE
[craftercms] Support upgrading the bundle and related configuration from 3.0 to 3.1

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3006]
Add support for upgrading 3.0 to 3.1.

**Comment by jdrossl** [comment]
Because of the upgrade from Solr 6 to Solr 7 we should consider including automatic core delete/create/reindex for existing sites

**Comment by sumerjabri** [comment]
@jdrossl what would it take?

3.1.0?

**Comment by jdrossl** [comment]
yes `3.1.0`, I think all needed operations can be done using Search API
