### ISSUE TITLE
[studio-ui] Filters are not cleared after doing a new search

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3009]
## Describe the bug
If you enter a search term, pick a filter, and then enter a new search term, the filter is left and affects the next search.

## To Reproduce
1. Create a site from `editorial` bp.
2. Click on the Search icon.
3. Enter `women` in the search input.
4. On Filters, click on `Images - Width` and pick `480-800`.
5. Enter `entertainment` on the search input to do a new search.
6. No results are produced and you see that the filter still appears on the browser search URL.

## Expected behavior
When entering a new search term all previous filters should be dropped.

## Screenshots
![Screenshot from 2019-03-28 12-25-00](https://user-images.githubusercontent.com/1598884/55174921-b6f31f00-5154-11e9-811d-f8594c6b0c4e.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1098

**Comment by avasquez614** [comment]
Verified
