### ISSUE TITLE
[videocenter] website_editorial/videocenter pages are displayed incorrectly when both sites exists, depending on which site was created first

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3010]
## Describe the bug
website_editorial/videocent pages are displayed incorrectly when both sites exists, depending on which site was created first.
If you create the videocenter site first, then create a website_editorial site, when you go back to preview videocenter, the page is not previewed correctly (It's empty)
If you create website_editorial site first, then create the videocenter site, when you go back to preview the website_editorial site, the pages are previewed incorrectly

## To Reproduce
1. Create a site using the website_editorial bp (`site1`)
2. Create a site using the videocenter bp (`site2`)
3. Click `Main Menu` -> `Sites` and preview `site1`
4. Notice how the `Home` page is rendered, and when you `Inspect`, notice the error
![Screen Shot 2019-03-28 at 12 17 59 PM](https://user-images.githubusercontent.com/25483966/55174411-c3c34300-5153-11e9-839c-26efa8a615f7.png)
5. Preview some of the other pages in `site1` and notice that they are displayed incorrectly
![Screen Shot 2019-03-28 at 12 23 40 PM](https://user-images.githubusercontent.com/25483966/55174730-5b289600-5154-11e9-8d9d-8cd9a393bbeb.png)
6. Delete both the sites created in the previous steps
7. Create a site using the videocenter bp
8. Create a site using website_editorial bp
9. Go to the `Main Menu` and click on `Sites`
10. Preview the videocenter site, notice that the page is empty
<img width="1412" alt="Screen Shot 2019-03-29 at 8 05 13 AM" src="https://user-images.githubusercontent.com/25483966/55235695-88cd1800-5204-11e9-9677-a519b0fa6b34.png">

Just as another example to the issue, so, from step 10, we have a videocenter site that is not previewing correctly, do the next steps:
11. Create another site, using the videocenter website
12. Go back to the website_editorial site, notice that the pages are not being rendered correctly
Alternate creating sites between the website_editorial bp and the videocenter bp and notice how the pages are rendered.

## Expected behavior
Previewing videocenter or website editorial sites should not be affected on which site was created first

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).
Here's a short clip:
https://www.useloom.com/share/ca26d51122ad46daa2a87ef5f4f2f37e

### Version
Studio Version Number: 3.1.0-SNAPSHOT-4da7aa
Build Number: 4da7aae3c7ebd756216ba391e465761fce6a7521
Build Date/Time: 03-28-2019 11:29:50 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by alhambrav** [comment]
Updated the description and steps to reproduce the issue.

**Comment by jvega190** [comment]
videocenter: https://github.com/craftercms/video-center-blueprint/pull/22
studio: https://github.com/craftercms/studio/pull/1538

**Comment by alhambrav** [comment]
Verified fixed.
