### ISSUE TITLE
[studio] User is not removed from groups user belonged to when user is deleted

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3015]
## Describe the bug
When you delete a user, the user is not removed from groups that the user belongs to

## To Reproduce
1. Create a user `jane`
2. Add user `jane` to group `site_author`
![Screen Shot 2019-03-29 at 11 29 26 AM](https://user-images.githubusercontent.com/25483966/55243607-f3d31a80-5215-11e9-89bd-964bc74372ef.png)
3. Go back to `Users` from the `Main Menu` and delete user `jane` 
4. Go back to `Groups` from the `Main Menu` and click on `Edit` the group `site_author`
5. Notice that user `jane` is still listed as part of the group

## Expected behavior
A user that has been deleted should be removed from the groups that the user belongs to

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-f02f9d
Build Number: f02f9d02d434ad9759fdf82a14b00a65586ee21e
Build Date/Time: 03-29-2019 09:35:38 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1534

**Comment by alhambrav** [comment]
Verified fixed.
