### ISSUE TITLE
[studio] can't create a user using a deleted username

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3018]
## Describe the bug
If a user is deleted is not possible to create it again using the same username

## To Reproduce
1. Create a new user `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -H "Content-Type: application/json"  -v -X POST -d '{"enabled":true,"firstName":"test08","lastName":"test08","username":"test08","password":"test08","email":"test08@gmail"}' http://localhost:8080/studio/api/2/users`
2. Remove the user created `cur{"response":{"code":6001,"message":"User already exists","remedialAction":"Try a different username","documentationUrl":""}}l --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -v -X DELETE http://localhost:8080/studio/api/2/users\?username\=test08`
3. Try to create a new user with the previous username 
`curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -H "Content-Type: application/json"  -v -X POST -d '{"enabled":true,"firstName":"test08","lastName":"test08","username":"test08","password":"test08","email":"test08@gmail"}' http://localhost:8080/studio/api/2/users`
4. See response `{"response":{"code":6001,"message":"User already exists","remedialAction":"Try a different username","documentationUrl":""}}`

## Expected behavior
User can be created

## Screenshots
User marked as deleted in DB
![image](https://user-images.githubusercontent.com/6722074/55252321-40b7f080-5218-11e9-9fe2-ca8d12a32982.png)

## Logs
Catalina log https://gist.github.com/yacdaniel/4700257fa658bc67546625b144190b00

### Version
3.1.0-SNAPSHOT

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by sumerjabri** [comment]
Known and accepted. We no longer allow permanent deletion of users, and usernames, once used, cannot be re-used. The reason is easy to read audit trail.

We may revisit this based on user feedback down the road.
