### ISSUE TITLE
[studio-ui] can't delete a user after being created

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3019]
## Describe the bug
Right after a user is created it cannot be removed using the UI, the user should go to another submenu and then back to users menu to be able to delete it.

## To Reproduce
1. Go to Users menu and create a new user
2. Click the delete button next to the created user.
3. User is not deleted, the DELETE call is passing undefined for the ip parameter `http://localhost:8080/studio/api/2/users?id=undefined`

## Expected behavior
User can be removed just after is created.

## Screenshots
![delete user](https://user-images.githubusercontent.com/6722074/55253663-93df7280-521b-11e9-8b62-df92210c2f9b.gif)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
3.1.0-SNAPSHOT

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1114

**Comment by yacdaniel** [comment]
Verified fixed.
