### ISSUE TITLE
[studio] Error using header authentication

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3021]
## Describe the bug
Using headers based authentication always throws a NPE in the following line:

https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/web/security/access/StudioAuthenticationTokenProcessingFilter.java#L117

### Version
3.1

### OS
Ubuntu

### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1539

**Comment by sumerjabri** [comment]
Is this a 3.1 only issue?

**Comment by dejan-brkic** [comment]
yes. only 3.1

**Comment by jdrossl** [comment]
Verified
