### ISSUE TITLE
[videocenter] User belonging to default groups site_xxx is not able to access sites created with the videocenter bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3022]
## Describe the bug
User belonging to the groups created by default site_xxx is not able to access sites created with the videocenter bp.

## To Reproduce
1. Create a user `jane`
2. Add user `jane` to group `site_author`
![Screen Shot 2019-04-01 at 2 49 12 PM](https://user-images.githubusercontent.com/25483966/55351845-5da92980-548d-11e9-8ff2-98c2e9560133.png)

3. Create a site using the website_editorial bp
4. Create another site, this time based on the videocenter bp
![Screen Shot 2019-04-01 at 2 48 55 PM](https://user-images.githubusercontent.com/25483966/55351857-6994eb80-548d-11e9-85fe-ad66daf300f6.png)

5. Logout user `admin`
6. Login as user `jane`
7. Notice the videocenter site is not available for user `jane`
![Screen Shot 2019-04-01 at 2 48 05 PM](https://user-images.githubusercontent.com/25483966/55351862-6e599f80-548d-11e9-8186-f3443fa55b2c.png)
8. You can try adding a user to any of the other default groups named `site_xxx`, and when you login as a user that's a member of group `site_xxx`, the videocenter site is not in the list of accessible sites

## Expected behavior
A user belonging to `site_xxx` should be able to access a videocenter site

## Logs
Here's a short clip showing 3 sites in Studio, empty, website_editorial, and videocenter with user `admin` logged in, then user `jane`, a member of group `site_author` logs in and does not see the videocenter site in the `Sites` screen:
https://www.useloom.com/share/e0503d1ca87344689bf0755d43043f70

### Version
Studio Version Number: 3.1.0-SNAPSHOT-2c3da4
Build Number: 2c3da4132a416904fd64a24984661d48f9b3ef5a
Build Date/Time: 04-01-2019 12:18:22 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
It looks like in the `Role Mappings` configuration, the group names used as default is not `site_xxx` like in the other 4 blueprints

Here's the default `Role Mappings` configuration when you use the videocenter bp:
```
<role-mappings>
	<version>2</version>
    <groups>
        <group name="video_admin">
            <role>admin</role>
        </group>
        <group name="video_developer">
            <role>developer</role>
        </group>
        <group name="video_author">
            <role>author</role>
        </group>
        <group name="video_publisher">
            <role>publisher</role>
        </group>
        <group name="video_reviewer">
            <role>reviewer</role>
        </group>
    </groups>
</role-mappings>
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/video-center-blueprint/pull/23

**Comment by alhambrav** [comment]
Verified fixed.
