### ISSUE TITLE
[documentation] Add a Docker Compose section under Subsystems

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3023]
In https://docs.craftercms.org/en/3.1/developers/index.html, under `Subsystems and API Documentation`, underneath the `Crafter CMS` item, add an item for `Crafter CMS Docker Compose` that points to the Docker Compose project documentation.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/713

**Comment by avasquez614** [comment]
Verified
