### ISSUE TITLE
[studio] Studio logs (not Engine) - API

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3024]
A new API needs to be added into Crafter Studio, to get studio logs in order to be used in a 'Log Console' on studio global menu

**Comment by sumerjabri** [comment]
@dejan-brkic note that this is for 3.1.1 (not 3.1.0)
This should be similar to getting the preview Engine logs, but pull from Studio instead.

**Comment by jdrossl** [comment]
@jvega190 the new API is ready https://app.swaggerhub.com/apis/craftercms/studio/2.0.23#/monitoring/getLogEvents

**Comment by jvega190** [comment]
verified
