### ISSUE TITLE
[studio-ui] Empty site is created even if bp selected in Create Site screen is not the empty bp

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3030]
## Describe the bug
Empty site is created even if bp selected in Create Site screen is not the empty bp

## To Reproduce
1. In the `Sites` screen, click on the `Create Site` button
2. Scroll to the  `Headless Blog Blueprint` then click on the `Select` button
![Screen Shot 2019-04-03 at 2 56 37 PM](https://user-images.githubusercontent.com/25483966/55505306-d4c2f700-5620-11e9-8ecb-a9aceb5d2045.png)

3. Enter a name for your site in the `Site Id` field, then hit the \<enter\> key on your keyboard
4. Click on the `Review and Create` button
![Screen Shot 2019-04-03 at 2 56 52 PM](https://user-images.githubusercontent.com/25483966/55505415-0f2c9400-5621-11e9-99a7-13ead8c217d4.png)

5. Notice in the next screen, the blueprint about to be created is the Empty blueprint instead of the headless blog
![Screen Shot 2019-04-03 at 2 57 00 PM](https://user-images.githubusercontent.com/25483966/55505423-1358b180-5621-11e9-8313-6cabfa920f97.png)

You can try selecting other blueprints, but, as long as you hit the \<enter\> key on the keyboard after entering `Site Id`, the site to be created turns into the Empty one instead of what you selected.  If you're not paying attention, and just click on the `Create` button, all you'll notice is that an Empty site is created instead of the one you selected.

## Expected behavior
When you select a blueprint, the selected blueprint should be the one created, even if you hit the \<enter\> key 

## Logs
Here's a short clip showing the above steps:
https://www.useloom.com/share/efd57acafccf41bf9fdc337825bf24db

Notice around timestamp 9 sec, the \<enter\> key is being pressed on the keyboard

### Version
Studio Version Number: 3.1.0-SNAPSHOT-fbe334
Build Number: fbe33459558e9b3437b4205269a50fc4656a10cb
Build Date/Time: 04-03-2019 14:23:18 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1110

**Comment by alhambrav** [comment]
Verified fixed.
