### ISSUE TITLE
[studio-ui] Clicking `Edit` from context nav for an article does not open the form for the page currently being previewed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3032]
## Describe the bug
 Clicking `Edit` from context nav for an article does not open the form for the page currently being previewed

## To Reproduce
1. Create a site using the website_editorial bp
2. After the site is created, you are taken to the Home page
3. Click on the hamburger icon if the left-rail is not yet open, and click on the first article listed under `Latest Articles`
![Screen Shot 2019-04-03 at 3 46 06 PM](https://user-images.githubusercontent.com/25483966/55508354-ba404c00-5627-11e9-93fc-cc5dabcd6110.png)

4. Click on `Edit` from the context nav 
![Screen Shot 2019-04-03 at 4 06 18 PM](https://user-images.githubusercontent.com/25483966/55509693-8ca8d200-562a-11e9-810c-42cbaefb75df.png)
5. Notice the form is for the `Home` page instead of `5 Popular Diets for Women`
![Screen Shot 2019-04-03 at 4 07 54 PM](https://user-images.githubusercontent.com/25483966/55509748-ab0ecd80-562a-11e9-9acb-70a0d9d717e2.png)

## Expected behavior
Clicking `Edit` from the context nav should display the form for the page currently being previewed

## Logs
Here's a short clip showing the steps listed above:
https://www.useloom.com/share/188a72bc485e4493b06925231109bfb9

### Version
Studio Version Number: 3.1.0-SNAPSHOT-fbe334
Build Number: fbe33459558e9b3437b4205269a50fc4656a10cb
Build Date/Time: 04-03-2019 14:23:18 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/3035

**Comment by alhambrav** [comment]
Adding some more notes for the issue here:

After navigating to a page to preview from the Nav Tree in the Sidebar, if you preview a different page by clicking on one of the links from the page, the context nav is displaying wrong workflow icons and options.

Here's a short clip showing the behavior mentioned above:
https://www.useloom.com/share/ec45c82905bb4aebad321dd2e5486efc

**Comment by jvega190** [comment]
This is not related to https://github.com/craftercms/craftercms/issues/3035, I'll work on this one separately

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1116
videocenter: https://github.com/craftercms/video-center-blueprint/pull/27

**Comment by alhambrav** [comment]
Verified fixed.
