### ISSUE TITLE
[studio-ui] Editing an asset while previewing a page changestop bar selected content

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3035]
## Describe the bug
Top bar changes selection after editing an asset while previewing a page.

## To Reproduce
1. Go to 'Editorial' page and preview home page.
2. Edit an asset (ftl, css, etc)
3. Save asset.
4. Click 'Edit' from the top bar (also other actions from top bar)

The last edited asset shows in the editor instead of the previewed page editor.

## Expected behavior
The form for the current page (the one being previewed) should be displayed instead of the asset editor.

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/3032

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1108

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1117

**Comment by yacdaniel** [comment]
Verified fixed.

**Comment by jvega190** [comment]
This issue happens also with other types (not only assets). Will work on that

**Comment by jvega190** [comment]
3.1.x: https://github.com/craftercms/studio-ui/pull/1127
3.0.x: https://github.com/craftercms/studio-ui/pull/1128
