### ISSUE TITLE
Wants to contribute a feature to replace Spring with Spring boot

### ISSUE THREAD

**Issue by ealio** [craftercms/craftercms#3038]
How could I attend this project? I want to replace spring framework to spring boot.

**Comment by sumerjabri** [comment]
Please join us either on forums or on public chat, here: https://join.slack.com/t/craftercms/shared_invite/enQtNDg0NzI3NzA0NjMwLThkOWQwOWVlYWM5NzIyODZjZjQ2MTY1OTliM2EyZDI3ZjFjY2EwYWNlYjgyZGMwMWM3ZjZkZmNiYTJkZDgzMzc

We can discuss the Springboot contribution there.
