### ISSUE TITLE
[studio] move config samples to global repo

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3039]
It would be great to have a single place to update config sample files instead of having to do it for all blueprints and exiting sites.

One option is to move them to the global repo and display them directly from there

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1569
https://github.com/craftercms/studio-ui/pull/1121
https://github.com/craftercms/video-center-blueprint/pull/31

**Comment by sumerjabri** [comment]
@alhambrav please validate and make sure docs are up to date. Especially how to make your own blueprint cookbook.

**Comment by sumerjabri** [comment]
One site broke:
https://gist.github.com/sumerjabri/12dd90f4821db5d8e4073bf05c94d877

See logs:
https://gist.github.com/sumerjabri/47fb9689b792e74d6c5e90a68b301220

**Comment by dejan-brkic** [comment]
Reviewed log files. It seems like that site `2345r2345r345` exists on disk but not in DB. Upgrade manager gets the list of sites from DB.
The error stack trace is coming from the engine, failed to create the context for that site. Engine reads from disk.

**Comment by sumerjabri** [comment]
Verified
