### ISSUE TITLE
Invalid table name for index on oracle create DDL script

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#304]
studio2/src/main/resources/crafter/studio/database/createDDL-oracle.sql

ALTER TABLE `CSTUDIO_OBJECTMETADA`
ADD CONSTRAINT CSTUDIO_OBJECTMETADA_UK1 UNIQUE

CSTUDIO_OBJECTMETADATA table is typo'd above.

Missing constraint causes publishing operations to fail on items that have been renamed and other scenarios where multiple records get added to the CSTUDIO_OBJECTMETADATA table because the constraint is not in place.

**Comment by dejan-brkic** [comment]
Fixed PR #411 #412
