### ISSUE TITLE
[engine] Optimize site context rebuild

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3041]
The site context build process should not interrupt the site until the new context is ready.

**Comment by jdrossl** [comment]
everything looks good in authoring but @yacdaniel found some issues in delivery

**Comment by avasquez614** [comment]
@jdrossl next time please assign it to @yacdaniel so that he can explain what's wrong, don't assign it back to me

**Comment by yacdaniel** [comment]
I created a site from editorial and `init-site.sh` in delivery.  Here is part of the stack trace from `crafter-delivery/logs/tomcat/catalina.out` https://gist.github.com/yacdaniel/176fc98c781296bf65e97af1900e4467

**Comment by avasquez614** [comment]
@yacdaniel please test again with the latest.

**Comment by yacdaniel** [comment]
Verified fixed.
