### ISSUE TITLE
[studio] 3.0.x version does not start up

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3043]
## Describe the bug
Studio does not start up normally for 3.0.x. Logs report missing class from commons inside engine spring context

## To Reproduce
Update 3.0.x to latest and build it.
Start authoring. Studio does not start

## Expected behavior
Studio starts up normally 

## Logs
https://gist.github.com/dejan-brkic/6ea16905e50ba79a1f6f6a2d931d3412

### Version
Software version if applicable (copy paste from Help > About).

### OS
What OS did you use to produce the bug.

### Browser
What browser did you use to produce the bug.

**Comment by jdrossl** [comment]
@dejan-brkic can you check if `commons` is also updated to the latest? I just did a fresh install from `support/3.0.x` and both engine & studio are working fine

**Comment by dejan-brkic** [comment]
everything is updated to latest 3.0.x

**Comment by dejan-brkic** [comment]
Local maven repository issue. Closing
