### ISSUE TITLE
[studio] Support repository level changes to the git history

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3044]
**Is your feature request related to a problem? Please describe.**
From time to time, Administrators find it necessary to git reset --hard/soft COMMITID on the sandbox or publishing. Administrators need a way to reset the database in a project along with the repository.

**Describe the solution you'd like**
Support repository level resets (hard and soft) as well as rebase operations.
- database synchronization
- consistent / predictable publishing behavior

**Comment by sumerjabri** [comment]
Approach:
- Add an API to do this
- Lock the world
- Clone the version to a folder
- Rsync from clone to current (--ar --delete exclude .git)
- Add and commit
- Unlock the world

--- This can be done manually today, we're just adding an API to make it easy
