### ISSUE TITLE
[profile] Default the profile cookies to secure

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3047]
Please switch the default to secure.

**Comment by avasquez614** [comment]
@sumerjabri  making this change will mage local development and testing more difficult because now you'll need to configure an Apache or Tomcat with SSL. Maybe it's better to document it for production?

**Comment by alhambrav** [comment]
commit: https://github.com/craftercms/docs/pull/757/commits/4205e17c720189a2b8703fccccefb0967b448312

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/758

**Comment by sumerjabri** [comment]
Verified fixed.
