### ISSUE TITLE
[studio] Can't create site with the option push to remote

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3048]
## Describe the bug
Creating a site from any BP and using the option Push to remote is throwing: `Error: Internal server error: org.craftercms.studio.api.v1.exception.SiteNotFoundException`

## To Reproduce
1. Select any BP from the Create Site dialog and file the site id
2. Click on Additional Developer Options
3. Click on the checkbox `Push the site to a remote Git repository after creation`
4. Fill remote repo values
5. Click on Review and Create and then Create button

## Expected behavior
Site created and pushed to remote repo

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/55812698-ab82ea80-5aa8-11e9-85c0-69bb5e5668d2.png)

## Logs
https://gist.github.com/yacdaniel/09914f0511d3ab156eadc44f77689132

### Version
Studio Version Number: 3.1.0-SNAPSHOT-827427
Build Number: 82742775dfdc8988b32ecb6793f73480ee69c887
Build Date/Time: 04-09-2019 08:23:33 -0600

### OS
Linux

### Browser
What browser did you use to produce the bug.

**Comment by dejan-brkic** [comment]
https://github.com/craftercms/studio/pull/1559

**Comment by yacdaniel** [comment]
Verified fixed.
