### ISSUE TITLE
[studio] Blank Page for Site Config in Empty, Blog and Store BP's

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3054]
## Describe the bug
There is a blank page for the `Site Config` for sites created using Empty, Store and Blog BP's

## To Reproduce
1. Create a site using Empty, Blog and Store BP's
2. Go to the `Site Config` for each site.
3. See blank page.

## Expected behavior
`Site Config` loads

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/55833867-c455c500-5ad5-11e9-92a2-9fc3cb54520e.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-741f0b
Build Number: 741f0bb2f09a4bb21fc797e90ff4c6ee5ca168ad
Build Date/Time: 04-09-2019 13:57:52 -0600

### OS
Linux/Mac

### Browser
What browser did you use to produce the bug.

**Comment by vestrada** [comment]
![image](https://user-images.githubusercontent.com/11640613/55901634-f115e500-5b86-11e9-88e4-4f412dc69923.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1564

**Comment by yacdaniel** [comment]
Verified fixed.
