### ISSUE TITLE
[docs] Docker Engine memory setting

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3057]
When Docker is installed, the Docker Engine has default settings to limit resources. For memory on Mac (and windows) default size is 2GB.
When starting Authoring docker image, Elasticsearch exits with code 137 (it's killed due to out of memory). After increasing memory limit to 4GB fo Docker Engine, Authoring image starts normally.

Docker Engine settings:
![docker](https://user-images.githubusercontent.com/4053827/55876978-25929c80-5b99-11e9-9244-006a58f7181a.png)

Please document recommendations for Docker Engine settings

**Comment by avasquez614** [comment]
Hi @dejan-brkic. This is already documented. See in https://github.com/craftercms/docker-compose/tree/develop: `For Windows and Mac, we recommend you give Docker Desktop at least 8GB of RAM and 4 CPUs. To do this, go to Docker Desktop's Settings > Advanced, and then change the resource limits.`. Also in https://docs.craftercms.org/en/3.1/getting-started/quick-start-guide.html#running-crafter-cms-in-a-docker-container.

**Comment by sumerjabri** [comment]
@avasquez614 can we make the docs a touch nicer/easier and perhaps use a screenshot or two to communicate things more clearly?
