### ISSUE TITLE
[studio] Make Studio Environment configuration aware of engine, preview and GraphQL server locations

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3058]
In the past, the preview server and engine were often assumed to be the same server and tools in Studio could comfortably make this assumption.  Today, with the introduction of GraphQL and external preview servers Studio tooling needs to be able to make finer-grained distinctions about the locations of services;
Common use cases
1. Engine and Preview servers on different servers (NodeJS on server A and Engine on server B)
2. GraphQL of GraphQL + others. GraphiQL is there to support developers who are building apps on GraphQL.  Many organizations may have their own GraphQL server and want their app to talk to it (and it to us.)  We want that tool to be able to point to wherever the developer needs (defaulting to the GraphQL Server on Engine)

**Describe the solution you'd like**
Add configuration in `environment-config.xml` XML and the get-config APIs that for:
- preview-server-url (exists)
- preview-engine-server-url
- graphql-server-url

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1569
https://github.com/craftercms/video-center-blueprint/pull/31

**Comment by russdanner** [comment]
Confirmed! Woot! Woot! :D

**Comment by russdanner** [comment]
It looks like this is no longer working
https://www.loom.com/share/5f6970813caf4a4a836c8f20b70decc4

**Comment by dejan-brkic** [comment]
```
Studio Version Number: 3.1.0-SNAPSHOT-271080

Build Number: 27108093400c2dac3317f9b3a288c0d40913b7ff

Build Date/Time: 04-25-2019 20:06:33 +0200
```

Works fine, with same configuration values and urls as in the video. Not studio BE issue. There were no code changes in the last 3 days on studio code to make it stop working. I have tested also with latest UI, and other crafter libraries.

**Comment by russdanner** [comment]
https://www.loom.com/share/12079f221c4d48f3a837b59807d85bf2

**Comment by russdanner** [comment]
You do not need a test server on node to test, you can use the following environment config:
```
<environment-config>
   <preview-server-url>http://craftersoftware.com</preview-server-url>
   <preview-engine-server-url>http://localhost:8080</preview-engine-server-url>
   <graphql-server-url>http://localhost:8080</graphql-server-url>
   <authoring-server-url>http://localhost:8080/studio</authoring-server-url>
   <live-server-url>http://localhost:9080/?crafterSite={siteName}</live-server-url>
   <open-sidebar>false</open-sidebar>
   <publishing-targets>
      <target>
         <repo-branch-name>live</repo-branch-name>
         <display-label>Live</display-label>
      </target>
   </publishing-targets>
</environment-config>
```

Graphi should go to the graphql server, not the preview server

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1580

**Comment by jvega190** [comment]
GraphiQL reading from graph-ql-server
https://github.com/craftercms/studio-ui/pull/1148

**Comment by russdanner** [comment]
CONFIRMED!!!!
