### ISSUE TITLE
[studio] cached user authorizations are not updated on sign-in

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3059]
## Describe the bug
Crafter Studio 2.5.x caches users when used in conjunction with Alfresco.  When a user signs in, if Studio has already seen the user it uses roles from cache rather than reading them anew and updating the cache.

If a user's role changes between sign-ins a clear cache operation or a restart of studio is required (which in a sense clears the cache)

## To Reproduce
1. Configure Studio to use Alfresco
2. Sign in as user with one set of roles for a site
3. In Alfresco, change the user's roles
4. Sign in to Studio again an note roles are not updated

## Expected behavior
Crafter should always re-read authorizations on sign in and update as appropriate.

### Version
2.5.19 and below

### OS
All

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/1562
