### ISSUE TITLE
[studio-ui] pages folder is showing duplicate objects on create action

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3061]
## Describe the bug
When a user creates content the page tree duplicates the item twice. 

 A refresh corrects the tree rendering.

## To Reproduce
1. start with studio on disk repository
2. create a site based on empty
3. open home page in side bar pages folder and right click create new
4. chose entry and fill out and then save form
5. note two children are rendered
6. repeat create process to see further examples
7. refresh corrects rendering

## Expected behavior
On save the tree should show only one new object.

## Screenshots
https://www.loom.com/share/6a80519ccbe14ddf9ee0e901c45b6f0d

## Logs
N/A

### Version
2.5.20

### OS
All

### Browser
All

**Comment by russdanner** [comment]
Occurs on Alfresco. Checking now to see if it happens on Disk Repo.

**Comment by russdanner** [comment]
Confirmed this can be reproduce with Disk repository. I will update steps accordingly.

**Comment by vestrada** [comment]
2.5.x -> https://github.com/craftercms/studio-ui/pull/1120

**Comment by vestrada** [comment]
3.0.x -> https://github.com/craftercms/studio-ui/pull/1122

**Comment by vestrada** [comment]
3.1.1 -> https://github.com/craftercms/studio-ui/pull/1123

**Comment by yacdaniel** [comment]
Verified fixed in `2.5(Disk Repository)`, `3.0` and `3.1` I created 10 levels of entry content. Duplicated items were not visible. @russdanner if you can test the fix with Alfresco please do, otherwise, close the issue. Thanks
![levelContentSidebar](https://user-images.githubusercontent.com/6722074/56295104-7b130000-60e9-11e9-819d-2bc990104810.gif)

**Comment by russdanner** [comment]
Confirmed
