### ISSUE TITLE
[videocenter] Error message when editing content using TinyMCE5 control

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3062]
## Describe the bug
Error message `Failed to load plugin: templatecodesample from url http://localhost:8080/studio/static-assets/modules/editors/tinymce/v5/tinymce/plugins/templatecodesample/plugin.min.js` show when edited the content of a TinyMCE5.
 
## To Reproduce
1. Create a site using videocenter BP
2. In the Sidebar expand `Videos` and then right-click any video to edit it.
3. In the `Metadata` section click the Description content.

## Expected behavior
No error when editing the content of a TinyMCE5 control.

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/55906974-c2057080-5b92-11e9-8dc3-57794286def9.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-1a0920
Build Number: 1a09203ba359a1d17e1cd1c68f25905da43b2bfb
Build Date/Time: 04-10-2019 11:13:24 -0600

### OS
Mac

### Browser
Chrome/Firefox

## Additional context
If the message is closed, the content can be edited and saved.

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/30

**Comment by yacdaniel** [comment]
Verified fixed.
