### ISSUE TITLE
[studio] Create new API to get `Default Types` for datasources

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3063]
**Is your feature request related to a problem? Please describe.**
https://github.com/craftercms/craftercms/issues/2996
When configuring a datasource with a specific type, Studio should validate the value or offer a list of the existing content-types to select one.

**Describe the solution you'd like**
Create new API to get `Default Types` for datasources 

![image](https://user-images.githubusercontent.com/11640613/55912515-0fd4a580-5ba0-11e9-9ee8-b892cfeb286e.png)

**Comment by sumerjabri** [comment]
Closing since we've gone in a different direction.
