### ISSUE TITLE
[videocenter] search is not returning live events/streams content

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3064]
## Describe the bug
Search in videocenter BP is searching only for `content-type: /component/video`. Content in `/component/stream` is not being returned as a result.

## To Reproduce
1. Create a site from videocenter BP
2. Go to the search icon and search for content that is under `Videos/stream`
3. No results

## Expected behavior
Content from `Videos/steam` is returned.

## Screenshots
<img width="1366" alt="Screen Shot 2019-04-10 at 14 55 07" src="https://user-images.githubusercontent.com/6722074/55913010-d8b2c400-5ba0-11e9-9e54-7183d59d411d.png">

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-1a0920
Build Number: 1a09203ba359a1d17e1cd1c68f25905da43b2bfb
Build Date/Time: 04-10-2019 11:13:24 -0600

### OS
Mac

### Browser
Chrome/Firefox

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/29

**Comment by yacdaniel** [comment]
Verified fixed.
