### ISSUE TITLE
[videocenter] stream start date is not updated in the Live Events page

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3065]
## Describe the bug
When the stream start date is edited, his content in the `Live Events` is not being updated.

## To Reproduce
1. Create a site using videocenter BP
2. Edit the start date of any of the videos in `Videos/stream`
3. Go to the `Live Events` page and check for the edited stream

## Expected behavior
The date in the `Live Events` for the stream edited is updated.

## Screenshots
https://www.loom.com/share/233556d334be49c6bc3ee0fb870cb847

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-1a0920
Build Number: 1a09203ba359a1d17e1cd1c68f25905da43b2bfb
Build Date/Time: 04-10-2019 11:13:24 -0600

### OS
Mac

### Browser
Chrome/Firefox

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/29

**Comment by yacdaniel** [comment]
Verified fixed.
