### ISSUE TITLE
[studio] Organize the UpgradeManager files into a hierarchy

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3069]
The upgrade manager files are all in a single folder right now called "upgrade."

Please reorg to have it by version, by pipeline. Like this:
```
upgrade/{version}/{pipeline}/{subversion}/...
```

Example:
```
upgrade/3.0.x/system/3.0.20/...
```

If you have a better way of decluttering, please suggest here or on Slack.

**Comment by jdrossl** [comment]
@sumerjabri what do you think about `upgrade/{branch}/{version}/{pipeline}` to make the paths smaller, example: `upgrade/3.0.x/3.0.20/system`, `upgrade/3.0.x/3.0.20/site`, `upgrade/3.1.x/3.1.0/config`, ...

**Comment by sumerjabri** [comment]
@jdrossl sounds great, let's do it!

**Comment by sumerjabri** [comment]
Verified
