### ISSUE TITLE
[studio] Port Repository Management API1 to 2

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3070]
Port this API https://docs.craftercms.org/en/3.0/developers/projects/studio/api/index.html#repo-management

to API 2 and add the features:
- Support `-X theirs` in pull requests

Consider supporting additional Git mechanics in pull/push.

Related to: https://github.com/craftercms/craftercms/issues/3071

**Comment by sumerjabri** [comment]
@dejan-brkic please add the ability to provide a comment for `pull`.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1169
https://github.com/craftercms/video-center-blueprint/pull/36
https://github.com/craftercms/studio/pull/1583

**Comment by sumerjabri** [comment]
@yacdaniel please validate and update the test suite to test the new API.

**Comment by yacdaniel** [comment]
@dejan-brkic could you add the response `409 resource already exist` ? when I add a remote that is already in the system my response is `500`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1646

**Comment by yacdaniel** [comment]
Verified.
