### ISSUE TITLE
[studio-ui] Switch to the new Repository Management API and add flags

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3071]
Depends on: https://github.com/craftercms/craftercms/issues/3070

Switch repository management to use the new API for repository management.

Add the flag `-X theirs` to the `pull` dialog to give the user (checkbox).

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1219

**Comment by sumerjabri** [comment]
@alhambrav please document.

@alhambrav this is also related to: https://github.com/craftercms/craftercms/issues/3303

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/804
