### ISSUE TITLE
[studio-ui] Fix warning related to missing media

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3073]
## Describe the bug
Create Site dialog results in the warning:
```
```[WARN] 2019-04-15T11:35:15,798 [http-nio-8080-exec-7] [f] [impl.ViewNotResolvedExceptionHandler] | Resource '/{{media.screenshot.url}}' not found``` ```
 in the logs

## To Reproduce
Steps to reproduce the behavior:
1. Create a site
2. Read the logs

## Expected behavior
Roys suggested there is a problem is NG syntax:
```
to me it looks more like the right angular syntax is not getting used since, if the issue was that the blueprint image was not present you’d be seeing something more along the lines of `Resource '/undefined' not found`. either way, needs a bit of a check :slightly_smiling_face: (edited) 
maybe `src="{{media….}}"` is being used instead of `ng-src="…"` sort of thing 
```

## Logs
```
[WARN] 2019-04-15T11:35:15,798 [http-nio-8080-exec-7] [f] [impl.ViewNotResolvedExceptionHandler] | Resource '/{{media.screenshot.url}}' not found 

```

## Specs
### Version
3.1.0-SNAPSHOT

### OS
Linux, Ubuntu 18.04

### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1134

**Comment by sumerjabri** [comment]
Verified fixed.
