### ISSUE TITLE
[videocenter] Missing icons for items in Videos and Origins

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3074]
## Describe the bug
Missing icons in the sidebar/dashboard for `Videos` and `Origins`

## To Reproduce
1. Create a site from videocenter BP
2. Expand the sidebar and then `Videos` a `Origins`
3. Edit an item from `Videos` or `Origins` and go to Dashboard.

## Expected behavior
Icons for `Videos` and `Origins` items

## Screenshots

![image](https://user-images.githubusercontent.com/6722074/56150954-52fe9200-5f6d-11e9-8217-f96375edffd5.png)
![image](https://user-images.githubusercontent.com/6722074/56150999-71fd2400-5f6d-11e9-8755-58c8e78ef461.png)

## Logs
If applicable, attach the logs/stack trace (use https://gist.github.com).

### Version
Studio Version Number: 3.1.0-SNAPSHOT-e3e142
Build Number: e3e1427118fa3cb985cdd7542a9f7f7bc34af35c
Build Date/Time: 04-15-2019 10:43:35 -0600

### OS
Linux

### Browser
Chrome/Firefox

**Comment by sumerjabri** [comment]
@yacdaniel I fixed this directly.

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/56161000-c0b6b800-5f85-11e9-8305-4a7f27012917.png)
