### ISSUE TITLE
[studio] Studio log viewers don't work as expected

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3076]
Please fix the log viewer:
- Switch the log viewers, Studio and Preview Engine, to show the past 60 mins.
- Use the new tool, NG, on the SiteConfig and get rid of the old tool. Make sure the UI is consistent.
- Change the headings to match the API and test to see if it makes sense.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1126

**Comment by sumerjabri** [comment]
Verified.
