### ISSUE TITLE
[engine] Support item, page and component interfaces in GraphQL

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3078]
**Is your feature request related to a problem? Please describe.**
It is useful to be able to query for all pages or all components.  Currently our GraphQL schema does not support that.  A query must be for a specific type of content.  You cannot get results of mixed content types with similar fields.

GraphQL supports interfaces that can make it easy to do queries like:
* get all content
* get all pages
* get all components

These can be useful queries when building navigation or displays that are assembled by authors based on components

See example of Graph Schema
```
interface Character {
  id: ID!
  name: String!
  friends: [Character]
  appearsIn: [Episode]!
}

type Human implements Character {
  id: ID!
  name: String!
  friends: [Character]
  appearsIn: [Episode]!
  starships: [Starship]
  totalCredits: Int
}

type Droid implements Character {
  id: ID!
  name: String!
  friends: [Character]
  appearsIn: [Episode]!
  primaryFunction: String
}
```
**Describe the solution you'd like**
Support a Hierarchy of interfaces
```
ContentItem
  +---Page
  |      +---[THE SPECIFIC TYPE]
 +---Component
        +---[THE SPECIFIC TYPE]
```
**Describe alternatives you've considered**
Provide a single parent type [ContentItem] and index a type field that could be filtered on

**Comment by avasquez614** [comment]
@russdanner Added `pages`, `components` and `contentItems` fields to query. Please verify

**Comment by russdanner** [comment]
Confirmed!
