### ISSUE TITLE
[studio-ui] Sidebar is not being refreshed with elements inside Videos

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3079]
## Describe the bug
Sidebar is not being refreshed with elements inside `Videos` using videocenter BP.
## To Reproduce
1. Create a site using the videocenter BP
2. Open the Sidebar, expand Videos and edit the `Title` of a video.

## Expected behavior
The Sidebar is refreshed, there should be a icon of edited over the icon and the `Title` should change to the value edited.

## Screenshots
![sidebarRefreshItems](https://user-images.githubusercontent.com/6722074/56162283-dbd6f700-5f88-11e9-9a74-75d92907d782.gif)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.0-SNAPSHOT-2abecc
Build Number: 2abecc7a723936c2e51d055dc9d7ea013c6f5a24
Build Date/Time: 04-15-2019 13:44:46 -0600

### OS
Linux

### Browser
Chrome/Firefox

## Additional context
A refresh using the browser updates the ui.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1129

**Comment by yacdaniel** [comment]
Verified fixed.
![videocenterRefresh](https://user-images.githubusercontent.com/6722074/56322157-88e67680-6125-11e9-84ec-1b16fc9e49fa.gif)
