### ISSUE TITLE
Studio: When a component is created some fields are missing.

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#308]
We have a content-type with two date picker controls (publishedDate_dt & expiryDate_dt) and a repeating group (sections), when creating a new component we have this issue: if we add an item to the repeating group the date picker values are not stored in the xml.

When editing the content after it is created, the values are added to the xml.

Attached you can find the content-type definition.

[form-definition.xml.txt](https://github.com/craftercms/craftercms/files/639858/form-definition.xml.txt)

**Comment by russdanner** [comment]
Hi Jose V, This was assigned to Jose R. Check with him to make sure this is not already underway first.
