### ISSUE TITLE
[studio-ui] add drag and drop image insertion support to TinyMCE5

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3084]
**Is your feature request related to a problem? Please describe.**
Users should be able to drag and drop images from their desktop in to the RTE where they want them inserted.  

**Describe the solution you'd like**
Dragging and dropping and image from the desktop should trigger a UX flow via dialog where the user can chose the data source and then go through the appropriate steps for the data source to get the image uploaded.

Ideally the user does not need to "Re-drag" from the desktop the image to initiate the upload to the data source.

**Comment by sumerjabri** [comment]
If no Desktop data source is present, reject the upload (fail it) with a note to the user.

**Comment by russdanner** [comment]
Confirmed in form engine
