### ISSUE TITLE
[studio-ui] Clicking on a page in the search results doesn't work in some BPs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3085]
## Describe the bug
Clicking on a page in the search results page doesn't work in some blueprints.

## To Reproduce
1. Create a site using Headless Store BP
2. Click on search
3. Click on a page
4. Nothing happens, open the inspector and see the problem

## Expected behavior
Clicking on a page should take you to that page in preview regardless of the BP used.

### Version
3.1.0-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1130

**Comment by sumerjabri** [comment]
Verified.
