### ISSUE TITLE
[studio] post-activity.json returns "No such property: ActivityService"

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3086]
## Describe the bug
post-activity.json returns `No such property: ActivityService for class: post-activity_post`

## To Reproduce
1. Create a site from editorial bp
2. POST request `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H "accept: application/json" -H "Content-Type: application/json" -v -X POST http://localhost:8080/studio/api/1/services/api/1/activity/post-activity.json?site_id=testid&user=admin&path=/site/website/index.xml&activity=UPDATE&contentTypeClass=pages` 
3. Check response `"message": "No such property: ActivityService for class: post-activity_post"`

## Expected behavior
Response `Status 200 OK` and no error in logs

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/yacdaniel/eb0e4632ea0edd100d6560e999888a30

### Version
Studio Version Number: 3.1.0-SNAPSHOT-8d8a81
Build Number: 8d8a818807d430eec893a6000f0cf1f0c20fcc71
Build Date/Time: 04-17-2019 06:49:20 -0600

### OS
Linux Ubuntu

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
This is an old audit service. It is deprecated now.

PR:
https://github.com/craftercms/studio/pull/1570

**Comment by yacdaniel** [comment]
@dejan-brkic a call to `post-activity.json` now returns `"message": "API deprecated."`
but `My Recent Activity` now is broken
![image](https://user-images.githubusercontent.com/6722074/56322848-59386e00-6127-11e9-8716-0f587d7e23d6.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1572

**Comment by sumerjabri** [comment]
Verified.
