### ISSUE TITLE
[studio] site-config-tools configuration file is missing the <controls> tag after upgrading site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3087]
## Describe the bug
When you upgrade a site from 3.0.20 to the latest develop, the site-config-tools configuration file is missing the \<controls\> tag, so, when you try to view a content type, the properties, controls and datasources are not rendered

## To Reproduce
1. Create a site in a 3.0.20 studio install
2. Clone, build and deploy the develop branch of craftercms
3. Copy the data folder from the 3.0.20 studio install, then paste it to the install from the previous step (craftercms develop branch)
4. Start studio with Solr, `./gradlew -PwithSolr=True start`
5. Upgrade Solr cores by following the guide here: https://docs.craftercms.org/en/3.1/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.html
6. Preview your upgraded site
7. Click on `Site Config`  then `Content Types`
8. Open an existing content type, let's pick `Page - Article`
9. Notice the right hand side is empty (no properties, controls and datasources)
![Screen Shot 2019-04-16 at 3 24 22 PM](https://user-images.githubusercontent.com/25483966/56314378-e5946200-6122-11e9-9c69-2da08bc14a66.png)
10. View the Site Config Tools configuration file, and notice that the \<controls\> tag is missing.

The site-config-tools config file should go like:
```
<config>
	<tools>
		<tool>
			...
			<controls>
				<control>
					...
				</control>
				<control>
					...
				</control>
				...
			</controls>
			...
		</tool>
	</tools>
</config>
```

When you upgrade the site, it looks like this:
```
<config>
	<tools>
		<tool>
			...
			<control>
			...
			</control>
			<control>
			...
			</control>
			...
			...
		</tool>
	</tools>
</config>
```

## Expected behavior
\<controls\> tag should not be removed from the site-config-tools configuration file, which would let the properties, controls and datasources be rendered when viewing a content type

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.0-SNAPSHOT-8d8a81
Build Number: 8d8a818807d430eec893a6000f0cf1f0c20fcc71
Build Date/Time: 04-17-2019 14:47:35 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1571

**Comment by alhambrav** [comment]
Verified fixed.
