### ISSUE TITLE
[studio-ui] Duplicate dialog is not clickable after publishing an item

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3088]
## Describe the bug
Duplicate dialog is not clickable after publish an item

## To Reproduce
1. Create a new site using a BP
2. Go to Preview
3. Go to sidebar, right click and select duplicate opt, see it is working
4. Go to sidebar, right click and select publish opt, and then submit.
5. Go to sidebar, right click and select duplicate opt, see that dialog is not clickable

## Expected behavior
Duplicate dialog should be always clickable

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1133

**Comment by sumerjabri** [comment]
Verified.
