### ISSUE TITLE
[studio] New site created is using Solr instead of Elasticsearch when Studio has upgraded sites using Solr

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3089]
## Describe the bug
After upgrading a site and using Solr for the upgraded site, create a new site and notice that the new site is using Crafter Search/Solr for the search engine instead of Elasticsearch

## To Reproduce
1. Create a site in a 3.0.20 studio install
2. Clone, build and deploy the develop branch of craftercms
3. Copy the data folder from the 3.0.20 studio install, then paste it to the install from the previous step (craftercms develop branch)
4. Start studio with Solr, ./gradlew -PwithSolr=True start
5. Upgrade Solr cores by following the guide here: https://docs.craftercms.org/en/3.1/system-administrators/upgrade/upgrading-to-craftercms-3-1-0.html
6. Preview the site you upgraded
7. Click on the `Main Menu` and click on `Sites`
8. Click on `Create Site` and select `Website_editorial` bp
9. Notice the error message in the site preview
<img width="1440" alt="Screen Shot 2019-04-18 at 2 13 10 AM" src="https://user-images.githubusercontent.com/25483966/56340354-afd19680-617f-11e9-819d-29a3e394718e.png">
10. Look at the logs and notice that the newly created site seems to be using Crafter Search/Solr instead of Elasticsearch

```
[ERROR] 2019-04-17T17:44:20,262 [http-nio-8080-exec-10] [controller.ExceptionHandlers] | Request /crafter-search/api/2/search/search failed with status 500
```

## Expected behavior
The new site should use Elasticsearch as the search engine

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/alhambrav/dedad0f61a87a70a4d3fd022a7a2b80a

### Version
Studio Version Number: 3.1.0-SNAPSHOT-a9a9be
Build Number: a9a9bed7345e34a4bbcc1b6f4e73f0bf2e69d9a6
Build Date/Time: 04-17-2019 17:26:50 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1573

**Comment by alhambrav** [comment]
Verified fixed.
