### ISSUE TITLE
[studio] The upgrade manager is deleting all blueprints

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3094]
## Describe the bug
During startup, the upgrade manager deletes all blueprints from the global repo

## To Reproduce
1. Deploy a new environment with `./gradlew build deploy start`
2. Check that `data/repos/global/blueprints` only has the manifest file

## Expected behavior
The rename operations should not delete existing folders if the file/folder to be renamed does not exist

### Version
3.1.0-SNAPSHOT-5d6ea3

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1575

**Comment by jdrossl** [comment]
Verified
