### ISSUE TITLE
[studio] Add default dep resolver to Studio and allow BPs to overwrite

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3095]
Right now BPs govern dependency resolution via config, but Studio doesn't have defaults.

Please add defaults and allow BPs to overwrite if needed.

Please use the latest config from `samples` as a starting point.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1576

**Comment by sumerjabri** [comment]
Verified fixed.
