### ISSUE TITLE
[docs] Update code style and add copy-to-clipboard

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3098]
Please update the code block style to be more legible and add a button to quickly copy to clipboard.

Please see this as an example: https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#add-resource-configs-for-mysql-and-wordpress

**Comment by alhambrav** [comment]
Hi!  @jvega190 here are some things I noticed for the copy button: 
It looks like for code-blocks with linenos,  the copy button appears when you hover:
<img width="611" alt="Screen Shot 2019-07-23 at 2 43 31 PM" src="https://user-images.githubusercontent.com/25483966/61738646-beb87e00-ad58-11e9-9ada-7d57a102df3f.png">

Also note that for code-blocks with linenos, if the text does not wrap, you will have to move the bottom scroll bar all the way to the right to be able to see the copy button:
<img width="1297" alt="Screen Shot 2019-07-23 at 2 49 00 PM" src="https://user-images.githubusercontent.com/25483966/61738847-2ec70400-ad59-11e9-8be6-c058cb1f7965.png">

For code-blocks without linenos, the copy button is not available:
<img width="699" alt="Screen Shot 2019-07-23 at 2 43 53 PM" src="https://user-images.githubusercontent.com/25483966/61738881-469e8800-ad59-11e9-8ec8-fb97242168e1.png">

The screenshots were taken from this page: https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-mongodb-configuration.html

**Comment by jvega190** [comment]
https://github.com/craftercms/docs/pull/791
@alhambrav fixed issue where codeblocks with no lineos didn't have copy button. Not wrapped text enhancement will be worked separately.

**Comment by jvega190** [comment]
https://github.com/craftercms/docs/pull/828

**Comment by sumerjabri** [comment]
Verified.
