### ISSUE TITLE
[studio-ui] Image in RTE not retaining adjusted size when creating a new section

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3099]
## Describe the bug
Image in RTE not retaining adjusted size when creating a new section

## To Reproduce
1. Create a site using website_editorial bp
2. Preview an article and edit
3. Scroll down to the sections and click on `Add Another`
4. In the new section, insert an image by clicking on `Insert` -> `Image` then `Upload Images` 
5. In the short clip below, I uploaded a large image, resize the image by dragging the corners of the image
6. Click on `Add Another` to add another section.  Notice that the image you just resized in the previous section has reverted to the size when it was uploaded.

## Expected behavior
The RTE should retain the image size (resized) after adding another section

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://www.loom.com/share/50e773cea84d401eae47bda75be504ab

### Version
Studio Version Number: 3.1.0-SNAPSHOT-829b22
Build Number: 829b2296ae751a16e8007e079a697c638ece6d44
Build Date/Time: 04-24-2019 10:15:19 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1135

**Comment by alhambrav** [comment]
Verified fixed.
