### ISSUE TITLE
[studio-ui] Dates are off in version history

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#310]
Dates around UI are off by 1 (thats ok I was in CT time zone) but dates are off in version history by 5 hours (GTM)

**Comment by jvega-crafter** [comment]
"lastModifiedDate" is set up wrong, it should be the current time of last modification in server configured timezone.

**Comment by dejan-brkic** [comment]
PR #470

**Comment by russdanner** [comment]
Failed Testing.  Please rework and submit or provide proper testing instructions.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/186

**Comment by gortizcrafter** [comment]
The behavior is correct, the time shown is correct using different time zones.

1. Edit new or old content
2. View the history (the time/date shown is fine)

3. Publishing new or old content
4. View the history (the time/date shown is fine)

https://www.screencast.com/t/AF1Lr52HJy
