### ISSUE TITLE
[studio-ui] Missing validation msg in Push to Remote Git Repo and Use a remote Git repository instead

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3100]
## Describe the bug
Missing validation msg when creating site using `Push to Remote Git Repo` and using the option `Use a remote Git repository instead`

## To Reproduce
1. In the Create Site dialog choose any BP
2. Set a site id and click `Additional Developer Options` button
3. Check the checkbox `Push the site to a remote Git repository after creation` 
4. In `Authentication Type:` select `Remote Git Repository Private Key`. Notice that there is no `*` used for the required fields
5. Click in another field, a validations msg is not present.
6. Go back to the start of the Create Site dialog, instead of choosing a blueprint, check `Use a remote Git repository instead of a built-in blueprint` and click `Basic Information` button.
7. Set a site id and click `Basic Developer Options` button
8. In `Authentication Type:` select `Remote Git Repository Private Key`. Notice that there is no `*`used for the required fields
9. Click in another field, a validations msg is not present.
10. Select different `Authentication Types`, notice that there is no validation msg for `Basic` and `Remote Git Repository Token`. 

## Expected behavior
- A `*` at the beginning of `Remote Git Repository Private Key` as used for the required fields.
- Validation for `Remote Git Repository Private Key` when using the option `Push the site to a remote Git repository after creation`.
- Validations for `Basic`, `Remote Git Repository Token`, `Remote Git Repository Private Key` when using the option `Use a remote Git repository instead of a built-in blueprint`.

## Screenshots
https://www.loom.com/share/a9dc67bd3b0545a5816ee3d0bc3f8674

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.0-SNAPSHOT-829b22
Build Number: 829b2296ae751a16e8007e079a697c638ece6d44
Build Date/Time: 04-24-2019 05:07:31 -0600

### OS
Linux Ubuntu 16.04

### Browser
Chrome, Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1137

**Comment by yacdaniel** [comment]
Verified fixed.
