### ISSUE TITLE
[studio-ui] Right-click popup on templates has some weird lines

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3101]
## Describe the bug
When you right-click a file under the Templates folder and the popup appears, the popup is drawn with a couple of unnecessary lines or borders over the `Create Template` option.

## To Reproduce
1. In any site, right click on a file under the Templates folder. The popup that appears should look like the one in the image attached.

## Expected behavior
The extra lines shouldn't appear

## Screenshots
![popup](https://user-images.githubusercontent.com/1598884/56686345-c73de180-66a1-11e9-897a-5e8f41d316ef.png)

**Comment by vestrada** [comment]
https://github.com/craftercms/studio-ui/pull/1138

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1140

**Comment by avasquez614** [comment]
Verified
