### ISSUE TITLE
[studio-ui] Creating a template doesn't refresh the sidebar

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3102]
## Describe the bug
When you create a new Template, the sidebar is not refreshed. Cutting/pasting a file in Templates has the same issue.

## To Reproduce
1. Create a site based on editorial bp.
2. Go under Templates > web > components and right click and chose `Create Template`.
3. Put any valid Fremarker in the template, and save.
4. The new file should appear in the sidebar, but it doesn't.

## Expected behavior
The sidebar should be refreshed with the changes when a template is created or is cut/pasted.

**Comment by yacdaniel** [comment]
@vestrada I also noticed that creating a folder in any place from the sidebar is not refreshing it
![folderNoRefresh](https://user-images.githubusercontent.com/6722074/56688741-af149500-6696-11e9-9b60-8786c1484866.gif)

same as creating a controller under `Scripts` 
![controller](https://user-images.githubusercontent.com/6722074/56688830-eaaf5f00-6696-11e9-8937-8a2a62289511.gif)

**Comment by vestrada** [comment]
PR: craftercms/studio-ui#1138

**Comment by vestrada** [comment]
@yacdaniel please check refresh on sidebar

**Comment by yacdaniel** [comment]
Verified fixed, refresh on sidebar looks good.
