### ISSUE TITLE
[studio-ui] After saving a content type without template, and selecting another content type, the screen becomes unresponsive

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3103]
## Describe the bug
When editing a content type without a template, saving it, getting the warning that the content type has no template, clicking on Save, and then trying to open another content type, causes the screen to gray out and become unresponsive. Only by doing a browser refresh can you work again on the Site Config

## To Reproduce
1. Create a site based on the editorial blueprint.
2. Go to Site Config.
3. Create a new content type.
4. Add some field and try to save it. The "no template" warning will appear. Click on Save.
5. Click on Open Existing Content type.

The screen grays out and becomes unresponsive, as shown in the screenshot.

## Expected behavior
The screen should work as normal.

## Screenshots
![grayed-out](https://user-images.githubusercontent.com/1598884/56690278-16d4db00-66ab-11e9-8221-b18e3cd9dbec.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1136

**Comment by avasquez614** [comment]
Verified
