### ISSUE TITLE
[studio-ui]  Some actions in history dialog are failing. 

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3108]
## Describe the bug
Some actions in history dialog are failing when user tries to compare or view the file when the item is template, scripts, HTML...

## To Reproduce
1. Go to Sidebar
2. Scroll down to and Right Click on any template.
3. Select history
4. Cilc in compare or view icons
5. See the error.

## Expected behavior
I think the icons for those functions shouldn't be visible.

## Screenshots
https://www.loom.com/share/830fac52ad9a4cd5864175630d0ad0f9

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1139

**Comment by vestrada** [comment]
Verified
