### ISSUE TITLE
[studio] Dashboard activities from deleted site are present when a new site is created with the same site id of a previously deleted site.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3109]
## Describe the bug
Dashboard activities of a deleted site are being displayed in a new site if this new site has the same site id of the deleted site.

## To Reproduce
1. Create a site with site id `test` then made some changes and view the changes in the dashboard
2. Remove the site `test` from studio
3. Create a new site using the same site id as in 1. `test`
4. Go to the dashboard, the activities from the site in 1 are present.

## Expected behavior
Dashboard activities are clean each time a site is created, without information about another site.

## Screenshots
https://www.loom.com/share/90211e7764ef474e91beb9be5ff88f2f

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.0-SNAPSHOT-271080
Build Number: 27108093400c2dac3317f9b3a288c0d40913b7ff
Build Date/Time: 04-25-2019 10:11:04 -0600

### OS
Linux/Mac

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1578

**Comment by yacdaniel** [comment]
verified fixed.
