### ISSUE TITLE
[studio-ui] After open history dialog, some dialogs aren't clickable

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3110]
## Describe the bug
After open history dialog, some dialogs aren't clickable.

## To Reproduce
1. Go to sidebar
2. Scroll down to templates for example
3. Right Click on a ftl file
3. Click on history opt and close
4. Right Click on a ftl file
5. Choose create template
6. It is not clickclable

## Expected behavior
History should destroy all its overlays.

## Screenshots
https://www.loom.com/share/1dd6a7ae50a44243abd6f64798522502

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1141

**Comment by vestrada** [comment]
Verified
