### ISSUE TITLE
[studio-ui] When editing a content type and cancelling changes, the screen becomes unresponsive

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3111]
## Describe the bug
When editing a content type, clicking on `Open Existing Type`, and then clicking yes on abandon changes, the screen grays out and becomes unresponsive.

## To Reproduce
1. Create a site based on Editorial bp.
2. Go to Site Config and open the Home page content type.
3. Change the order of some fields.
4. Click on `Open Existing Type`, and click on yes to the abandon changes dialog.

The screen immediately grays out and becomes unresponsive.

## Expected behavior
The screen should work normally.

## Screenshots
![grayed-out2](https://user-images.githubusercontent.com/1598884/56765141-72b76680-6774-11e9-88eb-540883bd631e.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1142

**Comment by avasquez614** [comment]
Verified
