### ISSUE TITLE
[studio-ui] Preview Assets in Browse page for s3, cmis webdav is not working

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3120]
## Describe the bug
Preview Assets in Browse page for s3, cmis webdav is not working. Also You can see at the end of the page extra DOM elemets (trash).

## To Reproduce
1. Create a site using a BP
2. Add s3, webdav and cmis Controls
3. Got to the page and edit the form
4. Browse new item
5. See the bug

## Expected behavior
Preview Assets should work as it is default browse

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![image](https://user-images.githubusercontent.com/11640613/56911377-06857d00-6a6a-11e9-9bd8-aeaefa39d93b.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1146

**Comment by yacdaniel** [comment]
Verified fixed, no extra DOM elemets(trash)
![imagen](https://user-images.githubusercontent.com/6722074/56991869-006cca80-6b56-11e9-95dc-33d56a84bec3.png)
