### ISSUE TITLE
[studio-ui] Please destroy select template dialog after click on ok

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3122]
## Describe the bug
Some dialogs are unclickable after open select template dialog and click on ok button.

## To Reproduce
1. Create a site using a BP.
2. go to site configuration
3. Open a content type.
4. Click on Workflow states
5. Click on set state. 
6. See the error

## Expected behavior
 Select template dialog should be destroy after select a template.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1147

**Comment by yacdaniel** [comment]
Hi @vestrada looks like the original issue is fixed, but I found this:
https://www.loom.com/share/0180b6e3174e42daa46ffaaabccd6975
I change the state of 1 item 2 times, then I try to change the state using the `Select All` option, the dialog is not closing when I click the set state.
Could you take a look? thanks.

**Comment by yacdaniel** [comment]
Closing as fixed, the issue found will be worked in https://github.com/craftercms/craftercms/issues/3134
