### ISSUE TITLE
[videocenter] Search icon does not seem to work as expected when in the search results page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3127]
## Describe the bug
Search icon does not seem to work as expected when in the search results page

When you click on the search icon for the first time and perform a search, it works as expected.  From the search results page, if you click on the search icon again at the top right and try to perform another search, it does not do anything.

## To Reproduce
1. Create a site using the videocenter bp
2. Click on the search icon (magnifying glass) at the top right.
3. Enter a search term, `quantum`, a couple of results should show up
4. Click on the search icon (magnifying glass) at the top right again
5. Enter a searcg term, `sleep`, notice that it does not look like it performed a search for the tem `sleep`

## Expected behavior
Search should be performed every time the search icon is clicked and a search term entered on any page

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's a short clip:
https://www.loom.com/share/05cc591ef7014c68bcaef441a9b62b40

### Version
Studio Version Number: 3.1.0-SNAPSHOT-0236e6
Build Number: 0236e670073b2657c88dec6192aa057ea2cfef19
Build Date/Time: 04-30-2019 14:40:17 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/34

**Comment by alhambrav** [comment]
Verified fixed.
