### ISSUE TITLE
[studio-ui] Dependencies are shown incorrectly

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3128]
## Describe the bug
When inspecting the dependencies of an items (after right click > `Dependencies`), the dependencies shown in `Depends on` and the ones shown in `Depends on me` appear to be switched.

## To Reproduce
1. Create a site based on Editorial bp.
2. Right click on Home, then select `Dependencies`.
3. Switch the dropdown to `Depends on me`.

The dependencies shown are wrong, the ones that appear should be on `Depends on` (see screenshot).

## Expected behavior
The dependencies should be shown correctly.

## Screenshots
![dependencies](https://user-images.githubusercontent.com/1598884/57022398-08cc1080-6bfd-11e9-8b8f-e53969db4ddf.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1150

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1151

**Comment by avasquez614** [comment]
Verified
