### ISSUE TITLE
[studio-ui] User first name and last name is not displayed in the Account Management screen

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3132]
## Describe the bug
User first name and last name is not displayed in the Account Management screen

## To Reproduce
1. Login to Studio
2. Click on the \<user name\> at the top right, then click on `Settings 
3. Notice there is no user first name and last name listed above the email address in the Account Management screen

![Screen Shot 2019-05-06 at 12 40 15 PM](https://user-images.githubusercontent.com/25483966/57243464-31d91080-7004-11e9-8923-396899abd4b9.png)

## Expected behavior
The user first name and last name should be displayed in the Account Management screen, like below:

![Screen Shot 2019-05-06 at 12 39 54 PM](https://user-images.githubusercontent.com/25483966/57243388-05bd8f80-7004-11e9-9086-c2070cbe913f.png)

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-45408d
Build Number: 45408d52ece705a6a2d24f4aeb9fbaee56195e56
Build Date/Time: 05-06-2019 12:16:36 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
Sometimes the user first name and last name is displayed, but I can't reliably reproduce when.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1158

**Comment by alhambrav** [comment]
Verified fixed.
