### ISSUE TITLE
[studio] Update the upgrade manager to include new upload CMIS datasources

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3133]
Update the upgrade manager to include new upload CMIS datasources

Make CMIS datasources consistent with WebDav and S3 datasource, so we'd have something like the following for CMIS:

File from CMIS Repository
Image from CMIS Repository
Video from CMIS Repository
File Uploaded to CMIS Repository
Image Uploaded to CMIS Repository
Video Uploaded to CMIS Repository

Please see: https://github.com/craftercms/craftercms/issues/2812

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1596

**Comment by sumerjabri** [comment]
Verified fixed.
