### ISSUE TITLE
[studio-ui] select states dialog can't be clickable when using Select All

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3134]
## Describe the bug
The `Set States` dialog in the `Workflow States` from `Site Config`  is not responsive after using `Select All`

## To Reproduce
1. Create a site form any BP
2. Go to site `Site Config` and then `Workflow States` 
3. Click the `Select All` option, then click `Set States`
4. In the `Select States` popup click the checkbox `System Processing` to change the current value from `False` to `True`
4. Click `Set States`
5. Repeat step 3 and 4, this time in `System Processing: ` should be unchecked, to change from `True` to `False`
6. Click `Set States`
7. Notice popup/application is unresponsive.

## Expected behavior
Application responsive, popup should be closed.

## Screenshots
https://www.loom.com/share/f9ed80483c9a49828f7008209d69d038

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-45408d
Build Number: 45408d52ece705a6a2d24f4aeb9fbaee56195e56
Build Date/Time: 05-06-2019 11:05:13 -0600

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1155

**Comment by yacdaniel** [comment]
Verified fixed.
