### ISSUE TITLE
[studio-ui] Change the "Content Type" and "Mime Type" filter selection to checkboxes in Studio search

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3135]
## Describe the bug
Change the "Content Type" and "Mime Type" filter selection to checkboxes in Studio search.  Say the user wants to search for all `Page` content type, the user is not able to make multiple selections, since we have radio buttons instead of checkboxes.

## To Reproduce
1. Click the Studio search icon on the top right
2. Click on `Filters` and select `Content Type`
3. Notice that it uses radio buttons instead of checkboxes
**Content Type**
![Screen Shot 2019-05-07 at 3 09 27 PM](https://user-images.githubusercontent.com/25483966/57326312-35d76200-70da-11e9-87f7-27fbd42dec11.png)
4. Click on `Mime Type`, notice that it also uses radio buttons instead of checkboxes
**Mime Type**
![Screen Shot 2019-05-07 at 3 10 31 PM](https://user-images.githubusercontent.com/25483966/57326380-5e5f5c00-70da-11e9-8454-5cb96c787b05.png)

## Expected behavior
Checkboxes for the `Content Type` and `Mime Type` filters should be used instead of radio buttons to allow users multiple selections

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-4fe160
Build Number: 4fe160c61191f8312f602cd7f6104fd5013e2aec
Build Date/Time: 05-07-2019 07:55:18 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
There's backend work needed. Will assign @jdrossl.

**Comment by jdrossl** [comment]
@jvega190 the service now supports multiple values for facets, the UI needs to be updated to handle them

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1208

**Comment by alhambrav** [comment]
@jvega190 In the content type filter,  
![Screen Shot 2019-07-15 at 10 57 30 AM](https://user-images.githubusercontent.com/25483966/61227906-42d48b00-a6f3-11e9-9587-a1db4661d267.png)

after checking some of the checkboxes, the other checkboxes disappear:
![Screen Shot 2019-07-15 at 10 57 52 AM](https://user-images.githubusercontent.com/25483966/61227959-54b62e00-a6f3-11e9-93bd-6b4b12f2accb.png)

If I want to check all the component content types, I need to be very quick making the selection so I can check all of the items that I want.

It would be nice if the other checkboxes don't disappear after making some selections so the user can see all the time what items are available.

Here's a short clip showing the behavior mentioned above (I was trying to select all the component content type in the filter): https://www.loom.com/share/c8bc0f98b19d4e0ab688bfc79528a724

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1238

**Comment by alhambrav** [comment]
Verified fixed.
