### ISSUE TITLE
[studio-ui] graphiql should work when accessed from URL differents than localhost

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3136]
## Describe the bug
GraphiQL doesn't load when authoring is accessed from URL that is not localhost

## To Reproduce
1. Login to authoring using a URL that is not localhost e.g : 127.0.0.1, hostname, local IP.
2. Create a site from any BP 
3. Go to `Site Config` and then `GraphiQL`

## Expected behavior
GraphiQL works with different host values

## Screenshots
Notice the call to `http://localhost:8080/api/1/site/graphql` when crafter is accessed through laptop's hostname `Yacdaniels-MacBook-Pro.local`
<img width="1290" alt="Screen Shot 2019-05-08 at 13 33 53" src="https://user-images.githubusercontent.com/6722074/57404251-c7a5a480-7198-11e9-82cc-d58a7cd7af81.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-c0a876
Build Number: c0a8763559d20fe86b5dee5e68365506de43a9bd
Build Date/Time: 05-08-2019 08:11:44 -0600

### OS
Linux

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by avasquez614** [comment]
@jvega190 I think this is not an issue, and it's just a matter of configuring the GraphiQL URL, but check and let me know.

**Comment by jvega190** [comment]
@avasquez614 @yacdaniel yes, this is not an issue, GraphiQL URL needs to be properly configured in order to work. Configuration can be changed in `/config/studio/environment/environment-config.xml` under `graphql-server-url`.
Please let me know if you need more details.

**Comment by jdrossl** [comment]
@jvega190 please switch GraphiQL to use `GET` instead of `POST`, that should prevent the `403` response that Yac is getting

**Comment by jvega190** [comment]
@yacdaniel Even though I updated graphiql to use get method for calls, the CORS error was still showing. Config for graphi is needed in this scenario.

**Comment by yacdaniel** [comment]
@alhambrav could you add a note in the docs about this issue? maybe in https://docs.craftercms.org/en/3.1/developers/cook-books/graphql/index.html ?
Saying that if the user access authoring from a URL different than localhost, that URL value(IP, hostname, etc) should be added in the `Site Config - Configuration - Environment Configuration` the value in the tag `<graphql-server-url>http://localhost:8080</graphql-server-url>`

**Comment by alhambrav** [comment]
PR: https://github.com/craftercms/docs/pull/752 commit: https://github.com/craftercms/docs/pull/752/commits/a957ed79c280e0d216444cd2746f480dc6dfe1c1

**Comment by yacdaniel** [comment]
Verified fixed.
