### ISSUE TITLE
[studio] site start up failure blocks access to other sites

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3137]
## Describe the bug
A site configuration parsing issue (XML parsing error) in one site blocks the entire get-sites API from working properly which renders the sites list in Crafter Studio broken.

## To Reproduce
1. Create a site
2. Alter the site's environment-config.xml so that it is INVALID XML
3. Commit the changes
4. Note that the Studio sites list will begin to fail

Note: Fixing the configuration error and committing will restore the dashboard to proper functioning order.  The work around is to fix the configuration issue that's causing the problem.

## Expected behavior
One site's failure to start should not impact any other site.

## Screenshots
When site configuration is bad the list of sites in Studio does not show due to get-sites API call failure.

On the first load the site screen is completely empty:
<img width="1415" alt="No-sites" src="https://user-images.githubusercontent.com/169432/57470382-b327e180-7256-11e9-8d0a-761c54e36a38.png">
On a browser refresh the menu appears but the sites list and create button remain missing
<img width="1420" alt="No-sites-2" src="https://user-images.githubusercontent.com/169432/57470411-c2a72a80-7256-11e9-977f-a51fcf552c7f.png">

Inspection of the REST API calls reveals the error causing the UI to fail:
```
{"response":{"code":1000,"message":"Internal system failure: Unable to get role mappings config for site 'vue-cart'","remedialAction":"Contact support","documentationUrl":""}}
```

Inspection in the tomcat logs shows the root cause which is a configuration issue in one site.
See logs

## Logs
https://gist.github.com/russdanner/9efa01b2cdc97a538b53b1376f144ea0

### Version
```
Studio Version Number: 3.1.0-9ea616
Build Number: 9ea61648fa5b429f1bd229771d036c3032d9ddd3
Build Date/Time: 05-08-2019 10:05:15 -0400```
```
### OS
Any

### Browser
N/A

**Comment by dejan-brkic** [comment]
Cannot reproduce with:

```
Studio Version Number: 3.1.1-SNAPSHOT-c0a876

Build Number: c0a8763559d20fe86b5dee5e68365506de43a9bd
```

**Comment by russdanner** [comment]
Confirmed
