### ISSUE TITLE
[studio-ui] Add a "Date" filter in the Studio search filters

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3138]
**Is your feature request related to a problem? Please describe.**
Users cannot search by date in Studio search
![page-search-filters-sort](https://user-images.githubusercontent.com/25483966/57536317-ebd8c100-7311-11e9-8a70-4de76b55d36b.png)

**Describe the solution you'd like**
Add a "Date" filter in the Studio search filters, to allow users to sort by say, date created or date last modified

**Describe alternatives you've considered**

**Additional context**

**Comment by jdrossl** [comment]
@sumerjabri we need to define the ranges for the new facets, for example they could be:
```
- Today
- This week
- Last week
- Last month
...
```

**Comment by sumerjabri** [comment]
- Today
- Within a week
- Within a month
- Within 6 months
- Within a year
- All

Maybe `All` doesn't exist because it's the default.

**Comment by jdrossl** [comment]
@jvega190 the service is now sending the new facet for the date, the UI needs to be updated to handle it

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1177

**Comment by alhambrav** [comment]
Verified.
