### ISSUE TITLE
RTE Insert Image - Browse modal content is taking about 5 mins to load

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#314]
This issue was reproduced on deep directory structure, the browse modal calls `/studio/api/1/services/api/1/content/get-pages.json?site=sitename&path=/static-assets/images&order=default&nocache=Wed%20Dec%2014%202016%2015:35:19%20GMT-0600%20(CST)`, but the server responds after 5 mins with the result, the result size is about 35Mb, which means that modal load, is not optimized to handle large folders structures:
<img width="1393" alt="screen shot 2016-12-14 at 3 53 01 pm copy" src="https://cloud.githubusercontent.com/assets/813023/21208478/d330b716-c233-11e6-8b54-198d01798a78.png">

Also found, `get-pages.json` service needs the `depth` param, so it will retrieve only N levels instead of retrieve all the deeper levels.

I tried to modify the service call in the https://github.com/craftercms/studio2-ui/blob/master/static-assets/components/cstudio-browse/browse.js#L431 file so instead of `null` pass `2` but if you try to expand children folder, it won't do anything to lazy load the rest of children. 

Seems browse modal still need to be improved and optimized to handle large files structures

**Comment by vestrada** [comment]
per conversation with Ale, this is fixed
