### ISSUE TITLE
[studio-ui] Fix right navigation when the browser is narrow

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3140]
## Describe the bug
Fix right navigation when the browser is narrow

## To Reproduce
1. Create new site using a PB
2. Make your browser narrower by dragging the sides towards the left, notice the right nav is falling down.

## Expected behavior
Right nav bar should look good.

## Screenshots
![image](https://user-images.githubusercontent.com/11640613/57559314-759e8380-733e-11e9-9ad4-7f13bde43fba.png)

![image](https://user-images.githubusercontent.com/11640613/57559362-ada5c680-733e-11e9-8d87-a4cf0f1de6ba.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1167

**Comment by yacdaniel** [comment]
Verified fixed.
![imagen](https://user-images.githubusercontent.com/6722074/58660666-329f5280-82e3-11e9-9e7a-3d62ab804749.png)
