### ISSUE TITLE
[engine] GraphQL should support fragments

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3145]
## Describe the bug
GraphQL queries support inheritance but not fragments

## To Reproduce
See screenshot

## Expected behavior
All fields should be resolved correctly

## Screenshots
<img width="1054" alt="Screen Shot 2019-05-13 at 2 33 22 PM" src="https://user-images.githubusercontent.com/1236955/57652361-99570900-758c-11e9-8bae-300f261c3a42.png">

### Version
3.1.1-SNAPSHOT

**Comment by avasquez614** [comment]
@jdrossl please also add an example in the GraphQL doc of how to use fragments with Crafter

**Comment by avasquez614** [comment]
Verified
