### ISSUE TITLE
[studio-ui] Allow resizing of Data Sources, Controls and Properties Explorer in Content Type

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3146]
**Is your feature request related to a problem? Please describe.**
Allow resizing of Data Sources, Controls and Properties Explorer pane/box in Content Type
There are a lot of Data Sources, Controls and Properties in Content Type and it would be nice if you can resize them so when you're looking for things, you're not limited to 5 or 4 items at a time

**Describe the solution you'd like**
Allow resizing of Data Sources, Controls and Properties Explorer in Content Type as shown in the image below (similar to how you can resize panes in your IDE, say IntelliJ):

![Screen Shot 2019-05-14 at 2 17 47 PM](https://user-images.githubusercontent.com/25483966/57722223-f964b280-7653-11e9-82ef-a7d5e1f82695.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
This was addressed — differently — already.

**Comment by rart** [comment]
This was addressed — differently — already.
