### ISSUE TITLE
[studio-ui] Add title validation when controls are inside repeating group

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3147]
## Describe the bug
When controls are added inside a `Repeating Group` and no `Title` is added to the control, the form can be saved without a notification that the `Title` is empty. 

## To Reproduce
1. Create a site from Editorial BP
2. Go to `Site Config` - `Content Types` - `Open Existing Type` and select `Page - Article`
3. Add any control inside the `Sections Repeating Group` and do not add the title of the control.
4. Click Save

## Expected behavior
The popup `Save Failed. Please fill every title for fields and datasources.` should appear when there is no `Title` for the control inside a `Repeating Group`

## Screenshots
Notice how the notification popup is shown when the control is not in a `Repeating Group`
![contenTypesTitle](https://user-images.githubusercontent.com/6722074/57868527-639a6600-77c0-11e9-923c-012424f32979.gif)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-e7cdd1
Build Number: e7cdd1c16932518745bf73e9f48740e802efe595
Build Date/Time: 05-16-2019 07:40:17 -0600

### OS
Linux

### Browser
Firefox/Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
@rart please route

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1174

**Comment by yacdaniel** [comment]
Verified fixed.
