### ISSUE TITLE
[search] Creating Site spinner does not go away when creating a site from a bp with remote assets

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3152]
## Describe the bug
Creating Site spinner does not go away when creating a site from a bp without graphql

## To Reproduce
1. Start Studio
2. Install your bp without graphql by following the steps here: https://docs.craftercms.org/en/3.1/developers/cook-books/blueprint/index.html
You will need to create a `craftercms-plugin.yaml` file, the images are optional. (You can copy the `craftercms-plugin.yaml` file from one of the default bp, say, the `empty` bp and modify it for your bp).  Remember to create your `craftercms-plugin.yaml` file first before adding and committing your new bp files 
3. In Studio, click on `Create Site` and select the newly installed bp
4. Look in the logs and notice the exception: 
```
Error building the GraphQL schema for site 'yoursite'
```
Notice also that the `Creating Site` spinner does not go away even if you wait for a while.

![Screen Shot 2019-05-20 at 10 46 57 AM](https://user-images.githubusercontent.com/25483966/58035007-d9227100-7af5-11e9-98cd-b9f0d3e83b29.png)

Refresh you browser and notice that your site is created.

## Expected behavior
The `Creating Site` spinner should go away after the site is created

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's the stack trace of the exception which is expected since the bp does not have graphql:
https://gist.github.com/alhambrav/bb15af58c767f891946af8450d587fee

### Version
Studio Version Number: 3.1.1-SNAPSHOT-e7cdd1
Build Number: e7cdd1c16932518745bf73e9f48740e802efe595
Build Date/Time: 05-20-2019 10:18:15 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Ping me for more info

**Comment by alhambrav** [comment]
Here's the response for create.json:
![Screen Shot 2019-05-23 at 9 49 46 AM](https://user-images.githubusercontent.com/25483966/58258493-d6678c00-7d40-11e9-90f0-96e1577e693d.png)

**Comment by vestrada** [comment]
![image](https://user-images.githubusercontent.com/11640613/58269065-f2b8f800-7d43-11e9-93d8-a05f3ba20d37.png)

**Comment by vestrada** [comment]
Ui is waiting 10 mins to get the response this is why the spinner seems to goes for ever.
Dejan please verify if something is happening trough BE to take so much time. Vita is going to comment the size of the BP.

**Comment by alhambrav** [comment]
Hi!  I checked the size of the blueprint and it says 58.1 MB, whereas the website editorial is 10.8 MB

**Comment by dejan-brkic** [comment]
```
Studio Version Number: 3.1.1-SNAPSHOT-35a73c

Build Number: 35a73c9c57acb78bc685cce83c9bafb187f1e52d
```

Create site does not spin for a long time.
The error message is still in the logs but it is not coming from the studio. It is coming from the preview engine.

**Comment by sumerjabri** [comment]
@alhambrav I'm unable to reproduce. Ping me if you'd like me to demo.

**Comment by sumerjabri** [comment]
@jdrossl I can show you how to reproduce this. GraphQL shouldn't be trying to build the schema for a Solr site. Let's discuss.

**Comment by jdrossl** [comment]
@sumerjabri the spinner issue is caused because the deployer is indexing remote files from Box and there is an error there, I will send a fix for that.

The GraphQL error log is caused by a content error in the blueprint, we have no issue building the schema even if the site uses Solr, but if we want to change that maybe we should file a ticket with the new requirements for that.

**Comment by sumerjabri** [comment]
@jdrossl please send a PR to fix the BP problem as well.

**Comment by jdrossl** [comment]
@alhambrav there are also changes in the blueprint to fix some of the issues, so please update it in your global repo for testing

**Comment by alhambrav** [comment]
Verified fixed.
