### ISSUE TITLE
[studio][videocenter] disabled field is missing from most of the blueprints

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3153]
## Describe the bug
The field `disabled` is present in the content type `form-definition` but is missing in the site/components index.xml file. 
## To Reproduce
1. Create a site using Editorial BP
2. Check one of the articles file from the site `crafter-authoring/data/repos/sites/editorial/sandbox/site/website/articles/2017/3/top-clubs-in-virginia/index.xml`. Notice that there is is no `disabled` field
3. Components files are also missing the field, for example `crafter-authoring/data/repos/sites/editorial/sandbox/site/components/contacts/contact-widget.xml`
4. Right-click any page/component and click edit
5. Click save and close
6. Right-click the edited file and click History
7. Compare the two versions
8. Notice that `disabled` field was added

## Expected behavior
The field `disabled` is added in the blueprint page/components files that have it defined in their content types

## Screenshots
Diff of edited article.
{{If applicable, add screenshots to help explain your problem.}}
![image](https://user-images.githubusercontent.com/6722074/58107437-1561da00-7ba7-11e9-9890-723d2dc6d9b0.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-e7cdd1
Build Number: e7cdd1c16932518745bf73e9f48740e802efe595
Build Date/Time: 05-20-2019 05:25:57 -0600

### OS
Linux

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Not really an issue. The `disabled` flag is not present by default and will be added upon writing content. We can add it to all default content, but it won't make a big difference.
