### ISSUE TITLE
[studio] LDAP user is not marked as externally managed

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3154]
## Describe the bug
LDAP user is not marked as externally managed

## To Reproduce
1. Setup Studio for LDAP authentication
2. Start Studio and login as the LDAP user (`jbloggs` is used in the short clip attached)
3. Sign out the LDAP user then login as Studio `admin`
4. Click on `Users` from the main menu
5. Click on the pencil next to the userid of the LDAP user
6. Notice that the checkbox for `Externally Managed` is not checked
![Screen Shot 2019-05-21 at 2 56 53 PM](https://user-images.githubusercontent.com/25483966/58123029-e7958900-7bd8-11e9-8946-c100f149e48e.png)
7. Check the database and the user is also not marked externally managed:
```
+----+---------------------+----------+-----------------------------------------------------------------------+------------+-----------+--------------------+----------+--------+-----------------------+---------+---------+
| id | record_last_updated | username | password                                                              | first_name | last_name | externally_managed | timezone | locale | email                 | enabled | deleted |
+----+---------------------+----------+-----------------------------------------------------------------------+------------+-----------+--------------------+----------+--------+-----------------------+---------+---------+
|  1 | 2019-05-21 14:46:31 | admin    | vTwNOJ8GJdyrP7rrvQnpwsd2hCV1xRrJdTX2sb51i+w=|R68ms0Od3AngQMdEeKY6lA== | admin      | admin     |                  0 | EST5EDT  | en/US  | evaladmin@example.com |       1 |       0 |
|  2 | 2019-05-21 14:48:46 | jbloggs  | OAelsYGdn7N+XmslV9pE8uiHah1fcYkOdAiCdyNzqBw=|WbOxxJAII+unGVWTAKPVxw== | Joe Bloggs | Bloggs    |                  0 |          |        | joe@example.com       |       1 |       0 |
+----+---------------------+----------+-----------------------------------------------------------------------+------------+-----------+--------------------+----------+--------+-----------------------+---------+---------+
```
## Expected behavior
LDAP users should be marked as externally managed users.

## Screenshots
Here's a short clip:
https://www.loom.com/share/50eea84fb03a488383967e2ee594739c

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-553220
Build Number: 553220864b3417aa33cd707b5f4d4977eb6a2cd3
Build Date/Time: 05-21-2019 14:42:08 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1623

**Comment by alhambrav** [comment]
Verified fixed.
