### ISSUE TITLE
[studio] Update the upgrade manager to include new time control

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3155]
Update the upgrade manager to include new time control

This is the new section: 

`<control>
   <name>time</name>
   <icon>
       <class>fa-clock-o</class>
   </icon>
</control>`

Please see: #2649

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1600

**Comment by sumerjabri** [comment]
Verified fixed.
