### ISSUE TITLE
[studio] Add missing JavaDoc

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3157]
JavaDoc is missing from API 2 interfaces:
- AuditService
- AuthenticationChain
- AuthenticationProvider
- BaseAuthenticationProvider
- UserPermissions
- InstanceService

**Comment by dejan-brkic** [comment]
`UserPermissions` not used in code - deleted

Done
PR:
https://github.com/craftercms/studio/pull/1659
