### ISSUE TITLE
[studio-ui] let user know they don't have access to any sites when sites dashboard is empty

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3166]
**Is your feature request related to a problem? Please describe.**
When a user does not have access to any sites the site's dashboard is empty for them.  They should be given a basic message that indicates that they do not yet have access to any sites.

**Describe the solution you'd like**
A simple message in the center screen where sites are normally listed is sufficient:
`You are not a member of any site. Please contact your administrator to request access.'

<img width="1417" alt="Screen Shot 2019-05-24 at 11 12 47 AM" src="https://user-images.githubusercontent.com/169432/58338022-0f713080-7e15-11e9-945d-e8999e012a4b.png">

**Comment by sumerjabri** [comment]
@vestrada please use the message in the text, not in the graphic.

**Comment by sumerjabri** [comment]
@vestrada please note this needs to go to 3.0 and 3.1

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1172

**Comment by vestrada** [comment]
3.0 -> PR: https://github.com/craftercms/studio-ui/pull/1173

**Comment by yacdaniel** [comment]
@sumerjabri When I setup LDAP and login with a user which doesn't have a group set in the LDAP attributes, the site screen is blank
![imagen](https://user-images.githubusercontent.com/6722074/61463295-5705cb80-a931-11e9-8ace-f53134c7d4af.png)

Should this message also go into users authenticated with LDAP?

**Comment by sumerjabri** [comment]
@yacdaniel Yes, it should.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1247

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1251

**Comment by yacdaniel** [comment]
@jvega190 in 3.1 looks good when LDAP user doesn't have a group attribute. This ticket is for 3.0 also, please send a fix there.

**Comment by jvega190** [comment]
@yacdaniel here's the PR for 3.0.x
https://github.com/craftercms/studio-ui/pull/1255

**Comment by yacdaniel** [comment]
Verified the message is displayed when a user is not a member of any site.
![image](https://user-images.githubusercontent.com/6722074/62559499-5d081180-b838-11e9-9564-5ae91dca5f38.png)
