### ISSUE TITLE
[studio] site created with sandbox_branch parameter uses master in authoring

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3167]
## Describe the bug
If a site is created using the parameter `sandbox_branch` the site will save content to the master branch instead of the `sandbox_branch` value.

## To Reproduce
1. Create a site  `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -d '{"site_id" : "my-site","description" : "My very first site!", "blueprint" : "org.craftercms.blueprint.empty", "sandbox_branch" : "testing"}' -X POST http://localhost:8080/studio/api/1/services/api/1/site/create.json` 
2. Edit a page and save it
3. Go to `crafter-authoring/data/repos/sites/my-site/sandbox`
4. `git branch -l` notice that you are on master, and `git log` shows that the edit of the page is there. The branch `testing` is present but is not used by authoring

## Expected behavior
When a site is created using the parameter `sandbox_branch` authoring should work on top of that instead of the default master branch.

## Screenshots
master with edit
![image](https://user-images.githubusercontent.com/6722074/58341166-d8961d00-7e0a-11e9-881f-7b58b7d4df11.png)
testing branch 
![image](https://user-images.githubusercontent.com/6722074/58341201-eea3dd80-7e0a-11e9-8282-86b389e665a7.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-35a73c
Build Number: 35a73c9c57acb78bc685cce83c9bafb187f1e52d
Build Date/Time: 05-24-2019 08:09:02 -0600

### OS
Linux

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1603

**Comment by yacdaniel** [comment]
Verified fixed.
