### ISSUE TITLE
[studio-ui] Create Site Dialog: sandbox branch should be an option in Additional Developer Options

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3168]
## Describe the bug
While creating a site from a BP, the sandbox branch can be only changed when the user checks  `Push the site to a remote Git repository after creation`. 

## To Reproduce
1. Choose a BP, set the site id and click `Additional Developer Options`
2. Try to set the sandbox branch of the site.

## Expected behavior
Sandbox branch should be an option under `Additional Developer Options`, using the `Push the site to a remote Git...` option shouldn't be required to set the branch.

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/58350728-fa4fce00-7e23-11e9-83f6-c254ada0be97.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-35a73c
Build Number: 35a73c9c57acb78bc685cce83c9bafb187f1e52d
Build Date/Time: 05-24-2019 08:09:02 -0600

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1170

**Comment by yacdaniel** [comment]
Verified.
