### ISSUE TITLE
[studio] Upgrade Spring Security to version 4.2.12 or later

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3169]
Upgrade org.springframework.security:spring-security-core to version 4.2.12 or later

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1604

**Comment by sumerjabri** [comment]
Please do the same for 3.0.x

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1605
