### ISSUE TITLE
[studio] Quick Create API

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3173]
@see #2947

Suggested response:

```js
{
  "items": [
    { 
      "label": "Press Article", 
      "contentTypeId": "/page/article", 
      "path": "",
      /* ...other needed props to open form */ 
    }
  ]
}
```

**Comment by sumerjabri** [comment]
@dejan-brkic please create spec in OAS and send API spec for review.
Please implement per our conversation:
- Test what's quick-creatable
- Test for permissions
- Return results

Think of a way to make this faster. Suggestion:
- Cache content types and whether or not they're quick creatable
- Invalidate the above cache on content type CUD

**Comment by dejan-brkic** [comment]
API spec
https://github.com/craftercms/studio/pull/1608

**Comment by sumerjabri** [comment]
@dejan-brkic Please make sure we're returning 404 for Site Not Found, and 200 and an empty list for no quick create items.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1618

**Comment by rart** [comment]
Verified.
