### ISSUE TITLE
[studio] get auditLog clarify behavior with siteId and siteName parameters

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3174]
## Describe the bug
The parameter for audit log `siteName` is working as expected and `siteId`is returning the json with empty results. The parameter `siteName` is the one being used in the `Audit` global menu

## To Reproduce
1. Create a site `testing` from any BP
2. Query with `siteName`  `GET "http://localhost:8080/studio/api/2/audit?siteName=testing"` will result in response data
3. Query with `siteId` `GET "http://localhost:8080/studio/api/2/audit.json?siteId=testing"` will result in a empty json data
```
{
  "response": {
    "code": 0,
    "message": "OK",
    "remedialAction": "",
    "documentationUrl": ""
  },
  "total": 0,
  "offset": 0,
  "limit": 0,
  "auditLog": []
}
```
4. Query with a non existing site name `GET "http://localhost:8080/studio/api/2/audit.json?siteName=nosite"` the response is
```
{
  "response": {
    "code": 0,
    "message": "OK",
    "remedialAction": "",
    "documentationUrl": ""
  },
  "total": 0,
  "offset": 0,
  "limit": 0,
  "auditLog": []
}
```
with a HTTP code response 200

5. Query with a non existing site id `GET "http://localhost:8080/studio/api/2/audit.json?siteId=nosite"` the response is:
```
{
  "response": {
    "code": 5000,
    "message": "Project not found",
    "remedialAction": "Check if you sent in the right Project Id",
    "documentationUrl": ""
  }
}
```
With a HTTP code response of 404

## Expected behavior
Maybe just use `siteName`? and make a response of  project not found when the `siteName` does not exist with http code 404? 

## Screenshots
Crafter Studio API v2 Swagger 
![image](https://user-images.githubusercontent.com/6722074/58648419-e0e8cf00-82c6-11e9-9867-9e1f2700a18e.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-116517
Build Number: 116517f4b2dea22980f6935a96f637c8028c834b
Build Date/Time: 05-29-2019 23:42:25 -0600

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
`siteId` parameter is ID from database (integer)

Done
PR:
https://github.com/craftercms/studio/pull/1656

**Comment by yacdaniel** [comment]
Verified fixed.
