### ISSUE TITLE
[studio] Enhance indexing on time-only control fields and update GraphQL to accommodate

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3175]
Enhance for indexing the new time only control fields and update GraphQL accordingly.

Related to: https://github.com/craftercms/craftercms/issues/2649

**Comment by jdrossl** [comment]
@sumerjabri is this for Elasticsearch only or for Solr too?

**Comment by sumerjabri** [comment]
@jdrossl let's do both please.

**Comment by yacdaniel** [comment]
Verified.
