### ISSUE TITLE
[studio] Dependency issue after site upgrade

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3178]
## Describe the bug
After creating a site from a `3.0.x` blueprint the log shows a lot of errors about dependencies, it seems to be one for each file in the repository.

## To Reproduce
1. Create a site from a remote repository
2. Watch the Tomcat log

## Expected behavior
There should be no errors

## Logs
```
[ERROR] 2019-05-30T14:01:54,440 [http-nio-8080-exec-13] [dependency.RegexDependencyResolver] | Failed to extract dependencies. Content was empty/null found for site: box2, path: /templates/web/entry.ftl 
```

### Version
3.1.1-SNAPSHOT

### OS
macOS

**Comment by dejan-brkic** [comment]
Cannot reproduce

```
Studio Version Number: 3.1.1-SNAPSHOT-5f58c6

Build Number: 5f58c6c92b357b23159ab00bdcf066af755869bf
```

**Comment by jdrossl** [comment]
@dejan-brkic Still happening with [this blueprint](https://github.com/craftersoftware/box-document-center-blueprint), maybe it was created with an older `3.0.x` version and we need to add something in the upgrade manager to handle it?

**Comment by dejan-brkic** [comment]
Still cannot reproduce it. Neither as create from remote nor create from blueprint (download and add to blueprints)

**Comment by jdrossl** [comment]
@dejan-brkic did you start Solr? I asked @yacdaniel to test it quickly and he can reproduce it too, let me know if you need more info or we can do a call

**Comment by dejan-brkic** [comment]
I was able to reproduce it. But this is not an issue. Errors are coming from replying git log. Create site from remote is pulling full git log and sync repo with DB is replaying git log.
By reviewing DB and logs, you can see that dependencies are extracted. Reported errors are for content that does not exist in the repo, meaning errors are valid and part of the process. If you download blueprint or fork repository and create a site from the fork, errors will not be reported.
