### ISSUE TITLE
[studio] Invalid UUID errors when site is being upgraded

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3179]
## Describe the bug
When importing a 3.0.x site into 3.1.x (with create site from remote), and the site is being upgraded, a bunch of `Invaid site UUID. Local copy will not be deleted ` appear in the log.

## To Reproduce
1. Import a big 3.0.x site into 3.1.x with create site from remote repository.
2. While the site is being upgraded, you should see `Invaid site UUID. Local copy will not be deleted ` messages in the log.

## Expected behavior
There shouldn't be messages if the site UUID hasn't been created yet.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1632

**Comment by avasquez614** [comment]
Verified
