### ISSUE TITLE
[studio-ui] UI locks the user out during form editing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3184]
## Describe the bug
A specific sequence of form edits causes the UI to lock the user out until a reload.

## To Reproduce
1. Create a site using Editorial
2. Edit an article
3. Change the article title
4. Press Escape
5. Select `No`
6. Scroll down to the image picker and click `replace` and select `Upload`
7. Hit `Escape`
8. Click anywhere on the screen (to switch focus)
9. The dialog is now locked up, and you can make it worse by pressing Escape again

## Expected behavior
The system should let the user close out the `Upload` dialog and revert the focus to the previous dialog.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![image](https://user-images.githubusercontent.com/3931908/58824518-3b0ccb80-860a-11e9-9cc4-3b31431241b4.png)

## Logs
N/A

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1233

**Comment by sumerjabri** [comment]
Verified.
