### ISSUE TITLE
[studio-ui] Missing results for unknown types on search result page

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3187]
## Describe the bug
When a site includes files like MS Office documents the search result page is unable to display them.

Found while working on https://github.com/craftercms/craftercms/issues/3152

## To Reproduce
1. Upload a MS Word in any site
2. Try to perform a search that includes the document
3. See error in the browser console (see screenshot)

## Expected behavior
All documents should be displayed even if there is no specific icon for the type

## Screenshots
<img width="581" alt="Screen Shot 2019-06-04 at 8 52 59 AM" src="https://user-images.githubusercontent.com/1236955/58889479-339b0000-86a6-11e9-808e-0ef376a3e0e5.png">

### Version
3.1.1-SNAPSHOT
### OS
macOS

### Browser
Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1188

**Comment by jdrossl** [comment]
Verified
