### ISSUE TITLE
[studio] Session times out and logs the user out even when the user is active

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3192]
## Describe the bug
User gets logged out while working on Studio.

## To Reproduce
1. Create a site using Editorial BP
2. Click around on the Sidebar under static-assets/images
3. Wait a bit, and click around again
4. Wait some more
5. You'll eventually get logged out

## Expected behavior
Active users shouldn't get logged out.

## Screenshots
![image](https://user-images.githubusercontent.com/3931908/58984793-de471780-87a7-11e9-9752-f17db8cfbaef.png)

## Logs
N/A

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1633

**Comment by sumerjabri** [comment]
Verified fixed.
