### ISSUE TITLE
[docs] remove content/add note about the --full flag in upgrades

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3194]
## Describe the bug
Since crafter 3.0.19 the flag for full upgrades `-f,--full` is deprecated.

## To Reproduce
1. Check https://docs.craftercms.org/en/3.0/system-administrators/upgrade/index.html and https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html
2. From a  authoring/delivery `3.0.20` build, execute the file `upgrade-target.sh --help` under `bin/upgrade`
```
authoring/crafter/bin/upgrade $ ./upgrade-target.sh --help
usage: upgrade-target [options] <target-installation-path>
 -f,--full   Deprecated option. Since 3.0.19, a full upgrade is always
             executed
 -h,--help   Show usage information
```

## Expected behavior
Documentation related to the full flag should be removed or a note added about the full flag is now deprecated.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/768
PR https://github.com/craftercms/docs/pull/767

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/769

**Comment by yacdaniel** [comment]
Verified.
