### ISSUE TITLE
[studio-ui] Form engine should validate and enforce use of _postfix on field names

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3198]
**This is should only be done when the search engine being used is Elasticsearch.**

Because of possible indexing conflicts between fields that have the same name but are of a different kind (for example, a `company` field that's an input in a content type, and a node-selector in another), the form engine must promote the use of type `_postfixes` that are pertinent for the controls, by 1) autocompleting the field name with a valid `_postfix` when the user is entering the field's `Title`, 2) when the content type is saved, checking each field for its `_postfix`, and if the field name is missing one or has an unexpected one, showing a warning with the invalid fields.

These are the expected/valid `_postfixes` for each control:

- **Repeating Group:** `_o` (for Object)
- **Input:** `_s`, `_t`, `_txt` and `_en`. Use `_s` on autocomplete.
- **Text Area:** `_s`, `_t`, `_txt` and `_en`. Use `_t` on autocomplete.
- **Rich Text Editor:** `_html`
- **Dropdown:** `_s`
- **Time:** `_dt`
- **Date/Time:** `_dt`
- **Checkbox:** `_b`
- **Grouped Checkboxes:**: `_o`
- **Item Selector:** `_o`
- **Image:** `_s`
- **Video:** `_s`
- **Label:** `_s`

On the `Name / Variable Name`  property input, add a small help popup that indicates the valid `_postfixes` for that particular control. The popup can be shown by hovering over the input or by clicking a question mark help icon.

The UI will not allow the form to be saved if the field names are not compliant.

This feature will be configurable per site. The configuration should be in `Site Configuration` configuration file, like this:
```
    <form-engine>
        <field-name-postfix>true</field-name-postfix>
    </form-engine>
```
This will follow `<published-repository>` configuration.

If the configuration item is missing, DON'T enforce/check postfixes.

**Comment by avasquez614** [comment]
@sumerjabri @vestrada I've been thinking that instead of validating the field names at content type save, maybe just validating when the user stops editing the field? That way it's not as disruptive and you wouldn't get the warning when making some changes to migrated content types from 3.0.x that were left on purpose without field `_postfixes` to avoid a lot of field renaming.

**Comment by sumerjabri** [comment]
@avasquez614 I think we have to be able to turn this on/off per site. Default is on. Migrated sites turn this off, and we warn during the migration of what's broken if anything.

We should also do the warning/prevent saving for broken schemas for `on` state.

**Comment by avasquez614** [comment]
@vestrada the form engine is not doing autocomplete for the field types, only for input.

**Comment by avasquez614** [comment]
Also please don't validate the postfix on Studio specific fields: `file-name`, `internal-name`, `placeInNav`, `disabled`. Right now for example, if I try to save the `Page - Home` content type in editorial, it doesn't let me because `disabled` doesn't have postfix.

**Comment by avasquez614** [comment]
The error message should also indicate what are the expected values for the postfix (e.g. if a Repeating Group is missing `_o` or has an invalid postfix like `_t`, then the message should indicate that `_o` is expected).

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1246

**Comment by avasquez614** [comment]
Verified
