### ISSUE TITLE
[studio] Studio broke after upgrade

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3203]
The last few PRs seems to have broken Studio, check with others, it seems that symptoms are different.

Logs: https://gist.github.com/sumerjabri/196deb5db3878fbaf57c7e3c658f3254

![image](https://user-images.githubusercontent.com/3931908/59135938-e3929680-894e-11e9-92eb-5549854aae46.png)

Visit Slack #craftercms for more information.

Forcing a specific site using URLs, Sidebar dies:
![image](https://user-images.githubusercontent.com/3931908/59136000-2b192280-894f-11e9-9867-24bee9ea2892.png)

Sidebar related errors?
![image](https://user-images.githubusercontent.com/3931908/59136085-8e0ab980-894f-11e9-97d6-b42c99f93bb9.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1616

**Comment by sumerjabri** [comment]
Verified fixed.
