### ISSUE TITLE
[studio] Remote Repos API2 actions aren't being logged in audit

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3204]
## Describe the bug
Remote Repositories API2 actions aren't being logged in audit.

## To Reproduce
1. Create a site from editorial BP
2. Add a remote repo `curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/repository/add_remote" -H  "accept: application/json" -H  "Content-Type: application/json" -d '{  "siteId": "editorial",  "remoteName": "origin",  "remoteUrl": "https://github.com/yacdaniel/barerepo4.git",  "authenticationType": "basic",  "remoteUsername": "yacdaniel",  "remotePassword": "topSectretPassword"}'`
3. From Studio push to remote, pull form remote and remove the remote repo.
4. Go to Studio, Audit Menu, filter by Operations(Add Remote, Remove Remote, Push to Remote, Pull from Remote)
5. Check that there is not audit log entries.

## Expected behavior
Remote Repositories API2 actions saved in the audit log.

## Screenshots
N/A

## LogsGo to Studio, Audit Menu, filter by Operations(Add Remote, Remove Remote, Push to Remote, Pull from Remote)
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-819642
Build Number: 819642dcc22cfb65f71b9a6df30b3dc084358a22
Build Date/Time: 06-10-2019 07:44:01 -0600

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1622

**Comment by yacdaniel** [comment]
Hi Dejan, when a remote is removed an `ADD_REMOTE` operation is added in audit https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/repository/RepositoryManagementServiceImpl.java#L120

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1625

**Comment by yacdaniel** [comment]
Verified fixed.
