### ISSUE TITLE
[studio-ui] Optimize condition and fix potential type coercion

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3207]
At common-api.js#L7806

`lockOwner && lockOwner != null` are redundant conditions.
avoid potential type coercion, use `!==`.

Looks like `if ((lockOwner || "").trim() !== "")` would suffice :)

For reference:
https://github.com/craftercms/studio-ui/pull/1184

**Comment by jvega190** [comment]
Draft PR https://github.com/craftercms/studio-ui/pull/1280

**Comment by rart** [comment]
👍🏻
