### ISSUE TITLE
[studio] Upgrade manager fails if it can't find the plugin descriptor

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3210]
## Describe the bug
When the upgrade manager runs and the site doesn't have a plugin descriptor, and error is thrown.

## To Reproduce
1. In Studio, import the site with no plugin descriptor.
2. Check the logs

A `org.craftercms.studio.api.v2.exception.UpgradeException: Plugin descriptor file not found for $SITE` should appear

## Expected behavior
The upgrade manager should not care if the site has no plugin descriptor, or a warning instead of an error should be logged, with a recommendation that a plugin descriptor should be added.

## Logs
https://gist.github.com/avasquez614/7d6ed9c179b449fd05725381c5b2921e

**Comment by sumerjabri** [comment]
@jdrossl I also want the default search engine for BPs without a plugin descriptor to be Solr, since that's most likely to work.

Perhaps we can create a descriptor and place it there with the default search engine. Other values can be constituted based on the site name or similar. Ping me to discuss different approaches.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 in order for the default descriptor to work we need to change the order of the operations during create site, as it is now the target in the deployer is created before the upgrade manager runs

**Comment by avasquez614** [comment]
Do you think there will be any issue changing the order of operations?

**Comment by jdrossl** [comment]
I think we just need to discuss about handling rollbacks if the target creation fails, right now it's the first step so we are able to fail very fast if there is an error in the deployer, if we move it then it will take more time to rollback all filesystem & db changes

**Comment by sumerjabri** [comment]
Agreed to default to a configured search engine in Deployer. Default is Solr for now (sites without the descriptor are likely to be Solr-based).

**Comment by avasquez614** [comment]
Verified
