### ISSUE TITLE
[studio] Created site not available on "Sites" screen after creating site and push to remote fails

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3213]
## Describe the bug
When using the `Create Site` button with the `Push the site to a remote Git repository after creation`, the created site not available on "Sites" screen after creating site and push to remote fails 

Fix typo in message (**Invaid**):
```
[INFO] 2019-06-14T08:21:40,705 [Studio_Publisher_Thread_Pool2] [job.PublisherTask] | Invaid site UUID. Local copy will not be deleted
```

## To Reproduce
1. Start Studio, then click on `Create Site`
2. Select the Website Editorial bp, give it a name
3. In the next screen, check ``Push the site to a remote Git repository after creation` and fill in the required details, making sure that the remote repo URL is incorrect.  In the short clip below, I pasted `git clone https://crafter-qa@bitbucket.org/crafter-qa/mysweetdotcom.git` direct from BitBucket without removing `git clone`
4. See the error on Studio.
<img width="564" alt="Screen Shot 2019-06-13 at 3 45 43 PM" src="https://user-images.githubusercontent.com/25483966/59509030-e07f3500-8e7d-11e9-9297-52f99b44d882.png">
5. See the error in the logs

## Expected behavior
If the created site failed to be pushed to the remote and the expected flow is for the created site not to be deleted, the created site should be available in the `Sites` screen so the user can go into the site, then just add the remote using the `Site Config` -> `Remote Repositories` menu and better messaging to the user on what happened, e.g. `The site was not pushed to remote.  Please add your remote using Site Config -> Remote Repositories` or some other message

Fix typo in message (**Invaid**):
```
[INFO] 2019-06-14T08:21:40,705 [Studio_Publisher_Thread_Pool2] [job.PublisherTask] | Invaid site UUID. Local copy will not be deleted
```

## Screenshots
Here's a short clip:
https://www.loom.com/share/316f707f2d974df487e454ef198641da

## Logs
https://gist.github.com/alhambrav/772b02a7ed36375d6f942421d808c0ae

### Version
Studio Version Number: 3.1.1-SNAPSHOT-324abf
Build Number: 324abfa845124228393efc282fa23b1e962c9e6c
Build Date/Time: 06-14-2019 06:57:15 -0400

### OS
OS X

### Browser
Chrome browser
## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1630

**Comment by alhambrav** [comment]
Verified site created is now available in `Sites` after failing to push to remote.
