### ISSUE TITLE
[studio] Please update the Upgrade Manager to add Quick Create

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3214]
**Is your feature request related to a problem? Please describe.**
Please update the upgrade manager for Quick Create.

Update configuration:
- Add to `contextual-nav.xml`:
```
<item><modulehook>quick-create</modulehook></item>

<module><moduleName>quick-create</moduleName><value>quick-create</value></module>
```

Example:
![image](https://user-images.githubusercontent.com/11640613/59526022-272c5980-8e95-11e9-817e-2a83dc21b409.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1631
https://github.com/craftercms/video-center-blueprint/pull/40

**Comment by vestrada** [comment]
verified
