### ISSUE TITLE
[videocenter] View all page for categories is not loading any content

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3216]
## Describe the bug
When you go to any category it shows content and a 'view all' link, if you to go that link it shows a page with no content.

## To Reproduce
- Create a site using VideoCenter blueprint
- Click on a category

## Expected behavior
The page should show all the matches for the category

## Screenshots
![Screenshot from 2019-06-14 14-58-39](https://user-images.githubusercontent.com/18267471/59537839-f5c38600-8eb4-11e9-9813-bb3728ab584a.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/42

**Comment by sumerjabri** [comment]
Verified.
