### ISSUE TITLE
[studio-ui] Clean jQuery UI scripts

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3218]
**Is your feature request related to a problem? Please describe.**
The jQuery UI script includes a bunch of bulk of unused components/code. We should have only core + the components that are used.

**Describe the solution you'd like**
Create a custom build with just the used components.

**Describe alternatives you've considered**
Remove jQuery UI all together.

**Comment by sumerjabri** [comment]
@rart 
- Would this be addressed by the new UI mechanics we're introducing now?
- What time horizon?

**Comment by rart** [comment]
They are separate concerns. 
This requires manual intervention on the studio side of things.

Effort wise, this is a couple of hours of work to:
1. Identify what jQuery UI components are actually in use
2. [Generate a custom build](https://jqueryui.com/download/)
3. Replace the bulky script import with the lighter analog

**Comment by rart** [comment]
Verified.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1222

**Comment by jvega190** [comment]
build link (using smoothness theme, same used before): https://jqueryui.com/download/#!version=1.12.1&components=111100000100101010000000010000000000000000000000&zThemeParams=5d00000100d905000000000000003d8888d844329a8dfe02723de3e5701fa198449035fc0613ff729a37dd818cf92b1f6938fefa90282d04ae436bb72367f5909357c629e832248af2c086db4ab730aa4cced933a88449eca61db9f7f3b23d47f58a712d809b6088edfb3e1ab0fd4487a569ff42031bb9aefd95aa0a010c29ca4db94f3366f7eb73778008bb690e9d38991c2ab5acb470930c835016bb59ce85223ee2eb2ca74db38bd686e4f0726028207a63e44a04f3ac741d7b0bc5eb3b945532e31642bd3df4c99455415fbf190a56a8384a7a1b06182dbe2759fa2eee7ddbbe32e4be6469419ec67ee260c2aa1654c7a39f0ac8c9b103a68f684dddbe918860409194e418045ff4aa83ac8dfdab69bea83b7cb70ce4c3ebae729c9625a6595e2129f9fb213105d2bddf7fde48ba6844e19d5c44cd55a084be9df2aac2a361d764dd099320cd80849bccd086428d2c262f4adee5e482c00ce779ddaa07097b0111bba4d8294c6b481caba5df02a6796634e7111a01634cc6289876eb90fbc361ec343fcd5c738db443ad6a10040f369eb4d58a61e666560b5f9dac9d9edc158ac7f15f9117fa324e687480e0fa48738c79a5d468cd91db5569f0d4afdc1ab3ffae7ebdc5ac0e6c54873d8b9c97bfffd3cf14ad
