### ISSUE TITLE
[studio] remote repo api 2 endpoints should return 404 when site not found

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3219]
## Describe the bug
Repository API 2 is returning HTTP code 500 when any of the endpoints is used with a `siteId` that doesn't exist in authoring. 

## To Reproduce
1. Create a site from any BP 
2. Do a API call to any of the following endpoints using a `siteId` that doesn't exist in authoring:
    - `/repository/add_remote`
    - `/repository/pull_from_remote`
    - `/repository/push_to_remote` 
    - `/repository/rebuild_database`
    - `/repository/remove_remote`
    - `/repository/list_remotes`
3. Notice that an error is logged in `logs/tomcat/catalina.out` and the HTTP response code is `500`

## Expected behavior
HTTP response code should be `404 Resource not found` when any of the previous endpoints is used with a `siteId` that doesn't exist in authoring.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-5ea8bc
Build Number: 5ea8bc233d875a4611edddfec4b31cb8abc2cba8
Build Date/Time: 06-17-2019 07:36:00 -0600

### OS
Any

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1638

**Comment by yacdaniel** [comment]
Verified fixed.
