### ISSUE TITLE
When context editing and saving not refreshing status icon

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#322]
Steps to reproduce:
1. Click the pencil icon to enable in-context editing 
2. Be sure you are in a "live status" page
3. Click the pencil in the right of a content
4. Edit
5. Save & Close 
6. The Crafter toolbar didn't refresh and the page status is "Live". 
7. Click refresh on the browser 
8. The page status is now "Edited".

**Comment by asotog** [comment]
Seems related also when `content-as-folder` is set to true

**Comment by russdanner** [comment]
Gus please test so I can assign to carlos to patch in to 2.5.2.1

**Comment by asotog** [comment]
Need to research more on our side, tested switching `content-as-folder` but still working properly

**Comment by gortizcrafter** [comment]
The bug steps are followed and the bug is not reproduce, the bug is closed as invalid.
