### ISSUE TITLE
[docs] Fix paths in Build a Form Engine Data Source doc

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3220]
The paths to data sources and controls that appear in https://docs.craftercms.org/en/3.1/developers/extending-studio/build-a-data-source.html and https://docs.craftercms.org/en/3.0/developers/extending-studio/build-a-data-source.html are wrong. Instead of starting with `STUDIO-WAR/components/cstudio-forms`, they should start with `/STUDIO-WAR/default-site/static-assets/components/cstudio-forms`.

**Comment by alhambrav** [comment]
For 3.0: PR https://github.com/craftercms/docs/pull/773
For 3.1: PR commit https://github.com/craftercms/docs/pull/772/commits/f707a60721408543c3c4378381abb7a8ae6086b9

**Comment by avasquez614** [comment]
Verified
