### ISSUE TITLE
[studio-ui] Using repeating group control actions resets the unsaved time control data

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3222]
## Describe the bug
When Repeating Group actions(Add Another, Move Up, Move Down, Delete) are used while editing content, the time only control data that was added/modify it during the edit(unsaved) is restored to his default

## To Reproduce
1. Create a site from editorial BP
2. Edit the `Page - Article` `ContentTypes`, Add a `Time` control inside a `Repeating Group`
2. Go to any article and click edit
3. Add a `First Item` to the `Repeating Group` set a value and then `Add Another` item
4. Add more items and play with the others `Repeating Group` actions.
5. Notice any time you click the `Repeating Group` actions the data saved in the `Time` control is reseted to his default, ignoring  any changes you did.

## Expected behavior
Changes during the edit should't be reverted when the `Repeating Group` actions are used.

## Screenshots
https://www.loom.com/share/2eccb4a521ac4105bf7100a6add03bb3

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-5ea8bc
Build Number: 5ea8bc233d875a4611edddfec4b31cb8abc2cba8
Build Date/Time: 06-17-2019 07:36:00 -0600

### OS
Mac

### Browser
Chrome/Firefox

## Additional context
Time data that is already saved doesn't get modify it when `Repeating Group` actions are used.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1207

**Comment by yacdaniel** [comment]
@vestrada looks like the last value I change(hours, minutes, sec) is restored to the previous value it has when a repeating groups action is used, please take a look at https://www.loom.com/share/ab3aaa763a6342d1850e57f24d1d8f7a

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1216

**Comment by yacdaniel** [comment]
Verified fixed.
