### ISSUE TITLE
[studio] Create Folder details are not expanded in Git Log

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3224]
## Describe the bug
Create Folder details are not expanded in Git Log

Example: 
See {site}/{path} should be replaced with details
```
commit cafd2b8abea6e76611b1cbbcc3d973b1c9da36f6 (HEAD -> feature/modeling)
Author: admin admin <evaladmin@example.com>
Date:   Mon Jun 10 12:18:07 2019 -0400

    Created folder site: {site} path: {path}
```

## To Reproduce
1. Create a folder via Studio
2. Look at git log of sandbox repository

## Expected behavior
Site and Path details should replace placeholders

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-404e40
Build Number: 404e4049302946700dc55bfdb016251b68bc389b
Build Date/Time: 06-12-2019 19:50:55 -0400

### OS
Any

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1637

**Comment by russdanner** [comment]
Confirmed
