### ISSUE TITLE
Refactor content type Groovy controller

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3225]
**Is your feature request related to a problem? Please describe.**
Today Content Type Groovy controllers have a good understanding of action taken but do not make it easy to act on the content being written.   

**Describe the solution you'd like**

* Make controller coding more simple.  Today there is a lot of boilerplate code in controllers (See example below.) Remove the need to include the code below:
```
import scripts.libs.CommonLifecycleApi;

def contentLifecycleParams =[:];
contentLifecycleParams.site = site;
contentLifecycleParams.path = path;
contentLifecycleParams.user = user;
contentLifecycleParams.contentType = contentType;
contentLifecycleParams.contentLifecycleOperation = contentLifecycleOperation;
contentLifecycleParams.contentLoader = contentLoader;
contentLifecycleParams.applicationContext = applicationContext;

def controller = new CommonLifecycleApi(contentLifecycleParams);
controller.execute();
```
* Allow controller to modify in-flight content to be modified. It looks like there is an object that would allow this but it is not passed to the groovy script. See lines 43-62
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/content/pipeline/ContentLifeCycleProcessor.java

**Comment by sumerjabri** [comment]
Approach, to immediately help with this:
- Don't commit to Git until this controller is done executing
- Allow this thread/controller to update this XML (system processing state shouldn't lock this thread out)
- Simplify the boilerplate work and reduce it, consider a whole new Processor-based API/IF and deprecate the old stuff for future removal

Ping me for more information.

**Comment by sumerjabri** [comment]
- [ ] Design the events
- [ ] Design the new API and simplify it to reduce boiler-plate code
- [ ] Make it so it's not dual-committing the item (write to disk, run the LifeCycle hook, then commit)

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6061
