### ISSUE TITLE
[studio] validate-session returns internal error

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3227]
## Describe the bug
validate-session returns internal error

## To Reproduce
1. `GET "http://localhost:8080/studio/api/1/services/api/1/security/validate-session.json"`
2. See error
```
{
  "message": "Internal server error: \njava.lang.NullPointerException"
}
```

## Expected behavior
No error.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
3.1.1-SNAPSHOT

### OS
Any

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1636

**Comment by yacdaniel** [comment]
Verified fixed.
