### ISSUE TITLE
[studio-ui] Date/Time control is not populated with populate expression when creating a new article page in website editorial

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3228]
## Describe the bug
Date/Time control is not populated with populate expression when creating a new article page in website editorial (Property `Populated` is checked and `Populate Expression` value is `now` for the date/time control in the content type)

## To Reproduce
1. Create a site using website editorial
2. Navigate to the folder `/articles/2017/3`
3. Right click on the folder and click on `New Content`
4. Select `Page - Article`
5. Scroll down to `Content` and notice that the `Date` field is not filled in
![Screen Shot 2019-06-18 at 2 32 39 PM](https://user-images.githubusercontent.com/25483966/59713130-ad6dd600-91dc-11e9-8e2a-2c2d25cbae60.png)

6. From the `Sidebar` click on `Site Config`
7. Click on `Content Type` then click on `Open Existing Type`
8. Select `Page - Article`
9. Scroll to the `Content` section
10. Click on `Date` and look at the properties `Populated` and `Populate Expression`
![Screen Shot 2019-06-18 at 2 34 37 PM](https://user-images.githubusercontent.com/25483966/59713331-2c630e80-91dd-11e9-91b3-49336197be50.png)

 

## Expected behavior
The date field should be filled in with the value in the `Populate Expression` when `Populated` is checked in the properties of the date/time control in the content type

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-d0beb2
Build Number: d0beb256b5ad5d98b7fda7af8e85c8fc2cbb7439
Build Date/Time: 06-18-2019 11:27:43 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1209

**Comment by yacdaniel** [comment]
Verified fixed.
