### ISSUE TITLE
[studio] Unable to notify content submission

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3229]
## Describe the bug
Unable to get notification message from notification configuration 

## To Reproduce
1. Create a site from Editorial BP
2. Edit a page and click `Approve and Publish`
3. See error in `/logs/tomcat/catalina.out`

Error can also be reproduced if you set up an author-reviewer and send content to approve and then with reviewer approve-reject the content

## Expected behavior
No errors when notifying content. Emails are sent successfully.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/yacdaniel/738c91cc15c52175fc784389631e6906

### Version

Studio Version Number: 3.1.1-SNAPSHOT-8d7cdb
Build Number: 8d7cdbdb8d74996704816f532fb9944d052d8041
Build Date/Time: 06-19-2019 07:55:58 -0600

### OS
Linux/Mac

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1639

**Comment by yacdaniel** [comment]
@dejan-brkic Please try the following tests.  Users are in their respective groups.
- Author sends content to be approved. In the logs I see:
  - `[ERROR] 2019-07-01T12:56:04,283 [http-nio-8080-exec-9] [notification.NotificationServiceImpl] | Unable to notify content submission`  
-  Content sent by author is approved by an user from groups: reviewer, publisher, developer, in logs:
   - `[ERROR] 2019-07-01T12:53:25,608 [http-nio-8080-exec-7] [notification.NotificationServiceImpl] | Unable to Notify Content Approval` 
-  Content sent by author is approved by an user from groups: system admin, site admin, developer. no errors in logs and email not recieived.  Is this expected?

The author gets rejected emails succesfully. 

Thanks

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1653

**Comment by yacdaniel** [comment]
Verified fixed.
