### ISSUE TITLE
[studio] Quick create button is not available for author user

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3230]
## Describe the bug
Quick create button is not available for author user

## To Reproduce
1. Create a site in Studio.  Notice that for user `admin` the quick create button is available
![Screen Shot 2019-06-19 at 1 19 56 PM](https://user-images.githubusercontent.com/25483966/59786670-c5edf700-9295-11e9-9b00-08c77355c736.png)

2. Create an `author` user (Create a user and add the user to `site_author` group)
![Screen Shot 2019-06-19 at 1 26 20 PM](https://user-images.githubusercontent.com/25483966/59786748-f5046880-9295-11e9-959e-c38d042483f4.png)

3. Login to Studio using the `author` user, notice that the quick create button is not available for the `author` user
![Screen Shot 2019-06-19 at 1 28 24 PM](https://user-images.githubusercontent.com/25483966/59786923-54fb0f00-9296-11e9-9a3a-4383a6828115.png)

## Expected behavior
The quick create button should be available to all users that are able to create content.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-8d7cdb
Build Number: 8d7cdbdb8d74996704816f532fb9944d052d8041
Build Date/Time: 06-19-2019 10:07:31 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
When you do an inspect in the browser for the `author` user, there is an error in the response for `Request URL: http://localhost:8080/studio/api/2/content/list_quick_create_content.json?siteId=mysite&nocache=Wed%20Jun%2019%202019%2013:30:51%20GMT-0400%20(Eastern%20Daylight%20Time)`

```
{"response":{"code":2001,"message":"Unauthorized","remedialAction":"You don't have permission to perform this task, please contact your administrator","documentationUrl":""}}
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1640

**Comment by alhambrav** [comment]
Verified fixed.
