### ISSUE TITLE
[studio] Please update the Upgrade Manager to add Video Transcoding datasource

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3231]
**Is your feature request related to a problem? Please describe.**
Please update the Upgrade Manager to add Video Transcoding control

Update configuration
`/site-config.xml`

`
<datasource>
    <name>video-S3-transcoding</name>
    <icon>
        <class>fa-film</class>
        <stackedclass>fa-amazon</stackedclass>
    </icon>
</datasource>
`

Example:
![Screenshot from 2019-06-19 15-58-08](https://user-images.githubusercontent.com/18267471/59804282-1cb1fb80-92ab-11e9-9300-4ff01dff8541.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1648
https://github.com/craftercms/video-center-blueprint/pull/44

**Comment by jvega190** [comment]
@dejan-brkic it works, but there's one detail:

```
<datasource>
    <name>video-S3-transcoding</name>
    <icon>
       <class>fa-film</class>
       <class>fa-amazon</class>            <--- this should be <stackedclass>...
    </icon>
</datasource>
```

This is causing the icon not to show

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1655

**Comment by jvega190** [comment]
Verified fixed
