### ISSUE TITLE
[commons] Update configuration files for AWS, Box & Webdav

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3232]
Profiles should be organized into separate sections for each service, for example:
```xml
<aws>
  <s3>
    <profile>
      ...
    </profile>
  </s3>
  <mediaConvert>
    <profile>
       ...
    </profile>
  </mediaConvert>
</aws>
```

**Comment by jdrossl** [comment]
@jvega190 please do an upgrade (there are changes in engine, studio & deployer) and confirm that the service works the same

**Comment by jvega190** [comment]
@jdrossl tested in s3 and it worked, but not working on webdav

**Comment by jdrossl** [comment]
the issue was caused by a typo, all services are verified to be working as expected
