### ISSUE TITLE
[studio] Upgrade the embedded MariaDB to the latest

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3233]
Please upgrade our MariaDB4j fork to use the latest MariaDB version.

**Comment by sumerjabri** [comment]
@dejan-brkic please upgrade the MariaDB4J package and Crafter Studio to the latest MariaDB

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1671

**Comment by sumerjabri** [comment]
Verified.
