### ISSUE TITLE
[studio] Aurora serverless DB causes an error in the logs, but works otherwise

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3234]
Studio should be able to use Aurora 5.6 serverless as its DB.

**Comment by avasquez614** [comment]
@dejan-brkic please ping me so I can give you the Aurora endpoint for testing when you start working on this ticket.

**Comment by dejan-brkic** [comment]
Studio throws exceptions on the first run but creates the database and starts normally.

**Comment by dejan-brkic** [comment]
This should be resolved as we upgraded embedded DB

**Comment by avasquez614** [comment]
Yes, verified a while ago.
