### ISSUE TITLE
[studio] History doesn't work in Site Config - Configuration

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3235]
## Describe the bug
History in Site Config - Configuration is not working, the endpoint `http://localhost:8080/studio/api/1/services/api/1/content/get-item-versions.json?site=confighistory&path=site-config.xml` is returning an empty array of versions. 

## To Reproduce
1. Create a site from any BP
2. Go to `Site Config` -> `Configuration`
3. Edit and Save any configuration, then click `History`
4. Nothing is shown in History dialog.

## Expected behavior
History shows versions of the configuration. 

## Screenshots
![history configuration](https://user-images.githubusercontent.com/6722074/59942441-e5635c00-941c-11e9-9211-2f13f2fdc4ca.gif)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-dfb9aa
Build Number: dfb9aad670a85367696829a41308f09034ff901a
Build Date/Time: 06-21-2019 07:07:53 -0600

### OS
Linux/Mac

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
UI:
https://github.com/craftercms/studio-ui/pull/1275

BE:
https://github.com/craftercms/studio/pull/1722

**Comment by yacdaniel** [comment]
@dejan-brkic  Im getting this error while selecting 2 items then clicking the `Compare` button.
![image](https://user-images.githubusercontent.com/6722074/64207963-00117280-ce5b-11e9-866a-14d9eee8545b.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1300

**Comment by yacdaniel** [comment]
Verified fixed.
