### ISSUE TITLE
[studio] Please update the Upgrade Manager to add No Template Required field

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3236]
**Is your feature request related to a problem? Please describe.**
Please update the upgrade manager to include the `no-template-required` property into the `site-config-tools.xml` file.

Update configuration:

Add to `site-config-tools.xml`, under `<objectTypes>`, in both Page And Component:
```
<property>
     <name>no-template-required</name>
     <label>No Template Required</label>
     <value></value>
     <type>boolean</type>
 </property>
```

Example:
![Screenshot from 2019-06-21 12-43-13](https://user-images.githubusercontent.com/18267471/59944518-2f9b0c00-9422-11e9-934d-0aad4cce36ee.png)

Ping me if you have any questions.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1648
https://github.com/craftercms/video-center-blueprint/pull/44

**Comment by jvega190** [comment]
confirmed
