### ISSUE TITLE
[engine] Improve GraphQL schema

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3241]
Improve the `node-selector` schema mapping to support queries for mixed types.

**Comment by jdrossl** [comment]
@rart please validate you can get all components in a single query now

**Comment by rart** [comment]
Good. Able to get all the component information in a single query!

Future work: Nav retrieval is limited. Can only get first level and the URL doesn't get sent due to current system limitations. Schema is quite verbose due to XML origin.
