### ISSUE TITLE
[studio] Change password with requirements in account managment throws an error

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3247]
## Describe the bug
Changing the password from the Account Managment when the feature password requirements are enabled results in an error.

## To Reproduce

1. Enable the property `studio.security.passwordRequirements.enabled: true` and set the regex validations in `studio-config-override.yaml`
2. Create an user
3. Log in with the user previously created.
4. Click the username in the top right corner, then click settings.
5. Change the password using a new password that does not fulfill the requirements.

## Expected behavior
The endpoint `change-password.json` should not return http code 500, should be 400.  Response message should has the content `CODE: 6003, MESSAGE: User password does not fulfill requirements, REMEDIAL ACTION: Use password that will fulfill password requirements`

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/60189583-612f2100-97ee-11e9-9c9f-f8b81fb1af44.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-ddad26
Build Number: ddad264308e75977036df73f6b8a04c6111d73dd
Build Date/Time: 06-26-2019 08:16:32 -0600

### OS
Linux/Mac

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1220
https://github.com/craftercms/studio/pull/1651

**Comment by yacdaniel** [comment]
@sumerjabri BE for this one is fixed, UI needs to handle the error message, same as we do when the user that is being created does not fulfill password requirements

For reference. Create User with the error about the password.
![password](https://user-images.githubusercontent.com/6722074/60602374-e4152600-9d70-11e9-9266-2a6f0f859dc8.png)

**Comment by yacdaniel** [comment]
Verified fixed.
