### ISSUE TITLE
[studio-ui] Site name restrictions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3248]
The site name is currently restricted to be lower-case alphanumeric and '_'. It needs to be further restricted to exclude:
```
00 or more 0s (two or more zeros as a name, example: 000000)
_* (starts with an _)
```

These restrictions are necessary due to limitations of Elasticsearch (not all of which are documented in Elasticsearch)

**Comment by yacdaniel** [comment]
Site name starting with one zero `0` and following with other numbers are also breaking studio, like: `01`, `012`.

**Comment by yacdaniel** [comment]
Verified fixed.
