### ISSUE TITLE
[studio] Auto-build site's project source files

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3249]
There is an array of possible build processes that developers may use to develop their apps. They may write source code that requires a build or transpiling process before end-user/browser consumption. Examples of these are:
- Single page applications such as projects that use create-react-app, angular CLI, or similar web pack builds
- CSS supersets such as sass, less, postcss
- ES6 transpiling
- Typescript

Most commonly, these are enabled by some form of node-power build scripts however it may also be something else (e.g. ruby for SASS, or ecmascripten for WASM projects).

Pushing/committing build outputs can be troublesome and inconvenient for developers.

**Solution**
Allow the configuration of *intelligent* build systems that would execute build processes and drop the output in the right location for end-user consumption (e.g. `static-assets/*`); developers would only commit the source and the system would perform the relevant build.

**Additional Considerations**
- For cache busting purposes, build systems may change the file names every time the build detects a change. In git, this translates to a bunch of deletions and additions. Is this ok? How does this impact repo size growth, history browsing UX, etc? Should these be "silent" commits if that's even possible?
- Most common web development compilation/transpilation/etc is powered by node and some of the no-node powered ones (like sass) have a node analog (e.g. node-sass). Node could be a good starting point for version 1 but we should consider supporting other techs.
- Consider some form of file watching system so the system knows when to trigger a build.
- [Tangential] Consider the `preview-server-url`. If that property is committed to point to a local node dev server (for example), it currently brakes preview for non-developers (e.g. authors, reviewers, admins) that are not running the node server.
- A project may have multiple decoupled build processes.

**Comment by sumerjabri** [comment]
After much research, we decided that this is of little value to developers since they have their own local IDEs/build tools that handle this, and it's too expensive (and possibly risky) to introduce to actual live servers.

We will put this on ice and revisit in the future if a case can be made for this.
