### ISSUE TITLE
[studio][studio-ui] Set a new password without requirements using forgot password is returning an error 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3250]
## Describe the bug
When the password is set using the `Forgot Password` feature and the user types a password that doesn't meet the requirements, studio is returning and error and also no UI message is displayed about it.

## To Reproduce
1. Enable the `property studio.security.passwordRequirements.enabled: true` and set the regex validations in studio-config-override.yaml`
2. Create an user
3. Log out from current user
4. In the log in screen click `Forgot Password` and fill the data with the username created in step 2.
5. Open the forgot password link you recieved
6. Set a new password which does not fulfill the requirements.
7. Notice nothing happens.

## Expected behavior
- The endpoint `set-password.json` should not return http code 500, should be 400. Response message should has the content CODE: 6003, MESSAGE: User password does not fulfill requirements, REMEDIAL ACTION: Use password that will fulfill password requirements.

- Studio UI should show an error message with the content from the API response(Message and Remedial Action).

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/60197767-4fa14580-97fd-11e9-9ee4-f557e085a3b6.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-ddad26
Build Number: ddad264308e75977036df73f6b8a04c6111d73dd
Build Date/Time: 06-26-2019 08:16:32 -0600

### OS
Linux/Mac

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1220
https://github.com/craftercms/studio/pull/1651

**Comment by yacdaniel** [comment]
@sumerjabri BE for this one is fixed, UI needs to handle the error message, same as we do when the user that is being created does not fulfill password requirements 

For reference. Create User whith error about password.
![image](https://user-images.githubusercontent.com/6722074/60600497-787d8980-9d6d-11e9-9b3e-f86250200cba.png)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1225

**Comment by yacdaniel** [comment]
Verified fixed.
