### ISSUE TITLE
[studio] Upgrade jquery to latest

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3251]
Upgrade JQuery to the latest version and test.

**Comment by vestrada** [comment]
3.1 -> https://github.com/craftercms/studio-ui/pull/1217

**Comment by vestrada** [comment]
3.0 -> https://github.com/craftercms/studio-ui/pull/1218

**Comment by yacdaniel** [comment]
Verified in 3.0 and 3.1
