### ISSUE TITLE
[craftercms] Add custom error pages for all products

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3252]
Please use a custom error page for Tomcat, regardless of what module runs within.

**Comment by sumerjabri** [comment]
@russdanner please validate (it passed my quick tests on 3.1)

**Comment by russdanner** [comment]
@jdrossl Please add this to 3.0.x

**Comment by jdrossl** [comment]
@russdanner the PR's have already been backported to `support/3.0.x`

**Comment by russdanner** [comment]
Example test url
```
http://localhost:8080/studio/diff?site=child&path=/site/website/index.xml&version=BLOWUP32f6adee8c1c4de5ce6558e1dafca848826607b2&versionTO=32f6adee8c1c4de5ce6558e1dafca848826607b2&mode=iframe
```
CONFIRMED
