### ISSUE TITLE
[studio-ui] Remove XSRF cookie property from authoring context 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3253]
The file `studio-ui/templates/web/common/page-fragments/studio-context.ftl` is printing the value of the XSRF-TOKEN: `xsrfToken: "${_csrf.token}"`. This token is already provided in the cookie and shouldn't be returned by the Freemarker template. Please remove it and use the cookie value.

**Comment by rart** [comment]
`entry.flt:70` is also printing the token. Please remove and adjust there as well.

Create new function `getRequestForgeryToken` under `CrafterCMSNext.util.storage` and call it everywhere where the authoring context var is currently read.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1213

**Comment by jvega190** [comment]
3.0.x: https://github.com/craftercms/studio-ui/pull/1215

**Comment by avasquez614** [comment]
Verified
