### ISSUE TITLE
[studio][studio-ui] Change user password using Edit User form when pwd requirements aren't fulfilled results in an error.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3254]
## Describe the bug
When the password is changed using the Edit User form and the user types a password that doesn't meet the requirements, studio is returning and error and also no UI message is displayed about it. The process looks like was succesfull but it isn't.

## To Reproduce
1. Enable the property `studio.security.passwordRequirements.enabled: true` and set the regex validations in `studio-config-override.yaml`
2. Create a user
3. Edit the created user and set a new password which does not fulfill the requirements.

## Expected behavior
- The endpoint `reset-password.json` should return 400 and the correct error message.
- The Edit User form should shown an error about the password does not fulfill requirements before saving any data.

## Screenshots
I changed the password to 123, the edit of the user was ok, but I couldn't login because the password wasn't changed.
https://www.loom.com/share/3619ccea83d24ce1a23bd0a411769b60

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-89a60e
Build Number: 89a60ec1c18b42d733fa569791c0099623309083
Build Date/Time: 06-26-2019 13:23:15 -0600

### OS
Linux/Mac

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1220
https://github.com/craftercms/studio/pull/1651

**Comment by yacdaniel** [comment]
@dejan-brkic this one is returning a `{}` when response is 200
```
curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/users/test01/reset_password" -H  "accept: application/json" -H  "Content-Type: application/json" -d '{"username":"test01","new":"1234asDF$"}'  
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:8080...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /studio/api/2/users/test01/reset_password HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.65.1
> Cookie: XSRF-TOKEN=A_VALUE;JSESSIONID=76E2057A1E74036D76BB5A43B627A73C
> X-XSRF-TOKEN:A_VALUE
> accept: application/json
> Content-Type: application/json
> Content-Length: 39
> 
* upload completely sent off: 39 out of 39 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 03 Jul 2019 14:26:02 GMT
< 
* Connection #0 to host localhost left intact
{} 
```

**Comment by yacdaniel** [comment]
@rart In the UI the Edit User form should show an error about the password that does not fulfill requirements before saving any data. Please asign the ticket.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1230

**Comment by yacdaniel** [comment]
@jvega190 please try to see if we can address the issue we discuss in this ticket. Also, we can close this as fixed and open a new one.  Let me know what works for you. Thanks :+1:

**Comment by jvega190** [comment]
@yacdaniel from discussion with Roy views will be separated into edit user and reset password.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1239

**Comment by yacdaniel** [comment]
Verified fixed.
