### ISSUE TITLE
[studio] Fix broken Groovy script calling old API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3255]
## Describe the bug
A Groovy script is calling an old API and results in broken functionality.

## To Reproduce
1. Create a site
2. Tail the logs
3. Wait

## Expected behavior
No errors should occur.

## Screenshots
N/A

## Logs
https://gist.github.com/sumerjabri/a5d3cddf146d3471edee3b81ca618ce5

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu 18.04

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1654

**Comment by sumerjabri** [comment]
Verified.
