### ISSUE TITLE
[engine] Integrate url transformation in GraphQL

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3257]
Allow GraphQL queries to call the UrlTransformationService. Example:

```
{
  pages {
    items {
      renderUrl: localId(transform: "storeUrlToRenderUrl")
    }
  }
}
```

Reference
https://www.graphql-java.com/documentation/v11/sdl-directives/#another-example-date-formatting

**Comment by jdrossl** [comment]
@rart please validate that you can get the render urls from graphql now

**Comment by rart** [comment]
Verified 🥳
