### ISSUE TITLE
[videocenter] Clicking on `View All` should show all videos in a channel

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3258]
Per our conversation, please make it such that View All shows all the videos in a channel, not just the featured videos. Please sort by create date.

Please also add videos to Quick Create, so the user can add videos quickly.

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/45

**Comment by sumerjabri** [comment]
Verified.
