### ISSUE TITLE
[studio-ui] missing sidebar menu items

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3263]
## Describe the bug
En some occasions, the sidebar menu items don't load when going to preview page

## To Reproduce
1. Create a site from any BP
2. In preview, click in the Sidebar
3. Notice that some sidebar menu items are missing.

## Expected behavior
Sidebar menu items load completely.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![imagen](https://user-images.githubusercontent.com/6722074/60525753-350f1680-9cac-11e9-8715-63222214a632.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-494bd5
Build Number: 494bd50ddf39535acaf484abd22cd7a9387580d1
Build Date/Time: 07-02-2019 07:18:13 -0600

### OS
Any

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1224

**Comment by yacdaniel** [comment]
Still see this in randomly, can't find a reliable path to reproduce it. Will keep trying.

**Comment by sumerjabri** [comment]
@yacdaniel see what you can do to reproduce this.

**Comment by yacdaniel** [comment]
Verified fixed.
