### ISSUE TITLE
[studio-ui] Date-time-picker inside the targeting dialog.

### ISSUE THREAD

**Issue by gerald-exa** [craftercms/craftercms#3268]
**Is your feature request related to a problem? Please describe.**
When adding a property to the targeting dialog it's not possible to provide a date-time-picker.

**Describe the solution you'd like**
I'd like to add a date-time-picker to the targeting dialog.

**Describe alternatives you've considered**
I already discussed this issue in the Crafter Slack Channel with sumer. So I haven't thought about alternatives.

**Additional context**
Background: We would like to have a preview for scheduled assets at a certain moment in time. This means the editor should be able to set a date/time and in previewMode the template should render assets or not depending on the assets scheduled date.
The preview date should be valid for the whole page, not only for a single asset.
Currently it's only possible to write a date/time into a simple text field, but that's not good UX.

**Comment by gerald-exa** [comment]
<img width="811" alt="Screenshot 2019-07-02 at 08 53 46" src="https://user-images.githubusercontent.com/1712663/60864270-685d2280-a223-11e9-9a01-a226c7de1462.png">

This is the current status. The editor has to type a date manually. It would be much better UX to set a date and the time by using a date-time-picker.

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1262
studio: https://github.com/craftercms/studio/pull/1707

**Comment by sumerjabri** [comment]
@russdanner please validate

**Comment by russdanner** [comment]
User should be able to set timezone

**Comment by russdanner** [comment]
User should also be able to clear the time

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1369

**Comment by russdanner** [comment]
Confirmed
