### ISSUE TITLE
[studio-ui] Missing push URL value in Remote Repositories.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3269]
## Describe the bug
Missing `Push URL` value in Remote Repositories.

## To Reproduce
1. Create a site from any BP
2. Go to `Site Config` - `Remote Repositories`
3. Add a Repository

## Expected behavior
`Push URL` has the correct value.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![image](https://user-images.githubusercontent.com/6722074/60895502-0819b100-a222-11e9-8ad9-03e23cdc68d1.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-0a46f9
Build Number: 0a46f955d09fbcdf646eda13c478a0f1feb745db
Build Date/Time: 07-08-2019 16:56:54 -0600

### OS
Linux

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1234

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/61156771-7f18a900-a4b1-11e9-9da1-fb19000a711e.png)
