### ISSUE TITLE
[engine] Please create service which tells if it's "preview" or "live"

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3270]
There's a bean that sets a free marker variable called `modePreview` (boolean). This variable should say if the site is being rendered in preview (authoring) or live (delivery). 

Please create a service which may be invoked via AJAX that would return this value.

The purpose is primarily In Context Editing support for SPAs.

**Comment by rart** [comment]
@jdrossl please comment around API usage, params, etc.

**Comment by jdrossl** [comment]
@rart sorry I forgot to send the docs

**Comment by rart** [comment]
Verified.
