### ISSUE TITLE
[studio] Default site blueprints should enforce postfixes by default and have all content type fields with postfixes  

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3271]
Change all our current blueprints to have the `Site Configuration` property set to true:

```
    <form-engine>
        <field-name-postfix>true</field-name-postfix>
    </form-engine>
```

All content type fields of the blueprints should also have postfixes.

For more info refer to https://github.com/craftercms/craftercms/issues/3198

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/video-center-blueprint/pull/47

**Comment by avasquez614** [comment]
@vestrada `video-center-blueprint` doesn't have the 

```
    <form-engine>
        <field-name-postfix>true</field-name-postfix>
    </form-engine>
```

in the develop branch

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/video-center-blueprint/pull/52

**Comment by sumerjabri** [comment]
@avasquez614 ready for testing

**Comment by avasquez614** [comment]
Verified
