### ISSUE TITLE
[docs] Fix LDAP doc

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3272]
The studio config for LDAP auth in https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/setting-up-an-ldap-server-for-dev.html is invalid. It references the old way of configuring authentication, it should be changed to the new way (authentication chain).

**Comment by yacdaniel** [comment]
PR https://github.com/craftercms/docs/pull/782

**Comment by avasquez614** [comment]
Verified
