### ISSUE TITLE
[studio-ui] Targeting fails with empty values

### ISSUE THREAD

**Issue by gerald-exa** [craftercms/craftercms#3278]
## Describe the bug
When using input fields in the targeting dialog and the input fields are cleared it's not possible to save - the apply button does not work.

## To Reproduce
1. Click the targeting icon in the upper right corner of the CMS.
2. In the targeting dialog clear all values (especially input fields).
3. Click the apply button.
4. Current behavior: Nothing happens. Values are not saved and the dialog is not closed.

## Expected behavior
Even if I clear all form fields inside the targeting dialog I should be able to hit the apply button to save the current state.

## Screenshots
<img width="800" alt="Screenshot 2019-07-11 at 08 11 26" src="https://user-images.githubusercontent.com/1712663/61026447-a7ba7900-a3b3-11e9-9155-a8cdcccf76df.png">

## Logs
Browser Console: I get a 404 for the serviceUri which is something like: ...api/1/profile/set&Thu%20Jul%2011%202019%2007:53:47%20GMT... 

### Version
Studio Version Number: 3.1.0-2788d2

### OS
Mac OS

### Browser
Chrome 75

## Additional context
We added input fields to the targeting dialog. When I clear the fields then there is no value and so the generated serviceUri (see snippet) does not contain a question mark. But at the end of the serviceUri a “&” is added. This means the serviceUri is not valid and if I click the apply button after clearing all values nothing happens, because the asyncRequest is not successful.

This is where the bug arises:
file: components/cstudio-contextual-nav/targeting.js
function: updateTargeting

`
for (var property in this.model) {

	if(this.model.hasOwnProperty(property)){
		value = this.model[property];
		key = property;
		console.log("props: ", property, key, value);

		if(value){
			console.log("property: ", property);
			if(first){

				first = false;
				serviceUri += "?" + key + "=" + value;
			}else{
				serviceUri += "&" + key + "=" + value;
			}
		}
	}
}

serviceUri = serviceUri + "&" + new Date();
console.log(serviceUri);

YConnect.asyncRequest('GET', CStudioAuthoring.Service.createEngineServiceUri(encodeURI(serviceUri)), {
	success: function() {
`

Maybe this happens only if there's only input fields (no other types like checkboxes etc.). I haven't tried to add checkboxes or dropdowns.

**Comment by gerald-exa** [comment]
Possible fix for this bug:

Sorry, currently I don't have to time send a pull request. Maybe you can use this snippet:
Project: studio-ui
file: file: components/cstudio-contextual-nav/targeting.js

`updateTargeting: function(reportContainerEl) {
	this.updateModel();

	var serviceUri = "/api/1/profile/set?",
		value,
		key;

	for (var property in this.model) {

		if(this.model.hasOwnProperty(property)){
			value = this.model[property];
			key = property;

			if(value){
				serviceUri += key + "=" + value + "&";
			}
		}
	}

	serviceUri += new Date();`

Notes about my changes:
Since there's always a date added to the end of the serviceUri (see last line of snippet) there will definitely be at least one url parameter. That's why I added the question mark to "var serviceUri = "/api/1/profile/set?",".
Then we can always put the "&" AFTER each parameter.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1236

**Comment by jvega190** [comment]
@yacdaniel please let me know if you need help to test this properly

**Comment by yacdaniel** [comment]
Verified fixed. 
@gerald-exa the next release of crafter  `3.1.1` will have this fix. 
![targeting](https://user-images.githubusercontent.com/6722074/61139564-cb9abf00-a486-11e9-99fb-e47a9df98cdb.gif)
