### ISSUE TITLE
[studio] User API - usernames with dots are truncated

### ISSUE THREAD

**Issue by suelje** [craftercms/craftercms#3280]
## Describe the bug
Usernames containing dots are not supported by Studios User API. 

## To Reproduce
1. Login to Studio
2. Create a new user with dot in its username
3. Try to edit/delete this user
4. See screenshot with empty values and Log attached

## Expected behavior
Usernames containing dots should be supported

## Screenshots
<img width="1878" alt="Bildschirmfoto 2019-07-12 um 09 04 34" src="https://user-images.githubusercontent.com/1357798/61109067-44e4e280-a484-11e9-8b4a-405864c68e26.png">

## Logs
`[ERROR] 2019-07-12T08:49:39,954 [http-nio-8080-exec-7] [v2.ExceptionHandlers] | API endpoint http://localhost/studio/api/2/users/cmsuser.thomas failed with response: ApiResponse{code=6000, message='User not found', remedialAction='Check if you're using the correct User ID', documentationUrl=''}
org.craftercms.studio.api.v1.exception.security.UserNotFoundException: No user found for username 'cmsuser' or id '-1'
	at org.craftercms.studio.impl.v2.service.security.internal.UserServiceInternalImpl.getUserByIdOrUsername(UserServiceInternalImpl.java:78) ~[classes/:3.1.0]`

### Version
Crafter CMS v3.1.0

## Additional context
[Studios User API](https://github.com/craftercms/studio/blob/c03a9067f3788a317ab4b8e9250d9898fdd7a4c9/src/main/java/org/craftercms/studio/controller/rest/v2/UsersController.java#L190)

Springs @PathVariable with dot (.) is getting truncated, see https://github.com/spring-projects/spring-framework/issues/10832 or https://github.com/spring-projects/spring-framework/issues/12288

**Comment by yacdaniel** [comment]
Verified fixed.
