### ISSUE TITLE
[studio-ui] Cannot add users to group when there are more than 10 users available

### ISSUE THREAD

**Issue by suelje** [craftercms/craftercms#3281]
## Describe the bug
When you have more than 10 users in the CMS, you are not able to add them all to a group due to the default [Studios User API getAllUsers()](https://github.com/craftercms/studio/blob/c03a9067f3788a317ab4b8e9250d9898fdd7a4c9/src/main/java/org/craftercms/studio/controller/rest/v2/UsersController.java#L93) limit of `10`. So only the first 10 users are fetched and offered for selection.

## To Reproduce
1. Create more than 10 CMS users
2. Try to add them all (or the 11th user (sorted alphabetically by username)) to a group

## Expected behavior
All users are offered for adding them to a group.

### Version
Crafter CMS v3.1.0

## Additional context
Request to Studios API:
`http://localhost:8080/studio/api/2/users`

The response is like: 
`{"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"total":50,"offset":0,"limit":10,"users":[ ... ]}`

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/3283

**Comment by yacdaniel** [comment]
Verified fixed. Thanks for the help @suelje!
