### ISSUE TITLE
[studio-ui] on delete warn user if there are existing dependencies that depend on the object being deleted

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3285]
**Is your feature request related to a problem? Please describe.**
Users delete items that have other objects in the system that count on the item to be deleted which causes broken links.

**Describe the solution you'd like**
On delete action, warn the user via dialog if there are existing dependencies that depend on the object being deleted

**Comment by rart** [comment]
<img width="1055" alt="delete-flow" src="https://user-images.githubusercontent.com/3928341/64278874-13513a80-cf4e-11e9-8609-ee6682675a8a.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1304

**Comment by russdanner** [comment]
Feature works when deleting a single asset. Deleting a folder that contains the image does not show the correct response:
https://www.loom.com/share/654d82a56d8e4dc3b3d81f9c23f0472f

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1795

**Comment by russdanner** [comment]
Confirmed
