### ISSUE TITLE
Studio: Preview is not reloaded after using the "Change Template" option.

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#329]
Steps to reproduce:

1. Open a page in preview
2. Right click the same page in the site dropdown
3. Click the "Change Template" option
4. Select the new content-type & update the required fields
5. Save the changes
6. The page in preview will show the previous content-type & content

When the page is manually reloaded from the browser the new content is displayed.

**Comment by vestrada** [comment]
completed
