### ISSUE TITLE
[studio-ui] Language settings are persisted per browser and not per user

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3290]
## Describe the bug
 When a user changes his language all the users in crafter on that browser will use that language.

## To Reproduce
1. As admin create a `test` user
2. Log out and Log In as `test` user
3. Change the language of `test` user to Spanish
4. Log out and Log In as `admin` user

## Expected behavior
Persist language settings per user instead of the browser if possible.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-f2e773
Build Number: f2e7738436efffcb2362118510d1c54ba10e7394
Build Date/Time: 07-17-2019 08:38:00 -0600

### OS
Any

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1289

**Comment by yacdaniel** [comment]
Verified fixed.
Automated test case: https://github.com/craftercms/test-suite/pull/428
