### ISSUE TITLE
[studio-ui] Changes made in configuration files are not listed in the "My Recent Activity" widget in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3293]
## Describe the bug
Changes made in configuration files are not listed in the "My Recent Activity" widget in the dashboard as edited

## To Reproduce
1. Create a site using any bp
2. Click on `Site Config` -> `Configurations`
3. From the dropdown, select any of the configurations
4. Make some changes to the selected configuration (add a comment or something)
5. Save your changes
6. Open the dashboard and look at the `My Recent Activity` widget.  Notice that the configuration file you modified is not listed

## Expected behavior
Changes made in configuration files should listed in the "My Recent Activity" widget in the dashboard

## Screenshots
Here's a short clip:
https://www.loom.com/share/802a4ea9a78c42458e7360eb88e57673

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-f2e773
Build Number: f2e7738436efffcb2362118510d1c54ba10e7394
Build Date/Time: 07-17-2019 10:16:42 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1677

**Comment by alhambrav** [comment]
Verified fixed.
