### ISSUE TITLE
[studio] AWS configuration file gets overwritten by the upgrade manager

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3295]
## Describe the bug
AWS configuration file gets overwritten by the upgrade manager and the upgraded Box/WebDAV Configuration have duplicate tags?

## To Reproduce
1. Create a site using the website editorial bp
2. Open the AWS/Box/WebDAV configuration files and fill in a profile by clicking on `Site Config` -> `Configurations`

This is what I put in the AWS configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<aws>
    <s3>
	    <profile>
            <id>s3-default</id>
            <credentials>
                <accessKey>xxxxxxxxx</accessKey>
                <secretKey>xxxxxxxxx</secretKey>
            </credentials>
            <region>us-west-1</region>
            <bucketName>sample-input-bucket</bucketName>
        </profile>
    </s3>
</aws>
```

This is what I put in the Box configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<box>
  <profile>
     <id>box-default</id>
     <clientId>abc</clientId>
     <clientSecret>...</clientSecret>
     <enterpriseId>...</enterpriseId>
     <publicKeyId>...</publicKeyId>
     <privateKeyPath>...</privateKeyPath>
     <privateKeyPassword>...</privateKeyPassword>
     <uploadFolder>videos</uploadFolder>
  </profile>
</box>
```

This is what I put in the WebDAV configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<webdav>
  <profile>
     <id>webdav-default</id>
     <baseUrl>abc</baseUrl>
     <deliveryBaseUrl>...</deliveryBaseUrl>
     <username>...</username>
     <password>...</password>
  </profile>
</webdav>
```

3. Save your changes to the configuration files
4. Restart Studio
5. Look at the configuration files modified from the previous steps, notice that it has been overwritten with the following:

For the AWS Configuration:
```
<?xml version="1.0" encoding="UTF-8"?><aws>
	<version>2</version>
   <s3/>
   <elasticTranscoder/>
   <mediaConvert/>
</aws>
```

For the Box Configuration:
```
<?xml version="1.0" encoding="UTF-8"?><box>
	<version>2</version>
   <box>
      <profile>
         <id>box-default</id>
         <clientId>abc</clientId>
         <clientSecret>...</clientSecret>
         <enterpriseId>...</enterpriseId>
         <publicKeyId>...</publicKeyId>
         <privateKeyPath>...</privateKeyPath>
         <privateKeyPassword>...</privateKeyPassword>
         <uploadFolder>videos</uploadFolder>
      </profile>
   </box>
</box>
```

For the WebDAV Configuration:
```
<?xml version="1.0" encoding="UTF-8"?><webdav>
	<version>2</version>
   <webdav>
      <profile>
         <id>webdav-default</id>
         <baseUrl>abc</baseUrl>
         <deliveryBaseUrl>...</deliveryBaseUrl>
         <username>...</username>
         <password>...</password>
      </profile>
   </webdav>
</webdav>
```

## Expected behavior
Values already in the AWS configuration file should not be overwritten/erased.

Also, notice the Box Configuration after restarting Studio and the sample Box Configuration, there's 2 box tags (\<box\>), should it just be one box tag?

Also, notice the WebDAV Configuration after restarting Studio and the sample WebDAV Configuration, there's 2 webdav tags (\<webdav\>), should it just be one webdav tag?

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-f2e773
Build Number: f2e7738436efffcb2362118510d1c54ba10e7394
Build Date/Time: 07-17-2019 10:16:42 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jdrossl** [comment]
@alhambrav the format of the files changed so it is expected to have repeated `box` & `webdav` tags, I will fix the bug of the existing data being removed

**Comment by alhambrav** [comment]
Verified fixed.
