### ISSUE TITLE
[studio] Site creation fails with an SQL error 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3296]
## Describe the bug
After a site creation fails (for example, if the site needs Solr and Solr is not running), if you try to create the site again, an SQL expetion occurs.

## To Reproduce
1. Try to create a site from a remote 3.0.x site (make sure you don't have Solr running)
2. An error appears saying the site couldn't be created because the deployer targets couldn't be created.
3. Try to create the same site again.

Notice now a huge SQL error appears in the message dialog (see screenshot).

## Expected behavior
Site creation should fail again, with the same message as the first one.

## Screenshots
![site-create-sql-error](https://user-images.githubusercontent.com/1598884/61406720-67269800-a8aa-11e9-909c-60aa704f175c.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1670

**Comment by avasquez614** [comment]
Verified
