### ISSUE TITLE
[studio-ui] WebDav Image Browse datasource not working

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3299]
## Describe the bug
When trying to browse images from WebDav (using the `Image from WebDav Repository`) the browse window never opens.

## To Reproduce
1. Create an `Image from WebDav Repository` datasource and associate it to an image picker. 
2. Open the content form and try browse from the image picker.

No browse window/popup appears and a JS error appears in the console:

```
Uncaught TypeError: Cannot read property 'id' of undefined
   at cb (<anonymous>:49:29)
   at Object.success (<anonymous>:90:21)
   at Object.success (common-api.js?version=35cb476ddb9123787076f3e65dff567490606756:3727)
   at Object.handleTransactionResponse (utilities.js?version=35cb476ddb9123787076f3e65dff567490606756:15)
   at utilities.js?version=35cb476ddb9123787076f3e65dff567490606756:15
```

## Expected behavior
You should be able to browse the WebDav images.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1240

**Comment by avasquez614** [comment]
Verified
