### ISSUE TITLE
[studio-ui] publish child page does not update the parents page status icon.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3302]
## Describe the bug
When a child page is created under pages that are not published, if the child is published the icon status of the parents pages remains never published. 
This happens independent of the total of parents page, reproducible with a minimum of 2 pages, a parent and a child. 

## To Reproduce
1. Create a site
2. Create a page 1
3. Create a child page 2
4. Create a child of that page called 3
5. Publish 3

## Expected behavior
Sidebar tree should update the icons of the parents

## Screenshots
https://www.loom.com/share/e7c4b7eb08474f39bd3f6b77df2ddd2b

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-f2e773
Build Number: f2e7738436efffcb2362118510d1c54ba10e7394
Build Date/Time: 07-18-2019 07:36:32 -0600

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1245

**Comment by yacdaniel** [comment]
Verified fixed.
