### ISSUE TITLE
[studio] Rebase option for pull-from-remote

### ISSUE THREAD

**Issue by suelje** [craftercms/craftercms#3303]
**Is your feature request related to a problem? Please describe.**
We try to seperate content creation from development. On one hand, our content editors work in Studios sandbox branch. They are allowed to CRUD content assets like pages, components, images. Our developers push code changes (templates, controllers, configurations) to a remote repository. Basically, our code deployment workflow works as follows: 
    - login to studio: $STUDIOSERVER/studio/api/1/services/api/1/security/login.json
    - and pull code changes $STUDIOSERVER/studio/api/1/services/api/1/repo/pull-from-remote.json
Unfortunately, afterwards in Studio ALL "content“ assets  are set to status "NEW_UNPUBLISHED_UNLOCKED". Unpleasant :-/ Our investigations lead to the assumption that a rebase instead of a merge would help and would not lead to those status changes.

Our workaround is to do the merge on our git server like: 
- pull Studios sandbox branch first
- **rebase** all code changes on that sandbox branch and, afterwards,
- pull back this branch into Studios sandbox 

**Describe the solution you'd like**
An additional parameter in $STUDIOSERVER/studio/api/1/services/api/1/repo/pull-from-remote.json which allows to do a rebase instead of a merge.

**Additional context**
[reproduce.pdf](https://github.com/craftercms/craftercms/files/3416657/reproduce.pdf)

**Comment by sumerjabri** [comment]
@dejan-brkic please add the option to the back, and then assign to front for UI.

**Comment by sumerjabri** [comment]
This is actually a bug in the way we process commits. The ticket to fix the bug is here: https://github.com/craftercms/craftercms/issues/3707

I will close this issue as it will be addressed elsewhere.
