### ISSUE TITLE
[engine] GraphQL should support additional tokenized fields

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3304]
## Describe the bug
When a field uses the `Tokenize for Indexing` option in a content-type the GraphQL schema should include both fields.

## Screenshots
![Screen Shot 2019-07-22 at 8 43 11 AM](https://user-images.githubusercontent.com/1236955/61641687-cc88d900-ac5c-11e9-89ca-d80184dd954e.png)

![Screen Shot 2019-07-22 at 8 42 41 AM](https://user-images.githubusercontent.com/1236955/61641692-ceeb3300-ac5c-11e9-9e7b-db4a86e04397.png)

### Version
3.1.1-SNAPOSHOT

**Comment by avasquez614** [comment]
@yacdaniel please help with testing this

**Comment by yacdaniel** [comment]
Verified.
