### ISSUE TITLE
[docs] Update Create Site API

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3307]
Add `authentication_type` parameter in example and notes.
https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/create-site.html
3.0 and 3.1

**Comment by alhambrav** [comment]
For 3.1: PR https://github.com/craftercms/docs/pull/793 
For 3.0: PR https://github.com/craftercms/docs/pull/794

**Comment by yacdaniel** [comment]
Verified fixed, just a small change in 3.0 for the blueprint name is needed
PR here: https://github.com/craftercms/docs/pull/796
