### ISSUE TITLE
[studio] Fix JavaDoc warning for ContentTypeServiceInternal

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3308]
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/sumer/code/crafter/craftercms/src/studio/src/main/java/org/craftercms/studio/api/v2/service/content/internal/ContentTypeServiceInternal.java:32: warning - @return tag has no arguments.
[INFO] Building jar: /home/sumer/code/crafter/craftercms/src/studio/target/studio-javadoc.jar

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1678
