### ISSUE TITLE
[studio] Audit error when bulk publish a big tree content

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3311]
## Describe the bug
When you bulk publish big content changes, audit log cannot be updated and an error is thrown. 

## To Reproduce
1. Create a site from editorial BP
2. In preview copy the folder `2016` and paste it into the folder `2017` keep doing this until you have a tree of ~10 folders
<img width="453" alt="Screen Shot 2019-07-24 at 08 29 01" src="https://user-images.githubusercontent.com/6722074/61803066-bc086800-adee-11e9-981d-c08049c25cad.png">

3. Go to `Site Config`  - `Publishing` and do a `Bulk Publish` of `/site/website/articles/`
4. See errors in `catalina.out` log, notice that `Publisher` became stopped
5. Chek `Audit` in `Main Menu`, there is no log about the bulk publish.

## Expected behavior
No errors in log and `Audit` logs the `Bulk Publish` process when there is a big tree of content.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![imagen](https://user-images.githubusercontent.com/6722074/61804153-a85e0100-adf0-11e9-8c9d-a1d6a4fefb6e.png)

## Logs
https://gist.github.com/yacdaniel/85dc

### Version
Studio Version Number: 3.1.1-SNAPSHOT-938521
Build Number: 938521904d360385edbf11382d59144ee622144d
Build Date/Time: 07-23-2019 12:46:17 -0600

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1676

**Comment by yacdaniel** [comment]
Verified fixed.
