### ISSUE TITLE
[studio-ui] Group management issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3312]
## Describe the bug
There are two issues in the `Groups` management section:
 1. When a user is added into the group, the group members list doesn't get updated, a reload of the page is required.
 2. When you search for a user which is in a different page that the current viewed, the user is not show.

## To Reproduce
Steps to reproduce the behaviors:
1. Add an User into a Group
2. Add more than 10 users, in the groups members list be located in page 1, search for a user which is in page 2

## Expected behaviors
1. User is shown in the members list when added.
2. Search return results even if they are in different pages.

## Screenshots
Issue 2. 
Members page 1
![imagen](https://user-images.githubusercontent.com/6722074/61828577-43240300-ae24-11e9-9bd3-88cd1a81e1fd.png)
Members page 2
![imagen](https://user-images.githubusercontent.com/6722074/61828595-4dde9800-ae24-11e9-8945-f43b13820202.png)
In page 1 search for a member that is listed in page 2
![imagen](https://user-images.githubusercontent.com/6722074/61828684-80889080-ae24-11e9-849c-22c5b65ac869.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-9867ea
Build Number: 9867ea92424e516d46a1db6e7661d5fede8e44c1
Build Date/Time: 07-24-2019 12:24:23 -0600

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1244

**Comment by yacdaniel** [comment]
Verified fixed.
