### ISSUE TITLE
[studio-ui] Warning message in the logs when previewing a page or saving edits on a page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3313]
## Describe the bug
There are warning messages in the logs when previewing a page or saving edits on a page

## To Reproduce
1. Create a site using the website editorial bp
2. Open the logs to see the warning messages before we begin previewing different pages on the site/editing
3. Edit the Home page then save you changes
4. Notice in the logs the warning message:
```
[WARN] 2019-07-25T16:06:56,669 [http-nio-8080-exec-1] [impl.ViewNotResolvedExceptionHandler] | Resource '/studio/static-assets/styles/guest.css' not found
[WARN] 2019-07-25T16:06:56,669 [http-nio-8080-exec-10] [impl.ViewNotResolvedExceptionHandler] | Resource '/studio/static-assets/themes/cstudioTheme/css/font-awesome.min.css' not found
```
5. Preview an article
6. Look in the logs and notice the warning message again
7. Preview some other pages and notice that every time a page is previewed, a couple of warning messages appear in the logs

## Expected behavior
There should be no warning messages when previewing pages/saving edits to pages

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's the warning in the logs:
```
[WARN] 2019-07-25T16:06:56,669 [http-nio-8080-exec-1] [impl.ViewNotResolvedExceptionHandler] | Resource '/studio/static-assets/styles/guest.css' not found
[WARN] 2019-07-25T16:06:56,669 [http-nio-8080-exec-10] [impl.ViewNotResolvedExceptionHandler] | Resource '/studio/static-assets/themes/cstudioTheme/css/font-awesome.min.css' not found
```

Here's a short clip showing the warning messages in the logs:
https://www.loom.com/share/68bf9d0b59d046c2b89280f9b4a09bd4

### Version
Studio Version Number: 3.1.1-SNAPSHOT-786427
Build Number: 786427b1901fed565d3ebc22b2a82b4b9dce5aca
Build Date/Time: 07-25-2019 10:23:53 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@alhambrav fixed in https://github.com/craftercms/studio-ui/pull/1248

**Comment by alhambrav** [comment]
Verified fixed.
