### ISSUE TITLE
[studio] Add YAML configuration that allows admins to configure a user friendly description of the password requirements

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3314]
**Is your feature request related to a problem? Please describe.**
An admin can set requirements for a password with a regex but they do not have a way to configure an error message that explains to the user what the requirements are.

**Describe the solution you'd like**
Allow the admin to specify a string in the studio YAML file that states what the password requirements are.

**Additional context**
Related to #2364

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1763
https://github.com/craftercms/craftercms/pull/3493

**Comment by russdanner** [comment]
When I enable the requirements and the message and then use the UI to reset my password I do not get the detailed description and I have this error in the log.

<img width="1393" alt="Screen Shot 2019-10-28 at 1 34 21 PM" src="https://user-images.githubusercontent.com/169432/67702325-e9355b00-f987-11e9-8ef7-e07f255bd3a4.png">

```
[ERROR] 2019-10-28T13:34:17,965 [http-nio-8080-exec-10] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/users/me/change_password failed with response: ApiResponse{code=6003, message='User password does not fullfill requirements', remedialAction='Use password that will fullfill password requirements', documentationUrl=''}
org.craftercms.studio.api.v2.exception.PasswordRequirementsFailedException: null```

**Comment by russdanner** [comment]
1. I don't think we you shave an error in the logs.  This is not an error scenario.
2. The UI should present the requirements.

**Comment by sumerjabri** [comment]
@dejan-brkic switch log level to `debug`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1812

**Comment by russdanner** [comment]
Confirmed log levels and spelling corrections
