### ISSUE TITLE
[craftercms] Upgrade Spring Security to 4.2.13

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3317]
Upgrade Spring Security in Studio, Profile Security Provider, and Social to 4.2.13.

**Comment by jdrossl** [comment]
Engine doesn't have a dependency for spring security

**Comment by avasquez614** [comment]
Sorry, it seems to be coming fro  Profile, I'll create a ticket for that

**Comment by avasquez614** [comment]
@jdrossl I updated the ticket description to say that it needs to be done in Profile Security Provider too.

**Comment by avasquez614** [comment]
@jdrossl we need to update Social too

**Comment by jdrossl** [comment]
@avasquez614 in social the `spring-security` dependency comes from profile

**Comment by avasquez614** [comment]
Verified
