### ISSUE TITLE
Studio failed to update taxonomy when upgraded from v3.0.18 to v3.0.20

### ISSUE THREAD

**Issue by manateeyl** [craftercms/craftercms#3321]
## Describe the bug
Studio failed to update our custom taxonomy (video-streams.xml) when upgraded from v3.0.18 to v3.0.20

## To Reproduce
1. Go to studio site
2. Click on taxonomy/videos
3. Add a new channel and click submit
4. See error "unable to write ...xml"

## Expected behavior
No error should be seen. When we roll it back to 3.0.18 and things start working again

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
V3.0.20
### OS
ubuntu

### Browser
Firefox

**Comment by russdanner** [comment]
Hi @manateeyl, 
When you have a error on write there will almost always be an error in CRAFTER/logs/tomcat/catalina.out.  Can you capture that stack trace, remove anything that's sensitive and post it here https://gist.github.com and provide the link to the post in this ticket?

This will help us understand why the write failed.

**Comment by russdanner** [comment]
@manateeyl Because your ticket originally referenced an E version of Crafter, I wanted to mention, you can go through Crafter Software's Support portal (https://craftersoftware.zendesk.com) for these types of issues/questions. If you have trouble logging in you can email us at support.at.craftersoftware.com

**Comment by manateeyl** [comment]
Please check the error stack: https://gist.github.com/manateeyl/6be7b25eee3bbace3b72e906d12c3329

**Comment by russdanner** [comment]
Hi @manateeyl reviewing your stack trace, it seems there is a policy file related issue with Tomcat/JVM.  Can you share: CRAFTER/bin/apache-tomcat/conf/catalina.policy.

**Comment by manateeyl** [comment]
What has been done to fix this? 
Also CRAFTER/bin/apache-tomcat/conf/catalina.policy is coming from the AMI. There is no custom change made.

**Comment by sumerjabri** [comment]
v3.0.25 addresses this issue.
