### ISSUE TITLE
[studio-ui] Create a new input only for numbers

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3322]
There should be a new form control that's basically an input/spinner that only accepts numbers, like HTML's `<input type="number"/>` (https://www.html5tutorial.info/html5-number.php). Valid postfixes are `_i`, `_l`, `_f` and `_d`, and field name autocomplete should be set to `_i`.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1252

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio/pull/1688

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/video-center-blueprint/pull/49

**Comment by avasquez614** [comment]
Verified
