### ISSUE TITLE
[craftercms] Update fields with `_i` in blueprints to use new number control

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3323]
The fields that have `_i` (and `_l`, `_f` and `_d`) in our blueprints should be changed to use the new number input control. Depends on https://github.com/craftercms/craftercms/issues/3322.

**Comment by vestrada** [comment]
studio - PR: https://github.com/craftercms/studio/pull/1691

**Comment by vestrada** [comment]
VC PR: https://github.com/craftercms/video-center-blueprint/pull/51

**Comment by avasquez614** [comment]
Verified
