### ISSUE TITLE
[studio] Some API in SwaggerHub does not have an indication of which properties in the request body is required

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3324]
## Describe the bug
Some API in SwaggerHub does not have an indication of which properties in the request body is required

## To Reproduce
1. In your browser, go to `https://app.swaggerhub.com/apis/craftercms/studio/3.1.1.11`
2. Look at the APIs under `repository`
3. Below is the `push_to_remote` API.  Notice there's no indication which parameters in the request body are required.
![Screen Shot 2019-07-30 at 3 25 50 PM](https://user-images.githubusercontent.com/25483966/62158884-7b24bd80-b2de-11e9-87f0-4a1ea7911757.png)

## Expected behavior
Required properties inside the request body for all Studio APIs should be marked in SwaggerHub like below:
![Screen Shot 2019-07-30 at 3 22 13 PM](https://user-images.githubusercontent.com/25483966/62158713-1a958080-b2de-11e9-8277-67c7f198b15f.png)

The following are what I have noticed so far that does not have an indication of the required properties inside the request body of the api:
- groups
- users
- search
- cmis
- repository
- configuration

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1695

**Comment by alhambrav** [comment]
Verified.
