### ISSUE TITLE
[studio] Not all configuration files have indication of workflow status (edited, new, etc) in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3325]
## Describe the bug
Not all configuration files have indication of workflow status (edited, new, etc) in the dashboard.

## To Reproduce
1. Create a site using the website editorial bp
2. Edit one of the configuration files by clicking on **Site Config** -> **Configuration**, then select one of the configurations from the dropdown.  We'll select the **AWS Profiles**  and **RTE (TinyMCE 5) Setup** for our example
3. Edit the configurations and save your changes.  For a new site, the `aws.xml` file should be a new file and the rte should be an edited file in the dashboard workflow when we look at the **My Recent Activiity** widget
4. Notice that the icon for the `rte-setup-tinymce5.xml` does not indicate any workflow.  
![Screen Shot 2019-07-30 at 2 34 43 PM](https://user-images.githubusercontent.com/25483966/62156333-d05dd080-b2d8-11e9-81ed-3a9df0c395c1.png)

If you look in Studio 3.0.x, configuration files have workflow status on its icon in the dashboard like below:
![Screen Shot 2019-07-30 at 2 27 29 PM](https://user-images.githubusercontent.com/25483966/62155204-490f5d80-b2d6-11e9-987c-588574b9a1f5.png)

## Expected behavior
Configuration files should have indication of workflow status in the dashboard

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-d2a6e6
Build Number: d2a6e6c226aeff2ad39293a4389f408b6d7b9e55
Build Date/Time: 07-30-2019 10:25:54 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1728

**Comment by alhambrav** [comment]
Verified fixed.
