### ISSUE TITLE
[engine] Engine should use it's own deps for Grapes instead of the local .m2

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3326]
Grapes is sometimes saying that a dependency can't be retrieved even though it's in the local `.m2`. It seems like for some reason it doesn't like `.m2` dependencies. Configure Groovy/Grapes in Engine so it doesn't use the dependencies of `.m2`.

**Comment by ImJohnDoe** [comment]
@avasquez614 I'm experiencing an issue that seems to be related to this.

### The Problem

When I run the `init-site.sh` script on my aws AMI instance I get the following output

```bash
/opt/crafter/bin$ ./init-site.sh 
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing grapes -- /opt/crafter/bin/grapes/resolved-caller-all-caller-working23.xml (Permission denied)

java.lang.RuntimeException: Error grabbing grapes -- /opt/crafter/bin/grapes/resolved-caller-all-caller-working23.xml (Permission denied)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...
```

### Attempted Solution

The bit about permission being denied suggests a lack of permissions. This is not to be solved by running as root, crafter actually advises against it should you try.

```bash
/opt/crafter/bin$ sudo ./init-site.sh 

Crafter CMS cowardly refuses to run as root.
Running as root is dangerous and is not supported.

```

Please Advise.

**Comment by ImJohnDoe** [comment]
According to [this guide for the AWS AMI](https://craftercms.org/blog/2019/04/setup-crafter-cms-delivery-using-crafters-aws-ami) I should have been in the authoring instance as the crafter user. I believe this was my mistake.

**Comment by avasquez614** [comment]
Verified
