### ISSUE TITLE
[studio] ICE does not init due to incorrect domain in overlayhook

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3327]
## Describe the bug
Pencils and drag and drop fail to init properly due to bad domain value in overlay hook

## To Reproduce
1. Go to editorial
2. Click on studio drag and drop or pencils, they do now init / work as epxected

## Expected behavior
Pencils should show and a DnD should work

## Screenshots
Overlayhook output looks like this 
```
requirejs.config({ baseUrl: 'http://localhost:8080/studio/static-assets/scripts', paths: { 'libs': 'http://localhost:8080/studio/static-assets/libs/', 'jquery': 'http://localhost:8080/studio/static-assets/libs/jquery/dist/jquery', 'jquery-ui': 'http://localhost:8080/studio/static-assets/libs/jquery-ui/jquery-ui', 'amplify': 'http://localhost:8080/studio/static-assets/libs/amplify/lib/amplify.core', 'noty': 'http://localhost:8080/studio/static-assets/libs/notify/notify.min', 'cache': 'http://localhost:8080/studio/static-assets/libs/js-cache/cache' } }); require(['guest'], function (guest) { guest.init({ hostOrigin: 'http://localhost:8080/studio', studioContext: 'studio', studioStaticAssets: 'static-assets' }); });
```
However, this value:
```
function (guest) { guest.init({ hostOrigin: 'http://localhost:8080/studio', studioContext: 'studio', studioStaticAssets: 'static-assets' }); });
```
and specifically the hostOrigin value should be `http://localhost:8080`

## Logs
NA

### Version
Studio Version Number: 3.1.1-SNAPSHOT-2cafd8
Build Number: 2cafd837239dd8ea7a346ed0d83929277e4153df
Build Date/Time: 07-31-2019 10:33:47 -0400

### OS
Any

### Browser
Any

**Comment by rart** [comment]
Fixed as part of https://github.com/craftercms/studio-ui/pull/1248

**Comment by russdanner** [comment]
CONFIRMED
