### ISSUE TITLE
[studio-ui] item-selector dropdown displays incorrectly when multiple data sources are configured

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3330]
## Describe the bug
When 2 or more item data sources are set for an item selector it creates mutiple/overlayed dropdowns instead of presenting the appropriate options in a single dropdown

## To Reproduce
1. Go to editorial blueprint based site edit the homepage content type to include a new item data source
2. Assign it to the item selector for the features
3. Edit the homepage and click the add button on the item selector

## Expected behavior
When multiple data sources are selected they should show up in a single dropdown

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-2cafd8
Build Number: 2cafd837239dd8ea7a346ed0d83929277e4153df
Build Date/Time: 07-31-2019 10:33:47 -0400

### OS
Any

### Browser
Any

## Additional context
<img width="1105" alt="Screen Shot 2019-07-31 at 1 57 15 PM" src="https://user-images.githubusercontent.com/169432/62235890-ea141c00-b39b-11e9-811a-3c6bfc669283.png">

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1254

**Comment by russdanner** [comment]
Confirmed
