### ISSUE TITLE
[studio] Studio authentication times out even though user has activity

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3338]
## Describe the bug
User is prompted by dialog to sign in while actively working in studio after some time.

## To Reproduce
1. Go to Sign in to studio
2. Over the course of 60 minutes, work in studio
3. You will be prompted via dialog to sign in at some point

## Expected behavior
Users session should never time out while they are actively working in studio

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-917471
Build Number: 917471786ee424e680bb2ff7fcdae81104112fd6
Build Date/Time: 08-02-2019 10:30:18 -0400

### OS
Any

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1692

**Comment by russdanner** [comment]
I am getting a disconnect message on every refresh now.
https://www.loom.com/share/1b604f2a4ae9499ab0c86f7ef59b81b7

```
Studio Version Number: 3.1.1-SNAPSHOT-06835e
Build Number: 06835ec16fb4a1ce22855a727ca89364b753fd3b
Build Date/Time: 08-13-2019 09:13:52 -0400
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1702

**Comment by russdanner** [comment]
Confirmed!

**Comment by russdanner** [comment]
Latest build fails on UI, 404 is returned as studio dynamically loads code for dialog on approve and publish action.  The following request failed.
`/studio/static-assets/components/cstudio-templates/approve.js` 


Version:
```
Studio Version Number: 3.1.1-SNAPSHOT-077fde
Build Number: 077fde129e0a1aeb1bd8fc97fc27b80db6345607
Build Date/Time: 08-23-2019 16:34:55 -0400```
