### ISSUE TITLE
Editing a css file from Studio not working 

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#334]
Verified on Crafter Studio 2.5.3

Currently:
Once edit file modal comes up, the browser console throws the following error
```
Uncaught TypeError: Cannot read property 'length' of null
    at Object.success (template-editor.js?version=4578396…:342)
    at Object.success (common-api.js?version=4578396…:3460)
    at Object.handleTransactionResponse (utilities.js?version=4578396…:15)
    at utilities.js?version=4578396…:15
```
And file can't be saved/updated

Expected:
User should be able to edit files from crafter studio.

Notes:
Seems issue is related to null array of options, might be at least filled with empty array `[]` and variable `variableOpts` is scoped inside `if` statement, should be outside of it, that is what looks like

**Comment by hlim** [comment]
tested  & confirmed.
