### ISSUE TITLE
[studio-ui] Update to GraphiQL to the latest version

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3341]
Please update graphiQL to the latest version (GraphiQL v0.13.2 at time of ticket) and enable explorer feature.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1256

**Comment by russdanner** [comment]
Assigned to Roy for code review/merge. Functionality is not merged yet.

**Comment by jvega190** [comment]
@russdanner it is merged now

**Comment by russdanner** [comment]
Confirmed
