### ISSUE TITLE
[studio] Add arbitrary key-value params to create site

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3342]
**Is your feature request related to a problem? Please describe.**
Blueprints receive a single parameter during site creation, the site ID. Other parameters like AWS creds, Box creds, CommerceTools creds, and so on, need to be passed to the BP as these can't be left in the BP.

**Describe the solution you'd like**
We want to support passing parameters to blueprints during creation. These are arbitrary KVP.

**Describe alternatives you've considered**
Provide help text to the BP user to add the missing fields. This results in a broken BP until these are filled out. Bad experience.

Please create API spec and let's discuss the spec and implementation approach.

**Comment by dejan-brkic** [comment]
Already implemented as part of other ticket(s)

**Comment by sumerjabri** [comment]
Verified.
