### ISSUE TITLE
[studio] List marketplace blueprints

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3343]
Create an API in Studio that proxies the Marketplace and lists the marketplace blueprints.

This is either a new API or an expansion on the list blueprints API.

Let's discuss when you're ready.

**Comment by sumerjabri** [comment]
@yacdaniel please add test automation to this API.

**Comment by yacdaniel** [comment]
@jdrossl please document in Swagger the `401 Unauthorized` response.

**Comment by yacdaniel** [comment]
@jdrossl please check the param `keywords`
This works `/marketplace/search?keywords=pizza`
```
{
  "response": {
    "code": 0,
    "message": "OK",
    "remedialAction": "",
    "documentationUrl": ""
  },
  "total": 1,
  "offset": 0,
  "limit": 10,
  "plugins": [
       .....
       .....
```

 but with more than one keyword it doesn't `/marketplace/search?keywords=blueprint%20pizza`
```
{
  "response": {
    "code": 0,
    "message": "OK",
    "remedialAction": "",
    "documentationUrl": ""
  },
  "total": 0,
  "offset": 0,
  "limit": 10,
  "plugins": []
```

**Comment by yacdaniel** [comment]
Verified.
