### ISSUE TITLE
[studio-ui] Add marketplace tab in create site dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3344]
Add a new tab within the create site dialog within the blueprints selector to allow selecting a blueprint from the marketplace (the first tab is built-in, the second tab is marketplace).

Start with a listing, but be ready to add filtering in the future.

**Comment by jdrossl** [comment]
Please take this in consideration for the new design https://github.com/craftercms/craftercms/issues/3479

**Comment by yacdaniel** [comment]
@rart @yureii00 feedback about the new Create Site dialog:
* Add message error when any of the required fields are missing. Take a look at the old Create Site messages, if the field's label has changed, update according.
  * `Site Id is required`
  ![imagen](https://user-images.githubusercontent.com/6722074/66503424-7588e800-ea84-11e9-8bf4-cd0f6120d979.png)
  * `Repo URL is required`
  ![imagen](https://user-images.githubusercontent.com/6722074/66503640-f47e2080-ea84-11e9-898d-c907a8a0957a.png)
  * `Username and Password` Authentication
  ![imagen](https://user-images.githubusercontent.com/6722074/66504127-c3522000-ea85-11e9-9725-c83190eeb08f.png)
  * `Username and Token` Authentication
  ![imagen](https://user-images.githubusercontent.com/6722074/66504196-e11f8500-ea85-11e9-95f8-2fd05a701025.png)
  * `Private Key` 
  ![imagen](https://user-images.githubusercontent.com/6722074/66504268-04e2cb00-ea86-11e9-838d-295d561de058.png)

* `Site Id` has a couple of restrictions:
  * When any special character is typed it shouldn't be added to the `Site Id`. Only `-` and `_` should be accepted.
  * Numeric `Site Id` restriction.  https://github.com/craftercms/craftercms/issues/3248
  ![imagen](https://user-images.githubusercontent.com/6722074/66504744-137db200-ea87-11e9-972c-79c38a3bc1c1.png)
  * Max length of 50 chars is not being honor, user should not be able to add more than 50 chars in the `Site Id`. Example with 52 chars:
  ![imagen](https://user-images.githubusercontent.com/6722074/66505016-b33b4000-ea87-11e9-9be5-4fa5906e928b.png)

* Add the word `Git` at the beginning of `Repo URL` and `Branch` 
![imagen](https://user-images.githubusercontent.com/6722074/66506590-dadfd780-ea8a-11e9-9cb1-1a8cf31cd076.png)

* When `Branch` and `Git Remote Name` are left empty, the default values should be shown in the Review page
![imagen](https://user-images.githubusercontent.com/6722074/66506887-66f1ff00-ea8b-11e9-9bb3-7929eed46ed4.png)
![imagen](https://user-images.githubusercontent.com/6722074/66506832-52156b80-ea8b-11e9-9dbd-f482fa4c9973.png)

* Select a BP, then check the `Push the site to a remote Git...` selet any auth, fill the data, uncheck the `Push the site to a remote Git...`  and check it again. Notice the auth fileds are missing.
![Credentials missing](https://user-images.githubusercontent.com/6722074/66507977-73775700-ea8d-11e9-905f-a5eac707c1b5.gif)

* Blueprint Details there is a lower case in `crafterCMS` it should be `CrafterCMS` 
![imagen](https://user-images.githubusercontent.com/6722074/66508171-c18c5a80-ea8d-11e9-82bb-4fe674009747.png)

**Comment by yacdaniel** [comment]
One more, the `Private Key` authentication method is not working, looks like the parameter is being sent empty
![imagen](https://user-images.githubusercontent.com/6722074/66514497-7b89c380-ea9a-11e9-9637-e3ecafe3dac8.png)

**Comment by yacdaniel** [comment]
@yureii00 private key still does not work, also in the first Create Site page add a space in `CrafterCMS` so it looks like `Crafter CMS`

**Comment by yacdaniel** [comment]
Verified.
