### ISSUE TITLE
[deployer] CommanLineProcessor should run regardless if there is a change set or not

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3347]
Currently the `CommandLineProcessor` only runs if there's' a changeset. It should run whenever the deployment is running, regardless if there's a changeset or not. For example, you might need a processor to run an `rsync` before any other processor runs.

**Comment by sumerjabri** [comment]
We need the _option_ to run without a changeset. Let's discuss.

**Comment by avasquez614** [comment]
Verified
