### ISSUE TITLE
[studio-ui] Change Publish status "Idle" to "Ready"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3351]
**Is your feature request related to a problem? Please describe.**
The Publish Status currently displays `Idle` when there's nothing in the publish queue.  Please change the status message to `Ready` instead of `Idle` (Message looks nicer with `Ready` =D)

![Screen Shot 2019-08-06 at 2 37 42 PM](https://user-images.githubusercontent.com/25483966/62566794-ccd9c480-b857-11e9-8b9d-08c1469c4cae.png)

Also, it would be nice for the status to get updated to `Ready` after the status `Started` instead of staying in the `Started` status.  Right now, the status stays in `Started` until another item is published

![Screen Shot 2019-08-02 at 3 46 59 PM](https://user-images.githubusercontent.com/25483966/62567306-e9c2c780-b858-11e9-9ce7-0f944f05ba6f.png)

![Screen Shot 2019-08-06 at 2 47 09 PM](https://user-images.githubusercontent.com/25483966/62567397-20004700-b859-11e9-9c9b-464c602c3b4f.png)

**Describe the solution you'd like**
Change Publish status "Idle" to "Ready"

If possible, update the `Started` publish status to `Ready` once Studio is ready to start publishing.

**Describe alternatives you've considered**

**Additional context**

**Comment by yacdaniel** [comment]
Verified fixed. The transition from  `Started`  to `Ready` was not possible. Studio just logs the last action to publishing.
