### ISSUE TITLE
[studio] escaped strings in xml after site update

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3354]
## Describe the bug
Escaped strings are present in notification-config.xml after site update

## To Reproduce
1. Start authoring with solr and without es `./gradlew -Penv=authoring -PskipElasticsearch=true -PwithSolr=true start  `
2. Create a site from this remote repo(based on a 3.0 bp) https://github.com/jdrossl/siterepo
3. Check the ` notification-config.xml ` file
4. See escaped strings.

## Expected behavior
No escaped strings in xml

## Screenshots
<img width="1110" alt="Screen Shot 2019-08-07 at 1 26 49 PM" src="https://user-images.githubusercontent.com/6722074/62657394-9ec1b680-b923-11e9-8ca7-4c7e42bc2fa9.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.1-SNAPSHOT-2613ef
Build Number: 2613efd83d9d67e9d56c3e0ceaa458dabd20bf65
Build Date/Time: 08-05-2019 10:44:26 -0600

### OS
Linux

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1708

**Comment by yacdaniel** [comment]
Verified fixed.
