### ISSUE TITLE
[studio] Implement repository conflict resolution API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3357]

**Comment by dejan-brkic** [comment]
3.0.x
Done
PR:
https://github.com/craftercms/studio/pull/1701

**Comment by russdanner** [comment]
Confirmed

**Comment by dejan-brkic** [comment]
Done 3.1
PR:
https://github.com/craftercms/studio/pull/1715
https://github.com/craftercms/video-center-blueprint/pull/53
