### ISSUE TITLE
[studio] Log entry when a site is removed should have the site name

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3358]
## Describe the bug
The log entry when a site is removed does not have information about which site was removed. 

## To Reproduce
1. Create and remove a site from authorin
2. Go to `Audit` main menu
3. See logs of `CREATE` and `DELETE` operations

## Expected behavior
The log entry when a site is removed shoudl have the site name value in the target field.

## Screenshots
Log entry when site is deleted
![image](https://user-images.githubusercontent.com/6722074/62801283-a3f93f80-baa2-11e9-8751-853c74f41881.png)

Log entry when site is created. Notice that here we add the site name in the target field.
![image](https://user-images.githubusercontent.com/6722074/62801319-bb382d00-baa2-11e9-9ac6-0deb25189b6d.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
```
Studio Version Number: 3.1.1-SNAPSHOT-2613ef
Build Number: 2613efd83d9d67e9d56c3e0ceaa458dabd20bf65
Build Date/Time: 08-05-2019 10:44:26 -0600
```

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1710

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/63309370-c31e7b00-c2b3-11e9-8368-f5c21d95d446.png)
