### ISSUE TITLE
[studio-ui] Create a UI for conflict resolution within Studio

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3359]
**Is your feature request related to a problem? Please describe.**
When a pull is performed from studio "Remote repos" module and merge conflicts occur, users are not able to solve conflicts from Studio UI.

**Describe the solution you'd like**
Create a UI that shows a `git status` summary as it pertains to conflicts that occurred during last pull and allow for resolution from within Studio UI.

**Describe alternatives you've considered**
<img width="2985" alt="conflict-resolution-v3" src="https://user-images.githubusercontent.com/3928341/62802361-ff015580-bae7-11e9-8b56-c571a072d527.png">

Note: For release one of this feature, use the stacked split view for the "Diff" dialog

**Comment by jvega190** [comment]
<img width="4190" alt="conflict-resolution-v5" src="https://user-images.githubusercontent.com/18267471/62872816-7ba85580-bcdb-11e9-8136-917e6b158ca0.png">

**Comment by rart** [comment]
**Latest Mockup**
<img width="4190" alt="Studio conflict resolution mockups" src="https://user-images.githubusercontent.com/3928341/62874069-d9ab5c00-bd20-11e9-8b75-4f0f4241222a.png">

**Comment by russdanner** [comment]
Confirmed 3.0.25

**Comment by jvega190** [comment]
3.1.1: https://github.com/craftercms/studio-ui/pull/1260
