### ISSUE TITLE
[studio] Add ability to configure a prefix and a postfix message to all commits

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3361]
**Is your feature request related to a problem? Please describe.**
Today every commit operation performed by Studio has a configurable commit message.
Some administrators need to attach a common prefix or postfix to every message.  Today this requires them to override every message and to look for new types of messages during upgrades.

**Describe the solution you'd like**
Provide the ability to configure a prefix and a postfix message that get attached to every type of commit message.

**Comment by sumerjabri** [comment]
@dejan-brkic think of it as a line/paragraph before the configured message and a line/paragraph after.

These configured messages are above and below the specific configured messages and are only applied if specified.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1729

**Comment by sumerjabri** [comment]
Messages are called _prologue_ and _postscript_ for before and after commit messages.

**Comment by russdanner** [comment]
confirmed
