### ISSUE TITLE
[studio] Sync `global` repo as part of cluster sync

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3362]
We should sync the global repo as part of cluster sync.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1725

**Comment by sumerjabri** [comment]
@yacdaniel please verify and test. Ping me if you need context.

**Comment by yacdaniel** [comment]
@dejan-brkic please change the log level in https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/cluster/StudioNodeSyncGlobalRepoTask.java#L96
 `        logger.error("Starting Cluster Node Sync Global repo task");`to debug

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1748

**Comment by yacdaniel** [comment]
Verified sync of `global` repo in cluster.
