### ISSUE TITLE
[studio] `api/1/publish/status.json` returns HTML for the `.json` call when user session times out.

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3364]
## Describe the bug
The system recurrently checks for publishing status via `status.json` API. When session times out, the service 401s and but the return value is HTML - subsequently causing parsing errors on the UI.

## To Reproduce
1. Log in
2. Wait for session timeout
3. Next automatic call to status.json results in a 401 followed by a browser console error

## Expected behavior
The service should return JSON with a user message (not developer lingo) that is usable for the UI.

**Comment by sumerjabri** [comment]
This will be addressed as part of 3.2 by switching to JWT.
