### ISSUE TITLE
[studio-ui] "Network error. Some functionality may be unavailable" message in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3366]
## Describe the bug
There's a "Network error. Some functionality may be unavailable" message in Studio
when refreshing the page or going to a different URL

## To Reproduce
1. Create a site using the website editorial bp.  Notice when the site loads, there's a "Network error. Some functionality may be unavailable" message on the bottom right of the browser
![Screen Shot 2019-08-14 at 12 15 24 PM](https://user-images.githubusercontent.com/25483966/63037544-4d6a7780-be8d-11e9-9af1-7997961fb454.png)

2. Click on `Dashboard` from the `Sidebar`, notice the network error message will again appear once the dashboard loads
3. Right click on your browser and select `Inspect` then select `Network`
4. Refresh the page and notice the network error message again and a 500 response 
![Screen Shot 2019-08-14 at 12 06 21 PM](https://user-images.githubusercontent.com/25483966/63036917-fe701280-be8b-11e9-89f8-3057dca97120.png)
5. From the `Sidebar` click on `Site Config`.  Again, notice the network error message once Site Config is displayed

## Expected behavior
There should be no network error messages when refreshing a page/going to a different URL

## Screenshots
Here's a short clip showing the network error message in Preview when refreshing/going to a different URL: https://www.loom.com/share/8ee1b146360542b7b683d546db461787

## Logs
When you inspect, the following messages appear in the Headers tab:
```
Request URL: http://localhost:8080/studio/api/1/services/api/1/security/validate-session.json?nocache=Wed%20Aug%2014%202019%2011:43:39%20GMT-0400%20(Eastern%20Daylight%20Time)

Request Method: GET
Status Code: 500 
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer-when-downgrade
```

In the Response tab, this is the message:
```
{"message":"Internal server error: \njava.lang.NullPointerException"}
```

![Screen Shot 2019-08-14 at 11 47 53 AM](https://user-images.githubusercontent.com/25483966/63035794-c5cf3980-be89-11e9-9d88-2ad54b5d92e8.png)

### Version
Studio Version Number: 3.1.1-SNAPSHOT-06835e
Build Number: 06835ec16fb4a1ce22855a727ca89364b753fd3b
Build Date/Time: 08-14-2019 10:09:55 -0400

### OS
OS X 10.13.6

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
@alhambrav this might be caused by https://github.com/craftercms/craftercms/issues/3338
Look at Russ comment https://github.com/craftercms/craftercms/issues/3338#issuecomment-520893682.
Should we close this?

**Comment by alhambrav** [comment]
@yacdaniel Thanks!  It is related to a comment in ticket https://github.com/craftercms/craftercms/issues/3338 that I did not see.
I have verified that the issue is fixed after the last PR https://github.com/craftercms/studio/pull/1702 in the ticket mentioned.

Closing the ticket now.
