### ISSUE TITLE
[studio-ui] Change the icon to something green/indicates success

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3369]
When git pulling/push from remote, the icon for success appears as follows:
![image](https://user-images.githubusercontent.com/3931908/63120357-2cc71e00-bf70-11e9-9734-cc46b463d77c.png)

Change it to something green/indicates success.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1283

**Comment by yacdaniel** [comment]
Verified new icon.

![image](https://user-images.githubusercontent.com/6722074/64622784-1bbdd100-d3a5-11e9-8b13-c948a946896b.png)
