### ISSUE TITLE
[studio] NullPointerException on publish when using an upgraded 3.0.x Crafter

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3370]
## Describe the bug
After upgrading a Crafter Authoring from 3.0.x to 3.1.1, and trying to publish, a `NullPointerException` appears. Publish still works and goes through though.

## To Reproduce
1. Create an editorial site in 3.0.x
2. Upgrade Authoring from 3.0.x to 3.1.x
3. Edit the Home page and publish.

Publishing goes through, but a `NullPointerException` is thrown by the `NotificationServiceImpl` and shown in the `catalina.out`.

## Expected behavior
No exception should be shown in the logs.

## Logs
https://gist.github.com/avasquez614/7a1efbfa3aff2ddf181735110957f1c7

**Comment by dejan-brkic** [comment]
https://github.com/craftercms/studio/pull/1712

**Comment by avasquez614** [comment]
Verified
