### ISSUE TITLE
[studio] Fix features drag and drop in editorial blueprint

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3378]
## Describe the bug
Drag and drop on home page of editorial fails.

The zoneId on the drag and drop of features (home page) is wrong due to field re-name.  Zone ID should be features_o.

## To Reproduce
1. Go to editorial site
2. Click on page components in preview tools

## Expected behavior
Drag and drop should work properly

### Version
Studio Version Number: 3.1.1-SNAPSHOT-5f88db
Build Number: 5f88db7a3a79bc7214c7be274786fe4dc0edf2e1
Build Date/Time: 08-16-2019 16:57:30 -0400

### OS
Any

### Browser
Any

**Comment by sumerjabri** [comment]
Verified.
