### ISSUE TITLE
[studio] API2 bad requests are returning 500 instead of 400 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3380]
## Describe the bug
 API2 bad request are returning a 500 instead of 400 
This endpoints are tested in the test suite, all of them use to return 400 when the bad request was made. Probably anothers endpoints that are not in the test suite are affected as well. 

## To Reproduce
1. Add a member to group bad request 
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/groups/2/members" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"BadRequestUsernames":["test1"]}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/4e483c75052c68f0b7c3e343d486e38b

2. Add remote bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/repository/add_remote" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"siteBadRequest":"test01"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}} `

Catalina error https://gist.github.com/yacdaniel/d5e8cacb6c0634b1c9b44b294871fe78

3. Create group bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/groups" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"idBadRequest": 100, "name": "testgroup", "desc": "group descriptio"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}} `

Catalina error https://gist.github.com/yacdaniel/a4e9563a2f05615cff52aebf6e1c687f

4. Create user bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/users" -H  "accept: application/json" -H "Content-Type: application/json" -d '{  "id": 10, "usernameBadRequest": "test2", "password": "test2", "firstName": "test2", "lastName": "test2", "email": "test2@test2", "enabled": true, "externallyManaged": false}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}} `

Catalina error https://gist.github.com/yacdaniel/2d4fb5ffe0b2617019fe45250d68baad

5. Get group by id bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X GET "http://localhost:8080/studio/api/2/groups/1BadRequest" -H  "accept: application/json" 

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/2b35681e7437f8c003754c5da4ac495a

6. Get all users bad request 
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X GET "http://localhost:8080/studio/api/2/users?limit=badRequest" -H  "accept: application/json" 

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/a6edb3a70203fad4ceaaf4258f8d78ad

7. Get all groups bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X GET "http://localhost:8080/studio/api/2/groups?limit=1BadRequest" -H  "accept: application/json" 

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/6c6a98017e4838c8adbb74744b4f0002

8. Get group members bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X GET "http://localhost:8080/studio/api/2/groups/1BadRequest/members" -H  "accept: application/json" 

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/7e23d29d92439f364b447812548af6f5

9. Pull from remote bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/repository/pull_from_remote" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"siteIdBadRequest": "test", "remoteName": "origin", "remoteBranch": "master", "mergeStrategy": "none"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/69fce172003b29c96562ed96f204d090

10. Push from remote bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/repository/push_to_remote" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"siteIdBadRequest": "test", "remoteName": "origin", "remoteBranch": "master", "force": true}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/61d39be096be0fb4db0c02e4177df5fb

11. Rebuild database repository bad request 
>  curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X POST "http://localhost:8080/studio/api/2/repository/rebuild_database" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"siteIdBadRequest": "test"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/6a5d45cec8ece4f35ee2be76f50370f8

12. Update groups bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X PATCH "http://localhost:8080/studio/api/2/groups" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"idBadRequest": 7, "name": "updated", "desc": "updated"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/ddd729ba457c4256dd97a0f4f529ed93

13. Update user bad request
> curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X PATCH "http://localhost:8080/studio/api/2/users" -H  "accept: application/json" -H "Content-Type: application/json" -d '{  "idBadRequest": 3, "username": "test2", "password": "test2", "firstName": "test2", "lastName": "test2", "email": "test23@test23"}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/a2488bb593ddf4a79f5096eadabceb08

14. Enable disable user by username bad request
>curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X PATCH "http://localhost:8080/studio/api/2/users/disable" -H  "accept: application/json" -H "Content-Type: application/json" -d '{"usernamesBadRequest": ["test2"]}'

`{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}`

Catalina error https://gist.github.com/yacdaniel/6efee87394a7fc089fa78265e8fb2ee7

## Expected behavior
HTTP response code is 400 and the response message is according to the 400

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-246997
Build Number: 24699729dc88675e92e8f194f807c92085154d76
Build Date/Time: 08-19-2019 15:45:30 -0600

### OS
Linux

### Browser
N/A

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1718

**Comment by yacdaniel** [comment]
Verified fixed.
