### ISSUE TITLE
[studio] Merge conflict results in empty dialog box

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3384]
## Describe the bug
Pulling from a remote repository and causing a conflict opens an empty dialog.

## To Reproduce
1. Create a site using Editorial BP called `parent`
2. Create a site called `child` using remote repository, and point it to {PATH_TO_CRAFTER_BUNDLE}/crafter-authoring/data/repos/sites/parent/sandbox
3. Edit the homepage and make a change in `child`
4. Edit the home and make a change in `parent`
5. Go to `child` site
6. Go to SiteConfig > Remote Repositories and pull from the parent
7. See error

## Expected behavior
The dialog should report that there was a merge conflict.

## Screenshots
![image](https://user-images.githubusercontent.com/3931908/63461534-d3a33280-c426-11e9-9a8e-ae2a09380047.png)

## Logs
https://gist.github.com/sumerjabri/05c73151a4385889e32724ae1a76efd5

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu 18.04 LTS

### Browser
Chrome

## Additional context
N/A

**Comment by sumerjabri** [comment]
@yureii00 please handle 500 better. The main bug is backend, but just wanted you to add better error handling. Roy has more context, reach out to him, please.

**Comment by sumerjabri** [comment]
@dejan-brkic several issues:
- Pulling with conflict returns 500 instead of 409
- Keep local file returns Unauthorized (missing permission config?)
- Accept remote returns Unauthorized

Try following the steps above to reproduce it all.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1717

**Comment by sumerjabri** [comment]
The UI is not honoring the 409 (see log) returned by the backend.

![image](https://user-images.githubusercontent.com/3931908/63530904-66020f80-c4d5-11e9-8446-bba14bd15fc2.png)

**Comment by sumerjabri** [comment]
Verified fixed.
