### ISSUE TITLE
[build] Include the version number in the binary archive files

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3387]
**Is your feature request related to a problem? Please describe.**
Uses who maintain multiple downloads of Crafter across versions would benefit from archive files that contain a version number

Example:
When download multiple versions of Crafter over time to a common folder, i.e.: crafter-cms-authoring.tar.gz

Multiple files/"versions" get created but there is no way of disambiguating which file is for which version:
crafter-cms-authoring.tar.gz 
crafter-cms-authoring.tar.gz (1) 
crafter-cms-authoring.tar.gz (2)

**Describe the solution you'd like**
crafter-cms-authoring-<version>.EXTENSION

**Comment by sumerjabri** [comment]
Verified fixed.
