### ISSUE TITLE
[studio-ui] I18n bundle entries used as constants in code

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3388]
## Describe the bug
The create/edit user dialog uses message bundle entries as constants in code. This breaks the dialog mechanics whenever the active language is anything but English.

```js
// admin.js
$scope.dialogMode = $translate.instant('common.CREATE');
```

```html
<!-- admin-users.html -->
<div class="form-group" ng-if="!(dialogMode == 'create')">
```

**Comment by sumerjabri** [comment]
@rart please write up the steps to reproduce and test and then assign to @yacdaniel

**Comment by rart** [comment]
## To reproduce
- Foreach available language review title and submission buttons for create/edit user, create group, new repository
- The text should read "Create" or "Edit" in the selected language rather than a constant looking (e.g. "common.CREATE User" would be incorrect, "Create User" would be correct)

**Comment by yacdaniel** [comment]
Verified fixed.
