### ISSUE TITLE
[engine] Support flattened content XML

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3392]
**Is your feature request related to a problem? Please describe.**
After the UI flattening efforts, rendering breaks due to [the new datasource mechanics](https://github.com/craftercms/craftercms/issues/2884). Please update the backend to support.

**Describe the solution you'd like**
The backend processor should read the inline attribute and handle the replacement of the include with the component XML inline.

**Additional context**
This is required for properly developing ICE of flattened components.

References
https://github.com/craftercms/craftercms/issues/2884
https://github.com/craftercms/craftercms/issues/2795

**Comment by rart** [comment]
@yureii00 please update your env, verify backend support and close ticket by commenting “Verified” and hitting close & comment once you have indeed verified. Comment or discuss and reassign to José Ross if needed if something doesn’t go as planned.

**Comment by yureii00** [comment]
Verified

**Comment by sumerjabri** [comment]
@yacdaniel please include test cases for the new data source in terms of using it to build content and searching for it.

**Comment by sumerjabri** [comment]
@alhambrav please document this feature.

This is assigned to Yac for testing and Vita for documentation.

**Comment by alhambrav** [comment]
Doc: PR https://github.com/craftercms/docs/pull/847

**Comment by yacdaniel** [comment]
Verified.
