### ISSUE TITLE
[studio-ui] Data sources that perform uploads should show progress bars during the upload

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3395]
**Is your feature request related to a problem? Please describe.**
Users need feedback during upload operations on large files like videos audio and other large assets.

**Describe the solution you'd like**
All form engine data sources and controls that support a file upload should show a progress bar during the upload process.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1311

**Comment by russdanner** [comment]
Confirmed
