### ISSUE TITLE
[docs] Add documentation on how to enable SSL/ TLS for crafter authoring, delivery in traditional deployment and docker container 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3397]
**Is your feature request related to a problem? Please describe.**
There is no documentation on how to enable SSL/ TLS for crafter authoring, delivery in traditional deployment and docker container

**Describe the solution you'd like**
Add documentation on how to enable SSL/ TLS for crafter authoring, delivery in traditional deployment and docker container

**Describe alternatives you've considered**

**Additional context**
Tomcat SSL config for authoring and delivery: `https://tomcat.apache.org/tomcat-8.5-doc/ssl-howto.html`

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/855

**Comment by avasquez614** [comment]
Verified
