### ISSUE TITLE
[craftercms] See if it's possible to use --auth-root-authentication-method=socket in embedded DB

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3399]
Since MariaDB 10.4, the default authentication mode is `--auth-root-authentication-method=socket`. See if it's possible to switch to this mode without affecting upgrades and backups.

**Comment by jdrossl** [comment]
To connect as `root` using the socket we would need to use `sudo` to run the scripts and I think we are preventing that for security, should we try to make the backup/restore work with the current user (assuming it would be `crafter` to match the user in the db)?

**Comment by sumerjabri** [comment]
We found another way.
