### ISSUE TITLE
[craftercms] Find a way to perform complex upgrade operations in Kubernetes

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3405]
Right now, upgrading from Kubenetes pods in 3.1.0 to 3.1.1 is relatively simple:

- Upgrade mounted configuration files.
- Restart the Kubernetes pods. A DB error will appear in the logs
- Run `./bin/crafter.sh upgradedb`
- Restart the Kubernetes pods. Authoring should be up successfully

The problem is if in later versions more changes need to be made, like the changes needed to upgrade from 3.0.x to 3.1.1, like updated the Deployer target files, which should be done before Studio starts.

Please find a way to do these upgrades in Kubernetes.

**Comment by sumerjabri** [comment]
Not required anymore. May reopen/create similar if we have this type of issue again.
