### ISSUE TITLE
RTE - Dragging custom component does not work properly

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#341]
## Currently
When dragging a custom component from different places inside RTE, the RTE gets rid of the container = `<span id="video-test" class="crComponent mceNonEditable">  . . . .  </span>` , leaves only the content of the component

Component Template /templates/web/video-component.ftl:
```
<img src=" . .  IMAGE PATH"/> 
```

Also tried another different markup for the component, like `div` or `span` (with inline styling) with image inside of it, but drag stops working entirely

## Expected
Components dragging should work properly inside RTE

Notes:
Browser: Chrome

**Comment by russdanner** [comment]
Please post component FTL (generic/simplified) version of it

**Comment by asotog** [comment]
not following what do you mean ? the "tested" component template was just an image on it

**Comment by russdanner** [comment]
You are talking about dragging an inserted image?

Or dragging an inserted COMPONENT?  If COMPONENT please post FTL for component.

**Comment by asotog** [comment]
No, the component template is the same i put above, just an image, i tried the simplest case possible, so when you insert this type of component it renders `<span ...> <img .. > </span>`, then when i try to drag the custom image component to other position, the `span` gets lost in the road, so the final dragged element is only `span` content which is the `img`.


Also tried component template with different structure like 
```
<div style="background-image: url(....); ">   
    ...
</div> 
```

And the dragging stops working, even styling the box as inline-block, defined width,...
