### ISSUE TITLE
[studio-ui] Require submission comment on publish request and publish related operations

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3413]
**Is your feature request related to a problem? Please describe.**
Some organizations require authors and administrators who publish content to comment/document the motivation for the request or publish activity.  Currently Crafter Studio does not require the comment box to be filled out.

Additionally, Delete which is at present a publish activity does not request a comment from the user.

**Describe the solution you'd like**
1. Provide a UI input for comment on every publish related UI that do not currently have one:
- Delete
- Bulk Publish

2. Provide a site-level configuration that determines if a comment is required. This should default to false for backward compatibility.

3. Enforce a required comment if the configuration is set to true.

**Comment by vestrada** [comment]
BE Ticket: https://github.com/craftercms/craftercms/issues/3437

**Comment by vestrada** [comment]
Approve, request publish and bulk publish is done.

PR: https://github.com/craftercms/studio-ui/pull/1312

Delete will be worked on: https://github.com/craftercms/craftercms/issues/3285

**Comment by vestrada** [comment]
XML:

`<publishing>
        <comments>
            
            <required>true</required>
            
            <delete-required>true</delete-required>
            <bulk-publish-required>true</bulk-publish-required>
        </comments>
    </publishing>`

**Comment by vestrada** [comment]
Per yac recommendation, I'm adding ui and configuration to support  require submission comment on publish by commit Id(s) secion on publishing tab.

PR: 
studio-ui: https://github.com/craftercms/studio-ui/pull/1364

**Comment by yacdaniel** [comment]
Verified.
