### ISSUE TITLE
[engine] Update @studio.iceAttr macro to support flattened components

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3414]
To support ICE on flattened components, in contrast with _regular_ components, we need additional information to execute the ICE op.

For example if you want to edit a flattened component inside `index.xml`,
we're suggesting adding a new attribute called `embeddedItemId`.
```freemarker
<@studio.iceAttr 
  path="/site/website/index.xm" 
  embeddedItemId="33333946-9b4b-2f99-03ef-a16af3f7f3e9"
/>
```
This would later translate to a new attribute on HTML elements: `data-studio-embedded-item-id`.

**Comment by sumerjabri** [comment]
Note that I renamed `child` to `embeddedItem`

**Comment by yureii00** [comment]
oks, will do the change

**Comment by jdrossl** [comment]
@yureii00 Would it be ok to generate something like this:
```
<div data-studio-component-path="33333946-9b4b-2f99-03ef-a16af3f7f3e9" data-studio-component-type="embedded">
```
 
It's better for backwards compatibility & support mixed items to use the same property.

**Comment by rart** [comment]
We need the parent path to be able to get to the child. What we suggest doesn’t break backward compatibility. A child component would look exactly like current mechanics dictate setting up an ICE op only with a new attribute.

**Comment by yureii00** [comment]
verified.

**Comment by yureii00** [comment]
Documentation needs to be updated.

**Comment by sumerjabri** [comment]
@yacdaniel after testing, send to @alhambrav for documentation updates.

**Comment by yacdaniel** [comment]
Verified, @alhambrav please add to the docs.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/860

**Comment by yureii00** [comment]
Verified
