### ISSUE TITLE
[docs] Update release notes of 3.1.1 to point to the upgrade with scripts doc

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3418]
Right now, the release notes of 3.1.1 still reference the upgrade from 3.0.x to 3.1.0 doc. It should now reference the `https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html` that explains how to use the upgrade scripts.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/825
PR https://github.com/craftercms/docs/pull/826

**Comment by avasquez614** [comment]
Verified
