### ISSUE TITLE
[commons] Use new tab for opening links present in the entitlement description footer

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3419]
**Is your feature request related to a problem? Please describe.**
Clicking any of the links present in the entitlement description footer open the link in the current browser window. This might cause loss of data is the user hasn't save before clicking any link in the footer. 
![image](https://user-images.githubusercontent.com/6722074/64050861-831e8a00-cb36-11e9-8ec0-874cf6dc38f3.png)

**Describe the solution you'd like**
Include the attribute `target="_blank"` in all the links that are present in the entitlement description footer

**Describe alternatives you've considered**
N/A

**Additional context**
Also update commons ent with this change.

**Comment by vestrada** [comment]
PRs:
craftersoftware/commons: https://github.com/craftersoftware/commons/pull/28

craftercms/commons: https://github.com/craftercms/commons/pull/184

**Comment by yacdaniel** [comment]
Verified fixed.
