### ISSUE TITLE
submittedfordeletion column not created causing publish fail with postgres 

### ISSUE THREAD

**Issue by jrosler** [craftercms/craftercms#342]
When trying to publish with alfresco as a repo and postgres as the database, received, "ERROR: column "submittedfordeletion" of relation "cstudio_objectmetadata" does not exist". 

I took a quick look in git and it appears that this column isn't created with postgres (in createDDL-postgres.sql), but is created with derby, mysql, oracle, and sql server.

**Comment by jrosler** [comment]
I worked around this by manually creating the column in postgres.

1. connect to postgres with psql
2. connect to your database (e.g. \connect crafter)
3. run the alter table to add the column (alter table cstudio_objectmetadata add column submittedfordeletion integer;)

**Comment by dejan-brkic** [comment]
Added missing column to create db script.
