### ISSUE TITLE
[studio-ui] Audit log operation filter for a site (from Site Config) should list only applicable items

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3421]
**Is your feature request related to a problem? Please describe.**
In the current version, the Audit log operation filter for a site, accessed from `Site Config` lists all possible operations, with some operations not applicable.  For example, the operation `Login` or `Login Fail` is not applicable for a site, it's a system operation. 

![Screen Shot 2019-09-03 at 11 40 46 AM](https://user-images.githubusercontent.com/25483966/64188078-b5cec800-ce3f-11e9-82c8-26d6706ce6ee.png)

**Describe the solution you'd like**
It would be nice for the Audit (from Site Config) log operation filter for a site to list only applicable items

**Describe alternatives you've considered**

**Additional context**

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1292

**Comment by alhambrav** [comment]
Verified fixed.
