### ISSUE TITLE
[studio] Support the Delete dialog with API to get child items & dependencies

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3422]
**Is your feature request related to a problem? Please describe.**
We need new API(s) to get dependent items as well as child items for the #3285 feature request. 

Prospect design is:
<img width="1055" alt="delete-flow" src="https://user-images.githubusercontent.com/3928341/64278874-13513a80-cf4e-11e9-8609-ee6682675a8a.png">

**Describe the solution you'd like**
Please create new API to get child items and dependent items from a list of paths. The API should work similar to the new publish API by receiving a list of URIs/paths from the items that are selected for deletion and return two list of items:
- Dependent items: items that will end up with broken references upon deleting the main set of selected files*
- Child items: items that will get deleted along with the main set of selected files*

`*` List of files that the API got called with

**More info & alternatives**
API 1 has `studio/api/1/services/api/1/dependency/get-dependencies` but doesn't provide get child items contain irrelevant pieces of information and different semantics.

[See #3285 for request details.](https://github.com/craftercms/craftercms/issues/3285)

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss the design.

**Comment by dejan-brkic** [comment]
API update:
https://github.com/craftercms/studio/pull/1732

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1738

**Comment by vestrada** [comment]
Please assign it to me when changes are done and merged.

**Comment by vestrada** [comment]
Verified
