### ISSUE TITLE
[studio-ui] History: Revert of item removes the ability to revert until screen refresh

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3423]
## Describe the bug
Revert of item removes the ability to revert until screen refresh

## To Reproduce
1. Create a site from any BP
2. Edit and Save page
3. Click on the `History` option
4. Click on the `Revert to this version` button for the last item in the `History` dialog.
5. Check that when the revert action takes places in the `History`  dialog the `Revert to this version`  button is missing.

## Expected behavior
`Revert to this version`  button is present when the content is reverted to any version.

## Screenshots
https://www.loom.com/share/389921fa3f2f40e7b9860c02a264403f

## Logs
N/A

### Version
Studio Version Number: 3.1.2-SNAPSHOT-1f0df9
Build Number: 1f0df9e38e6b916232af1299c06a6e21224f32f4
Build Date/Time: 09-03-2019 13:57:24 -0600

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by yacdaniel** [comment]
Also, notice that in `Site Config - Configuration`  when the `Revert` is used the `History` link in the `Configuration` page disappears. 
![historyLinkRemoved](https://user-images.githubusercontent.com/6722074/64881415-f389d880-d617-11e9-9e8e-2e53a1ad8a07.gif)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1305

**Comment by yacdaniel** [comment]
Verified fixed.
