### ISSUE TITLE
[studio] Rename publish status key "idle" to "ready" and support transition from "Started" status

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3424]
**As requested on #3351**
The api should return the key for 'Ready' status consistently called 'ready' as wished for.

**Describe the solution you'd like**
Temporarily, we're checking for "idle" to print ready. The backend should return the appropriate key or translated message.

**Additionally**
It is desired to update the Started publish status to Ready once Studio is ready to start publishing.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1744

**Comment by yacdaniel** [comment]
Verified.
