### ISSUE TITLE
[studio-ui] Capitalization of items in Audit logs operations filter is not consistent

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3428]
## Describe the bug
When looking at the available operations to filter for in the audit logs, the capitalization of the operations in the dropdown box is not consistent

## To Reproduce
1. Create a site in Studio
2. Open the `Sidebar` and click on `Site Config` then click on `Audit`
3. Click on the `Operations` dropdown 
4. Notice in some lines, all the words are capitalized and in some not
<img width="1349" alt="Screen Shot 2019-09-05 at 7 32 38 AM" src="https://user-images.githubusercontent.com/25483966/64338474-d87fee80-cfaf-11e9-95b6-6ce8cd98ab95.png">

## Expected behavior
It would be nice to have consistent capitalization of items in the operations filter, say:
**Add Remote**
**Remove Remote**

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.2-SNAPSHOT-1f0df9
Build Number: 1f0df9e38e6b916232af1299c06a6e21224f32f4
Build Date/Time: 09-04-2019 14:12:51 -0400

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1308

**Comment by alhambrav** [comment]
Verified fixed.
