### ISSUE TITLE
[studio] Create APIs to support "Publishing status dashboard"

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3429]
**In relation to #3352...**
We need new APIs to be able to support #3352's requests.

**Describe the solution you'd like**
Required APIs would be
- Get packages - retrieves the list of packages on the publishing queue. Each package should have at a minimum scheduled date, user who submitted, status, environment, comment and package id. It should support several filters namely a path expression, environments, and states.
- Get package details - retrieves the list of files associated with the package by package id. If this is not expensive to do at once on the `get packages` call, please do fit it there and we wouldn't need this second call.
- Cancel packages - given a list of package ids, it'd _cancel_ all.

![Publishing queue design](https://user-images.githubusercontent.com/3928341/64194478-863fb000-ce7f-11e9-8421-a5426ff39f24.png)

**Comment by dejan-brkic** [comment]
API doc:
https://github.com/craftercms/studio/pull/1743

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/video-center-blueprint/pull/63
https://github.com/craftercms/studio/pull/1756

**Comment by yureii00** [comment]
The api is working as expected.
