### ISSUE TITLE
[studio-ui] Template Code Examples

### ISSUE THREAD

**Issue by Auer111** [craftercms/craftercms#3430]
### Problem
Creating snippets for a templated code structure to be used by a whole team must be done with external tools. This creates inconstancy, is slower, and is prone to bugs. 

### Solution
Allow the [Template Code Examples](https://github.com/craftercms/studio-ui/blob/master/static-assets/components/cstudio-forms/template-editor.js) to be updated via a configuration file. Preferably in Site Config > Configuration > Select Configuration

### Currently
We either copy an existing component's contents, paste them into the new file, then gut them. Or, we pull snippets from from saved notepad.txt files.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1297

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1737

**Comment by jvega190** [comment]
videocenter bp: https://github.com/craftercms/video-center-blueprint/pull/58

**Comment by jvega190** [comment]
@jdrossl This needs to be added to upgrade manager. Please ping me if you have any questions

**Comment by jdrossl** [comment]
@yacdaniel please test

**Comment by yacdaniel** [comment]
@jvega190  please check if new lines, indentation could be preserved.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1346

**Comment by yacdaniel** [comment]
Verified
@alhambrav please add this new Configuration, `Code Editor Configuration` to the docs

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/863
