### ISSUE TITLE
[studio-ui] Update all controls to specify the supported postfixes

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3433]
All controls should have a function like `getSupportedPostfixes()` so the form engine can validate and display the right options for custom controls too.

**Comment by jdrossl** [comment]
@sumerjabri @rart while verifying the ticket I got these questions:
- The dropdown control only allows `_s`, is it really the only type supported or should we include others? there are some datasources that include a type property that could cause conflicts
- Should we allow custom controls to use any postfix or somehow limit to the ones we have defined? It could be possible for someone to create a custom mapping in ES but I think it's very unlikely and more error prone

**Comment by avasquez614** [comment]
@jdrossl:

- Can we get the list of datasources that can be used by the dropdown, and what types they can return?
- I think we should allow clients to specify their own postfix for customs controls.

**Comment by jdrossl** [comment]
@jvega190 can you help us with the list? I was looking at the `static-value-list` that has its own type property but I'm not sure if it really affects the resulting value in any way

**Comment by jvega190** [comment]
@jdrossl sure, I'll take a look

**Comment by jvega190** [comment]
@avasquez614 yeah, the `static-value-list` datasource support different types (but they are not validated anywhere). Still, the dropdown value can be any of those types (integer, string, boolean, etc). So we can set the default for dropdown to be `_s` and alow the user to select another if needed.

**Comment by jdrossl** [comment]
@avasquez614 do you think this needs to be updated or can be closed?

**Comment by avasquez614** [comment]
@jdrossl so the `dropdown` now has `_s` as default, but which ones are valid? Any? For example `_o` should be invalid.

**Comment by jdrossl** [comment]
It only accepts `_s`

**Comment by avasquez614** [comment]
Ok good, we can close the ticket
