### ISSUE TITLE
[marketplace] Design & implement the UI

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3436]
Right now the Marketplace App has only static pages & email templates, I started using https://materializecss.com/ but I'm not sure if we are going to make a full React app instead (maybe sharing components with Studio?).

The existing templates are:
- Home Page (already using materializecss)
- Getting Started (already using materializecss)
- Plugin Review Email
- Github Plugin Added Email
- Github Plugin Error Email

Please review the existing template and update according to new designs

**Comment by sumerjabri** [comment]
@rart you can schedule a call to review the MP current state and discuss options prior to visual design.

**Comment by rart** [comment]
Completed.
