### ISSUE TITLE
[studio] Please add comment field to go-delete and bulk-golive apis

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3437]
**Is your feature request related to a problem? Please describe.**
Related with https://github.com/craftercms/craftercms/issues/3413 ticket, We need to provide a UI input for comment on every publish related UI that do not currently have one:

* Delete
* Bulk Publish

The apis that we are using for those sections don't contain comment field.

Apis:
* https://docs.craftercms.org/en/3.1/developers/projects/studio/api/workflow/go-delete.html
* https://docs.craftercms.org/en/3.1/developers/projects/studio/api/deployment/bulk-golive.html

**Describe the solution you'd like**
Please add comment field to go-delete and bulk-golive apis

**Additional context**
Please review: https://github.com/craftercms/craftercms/issues/3413 ticket

**Comment by sumerjabri** [comment]
@dejan-brkic perhaps it's time we refactored bulk-publish to API2 and optimized it?
With regard to `delete`, we may also design API2 and prepare for the recycle bin implementation by spec'ing out the core API and keeping the functionality as-is until we tackle the new stuff.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1746

**Comment by vestrada** [comment]
Please:
* Please add comment field to go-delete.
* Don't forget to update documentation.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/docs/pull/838

Go delete already supports comment field. it is `submissionComment` (same as go-live API)
