### ISSUE TITLE
[studio-ui] The cursor is not always on the first field in the form when creating new content

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3440]
## Describe the bug
The cursor is not always on the first field on the form when creating new content

## To Reproduce
1. Create a site using any of the following bp: headless blog, headless store and website editorial.  For this example, we'll create a site from the website editorial bp
2. Open the `Sidebar` and navigate to the folder `/articles/2017/1` then right click and select `New Content`
3. Select `Page - Article` then click `Ok`
4. Notice that the cursor is not alway on the `Page URL` field, the first field in the form
![Screen Shot 2019-09-09 at 2 59 09 PM](https://user-images.githubusercontent.com/25483966/64558727-8ffb6480-d312-11e9-9222-417c308de4c4.png)
5. Try creating a site from the headless blog and the headless store and notice too that when creating new content that the cursor is not always on the first field on the form 

## Expected behavior
The cursor should always be on the first field in the form when creating new content

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's a short clip using the website editorial bp: https://www.loom.com/share/ed72d6baa9f745ceb6680ff09b6a0bf4
Some more example with headless blog and store:
https://www.loom.com/share/24e9f5ad8f544cc19f00b9aebdaec59e

### Version
Studio Version Number: 3.1.3-SNAPSHOT-c18ebe
Build Number: c18ebe9a2bc9ef51aa0b34a3d10fe763908a67ef
Build Date/Time: 09-09-2019 13:39:01 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@vestrada please review with aaron on best place to locate the focus call. He’s done recent work that pertained when the form had finished rendering.

Take into account ICE groups! where forms don’t render all fields but just the ice group fields.

Take into account controls other than inputs. For node selectors for example, you may focus the first button. Keep it simple though. If logic seems to be getting too crazy, reach out to me to discuss.

**Comment by alhambrav** [comment]
It seems like I am able to reproduce the cursor not appearing on the first item in the form when using the **Headless Blog** blueprint, then create new content for `items/posts`

Here's a short clip showing where I created 3 sites based on the Headless Blog bp, and for all 3 sites, the cursor does not appear on the form when I create new content for items/posts: https://www.loom.com/share/7b10dedf384d436a8111648f11ad77c8
 
Studio version used for the clip above is:

**Comment by sumerjabri** [comment]
FE2 will address this.
