### ISSUE TITLE
[studio-ui] Upload Image dialog from Page - Article's file field goes to edge of dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3442]
## Describe the bug
Upload Image dialog from Page - Article's file field goes to edge of dialog

## To Reproduce
1. Create a site using the website editorial bp
2. Preview one of the articles and click on `Edit`
3. Scroll down to the `Content` section and click on the `Replace` button in the `Image` field, then click on `Upload Images`
4. Notice the box for the file field goes to the edge of the dialog (see screenshots)

## Expected behavior
It would be nice for the box for the file field to not go to the edge of the Upload dialog from Page - Article, 

## Screenshots
![Screen Shot 2019-09-09 at 2 34 08 PM](https://user-images.githubusercontent.com/25483966/64568165-140c1700-d328-11e9-9f2f-1749e3ea1c0a.png)

## Logs
Here's a short clip showing the steps above: https://www.loom.com/share/cc3985f2421c473b9cb03a6f08823a81

### Version
Studio Version Number: 3.1.3-SNAPSHOT-c18ebe
Build Number: c18ebe9a2bc9ef51aa0b34a3d10fe763908a67ef
Build Date/Time: 09-09-2019 13:39:01 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@sumerjabri shall we replace this uploaded with the progress-showing uploaded we are working on for data sources?

@jvega190 what’s the status of the uploader?

**Comment by sumerjabri** [comment]
progress bars are always better

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1311

**Comment by alhambrav** [comment]
Verified fixed.
