### ISSUE TITLE
[studio-ui] User/group list does not get updated when adding more than the number to display

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3443]
## Describe the bug
User/group list does not display pagination links/get updated when adding more than the number to display so even if the user gets the notification that the user/group has been added, when you look at the list it looks like the user/group was not added.

## To Reproduce
1. Start Studio
2. Click on `Main Menu` then click on `Users`
3. Change the `Users per page` to 2
4. Add two more users.  Notice that when you're adding the second user, the list is not updated to reflect there's a second page that has the second user just added.
5.  Try the same on `Groups` from the `Main Menu` and it behaves the same as users

## Expected behavior
User/group list should be updated when adding more than the number to display by displaying pagination at the bottom of list

<img width="945" alt="Screen Shot 2019-09-10 at 7 50 29 AM" src="https://user-images.githubusercontent.com/25483966/64611644-f1b5e000-d39f-11e9-8898-f6f49211eb05.png">

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's a short clip:
https://www.loom.com/share/a3ad370c24d44d1197da58a787d5d3ab

### Version
Studio Version Number: 3.1.3-SNAPSHOT-c18ebe
Build Number: c18ebe9a2bc9ef51aa0b34a3d10fe763908a67ef
Build Date/Time: 09-09-2019 13:39:01 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1319

**Comment by alhambrav** [comment]
Verified fixed.
