### ISSUE TITLE
[studio-ui] Items published via a schedule then edited displays a warning message in the `Approve & Publish` dialog when selected with other items to be published on the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3444]
## Describe the bug
Items published via a schedule then edited displays a warning message in the `Approve & Publish` dialog when selected with other items to be published on the dashboard

## To Reproduce
1. Create a site using the website editorial bp
2. Edit a couple of articles then save your changes
3. Publish one of your edited articles on a schedule, say in 5 minutes
4. Wait until the scheduled article is published, then edit the article again and save your changes
5. Go to the dashboard scroll to the `My Recent Activity` widget
6. Select the two edited articles and click on `Approve & Publish` from the context nav
7. Notice the warning message given to the user caused by the edited article that was recently published on a schedule:
```
WARNING: The items you have selected for approval were submitted with different requested publish dates/times.
```
![Screen Shot 2019-09-10 at 10 38 28 AM](https://user-images.githubusercontent.com/25483966/64627235-4156d480-d3bd-11e9-9d34-741baabd7c2c.png)
8. Cancel the dialog, and this time, just select the article edited in step 4 above and click on `Approve & Publish`.  Notice that when the dialog for publishing opens, it displays the scheduled time it was published (which is past the current time)

![Screen Shot 2019-09-10 at 10 40 04 AM](https://user-images.githubusercontent.com/25483966/64629639-90066d80-d3c1-11e9-8b27-9cad653c95d2.png)

## Expected behavior
Items published via a schedule then edited should not display a warning message in the `Approve & Publish` dialog when selected with other items to be published on the dashboard

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's a short clip showing the steps above: https://www.loom.com/share/e2a34dd775c9403184ba96ee9cbd901f

### Version
Studio Version Number: 3.1.3-SNAPSHOT-a85a67
Build Number: a85a675c760b6f9c9fe5c10876cd57bdd579dedd
Build Date/Time: 09-10-2019 09:39:55 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1741

**Comment by alhambrav** [comment]
Verified fixed.
