### ISSUE TITLE
[videocenter] Incorrect data structure manipulations cause exceptions

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3445]
## Describe the bug
Video.js and Slider.js are reading data structures in a incorrect way.

## Additional context

See Video.js#L120
Adding multiple categories to a video causes the app to crash

Check access to props.data on Slider.js - data is an array but not consistently treated as such. Component should probably receive it's object instead of a single item array with it's bound object. It's been noticed that the slider doesn't show up at all due to these issues.

Check for other places where this issue may be occurring.

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/58

**Comment by russdanner** [comment]
Confirmed
