### ISSUE TITLE
[studio] Add delete_content permission to blueprints and upgrade pipeline for Delete dialog APIs

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3446]
Required for APIs implementation

https://github.com/craftercms/craftercms/issues/3422

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1739

**Comment by yacdaniel** [comment]
Verified the permission `delete_content` is present in the built-in blueprints and for existing sites the upgrade manager adds it.
