### ISSUE TITLE
[studio-ui] `Approve for Publish` dialog should have hard/soft dependencies listed with what files they belong with

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3448]
## Describe the bug
It would be nice to have hard/soft dependencies displayed with what files they belong with in the `Approve for Publish` dialog

## To Reproduce
1. Create a site using the website editorial bp
2. Edit a couple of articles and save your changes
3. Edit one more article and change the `Image` by uploading a new image for the article
4. Click on `Dashboard` from the `Sidebar`
5. Place a checkmark on all the articles that was edited, then click on `Approve & Publish` on the context nav
6. Notice how the dependencies are listed separately from the files to be published and you can't tell which dependency belongs with what

![Screen Shot 2019-09-10 at 2 24 00 PM](https://user-images.githubusercontent.com/25483966/64639827-b256b600-d3d6-11e9-982c-a4fde409d936.png)

## Expected behavior
It would be nice to have hard/soft dependencies displayed with what files they belong with in the `Approve for Publish` dialog

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.3-f331b6
Build Number: f331b617e4239ed6c9128a14a4e1c903b36b881f
Build Date/Time: 09-10-2019 11:10:12 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Completed.
