### ISSUE TITLE
[studio-ui] Clicking on "Schedule" should open dialog with "Items go live on a specific day & time" selected

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3449]
## Describe the bug
Clicking on `Schedule` from the context nav opens up the `Approve for Publish` dialog with `Items should go live now` selected and clicking on `Approve & Publish` from the context nav opens up the dialog with `Items go live on a specific day & time` selected

## To Reproduce
1. Create a site using website editorial bp
2. Edit the home page and save your changes
3. Click on `Schedule` from the context nav.  Notice that when the dialog opens, `Items should go live now` is selected.  Click on cancel 
4. From the context nav, click on `Approve & Publish`.  Notice that when the dialog opens, `Items go live on a specific day & time` is selected

## Expected behavior

When `Schedule` is clicked from the context nav, the `Approve for Publish` dialog should open up with `Items go live on a specific day & time` selected and when `Approve & Publish` is clicked from the context nav, the `Approve for Publish` dialog should open up with `Items should go live now` selected.
![Screen Shot 2019-09-11 at 10 24 15 AM](https://user-images.githubusercontent.com/25483966/64705779-7840ef00-d47e-11e9-883a-1a29dd94969d.png)
 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.3-SNAPSHOT-a85a67
Build Number: a85a675c760b6f9c9fe5c10876cd57bdd579dedd
Build Date/Time: 09-11-2019 09:23:24 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1306

**Comment by alhambrav** [comment]
Verified fixed.
