### ISSUE TITLE
The date row doesn't render lines fully in the 'Recently Published' widget

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#345]
When there are multiple date groups of published items, those date groups after the first one doesn't render lines fully as shown in the screenshot.

![screen shot 2017-01-10 at 1 32 17 pm](https://cloud.githubusercontent.com/assets/4325885/21819349/56de00fe-d739-11e6-9472-a68dbb8db0d9.png)

**Comment by vestrada** [comment]
Done

Master: #195
2.5.x: #196
