### ISSUE TITLE
[video-center] `manifest.json` 404s even though it exists

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3450]
## Describe the bug
React apps are ones to use a manifest.json file. On our react blueprints, when building the react app we leave the manifest.json in it's place and when the app tries to fetch it, engine replies with a 404 even though the file is in the correct location.

## To Reproduce
1. Clone video center - or other recent react blueprint
2. Load the homepage
3. Check network tab on dev tools for manifest.json
4. Notice 404 though build script does place the manifest.json in the place that's getting looked for

## Expected behavior
manifest.json file loads correctly

## Screenshots
<img width="637" alt="Screen Shot 2019-09-11 at 6 38 52 PM" src="https://user-images.githubusercontent.com/3928341/64716909-92e98700-d4c3-11e9-9766-2a2bd1b38158.png">

## Additional context
My guess is that the .json is getting mapped to services or scripts even though in this case is a physical file and even though the attempt is to get it pulled from static-assets.

**Comment by jdrossl** [comment]
@rart this issue is caused because the request to get the manifest file doesn't include the cookie or the parameter to set `crafterSite` so engine is looking for the file in the fallback site

**Comment by rart** [comment]
@jvega190 Please try adding `crossorigin="use-credentials"` to the manifest call and check if this incurs in cookies getting sent.

https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by jvega190** [comment]
@rart `crossorigin="use-credentials"` worked.
video-center: https://github.com/craftercms/video-center-blueprint/pull/58
ecom-bp: https://github.com/craftersoftware/ecom-blueprint/pull/33

**Comment by jdrossl** [comment]
We should also document this, do we have a guide for developing SPA apps?

**Comment by rart** [comment]
I agree.

Only a couple of blog posts. (@russdanner)

There are a couple of un-official blueprints but they haven't been promoted or added to the product yet.

**Comment by sumerjabri** [comment]
@rart when completed, assign the ticket to @alhambrav for documentation along with instructions on what to say and where to include in the doc IA.

**Comment by jvega190** [comment]
@alhambrav 
what it needs to be into every react bp is under `{appfolder}/public/index.html` file, the manifest file to be included as:
`<link rel="manifest" href="%PUBLIC_URL%/manifest.json" crossorigin="use-credentials">`.
@rart Should this be enough to say for documentation?

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/845

**Comment by rart** [comment]
@alhambrav,

See comments on PR: https://github.com/craftercms/docs/pull/845

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/858

**Comment by rart** [comment]
Incorrect grammar on the first para:
`Some web apps uses a...` => `Some web apps use a...`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/864
