### ISSUE TITLE
[studio-ui] Wrong array initialization in forms-engine

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3455]
## Describe the bug
There's a wrong array initialization that may cause errors on variable reading.
`var attributes = [" "]` initializes with an empty string on the first position. It should be an empty array.

## Expected behavior
Initialization should be an empty array `[]`

**Comment by rart** [comment]
What seems to be the problem? Ticket description doesn’t provide any context on why the initialisation is not considered incorrect.
