### ISSUE TITLE
[docs] 3.1.0 to 3.1.3 Docker/Kubernetes upgrade notes

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3457]
We need to add the following steps for people that want to upgrade 3.1.0 Docker/Kuber deployments to 3.1.3:

1. Compare the custom `shared/classes` volume-mounted config files with the ones from 3.1.3, and make any necessary changes:

- For `authoring_tomcat`: https://github.com/craftercms/craftercms/tree/v3.1.3/resources/env/authoring/tomcat-config/crafter
- For `delivery_tomcat`: https://github.com/craftercms/craftercms/tree/v3.1.3/resources/env/delivery/tomcat-config/crafter

2. Change the image version to 3.1.3 and restart containers.
3. Wait for the containers to come up, the `authoring_tomcat` log should show some DB errors.
4. Run `/opt/crafter/bin/crafter.sh upgradedb` inside the `authoring_tomcat` container.
5. Restart the `authoring_tomcat` container. The DB errors shouldn't appear anymore.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/835

**Comment by avasquez614** [comment]
Verified
