### ISSUE TITLE
[docs] Update docs to indicate that a Studio restart is required for default SSH keys to get picked up

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3460]
In the docs we indicate that defaults SSH keys can be utilized for implicit authentication to remote repositories:
```
Set the authentication type to None in the Create Site screen, if you put the key in the default RSA key path in the Crafter Studio server (~/.ssh/id_rsa). Remember the key needs to use the default filename (id_rsa and id_rsa.pub) when using this method of setting up access to the remote repository.
```

However, Studio must be restarted for the JVM to pick up the default keys. We must indicate that in the docs.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/834
PR https://github.com/craftercms/docs/pull/833

**Comment by sumerjabri** [comment]
Verified.
