### ISSUE TITLE
[studio-ui] Use green success icon in popup notification

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3463]
**Describe the solution you'd like**
When an action success and a notification pops, the icon is yellow with a warning icon. Change the icon to something green that indicates success. 

* Add User
![imagen](https://user-images.githubusercontent.com/6722074/65253732-61bb1900-dab8-11e9-8afa-0909a3ead359.png)
* Edit User / Reset Password
![imagen](https://user-images.githubusercontent.com/6722074/65253778-7697ac80-dab8-11e9-897e-7b46a8f4e09e.png)
* Remove User 
![imagen](https://user-images.githubusercontent.com/6722074/65253870-9af38900-dab8-11e9-882e-86d27a0698ae.png)
* Add Group 
![imagen](https://user-images.githubusercontent.com/6722074/65254017-d726e980-dab8-11e9-9364-b4f2e9d44bd7.png)
* Edit Group 
![imagen](https://user-images.githubusercontent.com/6722074/65254077-f32a8b00-dab8-11e9-87f0-52a6c5f0f9d8.png)
* Add User to group 
![imagen](https://user-images.githubusercontent.com/6722074/65254109-02113d80-dab9-11e9-97fb-4b15fa11ce6d.png)
* Remove User from group
![imagen](https://user-images.githubusercontent.com/6722074/65254223-2ec55500-dab9-11e9-887d-22aeea3fa933.png)
* Remove group 
![imagen](https://user-images.githubusercontent.com/6722074/65254792-14d84200-daba-11e9-8cf9-28352ccdf2dc.png)
* Account Managment - Change Language 
![imagen](https://user-images.githubusercontent.com/6722074/65254817-1c97e680-daba-11e9-857f-ea8f1d53183e.png)
* Account Managment - Change Password
![imagen](https://user-images.githubusercontent.com/6722074/65254985-5537c000-daba-11e9-86b0-7fa5f7f79b30.png)

**Additional context**
`Crafter CMS 3.1.4-SNAPSHOT`
Related to https://github.com/craftercms/craftercms/issues/3369

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1326

**Comment by yacdaniel** [comment]
Verified fixed.
