### ISSUE TITLE
[studio-ui] Clicking the label on dependency selection dialogs does not toggle the checkboxes

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3466]
## Describe the bug
When clicking labels on the approve or request publish dialogs, the checkboxes are not getting toggled

## To Reproduce
1. Open one of the recent dependency selection dialogs
2. Click the label

## Expected behavior
Checkboxes should respond to their label click

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1320

**Comment by rart** [comment]
Verified.
