### ISSUE TITLE
[studio] Add more info in the log during site creation

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3470]
There's too little information going out in the logs during site creation, specially when creating a site from remote. Please add more information like the following:

- Started site creation
- Cloning site from remote
- Creating Deployer targets
- Processing items
- Finished site creation

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1764

**Comment by avasquez614** [comment]
Verified
