### ISSUE TITLE
[docs] Updates for quick start guide

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3473]
## Describe the bug
The quick start guides https://docs.craftercms.org/en/3.1/getting-started/quick-start-guide.html
and https://docs.craftercms.org/en/3.0/getting-started/quick-start-guide.html contains example using the old bundle filename  convection `crafter-cms-authoring.tar.gz` this should be updated to something like `crafter-cms-authoring-3.1.X.tar.gz ?`  and for `3.0` `crafter-cms-authoring-3.0.X.tar.gz`

Also rename the `Derby database` to `MariaDB` database. 

### Version
`3.1.4-SNAPSHOT`
`3.0.27-SNAPSHOT`

**Comment by alhambrav** [comment]
`3.0`: PR https://github.com/craftercms/docs/pull/841
`3.1`: PR https://github.com/craftercms/docs/pull/842

**Comment by yacdaniel** [comment]
Verified.
