### ISSUE TITLE
[studio-ui] History: Compare to current opens a new dialog that is not focused

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3474]
## Describe the bug
When the user click the `History` option and then the `Compare to current` the new opened dialog is not selected by default. If you press the `Esc` key the ` History` dialog is being closed first when it should be closed the first element at the top of the dialogs, in this case, the one that opens with `Compare to Current`

## To Reproduce
1. Create a site from any BP
2. In the Home page click the `History` option
3. Click the `Compare to Current` action
4. Press the `Esc` key.

## Expected behavior
The dialog that opens with `Compare to current` should be focused when is open, so when a `Esc` key is presed the dialog is closed.

## Screenshots
![history compare current esc](https://user-images.githubusercontent.com/6722074/65523599-bd671700-dea9-11e9-98ea-de708549f138.gif)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`  `3.0.26-SNAPSHOT`

### OS
Any

### Browser
Chrome/Firefox

## Additional context
N/A

**Comment by rart** [comment]
Check for [PR](https://github.com/craftercms/studio-ui/pull/1336) being merged first.

**Comment by yacdaniel** [comment]
Verified fixed. 

![HistoryCompare](https://user-images.githubusercontent.com/6722074/66662046-51a0e000-ec05-11e9-820b-982ea3c2b63d.gif)
