### ISSUE TITLE
[studio-ui] Embedded Content DS should display Components when Content Type property is missing

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3477]
## Describe the bug
When the property `Content Type` of the `embedded-content` DS is empty and you edit a Page which contains an `Item selector` bound to the DS, the form will display Pages Content Types

## To Reproduce
1. Create a site from editorial BP 
2. Add the `embedded-content` to the site config tools, as is not added by default to the BP yet.
3. Go to `Site Config` and then open the `Page - Article` Content Type
4. Add an `embedded-content` DS and then an `item-selector` which is linked to the DS
5. Go to any page article and edit it, in the added `item-selector` click add.
6. Notice that the dialog that opens is displaying `Page Content Type`

## Expected behavior
If no `Content Type` is specified during modeling, when you add a item in Preview it should show `Components Content Type` 

## Screenshots
![image (1)](https://user-images.githubusercontent.com/6722074/65619751-ec4ebd00-df7d-11e9-90aa-889aace24ba4.png)
![image (2)](https://user-images.githubusercontent.com/6722074/65619783-fbce0600-df7d-11e9-892b-d1bf47e3afd9.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1339

**Comment by yacdaniel** [comment]
Verified.
