### ISSUE TITLE
[studio] Add a default gitignore file for all blueprints

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3478]
The file will be added to all built-in blueprints and added to existing sites using the Upgrade Manager

**Comment by sumerjabri** [comment]
Defaults include:
`node_modules`

**Comment by jdrossl** [comment]
@yacdaniel please do some tests to see if it works ok

**Comment by yacdaniel** [comment]
@jdrossl please check when a site is created from a blueprint

**Comment by yacdaniel** [comment]
Verified.
