### ISSUE TITLE
[studio] Cut and Paste Fails with Path Issue

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#348]
# Scenario
Cut sibling /contact-us and paste under sibling /about

# REST CALL
`GET http://localhost:8080/studio/api/1/services/api/1/clipboard/paste-item.json?site=test&parentPath=/site/website/about/index.xml&nocache=Tue%20Jan%2010%202017%2013:41:18%20GMT-0500%20(EST)`

## Request

```

> Regex
> 
> Hide data URLs
> All
> XHR
> JS
> CSS
> Img
> Media
> Font
> Doc
> WS
> Manifest
> Other
> Headers
> Preview
> Response
> Cookies
> Timing
> General
> Request URL:http://localhost:8080/studio/api/1/services/api/1/clipboard/paste-item.json?site=test&parentPath=/site/website/about/index.xml&nocache=Tue%20Jan%2010%202017%2013:41:18%20GMT-0500%20(EST)
> Request Method:GET
> Status Code:500 Internal Server Error
> Remote Address:[::1]:8080
> Response Headers
> view source
> Cache-Control:no-cache, no-store, max-age=0, must-revalidate
> Connection:close
> Content-Language:en-US
> Content-Type:application/json;charset=UTF-8
> Date:Tue, 10 Jan 2017 18:41:18 GMT
> Expires:0
> Pragma:no-cache
> Server:Apache-Coyote/1.1
> Transfer-Encoding:chunked
> Request Headers
> view source
> Accept:*/*
> Accept-Encoding:gzip, deflate, sdch, br
> Accept-Language:en-US,en;q=0.8
> Cache-Control:no-cache
> Connection:keep-alive
> Cookie:JSESSIONID=346430AD18C740B9167B4B4DAB5F1271; TinyMCE_mce_0_sizefd4f7ad0-24b9-cef3-4ab6-daa4062fbb36=cw%3D627%26ch%3D100; COMPANY_ID=20116; COOKIE_SUPPORT=true; GUEST_LANGUAGE_ID=en_US; ID=47616655704e4a5034546951794d724f5057503864673d3d; LOGIN=727573732e64616e6e65724063726166746572736f6674776172652e636f6d; moments_profile_moments_nav_tooltip_self=true; PASSWORD=6e4e6b324f384158796f466b374a3663646d6a4c34673d3d; REMEMBER_ME=true; SCREEN_NAME=6745354b632f51593671683078347132746b505973413d3d; USER_UUID=653848654e57574730367545635a485344693647776445523951626d77376d5a434641616e5a50504632453d; plugintestcom-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; canvas-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22%2Fsite%2Fwebsite%2Fcanvas-single-col%22%5D%7D; bootstrapbasic-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; bootstrapbasic-engineconfig-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22siteplugin-resources%22%3A%5B%22%2Fsite%2Fplugin-resources%2Fcomponent%2Fgoogle-map%22%2C%22%2Fsite%2Fplugin-resources%2Fcomponent%2Fqr-code%22%5D%7D; formEngineHeight=590; bootstraptest2-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; bootstraptest3-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%7D; bootstraptest4-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%7D; plugintest2-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; testing4-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; canvas-engineconfig-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22siteplugin-resources%22%3A%5B%22root-folder%22%5D%7D; testing4-components-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitecomponents%22%3A%5B%22%2Fsite%2Fcomponents%2Fslider-sets%22%2C%22%2Fsite%2Fcomponents%2Fthemes%22%5D%7D; testing4-engineconfig-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22siteplugin-resources%22%3A%5B%22%2Fsite%2Fplugin-resources%2Fplugins%2Ftheme-canvas%2Ftheme-canvas%22%5D%7D; testing5-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%7D; testing6-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; mike-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; test7-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; test9-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%7D; rt1-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%7D; rt2-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22root-folder%22%5D%7D; test-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22%2Fsite%2Fwebsite%2Fabout%22%5D%7D; test2-pages-opened=%7B%22root-folder%22%3A%5B%22root-folder%22%5D%2C%22sitewebsite%22%3A%5B%22%2Fsite%2Fwebsite%2Fen%22%5D%7D; JSESSIONID=EB0D0BD1B44C9B6A60C0CA507A340816; crafterStudioLanguage=en; wcm-site-dropdown-prefs-default=%7B%22height%22%3A%22237px%22%2C%22width%22%3A%22265px%22%2C%22visible%22%3Atrue%2C%22scrollX%22%3A0%2C%22scrollY%22%3A81%7D; crafterSite=test
> Host:localhost:8080
> Pragma:no-cache
> Referer:http://localhost:8080/studio/preview/
> User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> X-Requested-With:XMLHttpRequest
> Query String Parameters
> view source
> view URL encoded
> site:test
> parentPath:/site/website/about/index.xml
> nocache:Tue Jan 10 2017 13:41:18 GMT-0500 (EST)

````

## SERVER RESPONSE

`{"message":"Entry not found by path: site/website/aboutcontact-us"}`

### UI RESPONSE

Ugly undefined alert box

### LOGS

> [ERROR] 2017-01-10 13:35:35,962 [http-bio-8080-exec-17] [clipboard.ClipboardServiceImpl] | Destination URI: /site/website/about/search 
> [ERROR] 2017-01-10 13:35:36,048 [http-bio-8080-exec-17] [rest.RestScriptsController] | Error executing REST script at /scripts/rest/api/1/clipboard/paste-item.get.groovy 
> org.craftercms.engine.exception.ScriptException: Entry not found by path: site/website/aboutsearch
> 	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:61)
> 	at org.craftercms.engine.controller.rest.RestScriptsController.executeScript(RestScriptsController.java:131)
> 	at org.craftercms.engine.controller.rest.RestScriptsController.handleRequestInternal(RestScriptsController.java:83)
> 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
> 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.craftercms.studio.impl.v1.service.security.StudioAuthenticationTokenProcessingFilter.doFilter(StudioAuthenticationTokenProcessingFilter.java:57)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
> 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.craftercms.engine.servlet.filter.SiteContextResolvingFilter.doFilter(SiteContextResolvingFilter.java:46)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.craftercms.engine.servlet.filter.ExceptionHandlingFilter.doFilter(ExceptionHandlingFilter.java:56)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.craftercms.commons.http.RequestContextBindingFilter.doFilter(RequestContextBindingFilter.java:78)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Entry not found by path: site/website/aboutsearch
> 	at org.eclipse.jgit.api.CommitCommand.createTemporaryIndex(CommitCommand.java:480)
> 	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:236)
> 	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.moveContent(GitContentRepository.java:257)
> 	at org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.moveContent(ContentServiceImpl.java:499)
> 	at org.craftercms.studio.impl.v1.service.content.DmRenameServiceImpl.rename(DmRenameServiceImpl.java:360)
> 	at org.craftercms.studio.impl.v1.service.clipboard.ClipboardServiceImpl.cutPaste(ClipboardServiceImpl.java:361)
> 	at org.craftercms.studio.impl.v1.service.clipboard.ClipboardServiceImpl.paste(ClipboardServiceImpl.java:80)
> 	at org.craftercms.studio.api.v1.service.clipboard.ClipboardService$paste.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:146)
> 	at scripts.api.impl.clipboard.SpringClipboardServices.paste(SpringClipboardServices.groovy:54)
> 	at scripts.api.impl.clipboard.SpringClipboardServices$paste$4.callCurrent(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:179)
> 	at scripts.api.impl.clipboard.SpringClipboardServices.paste(SpringClipboardServices.groovy:98)
> 	at scripts.api.impl.clipboard.SpringClipboardServices$paste$3.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:146)
> 	at scripts.api.ClipboardServices.paste(ClipboardServices.groovy:32)
> 	at scripts.api.ClipboardServices$paste$2.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:146)
> 	at paste-item_get.run(paste-item.get.groovy:15)
> 	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:589)
> 	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
> 	... 70 more

**Comment by russdanner** [comment]
Font end looks correct.  It is passing the parent location where the paste should happen.  Assumption is that whatever is on the clipboard is getting pasted there.

**Comment by sumerjabri** [comment]
Closing as copy/paste is being refactored in 2.5 and will be committed to both branches.
