### ISSUE TITLE
[studio-ui] Remote repositories list is not responsive

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3480]
## Describe the bug
The `Remote Repositories` list in `Site Config`  is not responsive.

## To Reproduce
1. Add a Remote Repository in `Site Config`
2. Narrow the width browser screen until you notice the missing elements at the right in the table, like the push, pull an remove buttons.

## Expected behavior
The `Remote Repository` list is responsive

## Screenshots

![imagen](https://user-images.githubusercontent.com/6722074/65644310-271e1880-dfb1-11e9-8a42-bcf538faeb82.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1322

**Comment by yacdaniel** [comment]
Verified fixed.
![imagen](https://user-images.githubusercontent.com/6722074/65882789-f5aba100-e352-11e9-8407-ac370dc01c60.png)
