### ISSUE TITLE
[studio] Add new data sources (Shared, Embedded) and deprecate old one (Child)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3485]
Please add two new data sources:

- `Embedded Content` This is to use the new content flattening mechanics
- `Shared Content` This is the old Child Content data source renamed to this

Rename:
- `Child Content` to become `Child Content (deprecated)` <== just the label changes

**Comment by rart** [comment]
@vestrada see comments on https://github.com/craftercms/craftercms/issues/2884

**Comment by sumerjabri** [comment]
@jdrossl please update UM to handle this.

**Comment by sumerjabri** [comment]
Verified.
