### ISSUE TITLE
[studio-ui] Do not allow user to save content type that does not have a file-name component

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3487]
## Describe the bug
The `file-name` variable name is a required field. The content-type builder should enforce the existence of this variable before allowing a user to save a definition.

Currently, the builder does not enforce the field which means forms can be created/loaded that will not save properly.

## To Reproduce
1. Go to content type editor for site empty
2. Click on open existing form for entry
3. remove page url field (file-name)
4. You can save even though you should get an error.

## Expected behavior
User should get an error when trying to save a content type definition that does not contain a field that is called file-name

### Version
Studio Version Number: 3.0.16-SNAPSHOT-4c989c
Build Number: 4c989c7cb50201155c988637a6db453257b7a1cc
Build Date/Time: 08-02-2018 14:57:36 -0400

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1334

**Comment by russdanner** [comment]
Confirmed
