### ISSUE TITLE
[studio-ui] support multi-select control in form engine

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3488]
**Is your feature request related to a problem? Please describe.**
Group checkboxes typically are used today to support multi-select scenarios in the form engine.  However, when the list of options is large this control can be unwieldy.

Select a multi-select control in to form engine

UX Example:
https://mdbootstrap.com/docs/jquery/forms/multiselect/

**Describe the solution you'd like**
Provide a multi-select control that allows for a large number of options to be reviewed and selected.  Example:
https://mdbootstrap.com/docs/jquery/forms/multiselect/

**Comment by sumerjabri** [comment]
Will be handled in FE2. Added to requirements.
