### ISSUE TITLE
Version History is lost after renaming a content

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#349]
1) Create a content
2) Publish a content
3) View history. The content should have ver 1.0
4) Edit the content and change the file name.
5) View history. The content only has ver 0.1

We might need a discussion around this, but at least the user should be warned that version history will be lost when they rename a content. Also, how can we recover version history in this case?

**Comment by gortizcrafter** [comment]
1. I Created a content
2. I published the content created
3. The history display the version 1.
4. I edited the content published
5. The history display the version 1.1
6. I pusblised the content edited
7. The history display the version 2.


The behavior is correct.

**Comment by hlim** [comment]
Has this been tested in Alfresco Repo and also with a page content (content-as-folder = false)?

**Comment by hlim** [comment]
This issue happens with Alfresco repo. Doesn't need a page content to reproduce.

**Comment by russdanner** [comment]
When you re-open a ticket, please put it IN PROGRESS column and ASSIGN it back to the developer or they will not act on it.

**Comment by gortizcrafter** [comment]
All test using crafter-alfresco (alfresco repo)

Test1
   1. I Created a content
   2. I published the content created
   3. The history display the version 1.
   4. I edited the content published
   5. The history display the version 1.1
   6. I published the content edited
   7. The history display the version 2.

The behavior is correct.

Test2
   8. I used old content
   9. I published the content 
   10. The history display the version 1.
   11. I edited the content published
   12. The history display the version 1.1
   13. I published the content edited
   14. The history display the version 2.

The behavior is correct.

Repository used: https://www.screencast.com/t/lf3pGGuzkxG
