### ISSUE TITLE
[studio-ui] Add validation messages to Create User dialog

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3491]
## Describe the bug
The create user dialog allows entering fields of any length which causes DB errors

## To Reproduce
1. Go to Users menu
2. Click on New User
3. Fill in the First Name, Last Name or Username with values longer than 32 chars, fill the remaining values
4. Click Save
5. See error

## Expected behavior
`First Name` `Last Name` and `Username`  should have validations. When a value is longer than the 32 chars a message error should be displayed under each input and the form can not be saved until those values are fixed.

## Screenshots
![image (2)](https://user-images.githubusercontent.com/6722074/66061818-67bfe980-e4fd-11e9-895d-8bee2c18c8e6.png)

N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1325

**Comment by yacdaniel** [comment]
@jvega190 please add translactions
![imagen](https://user-images.githubusercontent.com/6722074/66230189-dbe6c280-e6a0-11e9-802f-5c50e965a7dd.png)

**Comment by jvega190** [comment]
@yacdaniel the updated fields are using new i18n mechanics, and its tranlations will be generated when releasing

**Comment by yacdaniel** [comment]
thanks @jvega190
Verified message with English language.
