### ISSUE TITLE
[studio] Develop self-clustering embedded database for Studio

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3496]
Per our conversation, please develop the self-clustering embedded database for Studio we designed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/MariaDB4j/pull/17
https://github.com/craftersoftware/MariaDB4j/pull/1
https://github.com/craftersoftware/craftercms/pull/3
https://github.com/craftercms/craftercms/pull/3624
