### ISSUE TITLE
[engine] cstudio-support.ftl should not use overlayCallback

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3498]
The overlay callback was only used in Crafter 2.5, and the related classes will be removed in Engine soon. Please update the `cstudio-support.ftl` that uses the `siteContext.overlayCallback` to check if Engine is running in preview mode to use `modePreview` instead.

**Comment by sumerjabri** [comment]
@alhambrav please update documentation.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/851

**Comment by avasquez614** [comment]
Verified
