### ISSUE TITLE
[studio] Sites with descriptorVersion: 1 cannot be upgraded.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3499]
## Describe the bug
A site with the  value `descriptorVersion: 1` defined in `craftercms-plugin.yaml`  cannot be upgraded.

## To Reproduce
1. Create a site from remote using a 3.1.0 version https://github.com/crafter-qa/editorialsite310
2. See error

## Expected behavior
Site is upgraded and works as expected.

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/66220745-cbc3e880-e68a-11e9-9fa4-aaf9aa59f414.png)

## Logs
Tomcat Studio log:
```
[INFO] 2019-10-04T09:38:45,954 [http-nio-8080-exec-5] [site.SiteServiceImpl] | Clone from remote repository create option selected 
[INFO] 2019-10-04T09:38:45,954 [http-nio-8080-exec-5] [site.SiteServiceImpl] | Creating site testsite310 by cloning remote repository origin (https://github.com/crafter-qa/editorialsite310) 
```

### Version
`3.1.4-SNAPSHOT` 

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1768

**Comment by yacdaniel** [comment]
Verified fixed.
