### ISSUE TITLE
Cannot create new components on sites

### ISSUE THREAD

**Issue by jrosler** [craftercms/craftercms#350]
In 2.5.2, if I create a new site with one of the templates (tried this with empty and corporate), I noticed that if I'm in studio and right click on the Components/components in the site content pane, I get a dropdown that lists view, Copy, and Unlock and no other actions (like New Content).

It appears that the problem is that the components folder is missing from my site's work-area. I can work around this by going into my repo (e.g. ./data/repo/wem-projects/<sitename>/<sitename>/work-area/site) and creating a components folder. After I do that and refresh my page I get New Content, New Folder, etc. in the right click context menu in studio.

I'd guess this is a problem with the components folder not getting set correctly in the blueprints (or something in the site creation process). Can you please add this to all of the blueprints?

**Comment by russdanner** [comment]
Hi Jeff,

100% correct.  I think the issue here is that we checked the folder in to Git but it was empty do Git dropped it.

**Comment by jrosler** [comment]
Yea, Gi was thinking that might be the case too.
