### ISSUE TITLE
[engine] GraphQL schema customizer should not allow you to replace top level type

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3501]
## Describe the bug
The GraphQL Schema customizer should not allow you to completely replace a top-level type that's built by the dynamic schema generator.

API Should allow you to test that a type or field exists and get a reference to it.

## To Reproduce
1. Go to create a site based on editorial
2. Create an /scripts/graphql/init.groovy
3. Add the following code

```

def topLevelObj = newFieldDefinition()
  .name('page_page') 
  .description('Doing this replaces the object')
  .type(nonNull(GraphQLString))

// Add the new fields to the top level type
schema.field(topLevelObj)
```
4. Save the script and use GraphiQL schema explorer to that the type has been replaced

## Expected behavior
An exception should be generated in the logs that state that the type already exists.  

A developer should be able to use the API to check if a type or field already exists
A developer should be able to use the API to get an existing type or field and augment it
The following augmentation should be possible
- Set description
- Add fields

### Version
```
Studio Version Number: 3.1.4-SNAPSHOT-c289de
Build Number: c289deefde933b60365f4cb7e49fc8d45a1191ef
```

### OS
Any

### Browser
N/A

**Comment by jdrossl** [comment]
@russdanner please verify and if it is ok assign back to me for updating the docs

**Comment by russdanner** [comment]
Code in ticket now results in 
```
[ERROR] 2019-10-17T10:12:18,622 [pool-43-thread-1] [dazzle] [context.SiteContext] | Error building the GraphQL schema for site 'dazzle'
org.craftercms.engine.exception.ScriptException: No signature of method: init.newFieldDefinition() is applicable for argument types: () values: []
```

**Comment by russdanner** [comment]
Confirme
