### ISSUE TITLE
[docs] Push processor documentation references pull operation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3502]
## Describe the bug
Push processor operations reference pull in parameter descriptions

## Corrections
Add the parameter
localRepoBranch | The branch of the local repo to push.

Update parameter descriptions with the following text
url |   The URL of the remote repository to push to
branch   | The branch of the remote repository to push to

## Additional context
https://github.com/craftercms/deployer/blob/master/src/main/java/org/craftercms/deployer/impl/processors/GitPushProcessor.java

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/853

**Comment by russdanner** [comment]
Confirmed
