### ISSUE TITLE
[studio] Allow configurable DB schema

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3503]
There's a use case where one DB engine instance is used for several Studio schemas. Right now Studio only supports the `crafter` schema name, which is hardcoded in several places, like the `DataSourceInitializerImpl` and the `DefaultDbIntegrityValidatorImpl`. Please make it so the DB schema name can be specified through configuration.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/3511
https://github.com/craftercms/studio/pull/1770
https://github.com/craftercms/commons/pull/190

**Comment by avasquez614** [comment]
@yacdaniel please help with testing this

**Comment by yacdaniel** [comment]
Verified.
