### ISSUE TITLE
[studio-ui] Improve screenshot resolution of blueprints

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3504]
## Describe the bug
The screenshots defined in the `craftercms-plugin.yaml` are using a low-resolution image(because of the old create site). Please update the built-in blueprints and the ones from marketplace. 

## To Reproduce
1. Click `Create Site`
2. In any blueprint click the options icon and then `Details`
3. Check screenshots

## Expected behavior
Screenshots are with a nice resolution

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/66499886-e7a9fe80-ea7d-11e9-93cc-f04b05d36079.png)
![imagen](https://user-images.githubusercontent.com/6722074/66499961-fd1f2880-ea7d-11e9-8c68-0f87a0dd3a54.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1781

**Comment by yacdaniel** [comment]
Much better :tada: thanks @jvega190 
Verified fixed.
