### ISSUE TITLE
[studio-ui] Add "no template required" option for components too

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3505]
Pages offer a no template required check box on form builder so saving doesn't warn you if you haven't selected a template before saving.

Please add same for components.

Use case: SPA components that interact with CMS content types

**Comment by rart** [comment]
Nevermind. Functionality is there. Wasn't showing due to not selecting the right area of the builder.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/video-center-blueprint/pull/69
