### ISSUE TITLE
[studio-ui] Add min & max constraints to numeric input

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3506]
- Add min and max value constraints to numeric input form control.
- Max length doesn't make sense for this control, does it?

**Comment by rart** [comment]
@yacdaniel check merged before testing: https://github.com/craftercms/studio-ui/pull/1347

**Comment by yacdaniel** [comment]
Verified
![imagen](https://user-images.githubusercontent.com/6722074/67332985-0af09700-f4dd-11e9-9808-d983f83f9e22.png)
