### ISSUE TITLE
[studio] Support pretty-printed site names

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3507]
Currently the `site name` is more like a site id. It has quite a few rules and it's used to great extent mostly by the system. 

It'd be lovely if sites can be created with a user-friendly / pretty-printed site name.

For example, I may want to name my site "E-Commerce Portal". Then the site ID can be auto-generated for the user as `e-commerce_portal`. The admin may still manually tweak if desired. 

What's currently called site name should be called otherwise (e.g. site id, site code, site nickname, handle, etc). And the site name would be a readable, pretty string that would get displayed in site listings and it's dashboard, etc to the user base.

**Comment by sumerjabri** [comment]
Closing in support of explicit site id, name and description.
