### ISSUE TITLE
[studio-ui] History dialog "Revert" action doesn't ask for confirmation before executing

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3512]
Revert action should have confirmation before committing. 

Note to UI: Use a dropdown config instead of a dialog/popup.

**Comment by jvega190** [comment]
draft PR https://github.com/craftercms/studio-ui/pull/1354

**Comment by yacdaniel** [comment]
@jvega190  please check this behavior:
When the History dialog is full of versions and you try to revert the last item you will notice that the revert confirmation is displayed under the currently visible screen and might not be noticed by the user.
![HistoryConfirm](https://user-images.githubusercontent.com/6722074/67779759-b5f7d800-fa2a-11e9-9e6e-48287de81c06.gif)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1387

**Comment by jvega190** [comment]
@yacdaniel when more than 5 versions, last 5 will show a `dropup` (dropdown facing up)

**Comment by yacdaniel** [comment]
@jvega190 I can't revert any of the last 5 facing up, browser error:
`TypeError: contentTO is undefined common-api.js:4770:17`

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1397

**Comment by yacdaniel** [comment]
Verified fixed.
