### ISSUE TITLE
[studio][studio-ui] remote_branch parameter is not used when creating a site and push to remote

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3514]
## Describe the bug
`remote_branch` parameter is not used when creating a site and push to remote

## To Reproduce
1. `curl --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE" -H  "accept: application/json" -X POST http://localhost:8080/studio/api/1/services/api/1/site/create.json -d '{  "site_id" : "siteremote123","description" : "My very first site!","blueprint" : "org.craftercms.blueprint.empty", "create_option": "push", "remote_branch": "remote", "remote_username": "crafter-qa", "remote_token": "mytoken", "remote_url": "https://github.com/crafter-qa/craftercmstests2", "authentication_type": "token", "sandbox_branch": "testing", "use_remote": true}'` 
2. Check the repository url, notice that the branch is the one from the sandbox `testing` instead of the `remote_branch` value `remote`

## Expected behavior
The branch to the remote pushed should be from the `remote_branch` parameter in this case `remote` 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by sumerjabri** [comment]
Remove the ability to Create and Push in one shot from the API and impl.

**Comment by sumerjabri** [comment]
@jdrossl this is just remove the push to remote capability during site creation and update the docs.

**Comment by jdrossl** [comment]
@rart we also need to remove the push option from the create site dialog

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1207

**Comment by yacdaniel** [comment]
Verified.
