### ISSUE TITLE
[studio] Please add "type" filtering for get-content-types API

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#3518]
**Is your feature request related to a problem? Please describe.**
Please see ticket: https://github.com/craftercms/craftercms/issues/3477 for a better context.
Ui needs to get specific content type list depending on type porperty (component or page). 

**Describe the solution you'd like**
We need a new api that respond with specific list of content types, or we can update get-content-types to receive a parameter named filter and respond with specific component list.

**Additional context**
https://github.com/craftercms/craftercms/issues/3477

**Comment by sumerjabri** [comment]
Closing since we've gone in a different direction.
