### ISSUE TITLE
[studio-ui] Double crafterSite cookie appears after creating site

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3526]
## Describe the bug
When using a Studio URL that has a subdomain, e.g `http://authoring.craftercms.local:8080/studio`, and creating a site, 2 `crafterSite` cookies with a slightly different domain are set, causing issues while trying to navigate through Studio

## To Reproduce
1. In your `/etc/hosts` add a host with a subdomain that points to 127.0.0.1 (like `127.0.0.1       authoring.craftercms.local`).
2. Go to the Studio URL using the new host and create a site
3. After creating the site, if you check the current cookies (in the Developer Tools pane in case of Chrome), there a 2 `crafterSite` cookies: one for the `.authoring.craftercms.local` host and one for `authoring.craftercms.local` (see screenshot).
4. If you go back to the site list and select another site, you'll be redirected to the created site preview instead of the preview of the site you selected.
5. If you delete both cookies and go back to the site list and select another site, then only the `.authoring.craftercms.local` host cookie will be set and the correct preview is shown and you can navigate normally without issues. So it seems the other cookie is only set on site creation.

## Expected behavior
Only one `crafterSite` cookie (the `.authoring.craftercms.local` host one) should be set.

## Screenshots
![Screenshot from 2019-10-11 19-25-13](https://user-images.githubusercontent.com/1598884/66690525-91e07c80-ec5e-11e9-804a-15897b210d94.png)

**Comment by rart** [comment]
@vestrada check CreateSiteDialog.tsx:448.

The set cookie call should be made equivalent to the prior one by adding domain.

Something like...
```
Cookies.set('crafterSite', site.site_id, {
  domain: location.hostname.includes('.') ? 'domain=' + location.hostname : '',
  path: '/'
});
```

**Comment by avasquez614** [comment]
Verified
