### ISSUE TITLE
[studio-ui] Preview Persona Images do not Work in C3

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#353]
URL to content has changed:
 Correct UI to request content at new URL

NEW URL FORMAT/EXAMPLE
http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/config/studio/targeting/personas/thumbs/anon.jpg&site=test2

**Comment by dejan-brkic** [comment]
Path is wrong. Repository structure is changed in 3.0.0

**Comment by dejan-brkic** [comment]
Path is wrong. Repository structure has changed in 3.0.0

**Comment by russdanner** [comment]
Ok how should it be changed so this can be assigned to a UI person?

**Comment by dejan-brkic** [comment]
Something like this:
http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?site=test&path=/config/studio/targeting/personas/thumbs/anon.jpg
You can find file on disk and verify path relative to sandbox folder. (if example has wrong param)

**Comment by russdanner** [comment]
I tried these without any luck:
* http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/sites/test2/sandbox/config/studio/targeting/personas/thumbs/anon.jpg

* http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/test2/sandbox/config/studio/targeting/personas/thumbs/anon.jpg

* http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/config/studio/targeting/personas/thumbs/anon.jpg

* http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/targeting/personas/thumbs/anon.jpg

**Comment by dejan-brkic** [comment]
missing site param in url in all of them

**Comment by russdanner** [comment]
good point. let me see if that works

**Comment by russdanner** [comment]
The following URL Works
http://localhost:8080/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/config/studio/targeting/personas/thumbs/anon.jpg&site=test2

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/187
