### ISSUE TITLE
[studio-ui] Parameter of type password should have a option to have hidden/visible text

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3531]
## Describe the bug
When a parameter of type `PASSWORD` is returned in the `Create Site` dialog, the UI should show an input with the capability to show/hide the text, like the passwords. 

## To Reproduce
1. Click `Create Site` button
2. Go to `Marketplace` tab
3. Select the `commercetools Blueprint`

## Expected behavior
The parameter `Client  Secret` is of type `Password`, it should have the capability of show/hide the text, like the password/token when using a git remote.
Also the parameters name/values should be displayed in the `Review` page

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/66841583-267d0000-ef27-11e9-8098-1f06121369d7.png)

Parameters in Create Site dialog
![imagen](https://user-images.githubusercontent.com/6722074/66841763-680dab00-ef27-11e9-983c-e8521c07feb5.png)

Parameters name/value missing in the Review page
![imagen](https://user-images.githubusercontent.com/6722074/66841824-79ef4e00-ef27-11e9-8315-7d293514f3f4.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by yacdaniel** [comment]
@yureii00  When I have parameters defined in the BP I can see them in the Review page(commerce blueprint for example)
![imagen](https://user-images.githubusercontent.com/6722074/67294098-9dc01000-f4a2-11e9-8efc-8c524deb2cd2.png)

And for any of the others BP in the Public Marketplace, they do no have parameters but I'm seeing the Blueprint Parameters in the Review Page
![imagen](https://user-images.githubusercontent.com/6722074/67295162-ff34ae80-f4a3-11e9-9483-566da77038c2.png)

If there are no parameters in the BP, the `Review Page` should not contain the `Blueprint Parameters`

**Comment by yureii00** [comment]
Done, 
PR: https://github.com/craftercms/studio-ui/pull/1356

**Comment by yacdaniel** [comment]
Verified.
