### ISSUE TITLE
[craftercms] Backup doesn't work in Windows

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3534]
Backup in Authoring 3.0.26 in Windows is not working, there's no error in the output but the zip is empty. It might be a problem with the `craftercms-utils` zipping tool, so it might not work in Unix based systems either.

**Comment by jdrossl** [comment]
I was not able to reproduce the issue, `backup` & `restore` work as expected in Windows. I also was able to unzip the backup file in macOS & Ubuntu.

**Comment by avasquez614** [comment]
I'll taste again as soon as I can, thanks.
