### ISSUE TITLE
[studio-iu] Create Site Dialog Polish

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3535]
**Is your feature request related to a problem? Please describe.**
 Change the current design of the Blueprint cards

**Describe the solution you'd like**

- I fear the big Details button may obscure the clickability of the whole card to select and perceive as if they are forced to see the details before actually using it; hence the addition of the Use button.
- Clicking the white area of the card would still select that blueprint for use. Same as the “Use” button.
- I’m gonna assume people clicking on the images are looking to make them bigger to see more comfy so, clicking the picture(s) takes you to the details view with the clicked picture preselected (sorry, you’re smart, you’ll figure it out :sonrisa:). Add a semi-transparent fav on hovering the image with an expand icon.
- More button takes you to details view.
- Notice the separation of the carousel dots from the image and the coloured container of the dots. That’ll cure us from different images making dots barely visible.

**Additional context**
![colour-scheme](https://user-images.githubusercontent.com/10813283/66929812-e7b37c80-eff0-11e9-80b0-d963f23f07c1.png)

**Comment by yacdaniel** [comment]
Verified.
