### ISSUE TITLE
[studio-ui] Item-Selector with File Upload and File Browse data sources fail on add action

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3537]
## Describe the bug
Add item action fails / is buggy when using item selector in conjunction with the file upload and file browse data source.
* Dialogs do not close and item is often not added to the item selector

https://www.loom.com/share/40534bdf558f43ed9ed85225231bdda6

## To Reproduce
1. Go to Create a form with an item selector and an a file browse data source
2. Try to browse for and add an item

## Expected behavior
* When a user checks and item and clicks add and close or add item the item should be added and the dialog should close.

## Screenshots
https://www.loom.com/share/40534bdf558f43ed9ed85225231bdda6

## Logs
N/A

### Version
```Studio Version Number: 3.1.4-SNAPSHOT-31df36
Build Number: 31df362f307966926633b458806695069f844f77
Build Date/Time: 10-15-2019 13:54:42 -0400```

### OS
Any

### Browser
Any

**Comment by vestrada** [comment]
I also fixed:
CMIS: File, image, video (Upload and Repo), 
Webdav: File, image, video  (Upload and Repo), 
S3: File, image, video  (Upload and Repo).

**Comment by yacdaniel** [comment]
Verified fixed. `Add and Close` work as expected and when you right-click in the browse folder and use the upload the browse window is refreshed with the new asset.
