### ISSUE TITLE
[studio-ui] uncommited work in sandbox triggers conflict resolution state on remote repositories tool

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3539]
## Describe the bug
When a developer is working locally with Studio they  may have uncommitted work in the sandbox.  When the developer goes to the remote repositories screen it show a conflicted state with no details (there is not conflict)

## To Reproduce
1. Go to create a project based on a remote
2. add uncommitted work to the sandbox
3. View the remote repositories screen

## Expected behavior
If there is no conflict, do not show the conflict resolution tool.

A useful enhancement would be to list uncommitted work or display the git status details.

## Screenshots
<img width="1429" alt="Screen Shot 2019-10-16 at 12 05 15 PM" src="https://user-images.githubusercontent.com/169432/66937619-c44afa80-f00d-11e9-81fa-f876d09aad46.png">

## Logs
N/A

### Version
Studio Version Number: 3.1.4-SNAPSHOT-31df36
Build Number: 31df362f307966926633b458806695069f844f77
Build Date/Time: 10-15-2019 13:54:42 -0400

### OS
Any

### Browser
Any

**Comment by sumerjabri** [comment]
@vestrada @rart please see the API response below:
![Screenshot_20191016_210845](https://user-images.githubusercontent.com/3931908/66951265-fd906400-f027-11e9-8192-40fa5e37b728.png)
![Screenshot_20191016_210642](https://user-images.githubusercontent.com/3931908/66951266-fd906400-f027-11e9-9cdd-d1ab0088dbd6.png)

The API response seems to have enough information for you to do this.

If the flag `clean` is `false`, then something is not right and you need to alert the user.
If the `conflicting` > 0, then we have conflicts and you do what you do today.
If the `uncommittedChanges` > 0, then you have files that are uncommitted and you just inform the user that the files listed there are not committed.

Note it's possible to have both conditions, and the UI will show both.

@rart please design (lightweight/quick)
@vestrada please implement.

**Comment by rart** [comment]
@vestrada same style of message as the “disabled while conflicts” message, only that the repo grid should show up below.

“(i) The repo has uncommitted changes.”

**Comment by vestrada** [comment]
I was checking the issue and I noticed that the issue is that if you edit a file that is already on git, the api will return the file as "uncommittedChanges". But if you add manually a new file, the api will return an empty array, or it wont recognize the new file. 

@dejan-brkic , please update the api to return files that are manually added.

**Comment by dejan-brkic** [comment]
Per discussion with @sumerjabri, the latest request (use case) opens up more possibilities for additional features/use cases.

**Comment by russdanner** [comment]
This state is detectable.  There's no pending commit and nothing to resolve.  We do not need to give a user interface to resolve these issues at this time.  Unstaged files are added manually via the CLI so they can be addressed that way as well.  

For now we just want the UI to understand and report the state.  
- If there is no pending commit: Do not show the resolve buttons (they don't do anything) and do not show the Pending header with an empty list.
- If there are unstaged files, simply announce that there are unstaged files: "There are unstaged files in your repository."

<img width="1275" alt="Screen Shot 2019-10-22 at 2 17 03 PM" src="https://user-images.githubusercontent.com/169432/67317023-78012e00-f4d7-11e9-84ec-9f22e8bbf865.png">

**Comment by russdanner** [comment]
Confirmed
