### ISSUE TITLE
[studio] Add Embedded Content data source to existing sites

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3544]
Upgrade Manager should add the Embedded Content and shared content data sources to the Site Config Tools configuration file.

Upgraded site does not have Embedded Content data source available
https://www.loom.com/share/66548df68f114e90a6f5c6166d9c884b

### Version
Studio Version Number: 3.1.4-SNAPSHOT-31df36
Build Number: 31df362f307966926633b458806695069f844f77
Build Date/Time: 10-15-2019 13:54:42 -0400

### OS
Any

### Browser
Any

**Comment by sumerjabri** [comment]
@russdanner this was completed recently, please rebuild and retest. I tested it again, and it's working for me.

**Comment by russdanner** [comment]
Confirmed
