### ISSUE TITLE
[studio-ui] Page components should support drag-drop of embedded components

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3545]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to use embedded components via the form engine (Item Selector+Embedded Component Data Source)

It's not possible to drag and drop an embedded component

**Describe the solution you'd like**
Update the Preview Components configuration structure to support embedded components
https://www.loom.com/share/6a084faa04cb48deb28e7b1d130a35db

The current Structure Per Component is:
```
<component>
   <label>Five Col Layout</label> 
   <type>/plugins/bootstrap-layouts/5-col</type>
   <path>/site/components/page</path>
</component>
```

A User can also browse for Shared Components if a library is defined
```
<config>
   ...
   <browse>
         <label>Common</label>
         <path>/site/components/common</path>
   </browse>
   ...
</config>
```

IF not path is defined, assume the component is embedded.  

**Describe alternatives you've considered**
Add an additional field to indicate that the item is embedded to the component structure.

**Comment by russdanner** [comment]
I've configured the component panel as specified and confirmed that the data source is embedded but am not able to drop the component in the editorial blueprint. 
https://www.loom.com/share/8cbcd1bdb117418097494040b645e004

**Comment by yureii00** [comment]
Hi @russdanner  can you try to uncomment the path and let it empty

**Comment by yureii00** [comment]
Looks like when the path is not defined the element is created as "data-studio-component-path="undefined", I need to add a validation to create it empty if path is not defined

**Comment by russdanner** [comment]
Confirmed
