### ISSUE TITLE
[studio-ui] - Input fields in create dialog is not responsive

### ISSUE THREAD

**Issue by vladimirverbitski** [craftercms/craftercms#3546]
## Describe the bug
The input field is crawls out of the block border if we increasing the length of the string.

## Expected behavior
I think it is better to make fix length of the input fields.

## Screenshots
![crafter-bug](https://user-images.githubusercontent.com/16860815/66977831-3e8c8500-f0c9-11e9-9e0c-644674bb463e.png)

### Version
v3.1.0

### Browser
Chrome

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1406

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/68601188-763ce180-0469-11ea-9114-0c39d88f9b38.png)

@vladimirverbitski the upcoming release of `Crafter CMS 3.1.4` will have this fixed, thanks!
