### ISSUE TITLE
[videocenter] Video Center preview doesn't work through HTTPs

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3548]
## Describe the bug
When using HTTPs, Video Center preview is empty. A bunch of JS HTTPs related errors appear in the browser console

## To Reproduce
1. Using HTTPs, go to Studio in the browser. 
2. Login and create a site based on VC.

You should see a completely empty preview. If you open Dev Tools and go to the Console, you'll see a bunch of `Mixed Content: The page at 'https://HOST/studio/preview/#/?page=/&site=vc' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://HOST/api/1/site/content_store/descriptor.json?url=%2Fsite%2Fwebsite%2Fcrafter-level-descriptor.level.xml&crafterSite=vc'. This request has been blocked; the content must be served over HTTPS.`

## Expected behavior
Preview should work

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/71

**Comment by avasquez614** [comment]
Verified
