### ISSUE TITLE
Version history doesn't display edited time correctly

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#355]
Alfresco Repo

1) Create a content
2) Edit the content
3) Select the item and view history

The last edited time should be 4:16PM but it shows 9:16 PM
![screen shot 2017-01-10 at 4 16 55 pm](https://cloud.githubusercontent.com/assets/4325885/21825114/5ea33f7c-d750-11e6-9c8c-3c5d520f53dc.png)

While Recent Activity displays a correct time.

![screen shot 2017-01-10 at 4 17 24 pm](https://cloud.githubusercontent.com/assets/4325885/21825126/6cf1cc88-d750-11e6-9859-65800d2b105a.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/186
