### ISSUE TITLE
[engine] Download from s3 does not respect endpoint configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3550]
## Describe the bug
`/remote-assets/s3/` download endpoint ignores the endpoint configuration in the profile.

Root cause 
There are multiple places in across crafter's code base where we init the S3 Client based on the profile settings:

Example from Studio (uses endpoint)
`studio/src/main/java/org/craftercms/studio/impl/v2/service/aws/s3/AwsS3ServiceImpl.java`

Example from Commons (ignores endpoint)
`src/main/java/org/craftercms/commons/file/stores/S3Utils.java `

The s3Utils.java is what cases the issue in this ticket.  We should consider consolidating how the clients are built/configured.

## To Reproduce
1. Go to Configure an AWS profile with an non standard endpoint (either a test aws endpoint or something like `https://min.io/`
2. Add an asset to S3 bucket
3. Attempt to download it via the URL
Example: `http://localhost:8080/remote-assets/s3/s3-test/test/test/photo.png`
4. Note the download fails

## Expected behavior
Asset should download

## Logs
`Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: test01.s3.amazonaws.com
`
### Version
```
Studio Version Number: 3.1.4-SNAPSHOT-31df36
Build Number: 31df362f307966926633b458806695069f844f77
Build Date/Time: 10-15-2019 13:54:42 -0400
```

### OS
Any

### Browser
Any

**Comment by avasquez614** [comment]
@jdrossl if it's possible let's try to use a single set of classes defined in commons

**Comment by russdanner** [comment]
Confirmed
