### ISSUE TITLE
[studio-ui] Cursor should be on "Site ID" in the "Create Site" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3552]
## Describe the bug
When creating a site using the `Create Site` button, once you get to the screen where the user needs to enter a `Site ID`, the cursor is not on any of the fields in the screen

## To Reproduce
1. From the `Main Menu` -> `Sites`, click on the `Create Site` button
2. Select a bp, say `Website Editorial`
3. Notice that there is no cursor visible in the dialog
![Screen Shot 2019-10-17 at 10 43 21 AM](https://user-images.githubusercontent.com/25483966/67105206-541bb080-f196-11e9-91fc-a06b351df6a7.png)

## Expected behavior
Cursor should be on "Site ID" in the "Create Site" dialog.  Pressing tab should also cycle through the fields and buttons in the dialog

## Screenshots
Here's a short clip:
https://www.loom.com/share/2ad4ef942e65469a9b964b34430fef81

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-c048a5
Build Number: c048a579ba96fb063f515ea90451972fb5e100e9
Build Date/Time: 10-17-2019 10:41:07 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
Verified fixed.
