### ISSUE TITLE
[studio] APIs to support "Publishing status dashboard" are not working as expected

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3553]
## Describe the bug
/publish/packages optional parameters are not working "environment", "path", "state"

## To Reproduce
Send a api call to `.../studio/api/2/publish/packages?siteId=editorial&state=CANCELLED`

## Expected behavior
should return packages with status on cancelled

### Version
Crafter 3.1.4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1792

**Comment by yureii00** [comment]
verified
