### ISSUE TITLE
[studio-ui] When session expires, preview shows a console error

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3559]
## Describe the bug

When watching preview directly (guest without host), if the session expires guest still loads fine but a browser console error shows up until logging back into authoring

The error seems to be related to loading the overlayhook. When there's no session, it 302s and seems to cause a HTTP redirect or similar to /studio.

## To Reproduce
1. Go to a site which runs the @studio.toolSupport macro (or manually add the overlayhook import)
2. Log out of studio (or let the session expire)
3. Open the browser console

## Expected behavior
No errors appear in the console.

## Solution Approach
A few options:
- Fix the toolSupport macro so it doesn't write the scripts if there's no session
- Return a blank file for overlayhook
- Analyse if those scripts should really be protected by user authentication and if not make them public

## Screenshots
<img width="730" alt="Screen Shot 2019-10-22 at 2 19 12 PM" src="https://user-images.githubusercontent.com/3928341/67285044-1c36a500-f4d7-11e9-9b70-354e3f902f8d.png">

**Comment by rart** [comment]
Furthermore, even when session is valid, when different domains are being used for studio vs preview, this is also an issue.

**Comment by sumerjabri** [comment]
Not an issue anymore.
