### ISSUE TITLE
No version is created when the content doesn't have cm:versionable aspect 

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#356]
Env: Alfresco Repo

The system has many contents upgraded from an old version, however when editing these contents the system doesn't create any versions while changes are still applied. This is due to missing cm:versionable aspect. It's possible that contents could be dropped in manually specially since we are missing the bulk import feature, that the system should add cm:versionable aspect if the content doesn't have it before creating a version.

**Comment by russdanner** [comment]
Isn't the only way this scenario comes up is on an import of some kind or a user going through the back-end?
