### ISSUE TITLE
[studio-ui] Add description to git tile on create site dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3561]
Add short description to the git tile to help people understand this option better.

`Create a new site based on a Crafter CMS project in an existing, remote git repository.`

<img width="1440" alt="Screen Shot 2019-10-22 at 11 42 30 AM" src="https://user-images.githubusercontent.com/169432/67304019-3ebdc380-f4c1-11e9-87bd-8fffcc2b7353.png">

**Comment by yacdaniel** [comment]
Verified.
![imagen](https://user-images.githubusercontent.com/6722074/67317685-a545e000-f4c7-11e9-8d25-5f23346d79c6.png)
