### ISSUE TITLE
[studio-ui] Add UI support for unstaged files in the repository admin tool

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3563]
**Is your feature request related to a problem? Please describe.**
The Repositories admin tool does not allow users to deal with unstaged files via the UI

An unstaged file is a file that is created in the repository sandbox but has not had a git add operation applied to it.

**Describe the solution you'd like**
Support the ability to remove, stage and commit staged files that are currently unstaged.

**Describe alternatives you've considered**

**Additional context**
https://github.com/craftercms/craftercms/issues/3539

**Comment by sumerjabri** [comment]
Minimal conflict resolution was added to the UI.
