### ISSUE TITLE
[studio] Support per-user config overrides

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3566]
Across the different XML config files, support a `user-settings` tag which would enable personalized settings per user in each site.

Configuration would then become a cascade of overrides
- System defaults
- Site overrides
- User overrides

For example:
```xml
<environment-config>
  <version>2</version>
  <preview-server-url>http://localhost:8080</preview-server-url>
  <preview-engine-server-url>http://localhost:8080</preview-engine-server-url>
  <graphql-server-url>http://localhost:8080</graphql-server-url>
  <authoring-server-url>http://localhost:8080/studio</authoring-server-url>
  <live-server-url>http://localhost:9080/?crafterSite={siteName}</live-server-url>
  
  <overrides username="roy">
    <preview-server-url>http://localhost:3000</preview-server-url>
  </overrides>
  
  <open-sidebar>false</open-sidebar>
  <publishing-targets>
    <target>
      <repo-branch-name>live</repo-branch-name>
      <display-label>Live</display-label>
    </target>
  </publishing-targets>
</environment-config>
```

Inline with the thought of consolidating config into a central location, instead of per-xml, there could be a single config file (yaml, xml, json, what ever it may be) where all the overrides are set for the different configs.

**Note/Thought** 
Here, overrides are presented per username. Are there instances where the driver of the override could be something other than the user? (e.g. host, environment, geographical, time)

**Comment by sumerjabri** [comment]
Addressed via Roles in the new `ui.xml`. We will not pursue per specific user, we will only support roles.
