### ISSUE TITLE
[studio-ui] ICE group is not working with embedded components

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3569]
## Describe the bug
When an ICE tag is set with `iceGroup` for an embedded component the forms still shows all fields in the component

```
<@studio.iceAttr component=component iceGroup="myGroup"/>>
```

## To Reproduce
1. Create an embedded component with an `iceGroup`
2. Add ice tags using the `iceGroup`
3. Click on the pencil in preview

## Expected behavior
The form should only show the fields that belong to the given `iceGroup`

### Version
3.1.4-SNAPSHOT

**Comment by yacdaniel** [comment]
Verified fixed.
