### ISSUE TITLE
[search] Explicitly clear all scroll requests used during indexing

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3570]
Elasticsearch classes using the scroll API should clean the request when done to prevent issues:

```request [POST http://localhost:9201/doingbetter-authoring/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512] returned 1 warnings: [299 Elasticsearch-6.6.0-a9861f4 "Trying to create more than 500 scroll contexts will not be allowed in the next major version by default. You can change the  [search.max_open_scroll_context] setting to use a greater default value or lower the number of scrolls that you need to run in parallel." "Wed, 23 Oct 2019 16:38:34 GMT"]```

**Comment by jdrossl** [comment]
@avasquez614 please verify

**Comment by avasquez614** [comment]
Verified
