### ISSUE TITLE
[studio][studio-ui] Update new API parameter names

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3572]
The new API for `/sites/create_site_from_marketplace` should use `camelCase` for all parameters.

**Comment by jdrossl** [comment]
@rart Assigning to you for the create site dialog updates

**Comment by yureii00** [comment]
Done.
PR: https://github.com/craftercms/studio-ui/pull/1373

**Comment by yacdaniel** [comment]
Verified new parameters.
