### ISSUE TITLE
[studio-ui] Fix label for fileManager property in TinyMCE 5 control

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3573]
## Describe the bug
Fix label for fileManager property in TinyMCE 5 control

## To Reproduce
1. Create a site from Editorial blueprint
2. Open the `Page - Home` Content Type
3. Select the `Hero Title` control
4. View the properties

## Expected behavior
The property `fileManager` should be `File Manager` 

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/67497147-cd098500-f63a-11e9-9d4f-422e1696730b.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1371

**Comment by yacdaniel** [comment]
Verified fixed.
