### ISSUE TITLE
[studio-ui] In login session expires, the password input is not editable if create site dialog is open

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3574]
## Describe the bug
When the create site dialog is open and the login session expires, the password input inside the login dialog is not editable.

## To Reproduce
1. Open create site dialog
2. Wait until session expires.

## Expected behavior
Password input should be editable

### Version
Crafter 3.1.4

**Comment by yacdaniel** [comment]
Verified fixed.
