### ISSUE TITLE
[studio] API 2 publish/package does not return comment(submission comment) 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3575]
## Describe the bug
`http://localhost:8080/studio/api/2/publish/packages?siteId=editorial` is returning null for the `comment` property. 

## To Reproduce
1. Edit a Page and Request Publish, add a `Submission Comment`
2. Call  `/api/2publish/packages`

## Expected behavior
The property `comment` contains the value of the `Submission Comment` from the Publish Request

## Screenshots
Notice that the value of `comment` is null.
![image](https://user-images.githubusercontent.com/6722074/67512334-d5bb8480-f655-11e9-83ef-339953f91072.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
N/A

### Browser
N/A

## Additional context
The API `publish/packages` returns the expected `comment` 
`GET "http://localhost:8080/studio/api/2/publish/package?siteId=ed2&packageId=02835fde-0626-441c-95f2-9c3784a3449f"`
![image](https://user-images.githubusercontent.com/6722074/67512542-419ded00-f656-11e9-8f97-06096e252649.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1805

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/67778693-30bff380-fa29-11e9-9133-fd96692fd07c.png)
