### ISSUE TITLE
[studio-ui] Two forms are opened when clicking on a pencil on an embedded component

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3576]
## Describe the bug
When a pencil is added to an embedded component, when an author clicks on the pencil for the embedded component, there are two forms opened, the form for the parent and the form for the embedded component the author wants to edit.

## To Reproduce
1. Create a site using the Website Editorial bp.  Notice when you turn on ICE, there are no pencils for each of the feature in the features (Erat Lacinia) section of the home page
![Screen Shot 2019-10-24 at 2 00 44 PM](https://user-images.githubusercontent.com/25483966/67513556-0c4eca80-f669-11e9-8813-9fb68574788a.png)

2. The features are embedded components.  We will now add pencils to them by opening the file `/templates/web/components/feature.ftl`.  On the second line, add in `<@studio.iceAttr component=contentModel/>` it so it looks like:
```
<article <@studio.iceAttr component=contentModel/> <@studio.componentAttr path=contentModel.storeUrl />>
```
Save your changes.
3. You should now see pencils on each of the features
![Screen Shot 2019-10-24 at 2 20 43 PM](https://user-images.githubusercontent.com/25483966/67513838-ac0c5880-f669-11e9-82d4-68aaece3b852.png)

4. Click on the pencil on one of the features, close the form for the feature you just opened, and notice that the form for the home page is also open underneath the feature form.  If you look closely after clicking on the pencil of the feature, you'll notice that there are two forms opened
![Untitled](https://user-images.githubusercontent.com/25483966/67514909-a152c300-f66b-11e9-843b-fb9a888f1b02.png)

## Expected behavior
Only the form for the embedded component, whose pencil the user clicked, should be open. (Or is this the expected behavior for embedded components?)

## Screenshots
Here's a short clip showing the behavior:
https://www.loom.com/share/2a5fea0705be46838cb37b2351996b93

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-41bfcd
Build Number: 41bfcd549c1b0c3428abe84d5a0df4a7ade4380e
Build Date/Time: 10-24-2019 13:30:46 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yureii00** [comment]
Done.
PR: https://github.com/craftercms/studio-ui/pull/1374

**Comment by yacdaniel** [comment]
Verified fixed.
