### ISSUE TITLE
[studio] /studio/api/2/monitoring API enhancement

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3577]
`/studio/api/2/monitoring` should be enhanced to use some type of API token or keyword

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss design.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/commons/pull/194
https://github.com/craftercms/deployer/pull/181
https://github.com/craftercms/engine/pull/326
https://github.com/craftercms/search/pull/190
https://github.com/craftercms/studio/pull/1839

**Comment by avasquez614** [comment]
@dejan-brkic I talked with @sumerjabri and since there's another ticket related to these tokens, https://github.com/craftercms/craftercms/issues/3578, we should change the word `monitoring token` to `management token`. Please make the appropriate changes to the pull requests. I'm also assigning you the other ticket.

**Comment by avasquez614** [comment]
Verified
