### ISSUE TITLE
[studio] Wrong Publish API2 response  when siteId does not exist.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3580]
## Describe the bug
Wrong Publish API2 response  when siteId does not exist.

## To Reproduce
1. Use a no existing `siteId` in the calls `GET /publish/packages`,  `GET /publish/package` and  `GET /publish/cancel` They are returning  HTTP code 403 with the response:

```
{
  "response": {
    "code": 2001,
    "message": "Unauthorized",
    "remedialAction": "You don't have permission to perform this task, please contact your administrator",
    "documentationUrl": ""
  }
}
```

## Expected behavior
1. It should return HTTP code 404 NotFound with an appropriate ApiReponse code?

## Screenshots
N/A

## Logs
https://gist.github.com/yacdaniel/67a8041b8497967ec1994c18eb051a3d

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1806

**Comment by yacdaniel** [comment]
Verified fixed.
```
< HTTP/1.1 404 
{
  "response": {
    "code": 5000,
    "message": "Project not found",
    "remedialAction": "Check if you sent in the right Project Id",
    "documentationUrl": ""
  }
}
```
