### ISSUE TITLE
[studio-ui] Clicking on "Save draft" after an image upload blocks further uploads in a component

### ISSUE THREAD

**Issue by T0P** [craftercms/craftercms#3581]
## Describe the bug
If you want to upload some images as part of a slider component, a click on the "Save draft" button in the meantime, blocks the whole content editing. 
The bug only occurs if a component is edited directly and not as part of a page.

also see: https://github.com/craftercms/craftercms/issues/3184

## To Reproduce
1. Login as admin
2. Create a new site based on Video Center Blueprint.
3. Open the preview
4. Go to "components -> sliders -> Home Slider" 
5. Click on "Edit"
6. Replace a background image
7. Click on "Save Draft"
8. Replace an another background image

Then the further editing is blocked (see the grey overlay).

## Expected behavior
An image upload after a click on "Save Draft" in a component shouldn't block the content editing.

## Screenshot
![Auswahl_019](https://user-images.githubusercontent.com/1247903/67577706-4ee3d600-f741-11e9-8d59-8325771cb135.png)

### Version
Crafter CMS 3.1.3 Community Edition without modifications
Video Center Blueprint

### OS
Fedora Linux 30

### Browser
Firefox 69.0.3
also occured in Google Chrome

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1370

**Comment by sumerjabri** [comment]
@jvega190 assign to @yacdaniel for validation when PR is merged.

**Comment by sumerjabri** [comment]
@yacdaniel please validate.

**Comment by yacdaniel** [comment]
Verified fixed.
@T0P this should be fixed in the next release `Crafter CMS v3.1.4` 
The fix is preatty easy if you want to try it in your current installation:
- Edit the 1file `crafter-authoring/bin/apache-tomcat/webapps/studio/default-site/static-assets/components/cstudio-forms/forms-engine.js` and change from `dialogEl.dialog.hide();`  to `dialogEl.dialog.destroy();`
