### ISSUE TITLE
[commercetools-blueprint] Variants of products are not shown when the country is German

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3583]
## Describe the bug
 Variants of products are not shown when the country is German

## To Reproduce
1. Create a site from the commercetools-blueprint in the Marketplace
2. Go to the `Catalog` and select any product
3. Click the `Select` dropdown
4. The select is with empty values
5. Change the country to USA
6. Check the `Select` now contains the values.

## Expected behavior
The `Select` in a product should contians visible values when `German` is selected. 

## Screenshots
German empty values
![image](https://user-images.githubusercontent.com/6722074/67585964-cd268500-f70d-11e9-9127-b9734df30925.png)

USA with values
![image](https://user-images.githubusercontent.com/6722074/67585997-e0395500-f70d-11e9-925b-e7cabd8af7c6.png)

## Logs
N/A

### Version
Studio `3.1.4-SNAPSHOT`
ecommerce-blueprint `1.0.5` 

### OS
Linux

### Browser
Chrome/Firefox

## Additional context
N/A

**Comment by sumerjabri** [comment]
@yacdaniel the German store and the American store are not the same catalogs... That's how it is on commercetools.
