### ISSUE TITLE
[vcbp] Crafter Video Center Marketplace Blueprint's Video Player Full Screen Issue (on iPhoneX) 

### ISSUE THREAD

**Issue by aelnattar** [craftercms/craftercms#3587]
Hi,

Steps to reproduce:
1- Use Crafter Video Center Marketplace Blueprint to create a Video Center site
2- Navigate to that site's Preview inside of Studio using an iPhoneX
3- Pick any video to watch
4- Try to touch the maximize icon

Expected behavior = Video maximizes

Actual behavior = Nothing happens.

Note: see screenshot for detail on which icon is not touchable in the scenario described above.
<img width="1346" alt="Screen Shot 2019-10-25 at 1 46 37 PM" src="https://user-images.githubusercontent.com/36507927/67599703-9ae14b80-f73e-11e9-95bb-8b98a5938bbc.png">

**Comment by jvega190** [comment]
https://github.com/craftercms/video-center-blueprint/pull/73

**Comment by jvega190** [comment]
@yacdaniel thanks, please let me know if you need something

**Comment by sumerjabri** [comment]
Verified fixed on iPhone X running Safari
![image](https://user-images.githubusercontent.com/3931908/68618703-ef532d80-0497-11ea-97bf-004782760795.png)
