### ISSUE TITLE
[docker] Please add an overview to docker images in Docker Hub

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3588]
**Is your feature request related to a problem? Please describe.**
There is no overview for our docker images in Docker Hub

<img width="1174" alt="Screen Shot 2019-10-25 at 4 47 39 PM" src="https://user-images.githubusercontent.com/25483966/67603817-f237e980-f747-11e9-8a3a-2c43de8ed179.png">

**Describe the solution you'd like**
Add an overview to all our docker images in Docker Hub, for example, for our authoring_tomcat image, maybe put some quick instructions on how to use the image or put in a link to our docs on how to use the image and get started on using Crafter CMS, or add something about Crafter CMS, links on how to reach us, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by dokuboyejo** [comment]
:+1:  This is essential and would be valuable

**Comment by sumerjabri** [comment]
Updates will be reflected with the next build/publish of the images.
