### ISSUE TITLE
[studio] Create site operation with orphan option set should remove remote after creation 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3589]
## Describe the bug
When a user creates a site from a blueprint, the marketplace or from a remote with the orphan option set to true the origin remote should be removed once the site is created.

It currently remains configured after the create operation.

## To Reproduce
1. Go to create site from marketplace
2. Go to remotes panel in site Config
3. Note remote named origin is present

## Expected behavior
Any site created with the orphan option set to true should have it's remote removed on completion of the create process.

### Version
```
Studio Version Number: 3.1.4-SNAPSHOT-bca2af
Build Number: bca2af8ec32c2cd9e2daeb645ef3d1955934945c
Build Date/Time: 10-28-2019 10:10:04 -0400```

### OS
Any

### Browser
All

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1813

**Comment by russdanner** [comment]
confirmed
