### ISSUE TITLE
On some cases the Collapse Button of a form never allows to Resize

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#359]
In some cases the Collapse button of a form never changes to the "resize" , this means that under certain  conditions the classes of the collapse/resize is never change, presumably due a container size.

**Comment by vestrada** [comment]
Hi!

I tested this issue in all major browsers (chrome, ff, safari, IE11), also I tested it on my local, using alfresco and author url, but I still can't reproduce this issue.
