### ISSUE TITLE
[studio-ui] Encapsulate Require.js in Studio's ICE support

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3593]
## Describe the bug
The require.js library for Studio's in-context editing support has conflicts with host site's versions of require.JS from time to time which causes issues loading in-context editing controls.

## Expected behavior
Fully encapsulate require.js so it cannot conflict with the host's libraries.

### Version
Studio Version Number: 3.1.4-SNAPSHOT-bca2af
Build Number: bca2af8ec32c2cd9e2daeb645ef3d1955934945c
Build Date/Time: 10-28-2019 10:10:04 -0400

### OS
All

### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1394

**Comment by russdanner** [comment]
This works for my test case.  We're discussing how we may be able to test this further.

**Comment by russdanner** [comment]
Confirmed. Code now users crafterRequire reference
