### ISSUE TITLE
[studio-ui] Display character limit for group display name when creating group

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3596]
## Describe the bug
The dialog does not specify a limit for the number of characters allowed for the display name when creating a new group.

## To Reproduce
1. From the `Main Menu` click on `Groups`
2. Click on the `New Group` button
3. Fill in the `Display Name` field with more than 32 characters, notice that the dialog does not warn the user about the max number of characters allowed
![Screen Shot 2019-10-29 at 10 54 06 AM](https://user-images.githubusercontent.com/25483966/67780885-17c13d80-fa3d-11e9-9138-38c5c49254d2.png)
4. Click on the `Create` button.  The group is created and listed:
![Screen Shot 2019-10-29 at 10 54 28 AM](https://user-images.githubusercontent.com/25483966/67781049-50611700-fa3d-11e9-8122-f4d9c88d407e.png)
Notice when you refresh the browser and click on `Groups` from the `Main Menu` that the group name is now truncated to 32 characters
![Screen Shot 2019-10-29 at 11 16 51 AM](https://user-images.githubusercontent.com/25483966/67781288-a59d2880-fa3d-11e9-9396-309204fb3eed.png)
 
## Expected behavior
Character limit for group display name should be displayed in the dialog when the input has exceeded max, just like when creating a new user
![Screen Shot 2019-10-29 at 10 52 27 AM](https://user-images.githubusercontent.com/25483966/67781836-54416900-fa3e-11e9-948e-a146116555bb.png)

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-30c533
Build Number: 30c53326c589e2a7dcded3ed6c1ec85acc0ffd96
Build Date/Time: 10-29-2019 10:34:16 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1379
