### ISSUE TITLE
[studio-ui] ICE edits on embedded components do not refresh the page once saved like regular components do

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3597]
## Describe the bug
ICE edits on embedded components do not refresh the page once saved like regular components do

## To Reproduce
1. Click pencil on embedded component
2. Do an edit and save
3. Content is not updated
4. Refresh and see the updated

## Expected behavior
Manual refresh is not required. Same as ICE on non-embedded components.

**Comment by yacdaniel** [comment]
Verified fixed.
