### ISSUE TITLE
[studio-ui] RTE code editor doesn't work

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3598]
## Describe the bug
The code editor for RTE fields doesn't load correctly

## Screenshots
<img width="1310" alt="Screen Shot 2019-10-29 at 3 03 18 PM" src="https://user-images.githubusercontent.com/1236955/67809010-7c8c9000-fa5d-11e9-8722-ecafcb8b3a2e.png">

## Logs
From the browser console
```
GET http://localhost:8080/studio/static-assets/components/cstudio-common/ace/ace_editor.css?version=3db61467a1c916c486c2b1cbbf67b629fe4da4fb net::ERR_ABORTED 404
```

### Version
3.1.4-SNAPSHOT

### OS
macOS

### Browser
Chrome 77.0.3865.120

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1382

**Comment by jdrossl** [comment]
Verified
