### ISSUE TITLE
[studio-ui] Workflow keeps submition comments after other user cancel the workflow

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#360]
1. As an author Edit a page and send request it to publish
2. As an other user (could be a site admin) edit the same page to cancel the workflow
3. Try to publish the page, on the Submission Comment field  the original Author comment still shows up.

Expected behavior once a item's workflow is cancel original messaged should be discarted too.

**Comment by vestrada** [comment]
Hi @dejan-brkic 

Per coversation, When schedule property is set to "false" (BE), please remove the information for: scheduledDate, submissionComment properties through BE.

**Comment by dejan-brkic** [comment]
Issue fixed
PR #487 for 2.5.x branch

**Comment by gortizcrafter** [comment]
1. Login with author
2. Edit Content
3. Publish request with a valid comment
4. Submit

5. Login with admin
6. Edit the same content edited in the step 2.
7. Try to publish 

Behavior: the comment typed in the step 3 not exist, the behavior is correct.
