### ISSUE TITLE
[studio-ui] Issues and tweaks for Create Site Dialog

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3603]
## Describe the bug
A) Change Blueprint card to have the title as a header.
B) Sometimes is needed to double click on review and back
C) Close form when data and click on ok, then create site dialog doesn't open.

### Version
Crafter 3.1.4

**Comment by yacdaniel** [comment]
I tried for a while the problem with the review and back but couldn't reproduce it. If continue to happen please report a new issue.
Verified fixed.
