### ISSUE TITLE
[studio-ui] Missing error dialog when internal-name is removed from Content Type

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3604]
## Describe the bug
An error dialog is not displayed when the user tries to remove the `internal-name` property from a Content Type

## To Reproduce
1. Open any Content Type or create a new
2. Remove the `Internal Name` Page property

## Expected behavior
`internal-name` shouldn't be removed, an error dialog should appear like when the `file-name` is tried to be removed.

## Screenshots
Page Content Type saved with the `internal-name` removed.
![imagen](https://user-images.githubusercontent.com/6722074/67883954-9df78580-fb0a-11e9-94e3-aa85f3883d28.png)

Error dialog when `file-name` or `auto-filename` is removed
![imagen](https://user-images.githubusercontent.com/6722074/67884332-43125e00-fb0b-11e9-8117-728ecac5a111.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Firefox, Chrome

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1388

**Comment by yacdaniel** [comment]
Verified, the message should be updated when https://github.com/craftercms/craftercms/issues/3649 is done.
