### ISSUE TITLE
[studio-ui] Moving away from Global Config changes doesn't remind the user that it's not saved/confirm loss

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3605]
## Describe the bug
Moving away from an edited Global Config (in the Main Menu) doesn't remind the user that they will lose their changes and ask for confirmation.

## To Reproduce
1. Go to Main Menu
2. Click on Global Config
3. Make changes
4. Click on another tool like Sites
5. You lost your changes

## Expected behavior
Studio should stop the user from navigating away and request a confirmation. @rart to design.

## Screenshots
N/A

## Logs
N/A

### Version
3.1.4-SNAPSHOT

### OS
Linux - Ubuntu 18.04

### Browser
Chrome

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1398

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1408

**Comment by sumerjabri** [comment]
Click on Global Config, and start typing your new configuration. Nothing happens. The focus must be on the text in the Window and there is no reason to select all. Simply put the cursor at the first location within the text file (don't select all).

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1417

**Comment by sumerjabri** [comment]
The focus breaks if you click on `Sample` then  `Use Same Content ` then either option. It should replace what exists and put the caret at  0:0 and have nothing selected.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1432

**Comment by sumerjabri** [comment]
Verified.
