### ISSUE TITLE
[studio][studio-ui] Improve site-component datasource

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3608]
**Is your feature request related to a problem? Please describe.**
`site-component.js` datasource needs refactoring to improve the way it works. It currently relies on engine APIs and they async load is not optimized.

**Describe the solution you'd like**
Better async loading and if possible not relying on engine APIs

**Comment by rart** [comment]
- Verify that engine APIs used can be replaced using taxonomy fetcher from studio APIs.
- What else this data source does?
- Careful as many sites/blueprints rely on it and use it

**Comment by yacdaniel** [comment]
Verified.
