### ISSUE TITLE
[studio-ui] Missing translation  admin.publishing.QUEUED   

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3609]
## Describe the bug
Missing translation in `Publishing` - `Status` when there are Items queued for publishing    

## To Reproduce
1. Approve and select the Schedule `Items go live on a specific date & time` 
2. Go to `Site Config` -> `Publishing` -> `Status`

## Expected behavior
Status text instead of the variable `admin.publishing.QUEUED  `

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/67956751-3731a500-fbba-11e9-87b0-ea2d673ecc77.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1396

**Comment by yacdaniel** [comment]
Verified fixed.
![imagen](https://user-images.githubusercontent.com/6722074/68333928-280d9400-009f-11ea-82c2-e3b078218738.png)
