### ISSUE TITLE
Browse Items should rely on path value instead of browserUri

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#361]
Checking code, seems browse items/components/templates modal code is using `browserUri` in order to call the service that retrieves children elements, `browserUri` is more intended to be used to load item from web browser, so it's better to use `path` because contains real location value for service call

File /studio2-ui/static-assets/components/cstudio-browse/browse.js ln 189

**Comment by gortizcrafter** [comment]
The change in the source code exist.

evidence: https://www.screencast.com/t/TRpZseSriwEx

**Comment by russdanner** [comment]
@gortizcrafter The fact that the code is there does not qualify as tested.  If you need help defining how to test, please ask in the ticket.

**Comment by gortizcrafter** [comment]
Source code with the change : https://www.screencast.com/t/yr3fviS

Some tests performed.

Test 1 : https://www.screencast.com/t/JQ3qbUeO

Test 2 : https://www.screencast.com/t/vlp9vMQQHXGx

Test 3 : https://www.screencast.com/t/fJyQ1w7h
