### ISSUE TITLE
[studio-ui] Form shrinks after uploading a file when ICE is used to edit an RTE

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3610]
## Describe the bug
Form shrinks after uploading a file when ICE is used to edit an RTE

## To Reproduce
1. Edit the `Page - Article` content type by adding a `File Uploaded from Desktop` data source
![Screen Shot 2019-10-31 at 11 33 58 AM](https://user-images.githubusercontent.com/25483966/67961674-66eca700-fbd2-11e9-8add-51db2ca0e84b.png)
 
2. In the RTE in `Page - Article`, go to the `Properties Explorer` then scroll down to `File Manager` and check the checkbox for the new data source we added
![Screen Shot 2019-10-31 at 11 35 07 AM](https://user-images.githubusercontent.com/25483966/67961819-9ac7cc80-fbd2-11e9-90f0-8d920e3c8f7d.png)

3. Save your changes.
4. Preview an article and turn on the ICE pencils.  Click on an ICE pencil on an RTE

![Screen Shot 2019-10-31 at 11 38 52 AM](https://user-images.githubusercontent.com/25483966/67962143-11fd6080-fbd3-11e9-82f1-8b5f5bbaa4bf.png)

5. Click on an ICE pencil in the article body, put the cursor inside the RTE, then click on the insert link icon

![Screen Shot 2019-10-31 at 11 40 36 AM](https://user-images.githubusercontent.com/25483966/67962697-d747f800-fbd3-11e9-9a88-797b6d7cab11.png)

6. Upload a file.  Notice that the form shrinks

![Screen Shot 2019-10-31 at 11 42 57 AM](https://user-images.githubusercontent.com/25483966/67962735-e6c74100-fbd3-11e9-813e-709cfbeb3b5b.png)

## Expected behavior
The form should not shrink after uploading a file when ICE is used to edit an RTE

## Screenshots
Here's a short clip:
https://www.loom.com/share/cee23c12adb04502b06faf92fcca2d8f

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-76b00a
Build Number: 76b00ac31699980c18a2f640390c578947346b50
Build Date/Time: 10-31-2019 09:45:01 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
The form shrinks after uploading only if I use the ICE pencil to edit the RTE.  If I click on `Edit` from the context nav for the article, then just scroll to the RTE and upload a file to create a link, the form does not shrink.

**Comment by yacdaniel** [comment]
Verified
