### ISSUE TITLE
[studio-ui] Missing content type for scripts and taxonomy in publish package

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3611]
## Describe the bug
Missing content type for scripts and taxonomy in publish packages

## To Reproduce
1. Create a site from Editorial bp
2. Edit and publish one file from `Scripts` and another from `Taxonomy`
3. Go to `Site Config` -> `Publishing` -> `Publishing Queue`
4. Fetch the package files

## Expected behavior
The content types for `Taxonomy` and `Scripts` are not unknown.

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/67966825-2557fe00-fbca-11e9-9aea-cf73435de198.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1817

**Comment by yacdaniel** [comment]
![image](https://user-images.githubusercontent.com/6722074/68135676-a9232a80-fee9-11e9-8135-648f28d7b59e.png)
Verified fixed.
