### ISSUE TITLE
[deployer] GitPushProcessor should be able to push to all branches

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3612]
`GitPushProcessor` should be able to push all branches to the remote. It should also be able to push from a specific local branch (right now it only accepts the name of the remote branch to push to).

**Comment by avasquez614** [comment]
@jdrossl the push to all branches option is done. Please help with the option of pushing a specific local branch.

**Comment by avasquez614** [comment]
@yacdaniel please help with testing this

**Comment by yacdaniel** [comment]
Verified.
