### ISSUE TITLE
[studio] API 2 /publish/cancel should cancel the workflow of a Ready_For_Live package

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3615]
## Describe the bug
When the API 2 /publish/cancel is used to cancel a package that is in the state `Ready_For_Live` the files stays with a `Workflow State` of  Scheduled

## To Reproduce
1. Edit content and Approve and select the Schedule `Items go live on a specific date & time`
2. Go to `Site Config`-> `Publishing` -> `Publishing Queue`  and cancel the package
3. In Preview check the `Workflow State` of the file that was canceled.
4. Notice that the file is in `Scheduled` 

## Expected behavior
The file should have the `Workflow State` of Edited.

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1822

**Comment by yacdaniel** [comment]
Verified.
