### ISSUE TITLE
[studio-ui] CMIS browse should show a progress bar when clonning an asset

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3617]
## Describe the bug
When an asset is cloned from CMIS there is no progress bar that informs the user about the action taking place. If an asset is too big this may take time a lot of seconds. 

## To Reproduce
1. Set Up CMIS server and a big video file uploaded  ~ 200mb http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4
2. Set Up a Video From CMIS Repository Datasource and a Video Control bound to the Data Source
3. Edit content and try to clone a big video from the CMIS
4. Nothing happens, the browser window is not closed user is not able to know if the action succeeds or not

## Expected behavior
Maybe a progress bar with the clone informatio. Same as we do when we upload assets?

## Screenshots
![cmisBigVideo](https://user-images.githubusercontent.com/6722074/68045093-5b66b200-fc9e-11e9-87b7-af95af18cf21.gif)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1411

**Comment by yacdaniel** [comment]
Verified a new progress bar is displayed when cloning an asset:
![image](https://user-images.githubusercontent.com/6722074/68593978-33284180-045c-11ea-9252-42c8ec40b5d0.png)
