### ISSUE TITLE
[studio-ui] Cancel button does not work when editing config.xml from content type

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3618]
## Describe the bug
Cancel button does not work when editing config.xml from content type

## To Reproduce
1. Create a site using any bp
2. Click on `Site Config` ➜ `Content Types` ➜ `Open Existing Type` 
3. Select any of the available content type
4. In the `Properties Explorer`, scroll to `Configuration`
5. Click on `config.xml`, a pencil will appear right next to it
6. Click on the pencil to edit the `config.xml`
7. Make some changes to the file, say add something to the comments, etc
8. Click on the `Cancel` button. Notice that nothing happens.

## Expected behavior
When a user has made changes to the `config.xml` file and the `Cancel` button is clicked, a popup should appear asking if the user wants to discard changes, or something like that.  If the user wants to discard the changes, the editor for the `config.xml` file should then close

## Screenshots
Here's a short clip:
https://www.loom.com/share/16661016c46b45d399c39aa1dd16ca11

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-3edffe
Build Number: 3edffe32aabd42a760bbe2fa5bfedbc3de9223f6
Build Date/Time: 11-04-2019 07:21:55 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1401

**Comment by alhambrav** [comment]
Verified fixed.
