### ISSUE TITLE
[studio-ui] Files Data Sources issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3619]
## Describe the bug
When there are some combinations of Files Data Sources with an item selector control, the UI is sending wrong parameters in the upload API. The Data Sources work correctly when used alone without any other selection in the `Item Manager` property of the `Item Selector` Control.

## To Reproduce
All of the tests are done with the Editorial BP and a `node-selector` Control.
1. Have a `WebDAV-upload` with an `S3-upload`  or a `CMIS-upload`. Or with both `S3` and `CMIS` upload. 
![image](https://user-images.githubusercontent.com/6722074/68127901-6149d680-fedc-11e9-82b3-821566a3de2b.png)
Then try to upload a file using the `WebDAV-upload`
An error is shown 
![image](https://user-images.githubusercontent.com/6722074/68128036-9ce4a080-fedc-11e9-98fc-e0ad4c4fa0f5.png)

2. Have a `CMIS-upload` with a `S3-upload`  or a `WebDAV-upload`
![image](https://user-images.githubusercontent.com/6722074/68128437-59d6fd00-fedd-11e9-820a-64ea92d6c150.png)
Then try to upload a file using the `CMIS-upload`
An error is shown. 
![image](https://user-images.githubusercontent.com/6722074/68128487-7410db00-fedd-11e9-8eb8-f4280f864c26.png)

3. Have a `CMIS-repo` and any other File Data Source(Upload or Repo) 
![image](https://user-images.githubusercontent.com/6722074/68129585-6ceacc80-fedf-11e9-81c6-7a5146573f3b.png)
Go to the Form Engine and click the `Add` in the Control. Notice that the Form opens the CMIS browse without a chance to choose another Data Sources and the `CMIS-repo` is not visible in the options
![CMISRepo](https://user-images.githubusercontent.com/6722074/68129666-8ee44f00-fedf-11e9-85de-c6392261381d.gif)

## Expected behavior
1. No errors when uploading file to `WebDAV`
2. No errors when uploading file to `CMIS`
3. The Data Source is not automatically selected. Also, there is a visible option for the `CMIS-repo` when you click the `Add` button. 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1403

**Comment by yacdaniel** [comment]
Verified!
