### ISSUE TITLE
[studio-ui] User dashboard refresh always redirects to first global menu item regardless of URL

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3623]
## Describe the bug
User dashboard always redirects to first global menu item regardless of URL upon loading. If browser-refreshing on a certain page that has an assigned URL, page should stay put.

## To Reproduce
1. Go to user dashboard/global menu
2. Go to groups 
3. Refresh
4. Sites is the new active route after refresh

## Expected behavior
URL is followed. Only go to default route if there is no specific route on the URL.
e.g. `#/groups` stays in groups, `/` goes to first global menu item

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1413

**Comment by yacdaniel** [comment]
Verified.
