### ISSUE TITLE
[studio-ui] Reactify Approve dialog

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3627]
Migrate approve dialog to codebase next

**Comment by rart** [comment]
- [ ] RequestPublishDialog & ApproveDialog ended up being a copy paste of each other. Let's unite them into a single `PublishDialog` component. This component would have the smarts to present Approve or Request UI depending on the user role(s). Their submit function though currently named differently, are the same - you may simply call it "submit".
- [ ] For styles, make sure you're using the palette colors. Remove all hard coded ones.
- [ ] Remove padding from path line of the line items and make the title line an h4
- [ ] Disable "Show all deps" button when nothing is selected
- [ ] Entering an invalid date format shows error on both date and time inputs
- [ ] Using the timezone selector, when the drop down renders above the field, filtering causes separation between the field and the input. Investigate. Open up a MUI bug if necessary.
- [ ] Clean up the "Later" form if "Now" is selected - including any errors. Do this on a timeout (2s). Make sure if you submit within those 2s, the submission is still correct (you may use a larger timeout to test).
- [ ] Submit button should be disabled whilst there are "Later" form errors.
- [ ] Reduce the spacing above validation errors on the "Later" form. Make them more proximal to their field.
- [ ] Notice how small the hover is on the close icon when hovered. You may compare it with Create Site Dialog. It should look like that one.
- [ ] For accessbility, now/Later should be wrapped as a radio button group.
- [ ] Move the useEffect function bodies to inline the effect so the linter can do it's job.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1531
