### ISSUE TITLE
[studio] Create a user-specific catalog for storing special preferences

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3636]
**Is your feature request related to a problem? Please describe.**
Need a persistent way of tracking whether a user has seen/dismissed a certain UI or has performed certain interactions. For example:
• Has completed the welcome tutorial/tour
• Has received/dismissed the new UI information tool tip
• Certain view preferences

**Describe the solution you'd like**
Create a persistent catalog (database) which keeps tracks of this sort of thing so the UI knows when to show or not to show certain tips or otherwise.

**Describe alternatives you've considered**
Store in local storage - not good since things would not be persistent across machines.

**Comment by sumerjabri** [comment]
/me API for the user to see/edit their params
admin can see/edit everyone's param for support

Consider a new tables, preferences as a KVP attached to `user`

**Comment by sumerjabri** [comment]
Done via user preferences and browser storage.
