### ISSUE TITLE
[studio-ui] Add rexgex support to wcm-root-folder path excludes

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3642]
**Is your feature request related to a problem? Please describe.**
Currently wcm-root-folder plugin allows you to exclude specific paths.  The match is a string match/compare instead of a regex.  As a result you cannot configure path like `/site/website/blog/.*` where /blog is not excluded but all of its children are.

**Describe the solution you'd like**
Change the exclude configuration to use a regex instead of a string match

**Comment by russdanner** [comment]
Moving this to 3.1.4 because https://github.com/craftercms/craftercms/issues/3643 is related and if we fix that this may easier to do at the same time.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1420

**Comment by rart** [comment]
@russdanner to use regex, add a `regex` tag inside the `excludes`...

```xml
<excludes>
  <exclude>/site/website/style</exclude>
  <regex>entertainment</regex>
</excludes>
```

**Comment by russdanner** [comment]
Confirmed

**Comment by russdanner** [comment]
confirmed
