### ISSUE TITLE
[studio-ui] Create API to support publish by tag

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3644]
**Is your feature request related to a problem? Please describe.**
Administrators and CI/CD automation platforms  moving code forward are tag the code they want to release and want to be able to publish by a tag rather than the Git commit ID.  

**Describe the solution you'd like**
Add an API to studio that allows you to publish by tag

**Comment by jdrossl** [comment]
@sumerjabri @russdanner I don't think we need a new API for this because git will automatically accept the tag as a commit id, would it be ok to update only the UI to support this?

Example publishing a tag `v1`

```
commit 0d1108e838b8b8629d8e3749fbc7b2c06b3d6293 (HEAD -> live, tag: 2021-04-06T214328000Z_published_on_2021-04-06T214328740Z)
Author: admin admin <evaladmin@example.com>
Date:   Tue Apr 6 15:43:28 2021 -0600

    Publish event triggered by admin on 2021-04-06T214328738Z via UI.
    
    Publish note from user: "
    "
    
    Commit ID: v1
    
    Package ID: 8dce1fd0-6c9f-4630-8ed1-33cb05289dfb

site/website/index.xml

```

**Comment by sumerjabri** [comment]
@rart see the note from @jdrossl and let us know if you have any questions.

**Comment by russdanner** [comment]
Confirmed
