### ISSUE TITLE
[studio] Update Editorial blueprint taxonomies

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3645]
**Is your feature request related to a problem? Please describe.**
Editorial blueprint has a "segments" taxonomy. Current segments are "guy" or "gal" which might be too simple to show what the system can do.

**Describe the solution you'd like**
Update to something more elaborate.

**Describe alternatives you've considered**
Never mind it.

**Comment by sumerjabri** [comment]
Will not pursue.
