### ISSUE TITLE
[studio] hide text on toggle button in editorial Blueprint

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3648]
## Describe the bug
Toggle button is showing a text "toggle"

## To Reproduce
Create a editorial site

## Expected behavior
The toggle button should no show any text

## Screenshots
<img width="550" alt="Captura de Pantalla 2019-11-07 a la(s) 10 46 50" src="https://user-images.githubusercontent.com/10813283/68408962-ebe43d00-014b-11ea-91d5-c12a440dda98.png">

### Version
Crafter 3.1.4

**Comment by sumerjabri** [comment]
Verified
