### ISSUE TITLE
[studio-ui] Add a Internal Name control

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3649]
**Is your feature request related to a problem? Please describe.**
If the user removes the `internal-name` input control from a Content-Type add tries to save it then it displays a simple error message: `This content type requires an Internal Name.` The process of adding the Internal Name is adding an input control with `internal-name` as the `Name - Variable`  value.  

**Describe the solution you'd like**
Create a new control: `Internal Name`, this should be an `Input` control with the  `Name / Variable Name` property set to `internal-name`.  This would make the process of adding back the internal-name smooth and user-friendly.

**Describe alternatives you've considered**
N/A

**Additional context**
Related to the new error message https://github.com/craftercms/craftercms/issues/3604

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1422
studio: https://github.com/craftercms/studio/pull/1827

**Comment by jvega190** [comment]
@jdrossl we need to update UM to include this control please, as in PR craftercms/studio#1827

**Comment by sumerjabri** [comment]
@jvega190 resubmit the PRs to `develop` and then assign the ticket to @jdrossl for UM

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1472
studio: https://github.com/craftercms/studio/pull/1840

**Comment by yacdaniel** [comment]
Verified.
