### ISSUE TITLE
[docs] Document references Code Forward, Content Back incorrectly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3650]
`Code Back, Content Forward Process` is mentioned on this page 
https://docs.craftercms.org/en/3.1/developers/developer-workflow/implementation-prod-repo-sync.html

It should be `Code Forward, Content Back`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/873

**Comment by russdanner** [comment]
This is not merged yet.

**Comment by russdanner** [comment]
Confirmed
