### ISSUE TITLE
[docs] Document development setup of Docker-based install

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3651]
**Is your feature request related to a problem? Please describe.**
Developers who chose to use Docker install on their machine need instructions on how to use Docker and be able to mount the repos folder locally so they can use IDEs.

**Describe the solution you'd like**
Add instructions for performing windows and osx development with the docker-compose (e.g. creating folders and mounting them appropriately for sites, if git based development is being done with an IDE in windows (e.g. Intellij) for one or more sites.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/921

**Comment by russdanner** [comment]
Confirmed
