### ISSUE TITLE
[studio-ui] Add Display Format property to grouped checkbox

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3652]
**Is your feature request related to a problem? Please describe.**
Some grouped checkbox data is best served to users left to right while in other cases it would be best to list the options vertically

Today the only option is this format
A B
C D
E F

Add the ability to support this format
A D
B E
C F

**Describe the solution you'd like**
Add a property to allow the content type developer to select list horizontally or vertically

The default should be "horizontal" to accommodate existing installations.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1421

**Comment by jvega190** [comment]
Merged into `craftercms:2019-11-ui-restructure`

**Comment by sumerjabri** [comment]
@jvega190 Please send PR to `develop` to make it part of 3.1

**Comment by jvega190** [comment]
@sumerjabri  done: https://github.com/craftercms/studio-ui/pull/1472

**Comment by russdanner** [comment]
Confirmed
