### ISSUE TITLE
[studio] Sample/default global config outdated password comments

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3654]
## Describe the bug
The sample and default config comments are outdated in regards to password validation. 
• **studio.security.passwordRequirements.description** is no longer applicable
• **studio.security.passwordRequirements.validationRegex** needs to be the one with the [capture groups](https://github.com/craftercms/craftercms/issues/3530#issuecomment-543723200)
• **Password requirements validation regular expression** description tip comments should explain/list the supported keys and the capture groups matter. Would be good if we had a docs page around it.

## To Reproduce
1. Go to global config
2. Inspect the password-related content on the defaults **and** the sample
3. See outdated content 

## Expected behavior
Defaults and sample reflect and explain the latest mechanics and document the supported validations.

## Screenshots
<img width="872" alt="image" src="https://user-images.githubusercontent.com/3928341/68472957-01c43180-0222-11ea-9665-c60926bdf464.png">

## Additional context
https://github.com/craftercms/craftercms/issues/3530

**Comment by dejan-brkic** [comment]
Already fixed with this PR:
https://github.com/craftercms/studio/pull/1823

Ticket:
https://github.com/craftercms/craftercms/issues/3530

**Comment by rart** [comment]
We should add a comment with the listed expressions and capture group names supported for full internationalization. The PR doesn't add that.

The supported keys are...
hasNumbers
hasLowercase
hasUppercase
hasSpecialChars
noSpaces
minLength
maxLength
minMaxLength
passwordValidation
validPassword
invalidPassword
fulfillAllReqErrorMessage

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/3657
https://github.com/craftercms/studio/pull/1826

**Comment by rart** [comment]
Ok
