### ISSUE TITLE
[studio] Allow a way to upgrade a site with changes from a MP blueprint.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3655]
We need a way to upgrade a site to a new version of a MP bp when it comes out (needed specially if the BP has a bug). Since the sites are created as orphan, we can't just add the bp as a remote (and it's not recommended anyway). A possible solution is to have an option in Site Config to check for BP updates, which will make Studio check for the latest bp version and then show a diff of the changes, which can later be applied.

**Comment by sumerjabri** [comment]
Will not pursue.
