### ISSUE TITLE
[studio-ui] Warn the user when create an orphan site from a remote

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3656]
When creating a site from remote and the orphan option is selected, the user should be warned that the history of the remote site will not be kept and that it will not be possible to add the remote and pull from it later, since the history will be different.

**Comment by sumerjabri** [comment]
@rart I'm thinking within the Create Site dialog, when the user selects create as orphan, we can add the text right below that switch. Something like:
```
Creating the site as an orphan will dissociate the site from the source git repository and remove all history.
```

**Comment by yacdaniel** [comment]
Verified.
