### ISSUE TITLE
[studio-ui] Switch lib QSA cache busters to lib version instead of studio build version

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3659]
**Is your feature request related to a problem? Please describe.**
Libs rarely change in studio. Currently, we use build number as a cache buster. This forces browsers to reload the lib despite not having to, making page loads a bit slower on every first load after upgrades.

**Describe the solution you'd like**
Let’s use the lib version instead of studio build as cache buster.

**Comment by sumerjabri** [comment]
Done via eTags and cache headers.
