### ISSUE TITLE
[studio] Remove space between `COUNT` and `(` in SQL

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3665]
For better DB compatibility, remove the space between `COUNT` and `(` in SQL statements like:
https://github.com/craftercms/studio/blob/f331b617e4239ed6c9128a14a4e1c903b36b881f/src/main/resources/org/craftercms/studio/api/v2/dal/UserDAO.xml#L155

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1831

**Comment by sumerjabri** [comment]
Verified
