### ISSUE TITLE
[studio] Add preview proxy to Studio 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3667]
**Is your feature request related to a problem? Please describe.**
Setting up preview and in-context editing can be complex when multiple servers and domains are involved.  Developers and ops admins want a simple, easy to understand configuration and topology

**Describe the solution you'd like**
The preview frame should go to a proxy within Studio that forwards all requests to the configured preview server location. 

In this way configuration for the admin is very simple and all authentication, headers, cookies, etc that are set with the studio log-in are available in preview.

**Comment by sumerjabri** [comment]
Studio UI preview pane should also point to the proxy.

**Comment by sumerjabri** [comment]
Let's discuss when ready.

**Comment by sumerjabri** [comment]
Start by looking at this: https://github.com/mitre/HTTP-Proxy-Servlet

If that doesn't work for us, try this: https://github.com/mkopylec/charon-spring-boot-starter

Failing that, we can go back to our own implementation from scratch.

**Comment by sumerjabri** [comment]
@jdrossl please remove `environment-config.xml` via UM.

**Comment by jdrossl** [comment]
PR for `support/3.1.x`
