### ISSUE TITLE
[studio] Feature drag drop fails on editorial home page

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3671]
## Describe the bug
drag and drop of feature fails on out of the box editorial blueprint

## To Reproduce
1. Create site based on editorial
2. Go to drag-drop mode
3. Drag a feature in to the features zone
4. Note the error message `The drop zone not support this type of Components`

## Expected behavior
Features are the only thing on the blueprint you can drop. You should be able to drag-drop them

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.4-SNAPSHOT-42b389
Build Number: 42b389f17553cb5eddb1514057b512ab243433e2
Build Date/Time: 11-13-2019 12:21:09 -0500

### OS
Any

### Browser
All

**Comment by jvega190** [comment]
https://github.com/craftercms/studio/pull/1833

**Comment by russdanner** [comment]
Confirmed
