### ISSUE TITLE
[studio-ui] Partial language update

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3673]
## Describe the bug
Language settings in the profile persist without a save.

## To Reproduce
1. Go to Profile Settings
2. Change the language but don't apply/save
3. Move back to the Main Menu
4. See the site translated in the language you selected but didn't save
5. Click back to the profile and see the original language (not the one in use right now)

## Expected behavior
You must hit apply/save before the language settings are applied.

## Screenshots
N/A

## Logs
N/A

### Version
3.1.4

### OS
Ubuntu Linux

### Browser
Chrome

## Additional context
N/A

**Comment by rart** [comment]
@vestrada also, change the notification to a toast instead of a dialog. (similar to global config)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/1441

**Comment by sumerjabri** [comment]
Verified.
