### ISSUE TITLE
[studio-ui] ICE/Pencils: separate render from model fetch so they can be called individually

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3674]
**Is your feature request related to a problem? Please describe.**
When ICE repaint is called, it re-fetches models too. For SPA applications, being able to call repaint with out model reload would be most efficient.

**Describe the solution you'd like**
Separate the logic of painting the pencils (updating their position and/or existence) from the logic that fetches the model information.

**Describe alternatives you've considered**
Wait for page builder release.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1483

**Comment by rart** [comment]
@yacdaniel this touches on ICE/drag&drop stuff. Please give that a test to make sure that was unaffected.

(I'll verify the pencil rendering request - though you're welcome to try things around it too.)

**Comment by yacdaniel** [comment]
Verified.
