### ISSUE TITLE
[studio-ui] Drag & Drop issues

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3676]
## Describe the bug
1: Save as draft doesn't work in a drag and drop of embedded components
2: Nested drop of component doesn't work in all situations

## To Reproduce
1: Create a new embedded component as draft
2: Try to drop components on a nested drop zone.

## Expected behavior
Draft of embedded components should work.
Dnd of nested components should work.

### Version
Crafter 3.1.4

**Comment by yacdaniel** [comment]
@yureii00 please check when a Feature is dropped in the zone, information is added and then I hit the `Cancel` button. Looks like is not waiting for the user confirmation
![cancelDragDrop](https://user-images.githubusercontent.com/6722074/69279749-ab081180-0baa-11ea-9e00-31da16c0eaaf.gif)

**Comment by yureii00** [comment]
Fixed.

**Comment by russdanner** [comment]
confirmed
