### ISSUE TITLE
[studio-ui] scroll does not work in select content type dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3682]
## Describe the bug
User cannot scroll with the mouse in the select content type dialog

## To Reproduce
1. create a lot of content types
2. go to the content type editor and select edit existing content type
3. try to scroll from the top of the list to the bottom

## Expected behavior
scroll should work

### Version
Studio Version Number: 3.1.4-SNAPSHOT-231304
Build Number: 231304783cdaef14ffde65436d74c101813b1a7f
Build Date/Time: 11-17-2019 18:28:33 -0500

### OS
Any

### Browser
Any

**Comment by rart** [comment]
@russdanner check for merge of https://github.com/craftercms/studio-ui/pull/1445

**Comment by sumerjabri** [comment]
Verified fixed.
