### ISSUE TITLE
[studio-ui] saving a page takes user to homepage in preview

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3683]
## Describe the bug
When a user edits a page and saves it they are redirected to the home page

## To Reproduce
1. start with editorial blueprint
2. open side bar and navigate to style page
3. Save the page
4. Note you are redirected to the home page 

## Expected behavior
The page you were on (style) should be refreshed in preview

## Screenshots
https://www.loom.com/share/501befbeed954d68aca4759f94b245da

## Logs
N/a

### Version
Studio Version Number: 3.1.4-SNAPSHOT-231304
Build Number: 231304783cdaef14ffde65436d74c101813b1a7f
Build Date/Time: 11-17-2019 18:28:33 -0500

### OS
Any

### Browser
Any

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1446

**Comment by russdanner** [comment]
Confirmed
