### ISSUE TITLE
[engine] Add content-type to componentContainerAttr

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3685]
**Is your feature request related to a problem? Please describe.**
DnD needs the content-type for it's mechanics. Please add the attribute `data-studio-zone-content-type` to the attributes written by componentContainerAttr macro.

**Describe the solution you'd like**
Preferably, instead of adding an additional macro argument, remove objectId and send the contentModel to the macro. Inside, the macro it can then decide what to do with it to write what it does now plus new and future stuff.

**Describe alternatives you've considered**
Add a new argument to the macro argument which is the content type.

**Additional context**
This will require blueprint updates and people with existing sites to update their templates. We're putting feedback dialogs in place to warn people about requiring to update their templates when the information lack is detected.

**Comment by yureii00** [comment]
verified.
