### ISSUE TITLE
[studio-ui] Context Nav - Content Tree is collapsed and not refreshed after page creation

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#369]
After you create a new page like `folder 1 > folder 2 > NEW PAGE`  the `folder 2` gets collapsed and not reflects to the user the new created page

Found a possible fix but need further testing

**Comment by asotog** [comment]
Will test this fix from my fork further

**Comment by vestrada** [comment]
Closed - #189

**Comment by gortizcrafter** [comment]
1. Create folder 1
2. Create folder 2 into the folder 1
3. Create new content into the folder 2
The content created is show properly and the folder 2 not collapse.
The behavior is correct.
