### ISSUE TITLE
[studio] "Sort by"-filter in studio search should be optional

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#3693]
**Is your feature request related to a problem? Please describe.**
When you insert more than one token to search for e.g. "John Doe" the seach engine returns documents that contain "John" or "Doe" or both. Seach engines like elasticsearch score the hits which usually results in a higher score for documents that contains all tokens. But in Studio the user does not have the possibility to present the results in the order of the score, because the result is always sorted by another criteria.

**Describe the solution you'd like**
"Sort By" should be optional for the user.

**Describe alternatives you've considered**
 "score"-criteria could be added as default for the Studio search

**Additional context**
Users google a lot so they expect any other search to be like google ;-)

**Comment by sumerjabri** [comment]
@rart consider sending the sort order as "Relevance."
@jdrossl does the BE API already support relevance (or similar) sorting criterion? What other criteria exist?

**Comment by jdrossl** [comment]
in the BE the default is to sort by score, so the UI should just remove the parameter

**Comment by sumerjabri** [comment]
@rart ping me to discuss options here before implementation.

**Comment by rart** [comment]
@yureii00 to be done on top of develop and forward-ported to 2019-branch. I'll give you a green light to start once discussed with Sumer.

**Comment by yacdaniel** [comment]
Verified.
