### ISSUE TITLE
[studio-ui] Dependencies dialog has flipped listing types

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3696]
## Describe the bug
The select to display items that depend on item in question or items the item in question depends on seems to be flipped.

## To Reproduce
1. Open static-assets/images
2. Right click an image that is used on some page(s) and select view dependencies 
3. Review the listing of both values of the select box

## Expected behavior
Correct listing according to the select value

**Comment by jvega190** [comment]
https://github.com/craftercms/craftercms/issues/3696

**Comment by sumerjabri** [comment]
@russdanner I can't merge the PR until you confirm this is an issue to be resolved in 3.1.4

**Comment by russdanner** [comment]
Confirmed
