### ISSUE TITLE
[studio-ui] Page preview does not work after previewing an image

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3699]
## Describe the bug
After previewing an image, previewing a page from the site tree does not work

## To Reproduce
1. Create a site using the website editorial bp
2. Preview an image by navigating to `static-assets/images` and clicking on an image, say `coffee-pic.jpg`
3. From the Sidebar, click on the `Home` page
4. Notice that the `Home` page is not displayed, but when you click on `Edit` from the context nav, it opens the form for the `Home` page
5. Click on other pages and notice that it is also not displayed
<img width="1227" alt="Screen Shot 2019-11-25 at 6 52 17 PM" src="https://user-images.githubusercontent.com/25483966/69587911-fbb9a900-0fb4-11ea-9b1c-093455d60780.png">

6. Refresh the page and it now displays the correct thing

## Expected behavior
When you click on a page from the site tree, the page should be displayed correctly

## Screenshots
Here's a short clip showing the behavior:
https://www.loom.com/share/287be2757eb8436e8a143c48852be4a3

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-815148
Build Number: 8151484fb35c2cc3d924d5e88da30c67cf032c49
Build Date/Time: 11-25-2019 18:29:50 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1471

**Comment by alhambrav** [comment]
Verified fixed.
