### ISSUE TITLE
[studio-ui] Display the name of the user whose password is being reset

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3700]
**Is your feature request related to a problem? Please describe.**
When resetting a user's password from the `Main Menu` ➜ `Users`, it would be nice if the dialog where you reset the password also displays the name of the user whose password is being reset 
 
**Describe the solution you'd like**
Display the name of the user whose password is being reset

<img width="556" alt="Screen Shot 2019-11-19 at 1 12 08 PM" src="https://user-images.githubusercontent.com/25483966/69174351-9efb5180-0acf-11ea-9d01-89dfaa897417.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by aachavarria** [comment]
@rart 
<img width="614" alt="username" src="https://user-images.githubusercontent.com/10813283/92168678-f2892280-edf7-11ea-84a6-c96ad4645375.png">

**Comment by alhambrav** [comment]
Verified in 3.1 and develop
