### ISSUE TITLE
[studio-ui] Allow display of non-default password requirements

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3701]
**Is your feature request related to a problem? Please describe.**
The password requirements displayed is always the default password requirements.  
For example, if we have the following regex:
```
studio.security.passwordRequirements.validationRegex: ^(?=(?<hasNumbers>.*[0-9].*[0-9]))(?=(?<hasLowercase>.*[a-z]))(?=(?<hasUppercase>.*[A-Z]))(?=(?<hasSpecialChars>.*[~|!`,;\/@#$%^&+=]))(?<minLength>.{8,})$
```
The password requirements displayed still says `Must contain at least one number` even though the regex requires at least two numbers

**Describe the solution you'd like**
It would be nice if there's a mechanism to display the password requirements based on what the regex is

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
If the built in translations don’t match the RegEx used, admins should not use one of the built-in keys. This won't be localized but [the system will show it raw](https://github.com/craftercms/studio-ui/pull/1468).

For that reason, for keys outside of the built ins, should use a readable string. 

e.g. using your example:

```
^(?=(?<Must_Have_At_Least_Two_Numbers>.*[0-9].*[0-9]))...
```

Worth highlighting this on the docs.

**Comment by sumerjabri** [comment]
@alhambrav please update docs.

**Comment by sumerjabri** [comment]
Switched to a better way to manage password requirements.
