### ISSUE TITLE
[deployer] Add flag to CloudFormation target that allows keeping the CloudFormation on target delete

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3703]
Currently, when an AWS CloudFormed target is deleted, the S3 bucket is cleared and the CloudFormation is deleted. Add a `retainCloudFormation` flat to the template variables that allows keeping the CloudFormation and a `disableS3BucketClear` that disables clearing the S3 bucket.

**Comment by sumerjabri** [comment]
@jdrossl please send the same PR to 3.1.x

**Comment by avasquez614** [comment]
Verified
