### ISSUE TITLE
[studio-ui] image view for file names with umlauts doesn't work

### ISSUE THREAD

**Issue by T0P** [craftercms/craftercms#3704]
## Describe the bug
_See_:
studio-ui -> asset management

1) If you want to open an image with umlauts in the file tree in Crafter Studio, you will see "Oops! The requested page can't be found."
2) file publish doesn't work (see below)

## To Reproduce
1. upload an image with umlauts in the name (ü,ä, etc.)
2. click on the uploaded image in the file tree
3. You will see "Oops! The requested page can't be found."
4. As a consequence you can't publish the file
* After you click on "Approve & Publish" and then on "Submit", the button is disabled and nothing happens.

## Expected behavior
I want to see the image viewer and I want to publish files with umlauts.

## Screenshots
![Bildschirmfoto von 2019-11-27 14-18-58](https://user-images.githubusercontent.com/1247903/69726572-2163c100-1121-11ea-9cb5-df7300401f2b.png)

### Version
Crafter CMS 3.1.3

### OS
Fedora Linux 30

### Browser
Firefox and Chrome

**Comment by dejan-brkic** [comment]
Ui bug escaping filename

**Comment by rart** [comment]
@jvega190 there are several points of change for this matter but please modify any usages of `escape(...)` to use `encodeURIComponent`.

Start with common-api:Operations.getPreviewUrl and work your way down to the rest of places. These include selecting an item from the dashboard or context nav as well as other things you may find along the way.

**Comment by yacdaniel** [comment]
Verified.
