### ISSUE TITLE
[deployer] init-site.sh should allow creating a Crafter Search enabled target

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3705]
Right now when creating a site through `init-site.sh` the created target will always use ES. Add a new parameter to `init-site.sh` that allows specifying that the target should use Crafter Search instead.

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 we already have that parameter:
```
 -s,--crafter-search                       Use Crafter Search instead of
                                           Elasticsearch
```

**Comment by avasquez614** [comment]
I'm blind, my bad
