### ISSUE TITLE
[studio-ui] Numeric Input control doesn't save default value unless it's focused

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3706]
## Describe the bug
The numeric input control has a defaultValue property, but when you open a form and save it without editing the field (or just focusing) the numeric input control value doesn't get saved.

## To Reproduce
1. Go to 'Site Config -> Content Types' and open Home content-type
2. Add a numeric input control and enter a default value, then save
3. Open the Home page, look at the numeric input that has the default value (but don't set the focus on it)
4. Save the page
5. Open the homepage `index.xml` content file
6. Look for the numeric input control variable, is not there.

## Expected behavior
Numeric input control value should be saved

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1475

**Comment by yacdaniel** [comment]
Verified fixed.
