### ISSUE TITLE
[studio]Site creation rollback when a site is created from git remote empty repo doesn't remove sandbox folder.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3708]
## Describe the bug
When the user creates a site from a remote git and the remote repo is empty the rollback of the failed site is not completed, the sandbox folder remains in the disk. 

## To Reproduce
1. In the Create Site dialog choose the option `Remote Git Repository` and fill the data, use a remote empty repository https://github.com/crafter-qa/emptyrepo
2. When the error is displayed go back and edit the repo url with a repository that contains a valid site https://github.com/crafter-qa/editorialsite313
3. Se error, also check the `crafter-authoring/data/repos/sites` the site sandbox is there.

## Expected behavior
Authoring should rollback any changes when the site creation fails because of an empty git remote repo

## Screenshots
![createRemote](https://user-images.githubusercontent.com/6722074/69986279-afb1bb80-1502-11ea-91ed-d30f60c8a914.gif)

## Logs
`Internal server error: org.eclipse.jgit.api.errors.JGitInternalException: Destination path "sandbox" already exists and is not an empty directory. `

### Version
`3.1.5-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1866

**Comment by yacdaniel** [comment]
@dejan-brkic sandbox doesn't seem to be removed when the site is created from an empty repo
https://gist.github.com/yacdaniel/3c1d7206c0ceb3f1e03467e779ec269c

**Comment by dejan-brkic** [comment]
@yacdaniel 
```
Studio Version Number: 3.1.5-SNAPSHOT-6cd8f5

Build Number: 6cd8f5a8baf0b196637cda8d1df2c9dd8bf5f7bd
```
https://github.com/crafter-qa/emptyrepo

cleans up repository after failure on create

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1870

**Comment by yacdaniel** [comment]
Verified fixed.
