### ISSUE TITLE
[studio-ui] Conditional fields in content types 

### ISSUE THREAD

**Issue by T0P** [craftercms/craftercms#3710]
**Is your feature request related to a problem? Please describe.**

In a content type we have a plenty of fields, which we need for a template.
Sometimes we have the situation that there are dependencies between the fields.

_Example_:
Checkbox "Additional picture?" (Name: _hasAdditionalPicture_) is set

Then we have to insert text into:
- picture title
- URL

**Describe the solution you'd like**

Idea: We need a "condition" field for expressions, which we can use in content field types.

_Back to example_:

Input field "picture title", condition: ${hasAdditionalPicture}
- If field variable "hasAdditionalPicture" is evaluated as true, the field will be displayed for content editing, otherwise it will be hidden.
- If a field with a condition is hidden, the value should be empty.

**Describe alternatives you've considered**

At the moment all available fields will be displayed.
We want to reduce the amount of fields depending on the particular use case, especially for components.

**Comment by grundmann-thalia** [comment]
Two  variants of the above issue: 
1. Depending on a condition a field can be optional/mandatory (instead of visible / invisible)
2. Exactly one of two fields need to be set (XOR-Logic between two fields)

**Comment by sumerjabri** [comment]
This flows into the Form Engine 2.0. I will add these to the core requirements.

**Comment by sumerjabri** [comment]
Related docs that can help bridge the gap:
https://docs.craftercms.org/en/3.1/developers/extending-studio/control-plugins.html
https://docs.craftercms.org/en/3.1/developers/extending-studio/data-source-plugins.html

**Comment by sumerjabri** [comment]
Now part of Form Engine 2 requirements. Closing this ticket.
