### ISSUE TITLE
[studio-ui] Missing auth validations for site created from git repo

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3712]
## Describe the bug
The validations for the different Authentication methods when creating a site using a remote git repo are missing.

## To Reproduce
1. Create a site from a Remote Git Repository
2. Fill Site Id and Git Repo URL
3. Select the different Authentication methods leave them blank and click Review
4. No validations are shown and user can go to the Review page.

Also when the `Git Repo URL` is missing from a site from remote or a private blueprint the validation message should be updated.

## Expected behavior
Validations should me displayed and the user shouldn't be allowed to move to the next screen.

The validation when the `Git Repo URL` should be `Git Repo URL is required`

## Screenshots
No validations for auth and notice the validation for the missing `Git Repo URL`
![image](https://user-images.githubusercontent.com/6722074/70157189-c418c400-167a-11ea-983e-2d8b00baa1d6.png)

## Logs
N/A

### Version
`3.1.4`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by rart** [comment]
@yureii00 this work should be done on top of develop and forward-ported to 2019. You need to do this somehow manually due to the divergent directory structures and code formatting differences.

**Comment by yacdaniel** [comment]
@yureii00 When a site is created from remote and the authentication set to Private Key and you left it empty and click Review, the helper message isn't with the red color style as all the others validations. 
![image](https://user-images.githubusercontent.com/6722074/71188075-e9dec500-2245-11ea-8836-ae3e2f9669b9.png)

**Comment by yacdaniel** [comment]
Verified.
