### ISSUE TITLE
[studio-ui] Add float type for controls to be able to use decimals in prop types

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3713]
Right now we have a numeric-control input, that has properties to set a range (min-max) number allowed. The detail is that in form, we support decimal numbers, but we have no type for floats to allow decimal ranges. We need to add a new decimal type.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1476

**Comment by jvega190** [comment]
@yacdaniel please verify. Let me know if you need any details

**Comment by yacdaniel** [comment]
Verified decimals in Min-Max properties.
![image](https://user-images.githubusercontent.com/6722074/72270291-8cdaf280-35ea-11ea-8719-4e77fa4f4b98.png)
