### ISSUE TITLE
[studio] /api/2/dependency/dependencies wrong response when path contains a comma (,)

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3717]
## Describe the bug
When the parameter `path` contains a comma `,` the API  `http://localhost:8080/studio/api/2/dependency/dependencies?siteId=editorial&paths=/static-assets/item/images/1,2,3,4.jpeg` returns wrong hard dependencies:
```
{ 
 "response": { 
   "code": 0, 
   "message": "OK", 
   "remedialAction": "", 
   "documentationUrl": "" 
 }, 
 "items": { 
   "softDependencies": [], 
   "hardDependencies": [ 
     "2", 
     "3", 
     "4.jpeg", 
     "/static-assets/item/images/1" 
   ] 
 } 
}
```

## To Reproduce
1. Create a site from Editorial BP
2. Create a new Article page and add an image which name contains a comma `1,2,3,4.jpeg` 
3. In the Sidebar menu `Static-Assets` find the image and click `Approve & Publish` 
4. Click `Show All Dependencies` 

## Expected behavior
The item that contains a comma should display his dependencies correctly. 

## Screenshots
![image (4)](https://user-images.githubusercontent.com/6722074/70449372-7aa7ea80-1a67-11ea-8603-867ae7c6bca6.png)

## Logs
N/A

### Version
`3.1.5-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by sumerjabri** [comment]
Site Policy should help with this since it'll disallow these types of file names.

**Comment by sumerjabri** [comment]
Site policy now prevents this.
