### ISSUE TITLE
[docs] Document the new management authentication token

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3722]
A new authentication token is now configurable in all modules to protect monitoring APIs and similar. The full details are documented in the tickets:
https://github.com/craftercms/craftercms/issues/3578
https://github.com/craftercms/craftercms/issues/3577

More detail can be obtained from @dejan-brkic .

We need to document how to change the default token and when and where to use the token. (For example, monitoring.)

**Comment by sumerjabri** [comment]
@alhambrav a decision was made to move the configuration to set-env. Please stay tuned.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/903

**Comment by sumerjabri** [comment]
Verified.
