### ISSUE TITLE
[studio] Studio UI is missing token parameter for monitoring API requests

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3723]
When user is logged in, monitoring APIs will not require management token.

Update configurations to use the token value set as environment variable using the shell script

Provide token value for API calls between crafter modules.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/3726

**Comment by yacdaniel** [comment]
@dejan-brkic the new `token` parameter should be added to swagger docs?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1856

**Comment by yacdaniel** [comment]
Verified
