### ISSUE TITLE
[studio-ui] Improve Content Type Editor UI

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3724]
**Is your feature request related to a problem? Please describe.**
On `Site Config > Content Types`
1. The whole right sidebar could make better use of space
2. The command bar overlays the sidebar
3. Click on Content Types on the sidebar is always a bit disorienting as it doesn't show anything

**Describe the solution you'd like**
1. Improve space usage
2. Fix
3. Show something more evident when clicking the Content Types option

**Comment by rart** [comment]
@yacdaniel please work your magic to make sure changes didn't break anything. 🙂

**Comment by sumerjabri** [comment]
@alhambrav please queue the changes once final for screenshot updates.

**Comment by yacdaniel** [comment]
Verified. 
@alhambrav when screenshot updates are done please close the ticket. Assign back to Roy in case you found something.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/891

**Comment by alhambrav** [comment]
Verified by Yac and screenshots updated for Content Type Editor
