### ISSUE TITLE
[studio-ui] Tree highlight bugs

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3727]
## To Reproduce
Bug#1:
1. On the sidebar, open any tree up to make the container scrollable.
2. Position the cursor over any tree item to make it highlight
3. Scroll, you'll see that highlight doesn't hide when the scroll is not over the element.

Bug#2:
1. Go to the search page
2. Open any tree and check highlighting of elements (on hover)
3. Scroll down a little bit on the results page
4. Test highlighting of elements again, you'll see that highlight is not properly positioned.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1492

**Comment by jvega190** [comment]
@yacdaniel please verify, notice that is from `2019-11-ui-restructure` branch. Let me know if you need any details

**Comment by yacdaniel** [comment]
Verified fixed.
