### ISSUE TITLE
[studio] Get content API service does not set Content-Type header on response

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3728]
## Describe the bug
Get content API service does not set Content-Type header so in the response a default value is set by Tomcat or JVM which is not correct

## Expected behavior
Set Content-Type header value for response according to a content that is retrieved

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1855
https://github.com/craftercms/studio-ui/pull/1508

**Comment by yacdaniel** [comment]
Verified.
