### ISSUE TITLE
[studio-ui] Add new tool for encrypting text

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3732]
Please add a new section in the Site Config menu that allows users to encrypt text values, the tool only needs to provide an input field and show the result of the encryption.

The new API can be found at: `/api/2/security/encrypt`

**Comment by rart** [comment]
@jvega190, pull from my fork branch [feature/3732](https://github.com/rart/studio-ui/commit/9c14750282dc5404616e13484496eaf3d758f51f). The branch has the initial setup for this work...

Adds a "Encrypt Marked" button to config editor UI which searches the XML document for tags marked with attribute `encrypt=""` and use the encrypt service to replace the text with it's encrypted version and sets various validations around these process.

For example...
```
<some-doc>
  <some-tag encrypted="">password</some-tag>
```
gets transformed to something like...
```
<some-doc>
  <some-tag encrypted="true">blahblah/encryptedhashyadayadayada=</some-tag>
```

TODO:
- Add parse validation before saving the XML document (use provided). Display error and stop from saving until doc is valid.
- Translate all new added bits
- Replace alerts with styled dialogs
- As soon as you load site config page it navigates to "Configuration" and selects the "Sidebar Configuration" document. This is meant to help make dev quicker and should naturally be removed when done.
- Proper testing and verification (e.g. test feature, save and test that artifacts that use the xml keep working, etc...)

**Comment by jdrossl** [comment]
@rart @jvega190 we still need a way to encrypt values that will be used in other files (like yaml) is that included already?

**Comment by rart** [comment]
@jvega190, please add config to blueprints 
```
      <tool>
         <name>encrypt-tool</name>
         <label>Encryption Tool</label>
         <icon>
            <class>fa-lock</class>
         </icon>
      </tool>
```

**Comment by sumerjabri** [comment]
@jvega190 please make it a global tool, @rart will advise on design.

**Comment by jvega190** [comment]
studio-ui: https://github.com/craftercms/studio-ui/pull/1527
studio: https://github.com/craftercms/studio/pull/1865

**Comment by jvega190** [comment]
@jdrossl please add to upgradeManager

**Comment by jdrossl** [comment]
@yacdaniel @alhambrav please help us test & document this new feature

**Comment by yacdaniel** [comment]
@jvega190 please see if possible to escape the string, I been testing with values from https://owasp.org/www-community/password-special-characters 

@rart also I think we should handle the case when the API response with a status code different than 200 for example, the previous case returns 400 and the user is not aware of what happened
![encryp](https://user-images.githubusercontent.com/6722074/73377919-6f15ba80-4285-11ea-97b1-0d5ae13f87e8.gif)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1549

**Comment by alhambrav** [comment]
Documentation PR https://github.com/craftercms/docs/pull/914

**Comment by yacdaniel** [comment]
@rart ui is sending the request with the Content Type `application/x-www-form-urlencoded`. It should send it with `application/json`

**Comment by yacdaniel** [comment]
Also, we are missing the updates to POST & Content Type in `Site Config` still sending request as GET

**Comment by rart** [comment]
@yacdaniel 

https://github.com/craftercms/studio-ui/pull/1563
(feature/3732 on my fork)

**Comment by yacdaniel** [comment]
@rart the changes made to escape the text are no longer needed as the endpoint now uses POST. Please revert that.

**Comment by rart** [comment]
Done https://github.com/craftercms/studio-ui/pull/1568

**Comment by yacdaniel** [comment]
Verified.
