### ISSUE TITLE
[studio] There's a typo in logger message for publisher task

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3733]
## Describe the bug
There's a typo in the logger message for publisher task: ``Invaid site UUID. Local copy will not be deleted``

## Expected behavior
Fix the typo, from `Invaid` to `Invalid`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1888

**Comment by alhambrav** [comment]
Verified fixed.
