### ISSUE TITLE
Upgrade Elasticsearch to 7.2

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3736]
Upgrade Elasticsearch to latest 7.2

**Comment by jdrossl** [comment]
here is what I found after some quick tests with the latest ES:
```
1. ES is ready to drop Java 8 support (probably in the next release), that means we will need to catch up soon
2. Starting with ES 7 they have platform specific packages, that means we will need to make also platform specific bundles (linux vs macos)
3. We need to update the client in all Crafter modules to match the ES server version used, fixing any breaking changes in the way
```

**Comment by russdanner** [comment]
CI Requirements are 7.2.1. We will need to research compatibility.

**Comment by sumerjabri** [comment]
@jdrossl this is the high priority task for 3.1.8. Please ping me to discuss options on how to do this.

**Comment by jdrossl** [comment]
Breaking changes that affect sites:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response

@alhambrav we will need to include these in the release notes later

**Comment by jdrossl** [comment]
@rart please update the SDK & react blueprints as needed.

For the blueprints we might need to mark them as incompatible with versions previous to 3.2, reach out if you need more details
