### ISSUE TITLE
[studio] add asset processor to convert from 1 encoding to another

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3743]
**Is your feature request related to a problem? Please describe.**
Users want to upload content from a source encoding that is different from either the default encoding of Crafter CMS (UTF-8) or destination encodings and need a way to convert them.

**Describe the solution you'd like**
Add an asset processor for Studio that converts between two configured encodings and places creating new objects in the specified encoding at the specified path
https://docs.craftercms.org/en/3.1/developers/asset-processing.html

**Comment by sumerjabri** [comment]
We decide not to pursue this approach.
