### ISSUE TITLE
[studio] Add support for bucket storage publishing (preview -> staging -> live)

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3744]
**Is your feature request related to a problem? Please describe.**
When a single bucket is used between authoring and delivery assets are available to delivery as soon as they are uploaded in authoring.  While is is ok for some installations, others require that assets only be available to delivery after they haven been approved and published.

**Describe the solution you'd like**
Add the ability to publish from preview bucket to staging and live.

**Comment by avasquez614** [comment]
@russdanner what happens if an item is deleted? Should the asset be deleted from the S3 bucket if it's referenced no more?

**Comment by avasquez614** [comment]
on hold, need to discuss it with @sumerjabri

**Comment by sumerjabri** [comment]
@jdrossl please hold while we finish the design doc

**Comment by sumerjabri** [comment]
@jdrossl please proceed with detailed design and implementation based on the high-level design we agreed to. Please feel free to create child tickets and divvy up the work with @dejan-brkic as needed.

**Comment by yacdaniel** [comment]
@jdrossl please fix the scenarios we discuss:
- Assets are not displayed in delivery.
- Studio Search gets broken when assets are are uploaded.

**Comment by jdrossl** [comment]
@yacdaniel those issues are fixed now

**Comment by yacdaniel** [comment]
@jdrossl pls review this case
I have an asset published to live, then I edit and save the asset in sandbox. The state of the asset doesn't change to edited. 
![s3ToLive](https://user-images.githubusercontent.com/6722074/76627676-0b77e180-6501-11ea-84fc-68d6180ff036.gif)

**Comment by jdrossl** [comment]
@yacdaniel edit issues are fixed now

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/944

**Comment by russdanner** [comment]
Confirmed. 
There are publishing and deployment bugs that arise if staging is created and configure long after live pub target has been used fro some time. It may be a challenge to add staging "later." #3949
