### ISSUE TITLE
Error when creating a new blank site

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#3745]
I'm just trying to create a new site based on blank blueprint and getting error, site not created

1. Start crafter 3.1.4
2. Click on Create Site, choose Empty blueprint, fill id and click review
3. Click Create Site
4. Error is thrown

## Expected behavior
Should not throw any error and create the empty site properly

## Screenshots
![image](https://user-images.githubusercontent.com/813023/71598030-f3501300-2b0a-11ea-9b87-d6580d5cf96f.png)

## Logs
https://gist.github.com/asotog/6bb2ce62f4512aee8aa3f285ed2982ac
Also 
```
[INFO] 2019-12-30T13:47:22,234 [http-nio-8080-exec-2] [site.SiteServiceImpl] | Starting site creation process for site gplace from org.craftercms.blueprint.empty blueprint. 
[INFO] 2019-12-30T13:47:22,234 [http-nio-8080-exec-2] [site.SiteServiceImpl] | Creating deployer targets. 
[ERROR] 2019-12-30T13:47:22,242 [http-nio-8080-exec-2] [site.SiteServiceImpl] | Error while creating site: gplace ID: gplace from blueprint: org.craftercms.blueprint.empty. The required Deployer targets couldnt be created 
org.craftercms.commons.rest.RestServiceException: responseStatus = 404, errorDetails = html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /api/1/target/create_if_not_exists. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
```

### Version
Crafter CMS 3.1.4

### OS
Mac OS 10.14.5

### Browser
Chrome 79

## Additional context
Also happens when checking option Push the site to a remote git repo

**Comment by asotog** [comment]
UPDATE: restarted server after first brand new startup and now site can be created, but definitely something buggy there

**Comment by avasquez614** [comment]
@asotog we tried to reproduce and couldn't. this sounds like Elasticsearch or some other component didn't startup correctly, maybe because a port was already being used. I will close the ticket, but if you still see this issue, please check for any errors in `logs/tomcat/catalina.out` and `logs/deployer/crafter-deployer.out`, and re-open the ticket if it doesn't look like a port conflict.

**Comment by asotog** [comment]
thanks it could, not using docker for crafter but something failed on docker Mac app when i shut down crafter and started again

**Comment by ArthurGenet** [comment]
I have got the same issue on MacOS (doesn't know on other OS), I've downloaded Crafter with the bundles and I've tried to create a site (I tried all type of site but no one worked). I've been able to create a site once but I don't know the reason why it worked (I just shutdown and restarted multiple times)

**Comment by AhmedRiahi** [comment]
Faced same issue, deployer startup failure because I have setup environment variable  `LOGGING_LEVEL = debug`. **I have unset `LOGGING_LEVEL` and deployer started successfully.**
```

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'logging.level' to java.util.Map<java.lang.String, org.springframework.boot.logging.LogLevel>:

    Property: logging.level
    Value: debug
    Origin: System Environment Property "LOGGING_LEVEL"
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, org.springframework.boot.logging.LogLevel>]

Action:

Update your application's configuration
```

**Comment by sumerjabri** [comment]
Thank you @AhmedRiahi, please consider joining us on Slack at https://craftercms.com/slack to engage the community and developers.

**Comment by zhaojc** [comment]
4.0 have the same error

**Comment by zhaojc** [comment]
Internal server error: org.craftercms.studio.api.v1.exception.DeployerTargetException: Failed to create site 'aaaa' ID 'aaaa' based on blueprint 'org.craftercms.blueprint.editorial'. The deployer targets couldn't be created. Rolling back site creation.

**Comment by zhaojc** [comment]
and the docker compose donesnt supprt arm architecture

**Comment by zhaojc** [comment]
docker: Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found.
