### ISSUE TITLE
[studio-ui] Content Type: Insert expression for Destination Path Pattern and Postfix are broken

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3752]
## Describe the bug
The Insert expression for `Destination Path Pattern` and `Name / Variable Name` Postfix is broken, the user is not able to insert data with it. 

## To Reproduce
1. Create a site from an empty blueprint
2. Open the Entry Content Type
3. In the `Properties Explorer` click the `?` in  `Destination Path Pattern` 
4. Click any of the expressions, nothing happens.
5. In `Main Content` select `Title`, click the `?` in `Name / Variable Name` 
6. Click any of the expressions, nothing happens. 

## Expected behavior
When the expressions are clicked they are added in the appropriate way.

## Screenshots
![contentType](https://user-images.githubusercontent.com/6722074/72083074-d532a180-32c6-11ea-8d71-c6ed703ec2e2.gif)

## Logs
Firefox console `SyntaxError: expected expression, got '}' site-config:2`

### Version
`3.1.5-SNAPSHOT`

### OS
Linux

### Browser
Chrome / Firefox

## Additional context
N/A

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1522

**Comment by yacdaniel** [comment]
Verified fixed.

**Comment by yacdaniel** [comment]
Verified fixed.
