### ISSUE TITLE
[studio] Create dashboard API -- Part 1

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3753]
**Is your feature request related to a problem? Please describe.**
Crafter Studio and other consumers of Crafter Studio APIs want the ability to support user defined dashboards. Crafter Studio needs a flexible "dashboard" API that enables consumers to retrieve the content they want to show based on content and metadata criteria they define.

**Describe the solution you'd like**
Create a dashboard API that allows callers to query for content based on content and workflow metadata:
Examples include:
- type
- workflow state
- publishing status / environment
- create date
- modified date

**Comment by sumerjabri** [comment]
@dejan-brkic please start with OAS spec and send that for review.

**Comment by jrosler** [comment]
This may be inherent in the request, but we also want to be able to make updates through the dashboard as well (e.g. approve/publish, content updates, etc.), so in the dashboard UI we would need a way to access those beans or have a token in the session to make API calls.

**Comment by russdanner** [comment]
Hi @jrosler ,
Actions such as approve/publish will be handled by the existing services/APIs. This API is a read-only API that retrieves lists of content sliced and diced the way the consumer requests.

**Comment by sumerjabri** [comment]
@dejan-brkic we will start with a partial implementation (whatever we can provide based on the current DB schema) for:
* Audit
* Publishing
* Content

As spec'd: https://app.swaggerhub.com/apis/craftercms/studio/3.1.6.3#/dashboard

I'll file another ticket to complete the API spec

**Comment by dejan-brkic** [comment]
Part 1
PR:
https://github.com/craftercms/studio/pull/1903

**Comment by dejan-brkic** [comment]
Consolidated PR:
https://github.com/craftercms/studio/pull/1925

**Comment by sumerjabri** [comment]
@yacdaniel please add test cases. Please bear in mind this is still a work in progress (phase 1).

**Comment by yacdaniel** [comment]
@dejan-brkic some issues:
* the API parameter `sortBy` and `order` doesn't seem to take effect in the results of the API's: Audit,  Publishing & Content. The results are the same no matter what value is passed in the param. 

* Look at how the filters parameters are defined in the API spec for `/dashboard/content` and compare to the others 2 dashboard API's, where each filter is defined as a single parameter in the spec.

* `/dashboard/publishing?siteId=empty&filters.publisher=admin` the param `filters.publisher` doesn't seem to work, it returns results from all usernames. 

* Please check the date filters, there is an error when using it in any of the 3 dashboard API's 
```
org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors                                                                             
Field error in object 'publishingDashboardRequestParameters' on field 'filters.publishedDateFrom': rejected value [2020-03-26T14:14:59Z]; codes [typeMismatch.publishingDashboardRequestParameters.filters.publishedDateFrom,typeMismatch.filters.publishedDateFrom,typeMismatch.publishedDateFrom,typeMismatch.java.time.ZonedDateTime,typeMismatch]; arguments [org.springframework.conte
xt.support.DefaultMessageSourceResolvable: codes [publishingDashboardRequestParameters.filters.publishedDateFrom,filters.publishedDateFrom]; arguments []; default message [filters.publishedDateFrom]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.time.ZonedDateTime' for property 'filters.publishedDateFrom'; nested exception
 is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.ZonedDateTime] for value '2020-03-26T14:14:59Z'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2020-03-26T14:14:59Z]] 
```

**Comment by dejan-brkic** [comment]
Fixed sorting
https://github.com/craftercms/studio/pull/1937

**Comment by yacdaniel** [comment]
Verified part 1, `/dashboard/publishing` sort & order to be improved in next releases as we enhance our DB schemas.
