### ISSUE TITLE
[studio] Upload_asset service bad JSON response

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#3754]
## Describe the bug
The response from the Upload_asset service is not a JSON response

## To Reproduce
1. Upload a asset
2. See the network response

## Expected behavior
Should be a JSON response

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

![image](https://user-images.githubusercontent.com/10813283/72162893-61f16400-3388-11ea-9aff-5b2e58052881.png)

## Version
3.1.5-SNAPSHOT

**Comment by rart** [comment]
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/3928341/72223136-2c0cd500-356c-11ea-8e8b-ebb80400751b.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/3928341/72223139-34651000-356c-11ea-92e5-87bd6d1cefad.png">

**Comment by jdrossl** [comment]
@sumerjabri `asset-upload` doesn't exist in v4, it was replaced with the proper API

**Comment by sumerjabri** [comment]
@rart okay to close this?

**Comment by rart** [comment]
@jvega190 please check if service is still in used and close if it's not.

**Comment by jvega190** [comment]
Service is not being used in 4.0, closing
