### ISSUE TITLE
[studio-ui] Numeric input control issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3758]
## Describe the bug
Issues with the numeric input control

## To Reproduce
Steps to reproduce the behaviors:
Add a Numeric Input control in any Content Type: 
* Increase the `Display Size` Property, save the changes and go edit content, in the form notice that the length of the control is not increased. 
`Display Size` of control `numeric` is 50 and  `Display Size` of control `numeric2` is 100.
![image](https://user-images.githubusercontent.com/6722074/72289923-c3783380-3611-11ea-9cae-cdff96dda9d5.png)

* Use Firefox (Chome does not show the red box around the control).  Add properties  `Maximum` *10* and `Minimum`  *1*, save the changes and edit content, in the form enter a decimal valid number like `5.5` 
![image](https://user-images.githubusercontent.com/6722074/72289595-11d90280-3611-11ea-9ee4-e811af044a05.png)

* Add properties using decimals `Maximum` *9.9* and `Minimum`  *1.9*, save the changes and edit content, in the form enter the decimal value `5.5` and also `5` 
![image](https://user-images.githubusercontent.com/6722074/72289861-9a57a300-3611-11ea-9763-c66ca6261ac7.png)
![image](https://user-images.githubusercontent.com/6722074/72289839-8ca21d80-3611-11ea-8da5-9a735a3f2d34.png)

## Expected behavior
* Display size should change in the content editor's form.
* Decimal values are allowed when the `Maximum` and `Minimum` are set to integers or decimal values. When these properties are not set the decimal values should be allowed also. 
* There is a red rectangle around the controller when the values are not met. The red rectangle should be visible in Chrome (Right now only shows in Firefox) 
* It would be good to have a verification when the values of the 'Maximum' and 'Minimum' properties are set, so we do not end up with maximum values that are really minimum values or the other way around.

### Version
`3.1.5-SNAPSHOT`

### OS
Any

### Browser
Chrome and Firefox

## Additional context
N/A

**Comment by sumerjabri** [comment]
Will address in the new form engine.
