### ISSUE TITLE
[studio] Bulk publish after bulk upload assets does not publish everything - race condition

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3764]
Steps to reproduce:
1. create a new site
2. right-click on the tree to create `craftercms_test/folder_1` on `static-assets`
3. right-click on `folder_1` and choose “Bulk upload”,
4. Drag & Drop files (500 images 2M size) to the zone
5. Click Done
6. Go to Site configuration and select bulk publish
7. Input `/static-assets/craftercms_test/folder_1/` to the path, input comment the click “Publish”
8. Not all images are copied to the published repo (199 in the test to reproduce the issue)

**Comment by dejan-brkic** [comment]
The original issue does not exist anymore.
The new upload dialog, new Item table, and new publishing mechanics helped to fix this issue.
If there is a race condition issue, most probably it can appear on some operations executed directly on the git repository.

**Comment by dejan-brkic** [comment]
PR: 
https://github.com/craftercms/studio/pull/2474

**Comment by yacdaniel** [comment]
Verified as not reproducible in 4.0.0 with recent improvements.
