### ISSUE TITLE
[studio-ui] Parameter "token" missing from call to /api/1/monitoring/log.json

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3766]
## Describe the bug
There is an error in the logs that `Required String parameter 'token' is not present` when you click on `Log Console` from `Site Config`

## To Reproduce
1. Create a site using the website editorial bp
2. Click on `Site Config`
3.  Right click on the browser and select `Inspect`, then click on `Network` 
4. Click on `Log Console` and notice the error.  It seems like the call to `/api/1/monitoring/log` does not include the required `token` parameter

![Screen Shot 2020-01-21 at 11 15 13 AM](https://user-images.githubusercontent.com/25483966/72823199-4ec07d00-3c41-11ea-8a0f-58f731cd4e16.png)

Check the tomcat logs and notice the error there too.
Here's the error in the tomcat log:
```
[ERROR] 2020-01-21T11:00:38,015 [http-nio-8080-exec-5] [mysite] [rest.ExceptionHandlers] | Request for /api/1/monitoring/log.json failed
org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'token' is not present
```

## Expected behavior
Parameter `token` should be added to api call so there are no errors when viewing log console

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.5-SNAPSHOT-be2203
Build Number: be2203016285e1f305af2cfd4cc320fea974e934
Build Date/Time: 01-21-2020 10:32:33 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@dejan-brkic I'll assign it to you to see what can be done with the token

**Comment by sumerjabri** [comment]
@dejan-brkic I think having Studio proxy these calls and inject the token is the way to go.

The token should flow through Studio Config, and the UI will never see it (it calls the proxy).

Please send a proposed API spec and we can start the discussion.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/3785

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by yacdaniel** [comment]
@rart it seems that the API works but in the UI the Log Console doesn't show any entry
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1875

**Comment by yacdaniel** [comment]
Verified fixed.
