### ISSUE TITLE
[studio-ui] Create the Receptacles ICE Panel

### ISSUE THREAD

**Issue by yureii00** [craftercms/craftercms#3767]
**Is your feature request related to a problem? Please describe.**
When using ICE, users should be able to view the list of welcoming receptacles

**Describe the solution you'd like**
Doing click on components panel> option 'list of welcoming receptacles', should show a list of receptacles, also should highlight those. 

<img width="502" alt="Captura de Pantalla 2020-01-21 a la(s) 15 44 23" src="https://user-images.githubusercontent.com/10813283/72845772-ef746400-3c64-11ea-9c39-a616c654d119.png">

**Comment by rart** [comment]
👍🏻
