### ISSUE TITLE
[studio-ui] site-component DS unable to send extra values

### ISSUE THREAD

**Issue by AlexOvR** [craftercms/craftercms#3768]
**Is your feature request related to a problem? Please describe.**
On version 3.1.0 the DS for site-component was able to send extra parameters , we need this functionality since we managed to use this behavior in order to communicate between different components, on version 3.1.4 it seems like the site-component DS is restricted to just a key & value, which is limiting the custom functionalities that we build up.

**Describe the solution you'd like**
We like to have this functionality back or at least an option to allow the DS to be able to send/receive extra custom parameters.

**Comment by sumerjabri** [comment]
@russdanner please test and validate

**Comment by russdanner** [comment]
Confirmed.
