### ISSUE TITLE
[studio] Remove encoding changes made for PR 1853

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3769]
We've build a more general alternative solution for this need and thus would like to back out the updates made by this pull request.

https://github.com/craftercms/studio/pull/1853

**Comment by dejan-brkic** [comment]
Encoding changes are in these PRs
https://github.com/craftercms/studio/pull/1855
https://github.com/craftercms/studio-ui/pull/1508

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1867
https://github.com/craftercms/studio-ui/pull/1537

**Comment by russdanner** [comment]
Confirmed
