### ISSUE TITLE
[studio-ui] When Select All is checked and the user moves to next page results, Select All still checked but no items selected

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3770]
## Describe the bug
 When Select All is checked and the user moves to next page results,  the `Select All` checkbox still selected but there are no items selected in the Search result.

## To Reproduce
1. Create a site from Editorial BP
2. Go to Studio Search
3. Check the `Select All` checkbox
4. Move to the next search page result. 

## Expected behavior
`Select All` is not checked, as there are no items selected.

## Screenshots
![studiosearch2](https://user-images.githubusercontent.com/6722074/72917457-7ed35300-3d09-11ea-919c-11ff2ef4ad95.gif)

## Logs
N/A

### Version
```
3.1.5-SNAPSHOT
studio-ui develop branch
```

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by rart** [comment]
@yureii00 assess complexity and let me know before fixing.

**Comment by yacdaniel** [comment]
Verified fixed.
