### ISSUE TITLE
[studio] Internal Server Error when get_delete_package is sent with no values for path parameter

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3776]
## Describe the bug
When the user does not send values for the `paths` parameter in the `content/get_delete_package` API response is HTTP code 500 Internal Error

## To Reproduce
1. Create a site based on any BP
2. `curl -v --cookie "XSRF-TOKEN=A_VALUE;JSESSIONID=$cookie" -H "X-XSRF-TOKEN:A_VALUE"  -X GET "http://localhost:8080/studio/api/2/content/get_delete_package?siteId=mysite&paths=" -H  "accept: application/json"  -H "Content-Type: application/json" `
3. See response 
```
{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}
```

## Expected behavior
There should be no Internal Error when paths are missing, maybe an HTTP 400 Bad Request response?

## Screenshots
When an item is unchecked in the Delete dialog.
![getdeletepackage](https://user-images.githubusercontent.com/6722074/73281159-2989bc80-41b5-11ea-9bc2-a6ee863caa06.gif)

## Logs
https://gist.github.com/yacdaniel/20f265375f615e8b8aa830d6f04da9ed

### Version
`3.1.5-SNAPSHOT`

### OS
Linux

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1889

**Comment by yacdaniel** [comment]
Verified fixed, response is 
```
{"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"items":{"dependentItems":[],"childItems":[]}}
```
