### ISSUE TITLE
[studio][docs] Update Editorial BP SuggestionHelper.groovy and Search with Elasticsearch doc with postfixs

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3777]
## Describe the bug
The script [SuggestionHelper.groovy](https://github.com/craftercms/studio/blob/master/src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/scripts/classes/org/craftercms/sites/editorial/SuggestionHelper.groovy#L27)  from Editorial BP is missing the postfix in `DEFAULT_SEARCH_FIELD = "subject"`   

Images and scripts examples should be updated with the postfix  feature in https://docs.craftercms.org/en/3.1/developers/search-elasticsearch.html 

### Version
`3.1.5-SNAPSHOT`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/1871
PR https://github.com/craftercms/docs/pull/904

**Comment by yacdaniel** [comment]
Verified fixed.
