### ISSUE TITLE
[studio-ui] empty Global menu (no selection)

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3778]
## Describe the bug
In some scenarios the global menu shows empty (with no selection). For example clicking on the global menu icon while being already there, or clicking on the global menu icon while being on the settings view.

## Expected behavior
Global Menu should always show a default view

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1543

**Comment by jvega190** [comment]
@yacdaniel can you please verify?

**Comment by yacdaniel** [comment]
@jvega190 sure 👍

**Comment by yacdaniel** [comment]
Verified Global Menu always show a default view.

**Comment by rart** [comment]
https://github.com/craftercms/studio-ui/pull/1543 seems to have broken direct navigation to internal routes. Directly navigating to anything but `/sites` takes you to `/sites`

**Comment by jvega190** [comment]
@yacdaniel can you please verify again?

**Comment by yacdaniel** [comment]
Verified.

**Comment by yacdaniel** [comment]
@yureii00 
looks like when the user is not authenticated it could view the static pages from Global Menu items like
http://localhost:8080/studio/#/globalMenu/audit.
If the user goes to http://localhost:8080/studio it takes you to globalMenu static page.

There should be a redirect to login page when user is not authenticated. 
![usernotlogged](https://user-images.githubusercontent.com/6722074/74440084-f856f080-4e32-11ea-8acd-fb1effd0170b.gif)

**Comment by jvega190** [comment]
@yacdaniel Issue is not related to this. It'll be fixed in another ticket.
