### ISSUE TITLE
[docs] Please update craftercms_sphinx_theme

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3786]
**Is your feature request related to a problem? Please describe.**
Please update craftercms_sphinx_theme,  `script_files` appended by the theme were deprecated in sphinx-doc.

Here's the waning message that you will see when building the docs:
```
RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
```

**Describe the solution you'd like**
It would be nice to have no warnings about deprecated files when building

**Describe alternatives you've considered**

**Additional context**
Here is an issue mentioning the same warning about deprecated `script_files` with resolution:
https://github.com/sphinx-doc/sphinx/issues/6088

**Comment by jvega190** [comment]
@alhambrav the warning is a bug in version ~2.3.1, when updated to latest the warning is not showing anymore. Please let me know if you need something.

**Comment by alhambrav** [comment]
Verified warning is gone after updating sphinx-doc to 3.1.2 and closing ticket.
