### ISSUE TITLE
[studio-ui] Disallow names with hyphen for content type fields

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3790]
GraphQL disallows names with hyphens per spec. When a content has a field with hyphens, hyphen would get transformed to double underscore for the GraphQL queries. 

We should also disallow hyphens to maintain consistency and avoid discordance/confusion in content retrieval and field usage.

**Comment by sumerjabri** [comment]
Hyphens are also a problem for FTL.

We must remember that some core model names have hyphens and must either be tolerated or migrated (the system must remain backward compatible with existing content and older models).

**Comment by rart** [comment]
(I vote migrated.)

**Comment by rart** [comment]
Please check if we can do anything for pasting using the mouse. If you right click the field and paste something with a hyphen, it remains.

**Comment by rart** [comment]
👍
