### ISSUE TITLE
[engine] Add an API to get the status of a site

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3795]
Add an API under `/api/1/site/context/status` that returns the status of the current site context (`CREATED`, `INITIALIZED`, `DESTROYED`). The response body of the API should be the like the following:

```
{
   "status": "CREATED"
}
```

**Comment by sumerjabri** [comment]
@avasquez614 How about:

- Initializing
- Ready
- Destroyed

Since CREATED implies ready. Initialized doesn't imply ready.

**Comment by avasquez614** [comment]
The status I listed are the current ones but yeah I agree with the new ones. @jdrossl what do you think?

**Comment by jdrossl** [comment]
Yeah, I think `Initializing` & `Ready` make it more clear

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 should this new endpoint be protected with the management token?

**Comment by sumerjabri** [comment]
@jdrossl I think that makes sense.

**Comment by sumerjabri** [comment]
@yacdaniel please validate and close if correct.

**Comment by yacdaniel** [comment]
Verified.
