### ISSUE TITLE
[studio-ui] Use new Engine API to check when a site is ready

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3796]
A new API will be added to return when a site context is ready: https://github.com/craftercms/craftercms/issues/3795. When Studio is creating the site, the UI needs to use this API to check when the site is ready to be displayed in preview (status = `READY`). If the site is not ready, then the UI can display some waiting icon like a wheel.

**Comment by sumerjabri** [comment]
Add a button to the page:
```
Could not resolve site for the current request.
```

called "Retry" and it will reload the current page.

**Comment by avasquez614** [comment]
Verified
