### ISSUE TITLE
[studio] Compare to Current not working

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3797]
## Describe the bug
Compare to current returns a server error.

## To Reproduce
1. Create a site from any BP
2. In the Home page click the `History` option
3. Click the `Compare to Current` action

## Expected behavior
Diff of the compare is displayed. 

## Screenshots
![imagen](https://user-images.githubusercontent.com/6722074/73784010-506a6480-475a-11ea-979a-c093db57350e.png)

## Logs
catalina.out log
https://gist.github.com/yacdaniel/6d7286a59f82974c86451b55207fee43

### Version
`3.1.5-SNAPSHOT`

### OS
MAC

### Browser
Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1879

**Comment by yacdaniel** [comment]
Verified fixed.
