### ISSUE TITLE
[studio-ui] Add description of attribute to be used on mouse-over of "Encrypt Marked" button in Configuration

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3800]
**Is your feature request related to a problem? Please describe.**
Add description of attribute to be used on mouse-over of "Encrypt Marked" button when you open a configuration from `Site Config` -> `Configuration` or something like that to give the user a hint on the attribute to be used to mark for encryption 

**Describe the solution you'd like**
It would be nice to display some description underneath the `Encrypt Marked` button on how it works on mouse-over (or something like that)

![Screen Shot 2020-02-05 at 11 49 27 AM](https://user-images.githubusercontent.com/25483966/73864065-05f6ef80-480f-11ea-9360-e73068b28474.png)

Something like, `To mark items for encryption, add the attribute 'encrypted=""'. Example: <some-tag encrypted="">xxxx</some-tag>`

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
@jvega190 copy:

```
By adding the `encrypted=””` attribute to a tag on the config document you mark it for encryption. By pressing the “Encrypt Marked” button, the system will encrypt the inner text of each of the marked tags. Use the `encrypted=””` attribute only on tags which directly hold the value to be encrypted (text). Don’t add the attribute on tags that contain other tags - unless you actually want to encrypted a chunk of XML. The encrypted text result will be in the form of `${enc:..}`. This wrapping is a hint to the system that this is an encrypted value. Please do not manipulate encryption results manually.
```

**This effort is comprised of two pieces:**

![encrypt-hints](https://user-images.githubusercontent.com/3928341/75982490-10c4a300-5ee7-11ea-9b2e-635e52862340.png)

1. Add hint text below the config XML editor
2. Add an info icon which displays the same hint text as a dialog when the icon button is pressed

![encrypt-hints-dialog](https://user-images.githubusercontent.com/3928341/75982498-15895700-5ee7-11ea-8c3e-28ce04f8600e.png)

**Notes** 
* All text should be translated. Use the same key for both messages. 
* The message below the config XML editor should only show when a config file selected.

**Comment by alhambrav** [comment]
Hi!
I think there's a typo in the help message:
'''
By adding the `encrypted=””` attribute to a tag on the config document you mark it for encryption. By pressing the “Encrypt Marked” button, the system will encrypt the inner text of each of the marked tags. Use the `encrypted=””` attribute only on tags which directly hold the value to be encrypted (text). Don’t add the attribute on tags that contain other tags - unless you actually want to **encrypted** a chunk of XML. The encrypted text result will be in the form of `${enc:..}`. This wrapping is a hint to the system that this is an encrypted value. Please do not manipulate encryption results manually.
'''

Change `encrypted` to `encrypt` so the sentence reads like:  `unless you actually want to encrypt a chunk of XML.

Also, what do you think about adding some line breaks to the help message so it looks something like this instead (Please note the spaces between paragraphs, so it does not look like one big blob of text?):

```
To encrypt a tag, (1) mark the desired tags for encryption, then (2) click on the "Encrypt Marked" button. 

(1) Mark your tag/s for encryption by adding the attribute `encrypted=""`. 
Example: <accessKey encrypted="">AKIAIOSFODNN7EXAMPLE</accessKey>

(2) Click on the `Encrypt Marked` button, and your tag should now look like:
<accessKey encrypted="true">${enc:xeJW23SomeEncryptedValuesListedHere</accessKey>

Remember:
* Use the `encrypted=””` attribute only on tags which directly hold the value to be encrypted (text). * Don’t add the attribute on tags that contain other tags - unless you actually want to encrypt a chunk of XML.
* Do not manipulate encryption results manually.
```

**Comment by rart** [comment]
"To encrypt a tag" => "To encrypt the content of a tag"

@jvega190

**Comment by alhambrav** [comment]
Verified fixed.
