### ISSUE TITLE
[videocenter] Remove deprecated aws-video-upload control

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3802]
## Describe the bug
Remove the control `aws-video-upload` which uses a deprecated API. Later we should add a video control with the new aws datasources.

## Expected behavior
`aws-video-control` removed from the BP

## Screenshots
![image (5)](https://user-images.githubusercontent.com/6722074/73946472-98ed6380-48bb-11ea-88ea-b88c9afe3a08.png)

## Logs
N/A

### Version
`3.1.5-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jdrossl** [comment]
@sumerjabri should we do a release just for this change?

**Comment by sumerjabri** [comment]
@jdrossl yes, we should. Update the plugin YAML file and let's tag it and cut a new release for 3.1.6/7 and 3.2

**Comment by yacdaniel** [comment]
@jdrossl looks like the control was added back to the bp. Please fix it.

**Comment by jdrossl** [comment]
@sumerjabri should we release a new version for this?

**Comment by sumerjabri** [comment]
@jdrossl @yacdaniel new version v1.1.5 released.

**Comment by yacdaniel** [comment]
Verified fixed in videocenter BP 1.1.5
