### ISSUE TITLE
[core][engine] REST API responses changed format

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3804]
Because of the changes made for https://github.com/craftercms/craftercms/issues/3755 some API responses have changed, for example `/api/1/site/content_store/descriptor`

**Comment by sumerjabri** [comment]
Per our conversation, we must fix the responses to match what they were.

**Comment by jdrossl** [comment]
@jvega190 please confirm that the JS SDK is returning the expected format again

**Comment by jvega190** [comment]
verified
