### ISSUE TITLE
[studio-ui] Complete community PR translations

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3806]
The community PR doesn't update all translations
https://github.com/craftercms/studio-ui/pull/1564

Also, need to update 2019 branch.

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1571

**Comment by jvega190** [comment]
2019 branch: https://github.com/craftercms/studio-ui/pull/1572

**Comment by sumerjabri** [comment]
@jvega190 is this done? If so, assign to reported for validation.

**Comment by yacdaniel** [comment]
Verified.
