### ISSUE TITLE
[studio-ui] Content Tree Panel

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3809]
![image](https://user-images.githubusercontent.com/3928341/74343750-d2d2d400-4dab-11ea-8a9f-6a096ce27d33.png)

<img width="995" alt="panel-flow-1" src="https://user-images.githubusercontent.com/3928341/74344251-994e9880-4dac-11ea-8516-0292f2c3ba0d.png">

<img width="770" alt="panel-flow-2" src="https://user-images.githubusercontent.com/3928341/74344266-9e134c80-4dac-11ea-919e-84a294977e53.png">

**Comment by rart** [comment]
Please fix incorrect field indentation:

![image](https://user-images.githubusercontent.com/3928341/78350390-6a32f700-75a5-11ea-9ac2-95d833b00048.png)

**Comment by rart** [comment]
- [ ] Implement click to select/lock for drag
- [ ] R&D d&d within the tree

**Comment by aachavarria** [comment]
Request changes on the UI

<img width="626" alt="Captura de Pantalla 2020-07-06 a la(s) 08 56 18" src="https://user-images.githubusercontent.com/10813283/86607504-91afac00-bf66-11ea-869c-4f83a909c79d.png">

**Comment by rart** [comment]
👍
