### ISSUE TITLE
[studio-ui] Reactify Quick Create

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3811]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/3928341/74348019-5099de00-4db2-11ea-93cd-4d3d4fa3cb61.png">

==>

![image](https://user-images.githubusercontent.com/3928341/74348033-58598280-4db2-11ea-838b-8c81524d274f.png)

**Comment by rart** [comment]
Please handle service errors. Use GlobalDialogManager.

**Comment by jvega190** [comment]
Handling errors was done in here https://github.com/craftercms/studio-ui/pull/1749

**Comment by rart** [comment]
👍🏻
