### ISSUE TITLE
[studio] Validate session not added to global repo overrides as public url

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3816]
Validate session is public URL now and is not added to YAML configuration file inside the global repository.

Workaround:
Update `crafter-authoring/data/repos/global/configuration/studio-config-override.yaml` to have following property
```
studio.security.publicUrls: >
  /api/1/services/api/1/server/get-available-languages.json,/api/1/services/api/1/server/get-ui-resource-override.json,
  /api/2/monitoring/.+,/api/2/users/forgot_password,/api/2/users/set_password,/api/1/services/api/1/security/validate-session.json
```

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/1885

**Comment by yacdaniel** [comment]
Verified validate session is added to global repo override as public url. Upgrade from 3.1.4 to 3.1.5
