### ISSUE TITLE
[studio] API2 dep calc doesn't work for mandatory parent

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3819]
## Describe the bug
Publishing a new child page of a new parent page doesn't show the parent in the publishing deps dialog nor update the item state (even though the page is indeed published).

## To Reproduce
1. Create a site from Editorial BP
2. Copy 2017 folder and paste it in Articles
3. Paste it again in Men's Styles for Winter under the new `2017-xxxx/01/Men's Styles for Winter`
4. Publish a leaf child page and see the parent Men's Styles for Winter remain in workflow state new unpublished

## Expected behavior
While the publishing system does indeed work and the parent page is published, it's not reported in the publishing dialog nor is the item state updated.

## Logs
N/A

### Version
3.1.5-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1887

**Comment by yacdaniel** [comment]
Verified the parent is published and parent items are in the Hard Dependencies section after clicking Show All 
![publisherror](https://user-images.githubusercontent.com/6722074/74771418-bb846280-5253-11ea-9b7a-f0b79fd21bd7.gif)
