### ISSUE TITLE
[studio] DnD error dialog cannot be dismissed

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3821]
## Describe the bug
{{A clear and concise description of what the bug is.}}

## To Reproduce
1. create site based on this repo
https://github.com/russdanner/react-cart-dnd
2. Open Page Components
3. See error, this cannot be dismissed

## Expected behavior
Dialog should be dismissable

## Screenshots
https://www.loom.com/share/665b2786c16b4f71a737561e8d1408aa

## Logs
N/A

### Version
Studio Version Number: 3.1.5-SNAPSHOT-fac2cf
Build Number: fac2cf3437c0f6f56effbbcabbe665119fb0ed74
Build Date/Time: 02-16-2020 09:02:56 -0500

### OS
Any

### Browser
Chrome/all

## Additional context
You can work around the issue by clearing cookies OR switching sites and clicking done to close the DnD panel.

**Comment by yacdaniel** [comment]
Verified fixed, dialogs can be dismissed.
![dnddialogs](https://user-images.githubusercontent.com/6722074/74985488-28872c00-53fd-11ea-8527-dac69744c15d.gif)
