### ISSUE TITLE
[studio] Image/video preview in cms search cannot be cancelled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3822]
## Describe the bug
User should be able to cancel and continue from an image preview in CMS search.
Hitting the escape button works BUT a cancel button/x should be available and visible to the user

## To Reproduce
1. Create a site based on editoriua
2. Go to CMS search
3. Find an image and click preview

## Expected behavior
User should be able to easily and obviously cancel the preview and continue working

## Screenshots
https://www.loom.com/share/31487f0450574d2f9b6eb6100d86bc09

## Logs
N/

### Version
Studio Version Number: 3.1.5-SNAPSHOT-fac2cf
Build Number: fac2cf3437c0f6f56effbbcabbe665119fb0ed74
Build Date/Time: 02-16-2020 09:02:56 -0500

### OS
N/a

**Comment by yacdaniel** [comment]
@jvega190 please check this case: 
2000 pixel image in a 1280x800 screen
![image (9)](https://user-images.githubusercontent.com/6722074/75045384-d390f780-5488-11ea-9061-09103454ad30.png)

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/75895289-0b8a2a00-5dfb-11ea-81ce-f7bfb40855fc.png)
