### ISSUE TITLE
[graphql] be able to alias a field of a component

### ISSUE THREAD

**Issue by mjhost** [craftercms/craftercms#3823]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by the fact that changing the primitive reference of a field it changes name in the schema ex. `foo_s` -> `foo_i`

**Describe the solution you'd like**
a way to alias `foo_s` -> `foo` such as that if i need to change to `foo_i` i can have the alias to `foo` alive

**Describe alternatives you've considered**
i've considered wrapping crafer graphql api as described in <https://docs.craftercms.org/en/3.1/developers/cook-books/graphql/custom-graphql-schema.html> but it would create a "useless" layer

**Comment by sumerjabri** [comment]
Will be supported by FE2's field definition (can be emitted as a field attribute or similar which feeds the rest of the machinery). Will add to the requirements.
