### ISSUE TITLE
Crafter 3.1.4: Delete-dialog shows each child item twice

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#3826]
## Describe the bug
 Delete-dialog shows each child item twice on any page.

## To Reproduce
1. Install Crafter 3.1.4
2. Create page with a component (child-item)
3. Right-Click on page
4. Select Delete

## Expected behavior
Each child-item is shown once

## Screenshots
Page 'foo' with **one** component
![image](https://user-images.githubusercontent.com/58164705/74853119-c3203600-533d-11ea-86d3-0cad26556bb6.png)

### Version
3.1.4

### OS
Fedora 30

### Browser
Chrome 80

**Comment by grundmann-thalia** [comment]
BTW: Our users would appreciate to see the names of the child items (like it is shown for the page) - not only the filename.

**Comment by yacdaniel** [comment]
Hi @grundmann-thalia the next version `Crafter CMS 3.1.5` will contain the fix for the duplicated child item. The name of the child item to remove will be worked in the `3.1.6` release https://github.com/craftercms/craftercms/issues/3838 . Thanks for your report!

**Comment by yacdaniel** [comment]
Verified fixed.
