### ISSUE TITLE
[studio-ui] "Close this form without saving" dialog not clickable

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3832]
## Describe the bug
"Close this form without saving" dialog not clickable after making a change to the `Page URL` field then canceling the edit by clicking on `Cancel` on the form

## To Reproduce
1. Create a site using the website editorial bp
2. Edit an article, for our example, we're editing `Women styles for winter`
3. Click the `Edit` button on the `Page URL` field of the form, then click `OK`
4. Make some changes
5. Click on `Cancel` to discard the change we made to the `Page URL`
6. Notice that the `Close this form without saving` dialog is not clickable

![Screen Shot 2020-02-19 at 2 48 29 PM](https://user-images.githubusercontent.com/25483966/74870680-21dab500-5328-11ea-99ac-c7c5763a5b96.png)

## Expected behavior
The `Close this form without saving` dialog should be clickable

## Screenshots
Here's a short clip:
https://www.loom.com/share/303972f8b7ce4326a113c7e162fde7fa

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.5-SNAPSHOT-4cfb5c
Build Number: 4cfb5c4b475273f85a0d28ca2f5e2f8308d267c7
Build Date/Time: 02-19-2020 12:25:18 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Hi!
 It looks like the dialog asking if you want to close the form without saving does not pop up after clicking on the cancel button.

Here's a short clip:
https://www.loom.com/share/9229380510b4496e8f7b541120c4932e

**Version**
Studio Version Number: 3.1.5-SNAPSHOT-4cfb5c
Build Number: 4cfb5c4b475273f85a0d28ca2f5e2f8308d267c7
Build Date/Time: 02-20-2020 09:44:42 -0500

**Comment by rart** [comment]
Stand by for merge of https://github.com/craftercms/studio-ui/pull/1590

**Comment by sumerjabri** [comment]
Merged and ready.

**Comment by alhambrav** [comment]
Verified fixed.
