### ISSUE TITLE
[studio-ui] Edit page url dialog message is hard coded (not translated)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3834]
<img width="1201" alt="Screen Shot 2020-02-20 at 9 01 11 AM" src="https://user-images.githubusercontent.com/3928341/74912776-a2002980-53bf-11ea-8f44-1981c69dccd0.png">

<img width="481" alt="Screen Shot 2020-02-20 at 9 01 31 AM" src="https://user-images.githubusercontent.com/3928341/74912777-a3c9ed00-53bf-11ea-8081-73b6cd1243a8.png">

**Comment by yacdaniel** [comment]
@rart please assign back when translations are in place.

**Comment by rart** [comment]
Verified via code inspection. 👍🏻
