### ISSUE TITLE
[studio-ui] Zoom-Button for images not working

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#3835]
## Describe the bug
When I open a content-type to edit its properties nothing happens when I click the zoom-button related to an uploaded image (see screenshot)

## To Reproduce
1. Create content-type with image-property
2. Upload image
3. Click on magnifiying lens shown in the upper right corner of the image

## Expected behavior
Magnified image as an overlay similar to the one that is shown when I click on the magnifying-lens of an image within search results.

## Screenshots
![image](https://user-images.githubusercontent.com/58164705/74914190-48e5c500-53c2-11ea-8c2e-91be18855e8d.png)

### Version
Crafter 3.1.4

### OS
Mac OS X 10.15

### Browser
Chrome 80

**Comment by yacdaniel** [comment]
Verified fixed. The fix goes in the next `3.1.6` release @grundmann-thalia . Thanks for your report!
![zoomVideo](https://user-images.githubusercontent.com/6722074/75565616-e751d600-5a13-11ea-9bc8-93a8c344d486.gif)
