### ISSUE TITLE
[studio-ui] The cursor should be in the new section(rte) added in the form when clicking "Add Another" in website editorial

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3836]
## Describe the bug
When clicking on `Add Another` in the `Sections` part of the form when editing a page content type in the website editorial bp, the cursor is not inside the new section added

## To Reproduce
1. Create a site using the website editorial bp
2. Navigate to one of the articles then edit it
3. Scroll down to the `Sections` portion of the form then click on `Add Another`
4. Notice that there's no cursor inside the new section (rte) added

<img width="1266" alt="Screen Shot 2020-02-20 at 7 46 00 AM" src="https://user-images.githubusercontent.com/25483966/74934928-4892fd00-53b5-11ea-8e09-a29fc3913da1.png">

## Expected behavior
It would be nice if the cursor is in the new section(rte) added in the form when clicking "Add Another" in website editorial page content type

## Screenshots
Here's a short clip:
https://www.loom.com/share/9ce260f3232640c688b9ff825ce59647

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.5-SNAPSHOT-4cfb5c
Build Number: 4cfb5c4b475273f85a0d28ca2f5e2f8308d267c7
Build Date/Time: 02-19-2020 12:25:18 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Will be addressed in FE2.
