### ISSUE TITLE
[videocenter-bp] Update blueprint to use media convert

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3837]
## Describe the enhancement
Today Crafter CMS supports both media convert AND elastic transcoder.  Media convert is the preferred platform going forward.  Update the blueprint to use media convert and make sure when videos are uploaded to S3 that the play leverages the specified renditions.

**Comment by avasquez614** [comment]
Done

**Comment by russdanner** [comment]
confirmed
