### ISSUE TITLE
[studio-ui][studio] Login mechanism improvements

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3841]
## Describe the bug
- After Studio first starts up and then user goes to login page, the login page is trying to access `studio/api/2/monitoring/version` without being logged in which results in a invalid token.
- The login page shares the same url and code to the login system; would be best to keep login page isolated and internal pages full protected under authorisation. This causes some requests to fail prior to authentication.

## To Reproduce
1. Do a clean build deploy and start up Studio
2. Go to http://localhost:8080/studio/
3. Check studio's tomcat log, there is an error about `studio/api/2/monitoring/version` being accessed without the management token.
4. Observe the network panel prior being logged out.

## Expected behavior
- Login page should not try to access `studio/api/2/monitoring/version`, because it requires the `token` parameter which is only passed when user is authenticated.
- Login page should be a reserved URL, not shared with the user dashboard (`/studio` route).
- The `/studio` route should be protected by auth control like any other internal page. 
- The system should redirect to `/studio/login` when there’s no valid user session. When there's a referrer, it should include a query string param named `redirect` with the referrer Url, which will be used to redirect the user back once authenticated to the page that was attempted to access prior to logging in.

## Screenshots
First login after start up, notice the call to `/monitoring/version` API
![image (10)](https://user-images.githubusercontent.com/6722074/75073054-4ff1fd80-54be-11ea-86fc-5e8eb6e773cc.png)
Any login after the first one, no API call to `/monitoring/version`
![image (11)](https://user-images.githubusercontent.com/6722074/75073105-65ffbe00-54be-11ea-8cc3-f2dfc2b3e26a.png)

## Logs
studio tomcat log
```
[ERROR] 2020-02-21T14:47:40,432 [http-nio-8080-exec-6] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/monitoring/version failed with response: ApiResponse{code=1001, message='Invalid parameter(s) : Missing parameter: 'token'', remedialAction='Check API and make sure you're sending the correct parameters', documentationUrl=''} 
org.craftercms.studio.api.v2.exception.InvalidParametersException: Missing parameter: 'token'
	at org.craftercms.studio.controller.rest.v2.MonitoringController.validateToken(MonitoringController.java:67) ~[classes/:3.1.5-SNAPSHOT]
	at org.craftercms.studio.controller.rest.v2.MonitoringController.getCurrentVersion(MonitoringController.java:97) ~[classes/:3.1.5-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.18.RELEASE.jar:4.3.18.RELEASE]
```

### Version
`3.1.5-SNAPSHOT` 

### OS
Any

### Browser
Looks like only happens with Chrome, Firefox is not calling the monitoring API while loading the login page.

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@dejan-brkic UI ready: https://github.com/craftercms/studio-ui/pull/1608

**Comment by dejan-brkic** [comment]
3.1.x: https://github.com/craftercms/studio/pull/1963

**Comment by dejan-brkic** [comment]
Develop:
https://github.com/craftercms/studio/pull/1964

**Comment by dejan-brkic** [comment]
Develop:
https://github.com/craftercms/studio/pull/1966

**Comment by yacdaniel** [comment]
please fix the following:
* @rart changing the password from `Account Management` page should logout and redirect the user to login page `develop 3.2` and `support 3.1.x`
* @dejan-brkic when using the Forgot Password in login, when the use clicks the link http://localhost:8080/studio/#/reset-password?token=MbTAraMwKSMWp%2BEjxlLgwX%2BeCMG3Jzxd%2FObTQioUeE0WOmbsLb1zqRSX1wq0ysbZ  it goes to http://localhost:8080/studio/login?redirect=/studio/#/reset-password?token=MbTAraMwKSMWp%2BEjxlLgwX%2BeCMG3Jzxd%2FObTQioUeE0WOmbsLb1zqRSX1wq0ysbZ  we need the reset-password to be a public URL, maybe something under `studio/login` like `http://localhost:8080/studio/login/reset-password?token=MbTAraMwKSMWp%2BEjxlLgwX%2BeCMG3Jzxd%2FObTQioUeE0WOmbsLb1zqRSX1wq0ysbZ `  `develop 3.2` and `support 3.1.x`
* @rart when the user is in any page of the global menu or `Account Management` page and clicks Sign Out the user is taken to the old login page.  `support 3.1.x` 
* @dejan-brkic users are redirected to old login page when they are not authenticated `support 3.1.x`
* @dejan-brkic if I go to http://localhost:8080/studio/#/globalMenu/cluster without being authenticated (tested in `develop 3.2` where redirect works) it takes me to http://localhost:8080/studio/login?redirect=/studio/#/globalMenu/cluster  can we make that redirect to encoded the url value? so it becomes something like  http://localhost:8080/studio/login?redirect=%2Fstudio%2F%23%2FglobalMenu%2Fcluster  without this change the user is not taken to cluster page directly. `support 3.1.x` and `develop 3.2`

**Comment by dejan-brkic** [comment]
PRs:
https://github.com/craftercms/studio/pull/1976
https://github.com/craftercms/studio-ui/pull/1741
https://github.com/craftercms/studio/pull/1977
https://github.com/craftercms/studio-ui/pull/1742

**Comment by yacdaniel** [comment]
@rart please review the missing items from the previous checklist.

**Comment by yacdaniel** [comment]
Verified.
