### ISSUE TITLE
[studio] Getting Could not read packet: unexpected end of stream, read 0 bytes from 4 when using AWS Aurora serverless

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3842]
We've been getting some `Could not read packet: unexpected end of stream, read 0 bytes from 4` exceptions when using AWS Aurora serverless, which means that the server closed the connection. These errors are infrequent, they appear maybe once every couple of weeks. 

There can be 2 causes for the issue: 1) the client connection being used is invalid or 2) Aurora serverless might have sometimes some "hiccups" and can't handle the connection. Some possible solutions for each one:

1) Do a better validation of connections in the connection pool (Aurora serverless is a MySQL 5.6 DB so maybe the validation needs to be different).
2) Be able to retry an SQL operation if it fails.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1909

**Comment by avasquez614** [comment]
Tested it with a Studio connected to an Aurora Serverless for 12 hours. No issues found. All good
