### ISSUE TITLE
[studio-ui] Make the `State` in the `Publishing Queue` filter multi-select

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3843]
## Describe the bug
The `State` in the `Publishing Queue` filters are currently radio buttons, thus not allowing the user to select multiple states to filter

![site-config-publish-queue-filter](https://user-images.githubusercontent.com/25483966/75163284-f3285a00-56ec-11ea-8517-147ac0e6a851.png)

## To Reproduce
1. Create a site using any bp
2. Click on `Site Config` -> `Publishing`
3. Click on the `Publishing Queue` tab and click on the `Filters` dropdown box
4. Notice that for `State`, radio buttons are used so the user is unable to select multiple states to filter

## Expected behavior
Make the `State` in the `Publishing Queue` filter multi-select
(Used ticket https://github.com/craftercms/craftercms/issues/2471 as reference for multi-select requirement for state)

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.5-SNAPSHOT-4cfb5c
Build Number: 4cfb5c4b475273f85a0d28ca2f5e2f8308d267c7
Build Date/Time: 02-20-2020 10:57:55 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
BE Done
PR:
https://github.com/craftercms/studio/pull/1894

**Comment by rart** [comment]
@yureii00 

1. looks like currentFilters on PublishingPackage is no longer in use. Please check/remove.
2. Test on 2019. Merge has been done.

**Comment by rart** [comment]
Pending merge of https://github.com/craftercms/studio-ui/pull/1599

**Comment by sumerjabri** [comment]
@rart merged.

**Comment by sumerjabri** [comment]
Verified fixed.
