### ISSUE TITLE
[studio] Add to audit log when a publishing package is cancelled

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3845]
## Describe the bug
When a publishing package is cancelled, there is no record in the audit log of the cancelled package

## To Reproduce
1. Create a site using website editorial
2. Edit an article then schedule it for publishing at a later time
3. Click on `Site Config` then click on `Publishing`
4. In the `Publishing Queue` tab, select the publishing package scheduled in the step above, then cancel it
5. Click on `Audit` from the sidebar, notice that there is no log for the cancelled publishing package

## Expected behavior
Cancelled publishing packages should be in the audit logs

## Screenshots
Here's a screenshot of the publishing queue where a package has been cancelled
![Screen Shot 2020-02-24 at 2 28 53 PM](https://user-images.githubusercontent.com/25483966/75184278-24ffe780-5712-11ea-85c2-eb1fb90bfc8d.png)

Here's the audit log:
![Screen Shot 2020-02-24 at 2 27 00 PM](https://user-images.githubusercontent.com/25483966/75184320-347f3080-5712-11ea-93fb-f863d322b75f.png)

Notice there's no log for a cancelled publishing package

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.6-SNAPSHOT-0ad36f
Build Number: 0ad36f86c301c8ff6f83459fd3bdfbb348998e81
Build Date/Time: 02-24-2020 10:24:56 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Hi @dejan-brkic! 

I see in the current implementation that the audit log lists the operation for cancelling a publishing package as `REJECT`

Would it be possible to have the operation logged in the audit logs as `CANCELLED` when a publishing package is cancelled through `Site Config`?  It would be nice if the action performed in the UI is reflected in the audit logs as the same, so, for cancelling a publishing package through `Site Config` -> `Publishing`, the audit log should reflect the operation as `CANCELLED`

It that is not possible, can we have more description in the audit logs so we can tell that the `REJECT` operation is from cancelling a publishing package and not from a workflow rejection because of say, typos in the article?

In the image below, 
the first item in the audit log, is a rejection from workflow (I clicked on `Reject` from the context nav)
the second item in the audit log, is a `REJECT`, but from cancelling the publishing package from `Site Config`

![Screen Shot 2020-02-26 at 12 22 46 PM](https://user-images.githubusercontent.com/25483966/75371138-37a22a00-5894-11ea-9a5f-7d8d0b2e7152.png)

As you can see in the image above, we cannot tell where the rejection came from (workflow? administrative from `Site Config`?).  More description in the audit logs would be nice so we can tell that the `REJECT` operation is from cancelling a publishing package and not from a workflow rejection because of say, typos in the article

Thanks!

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1595
https://github.com/craftercms/studio/pull/1895

**Comment by alhambrav** [comment]
Verified fixed.
