### ISSUE TITLE
[studio-ui] Change the wording in the `Confirm` option when the `Cancel` button next to a publishing package is clicked

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3847]
**Is your feature request related to a problem? Please describe.**
 Change the wording in the `Confirm` option when the `Cancel` button next to a publishing package is clicked.  

## To Reproduce
1. Create a site using the website editorial bp
2. Edit an article then schedule it for publishing at a later time
3. Click on `Site Config` -> `Publishing` and select the `Publishing Queue` tab
4. Click on `Cancel` for the publishing package scheduled for later, notice the message displayed under the `Confirm` option: `Set the state for all selected items to "Cancelled"`

It would be nice to have a different wording in the `Confirm` option to something like: `Set the state of publishing package xxxidxxx to CANCELLED`

![Screen Shot 2020-02-25 at 12 22 59 PM](https://user-images.githubusercontent.com/25483966/75271917-027dd500-57cb-11ea-8b8f-162e2fab1dd2.png)

**Describe the solution you'd like**
Reword the `Confirm` message when cancelling a publishing package using the `Cancel` button next to a publishing package to: `Set the state of publishing package xxxidxxx to CANCELLED`
or something like that.

Maybe make the experience for cancelling a package a little more intuitive?

**Additional context**

**Comment by sumerjabri** [comment]
![image](https://user-images.githubusercontent.com/3931908/75477872-f0d33380-596a-11ea-9cc0-3d2b441d9c08.png)

**Comment by rart** [comment]
Verified.
Fixed on https://github.com/craftercms/studio-ui/pull/1596
