### ISSUE TITLE
[studio-ui] Fix typos

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3853]
Please check all messages to fix the word `where` used instead of `were`, example:

<img width="1173" alt="Screen Shot 2020-02-28 at 8 41 15 AM" src="https://user-images.githubusercontent.com/1236955/75558676-ca170a80-5a07-11ea-913c-206086f7c707.png">

**Comment by rart** [comment]
Pending merge of https://github.com/craftercms/studio-ui/pull/1599

**Comment by sumerjabri** [comment]
@rart merged.

**Comment by sumerjabri** [comment]
Verified fixed.
