### ISSUE TITLE
[mp-ui] Show all supported Crafter CMS versions instead of only one

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3858]
## Describe the bug
Create site from marketplace blueprint or built-in blueprint shows only the first version supported by the BP instead of all.

## To Reproduce
1. Go to https://marketplace.craftercms.org
2. Click on More Info of a built-in BP or MP BP
3. See error

## Expected behavior
The UI should show all supported versions or not show the versions at all. Currently, it's confusing.

Note built-in BPs don't carry the right versions, that a different issue.

## Screenshots
![Screenshot from 2020-03-02 17-18-52](https://user-images.githubusercontent.com/3931908/75723263-eb972100-5ca9-11ea-9d3d-838c49bf6bed.png)
![Screenshot from 2020-03-02 17-20-07](https://user-images.githubusercontent.com/3931908/75723336-18e3cf00-5caa-11ea-889d-2c8fbb76683e.png)

## Logs
N/A

### Version
3.1.6-SNAPSHOT

### OS
Ubuntu, Linux

### Browser
Chrome latest

## Additional context
N/A

**Comment by rart** [comment]
Will there ever be a case that the supported versions will have jumps?

e.g. supported by 3.1.4 & 3.1.6 but not 3.1.5?

I’m thinking we could display something like in a package.json style. Following the attached response screenshot:  
- <3.1.4
- ^3.1.4
- 3.1.4+
- 3.1.(4-6)

Alternatively we could do 3.1.4-3.1.6 but from here on we have to start coming up with alternative UIs and possibly not displaying the version on the summary view.

**Comment by sumerjabri** [comment]
> Will there ever be a case that there would be supported version jumps?

Yes.

Perhaps we show the latest version, and if you click, we list all versions supported.

**Comment by rart** [comment]
Ping me to discuss when you get to this ticket, @jvega190

**Comment by jvega190** [comment]
@sumerjabri @rart should I close this ticket? changes are being work on this ticket https://github.com/craftercms/craftercms/issues/3883

**Comment by sumerjabri** [comment]
I think we still do this for the MP application.
