### ISSUE TITLE
[studio] Integrate Site Create/Delete with Deployer

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#386]
Integrate site create/delete with known target deployers

**Comment by dejan-brkic** [comment]
PR #540

Create target request body:

{ 
	"env":"preview",
	"site_name":"test",
	"replace":true, 
	"template_name":"preview", 
	"remote_repo_url":"<crafter_root>/data/repos/sites/test/sandbox", 
	"remote_repo_branch":"master", 
	"engine_url":"http://localhost:8080" 
}
Deployer creates target config, but does not contain all params being sent. Therefore deployer does not create preview target out of the box.

Delete target post request according to documentation, but deployer responds with 404 and:
{
  "message": "Target not found"
}

Studio integration part completed, errors are on deployer side
