### ISSUE TITLE
[studio-ui] z-order issue on upload image from desktop dialog in RTE

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3863]
## Describe the bug
User cannot upload an image from desktop in RTE because the dialog for upload is hidden and disabled due to a z-order bug

## To Reproduce
1. In editorial blueprint go to an article and edit it
2. In the RTE click the insert image and choose upload

## Expected behavior
User should be able to interact with the upload dialog

## Screenshots
https://www.loom.com/share/886c79ef094742e79813981097c225a2

## Logs
N/A

### Version
Studio Version Number: 3.1.5
Build Number: 78758bb3b0ef328184808e93e5f1aea7687262c5
Build Date/Time: 02-21-2020 18:38:13 -0500

### OS
N/A

### Browser
Chrome

**Comment by russdanner** [comment]
We also need to double check other data sources:
Upload image to S3
Upload video from desktop, Upload to S3

**Comment by yureii00** [comment]
the others data sources were already fixes on another ticket

**Comment by russdanner** [comment]
Confirmed
