### ISSUE TITLE
[studio-ui] File Browse DS: adding 2 or more items that already exist cause unclickable screen

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3865]
## Describe the bug
When 2 or more item that already exist in site are added again from the File Browse data source the Edit Form becomes unclickable after the user accepts the notification message.

## To Reproduce
1. Create a site from empty BP
2. In the Page Content Type add a `File Browse` data source which uses `/static-assets/js` as Repository Path then add a `Item Selector` control which uses the `File Browse` Data Source as Item Manager. 
3. Edit Content, click add in the `Item Selector` control
4. In the browse window expand `static-assets`and go to `js` folder, click `Select All` or check both files finally click in `Add Selection`. (*Developer note*: save this change so you can repeat the test with more ease). 
5.  Do the previous step again, adding the same files that are already added.

## Expected behavior
Screen is clickable, no gray-out screen. 

## Screenshots
![select all browse files](https://user-images.githubusercontent.com/6722074/75910675-df2ed780-5e13-11ea-823b-d3cdb9a39bf5.gif)

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
Linux

### Browser
Chrome, Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@yacdaniel fix here: https://github.com/craftercms/studio-ui/pull/1611

**Comment by yacdaniel** [comment]
@rart could we fix the case when we try to add a big amount of items that are already added? the popup dialog is not displaying the Ok button at the button, and some items might not shown in the dialog. In my case I have 30 items added / try to be added again.  Hitting `Esc` key will close the dialog. 
![image](https://user-images.githubusercontent.com/6722074/76091102-8598eb00-5f82-11ea-9563-3d26d747cd79.png)

**Comment by rart** [comment]
Don’t think this is critical for 3.1.6. 
Shall we file a new issue and consider this resolved, @russdanner?

**Comment by rart** [comment]
Never mind... Fixed.

**Comment by yacdaniel** [comment]
Verified fixed, now there is a scrollable dialog when notification about items already added is displayed
![image](https://user-images.githubusercontent.com/6722074/76323961-fefa4b80-62aa-11ea-8ac0-d67c4da46efe.png)
