### ISSUE TITLE
[studio-ui] Add a link from Studio to acknowledgements page in docs

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3866]
**Is your feature request related to a problem? Please describe.**
Add a link from Studio to acknowledgements page in docs

**Describe the solution you'd like**
Please add a link from the `Help` -> `About` screen in Studio with the link pointing to https://docs.craftercms.org/en/3.1/acknowledgements/index.html

(Something like the screen below, the message is not centered, but that's the idea =) )

![Screen Shot 2020-03-04 at 2 05 11 PM](https://user-images.githubusercontent.com/25483966/75913780-89f9c280-5e21-11ea-8530-e9e0e514f03f.png)

`Crafter CMS is made possible by these other_open source software projects_ `
where `_open source software projects_` points to the acknowledgements in the docs

**Describe alternatives you've considered**

**Additional context**

**Comment by sumerjabri** [comment]
@rart if you use a variable for `3.1` then we can update that part of the URL for both the Help link and this ack link when we release 3.2/etc.

**Comment by rart** [comment]
@sumerjabri I'm not clear of what are the two places you're referring to exactly or the link lifecycle. At the moment is in a single place so just added the clear text. Let's discuss and add a ticket to refactor if required.

**Comment by rart** [comment]
@alhambrav note [PR](https://github.com/craftercms/studio-ui/pull/1612) status for testing.

**Comment by sumerjabri** [comment]
@rart 
There are two links in Crafter Studio to our docs. Both need to maintain the version of the docs they're referring to (`major.minor`). I want that version/base-domain abstracted out. If that's the case already, then we're good, if not, make it so.
The two places are:
![image](https://user-images.githubusercontent.com/3931908/75993768-fe873c80-5ec7-11ea-8a38-6da505942f1b.png)
and this new one requested on this ticket.

**Comment by sumerjabri** [comment]
Change the tex to be:

```
Crafter CMS is made possible by these other open source software projects.
```

**Comment by alhambrav** [comment]
Verified.
