### ISSUE TITLE
[studio-ui] In Form Engine File Browse data sources should display the title of the DS in the dropdown

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3870]
## Describe the bug
When the File Upload to Remote Repository DS's are used with a Item Selector, in the Form Engine they are displayed as `Upload - {Title of Data source}`. File Browse To Remote Repository DS's  are displayed as `Browse - {A hard-coded value}`. 

## Expected behavior
The displayed value should be with the Title of DS  `Browse - {Title of Data source}`

![image](https://user-images.githubusercontent.com/6722074/76011013-77db5b00-5ed9-11ea-8397-8f1609c0fb29.png)

![image](https://user-images.githubusercontent.com/6722074/76010979-67c37b80-5ed9-11ea-9d72-55329a095d89.png)

The previous image should be  displayed as `Browse - File From CMIS`, `Browse - File From WEBDAV`, `Browse - File From S3`. Uploads names are as expected. 

### Version
 `3.1.6-SNAPSHOT`

**Comment by sumerjabri** [comment]
@rart FYI

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/76114421-a4f83e00-5fab-11ea-8edc-2e797ab0868c.png)
