### ISSUE TITLE
[studio] Update getChildrenBy* APIs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3871]
Please modify the response so that, it returns: the parent, the level descriptor and the children.

The pagination pieces of the request and response should consider only children that aren’t the level descriptor. 

```js
{
  response: {},
  parent: {
    id: ,
    ...
  },
  levelDescriptor: {
    ...
  },
  children: [
    {},
    {},
    ...
  ],
  total: ,
  limit: ,
  offset: 
}
```

Could we also rename sortOrder `default` to something more semantic? It can be the default sorting mechanism (i.e. if param is not sent), but can we rename it to a descriptive term?

**Comment by sumerjabri** [comment]
@dejan-brkic ping me if you need any context

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1903

**Comment by rart** [comment]
Would we still be able to tweak a couple of prop names?
- SandboxItem
  - createdDate => dateCreated
  - lastModifiedDate => dateModified
- DetailedItem.{sandbox, staging, live}
  - lastModifiedDate => dateModified
  - lastScheduledDate => dateScheduled
  - lastPublishedDate => datePublished
- PublishingDashboardItem
  - publishedDate => datePublished

**Reasons**:
- Front-load the "date" word
  - Most dates are type string so it helps
- Remove redundancy/obvious of "last"
  - The date in which was modified/published should be obvious that is the last
  - Removing the word last makes the prop name more concise and short
- Consistency with UI models

Alternatively, if front-loading the word "date" is not desired, could we remote "last"?
- SandboxItem
  - lastModifiedDate => modifiedDate
- DetailedItem.{sandbox, staging, live}
  - lastModifiedDate => modifiedDate
  - lastScheduledDate => scheduledDate
  - lastPublishedDate => publishedDate

**Comment by rart** [comment]
@sumerjabri @dejan-brkic we didn't do any of these from comment above. Will we?

> Would we still be able to tweak a couple of prop names?
> 
> * SandboxItem
>   
>   * createdDate => dateCreated
>   * lastModifiedDate => dateModified
> * DetailedItem.{sandbox, staging, live}
>   
>   * lastModifiedDate => dateModified
>   * lastScheduledDate => dateScheduled
>   * lastPublishedDate => datePublished
> * PublishingDashboardItem
>   
>   * publishedDate => datePublished
> ...

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2358

**Comment by rart** [comment]
Verified
