### ISSUE TITLE
[studio] Remove "studio.configuration.site.environment" from studio config if not used

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3872]
## Describe the bug
Property `studio.configuration.site.environment` does not work for setting the environment in Studio.  Please remove from the Studio config files if not used at all in Studio.

## To Reproduce
1. Open your `studio-config.yaml` file, look at the property:
```
# Defines name used for environment specific configuration. It is used for environment overrides in studio. Default value is local.
studio.configuration.site.environment: local
```
2. When the above mentioned property is used to set the environment, it does not work
Here's the steps used to setup an env:
   a. create a folder under `data/repos/site/mysite/sandbox/config/studio` called `env`
   b. Inside the folder,  create a directory called `myenv` 
   c. Copy the configuration file you want (inside your `myenv` folder) to override in the new environment you are setting up, 
   following the folder structure under `config/studio`.  Remember to commit the files copied so Studio will pick it up.
   d. In the studio override yaml file in `TOMCAT/shared/classes/crafter/studio/extension` set the 
   following property
   ```
   # Defines name used for environment specific configuration. It is used for environment overrides in studio. Default value is local.
   studio.configuration.site.environment: myenv   
   ```
   e. Restart studio
   f. Notice that after restarting, the active environment is not what we set from the previous step.  Please verify if the property is used anywhere else, and if not, please remove.

## Expected behavior
Please remove unused property in the configuration files `studio.configuration.site.environment`

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.6-SNAPSHOT-4f1bdf
Build Number: 4f1bdfb246c70ba87c14ab33cb3276815232c3a8
Build Date/Time: 03-06-2020 11:32:16 -0500

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Already removed

**Comment by alhambrav** [comment]
Verified.
