### ISSUE TITLE
[all] Update dependencies

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3874]
Update jackson-databind to latest.

**Comment by jdrossl** [comment]
@sumerjabri maybe we can wait for the release of databind `2.9.10.4` to avoid having to change all jackson dependencies to `2.10.0` (we can't bump just databind to this version)

**Comment by jdrossl** [comment]
they do have planned a `2.9.10.4` release but there is no date https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches

**Comment by sumerjabri** [comment]
Done
