### ISSUE TITLE
[social] Update dependencies

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3875]
Update Rake to the latest, similar to: https://github.com/craftercms/social/pull/363

This, of course, needs to go to `develop`

**Comment by jdrossl** [comment]
@sumerjabri the file reported is not really used for the build, it comes from another dependency so maybe we should update that one? 

Maybe @rart should take a look to see if it's worth changing this app because it's pretty outdated and I suspect is going to take extra time

**Comment by rart** [comment]
@jvega190 please validate this update.
Could we get rid of lib in favour of npm? If it's a considerable effort, ping me to discuss.
