### ISSUE TITLE
[craftercms] Tomcat is not shutting down in time

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3877]
## Describe the bug
Tomcat is not shutting down in time and the process is killed, log related to the thread dump is added to catalina log. 

## To Reproduce
1. Build from develop
2. `./gradlew start`
3. `./gradlew stop`
4. See error while stopping. 

## Expected behavior
Tomcat shutdown gracefully

## Screenshots
N/A

## Logs
```
------------------------------------------------------------------------
Stopping Tomcat
------------------------------------------------------------------------
/home/tmp/craftercmsCE/crafter-delivery/bin/apache-tomcat/bin/catalina.sh: 2: [: tmp: unexpected operator
Tomcat did not stop in time.
To aid diagnostics a thread dump has been written to standard out.
Killing Tomcat with the PID: 10991
The Tomcat process has been killed.
------------------------------------------------------------------------
Stopping Deployer
------------------------------------------------------------------------
------------------------------------------------------------------------
Stopping Elasticsearch
```

https://gist.github.com/yacdaniel/a8819d577f6f23f86486b5fc2f0a9792

### Version
`3.1.6-SNAPSHOT`

### OS
```
Ubuntu 16.04.6 LTS
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

### Browser
N/A

## Additional context
N/A

**Comment by avasquez614** [comment]
@yacdaniel are you stopping almost immediately after starting Crafter, without letting Tomcat start completely?

**Comment by yacdaniel** [comment]
@avasquez614 no, I wait for complete start up. I have notice the error even after using crafter for several hours.

**Comment by avasquez614** [comment]
I'll try to reproduce, thanks

**Comment by avasquez614** [comment]
Indeed, I was able to reproduce the issue. This is the log: https://gist.github.com/avasquez614/84bf4488db8842ddd67753bfaeec8537

**Comment by yacdaniel** [comment]
Verified fixed.
