### ISSUE TITLE
[docs] remove the term environment from any references to publishing to staging throughout documentation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3878]
**Is your feature request related to a problem? Please describe.**
We are consolidating the use of the term ENVIRONMENT to mean wholly unique separate installations of Crafter e.g. (DEV, QA, STAGING, LOAD TESTING, PRODUCTION)

Today our documentation and some configurations reference the term ENVIRONMENT when discussing the intermediate preview STAGING used by authors for workflow on the way to live.  We want to remove this as it can be confusing.  We'll refer to this as simply Publishing to Staging or Publishing to Live.  These are publishing endpoints / objectives (LIVE, STAGING) that are part of a given ENVIRONMENT. 

**Describe the solution you'd like**
```Studio config yaml contains the doc. Remove the term environment.
# Git repository branch for the `staging` environment, default "staging"
studio.repo.published.staging: staging
```
Online doc also needs to be updated:
Example:
https://docs.craftercms.org/en/3.1/system-administrators/activities/authoring/staging-env.html?highlight=env

This title can be updated to  Configuring Publishing to Staging Preview

**Describe alternatives you've considered**
The most important act here is to remove the term environment from this use because of it's well established meaning in operations circles.  We could introduce a new term for Staging and Live such as Publishing Target, Publishing Objective, Publishing Endpoint etc.  This would require further conversation.

**Comment by alhambrav** [comment]
Ticket https://github.com/craftercms/craftercms/issues/3884 - to update dashboard widgets `Environment` column

**Comment by alhambrav** [comment]
Docs: PR https://github.com/craftercms/docs/pull/983

**Comment by russdanner** [comment]
Confirmed
