### ISSUE TITLE
[Social] Social UI local server configuration documentation

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#388]
There should be any documentation about to solve this and speed up any possible contribution from developers.

Couple of weeks ago was going to try some tweaks over social ui, but found tricky how to connect the ui repo with the server. All the configuration is pointing to `localhost:8080`, that's fine. But i started to get cross origin issues because ui runs on `localhost:9000`, after fixing this; noticed authentication service returns nothing, so no comments  or initialisation.

**Comment by sumerjabri** [comment]
http://docs.craftercms.org/en/3.0/system-administrators/social/index.html
