### ISSUE TITLE
[studio] Support Engine multi-environment configurations

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3881]
In case that there are environment override files for Engine Site Configuration, Engine Site Application Context and Engine URL Rewrite Configuration, load those instead of the main files,

**Comment by jdrossl** [comment]
@sumerjabri no, this is for Studio to show the right file in the UI, I only worked on engine itself reading the files

**Comment by sumerjabri** [comment]
@dejan-brkic another 3.1.7 for you.

We should also consider future mechanics for Deployer in this context.

**Comment by dejan-brkic** [comment]
Already implemented in studio

**Comment by sumerjabri** [comment]
@alhambrav all yours for validation and closure.

**Comment by alhambrav** [comment]
Verified.
