### ISSUE TITLE
[studio] Consolidate setup location for `staging` and `live` and remove `environment` from comments and names

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3885]
**Is your feature request related to a problem? Please describe.**

In the current Studio version 3.1.5, `staging` is enabled from `site-config.xml` , so is the option to rename `live` and `staging`:
```
       <published-repository>
          <enable-staging-environment>true</enable-staging-environment>
          <staging-environment>staging</staging-environment>
          <live-environment>live</live-environment>
       </published-repository>
```
In `environment-config.xml` you can set names too for publishing targets (e.g. `live`, etc.)
```
    <publishing-targets>
        <target>
            <repo-branch-name>live</repo-branch-name>
            <display-label>Live</display-label>
        </target>
    </publishing-targets>
```
In `studio-config-override.yaml`, you can set default branch names for ``live`` and ``staging`` when not using the *environment-config.xml*
```
   # If not using environment-config.xml, environments are configured here
   # Git repository branch for the `live` environment, default "live"
   # studio.repo.published.live: live
   # Git repository branch for the `staging` environment, default "staging"
   # studio.repo.published.staging: staging
```
It would be nice if there's only one place to setup publishing targets (e.g. `live` and `staging`) instead of the multiple files that we have now.

Also, re this ticket: https://github.com/craftercms/craftercms/issues/3878, please remove `environment` from the comments and names

**Describe the solution you'd like**
Consolidate setup location for `staging` and `live` and remove `environment` from comments and names.

**Describe alternatives you've considered**

**Additional context**

**Comment by sumerjabri** [comment]
This should be mostly done. Let's verify.

**Comment by dejan-brkic** [comment]
`environment-config.xml` was already removed.
Comments don't have an `environment` word.
Default branch names are in `studio-config.yaml`. Per site can be overridden in `site-config.xml`.

**Comment by alhambrav** [comment]
Verified.
