### ISSUE TITLE
[studio-ui] user should be able to pick a page via the RTE insert link

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3886]
**Is your feature request related to a problem? Please describe.**
Today you can "cheat" and pick a page by adding a file data source to the RTE but it inserts the path to the XML which your FTL or app has to process.

Users routinely ask an easy way to browse or search for pages and insert links to them in the RTE and other controls.

**Describe the solution you'd like**
Add add a data source (or logic to the RTE insert link component that understands an inbound store URL) that allows the user to insert a URL to a page object rather than the store URL

**Additional context**
See video that explains this via the work-around
https://www.loom.com/share/010a6bb32bb148eb997bbeb450b2c918

**Comment by sumerjabri** [comment]
@yacdaniel please validate
@alhambrav please document/update docs

Tasks:
- [ ] Validate
- [ ] Document

**Comment by yacdaniel** [comment]
@alhambrav  here are the steps if needed:
- Add a file browse DS with `/site/website` path
- In the RTE check the previous DS in the Item Manager
- When editing with the RTE, click Insert and select the DS and add any page. 
![rte page link](https://user-images.githubusercontent.com/6722074/81087325-cf388000-8eb6-11ea-9cbc-e96f733b46e3.gif)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/978

**Comment by sumerjabri** [comment]
![image](https://user-images.githubusercontent.com/3931908/82373304-663f2500-99eb-11ea-86eb-07d40418691a.png)

Still fails for Shared Content data source.

**Comment by russdanner** [comment]
- We are going to leave this fix functionality AS IS for the file data source which allows you to use the data source to pick both static-assets and  pages.
- No change to the shared content data source will be made (contradicting the requirements above.)
- Error handling will be added to the RTE to catch and address the exception above:
A message should be provided to the user (which should be caught in development testing)
"The data source configured for browse is not compatible with the Rich Text Editor. Please contact your administrator."
- Additionally we will be filing tickets for new data sources to more cleanly address this issue. This ticket will be updated to include references to the ticket.

**Comment by russdanner** [comment]
Confirmed
