### ISSUE TITLE
[studio-ui] Add a new video picker control just for MediaConvert datasource

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3888]
Right now you can wire a `Video` control with a single file upload datasource and a MediaConvert datasource. This makes the video picker incompatible with indexing because the single file upload DS will put a single value in the field (`_s` suffix field), while the MediaConvert DS will put a list of `<item>`s in the field (making the suffix `_o` required for indexing). 

To fix this, create a new video control called `Transcoded Video`, which basically is a `Video` control but that only accepts the MediaConvert DS. Also, make the `Video` control accept all video DS except the MediaConvert DS.

**Comment by jvega190** [comment]
@jdrossl please add this to UM, thanks!

**Comment by avasquez614** [comment]
Verified
