### ISSUE TITLE
[studio-ui] Update the Bulk Upload function to support larger amounts of files and be more precise

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3890]
Update the Bulk Upload function to: 
- Send the files to the backend in groups of X, where X is configurable and defaults to 1. 
- This is configurable per Site.

**Comment by yacdaniel** [comment]
@yureii00 please fix the issue when multiple items are selected from the browse button, only one item is show in the upload dialog
![image](https://user-images.githubusercontent.com/6722074/77477973-da41c000-6de2-11ea-956e-5d833591bdf1.png)

**Comment by yacdaniel** [comment]
Verified. 
>  Send the files to the backend in groups of X, where X is configurable and defaults to 1.
    This is configurable per Site.

multiple upload defaults to 2, configurable per site still pending.
