### ISSUE TITLE
[docs] configurable script/elements support TinyMCE 5

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3898]
Document script and custom elements support in TinyMCE5

Steps to make configuration work:

- Under Site Confifg -> Configuration -> RTE (TinyMCE 5) Configuration add the following configuration:
`<extendedElements>{desiredElement},{otherElementCommaSeparated}</extendedElements>`

![Screenshot from 2020-03-18 14-14-43](https://user-images.githubusercontent.com/18267471/77003868-bf270a00-6923-11ea-97cc-f0095eab0b94.png)

It's recommended to disable `Force Root Blockp Tag` and `Force p tags New Lines` to avoid wrapping the added elements on the RTE (those options are to wrap content in `<p></p>` tags. (Under Site Config -> Content Types)

![Screenshot from 2020-03-18 14-17-09](https://user-images.githubusercontent.com/18267471/77004103-2a70dc00-6924-11ea-8e95-e23482280cd7.png)

Done, you can add your allowed elements on the RTE's code editor:

![Screenshot from 2020-03-18 14-16-51](https://user-images.githubusercontent.com/18267471/77004070-1fb64700-6924-11ea-8ffe-fd57ff80260f.png)

You can also add regular expressions:

![Screenshot from 2020-03-18 14-26-02](https://user-images.githubusercontent.com/18267471/77004263-6c9a1d80-6924-11ea-9b5f-7ef3305b051e.png)

that will allow tags like:
`<a>custom tag</a>`
or
`<aa>another custom tag allowed by the regex</aa>`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/946

**Comment by sumerjabri** [comment]
@jvega190 please validate: https://docs.craftercms.org/en/3.1/site-administrators/studio/rte2-setup.html

**Comment by jvega190** [comment]
Verified
