### ISSUE TITLE
[videocenter] Non-live streams (past and upcoming) shouldn't appear in the Channels

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3902]
Streams that are not live (like past and upcoming), are clickable and displayed in Channels. They shouldn't appear there.

**Comment by avasquez614** [comment]
@jvega190 we decided that upcoming events should appear in Channels, can you add that back please?

**Comment by jvega190** [comment]
@avasquez614 done

**Comment by avasquez614** [comment]
Verified
