### ISSUE TITLE
[studio-ui] Rename "Transcoded Video Picker" control to "Transcoded Video"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3904]
The other picker controls we have does not have `Picker` in the control names. (`Video` and `Image`).  It would be nice if the names of the picker controls are consistent

Please rename the `Transcoded Video Picker` to `Transcoded Video`

<img width="203" alt="Screen Shot 2020-03-19 at 3 54 43 PM" src="https://user-images.githubusercontent.com/25483966/77160805-86e80e80-6a7e-11ea-9e8b-b040a195a366.png">

**Comment by sumerjabri** [comment]
@jdrossl UM is required for this.

**Comment by jdrossl** [comment]
@sumerjabri @jvega190 if only the label changed then there is no need for UM, only if the file name changes

**Comment by sumerjabri** [comment]
Updated accordingly. Over to @alhambrav for validation and closure.

**Comment by jvega190** [comment]
@rart translations need to be updated, please assign Vita when ready.

**Comment by alhambrav** [comment]
Verified.
