### ISSUE TITLE
[studio-ui] Sequenced embedded component malformed XML upon write

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3907]
1. Create site based on https://github.com/rart/craftercms-wordify-blueprint.git (name it wordify)
2. Edit a post
3. Add a "Responsive columns" component and add a couple of internal components
4. Page breaks
5. Inspect the XML of the responsive columns - the inner embedded components are in a incorrect system XML

**Comment by yacdaniel** [comment]
Verified.
