### ISSUE TITLE
[studio-ui] ContentTypeEditor: Path outside /site used as "repository path" of datasource provides no warning and breaks model

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3908]
## To Reproduce
1. Create shared datasource and add `/component/{someComponentName}` as path (something outside of `/site`)
2. Use this datasource on a node selector
3. Open a content form and create a new item using that item selector/data source
4. Observe the created XML (has issues) - both the edited page and the new created shared component

## Expected behavior
Should paths outside `/site` even be allowed? Otherwise, should be validated.
If they are allowed, then this should work normally regardless of the path.

**Comment by russdanner** [comment]
@rart In any data source that is looking for paths based on Crafter Content Objects. /site should be required and validated. We do not support content objects outside this folder.

**Comment by rart** [comment]
The current validation can be fooled by doing something like `/sites/yada`. Need to make sure that the root is literally `/site`.

Try this expression instead: `^\/site(\/.*)?$`.

Perhaps we can get rid of the startsWith and replace with regEx

**Comment by aachavarria** [comment]
done in https://github.com/craftercms/studio-ui/pull/1909
