### ISSUE TITLE
[studio-ui] Display Inherited Fields on Form Engine

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3909]
When opening a form for edit, the form engine should marry the "section defaults" with the current model and display a combined form.

Content type builder should somehow reflect inherited fields too.

The values should also be populated and overridedable (conditionally?). The value overrides would get stored on the content model, not on the inherited model.

**Comment by sumerjabri** [comment]
@rart as a first step, simply show the inherited data present in THIS form definition with a different color (maybe gray) with a hint that this field is populated through inheritance and an indication as to which parent/descriptor it is.

**Comment by sumerjabri** [comment]
FE2
