### ISSUE TITLE
[studio] Dependencies are not calculated for assets which filename contains parentheses "()"

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3910]
## Describe the bug
Dependencies are not calculated for assets which filename contains parentheses "()"

## To Reproduce
1. Create a site from Editorial BP
2. Edit Home page, upload a new image in the Hero Image, make sure the image have a parentheses `()` in the filename.
3. Check dependencies of the Home page, select `Is referenced by this item`
4. Notice the image dependency is not show. 

## Expected behavior
Assets which filenames contains parentheses should be calculated in dependencies.

## Screenshots
![dependencies](https://user-images.githubusercontent.com/6722074/77326107-ecd2d100-6cde-11ea-8157-ac47d5a3a683.gif)

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
N/A

### Browser
N/A

## Additional context
Is there some other kind of content that can have this issue besides static assets?

**Comment by sumerjabri** [comment]
Will be addressed via Site Policy which will deny ().
