### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by pwntester** [craftercms/craftercms#3911]
Hi,

Im a security researcher working with Github Security Lab (https://securitylab.github.com/). As part of a security review of CMS platforms, we have identified a security vulnerability on Crafter CMS. What would be the best private way to report the details?

We recommend you create a private [GitHub Security Advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) for these findings. This also allows you to invite the GHSL team to collaborate and further discuss these findings in private before they are [published](https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory).

Thanks,
A

**Comment by sumerjabri** [comment]
@pwntester We have one, and we will invite you shortly. Thanks for the discretion.

**Comment by sumerjabri** [comment]
Closing this issue in favor of the security advisory and in accordance with https://docs.craftercms.org/en/3.1/security/security-policies.html
