### ISSUE TITLE
[studio] First publish to staging is not showing published items in Recently Published widget. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3912]
## Describe the bug
When the user publish for the first time to staging those items are not displayed in the Recently Published widget. 

## To Reproduce
1. Create a site from any BP and set staging in Site Config
2. Publish a item to staging
3. Go to Dashboard and check Recently Published widget
4. Items published are not in the widget

## Expected behavior
First items published to staging should be displayed in the Recently Published widget. 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
N/A

### Browser
N/A

## Additional context
If you edit and publish again the item it will be displayed in the widget.

**Comment by sumerjabri** [comment]
This will be addressed with the new database mechanics and APIs. Keeping this ticket for validation upon completion of the work.

**Comment by sumerjabri** [comment]
No longer an issue since the first publish now publishes the entire site as one operation.
