### ISSUE TITLE
[studio-ui] Reactify Dependencies dialog

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3915]
Migrate dependencies dialog to codebase next

**Comment by rart** [comment]
We had discussed fixing the styles of the empty state. They were not fixed.

<img width="735" alt="Screen Shot 2020-04-16 at 2 20 19 PM" src="https://user-images.githubusercontent.com/3928341/79455782-b0e51000-7fed-11ea-9e1a-cd61023a5ffc.png">

**Should be:**

![dependencies-dialog--empty-state](https://user-images.githubusercontent.com/3928341/79456119-3b2d7400-7fee-11ea-9975-edbf82d7c51c.png)

**Comment by jvega190** [comment]
@rart update for empty state is merged, can you please verify?

**Comment by rart** [comment]
👍🏻
