### ISSUE TITLE
[docs] Update plugin docs 

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3916]
* Update [“Create form control plugin docs”](https://docs.craftercms.org/en/3.1/developers/extending-studio/control-plugins.html) to suggest “form-control” instead of just “control” for the example(s).

* Update “Create data source” doc too if there is one.

* Further nesting could also be the suggested approach:
  ```
  /config
    /studio
      /plugins
        /form-engine
          /controls
            /text-input
              main.js
          /data-sources
            /s3
              main.js
  ```
  - The load would then be done this way
    - `plugin/file?siteId={site}&`
        - `type=form-engine/controls&name=text-input&filename=main.js`
        - `type=form-engine/data-sources&name=s3&filename=main.js`
        -

* Add generic plugin docs explaining more of the system.

**Comment by rart** [comment]
Here is a starting point for the generic guide: 
  - [CrafterCMSPluginDevelopmentTurboGuide.md.txt](https://github.com/craftercms/craftercms/files/4379829/CrafterCMSPluginDevelopmentTurboGuide.md.txt)

It needs work to present it as generic, yet clear as possible but the content is good.

**Comment by rart** [comment]
ToDo add note stating to..

Make sure the first parameter sent to moduleLoaded matches the value of the <name /> tag on the XML.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/976
