### ISSUE TITLE
[engine] Strange GraphQL failure on `embedded component` Node Selector with type `Page`

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3917]
1. Clone https://github.com/rart/craftercms-wordify-blueprint.git
2. Use the attached queries [WordifyGraphQLQueries.graphql.txt](https://github.com/craftercms/craftercms/files/4377247/WordifyGraphQLQueries.graphql.txt)
3. On the `byUrlQuerySlider` fragment, `posts_o` adding just key works, but key + component produces error. Just component doesn't err, but the response is not correct either.

**Comment by sumerjabri** [comment]
@rart the steps are not clear, we need better and clearer steps to prioritize this.

Does this fail for embedding a page only? We won't support embedding a page in a page.

**Comment by rart** [comment]
> Does this fail for embedding a page only? We won't support embedding a page in a page.

Yes, for page only. Not embedding, just referencing (content item with reference-type field that points to pages).

We had a conversation when this issue was filed and the conclusion was that it is not supported at the moment; perhaps in the future. Closing as not supported.
