### ISSUE TITLE
[studio-ui] grouped checkbox form control combined with item data source does not properly escape ampersand

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3920]
## Describe the bug
When you update the value with '&' character in a 'checkbox-group' controller, an additional "amp;" String is appended in the "index.xml" file. This results in loading incorrect value in the XML: "&amp;amp;"

## To Reproduce
1. using editorial change category taxonomy item to contain & in the value and key (ex: style & fashion)
2. go to article, open form and tag with style & fashion
3. open XML and note value in xml is style &amp;amp;
4. open form again and note the item is no longer checked

## Expected behavior
Value in XML should be style &amp; fashion. When form is re-opened, value should be selected.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-d23456
Build Number: d234563e697ee66493c712e33b0916715cf5b89f
Build Date/Time: 03-25-2020 22:13:08 -0400

### OS
Any

### Browser
Any

**Comment by rart** [comment]
The value-not-selected issue was fixed. The values on the XML would be a delicate issue to add to 3.1.6. Please retest and if sufficient, let’s carry forward the XML issue to another ticket in a less critical moment. @russdanner

**Comment by russdanner** [comment]
Confirmed
Note that existing content with the defective ;amp will need to "migrated" or simply retagged
