### ISSUE TITLE
[studio-ui] Studio UI hangs on to CrafterSite ID when multi-dot subdomains

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3921]
## Describe the bug
If you have a configuration where:
mysite.com sets a crafterSite=someSite and later you go to authoring at a domain of cms.mysite.com and that crafterSite ID does not exist the user has to clear their cookies to make Studio and preview work.

common API.js seems to be the main source of the issue
```
domainVal = (CStudioAuthoringContext.cookieDomain.indexOf(".") > -1) ? "domain=" + CStudioAuthoringContext.cookieDomain : "";
```

## To Reproduce
1. install crafter authoring and delivery
2. configure /etc/hosts mysite.com and cms.mysite.com to localhost then point a webserver (both port 80) such that cms.mysite.com points to 8080 and mysite.com points to engine (where the siteID on engine is different than the one used for the site in authoring)
3. hit delivery
4. go to authoring and login 
5. see that you will get an exception on preview
6. clearing cookies will correct his issue

## Expected behavior
Studio's cookie should consider the whole server/domain name, not just part of it

## Screenshots
N/A

## Logs
https://gist.github.com/russdanner/241b38ab901c07ed6738ecf00f3c2cee

### Version
Studio Version Number: 3.1.6-SNAPSHOT-d23456
Build Number: d234563e697ee66493c712e33b0916715cf5b89f
Build Date/Time: 03-25-2020 22:13:08 -0400

### OS
Any

### Browser
Any

**Comment by rart** [comment]
Check out the cookie setting logic on 2019. We could possibly bring it to develop — with considerations. @jvega190

**Comment by sumerjabri** [comment]
@russdanner please test again in 4 and see if it's still an issue
