### ISSUE TITLE
[studio] Change the "no preview image available" default pic to something more subtle

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3922]
Please change the default image to something more subtle.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/3928341/77639428-0d0dc480-6f59-11ea-83fa-c2d5acf3815f.png">

Here's a proposal of what to replace with:

![unassigned-content-type-image](https://user-images.githubusercontent.com/3928341/77640306-72ae8080-6f5a-11ea-8020-3e0742ea0657.png)

Or something slightly more visual:

![content-type-preview-unassigned](https://user-images.githubusercontent.com/3928341/77640482-bf925700-6f5a-11ea-9482-5a53d72fb199.png)

**Comment by sumerjabri** [comment]
You can grab the image from Roy.

**Comment by rart** [comment]
@jvega190 the pic was changed on 3.1 too; please validate if styles need tweaking.

**Comment by jvega190** [comment]
Validaded, no style updates are needed
