### ISSUE TITLE
[studio] Update the Upgrade Manager to support multi-environment site configuration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3923]
We now support a set of configuration files per site per env (Dev, QA, Prod -- overrides). UM needs to become aware of that and support the upgrade of root configuration files and env overrides.

**Comment by sumerjabri** [comment]
@yacdaniel Please validate.

Related to: https://github.com/craftercms/craftercms/issues/4023

**Comment by yacdaniel** [comment]
Verified UM works with multi-env site config.
