### ISSUE TITLE
[studio] modifier value in item_metadata table set to 'N/A' after database repo sync

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3924]
## Describe the bug
After content is edited the value for `modifier` in `item_metadata` table is set to the username who did the edit. When studio finish the sync between db and repo that value is set to `N/A` which causes data loss. 
Are we losing other metadata across different edit/add/delete actions? where else?

## To Reproduce

0. Have connection to db ready so we can see the values immediately after the edit.
1. Create site from empty BP and edit home page, do the edit from dashboard so you can see the `Last Edited By` 
2. Check for the `modifier` value in crafter db `select * from item_metadata where site='empty' and path='/site/website/index.xml'`
3. Wait for the finish of sync between db and repo site `[site.SiteServiceImpl] | Done syncing database with repository for site: empty`
4. Do step 2 again, this item `modifier` will have the value `N/A`

## Expected behavior
`modifier` value don't get changed when sync happens and value stays until next edit.

## Screenshots
![modifier](https://user-images.githubusercontent.com/6722074/77761205-4b5cbf80-6ffd-11ea-9222-590591f4eb40.gif)

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
Linux

### Browser
N/A

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1934

**Comment by yacdaniel** [comment]
Verified fixed.
