### ISSUE TITLE
[deployer] Command line processor should pass site path and operation as parameters

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3927]
**Is your feature request related to a problem? Please describe.**
Developers want to use the command line processor to extend Crafter CMS deployment processes by calling external programs.  Today the command line processor simply calls a command. It does not transmit the files of a changeset or the operation taken on those files. This limits how the out of the box processor can be user.

**Describe the solution you'd like**
Enhance the processor to call the command once per file and pass the site, path and operation for each file. 

**Describe alternatives you've considered**
Pass the entire change set as a parameter to the external command and let the external command deal with it.  This may be an issue in large change sets. Therefore it's recommended that a per file/op approach be adopted.

That said, a batch model would be very useful.

- [x] add feature
- [ ] update documentation https://docs.craftercms.org/en/3.1/system-administrators/deployer/processors-guide.html

**Comment by jdrossl** [comment]
@russdanner how about exposing the changes as environment variables to the external command? for example `NEW_FILES`, `UPDATED_FILES`, `DELETED_FILES`. I think that is better than executing the command multiple times

**Comment by russdanner** [comment]
My only concern with this is overflow bugs:
```
Linux seems to have a default limit of 128KiB (131072) on the length of any single environment variable -- any attempt to set an envvar longer than this and then run any program will result in an 'Argument list too long' error```

**Comment by russdanner** [comment]
@jdrossl @alhambrav We need to update this document:
https://docs.craftercms.org/en/3.1/system-administrators/deployer/processors-guide.html

**Comment by russdanner** [comment]
Functionality Confirmed

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/957

**Comment by russdanner** [comment]
Confirmed
