### ISSUE TITLE
[studio] Studio does not report error on bulk upload to UI on write failure

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3931]
## Describe the bug
Studio does not report error on bulk upload to UI on write failure. Instead, UI signals a success to user. 

## To Reproduce
1. Configure blob store to S3 bucket that does not exist
2. Attempt bulk upload
3. UI shows green progress bar, backend catalina log shows error, no file is uploaded.

## Expected behavior
UI should report a failure to the user.

## Screenshots
<img width="1365" alt="Screen Shot 2020-04-01 at 6 21 03 PM" src="https://user-images.githubusercontent.com/169432/78192175-9df70b00-7445-11ea-9c1e-fc917a2cd7f0.png">

<img width="1113" alt="Screen Shot 2020-04-01 at 6 25 28 PM" src="https://user-images.githubusercontent.com/169432/78192493-47d69780-7446-11ea-9288-89515bfd849e.png">

## Logs
https://gist.github.com/russdanner/6e6e40d2a36a16289a9878b76241e433

### Version
Studio Version Number: 3.1.6-SNAPSHOT-768fca
Build Number: 768fca62056b29633b1569e06cb2ff966e5826d2
Build Date/Time: 04-01-2020 17:25:09 -0400

### OS
Any

### Browser
All

**Comment by russdanner** [comment]
This is an high priority unless we can determine that only some write failures of low probability will return as a 200

**Comment by sumerjabri** [comment]
@dejan-brkic can this be handled within the scope of API1 before we move to API2?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1940

**Comment by russdanner** [comment]
Confirmed
