### ISSUE TITLE
[studio] Static asset folder with dot in the name show as files the UI

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3932]
## Describe the bug
 Static asset folder with . in the name show as files in Studio UI

## To Reproduce
1. in static assets bulk upload a folder with a . in the name 
2. Note on disk the folder is a folder
3. In the uI the item is represented as a file

## Expected behavior
A folder with any name should be represented properly in the UI as a folder

## Screenshots
<img width="944" alt="Screen Shot 2020-04-01 at 10 42 51 PM" src="https://user-images.githubusercontent.com/169432/78205927-72871700-746b-11ea-93ee-d85c4c2be0cb.png">

## Logs
NA

### Version
Studio Version Number: 3.1.6-SNAPSHOT-768fca
Build Number: 768fca62056b29633b1569e06cb2ff966e5826d2

### OS
Any

### Browser
Any

## Additional context
The only way to get such a folder into static assets is via bulk upload, a script or via git. Create folder actions remove the dot

**Comment by russdanner** [comment]
Based on previous experience, i believe this bug has to do with the dot being used as a determining factor in deciding if an item is file when building the API response. As such this is a long standing issue and is thus low priority due to the obvious workaround of renaming the folder and the duration of the limitation.

**Comment by jvega190** [comment]
@sumerjabri @russdanner after checking I found that some of the item fields are incorrect (coming from API), causing the folder to show and behave incorrectly.

![Screenshot from 2020-10-14 15-02-22](https://user-images.githubusercontent.com/18267471/96047782-dc2ca880-0e32-11eb-93c1-06a8741bc492.png)

Those fields are incorrect comparing to another folder's fields. `path` also has an incorrect value, and it will cause the folder show incorrect items when opening.

![Screenshot from 2020-10-14 15-36-41](https://user-images.githubusercontent.com/18267471/96047999-3af22200-0e33-11eb-97ef-393412f9a74e.png)

**Comment by sumerjabri** [comment]
@dejan-brkic would switching to the new API address this issue?

**Comment by jvega190** [comment]
@sumerjabri should this be reassigned since it's not an ui issue?

**Comment by sumerjabri** [comment]
@jvega190 just hold tight while we get an answer from @dejan-brkic

**Comment by jvega190** [comment]
checked on this again, using '/studio/api/1/services/api/1/content/get-items-tree.json' (legacy sidebar tree), uploaded a folder named `test.js` (using .js as in ticket description)

![2021-04-12_16-20](https://user-images.githubusercontent.com/18267471/114469891-2fe23980-9bab-11eb-839c-774258e3f336.png)

**Comment by dejan-brkic** [comment]
Not issue anymore with API 2

**Comment by russdanner** [comment]
Confirmed
