### ISSUE TITLE
[studio-ui] File upload (with upppy) progress timeout issue

### ISSUE THREAD

**Issue by tringMokesh** [craftercms/craftercms#3933]
## Describe the bug
While making a XHRrequest uppy is cancelling the request after 30 seconds

## To Reproduce
1. Go to crafter
2. Configure s3 bucket for video upload
3. Upload large size video
4. When request takes more than 30 seconds, request getting cancelled

## Expected behavior
Video should be uploaded

## Logs
Upload stalled for 30 seconds, aborting.

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
linux

### Browser
Chrome
Firefox

## Additional context
Kindly remove the timeout limit because the upload might take unpredictable time, if video size is large or network is slow. Thanks.

**Comment by rart** [comment]
@tringMokesh 

When no upload **progress events** have been received for X amount of milliseconds, it is assumed that the connection has an issue and the request is aborted. Note that this is a timer between **progress events**: [the total upload can take longer than this value](https://uppy.io/docs/xhr-upload/#timeout-30-1000).

This implies that the S3 server is not replying with progress. There's a lot of moving parts here but there could be an issue with your bucket config and this may be the real culprit of the _timeout_. 

Please:
1. Double check your settings. Somehow, verify they are correct (e.g. curl, some other external test using the settings and credentials you're using in Crafter CMS bucket config).
2. Please supply your bucket config (masking sensitive information, of course).
3. Please specify the config steps you went through to configure your bucket in Crafter CMS (per your ticket report, please provide further details around step # 2).

**Comment by tringMokesh** [comment]
Hi I tried uploading a file from local to crafter assets locally (file size: 2GB), The same issue happening there as well. So this is not related to s3 config it seems.

**Comment by sumerjabri** [comment]
Might be related to https://github.com/craftercms/craftercms/issues/3931

**Comment by sumerjabri** [comment]
Temporary fix for 3.1.6, and a better fix for the following release in the ticket https://github.com/craftercms/craftercms/issues/3934

**Comment by sumerjabri** [comment]
@tringMokesh please test and let us know how it goes.

**Comment by tringMokesh** [comment]
> @tringMokesh please test and let us know how it goes.

@sumerjabri As I shared you in the slack I'm getting maven build error. And the build that you have shared in gdrive is also giving me 500 error.

**Comment by sumerjabri** [comment]
Timeout removed and will become configurable.
