### ISSUE TITLE
[studio] Status call should not return success unless the DB is ready to work.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3937]
Right now, even if the DB is not ready to accept connections or it crashed, the `/studio/api/2/monitoring/status.json` API call is returning success (HTTP 200). The API call should only be successful if Studio is basically usable (the DB is up and running and the upgrade manager has finished running).

**Comment by avasquez614** [comment]
Seems like Studio is not the one responding to `/studio/api/2/monitoring/status.json` (the app is down), it is Engine with a 200 and a `{}` response.

**Comment by sumerjabri** [comment]
Return 404 as HTTP status along with the existing Site not found.

**Comment by avasquez614** [comment]
Verified
