### ISSUE TITLE
[studio] Asset processing field keep original should be optional

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3943]
## Describe the bug
The doc states that keepOriginal tag/field is **optional**
https://docs.craftercms.org/en/3.1/developers/asset-processing.html?highlight=asset
However, the system fails to write #3942 in some cases when this field is not present.

Please make this field optional
## To Reproduce
See steps from #3943 

## Expected behavior
System should not fail if field is not present

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-768fca
Build Number: 768fca62056b29633b1569e06cb2ff966e5826d2

### OS
Any

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1942

**Comment by russdanner** [comment]
Confirmed
