### ISSUE TITLE
[studio] Add the status/attribute of an item that indicates it is versioned

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3945]
External store items (like S3 stored items) may or may not be versioned. Please add that to the list of item metadata (bitmap?). Let's discuss when ready.

**Comment by sumerjabri** [comment]
Related to Available Actions.

**Comment by sumerjabri** [comment]
@dejan-brkic this might already be addressed by the new AA bitmap where we don't allow History for Blob Store items.

**Comment by dejan-brkic** [comment]
It will be addressed here:
https://github.com/craftercms/craftercms/issues/4556
