### ISSUE TITLE
[studio] publish to live fails silently in logs when studio does not have access to bucket

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3948]
## Describe the bug
Publish action on s3 blob object to live fails silently in logs when studio does not have access to bucket.

Studio will leave item in unpublished state but there is no indication to administrator why publishing has failed to make publish happen. This scenario may be very difficult to debug without any indication from the system.

## To Reproduce
1. upload an blob to s3, note that it is in sandbox
2. more permissions to bucket for delivery so Studio cannot access it
3. Approve and publish to live. Note no errors in the log.

## Expected behavior
A error should be generated stating that access to the bucket cannot be established within the Studio log.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-9f970a
Build Number: 9f970a6828af679c2ab9ded921f60b6c88b59cf6

### OS
Any

### Browser
Any

**Comment by russdanner** [comment]
In some cases I am able to get studio to stop the publishing queue and report the error. Down grading this tho a low.

**Comment by jdrossl** [comment]
@russdanner I was not able to reproduce the issue, in all my tests I see the errors in the log, the notification is sent & the queue stops

**Comment by sumerjabri** [comment]
Can't reproduce.
