### ISSUE TITLE
[docs] Document process for adding Staging "later" to a site that uses blob stores

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3949]
**Is your feature request related to a problem? Please describe.**
Staging publishing target is an optional target that can be added at any time.

When blob stores are used, there needs to be a documented process for properly setting up the store for `Staging`. Studio does not automatically clone the live blob store and a bulk publish of the store to staging will not work at this time.
https://www.loom.com/share/7dde0f6889bf4fc59ecc822f43b34c9a

**Describe the solution you'd like**
Create a document that states if you add staging at any time after the fact you must copy the `Live` S3 bucket to the `Staging` bucket.

**Additional context**
Studio only publishes assets to staging that is not in a LIVE, UNEDITED state
https://www.loom.com/share/7dde0f6889bf4fc59ecc822f43b34c9a

**Comment by jdrossl** [comment]
@russdanner this could be a bug in Studio, the .blob files are supposed to be published  to staging in git and based on that copied in S3.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/950

**Comment by russdanner** [comment]
@jdrossl We don't think it is a bug at the moment.

**Comment by russdanner** [comment]
@sumerjabri this document uses the AWS console to copy assets. Should we be describing the CLT process instead or addition to this per our conversation?

**Comment by sumerjabri** [comment]
@russdanner What's a CLT?

@russdanner Admins are free to copy the files any way they like, this is one way of doing it.

**Comment by russdanner** [comment]
Confirmed
