### ISSUE TITLE
[studio] Add inspection if an action is allowed to be executed

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3953]
Add inspection if an action is allowed to be executed.
Currently, studio has permissions check if a user is authorized to execute an operation. It is executed on the outer service layer. It is needed to perform an additional check if an action is allowed to be executed depending on some more conditions (e.g. type of content, type of storage, regular expressions, etc.) This check should be executed on the inner service layer in order to control composite operations.

Related tickets:
https://github.com/craftercms/craftercms/issues/3871
https://github.com/craftercms/craftercms/issues/3952

**Comment by sumerjabri** [comment]
Superseded by https://github.com/craftercms/craftercms/issues/3954
