### ISSUE TITLE
[studio] Parse and cache `permission-mappings-config.xml`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3956]
In support of https://github.com/craftercms/craftercms/issues/3954

We must have the `permission-mappings-config.xml` parsed and cached in memory for speed of execution.

The file must be loaded into memory and parsed ahead of time, the cached version must be updated every time:
- The file is updated via API
- The file is updated via git sync

The parsed format of the file in RAM must facilitate rapid evaluation of permissions for the semantic evaluation of possible actions, see https://github.com/craftercms/craftercms/issues/3954 for context.

Progress:
- [x] Design the data structure
- [x] Design the caching mechanism
- [x] Implement
- [x] Switch to use the new configuration cache and standardize the key in src/main/java/org/craftercms/studio/impl/v2/security/AvailableActionsResolverImpl.java and one other file to be identified
- [x] Make sure this is invalidated when the file is updated via Git, such that if the key matches the file name of `permission-mappings-config.xml`, general approach:
```
  Invalidate multiple keys by having a single function that generates many keys for one file. One key per type of object we cache for this config. Example: `permission-mappings.xml` is cached twice, and must be invalidated twice.
```
- [x] Test and validate

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2224
