### ISSUE TITLE
[studio-ui] Datasources that contains "_" are breaking the display of options in form engine.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3957]
## Describe the bug
When the name of the data source contains a underscore  `_` the form engine fails to display the options

## To Reproduce
1. Create a site from editorial BP
2. Go to the Page Article Content Type, notice that `Upload Images` and `Existing Images` both contains a  `_` in the Name property.
3. Add another image data source(with no underscores in the name) and add it to the existing `Image` Control 
4. Go to a page article, click to edit the page and check the DS options for the image

## Expected behavior
All the data sources options are displayed. 

## Screenshots
https://www.loom.com/share/7f9820ba301f4f5c962b86df86d49212

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
Linux

### Browser
Chrome / Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Verified fixed.
