### ISSUE TITLE
[studio-ui] Create folder in Scripts blocks the use of {} in the name which are used to indicate parametrized portions of the url

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3959]
## Describe the bug
Create folder in Scripts blocks the use of {} in the name which are used to indicate parametrized portions of the url

## To Reproduce
1. open scripts/rest
2. create a folder under rest called {myParam}
3. Note the UI blocks the user from doing this

## Expected behavior
{ } are valid characters for folder names under the /scripts/rest folder and should be allowed in this space

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-9f970a
Build Number: 9f970a6828af679c2ab9ded921f60b6c88b59cf6

### OS
Any

### Browser
Any

**Comment by yacdaniel** [comment]
@aachavarria please check this, I'm not able to create new folders/controllers under a folder with `{}` 
I was able to tweak the request and encode the path parameter and a controller was created but is not visible in UI. 
Ping me if you need details.

**Comment by yacdaniel** [comment]
@aachavarria I'm still not able to create folders and controllers under a folder with `{}` 
![image](https://user-images.githubusercontent.com/6722074/104333313-b73de500-54b6-11eb-826e-9605d71003a5.png)

**Comment by aachavarria** [comment]
Im able to create Folders and Files, but the API "/studio/api/1/services/api/1/content/get-items-tree.json" is not returning the children [] for the folder with {} in the name, that is why looks like it is not working. @yacdaniel 

Pending to be fixed on BE; @sumerjabri

**Comment by sumerjabri** [comment]
@dejan-brkic would that API get deprecated given the new API? If not, we must fix it. Also, the new API should accept the params as required.

**Comment by jdrossl** [comment]
@aachavarria looks like the UI is not properly encoding the curly brackets: 

![Screenshot from 2021-03-22 10-50-50](https://user-images.githubusercontent.com/1236955/112027315-af28a400-8afc-11eb-86ff-cd71cef9e9a1.png)

**Comment by yacdaniel** [comment]
Verified fixed.

**Comment by sumerjabri** [comment]
@jdrossl indicated this is an issue in 3.1 @russdanner @rart

**Comment by russdanner** [comment]
Confirmed
