### ISSUE TITLE
[Studio] Copy-Paste & Duplicate sends different parameters to the ContentProcessorPipeline.

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#396]
Some parameters used in the ContentProcessorPipeline are sent with wrong values compared to the call to write a new file.

# Examples:

## New Operation:
- content.path = "/site/website/PATH/test.xml"
- _id = "SITE:/site/website/PATH/test.xml:test.xml:CONTENT_TYPE"

## Copy / Duplicate Operation:
- content.path ="/site/website/PATH" *(Missing file name)*
- _id = "SITE:/site/website/PATH:test-1.xml:CONTENT_TYPE" *(Missing file name)*

**Comment by russdanner** [comment]
Dejan,

This is not the same as the duplicate bug we looked at previously.

We changed the UI to rely on the back-end (as it was previously.) for duplicate  I will have that committed as soon as I can today.

**Comment by dejan-brkic** [comment]
That is UI issue. UI is not consistent with path format when sending params on write content. Sometimes it is full path (with file name) some times it is just folder path. 
Behavior is not recent. It has been like that forever (v 1.6 and probably older)

**Comment by russdanner** [comment]
@dejan-brkic 
Does duplicate API call expect something different than what is being sent?

**Comment by dejan-brkic** [comment]
That is difficult to answer since it is obvious that duplicate API is not been used for a while. I am not even sure if it is a valid API, because i don't know how long it is not in use. The API as it is now expects only site and path as param. I know write content API  is using a lot more params. From that perspective, workaround that is in use now does not look like good idea at all.

**Comment by russdanner** [comment]
We removed the work-around based on write does not send any duplicate signal.  It's a technically and architecturally invalid work-around.  So we're going to need to make the duplicate service work... whatever the issues are.
