### ISSUE TITLE
[studio] Studio is not reading multi-environment configs

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3960]
## Describe the bug
When multi environment is set the configuration files are read from normal studio and not from the multi-env override. I tried with blob stores and aws profiles, none of them when picking the config from the multi env. 

## To Reproduce
1. Enable multi environment in studio https://docs.craftercms.org/en/3.1/site-administrators/studio/multi-environment-configurations.html
2. Add a AWS profile for the multi-env
3. Try to upload an asset
4. See error in catalina.out error, studio is using the aws profile config from normal studio which does not exist. 

## Expected behavior
Configs should be read from multi-env. 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by alhambrav** [comment]
Verified.
