### ISSUE TITLE
[docs] Please document plugin host page

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3962]
There are 3 different setups:

- **Vanilla**: the simplest possible plugin with a single JS index.js 
- **React**: a create-react-app react application. This is one of the most popular set ups for react apps and one of the advantages is that people can run their own little dev server to run the app out side of studio — because of this, devs wouldn’t need to commit every single change so studio can view the changes like in the other two setups.
- **Modern**: also a react-based app but not using create-react-app, but using still, using a modern setup (transpilation and bundling). This one has a watch mode that transpiles, bundles and commits on every change; it’s quite nice but git log will get a fair amount of history since, when developing and testing devs do loads of changes/saves. This can be mitigated with, developing, doing all the work and once you’re in a happy place `git reset {commit}` to clean the log and only commit the significant milestones.

These can be viewed by:

1. Using the Create site dialog, create a site from git; name it `editorial` (sites can have any name but this plays a role in the config of the different setups). The remote URL is https://github.com/rart/craftercms-editorial-ice
2. cd into your `{sandbox}/sources` and run the commands below. After that, you should end up with `{sandbox}/config/studio/plugins/apps/{vanilla,react-app,modern}`
```
chmod +x plugin_deploy.sh
./plugin_deploy.sh --target=studio-plugin-cra --name=react-app
./plugin_deploy.sh --target=studio-plugin-modern --name=modern
./plugin_deploy.sh --target=studio-plugin-vanilla --name=vanilla
```
3. Commit the plugins folder

Visit the the plugin page with the respective URL for the plugin to view
```
/studio/plugin?site=editorial&type=apps&name=vanilla
/studio/plugin?site=editorial&type=apps&name=react-app&file=build/index.html
/studio/plugin?site=editorial&type=apps&name=modern
```

Since we’ve had the sources folder pattern for a while now, that’s where plugin source should live and the build should placed in the `…/config/studio/plugins/*` folder. 

Please see https://github.com/rart/craftercms-editorial-ice/tree/master/sources for most up to date plugin samples

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/976
