### ISSUE TITLE
[studio] Can't create a site from remote

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3965]
## Describe the bug
Creating a site from a Git remote fails.

## To Reproduce
1. Go to Studio.
2. Try to create a site from this remote Git repository: https://github.com/craftercms/video-center-blueprint.git

Site creation should fail with an error like the attached log.

## Expected behavior
Site creation from remote should work

## Logs
https://gist.github.com/avasquez614/ceaf65ac4619abe8ad8e4a9fb4dba487

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1945

**Comment by avasquez614** [comment]
Verified
