### ISSUE TITLE
[studio-ui] Text area box in form becomes misaligned at a certain point when zooming out

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3968]
**Is your feature request related to a problem? Please describe.**
When changing the font size of the browser to be smaller in order to see more of the form, the text area box in the form moves to a different alignment at a certain point when zooming out
<img width="501" alt="Screen Shot 2020-04-14 at 9 47 45 AM" src="https://user-images.githubusercontent.com/25483966/79233666-2b1f6400-7e37-11ea-9187-d3d441054b16.png">

**Describe the solution you'd like**
The text area box should always be aligned no matter the size of the texts

**Steps**
1. To reproduce, create a site using a bp with a text area box in content type, such as the  Website Editorial bp or the videocenter bp.  Let's use a site created using the website editorial bp as an example
2. Edit an article
3. Make the text size smaller by pressing the `CTRL` + `-` keys or, by zooming out, notice that the text area box is still aligned the first few times you zoom out
<img width="804" alt="Screen Shot 2020-04-14 at 10 08 03 AM" src="https://user-images.githubusercontent.com/25483966/79234176-e6e09380-7e37-11ea-9561-083088e7f410.png">

4. Keep zooming out and notice at some point, the text area box becomes misaligned
<img width="498" alt="Screen Shot 2020-04-14 at 10 10 11 AM" src="https://user-images.githubusercontent.com/25483966/79234373-28713e80-7e38-11ea-9e91-aee908f9fa9e.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
There's a whole new set of style on form engine. I don't see this happening any more. Please verify.

**Comment by alhambrav** [comment]
Verified ticket does not apply anymore to current set of style on form engine.
