### ISSUE TITLE
Asset processing for S3 images (Image resize)

### ISSUE THREAD

**Issue by hhettiarachchi** [craftercms/craftercms#3971]
Crafter 3.1.4  has an asset processing pipeline so that you can upload hi-res images and then use image processing software to transform and crop them.

But this is only working for images in the static-assets. This needs to be extendable for images on S3 as most production environments use S3 to store the assets depending on the number of images.

**Comment by russdanner** [comment]
This functionality has been addressed and will be released in 3.1.6
https://github.com/craftercms/craftercms/issues/3744
