### ISSUE TITLE
[studio] UM should only add to git the files it updates

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3972]
Uncommitted or unstated files seem to be getting committed with the upgrade manager stuff

tags: upgrade manager git add all

**Comment by rart** [comment]
@yacdaniel no idea how to test this. please help 🙂 ping me if you need clarification as to what the issue was.

**Comment by yacdaniel** [comment]
sure @rart I think I have a way to reproduce it by triggering upgrade manager during Studio's  start up and having a non clean git site repo.

**Comment by yacdaniel** [comment]
Verified fixed.
