### ISSUE TITLE
[studio] api/2/configuration/get_configuration_history doesn't work when default environment is set

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3979]
## Describe the bug
The API 2 `configuration/get_configuration_history` doesn't work when environment is set to `default`

## To Reproduce
1. Create a site from any BP
2. Go to `Site Config - Configuration`, edit and save a configuration
3. Click History
4. See empty list of versions

## Expected behavior
Versions are displayed

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}
![image](https://user-images.githubusercontent.com/6722074/79596441-cdd91c00-809d-11ea-9ecd-0480deee74ad.png)

## Logs
N/A

### Version
`3.1.6-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
3.1.x:
https://github.com/craftercms/studio/pull/1961

**Comment by dejan-brkic** [comment]
develop:
https://github.com/craftercms/studio/pull/1962

**Comment by yacdaniel** [comment]
@rart please check this: when I click Revert in the History of a configuration, the History dialog goes blank
![revertConfig](https://user-images.githubusercontent.com/6722074/79765536-f94d4800-82e3-11ea-9b57-258eba662e0a.gif)

**Comment by aachavarria** [comment]
@dejan-brkic "/studio/api/1/services/api/1/content/get-item-versions.json?site=editorial&path=/config/studio/default/code-editor-config.xml&maxhistory=100"
it is returning versions: []

**Comment by dejan-brkic** [comment]
@aachavarria please use API 2 `get_configuration_history` for configuration files

**Comment by yacdaniel** [comment]
Verified fixed in `support/3.1.x`. 
I'll close this in `3.1` project and assign it to `3.2` work.

**Comment by yacdaniel** [comment]
@aachavarria please check this behavior:
If i click revert and confirm, and the move to another section of the `Site Config` and go back to any configuration and revert it, a new `History` header is added. 
![revert issue](https://user-images.githubusercontent.com/6722074/80254481-7e17c900-8638-11ea-99c1-c179f50b1e92.gif)
This happens in both `support/3.1.x` and `develop`

**Comment by yacdaniel** [comment]
Verified fixed.
