### ISSUE TITLE
[studio-ui] Invalid site notification after creating site from marketplace

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#3980]
An error notification shows after creating a site from marketplace (with no previous sites created). crafterSite cookie is not being properly set.

<img width="623" alt="Screen Shot 2020-04-16 at 10 42 22 AM" src="https://user-images.githubusercontent.com/18267471/79619688-dd228e80-80ca-11ea-9986-9762f378be51.png">

**Comment by jvega190** [comment]
@jdrossl can you please validate?

**Comment by jdrossl** [comment]
Verified
