### ISSUE TITLE
[studio] Overlayhook context changed again

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3982]
## Describe the bug
We had a similar issue before with the per-environment changes that broke the overlayhook (which breaks ICE). Looks like something similar happened again. 

## To Reproduce
1. Go to preview
2. Try to use ICE
3. Notice it doesn't work

### Lower level
- Type `localhost:8080/studio/overlayhook` in the browser & see output
```js
crafterRequire.config({
  baseUrl: '/static-assets/scripts',
  paths: {
    'libs': '/static-assets/libs/',
    'jquery': '/static-assets/libs/jquery/dist/jquery',
    'jquery-ui': '/static-assets/libs/jquery-ui/jquery-ui',
    'amplify': '/static-assets/libs/amplify/lib/amplify.core',
    'noty': '/static-assets/libs/notify/notify.min'
  }
});

crafterRequire(['guest'], function (guest) {
  guest.init({
    hostOrigin: '',
    studioContext: 'studio',
    studioStaticAssets: 'static-assets'
  });
});
```
- Test the value of `envConfig.authoringServer`. Notice it is blank.
- Test the value of `envConfig.previewServerUrl`. Notice it is blank.

## Expected behavior
- ICE works
- `envConfig.authoringServer` value is `"{host}:{port}/{studioContext}"` instead of `""`
- Overlayhook returns correct full paths
```js
crafterRequire.config({
    baseUrl: 'http://authoring.sample.com:8080/studio/static-assets/scripts',
    paths: {
        'libs': 'http://authoring.sample.com:8080/studio/static-assets/libs/',
        'jquery': 'http://authoring.sample.com:8080/studio/static-assets/libs/jquery/dist/jquery',
        'jquery-ui': 'http://authoring.sample.com:8080/studio/static-assets/libs/jquery-ui/jquery-ui',
        'amplify': 'http://authoring.sample.com:8080/studio/static-assets/libs/amplify/lib/amplify.core',
        'noty': 'http://authoring.sample.com:8080/studio/static-assets/libs/notify/notify.min'
    }
});

crafterRequire(['guest'], function (guest) {
    guest.init({
        hostOrigin: 'http://authoring.sample.com:8080',
        studioContext: 'studio',
        studioStaticAssets: 'static-assets'
    });
});
```
- `${envConfig.previewServerUrl}` is the full preview server URL
- `${envConfig.authoringServer}` is the full authoring server

### Version
3.2-SNAPSHOT

### OS
Mac

### Browser
Chrome. But irrelevant, it's a server-side issue

## Additional context
- These are the ones I've noticed. There's likely more.
- This is likely related to the removal of env config (xml, etc)
- We could use this as an opportunity to clean up env variables in consistency (e.g. authoringServer is not postfixed by "Url" but previewServerUrl is) and co-location (i.e. all the FTL context in a single file instead of envConfig + applicationContext).
- We had previously discussed using the client side api (i.e. window.location.origin) for part of this, however retrieving it in the backend could provide scalability

**Comment by sumerjabri** [comment]
@rart fill out the ticket template metadata

**Comment by rart** [comment]
This seems like is all realated to https://github.com/craftercms/craftercms/issues/3889
This PR addresses the issues and should restore ICE: https://github.com/craftercms/studio-ui/pull/1724

We should however assess and make inventory of what remains in the FTL context and what doesn't and clean up.

**Comment by rart** [comment]
Closing in favour of https://github.com/craftercms/craftercms/issues/3889
