### ISSUE TITLE
[studio-ui] Parameterize leftActions and rightActions on DialogHeader component

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3983]
The idea is that the DialogHeader would support doing things like these easily:

<img width="450" alt="param-header-actions" src="https://user-images.githubusercontent.com/3928341/79685664-c7cc7200-823a-11ea-9d8b-539d89e6032d.png">

If looks convoluted perhaps we can refactor the DialogHeader further breaking it down so DialogHeader doesn't change and another component becomes the lower level that supports this.

**Comment by yureii00** [comment]
Is this component should be used as a DialogHeader?

**Comment by rart** [comment]
👍🏻
