### ISSUE TITLE
[docs] Add _Since_ and _Last Updated_ tags to all pages

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3984]
**Is your feature request related to a problem? Please describe.**
Presently, the documentation doesn't clearly show when a page or feature was introduced to Crafter CMS, nor does it clearly show when a page/feature was last updated. Having those two piece of information on the docs will help users in knowing what's available for _their_ version and when they need to update their code/install.

**Describe the solution you'd like**
Add easy-to-use SphinxDoc mechanics or similar to allow for consistent, cross-docs annotation of all pages with these two pieces of metadata.
The tags are:
- _Since_ | _version_
- _Last Updated_ | _version_

**Describe alternatives you've considered**
Use of images or other means of tagging. Use of SpringFramework-like tags for docs.

**Checklist**
- [x] Define the tags
- [x] Create the SphinxDoc mechanics
- [x] Create the CSS to render these pretty
- [ ] Add to all pages in `master` (current release)
- [ ] Validate

**Example Aesthetics**

![image (3)](https://user-images.githubusercontent.com/3931908/79886201-61745a80-83c6-11ea-8a34-785cb769c20d.png)

![image (1)](https://user-images.githubusercontent.com/3931908/79886387-c92aa580-83c6-11ea-9c5d-83463ca3ac88.png)

**Comment by alhambrav** [comment]
@jvega190 Please create the CSS to render the tags pretty.  I added some text to display the versions only as an example in the `layout.html` and to test the tags.

Here are the tags to be added at the top of the docs pages:
```
:since-version: 3.1.0
:last-updated: 3.1.18
```

**Comment by sumerjabri** [comment]
Mostly done and ongoing for all new docs.
