### ISSUE TITLE
[studio-ui] Nested drop-zone created component but it's not binding it to the drop-zone

### ISSUE THREAD

**Issue by malnajdi** [craftercms/craftercms#3988]
## Describe the bug
I used the empty blueprint to test the nested dropzones. I added a freemarker block which accept a Component content type called `section` and when i drag `section` to that dropzone it works fine. Now that section component also accept a dropzone of any Component content type exists in the site. When i drag any component is gets created but never bound to that dropzone. If i would do the same steps with the manual way by clicking Edit and add component it works.

## To Reproduce
1. create a new site based on the **empty blueprint**.
2. go to **site config**
3. Open **A Page** content type
4. Add a node selector named **sections** with a data-source of embedded-content with a type of `/component/layoutsection`
5. edit the template to have this block of
```
<section class="section" <@studio.componentContainerAttr target="sections_o" component=contentModel/>>
  <#if contentModel.sections_o?? && contentModel.sections_o.item??>
    <#list contentModel.sections_o.item as section>
      <@renderComponent component=section />
    </#list>
  </#if>
</section>
```
6. create a new Component Content Type called **Layout - Section** which will have a type name as `/component/layoutsection`
7. add a form section
8. add node-selector inside the form section and call it **Components** with a variable name `components_o`
9. assign a **shared-content** data-source to this node-selector named **Shared Components** with a path repository/browse path `/site/components/`
10. edit the template to be
```
<#import "/templates/system/common/cstudio-support.ftl" as studio />
<div <@studio.componentAttr path=contentModel.storeUrl ice=true /> >
    <div style="border: 1px solid black" <@studio.componentContainerAttr target="components_o" component=contentModel/>>
        <#if contentModel.components_o?? && contentModel.components_o.item??>
            <#list contentModel.components_o.item as component>
                <@renderComponent component=component />
            </#list>
        </#if>
    </div>
</div>
```
11. edit the Preview Components Configurations
```
<config>
    <category>
        <label>Layouts</label>
        <component>
            <label>Section</label>
            <type>/component/layoutsection</type>
        </component>
    </category>
    <category>
        <!-- any component of your choice to test -->
        <label>Basic Components</label>
        <component>
            <label>Header</label>
            <type>/component/componentheader</type>
            <path>/site/components/headers</path>
        </component>
    </category>
    <browse>
        <label>Header</label>
        <path>/site/components/headers</path>
    </browse>
</config>
```
12. Open the home page and click preview tools to drag component.
13. drag a section component (it should work fine)
14. drag any component inside the section that we dragged (in my case a header component)
15. A header will be created but it won't be bound to that dropzone.

Note: my header component is just HTML it has nothing at all.

## Expected behavior
When I drag a component to the dropzone inside the section component it should be not only created it also should be bound.

## Screenshots
https://craftercms.slack.com/archives/C0ME7US74/p1587699413244900

## Logs
n/a

### Version
Studio Version Number: 3.1.5-fb3509
Build Number: fb35092a40f7b3d5edf1f2ef61e437b61cc2e5e6
Build Date/Time: 02-22-2020 02:17:38 +0300

### OS
Debian Buster (10)

### Browser
Firefox, chromium

## Additional context
n/a

**Comment by malnajdi** [comment]
By the way. A Video was created a while ago which seems it worked. https://youtu.be/nHOpZsLWppo?t=277 but not anymore so i would like to confirm if this is really a bug or am i missing something.

**Comment by malnajdi** [comment]
This was related to embedded-content data-source is not currently supported for DND. The messages or alerts at the dnd-controller.js are not working. I did not get notify that i can't dnd because of the embedded-content data-source.

**Comment by rart** [comment]
@malnajdi would you be able to upload your site to a public GitHub repo and share the remote URL? That would be the best way of helping you.
If you have any customer info, logos or sensitive config values, you may create a clone without all of that, just leaving the content type definitions, preview components config, freemarker templates, and any other details to reproduce the situation straight out of the clone that you provide.
Thanks.

**Comment by malnajdi** [comment]
@rart https://github.com/malnajdi/blog

**Comment by malnajdi** [comment]
@rart @sumerjabri 
There is no need to check why an item won't get bind the issue is i am using an embedded-content data-source which seems not supported currently. 

So this issue can be closed or changed to [studio-ui] Alert users when trying to DND to embedded-content data-source

**Comment by jvega190** [comment]
Hi @malnajdi! Effectively the case you're mentioning is not supported yet. There's a detail in your setup causing the alert not to show. In **Layout - Section** template, you have
`<@studio.componentAttr path=contentModel.storeUrl ice=true />`, but the correct parameter is component, like this:
`<@studio.componentAttr component=contentModel ice=true />`
That way the component will be validated properly, and the alert with show up. 

You can check the configuration in here:
https://docs.craftercms.org/en/3.1/developers/in-context-editing-ftl.html#in-context-editing-ftl

**Comment by malnajdi** [comment]
@jvega190 Thanks a lot for finding out the issue. tested and confirmed. 

One issue tho. I did not take that code from the docs i took it from the Freemarker Example list provided in the CrafterCMS Authoring Template Edit (Template Code Example: Component Attribute)
so maybe it needs to be updated ? 
`<@studio.componentAttr path=contentModel.storeUrl ice=false />`

**Comment by jvega190** [comment]
@malnajdi You're right, it needs to be updated, thanks for the info, a ticket will be created to update the example. Is that ok if I close this ticket?
