### ISSUE TITLE
Publishing content does not generate expected events

### ISSUE THREAD

**Issue by uber-rivet** [craftercms/craftercms#399]
Expected events are not triggered (onDeploymentEvent) for a registered DeploymentEventListener 

publishing an already published item generates a STATE_NEW event instead of STATE_UPDATED 
publishing after a Cut/Paste: generates a STATE_NEW event for the target destination
publishing after a Rename (by changing file-name property): generates a STATE_NEW event for the target destination

**Comment by hlim** [comment]
On rename and cut/paste it should generate MOVE event with an extra property: oldPath.

**Comment by uber-rivet** [comment]
I submitted a fix (already merged) for the oldPath property.  For the other part of the ticket, it seems it's an issue with my local environment.
