### ISSUE TITLE
[studio-ui] using `header` as variable breaks the Item Manager picker

### ISSUE THREAD

**Issue by malnajdi** [craftercms/craftercms#3990]
## Describe the bug
When i add a new data-source with a variable name `header` the Item Manager property in the node-selector field breaks. 

## To Reproduce
1. open any content type model.
2. add a new data-source of type **shared-content**
3. Make sure to name the variable name **header**
4. add a node-selector field and check the **Item Manager** property

## Expected behavior
It should appear as normal

## Screenshots
[Video Link](https://craftercms.slack.com/files/UG99KMU6R/F012QJYT8KE/craftercms_ui_bug-2020-04-26_01.20.37.mp4)

## Logs
n/a

### Version
3.1.5

### OS
Debian buster ( 10 )

### Browser
firefox, chrome

## Additional context
n/a

**Comment by rart** [comment]
@jvega190 looks like the control ID is used as the element id. There are probably styles associated with header (`#header`) that make it break as shown on the report. Change the ID generation to something compound (e.g. `datasource_{id}`) or even something pseudo random. Make sure characters that would challenge attributes in the way they're getting used are not used as part of the attribute.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/3928341/80299493-06ab7c00-8795-11ea-93ea-55fdcb86783e.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/3928341/80299490-00b59b00-8795-11ea-93af-17cdd9d787b0.png">

**Comment by jvega190** [comment]
@yacdaniel can you please verify? Please let me know if you need something from me

**Comment by yacdaniel** [comment]
sure @jvega190 I'll take a look.

**Comment by yacdaniel** [comment]
Verified fixed.
