### ISSUE TITLE
[studio-ui] NumPad keys not working

### ISSUE THREAD

**Issue by malnajdi** [craftercms/craftercms#3991]
## Describe the bug
when the Numpad keys are used they are not wokring

## To Reproduce
1. open any content type model
2. add node-selector field
3. try to type any number in **Min Size** property using Numpad keys

## Expected behavior
numpad keys should works just like other keys

## Screenshots
[Video Link](https://craftercms.slack.com/files/UG99KMU6R/F012X38N4AD/craftercms_numpad_not_working-2020-04-26_01.53.01.mp4)

## Logs
n/a

### Version
3.1.5

### OS
Debian buster ( 10 )

### Browser
firefox, chrome

## Additional context
n/a

**Comment by rart** [comment]
@jvega190 please change the input events to check the input char instead of the keys pressed.

**Comment by yacdaniel** [comment]
@jvega190 please check the following controls where numpad is not working: 
`Maximum` and `Minimum` values in `numeric-input` 
`Width min-max` and `Height min-man` in `image-picker`

**Comment by jvega190** [comment]
@yacdaniel done, please let me know if you need anything else

**Comment by yacdaniel** [comment]
Verified fixed.
@malnajdi this will go into the next Crafter CMS release `3.1.7`

**Comment by malnajdi** [comment]
@yacdaniel and the team, Thanks a lot.
