### ISSUE TITLE
[docs] Improve Engine SAML 2 documentation

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3993]
https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-saml2-configuration.html needs some improvements:

- Provide steps to generate SP data and metadata:

  1. Generate keys: `keytool -genkey -alias CREDENTIAL_NAME -keystore keystore.jks -storepass STORE_PASSWORD`
  2. Export X509 certificate: `keytool -export -alias CREDENTIAL_NAME -keystore keystore.jks -rfc -file CREDENTIAL_NAME.cer`.
  3. Go to https://www.samltool.com/sp_metadata.php and fill: `EntityId`, `Attribute Consume Service Endpoint (HTTP-POST)` with `DELIVERY_DOMAIN/saml/SSO` , `Single Logout Service Endpoint (HTTP-REDIRECT)` with `DELIVERY_DOMAIN/saml/logout`, `SP X.509 cert (same cert for sign/encrypt)` with the exported X509. Or if we don't want to use `https://www.samltool.com`, please explain how to generate the SP metadata file.

- Explain that `keystore.password` and the password in `keystore.credentials.credential` are almost always the same value (`keytool` doesn't let you have a credential password that's different from the store password).
- If possible provide an example with the `authToken` that prints the incoming attributes from SAML.

**Comment by jdrossl** [comment]
I just did a test and it is possible to use different passwords using `keytool`:

```
Enter key password for <CREDENTIAL_NAME>
	(RETURN if same as keystore password):
```

**Comment by avasquez614** [comment]
@jdrossl when I run the `keytool` I get this:

```
➜  ~ keytool -genkey -alias mykey -keystore keystore.jks -storepass mypass   
What is your first and last name?
  [Unknown]:  Alfonso
What is the name of your organizational unit?
  [Unknown]:  Vasquez
What is the name of your organization?
  [Unknown]:  Crafter Software
What is the name of your City or Locality?
  [Unknown]:  Reston
What is the name of your State or Province?
  [Unknown]:  VA
What is the two-letter country code for this unit?
  [Unknown]:  US
Is CN=Alfonso, OU=Vasquez, O=Crafter Software, L=Reston, ST=VA, C=US correct?
  [no]:  y
```

As you see, it doesn't ask for the key password. And the if I specify the `keypass` in the command line I get:

```
➜  ~ keytool -genkey -alias mykey -keystore keystore.jks -storepass mypass -keypass myotherpass            
Warning:  Different store and key passwords not supported for PKCS12 KeyStores. Ignoring user-specified -keypass value.
What is your first and last name?
  [Unknown]:
```

I don't know if it's some difference with the version of Java that we're using, but we should mention then that you don't specify a `keypass` in some occasions and that it should be the the same as the `storepass` if not specified.

**Comment by avasquez614** [comment]
Verified
