### ISSUE TITLE
[studio-ui] Cleanup legacy UI and Update to Next UI

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3994]
# Intro

As the Next UI absorbs more and more of legacy, we should start code clean up. We will use this ticket as a live tracker for the cleanup.

## Migration complete

_Listed items are things that Next UI has taken over. Checked ones mean legacy counterpart code has been removed._

### To be deleted from the legacy by UI Devs
- [x] Create site dialog
- [x] Bulk upload dialog
- [x] Single file upload
- [x] History dialog
- [x] Dependencies dialog
- [x] Schedule/Request dialog
- [x] Approve/publish dialog
- [ ] New content dialog
- [x] Delete dialog
- [x] Quick create
- [x] Login dialog
  - [x] User dashboard login-related code
  - [x] Common-api/internal page login-related code
- [x] GraphiQL
- [x] Search
- [x] Publishing queue
- [x] Workflow cancellation dialog
- [x] Reject dialog
- [x] Copy
- [x] Create/Rename folder dialog
- [x] Layered root folder
- [x] wcm-taxonomy-folder

### To be migrated to Next UI -- Don't delete for backward compatibility

- [x] Sidebar widgets
  - [x] wcm_root_folder
  - [x] wcm_assets_folder
  - [x] Layered root folder -> deprecated
- [x] Preview
  - [x] Preview tools (TODO: Break down to individual checkboxes)
    - [x] Host
  - [x] Guest
    - [x] Associated libs (Most of `/static-assets/scripts` folder: dnd-controller, communicator, etc.)

**Comment by jvega190** [comment]
@rart in New content dialog, this is the same dialog being used in Site Config -> Content Types, can't be removed yet

**Comment by jvega190** [comment]
@rart also, I see nothing left from publishing-queue, will check it as done

**Comment by rart** [comment]
Some cleanup done via JWT works https://github.com/rart/studio-ui/pull/1

**Comment by rart** [comment]
This has now served it's purpose. Migration of these is basically complete with exception of new content which is still in use in site config and will be attended when addressing that module.
