### ISSUE TITLE
[social] Social comments not loading

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#3996]
## Describe the bug
Comments not loaded because an error happening in Social backend

## To Reproduce
1. Go to any page where comments are enabled
2. Open your browser console
5. Also open server logs
6. There is an error attached below

## Expected behavior
`childrenCount` should be optional in the backend and provide a default value, now is enforcing the social UI to send it but is not sending anything, looks js was not updated to consider this scenario, either way looks like a bug.

## Logs
https://gist.github.com/asotog/94ae580f1d1c5d3f4f3e958eb87ac7ba

### Version
3.1.5E

### OS
Any

### Browser
Any

**Comment by sumerjabri** [comment]
@asotog is your target deployment 3.1.x?

**Comment by sumerjabri** [comment]
@rart please see if it's a SUI issue or deeper. If backend, assign back to me. Thanks.

**Comment by asotog** [comment]
> @asotog is your target deployment 3.1.x?

@sumerjabri yes 3.1.5E

**Comment by rart** [comment]
@sumerjabri this is backend

**Comment by jdrossl** [comment]
@yacdaniel please help validate

**Comment by yacdaniel** [comment]
Verified fixed, `childrenCount` is now an optional param. 

@asotog the fix will be available in the next Crafter CMS release `3.1.7`
