### ISSUE TITLE
[docs] Update screenshots based on the new UI

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3999]
### Documentation Updates
Update the documentation screenshots as the dialogs become available, for:
- [ ] Create site dialog
- [x] Bulk upload dialog
- [ ] Single file upload
- [x] History dialog
- [ ] Dependencies dialog
- [x] Schedule/Request dialog
- [x] Approve/publish dialog
- [x] New content dialog
- [ ] Delete dialog
- [x] Quick create
- [ ] Login dialog
  - [ ] User dashboard login-related code
  - [ ] Common-api/internal page login-related code
- [ ] GraphiQL
- [ ] Search
- [ ] Publishing queue

**Comment by sumerjabri** [comment]
Mostly done and ongoing.
