### ISSUE TITLE
[studio] History Item - versionNumber has a wrong value

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#400]
When getting history versions from an item,
'/studio/api/1/services/api/1/content/get-item-versions.json'

the versions array of the response has a "versionNumber" value, that is used to show on the history dialog, and seems to have a wrong value, for example "743aa064459910f9015db239bf54b1eaf36ba268"

**Comment by sumerjabri** [comment]
No longer needed.
