### ISSUE TITLE
[deployer] Test email processor is send notifications on indexing issues

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4000]
Test if the `MailNotificationProcessor` is sending notifications when the Deployer fails to index files for any reason. The configuration for the `MailNotificationProcessor` can be found here: https://docs.craftercms.org/en/3.1/system-administrators/deployer/processors-guide.html#mail-notification-processor. The possible notification status are these:

```
        /**
         * Notifications will be sent for all deployments.
         */
        ON_ANY_STATUS,

        /**
         * Notifications will be sent for deployments in which at least one processor has failed.
         */
        ON_ANY_FAILURE,

        /**
         * Notifications will be sent for deployments in which the general status indicates failure.
         */
        ON_TOTAL_FAILURE
```

**Comment by yacdaniel** [comment]
@avasquez614 deployer is not sending email notifications when it fails but it does send notification in case of success. 
Here are the steps I did
0. Have a smtp server configured, I use mailcatcher  `docker run -d -p 1080:1080 -p 25:1025 --name mailcatcher schickling/mailcatcher` then emails arrive at `localthost:1080` There is no crafter config needed, as mailcatcher listen to the default's crafter smtp port: 25.
1. Create a site in authoring and init-site in delivery
2. Add to delivery deployer target the email notification, in `/crafter-delivery/data/deployer/targets/` edit the `siteName-default.yaml` add at the end:
```
      - processorName: mailNotificationProcessor
        to:
        - admin@example.com
        - author@example.com
        status: ON_ANY_STATUS
```
3. Shut down elasticsearch in delivery, so we can have a failure in the deployer pipeline
`./crafter-delivery/bin/crafter.sh stop_elasticsearch`
4. Edit and publish content in authoring, wait for delivery to pick up the changes. 
5. Check the `deployer` logs in delivery. There is an error and no emails are sent.
Deployer log https://gist.github.com/yacdaniel/8a12bd93eefef7834fdfbea002828b7a

**Comment by avasquez614** [comment]
@jdrossl seems like we're not correctly catching errors when ES is down, I checked the log Yac provided and I don't see the deployment continue with the `fileOutputProcessor` and the `mailNotificationProcessor`.

**Comment by yacdaniel** [comment]
Verified fixed.
