### ISSUE TITLE
[studio] Email notification template format issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4013]
## Describe the bug
Emails notification templates have some format issues. 

## To Reproduce
1. Have a smtp server configured for authoring. Also setup at least author and publisher users. 
2. Do some Request Publish, Reject, Schedule and Content Approved actions to trigger the email notifications. 
3. Check the emails.

## Expected behavior
* Content Review Email - issues: 
  * Items to review are listed twice.
![image](https://user-images.githubusercontent.com/6722074/80721879-fd375200-8abb-11ea-9861-892169269586.png)
  *  `Click Here to View Content Waiting for Approval` goes to http://localhost:8080/site-dashboard which does not exist, it should link to Studio url http://localhost:8080/studio/site-dashboard 
  * There is a img  link about a workflow email footer, which doesn't exist, fix link or remove the section from template? 

     ```
                            <a href="http://localhost:8080/site-dashboard">Click Here to View Content Waiting for Approval</a>
                            <br/><br/>
        <a href="http://localhost:9080/?crafterSite={siteName}" >
            <img style="max-width: 350px;  max-height: 350px;" src="http://localhost:9080/?crafterSite={siteName}/static-assets/images/workflow-email-footer.png" alt="" />
        </a>
    ```
 * Content Requires Revision Emails - issue:
   * Img  link about a workflow email footer, which doesn't exist, fix link or remove the section from template?
    ```
                                <a href="http://localhost:8080/studio/site-dashboard" >
                                    <img style="max-width: 350px;  max-height: 350px;" src="http://localhost:9080/?crafterSite={siteName}/static-assets/images/workflow-email-footer.png" alt="" />
                                </a>
    ```
 * Content Approved Email - issues:
   * Content goes to a invalid delivery url, check the missing value of `siteName` and also the double `//`
   ![image](https://user-images.githubusercontent.com/6722074/80723005-48059980-8abd-11ea-81d4-60520412e924.png)
   `<a href="http://localhost:9080/?crafterSite={siteName}//search-results"> <li>Search Results </a> `
   * Img  link about a workflow email footer, which doesn't exist, fix link or remove the section from template?
     ```
                                <a href="http://localhost:8080/studio/site-dashboard" >
                                    <img style="max-width: 350px;  max-height: 350px;" src="http://localhost:9080/?crafterSite={siteName}/static-assets/images/workflow-email-footer.png" alt="" />
                                </a>
    ```
 * Content Scheduled Email - issues:
   * TimeZone values is harcoed in template, it should come from the defined TZ in config?
![image](https://user-images.githubusercontent.com/6722074/80723967-80f23e00-8abe-11ea-878d-ddfbcc298d97.png)
   *  Content goes to a invalid delivery url, check the missing value of `siteName` and also the double `//`
   * Invalid URL in `Click Here To View Your Published Content, missing siteName value`
   * Img  link about a workflow email footer, which doesn't exist, fix link or remove the section from template?
     ```
                                <a href="http://localhost:8080/studio/site-dashboard" >
                                    <img style="max-width: 350px;  max-height: 350px;" src="http://localhost:9080/?crafterSite={siteName}/static-assets/images/workflow-email-footer.png" alt="" />
                                </a>
    ```

### Version
`3.1.7-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jdrossl** [comment]
@russdanner @sumerjabri I have a couple of questions:

1. as Yac mentioned all templates have a footer with a missing image (`/static-assets/images/workflow-email-footer.png`) should we remove the whole footer or replace the image with some text?

2. Should we update only the blueprints but not existing sites? I think this file is not safe for the UM to change (because there is no way to know if someone has already changed the templates)

**Comment by sumerjabri** [comment]
1) Remove the footer
2) Only change our blueprints and RL's/marketplace blueprints

**Comment by yacdaniel** [comment]
@sumerjabri notification config have been updated in all of the Studio blueprints. 
Ours and RL marketplace blueprints don't have the updated configuration yet.

**Comment by sumerjabri** [comment]
Completed.

**Comment by yacdaniel** [comment]
Verified.
