### ISSUE TITLE
[docs] Add NPM modules to the list of APIs for Crafter Engine

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4014]
Please update the Crafter Engine API docs to include:
- https://www.npmjs.com/package/@craftercms/content
- https://www.npmjs.com/package/@craftercms/classes
- https://www.npmjs.com/package/@craftercms/models
- https://www.npmjs.com/package/@craftercms/redux
- https://www.npmjs.com/package/@craftercms/search
- https://www.npmjs.com/package/@craftercms/utils
- https://www.npmjs.com/package/@craftercms/ice

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/974

**Comment by sumerjabri** [comment]
Verified.
