### ISSUE TITLE
[studio] Make the Upgrade Manager commits be more distinguished

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4017]
**Is your feature request related to a problem? Please describe.**
When looking at the commit history for a site, would be nice that it is very clear/evident which commits where done by the upgrade manager — the system, for that matter.

**Describe the solution you'd like**
Prefix messages with `[Upgrade Manager]` or `[System]` or alike.

**Comment by sumerjabri** [comment]
Completed
