### ISSUE TITLE
[studio-ui] -Site Translation- Add locale as an intrinsic item metadata in the content modeling tool

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4020]
All content items must carry a locale as an intrinsic metadata field, like name or object id.

### Tasks
- [ ] Form Builder: Add locale to the base set of metadata for every page or component and ability to refuse/disable localization
- [x] Form Engine: Add a locale data-source backed by the locales, see https://github.com/craftercms/craftercms/issues/4019 for the API to get those for a site. If the site doesn't have locales, hide this field and don't write it to the XML. A locale is not a required field.

### Dependencies
https://github.com/craftercms/craftercms/issues/4019

**Comment by jvega190** [comment]
@jdrossl I'll assign this to you for UM work as soon as the PR is ready

**Comment by jdrossl** [comment]
@jvega190 the URL for the API has changed, check it out here https://github.com/craftercms/studio/pull/2038

**Comment by jdrossl** [comment]
@jvega190 the API is merged, please update the control to use it

**Comment by jdrossl** [comment]
@jvega190 the locale selector needs to support locale codes without country too, eg. `es`, `en`

**Comment by jvega190** [comment]
@jdrossl done, can you please verify?

**Comment by jdrossl** [comment]
@jvega190 this part seems to be missing `If the site doesn't have locales, hide this field and don't write it to the XML`

**Comment by jvega190** [comment]
@jdrossl now field won't render if the site have no locales, avoid writting to the XML can not be done due to current form-engine limitations.

**Comment by jdrossl** [comment]
Verified
