### ISSUE TITLE
[studio-ui] Search filters are cleared on keyword edit

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4024]
## Describe the bug
In Studio's authoring search, when the user sets up filters and then enters a keyword the filters are cleared.

## To Reproduce
1. Go to search in Crafter Studio
2. Filter the content by content type
3. Enter a keyword

## Expected behavior
Changing the keyword should not impact the filters that have been set.
Paginating through the results should not change the filters either

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 04-23-2020 17:14:24 -0400

### OS
Any

### Browser
All

**Comment by sumerjabri** [comment]
Fix for `develop`

**Comment by jvega190** [comment]
@sumerjabri the search issue is already fixed in here https://github.com/craftercms/craftercms/issues/4121

**Comment by sumerjabri** [comment]
Verified fixed.
