### ISSUE TITLE
[studio-ui] Shared content data source does not pass default type or path to search when selecting via search

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4025]
## Describe the bug
Shared content data source does not pass default type or path to search when selecting via search

## To Reproduce
1. Set up a shared content node selector to allow search. Limit the path and type
2. Open the form and using the associated node selector, pick an item via search
3. Note that the entire repo is searched and no filters are applied

## Expected behavior
Search should automatically be limited by the content type and the path

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 04-23-2020 17:14:24 -0400

### OS
Any

### Browser
All

**Comment by russdanner** [comment]
Jose, Please check this for all datasources, video, image etc. Images data source do not pass path.

**Comment by jvega190** [comment]
@russdanner there's a pending backend change needed to implement search with path
https://github.com/craftercms/craftercms/issues/4047. Will be implemented when this change is done

**Comment by sumerjabri** [comment]
@jvega190 #4047 is now back on 3.1.8 timeline.

**Comment by russdanner** [comment]
@jvega190 Is the backend in place now?

**Comment by russdanner** [comment]
<img width="1283" alt="Screen Shot 2020-06-22 at 5 13 40 PM" src="https://user-images.githubusercontent.com/169432/85336089-1224d600-b4ac-11ea-9306-14213798ace1.png">

The UI states there are two filters applied but only shows 1.  

Please include the path filter in the dropdown.

**Comment by jvega190** [comment]
@russdanner assigning it to you to test in 3.1.x, please assign it back to me when it's ready for 3.2.x work

**Comment by russdanner** [comment]
confirmed.
Assigning back

**Comment by jvega190** [comment]
@rart assigning it to you for design work

**Comment by aachavarria** [comment]
@yacdaniel Please validate on 3.2

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0`
