### ISSUE TITLE
[docs] Document the case sensitivity of keyword search and choices/options in Crafter Engine and Crafter Studio

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4026]
## Describe the bug
In Crafter Studio, keyword search is case sensitive.
This might also be the case for Engine-based searches for sites/apps.

## To Reproduce
1. Create a site based on editorial
2. Go to search and search for "Editorial" and "editorial" 
4. See the result count is different. 

## Expected behavior
Search shouldn't be case-sensitive in Studio.
This should also be the case for Engine, and perhaps configurable per site (since some sites may require case-sensitivity).

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 04-23-2020 17:14:24 -0400

### OS
Any

### Browser
All

**Comment by jdrossl** [comment]
@russdanner @sumerjabri I don't think this is an issue.

In both Solr & ES it is not possible to decide how to perform a search, it will always depends on the indexed fields. Fields of type `text` are case insensitive, but `strings` are always case sensitive. Any search that runs on multiple fields (like the one in studio) will be affected by this.

To achieve a full case insensitive search we would need to index all fields as both `text` & `string` but that is controlled by authors in the content-types

**Comment by avasquez614** [comment]
Just to add to what JR is saying, case insensitive search can be provided for a particular `string` field by enabling tokenization of the field in the content type.

**Comment by sumerjabri** [comment]
The idea is to document what we have. See JR's notes and ping any of us for any additional information.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1062  and https://github.com/craftercms/docs/pull/1063

**Comment by russdanner** [comment]
Confirmed
