### ISSUE TITLE
[studio] Removing a Git remote via Studio UI leaves the branch references in place

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4028]
## Describe the bug
When you add and later remove a Git remote via the Studio remote console it leaves the remote branch references around

## To Reproduce
1. Add a Git remote to a site
2. Remove it
3. Go to sand box and list branches. You will see the remote references

## Expected behavior
Remote branch references should be removed/cleaned up when a remote is removed.

To manually fix this, you must execute the following command to clean up the remote reference
`git branch -d -r myremote/coolbranch`

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-912bc5
Build Number: 912bc5e2c5c097421056e0dc2a8cced44af91548
Build Date/Time: 03-16-2020 15:37:39 -0400

### OS
Any

### Browser
N/A

**Comment by jdrossl** [comment]
@russdanner seems like this is already fixed, I was not able to reproduce it

**Comment by russdanner** [comment]
Confirmed
