### ISSUE TITLE
[studio] Git Remotes console push/pull dialog fails when 2 remotes contain the same branch names

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4029]
## Describe the bug
Git Remote Branches API to get branches contains all branch references. As a result, Console UI push/pull dialog fails when 2 remotes contain the same branch names

## To Reproduce
1. Add a remote called origin with branch called feature/x
2. Add a remote called qa with a branch called feature/a
3. In sandbox perform a `git branch -a`
4. Note these that the references for origin and qa remotes will be shown
5. Attempt to do a pull (or a push) and see that dialog throws error concerning duplicates

## Expected behavior
Remotes servers should only return the branches for a given remote (which eliminates the dupes error) seen in the UI

## Screenshots
Branches dropdowns are empty. Exception in browser console.

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-912bc5
Build Number: 912bc5e2c5c097421056e0dc2a8cced44af91548
Build Date/Time: 03-16-2020 15:37:39 -0400

### OS
Any

### Browser
All

**Comment by jdrossl** [comment]
@russdanner seems like this is already fixed, I was not able to reproduce it

**Comment by russdanner** [comment]
confirmed
