### ISSUE TITLE
[studio] Get Remotes API does not list any remotes when one remote is unreachable

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4030]
## Describe the bug
 Get Remotes API does not list any remotes when one remote is unreachable. The remote should always be listed not matter what.  Administrators need to be able to remove and/or work with other remotes.

## To Reproduce
1. Add 2 remotes to a project one 
2. Render one of the remotes unreachable (move the directory if local or deactivate the security token if remote)
3. Note that the service does not return either remotes and the UI is empty.

## Expected behavior
All remotes should be returned regardless of reachability so that an administrator can remove and re-add them to re-authorize them if needed.

Consider sending a reachable state value back with the remote so that the UI can disable push and pull.
 
## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-912bc5
Build Number: 912bc5e2c5c097421056e0dc2a8cced44af91548
Build Date/Time: 03-16-2020 15:37:39 -0400

### OS
Any

### Browser
All

## Additional context
The number one reason we see this issue has to do with expiring security credentials. Once this error occurs the only fix is to remove the remote manually from the Git repo and the database which is not always possible due to security constraints.

**Comment by sumerjabri** [comment]
We should list broken remotes and indicate in the UI that they're unreachable. If we can provide a reason why that's all the better.

**Comment by dejan-brkic** [comment]
Tasks:
[ ] Fix list remotes issue
[ ] Update API Doc
[ ] Add new properties to the response in BE
[ ] UI updates

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2014
https://github.com/craftercms/studio/pull/2013

**Comment by sumerjabri** [comment]
Verified fixed.
![repo-unreachable](https://user-images.githubusercontent.com/3931908/83301817-46b4b300-a1c8-11ea-8ad8-a32b7dc6de1a.png)
