### ISSUE TITLE
[deployer] Create a GitDiffOnly Processor and a GitCompleteProcessor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4031]
**Is your feature request related to a problem? Please describe.**
Today the GitDiffProcessor reads and immediately updates the processed commits.  This is ok in many cases but in some cases you only want to update the processed commits when the processing pipeline has reached a given point.

**Describe the solution you'd like**
Add a processor "GitDiffOnly" that just creates a diff for future processors but does not modify the processed commit value

Add a second processor "GitComplete" that only updates the processed commits value with the current commit

**Describe alternatives you've considered**
None

**Comment by sumerjabri** [comment]
Consider having a commit_id per processor. If a processor fails, it picks up where it left off.

We must discuss this further and design it properly.

**Comment by yacdaniel** [comment]
@jdrossl could you please call `.name()` to the `ObjectId` to have a better log entry in `GitUpdateCommitIdProcessor.java` 
```
ObjectId commitId = (ObjectId) deployment.getParam(LATEST_COMMIT_ID_PARAM_NAME);
logger.info("Updating processed commit to {}", commitId);
```
Right now is logged as:
```
2020-06-18 15:33:11.878  INFO 24174 --- [deployment-4] rocessors.git.GitUpdateCommitIdProcessor : Updating processed commit to AnyObjectId[32c2ae44c8033161660df5982fa6af12df9ae835]
```

**Comment by russdanner** [comment]
Confirmed
