### ISSUE TITLE
[deployer] Support creating and wiring processors via Groovy and deployed via Studio

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4032]
**Is your feature request related to a problem? Please describe.**
Creating deployment processors requires java and heavy deployment. Configuring deployment requires updates to Yaml that must be made externally and deployed to the server. 

**Describe the solution you'd like**
Make it possible to write processors via scripting and configure and deploy them via Crafter Studio/publishing mechanics.

**Describe alternatives you've considered**
None

**Comment by sumerjabri** [comment]
Replaced by https://github.com/craftercms/craftercms/issues/6210
