### ISSUE TITLE
[docs] Clarify the configuration file referenced in the docs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4036]
In articles such as:
https://docs.craftercms.org/en/3.1/developers/projects/engine/api/templating-api.html#id11
and
https://docs.craftercms.org/en/3.1/developers/projects/engine/api/access-to-services.html

The configuration files being modified are unclear. Please add Sphinx-Doc snippets (shared) explaining the main configuration files, and where/how to edit them. Then link those to these and similar articles so all articles point to the configuration file being editing in a clear and clean way.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/995
