### ISSUE TITLE
[docs] Add example configuration to kubernetes documentation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4041]
**Is your feature request related to a problem? Please describe.**
Users request example / additional example configurations for kubernetes configurations

**Describe the solution you'd like**
Add configuration examples or links to examples to documentation

**Comment by sumerjabri** [comment]
This is a great thing to reference: https://github.com/craftercms/kubernetes-deployments

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1067 and https://github.com/craftercms/docs/pull/1068

**Comment by russdanner** [comment]
Confirmed
