### ISSUE TITLE
[studio] Administrator cannot re-create a user that was previously deleted

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4043]
## Related to
https://github.com/craftercms/craftercms/issues/4044

## Describe the bug
Administrator cannot re-create a user that was previously deleted

## To Reproduce
1. Create a user
2. Delete the user
3. Attempt to re-create the user

## Expected behavior
Administrator should be allowed to re-create or re-enable a previously deleted user.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-912bc5
Build Number: 912bc5e2c5c097421056e0dc2a8cced44af91548
Build Date/Time: 03-16-2020 15:37:39 -0400

### OS
All

### Browser
Any

**Comment by sumerjabri** [comment]
@russdanner Users cannot be deleted permanently nor re-created because of audits and actions taken within the system.

Re-enabling a user is possible and will require UI updates to show users that are deleted and allow re-enablement. The effort here is now bigger, would this still be a 3.1.8?
