### ISSUE TITLE
[engine] Make the profile for preview targeting, delivery and delivery + SSO more seamless

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4045]
**Is your feature request related to a problem? Please describe.**
Today use of the `profile` object is highly dependent on the context that you are in (preview, delivery + Crafter Profile, delivery + SSO integration, etc) which makes it difficult to write controllers, templates, and other backend code for sites. Developers have to create their own concepts and helpers to hide these details and homogenize their site code. Example:

* Preview targeting populates a profile object but only after the user opens the dialog and accepts in Studio otherwise the "profile" object is null.
* Crafter Profile populates the profile object when integrated into delivery otherwise the `profile` is null.
* SSO creates an "authToken" object but no user by default.

You can see from the above that as a person coding a template I'm in trouble. I just want to write <#if profile.attributes.someValue == "myValue">...</#if> and know that it will work in preview and delivery and behind SSO.

**Describe the solution you'd like**
Make it more seamless to work with the profile in preview, delivery, and delivery + SSO

**Describe alternatives you've considered**
None

**Comment by sumerjabri** [comment]
Closing as this will be addressed by enhancements to Engine.
