### ISSUE TITLE
[studio] Git remote APIs return 200 status code on internal error

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4049]
## Describe the bug
Most Git remote APIs return 200 status code on internal error 

https://github.com/craftercms/studio/blob/70ad9b0b002a074b36cf9bf95cf7bd7c8ccf0bc0/src/main/java/org/craftercms/studio/controller/rest/v2/RepositoryManagementController.java

## Expected behavior
A 500 status code + API error codes (per docs) should be returned when an error occurs so that UI can inform the user.

Example:
```
        boolean res = repositoryManagementService.removeRemote(removeRemoteRequest.getSiteId(),
                removeRemoteRequest.getRemoteName());

        ResponseBody responseBody = new ResponseBody();
        Result result = new Result();
        if (res) {
            result.setResponse(OK);
        } else {
            result.setResponse(INTERNAL_SYSTEM_FAILURE);
        }
        responseBody.setResult(result);
        return responseBody;
```
## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.6-SNAPSHOT-912bc5
Build Number: 912bc5e2c5c097421056e0dc2a8cced44af91548

### OS
N/A

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2024
https://github.com/craftercms/studio/pull/2025

**Comment by russdanner** [comment]
Reviewing the code it seems that the error will now be reported to the UI but no detailed logs are produced for the failure condition and a simple true false is passed up to the caller. The details of the error are lost.

`studio/src/main/java/org/craftercms/studio/impl/v2/service/repository/internal/RepositoryManagementServiceInternalImpl.java`

```
 boolean toRet = true;
            List<RemoteRefUpdate.Status> failure = Arrays.asList(REJECTED_NODELETE, REJECTED_NONFASTFORWARD,
                    REJECTED_REMOTE_CHANGED, REJECTED_OTHER_REASON);
            for (PushResult pushResult : pushResultIterable) {
                Collection<RemoteRefUpdate> updates = pushResult.getRemoteUpdates();
                for (RemoteRefUpdate remoteRefUpdate : updates) {
                    toRet = toRet && !failure.contains(remoteRefUpdate.getStatus());
                    if (!toRet) break;
                }
                if (!toRet) break;
            }
            return toRet;
```

This makes it very difficult to address the issue.  
_All_ error in the response should be clearly enumerated and reported explicitly in the code (see current code currently groups all errors together and checks for issue with contains) and with as much detail as possible in the logs.

**Comment by dejan-brkic** [comment]
Improved logs.
Error reporting as desired not possible. Loop checks the status of each pushed commit. The original issue was reported because the execution of the operation is actually successful. The only way to look for failures is to check status on each commit if it was pushed or not.

PR:
https://github.com/craftercms/studio/pull/2042
https://github.com/craftercms/studio/pull/2043

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftersoftware/studio/pull/66
https://github.com/craftersoftware/studio/pull/65

**Comment by avasquez614** [comment]
After a discussion with @dejan-brkic and @sumerjabri, we decided to try to see if it's possible to extract the pre-hook rejection messages from JGit. @dejan-brkic these are the steps to reproduce it:

1. Create a private Github repo.
2. Create a site based on `empty` and push to the Github repo.
3. Add a file bigger than 100 MB to the site from Studio (e.g. the `ROOT.war`).
4. Push the site to Github from Studio, then push the site to Github from the command line.

In both cases the push will fail, but the message is more detailed in the CLI.

Studio message:

```
[ERROR] 2020-06-24T14:08:38,438 [http-nio-8080-exec-3] [internal.RepositoryManagementServiceInternalImpl] | Remote ref refs/heads/master update was rejected for other reason.
pre-receive hook declined 
```

CLI message:

```
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 43a00a3a2c0a95f308ea10fcb232b6c2
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File static-assets/blobs/ROOT.war is 150.03 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:avasquez614/craftercms-push-error-tests.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:avasquez614/craftercms-push-error-tests.git'
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2050

**Comment by avasquez614** [comment]
Verified by trying to push a large file to Git. Reassigning it to @russdanner to see if he needs to test something else

**Comment by russdanner** [comment]
Confirmed
