### ISSUE TITLE
[studio-ui][PageBuilder][Forms] Content Type Field Validations

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4052]
We must

- Define the set of validations that would be applied to content type fields.
- Define validations that apply to each type of field.
- Map existing content type editor validations (set of items required for PageBuilder 1.0.0-beta)

**Secured**

- allowedContentTypes
- allowedContentTypeTags
- maxLength
- readOnly?

**Draft**

- width – exact width to accept
- height – exact height to accept
- minWidth – min width to accept
- minHeight – min height to accept
- maxWidth
- maxHeight
- allowedMimeTypes - e.g. svg, png, etc for images or pdf, word, etc for a file selector
- count - exact number of items to accept
- minCount - min count of items to accept
- maxCount - max count of items to accept
- minValue - min value for a numeric input
- maxValue - max value for a numeric input
- minDate - min value for a date input
- maxDate - max value for a date input
- minTime - min value for a time input
- maxTime - max value for a time input
- minFileSize
- maxFileSize
- required
- minLength
- maxLength
- patternMatch - must match a given pattern
- patternMismatch - prohibit a given pattern
- allowedValues - allow only a known set of values
- allowSharedComponents
- allowEmbeddedComponents
- allowSorting

**Comment by sumerjabri** [comment]
We need to add translatable and translate?
