### ISSUE TITLE
[docs] Add the Engine sandbox configuration guides to other sections

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4053]
The documents
```
source/developers/projects/engine/api/access-to-services.rst
source/developers/projects/engine/api/script-sandbox-configuration.rst
```
explain the security model added to Crafter Engine to limit access to services and to sandbox the Groovy code. These documents need to be linked to from the Developer, System Admin, and Site Admin sections.

Perhaps create a snippet that points to the two documents and include that where needed.

The configuration is system-wide, and the concerns may show up at the site level during development.

Ping me if you need help.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/980
