### ISSUE TITLE
[engine] CORs is failing with SPAs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4055]
## Describe the bug
Engine Site Configuration `cors` section is broken.

## To Reproduce

1. Configure cors
2. Run a webpack web server or alike
3. Try to do a CORS request to graph/elastic/whathaveyou
4. Notice CORs headers aren't there
5. Try to do a proxied call (via web pack) proxy with the cors origin tag set to http://localhost:3000
6. Notice calls start to respond with 404

## Expected behavior
CORS works

## Additional context
Haven't tried yet but is likely that it is also happening in 3.1.x

**Comment by sumerjabri** [comment]
@rart are you using the new proxy or are you still trying to do the old stuff.

**Comment by rart** [comment]
The proxy is with it's OOTB config. I found the issue using the react (webpack) webserver outside of studio. This is just loading graph and doing elastic queries (i.e. trying to retrieve content). Nothing to do with ICE.
FYI: I saw the issue with J Ross so he's aware of the setup.

**Comment by jdrossl** [comment]
@rart the last part described in the issue is caused by react-scripts, if we update the config to use the manual setup all cases should work as expected https://github.com/facebook/create-react-app/issues/4302
