### ISSUE TITLE
[studio-ui] Remove or adjust QuickCreateMenu component for studio legacy

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4056]
**Is your feature request related to a problem? Please describe.**
Currently we have a separate component for studio legacy to render the QuickCreateMenu

**Describe the solution you'd like**
Verify if it's possible to remove or adjust the component to be the same as used in preview 2

**Comment by rart** [comment]
Done on https://github.com/craftercms/studio-ui/pull/1763
