### ISSUE TITLE
[studio] Monitoring API docs not accurate

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4058]
## Describe the bug
- The property wrapper for the response for each is wrong in all but version

## To Reproduce
- Notice the response from any but version have different property names than version

## Expected behavior
Docs to be accurate

## Additional context
https://app.swaggerhub.com/apis/craftercms/studio/#/monitoring

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2006/files
https://github.com/craftercms/studio/pull/2007/files
