### ISSUE TITLE
[studio-ui] Fix form engine close exception

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4059]
There's a new method on UI next content service called `unlock` content. On the form engine window, use this method and close the form on successful unlock instead of the sync XHR it does currently.

**Comment by russdanner** [comment]
@rart  @jvega190  I see a merge for 4.x and a comment requesting a fix for 3.1.x but no merge.

**Comment by jvega190** [comment]
@russdanner fixed in 3.1.x.

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for testing in 3.1.x

**Comment by sumerjabri** [comment]
@AndyReiter please validate.

**Comment by AndyReiter** [comment]
This has been confirmed fixed in 3.1.15-SNAPSHOT.
