### ISSUE TITLE
[studio][studio-ui]Problems writing audit table caused by (too) long filename

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#4060]
## Describe the bug
Our authors prefer to copy components instead of creating new one's because they often differ only slightly. Internally this results in a new xml-file which has the name of the old one followed by some additional random-like (a hash?) characters.
If you do this again and again the filename grows and when it's larger than 255 chars the system crashes while writing the name into the audit-table because the coloun length which should contain the filename is restricted to 255 chars.

This causes the deployer to stop ...

## To Reproduce
1. Create a component
2. Duplicate it again and again until lenght of filename exceeds 25 chars
3. Publishing does not work
4. See error.logs for dataase errors

## Expected behavior
A copy of a file should result always in a filename that respects the length restriction of a file-name.
Extending the column in the database seems to be not an option because it just delays the problem for some time.

## Screenshots
n.a.

## Logs
`[ERROR] 2020-05-08T14:32:28,001 [Studio_Publisher_Thread_Pool2] [job.PublisherTask] | Failed to sync database from repository for site thalia-crafter-site
org.springframework.dao.DataIntegrityViolationException:
Error updating database.  Cause: java.sql.SQLDataException: (conn:259) Data too long for column 'primary_target_id' at row 1
Query is: INSERT INTO audit (organization_id, site_id, operation, operation_timestamp, origin, primary_target_id,
        primary_target_type, primary_target_subtype, primary_target_value, actor_id, actor_details, cluster_node_id)
        VALUES (?, ?, ?, CURRENT_TIMESTAMP, ?, ?,
        ?, ?, ?, ?, ?,
        ?);, parameters [1,4,'CREATE','GIT',xxx:/site/components/2019/08/27/b63333f5-47e9-3569-e795-91e3e9f0c1cc-5d87c62e-9a7c5129-4ecb14f3-eb4f8a8e-1214f889-d48c1c35-150451ac-edf929da-c31d6188-35dff1c2-b89a4436-1da85d3b-
558ad987-97347519-794b87b3-650ed53b-3dcc4294-d594ef30-1fd228af.xml','Content Item','component','/site/components/2019/08/27/b63333f5-47e9-3569-e795-91e3e9f0c1cc-5d87c62e-9a7c5129-4ecb14f3-eb4f8a8e-1214f889-d48c1c35-150451ac-edf929da-c31d6
188-35dff1c2-b89a4436-1da85d3b-558ad987-97347519-794b87b3-650ed53b-3dcc4294-d594ef30-1fd228af.xml',' xxx','xxx','']
 The error may involve org.craftercms.studio.api.v2.dal.AuditDAO.insertAuditLog-Inline`

### Version
Crafter v 3.1.4

### OS
Linux

### Browser
Does not depend on browser

## Additional context
n.a.

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/4010

**Comment by dejan-brkic** [comment]
- [ ] BE fix https://github.com/craftercms/craftercms/issues/4061
- [ ] BE returns error when filename violates column length
- [ ] UI shows alert box to notify failure due to filename length vilolation

**Comment by sumerjabri** [comment]
@rart @grundmann-thalia  we will fix the backend for the duplicate case in ticket #4061 we will then use this ticket to fix the UI so it provides a better UX

**Comment by sumerjabri** [comment]
@grundmann-thalia please track #4061 for the backend fix which will flow into 3.1.x releases. The UI will follow in the new UI in 3.2.x (the UI is being rewritten in React).

**Comment by jdrossl** [comment]
@rart please check if the UI needs any updates

**Comment by aachavarria** [comment]
verified on 3.2
