### ISSUE TITLE
[docs] Document the characters that Crafter supports in filenames

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4062]
Please document that Crafter CMS can only support the following characters in filenames:

```
Alphanumeric, _, -, 
(last char was a space), so something like this in regex [a-zA-Z0-9-_  ]+
```

It's important to point out that while Studio enforces this regex, outside of Studio (like if developers is working on it's on IDE and pushes to the remote repo) users should make sure filenames follow this regex.

**Comment by sumerjabri** [comment]
Added a general `include` file and linked it here:
* https://docs.craftercms.org/en/3.1/content-authors/content-authors-assets.html#working-with-assets
* https://docs.craftercms.org/en/3.1/developers/content-modeling.html#form-control-variable-names

**Comment by avasquez614** [comment]
Verified
