### ISSUE TITLE
[deployer] Add support for automatically updating ES index settings

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4068]
Because we have an Upgrade Manager & ES aliases the Deployer could be able to automatically update ES indexes following a process like:

1. get the version of the current index from the name
2. create a new index with name v+1 using the new settings
3. index all existing content from the current into the new one
4. if everything is ok, switch the indexes and delete the old one

This could work for any update we need to make to the index settings as long as it is backward compatible to avoid data loss, for example changing limits & adding new fields.

Things to consider:
- Setup with multiple ES clusters, repeat for every cluster.

**Comment by avasquez614** [comment]
@jdrossl @alhambrav  let's make sure this is well documented. I also think whenever there's a version of Crafter that's going to perform this upgrade we should point it out.

**Comment by yacdaniel** [comment]
@jdrossl looks like there is an issue when we upgrade the index and crafter deployer is setup with ES multi-cluster, not all the indexes are upgraded. Ping me for details.

**Comment by jdrossl** [comment]
@yacdaniel everything is merged, please try again

**Comment by yacdaniel** [comment]
@jdrossl please add a way in the UM for the Deployer to wait for ES to be ready.

**Comment by yacdaniel** [comment]
Verified in `Crafter CMS v3.1.8-SNAPSHOT`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1007 for 3.1.8 release notes

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1073 AND https://github.com/craftercms/docs/pull/1074

**Comment by yacdaniel** [comment]
Verified fixed in 4.0
