### ISSUE TITLE
Support extending schema with Interfaces

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4069]
**Is your feature request related to a problem? Please describe.**
If a site has several _N_ content types that share a set of properties, in order to define that set of fields, one would need to define an identical fragment per content type. The idea is that Interfaces would solve this problem, [besides all their usual advantages](https://graphql.org/learn/schema/#interfaces).

**Additional context**
https://graphql.org/learn/schema/#interfaces

Partners have brought this forward in the past but I wasn't able to find a ticket.

**Comment by sumerjabri** [comment]
This is in line with content type inheritance in FE2.

**Comment by sumerjabri** [comment]
This will be done via fragments in FE2. Closing.
