### ISSUE TITLE
[studio] Change URL and save and draft then save and close create duplicate of the page

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#407]
**Alfresco Env Only**

1. Open a page in edit.
2. Edit the URL of the page 
3. Save and Draft
4. Edit some other field
5. Save and Close
6. Reload Studio (ctrl-f5)

You will see that the page now has a child which is a duplicate of it self file name (url) will contain _(SPACE)(Working Copy)_ as part of the name.

**Comment by vestrada** [comment]
@gortizcrafter Can you verify this is working good?

Thanks, Vero

**Comment by gortizcrafter** [comment]
I followed the steps mentioned and the issue cannot reproduce, the behavior is correct. https://www.screencast.com/t/E2ImX083INJ
