### ISSUE TITLE
[studio-ui] Number form control should support the numeric keys on a keyboard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4079]
**Is your feature request related to a problem? Please describe.**
Number form control should support the numeric keys on a keyboard

**Describe the solution you'd like**
Allow the user to use the numeric keys (including the decimal point when appropriate) on a full keyboard in the number form engine control.

The use-case also includes the use using the numeric keypad arrow keys to arrow up and down to change the value.

**Comment by rart** [comment]
@jvega190 similar to the other ticket, let's make sure we're not going off key codes for the validation.

**Comment by jvega190** [comment]
@russdanner there was a ticket for that including several controls https://github.com/craftercms/craftercms/issues/3991. Is it the same? Please let me know if it's an specific case

**Comment by yacdaniel** [comment]
Verified fixed.
