### ISSUE TITLE
[engine] GraphQL queries fail when broken item reference is encountered

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4081]
## Describe the bug
GraphQL queries fail when broken item reference is encountered.
Broken references are created when a user deletes an associated item (via the UI or Git) without cleaning up dependency references.  

Model:
```
Page 
Item selector
-------> child item 1 
-------> child item 2 (deleted)
```

The deleted item in the slider ends up looking like the store URL in the node-selector field in the content form.

In this case, the GraphQL server is able to figure out that child item 2 is deleted, but rather than handle that gracefully and skip the result, instead it seems to partially handle the situation and return null. That breaks the graphql server and spits out a nasty error, saying that a null value for an expected content item can't be rendered. 

## To Reproduce
1. Create the content model above
2. Create a graphQL query to pull the slide
3. Delete the second slide

## Expected behavior
- The Crafter implementation of GraphQL should suppress the null  entry entirely and then carry on.
- A warning should be produced in the log that indicates that GraphQL encountered a reference to an item that does not exist and skipped it. 

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.4E-BETA-3edffe
Build Number: 3edffe32aabd42a760bbe2fa5bfedbc3de9223f6
Build Date/Time: 11-01-2019 16:10:45 -0400

### OS
Any

### Browser
All

**Comment by jdrossl** [comment]
@russdanner using only ES queries (like we do to resolve GraphQL queries) is not possible to know when a reference is broken, we can only prevent the query from failing by indicating in the schema that the field can be `null`

**Comment by russdanner** [comment]
Confirmed:

<img width="1621" alt="1-query-w-working-ref" src="https://user-images.githubusercontent.com/169432/83170528-aa64b080-a0e2-11ea-8ad4-728b9956ce96.png">

<img width="1590" alt="2-break-the-ref-by-rename-or-delete" src="https://user-images.githubusercontent.com/169432/83170567-be101700-a0e2-11ea-8f0e-a4ff86c08170.png">

<img width="1611" alt="3-query-still-operates" src="https://user-images.githubusercontent.com/169432/83170614-d1bb7d80-a0e2-11ea-9594-40dc751f78a3.png">
