### ISSUE TITLE
[docs] Write 3.1.7, 3.0.27 release notes

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4083]
Please write up the release notes. Please provide links to articles related to these sections or document inline if that makes more sense.

Key changes include:
- [x] Security patches
  - [x] Build-in database security enhancements
  - [x] FreeMarker engine security enhancements with service access limits
  - [x] Groovy engine security enhancements
    - [x] Groovy engine service access limits
    - [x] Groovy engine sandboxing
- [x] Proxy system to proxy GraphQL, Engine, NodeJS or other application delivery system
- [x] Removal of `environment-config.xml` and what to do about that
- [x] Bug fixes (must look these up)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/985 and https://github.com/craftercms/docs/pull/986
