### ISSUE TITLE
[docs] Add release note about how to solve backup error.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4104]
## Describe the bug
There is an error while Authoring startup after a restore process, the problem is that the `crafter` db  user not been backed up.  @dejan-brkic have info in how to solve the problem by manually adding the user in the database.  Please add this info of how to get Authoring working after the restore into the release notes.

### Version
`3.1.7`

## Additional context
https://github.com/craftersoftware/craftercms/issues/112
https://github.com/craftercms/craftercms/issues/3987

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/992

**Comment by yacdaniel** [comment]
Verified!
