### ISSUE TITLE
[studio][configuration] proxy configuration require manual context rebuild

### ISSUE THREAD

**Issue by malnajdi** [craftercms/craftercms#4108]
## Describe the bug
Changing the proxy configuration won't take any affect unless authoring is restarted or the Studio context (within Engine) is rebuilt manually.

## To Reproduce
1. change the proxy configuration and save.
2. check if they are applied or not.
3. if not restart the server and you will see them works. 

## Expected behavior
1. change the proxy configuration and save.
2. the change should work without a restart or manual context rebuild

## Screenshots
n/a

## Logs
n/a

### Version
CrafterCMS: authoring: 3.1.7 and 3.2.0

### OS
OS: Debian Buster

### Browser
n/a

## Additional context
I think this issue is related also to the Engine URL Rewrite Configuration (XML Style).
If i have to run https://docs.craftercms.org/en/3.1/developers/projects/engine/api/site/context/rebuild.html than why:
1. include it in the docs of both proxy-config and Engine URL Rewrite Configuration (XML Style).
2. when clicking save it should invoke the rebuild.

**Comment by dejan-brkic** [comment]
Can not reproduce the issue. Context is rebuilt on configuration save automatically

**Comment by sumerjabri** [comment]
@yacdaniel to verify.

**Comment by yacdaniel** [comment]
Hi @malnajdi we are not able to reproduce this. 
As soon as I save the proxy config a context rebuild happens and proxy start working.

Feel free to reopen this issue if you have different/new steps to reproduce it. 

![refresh context proxy](https://user-images.githubusercontent.com/6722074/96934773-0d832500-1480-11eb-9aa5-7a6f7ec1fb30.gif)
