### ISSUE TITLE
[studio] Sidebar incomplete when page configured in sidebar.xml is missing

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#4109]
## Describe the bug
A user moved a page that is referenced as a path in sitebar.xml to somewhere else. As a result the the pathes from the sidebar that are listed below the moved path are missing in the Sidebar.

## To Reproduce
1. Configure a sidebar like this (sidebar.xml):
``` 
...
                               <modulehook>
                                    <name>wcm-root-folder</name>                                    
                                    <params>
                                        <label>Pages</label>
                                        <path>/site/website/a</path>
                                        <path>/site/website/b</path>
                                        <path>/site/website/c</path>
                                        <showRootItem>true</showRootItem>
                                        <onClick>preview</onClick>
                                    </params>
                                </modulehook>
...
```
You should see three folders when clicken on the "Pages"-label in the sidebar: a,b,c
2. (Re-) move folder `site/website/b`
3. Reload sidebar
4. Only folder `a` is visible

## Expected behavior
Folder `c` should still be visible, even if `b` was deleted or moved.

## Screenshots
n.a.

## Logs
n.a.

### Version
v3.1.4

### OS
Linux

### Browser
Chrome

## Additional context
n.a.

**Comment by sumerjabri** [comment]
@rart please route back if BE issue.

**Comment by rart** [comment]
@aachavarria catch the paths not found and show a message for them. if one fails, the others should still render.

**Comment by yacdaniel** [comment]
Verified fixen in `3.1.x` and  `Develop` 
@grundmann-thalia the next release `Crafter CMS 3.1.8` will contain this fix, in the sidebar we added a unavailable icon and a message that the item is not found. Thanks!
![image](https://user-images.githubusercontent.com/6722074/85046149-40718100-b14d-11ea-89e5-96a08845e1a1.png)
