### ISSUE TITLE
[studio] Inconsistent item-state after moving a page 

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#4111]
## Describe the bug
When you create a page, a subpage, publish both and than move the page the system does not recognize that the pages have changed. So you are not allowed to publish them (no publish-item in context-menu).

## To Reproduce
1. Create a page e.g. with file-name "page"
2. Create a subpage e.g. with file-name "subpage"
3. Publish both
4. Inspect item-state in database for `/site/website/page/index.xml` and `/site/website/page/subpage/index.xml` -> EXISTING_EDITED_UNLOCKED
5. Edit the file-name of page e.g. to "page-moved"
6. Inspect item-state in database for `/site/website/page-moved/index.xml` and `/site/website/page-moved/subpage/index.xml` -> still EXISTING_EDITED_UNLOCKED !

## Expected behavior
I don't know the lifecycle in detail but state should be something like NEW_UNPUBLISHED_UNLOCKED.

## Screenshots
n.a.

## Logs
n.a.

### Version
v3.1.4

### OS
Linux

### Browser
Chrome

## Additional context
n.a.

**Comment by sumerjabri** [comment]
@dejan-brkic Must take this scenario to the new item state management mechanics.

**Comment by dejan-brkic** [comment]
@sumerjabri This is a valid state transition (expected behavior). Moving content around does not make it new.

**Comment by sumerjabri** [comment]
Changing the name (moving) the page doesn't make it new, it simply makes it edited. Closing this ticket.
