### ISSUE TITLE
[engine] HttpStatusCodeAwareException Requires Message

### ISSUE THREAD

**Issue by zac-poe** [craftercms/craftercms#4113]
## Describe the bug
A Groovy REST endpoint that throws a HttpStatusCodeAwareException does not have that status code returned to the invoking client if the exception does not contain a message.
HttpStatusCodeException provides constructors that do not require a message.

## To Reproduce
1. Create a groovy endpoint on a Crafter site
2. throw a new org.craftercms.engine.exception.HttpStatusCodeException(400) in the endpoint implementation
3. Invoke the endpoint
4. Observe the HTTP 500 response (instead of the expected 400 response)

## Expected behavior
The expected behavior would be that all HttpStatusCodeAwareException status codes are returned to the client response, regardless of message contents.

### Version
Crafter 3.x

## Additional context
The check at https://github.com/craftercms/engine/blob/master/src/main/java/org/craftercms/engine/controller/rest/RestScriptsController.java#L183 and subsequent response handling appears to override the behavior at https://github.com/craftercms/engine/blob/master/src/main/java/org/craftercms/engine/controller/rest/RestScriptsController.java#L200 when exceptions do not include a message.

**Comment by jdrossl** [comment]
@yacdaniel please help validate the fix

**Comment by yacdaniel** [comment]
Hi @zac-poe, thanks for the report! The issue is fixed and should be available in the next release `Crafter CMS 3.1.9`

**Comment by zac-poe** [comment]
Thanks, guys!
