### ISSUE TITLE
[search][elasticsearch] Updating a shared-component within a page has no effect on search unless page is saved

### ISSUE THREAD

**Issue by malnajdi** [craftercms/craftercms#4114]
## Describe the bug
Changing any shared-components content should trigger a change on all places where it's being used and it show show these changes on the search but it's not. You have to save the component than save the page it's in to be able to see the search results.

## To Reproduce
1. add a shared-component in any page content type.
2. create that page with any component associated with it.
3. update the content of the component without saving the page.
4. go and check if your results appear in the search.

## Expected behavior
once updating a component i should see the changes i want in the search results.

## Screenshots
n/a

## Logs
n/a

### Version
3.1.x including 3.1.7

### OS
Debian

### Browser
firefox

## Additional context
keep in mind these scenarios.

  updating a 
1. component inside a component.
2. component inside a page.
3. component used by many components.
4. component used by many pages. 

I wish i can help and contribute with this with some guidelines from you guys.

**Comment by jdrossl** [comment]
@sumerjabri this is already fixed, but for existing sites the ES index needs to be recreated

https://github.com/craftercms/search/pull/200

**Comment by sumerjabri** [comment]
@malnajdi please re-create the search index.

We have a ticket open for the UM (Upgrade Manager) to do that for you down the road in 3.2.x or 3.3.x.

**Comment by malnajdi** [comment]
@sumerjabri @jdrossl So i followed these steps

1. Create a new index with CrafterCMS mapping:
     1.1 `curl -s -X PUT http://localhost:9201/portal-preview_v2 -H 'Content-Type: application/json' -d '@default-index-settings.json'`
      1.2 `curl -s -X PUT http://localhost:9201/portal-authoring_v2 -H 'Content-Type: application/json' -d '@authoring-index-settings.json'`
2. Reindexing: 
      2.1 `curl -s -X POST http://localhost:9201/_reindex -H 'Content-Type: application/json' -d '@preview-reindix.json'`
      2.2 `curl -s -X POST http://localhost:9201/_reindex -H 'Content-Type: application/json' -d '@authoring-reindix.json'`
3. Aliases:
      3.1 `curl -s -X POST http://localhost:9201/_aliases -H 'Content-Type: application/json' -d '@preview-swap-indexes.json'`
      3.2 `curl -s -X POST http://localhost:9201/_aliases -H 'Content-Type: application/json' -d '@authoring-swap-indexes.json'`
4. Delete Old index:
      4.1 `curl -s -X DELETE http://localhost:9201/portal-preview_v1`
      4.2 `curl -s -X DELETE http://localhost:9201/portal-authoring_v1`
5. Verify that mapping are correct:
`curl -s -X GET http://localhost:9201/portal-authoring_v2/_mapping` and i can see the exact same settings that i passed on. 

6. open `tail -f crafter/logs/deployer/crafter-deployer.log` and changed the content of one of the component without update the page it's in. I can see things are happening.
7. do the search for that keyword that i added and I got no results. 
8. Save the page and search and i got the result.

**Comment by malnajdi** [comment]
Ok i was not using a standard path for my components I was using /site/models which is not picked by deployer.
