### ISSUE TITLE
[studio-ui] Tokenized input fields are not working inside a "Repeating Group"

### ISSUE THREAD

**Issue by ebran1709** [craftercms/craftercms#4118]
## Describe the bug
Looks like Crafter is generating the content-type's xml without add the "tokenized" attribute to the input fields inside a repeating group. That behavior is causing a problem adding the index to elasticsearch because it did not create any "xxxxx_t" that represent the tokenized field.

## To Reproduce
1. Create a content-type with at least on "Repeating Group"
2. Add a input field to the "Repeating Group" and mark it as "Tokenize for Indexing"
3. Add a "New Content" using the content-type created before and fill the field inside the "Repeating Group"
4. Click "Save and Close"
5. Check the xml generated by Crafter and search for the input inside the "Repeating Group"

## Expected behavior
The xml generated should contains the "tokenized" attribute in the input inside the "Repeating Group"

### Version
3.1.5
3.1.6

### OS
Mac OS

### Browser
Google Chrome

**Comment by sumerjabri** [comment]
Verified fixed.
