### ISSUE TITLE
[engine] [studio] [deployer] Make the Elasticsearch client more configurable

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4119]
Right now some clients are reporting timeout issues of ES search in their environments, which could be fixed by configuring some timeout properties in the ES client. Right now this is not possible. Please allow to configure the ES client through Spring peroperties and allow to change the following:

- Timeouts: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_timeouts.html
- Number of threads: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_number_of_threads.html
- Max retry timeout millis: https://stackoverflow.com/questions/51341806/elasticsearch-resthighlevelclient-listener-timeout-after-waiting-for-30000

**Comment by jdrossl** [comment]
The last timeout has been remove in ES7 https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#maxretrytimeout-removed

**Comment by avasquez614** [comment]
Let's make the other ones configurable then

**Comment by avasquez614** [comment]
@jdrossl I think we're missing the properties in the extension files: https://github.com/craftercms/craftercms/tree/develop/resources

**Comment by avasquez614** [comment]
Verified
