### ISSUE TITLE
[studio] Create Forgot Password API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#412]
Create API call for forgot password:
Receive the username or the email address for whom to reset the password. Create a timed secure token and email it to the user's email associated with the username. Secure token contains the username, timestamp, salt.

Create API call for change password:
Received the secure token and new password and decrypts it to get the username and checks for timestamp expiry and throws away the salt. Then sets the password for the user username to the new password.

Additional configuration needed:
Crypto password for this Studio instance.
FreeMarker template for email.
Duration of token (24 hours by default).
Optionally the URL of the server (start with request URL given that's what we do today, and we'll consider alternatives for the next release).

**Comment by dejan-brkic** [comment]
Completed

**Comment by sumerjabri** [comment]
I get 500 when invoking with a valid username. Please fix and please add more logs.

**Comment by dejan-brkic** [comment]
Was not able to reproduce 500 error. Logging improved PR #566

**Comment by sumerjabri** [comment]
Please add logs to show both: failure and success. Please use the right log levels.

**Comment by dejan-brkic** [comment]
PR #569
