### ISSUE TITLE
[studio-ui] Bulk upload dialog becomes unresponsive with large volume of files 

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4124]
@avasquez614 please chime in with details

**Comment by yacdaniel** [comment]
@rart @aachavarria Studio UI should limit 1000 files per upload. Please add a limit to the UI to stop users trying to upload more.

**Comment by rart** [comment]
Attempting to drop more items on the dialog should discard the excess and issue a snack indicating only 1000 have been accepted.

The "drop here" message should also say "1000 max"

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/135356495-1beb46cb-7b70-4f36-b21a-4db84ba7f3ba.png)
