### ISSUE TITLE
[docs] SAML 2 Studio doc enhancements

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4127]
Please make the SAML 2 Studio doc https://docs.craftercms.org/en/3.1/system-administrators/activities/security/configure-studio-saml.html follow a similar structure as the SAML 2 Engine doc https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-saml2-configuration.html: 

- Specify how to create a `keystore.jks` with the `keytool`
- Specify how to create the SP metadata provider XML
- Explain the SAML Studio properties, especially how the `alias`, `storepass` and `keypass` map to the properties.

Also explain the new properties added by https://github.com/craftersoftware/craftercms/issues/110 and https://github.com/craftersoftware/craftercms/issues/103.

**Comment by avasquez614** [comment]
@alhambrav you can ask @dejan-brkic for help with the documentation

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1001

**Comment by avasquez614** [comment]
@alhambrav I updated the comments in the properties to explain more their function: https://github.com/craftersoftware/craftercms/blob/support/3.1.x/resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml#L201. Can you update the docs too please?

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1004

**Comment by avasquez614** [comment]
Verified
