### ISSUE TITLE
[studio] Secure User and Group Management API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#413]
Create User: Admin
Delete User: Admin
Read User: Logged In
Update User: Admin, Self
Forgot Password: Anonymous
Change Password: Admin, Anonymous + Token
Enable/Disable User: Admin

Group Management API: Admin

**Comment by sumerjabri** [comment]
When working on this ticket, review the documentation spec for details on permission and ping me if something looks off.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/649

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/655
