### ISSUE TITLE
[bp-commercetools] Language and currency reset on every page load in studio preview

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4138]
## Describe the bug
 Language and currency reset on every page load in studio preview

## To Reproduce
1. Create a commercetools site
2. Go to preview and using the site sent EN language and USD currency
3. Edit content or simply refresh page
4. See these are reset to German/Euro

## Expected behavior
Site should remain in EN and USD or other set values.  
The site would default to EN and USD rather than DE/EURO if no previous values have been set

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.8-SNAPSHOT-550d74
Build Number: 550d742deabe11e9b99813108b5b15db633f583a
Build Date/Time: 06-19-2020 00:18:55 -0400

### OS
All

### Browser
Any

**Comment by russdanner** [comment]
BP still loses state when a browser refresh is issued
https://www.loom.com/share/b07b16de94804faab04ea0d35fff7b4f

**Comment by sumerjabri** [comment]
@russdanner it wasn't published to MP. You used an older version. One way to test the latest is to clone from GitHub directly, which is what I did and it worked for me. We're publishing to MP now.

Closing as fixed.
