### ISSUE TITLE
[studio] Can't encrypt private keys

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4142]
## Describe the bug
If you try to add a private key in `Engine Site Config` and encrypt it with `Encrypt Marked`, you get an invalid text error.

## To Reproduce
1. From a site's dashboard, go into the `Site Config` > `Configurations` > `Engine Site Configuration`
2. Add an element whose text is an SSH private key (e.g. `<myPrivateKey encrypted="">...</myPrivateKey`).
3. Click on the `Encrypt Marker` button

You should see the an error like the one in the screenshot.

The cause of Studio seems to be that `studio.security.encryption.maxLength` is too short.

## Expected behavior
Encryption should work. Recommendations: `studio.security.encryption.maxLength` should be `5000` and the returned error message should indicate that the text is too long to encrypt, not that the text is invalid.

## Screenshots
![Screenshot from 2020-06-23 16-04-56](https://user-images.githubusercontent.com/1598884/85454862-52975900-b56b-11ea-9778-cfbaa09daf19.png)

**Comment by sumerjabri** [comment]
@dejan-brkic make the max length 4096 bytes. @avasquez614 I think that should suffice, please confirm.

**Comment by avasquez614** [comment]
@avasquez614 4096 sounds good

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2046
https://github.com/craftercms/studio/pull/2047

**Comment by avasquez614** [comment]
Verified
