### ISSUE TITLE
[studio] custom roles are not enforced for sidebar items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4146]
## Describe the bug
Custom roles are not enforced for sidebar items

## To Reproduce
1. Create a custom group
2. Map the group in role mapping and permissions (i copied permissions of author)
3. Add a new side bar element and add a role restriction so that only the custom group can see it
4. As the admin log in (not a user with a custom group) and see the item in the sidebar

## Expected behavior
If an element of the sidebar is restricted by any role or roles then only those users with that group/role should be able to see the item

## Screenshots
<img width="1622" alt="Screen Shot 2020-06-25 at 11 14 13 AM" src="https://user-images.githubusercontent.com/169432/85747501-5646ef00-b6d5-11ea-8b62-d1c9c1a41d01.png">
<img width="930" alt="Screen Shot 2020-06-25 at 11 14 49 AM" src="https://user-images.githubusercontent.com/169432/85747505-5646ef00-b6d5-11ea-99ca-80570f601fa3.png">

## Logs
N/a

### Version
Studio Version Number: 3.1.8-SNAPSHOT-550d74
Build Number: 550d742deabe11e9b99813108b5b15db633f583a
Build Date/Time: 06-19-2020 00:18:55 -0400

Also seen in 3.1.7E

### OS
Any

### Browser
All

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss.

**Comment by sumerjabri** [comment]
Super-admin can see everything. Other roles will see what they're supposed to see.
