### ISSUE TITLE
[studio-ui] Box component doesn't render in repeat group

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4147]
## Describe the bug
Box component doesn't render in repeat group

## To Reproduce
1. Create a form that is configured with a box control in a repeat group
2. Note that it does not render

## Expected behavior
Box control should render in repeat group

## Screenshots
![2020-06-24_11-19-16](https://user-images.githubusercontent.com/169432/85751743-d1f66b00-b6d8-11ea-89f2-a72834e2e5d8.jpg)
![2020-06-24_11-20-28 (1)](https://user-images.githubusercontent.com/169432/85751746-d28f0180-b6d8-11ea-8da3-36af2b817526.jpg)

## Logs
N/A

### Version
Studio Version Number: 3.1.8-SNAPSHOT-550d74
Build Number: 550d742deabe11e9b99813108b5b15db633f583a
Build Date/Time: 06-19-2020 00:18:55 -0400

### OS
Any

### Browser
All

**Comment by sumerjabri** [comment]
Verified fixed.
