### ISSUE TITLE
[studio] Update site creation service to enforce a site name limit

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#415]
Steps
1. Go to the studio.
2. Try to create a site with a long name, for example: testingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtesting

Current Result: https://www.screencast.com/t/RhIZPLo42fsg

Expected Behavior: Studio should have a service to enforce a name limit.

**Comment by sumerjabri** [comment]
Limit is 50 chars given current db schema.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/665
