### ISSUE TITLE
[studio-ui] Implement Item Selection on AddressBar

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4153]
![image](https://user-images.githubusercontent.com/3928341/85778768-350cef80-b723-11ea-9b1b-3eeedec4335c.png)

## Item selection
Being able to pull down the menu, browse through the pages structure and click on an item to preview that page. 
![image](https://user-images.githubusercontent.com/3928341/92242287-db156c80-eebf-11ea-8648-98e989312d51.png)

**Comment by sumerjabri** [comment]
@rart please break this into two tickets like we discussed.

**Comment by rart** [comment]
https://github.com/craftercms/craftercms/issues/4323

**Comment by rart** [comment]
Done.
