### ISSUE TITLE
Error creating site from Git

### ISSUE THREAD

**Issue by ebcaranto** [craftercms/craftercms#4156]
## Describe the bug
Trying to create site from Github to local instance of crafter (freshly installed) but failing.

## To Reproduce
1. Login to crafter
2. Click create site
3. Choose _remote git repository_
4. Fill necessary details and and click Review
5. Click create site

## Expected behavior
Successfully create site.

## Screenshots
![image](https://user-images.githubusercontent.com/40254257/85974437-03887280-ba08-11ea-9a15-5f71119ca13a.png)

## Logs
[Logs from catalina.out](https://gist.github.com/ebcaranto/001f3be272f33215cc78ef14d61a36ed)

### Version
CMS v3.1.7

### OS
MacOS Catalina v10.15.5

### Browser
Chrome v83

## Additional context
Crafter is freshly installed, tried restarting crafter and restart machine and same issue appears.

**Comment by sumerjabri** [comment]
@ebcaranto here is the upgrade guide: https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html

You should also consider migrating to Elasticsearch: https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/migrate-site-to-elasticsearch.html
