### ISSUE TITLE
[studio] Quick create is adding folder entries to the DB

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4157]
Quick create is adding unnecessary entries folders in the `item_metadata` table of the DB (folders are not tracked normally in Studio).

**Comment by russdanner** [comment]
It's more likely that quick create is one way to reproduce the issue.  The issue is likely related to the write content operation with the create folders flag set to true.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2053
https://github.com/craftercms/studio/pull/2054

**Comment by avasquez614** [comment]
Verified
