### ISSUE TITLE
[studio] The bulk publisher should skip DB item_metadata entries with commit_id = null

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4158]
When the publisher finds an `item_metadata` row in the DB (while bulk publishing) with `commit_id` = `null`, it throws a `NullPointerException` and stops the process completely:

```
[DEBUG] 2020-06-26T00:01:13,324 [Studio_Publisher_Thread_Pool10] [git.GitContentRepository] | Checking out file site/components/somefooter.xml from commit id null for site mysite
[ERROR] 2020-06-26T00:01:13,324 [Studio_Publisher_Thread_Pool10] [git.GitContentRepository] | Error when publishing site mysite to environment staging                                            
java.lang.NullPointerException: null 
```

The publisher should just skip the item (but log that it can't publish it) and continue.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2055
https://github.com/craftercms/studio/pull/2056

**Comment by avasquez614** [comment]
Verified
