### ISSUE TITLE
[studio-ui] Add UI validation to enforce a site name limit when creating a site

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#416]
1. Go to the studio.
2. Try to create a site with a long name, for example: testingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtestingtesting

Current Result: https://www.screencast.com/t/RhIZPLo42fsg

Expected Behavior: Studio should have a validation to enforce a name limit.

**Comment by gortizcrafter** [comment]
This bug is related to the following: [https://github.com/craftercms/craftercms/issues/415](url)

**Comment by vestrada** [comment]
Master - PR: https://github.com/craftercms/studio2-ui/pull/307

**Comment by sumerjabri** [comment]
@vestrada: Please do the same for Site Description.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/311

**Comment by vestrada** [comment]
Per conversation with Sumer, the site description max length is 4000 characters.
