### ISSUE TITLE
[studio] User with restricted permissions cannot see dependent items in Delete-dialog

### ISSUE THREAD

**Issue by grundmann-thalia** [craftercms/craftercms#4160]
## Describe the bug
Logged in as a user wih restricted permissions I can see  the dependencies for a component when I use the Dependencies-dialog but I cannot see these depencies in the section "Dependent Items" within the Delete-dialog.

As an admin-user I can see the same dependencies in Dependency-dialog and Delete-dialog.

## To Reproduce
1. Create a component that is referenced by one or more pages
2. Login as author with restricted rights (for the referenced pages)
3. Right-click on created component and choose 'Dependencies'
4. Dependent pages are shown
5. Right-click on created component and choose 'Delete'
6. Dependent pages are shown are *not* shown in section 'Dependent Items'

## Expected behavior
Even if a user has restricted permissions the user should always see all dependent items in Delete-dialog. Otherwise those users will break other pages by accident (already happened!)

## Screenshots
Dependencies-dialog for user this restricted permissions:
![image](https://user-images.githubusercontent.com/58164705/86022647-f3ce5580-ba2a-11ea-9745-77b7c955df9b.png)

Delete-dialog for user this restricted permissions:
![image](https://user-images.githubusercontent.com/58164705/86022500-c1bcf380-ba2a-11ea-845b-adae2c3baefd.png)

In cnotrast Delete-dialog for admin-user:
![image](https://user-images.githubusercontent.com/58164705/86023315-cf26ad80-ba2b-11ea-86fa-0dd342b09382.png)

## Logs
n.a.

### Version
Crafter 3.1.4

### OS
Linux

### Browser
Chrome

## Additional context
Permissions on folder where component to delete is located:
```
            <allowed-permissions>
                <permission>Read</permission>
                <permission>Write</permission>
                <permission>Create Content</permission>
                <permission>Publish</permission>
                <permission>Delete</permission>
            </allowed-permissions>
```
Permissions on folder where referenced page is located:
```
            <allowed-permissions>
                <permission>Read</permission>
                <permission>Write</permission>
                <permission>Publish</permission>
            </allowed-permissions>
```

**Comment by russdanner** [comment]
This issue has been resolved in Crafter 4.x
![image](https://github.com/craftercms/craftercms/assets/169432/8b8a36b5-278a-479e-9960-96b64aceeb28)

Also note: By default, authors are not given permission to delete.
