### ISSUE TITLE
[videocenter] Content Types marked for Quick Create are not shown in Studio

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4163]
## Describe the bug
The Content Types that are marked for `Quick Create` in the Video Center BP are not shown in the Quick Create menu in Studio.

## To Reproduce
1. Create a site from Marketplace -> Videocenter BP
2. Click the `Quick Create` button. 
3. List of items for `Quick Create` is empty.  

## Expected behavior
`Quick Create` menu in Preview should list the Content Types that are defined for Quick Create.

## Screenshots
Quick Create Menu
![image](https://user-images.githubusercontent.com/6722074/86154000-b49e1400-babf-11ea-8c49-9190614e3cf1.png)

Stream Content Type
![image](https://user-images.githubusercontent.com/6722074/86154192-f202a180-babf-11ea-887f-ba1e390a7821.png)

Stream Origin Content Type
![image](https://user-images.githubusercontent.com/6722074/86154215-fa5adc80-babf-11ea-85e4-eaee1e1429c9.png)

Video On Demand Content Type
![image](https://user-images.githubusercontent.com/6722074/86154259-0b0b5280-bac0-11ea-84e5-ea4f806586ff.png)

YouTube Video Content Type
![image](https://user-images.githubusercontent.com/6722074/86154292-18284180-bac0-11ea-93cd-0cec520d4fff.png)

## Logs
N/A

### Version
`Crafter CMS 3.1.8-SNAPSHOT` `Video Center Version 1.1.12`

### OS
Ubuntu

### Browser
Chrome & Firefox

## Additional context
N/A

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/video-center-blueprint/pull/108

**Comment by yacdaniel** [comment]
Verified fixed in `Video Center Version 1.1.13`

![image](https://user-images.githubusercontent.com/6722074/86255975-005ec500-bb75-11ea-887f-e47d4bd8364c.png)
