### ISSUE TITLE
[commercetools-blueprint] In a Blog post the Related Products keep changing a lot. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4164]
## Describe the bug
In a Blog post the Related Products section keeps changing the products, looks like the call to `api/1/product/all.json`  is being done over and over 

## To Reproduce
1. Create a site from Marketplace -> commercetools blueprint. 
2. Go to a blog post.
3. Check the Related Products section

## Expected behavior
Related Products should stay put without changes when the page loads

## Screenshots
![commercetools](https://user-images.githubusercontent.com/6722074/86156840-c97ca680-bac3-11ea-836c-3e5dde87e6e4.gif)

## Logs
N/A

### Version
`Crafter CMS 3.1.8-SNAPSHOT` `commercetools Blueprint 1.1.15`

### OS
Ubuntu

### Browser
Chrome & Firefox

## Additional context
N/A

**Comment by rart** [comment]
Please check recent useEffect dependency updates, @aachavarria

**Comment by yacdaniel** [comment]
Verified fixed.
