### ISSUE TITLE
[studio] Update permission names to one naming convention to be consistent

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4165]
**Is your feature request related to a problem? Please describe.**
There is no consistent naming convention used for permissions. Some permissions use underscores, some uses a dash, some uses spaces in the name, etc.

**Describe the solution you'd like**
It would be nice if we pick a naming convention for the permissions and update the permissions names with the selected naming convention

**Describe alternatives you've considered**

**Additional context**

**Comment by sumerjabri** [comment]
Done.
