### ISSUE TITLE
[studio-ui] Quick-create dropdown with very large number of items disallows reaching all items based on screen-size

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4171]
Reproduce:
1. Add many content-types to quick create
2. Shrink the height of your screen enough so that quick create menu doesn't fit all items on screen
3. Try to reach the last items

Expected:
Whole list is reachable.

**Comment by jvega190** [comment]
Not happening in 3.2.x. Fixed in 3.1.x
