### ISSUE TITLE
[studio] createSiteFromBlueprintGit method in SiteServiceImpl returns always true even if there are errors. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4172]
## Describe the bug
The method `createSiteFromBlueprintGit` in `SiteServiceImpl`returns always true even if there are errors. https://github.com/craftercms/studio/blob/support/3.1.x/src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java#L511
One way to trigger an error and notice that Studio continues is to create a site with a Sandbox Branch name `"abc 123" ` and then try to publish content. 

## To Reproduce
1. Create a site using as Sandbox Branch an invalid name: `"abc 123"`
![image](https://user-images.githubusercontent.com/6722074/86605286-bbb39f00-bf63-11ea-8402-bb22b9ecc65f.png)
2. When the site creation finished, click `Apporve & Publish` to Home page
3. Publisher stuck with error. 

## Expected behavior
Assign the response of `contentRepositoryV2.createSiteFromBlueprint(blueprintLocation, siteId, sandboxBranch, params);` https://github.com/craftercms/studio/blob/support/3.1.x/src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java#L519  to the `success` variable so the Site creation process fails when errors are found, in this case the Sandbox Branch invalid name. 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/yacdaniel/ec588575800f1a18f55b993f6e19bc52

### Version
`Crafter CMS 3.2.x` & `Crafter CMS 3.1.x`

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2072
https://github.com/craftercms/studio/pull/2073

**Comment by yacdaniel** [comment]
Verified fixed.
