### ISSUE TITLE
[studio] My recent activity dashboard is broken

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#4173]
## Describe the bug
My recent activity does not render

## To Reproduce
1. Create new site from editorial
2. Create new page
3. Switch to dashboard
4. My recent activity does not render

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2069
https://github.com/craftercms/studio/pull/2070

**Comment by yacdaniel** [comment]
Verified fixed.
