### ISSUE TITLE
[docs] Update Serverless guide

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4174]
## Describe the bug
We need to update in the Serverless guide https://docs.craftercms.org/en/3.1/system-administrators/activities/delivery/setup-serverless-delivery.html

* ElasticSearch version (6.8 for `support/3.1.x` and 7.2 for `develop`)
* The properties 
```
studio.serverless.delivery.deployer.target.remoteRepoUrl: ${env:CRAFTER_DATA_DIR}/repos/sites/{siteName}/published
# The deployer's local path where it will store the clone of the published site. This property is not needed if
# the deployer is not the preview deployer, so you can leave an empty string ('') instead
studio.serverless.delivery.deployer.target.localRepoPath: ${env:CRAFTER_DATA_DIR}/repos/aws/{siteName}
```
were replaced to only one
```
# The URL of the site repo that the Deployer needs to upload to the bucket needed by serverless delivery. If using the
# local deployer, this should be the local path to the published repo. If using a a Deployer in a separate node
# (because of clustering), this should be an load balanced SSH/HTTP URL to the published repo
# studio.serverless.delivery.deployer.target.repoUrl: ${env:CRAFTER_DATA_DIR}/repos/sites/{siteName}/published
```
* With the implementation of Lazy create published repo https://github.com/craftercms/craftercms/issues/4112 we should add a note in the guide that we can see this error in Deployer 
```
2020-07-07 15:33:00.004 ERROR 22576 --- [deployment-9] l.processors.AbstractDeploymentProcessor : Processor 'gitDiffProcessor' for target 'ed-serverless-delivery' failed
org.craftercms.deployer.api.exceptions.DeployerException: Failed to open Git repository at /home/ubuntu/craftercms/crafter-authoring/data/repos/sites/ed/published;
```
The error should be gone when we do a initial publish. 

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
3.1.x: PR https://github.com/craftercms/docs/pull/1011
master: PR https://github.com/craftercms/docs/pull/1012

**Comment by yacdaniel** [comment]
Verified.

**Comment by yacdaniel** [comment]
The change of the properties in `studio-config.yaml` was rolled back in https://github.com/craftercms/craftercms/issues/4197
https://github.com/craftercms/studio/pull/2088/files#diff-2d1f8d0690185e5259d10a7db11371f6
We need to change back  these properties in the doc. Applies for both 3.1 & 3.2

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1019 and https://github.com/craftercms/docs/pull/1020

**Comment by yacdaniel** [comment]
Verified.
