### ISSUE TITLE
[studio] Add Request Publish(NEW_UNPUBLISHED_UNLOCKED) -> Reject as a valid State Transition.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4176]
## Describe the bug
With the changes of Lazy published repo, when the site is created all content is left with the state `NEW_UNPUBLISHED_UNLOCKED` , when a user Request Publish and the content is Rejected there are no notifications of the Reject because this transition is not defined by Studio 

## To Reproduce
1. Have a `author`, `reviewer` user and email notifications set up
2. Create a site from any BP
3. With the `author` user `Request Publish` some content, notice the email notification is sent. 
4. With the `reviewer` user `Reject` the content, notice the email notification is not sent.

## Expected behavior
The transition state should be valid and email notification is send. 

## Screenshots
N/A

## Logs
```
[WARN] 2020-07-07T18:20:41,667 [http-nio-8080-exec-3] [objectstate.ObjectStateServiceImpl] | Transition not defined for event REJECT and current state NEW_UNPUBLISHED_UNLOCKED [object id: fe99af21-6a13-4d22-af2a-9522cbf3f72c]
[ERROR] 2020-07-07T18:20:41,710 [http-nio-8080-exec-3] [notification.NotificationServiceImpl] | Unable to notify content rejection
```

### Version
`3.1.x` & `3.2.x`

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2076
https://github.com/craftercms/studio/pull/2077

**Comment by yacdaniel** [comment]
@dejan-brkic please check the notification error when content is rejected
```
[ERROR] 2020-07-14T08:53:00,577 [http-nio-8080-exec-8] [notification.NotificationServiceImpl] | Unable to notify content rejection 
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2081
https://github.com/craftercms/studio/pull/2082

**Comment by yacdaniel** [comment]
Verified fixed.
