### ISSUE TITLE
[craftercms] Add a new salt variable and deprecate the current salt variable

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4178]
We've been documenting and using the `CRAFTER_ENCRYPTION_SALT` wrong. Right now we specify a normal, password-like string, but the class the does the encryption/decryption expects the salt in Base 64: https://github.com/craftercms/commons/blob/master/utilities/src/main/java/org/craftercms/commons/crypto/impl/PbkAesTextEncryptor.java#L43. 

It's not a good idea to ask system admins to base 64 the salt when installing, but we can't just change the way we use the salt variable because it will break currently encrypted strings. So we should do the following in our bundled `crafter-setenv.sh`:

1. Add a new variable called `CRAFTER_ENCRYPTION_SALT_STRING`. This variable should contain the password-like, clear string.
2. Make the old `CRAFTER_ENCRYPTION_SALT` empty, and add the following comment:

```
DEPRECATED. Please use the `CRAFTER_ENCRYPTION_SALT_STRING` if your installation is new or you haven't encrypted any configuration file values. If you have already, you can still use this variable. Please read more about this in here [DOCUMENTATION LINK]
```

3. Our Crafter modules should now check if the `CRAFTER_ENCRYPTION_SALT` is empty. If it is, then the `CRAFTER_ENCRYPTION_SALT_STRING` is used for encryption and is treated as a normal string. If it's not, then `CRAFTER_ENCRYPTION_SALT` is used and is treated as a Base 64 string.  

Our documentation needs to change to document the new and provide guidelines. We can leave a link in the new doc to the old doc for existing installs. We can even explain how to move to this if desired, but make sure the user understands that they don't have to. To move over, all encrypted values must be re-encrypted.

**Comment by jdrossl** [comment]
@alhambrav we didn't change the existing variables but only added a couple more that should be mentioned in the docs

**Comment by avasquez614** [comment]
@jdrossl there might be a problem with the new way we get the salt. Right now, we're calling `salt.getBytes()`, which uses the default charset. This could be a problem if, for example, a config value is encrypted on a server with a charset, and then a developer machine with different charset clones the site from remote. I think we should use https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#getBytes-java.nio.charset.Charset- with the `UTF-8` charset.

**Comment by avasquez614** [comment]
Verified
