### ISSUE TITLE
[studio] The other cluster node appears in the remote repositories

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4181]
## Describe the bug
On a Studio cluster, when going to Site Config > Remote Repositories, you can remove remote repo in the other node in the list.

## To Reproduce
1. Set up a Studio cluster.
2. Go to Site Config > Remote Repositories

You should see the repo of the other node in the list. Now remove it.

## Expected behavior
The repo of the other node shouldn't be removable from the Remote Repositories list.

## Screenshots
![Screenshot from 2020-07-09 13-00-31](https://user-images.githubusercontent.com/1598884/87068850-325ecf80-c1e4-11ea-9f86-75ca2643e9ec.png)

**Comment by sumerjabri** [comment]
@dejan-brkic is this a UI thing purely or BE can indicate that the site is removable or not?

**Comment by sumerjabri** [comment]
Will investigate to see if it actually breaks or not. The cluster syncer will re-create the missing repos (to be confirmed with an experiment).

**Comment by dejan-brkic** [comment]
Done:
PR:
https://github.com/craftercms/studio/pull/2097
https://github.com/craftercms/studio/pull/2098

**Comment by dejan-brkic** [comment]
UI needs to be updated.

- [ ] Delete action (trashcan icon) should be removed for repositories that have property `removable: false`

**Comment by sumerjabri** [comment]
@avasquez614 code is done, front and back, please validate.

**Comment by avasquez614** [comment]
Verified
