### ISSUE TITLE
[studio] History retrieval API enhancement

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4183]
**Is your feature request related to a problem? Please describe.**
The main issue is API1 history retrieval is not paginated

**Describe the solution you'd like**
Let's design & create an API2 for 3.2.x

**Describe alternatives you've considered**
We can use the API1 and remove the pagination temporarily. Large histories may be problematic to render — and maybe even retrieve.

**Additional context**
At the moment, this is primarily for the history dialog though there are designs which feature history too on other pieces of the design prospects.

**Comment by sumerjabri** [comment]
Done
