### ISSUE TITLE
[studio] Create getContentByCommitId(path, commit_id)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4184]
**Is your feature request related to a problem? Please describe.**
For version reviewing and comparing, there's no way of retrieving a past version of a content XML

**Describe the solution you'd like**
getContentByCommitId(path, commit_id)

**Additional context**
A similar API that would retrieve 2 commits at once would be optimal for comparing. We can manage with the single

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2658

**Comment by rart** [comment]
Please validate & carry on with the history dialog matter

**Comment by jvega190** [comment]
Verified

**Comment by sumerjabri** [comment]
Please switch to return an attachment containing the actual file and set the mime-type correctly. You may ignore the standard JSON response and just focus on returning the correct HTTP status code + the actual file.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2674

**Comment by rart** [comment]
Verified/integrated latest approach on https://github.com/craftercms/studio-ui/pull/2460.
