### ISSUE TITLE
[docs] Add a guide for the new proxy

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4185]
We should add a guide that includes the following:
- Explain why the proxy is needed and how it works in general
- Provide detailed steps for setting up the proxy with a react blueprint like videocenter or wordify

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1028 and https://github.com/craftercms/docs/pull/1025

**Comment by jdrossl** [comment]
Verified
