### ISSUE TITLE
[studio] Publisher doesn't work when a site with a published repo is removed and then a new site is created with same site name.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4189]
## Describe the bug
Publisher doesn't work when a site with a published repo is removed and then a new site is created with same site name.

## To Reproduce
1. Create a site wit site name "sitea"
2. Publish a page and wait for content published
3. Remove the created site
4. Create a new site using the same site name in 1. "sitea"
5. Publish a page

## Expected behavior
Page published without errors

## Screenshots
N/A

## Logs
Log of site creation, publish, remove of site, new site and publish
https://gist.github.com/yacdaniel/d6bb993d313b1cf443dbcde50c183344

### Version
`3.1.x` & `3.2.x`

### OS
Any

### Browser
Any

## Additional context
Probably related to the work did in https://github.com/craftersoftware/craftercms/issues/143

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2084
https://github.com/craftercms/studio/pull/2085

**Comment by yacdaniel** [comment]
Verified fixed.
