### ISSUE TITLE
[profile] Crafter Profile Admin should mark required fields as such when creating or changing a user

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#4190]
## Describe the bug
Crafter Profile Admin should mark required fields as such when creating or changing a user when creating or changing a user 
crafter profile admin fails if First Name, Last Name, Avatar Link or Display Name are not filled, 

## To Reproduce
1. Go to crafter profile admin
2. Create a new User 
3. Fill only the fields marked with * 
4. Click save 
5. See error

## Expected behavior
Either mark all fields as required or completed the execution with marked fields.

## Screenshots
![image](https://user-images.githubusercontent.com/574641/87357303-f055c680-c520-11ea-8fb1-7d1042ea706d.png)

## Logs
https://gist.github.com/cortiz/b3157f904019b97b47d0f47f7720bf66

### Version
Both 3.1.7E or 3.1.8E or CE 

### OS
Crafter 3.1.7E Byol AWS IAM 

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@sumerjabri per conversation with @avasquez614 the fields shouldn't be required (backend)
