### ISSUE TITLE
[studio][studio-ui] Add friendly name to sites list 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4192]
**Is your feature request related to a problem? Please describe.**
System and site administrators want to be able to label sites with a friendly name that is different than the site ID to make it easier for users to find their sites.

**Describe the solution you'd like**
* Add the support to create site that allows site admins to set a label for the site. Labels should be unique to avoid confusion.
* Site list should show label. 
* Site admin should be able to edit the label and site description at a later date

**Comment by rart** [comment]
**UI**
 - [ ] Add/send field on site creation form
 - [ ] Add/send field on site edit form
 - [ ] Display label on site list and other places where displayed including dashboard, global nav, site config, preview site selector.

**Backend**
 - [ ] Add field to db
 - [ ] Add/receive field to create API
 - [ ] Add/receive field to update API
 - [ ] Add/send field to retrieval API(s)

**Comment by sumerjabri** [comment]
@dejan-brkic we will add a new field for this, call it "name"? and use that as the friendly name. Description is already in there and will be used.

**Comment by jdrossl** [comment]
@jvega190 the API updates are now merged

@yacdaniel please track this ticket because the new field will break all tests

**Comment by jvega190** [comment]
@yacdaniel the PR is now merged, leaving it to you for testing, please let me know if you need something

**Comment by yacdaniel** [comment]
Hi guys, we need some changes:

@jdrossl  BE:

- [ ] Creating a site:  when the new `name` parameter is over the max length Studio should return a proper response(check what we currently do when `site_id` is over 50 chars), right now it returns HTTP 500 Internal Server Error with message: `{
    "message": "Internal server error: \norg.craftercms.studio.api.v1.exception.SiteCreationException: Error while creating site: 123 ID: 123 from blueprint: org.craftercms.blueprint.empty"
}`
- [ ] Changing the `name` with API `/studio/api/2/sites{siteId}`: Should also check for max length and return response properly, right now it returns HTTP 500 Internal Server Error. `"response": { "code": 1000,  "message": "Internal system failure",  "remedialAction": "Contact support", "documentationUrl": ""  }`
- [ ] Using the API ` /studio/api/2/sites{siteId}` allows to set values of `name` that are already in the DB. Studio should return an message indicating that value exist and shouldn't allow the duplicate value.  

@jvega190 UI:
- [ ] When editing a site name we should update to reflect the API response in case the value already exist(last case above)
- [ ] UI should allow up to `255` for `name` when a site is created and when we edit the site.
- Responsive issues when name is a long value:
  - [ ] Global site pages
![image](https://user-images.githubusercontent.com/6722074/95791357-760f1c80-0c9e-11eb-8625-4954193c6586.png)
  - [ ] Site config 
![image](https://user-images.githubusercontent.com/6722074/95791428-9343eb00-0c9e-11eb-9848-415518c80be3.png)
  - [ ] Preview with open Sidebar(check also with close Sidebar)
![image](https://user-images.githubusercontent.com/6722074/95791481-ae165f80-0c9e-11eb-9987-0056f9303e95.png)
  - [ ] Dashboard with open Sidebar(check also with close Sidebar)
![image](https://user-images.githubusercontent.com/6722074/95791528-c9816a80-0c9e-11eb-912a-e4a6e9850e1b.png)

**Comment by jdrossl** [comment]
@yacdaniel all validation are ready on the backend too

**Comment by yacdaniel** [comment]
@jdrossl please chagne the API both site name and description as optional values.

**Comment by jdrossl** [comment]
@jvega190 please update the UI so that the request only includes the fields changed by the user, for example if the name is not changed it should be `null` on the request

**Comment by jdrossl** [comment]
@yacdaniel fix for update ready

**Comment by yacdaniel** [comment]
Verified.
