### ISSUE TITLE
[studio-ui] Deleting an invalid value from input with pattern-validation, does not remove invalid state. 

### ISSUE THREAD

**Issue by philipp-brock-thalia** [craftercms/craftercms#4193]
## Describe the bug
Deleting an invalid value from input with pattern-validation, does not remove invalid state. 

## To Reproduce
1. Edit a component with an input with pattern-validation and not required value.
2. Insert an invalid value into the input field -> form-validation is displayed
3. Change the value to empty-string
4. Try to save the form -> form-validation is still displayed and you receive an error-alert "You cannot save until all form requirements are satisfied"

## Expected behavior
When changing the value of an input with pattern-validation from an invalid one to empty-string saving is possible without getting an error.

## Line of Code
[This line may be the cause](https://github.com/craftercms/studio-ui/blob/13229d58238a4065c93126c59ba0eba3019a2dcb/static-assets/components/cstudio-forms/controls/input.js#L59)

## Version
3.1.4

**Comment by jvega190** [comment]
@yacdaniel can you please verify?

**Comment by yacdaniel** [comment]
@jvega190 Please check the same case but with the control `numeric-input`, looks like the error is also there. Thanks!

**Comment by yacdaniel** [comment]
Hi @philipp-brock-thalia ! thanks for the bug report. The issue is fixed and the next release: `Crafter CMS v3.1.9` will contain the fix.
