### ISSUE TITLE
Content should be uploaded to a non-git location for checks and processing before being committed to git

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4195]
**Is your feature request related to a problem? Please describe.**
There are several scenarios where you do not want content committed to the repo:
- Large objects may need to be processed and or rejected
  - size checks
  - virus scanning
  - renditioning

**Describe the solution you'd like**
Upload the content to a holding area and process it first. If processing passes, add it to the repository.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/3225

A general approach should address both issues in the same flow.

Content writes should flow through the same code and permit interception and update of content before committing it to disk.

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6061
