### ISSUE TITLE
[studio-ui] Users with email address as user name cannot be edited via the Users admin console

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4196]
## Describe the bug
Users with email address as user name cannot be edited via the `Users` admin console.

## To Reproduce
1. In the Main Menu, click on `Users` and then create a user with the username using an email address.  We will use `myuser@example.com` for our example
2. Edit the newly created user `myuser@example  by clicking on the edit icon (pencil) next to the username.  Notice that the dialog that opens is empty, no field is filled in.  Cancel the dialog
3. Reset the password of the newly created user by clicking on the reset password icon (key) then entering a new password.  Click on `Save`.  Notice the error displayed
![Screen Shot 2020-07-16 at 12 59 17 PM](https://user-images.githubusercontent.com/25483966/87703876-7f551f80-c769-11ea-8bc0-05247ba5bb10.png)

If you inspect your browser while editing a user with the username using an email address, notice that requests to get the user (GET http://localhost:8080/studio/api/2/users/myuser@example.com) returns an http status code 406

## Expected behavior
Users with email addresses as the username should be editable and with password reset working via the `Users` admin console from the `Main Menu`

## Screenshots
Here's a short clip:
https://www.loom.com/share/319a6525c8ec4559911c76181331e349

showing the following:
(1) user `myadmin` is edited (notice all the fields are filled in the dialog that opens after clicking on the edit icon)
(2) user `myuser@example.com` is edited (notice all the fields are empty in the dialog that opens after clicking on the edit icon)
Notice the http status code 406 thrown when a GET http://localhost:8080/studio/api/2/users/myuser@example.com was performed
(3) password of user `myuser@example.com` is reset.  Notice the error
![Screen Shot 2020-07-16 at 1 21 09 PM](https://user-images.githubusercontent.com/25483966/87703068-41a3c700-c768-11ea-874a-a02a29aeb22e.png)
 

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.9-SNAPSHOT-ea1875
Build Number: ea1875bbcbf8c71c8244f75239e102908eec949a
Build Date/Time: 07-16-2020 10:18:39 -0400

### OS
Mac OS

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1858
https://github.com/craftercms/studio/pull/2086
https://github.com/craftercms/studio-ui/pull/1859
https://github.com/craftercms/studio/pull/2087

**Comment by yacdaniel** [comment]
Verified fixed.
