### ISSUE TITLE
[studio] Can't push to a branch that's different than the sandbox branch

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4199]
## Describe the bug
Can't push to a branch that's different than the sandbox branch (e.g. push from the `master` sandbox branch to the `test` branch) 

## To Reproduce
1. Create a site from a remote repo with at least 2 branches, e.g. `master` and `test`. Use `master` as the sandbox branch
2. Make a change, like saving the Home page
3. Go to Site Config > Remote Repositories and push to `test`.

An internal server error popup appears and a `java.io.IOException: Source ref test doesn't resolve to any object` appears in the logs.

## Expected behavior
The push should work

## Logs
https://gist.github.com/avasquez614/9de8333704733461c3d3728760359acb

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2092
https://github.com/craftercms/studio/pull/2093

**Comment by avasquez614** [comment]
Verified
