### ISSUE TITLE
Incorrect data format getting written to Solr

### ISSUE THREAD

**Issue by jrosler** [craftercms/craftercms#420]
Using 2.5.2, I create a new component type with a date-time control. After I create new content based on that component and look at the XML content (and solr content), I see that the date/time value is in a kind of MM/dd/yyyy HH:mm:ss kind of format. The problem is that this format gets persisted to Solr and I can't do any solr date type queries (e.g. &fq=lastModifiedDate_dt:[NOW-7DAY/DAY%20TO%20NOW]).

If I do a direct solr query and look at the record that was saved, I see that it appears that this happened to some extent before for create and modify dates, as I see a *_dt field for them which is in the proper solr format.

       "id":"asite:/site/components/meetings/40124e8c-78eb-98a5-0868-5aa6e40a530c.xml",
        "rootId":["asite:/site/components/meetings/40124e8c-78eb-98a5-0868-5aa6e40a530c.xml"],
        "crafterSite":"asite",
        "localId":"/site/components/meetings/40124e8c-78eb-98a5-0868-5aa6e40a530c.xml",
        "crafterPublishedDate":["2017-01-25T19:07:49.515Z"],
        "crafterPublishedDate_dt":"2017-01-25T19:07:49.515Z",
        "content-type":["/component/meeting"],
        "merge-strategy":["inherit-levels"],
        "objectGroupId":["4012"],
        "objectId":["40124e8c-78eb-98a5-0868-5aa6e40a530c"],
        "file-name":"40124e8c-78eb-98a5-0868-5aa6e40a530c.xml",
        "internal-name":"Some random meeting",
        "location":["Board room"],
        "canceled":["false"],
        "startDateTimeofMeeting":["01/26/2017 18:00:00"],
        "endDateTimeofMeeting":["01/26/2017 19:00:00"],
        "createdDate":["1/25/2017 19:6:33"],
        "createdDate_dt":"2017-01-25T19:06:33Z",
        "lastModifiedDate":["1/25/2017 19:6:33"],
        "lastModifiedDate_dt":"2017-01-25T19:06:33Z",
        "_version_":1557524664312397824}]

**Comment by jrosler** [comment]
My bad. I didn't name my field *_dt. After I did that problem solved.

**Comment by russdanner** [comment]
Jeff,

There is also another way to handle this which is to update your schema in Solr.  In 2.5.x we support multi-core Solr so each site can have it's own schema/config etc.

Use of a schema or dynamic types is up to you.  In some ways I prefer the schema although I recognize using dynamic typing in the content type variable name means I am updating things in one place.
