### ISSUE TITLE
[studio] Removing a remote doesn't remove the remote-tracking branches

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4200]
## Describe the bug
Removing a remote doesn't remove the remote-tracking branches

## To Reproduce
1. Create a site from a remote repo with several branches.
2. From the CLI, go to the sandbox repo and run `git branch -a`. You should see something like the following as the output:

```
* master
  remotes/origin/master
  remotes/origin/test
```

3. From Studio, go to Site Config > Remote Repositories, and remove the remote.
4. From the CLI, run again `git branch -a` in the `sandbox`.

The branches that start with `remotes/origin` are still there

## Expected behavior
All branches from the remote should be removed on remote remove. Basically, removing a remote should work exactly the same as `git remote remove`: https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emremoveem

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2090
https://github.com/craftercms/studio/pull/2091

**Comment by avasquez614** [comment]
Verified
