### ISSUE TITLE
[studio-ui] Long username overlaps with some columns in Studio Dashboard

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4202]
## Describe the bug
Long usernames, for example, those that come from corporate emails, are causing overlapping of text in some sections of the Studio Dashboard

## To Reproduce

0. Create a site from any blueprint.
1. Create a user with a long username value, example `yacdaniel.example@example.com` Add the user to the `site_admin` group
2. Create 3 different pages, send 1 page to live, send another page to a publish schedule, and leave the last page in an In Progress state.
3. Open your browser tools then go to the device toolbar and select the resolution `Laptop with HiDPI Screen`, or set manually a resolution of `1440x900` 
![imagen](https://user-images.githubusercontent.com/6722074/87994202-9ec1b480-caa9-11ea-9474-9f64ad1b5fd0.png)
3. Go to the Studio Dashboard. Click `Show "In-Progress" Items` in the `Items Waiting for Approval` widget. 
4. See overlaping of text in `Last Edited By` & `Last Edited` 
![imagen](https://user-images.githubusercontent.com/6722074/87994396-0c6de080-caaa-11ea-8d09-c71ff92cab73.png)
5. Check `My Recent Activity` widget, See overlapinf of text in `Last Edited By` & `My Last Edit` 
![imagen](https://user-images.githubusercontent.com/6722074/87994537-68d10000-caaa-11ea-8ccb-ec70abfbd40d.png)

## Expected behavior
Text from username should not overlap with other columns' information.

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.x` & `3.2.x`

### OS
Any

### Browser
Chrome & Firefox

## Additional context
The max lenght of a username is going to be defined here https://github.com/craftercms/craftercms/issues/4198

**Comment by jvega190** [comment]
Done in here:
3.1.x: https://github.com/craftercms/studio-ui/pull/1860
3.2.x: https: //github.com/craftercms/studio-ui/pull/1861

**Comment by yacdaniel** [comment]
Verified fixed 
![image](https://user-images.githubusercontent.com/6722074/89195984-d0855180-d566-11ea-8fa4-a5ab92842968.png)
