### ISSUE TITLE
[studio] Log additional details the Upgrade Manager commits

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4208]
**Is your feature request related to a problem? Please describe.**
When upgrades are applied to multiple environments and histories from those upgrade events are eventually merged through devops operations (content back) it can be difficult to understand where certain upgrade related changes came from.

**Describe the solution you'd like**
Log additional details un upgrade manager commits
- Studio ID
- Environment ID
- Machine ID

**Additional context**
Consider encrypting the details in these commit messages

**Comment by jdrossl** [comment]
@russdanner we have a `Studio ID`, but what would be `Environment ID` & `Machine ID`?

**Comment by russdanner** [comment]
Confirmed
