### ISSUE TITLE
[studio ui] Sidebar trees sometimes fail to render on slow internet connections and VPNs

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4209]
## Describe the bug
Sidebar trees sometime fail to render on slow internet connections and VPNs (see screen shot)

## To Reproduce
1. Use browser to simulate slow internet connection
2. Open the side bar in editorial and refresh screen until you see this behavior

## Expected behavior
The tree should always render no matter how slow the connection 

## Screenshots

![hidden-sidebar](https://user-images.githubusercontent.com/169432/88216205-c9874680-cc2a-11ea-9869-92cf53b5ea5c.png)

## Logs
None

### Version
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32

Also seen in 3.1.7 and 8

Build Date/Time: 05-07-2020 17:31:21 -0400
### OS
Any

### Browser
All

## Additional context
A full page refresh is the current workaround for this issue.

**Comment by russdanner** [comment]
3.2.0E will complete replace the APIs and Sidebar code that is associated with this bug.
The new widget and APIs support the following:
- Trees are replaced by a breadcrumb style browse
- The current folder is paginated
- Search is supported
- Translation status/operations are supported

<img width="1236" alt="Screen Shot 2020-07-22 at 2 45 37 PM" src="https://user-images.githubusercontent.com/169432/88216553-41557100-cc2b-11ea-9bb2-9b6ebbdf0611.png">

**Comment by rart** [comment]
This is tagged as 3.2 only. Can we fix provided 3.2 will have the new widgets? @russdanner

**Comment by rart** [comment]
This is tagged as 3.2 only. Can we close provided 3.2 will have the new widgets? @russdanner

**Comment by rart** [comment]
Closed as agreed on the 3.2 ticket review sheet.
