### ISSUE TITLE
[docs] Update active cache docs with important message indicating that active cache now has to be enabled

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4210]
Several releases ago, active cache was set to be disabled by default. In order to enable active cache, now a Spring profile has to be set in `crafter-setenv.sh`: `export SPRING_PROFILES_ACTIVE=crafter.core.activeCache`. Please update the doc in https://docs.craftercms.org/en/3.1/developers/cook-books/active-cache/cache-a-restful-response.html to indicate this. We need to add a comment to  `crafter-setenv.sh` with the line too.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1022 and https://github.com/craftercms/docs/pull/1023

**Comment by avasquez614** [comment]
Verified
