### ISSUE TITLE
[studio] Upgrade from 3.0.18 to 3.1.x fails

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#4214]
## Describe the bug
{{A clear and concise description of what the bug is.}}

## To Reproduce
1. Install from bundle 3.0.18
2. Start authoring
3. Create a site from the editorial blueprint
4. Upgrade to 3.1.x using documentation https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html
5. Authoring does not start. Error is below in the logs section

## Expected behavior
Upgrade successfully from 3.0.18 to 3.1.x 

## Logs
https://gist.github.com/dejan-brkic/e255849241686cbb524cbb66f4f0e0e1

## Additional context
Upgrade fails also for older versions (e.g. 3.0.14)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2101
https://github.com/craftercms/studio/pull/2102

**Comment by yacdaniel** [comment]
Verified fixed.
