### ISSUE TITLE
[studio] In a Studio cluster, a folder created in one node doesn't appear in the other node

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4216]
## Describe the bug
In a Studio cluster, a folder created in one node doesn't appear in the other node

## To Reproduce
1. Set up a Studio 2 node cluster
2. Create a site based in the editorial bp
3. Logged in to one of the nodes, create a folder under Pages > Home > articles, e.g. 2020

If you go to the other node, the folder doesn't appear, even if you refresh the page

## Expected behavior
A folder created in one node should appear in the other node

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2107
https://github.com/craftercms/studio/pull/2108

**Comment by avasquez614** [comment]
Verified
