### ISSUE TITLE
[studio] Error in log when creating site from marketplace/site as orphan

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4219]
## Describe the bug
There is an error in Studio's log when a site is created from marketplace or using the option create a site from remote repo as orphan. 

## To Reproduce
Steps to reproduce the behavior, 2 ways:
a) Option 1
1. Create a site from any site from marketplace

b) Option 2
1. Create a site from a remote repository, check the option `Create the site from a remote repository as orphan (no git history)`

* For both options, check error in catalina log

## Expected behavior
No errors in log when the site is created. 

## Screenshots
N/A

## Logs
Site created from marketplace
https://gist.github.com/yacdaniel/ade4537754c01c45c9f2734ca55a5b10

### Version
`3.1.x` & `3.2.x`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2110
https://github.com/craftercms/studio/pull/2111

**Comment by yacdaniel** [comment]
Verified fixed.
