### ISSUE TITLE
for authoring_elasticsearch_1  Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits

### ISSUE THREAD

**Issue by WatchingOn9** [craftercms/craftercms#4224]
Hi all, i've encountered this error when i trying to install crafter cms in docker container 

Error: 
```
PS C:\docker-compose\authoring> docker-compose up
Creating authoring_elasticsearch_1 ... error

ERROR: for authoring_elasticsearch_1  Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid option: Windows does not support Ulimits
ERROR: Encountered errors while bringing up the project.
```

OS Version: Windows Server 2019
16GB RAM, 4CPUs

Docker Version: 
```
PS C:\docker-compose\authoring> docker --version
Docker version 17.10.0-ee-preview-3, build 1649af8
```

I've performed in reference to this article: 
https://docs.craftercms.org/en/3.1/getting-started/quick-start-guide.html#running-crafter-cms-in-a-docker-container

Any help and comments is appreciated. Thank you.

**Comment by avasquez614** [comment]
Hi @WatchingOn9. Crafter CMS on Windows is meant for developers running Crafter locally on MS Windows for development purposes. For server deployments, you should use Linux. From your ticket, it seems that you're using Docker Enterprise on MS Windows Server.
