### ISSUE TITLE
[Studio] Current Version of MariaDB is not compatible with OSX 10.11

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#4225]
## Describe the bug
Crafter is unable to start under OSX 10.11, due to a missing internal symbol
 `dyld: lazy symbol binding failed: Symbol not found: _clock_gettime` this symbol was added in OSX 10.12 
https://developer.apple.com/forums/thread/67102 

Scripts should stop if the OSX version is 10.11 or older, and prompt an error message and/or Documentation should mention this requirement. 

## To Reproduce
1. Start Crafter Studio on OSX 10.11

## Expected behavior
Start Crafter 
## Logs
https://gist.github.com/cortiz/b9f9a70554635ce77b9124a24abd778a

### Version
Crafter 3.1.x

### OS
OSX 10.11

### Browser
Any

**Comment by sumerjabri** [comment]
@alhambrav let's add 10.12 as a minimum requirement here: https://docs.craftercms.org/en/3.1/system-administrators/requirements-supported-platforms.html#supported-platforms

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1032 and https://github.com/craftercms/docs/pull/1032
