### ISSUE TITLE
[docs] Update content monitoring docs to use ES queries

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4227]
The queries used in this article https://docs.craftercms.org/en/3.1/site-administrators/studio/content-monitoring.html need to be updated to use the ES format for date math https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math

You can also take a look at the default values that are already updated https://github.com/craftercms/studio/blob/support/3.1.x/src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/config/studio/site-config.xml#L148

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1037 and https://github.com/craftercms/docs/pull/1038

**Comment by sumerjabri** [comment]
Docs have been updated and now syncing to the CDN. @jdrossl please validate when you can.

**Comment by jdrossl** [comment]
Verified
