### ISSUE TITLE
[deployer] CloudfrontInvalidationProcessor causes the deployment to fail

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4231]
If the `CloudfrontInvalidationProcessor` tried to invalidate a path that no longer exists it will fail causing the the entire deployment to fail too

**Comment by jdrossl** [comment]
@avasquez614 I was not able to reproduce the issue, I tried with 2 s3 targets invalidating the same cloudfront distribution and never got an exception. Also if I add a hardcoded error the processor fails but the pipelines continues executing after that.

**Comment by avasquez614** [comment]
Verified, can't reproduce, we're good for now
