### ISSUE TITLE
[studio] Upgrading a 3.1.6 Studio cluster leaves the remote repos in a weird state

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4232]
## Describe the bug
Upgrading a 3.1.6 Studio cluster to the latest 3.1.9 build leaves the Remote Repositories of a site in a weird state

## To Reproduce
1. Setup a 2 node Studio 3.1.6 cluster.
2. Create an editorial site
3. Stop node 2
4. Stop node 1
5. Upgrade the Crafter CMS install of both nodes to the latest build of 3.1.9
6. Start node 1
7. Start node 2

If you login to node 1 and go to Site Config > Remote Repositories of the editorial site, there are 2 repositories for node 2, one of them removable (see first screenshot)

If you login to node 2 and go to Site Config > Remote Repositories of the editorial site, there's 1 removable repository for node 1 (see second screenshot)

## Expected behavior
After upgrade, each node should have a non-removable remote for the other node.

## Screenshots

Node 1 remotes:
![node 1 remotes](https://user-images.githubusercontent.com/1598884/89346491-1f221100-d677-11ea-9b2b-a40b05c04987.png)

Node 2 remotes:
![node 2 remotes](https://user-images.githubusercontent.com/1598884/89346492-1fbaa780-d677-11ea-84c5-d9d18b71fdac.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2118
https://github.com/craftercms/studio/pull/2119

**Comment by avasquez614** [comment]
after a meeting with @dejan-brkic and @sumerjabri, we found out that the upgrade is now removing the remotes from the DB. @dejan-brkic will troubleshoot.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2127
https://github.com/craftercms/studio/pull/2128

**Comment by avasquez614** [comment]
Verified
