### ISSUE TITLE
[studio-ui] Numeric input form control display a message when a decimal is typed. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4235]
## Describe the bug
A message is shown in the numeric form control when a decimal is typed. The message is visible in Firefox and  in Chrome it appears when you hover the control. 

## To Reproduce
1. Add a numeric input control to a content type
2. Edit content and enter a decimal value
3. In Firefox the message is displayed and in Chrome you need to hover the control to see it.

## Expected behavior
Decimal values are supported and saved successfully by form engine, the message shouldn't be displayed.

## Screenshots
Firefox
![image](https://user-images.githubusercontent.com/6722074/89428572-c2b40580-d6f9-11ea-8696-6aefa5fd5067.png)

Chrome
![image](https://user-images.githubusercontent.com/6722074/89428601-ce9fc780-d6f9-11ea-898d-12fc7c0d1b61.png)

## Logs
N/A

### Version
`3.1.9-SNAPSHOT`  &   `3.2.x` 

### OS
Ubuntu

### Browser
`Chrome 84.0.4147.89` & `Firefox 78.0.2`

## Additional context
N/A

**Comment by rart** [comment]
> The error messages need to follow two rules:
> 1. If the user defines it as a _d or _f then it needs to allow a .
> 2. If the user puts a regex on the number then we should have a generic message about that. 
@jvega190

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.10-SNAPSHOT` 
![image](https://user-images.githubusercontent.com/6722074/95116162-d5e84f00-0703-11eb-8b3f-d160afb731d4.png)

**Comment by yacdaniel** [comment]
Verified fixed in `3.2.0-SNAPSHOT`
