### ISSUE TITLE
[studio] Page isn't loading in preview when going to a not restricted page from a restricted page with a unauthenticated SSO profile.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4236]
## Describe the bug
When a user tries to see a restricted page with a unauthenticated SSO user and then moves to a page that doesn't have restriction, the page is not loading in preview. 

## To Reproduce
1. Set up Profile with SSO to a site in Studio
2. In Sutdio configure URL restrictions to a page.
3. Preview the restricted page
4. In Sidebar click any page that is not restricted

## Expected behavior
The user should be able to preview the not restricted page. 

## Screenshots
Restricted content is in `articles/**`
Notice how clicking the `Edit`button shows the form content from `Styles` page when isn't visible in Preview. 
![previewSSOError](https://user-images.githubusercontent.com/6722074/89438692-5be91900-d706-11ea-8712-d369133329fd.gif)

## Logs
N/A

### Version
`3.1.9-SNAPSHOT` & `3.2.x`

### OS
Ubuntu

### Browser
Firefox & Chrome

## Additional context
N/A

**Comment by sumerjabri** [comment]
In Studio, you should use Targeting to validate use-cases and not use real SSO within Preview.
