### ISSUE TITLE
[studio] monitor-content.json api only returns the value of the last monitor for the site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4240]
## Describe the bug
The `monitor-content.json` api only returns the value of the last monitor for the site.
The website editorial has multiple monitors defined, When you send the `monitor-content` request, the monitors are working based on the tomcat logs but the response of the request only returns the value for the last monitor defined in site configuration. 

## To Reproduce
1. Create a site using website editorial.  In the `Page -Article` content type, add a `Date/Time` control with the name set  `expired_dt`
<img width="1589" alt="Screen Shot 2020-08-07 at 8 29 42 AM" src="https://user-images.githubusercontent.com/25483966/89653611-553cdc00-d895-11ea-8d03-d85209a9135f.png">

2. Look at the monitors defined by opening the `Sidebar` then clicking on `Site Config` -> `Configuration` -> `Site Configuration`.  There's a monitor for `Content Expiring Tomorrow` which is listed as the first monitor
```
<contentMonitoring>
        <monitor>
            <name>Content Expiring Tomorrow</name>
            <query>expired_dt:[now+1d/d TO now+2d/d]</query>
            <paths>
                <path>
                    <name>All Site</name>
                    <pattern>/site/.*</pattern>
                    <emailTemplate>contentExpiringSoon</emailTemplate>
                    <emails>admin@example.com</emails>
                    <locale>en</locale>
                </path>
            </paths>
        </monitor>
        <monitor>
            <name>Content Expiring In One Week</name>
            <query>expired_dt:[now+7d/d TO now+8d/d]</query>
            ...
</contentMonitoring>
```

3. Edit an article and set the `Expired_dt` to the next day (in the example below, the date today is 8/7, so the `Expire Date` is set to 8/8/2020

![Screen Shot 2020-08-07 at 10 04 46 AM](https://user-images.githubusercontent.com/25483966/89653724-82898a00-d895-11ea-9779-2e527978374c.png)

4. Send the `monitor-content.json` request `http://localhost:8080/studio/api/1/services/api/1/site/monitor-content.json` and notice the response given does not list the article we set to expire the next day:
```
[{"siteId":"onesite","contentMonitoring":{"monitors":[]}}]
```
5. Look at the tomcat log and notice that all the monitors were processed and the article we set to expire tomorrow is found:
```
[INFO] 2020-08-07T09:57:25,295 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring Tomorrow
[INFO] 2020-08-07T09:57:25,303 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring Tomorrow) found 2 items
[INFO] 2020-08-07T09:57:25,303 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor: Content Expiring Tomorrow Sending notification (contentExpiringSoon)
[INFO] 2020-08-07T09:57:25,310 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In One Week
[INFO] 2020-08-07T09:57:25,316 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In One Week) found 0 items
[INFO] 2020-08-07T09:57:25,318 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In One Month
[INFO] 2020-08-07T09:57:25,324 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In One Month) found 0 items
[INFO] 2020-08-07T09:57:25,326 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In Two Months
[INFO] 2020-08-07T09:57:25,331 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In Two Months) found 0 items
```
6. Open the `Site Configuration` again and move the `Content Expiring Tomorrow` monitor at the end of the monitors list
```
<contentMonitoring>
        
        <monitor>
            <name>Content Expiring In One Week</name>
            <query>expired_dt:[now+7d/d TO now+8d/d]</query>
       ...
       <monitor>
            <name>Content Expiring Tomorrow</name>
            <query>expired_dt:[now+1d/d TO now+2d/d]</query>
            <paths>
                <path>
                    <name>All Site</name>
                    <pattern>/site/.*</pattern>
                    <emailTemplate>contentExpiringSoon</emailTemplate>
                    <emails>admin@example.com</emails>
                    <locale>en</locale>
                </path>
            </paths>
        </monitor>
    </contentMonitoring>
```

7. Send the `monitor-content.json` request `http://localhost:8080/studio/api/1/services/api/1/site/monitor-content.json` and notice the response given now lists the article we set to expire the next day:
```
[{"siteId":"onesite","contentMonitoring":{"monitors":[{"name":"All Site","emails":"admin@example.com","items":[{"id":"/site/website/articles/2016/12/top-books-for-young-women/index.xml","internalName":"Top Books For Young Women","url":"http://localhost:8080/preview/#/?page=/articles/2016/12/top-books-for-young-women&site=onesite"}]}]}}]
```

The tomcat log shows all monitors were executed:
```
[INFO] 2020-08-07T09:58:10,725 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In One Week
[INFO] 2020-08-07T09:58:10,730 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In One Week) found 0 items
[INFO] 2020-08-07T09:58:10,731 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In One Month
[INFO] 2020-08-07T09:58:10,736 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In One Month) found 0 items
[INFO] 2020-08-07T09:58:10,738 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring In Two Months
[INFO] 2020-08-07T09:58:10,750 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring In Two Months) found 0 items
[INFO] 2020-08-07T09:58:10,752 [http-nio-8080-exec-2] [impl.GroovyScript] | executing monitor: Content Expiring Tomorrow
[INFO] 2020-08-07T09:58:10,757 [http-nio-8080-exec-2] [impl.GroovyScript] | content monitor (Content Expiring Tomorrow) found 2 items
```

## Expected behavior
`content-monitor.json` should return all the monitors with values

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.9-SNAPSHOT-32e609
Build Number: 32e609104f820218acb517e52e8b323d7a029efa
Build Date/Time: 08-05-2020 10:45:34 -0400

### OS
macOS

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2120
https://github.com/craftercms/studio/pull/2121

**Comment by alhambrav** [comment]
Verified fixed.
