### ISSUE TITLE
[engine] Preview proxy fails behind load balancers

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4242]
## Describe the bug
After the work done in https://github.com/craftercms/craftercms/issues/4234 the preview proxy now receives the real URL of the server instead of the URL of the proxy causing a loop when rendering.

To avoid having to know the URL of each server the Proxy will be update to:

1. Execute requests as local if the `<url>` element is missing or empty for a `<server>`
2. Execute requests as local if no matching `<server>` is found

**Comment by jdrossl** [comment]
@avasquez614 please validate

**Comment by avasquez614** [comment]
Validates, but we still need to add an upgrade manager processor to replace all `<url>http://localhost:8080</url>` with `<url></url>`

**Comment by avasquez614** [comment]
Verified
