### ISSUE TITLE
[studio-ui] Add list of sites a user belongs to when viewing a user

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4251]
When viewing a user, the following information is listed: 
![Screen Shot 2020-08-18 at 10 47 20 AM](https://user-images.githubusercontent.com/25483966/90554987-a639b380-e164-11ea-9607-c9bb5f0aad78.png)

- if user is enabled
- if user is externally managed
- first name of user
- last name of user
- email of user
- username

It would be nice to have the list of sites a user belongs to when viewing a user like below:

![Screen Shot 2020-08-18 at 10 46 18 AM](https://user-images.githubusercontent.com/25483966/90553878-16dfd080-e163-11ea-94f6-4bbedd37cdd7.png)

**Comment by sumerjabri** [comment]
Done
