### ISSUE TITLE
[studio] Workflow notification duplicates content items

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4255]
## Describe the bug
The workflow notifications that tell publishers and reviewers that content items are ready for review/publishing lists items in duplicate.

## To Reproduce
Use the following template for the workflow notification:
```
<ul> 
<#list files as file> 
<#if file.page> 
<a href="${liveUrl}/${file.browserUri!""}"> 
</#if> 
<li>${file.internalName!file.name}</li> 
<#if file.page> 
</a> 
</#if> 
</#list> 
</ul>
```
1. Edit multiple content objects
2. Submit them to workflow
3. See that email notice duplicates links to items (requires SMTP to be configured)

## Expected behavior
Email notification for content items that are ready for review and publishing should only list the items once, not as duplicated items. 

## Screenshots
![Screen Shot 2020-08-19 at 11 44 27 AM](https://user-images.githubusercontent.com/169432/91332872-cbe53f00-e79a-11ea-9162-b1309ca1e885.png)

## Logs
N/A

### Version
```
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 05-07-2020 17:31:21 -0400
```

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by russdanner** [comment]
Closed because it is a duplicate.
