### ISSUE TITLE
[studio] Upgrade from 3.1.9 to 4 fails

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4258]
## Describe the bug
There is an error related to a db script during the upgrade

## To Reproduce
1. Try to upgrade a db from 3.1.9 to 4

## Expected behavior
The upgrade should complete without errors

## Logs
https://gist.github.com/jdrossl/aa77d795c63ce64f6b3251e6ff894910

### Version
4.0.0-SNAPSHOT

### OS
Linux

### Browser
Chrome

**Comment by jdrossl** [comment]
@yacdaniel please help validate

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/4993
