### ISSUE TITLE
[studio-ui] improve NEXT SingleFileUpload with additional points of extension

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4260]
**Is your feature request related to a problem? Please describe.**
The Single File upload dialog/framework has two limitations:
1. There is no hook on beforeUpload where a caller can inject an inspection of the file type, name etc and make changes or cancel the action.
2. The onComplete method does not return any information from the server.  The server returns a JSON object that contains the file name, size and other data but this is not returned by the dialog to the caller.  If the server changes the name or creates renditions etc these are not shared with the caller.  In the case of a filename change by the server, the front end currently reports the original (and now incorrect) file

**Describe the solution you'd like**
- Add a beforeUpload style method that allow the caller to insert inspection (ability to see the filename and type about to be uploaded), the ability to potentially change that file name and the ability to cancel the upload action if needed.

- Include whatever information comes from the server in the callback response from the dialog.

- If the server, for any reason changes the file name, communicate the new name as the filename in the current  response object

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sumerjabri** [comment]
Policy Engine fixes this.
