### ISSUE TITLE
[search] Disable date detection in Elasticsearch

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4262]
By default Elasticsearch will try to convert fields into dates if the value matches a valid pattern, this could cause conflicts during indexing. https://www.elastic.co/guide/en/elasticsearch/reference/6.8/dynamic-field-mapping.html#date-detection

This feature should be disabled for all indexes.

**Comment by jdrossl** [comment]
@avasquez614 please verify

**Comment by avasquez614** [comment]
Verified
