### ISSUE TITLE
[studio-ui] Save and Close fails due to race condition with the TinyMCE5 RTE

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4263]
## Describe the bug
When Editing a page in Crafter Studio that contains an RTE and clicking Save & Close, there is a race condition between the loading of the contents of the RTE and the Save & Close functionality.

## To Reproduce
1. Edit a page that contains an RTE
2. As soon as the Page Editor pops up, click Save & Close
3. The following may happen: The page editor will be stuck and not save the page changes, and the two Save buttons will be blurred thus having to click cancel and remove changes. 
4. Repeat the process and/or emulate slower network or server response times until error occurs.

## Expected behavior
When making edits to a page, the clicking of Save & Close should save the changes and close the page editor dialogue.
User should not be able to click Save and Close or Save as Draft until the form is completely initialized and ready to go.

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/91588357-03342700-e926-11ea-8b22-4564fc06484c.png)
![image](https://user-images.githubusercontent.com/42217570/91588441-2b238a80-e926-11ea-950e-6720bc36675a.png)

## Logs
```
Uncaught TypeError: Cannot read property 'getContent' of undefined
    at CStudioForms.Controls.RTETINYMCE5.save (rte-tinymce5.js?version=52d02e1794c9a4ed8f51d662ea1d79e71e9b9a06:678)
    at Object.callback.beforeSave (rte-tinymce5.js?version=52d02e1794c9a4ed8f51d662ea1d79e71e9b9a06:408)
    at CStudioForm.onBeforeSave (forms-engine.js?version=52d02e1794c9a4ed8f51d662ea1d79e71e9b9a06:646)
    at saveFn (forms-engine.js?version=52d02e1794c9a4ed8f51d662ea1d79e71e9b9a06:1269)
    at HTMLInputElement.saveButtonEl.onclick (forms-engine.js?version=52d02e1794c9a4ed8f51d662ea1d79e71e9b9a06:1625)
```

## Specs
Heading

### Version
```
Studio Version Number: 3.1.6E-e181c7
Build Number: e181c736065cb24309a3963dde947884465b8d32
Build Date/Time: 05-07-2020 17:31:21 -0400
```

### Browser
Any

## Additional context
N/A

**Comment by russdanner** [comment]
Confirmed
