### ISSUE TITLE
[commons] Upgrade manager is not updating all versions in the pipelines

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4264]
## Describe the bug
After the refactor done in https://github.com/craftercms/craftercms/issues/3801 it has been pointed out that the upgrade manager should write every version in the pipeline instead of only the last one.

## Expected behavior
The UM should track all versions in the pipelines to properly resume upgrades after errors

### Version
3.2-SNAPSHOT

**Comment by jdrossl** [comment]
@yacdaniel please help validate

**Comment by yacdaniel** [comment]
Verified fixed.
