### ISSUE TITLE
[studio] The system continuously generating an error on content-types/pages/config.xml file

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#427]
Studio continues to generate the following error message while there shouldn't be config.xml at the location.

[ERROR] 2017-01-26 10:35:58,889 [ajp-nio-7009-exec-8] [configuration.ContentTypesConfigImpl] | No content type configuration document found at /cstudio/config/sites/marriott/content-types/pages/config.xml

**Comment by russdanner** [comment]
changed message to debug

**Comment by hlim** [comment]
confirmed the fix. thanks
