### ISSUE TITLE
[craftercms] [studio] Can't restore backup because of missing crafter user

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4274]
## Describe the bug
Studio can't start after the restore of the backup because the `crafter` (`MARIADB_USER`) user doesn't exist.

## To Reproduce
1. Start Authoring
2. Create a simple site based on the editorial BP
3. Run `./bin/crafter.sh backup` to backup Crafter
4. Stop Authoring
5. Run `./bin/crafter.sh restore BACKUP_PATH`
6. Start Authoring

Studio will not be able to start and you will see the following error in the logs:

```
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'crafter'@'localhost' (using password: YES)
```

## Expected behavior
Studio should be able to start normally after a restore. There are 2 options to solve this:

1. Backup the users of the DB
2. Create the SQL user specified by the `MARIADB_USER` variable if it doesn't exist.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/4283
https://github.com/craftercms/craftercms/pull/4284

**Comment by avasquez614** [comment]
Verified
