### ISSUE TITLE
[studio-ui] My Sites menu actions buttons to go to Site Config / Dashboard doesn't work. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4276]
## Describe the bug
The actions button to go to the Dashboard/Site Config in the new My Sites menu is not working. User is always taken to the current site Dashboard/Site Config. 

## To Reproduce
1. Create 2 sites
2. Go to the Dashboard of 1 site, click the Crafter user settings in the top right
3. In `My Sites` click the action buttons of the 2nd site then click Dashboard

## Expected behavior
User goes to the Dashboard/Site Config of the selected site.

## Screenshots
![sites menu](https://user-images.githubusercontent.com/6722074/92154663-6240e280-ede3-11ea-84b2-1e429826127e.gif)

## Logs
N/A

### Version
`3.2.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by rart** [comment]
Done.

**Comment by yacdaniel** [comment]
Verified fixed.
