### ISSUE TITLE
[engine] Application Context overrides are loaded in the wrong order

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#4278]
## Describe the bug
According to docs: 
- https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-multi-target-configuration.html
- https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-multi-environment-configuration.html

`application-context.xml` can be overridden depending on the publishing target and environment, so priority would be most specific first.
e.g.: if the following files exist:
- application-context.xml
- application-context.preview.xml

Then `application-context.xml` would be used for **live** target. And application-context.preview.xml would be used for **preview**.

## To Reproduce
1. Add different application-context files. e.g.:
- application-context.xml
- application-context.preview.xml
1. Verify `application-context.xml` is always the one used, even for **preview** target

## Expected behavior
`application-context.xml` is the loaded for non-preview targets, but is overridden by `application-context.preview.xml` on **preview**

The actual file being loaded can be easily verified by introducing some syntax error in the xml

### Version
We used docker images based on
- craftercms/authoring_tomcat_solr_compatible:3.1.9E_BYOL
- craftercms/delivery_tomcat_solr_compatible:3.1.9E_BYOL

Actual engine is an overlay of Crafter 3.1.9E

**Comment by jdrossl** [comment]
@yacdaniel please help validate

**Comment by yacdaniel** [comment]
Thanks for the report @jmendeza The issue is fixed and should be available as part of the upcoming Crafter CMS release: `3.1.10`
