### ISSUE TITLE
[studio] debug level logging from ContentSerivceImpl prints stacktraces

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#428]
Changing log level to debug on ContentSerivceImpl prints the following stacktrace making log hard to read:

`[DEBUG] 2017-01-26 13:55:27,261 [ajp-nio-7009-exec-1] [content.ContentServiceImpl] | Stack trace (depth 20):
	org.craftercms.studio.impl.v1.service.content.ContentServiceImpl.getContentItem(ContentServiceImpl.java:1330)
	org.craftercms.studio.impl.v1.service.content.ContentTypeServiceImpl.getContentTypeForContent(ContentTypeServiceImpl.java:53)
	org.craftercms.studio.impl.v1.service.security.SecurityServiceImpl.getUserPermissions(SecurityServiceImpl.java:133)
	org.craftercms.studio.api.v1.service.security.SecurityService$getUserPermissions$1.call(Unknown Source)
	scripts.api.impl.security.SpringSecurityServices.getUserPermissions(SpringSecurityServices.groovy:36)
	scripts.api.impl.security.SpringSecurityServices$getUserPermissions$0.call(Unknown Source)
	scripts.api.SecurityServices.getUserPermissions(SecurityServices.groovy:62)
	scripts.api.SecurityServices$getUserPermissions$2.call(Unknown Source)
	get-user-permissions_get.run(get-user-permissions.get.groovy:54)
	groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:589)
	org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
	org.craftercms.engine.controller.rest.RestScriptsController.executeScript(RestScriptsController.java:131)
	org.craftercms.engine.controller.rest.RestScriptsController.handleRequestInternal(RestScriptsController.java:83)
	org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
	org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)`

This should be at the trace level.

**Comment by russdanner** [comment]
removed debug utils from class

**Comment by hlim** [comment]
confirmed the fix
