### ISSUE TITLE
[studio] Deployment error when a site is created using the same site id of a site that was previously removed

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4282]
## Describe the bug
Studio fails to do the initial deploy sync content when a site is created using the same site id of a site that was previously removed. 

## To Reproduce
1. Create a site from any BP
2. Remove the site
3. Create a new site from any BP using the same site id as Step 1
4. See error in tomcat log

## Expected behavior
No errors when site is created.

## Screenshots
N/A

## Logs
https://gist.github.com/yacdaniel/60aee7068c93d28aa7a2aff458a656e9

Email notification received
```
Deployment error on site empty01

 The following content was unable to deploy:

Error:
org.springframework.jdbc.BadSqlGrammarException: ### Error querying database. Cause: java.sql.SQLSyntaxErrorException: (conn:18) Result consisted of more than one row Query is: call tryLockPublishingForSite(?, ?, ?,?), parameters ['empty01','localhost/127.0.0.1',180,] ### The error may exist in org/craftercms/studio/api/v1/dal/SiteFeedMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: call tryLockPublishingForSite(?, ?, ?,?) ### Cause: java.sql.SQLSyntaxErrorException: (conn:18) Result consisted of more than one row Query is: call tryLockPublishingForSite(?, ?, ?,?), parameters ['empty01','localhost/127.0.0.1',180,] ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn:18) Result consisted of more than one row Query is: call tryLockPublishingForSite(?, ?, ?,?), parameters ['empty01','localhost/127.0.0.1',180,] 
```

### Version
`3.1.x` and `3.2.x`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2174
https://github.com/craftercms/studio/pull/2175

**Comment by yacdaniel** [comment]
Verified fixed.
