### ISSUE TITLE
[studio] Cut/Paste doesn't update timestamp on user activity

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#429]
Steps to reproduce

1) Create a content
2) Publish the content
3) Create another content
4) Publish the 2nd content
3) Cut/paste the first content to another location

The first content's state will change to 'Edited' but will still remain in the same order although it's the latest item modified. The activity timestamp won't change either.

**Comment by russdanner** [comment]
Added post activity to the update method

**Comment by hlim** [comment]
failed testing due to not inserting the correct contentType value.

**Comment by hlim** [comment]
tested and confirmed
