### ISSUE TITLE
[studio] Deleting an asset, deletes the siblings and parent folder

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4290]
## Describe the bug
When I delete a file in asset folder, the whole folder is deleted.
I created new folder -> upload 4 files -> delete 1 file -> reload -> whole folder with all 4 files are deleted

## To Reproduce
1. Go to 'Studio Dasboard'
2. Click on 'Static assets'
3. Create new folder `/static-assets/test`
4. Upload some files to folder `/static-assets/test`
5. Delete 1 file

## Expected behavior
Only 1 file is deleted

## Screenshots
Please refer to my video
https://craftercms.slack.com/files/UPZ2DRWBY/F01AHSMRL9Y/preview_-_crafter_cms.mp4

### OS
MacOS/Unix

### Browser
Chrome

## Additional context
It seem we have a check: If it is a file, then delete parent folder:
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/repository/git/GitContentRepository.java#L392

This may cause the bug

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2177

**Comment by phuongnq** [comment]
Thank you.
I checked the fix.

**Comment by yacdaniel** [comment]
@dejan-brkic  When we have a folder with only one item(assets, page, components, any content) and we delete the item the folder is also deleted.  We shouldn't delete the folder in this case. 

Look how `folder1` is deleted when we delete the content inside the folder.  
![delete](https://user-images.githubusercontent.com/6722074/93258254-40d4e480-f75b-11ea-8170-999b787935f4.gif)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2187
https://github.com/craftercms/studio/pull/2188

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.10`

**Comment by yacdaniel** [comment]
Verified fixed.
