### ISSUE TITLE
[craftercms] Detect when the DB is up on restore

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4295]
On slower systems, restore sometimes fails because the DB takes longer to start up than the expected 30 seconds. These expected 30 seconds can be found here https://github.com/craftercms/craftercms/blob/support/3.1.x/resources/bin/crafter.sh#L835 and here https://github.com/craftercms/craftercms/blob/support/3.1.x/resources/bin/crafter.sh#L1118. See if it's possible to detect when the DB has finished starting up, but if not possible, make this value configurable as an env variable.

**Comment by sumerjabri** [comment]
Configure this to sleep for 120 seconds in 3.1.x and address this with a DB detect in 3.2.x

**Comment by avasquez614** [comment]
Verified
