### ISSUE TITLE
[studio] Support file name and type policies

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4298]
**Is your feature request related to a problem? Please describe.**
File's uploaded by authors often have file names that are improper for web use because the contain spaces and other special characters.  Further organizations want the ability to restrict the types of files that are uploaded to their system.

**Describe the solution you'd like**
Add an ability to configure policies / rules for file names and policies to a site.  This would allow an administrator to quickly and easily manage policies independently from content type form controls and data sources.

**Describe alternatives you've considered**
Add rules to form control and data sources. The issue is that this is difficult to manage and does not cover direct upload via Sidebar, Drag-drop, etc

**Additional context**
N/A

**Comment by sumerjabri** [comment]
Done
