### ISSUE TITLE
[docs]System Administrators/ Documentation incomplete of Configure Studio with Alfresco 

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#430]
The user should be following this documentation http://docs.craftercms.org/en/stable/system-administrators/prod-environment/configure-studio-with-alfresco.html?highlight=alfresco, but is necessary more steps to run crafter-alfresco on local environment. 

This documentation need: 
Note: Studio and Alfresco should be use a different ports.

1. More details about the alfresco install, port used and take a note the port assigned.(for example port 8080) 
2. Go to file "server.xml" ../apache-tomcat/conf and edit the port. (for example the port 9080)
3. Go to file "server-config.properties" on ../apache-tomcat/shared/classes/crafter/cstudio/extension and use the port of the step 2 on the following line:
 
crafter.engine.search.server.url=http://localhost:9080/crafter-search

4. Go to file "server-config.properties" on ../apache-tomcat/shared/classes/crafter/engine/extension and use the port of the step 2 on the following line:

crafter.engine.search.server.url=http://localhost:9080/crafter-search

5. Go to file "server-config.properties" on ../apache-tomcat/shared/classes/crafter/search/extension and use the port of the step 2 on the following line:

crafter.search.solr.server.url=http://localhost:9080/solr-crafter

please add this information and the expected result should be the crafter-alfresco running properly when the user go to url: http://localhost:9080/studio/

**Comment by sumerjabri** [comment]
This is 2.5.x doc only.

@russdanner route back to me if you can't handle.
