### ISSUE TITLE
[studio][engine] Update tomcat session cookies to set httpOnly on session cookie

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4300]
**Is your feature request related to a problem? Please describe.**
Currently it's possible to look up the session ID with javascript which could potentially be used in a XSS 

**Describe the solution you'd like**
Add the following snippet to Web.xml
```
<session-config>
    <cookie-config>
        <http-only>true</http-only>
    </cookie-config>
</session-config>
```
**Describe alternatives you've considered**

**Additional context**

**Comment by jdrossl** [comment]
@russdanner both session cookies seem to already have the `httpOnly` flag set to `true`

![Screenshot from 2020-09-16 16-41-16](https://user-images.githubusercontent.com/1236955/93399780-79e48600-f83b-11ea-96d3-3ab736cb9225.png)

**Comment by russdanner** [comment]
Confirmed
