### ISSUE TITLE
[studio-ui] History dialog UI breaks with very long item names

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4301]
## Describe the bug
Showing History component of a file with long name (255 characters).

## To Reproduce
1. Go to 'Dashboard'
2. Click on 'Upload' to upload a static file with long name (255 characters)
3. Click on 'History' menu

## Expected behavior
File name should be wrapped in Content Item History view

## Screenshots
![Screen Shot 2020-09-17 at 10 22 33](https://user-images.githubusercontent.com/2996543/93485439-08d9c700-f93e-11ea-91a2-98190e5b07ca.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
3.2.0 (develop branch)

### OS
{{What OS did you use to produce the bug.}}

### Browser
Chrome

## Additional context
Using `overflow-wrap: break-word;` seem fix this

**Comment by yacdaniel** [comment]
@aachavarria the issue seems fixed in the history dialog, but in the history item version & compare version we have text sections not aligned in the dialog. 
![historyDetailsCompare](https://user-images.githubusercontent.com/6722074/93617876-c5aa4300-f993-11ea-8b9a-c3f8ddd1f59c.gif)

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/96312651-44ad8e00-0fc9-11eb-986b-ea3d3b8f2301.png)
