### ISSUE TITLE
[studio-ui] Delete dialog submit fails with large submission comments

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4302]
## Describe the bug
While deleting asset we can input a comment.
If the text is long enough, an error is showing but there is no hint for user.

## To Reproduce
1. Go to 'Dashboard'
2. Click on 'static-asset'
3. Select an image then click delete menu
4. Input a text of 4000 characters in comment

## Expected behavior
Showing error message if the text too long

## Screenshots

![Screen Shot 2020-09-17 at 23 36 28](https://user-images.githubusercontent.com/2996543/93486228-e85e3c80-f93e-11ea-872e-f8e128b6bb5a.png)

![Screen Shot 2020-09-17 at 23 36 13](https://user-images.githubusercontent.com/2996543/93486215-e4321f00-f93e-11ea-8f22-4b5716cd8469.png)

### Version
3.2 (develop branch)

### OS
MacOS/Unix

### Browser
Chrome

## Additional context
Do we have a spec for text limitation?

**Comment by rart** [comment]
@jvega190 please add helper text below the field: 
[left] Max {max} characters   --------   {current}/{max} [right]
Need to verify if it's an issue of the post or the API or both.

Confirm max length with @dejan-brkic.

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for verification

**Comment by phuongnq** [comment]
verified
