### ISSUE TITLE
[studio] Restoring a backup (with the users not backed up) fails

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4308]
## Describe the bug
Restoring a backup (from a version with the users not backed up) fails

## To Reproduce
1. Create a backup using an earlier version of Crafter.  For our example, we'll use 3.1.8
2. Using the 3.1.10 snapshot version of Crafter, restore the backup created using 3.1.8
3. Notice the error message `./crafter.sh: line 1126: /Users/vita/temp/test3/craftercms/crafter-authoring/mybackups/temp/users.sql: No such file or directory`

## Expected behavior
The restore should work

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
2020-09-22 10:42:36.717  INFO 78765 --- [           main] ch.vorburger.mariadb4j.DB                : Database startup complete.
2020-09-22 10:42:37.032  INFO 78765 --- [           main] c.v.m.s.boot.MariaDB4jApplication        : Started MariaDB4jApplication in 4.989 seconds (JVM running for 5.485)
------------------------------------------------------------------------
Restoring embedded DB
------------------------------------------------------------------------
./crafter.sh: line 1126: /Users/vita/temp/test3/craftercms/crafter-authoring/mybackups/temp/users.sql: No such file or directory
Unable to continue, an error occurred or the script was forcefully stopped
```

### Version
3.1.10 snapshot

### OS
OS X

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/4310
https://github.com/craftercms/craftercms/pull/4311

**Comment by alhambrav** [comment]
Verified fixed.
