### ISSUE TITLE
[Authoring][ElasticSearch] indexing for svg and video mime-type

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4313]
## Describe the bug
ES does not index for Video files and SVG files

## To Reproduce
1. Update crafter-authoring/bin/crafter-deployer/config/base-target.yaml
2. Add mime-types as following
  search:
    indexing:
      binary:
        authoring:
          supportedMimeTypes:
          - image/*
          - video/*
          - text/*
          - font/*
          - application/*

## Expected behavior
SVG and Video files are indexed and can be seached

### Version
3.2 develop branch

### OS
MacOS

### Browser
Chrome/PostMan

**Comment by jdrossl** [comment]
@phuongnq could you please provide more info about the format of the videos and the size of the files you are trying to index? The issue might be that we are not detecting the mime types correctly (it is based on the file extension) or that files exceed the size limit (by default 100 mb)

**Comment by phuongnq** [comment]
Hi @jdrossl It seems the file size of 100mb cause the issue.
I reindexing and seems fixed.!
