### ISSUE TITLE
[studio] Duplicate SQL entry errors are thrown on "rename" operation

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4314]
## Describe the bug
Errors in the tomcat logs point to an issue with the SQL database containing duplicate entries for the content of the site. These errors should not be outputted as the operation that produces this is a valid operation. 

## To Reproduce
1. Create a new site based on the editorial blueprint
2. Open the site config
3. Edit the content type for the "Page - Home"
4. Uncheck the "read-only" box from the Page URL configuration on the right-hand side of the page. 
5. Go back and edit the home page
6. Change the page URL from '/' to 'test'
7. Review the tomcat logs located at CRAFTER_HOME/logs/tomcat/catalina.out for the duplicate entry SQL Error.

## Expected behavior
The errors should not be reported after performing this valid operation.

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/94192480-00711700-fe7d-11ea-9647-e0c26eae1354.png)

## Logs
[Duplicate Entries SQL Error.txt](https://github.com/craftercms/craftercms/files/5278767/Duplicate.Entries.SQL.Error.txt)

### Version
```
Studio Version Number: 3.1.9E-43a860

Build Number: 43a8609f0d95e42fcab3bd46994df9eea125dc4b

Build Date/Time: 08-20-2020 17:41:16 -0400
```

### OS
N/A

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
@russdanner we don't support renaming of the homepage descriptor. Please ping me to discuss options.

**Comment by sumerjabri** [comment]
Reproducible on first-level folders. Please look into it @dejan-brkic

**Comment by russdanner** [comment]
Renaming the /style page did not create the same SQL errors. We'll determine steps to reproduce below the root and re-assign once found.

**Comment by russdanner** [comment]
I cannot reproduce the issue for folders deeper that a rename of / and we do not support rename of /
