### ISSUE TITLE
[studio] Update the publisher to handle null commit_ids

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4315]
Update the Studio Publisher to handle null commit_ids in the publish queue as follows:
* If the item has a null commit ID, pick up HEAD and check for file presence, if present, publish that, otherwise publish nothing
* Log the null commit ID as INFO so we're aware of what happened

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2194
https://github.com/craftercms/studio/pull/2195

**Comment by sumerjabri** [comment]
Please also address the issue:
* Commit ID is present but doesn't exist in the Git repo AND file exists, in which case WARN and then publish HEAD
  * This makes the logic: If commit_id is null or doesn't exist in git AND file exists, then warn and publish head, otherwise ignore
* The WARN message for NULL or invalid commit ID should include the text "Was the git repo reset at some point?"

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2198
https://github.com/craftercms/studio/pull/2199

**Comment by sumerjabri** [comment]
@russdanner I tested with NULL commit ID in item_metadata and NULL commit ID in publish_request. It behaved correctly in both cases.

**Comment by russdanner** [comment]
Tested publish to live looks good.
```
[INFO] 2020-10-06T13:07:33,352 [Studio_Publisher_Thread_Pool10] [site.SiteServiceImpl] | Last commit ID for site: editorial is 0c54525ba1f4eede4313705e8b420dea4dde4f6c 
[WARN] 2020-10-06T13:08:29,477 [http-nio-8080-exec-4] [deployment.DeploymentServiceImpl] | Commit ID null does not exist for content /site/website/style3/index.xml. Was the git repo reset at some point? 
[INFO] 2020-10-06T13:08:29,478 [http-nio-8080-exec-4] [deployment.DeploymentServiceImpl] | Publishing content from HEAD for /site/website/style3/index.xml 
[INFO] 2020-10-06T13:08:33,257 [Studio_Publisher_Thread_Pool8] [job.PublisherTask] | Starting publishing on environment live for site editorial 
[INFO] 2020-10-06T13:08:33,669 [Studio_Publisher_Thread_Pool8] [job.PublisherTask] | Finished publishing environment live for site editorial 
```
Trying staging direct and live with staging

**Comment by russdanner** [comment]
@dejan-brkic 
I don't think I am getting the same messages for staging
```
 result of: true 
[INFO] 2020-10-06T13:51:23,312 [Studio_Publisher_Thread_Pool6] [site.SiteServiceImpl] | Last commit ID for site: editorial is 26a95ec354e840fe6508d38f4e313b41f4211dbc 
[INFO] 2020-10-06T13:51:23,320 [Studio_Publisher_Thread_Pool6] [job.PublisherTask] | Starting publishing on environment live for site editorial 
[INFO] 2020-10-06T13:51:24,128 [Studio_Publisher_Thread_Pool6] [job.PublisherTask] | Finished publishing environment live for site editorial 

```

**Comment by russdanner** [comment]
Other cases that look good.
- Publish to live through staging
- Publish new with null
- Publish a rename with null
