### ISSUE TITLE
[studio] Prevent null commit ID items from being inserted into the new Item table

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4316]
Check for null commit ID and try to figure out the reason for the null commit ID.

Ping me to discuss findings and design to address this.

**Comment by sumerjabri** [comment]
Per Dejan:
* Identified as `git` sourced
* Fixed by assigning HEAD as the commit ID

Dropping priority and will continue to track to make sure it's resolved.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2643
