### ISSUE TITLE
[studio][studio-ui] Increase Group name length

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4319]
**Is your feature request related to a problem? Please describe.**
We are using group for each site, with format `<site-name>_xxxxx`.
If site-name is long, then group cannot be created.

**Describe the solution you'd like**
We would like to have longer group name. 

As current: 32 characters
Expected: 512 characters.

The reason for 512 is <site-name> has 255 character. We would like to have more for group name.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2201

**Comment by dejan-brkic** [comment]
Develop:
https://github.com/craftercms/studio/pull/2203

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by yacdaniel** [comment]
@jvega190 the Groups and Groups details screens are not responsive. UI breaks with long group names. 
![image](https://user-images.githubusercontent.com/6722074/95136802-09d36c80-0724-11eb-9297-e5a06a0d0903.png)
![image](https://user-images.githubusercontent.com/6722074/95136823-135cd480-0724-11eb-84d2-90b490da669d.png)

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.10`

**Comment by yacdaniel** [comment]
@jvega190 could you also fix responsiveness for the group description? Thanks. 
![image](https://user-images.githubusercontent.com/6722074/95878360-5d504680-0d32-11eb-842c-e649eef13052.png)

**Comment by yacdaniel** [comment]
Verified fixed.
