### ISSUE TITLE
[studio-ui] Fix base path for Studio 3 configuration files

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#432]
Starting Studio 3, we keep the site's config along with the site. As such, please do the following:

1. Extract the base path "/cstudio/config/sites/<my_site>/" to be a constant
2. Change that to "?site=<my_site>&path=/config/studio/" for example: "?site=new_site&path=/config/studio/content-types/page/entry/..."

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/221
