### ISSUE TITLE
[studio-ui] TinyMCE 5 does not escape HTML

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4320]
**Is your feature request related to a problem? Please describe.**
When adding HTML code to a TinyMCE 5 RTE on any page in crafter studio, the HTML is rendered and not saved as its HTML content as it does in the TinyMCE 2 RTE. For example, if I entered the following HTML into an RTE 5 and saved/closed the page editor then reopened it. The following HTML would not be in its HTML form but instead its rendered form.
```
<ol><li>test html</li></ol>
```

**Describe the solution you'd like**
HTML added to an RTE 5 should not escape and instead be editable.

**Describe alternatives you've considered**
N/A

**Additional context**
Example of how the RTE 2 handles HTML when editing after a Save & Close vs the RTE 5
![image](https://user-images.githubusercontent.com/42217570/94819917-d7e1a380-03cd-11eb-8731-d619a94acf00.png)

**Comment by russdanner** [comment]
If this is easy (a config) I'd like to put it in the release.  We think it's a config but we were not able to figure out the exact configuration for it.  TinyMCE2 editor is doing the correct thing as stated so a more detailed comparison may provide the answer.

**Comment by jvega190** [comment]
@AndyReiter assigning it to you for verification

**Comment by russdanner** [comment]
Confirmed
