### ISSUE TITLE
[studio][studio-ui] Implement item search ahead on AddressBar component

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4323]
![image](https://user-images.githubusercontent.com/3928341/85778768-350cef80-b723-11ea-9b1b-3eeedec4335c.png)

## Search ahead
Being able to type a query and get results of things that match the terms. Could be a url or something that matches some other key page model fields (e.g. title, description)
![image](https://user-images.githubusercontent.com/3928341/92242454-16b03680-eec0-11ea-96bc-46a868c4c9ee.png)

**Comment by sumerjabri** [comment]
@jdrossl please see if there is a backend component for this.

**Comment by jdrossl** [comment]
@rart I think the existing search service can be used for this, take a look and if something is missing we can add it https://app.swaggerhub.com/apis/craftercms/studio_3_2/3.2.0.0#/search/search

If you think this service is not enough please provide an API spec

**Comment by aachavarria** [comment]
this depends of https://github.com/craftercms/craftercms/issues/3967
@sumerjabri

**Comment by sumerjabri** [comment]
Pending #3967
