### ISSUE TITLE
[studio] Rename operations leaves old items in published repo when item is renamed before it is ever published

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4328]
## Describe the bug
Rename operations leaves old items in published repo when item is renamed before it is ever published.

## To Reproduce
1. Create a site based on editorial
2. Rename the style page to style-2 and publish it, see style-2 show up in published repo
3.  Rename the style-2 page to style-3 and publish it, see style-2 and style-3 show up in published repo

## Expected behavior
The old path (in the case above, style-2, should be removed from the published repo

## Screenshots
N/A

## Logs
N/A

### Version
```Studio Version Number: 3.1.10-SNAPSHOT-ecfcc5
Build Number: ecfcc50cb0ee12edd414e5d35a2e99416b98cf7b
Build Date/Time: 10-05-2020 13:32:34 -0400
```

### OS
ANY

### Browser
ALL

**Comment by dejan-brkic** [comment]
Can not reproduce with steps describe above

**Comment by sumerjabri** [comment]
@russdanner I cannot reproduce either:
Publish style-2
```
$ ls crafter-authoring/data/repos/sites/ed2/published/site/website/
index.xml  style-2
```
Publish style-3 (after rename)
```
$ ls crafter-authoring/data/repos/sites/ed2/published/site/website/
index.xml  style-3
```

**Comment by yacdaniel** [comment]
@sumerjabri @russdanner @dejan-brkic we need some cut-paste operations to reproduce it, details below: 

1. Rename style to style-2
2. Cut Health and paste it under Style
3. Approve and Publish Health.
4. Rename style-2 to style-3
5. Cut Entertainment and paste it under Style
6. Approve and Publish Entertainment. 

![rename publish copy paste](https://user-images.githubusercontent.com/6722074/95213981-a4778e00-07ac-11eb-91eb-314ce38b980a.gif)

**Comment by russdanner** [comment]
I see @yacdaniel's finding as a bug. The current expectation that the Studio UI leaves the author with is that everything under Style is renamed. The fact that this assumption is not transmitted to published makes it such that the authoring and published reality can be wildly out of sync and there is no way of seeing how from an authors perspective.

We either need to update the publish behavior to be true to what's shown in studio OR show the un-renamed ites in the old location within authoring

**Comment by sumerjabri** [comment]
@russdanner please let me know the required schedule and priority of this issue.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2309
https://github.com/craftercms/studio/pull/2310

**Comment by russdanner** [comment]
Confirmed
