### ISSUE TITLE
[studio-ui] Update the UI to use the new User representation

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#433]
Please update Studio 3 to make use of an be compliant with:
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-user.html

Currently the UI fails with freemarker errors per the shared screen session. Example:
`----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${last_name}  [in template "templates/web/entry.ftl" at line 11, column 82]
----`

**Comment by jvega-crafter** [comment]
Fixed by Dejan
