### ISSUE TITLE
[studio-ui] Remove the "Forgot your password?" link in the Forgot your password dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4344]
**Is your feature request related to a problem? Please describe.**
From the login screen, click on the `Forgot your password?` link to have your password reset.  Notice the dialog for requesting to have your password reset has a link to `Forgot your password?`, which is the dialog that's already open

<img width="332" alt="Screen Shot 2020-10-09 at 10 19 48 AM" src="https://user-images.githubusercontent.com/25483966/95596841-e22e1e00-0a1b-11eb-8024-86aad4282a02.png">

**Describe the solution you'd like**
The `Forgot your password?` link should be removed from the dialog since this is where the user is supposed to send their request to reset the password.  It also makes the dialog less confusing.
Might be nice too to have a title in the dialog that it's for resetting their password, say `Forgot Password` or `Password assistance` (like in Amazon) or `Let's get you into your account` (Yahoo) or something like that.

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
https://github.com/craftercms/studio-ui/pull/1965
https://github.com/craftercms/studio-ui/pull/1966

**Comment by alhambrav** [comment]
Verified.
