### ISSUE TITLE
[studio][studio-ui] Add support in /api/2/audit for friendly site name.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4347]
## Describe the bug
Audit API 2 should be updated to return the name of a site. Studio UI should use the `name` instead of the `siteId` of a site.

## To Reproduce
1. Create a site, use differents value in `Site Name` and `Site ID`
2. Go to the site Audit page
3. See error

## Expected behavior
- [ ] BE should return in `auditLog.siteName` the new site name.

- [ ] UI should  shown the site name in the dropdown(Global Menu), or his own site name (Site Config) and send it as a parameter

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Site  `siteId: site-id-empty` and `name: site name empty`
* Audit log response 
```
    "auditLog": [
        {
            "id": 357,
            "organizationId": 1,
            "siteId": 4,
            "siteName": "site-id-empty",
            "operation": "CREATE",
            "operationTimestamp": "2020-10-13T16:37:59-06:00",
            "origin": "GIT",
            "primaryTargetId": "site-id-empty:/config/studio/context-nav/contextual-nav.xml",
            "primaryTargetType": "Content Item",
            "primaryTargetSubtype": "unknown",
            "primaryTargetValue": "/config/studio/context-nav/contextual-nav.xml",
            "actorId": "admin admin",
            "actorDetails": "admin admin",
            "clusterNodeId": "",
            "parameters": []
        },
```

* Site Config - Audit 
![image](https://user-images.githubusercontent.com/6722074/96017772-a0c8b480-0e07-11eb-91a1-96048c164687.png)

* Audit Global Menu 
![image](https://user-images.githubusercontent.com/6722074/96018227-36644400-0e08-11eb-84f9-02d132a5a330.png)

### Version
 `3.2.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
https://github.com/craftercms/craftercms/issues/4192

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2218

**Comment by yacdaniel** [comment]
@sumerjabri @rart we need UI changes here.

**Comment by yacdaniel** [comment]
Our API docs say
![image](https://user-images.githubusercontent.com/6722074/96745011-ded35480-1382-11eb-9de0-b7069bddf58a.png)
but `http://localhost:8080/studio/api/2/audit?siteName=siteid` accepts a `siteId` in the `siteName` parameter which is kind of confusing because now we have both `siteId` and `siteName`

**Comment by dejan-brkic** [comment]
@sumerjabri Docs and API were designed before adding a custom site name field on the create site dialog. The feature works fine now but docs and API are confusing

**Comment by sumerjabri** [comment]
Let's fix the API and UI:
- [ ] Make the API allow query by siteId (string) and siteName (string) (remove site numeric ID (DB))
- [ ] Make the UI use the appropriate API

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/2401

**Comment by yacdaniel** [comment]
Verified fixed.
