### ISSUE TITLE
[studio-ui] Sidebar event propagation between widgets seems not to work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4348]
## Describe the bug
If two Sidebar Widgets overlap in repository coverage (one widget covers /site/website/ and one widget covers /site/website/articles), and action is taken in one widget, the other widget doesn't show the action taken.

## To Reproduce
1. Create an Editorial BP site based on Editorial 2 (preview 2)
2. Edit the sidebar configuration to have two widgets as follows:
```xml
<!-- Path Navigator: Pages -->
<modulehook>
  <render>PagesWidget</render>
  <props>
    <title>Pages</title>
    <icon>fa fa-file-text-o</icon>
    <path>/site/website</path>
    <excludes><exclude>/site/website/articles</exclude></excludes>
    <locale>en</locale>
  </props>
  <container>
    <style>
      <padding-left>9px</padding-left>
    </style>
    <class>next-pages-widget</class>
  </container>
</modulehook>
<modulehook>
  <render>PagesWidget</render>
  <props>
    <title>Articles</title>
    <showRootItem>false</showRootItem>
    <icon>fa fa-file-text-o</icon>
    <path>/site/website/articles</path>
    <locale>en</locale>
  </props>
  <container>
    <style>
      <padding-left>9px</padding-left>
    </style>
    <class>next-pages-widget</class>
  </container>
</modulehook>
```
3. Now open both widgets (Pages and Articles) to the same article
4. Duplicate an article and note how it appears in one widget but not the other (this is also true for workflow states)

## Expected behavior
Actions taken in one widget that impact another widget should propagate. Same for workflow states.

## Screenshots
![image](https://user-images.githubusercontent.com/3931908/96033647-5b6bad80-0e2e-11eb-8088-1e7745c0639f.png)

## Logs
N/A

### Version
3.2.0-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

## Additional context
N/A

**Comment by yacdaniel** [comment]
Verified fixed, used the next ui config file
https://gist.github.com/yacdaniel/046869b28d12f1cf8a212ab92ce7c7b9

https://user-images.githubusercontent.com/6722074/107235659-8932be80-69ea-11eb-96c5-b9a3d7d29d28.mp4
