### ISSUE TITLE
[studio] Update getChildren API to allow for "excludes"

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4352]
Certain folders should be hidden from certain user-roles. This is defined in the configuration of Sidebar Widgets.

In support of this, we need to update getChildren API to exclude certain paths regexes (array of regexes to exclude from the returned results).

Please ping me for more information if required.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2409
