### ISSUE TITLE
[studio-ui] History dialog doesn't load item versions.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4355]
## Describe the bug
History dialog is spinning forever the red gears, no content item history is displayed.

## To Reproduce
1. Create a Site from any BP
2. Right click on any Page and click History
3. See error

## Expected behavior
Content Item History display the item versions and his History buttons.

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/96146739-daf78c00-0ec3-11eb-855a-863170d47ecb.png)

## Logs
N/A

### Version
`3.2.0-SNAPSHOT`

### OS
Linux OpenSuse

### Browser
Any

## Additional context
N/A

**Comment by aachavarria** [comment]
This was fixed on https://github.com/craftercms/studio-ui/pull/1973.
@yacdaniel  please verify.

**Comment by yacdaniel** [comment]
Hi @rart we need a couple of issues to fix in the History dialog:
- [ ]  "Select a revision to compare" state should not show item menu 
- [ ] Remove the Item Menu from History in Configuration
![image](https://user-images.githubusercontent.com/6722074/96611090-956b0280-12b9-11eb-97f2-186814a59ece.png)
- [ ] Compare to is not working in Configuration, looks like UI is sending a wrong path value
![image](https://user-images.githubusercontent.com/6722074/96611493-f692d600-12b9-11eb-8ea5-81ece993264b.png)
- [ ] Changing content through Item Menu is only working with Pages, Static Assets, Scripts, Templates, Components are not working. 
![history dialog no page](https://user-images.githubusercontent.com/6722074/96615038-07dde180-12be-11eb-9855-27924206abe8.gif)
- [ ] When using Compare To and going back to select version and pick another version, the Dialog keeps using the old version to Compare to.
![GIFrecord_2020-10-20_104253](https://user-images.githubusercontent.com/6722074/96617757-3c9f6800-12c1-11eb-8b9d-3cdd114b785a.gif)
- [ ] Add a confirm to revert, as we had it in 3.1.x
- [ ] Double Revet to this version when History list is long
![image](https://user-images.githubusercontent.com/6722074/96617895-71132400-12c1-11eb-88ac-0a63357bac59.png)

**Comment by yacdaniel** [comment]
@jvega190 the previous issues are all fixed now but I found something buggy 
Selecting the first item in History dialog and click on `Revert to previous`
![image](https://user-images.githubusercontent.com/6722074/105059203-a5bb8680-5a3c-11eb-972d-55cccf76c103.png)
The confirmation dialog shows that you are going to revert to the same item, when it should be the previous item in the list(look at timestamps).
![image](https://user-images.githubusercontent.com/6722074/105059366-d00d4400-5a3c-11eb-9a0d-59e5a6e4698a.png)

**Comment by yacdaniel** [comment]
Verified fixed.
