### ISSUE TITLE
[docs] Add RHEL 8 to supported platforms list

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4356]
**Is your feature request related to a problem? Please describe.**
The Crafter CMS docs are not up to date with the latest supported platforms, this list should be updated. The docs can be found here: https://docs.craftercms.org/en/3.1/system-administrators/requirements-supported-platforms.html#requirements

**Describe the solution you'd like**
Crafter CMS docs should have RHEL 8 added to the list of supported platforms.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by russdanner** [comment]
Documentation already states that RHEL is supported. We do not need to specify specific versions. 
RHEL 8 is supported.
