### ISSUE TITLE
[studio] Add Content-Type response header to StudioAccessDeniedHandler

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4357]
## Describe the bug
When a site is created using /api/1/site/create.json  and the user doesn't have permissions to create a site the response doesn't contain the Content-Type header. This is causing some issues while using the craftercms CLI. 

## To Reproduce
1. Create a user and don't assign any group.
2. Create a site using /api/1/site/create.json  with the previous user.
4. See response headers

## Expected behavior
`Content-Type: application/json` should be returned in the header when user is not authorized. https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/web/security/access/StudioAccessDeniedHandler.java 

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/96195158-41eb6400-0f09-11eb-9e86-23fa3bd44001.png)

## Logs
N/A

### Version
`3.1.x` & `3.2.x`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2225
https://github.com/craftercms/studio/pull/2226

**Comment by sumerjabri** [comment]
Validated in 3.1.x

**Comment by yacdaniel** [comment]
Verified fixed in 3.2.x
