### ISSUE TITLE
[studio-ui] Preview iFrame doesn't auto-adjust left margin

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#436]
Preview iframe in studio 2.5.x and 3.0 doesn't automatically adjust to the right left margin, but instead starts at 225px and stays there until the user changes the width of the left navigation.

Starts like this: `<div class="studio-preview" style="left: 225px;">`

and if you try and resize, it immediately jumps to the correct `<div class="studio-preview" style="left: 265px;">`

You'll need to clear your cookies to test for this.

The code is in the file: `wcm_dropdown.js` line `136`

However, we don't want to change the default to 265, we want the system to auto adjust the first time without the user resizing. Assigning an arbitrary number won't fix this long-term.

Please fix in both 2.5 and 3.0.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/225
