### ISSUE TITLE
[studio] Search sometimes doesn't match paths

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4360]
## Describe the bug
When using search API, path is part of the search target and at times it works but some paths return no results.

## To Reproduce
1. Be on 3.2 (develop), create site via git cloning https://github.com/rart/craftercms-editorial-ice.git and go to Preview (or Search) on that site
2. Type `/articles/2017/1/men-styles-for-winter` on the URL, which matches the URL/path of `/site/website/articles/2017/1/men-styles-for-winter/index.xml`
3. Notice no results come out of that

## Expected behavior
Men styles for winter should show up as a result.

## Screenshots
![image](https://user-images.githubusercontent.com/3928341/96611008-88233780-12fc-11eb-92ce-756c46d0a620.png)
![image](https://user-images.githubusercontent.com/3928341/96610794-50b48b00-12fc-11eb-98db-289f586ff0fa.png)
![image](https://user-images.githubusercontent.com/3928341/96610856-632ec480-12fc-11eb-9cf4-758cd95fc252.png)

## Additional context
Note that other — simpler? — urls work as expected showing the matching page. For example `/articles`, `/health`. Seems to be that single piece urls/paths work but multi-piece don't.

**Comment by rart** [comment]
The issue is resolved.

The total number of results was a bit unexpected for me. I guess it's because it's doing keywords search? Looks like `/articles/2017/1/men-styles-for-winter` is not treated as a word but rather somehow split and all it's terms are used?

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3928341/100089087-6b28d980-2e51-11eb-8dd5-3e18af55ca10.png">

**Comment by jdrossl** [comment]
@rart yes the keywords are used to build a complex query with each token, if you need something different then you should use the `query` field to add a more restrictive query https://app.swaggerhub.com/apis/craftercms/studio_3_2/3.2.0.3#/search/search
