### ISSUE TITLE
[studio-ui] Scripts & Templates are not editable

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4363]
## Describe the bug
Scripts & Templates are not editable, user is only able to see the content. Creating a new Template/Scripts is working and content can be added. 

## To Reproduce
1. Create a site from any BP
2. Right click and `Edit` content from Scripts/Templates

## Expected behavior
User should be able to edit the Templates & Scripts.

## Screenshots
Only Close button available when editing a script.
![image](https://user-images.githubusercontent.com/6722074/96773183-629c3980-13a1-11eb-98b5-45e45b8bfc00.png)

## Logs
N/A

### Version
`3.2.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by rart** [comment]
Fixed https://github.com/craftercms/studio-ui/pull/1983

**Comment by yacdaniel** [comment]
Verified fixed.
