### ISSUE TITLE
[studio] CSRF-token can still be used after I log out

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4364]
## Describe the bug
The CSRF-token can still be used after I log out, CSRF tokens should be generated on the server-side. They can be generated once per user session or for each request.

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

## To Reproduce
1. Go to 'Studio'
2. Login
3. Notice that we have `XSRF-TOKEN` session value and this one is used for POST/PUT/DELETE requests
4. Logout
5. Login again
6. Notice that `XSRF-TOKEN` is still valid and can be used after logged out.

## Expected behavior
After logged out, CSRF Token should be invalid

**Comment by jdrossl** [comment]
@yacdaniel please help validating this

**Comment by sumerjabri** [comment]
Validated in 3.1.x

**Comment by yacdaniel** [comment]
Verified in 4.0.0.
