### ISSUE TITLE
[studio] Assets that are created as renditions of a source asset should be tracked and treated as dependencies of the source asset

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4366]
**Is your feature request related to a problem? Please describe.**
When an asset rendition is created via the asset processing pipeline it should be tracked as a dependency of that asset. 

**Describe the solution you'd like**
When a rendition is created, track the rendition as a dependency (a target) of the original asset (source.) This will ensure that if the asset is published the renditions will also be published. It will also be possible to see the relationship of the renditions and the source asset in the dependency dialogs.

Ideally deleting a source object would also delete the renditions. This not a general rule of dependencies and would need specific a design and handling.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/4195

**Comment by sumerjabri** [comment]
Closing in favor of the more general https://github.com/craftercms/craftercms/issues/4538
