### ISSUE TITLE
[studio-ui] Jump to Region does not work for features with internal names with space in Website Editorial

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4367]
## Describe the bug
In a site created with the Website Editorial blueprint, the `Jump to Region` does not work for features with internal names with space

## To Reproduce
1. In the `Features` section of the Home page, add a new feature using the internal name `My Feature` (don't forget the space in the name)
2. Open the `Preview Tools` panel by clicking on the wrench icon at the top right
3. Click on the `Jump to Region` drop down and select the new feature we just added, `My Feature`
4. Notice the message displayed: `Region My Feature could not be found`
<img width="463" alt="Screen Shot 2020-10-23 at 10 02 08 AM" src="https://user-images.githubusercontent.com/25483966/97013898-a1540000-1517-11eb-9350-3915a16ad0a4.png">

## Expected behavior
It should be able to jump to a feature with a space in the name in Website Editorial/ No region could not be found message

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.11-SNAPSHOT-b59653
Studio Version Number: 3.2.0-SNAPSHOT-bc55ec

### OS
MacOS 10.15.6

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
Verified fixed.
