### ISSUE TITLE
[studio-ui] Custom Form Control Plugins are not found in Crafter Studio for use

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4368]
## Describe the bug
Custom Studio Form Control Plugins are not made available for use in the Controls tab under Content-Type Editor in Crafter Studio. After dragging and dropping the custom plugin control in the content-type, it shows up as disabled with the label 'Control Not Available'. 

## To Reproduce
1. Create a site from the Editorial Blueprint 
2. Create a new Custom Form Control Plugin following the documentation: https://docs.craftercms.org/en/3.1/developers/plugins/studio/form-control-plugins.html
3. Once the plugin is created, in the directory CRAFTER_HOME/data/repos/sites/<site_name>/sandbox/config/studio/plugins ``git add .`` and then a ``git commit -m "<your commit message>"``.
4. Next navigate to the site-config-tools.xml file and add the custom plugin information (as is outlined in the documentation above). This file is located: CRAFTER_HOME/data/repos/sites/<site_name>/sandbox/config/studio/administration
5. Do a ``git add .`` and a ``git commit -m "<your commit message>"`` in order for these changes to be reflected
6. Navigate to the site you made in your browser
7. On the left side of the page, click Site Config
8. Next select Content Types and choose a template from the list, ``Page - Home`` will do
9. Drag and Drop the custom plugin that you created into the existing content type
10. Notice the Control shows up as 'Control Not Available'

## Expected behavior
A Custom Form Control Plugin that is created should be listed and available as a Control in Studio. The Custom Control should also be available for modifying and using via dragging and dropping from the existing Control list. 

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/97052407-f3644800-154e-11eb-8c4d-9ec7de200136.png)

## Logs
N/A

### Version
```
Studio Version Number: 3.1.10E-57fdd3
Build Number: 57fdd32fa5e6a50c05f7361be74c551477fe78a4
```

### OS
N/A

### Browser
N/A

## Additional context
N/A

**Comment by russdanner** [comment]
Confirmed. Plugin is loaded on both form engine and type builder
