### ISSUE TITLE
[studio] get_configuration_history API returns virtual file when requested file doesn't exist.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4369]
## Describe the bug
The get_configuration_history API (2) is returning data for a file that doesn't exist in the system, will the item properties and empty list of versions

## To Reproduce
1. Make a request to the get_configuration_history API with a non-existing file, like
`.../studio/api/2/configuration/get_configuration_history.json?siteId=editorial&path=%2Fnon-existing-file.xml&environment=default&module=studio`

2. See the returning data

## Expected behavior
get_configuration_history should indicate that the file doesn't exist instead of returning a non-existing item

## Screenshots
![Screenshot from 2020-10-23 09-55-59](https://user-images.githubusercontent.com/18267471/97025947-fabb2f80-1515-11eb-9913-7eb37c3524f6.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Crafter 3.2.x

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2354

**Comment by jvega190** [comment]
Verified fixed
