### ISSUE TITLE
[studio] Add Service to Sync from Repo

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#437]
Add a Studio service to request the database by sync'd from the underlying repository (git in the current case).

**Comment by sumerjabri** [comment]
Add documentation/spec first, then assign to Dejan.

**Comment by sumerjabri** [comment]
API spec'd here: http://docs.craftercms.org/en/latest/developers/projects/studio/api/repo/sync-from-repo.html

**Comment by dejan-brkic** [comment]
Completed
