### ISSUE TITLE
[studio-ui] Consolidate UI Next's configuration into a single file

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4371]
Consolidate the configuration of UI Next into a single file per site. Ping me to discuss the design.

- [x] Update the UI
- [x] Add to UM mechanics

**Comment by rart** [comment]
@sumerjabri please review https://github.com/rart/wordify-blueprint/blob/next/config/studio/ui.xml

**Comment by sumerjabri** [comment]
@jdrossl please add this new configuration file to UM so we can upgrade it over time.

**Comment by jdrossl** [comment]
should the UM add a fixed version to start or does it need to copy data from existing files?

**Comment by rart** [comment]
It could be helpful for customers to port:
- the sidebar config "modulehooks" (the folder trees only).
- the site config modules.
Not sure what Sumer has in mind, though. Might be worth checking with @russdanner how frequent is for people to divert from defaults on those.

A version goes regardless right? We might extend this file further going forward.

**Comment by sumerjabri** [comment]
@jdrossl @rart we won't be automatically porting/moving sites to the new UI, therefore the UM won't get involved at this stage. The UM will upgrade sites born into 4.0 to future 4+ versions, and the version of the configuration file can start at 1 (or 0, however you did it before).

Users upgrading 3.x sites to 4.x will need to create this file and configure it as needed as part of the upgrade to PB. The base file will have that fixed version. @russdanner I hope this is a shared expectation (that sites won't automatically upgrade from 3 to 4 at this time).

**Comment by sumerjabri** [comment]
@jdrossl Please add the version number and anything else the UM needs to the sample file if required. Once you feel the new configuration is ready to be upgraded from 4.0.0 to 4.0.x, please assign the ticket back to @rart to close.

**Comment by sumerjabri** [comment]
@jdrossl would the UM also be adding the sample file?

**Comment by jdrossl** [comment]
@rart please provide a shorter version with comments explaining each section to add as a sample
