### ISSUE TITLE
[studio-ui] Admin roles seens path navigators configured without admin role

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4373]
## Describe the bug
{{A clear and concise description of what the bug is.}}

## To Reproduce
1. Go to Sidebar configuration
2. adds two modulehook:

`<modulehook>
  <name>wcm-root-folder</name>
  <params>
    <label>Pages</label>
    <path>/site/website</path>
    <showRootItem>true</showRootItem>
    <onClick>preview</onClick>
    <roles>
      <role>admin</role>
    </roles>
  </params>
</modulehook>
<modulehook>
  <name>wcm-root-folder</name>
  <params>
    <label>Pages</label>
    <path>/site/website</path>
    <showRootItem>true</showRootItem>
    <onClick>preview</onClick>
    <roles>
      <role>author</role>
    </roles>
    <excludes>
      <exclude>/site/website/news</exclude>
    </excludes>
  </params>
</modulehook>`

3. Go to preview
4. Using a admin role should see both of the modules on the sidebar;

## Expected behavior
The admin role should only see the ones with admin roles or no roles.

## Screenshots
<img width="380" alt="sidebar" src="https://user-images.githubusercontent.com/10813283/97584221-6b05fd00-19bd-11eb-9c2d-f7c688e5a869.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Sidebar (and general containers) should honor their configuration and only their configuration for roles/visibility per the design session with @rart and @russdanner.

**Comment by aachavarria** [comment]
Not pending work to do on this, it is working as expected.
The admin sees the widget because the admin contains all the others roles.
