### ISSUE TITLE
[studio-ui] Large video files fail to upload to WebDav server through Studio UI with slow internet connection

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4374]
## Describe the bug
When uploading a large video file to a WebDAV server through Studio-UI with a slow internet connection, the video fails to upload.

## To Reproduce
1. Create a site based on editorial
2. Go to Site Config --> Content Types --> Page - Home
3. Add a video picker
4. Add a Video Uploaded from WebDav as the data source for the video picker
5. Save these changes
6. Go back and edit the home page
7. Right-click inspect the page once the edit form pops up
8. Navigate to the Network tab and under the "Online" drop-down, select "Fast 3G" in order to manipulate a slow internet connection
9. Next scroll down to the video picker and click "add"
10. Right-click the parent folder in the WebDav and click upload. Upload a video file from your computer bigger than 150 MB
11. Since internet connectivity is slow, the upload will take a while to fail out ~25 minutes
12. Tail the logs and see the errors

## Expected behavior
Large video files should be able to be uploaded to the WebDav server through the Studio-UI without issue.

## Screenshots
For how to slow internet connectivity:

![image](https://user-images.githubusercontent.com/42217570/97624657-c9eb6680-19fd-11eb-8e6b-ef35bc8bd561.png)

## Logs
https://gist.github.com/russdanner/1f45f8ff35edbfeb04b49f17853956bf

### Version
```
Studio Version Number: 3.1.6E-01732a
Build Number: 01732a89d4df260c34e4026fe93981f4cda98f6f
```

### OS
N/A

### Browser
N/A

**Comment by russdanner** [comment]
Note that it seems others have had similar exceptions with Sardine having to do with preemptive authentication. This may be useful:
https://groups.google.com/g/sardine-dav/c/OF-DUlSZK1E

**Comment by jdrossl** [comment]
I'm not able to reproduce this issue, I was able to upload a 160mb file in both Fast & Slow 3G modes. Tested with a docker & local webdav.

I think this timeout could be cause by configuration or other external factor

**Comment by russdanner** [comment]
@AndyReiter @jdrossl Please get together and reproduce this issue.

**Comment by russdanner** [comment]
We're going to upgrade the library.

**Comment by jdrossl** [comment]
@yacdaniel please help validate, so far only Andy has been able to reproduce the issue but it would be good to give it another try

@alhambrav to fix the issue a new option has been added to the webdav profile xml file, we will need to document this

**Comment by sumerjabri** [comment]
@AndyReiter please help validate this ticket.

**Comment by AndyReiter** [comment]
Validated @sumerjabri

**Comment by russdanner** [comment]
Confirmed
