### ISSUE TITLE
[studio] Add status property for sites

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#4375]
Add new property in the site table that will store site state. State property will be used to describe site status such as INITIALIZING (site being created), READY (when creating process is completed and site is ready for use), DELETED (when deleted). This property should be flexible enough to make easy adding new states/statuses as needed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2475

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
