### ISSUE TITLE
[studio-ui] Add snackbar for actions performed in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4376]
**Is your feature request related to a problem? Please describe.**
A snackbar informing users of actions performed in Studio where applicable would be nice to have.

One example is when deleting an item.  After clicking on the `Delete` button, a snackbar saying `Selection Deleted` would be nice.

Here's a short clip showing an item being deleted and no snackbar after performing action:
https://www.loom.com/share/5450c889201944038cb406714e7ac18a

In the previous UI, when an item is deleted, this is shown afterwards:
<img width="677" alt="Screen Shot 2020-10-30 at 10 15 51 AM" src="https://user-images.githubusercontent.com/25483966/97741084-97eb0a80-1ab8-11eb-838d-1503a0de53fe.png">

**Studio Version**
Studio Version Number: 3.2.0-SNAPSHOT-9af155

**Comment by alhambrav** [comment]
Hi! @aachavarria 

Verified snackbars appear when deleting/publishing items, deleting users/groups.

Should there be a snackbar too when you're in sites and you delete a site after clicking "Yes" in the confirmation dialog?

**Comment by rart** [comment]
Yes, there should. Please add, @aachavarria.

**Comment by alhambrav** [comment]
Verified snackbar appears when deleting a site.

For a user with the role `author`, when submitting a Request Publish, should there be a snackbar after hitting the “Submit” button that content has been submitted requesting to be published? 

<img width="1310" alt="Screen Shot 2020-12-10 at 3 05 20 PM" src="https://user-images.githubusercontent.com/25483966/101823984-98d07c80-3af9-11eb-9067-f44f27472e41.png">


Also, when rejecting a user request for publish, should there be a snackbar too that the rejection of submission has been performed/successful?

<img width="1320" alt="Screen Shot 2020-12-10 at 3 09 07 PM" src="https://user-images.githubusercontent.com/25483966/101824087-b998d200-3af9-11eb-9d13-7eaa416564dc.png">

**Comment by aachavarria** [comment]
@rart What about above questions?

**Comment by rart** [comment]
All views that don’t display a perceivable success message of their own, should present a snack indicating the success of the action.

**Comment by alhambrav** [comment]
Verified when submitting a `Request Publish` that a snackbar appears afterwards.

Just one more thing, when rejecting a request for publish, there is still no snackbar that appears after hitting the `Reject` button

**Comment by alhambrav** [comment]
Verified.
