### ISSUE TITLE
[studio-ui] Show only supported actions in the History dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4377]
## Describe the bug
In the History dialog, actions for comparing images to another version are permitted, but shows an error when performing the comparison.  .  It would be nice to show only supported actions in the History dialog

## To Reproduce
1. Using the website editorial bp, make an edit to one of the images under /static-assets/images.  Remember to commit the file after editing the image using your favorite image editor.  This will create another revision of your image file.
2. Open the `Sidebar` and navigate to the image you edited in the previous step.  Right click on the file and select `History`
3. Pick one of the revisions, then click on the three dots next to it to view the available actions for that version.  Notice the available actions.  In the example below, the three dots next to the bottom (initial) version is clicked.

![Screen Shot 2020-10-30 at 4 41 04 PM](https://user-images.githubusercontent.com/25483966/97755575-cfb17c80-1acf-11eb-9f11-c6f2c5f48980.png)

4. Click on `Compare to current`.  Notice the error message displayed.

<img width="888" alt="Screen Shot 2020-10-30 at 10 25 20 AM" src="https://user-images.githubusercontent.com/25483966/97755916-641bdf00-1ad0-11eb-952f-df1049d1462c.png">

5. Go back to the `History` list and this time, click on `Compare to previous`.  Notice that it looks like it does nothing (which is technically correct as there is no previous version.).   The same thing thing happens when you select `Compare to...`

## Expected behavior
It would be nice to show only supported actions in the History dialog.
For example, in the scenario listed above, it would be nice if we can't compare images, then the compare actions show not be shown.
It would be nice to not show the `Compare to previous` for the items that's at the bottom of the list (like the initial commit of the file), since, there's nothing previous to it.
 
## Screenshots
Here's a short clip:
https://www.loom.com/share/8d7f64c6c14540eba57903f012c06de2

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.2.0-SNAPSHOT-9af155
Build Number: 9af1558cc091391b162cec5475ebf8c82512a9e0
Build Date/Time: 10-29-2020 14:03:27 -0400

### OS
macOS 10.15.6

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
@aachavarria Here are some of my observations:

I am not sure if this is supposed to be addressed in the ticket, but `Compare to previous` still appears for the very first entry in History:
1. Using a site created using the website editorial bp. make an edit to the Home page then save your changes.  This should create an entry in History
2. Edit the Home page again and save your changes, which should create yet another entry in History.
3. View the History of the Home page.  There should be 3 entries listed.  Click on the more button (3 dots) of the initial commit version. Notice `Compare to previous` is still available even if there's no previous entry.
![Screen Shot 2020-11-05 at 3 17 41 PM](https://user-images.githubusercontent.com/25483966/98363706-6795f580-1ffd-11eb-86a0-344256513e58.png)
---------------------------------------------------------------------------------------
The items available from the more button changes depending on how the History dialog was opened.
In the image above, the History dialog was opened by opening the `Sidebar` then right clicking on `Home`, then select `History`.  When you click on the more buttons, you see the compare options.

Now, access the `History` dialog from the context nav:
1. Preview the home page, then click on `History` from the context nav (at the top)
2. Click on the more button.  Notice the compare options are not listed
<img width="958" alt="Screen Shot 2020-11-06 at 7 05 00 AM" src="https://user-images.githubusercontent.com/25483966/98364408-bee89580-1ffe-11eb-8d42-9ce63b7abb48.png">

I noticed for images, the `History` dialog is consistent whether it's accessed from the context nav or by right-clicking from the `Sidebar`, which brings me to my next observation

--------------------------------------------------------------------------------------------
Images (jpg, png files) still has the compare buttons:
<img width="915" alt="Screen Shot 2020-11-06 at 7 11 33 AM" src="https://user-images.githubusercontent.com/25483966/98365430-6b774700-2000-11eb-8ff0-7467ecf7d715.png">

You'll get the error message shown in this ticket when you click on the compare option

--------------------------------------------------------------------------------------------
Comparing js files does not work.  There's an error message displayed when comparing js files (javascript files in the `/static-assets/js` folder.

1. Navigate to `/static-assets/js`, then edit one of the js files, I edited the comment in `handlebars.min-latest.js`.  Save your changes to create a history entry.
2. From the `Sidebar`, right click on `handlebars.min-latest.js` and select `History`
3. Click on the more button of one of the entry then select `Compare to current` or `Compare to previous` depending on which history entry you selected.  Notice the error message displayed.

---------------------------------------------------------------------------------------------

Comparing items under templates and scripts does not work.  There's an error message displayed when comparing groovy or ftl files.  

1. Edit /templates/web/pages/article.ftl then save your changes
2. View the `History` of the edited page, then click on the more button of one of the entries. 
3. Select `Compare to current` or `Compare to previous.  Notice the error message displayed

Follow the same steps as above for one of the files under /scripts

**Comment by alhambrav** [comment]
@aachavarria

In 3.1, js, template and script files can have versions compared.  Please allow diffs of items that can be diffed (mostly files with just text, such as js, ftl and groovy files).  I think it's useful to be able to diff groovy, ftl, etc files.

------------------------------------------------------------------------------
Also, when you try to view a previous version of an image, there is an error
<img width="1347" alt="Screen Shot 2020-12-07 at 9 49 20 AM" src="https://user-images.githubusercontent.com/25483966/101372689-2e5dd900-387a-11eb-8306-4ad9adb29f14.png">

----------------------------------------------------------------------------
I also noticed we do not have the `Compare to current` option anymore in the History dialog.  Is this the expected behavior now?
<img width="987" alt="Screen Shot 2020-12-07 at 10 53 22 AM" src="https://user-images.githubusercontent.com/25483966/101373356-d673a200-387a-11eb-8547-7b1864c0f1c5.png">

**Comment by aachavarria** [comment]
@alhambrav hey Vita, I added the compare to current option, but for the other request, can you check this please, https://github.com/craftercms/craftercms/issues/3940, looks like those options now are not supported.

**Comment by alhambrav** [comment]
Hi! I Checked https://github.com/craftercms/craftercms/issues/3940 and agree with that, and also verified `Compare to current` is now available in the options.  Just a couple more observations:

- For the first item listed in the History dialog (the current item), should it not have the `Compare to current` option when you click on the three dots since it is already the current?: 
<img width="1192" alt="Screen Shot 2021-01-04 at 10 50 51 AM" src="https://user-images.githubusercontent.com/25483966/103649990-5ac64d00-4f2d-11eb-8bb6-88870db5e556.png">

- For the last entry in the History dialog, should it have the `Compare to current` option when you click on the three dots?
<img width="1177" alt="Screen Shot 2021-01-04 at 10 50 37 AM" src="https://user-images.githubusercontent.com/25483966/103650137-9103cc80-4f2d-11eb-9d7d-ab1c5601a2f6.png">

**Comment by alhambrav** [comment]
Verified.
