### ISSUE TITLE
[studio-ui] Add button to sync from repository

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#438]
Add a button below Preview Sync to invoke the new service to sync from repository.

API spec: http://docs.craftercms.org/en/latest/developers/projects/studio/api/repo/sync-from-repo.html

**Comment by sumerjabri** [comment]
API spec is here: http://docs.craftercms.org/en/latest/developers/projects/studio/api/repo/sync-from-repo.html

**Comment by jvega-crafter** [comment]
Done, service with correct url/params pending

**Comment by sumerjabri** [comment]
I can't see the button. How do I configure it to show?

**Comment by sumerjabri** [comment]
Is it the same button, currently labeled Preview Sync?
