### ISSUE TITLE
[studio] Make active filters prominent in search results page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4383]
**Is your feature request related to a problem? Please describe.**
1. Create a site using the website editorial bp, then click on `Search`
2. Click on the `Filters` button then set the filters mime-type to image/jpg
<img width="428" alt="Screen Shot 2020-11-04 at 9 40 38 AM" src="https://user-images.githubusercontent.com/25483966/98124990-df3f1580-1e81-11eb-8329-62523183d087.png">

3. Type in a search term, we'll use `lorem` for our example.  Notice the search returned 0 results, and you can't tell that there are active filters
<img width="1092" alt="Screen Shot 2020-11-04 at 9 40 17 AM" src="https://user-images.githubusercontent.com/25483966/98125097-072e7900-1e82-11eb-8314-6c9986ece7b3.png">

Also, when you open  the filters, the mime-type filter is not available and the user won't be able to clear it.
<img width="1003" alt="Screen Shot 2020-11-04 at 9 58 12 AM" src="https://user-images.githubusercontent.com/25483966/98127077-465dc980-1e84-11eb-85b0-a74d5f1920f6.png">

Here's a short clip showing the steps listed above:
https://www.loom.com/share/ba008a6c47024ec8a5d469c47697bacc

**Describe the solution you'd like**
Make active filters prominent in search results page that say, appears at the top of the search results page and make sure that the active filters can be cleared

### Version used for screenshots above
Studio Version Number: 3.2.0-SNAPSHOT-a65567
Build Number: a65567a2302cec9b76d0bc6df62d040cce620ee7
Build Date/Time: 11-03-2020 12:02:31 -0500

**Comment by rart** [comment]
@jvega190 Implement the full design as shown on Figma project 3.2 > Search

**Comment by alhambrav** [comment]
Verified there's a prominent message that there are filters active on the search page...
@rart @jvega190 Would it be possible to display/highlight all the active filters so users can pick/choose which filters to leave on/off?  

Using the example above this is how the search page looks after setting the MIME type filter:
<img width="1392" alt="Screen Shot 2021-01-15 at 10 07 03 AM" src="https://user-images.githubusercontent.com/25483966/104743471-be186200-5719-11eb-938c-28efe87eaa13.png">


Now, after entering a search term, the user does know that there are active filters, but, they wouldn't be able to find the active filter since the MIME type filter disappeared from the list

<img width="1392" alt="Screen Shot 2021-01-15 at 10 10 12 AM" src="https://user-images.githubusercontent.com/25483966/104743981-544c8800-571a-11eb-8098-a44386da819c.png">

Thanks!

**Comment by rart** [comment]
@alhambrav the issue is the UI is simply rendering the facets that the backend sends back. This is kind of a bigger matter that needs some discussion and thought. 

I would consider this one complete as long as you can "clear filters" which, doesn't seem to be the case. That we need to fix for sure since otherwise users are stuck; will see if we can fit the missing facets based on what we have on the URL (@jvega190).

Let's see where we can get, but we might need a separate ticket so we can discuss & prioritize accordingly.

**Comment by alhambrav** [comment]
Verified.
