### ISSUE TITLE
[docs] Document Crafter CLI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4386]
https://github.com/craftercms/crafter-cli

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1090 and https://github.com/craftercms/docs/pull/1091

**Comment by sumerjabri** [comment]
@alhambrav please see notes in Slack regarding this.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1115 and https://github.com/craftercms/docs/pull/1116
