### ISSUE TITLE
[studio-ui][studio] Don't allow underscore (_) in site names

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4387]
We use the site name in the creation of other resources (for example, an AWS CloudFormation when using serverless). These resources don't allow underscores in their name most of the time. We need to remove underscores from the allowed characters in the site name (I think we can leave it for the site label).

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2263
https://github.com/craftercms/studio/pull/2264

**Comment by avasquez614** [comment]
Verified. @rart please close this ticket when the hint has been fixed (like we discussed yesterday)
