### ISSUE TITLE
[studio-ui] Content-type form is not saving properties types (for datasources) to form-definition

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4394]
## Describe the bug
Datasources properties have types (boolean, string, list, etc) that are not being saved to the form-definition.xml file (they show as `<type>undefined</type>`).

## To Reproduce
1. Go to Site Config - Content Types
2. Open a type and add a datasource.
3. Edit its properties.
4. Save the type.
5. Go to the type's form-definition.xml and look for the added datasource.
6. See that the properties types are undefined.

## Expected behavior
The datasources properties should have its type on the form-definition.

### Version
3.2.x
3.1.x

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by sumerjabri** [comment]
Verified in 3.1.11

**Comment by yacdaniel** [comment]
Verified fixed in 4.0.0
