### ISSUE TITLE
[studio-ui] Form opened from a page (node-selector) with no changes is not closing when clicking cancel

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4395]
## Describe the bug
When you create a component from a form's node-selector, and make no changes to it, and you click on cancel, the form is not closing. 

## To Reproduce
1. Create a site using editorial (with new ICE).
2. Add a node-selector to the homepage with a receptacles datasource associated.
3. Edit the homepage and click on add (to the new added node-selector), and create a component.
4. When the component's form is opened, do not edit anything in the form and click on 'Cancel'.
5. See that the form is not closing.

## Expected behavior
The form should close when it has no changes (when clicking 'cancel')

### Version
Crafter CMS 3.2.x

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by yacdaniel** [comment]
Verified fixed.
