### ISSUE TITLE
[Studio] Create new folder does not add a record to `item` table

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4396]
## Describe the bug
When creating new folder with Studio UI, it seems there is no record added to db`item` table

## To Reproduce
1. Go to dashboard
2. Click on static-assets right menu
3. Choose create new folder
4. There is no record in `item` table

## Expected behavior
There is a record added to `item` table

### Version
3.2

### OS
MacOS

### Browser
Chrome

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2265

**Comment by yacdaniel** [comment]
Verified fixed.
