### ISSUE TITLE
[docs] Document how to setup CloudFront signed cookies in Crafter

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4403]
Document how to setup CloudFront signed cookies in Crafter

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1098 and https://github.com/craftercms/docs/pull/1099

**Comment by avasquez614** [comment]
@alhambrav let's make these changes: instead of `Create a Groovy filter that is applied to all requests and calls the class method`, let's do `Create a Groovy filter that checks for current user authentication/authorization, and then calls the class method`.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1120 and https://github.com/craftercms/docs/pull/1121

**Comment by avasquez614** [comment]
Verified
