### ISSUE TITLE
[docs] Missing info for blueprint parameters

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4405]
Our guide about blueprint parameters is missing the information about using the parameters in the configuration files

https://docs.craftercms.org/en/3.1/developers/plugins/blueprints.html#passing-parameters-to-blueprints

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1102 and https://github.com/craftercms/docs/pull/1103

**Comment by jdrossl** [comment]
Verified
