### ISSUE TITLE
[docs] Document the re-encryption process included in 3.1.9

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4408]
The release notes for 3.1.x should have a link to a guide including the following:
- Why the re-encryption is necessary
- What values will be re-encrypted
- How to re-encrypt values manually if the UM can't use the existing configuration

The release notes for 3.2.0 should include a warning indicating that it is not possible to upgrade from versions previous to 3.1.9

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1095 and https://github.com/craftercms/docs/pull/1096

**Comment by jdrossl** [comment]
Verified
