### ISSUE TITLE
[studio-ui] Add a validation that blocks user from creating a site with an existing site id

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#441]
Steps:

1. login on studio
2. Click on "create site" button.
3. Site name : test
4. SIte ID: test
5. Description : testing
6. Blueprint : empty
7. Click on "create" button
8. Try to create a site with the same data of the steps 3, 4, 5 and 6.

Current result: I created a site, and then I try to create an another site with the same data of the first site created and studio doesn't display a validation message indicating that you are creating a site with the same information as another, Studio does not create the second site but gives the feeling that if it did.

Evidence: https://www.screencast.com/t/kmzXsHllcC

Expected result: Studio should be display a validation message indicating that exist a site with the these data.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/241

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/241
