### ISSUE TITLE
[studio] Publishing is disabled messages repeat every 10 seconds cluttering studio logs

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4418]
**Is your feature request related to a problem? Please describe.**
Publishing is disabled for site <site> repeats in my log every 10 seconds when Crafter is running. This is happens on local development environment where delivery will not be running. 
[INFO] [Studio_Publisher_Thread_Pool1] [job.PublisherTask] | Publishing is disabled for site <site>

**Describe the solution you'd like**
Would like there to be a way to disable this message in studio so logs are not cluttered with this message

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sumerjabri** [comment]
Log upon the disablement of publishing, not in the worker thread. The worker thread can log as DEBUG.

**Comment by AndyReiter** [comment]
Turning off the publisher in 3.1.15-SNAPSHOT still results in the publishing disabled message being outputted about every 10 seconds in the logs. Assigning back to @jdrossl.

**Comment by AndyReiter** [comment]
Confirmed fix in 4.0. Closing this ticket now.
