### ISSUE TITLE
[studio-ui] Edit button should be hidden on item selector when associated DataSource does not offer an ability to edit

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4419]
**Is your feature request related to a problem? Please describe.**
The edit button should be hidden on the item selector if the edit functionality is not supported by the data source. 

Example:
Box data source: We should remove the edit button since there is no practical edit action with a Box-based data source.

**Describe the solution you'd like**
The Edit button should be removed/be hidden (rather than disabled.)

**Describe alternatives you've considered**
N/A

**Additional context**
For more context, it is this edit button that should be removed.
![image](https://user-images.githubusercontent.com/42217570/100007383-fe063d00-2d99-11eb-9c9a-ee70de21d536.png)

**Comment by sumerjabri** [comment]
Closing in favor of FE2 features.
