### ISSUE TITLE
[studio-ui] Right click on CMIS to browse and upload files

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4420]
**Is your feature request related to a problem? Please describe.**
Currently, when using the file from CMIS repo, you are not able to right-click and have the option to upload files to the CMIS repository via the data source like you are with WebDav files. 

**Describe the solution you'd like**
Users should be able to upload files to their listed CMIS repository through the context menu just like they are able to do with WebDav.

**Describe alternatives you've considered**
N/A

**Additional context**
For example functionality, please link an item selector to a file from the WebDAV repository. Then edit the page where this item selector and data source exists. Click "Add" to add a new file from the WebDav repository. Once the WebDAV repository navigator opens, right-click a folder and see the option to upload a file to that folder. This functionality is what is desired for CMIS items.
![image](https://user-images.githubusercontent.com/42217570/100009464-f4320900-2d9c-11eb-8f5b-73fe4353fa66.png)

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by russdanner** [comment]
Confirmed
