### ISSUE TITLE
[studio-ui] Create LegacyDashboardFrame component

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4421]
**Is your feature request related to a problem? Please describe.**
Create a component to wrap the Site Dashboard in embedded mode (by default)

**Describe the solution you'd like**
The component should receive the onlyDashboard param default to true (if true -> embedded mode).

**Comment by rart** [comment]
ToDo:
- The top bar is invisible but still occupies it's space. Space should be freed.
- Selecting an item and clicking "Edit" doesn't work.
- Test all action bar actions work correctly
- Hitting the "clear selected" on the action bar shows a spinner, loads a bunch of stuff and takes a while. This should be immediate.
