### ISSUE TITLE
[studio-ui] Persist content clipboard across refreshes

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4422]
- Store content clipboard on local storage every time clipboard is modified
- Retrieve it and put it in app state when the page loads
- Leave a date prop on the stored state and when retrieving, discard it if older than 24h - i.e. don’t put it on state and delete the stored item too.

**Comment by aachavarria** [comment]
@yacdaniel The persist content it is only working for the new PathNavigator in New Preview for testing purposes uses the new Editorial

**Comment by yacdaniel** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/6722074/111645042-001b5e00-87c6-11eb-9c84-d1f550165afe.png)
