### ISSUE TITLE
CrafterCMS has no site configured after initial setup

### ISSUE THREAD

**Issue by akudekar** [craftercms/craftercms#4424]
I downloaded the tar.gz for authoring with profile and social and also without profile and social.

With startup.sh http://localhost:8080/studio shows `no site configured. Please configure the site you want to show or select a site on the authoring environment.`

A quick look of the deployer logs show `No config files found under /crafter/data/deployer/targets`. No good documentation is available on this. I tried creating a yaml file after reading https://docs.craftercms.org/en/3.0/system-administrators/deployer/admin-guide.html still it doesn't change the situation.

I haven't tinkered with any configurations I only followed the quick start guide. No login page is also showed.

**Comment by sumerjabri** [comment]
That means Studio didn't start up correctly. See the logs in `logs/tomcat/catalina.out`. (Could be resources/memory.)

Join us here: https://join.slack.com/t/craftercms/shared_invite/enQtNDg0NzI3NzA0NjMwLWZmMGQzMDViMzA5NDE1YjMzM2M1N2JlOWJlZDA1MjA2MGJlZjgzNDVlMmI5ODQxNmNjMWQ3NzA5ZWNkN2UxOWE

or here: https://groups.google.com/forum/#!forum/craftercms

To ask questions and get support.

Closing this ticket.
