### ISSUE TITLE
[studio] ElasticSearch deploy-all functionality fails when trying to re-index sites

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4427]
## Describe the bug
ElasticSearch deploy-all functionality fails. The indices are all created but no documents or files are added to the indices. The logs show multiple timeout exceptions for ElasticSearch saying that the index could not be created but after looking at the es-index directory, the indices were created successfully however no documents have been created.

## To Reproduce
1. Create multiple sites in studio
2. Once the sites have been created, stop authoring
3. Delete the Indexes-es folder located at CRAFTER_HOME/data/indexes-es
4. Start authoring back up
5. Once authoring is successfully back up, tail the crafter-deployer.out logs
6. Once tailing the logs, make the following API call to trigger the deployment  `curl -X POST 'http://localhost:9191/api/1/target/deploy-all' -d '{"reprocess_all":true}' -H 'content-type: application/json'`
7. See errors in crafter-deployer.out logs

## Expected behavior
The API call to trigger deployment should result in a successful re-index and deployment of each site.

## Screenshots
N/A

## Logs
https://gist.github.com/AndyReiter/7928282d5c5e0c24192c8d43a72e267b

### Version
Studio Version Number: 3.1.11-SNAPSHOT-2e062c
Build Number: 2e062cde0f7f970c253e6454b52c0563e3895a2e

### OS
Any

### Browser
Any

**Comment by jdrossl** [comment]
@AndyReiter I have a couple of questions:

- For step 1: how many sites did you use to reproduce the issue?
- For step 6: the parameter should be `reprocess_all_files`, this could explain why no docs are being indexed

**Comment by AndyReiter** [comment]
@jdrossl I used 7 sites to reproduce this issue.

**Comment by jdrossl** [comment]
I'm not able to reproduce the timeout issue, these are the steps I followed:
- Clean install of crafter (tried both `support/3.1.x` & `support/3.1.x-es-7`)
- Create 30 editorial sites
- Stop crafter, delete `data/indexes-es`, start crafter
- Trigger the reindex for all targets (60 targets total), this returns an error because of the pool size
- Stop crafter, delete indexes again, increase pool size, start crafter
- Trigger the reindex for all target, this time no errors

**Comment by russdanner** [comment]
The workaround is to increase the pool size
The low priority bug is that the pool size should be allowed to be smaller than the number of sites. The system should use the pool and sites that do not fit in to the pool concurrently should be set aside until there is "room" to take on the work.
