### ISSUE TITLE
[studio-ui] Implement JWT

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4430]
Front-end sub-tasks for #4361

- [x] Remove all logic for login & logout present in the React app, everything will be handled by Spring now:
  - The login form should do a regular post to `/login`
  - The logout button should do a redirect to `/logout`
  - Spring will redirect to the original requested URL to launch the React app
- [x] If there is no JWT perform a call to a new API (TBD) to obtain the JWT & expire time (if the call fails show the login again)
- [x] Store the JWT **in memory only**, and set a timer to renew before the expire time (to the same API in the previous step)
- [x] Include the new header `Authentication: Bearer <JWT>` for all API requests
- [x] Remove the calls for validate-session API

Notes:
- It is possible we can remove the XSRF token from the API calls, but we need to look into it (it might still be needed to protect the refresh token API)

**Comment by rart** [comment]
@jdrossl  
- How does JWT changes "Reset password" processes?
- How does JWT changes "Recover password" processes?

Provided you're not logged in at those stages, API calls issued by the UI are unable to have a token/header. Are those endpoints public or will they require to be changed to posts to a spring URL like login and logout?

**Comment by jdrossl** [comment]
@rart all public URLs will continue to work as usual, no changes are needed

**Comment by rart** [comment]
@jdrossl good. But what I'm referring to are the APIs that power password recovery mechanisms. Those are APIs, they aren't postbacks.

**Comment by jdrossl** [comment]
@rart here is the list of public URLs, anything in there will work without the JWT https://github.com/craftercms/studio/blob/develop/src/main/resources/crafter/studio/studio-config.yaml#L243

**Comment by rart** [comment]
Completed.
