### ISSUE TITLE
[studio] Folder renames causes content to get deleted from published repository and live site

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4436]
## Describe the bug
Certain folder rename/content publish sequences cause content to get deleted from the published repository. 

## To Reproduce
1. Create a site from an empty blueprint 
2. In the UI Create a folder "mainfolder" 
3. Create two folders under the mainfolder called "subfolder1" and "subfolder2" 
4. Create two pages: "page1" in "subfolder1" and "page2" in "subfolder2" 
5. Publish both pages 
6. Rename "mainfolder" --> "mainfolder-renamed" 
7. Publish "page2". Do not publish "page1" at this point 
8. Rename back "mainfolder-renamed" --> "mainfolder" 
9. Publish "page1". Notice "page1" gets deleted from the published repo. It will not exist in the live site at all 
10. Publish "page2". Notice that "page2" gets moved back to "mainfolder"

## Expected behavior
Both page1 and page2 would exist under "mainfolder". Renaming folders should not cause content to get deleted from published repository and live site.

## Screenshots
Screenshot of page hierarchy: 
![image](https://user-images.githubusercontent.com/42217570/101662606-b62d1a00-3a17-11eb-97c0-3309104a9840.png)

Screenshot of the published directory after the publish of "page1" in step 9:
![image](https://user-images.githubusercontent.com/42217570/101669897-86cedb00-3a20-11eb-8ada-ae3a75c26c12.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.10E-57fdd3
Build Number: 57fdd32fa5e6a50c05f7361be74c551477fe78a4

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2311
https://github.com/craftercms/studio/pull/2312

**Comment by AndyReiter** [comment]
Validated @dejan-brkic

**Comment by russdanner** [comment]
Confirmed
