### ISSUE TITLE
Repository Path

### ISSUE THREAD

**Issue by kyleprichett** [craftercms/craftercms#444]
Can I upload a file to a custom repository path?

When I save files to any path besides /static-assets/* I get upload errors.

I'd like to save to a new path such as /media/*

Any Suggestions?

**Comment by russdanner** [comment]
Hi Kyle,

1. Easiest way to handle this is start with sub folders under static-assets like /static-assets/site vs /static-assets/media and then configure the authoring tools so it can only see static-assets/media

2. If you go the route of /media as a sibling to /static-assets: 
A: n preview where tomcat serves the content you will need to add another servlet mapping path in crafter engine's web XML
 
B: In production where apache is serving static assets, you will need to back up the apache set the docroot and proxy pass settings properly so static assets and media are both served by apache rather that tomcat

Method #1 should meet your needs and is the most supportable upgrade wise.
