### ISSUE TITLE
[studio-ui] Publish dialogs missing/mislabeled items

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4440]
## Describe the bug
- Reject publish request dialog is missing "Submitted By" section in 3.2
- The `Approve & Publish` and `Request Publish` dialogs uses `Environment` instead of `Publishing Target`

## To Reproduce
1. As a user with `author` role, edit a page then send a `Request Publish` for the edited page.  Notice in the dialog
<img width="1310" alt="Screen Shot 2020-12-10 at 3 05 20 PM" src="https://user-images.githubusercontent.com/25483966/102354591-c776a900-3f78-11eb-8987-12b3a6cb064c.png">

2. Login as `admin`  then preview the page requesting to be published or go to the dashboard and look in the `Items waiting for approval` widget and select the page requesting to be published there.  Click on `Reject` from the context nav
3. Notice there is no `Submitted by` section

<img width="1320" alt="Screen Shot 2020-12-10 at 3 09 07 PM" src="https://user-images.githubusercontent.com/25483966/102347209-123ef380-3f6e-11eb-8371-5bbf800b7d6c.png">

4. Click on `Approve & Publish`, notice in the dialog it uses `Environment` instead of `Publishing Target`

## Expected behavior
There should be a `Submitted by` section like in 3.1
<img width="822" alt="Screen Shot 2020-12-11 at 9 58 00 AM" src="https://user-images.githubusercontent.com/25483966/102347337-46b2af80-3f6e-11eb-9056-3b4609f947a6.png">

The `Approve & Publish` and `Request Publish` dialogs should use `Publishing Target` instead of `Environment`

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.2.0-SNAPSHOT-141d9b
Build Number: 141d9bae48ed668928e698efe2666a6f76fb4261
Build Date/Time: 12-15-2020 10:02:43 -0500

### OS
macOS 10.15.6

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
Fixed environment label.

@jvega190 please add submitted by to reject dialog.

**Comment by alhambrav** [comment]
Verified.
