### ISSUE TITLE
[deployer] Support running simple Groovy scripts as processors

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4443]
Support running Groovy scripts as processors. These scripts should be loaded from `CRAFTER_INSTALL/crafter-deployer/processors/scripts`. Pass the normal processor parameters as global variables and use the return value as the new change set.

**Comment by avasquez614** [comment]
@jdrossl can we maybe save the processor's `Configuration` from the `doInit`, and then pass it to the script as a `configuration` variable? That would be extremely helpful

**Comment by jdrossl** [comment]
@avasquez614 how about an additional key `scriptConfiguration` to avoid exposing the whole object?

**Comment by sumerjabri** [comment]
Verified by @alhambrav
