### ISSUE TITLE
[studio-ui] Show all actions that apply to item on Sidebar based on permissions and state.

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4444]
## Describe the bug
- The options listed for an item in live state on the Sidebar still lists `Publish` and `Schedule`.
- `Request Publish` option is not available on the Sidebar for user author

## To Reproduce
1. Open the `Sidebar`, then click on the three dots next to an item in `live` state
2. Notice `Publish` and `Schedule` is available from the options.  In the example below, the three dots next to the `Latest Articles Widget`, a component, was clicked.
<img width="479" alt="Screen Shot 2020-12-10 at 10 36 57 AM" src="https://user-images.githubusercontent.com/25483966/102369906-7b346480-3f8a-11eb-9f6f-0c080fb4ddd2.png">
  Take note of all the options available for a component as shown above.

3. Log in as a user with `author` role
4. Edit a page then save your changes.
5. On the `Sidebar`, click on the three dots next to the page you just edited, notice that `Request Publish` is not available.
<img width="478" alt="Screen Shot 2020-12-10 at 2 16 10 AM" src="https://user-images.githubusercontent.com/25483966/102371055-c9963300-3f8b-11eb-8d8a-94d00d311fb0.png">

6. Notice the the options available for a page as shown above is not the same as the options available for a component

## Expected behavior
Show all actions that apply to item on Sidebar based on permissions and state.

Also, should we make the options available for pages and components the same? As shown in the images above for a component and a page, the options available is not the same.

There should be a `Request Publish` option available for the author user when clicking on the three dots next to an edited item on the `Sidebar`

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.2.0-SNAPSHOT-141d9b
Build Number: 141d9bae48ed668928e698efe2666a6f76fb4261
Build Date/Time: 12-15-2020 10:02:43 -0500

### OS
macOS

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
Depends on https://github.com/craftercms/craftercms/issues/4359 (specifically, https://github.com/craftercms/craftercms/issues/3952)

**Comment by sumerjabri** [comment]
@rart is this no longer needed given AA?

**Comment by rart** [comment]
Possibly. It is a little duplicative of - at least - 2 other tickets that also point to available actions.

Now that available actions is in, we could (A) assign back to Vita for validation and then tracking issues with AA – the report suiting for testing AA. We may also close (B) and start with a fresh ticket or one of the existing. My plan was A, but either works; up to you, @sumerjabri
