### ISSUE TITLE
[studio-ui] Design & implement the Access Token Management UI

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4447]
Front-end sub-tasks for #4361

Studio users can have a new permission `manage_access_token`

This should make available a new section to create, update and delete access tokens using the new `/api/2/security/tokens` API https://app.swaggerhub.com/apis/craftercms/studio_3_2/3.2.0.8#/security/getAccessTokens

Note: the API will only return the value of the token once after it is created, the UI should show a notice to the user warning to store it in a secure place because it can't be recovered

**Comment by rart** [comment]
@aachavarria see 3.2 > Token Management on Figma.

**Comment by rart** [comment]
Verified
