### ISSUE TITLE
[studio] Cluster: Remote removed from a node should remove it in all cluster nodes. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4454]
## Describe the bug
Similar to https://github.com/craftercms/craftercms/issues/4299, when we remove a remote from a cluster node, the remote should be removed from all nodes. 

## To Reproduce
1. Add a remote to any site in a cluster.
2. Remove the remote
3. Check Remote Repo in all nodes

## Expected behavior
Remote should be removed in all cluster nodes. 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.12-SNAPSHOT`

### OS
Ubuntu 20.04

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
No longer relevant with the new clustering system.
