### ISSUE TITLE
[studio] Blob store not handling well files without extension

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4456]
## Describe the bug
Blob files for static assets without file extension don't end in `.blob`

## To Reproduce
1. Set up a blob store for a site
2. Upload a file without an extension to the blob store path (e.g. upload `coffee` to `/static-assets/blobs/images`)
3. Go to the file path inside the site repository from your CLI/file browser.

You should see that the blob metadata file is in there but has no extension (e.g. `coffee` instead of `coffee.blob`)

## Expected behavior
Blob metadata files for files without an extension should end always in `.blob`.

**Comment by alhambrav** [comment]
Verified fixed.
