### ISSUE TITLE
[studio-iu] Publishing and Log console within Site Config do not render properly on large screens

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4458]
## Describe the bug
The publishing console and log console tools in site config do not always render fully when the user first selects them.
The conditions seem to be related to view port size.

## To Reproduce
1. Open an incognito browser and navigate to Crafter Studio
2. Full screen the browser
3. Go to a site's Site Config and click on publishing
4. Note that the tool is selected but nothing renders. If you resize the window the UI for the tool will appear

## Expected behavior
The tools should render properly all the time regardless of viewport size

## Screenshots
N/A

## Logs
N/A

### Version
3.1.11+

### OS
Any

### Browser
Observed in Chrome

**Comment by sumerjabri** [comment]
@russdanner @rart I'm not sure if this applies to 3.2 or not, the SiteConfig may change even for older sites. @rart if we plan on keeping the old SiteConfig for old sites, then we must add this fix to 3.2 as well.

**Comment by rart** [comment]
@jvega190 please apply to 3.2 as well.

**Comment by russdanner** [comment]
Not able to replicate
