### ISSUE TITLE
[studio-ui] Key-value-list dialog doesn't add scrollbar when large

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#446]
When adding many key-value-list items, the dialog doesn't add a scrollbar to accommodate. Please see attached screenshot.

Please fix for 2.5.x and 3.x.
![screen shot 2017-02-10 at 9 21 59 am](https://cloud.githubusercontent.com/assets/3931908/22829916/b153174e-ef72-11e6-89dc-f1a4307bd2a2.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/242
