### ISSUE TITLE
[studio-ui] Cannot create component or taxonomy content

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4466]
## Describe the bug
Cannot create component or taxonomy content when right-clicking on the Sidebar and selecting `Create Content`

## To Reproduce
1. Open the `Sidebar` and navigate to `components/article-widgets` folder
2. Right click on the `article-widgets` folder and click on `Create Content`
3. Notice that it opens a dialog to browse for a template instead of opening the form for `article-widgets` and there are no templates available listed
<img width="1080" alt="Screen Shot 2021-01-14 at 3 46 25 AM" src="https://user-images.githubusercontent.com/25483966/104624301-66b6bb00-5661-11eb-8451-e4ad85911685.png">

4. Try creating content with the other components or taxonomy and notice the same thing as mentioned above.

## Expected behavior
User should be able to create new component/taxonomy content

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
Here's a short clip showing user cannot create content for components and taxonomy in new UI:
https://www.loom.com/share/45e190503c52461a80ccab8287286b10

### Version
Studio Version Number: 4.0.0-SNAPSHOT-6a1a25
Build Number: 6a1a25316c7725e874ad331c3d8b19e285d502f1
Build Date/Time: 01-14-2021 10:44:06 -0500

### OS
macOS 10.15.6

### Browser
Chrome browser

## Additional context
In the 3.1 version of Studio, when you right click on the `article-widgets` folder and select `New Content`, the form for article-widgets opens
<img width="1307" alt="Screen Shot 2021-01-14 at 3 40 39 AM" src="https://user-images.githubusercontent.com/25483966/104624490-a382b200-5661-11eb-8818-c7ef20a1110c.png">

**Comment by jvega190** [comment]
Created this ticket to discuss the content-types not showing https://github.com/craftercms/craftercms/issues/4473

**Comment by alhambrav** [comment]
Verified fixed.
