### ISSUE TITLE
[studio] Site policy issues

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4472]
## Describe the bug
Using the following config, creating a folder on `/site/website` with a name that violates the policy returns the same policy-violating name (i.e. the `modifiedValue` prop of the response, does not contain the fixed value).
```xml
<site-policy>
    <statement>
        <target-path-pattern>/site/website/.*</target-path-pattern>
        <permitted>
           <path>
                <source-regex>([a-z\-/\.]*)</source-regex>
                <target-regex caseTransform="lowercase">$1</target-regex>
            </path>
        </permitted>
    </statement>
</site-policy>
```

## To Reproduce
1. Create a Site Policy using the config above
2. Attempt to create a folder that goes against the policy
3. Notice the response `modifiedValue` field, has the same wrong name

## Expected behavior
When the policy check result is "allowed with modifications", the `modifiedValue` prop should contain the new adjusted value

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.2.0-SNAPSHOT-dc4a8f

Build Number: dc4a8f5e54d5253764e518a90b4a8d1a515d13a1

Build Date/Time: 01-12-2021 13:05:57 -0600

### OS
macOS Catalina 10.15.7

### Browser
Chrome 87.0.4280.141 

## Additional context
{{Add any other context about the problem here.}}

**Comment by jdrossl** [comment]
@aachavarria ping me when you are going to verify this because the config was wrong

**Comment by aachavarria** [comment]
There are still a issue using this config:
```
 <!-- Remove numbers in the path -->
    <statement>
        <target-path-pattern>/static-assets/remove-numbers.*</target-path-pattern>
        <permitted>
            <path>
                <source-regex>\d</source-regex>
                <target-regex/>
            </path>
        </permitted>
    </statement>
```
Creating the remove-numbers folders returns a modified value

**Comment by aachavarria** [comment]
verified
