### ISSUE TITLE
[studio] Get children API returns `.keep` files

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4475]
## Describe the bug
Get children API returns `.keep` files. These aren't really content so most likely we should exclude them or properly manage them.

## To Reproduce
1. Fetch a path that has a .keep file
2. See response

## Expected behavior
Keep files — or any other hidden/non-content — files should be excluded from the response.
Pagination should take this into account.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Mac OSX

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2368

**Comment by aachavarria** [comment]
Verified.

**Comment by rart** [comment]
Issue is back.

**Comment by rart** [comment]
Verified.
