### ISSUE TITLE
[Studio] Global Config changes for Simple Kubernetes Authoring setup not persisting in tomcat container

### ISSUE THREAD

**Issue by dokuboyejo** [craftercms/craftercms#4483]
After setting up authoring stateful deployment with persistent volume, based on https://github.com/craftercms/kubernetes-deployments/tree/master/authoring/simple, the ldap config changes made in /studio/#/globalMenu/global-config doesn't persist in the tomcat container. I verified this by restarting the pods, and then checking the content of `/opt/crafter/bin/apache-tomcat/shared/classes/crafter/studio/extension/studio-config-override.yaml` in the container, and could see that the changes weren't effect

**Comment by russdanner** [comment]
Hi Do, this issue repository is intended for software bugs, feature requests and tasks.  
As this issue pertains to installation concerns we'll close this ticket here and assist in opening a new version of it in the appropriate channels.
