### ISSUE TITLE
[studio] External commits do not trigger the appropriate events for the Deployer

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4485]
## Describe the bug
When Studio detects an external commit in a site repo the Deployer is not notified about the new changes.

## To Reproduce
1. Create a site from editorial
2. Using an IDE/editor change the text of any file, for example `site/website/index.xml`
3. Commit the change
4. Try to search for the new text in preview or authoring

## Expected behavior
When new commits are processed from the repo Studio should trigger a deployment for both the authoring & preview targets in the Deployer

### Version
4.0.0-SNAPSHOT
3.1.x

### OS
Linux

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2372
https://github.com/craftercms/studio/pull/2373

**Comment by jdrossl** [comment]
Verified
