### ISSUE TITLE
[studio-ui] RTE 5 toolbar disappears when anything is clicked

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4486]
## Describe the bug
RTE toolbar disappears when anything on the toolbar is clicked. See attached videos on how to reproduce the issue.

## To Reproduce
1. Create new site based on Editorial
2. Right click and edit the home page.
3. Modify the text in the RTE 5 then try to click something in the RTE toolbar.

## Expected behavior
RTE 5 toolbar should function as a normal toolbar instead of disappearing. 

## Screenshots
Screen recordings from the client:

https://user-images.githubusercontent.com/42217570/105767113-ac5c6900-5f28-11eb-924a-35b618635b1b.mov

https://user-images.githubusercontent.com/42217570/105767155-b5e5d100-5f28-11eb-911b-dde8f9a9a061.mov

## Logs
N/A

### Version

Studio Version Number: 3.1.10E-57fdd3
Build Number: 57fdd32fa5e6a50c05f7361be74c551477fe78a4

Studio Version Number: 3.1.12E-b128ef
Build Number: b128ef05088ba2239245220a5148c2e3a97d7468

### OS
Windows and macOS Mojave Version 10.14.6

### Browser
Firefox version 84.0.2 (64 bit)

**Comment by russdanner** [comment]
If this bug is a result of the toolbar being anchored to the top of the dialog we can stop doing this 
instead: anchor the toolbar to the top of the control (but never scroll the toolbar off the screen)

**Comment by jvega190** [comment]
@russdanner @AndyReiter we did change the toolbar to be on top of the control, and made it stick to the top of the control.

**Comment by AndyReiter** [comment]
Confirmed.
