### ISSUE TITLE
[studio] get_delete_package API should return unique items

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4489]
## Describe the bug
The API2 get_delete_package is returning duplicated items in the response. The response should only contain unique dependent items. 

## To Reproduce
1. Create a site from Editorial BP
2. Execute the request `http://localhost:8080/studio/api/2/content/get_delete_package?siteId=ed1&paths=/site/components/articles-widget/latest-articles-widget.xml,/site/components/articles-widget/related-articles-widget.xml,/site/components/contacts/contact-widget.xml`
3. See duplicated items in response
```
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "items": {
        "dependentItems": [
            "/site/components/left-rails/left-rail-with-related-articles.xml",
            "/site/components/left-rails/left-rail-with-related-articles.xml",
            "/site/components/left-rails/left-rail-with-latest-articles.xml",
            "/site/components/left-rails/left-rail-with-latest-articles.xml",
            "/site/components/left-rails/left-rail-with-no-articles.xml"
        ],
        "childItems": []
    }
}
```

## Expected behavior
The items in `dependentItems` should be unique. 

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/105870034-774e2600-5fbd-11eb-9a7e-8fce2fa5f6ff.png)

## Logs
N/A

### Version
`4.0.0` 

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2365

**Comment by yacdaniel** [comment]
Verified fixed.
