### ISSUE TITLE
[studio-ui] Prevent saving invalid YAML files

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4492]
The UI should not allow users to save invalid YAML files in `Global Menu > Global Config`

The editor should have the same behavior as invalid XML files:

![Screenshot from 2021-01-27 10-40-06](https://user-images.githubusercontent.com/1236955/106023214-37a23f80-608c-11eb-9b6a-b0575550178a.png)

Front-end task for https://github.com/craftersoftware/craftercms/issues/219

**Comment by rart** [comment]
@sumerjabri @jdrossl the web APIs have native XML capabilities; this is not the case for YAML. We would need to find the appropriate third party library and add it to the collection of scripts loaded by studio (on the browser).

I'll do some research to explore options. My hope is that the code editor publishes the validity of the document but haven't seen this — I don't think it does.

Does the backend have a yaml lib that could be published as an API to validate?

Please confirm desired approach & thoughts.

**Comment by jdrossl** [comment]
@rart we added validation in the API itself so the write will fail and the UI could display a message, but I think it would be a better experience for users if we prevent the call too

**Comment by sumerjabri** [comment]
@rart we're looking to ACE to help with this if possible, if not, the BE will fail it.

Here is a possible path to address this: tinyurl.com/2t4fthyu

**Comment by rart** [comment]
@jvega190 

On 4, change the success snack to a new snack.

On both 3 & 4, if there are errors, show them as soon as you click on the save button (i.e. don't wait until the "config save") to display the error snack.

**Comment by jdrossl** [comment]
When the file is rejected by the backend the editor remains disabled and the page needs to be reloaded to fix it

![Screenshot from 2021-02-11 14-08-47](https://user-images.githubusercontent.com/1236955/107692684-c4472300-6c72-11eb-8cb9-0cc1dcb2b324.png)

**Comment by rart** [comment]
@jdrossl how did you submit with errors?

**Comment by jdrossl** [comment]
you can see it in the screenshot `aaaaaaa`, it's a valid yaml but for us that would cause an issue because we load it as a map

**Comment by jvega190** [comment]
@rart I was able to reproduce it, what is missing is enabling back the editor (that is disabled while submitting) on error. I'll work on the fix for that

**Comment by rart** [comment]
@jvega190 does the backend return a valid message? The "failure" snack doesn't specify any details around the failure. Would be good to pass on what the backend says in case of such failures. Perhaps use error dialog instead if needed.

**Comment by jvega190** [comment]
@rart it does, I'll update the message with the one returned by the backend.

**Comment by rart** [comment]
Done.

**Comment by sumerjabri** [comment]
Verified.
