### ISSUE TITLE
[studio-ui] Overlapped text with buttons in Delete dialog

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4495]
## Describe the bug
The section `Dependent Items` is not responsive, the `Edit` button is overlapping with the item text.

## To Reproduce
0. Set up Chrome device toolbar, Laptop with MDPI screen
1. Create a site from Editorial
2. Rename `articles` to some long text like `articlesverylonglonglonglonglonglonglonglonglonglonglonglonglonname`
3. Go to `Dashboard` click on `Show In-Progress Items`
4. Select all items and click `Delete`
5. Scroll down to `Dependent Item`

## Expected behavior
No overlap in text with button

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/106164436-9381cc80-614f-11eb-8d4b-d3da811e31a7.png)

## Logs
N/A

### Version
`4.0.0`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by rart** [comment]
@aachavarria add ellipsis & make sure the title attribute is set so hovering would show full name

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/106626297-2bf7c280-653d-11eb-8af3-24375aabad59.png)
