### ISSUE TITLE
[studio] Create API to retrieve "system" user permissions

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4496]
**Is your feature request related to a problem? Please describe.**
Certain permissions are not against a path; they are "system" permissions rather than item permissions. We don't have an API to retrieve those.

**Describe the solution you'd like**
Two APIs would be useful `getUserPermissions` and/or `hasPermissions`. They both serve good purpose so if possible have them both. Hopefully, they are just small variations of the same backend and implementing both doesn't represent much more effort.

**Describe alternatives you've considered**
Implement only one of the two endpoints. If `hasPermissions` is the selected option, the key is for it to answer the question for various permissions at once.

**Additional context**

**Suggested `getPermissions` API**

```ts
// [GET] /users/me/permissions

interface GetPermissionsRequest {
  // no arguments
}

interface GetPermissionsResponse {
  response: ApiResponse;
  permissions: string[];
}

// Example:
// [GET] /users/me/permissions
{
  response: { ... },
  permissions: ["create", "update"]
}
```

**Suggested `hasPermissions` API**

```ts
// [GET] /users/me/has_permissions

interface HasPermissionsRequest {
  permissions: string[];
}

interface HasPermissionsResponse {
  response: ApiResponse;
  permissions: {
    [permissionKey: string]: boolean
  }
}

// Example:
// [GET] /users/me/has_permissions?permissions=create,update,delete
{
  response: { ... },
  permissions: { 
    create: true,
    update: true,
    delete: false
  }
}
```

**Comment by sumerjabri** [comment]
@dejan-brkic ping me to discuss options.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2389

**Comment by rart** [comment]
`has_permissions` was implemented the `permissions` argument as the body of the GET request. Browsers, [per spec](https://xhr.spec.whatwg.org/#the-send()-method), won't allow a GET request to have a body. We need to either make this into a POST, or make it a query string argument (QSA) and accept it's limitation. If we make it a QSA, we can change the permissions argument to be CVS to reduce the extra length that JSON introduces.

@see
https://xhr.spec.whatwg.org/#the-send()-method
<img width="660" alt="image" src="https://user-images.githubusercontent.com/3928341/108078209-af510200-706d-11eb-80a2-44debb8de771.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2412

**Comment by rart** [comment]
Verified (changed to post)
