### ISSUE TITLE
[studio] Add bulk getSandboxItems API calls

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4498]
Please add two new API calls:
- Get Sandbox Items by Paths
- Get Sandbox Items by IDs

Must include a parameter called: "preferContent" which defaults to false. This parameter will tell the backend to return a folder as content if it has `index.xml` (making it a content item not a folder, semantically speaking)

The APIs will return SandboxItem (not DetailedItem) data structure per item requested. This will speed up the Sidebar navigation widgets.

Tasks:
- [x] OAS Spec
- [x] Implement BE
- [x] Implement UI

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2377

**Comment by rart** [comment]
@aachavarria please finish integration
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.3#/content/getSandboxItemsByPath

**Comment by rart** [comment]
👍🏻
