### ISSUE TITLE
[studio] Remove the property `parent` from Children By *

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4499]
We no longer need the property "Parent" from the response of Children By *, please remove from docs and code:
- [x] Remove from OAS
- [x] Remove from UI
- [x] Remove from BE

Related to: https://github.com/craftercms/craftercms/issues/4498

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2375
