### ISSUE TITLE
[studio-ui] Language choice doesn't work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#450]
Login to Studio using English as the language.
Logout.
Login using Spanish as the language, note the language stays English until you refresh the browser.

Please fix for both 2.5.x and 3.0.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/244

**Comment by jvega-crafter** [comment]
Done on both 2.5.x and 3.0
