### ISSUE TITLE
[studio] Update Item By * to have a new preferContent flag

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4500]
Add a parameter to Item By * API calls to have a preferContent parameter (default false to maintain current behavior), this will return a content item if there is an `item.xml` in the folder.

See https://github.com/craftercms/craftercms/issues/4498 for more context.

Tasks:
- Update OAS
- Update BE

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2374

**Comment by sumerjabri** [comment]
@rart close this ticket if you're able to use `preferContent` flag in the API calls listed

**Comment by rart** [comment]
👍🏻
