### ISSUE TITLE
[studio] Item retrieval APIs (item_by*, children_by*) return systemType 'unknown' for config files

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4502]
## Describe the bug
Item retrieval APIs (item_by*, children_by*) return systemType 'unknown' for config files

## To Reproduce
1. Call `/studio/api/2/content/item_by_path?path=%2Fconfig%2Fstudio%2Fsite-config.xml&siteId=editorial`
2. Review `response.item.systemType`. Same deal for other item retrieval APIs (e.g. children_by_*, etc).

## Expected behavior
Service should return a valid system type (e.g. `config`)

## Screenshots
<img width="917" alt="image" src="https://user-images.githubusercontent.com/3928341/106609945-704b8880-6566-11eb-9bed-00b850d383b8.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Indiferent

### Browser
Indiferent

## Additional context
{{Add any other context about the problem here.}}

**Comment by phuongnq** [comment]
Sent PR to update from `file` type to the `configuration` type for `/config/**.xml` files (but not `/config/studio/content-type/**` files)

**Comment by rart** [comment]
@jvega190 please validate and update the UI to accommodate this change — I think is just typings that would need update, but check.

**Comment by jvega190** [comment]
Verified systemType for config files
