### ISSUE TITLE
[studio] Content item APIs return sytemType null for new content created

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4503]
## Describe the bug
Content item APIs(item_by_id, item_by_path) return `sytemType: null` for new content created.

## To Reproduce
1. Create a site and create new content(Page, scripts, component, any)
2. Call any of the content `item_by_*` API and use the path/id of the newly created content `http://localhost:8080/studio/api/2/content/item_by_path?path=/site/website/newpage/index.xml&siteId=editorial`
3. Check `item.systemType`

## Expected behavior
`systemType` is not null for new content created. 

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/106612368-aa009d00-652e-11eb-9725-6a8c04f32d4c.png)

## Logs
N/A

### Version
`4.0.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by yacdaniel** [comment]
this also applies for content created thru copy-paste and duplicate operations.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2381

**Comment by yacdaniel** [comment]
@dejan-brkic  `systemType` now return the appropiate item value but  `parentId` for new content created is returning `null`. could you please fix it? Thanks.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2388

**Comment by rart** [comment]
@dejan-brkic

The `label`, `creator` and `modifier` props are also null for new items (e.g. create template, upload image, create controller).

When creating a new page, the `label` is correct, but the `creator` and `modifier` are also null.

As far as the modifier, perhaps that's acceptable/debatable, but I expected modifier == creator — just like dateCreated == dateModifed.

**Comment by dejan-brkic** [comment]
@rart Done
PR:
https://github.com/craftercms/studio/pull/2396

**Comment by rart** [comment]
👍
