### ISSUE TITLE
[studio] clockPublisherTask allocates too much memory per cycle

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4507]
## Describe the bug
clockPublisherTask allocates too much memory per cycle

## To Reproduce
1. Start Studio with a few sites already created
2. See memory allocations over time

## Expected behavior
clockPublisherTask has a more stable memory footprint

## Screenshots
![image](https://user-images.githubusercontent.com/3931908/106814506-7f9f0480-6640-11eb-8c4d-cbd70039a75c.png)

## Logs
N/A

### Version
4.0.0-SNAPSHOT (Feb 3 2021)

### OS
Linux, Ubuntu

### Browser
Didn't use a browser

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2384

**Comment by sumerjabri** [comment]
@dejan-brkic please wire to the existing cache:
```
    <bean id="configurationCache" class="org.craftercms.commons.cache.GuavaCacheFactoryBean">
```

https://github.com/craftercms/studio/blob/develop/src/main/resources/crafter/studio/studio-services-context.xml#L1357

**Comment by dejan-brkic** [comment]
Done
PR:
[studio] Studio XML configuration is loaded in an inefficient manner wasting memory
