### ISSUE TITLE
[studio] Content item APIs(item_by_*, children_by_*) doesn't return the new name when a folder is renamed. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4508]
## Describe the bug
Content item retrieval APIs doesn't return the new `label` and `previewUrl`  of a renamed folder.

## To Reproduce
1. Rename a folder
2. Use any of the `item_by_*` and `children_by_*` content APIs
3. Check response

## Expected behavior
The new name of the renamed folder should be in the `label` and `previewUrl` of the response.

## Screenshots
`folder1` is the old name, `folder12` is after renaming.
![image](https://user-images.githubusercontent.com/6722074/106905308-c5e87800-66c1-11eb-84ae-034ebe271159.png)

## Logs
N/A

### Version
`4.0.0`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2386

**Comment by yacdaniel** [comment]
@dejan-brkic renaming a folder under `static-assets` or `pages` is not updating the `preview_url` of the items in the folder. 
![image](https://user-images.githubusercontent.com/6722074/107446092-57614b00-6b03-11eb-98e7-b282c4545c8e.png)

**Comment by yacdaniel** [comment]
Verified fixed.
