### ISSUE TITLE
[studio-ui] RTE wrap for long lines of code or text

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4509]
**Is your feature request related to a problem? Please describe.**
When having long lines in code view, the RTE displays a horizontal scrollbar which can be seen in the screenshot provided below. This default functionality makes it difficult for users to modify their long lines of code in the RTE as it is difficult to navigate using the scroll bar.

**Describe the solution you'd like**
The RTE should wrap the code down to the next line instead of keeping it all on one single line that requires a horizontal scroll bar to navigate. 

**Describe alternatives you've considered**
N/A

**Additional context**
Example of the current functionality with a horizontal scroll bar: 
![image](https://user-images.githubusercontent.com/42217570/106912434-026fa000-66d1-11eb-89d1-27a81584d647.png)

**Comment by sumerjabri** [comment]
@jvega190 please also do this:
- [ ] Updated default and Crafter Software managed BPs to have the correct defaults

@russdanner should we change the defaults in existing sites via UM?

**Comment by sumerjabri** [comment]
@russdanner didn't want UM to update this

@jvega190 assign this ticket back if your work is complete.
