### ISSUE TITLE
[studio] Error in GitContentRepository when a site is deleted and StudioAuditLogProcessingTask is running.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4512]
## Describe the bug
An error is thrown in `GitContentRepository` when a site is deleted and `StudioAuditLogProcessingTask` is running.

## To Reproduce
1. Enable `DEBUG` log level to `StudioAuditLogProcessingTask`
2. Create a site from https://github.com/crafter-qa/editorial-1000commits 
3. When creation of site finish, wait until a cycle of `StudioAuditLogProcessingTask` starts
4. Remove the site intermediately after `StudioAuditLogProcessingTask` start running a new cycle. 

## Expected behavior
No errors are thrown when the site is deleted. 

## Screenshots
N/A

## Logs
https://gist.github.com/yacdaniel/ec8f41c5840f4bbeddaf07718b95b5bc

### Version
`3.1.12` and `4.0.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
The issue can not be reproduced for 3.1.x version:
```
Studio Version Number: 3.1.15-SNAPSHOT-8f9aa1

Build Number: 8f9aa1e4fc33f56fa83cdb51c4459d40c2b84c64
```

**Comment by sumerjabri** [comment]
@yacdaniel please validate for 3.1

**Comment by sumerjabri** [comment]
Audits will no longer be a background job in 4.2, so I am closing this ticket.
