### ISSUE TITLE
[studio] item_by_path API failing with existing item/path

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4514]
## Describe the bug
On commercetools-bp, when going to Site Explorer, the API `item_by_path` is returning a 500 error on an existing path.

## To Reproduce
1. Create a site based on this repository (branch: next) https://github.com/jvega190/commercetools-blueprint.git
2. (commercetools-bp needs an account to work, please ping me if you need details)
3. Go to Preview -> Site Explorer
4. Check on developer tools API failing.
5. See error on tomcat log.

## Expected behavior
item_by_path shouldn't fail on existing items/paths.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/jvega190/92da13815d4c3c01f23915505333385d

### Version
Crafte 4.0.0

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Already fixed with https://github.com/craftercms/craftercms/issues/4515

**Comment by jvega190** [comment]
@dejan-brkic I created a new site based on the bp, and now I'm getting a 200 response code, but with null item

![Screenshot from 2021-02-10 11-25-12](https://user-images.githubusercontent.com/18267471/107548586-76f48400-6b94-11eb-831c-acab261c2ee3.png)

**Comment by dejan-brkic** [comment]
Your remote repository does not have the initial commit empty. The workaround is to create a site as an orphan.

**Comment by sumerjabri** [comment]
We will try a different way to process commits.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2397

**Comment by jvega190** [comment]
Verified fixed
