### ISSUE TITLE
[studio] Item_by_path returning 0 for availableActions

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4516]
## Describe the bug
Using Item_by_path with any Path is returning 0 for availableActions

## To Reproduce
1. Open Dev Tools
2. Go to Preview
3. Check the network tab on dev tools
4. See Item_by_path response

## Expected behavior
Using Item_by_path should return a valid value for availableActions

## Screenshots
<img width="681" alt="Captura de Pantalla 2021-02-09 a la(s) 09 31 35" src="https://user-images.githubusercontent.com/10813283/107386629-a7b3bb00-6ab9-11eb-8d8b-8fdf2b8ef455.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Crafter 4.0.0

### OS
macOs Catalina

### Browser
Any browser

## Additional context
Additional calling getChildren API with /site/website/style/index.xml is returning 1572900 as availableActions, and this one does not includes many options for example 'read'.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2392

**Comment by rart** [comment]
@dejan-brkic still a couple of issues

The service two services (itemBy*, childrenBy*) return different results for the same item

`/studio/api/2/content/item_by_path?path=%2Fsite%2Fwebsite%2Findex.xml&preferContent=true&siteId=editorial-neue`
Style: 16954572381094400 (page)

`/studio/api/2/content/children_by_path?path=%2Fsite%2Fwebsite&siteId=editorial-neue`
Style: 1573375 (page)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2400

**Comment by rart** [comment]
👍

**Comment by aachavarria** [comment]
@dejan-brkic still a couple of issues:

1)The itemBy* on Home page returns a bitmap that includes Duplicate, Cut, Copy, Delete.  Those should no be options for Home page

/studio/api/2/content/item_by_path?path=%2Fsite%2Fwebsite%2Findex.xml&preferContent=true&siteId=editorial-neue
Home: 1573375 (page)

2) The itemBy* on Pages returns a bitmap that doesn't have EditTemplate/Controller and History

/studio/api/2/content/item_by_path?path=%2Fsite%2Fwebsite%2%style%2Findex.xml&preferContent=true&siteId=editorial-neue
Style: 1573375 (page)

3) The itemBy* on Folder returns a bitmap that contains View: view should no be a option for folders

/studio/api/2/content/item_by_path?path=%2Fsite%2Fwebsite%2Farticles&preferContent=true&siteId=editorial-neue
Articles: 507 (folder)

**Comment by dejan-brkic** [comment]
@sumerjabri @rart @aachavarria These latest issues are the result of mapping user permissions to available actions and filtering them by possible actions per type of object/item. We don't have the final and definite version of these mappings and filters. I think we need a separate ticket and document/spreadsheet to address these mappings.

**Comment by rart** [comment]
Makes sense. Closing in favour of a future ticket to track the right actions per item per state.

fyi @yacdaniel @alhambrav
