### ISSUE TITLE
[studio-ui] Push to remote request is failing with jackson deserialization error

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#4518]
## Describe the bug
Push to remote is failing

## To Reproduce

1. Create a new authoring site e.g. test-site
2. Create a repository
3. Go to http://localhost:8080/studio/site-config?site=test-site#tool/repository
4. Create the remote repository to the site
5. Push the site to the repository

## Expected behavior
Push to remote should succeed in pushing the git repo

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 11] (through reference chain: org.craftercms.studio.model.rest.PushToRemoteRequest["siteId"])
```
https://gist.github.com/dejan-brkic/c4c5eaf4c347dca9d650992a2126dee3

### Version
4.0.0-SNAPSHOT

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by jdrossl** [comment]
This is an issue in the UI, the request body has the wrong format. The API returns the expected message

 `
[ERROR] 2021-02-11T16:05:02,628 [http-nio-8080-exec-9] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/repository/push_to_remote failed with response: ApiResponse{code=1001, message='Invalid parameter(s)', remedialAction='Check API and make sure you're sending the correct parameters', documentationUrl=''}
`


![Screenshot from 2021-02-11 10-10-00](https://user-images.githubusercontent.com/1236955/107663816-67874080-6c51-11eb-9ddf-2f7ff79fece1.png)

**Comment by dejan-brkic** [comment]
Verified
