### ISSUE TITLE
[studio] Nextify out of box blueprints

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4519]
**Is your feature request related to a problem? Please describe.**
Update out of box blueprints (editorial, empty, headless-store, headless-blog) to use next ICE mechanisms.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/4435

**Comment by jvega190** [comment]
RL blueprints PRs:
https://github.com/rivetlogic/craftercms-bp-gardeners/pull/28
https://github.com/rivetlogic/craftercms-bp-videogallery/pull/27
https://github.com/rivetlogic/craftercms-bp-singlepage-brochure/pull/13
https://github.com/rivetlogic/craftercms-bp-restaurant/pull/23
https://github.com/rivetlogic/craftercms-bp-pizza/pull/9
https://github.com/rivetlogic/craftercms-bp-hotelinfo/pull/33
https://github.com/rivetlogic/craftercms-bp-fitness/pull/44
https://github.com/rivetlogic/craftercms-bp-events/pull/33
https://github.com/rivetlogic/craftercms-bp-companyshowcase/pull/5
https://github.com/rivetlogic/craftercms-bp-artshowcase/pull/45

**Comment by rart** [comment]
@jvega190 most PRs are still in draft state

**Comment by jvega190** [comment]
@rart z-index update is because bootstrap's navbar z-index is higher than the one we use for the highlighted zone text
