### ISSUE TITLE
[studio-ui] Add missing translations for labels

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#452]
Please add missing translations for labels in Spanish and Korean (ask Lim for Korean).

See attachments for most things missing.
![screen shot 2017-02-13 at 11 29 14 am](https://cloud.githubusercontent.com/assets/3931908/22892218/cbb7bb2a-f1df-11e6-8fb0-d48f42c70007.png)
![screen shot 2017-02-13 at 11 29 04 am](https://cloud.githubusercontent.com/assets/3931908/22892219/cbb7eb90-f1df-11e6-835f-d7c9798f5e20.png)
![screen shot 2017-02-13 at 11 28 58 am](https://cloud.githubusercontent.com/assets/3931908/22892217/cbb6a94c-f1df-11e6-889c-24f492204b2f.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/327
Korean translations pending

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/362
