### ISSUE TITLE
[studio-ui] Item selector dialog for uploading/browsing a file is not displayed correctly

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4523]
## Describe the bug
When using the `item selector` with a file upload or file browse datasource, to upload/browse a file, when you click on the `Add +` , the complete dialog for uploading/browsing does not appear

<img width="904" alt="Screen Shot 2021-02-10 at 8 31 41 AM" src="https://user-images.githubusercontent.com/25483966/107973161-ded71000-6f82-11eb-84fe-05d2262138ff.png">

## To Reproduce
1. Using the website editorial bp, open the `Page - Article` content type, then in the content section of the form, add an `Item Selector` control and fill in the required properties
2. In the Data Source section, add any of the following data source and fill in the required properties: `File Browse`, `File Uploaded to CMIS Repository`, `File From CMIS Repository`, `File Uploaded to WebDAV Repository`, `File From WebDAV Repository`, `File From S3 Repository`, `File Uploaded to S3 Repository`
3. Bind the data source added in the previous step to the item selector.  Save your changes, then edit a page.

<img width="1219" alt="Screen Shot 2021-02-16 at 8 37 31 AM" src="https://user-images.githubusercontent.com/25483966/108070341-69c31380-7032-11eb-8e18-ba0568a8434f.png">

4. Scroll down to the content section of the form and click on `Add +` in the item selector added in a previous step above.
5. Notice that the dialog is not displayed completely

## Expected behavior
Dialog for item selector bound to the following data sources should be displayed correctly:
- `File Browse`
- `File Uploaded to CMIS Repository`
- `File From CMIS Repository`
- `File Uploaded to WebDAV Repository`
- `File From WebDAV Repository`
- `File From S3 Repository`
- `File Uploaded to S3 Repository`

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
v4.0.0-snapshot

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@alhambrav, done. 
I couldn't test actually uploading to most as don't know/have the setup. Also don't know all their ins and outs so please do test all their options to make sure they've been fully restored.

**Comment by alhambrav** [comment]
Verified fixed.
