### ISSUE TITLE
[docs] Document in more detail the difference between getDescriptor and getItem in Engine

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4528]
https://docs.craftercms.org/en/3.1/developers/projects/engine/api/site/content_store/item.html
https://docs.craftercms.org/en/3.1/developers/projects/engine/api/site/content_store/descriptor.html

Please indicate getDesc is deprecated in v3, and remove from v4 docs.

Get-Item retrieves items + meta-data and extracted meta-data. Get Descriptor only retrieves the descriptor.

Ping @avasquez614 for details and let's get these updated for clarity. Also, see Slack regarding how to document the returned fields.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1153 & https://github.com/craftercms/docs/pull/1154
