### ISSUE TITLE
[studio-ui] CrafterCMS information not showing in About page.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4532]
## Describe the bug
CrafterCMS information (about version, build, etc) is not showing in the about page

## To Reproduce
1. Go to 'About' page
2. See that information is not showing

## Expected behavior
CrafterCMS information should show in about page.

## Screenshots
<img width="706" alt="Screen Shot 2021-02-16 at 8 35 21 AM" src="https://user-images.githubusercontent.com/18267471/108274346-631fc380-713a-11eb-9521-b3c8fabfef94.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT-c56d39

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Verified fixed.
