### ISSUE TITLE
[studio-ui] Dark theme is not supported by Chrome on Linux

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4534]
## Describe the bug
Dark theme is not supported by Chrome when desktop is set to Dark mode.

## To Reproduce
1. Set up dark theme in SO
2. Go to Studio

## Expected behavior
Dark theme should be rendered. 

## Screenshots
N/A

## Logs
N/A

### Version
`4.0.0`

### OS
MacOS, Linux

### Browser
Chrome 88

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@rart I tested and the `useMediaQuery` hook returns false, also tried on a separate test using a style with the css media query and I got the same result. This is an issue with chromium/chrome in linux/gtk (https://bugs.chromium.org/p/chromium/issues/detail?id=998903)

**Comment by sumerjabri** [comment]
Chrome doesn't fully support dark mode. It's a Chrome thing, not a Crafter thing.
