### ISSUE TITLE
[studio] Add "About" and "Settings" options to global menu

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4535]
**Is your feature request related to a problem? Please describe.**
The global menu options "about" and "account management" are not part of the global menu items on the backend. These are options added/hard-coded by the UI. This would show the options on the "global app" sidebar helping with consistency of all of the global app views and the behaviour of the new "logo+hamburger" button.

**Describe the solution you'd like**
Add these options to the global menu for them to be part of the "system"

**Describe alternatives you've considered**

**Additional context**
Upgrade manager would need to add these options to old sites

**Comment by sumerjabri** [comment]
We decided to inject these in the UI service layer as a stepping stone towards configuring the global menu using a Sidebar config and using the Sidebar widget to drive the main menu experience.
