### ISSUE TITLE
[studio-ui] Editing repeating groups with next ICE updates model/xml incorrectly

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4539]
## Describe the bug
Editing repeating groups using the new ICE mechanisms doesn't update the model/xml correctly, saving the value outside the repeating group item.

## To Reproduce
1. Create a site using the new ICE mechanisms 
2. Go to a page with repeating group and in-line edit  an item
3. Reload page
4. See field with outdated value
5. Check xml and see that updated field is outside the repeating group.

## Expected behavior
When editing repeating groups, values should be correctly updated in model.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT-e61a10

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
Fixed. @jvega190 please verify.

**Comment by jvega190** [comment]
Verified fixed
