### ISSUE TITLE
[studio-ui] Build the Audit Log screen

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#454]
Please build the audit log viewer we discussed today. You need to use this API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/audit/get-audit-log.html

Please make sure it sits below the Users/Groups screens and is called: "Audit"

Please allow filtering by Action(s) and Usernames. The user *must* select a site-id to be able to view the audit log for that site.

Ping me if you have any questions.

**Comment by jvega-crafter** [comment]
Done, there are 2 issues pending on the audit service, need to test after fixing
https://github.com/craftercms/studio2-ui/pull/267
