### ISSUE TITLE
[studio] Bulk publishing not working in Studio with external Aurora Serverless

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4541]
## Describe the bug
When trying to bulk publish a site based on Editorial, in a Studio using an Aurora Serverless DB, the bulk publish doesn't work and a multitude of DB errors appear

## To Reproduce
1. Setup a Studio with Aurora Serverless as an external DB
2. Create a site based on Editorial
3. Bulk publish `/` to live.

You will so a lot of errors like the one shown in the attached Gist

## Expected behavior
Bulk publishing should work

## Logs
https://gist.github.com/avasquez614/04a6fa3ce336d83516ca8343e0e53a02

### Version
3.1.13

**Comment by sumerjabri** [comment]
Verified.
