### ISSUE TITLE
[studio] Replication of the published repo in a cluster with external DB not working

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4542]
## Describe the bug
The publishing repo is not replicated after creating a site in a 2 node Studio cluster with an external Aurora Serverless DB, and then publishing a file.

## To Reproduce
1. Setup a 2 node Studio cluster with an external Aurora Serverless DB 
2. Create a site based on Editorial
3. Publish the home page

If you go to the node that did the publish, you should see the `published` repo in there for the site. But if you go to the other node, there's no `published` repo.

## Expected behavior
Both nodes should have the `published` repo.

### Version
3.1.13

**Comment by dejan-brkic** [comment]
Could not reproduce the issue with `3.1.14-SNAPSHOT-309177`

**Comment by avasquez614** [comment]
Closing since we're moving to only support embedded DB
