### ISSUE TITLE
[docs] Update the plugin documentation

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4543]
https://docs.craftercms.org/en/4.0/developers/plugins/site-plugins.html is missing:
* Creating a Studio API via Groovy in a plugin and how to call it
* Consolidate this: https://docs.craftercms.org/en/4.0/search.html?q=plugin&check_keywords=yes&area=default (too many things called plugins not very consistent, especially Studio Plugins, those are replaced by this new system)

Other actions:
* Centralize the docs around plugins
* Explain everything:
  * Studio extensions: API, JS, etc.
  * Engine: API, FTL, Groovy, etc.
* The screenshots will need to be updated once the plugin screenie is updated

**Comment by alhambrav** [comment]
PR  https://github.com/craftercms/docs/pull/1246, https://github.com/craftercms/docs/pull/1258
