### ISSUE TITLE
[studio] get-user-activities.get.groovy seems to ignore the num=10 parameter

### ISSUE THREAD

**Issue by mcgitty** [craftercms/craftercms#4544]
## Describe the bug
After an account accumulated a large set of activities, opening the site dashboard will see the /activity/get-user-activities.json call take a long time to finish (almost 2 minutes for me), ignoring the pagination 'num=10' parameter.

During that time, the mysqld instance of Crafter Studio will have 98% CPU usage. Debug shows this call with parameter limit=10 lasted almost 2 minutes:

    org.craftercms.studio.impl.v2.service.audit.internal.AuditServiceInternalImpl.selectUserFeedEntries()

## To Reproduce
1. Use Groovy script to import 16,000 pieces of content using API /content/write-content.json
2. Open browser developer tool and network
3. Open Studio dashboard
4. Spinner will spin for almost 2 minutes

### 
Crafter Studio 3.1.7

### OS
MacOS

### Browser
FireFox

**Comment by russdanner** [comment]
This issue is filed against a version of Crafter that is significantly outdated. We'll need to verify this in the most recent version of Crafter first.

**Comment by sumerjabri** [comment]
@AndyReiter please test this in 3.1.15-SNAPSHOT

**Comment by AndyReiter** [comment]
Confirmed in 3.1.15-SNAPSHOT.

**Comment by mcgitty** [comment]
@AndyReiter What does "Closed" status mean? Did you confirm this issue still exist in 3.1.15-SNAPSHOT?

**Comment by AndyReiter** [comment]
Sorry @mcgitty. Yes this is confirmed fixed in 3.1.15-SNAPSHOT.
