### ISSUE TITLE
[studio-ui] Allow removal of "filename", "internal-name" and "auto-filename" controls from the form

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4550]
**Is your feature request related to a problem? Please describe.**
The "filename", "internal-name" and "auto-filename" controls cannot be removed from the form.  These controls do not have the `x` like other controls.

<img width="482" alt="Screen Shot 2021-03-02 at 9 18 55 AM" src="https://user-images.githubusercontent.com/25483966/109674311-d23ae600-7b44-11eb-9a09-e0228c9f4749.png">

If a user made a mistake and dragged those controls and realized it's not needed, there's no way to remove it from the form aside from exiting and not saving.  If the user has made other changes, then those changes would be lost

**Describe the solution you'd like**
Allow removal of "filename", "internal-name" and "auto-filename" controls from the form.  It would be nice if they can be removed somehow... Like maybe as long as one of those controls is on the form, then the others can be removed.

**Describe alternatives you've considered**

**Additional context**

**Comment by rart** [comment]
@jvega190 note the removal is authorised only when the requirement of having one is already covered.

**Comment by alhambrav** [comment]
Verified.
