### ISSUE TITLE
docs.craftercms.org current links are not working

### ISSUE THREAD

**Issue by brandonmcclure** [craftercms/craftercms#4553]
## Describe the bug
The links in this repo to docs.craftercms.org are not working at the moment. 

## To Reproduce
I click on the https://docs.craftercms.org/current link in the readme.md  and get an error:
```
this XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9X4V2Q0PCG7W5P5J</RequestId>
<HostId>v+U8wrJAjWyJqyzdKGwX7KU1qC9ULPHCOBF5nrADRmLqdwRkuxGyLxZWrFx34eIj/YWWGNuJ4RA=</HostId>
</Error>

```

## Expected behavior
It take me to the correct current version of the documentation. 

### Browser
Edge

**Comment by sumerjabri** [comment]
Fixed.
