### ISSUE TITLE
[studio] Implement Available Actions per the new design

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4556]
### Progress
- [x] Design
- [x] Implement backend
- [x] Test and validate backend
- [x] UM update global/configuration/samples/sample-permission-mappings-config.xml to the new permissions
- [x] Update OAS documentation for AA bitmap
- [x] Implement UI
- [x] Document the feature: RequirePeerReview
- [x] Document Editable types (let's discuss)
- [x] Test

### Motivation
The overlap between what's allowed and what's possible.

Intent:
- Reduce business logic and intelligence in UI
- Robust and rich API
- Thin facade in UI
- UI calls facade

----------------

### Psudo Code
```
calculateAvailableActions() {
    long userPermissionsBitmap = securirtyServcice.getUserPermissions();
    long systemTypeBitmap = AvailableActionsUtil.getBitmapForSystemType(item.systemType);
    long workflowStateBitmap = ItemStateUtil.getBitmapForState(item.state);

    long result = (userPermissionsBitmap & systemTypeBitmap) & workflowStateBitmap;
    long toRetrun = applySpecialUseCaseFilters(result);
    return toReturn
}

applySpecialUseCaseFilters (long availableActionsBitmap) {
    if ((availableActionsBitmap & EDIT_BIT_SET_FLAG) > 0 && (!ContentServiceInternal.isEditable(item)) { // JS, TS, TSX, FTL, XML, HTML, YAML, CSS
        availableActionsBitmap = availableActionsBitmap & ~EDIT_BIT_SET_FLAG;
    }

    if ((availableActionsBitmap & UPLOAD_BIT_SET_FLAG) > 0 && (!item.isFolder() || !ContentUtils.isAssetPath(item.getPath())) {
         availableActionsBitmap = availableActionsBitmap & ~UPLOAD_BIT_SET_FLAG;
    }
}

securirtyServcice.getUserPermissions() -> implement column A to H mapping

AvailableActionsUtil.getBitmapForSystemType() -> implement column I hashmap

ItemStateUtil.getBitmapForState() -> implement column J hashmap
							
```

### Affected APIs:
- children_by*
- item_by*
- sandbox_items_by*

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2439

**Comment by rart** [comment]
@dejan-brkic per conversation with @sumerjabri, please suppress the "Rename" option for assets, templates, controllers, groovys and content items — only leaving it for folders, like we have on >3.1.

Will create a ticket for a future "rename" option for those with the necessary smarts.

**Comment by sumerjabri** [comment]
@rart rename/delete supressed.

**Comment by Euquimides** [comment]
Hi @alhambrav! I checked the documentation along with the implemented available actions and seems that https://docs.craftercms.org/en/4.0/site-administrators/studio/permission-mappings.html , along with RequirePeerReview needs to be documented. Reassigning this to you.

**Comment by Euquimides** [comment]
Hi! I reviewed the documentation and did some testing. Permissions are working fine, but `requirePeerReview` isn't working properly. Still, the feature was added into the documentation. A ticket about this feature is still active: #4077. If it is validated, that means `requirePeerReview` is working properly.
