### ISSUE TITLE
[studio-ui] Add parameter "pluginId"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4559]
**Is your feature request related to a problem? Please describe.**
I get an error when trying out site plugins: 
```
Request URL: http://localhost:8080/studio/api/2/plugin/file?siteId=mysite&type=sidebar&name=react-sample&filename=main.js&version=d36843e83867cadbc2d277e861d0e3f805930264
Request Method: GET
Status Code: 401 
```
Plugins installed from the marketplace requires the `pluginId` parameter and should be included in the UI config.

Steps to reproduce:
1. Open the sidebar then `Site Config` -> `Plugin Management` -> `Search & Install`.  Select `Site Plugin Example` and install.
2. Add a sidebar plugin (I used the example sidebar plugin in the docs for the js file) to where the `Site Plugin Example` was installed and commit your changes
```
config/studio/plugins/js/org/craftercms/plugin/test/sidebar/react-sample/main.js
```
3. Edit the sidebar configuration to display the sidebar plugin added in the previous step
```
                                <!-- Sample React Sidebar Widget -->
                                <modulehook>
                                    <plugin>
                                        <pluginId>org.crafterms.plugin.test</pluginId>
                                        <type>sidebar</type>
                                        <name>react-sample</name>
                                        <file>main.js</file>
                                    </plugin>
                                    <params>    
                                        <!--
                                        Any config params you specify here, will
                                        be passed to the "initialize" function of your plugin.
                                        -->
                                    </params>
                                </modulehook>
```
4. Refresh your browser.  Notice the call made to getPluginFile does not contain the parameter `pluginId`, which is part of the path of the plugin
```
Request URL: http://localhost:8080/studio/api/2/plugin/file?siteId=mysite&type=sidebar&name=react-sample&filename=main.js&version=d36843e83867cadbc2d277e861d0e3f805930264
```

**Describe the solution you'd like**
Add parameter `pluginId` to getPluginFile call
See https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.6#/plugin/getPluginFile for the parameter description

@jdrossl mentioned that the `pluginId` is required for plugins installed via the marketplace

**Describe alternatives you've considered**

**Additional context**
Studio Version: 4.0.0-SNAPSHOT-7babd5

**Comment by jvega190** [comment]
Also updated API url due to this change (https://github.com/craftercms/craftercms/issues/4565)

**Comment by alhambrav** [comment]
Verified.
