### ISSUE TITLE
[studio-ui] Preview Tools don't push the preview iframe inwards

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#456]
The preview tools, when triggered, overlay the iframe with the preview site in it instead of shrinking the iframe and therefore they cover the site and make it hard to edit.
![screen shot 2017-02-14 at 9 05 25 am](https://cloud.githubusercontent.com/assets/3931908/22931994/bcfad56c-f294-11e6-8b34-81bd6c7e13d0.png)
![screen shot 2017-02-14 at 9 05 21 am](https://cloud.githubusercontent.com/assets/3931908/22931993/bcf580c6-f294-11e6-858e-f35b9707f14b.png)

**Comment by jvega-crafter** [comment]
Fixed in both 2.5.x and 3.0 as discussed with Sumer
https://github.com/craftercms/studio2-ui/pull/253
https://github.com/craftercms/studio2-ui/pull/254
