### ISSUE TITLE
[docs] Mark as deprecated security endpoints

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4564]
## Describe the bug
The security endpoints `Login`, `Logout` and `Validate Session` are no longer needed in 4.0

## To Reproduce
1. Check https://docs.craftercms.org/en/4.0/developers/projects/studio/api/api-version1.html#security and review the first 3 endpoints. 

## Expected behavior
Each security endpoints `Login`, `Logout` and `Validate Session` should be marked as deprecated in 4.0 docs, and add a link to the new security mechanism https://docs.craftercms.org/en/4.0/developers/cook-books/how-tos/working-with-crafter-studios-api.html#working-with-crafter-studios-api

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/110494948-ab872d00-80b9-11eb-8283-5d4e4c8b8fe2.png)

## Logs
N/A

### Version
`4.0.0-SNAPSHOT`

### OS
N/A

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
@alhambrav please remove unsupported APIs in v4, no need to mark deprecated.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1172

**Comment by yacdaniel** [comment]
Verified.
