### ISSUE TITLE
[studio] Bulk Publishing single file publishes all modified files

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4566]
## Describe the bug
When using the bulk publish feature on a single file in a site where changes were pulled from a remote repository, the bulk publisher auto publishes all modified files that were recently pulled in rather than the single file that was entered into the bulk publisher.

## To Reproduce
1. Create an empty repository on GitHub
2. Create a site based on editorial
3. Make a simple publish so the published directory is created (Publish the home page)
4. Navigate to Site Config
5. Click on Remote Repositories. 
6. Add a new repository and add the empty repo you just created on GitHub.
7. Once the repository is added. Push up your changes to the repo via the UI
8. Clone the newly pushed content to your local machine and make changes to 3 files (I chose to make simple changes to 3 different articles by modifying their titles). 
9. Once the changes are made to the articles locally, push the changes back up to the remote repository: `git add /path/to/files` `git commit -m <message>` `git push`
10. Back in studio, navigate back to the Remote Repository tab by going to Site Config --> Remote Repository's 
11. Pull the changes from the repository by clicking the down arrow, then click ok. 
12. Once the changes are pulled, navigate to Publishing --> Bulk Publish
13. In the Path to Publish section, add the path to the first file that you made changes to locally. 
14. Click Publish and then click the crafterCMS logo in the top left to go back to the Site Dashboard for the site.
15. Notice in the recently published section that all 3 of the files were published

## Expected behavior
When bulk publishing a single file, the single file should be the only file published. 

## Screenshots
Example of what was done to Bulk Publish the single item
![image](https://user-images.githubusercontent.com/42217570/110502174-f65c7100-80c8-11eb-88eb-4b3af7bbbe04.png)

After Bulk Publishing the single file:  /site/website/articles/2017/1/men-styles-for-winter/index.xml
![image](https://user-images.githubusercontent.com/42217570/110502467-37548580-80c9-11eb-92fb-e8c61c2c6f95.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
This is expected behavior. Bulk Publish will publish all files committed within the same commit and all dependencies. If 3 edited files are separated into 3 different commits before push and pull, Bulk Publish will publish only one files

**Comment by sumerjabri** [comment]
Resolved by https://github.com/craftercms/craftercms/issues/6181
