### ISSUE TITLE
[studio] Add a delete_site permission

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4568]
**Describe the solution you'd like**
Add a new permission `delete_site` and update the permission string to match the new naming convention. 

**Additional context**
`Crafter CMS 4.0.0-SNAPSHOT`

**Comment by sumerjabri** [comment]
Remove `Change Content Type` since it's unused (content_write handles that at this time)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2456

**Comment by yacdaniel** [comment]
Verified fixed.
