### ISSUE TITLE
[studio-ui] Fix Pencils for Editorial Blueprint

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#457]
Please fix the pencils so they show up correctly for Editorial Blueprint. The blueprint has been added to the latest 3.0.x codebase.

Note how they show up away from the items they're meant to edit and bounding box is not around the right content.

Ping me for a demo.

**Comment by vestrada** [comment]
https://github.com/craftercms/studio2-ui/pull/283

**Comment by vestrada** [comment]
Done
