### ISSUE TITLE
[studio-ui] Special Characters being saved in TinyMCE 2/5 and Text Area result in content being stuck in system processing

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4574]
## Describe the bug
When copy & pasting the text that contains special characters such as ` ` into a text area in studio, the file fails to save and causes the file to be stuck in a 'system processing' state. 

## To Reproduce
1. Create a site based on editorial
2. Navigate to Site Config
3. Edit the Content Type, Page - Home
4. Add a Text Area to the page, then save the content type.
5. Navigate back to the preview of the site
6. Right-click and edit the home page
7. Copy and paste the following text into the Text Area that you added to the page: `Brand Voice Guidelines | Photography Guidelines` and then click Save & Close.
8. Notice the error occurs when trying to Save & Close
9. Notice that the page is now stuck in 'System Processing'

## Expected behavior
If the text area does not support the characters that are inside it leading to a failure on saving, the file should not be stuck in a 'System Processing' state.

## Screenshots
Error that occurs when trying to save & close with the supplied text:
![image](https://user-images.githubusercontent.com/42217570/110814328-5719b400-8257-11eb-94b2-9b9b2d18663b.png)

System processing error that occurs after the first attempt to save & close:
![image](https://user-images.githubusercontent.com/42217570/110814368-61d44900-8257-11eb-8827-6c9679582a72.png)

## Logs
https://gist.github.com/AndyReiter/4464ceda1137c4369429a3c27c21fe07

### Version
Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
Firefox 86.0 (64-bit)

**Comment by jvega190** [comment]
@AndyReiter we're not being able to reproduce the error, in both tinymce2/5 and the textarea. We tried using the string detailed in the ticket and some extra special characters.

**Comment by jvega190** [comment]
@AndyReiter just tried again on firefox 88.0.1, still not showing the errors

**Comment by jvega190** [comment]
It seems like the special character wasn't saved in github correctly, Andy sent the proper character and now I'm being able to reproduce the error.

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation, please ping me if you need more details.

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.15-SNAPSHOT`

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
