### ISSUE TITLE
[studio-ui] Create a PathNavigatorTree Widget

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4575]
Please create a new UI Widget, PathNavigatorTree which allows the display of trees with expand collapse of containers. Much like the PathNavigator, this will show elements in a level based on ChildrenBy, however, this allows for container children to be further expanded without navigating to the child, and will allow many children to be open at the same time.

Opening a leaf container does nothing.

Filtering is supported per container.

**Comment by rart** [comment]
@aachavarria please use new ItemDisplay component on the tree.

See design on Figma on "Item State Representations" page.
