### ISSUE TITLE
[studio-ui] Show item state and publish target in PathNav*

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4576]
Display the workflow state of an item and the publishing target location if any in the PathNav* tools.

- [x] Design (almost done)
- [x] Implement
- [x] Test
- [x] Document and update screenshots

**Comment by rart** [comment]
Some detailing pending, but we may begin testing, @sumerjabri

**Comment by yacdaniel** [comment]
Looks good, improvements still going into Studio. Please add to docs when convenient @alhambrav
