### ISSUE TITLE
[studio] Create "Rename" API

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4577]
**Is your feature request related to a problem? Please describe.**
There's no API for renaming assets, templates, controllers, scripts, and other artifacts.

**Describe the solution you'd like**
Implement a rename API that does all the necessary rename-related tasks.
Stretch goal: Update references to the renamed object.

**Describe alternatives you've considered**
Use cut/paste

**Additional context**
Consider a rename for content items too? Should the available action show up for these and the UI shows a simplified dialog to just rename instead of the whole form?

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/5630
