### ISSUE TITLE
[studio-ui] Support parentPath[INDEX] for path macros

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4579]
**Is your feature request related to a problem? Please describe.**
Currently Crafter Studio supports {parentpath} 

Parent path subdirectories often have a semantic meaning such as locale, product type etc.  Make it possible to pull a single sub / of the parent path with the following syntax
{parentpath[0]}

**Describe the solution you'd like**
Add macro resolution support for sub elements of a parent path in Crafter Studio.
Make it possible to pull a single sub / of the parent path with the following syntax
{parentpath[0]}

**Example:**
/en/mypage
{parentpath[0]} = en

/products/household/cleaning
{parentpath[1]} = household

**Describe alternatives you've considered**
Plugins can be used to implement domain specific macros. This offers a strong option without requiring customizations

**Additional context**
This is working code:
```
     if (path.indexOf('{parentPath[') != -1) {

          // get the full parent path
          var fullParentPath = CStudioAuthoring.Utils.getQueryParameterByName('path').replace(
              /\/[^\/]*\/[^\/]*\/([^\.]*)(\/[^\/]*\.xml)?$/, '$1');
          
          var parentPathParts = fullParentPath.split("/");
          var index = /.*\[\s*(\d+)\s*\].*/.exec(path)[1];
          var value = parentPathParts[parseInt(index)]


          path = path.replace('{parentPath['+index+']}', value);
        }
```

in context of the common-api.js processMacros function

```
      /**
       * handle macros in file paths
       */
      processPathsForMacros: function (path, model, useUUID) {
        if (path.indexOf('{objectId}') != -1) {
          if (useUUID) {
            path = path.replace('{objectId}', CStudioAuthoring.Utils.generateUUID());
          } else {
            path = path.replace('{objectId}', model['objectId']);
          }
        }

        if (path.indexOf('{objectGroupId}') != -1) {
          path = path.replace('{objectGroupId}', model['objectGroupId']);
        }

        if (path.indexOf('{objectGroupId2}') != -1) {
          path = path.replace('{objectGroupId2}', model['objectGroupId'].substring(0, 2));
        }

        /* Date macros */
        var currentDate = new Date();
        if (path.indexOf('{year}') != -1) {
          path = path.replace('{year}', currentDate.getFullYear());
        }

        if (path.indexOf('{month}') != -1) {
          path = path.replace('{month}', ('0' + (currentDate.getMonth() + 1)).slice(-2));
        }

        if (path.indexOf('{parentPath}') != -1) {
          path = path.replace(
            '{parentPath}',
            CStudioAuthoring.Utils.getQueryParameterByName('path').replace(
              /\/[^\/]*\/[^\/]*\/([^\.]*)(\/[^\/]*\.xml)?$/,
              '$1'
            )
          );
        }

        if (path.indexOf('{parentPath[') != -1) {

          // get the full parent path
          var fullParentPath = CStudioAuthoring.Utils.getQueryParameterByName('path').replace(
              /\/[^\/]*\/[^\/]*\/([^\.]*)(\/[^\/]*\.xml)?$/, '$1');
          
          var parentPathParts = fullParentPath.split("/");
          var index = /.*\[\s*(\d+)\s*\].*/.exec(path)[1];
          var value = parentPathParts[parseInt(index)]


          path = path.replace('{parentPath['+index+']}', value);
        }


        if (path.indexOf('{yyyy}') != -1) {
          path = path.replace('{yyyy}', currentDate.getFullYear());
        }

        if (path.indexOf('{mm}') != -1) {
          path = path.replace('{mm}', ('0' + (currentDate.getMonth() + 1)).slice(-2));
        }

        if (path.indexOf('{dd}') != -1) {
          path = path.replace('{dd}', ('0' + currentDate.getDate()).slice(-2));
        }

        return path;
      },
```

**Comment by rart** [comment]
@russdanner Looking at the old code, I don't think the old/existing `{parentPath}` regex does what I understand it should be doing.

My understanding is that `/site/website/en/cars/honda/civic/index.xml`'s parent path should be `civic`. However, running that regex that's always been there (`\/[^\/]*\/[^\/]*\/([^.]*)(\/[^\/]*\.xml)?$`) would result in `en/cars/honda/civic`. In other words, that RegEx only works if the parent item is **directly** inside `/site/webiste` but not if there's further nesting.

I've addressed this ticket/request in [PR#2231](https://github.com/craftercms/studio-ui/pull/2231). I did not change the current behaviour of that regex for the simple `{parentPath}` expression as it's been there for ages. Let me know if you want to address.

**Comment by russdanner** [comment]
@rart Am I missing it? Is there a merge for 3.1.14?

**Comment by rart** [comment]
I missed the 3.1.x PR. Will send shortly.

**Comment by russdanner** [comment]
Confirmed

**Comment by russdanner** [comment]
Confirmed
