### ISSUE TITLE
[studio-ui] Preview Pencils don't move when the page moves

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#458]
Pencils don't track the ICE tags as they should if the page scrolls/moves around after initial placement.

Please see the two screenshots illustrating this problem on the Editorial Blueprint.
![screen shot 2017-02-14 at 2 02 08 pm](https://cloud.githubusercontent.com/assets/3931908/22944417/9fd40812-f2be-11e6-8a51-6b90d5fe6fe2.png)
![screen shot 2017-02-14 at 2 02 05 pm](https://cloud.githubusercontent.com/assets/3931908/22944416/9fd0b496-f2be-11e6-8960-893fab1126f4.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/285

**Comment by vestrada** [comment]
Done
