### ISSUE TITLE
[docs] Cluster: Document how to re-create remotes

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4581]
## Describe the bug
When an system admin changes Studio config  `studio.clustering.sync.urlFormat` from `HTTPS` to `SSH` and backwards, after starting up the nodes on disk contains the old `URL`  format

## Expected behavior
Document how to re-create the cluster remotes to match the chosen sync protocol.

### Version
`3.1.x` and `4.0.x`

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/1180 & https://github.com/craftercms/docs/pull/1181

**Comment by yacdaniel** [comment]
Verified.
