### ISSUE TITLE
[studio-ui] Break out Experience Builder Tools

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4582]
Per our conversation, we should break out the Experience Builder toolkit into a separate panel that's enabled/disabled with the top toggle.

Please:
- [x] Design
- [x] Implement
- [x] Test
- [x] Document

**Comment by yacdaniel** [comment]
Verified.
![page builder](https://user-images.githubusercontent.com/6722074/130260102-23624004-fc0f-43d5-99f8-d434502c40e4.gif)

@alhambrav please add to docs.
