### ISSUE TITLE
[studio-ui] File upload popup loses function if a file fails to upload

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4584]
## Describe the bug
When uploading a file in Crafter Studio, the dialogue box freezes and loses functionality if the upload fails. 

## To Reproduce
1. Create a new site based on an empty blueprint
2. Navigate to Site-Config
3. Modify the 'Entry' Content Type
4. Add an Item selector to the content type and connect it to a File Uploaded from Desktop DataSource
5. Navigate back to the preview of the home page
6. Right-click and Edit the home page
7. Scroll down to the file uploader and open up the File Uploader dialogue
8. Right-click and click inspect to open the network interface. Navigate to the Network tab and throttle the network speed to be very slow (we need to slow down the network so we can turn the network off to cause the upload to fail on purpose).
9. Upload a file and before it finishes uploading, throttle the network all the way back to be offline.
10. Notice that the file fails to upload and now you are unable to click out of the File Uploader dialogue box and need to refresh the page in order to be able to navigate around again.

## Expected behavior
When a file fails to upload, the dialogue box should not lose functionality and user's should be able to try and reupload.

## Screenshots
Screen gets hazy like this and you cannot click anywhere on the page.
![image](https://user-images.githubusercontent.com/42217570/111215445-8c9d0500-85a9-11eb-8901-d2c87ff1d321.png)

## Logs
N/A

## Specs
Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
@sumerjabri @AndyReiter I wasn't able to reproduce the issue exactly as described in version 3.1.15 (overlay is not over the dialog when it fails). Though, there was an issue in the same scenario where the close button wasn't enabled after the upload failure. PR's are for that bugfix.

**Comment by jvega190** [comment]
Confirmed with Andy that overlay over dialog is not showing, `Close` button not enabled on error fixed in PR

**Comment by jvega190** [comment]
@yacdaniel this is ready for testing in 4.0.x

**Comment by jvega190** [comment]
Ready for testing in 3.1.x too

**Comment by yacdaniel** [comment]
Verified fixed in both `3.1.16` and `4.0.0-SNAPSHOT`
