### ISSUE TITLE
[studio-ui] Remove calls to clear cache API

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4588]
The new configuration cache is able to reload objects when a configuration file changes so there is no need to manually call it.

Please remove all calls to ` api/1/site/clear-configuration-cache` from the UI

Front-end ticket for https://github.com/craftercms/craftercms/issues/4569

**Comment by jvega190** [comment]
@jdrossl done, please let me know if you need help validating

**Comment by jdrossl** [comment]
Verified
