### ISSUE TITLE
Create a `children_by_paths` API to load children of several paths in bulk

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4590]
**Is your feature request related to a problem? Please describe.**

To support efficient expanded path restoring on the new [PathNavigatorTree widget](https://github.com/craftercms/craftercms/issues/4575) please create an api that receives an array/list of parent paths and returns an indexed list of said paths children.

**Describe the solution you'd like**

`/api/2/content/children_by_paths?siteId={siteId}...`

```typescript
// Response contract
interface ChildrenByPathsResponse {
  response: ApiResponse;
  data: {
    [parentPath: string]: {
      response: ApiResponse;
      total: number;
      offset: number;
      limit: number;
      levelDescriptor: SandboxItem;
      children: Array<SandboxItem>;
    };
  };
}

// Response Sample
{
  response: {
    code: 0,
    message: 'OK',
    remedialAction: '',
    documentationUrl: ''
  },
  data: {
    '/site/website': {
      response: { /* ... */ }, // <== Send individually or just global?
      total: 6,
      offset: 0,
      limit: 10,
      levelDescriptor: {},
      children: [{ /* child1 */ }, { /* child2 */ }, { /* ... */ }]
    },
    '/site/website/articles': {
      /* ... */ 
    },
    '/some/other/path': {
      /* ... */ 
    }
  }
}
```

Optional arguments such as `limit`, `localeCode`, `sortStrategy` and `order` could likely be shared across all paths; however, to properly support the UI and widget requirements, `offset`, `keyword` and `excludes` need to be per-path. This suggests we use a POST with a JSON body that could support these needs.

```js
[POST] /api/2/content/children_by_paths?siteId=siteId&preferContent&limit&localeCode&sortStrategy&order
{
  "paths": {
    "/site/website": { "keyword": "my filter", "excludes": ["/site/website/articles"], "offset": 10 },
    "/site/website/articles": {},
    "/site/website/articles/2016": {}
  }
}
```

Query string args set the parameters for all requested paths, and the post body provides overrides for each path.

**Describe alternatives you've considered**
The UI would issue individual calls to children_by_path for each expanded node — much like it is today on the old tree.

**Additional context**
This is more or less the analog of [getSandboxItems api](https://github.com/craftercms/craftercms/issues/4498) but for the tree widget.

**Comment by sumerjabri** [comment]
We added bulk operations.
