### ISSUE TITLE
[videocenter] Live events page query fails if there have never been live events indexed

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4591]
## Describe the bug
The live events page query if there have never been live events indexed

## To Reproduce
1. Create a site based on VC
2. Delete all live streams
3. Push the site to a remote repo or copy the sandbox to another location
4. Create another site from the site you just created. This will make so there have never been streams indexed, and thus no `startDate_dt` field mapping in the index. 
5. Go to the Live Events page

You should see an error like the one shown in the Gist in the logs 

## Expected behavior
No error should appear in the logs and the page should show the there are no Live Events.

## Logs
https://gist.github.com/avasquez614/eddb057ed0deb05891dd5b21570a2c72

**Comment by jvega190** [comment]
@avasquez614 fix is done and merged in 3.1.x, pending PR is for 4.0.x. Assigning it to you for validation

**Comment by avasquez614** [comment]
Verified
