### ISSUE TITLE
[studio-ui] Approve & Publish Timezone offset is incorrect when dealing with Daylight Savings Time

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4593]
## Describe the bug
When scheduling items for publishing in studio, the timezone offset that is listed is incorrect during Daylight savings time which causes confusion among authors/approvers trying to schedule the approval and publishing of content.

## To Reproduce
1. Create a site based on editorial
2. Navigate to the preview of the site
3. Click Approve and Publish
4. Select "Items should be published on a specific date & time" under the "Selected Item Scheduling" section
5. Next click the "EST5EDT" hyperlink to select the timezone you want and to see the timezone offset
6. Notice that the timezone selected by default is (GMT -05:00) EST5EDT. This offset of -5 is incorrect when it comes to Daylight Savings Time.

## Expected behavior
The offset should be correctly calculated when it comes to timezones on Daylight Saving Time, which is currently -4 hours.

`The current EST5EDT time zone offset is:
Daylight Saving Time: This time zone changed to daylight saving time (DST) at 2:00 AM on Sunday, Mar 14, 2021. The GMT offset is currently UTC/GMT -4 hours (EDT).`

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/112042126-8a90f400-8b1d-11eb-87c7-ef1ab2ca20c3.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.12E-b128ef
Build Number: b128ef05088ba2239245220a5148c2e3a97d7468

Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by jvega190** [comment]
@AndyReiter the timezone offset is now considering Daylight Savings Time. We decided not to work on the dynamic offset for future dates selections by now. Assigning it back to you.

**Comment by AndyReiter** [comment]
Sounds good @jvega190. I will inform the client of this when it is released. This has been tested and confirmed in the 3.1.15 Dev build.
