### ISSUE TITLE
[studio/CLI] Allow CLI install of developer plugins

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4594]
Developers need a way to install/re-install plugins into sites while developing said plugins. Please provide an extension to Crafter CLI to install a plugin using a path to a Git repo (repeated installs allowed to clobber).

**Comment by sumerjabri** [comment]
@alhambrav please help validate this issue as you document this feature and plugins in general.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1190 and https://github.com/craftercms/docs/pull/1246
Verified.
