### ISSUE TITLE
[studio] Allow the unlocking of the publisher locks from Site Config > Publishing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4599]
It's now possible for the publisher to lock itself out upon a cluster restart where the nodes are based on k8s and IP/identifiers change with every restart.

Allow the UI to get the locks and display the values
Allow the UI to force unlock the publishing locks

Tasks
- [x] Design API
- [x] Build Backend
- [x] Build UI
- [x] Test
- [x] Document

**Comment by avasquez614** [comment]
@sumerjabri @dejan-brkic is it possible to ignore the lock when it's just a single instance?

**Comment by dejan-brkic** [comment]
API Design:
PR:
https://github.com/craftercms/studio/pull/2477
https://github.com/craftercms/studio/pull/2478

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2487

**Comment by rart** [comment]
UI for 3.1.x PR is merged and ready for testing ([2240](https://github.com/craftercms/studio-ui/pull/2240)).
4 is waiting on the backend to be merged.

**Comment by sumerjabri** [comment]
@rart 4 is ready, please send PR for 4

**Comment by rart** [comment]
4 done/merged now too.

**Comment by yacdaniel** [comment]
@dejan-brkic issues found:

* sites created from remote/marketplace are left with `publishing_status = NULL` in `sites` table.

* When publishing, `publishing_status_message`  is not with a proper format message `Currently publishing package: b5b73f34-2671-4021-a4e7-11056666750c on 2021-03-30T14:25:30Z. Item {x} of {y} is being published` 

* When publisher finish working, the `status` value is set to `queued` 
``` 
+----+-------------------+-----------------------------------------------------------------------------------------------------------------------+------------------------+-----------------------+---------------------------+
| id | publishing_status | publishing_status_message                                                                                             | published_repo_created | publishing_lock_owner | publishing_lock_heartbeat |
+----+-------------------+-----------------------------------------------------------------------------------------------------------------------+------------------------+-----------------------+---------------------------+
| 13 | queued            | Last successful publish was for package: b5b73f34-2671-4021-a4e7-11056666750c on 2021-03-30T14:28:26Z with 3987 items |                      1 | NULL                  | NULL                      |

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2494
https://github.com/craftercms/studio/pull/2495

**Comment by yacdaniel** [comment]
Verified in 3.1.14. @alhambrav please add docs.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1212 and https://github.com/craftercms/docs/pull/1213

**Comment by yacdaniel** [comment]
Hi @dejan-brkic, the permission `publish_clear_lock` is not working in Studio 4.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2607

**Comment by yacdaniel** [comment]
@dejan-brkic I'm not able to unlock publisher in `4.0.0-SNAPSOT` 
stacktrace -> https://gist.github.com/yacdaniel/c5d6cae5efdf3e6d65dcc6110e87e486

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2659

**Comment by yacdaniel** [comment]
Verified fixed.
