### ISSUE TITLE
[studio-ui] Browse dialog shows too much space between elements when item is not video or image

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#460]
note in the image below

There is a huge amount of padding after the item.  Images and videos require more area but simple items and files should list close together so that the user experience is more useful and simple.
![pasted_image_at_2017_02_16_14_46](https://cloud.githubusercontent.com/assets/169432/23040746/7458901a-f460-11e6-9611-89c6bcfe88f4.png)

**Comment by vestrada** [comment]
Completed
