### ISSUE TITLE
[studio] New folders are created with a previewUrl 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4601]
## Describe the bug
New folders created in Studio(any place: Pages, Assets, Components..) are setting a `previewUrl` in `item` table when it should be `null`. This cause that Studio tries to render a folder when it shouldn't.  

## To Reproduce
1. Create a new folder
2. Check `item` table for the new folder, also click the folder in Sidebar

## Expected behavior
`previewUrl` should be null for new folders.

## Screenshots
![image](https://user-images.githubusercontent.com/6722074/112228204-8d134c80-8bf6-11eb-980e-6d2c343021e9.png)

## Logs
N/A

### Version
`4.0.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2490

**Comment by yacdaniel** [comment]
@dejan-brkic I created a folder `f12` and renamed to `f123`, after the rename I see that `previewUrl` is getting returned with the original value before the rename
![image](https://user-images.githubusercontent.com/6722074/119516706-35977700-bd34-11eb-87aa-7589c925bafd.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2577

**Comment by yacdaniel** [comment]
Hi @dejan-brkic. Renaming folders is setting the `previewUrl` property. The property should stay `null`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2606

**Comment by yacdaniel** [comment]
Verified fixed.
