### ISSUE TITLE
[studio] Assets previewUrl are incomplete on get children APIs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4602]
## Describe the bug
The url for assets should start with `/static-assets` but response omits that piece of the path. Happens on all new item retrieval APIs.

```js
  "item": {
    ...
    "path": "/static-assets/js/crafter-support-1-0-0.js",
    "previewUrl": "/js/crafter-support-1-0-0.js", // <== incorrect
    ...
  }
```

## To Reproduce
1. Call `/studio/api/2/content/item_by_path?path=%2Fstatic-assets%2Fjs%2Fcrafter-support-1-0-0.js&siteId=editorial-test` or `/studio/api/2/content/children_by_path?path=%2Fstatic-assets%2Fjs&siteId=editorial-test`
2. See `previewUrl` for assets

## Expected behavior
Url for assets to be correct (starting with `/static-assets`). Copy pasting previewUrl and appending it to localhost:8080 should always resolve correctly.
```js
  "item": {
    ...
    "path": "/static-assets/js/crafter-support-1-0-0.js",
    "previewUrl": "/js/crafter-support-1-0-0.js", // <== incorrect
    ...
  }
```

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2496

**Comment by rart** [comment]
Verified
