### ISSUE TITLE
[engine] Allow configuring the header names when using header authentication

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4603]
When configuring Engine for headers authentication, it's right now not possible to configure the names of the incoming headers (the header names can be changed by overriding an `AbstractHeadersAuthenticationFilter` bean). These should be configurable by site:

- headerPrefix
- usernameHeaderName
- emailHeaderName
- groupsHeaderName
- tokenHeaderName

**Comment by sumerjabri** [comment]
@avasquez614 ready for validation

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.14.

**Comment by yacdaniel** [comment]
Verified fixed in 4.0.0
