### ISSUE TITLE
[studio] contentTypeId is blank for certain items when it should be null

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4604]
## Describe the bug
Anything that's not content should have `"contentTypeId": null`. Assets, xml files and groovy files are examples of things that are returning `contentTypeId` prop as blank. 

## To Reproduce
1. Invoke `/studio/api/2/content/children_by_path?path=%2Fscripts%2Frest&siteId=editorial-test` or `/studio/api/2/content/children_by_path?path=%2Fconfig%2Fstudio&siteId=editorial-test&keyword=xml` or `/studio/api/2/content/children_by_path?path=%2Fstatic-assets%2Fjs&siteId=editorial-test&keyword=xml`
2. See `contentTypeId` prop

## Expected behavior
Anything that's not content should have `"contentTypeId": null`.

## Screenshots
<img width="535" alt="image" src="https://user-images.githubusercontent.com/3928341/112516426-90920980-8d97-11eb-89c5-1da2371341b5.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
Please consider other scenarios. Assets, scripts and xml are only as far I as tested.

**Comment by dejan-brkic** [comment]
done
PR:
https://github.com/craftercms/studio/pull/2493
