### ISSUE TITLE
[studio] Password Reset token expiration causes all other reset password attempts to fail

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4609]
## Describe the bug
When a password reset token expires after a certain amount of time, other attempts to reset the password using the "Forgot Your Password" option are unsuccessful due to the same error: "Error resetting password: Token may be invalid or expired" no matter the age of the token. 

## To Reproduce
1. Create a user linked to your own email
2. Reset your password at the login screen
3. Wait the appropriate time for the token to expire
4. Once the token expires, attempt to use that token to reset your password
5. See the error that occurs when attempting to change your password due to the token being invalid or expired
6. Reset your password again at the login screen
7. Try to use this new password reset token to change your password
8. See the same error occurring with the new password reset token.

## Expected behavior
Password resets should be successful when a token is valid and not expired.

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/113032959-791f9b80-915e-11eb-982f-f2ba9416f627.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.14E-BETA-92c8ea
Build Number: 92c8ea1dbc5808b899d163dc7abf7926c45a8fde

Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Can not reproduce with described steps

**Comment by yacdaniel** [comment]
@dejan-brkic please try to reproduce it with the properties sent by Slack.

**Comment by dejan-brkic** [comment]
For Studio 4 we need to update the spring config to update constructor arguments for encryptor

**Comment by sumerjabri** [comment]
@yacdaniel please validate in 3.1

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.14` . Fix for Studio 4 depends on https://github.com/craftercms/craftercms/issues/4638
