### ISSUE TITLE
[studio] Non-previewable items have incorrect `previewUrl` when newly created

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4610]
## Describe the bug
If you create a new groovy script under `/scripts/**` and commit the change, upon calling `children_by_path` or `item_by_path` or `sandbox_items_by_path`, the new item has an incorrect previewUrl.

Same issue also happens if the file is created via Studio UI too.

## To Reproduce
1. Create a folder inside `scripts` (e.g. scripts/test)
2. Create a script inside the newly created folder (e.g. scripts/test/test.post.groovy)
3. Invoke `children_by_path` — or any of the item retrieval apis — for `/scripts/test`
2. See previewUrl for the groovy script

## Expected behavior
Only previewable items have a correct previewUrl

## Screenshots
![Screen Shot 2021-03-30 at 5 29 19 PM](https://user-images.githubusercontent.com/3928341/113032817-94a39a00-9190-11eb-8d70-5e499d9436aa.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-snapshot

### OS
Mac

### Browser
Any browser or rest client

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2497

**Comment by rart** [comment]
Verified
