### ISSUE TITLE
[studio] Authoring with Profile and Social bundle fails to startup

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4611]
## Describe the bug
When starting up the Crafter 3.1.13 bundle downloaded from [3.1.13 download](https://downloads.craftercms.org/3.1.13/social/crafter-cms-authoring-3.1.13.tar.gz), both /crafter-profile-admin and /crafter-social-admin fail to startup.

## To Reproduce
1. Download the 3.1.13 bundle from above.
2. Navigate to the bin directory and run the './startup' 
3. Tail the tomcat logs
4. See the errors that occur due to NoClassDefFoundError.

## Expected behavior
When starting up Crafter Authoring with Profile and Social, there should be no issue when starting up crafter-profile-admin and crafter-social-admin.

## Screenshots
N/A

## Logs
https://gist.github.com/AndyReiter/18194abce44736af6fcb69087ff83c93

### Version
Studio Version Number: 3.1.13-7a240f
Build Number: 7a240f1c44c924ed516f2127016d08db319d2d8e

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by sumerjabri** [comment]
Fixed in 3.1.14. We can provide Crafter Profile Admin and Crafter Social Admin WAR files as a temporary fix.

**Comment by AndyReiter** [comment]
Confirmed fixed in 3.1.14.
