### ISSUE TITLE
[studio] Studio sends a lot of publishing error emails if there is a problem connecting to the DB

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4613]
## Describe the bug
Studio sends a lot of publishing error emails if there is a problem connecting to the DB

## To Reproduce
1. Configure publishing email notifications for a site.
2. Kill the DB

You should start getting a lot of publishing error emails, with content similar to the following:

```
Error:
org.springframework.jdbc.UncategorizedSQLException: Error attempting to get column #4 from callable statement. Cause: java.sql.SQLException: No output result. ; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; No output result.; nested exception is java.sql.SQLException: No output result.
```

## Expected behavior
Just send an initial email. Maybe allow to configure the frequency of the emails, or display in the Publishing UI the last publishing error.

**Comment by yacdaniel** [comment]
Verified.
