### ISSUE TITLE
[studio] Database upgrade from 3.1.4 to 3.1.13/3.1.14 fails due to incompatible database error 

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4615]
## Describe the bug
When trying to upgrade Crafter Studio from 3.1.4 to the latest release of 3.1.13 as well as 3.1.14, the upgrade fails due to issues when upgrading the database.

## To Reproduce
1. Download, install, and install 3.1.4 
2. Create a site based on Editorial
3. Approve & publish the site to build up data and history
4. Shutdown 3.1.4
5. Download and install 3.1.14. Build the library's but do not startup studio yet
6. Copy over the entire Data directory from 3.1.4 into the install of 3.1.14 so it can be loaded upon startup of 3.1.14
7. Once the /data directory is in 3.1.14, start it up and tail the logs
8. Notice errors regarding upgrading the Database which cause the startup to fail

## Expected behavior
Upgrading a site from 3.1.4 to our latest release should work without issue.

## Screenshots
N/A

## Logs
https://gist.github.com/AndyReiter/6cb2cf84f5cedf49b0aee4717055a05e

### Version
Studio Version Number: 3.1.14
Build Number: 92c8ea1dbc5808b899d163dc7abf7926c45a8fde
Studio Version Number: 3.1.13E-ae7493
Build Number: ae74938662de44e5a38aab0c17c9171462a05e4a

### OS
Any

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
@jdrossl please also see if it's because of the upgrade.sh wasn't used.

**Comment by jdrossl** [comment]
@AndyReiter as Sumer mentioned this is not the right way to upgrade, here are some notes:
- For an upgrade you must always use the scripts because there can be other operations that are not performed by Studio
- In the `3.1.x` upgrade path, `3.1.9` is a required step, so the process should be `3.1.4 -> 3.1.9 -> 3.1.14`
