### ISSUE TITLE
[studio-ui] Error message in Remote Repositories does not display the message from the ApiResponse

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4619]
## Describe the bug
The error message in Remote Repositories does not display the message from the ApiResponse and instead just displays `Error Code: undefined`

<img width="716" alt="Screen Shot 2021-04-05 at 9 11 58 AM" src="https://user-images.githubusercontent.com/25483966/113577283-ffb8fa80-95ee-11eb-8352-a5f1d8b62c25.png">

## To Reproduce
1. Create a site using any bp, then go to `Site Config` -> `Remote Repositories`
2. Click on the `New Repository` button, fill in the required information and make a mistake in the `Remote Git Repository URL` so it will fail
3. Look in the tomcat log and notice the message there
```
[ERROR] 2021-04-01T09:31:41,657 [http-nio-8080-exec-10] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/repository/add_remote failed with response: ApiResponse{code=1000, message='Internal system failure', remedialAction='Contact support', documentationUrl=''}
```
4. Notice the error message displayed in the dialog
<img width="623" alt="Screen Shot 2021-04-01 at 4 00 17 AM" src="https://user-images.githubusercontent.com/25483966/113577986-2166b180-95f0-11eb-9cb6-8367c1d2f89a.png">

Here's another way to reproduce:
1. Add a remote repository that is not bare to a site
2. Do a pull, that will result in a conflict
3. Look at the tomcat log
```
[ERROR] 2021-04-05T09:07:02,245 [http-nio-8080-exec-5] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/repository/pull_from_remote failed with response: ApiResponse{code=12002, message='Pull from remote repository resulted in conflict', remedialAction='Resolve conflicts before continuing work with repository', documentationUrl=''} 
org.craftercms.studio.api.v2.exception.PullFromRemoteConflictException: Pull from remote result is merge conflict.
```
4. Notice the error message displayed in the dialog says `undefined`

## Expected behavior
The error message dialog should display the message  in the ApiResponse

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 4.0.0-SNAPSHOT-0a651c
Build Number: 0a651cd0b8778b2e25a853d906ceb1b5565c91bd
Build Date/Time: 04-01-2021 10:42:56 -0400

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@rart this is only happening in 4.0.x, confirmed with Vita. I'll remove the 3.1.x tag

**Comment by alhambrav** [comment]
Verified fixed.
