### ISSUE TITLE
[studio-ui] Line numbers goes over the action bar of configurations

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4620]
## Describe the bug
Line numbers goes over the action bar  of Configurations

## To Reproduce
1. Create a site using any bp, open `Site Config` or `Site Tools` if using the next UI
2. Select `Site Configuration` from the dropdown
3. Depending on your browser height, the line numbers goes over the action bar

`Site Config` -> `Configuration` -> `Site Configuration`
<img width="1171" alt="Screen Shot 2021-03-31 at 11 19 53 AM" src="https://user-images.githubusercontent.com/25483966/113581385-12363280-95f5-11eb-9171-d2097f16c275.png">

`Site Tools` -> `Configuration` -> `Site Configuration`
<img width="1454" alt="Screen Shot 2021-04-01 at 9 23 13 AM" src="https://user-images.githubusercontent.com/25483966/113581415-1bbf9a80-95f5-11eb-8251-16db76c5a518.png">

## Expected behavior
Line numbers should not go over the action bar of Configurations

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 4.0.0-SNAPSHOT-0a651c
Build Number: 0a651cd0b8778b2e25a853d906ceb1b5565c91bd
Build Date/Time: 04-01-2021 10:42:56 -0400

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@rart this is only happening in 4.0.x, confirmed with Vita. I'll remove the 3.1.x tag

**Comment by rart** [comment]
@jvega190 the PR does some z-index changes on the control bar, which is used in several places. 
Please do some code browsing to find places of usage and additional testing to make sure all keeps working on those views on their different state.

**Comment by jvega190** [comment]
@rart searched and tested, looking fine. Assigning to @alhambrav for validation

**Comment by alhambrav** [comment]
Verified fixed.
