### ISSUE TITLE
[studio] Add publish_status permission to all site members.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4625]
## Describe the bug
The `publish_status` API should work for users of any group.

## To Reproduce
1. Login to a site dashboard with an `author` user.
2. Check Studio logs.

## Expected behavior
No errors in logs about missing permission to access the `publish_status` API

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.14` and `4.0`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by sumerjabri** [comment]
@dejan-brkic please include in UM so 3.1.x upgrades will continue to allow site members to see the status.

**Comment by dejan-brkic** [comment]
3.1.x
PR:
https://github.com/craftercms/studio/pull/2504

**Comment by yacdaniel** [comment]
Verified fixed.
