### ISSUE TITLE
[studio] get_children_by & sandbox_items_by don't work for author role

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4626]
## Describe the bug
If you login as an author, said APIs 403

## To Reproduce
1. On 4, go to a PageBuilder logged in as an author
2. On the left sidebar, select site explorer panel
3. See how it never finish loading. See browser console for 403s

## Expected behavior
Requests resolve for all relevant roles

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2514

**Comment by sumerjabri** [comment]
@rart the changes done to the built-in blueprints need to be applied to all blueprints in the MP. Please assign a team member to handle this.

**Comment by rart** [comment]
@jvega190 you can batch up these changes with the TinyMCE changes.

**Comment by jvega190** [comment]
@sumerjabri @rart blueprints updated
