### ISSUE TITLE
[studio] Studio is setting all items to NEW_UNPUBLISHED_UNLOCKED

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4628]
## Describe the bug
Studio is setting all items to `NEW_UNPUBLISHED_UNLOCKED`

## To Reproduce
1. Start a Studio with a site with published items and unprocessed commits (by doing a git pull, for example).
2. Check Studio's DB to for item_states `NEW_UNPUBLISHED_UNLOCKED` (`select count(1) from item_state where state='NEW_UNPUBLISHED_UNLOCKED'`)

You should see the number increasing until all or almost all items are `NEW_UNPUBLISHED_UNLOCKED`.

## Expected behavior
Only new items should appear as `NEW_UNPUBLISHED_UNLOCKED`.

## Screenshots
![Screenshot from 2021-04-07 21-17-54](https://user-images.githubusercontent.com/1598884/113954019-132eb600-97e7-11eb-9543-b28b84582697.png)

![Screenshot from 2021-04-07 21-18-36](https://user-images.githubusercontent.com/1598884/113954046-1b86f100-97e7-11eb-8037-7ed03b355dc3.png)

![Screenshot from 2021-04-07 21-19-29](https://user-images.githubusercontent.com/1598884/113954064-22156880-97e7-11eb-8ac5-f65b900c4840.png)

## Logs
N/A

### Version
N/A

### OS
N/A

### Browser
N/A

## Additional context
N/A

**Comment by dejan-brkic** [comment]
There is not enough information on the ticket and steps to reproduce are inconclusive. There is no evidence that an existing published item transitioned into NEW_UNPUBLISHED_UNLOCKED

**Comment by sumerjabri** [comment]
Problems with Git history caused this.
