### ISSUE TITLE
[studio] Different times are shown in Studio between request publish, schedule and published item. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4631]
## Describe the bug
Studio shows different times(difference in hours/timezone) in items that are in request publish, schedule and published item.

## To Reproduce
1. Create a site from any BP, add an author and a reviewer user, configure timezone of the site in site-config.xml, set your local timezone.
2. With `author` request publish a page and set a schedule to tomorrow
![image](https://user-images.githubusercontent.com/6722074/114077480-1799b400-9865-11eb-99f5-58d01b07918c.png)
3. With `reviewer` user approve and schedule the item
![image](https://user-images.githubusercontent.com/6722074/114077687-4ca60680-9865-11eb-8486-d1d3b2fb9629.png)
4. Check the time in the server where Studio is running, for example mine is `Thu Apr  8 18:24:39 UTC 2021`   
5. Go to Dashboard and check the time, notice how time is not the time selected in the approve dialog, looks like is using the server time
![image](https://user-images.githubusercontent.com/6722074/114078067-b9b99c00-9865-11eb-9352-d0cc761adf32.png)

## Expected behavior
The time in Studio dashboard widgets and approve now/schedule dialogs should be consistent. 

## Screenshots
Tool tip in dashboard widget is incorrect.
![image](https://user-images.githubusercontent.com/6722074/114080111-38afd400-9868-11eb-941e-35fde98c4b88.png)

## Logs
N/A

### Version
`3.1.14` and `4.0.0`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
3.1.x
https://github.com/craftercms/studio/pull/2509

**Comment by yacdaniel** [comment]
@dejan-brkic please fix the endpoint `/studio/api/1/services/api/1/deployment/get-scheduled-items.json` the label date is hardcoded in a string `name` and `internalName`, please change it to use timezone as the `eventDate` in that response.

<img width="535" alt="imagen" src="https://user-images.githubusercontent.com/6722074/114886785-1288b780-9dc5-11eb-8443-aeb157ae2f17.png">

<img width="285" alt="imagen" src="https://user-images.githubusercontent.com/6722074/114887093-5a0f4380-9dc5-11eb-9347-d53969e57472.png">

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/2513

@rart Grouping label formated as we agreed.

**Comment by rart** [comment]
@jvega190 on both 3.1.x & 4, please apply date time formatting to the virtual item dates as they are now full date timestamps.
On 3.1.x, through the date time format functions used there and on 4, using all the new locale support.

**Comment by jvega190** [comment]
@dejan-brkic we need the same work for `/studio/api/1/services/api/1/deployment/get-deployment-history.json`
![Screenshot from 2021-04-16 17-47-18](https://user-images.githubusercontent.com/18267471/115094733-d6944600-9edb-11eb-8b67-c29399139a69.png)

**Comment by dejan-brkic** [comment]
@jvega190 It is done. Please keep in mind it is date part only (with time zone)
https://github.com/craftercms/studio/pull/2518

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.14`. I'll check if `4.0` needs any of the updates here.

**Comment by jvega190** [comment]
@dejan-brkic @yacdaniel  just checking, work for 4.0.x is pending right?

**Comment by dejan-brkic** [comment]
The issue is not present in 4.0

**Comment by yacdaniel** [comment]
@dejan-brkic  this issue with a fixed time is happening in 4, `get-scheduled-items.json` service 

> @dejan-brkic please fix the endpoint `/studio/api/1/services/api/1/deployment/get-scheduled-items.json` the label date is hardcoded in a string `name` and `internalName`, please change it to use timezone as the `eventDate` in that response.
> 
> <img alt="imagen" width="535" src="https://user-images.githubusercontent.com/6722074/114886785-1288b780-9dc5-11eb-8443-aeb157ae2f17.png">
> 
> <img alt="imagen" width="285" src="https://user-images.githubusercontent.com/6722074/114887093-5a0f4380-9dc5-11eb-9347-d53969e57472.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2746

**Comment by yacdaniel** [comment]
@jvega190 please do the fixes as we do for 3.1 in the dashboards, API now returns date with timezone
![image](https://user-images.githubusercontent.com/6722074/135287671-bab842a9-fec7-4794-8683-28defe1e1be6.png)

**Comment by yacdaniel** [comment]
Verified fixed.
