### ISSUE TITLE
[studio] Inconsistency on duplicating component behaviour

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4633]
## Describe the bug
While duplicating pages/components, we also duplicate dependencies components based on `studio.configuration.dependency.itemSpecificPatterns` configuration.

Even followed the `itemSpecificPatterns`, some user reported that the dependency components weren't duplicated and on new page, the original dependencies are injected.

```
Usually if a page is duplicated, the referenced components are copied and the original component paths should be replaced by new component paths in the XML file.

Unfortunately this is not always the case. Sometimes some of the original components are still referenced. Then if someone deletes the duplicate, these original components are also deleted.

I think the problem occurs in the studio in the ContentUtils class. The method convertStreamToXml returns an XML document. In this XML document it happens that component paths are split into substrings, e.g. the component path is /site/components/2020/08/10/d00bbda2-2d6c-da7f-e64f-73a7b318078b-e76baa55-50ad3096.xml and the XMl document contains:

content = {ArrayList@28687} size = 2 
0 = {DefaultText@28692} "org.dom4j.tree.DefaultText@4feccb94 [Text: "/site/components/20"]" 
1 = {DefaultText@28693} "org.dom4j.tree.DefaultText@5bccfe70 [Text: "20/08/10/d00bbda2-2d6c-da7f-e64f-73a7b318078b-e76baa55-50ad3096.xml"]"

Then the replaceCopyDependency method in the ClipboardService class fails and the old component paths are retained.
```

While reviewing source code, found out that 2 possible cases for this problem:

* We get dependencies from db then replacing its to xml files. If there is inconsistency between db `dependency` table and the content of xml file then the logic is broken. Or if there is db connection issue, dependency cannot be retrieved, then the original component won't be replaced.

https://github.com/craftercms/studio/blob/master/src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java#L771

* While replacing dependencies to new one in xml file, we don't check if the replacement is successful or not. If there is inconsistency between db and xml file content, the replacing may be failed. As a result, the original dependencies are injected to newly duplicated items.

https://github.com/craftercms/studio/blob/master/src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java#L875

## To Reproduce

1. Create an original page with dependency component
2. Update db `dependency` table to remove the dependent component
3. Duplicate the page
4. Notice that the dependency was not duplicated and the original component is referred.

## Expected behavior

A way to handle such inconsistency.

## Screenshots

See in comments

### Version
3.1.13

### OS
Ubuntu

### Browser
Chrome

## Additional context

```
# Regex pattern for item specific dependencies
studio.configuration.dependency.itemSpecificPatterns: /site/components/page/.*,/static-assets/page/.*,/site/components/item/.*,/static-assets/item/.*,/site/components/2020/08/10/.*
```

**Comment by phuongnq** [comment]
![update_db_remove_denpendency](https://user-images.githubusercontent.com/2996543/114339451-3a430a00-9b90-11eb-8837-d74750c52693.png)
![duplicated_page_component_not_copied](https://user-images.githubusercontent.com/2996543/114339456-3c0ccd80-9b90-11eb-9f43-3389e9a627a1.png)
![duplicated_page](https://user-images.githubusercontent.com/2996543/114339458-3ca56400-9b90-11eb-81fd-60a5fe0d30d3.png)
![original_page](https://user-images.githubusercontent.com/2996543/114339463-3d3dfa80-9b90-11eb-85ab-8137df203731.png)

**Comment by sumerjabri** [comment]
@russdanner having gone through this in detail, the paths detailed above are unlikely. DB failure or failed string replacement are not realistic:
* DB failure will result in Studio failure in short order, we don't see selective failure and we have an exception flow for that
* String replacement in RAM doesn't fail. They either replace or not replace, it's a request to replace if present.

Two other paths are possible:
* Misconfigured dependency scanner (not configured for the right mime-types or not the right regexes to extract deps)
* A problem with the content where the paths are broken due to some external agent

Happy to discuss more.

**Comment by russdanner** [comment]
Only item specific content is duplicated:
In the **CRAFTER_HOME/shared/classes/crafter/studio/extension/studio-config.yaml**
There MAY be an override value for this property that sets patterns for item specific content.  
**studio.configuration.dependency.itemSpecificPatterns**

If this property does not exist the default value is used:
**studio.configuration.dependency.itemSpecificPatterns: /site/components/page/.*,/static-assets/page/.*,/site/components/item/.*,/static-assets/item/.***

Example paths that do not match the pattern and are thus NOT item specific content and thus will NOT be duplicated:
```
site/components/2020/10/22/9ab8cf3a-f596-952b-59f0-3b94eef8dcba.xml
site/components/2020/09/04/dd63479f-2096-8b76-5e9e-7b5d48bff570-30ea9df5.xml
site/components/2020/09/04/dd63479f-2096-8b76-5e9e-7b5d48bff570.xml
site/components/2020/08/10/d00bbda2-2d6c-da7f-e64f-73a7b318078b-e76baa55-50ad3096.xml

```
To address/work around this you could add something like `/site/components/20.*' to the studio.configuration.dependency.itemSpecificPatterns config.
