### ISSUE TITLE
[engine] Add a property to allow creating S3 clients with path-style access

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4634]
In Engine, add a property to allow configuring serverless with path-style access to support S3-compatible storage like `s3://{endpoint}/{bucketName}`, similar to how it's done in Studio's S3 blob stores.

**Comment by sumerjabri** [comment]
@yacdaniel please do this:
* Download https://min.io/download#/linux
* Place a site in that storage
* Point Engine to that site with @avasquez614 support
* Test and validate it works

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.14`.

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0`
