### ISSUE TITLE
[studio] Return raw data for publishing status data in the API response

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4636]
Augment the publishing status API to return raw data to help the UI render a better experience.

- [ ] Design a new table to hold the raw data
- [ ] Design the API response and update OAS
- [ ] Review designs with @sumerjabri 
- [ ] Implement with care regarding clustering/locks and concurrency, performance, and the future addition of event propagation to the UI
- [ ] Test

**Comment by sumerjabri** [comment]
We will not pursue it.
