### ISSUE TITLE
[docs] Create an article to document how to wire header-based authentication, role-based authorization & targeting for preview

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4637]
## Describe the bug

Recipe/documentation is missing and is required to **tie together** the following features:

- header-based authentication
- role-based content authorization via authorizedRoles attribute
- using the targeting area of the Studio UI to allow authors to simulate a user in a particular role so that the experience can be tested

## Expected behavior
Currently, documentation for authorizedRoles is not bad (though role name rules aren't clear - do we need ROLE_ prefixes in the profile or in the authorizedRoles field?)

Header-based authentication for engine documentation is not bad (though it appears that perhaps the header names changed recently?  Also, how EXACTLY do we set roles that are picked up by the engine security feature that honors authorizedRoles?  Prefixes? Comma-separated?  

Targeting configuration documentation is not great - specifically, looking for information on how to configure that targeting configuration file to allow content authors to simulate the values set during header-based authentication (ideally, all of them, like name, username, arbitrary values, and most importantly, roles).  Users will need to be able to pick role values from a dropdown, checkbox, or multi-select box - it's not realistic to expect them to type the roles into a text field.  Are prefixes required?  

Documentation explaining the old profile object as well as the user principal object, and how they work together would also be helpful.

**Comment by tfield** [comment]
Doc should also indicate any compatibility issues with free marker vs rest api for this setup.

**Comment by sumerjabri** [comment]
@alhambrav please consult with @jdrossl when writing this up.

**Comment by jdrossl** [comment]
@sumerjabri this is a new feature request, I think it should be filed as a new ticket for the UI
```
Users will need to be able to pick role values from a dropdown, checkbox, or multi-select box - 
it's not realistic to expect them to type the roles into a text field. 
```

currently we only support dropdowns for single value and input for multiple values

**Comment by jdrossl** [comment]
@alhambrav here are some notes to help with the updates:

1. In [this section](https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-site-security-guide.html#restrict-pages) we need to add a note clarifying that the values in `authorizedRoles` need to include the `ROLE_` prefix
2. In [this section](https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-headers-based-authentication.html#configure-engine-for-headers-based-authentication) we need to add a note clarifying that previous to `3.1.14` the prefix for the headers is `MELLON_` and it can't be changed via site configuration
3. In [this article](https://docs.craftercms.org/en/3.1/developers/targeting.html#content-targeting) we need to add a new section describing how to setup targeting based on roles:
    - Add a property with name `roles`, it can be of type dropdown (for a single value) or an input (for multiple values separated by commas) (this might change depending on the ticket mentioned in the previous comment)
    - Include a note clarifying that the values for this field must include the `ROLE_` prefix
    - Include an example of `urlRestrictions` or `authorizedRoles` working together with the `Targeting` feature, something similar to [this](https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-headers-based-authentication.html#example-setting-up-engine-headers-authentication-with-optional-role-mappings-and-attributes)
4. We have [this note](https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-site-security-guide.html#migrating-from-crafter-profile) about the `profile` variable being replaced by `authToken` & `authToken.principal` but maybe we need to add another note more visible clarifying that the variables `profile` and `authentication` will be `null` in most cases and should not be used anymore

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1218  & https://github.com/craftercms/docs/pull/1219
