### ISSUE TITLE
[studio-ui][3.1.x] Styling issues in legacy preview tools panel

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4641]
## Describe the bug
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/3928341/114663157-287d7600-9cfa-11eb-8aea-2b0aa52026be.png">

## To Reproduce
1. Clone a site (legacy, not next. Seen in wordify & editorial.)
2. Go to preview and open preview tools

## Expected behavior
The studio-dnd-controller-overlay doesn't overlay the components panel

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by russdanner** [comment]
Confirmed
