### ISSUE TITLE
[studio-ui] Improve drag & drop usability

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4646]
**Is your feature request related to a problem? Please describe.**
- Cursor transitions are too subtle and may be missed
- Some items are undraggable because they are overlaid by child elements

**Describe the solution you'd like**
Design and implement improvements for the above items

**Describe alternatives you've considered**

**Additional context**

### Behavior to try
- Clicking on an editable item selects the outer parent object (the top-level XML file that contains the XML snippet), selection is not related to mouse movement (if you mouse out, it stays selected)
- A small menu with six dots :: indicating that this container can be moved is displayed below the outer selection (or above if the item is at the bottom of the screen)
- A small menu next to :: is clickable and provides the same menu we have today (Edit, Edit Template, etc.)
- A second click on a child element allows the user to edit
- A click outside the container unselects it

**Comment by sumerjabri** [comment]
Completed
