### ISSUE TITLE
[studio] Add keyword parameter to the Search User API

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4651]
## Describe the bug
The current Implementation of /users API don't support the keyword parameter.
The new Users UI needs this implementation to support filtered pagination.

## To Reproduce
1. using get user API /studio/api/2/users?keyword=admin
2. it returns all the users
3. The result are not filtered

## Expected behavior
The user list should be filtered using the keyword parameter

### Version
Studio Version Number: 4.0.0-SNAPSHOT-45559e
Build Number: 45559e1bb280ecd0edf75ce7320bdab44d5e4f9a

### OS
Mac

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2642

**Comment by yacdaniel** [comment]
@dejan-brkic could you please fix the import in https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/api/v2/dal/UserDAO.java#L24  to use  `org.craftercms.studio.api.v2.dal.QueryParameterNames.OFFSET`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2703

**Comment by aachavarria** [comment]
@yacdaniel please create a ticket to track this on the UI. A search box needs to be added to the new UI

**Comment by sumerjabri** [comment]
@aachavarria verified.
