### ISSUE TITLE
[docs] Create a guide for unit testing Crafter Groovy code

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4654]
Create a guide on how to set up unit testing for the Groovy code of a Crafter site:

- How to create unit tests for Groovy classes in `scripts/classes`, preferably with Maven/Gradle so that they can be run in testing servers.
- How to import Crafter classes in your unit tests:
  - The best way seems to be adding the Crafter Engine classes Maven dependency).
- (Optional) How to unit test rest, page and controller scripts:
  - Normally this is done by integration testing, but you can mock most of the services and variables, and frameworks like Spring makes unit testing REST APIs easier with mocks: https://www.petrikainulainen.net/programming/spring-framework/unit-testing-of-spring-mvc-controllers-rest-api/

**Comment by sumerjabri** [comment]
@jdrossl please ping me to discuss.

**Comment by jdrossl** [comment]
@sumerjabri @russdanner @avasquez614 there is a way to setup both gradle & maven to support this feature, however I was able to get it working only with gradle, should I spend a little more time troubleshooting it in maven (it's a runtime error) so we can offer both options or is it ok to move forward only with gradle?

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1227 https://github.com/craftercms/docs/pull/1228

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1239 and https://github.com/craftercms/docs/pull/1240

**Comment by avasquez614** [comment]
Verified
