### ISSUE TITLE
[studio] Publishing status api returns `status` as null

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4655]
## Describe the bug
`/studio/api/2/publish/status.json?siteId=editorial`
```js
{
  response: {
    code: 0,
    message: "OK",
    remedialAction: "",
    documentationUrl: ""
  },
  publishingStatus: {
    enabled: true,

    status: null, // <=== `status` shouldn't be null ⚠️

    message: "Last successful publish was for package: 9d3b1ea6-9540-4974-91d4-cb65507cd3d0 on 2021-04-07T23:39:45Z with 200 items",
    lockOwner: null,
    lockTTL: null
  }
}
```

## To Reproduce
1. Call `/studio/api/2/publish/status.json?siteId=editorial`
2. See `response.publishingStatus.status`

## Expected behavior
Publishing status should always be one of the predefined status constants

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
- Please call @jvega190 to see live/debug if you don't see it
- Please assess if the fix should go into 4 too.

**Comment by dejan-brkic** [comment]
Can not reproduce the issue.
Without exact steps on how to reproduce it and by inspecting source code, the only possible cause is corrupted DB or manually tempered DB.

**Comment by rart** [comment]
@sumerjabri up to you how to proceed

**Comment by dejan-brkic** [comment]
The use case is not reproducible. The site in the example was created with an older build of the studio.

**Comment by sumerjabri** [comment]
@rart make sure the UI can handle `null` if it ever happens.

**Comment by jvega190** [comment]
I doesn't apply to 4.0.x. Removing tag
