### ISSUE TITLE
[studio] Publishing black list

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4659]
Create a publishing blacklist as follows:
- [x] Add a configuration item to the global YAML called publishing.blacklist as a comma-separated list of regexes
- [x] Ignore the files that match this blacklist from publishing and mark them as published and log the fact as level `debug`
- [x] Document
- [x] Test

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2519

Property name:
`studio.configuration.publishing.blackList.regex`

**Comment by yacdaniel** [comment]
Verified in `3.1.14`.

**Comment by alhambrav** [comment]
[3.1] PR https://github.com/craftercms/docs/pull/1229

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2555

**Comment by yacdaniel** [comment]
Verified in `4.0.0`
