### ISSUE TITLE
[studio] Don't insert .keep files into the database while absorbing content via Git

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4660]
When absorbing content via Git, don't insert .keep files into the database (similar to content flow via API).

To validate, create some folders via the UI, create another site via Git and see if the .keep files make it into the DB or not.

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/2557
https://github.com/craftercms/studio/pull/2558

**Comment by yacdaniel** [comment]
Verified in `3.1.15-SNAPSHOT`

**Comment by yacdaniel** [comment]
@sumerjabri  @dejan-brkic  In version 4(I'll verify on 3 and update ticket accordingly) if a developer creates an empty folder on his local IDE and add the .`keep` to commit the folder, then push to remote and finally pulls the change to Studio, the folder is not added to the site.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2693

**Comment by yacdaniel** [comment]
Verified fixed.
