### ISSUE TITLE
[studio-ui] Add screenshot to blueprints

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4671]
**Is your feature request related to a problem? Please describe.**
The new Sites management UI shows a picture for each site that has a pic @ `/.crafter/screenshots/default.png`. If the site doesn't have a pic there's a fallback but optimally, we push for sites having their screenshot.

**Describe the solution you'd like**
Take a good screenshot of each site and add it to each blueprint

**Describe alternatives you've considered**
Add the image in an alternative location TBD

**Additional context**
@jvega190 don't work this without Sumer's go ahead as the location of pic is still something we're exploring.
@sumerjabri please comment if you want to hold it or if we should proceed with this location.

**Comment by sumerjabri** [comment]
Let's use the default:
`/static-assets/.crafter/screenshots/default.png`

**Comment by jvega190** [comment]
Using this path `/.crafter/screenshots/default.png` - according to this: https://github.com/craftercms/craftercms/issues/4711

**Comment by jvega190** [comment]
@rart only the PR for wordify/next is pending

**Comment by sumerjabri** [comment]
@jvega190 please add the final screenies to Wodify/next
