### ISSUE TITLE
[studio] Speed up the get publish history API call

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4672]
Switch to a database-backed service to retrieve publish history and switch to API 2 format.

- [x] Update the backend
- [x] Update the frontend

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/2528
https://github.com/craftercms/studio-ui/pull/2293

**Comment by rart** [comment]
How come this doesn't apply to 4? What happens there?

**Comment by sumerjabri** [comment]
@rart https://github.com/craftercms/craftercms/issues/4675 is for 4
