### ISSUE TITLE
[studio] Create publish history table and use that to report

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4675]
Replace the publish history service V1 with a new service backed by the DB (similar to 3.1 https://github.com/craftercms/craftercms/issues/4672) but using a new table.

- [x] Design
- [x] Review design
- [x] Implement
- [x] Update UI
- [x] Remove old API
- [x] Remove old API from documentation (now that it's API2 and OASd)
- [x] Test

**Comment by dejan-brkic** [comment]
Design:
https://lucid.app/lucidchart/invitations/accept/inv_f032fb24-b64b-4ddf-b193-beb292a683ef?viewport_loc=-11%2C143%2C2219%2C1041%2C0_0

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/2353
https://github.com/craftercms/studio/pull/2586

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1268

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2633
