### ISSUE TITLE
[studio] ItemByPath API returns modifier null

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4679]
## Describe the bug
/studio/api/2/content/item_by_path always returns null value in modifier field under sandbox, even after editing the item.

## To Reproduce
1. Create a site based on editorial (next)
2. Check `item_by_path` calls under network
3. See that modifier is null

## Expected behavior
Modifier field should have a proper value.

## Screenshots
![image](https://user-images.githubusercontent.com/18267471/116318511-1f68bc00-a772-11eb-920a-fd8533e8b250.png)

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT-f3d304

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
@dejan-brkic can this be avoided/fixed?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2569

**Comment by jvega190** [comment]
Verified fixed
