### ISSUE TITLE
[studio-ui] Beautify version number/date formatting for version history

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#468]
Please change the version history table to have the columns:

Version Date and Time  |  Edited By  |  Comment  |  Actions

Please see attached. The red box notes the area to be changed.
![screen shot 2017-02-21 at 1 23 59 pm](https://cloud.githubusercontent.com/assets/3931908/23178765/9de0c3ee-f839-11e6-9d35-ce0cfc7a46e1.png)

**Comment by jvega-crafter** [comment]
Done, format is "DayOfWeek, MONTH DD, YYYY, HH:MM:SS AM ZONE" as discussed with Sumer

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/252
