### ISSUE TITLE
[studio] Update pull from remote and syncDbFromRepo to support multi-parent git repos

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4681]
To support multi-parent git repos, switch pull from remote to insert into gitlog and syncDBfromRepo to work per commit. See full design for details.

**Comment by sumerjabri** [comment]
@avasquez614 please help validate

**Comment by avasquez614** [comment]
Verified

**Comment by sumerjabri** [comment]
Verified fixed in 4.
