### ISSUE TITLE
[search] Number types _i are treated as float in Elasticsearch

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4682]
## Describe the bug
Some search are returning inexact results when we are searching for a value in a field with suffix _i.

Locally we have reviewed the mapping with this url
All the fields ending with _i have type float.
It seems somehow for big integers like 66229024 elastic is including results with very close values like 66229022 (this doesn't happen if the numbers are small).

## To Reproduce
1. Create a site in dev based on Empty BP
2. Add an _i field to the site
3. Populate the value with a large number `66229022`
4. Execute query
```
"MYSITE-preview_v1" : {
"mappings" : {
"_doc" : {
"dynamic_templates" : [
{
"ints" : {
"match" : ".+_(i|is|imv)$",
"match_pattern" : "regex",
"mapping" : {
"type" : "float"
}
}
}
```

## Expected behavior
Please change the type to integer for all the fields ending on _i.

## Screenshots
N/A

## Logs
N/A

### Version
```
Studio Version Number: 3.1.14-d66f40
Build Number: d66f40a1b1f57ab9b54c1c9ede51ccc6d0e4a959
Build Date/Time: 04-27-2021 13:56:17 -0400
```
### OS
Any

### Browser
N/A

**Comment by jdrossl** [comment]
@russdanner FYI all existing content needs to be re-indexed for the fix to take effect

**Comment by russdanner** [comment]
@alhambrav @sumerjabri 
This fix seems to require the index to be re-created. There's an impact to UM, Docs or both.

**Comment by sumerjabri** [comment]
@alhambrav please update the docs as required.

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/1194/commits/cc3c518bfeddae0a0d16016bda08c437fe36be2c

**Comment by russdanner** [comment]
Confirmed
