### ISSUE TITLE
[studio] Issue with publishing status

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4691]
## Describe the bug
Publisher appears to be disabled for all sites.

## To Reproduce
1. Create a new site using the Editorial BP
2. Click on the publishing status icon
3. See error

## Expected behavior
New sites should have publishing enabled

## Screenshots
![Screenshot from 2021-05-04 15-52-30](https://user-images.githubusercontent.com/1236955/117074747-feafe180-acf0-11eb-9b79-c1ced6eb3edf.png)

### Version
4.0.0-SNAPSHOT-4369a6

### OS
Ubuntu 20.04.2

### Browser
Chome 90.0.4430.93

**Comment by sumerjabri** [comment]
@rart BE is fixed, over to you for UI

**Comment by sumerjabri** [comment]
Verified.
