### ISSUE TITLE
[studio-ui] Can't edit templates or scripts from the sidebar

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4692]
## Describe the bug
Nothing happens when the `Edit` option is clicked

## To Reproduce
1. Create a site from the Editorial BP
2. Navigate to Templates or Scripts
3. Open the context menu for any asset
4. Click Edit

## Expected behavior
The code editor should open

## Screenshots
![Screenshot from 2021-05-04 16-08-38](https://user-images.githubusercontent.com/1236955/117076274-5cddc400-acf3-11eb-9969-d32445a9e70b.png)

### Version
4.0.0-SNAPSHOT-4369a6

### OS
Ubuntu 20.04.2

### Browser
Chome 90.0.4430.93

**Comment by sumerjabri** [comment]
The same is true of anything relying on the code editor.

**Comment by jdrossl** [comment]
Verified
