### ISSUE TITLE
[studio-ui] Change the FreeMarker import structure

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4693]
Please add a new FreeMarker template that is used as the entry point to all required imports.

Add the root file

```ftl
<#import "/templates/system/crafter.ftl" as crafter />
```

This new FreeMarker will then include the old ICE

```ftl
<#import "/templates/system/common/ice.ftl" />
```

Additionally, change:
- `initPageBuilder` to `bottomInclude`

The new macro will include the `initPageBuilder`.

We will support:
- `headInclude`
- `bottomInclude`

The purpose of this is to allow plugins to wire at the root of all FreeMarker includes for an application and allow these plugins to add functionality to Engine and Studio (delivery and authoring).

- [x] Implement and note the new scope `crafter` as opposed to `studio`
- [x] Update all blueprints
- [x] Document
- [x] Test using an example plugin

**Comment by rart** [comment]
@aachavarria please change the product ftls and reassign to @jvega190 to update the blueprints

**Comment by aachavarria** [comment]
@jvega190 You need to update the BP ftl's to use <#import "/templates/system/common/crafter.ftl" as crafter /> instead of <#import "/templates/system/common/ice.ftl" as studio />, also need to change <@studio.initPageBuilder/> to  these <@crafter.head/>
<@crafter.body_top/>
<@crafter.body_bottom/>

**Comment by jvega190** [comment]
@sumerjabri there are still a couple of RL blueprints PR's pending to merge.

**Comment by rart** [comment]
Work complete. Just PRs pending merge.

**Comment by alhambrav** [comment]
Verified all the doc changes for the  Freemarker import structure are merged and live.
https://github.com/craftercms/docs/pull/1368 and https://github.com/craftercms/docs/pull/1357

**Comment by sumerjabri** [comment]
Tested as part of the already developed plugins. Closing.
