### ISSUE TITLE
[plugin:contact-form] Add styles to the contact form

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4694]
Please add a default style to the contact form component and also add instructions on how to override with custom styles.

https://github.com/craftercms/contact-form-plugin

**Comment by alhambrav** [comment]
For items marked as required, it would be nice to have an asterisk or something next  to it.  This is how it looks like right now, note that `Name` and `Email` is marked as required in the content form
<img width="284" alt="Screen Shot 2021-05-19 at 10 31 56 AM" src="https://user-images.githubusercontent.com/25483966/118837827-2d05f300-b893-11eb-8fd3-bff50f583f68.png">

<img width="1482" alt="Screen Shot 2021-05-19 at 11 14 06 AM" src="https://user-images.githubusercontent.com/25483966/118838056-5cb4fb00-b893-11eb-8e5f-25500153e36f.png">

**Comment by jvega190** [comment]
@alhambrav the required markers are added now, please ping me if you have any questions

**Comment by alhambrav** [comment]
Hi!
It would be nice to add some styles to the thank you page.  Here's how the  thank you page currently looks like:
<img width="1186" alt="Screen Shot 2021-06-01 at 9 53 24 AM" src="https://user-images.githubusercontent.com/25483966/120549507-b2c08d00-c3c1-11eb-91e6-577b71378651.png">

**Comment by alhambrav** [comment]
Verified styles added.
