### ISSUE TITLE
[Studio] dom4j randomly break xml text value with hyphen to ArrayList 

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4695]
## Describe the bug
While parsing XML data with dom4j, there are cases that a single value text with hyphen is broken into ArrayList instead of single string. This causes xpath search failed. As a result, there are error while duplicating page:

query:  //*/text()[normalize-space(.)="/site/components/2020/08/10/d00bbda2-2d6c-da7f-e64f-73a7b318078b-e76baa55-50ad3096.xml"]/parent::*

wont's match element

 [org.dom4j.tree.DefaultText@451a9ce9 [Text: "/site/components/2020/08/10/d00bbda2-2d6c-da7f-e64f"], org.dom4j.tree.DefaultText@3e35fcaf [Text: "-73a7b318078b-e76baa55-50ad3096.xml"]]

(https://craftersoftware.zendesk.com/agent/tickets/2215)

## To Reproduce
1. Refer to above ticket

## Expected behavior
dom4j  should parse value as a whole text instead of ArrayList

## Screenshots
![correct_parse_xml](https://user-images.githubusercontent.com/2996543/117093086-e5636f80-ad9a-11eb-8d24-27dc05f1ced1.png)
![long_text_break_into_ArrayList_1](https://user-images.githubusercontent.com/2996543/117093088-e72d3300-ad9a-11eb-83a9-5081e7827def.png)
![long_text_break_into_ArrayList_2](https://user-images.githubusercontent.com/2996543/117093089-e7c5c980-ad9a-11eb-9e45-83b646637bf1.png)

## Logs
Refer to ticket

### Version
3.1.x

### OS
Ubuntu

### Browser
Chrome

## Additional context
https://www.mail-archive.com/dom4j-user@lists.sourceforge.net/msg02690.html

**Comment by phuongnq** [comment]
Suggest fix: https://github.com/craftercms/studio/pull/2543

**Comment by sumerjabri** [comment]
for 4.0: https://github.com/craftercms/studio/commit/0220b902bff5cd22749e8ac46ec80eed314c3d67

**Comment by phuongnq** [comment]
verify fixed
