### ISSUE TITLE
[studio-ui] Screenshot not set

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4697]
Screenshot not set image:
- [x] Change the image from "Preview Image Not Assigned" to "Screenshot not Set"
- [x] Document what that means and how to fix it for sites and plugins
  - Note: the default path where Studio will look is: "/static-assets/.crafter/screenshots/default.png"

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1293
