### ISSUE TITLE
[studio] Clustered Deployment Architecture

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#47]
Features to be reviewed and designed:
- master node vs deploying from all nodes
- preview sync
- environment stores sync
- deployment failover (in case of master node)
- scheduling vs locking queues
- events
- error handling
- notifications:

**Comment by sumerjabri** [comment]
This is a conversation we need to have and define the clustering approach and document it. I'll update the ticket.

**Comment by sumerjabri** [comment]
Validated via SonarQube.

**Comment by sumerjabri** [comment]
Completed. Tickets to implement are forthcoming.
