### ISSUE TITLE
[studio] NullPointerException being thrown when blob store ID is wrong in a .blob

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4702]
## Describe the bug
When a `.blob` file has a wrong blob store ID, Studio throws a `NullPointerException`

## To Reproduce
1. Setup a Studio site with a blob store
2. Upload an image to the blob store directory in Studio
3. Go to the filesystem and edit the `storeId` element of the `.blob` descriptor
4. Open the image for preview from Studio

You should see a `NullPointerException` in the logs

## Expected behavior
Studio should throw a more meaningful exception, indicating that the store ID is invalid or not found.

## Screenshots
N/A

## Logs
N/A

### Version
3.1.14

### OS
N/A

### Browser
N/A

## Additional context
{{Add any other context about the problem here.}}

**Comment by jdrossl** [comment]
@avasquez614 please validate in v4.0

@sumerjabri do we want to backport the v4 to v3.1 to support these exceptions?

**Comment by sumerjabri** [comment]
@yacdaniel  we won't be pursuing this for 3.1.x at this time. Please validate for 4.0.

**Comment by yacdaniel** [comment]
Verified fixed
```
Caused by: org.craftercms.commons.file.blob.exception.BlobStoreMissingException: Blob store not found in the configuration file
```
