### ISSUE TITLE
[studio-ui] Item icons in dashboard and site explorer does not match

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4716]
## Describe the bug
Item icons in dashboard and site explorer does not match

## To Reproduce
1. Create a site  using the  website editorial  bp.  Set up the  `staging` publishing target by opening  `Site Tools` -> `Configuration` -> `Site Configuration` and set the  `enable-staging-environment`  to  true

```
<published-repository>
        <enable-staging-environment>true</enable-staging-environment>
    </published-repository>
```

2. Create a user with `site_author` role.
3. Publish the whole site to staging.  Notice the icons next to the items says `live` instead of `staging`
<img width="479" alt="Screen Shot 2021-05-14 at 10 29 03 AM" src="https://user-images.githubusercontent.com/25483966/118285386-5ee81580-b49f-11eb-8ed6-49df0bee300a.png">

Look in the Dashboard and notice that it displays the correct publishing target for the recently published items
<img width="987" alt="Screen Shot 2021-05-14 at 10 57 41 AM" src="https://user-images.githubusercontent.com/25483966/118289471-627d9b80-b4a3-11eb-9291-a5d8fb227e63.png">

4. Login as the user author.  Edit a page then `Request Publish` for a later date.  For our example, the  page `Top Clubs in Virginia` is used.  Notice the icons next to the page displays  `Unpublished`  and `Modified`
<img width="925" alt="Screen Shot 2021-05-14 at 10 31 38 AM" src="https://user-images.githubusercontent.com/25483966/118285859-e2a20200-b49f-11eb-8863-b5be5ca58fa5.png">

5. Open  the dashboard and notice that it displays `staging` for the publishing target and `In workflow`  for the workflow state as  opposed to the previous step
<img width="1003" alt="Screen Shot 2021-05-14 at 10 25 21 AM" src="https://user-images.githubusercontent.com/25483966/118286162-2bf25180-b4a0-11eb-92a9-1e064cee63f1.png">

## Expected behavior
Item icons in dashboard and site explorer should match

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-5a24af

Build Number:
5a24af0c2c63347bb17cab237694306b014b1678

Build Date:
5/14/2021, 9:54 AM

### OS
macOS10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
related to https://github.com/craftercms/craftercms/issues/4733

**Comment by alhambrav** [comment]
Hi!

1. Create a site using the website editorial bp. 
2. Publish the whole site to `live`
3. Edit a page and publish it to `staging` 
4. Notice that the edited page published  to staging in the Sidebar `Site Explorer` displays the page as published to `staging`
<img width="1209" alt="Screen Shot 2021-07-09 at 12 56 17 AM" src="https://user-images.githubusercontent.com/25483966/125025488-bf837100-e050-11eb-9149-212880a2fda8.png">
5. Open the dashboard and notice that the edited page then published to staging does not display the same publishing target as in the `Site Explorer`
<img width="1185" alt="Screen Shot 2021-07-09 at 1 00 58 AM" src="https://user-images.githubusercontent.com/25483966/125025925-90213400-e051-11eb-8874-039d82d560ea.png">

**Comment by alhambrav** [comment]
Hi!
I'm still  seeing the same issue.  The status displayed in `My Recent  Activity`  is different than the one in the  context  nav and  sidebar.    Also, the dates listed is incorrect, `12/31/1969 7:00 PM`

Studio Version Number:
4.0.0-SNAPSHOT-be4b3d
Build Number:
be4b3dc2480bdec7712ad8920cc949080c5de9ed
Build Date:
7/16/2021, 3:21 PM

<img width="1526" alt="Screen Shot 2021-07-16 at 3 26 35 PM" src="https://user-images.githubusercontent.com/25483966/125999859-2a02f526-7b36-4083-a70e-8c83f6af4bae.png">

Also, after making an edit to the  Home page then  publishing it to staging, the sidebar and context nav displays it as `live` but the dashboard is displaying is correctly as staging

<img width="1532" alt="Screen Shot 2021-07-16 at 3 40 12 PM" src="https://user-images.githubusercontent.com/25483966/126000709-0ca66494-aa53-4629-aa57-a44c082c46f4.png">

<img width="1529" alt="Screen Shot 2021-07-16 at 3 40 23 PM" src="https://user-images.githubusercontent.com/25483966/126000782-1200534d-89d4-40fb-ac29-56d9e8a76bda.png">

**Comment by alhambrav** [comment]
Hi!
One more thing not matching between the dashboard and sidebar/context nav:

1. Create a site using website editorial bp
2. Navigate to one of the articles folder , for our example, navigate to /articles/2020/16 then click on the 3 dots next to the folder and select New Content, then click on Article
3. Fill in the required fields for the new page article and save your changes
4. Notice in the Site Explorer that the new page has the correct icons, new, etc.
<img width="1031" alt="Screen Shot 2021-07-21 at 1 31 02 PM" src="https://user-images.githubusercontent.com/25483966/126533623-20f13aa3-865a-42a2-a3d0-fcfb4a0c3849.png">

5. Open the dashboard, scroll  to  the My Recent Activity widget and notice that your newly created page has a lock on it instead of the new icon
<img width="1028" alt="Screen Shot 2021-07-21 at 1 28 45 PM" src="https://user-images.githubusercontent.com/25483966/126533853-b80f3e35-d13f-4f2b-ba30-b43c055dea92.png">

**Comment by jvega190** [comment]
@alhambrav fixed in here https://github.com/craftercms/craftercms/issues/4911

**Comment by alhambrav** [comment]
Verified fixed.
