### ISSUE TITLE
[studio-ui] Don't close form dialogs with data entry when the user clicks out of a dialog

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4717]
## Describe the bug
Some of the forms in Studio can be closed if the user clicks outside of them. This can cause loss of data entered in the form.

## To Reproduce
1. Go to Users, click `Create User`
2. Fill all fields, don't click save and click outside the form

Affected sections:

 - Create User
 - Edit user
 - Create Group
 - Edit Group
 - Create Access Token

Studio Preview:
- Edit
- Create a New Folder
- Create New Content
- Dependencies
- History
- Copy
- Request Publish
- Schedule
- Edit controller
- Edit template
- Delete template

- All the Site Tools forms(Content Types, Encryption Tools...)

If a section don't described here is affected and fixed, please update the ticket. 

## Expected behavior
Form shouldn't close and should kept the focus.

## Screenshots

https://user-images.githubusercontent.com/6722074/118287112-5f2ce480-b490-11eb-91b8-a75006935606.mp4

## Logs
N/A

### Version
`4.0.0-SNAPSHOT`

### OS
Any

### Browser
Chrome & Firefox

## Additional context
N/A

**Comment by yacdaniel** [comment]
@rart sections still affected:

- Edit User
- Create Access Token

Preview:
- Create folder
- Copy
- All the Site Tools forms(Content Types, Encryption Tools...), open a section, edit something and click outside.

Also notice the example of creating a group, an user and user and clicking outside the form, the user experience is different(one with a dialog and another without)

![closing dialogs](https://user-images.githubusercontent.com/6722074/130635700-c3166ee6-ae4e-4682-9222-c12800014c32.gif)

**Comment by rart** [comment]
@aachavarria 
1. across dialogs, whenever there's input, let's drop the disabling of backdrop & escape in favour of a dismiss confirm.
2. On dialogs that have a submission, when submitting, backdrop click, escape or dismiss button should be disabled (i.e. you can't close the dialog at all while submission is in progress, nor you get the confirm, it's simply disabled all together with it's ui)

**Comment by yacdaniel** [comment]
Verified fixed.
