### ISSUE TITLE
[studio] S3 Transcoder not working

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4718]
## Describe the bug
When configuring and using the s3 transcoder, it fails and shows an error with the CLIENT_ENDPOINT field.

## To Reproduce
1. Setup s3 transcoder https://docs.craftercms.org/en/3.1/developers/cook-books/aws/upload-transcode-video.html
2. Use transcoded-video-picker with video-s3-transcoding to upload a video.
3. See that upload fails.
4. See tomcat log.

## Expected behavior
Video transcoder should upload and transcode the videos properly.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/jvega190/a14be6146ea5f67172f2a1ac9e6ea0e0

### Version
4.0.0-SNAPSHOT-0220b9

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
3.1.x is working correctly

**Comment by jdrossl** [comment]
I'm not able to reproduce this issue, @jvega190 please make sure all your installation is updated since the error seems to be related with a conflict of classes within the aws sdk

**Comment by jvega190** [comment]
After upgrading the installation it's not happening anymore, closing the ticket
