### ISSUE TITLE
[studio-ui] Dashboard  issues

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4719]
## Describe the bug
Dashboard  issues

- After requesting to  publish a couple pages, the Author's dashboard looks different than an  admin's/publisher's dashboard
- After approving a publish request,  the  approved item  still appears  in the  waiting for approval  widget in  the dashboard
- After  item has  been  published, the icon next to it still  display the  `In  Workflow` icon.   It is marked as  `Live - In Workflow  - Live`
- Approved scheduled items disappears from the widget after closing then re-opening the dashboard

## To Reproduce
1. Create a site using the website  editorial bp, publish the  site.  Next create a user `author`
2. Login  as  user  author  and edit a page.   Request publish for  later time  the edited page, check the dashboard.  We'll use the `Top Romantic Valentine Movies` page for our  example.   The  dashboard should display the page as `In Workflow`
<img width="1070" alt="Screen Shot 2021-05-17 at 2 28 30 AM" src="https://user-images.githubusercontent.com/25483966/118442896-33407780-b6b9-11eb-98b2-e58ffb914a43.png">
Edit another page and request to publish now.  We'll  use the page `10 Tips to get  a  six  pack` page  for this example.

3. Logout and login as a user with publishing rights.  Check the  dashboard.  Notice that there are more items  listed  as  waiting for approval  compared to the  dashboard of the user  author
<img width="1078" alt="Screen Shot 2021-05-17 at 2 29 03 AM" src="https://user-images.githubusercontent.com/25483966/118443117-874b5c00-b6b9-11eb-87e9-95a0b496c1ea.png">

4. Still logged in as a  user with publishing rights, approve the page to be published at a later date from the dashboard (`Top Romantic Valentine Movies` page).  Notice in the  dashboard that the approved page goes to the `Approved Scheduled Items`  widget  and the `Items Waiting for Approval` widget.

<img width="1085" alt="Screen Shot 2021-05-17 at 2 29 37 AM" src="https://user-images.githubusercontent.com/25483966/118443600-16f10a80-b6ba-11eb-9acd-18b1c89ebe34.png">

5. Close the dashboard, then open it again.  Notice that the item in the `Approved Scheduled Items` widget disappeared

<img width="1079" alt="Screen Shot 2021-05-17 at 2 30 00 AM" src="https://user-images.githubusercontent.com/25483966/118443883-70f1d000-b6ba-11eb-9b27-12724edc745b.png">

6. Now approve the page to be published now (`10 Tips to get  a  six  pack` page).  Notice in the dashboard the published item still displays an `In Workflow` icon and it appears in  the `Recently Published` widget and the `Items Waiting for Approval` widget

<img width="1080" alt="Screen Shot 2021-05-17 at 2 33 04 AM" src="https://user-images.githubusercontent.com/25483966/118444505-33da0d80-b6bb-11eb-9bd3-c10ddd4e96f7.png">

## Expected behavior
- After requesting to  publish a couple pages, the dashboard items listed should  be the same for an author and user with publishing rights
- After approving a publish request,  the  approved item  should disappears  from the  waiting for approval  widget in  the dashboard
- After  item has  been  published, the icon next to should not  display the  `In  Workflow` icon or `Scheduled` icon.   
- Items in the `Approved scheduled items` should not disappear from the widget until the item has been published

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-5a24af
Build Number:
5a24af0c2c63347bb17cab237694306b014b1678

### OS
macOS 10.15.17

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2640

**Comment by alhambrav** [comment]
Here's some more issues I noticed in the dashboard (I am not sure  if they are backend or ui issues...  ):
* After publishing the whole site to staging, then publishing it to live, the pages looks like it's displayed twice with the newer one displaying the correct status, `live` and the older one displaying it is in `staging`

<img width="975" alt="Screen Shot 2021-07-16 at 8 04 33 AM" src="https://user-images.githubusercontent.com/25483966/125945104-72bcfc0a-d4f1-4648-a147-d457cc3c56a1.png">

Following the steps listed above, the author  dashboard  and  the admin dashboard still  looks  different.  After logging in as an author and requesting the page to be published at a later time, the dashboard displays the item as `Unpublished` and `New`, as  opposed to  `Unpublished` and `Submitted`

<img width="1466" alt="Screen Shot 2021-07-16 at 8 12 59 AM" src="https://user-images.githubusercontent.com/25483966/125947794-baf71137-3228-4fca-bfbe-597a8d5765f3.png">
After editing another page and requesting publish:
<img width="1431" alt="Screen Shot 2021-07-16 at 8 36 49 AM" src="https://user-images.githubusercontent.com/25483966/125948760-c5507ba1-3885-44fd-9c8b-2e2c66cbcd13.png">

Login as user `admin`, the dashboard for `Items Waiting for Approval` looks different from the author's dashboard:
<img width="1465" alt="Screen Shot 2021-07-16 at 8 34 43 AM" src="https://user-images.githubusercontent.com/25483966/125948606-fd1d8312-8ae3-4368-97a5-fe8091d18fb8.png">
(Sidenote: Should both pages display status as `Submitted` instead of one of them  displaying as `Scheduled` since  it hasn't been approved yet)

Thanks!

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/2662

Publishing:
When the user publishes 1 page to 2 different environments (staging and live), it is displayed as 2 different publishing events. That is why there are duplicated items in the Recently Published dashboard. It is displaying the last publishing event for each content per environment.

Published date:
BE sends null. Epoch time is displayed by UI

**Comment by alhambrav** [comment]
Assigning to @rart  for UI issue mentioned by @dejan-brkic.
I have shown @jvega190 the issues.  
For the 2 different publishing  events, I was expecting a different date/time for the two entries 
<img width="868" alt="Screen Shot 2021-07-20 at 10 54 22 AM" src="https://user-images.githubusercontent.com/25483966/126346362-2dda95ca-c5ab-4cb0-878d-63e354f492fa.png">

**Comment by alhambrav** [comment]
Verified fixed.
