### ISSUE TITLE
Creating a new type: controller.js and extract.js files are created.

### ISSUE THREAD

**Issue by isaiulatesancho** [craftercms/craftercms#472]
controller.js and extract.js are generated when creating a new type.
Those should be groovy files instead.

Steps to reproduce:
- Go to admin console
- Create new content type
- Go to the repository and browse the content type definition
- See the newly generated controller.js and extract.js

**Comment by sumerjabri** [comment]
This is fixed in 3.0. Are you requesting this fix in 2.5.x?

**Comment by isaiulatesancho** [comment]
We are using 2.5.5 for Studio and 2.5.3 for engine.
Not critical but should be fixed.

**Comment by russdanner** [comment]
Vero the extension and the content of the files need to change.

Files are written by the static-assets/components/cstudio-dialogs/new-content-type.js dialog   You will find the path and the contents of the file in the JS file.  Both need to be updated.  

This isn't really the best place for the logic/contents of these files but we'll handle moving that later.

Sumer already updated this in Crafter 3.0/Master
https://github.com/craftercms/studio2-ui/pull/249/files
https://github.com/craftercms/studio2-ui/commit/e110931351e55d927a62697b8c9d0d15acc6cf45
