### ISSUE TITLE
[studio-ui][studio] Site Policy file size does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4722]
## Describe the bug
File size configured in the site policy does not seem to be  working.

## To Reproduce
1. Create  a site using any bp. Setup the following site policy:
```
<?xml version="1.0" encoding="UTF-8" ?>
<site-policy>
   <statement>
     <target-path-pattern>/static-assets/images/.*</target-path-pattern>
       <permitted>
         <maximum-file-size>1000000</maximum-file-size>
         <mime-types>image/*</mime-types>
        </permitted>
    </statement>
</site-policy>
```
2. Open the `Site  Explorer` and navigate to `/static-assets/images`
3. Upload an image.  Notice that the dialog is stuck just displaying a sand timer next to the file name being uploaded

<img width="786" alt="Screen Shot 2021-05-17 at 10 52 42 AM" src="https://user-images.githubusercontent.com/25483966/118531954-6c5a0580-b714-11eb-920a-45238ce2c0bd.png">

4. Look in the logs and the console, and see the error message there.

```
[ERROR] 2021-05-17T10:50:05,771 [http-nio-8080-exec-7] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/sites/mysite/policy/validate failed with response: ApiResponse{code=1000, message='Internal system failure', remedialAction='Contact support', documentationUrl=''}
java.lang.NullPointerException: null
```
<img width="1050" alt="Screen Shot 2021-05-17 at 11 26 25 AM" src="https://user-images.githubusercontent.com/25483966/118532098-927fa580-b714-11eb-8c4b-fe3279d13242.png">

Investigation by @jdrossl turned up the following:

This is an issue on both front & back, the UI is not sending the size of the file in the request and the back is throwing a NPE instead of a useful message

## Expected behavior
File size site policy  should work.

The UI should send the size of the file in the request and 
the back should send a useful message instead of throwing a NPE 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-5a24af

Build Number:
5a24af0c2c63347bb17cab237694306b014b1678

### OS
macOS

### Browser
Chrome Browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by aachavarria** [comment]
@jdrossl I sent a PR https://github.com/craftercms/studio-ui/pull/2327, however looks like site policy is not working at all, please check it

**Comment by aachavarria** [comment]
<img width="431" alt="Captura de Pantalla 2021-05-19 a la(s) 15 37 17" src="https://user-images.githubusercontent.com/10813283/118887835-2473e380-b8b8-11eb-86d9-a3a907acf323.png">

@jdrossl The ui is now sending the fileSize, see above image, however the validate call is returning Status Code: 500 

<img width="442" alt="Captura de Pantalla 2021-05-19 a la(s) 15 38 37" src="https://user-images.githubusercontent.com/10813283/118887981-4f5e3780-b8b8-11eb-8b5e-69232fcacb5b.png">

**Comment by alhambrav** [comment]
Hi!
The upload still fails with the following error message:

```
[ERROR] 2021-05-21T09:19:28,670 [http-nio-8080-exec-8] [processing.AssetProcessingServiceImpl] | Error processing asset
java.lang.IllegalArgumentException: File size is required for validation
```

I am uploading a 75kb png file, which should fit in with the conditions in the site policy config

<img width="1529" alt="Screen Shot 2021-05-21 at 9 30 27 AM" src="https://user-images.githubusercontent.com/25483966/119144993-38822700-ba17-11eb-918b-d748fbb0bf83.png">

Here's the full error message:
https://gist.github.com/alhambrav/7bd3d95b89085f53dae0e2e7edbeffff

@aachavarria , would it be possible to change the color of the filename to something else instead of green when an upload fails? I wasn't quite sure if that file uploaded properly or  not since I see green.  Thank you!

**Comment by alhambrav** [comment]
@jdrossl   Hi! I'm not sure if this is related to the site policy  config, but there's an error message in the tomcat log whenever you upload something:

```
[ERROR] 2021-05-22T00:39:16,103 [http-nio-8080-exec-2] [internal.ItemServiceInternalImpl] | Label = null
```

**Comment by jdrossl** [comment]
@alhambrav That error message is not related to the site policy

**Comment by alhambrav** [comment]
Verified fixed.
