### ISSUE TITLE
[studio] Remove the old item state APIs

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4728]
## Describe the bug
Remove the old item state APIs
`/api/1/services/api/1/content/get-item-states.json`, `/api/1/services/api/1/content/set-item-state.json`
### Version
`4.0.0`

**Comment by dejan-brkic** [comment]
Done as a part of Workflow management API ticket
https://github.com/craftercms/craftercms/issues/4720

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
