### ISSUE TITLE
[studio] Display unmet Site Policy condition on failed uploads

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4730]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Setup file size limits in your site policy configuration.  When a file is uploaded that exceeds the max size listed in the site policy config, You'll get this error message in the tomcat log:
```
[ERROR] 2021-05-21T10:34:05,458 [http-nio-8080-exec-6] [internal.PolicyServiceInternalImpl] | Validation failed for Action{type=CREATE, source='null', target='/static-assets/images/15906062177_6e6a2bf6e0_o.jpg', recursive=false}
org.craftercms.studio.api.v2.exception.validation.ValidationException: File size should be less than 1000000
```

On the UI, you'll get a message that it doesn't comply with site policy, but doesn't tell you what the site policy is that the upload didn't comply with.
<img width="886" alt="Screen Shot 2021-05-21 at 10 34 43 AM" src="https://user-images.githubusercontent.com/25483966/119161825-b9e1b580-ba27-11eb-9e68-02eb947a248b.png">

#### Describe the solution you'd like
It would be nice to display the error message from the tomcat log   `File size should  be less than 1000000`  in the ui, which tells the user what size the file should be or something like it that tells the user what site policy was not met

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
{{Add any other context or screenshots about the feature request here.}}

**Comment by phuongnq** [comment]
`/sites/{siteId}/policy/validate` response now has a detailed message. For example:

```
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "results": [
        {
            "type": "CREATE",
            "target": "/static-assets/images/xxxxx.jpg",
            "allowed": false,
            "modifiedValue": null,
            "message": "File size should be less than '1000000' bytes"
        }
    ]
}
```

**Comment by sumerjabri** [comment]
@rart please see if there is anything the UI must do to complete this enhancement.

**Comment by rart** [comment]
@jvega190 let's check/include the new friendly message on the validations. Check all around: copy pasting, uploading, bulk upload, etc. Find all usages of validation to ensure coverage.

**Comment by phuongnq** [comment]
@sumerjabri @jvega190 I sent a PR for this. An example of message:

```
Path is replaced from source regex '[\\(\\)\\s]' to target regex '-'. Path is transformed to lowercase.
```

If there is no text replacement or case transformation, that specific part will not be included in the reason message.

Let me know if we want to update the reason text.

**Comment by sumerjabri** [comment]
@phuongnq please see the PR notes.

We must make sure the error responses are being escaped. CC @Euquimides @yacdaniel.

**Comment by phuongnq** [comment]
@sumerjabri Please review @rart above commen. 
Let me know if we want to change the reason message for the current PR. Regexs will be tricky since we don't know what Regex is being used. We also don't have i18n in the backend AFAIK.

**Comment by sumerjabri** [comment]
@phuongnq I discussed this with @rart and we agreed to do what I wrote in the PR comments. We just need the "message" to have the source-file and target-file in the response. See my notes in the PR, please.

**Comment by alhambrav** [comment]
Verified fixed.
