### ISSUE TITLE
[studio] Publishing an item doesn't clear `Edited` nor `New` states

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4733]
## Describe the bug
Item state transition doesn't clear the first nor second bits in the state (New/Edited) after a publish.

## To Reproduce
1. Create a site
2. Publish an item before or after editing it
3. See item state

## Expected behavior
A published item is no longer Edited nor New. Additionally, the bitmap spec in the OAS docs is outdated, please update.

## Screenshots
N/A

## Logs
N/A

### Version
4.0.0-SNAPSHOT (2021/5/24)

### OS
Linux

### Browser
Chrome

## Additional context
N/A

**Comment by jvega190** [comment]
@sumerjabri @dejan-brkic I've seen a couple of things related with the item states.

1. When publishing items to staging (new site, and publish to staging), the state of the items return as 355, which matches live but not with stating.
2. When requesting a publish as an author, the item state matches edited and submitted, is edited ok in that case?

**Comment by rart** [comment]
> @sumerjabri @dejan-brkic I've seen a couple of things related with the item states.
> 
> 1. When publishing items to staging (new site, and publish to staging), the state of the items return as 355, which matches live but not with staging.
> 2. When requesting a publish as an author, the item state matches edited and submitted, is edited ok in that case?

As far as state goes, this is how we show the relevant icon and status text:
```js
  switch (true) {
    case stateMap.deleted:
      return "Deleted";
    case stateMap.locked:
      return "Locked";
    case stateMap.modified:
      return "Modified";
    case stateMap.systemProcessing:
      return "System Processing";
    case stateMap.submitted:
      return "Submitted";
    case stateMap.scheduled:
      return "Scheduled";
    case stateMap.new:
      return "New";
```
Only one of these will be presented so if for example, the state map says it's `modified` **and** `scheduled`, only the modified state will show on the UI. For this reason, the backend should either send only one of these as true **or** we need to coordinate the presence of the switch cases to make sure we get the result we want.

We've had this problem with the new flag because it was `new` and _something else_ and we wanted the something else, so we ended up moving new to the end of the switch.

**Comment by sumerjabri** [comment]
@dejan-brkic this is the precedence I came up with, what do you think?
```js
switch (true) {
    case stateMap.systemProcessing:
      return "System Processing";
    case stateMap.locked:
      return "Locked";
    case stateMap.deleted:
      return "Deleted";
    case stateMap.modified:
      return "Modified";
    case stateMap.scheduled:
      return "Scheduled";
    case stateMap.submitted:
      return "Submitted";
    case stateMap.new:
      return "New";
```

**Comment by dejan-brkic** [comment]
I think deleted should go on top, the rest is ok

**Comment by jvega190** [comment]
@sumerjabri @dejan-brkic @rart it still happens that we have both `scheduled` and `modified`, and because of the precedence it'll only show modified. Should scheduled be up in the precedence, or should the backend only send one of these as true?

Also, when publishing to staging, the state is still not matching the `staged` mask, but it does match the `live` one.

**Comment by sumerjabri** [comment]
@jvega190 scheduled should have higher precedence, good call.

**Comment by sumerjabri** [comment]
@dejan-brkic seems like a bug for the staging flag, please fix it.

**Comment by sumerjabri** [comment]
@dejan-brkic I also tested and the Edited bit remains set after publish. Ping me if you'd like a demo.

**Comment by rart** [comment]
> I think deleted should go on top, the rest is ok — dejan

> @jvega190 scheduled should have higher precedence, good call. — sumer

Based on latest comments, updated logic would be:
```js
switch (true) {
    case stateMap.deleted:
      return "Deleted";
    case stateMap.systemProcessing:
      return "System Processing";
    case stateMap.locked:
      return "Locked";
    case stateMap.scheduled:
      return "Scheduled";
    case stateMap.submitted:
      return "Submitted";
    case stateMap.modified:
      return "Modified";
    case stateMap.new:
      return "New";
```

@sumerjabri please confirm 👆

**Comment by sumerjabri** [comment]
@rart looks good. Bear in mind that `deleted` will change down after we build the Recycle Bin. Be ready to make that change in the future and best to leave a `todo` there somewhere to remember.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2605
