### ISSUE TITLE
[studio-ui] Move publishing status to bottom right of site tile in main menu

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4735]
The current publishing status is on the top left of the site tiles, that's the most prominent and most important spot (ahead of the name). Please move it to the bottom right as this is not that critical.

Ping me if you have questions or concerns.

**Comment by rart** [comment]
As agreed, will go with 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/3928341/119392988-b755b900-bcd0-11eb-8b36-d3f7d60f9b78.png">
