### ISSUE TITLE
[studio] Item/children retrieval APIs returns null for empty container folder content item

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4739]
## Describe the bug
The concrete bug is on the OOTB Empty blueprint, calling any children retrieval API returns nothing at all for `/site/components`. My interpretation is that because that directory happens to be empty on this blueprint, the backend is somehow ignoring it. There may be more to this as this is my conclusion from inspecting the bug.

Issue affects all retrieval apis:
- `item_by_path?path=/site/components` returns `null`
- `children_by_path?path=/site/components` returns `children` prop as `null` instead of `[]`
- `sandbox_items_by_path?paths=[/site/components]` returns `items` prop as `[]`

## To Reproduce
1. Create Empty blueprint from create site dialog
2. Go to preview & select Site Explorer on the sidebar
3. See UI crash. Inspect the network tab and notice the `sandbox_items_by_path` request for `/site/components` doesn't return the expected item.

## Expected behavior
The folder's content item object is returned despite it not having children

## Screenshots
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/3928341/119616627-1c103100-be01-11eb-808d-2406e44df7ec.png">
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/3928341/119616651-23cfd580-be01-11eb-944a-d1cea2109e4c.png">
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/3928341/119616685-30ecc480-be01-11eb-9aa4-5d002b0caf47.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3928341/119616729-3ba75980-be01-11eb-859a-13e000ce6882.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
When a path doesn't exist, the APIs return a 404 but in this case is a 200 so in some way the item/path is found but no item is retrieved.

**Comment by dejan-brkic** [comment]
done
PR
https://github.com/craftercms/studio/pull/2578

**Comment by rart** [comment]
Verified
