### ISSUE TITLE
[docs] Outdated documentation for logging override

### ISSUE THREAD

**Issue by mcgitty** [craftercms/craftercms#4740]
## Describe the bug
CrafterCMS 3.1 documentation topic "[Permanently Set Logging Levels](https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/override-logging-levels.html#permanently-set-logging-levels)" is no longer applicable to 3.1. This file mentioned in Step 2 does not exist in 3.1:

    bin/apache-tomcat/webapps/studio/WEB-INF/classes/log4j.xml

That file exist in 2.5.x.

## To Reproduce
https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/override-logging-levels.html#permanently-set-logging-levels

### Version
3.1.x

**Comment by alhambrav** [comment]
https://github.com/craftercms/docs/pull/1266 and https://github.com/craftercms/docs/pull/1267
