### ISSUE TITLE
[docker-compose] Add scripts for start/stopping containers and tailing their logs

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4743]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Right now it seems it's still not clear how to run Docker Compose, especially the enterprise version

#### Describe the solution you'd like

Please add the following scripts (make sure there's an `.sh` and a `.bat` version) under the `scripts` folder of the Docker Compose project (make sure it's in the `support/3.1.x` branch):

1. `start.sh ENVIRONMENT` to start Authoring or Delivery detached (`docker-compose up -d`). The script should also accept a flag indicating that the enterprise version should run. E.g. `start.sh authoring --enterprise`.
2. `stop.sh ENVIRONMENT` to stop Authoring or Delivery (`docker-compose down`. There's a `stop` version of Docker Compose but I think `down` is better in general since it does a complete cleanup). It should also accept the following flags:
   - `enterprise`: stop an enterprise version.
   - `delete-volumes`: besides stopping, clean up all the volumes (`docker-compose down -v`). Of course, do a warning that all the volumes will be deleted before proceeding.
3. `logs.sh ENVIRONMENT` to tail the logs of Authoring or Delivery (`docker-compose logs -f`).

**Comment by phuongnq** [comment]
PR is merged. Please double-check if this can be closed
