### ISSUE TITLE
[craftercms] Gradle doesn't handle properly all errors

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4749]
## Describe the bug
Some compilation errors are only logged but the system continues executing all tasks

## To Reproduce
1. Cause a compilation error in any of the projects
2. Run `./gradlew clean build deploy start`

## Expected behavior
The compilation errors should cause gradle to stop executing the next tasks

### Version
4.0.0-SNAPSHOT

### OS
Ubuntu 20.04.2

**Comment by sumerjabri** [comment]
Fixed.

**Comment by jdrossl** [comment]
Verified
