### ISSUE TITLE
[search] ES issues supporting the binary files with metadata

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4750]
## Describe the bug
When using ES the binary files with metadata have the following issues:

- Additional fields using the Solr syntax `company.name` are not properly merged with the main JSON that is indexed
- Some queries to fetch related metadata are using the `_id` field instead of `localId`

### Version
3.1.x

## Additional context
Issues found while working on https://github.com/craftercms/craftercms/issues/4736

**Comment by sumerjabri** [comment]
@jdrossl what about v4?

**Comment by jdrossl** [comment]
@sumerjabri those fixes were included in https://github.com/craftercms/craftercms/issues/4736

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.15-SNAPSHOT`
