### ISSUE TITLE
[studio][deployer] Handle site creation for incompatible blueprints

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4751]
After work for https://github.com/craftercms/craftercms/issues/4736 is completed sites using Solr & Crafter Search will no longer work so both Studio and Deployer should properly detect them and inform the user that it is an incompatible blueprint.

- [x] Deployer will log the failure and indicate that Solr is no longer supported in v4 and reference the Solr to Elasticsearch upgrade article in the docs
- [x] Studio will log the same (see above)
- [x] Studio UI will indicate to the user the reason for failure using the exception thrown from the back end
- [x] Test

**Comment by jdrossl** [comment]
@yacdaniel please help verify this ticket

**Comment by yacdaniel** [comment]
Verified in `4.0.0-SNAPSHOT` the API response for both Deployer and Studio when `CrafterSearch` target/site is trying to be created.
