### ISSUE TITLE
[studio-ui] The date and time control in content type is not displaying in content form except when "Use custom timezone" property is checked

### ISSUE THREAD

**Issue by RashaRmeh** [craftercms/craftercms#4752]
## Describe the bug
When the admin go to the content type to add " Date& Time" control to the content form, the control will not show in content form if the user did not checked the "Use Custom Timezone" property 

## To Reproduce
1. Go to preview page of the site
2. Click on Site tools 
3. Click on Content type
4. Create new content type
5. Drag Date&Time control to the page properties
6. Check only Show date and Show time properties
7. Go to the Site explorer, click on New content option 
8. Scroll down in the form
4. See error the Date and time control  is not displaying in the content form 
5. Repeat the same steps but click also on "Use Custom Timezone" property and the date and time will show in content form

## Expected behavior
The date and time control should be displayed in the content form without the need to check the "Use Custom Timezone property" 

## Screenshots
https://user-images.githubusercontent.com/81047683/120695525-81a39380-c479-11eb-84a4-0cb5c4a5bb10.mov

## Logs
N/A
### Version
`4.0.0-SNAPSHOT-36c49e`

### OS
`Ubuntu 18.04`

### Browser
Chrome
## Additional context
N/A

**Comment by yacdaniel** [comment]
Verified fixed.
