### ISSUE TITLE
[studio] Add system type "file" instead of "unknown" for system files using API workflow/item_states

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4753]
## Describe the bug
Using new API /studio/api/2/workflow/item_states, is returning items without systemType("unknown")

## To Reproduce
1. Create a site using Editorial
2. do a GET to  /studio/api/2/workflow/item_states?siteId=editorial
3. check the response

## Expected behavior
the system type for this files should be 'file'

## Screenshots
<img width="653" alt="Captura de Pantalla 2021-06-03 a la(s) 12 48 07" src="https://user-images.githubusercontent.com/10813283/120698062-c0cae800-c46b-11eb-9514-30700ed7946c.png">

### Version
Studio Version Number:
4.0.0-SNAPSHOT-1ea0fa
Build Number:
1ea0fa7f728bc53cd848fe7d44b9f51e90deea1c

### OS
macOs Big Sur

### Browser
Any Browser

**Comment by aachavarria** [comment]
@dejan-brkic I noticed that the lockOwner is null even when it is already locked

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2638

**Comment by aachavarria** [comment]
verified
