### ISSUE TITLE
[studio-ui] Content form engine opened thorough "new content" action can't be closed

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4758]
## Describe the bug
When an user opens the form engine though the new content option, the dialog can't be closed. 

## To Reproduce
1. In Sidebar right click in Home and select `New Content` 
2. Open any content type
3. Click Cancel

## Expected behavior
Form should be closed when cancelled. 

## Screenshots
N/A

## Logs
N/A

### Version
`3.1.15-SNAPSHOT`

### OS
Ubuntu

### Browser
Chrome

## Additional context
N/A

**Comment by sumerjabri** [comment]
@rart please make sure this is not the case in 4

**Comment by jvega190** [comment]
@sumerjabri just tested and it's not happening in 4

**Comment by yacdaniel** [comment]
Verified fixed.
