### ISSUE TITLE
[studio] Create site and site listing fail due to missing publish_status permission

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4760]
## Describe the bug
Site creation and site listing fail due to missing `publish_status` permission.

## To Reproduce
1. Create a site from Editorial BP
2. Watch the logs and the site listing screen

## Expected behavior
Site creation and site listing should work. Additionally, we should consider that `publish_status` is a must permission for those viewing the site listing.

## Screenshots
![image](https://user-images.githubusercontent.com/3931908/121085117-77ea9a80-c7af-11eb-8f55-8e657bff60bc.png)

## Logs
```logs
[ERROR] 2021-06-07T16:46:49,863 [http-nio-8080-exec-3] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/publish/status?siteId=ed failed with response: ApiResponse{code=2001, message='Unauthorized', remedialAction='You don't have permission to perform this task, please contact your administrator', documentationUrl=''} 
org.craftercms.commons.security.exception.ActionDeniedException: Current subject does not have permission to execute action "publish_status" on {siteId=ed}

```

### Version
4.0.0-SNAPSHOT on 6/7/2021

### OS
Linux

### Browser
Chrome

## Additional context
N/A

**Comment by sumerjabri** [comment]
@dejan-brkic please add `publish_status` to the UM to make sure it's added to the `global` repo. Also, update the default global repo.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2598
