### ISSUE TITLE
[studio] Prevent deletion of Git Repo User admin account

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4761]
Prevent the deletion of Git Repo User in a similar way to the super admin.

**Comment by dejan-brkic** [comment]
Git repo user does not exist in 3.1

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2634

**Comment by yacdaniel** [comment]
Verified fixed.
