### ISSUE TITLE
[studio] Optimize Site Create and Bulk Publish's audit logs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4762]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Site creation and bulk publish log in the Audit Params every file enacted upon. This is slow and unnecessary. It's best to log the actual params to those methods and not create these very large audit param logs.

#### Describe the solution you'd like
For site creation, log the BP or source Git repo as a param.
For bulk publish, log the regex used to bulk publish.

#### Describe alternatives you've considered
Didn't consider other alternatives.

#### Additional context
Site creation and bulk publish are heavy operations and are made heavier and slower with unnecessary large audit logs.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2639
