### ISSUE TITLE
[studio] Support out of the box pre-configured image and video transform/transcode

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4765]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Presently administrators have to set up rules to invoke transformation services when users upload image and video assets. Oftentimes implementations do not include this configuration because these configuration tasks are overlooked.

#### Describe the solution you'd like
Support out of the box image and video transform/transcode that are pre-configured

**Comment by sumerjabri** [comment]
Done.
