### ISSUE TITLE
[studio] Site created with same ID as previously deleted site does not replicate in cluster

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4767]
## Describe the bug
 Site created with same ID as previously deleted site does not replicate in cluster
 
## To Reproduce
1. In a cluster (typically 2 nodes but in the case witnessed there were 3 nodes, create a site and let it replicate
3. Delete the site
4. Create another site with the same name
5. Note that it does not replicate

## Expected behavior
You should be able to delete and re-create a site with the same ID any number of times in a cluster 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
N/A

### Version
3.1.12E

### OS
Any

### Browser
Any

## Additional context
For the site record entries in the database that were marked with a deleted flag:
1. first we noticed that the deleted flag was true but the state said created. So we updated the state to say deleted. This cause the site to be replicated and then deleted on the other nodes.

2. The we physically deleted the rows in the site table that had the deleted flag set true.  This left a single record in the site table for the site -- and the then site replicated properly in the cluster.

**Comment by russdanner** [comment]
@yacdaniel the use case is a good item for our test harness (if not present) and needs to be reviewed for 3.1.15 and 4.0.0

**Comment by sumerjabri** [comment]
@yacdaniel please close if you cannot replicate

**Comment by yacdaniel** [comment]
Not able to reproduce with the above steps. Please reopen/update if needed.
