### ISSUE TITLE
History comparison is confusing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4768]
Looking at an item's history and then comparing current to prior versions can get confusing.

Once a user begins to compare versions, it's easy to get back to "select another version to compare to" instead of back where they were in the history dialog. It's also easy to click the X and be thrown out of the whole experience.

See this video:

https://user-images.githubusercontent.com/3931908/121421248-f70cd980-c93b-11eb-915e-f6a9945875a5.mp4

Let's meet and discuss options.

**Comment by rart** [comment]
@jvega190 ping me to discuss before starting.
