### ISSUE TITLE
[studio] Groups Management - Get group per site returns only one group

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#477]
/studio/api/1/services/api/1/group/get-per-site.json?site_id=pluton

Service returns only one group, even though there are many group on that site

**Comment by dejan-brkic** [comment]
Already fixed

**Comment by sumerjabri** [comment]
Doesn't work per doc. Please fix. Example: http://localhost:8080/studio/api/1/services/api/1/group/get-per-site.json?site_id=321

Site 321 is present, but I get:
{
"status": "Site not found"
}

**Comment by dejan-brkic** [comment]
fixed PR #565
