### ISSUE TITLE
[studio] Improve API response messages for remote repos

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4771]
# Feature Request

#### Is your feature request related to a problem? Please describe.
The errors that come back from the remotes dialog are very high level and request the user contact support. The reality is that these are all generally cases that can be addressed by the end user. 

Examples:
Try to push to a remote that requries security. Today generic error. 
Tomorrow: Authentication failure. Create a new remote with proper authentication and authorization to write.  

Today: Push before you pull and you get a generic error. 
Tomorrow: You must pull before you can push. erc.

#### Describe the solution you'd like
The dialog box should be focused on providing a clear undersanding of the issue and the remediation. Today it says "create a support ticket."  I dont think we need to solve this until 4x. 

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
By @russdanner from internal feedback notes sheet

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2708

**Comment by sumerjabri** [comment]
the error message when it fails to create a remote (invalid url) is a little bit generic (Internal system failure: Error while adding remote test (url: /some/local/path) for site 4964). Is that something that can be improved?

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2725

**Comment by jvega190** [comment]
@sumerjabri the new message is more clear, though the message is a bit repetitive (Remote repository not found: Remote repository not found test (url: /some/local/path) for site 4964.

**Comment by sumerjabri** [comment]
@russdanner because we post the exception first, and then the message, the message here while correct, seems redundant. Can you live with it?

**Comment by russdanner** [comment]
Confirmed
