### ISSUE TITLE
[studio-ui] Improve code-editor/content-type "intellisense"

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4773]
# Feature Request

#### Is your feature request related to a problem? Please describe.
There is no way to get to a controller for a component so that the editor undestands the content model.  
Developers have to remeber the names of variables.  If it's possible to click on a component and edit the template, then the same should be true for the controller -- and the code editor should assist with variable names.

#### Describe the solution you'd like
Generally speaking it seems we dropped the feature in the code editor where the system knows the type you are editing and allows you to select and insert the value.  I thought maybe auto complete would take over but that does not seem to be true either.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
By @russdanner from internal notes feedback sheet

**Comment by sumerjabri** [comment]
Will reopen if there are specific issues to be addressed.
