### ISSUE TITLE
[studio-ui] Add a PageBuilder Edit Mode keyboard toggle

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4780]
Add a keyboard shortcut to toggle Edit Mode on/off in addition to the top-right visual toggle. This works together with the existing temporary toggle (`z`) and adds a way to turn Edit Mode on/off entirely. Consider using the `e` key.

**Comment by aachavarria** [comment]
"ctrl+e" or "command +e" will toggle the Edit Mode

**Comment by rart** [comment]
Verified
