### ISSUE TITLE
[studio-ui] Add <- and -> (forward and back) buttons to the URL/internal browser in Preview Toolbar

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4782]
The Preview Toolbar should have back and forward buttons before the refresh.
![Internal Browser Forward and Back Actions (1)](https://user-images.githubusercontent.com/3931908/124829260-65968480-df46-11eb-8d3d-abf4c153ede4.png)

**Comment by rart** [comment]
@jvega190 please update configs to include fwd & back buttons on the toolbar
@sumerjabri 👆 fyi (will need manual update unless you want to pull in UM)

**Comment by sumerjabri** [comment]
Manual updates are still fine at this stage.
