### ISSUE TITLE
[studio-ui] PageBuilder RTE enhancements for Studio v4.0.0

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4783]
Please implement:
- [x] Enter adds a new line (doesn't save)
- [x] CTRL (CMD on Mac) + Enter => saves edits
- [x] Escape ignores edits and cancels
- [x] Show TinyMCE hover toolbar
- [x] Show the type of field (Plain Text or HTML (Rich Text?)) somewhere on the screen so the author knows what they're editing

**Comment by rart** [comment]
There are important challenges for the last task (allow D&D from assets panel). We should create a separate ticket for the future.

**Comment by sumerjabri** [comment]
https://github.com/craftercms/craftercms/issues/4798
