### ISSUE TITLE
[studio] Rename becomes an new and delete of old instead of move

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4786]
## Describe the bug
Rename a content item or a folder with content items within causes a new/delete instead of move. Furthermore, deletes are never published and old artifacts continue to exist.

## To Reproduce
1. Go to an article
2. Edit the URL
3. Publish
4. See dashboard
5. Rename a top folder
6. Publish something underneath
7. See dashboard

## Expected behavior
Path renames must be treated as moves not delete/create

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
3.1.15-SNAPSHOT
4.0.0-SNAPSHOT

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
3.1.x
PR:
https://github.com/craftercms/studio/pull/2612

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2627

**Comment by sumerjabri** [comment]
Verified.
