### ISSUE TITLE
[blueprints] Build and send updated BPs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4789]
For BPs that must be built (like React-based), please build the latest and send PRs.
- [x] Wordify
- [x] VC
- [x] Ecom
- [ ] Other?

Please note: I already updated the version number in craftercms-plugin.yaml, so it's ready for MP publishing, just send the updated compiled code.

**Comment by jvega190** [comment]
@sumerjabri vc, wordify and commertools are all of the bps. No others

**Comment by rart** [comment]
Do we need to update yaml?

**Comment by jvega190** [comment]
@rart Sumer already updated the versions in the yaml files
