### ISSUE TITLE
[studio] User Management - Forgot and Set password services returning not authorized

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#479]
/api/1/services/api/1/user/forgot-password.json
and
/api/1/services/api/1/user/set-password.json

need to be used when the user is not authorized, but they return a 401 error (not authorized)

**Comment by sumerjabri** [comment]
API spec updated:

http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/forgot-password.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/set-password.html

@dejan-brkic Please update the code to match and it should work.

**Comment by dejan-brkic** [comment]
PR #540
