### ISSUE TITLE
[deployer] Refactor Target creation

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4790]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Right now instances of Target are created manually, this can lead to some configuration properties not being properly retrieved (example https://github.com/craftercms/craftercms/issues/4705#issuecomment-861881465)

#### Describe the solution you'd like
The instance of Target should be created by Spring as part of the child application context to avoid the issue in the future

**Comment by jdrossl** [comment]
@yacdaniel please help verify this ticket

**Comment by yacdaniel** [comment]
Verified fixed in 4.0
