### ISSUE TITLE
[studio-ui] Reactify Icon Guide Dashboard Widget

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4792]
# Feature Request
Reactify Icon Guide Dashboard Widget using new mechanisms

#### Describe the solution you'd like
{{A clear and concise description of what you want to happen.}}

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
{{Add any other context or screenshots about the feature request here.}}

**Comment by rart** [comment]
Missing publishing status/target icons, @jvega190

**Comment by rart** [comment]
Please consolidate freemarker/renderingTemplate and groovy/script icons into only displaying one for each.
Pass on ticket to Vita for validation.

**Comment by alhambrav** [comment]
Verified icons have been consolidated for groovy/script and freemarker/rendering template.
