### ISSUE TITLE
[studio-ui] Drop the `Documents` filter from the dashboard widgets

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4794]
In the dashboard widgets, it's possible to filter by Pages, Components, Documents, and All. Please drop the Documents filter as it's no longer meaningful. Additionally, make sure you no longer send that filter to the backend.

**Comment by jvega190** [comment]
@sumerjabri this is ready for testing in 3.1.x. Update for 4.0.x will be done in the reactified dashboard

**Comment by rart** [comment]
@jvega190 remember to apply the change to the legacy dashlets on 4 too
