### ISSUE TITLE
CRAFTERCMS-1692: Re-build Dependency Calc

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#48]
Original JIRA Fix Versions:
2.6.0, Original JIRA Components:
Studio, 
----------
Original JIRA Description: :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1692
----------

**Comment by sumerjabri** [comment]
This becomes part of Crafter 4. Closing for now.
