### ISSUE TITLE
[studio-ui] RTE upload from desktop not working correctly

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4800]
## Describe the bug
When uploading an image to RTE using desktop upload it never completes the upload.

## To Reproduce
1. Go to an editorial based site
2. Open a form with RTE
3. Insert > Image
4. Select the upload option and select an image from desktop, click upload.
5. See that upload never ends.

## Expected behavior
Desktop image upload in RTE should work correctly.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT-5a4df2

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Add the Insert Image mechanism to the RTE directly.

**Comment by jvega190** [comment]
@sumerjabri editorial blueprint updated with upload and browse datasources for RTEs

**Comment by sumerjabri** [comment]
@jvega190 please update the PageBuilder RTE configuration to have the full toolset like on the Form Engine and ping me to have a look if it's not too complex. Let's start with the Editorial Blueprint.
