### ISSUE TITLE
[studio] List quick create API is returning empty array

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4801]
## Describe the bug
Using the /studio/api/2/content/list_quick_create_content.json?siteId=editorial endpoint is returning items as [], however there are content masked as show on quickcreate 

## To Reproduce
1. Create a site using Editorial BP
2. Go to Preview
3. Click on QuickCreate
4. Check the network

## Expected behavior
the API should return the quick create items

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-429be9

Build Number:
429be9da732fa8603e521416aa4b58c318840a30

### OS
MacOS

### Browser
Any

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
@rart what's the importance/urgency of this issue?

**Comment by rart** [comment]
@sumerjabri high. Nothing shows up on quick create due to this issue.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2631

**Comment by aachavarria** [comment]
verified
