### ISSUE TITLE
[docs] Document parentPath[index] macro

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4804]
We need to document the version of the `parentPath` macro that allows using referring to parts of the path, with an index (e.g. `parentPath[2]`). You can use ticket https://github.com/craftercms/craftercms/issues/4579 for reference.

We also need to clearly indicate in the documentation that in both `parentPath` and `parentPath[index]`, the path starts without `/site/website` and `/site/components`. For example, if in the repository the parent is a page, and the page URL in the repository is `/site/website/en/about-us/index.xml`, then the `parentPath` is `/en/about-us/index.xml`. If the parent is a component, and the component URL in the repository is `/site/components/en/producst/myproduct.xml`, then `/en/producst/myproduct.xml`.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1288 and https://github.com/craftercms/docs/pull/1289

**Comment by avasquez614** [comment]
Verified
