### ISSUE TITLE
[studio-ui] Site Dashboard stuck in processing when a scheduled publish is published in Europe/Rome Timezone

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4809]
## Describe the bug
When scheduling a publish in Studio when it is configured to be in Europe/Rome timezone and a scheduled publish is completed, the Site Dashboard gets stuck in processing. 

## To Reproduce
1. Modify your systems clock to be running in the Europe/Rome Timezone.
2. Create a site based on Editorial
3. Navigate to Site Config --> Configuration --> Site Configuration
4. Modify the Default Timezone to be `<default-timezone>Europe/Rome</default-timezone>`
5. Navigate back to the Site Dashboard. 
6. Make an edit to the home page
7. Approve & Publish the change, and schedule it to be published as soon as possible in the dialogue.
8. Wait until the Scheduled Published time and then refresh the site dashboard.
9. Notice the endless spinning

## Expected behavior
The spinning refresh should not be endlessly running in the site dashboard once a publish has been run.

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/124145046-792f8000-da5a-11eb-89e1-664010e5dd5f.png)
![image](https://user-images.githubusercontent.com/42217570/124145111-8482ab80-da5a-11eb-93f6-04edc13648fb.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.15E-814e2a
Build Number: 814e2af9bcfe44d21928a8707be8c4f93bc25ed1

### OS
Any

### Browser
Any

## Additional context
We have been informed and have confirmed that the issue lays with the file CRAFTER_HOME/bin/studio/static-assets/components/cstudio-dashboard-widgets/recently-made-live.js (Studio 3.1.14), the regex at line 178:
`(\d{4}-\d{2}-\d{2})(-\d{2}:\d{2})`
the regex only works with negative time shifts like "2021-06-28-02:00". But with the timezone Europe/Rome it fails because of the plus sign: "2021-06-28+02:00". Changing the regex to be the following solves the issue: 
`(\d{4}-\d{2}-\d{2})((\+|-)\d{2}:\d{2})`

**Comment by jvega190** [comment]
This only happens in 3.1.x

**Comment by jvega190** [comment]
@AndyReiter assigning to you for validation

**Comment by AndyReiter** [comment]
Confirmed fixed in 3.1.16-SNAPSHOT.
