### ISSUE TITLE
[studio-ui] Form engine does not allow dashes in field names

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4812]
## Describe the bug
Some existing features require field names with `-` and it is not possible to use them right now

## To Reproduce
1. Create or open a site
2. Create or open a content type
3. Try to add a field with `-` in the name

## Expected behavior
The `-` character should be allowed for the list of exceptions from `site-config.xml`

### Version
4.0.0-SNAPSHOT

### OS
Ubuntu 20.04.2 LTS

### Browser
Google Chrome 91.0.4472.114

## Additional context
It is working as expected in 3.1.x

**Comment by rart** [comment]
@jdrossl Please list what are the names that require a dash? So we can add them to the exceptions.

**Comment by jdrossl** [comment]
we already have a list of all the properties https://github.com/craftercms/studio/blob/develop/src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/config/studio/site-config.xml#L53

**Comment by rart** [comment]
Pending some final decisions. 

However, we can go ahead and add the remaining items exceptions so they work like the other system variables of this nature, @jvega190

**Comment by sumerjabri** [comment]
@rart let me know if you need anything to finalize.

**Comment by jdrossl** [comment]
Verified
