### ISSUE TITLE
[studio-ui] parentPath[INDEX] macro not working on embedded components

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4817]
## Describe the bug
The `parentPath[INDEX]` macro returns `undefined` when it's in an embedded component.

## To Reproduce
1. Create a site based on Editorial
2. Edit the `Component - Feature` content type. Add an image browse DS, with `Repository Path` = `/static-assets/{parentPath[0]}/thumbnails`. Add an image picker called `Thumbnail` that uses the new DS.
3. Edit the `Page - Category Landing`. Add an embedded content DS, with a `Content Type` = `/component/feature`. Add a node selector field called `Features` that uses the new DS.
4. Go back to the dashboard, and under pages create folder `en`.
5. Under the new folder, try creating a new `Page - Category Landing`. Add a new `Feature` and try to pick up a `Thumbnail`. 

When picking the thumbnail, you should see `undefined` in the part of the path where the `en` folder should be, as shown in the screenshot.

## Expected behavior
If used inside an embedded component, the parent path should be the first ancestor that is not an embedded component. In the example provided to reproduce, it would be the category landing page.

## Screenshots
![parent-path-undefined](https://user-images.githubusercontent.com/1598884/124799542-a9779280-df22-11eb-9cf7-9e45dbade912.png)

## Logs
N/A

### Version
3.1.15

### OS
N/A

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
Fixed in 3.1.16

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
