### ISSUE TITLE
[studio-ui] Request Publish ends up publishing if the requestor is a publisher

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4818]
## Describe the bug
Request Publish publishes the items instead of sending them for approval.

## To Reproduce
1. Edit an item
2. Click on request publish
3. Watch it go live

## Expected behavior
Request Publish should send the item for approval and not live, even if the requestor is an admin.

## Screenshots
N/A

## Logs
N/A

### Version
4.0.0-SNAPSHOT on 2021/7/9

### OS
Linux

### Browser
Chrome

## Additional context
None

**Comment by dejan-brkic** [comment]
This is a UI issue.
It opens the same dialog (Approve for Publish) for both `Publish` and 'Request Publish` actions. The result is sending always items directly to the publishing queue (calls `go-live` API)

**Comment by rart** [comment]
@aachavarria please double check that this is now correct with the recent updates to the dialog

**Comment by aachavarria** [comment]
verified.

**Comment by sumerjabri** [comment]
Dialog styling is off:
![image](https://user-images.githubusercontent.com/3931908/125807602-15ce167f-13bb-4b46-8327-885a504671d9.png)

Also, during approval, it seems to still have the "Request Approval" checkbox. That shouldn't be there.

**Comment by sumerjabri** [comment]
Verified.
