### ISSUE TITLE
[Search] RestClient is missing file size when indexing binary documents.

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#482]
When using this method to index binary documents:

```java
public String updateFile(String site, String id, File file, Map<String, List<String>> additionalFields) throws SearchException
```
https://github.com/craftercms/search/blob/2.5.x/crafter-search-client/src/main/java/org/craftercms/search/service/impl/RestClientSearchService.java#L216

The indexed data is missing the stream_size field:

```
"meta": [
          "stream_size",
          "null",
          "stream_content_type",
          "text/plain",
          "Content-Encoding",
          "ISO-8859-1",
          "Content-Type",
          "text/plain; charset=ISO-8859-1"
        ]
```

**Comment by avasquez614** [comment]
The `stream_size` field can't be added by Crafter, that's something the ExtractRequestHandler/Apache Tika automatically adds when generating the document's metadata. You probably need a new field passed through `additionalFIelds`.

**Comment by avasquez614** [comment]
Talked with @jdrossl and it was fixed in the project by adding an additional field, like recommended, so this is not needed anymore.
