### ISSUE TITLE
[engine][docker] Routing ICE mechanics through the proxy while in Docker isn't working

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4820]
## Describe the bug
The ideal development environment for Crafter/Docker users who are working with a SPA is not clear. It is not possible to utilize the proxy setup to talk to a node.js app running on the host machine and have Crafter proxy to it, due to Docker networking constraints.

This has the net effect of making it extremely difficult to build an debug in-context editing functionality on a Windows host.

## To Reproduce
- run crafter on docker
- install a sample SPA site
- launch node.js on your host machine
- try to configure crafter to proxy to your hot
- alternately, try to develop in-context editing functionality without the preview context

**Comment by phuongnq** [comment]
@tfield Could you more specify the issue with proxy?
I'm following this document and I can connect to an application on host 3000.
https://docs.craftercms.org/en/3.1/site-administrators/studio/using-the-proxy-config.html#using-the-proxy-configuration

The only note is that instead of using `http://localhost:3000` in the proxy configuration, I used the network address as a docker container cannot bind to localhost as the host has different address.

```
Compiled successfully!

You can now view video-center-blueprint in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.11:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.
```

So I put the setting for proxy:

```
      <server>
         <id>preview</id>
         <url>http://192.168.1.11:3000</url>
         <patterns>
            <pattern>.*</pattern>
         </patterns>
      </server>
```

**Comment by phuongnq** [comment]
Alternatively, there is another option to add an extra host to docker-compose:
If you are in Windows or macOS: `host.docker.internal` or `gateway.docker.internal` should be available by default.
https://docs.docker.com/docker-for-mac/networking/

If you are in a Linux environment, modify `docker-compose.yml` for `tomcat` as following:

```
  ...
  tomcat:
    image: craftercms/authoring_tomcat:3.1.16 # craftercms version flag
    depends_on:
      - elasticsearch
      - deployer
    ports:
      - 8080:8080
    extra_hosts:
      "host.docker.internal": "host-gateway"
  ...
```

Config in Studio for proxy:

```
      <server>
         <id>preview</id>
         <url>http://host.docker.internal:3000</url>
         <patterns>
            <pattern>.*</pattern>
         </patterns>
      </server>
```

If you use `react-scripts` to start SPA, there is a change that there is an error while access http://host.docker.internal:3000:

```
root@ab4bd2494d44:/opt/crafter# curl http://host.docker.internal:3000
Invalid Host header
```

In that case, disable host checking in your `.env.development`:

```
DANGEROUSLY_DISABLE_HOST_CHECK=true
```

**Comment by phuongnq** [comment]
@sumerjabri this works in WSL2. (Docker for Windows with WSL2 backend https://docs.docker.com/docker-for-windows/wsl/)

Following host supports by default without any update on docker-compose.yml file:

```
host.docker.internal 
gateway.docker.internal
```

I can `curl` these URL from a docker container:

![wsl2_host](https://user-images.githubusercontent.com/2996543/129133279-3ac265e4-c6ed-4eec-8c86-26a0c79ddefe.png)
![wsl2_host_02](https://user-images.githubusercontent.com/2996543/129133282-43fb6e4f-6c98-401b-bbcf-a401f22d0c2b.png)

Here is the setting for Studio:

![preview](https://user-images.githubusercontent.com/2996543/129133309-138a4dbd-73e4-4684-944f-07b60325b35f.png)
![proxy_config](https://user-images.githubusercontent.com/2996543/129133312-db2777e7-057e-448e-a700-93e25dd3f622.png)

My `.env.development`:

```
# In production these are set via freemarker variables that are set on `templates/web/entry.ftl`.
# You may override with your local values here.

# A blank REACT_APP_SITE_NAME variable will make the app
# try to find the crafterSite cookie which, provided you're
# running both your local crafter and node dev web server for
# the app are the same, it should be set for you when you created
# the site. Manually set the here otherwise.
REACT_APP_SITE_NAME=

# You may override the base URL to which content requests are made
# by assigning the REACT_APP_BASE_URL.
REACT_APP_BASE_URL=http://localhost:8080

DANGEROUSLY_DISABLE_HOST_CHECK=true
```

**Comment by sumerjabri** [comment]
@alhambrav let's get this documented, thanks!
