### ISSUE TITLE
Crafter on Docker setup instructions sequencing is problematic

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4821]
The Docker setup instructions (https://github.com/craftercms/docker-compose/blob/develop/README.md) tell a user how to launch their environment, and they even state that the images are used primarily for developers. However, the crucial step about mapping docker repo folders to the host drive is listed at the end, after the user has completed everything.

Most crafter/docker use cases will require at least the sandbox folder and in some cases the main server config folder to be mapped, so that developers can develop their crafter site with the usual tools.

Correspondingly, at a bare minimum, the pre-requisites should be updated to have people decide if they want to map the drive or not.  Better yet, assume that by default people should map the drive, and allow them to not map it if they choose not to. Perhaps you could set a default location of $HOME/.crafter or something to make it easy.

Please update the documentation accordingly.

**Comment by tfield** [comment]
The main documentation has the same problem - the note about the step you have to take first is at the very end of the file :-(

https://docs.craftercms.org/en/3.1/getting-started/quick-start-guide.html#running-craftercms-in-docker

**Comment by sumerjabri** [comment]
@alhambrav please update the docker-compose README and the main docs.
