### ISSUE TITLE
Installing Crafter 3.1.6+ (including 3.1.13 at least) on a mac requires blessing the x-pack-ml file

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4822]
Crafter will not launch on a new install on macos without first blessing the x-pack-ml controller app.

After the initial download, the x-pack-ml Controller.app file is not recognized by Macos, so it will not open it programmatically. 
 The end user has to navigate to the  CRAFTER/bin/elasticsearch/modules/x-pack-ml/platform/darwin-x85_64 folder, open the Controller.app file (it won't open), and then right-click on it and choose open, and then when prompted, allow the file to open.

After that has been done, macos will allow Crafter to launch the file.

If you forget this step, it seems that you have to nuke your crafter install and install again (though this hasn't been verified lately).  

There should be a way to simplify the process for macos users to install this more easily.

NOTE: This process was greatly improved in Crafter 3.1.6 (# of files to fix dropped from 8 to 1), but the problem persists.

**Comment by sumerjabri** [comment]
@alhambrav please investigate and make recommendations on how to address this. Via documentation or is there something we can do on the software side.
