### ISSUE TITLE
Docker instances do not have installed text editors

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4823]
The docker instances for Crafter do not have a text editor installed on them.

I understand lean and mean is a goal for these images but vi is 160kb....

It's extremely inconvenient to not have one.

**Comment by sumerjabri** [comment]
@avasquez614 I think `vim` and `nano` should be doable. If not, ping me to discuss options.

**Comment by phuongnq** [comment]
@sumerjabri @avasquez614 
I added `vim` and `nano` to tomcat and deployer of both authoring and delivery.
Let me know if we should add to other images as well.

**Comment by sumerjabri** [comment]
@avasquez614 any objection to adding those to all images? What are your thoughts?

**Comment by avasquez614** [comment]
I'm ok with that @sumerjabri @phuongnq

**Comment by sumerjabri** [comment]
@phuongnq let's do it.

**Comment by phuongnq** [comment]
@sumerjabri we added vim and nano to all images in both 3.1.x and 4.0
