### ISSUE TITLE
[studio-ui] session time-out while editing, cannot login back using displaying popup

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4826]
## Describe the bug

While editing a page, I got the popup that mentioned that the session is a timeout. Input username/password then click Login button does not close the popup.

## To Reproduce
1. Go to the site dashboard
2. Editing a file, occasionally the session is a timeout
3. Enter username/password on displaying popup
4. Click Login
5. Notice that the user does not login back and the popup does not close.

## Expected behavior

There should be no session timeout while editing the page. Even if there could be, after input username/password, the user should be logged in back. The popup should be closed.

## Screenshots

![session_timeout_while_editing](https://user-images.githubusercontent.com/2996543/125017846-1f543900-e09e-11eb-990f-387fead2adb0.png)
![login_but_popup_not_close](https://user-images.githubusercontent.com/2996543/125017859-28450a80-e09e-11eb-80d2-71c775ebc267.png)

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by russdanner** [comment]
Confirmes
