### ISSUE TITLE
[studio-ui] Cannot drag scrollbar on Configuration screen

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4827]
## Describe the bug
In Site Tools (old or new), a user cannot drag the scrollbar on the Configuration screen if we drag it over the most right position (outside of the browser limits)

## To Reproduce
1. Create a site from a remote git repository that is created before 4.0
2. Open site-dashboard, Configuration screen
3. Drag scrollbar to the most right position
4. Notice that the scrollbar cannot be dragged back

## Expected behavior

The user should be able to drag the scrollbar back when it reached the most right position

## Screenshots

Refer to the video:

https://user-images.githubusercontent.com/2996543/125020060-5593b780-e0a2-11eb-85d0-92298df15d6d.mp4

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@jvega190 add a max width prop to component — with a default — and implement it if not already there. Additionally, add a style with a max-width: 90% !important and test that this prevents from getting too close to the right edge. Ping me to discuss alternatives should this not work.

**Comment by phuongnq** [comment]
verified fixed
