### ISSUE TITLE
[studio-ui] UI should not calculate contentTO.browserUri to compare with preview URL

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#483]
in wcm-root-folder.js and wcm_content.js, browserUri is calculated in order to compare with pageParameter.  UI should just use contentTO.item.browserUri and it must match the preview URL without any string replacement if the same page is being edited.

`                                var currentContentTO,
                                    URLBrowseUri = pageParameter.replace("html","xml"),
                                    contentTOBrowseUri = contentTO.item.uri.replace('/site/website', '').replace("/index.xml", "");
`

should be 

`                                var currentContentTO,
                                    URLBrowseUri = pageParameter,
                                    contentTOBrowseUri = contentTO.item.browserUri;
`

**Comment by sumerjabri** [comment]
@jvega-crafter please check with @hlim and see if this is still an issue and how to best address it. Also, if this is an issue in 3.0, we must get it in there too.

**Comment by jvega-crafter** [comment]
studio 3.0: https://github.com/craftercms/studio2-ui/pull/530
studio 2.5: https://github.com/craftercms/studio2-ui/pull/531
