### ISSUE TITLE
[studio] Recent Activity dashboard does not reflect the proper published state of items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4831]
## Describe the bug
Recent Activity Dashboard does not reflect the proper published state of items

## To Reproduce
1. Create a site based on editorial
2. Edit and publish the home page
3. Note the Live status is reflected in the toolbar, sidebar/page explorer, and dashboard publish activity
4. Note Recent Activity does NOT indicate the correct state

## Expected behavior
The workflow/publish state must be correct and consistent throughout the UI

## Screenshots
<img width="1450" alt="Screen Shot 2021-07-09 at 1 25 18 PM" src="https://user-images.githubusercontent.com/169432/125116123-3acd3d00-e0ba-11eb-80bd-08198ba1a8ed.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0

### OS
Any

### Browser
All

**Comment by jvega190** [comment]
Related to this ticket: https://github.com/craftercms/craftercms/issues/4832

**Comment by jvega190** [comment]
Fixed in https://github.com/craftercms/craftercms/issues/4716

**Comment by russdanner** [comment]
Confirmed
