### ISSUE TITLE
[studio] Issues in dashboard APIs

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4832]
## Describe the bug
Under some circumstances, the dashboard APIs (`/studio/api/2/publish/history` and `/studio/api/1/services/api/1/activity/get-user-activities`) are not returning correct values for the items.

## To Reproduce
1. Create a site using the website editorial bp. Set up the staging publishing target by opening Site Tools -> Configuration -> Site Configuration and set the enable-staging-environment to true.
2. Push the whole site to live (Site Tools -> Publishing -> Publish changes made in Studio via the UI). **This steps are necessary for it to be reproducible**.
3. Go to Dashboard and see items published.
4. Edit homepage, and publish to staging
5. Go again to Dashboard, notice that under `Recently Published` the Homepage shows twice, with status = live.

![image](https://user-images.githubusercontent.com/18267471/125115651-dc4b9300-e0a8-11eb-9d38-501bcce8c717.png)
If you check on the `/studio/api/2/publish/history` response, the first home item has `endpoint: "staging"` (correct), but the second one has `endpoint: "live"`.

6. Still on Dashboard, see that the `My Recent Activity` dashlet has Home, and the state is `Unpublished`.

![Screenshot from 2021-07-09 11-32-27](https://user-images.githubusercontent.com/18267471/125116149-81ff0200-e0a9-11eb-97e2-16ded5373c9c.png)
If you check on the `/studio/api/1/services/api/1/activity/get-user-activities` response, the item has `endpoint: null`

## Expected behavior
APIs should return the states consistently for the items.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
CMS v4.0.0-SNAPSHOT

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Point num 5 is UI issue per discussion on the call with Sumer

Point num 6 is also a UI issue. It is API 1 call and API 1 response. Service returns properties set accordingly to Item table values. For some reason, UI does not process and display properties as it does no a Recently Published dashboard. The Recently Published dashboard is API 2 call but it is returning API 1 data model due to legacy dashboard still being used

**Comment by jvega190** [comment]
@dejan-brkic as we discussed, we need an `isStaged` field in the response items, in this APIs:
- `/studio/api/1/services/api/1/activity/get-user-activities`
- `/studio/api/1/services/api/1/deployment/get-scheduled-items.json`
- `/studio/api/1/services/api/1/workflow/get-go-live-items`
- /studio/api/2/publish/history.json

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/2653

**Comment by jvega190** [comment]
Verified fixed

**Comment by jvega190** [comment]
I found a couple of details,
- When requesting a publish from an author user, and setting a custom date, then checking on the `get-go-live` API, the `scheduledDate` is null (also checked in 3.1.x and it did have a value).
- In `history` and `get-user-activities`, when logged as a author, the `publishedDate` is null. This doesn't happen when logged as an admin.

**Comment by rart** [comment]
- `endpoint`, `environment` and `submittedToEnvironment` are also null for a submitted item

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2664
