### ISSUE TITLE
[studio] Modify all blueprints to comment out the `example.com` email address

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4833]
Comment out example.com email addresses to avoid sending emails to that domain by accident.

Tasks:
 - [x] Modify all Blueprints to comment out the default email notification setting in the `notification-configuration.xml` for all sites. Don't remove the emails, just comment them out to make sure they're a good example for others to modify
 - [x] Modify the sample files the same way
 - [x] Validate that the emails are not being sent and the system is okay with an empty list
 - [x] UM should comment out all email addresses if they're `@example.com`.

**Comment by sumerjabri** [comment]
@jvega190 please send the PR to 3.1.x again with a better indented `<!--`

**Comment by jvega190** [comment]
@sumerjabri done, PR created with fixed indentation

**Comment by AndyReiter** [comment]
craftercms-bp-gardeners - Verified
craftercms-bp-videogallery - Verified
craftercms-bp-singlepage-brochure - Verified 
craftercms-bp-restaurant - Verified
craftercms-bp-pizza - Verified
craftercms-bp-fitness - Verified 
craftercms-bp-companyshowcase - Verified 
craftercms-bp-artshowcase - Verified
craftercms-bp-hotelinfo - Verified
craftercms-bp-events - Verified

**Comment by sumerjabri** [comment]
@AndyReiter if this is done, please go ahead and close the ticket.

**Comment by AndyReiter** [comment]
@sumerjabri verifying in 4.0 then will close the ticket.

**Comment by AndyReiter** [comment]
Running into issues that all of these blueprints have not been upgraded to 4.0 yet. Because of this, I am not able to successfully test whether this issue is fixed in 4.0. Please see the error below for more information. Reassigning to @sumerjabri for this to be addressed by engineering.

```Caused by: org.craftercms.commons.upgrade.exception.UpgradeNotSupportedException: Current version '3.1.4.4' for 'craftercmsbpsinglepagebrochure' cannot be upgraded automatically, requires '>=3.1.9'
	at org.craftercms.commons.upgrade.impl.pipeline.DefaultUpgradePipelineFactoryImpl.getPipeline(DefaultUpgradePipelineFactoryImpl.java:147) ~[crafter-commons-upgrade-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.craftercms.studio.impl.v2.upgrade.StudioUpgradeManagerImpl.doUpgrade(StudioUpgradeManagerImpl.java:141) ~[classes/:4.0.0-SNAPSHOT]
	at org.craftercms.commons.upgrade.impl.AbstractUpgradeManager.upgrade(AbstractUpgradeManager.java:63) ~[crafter-commons-upgrade-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	... 134 more```

**Comment by sumerjabri** [comment]
@AndyReiter all bps updated

**Comment by AndyReiter** [comment]
**4.0.0-rc1**
craftercms-bp-gardeners - Verified
craftercms-bp-videogallery - Verified
craftercms-bp-singlepage-brochure - Verified
craftercms-bp-restaurant - Verified
craftercms-bp-pizza - Verified
craftercms-bp-fitness - Verified
craftercms-bp-companyshowcase - Verified
craftercms-bp-artshowcase - Verified
craftercms-bp-hotelinfo - Verified
craftercms-bp-events - Verified
