### ISSUE TITLE
[studio-ui] Audit screen does not show full column when horizontal scrolling

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4841]
## Describe the bug

In the Audit screen, there are rows that have columns with value end with ...
If we horizontal scroll for those values, the full text does not display

## To Reproduce
1. Go to a Site Audit popup
2. Scroll for rows that have text with ...
3. Notice that full text does not display

## Expected behavior

Users should see the full text when horizontal scrolling

## Screenshots

https://user-images.githubusercontent.com/2996543/125375471-49b23900-e3b3-11eb-92ed-7ed721a384ae.mp4

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by aachavarria** [comment]
verified.

**Comment by aachavarria** [comment]
the columns must not have horizontal scrolling, that is a issue, to see the value the user must hover over the ellipsis

**Comment by phuongnq** [comment]
verify fixed
