### ISSUE TITLE
[studio-ui] Workflow States popup does not work

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4842]
## Describe the bug

When accessing Workflow States, the pop-up show 

Component craftercms.components.WorkflowStates not found.
Check ui config & make sure you've installed the plugins that contain the desired components.

## To Reproduce
1. Go Site Tools
2. Click "Workflow States " menu
3. Popup display a message that WorkflowStates not found

## Expected behavior

Users should see the workflow screen

## Screenshots

![2021-07-13_08-25](https://user-images.githubusercontent.com/2996543/125376078-6c911d00-e3b4-11eb-9373-3e200670043c.png)

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by rart** [comment]
This looks like an outdated config. Did you just create this site?

**Comment by phuongnq** [comment]
Hi @rart 

I created a new build with the latest blueprint. Here is the manual I followed:

```
git clone https://github.com/craftercms/craftercms.git
cd craftercms
./gradlew build deploy
./gradlew start
Create a new site with the Editorial blueprint
````

**Comment by rart** [comment]
@jvega190 this is certainly config. maybe it's just not merged. please check if there's a missing update.

**Comment by jvega190** [comment]
@rart @phuongnq Yes it is config, and is pending to merge, I'll assign it back after this is merged https://github.com/craftercms/studio/pull/2647 for testing.

**Comment by jvega190** [comment]
PR is merged, @phuongnq can you please validate?

**Comment by rart** [comment]
(site needs to be recreated or config needs to be updated)

**Comment by phuongnq** [comment]
confirmed fixed
