### ISSUE TITLE
[studio-ui] Template history view error

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4845]
## Describe the bug
 When View a template history, the page display an error message

## To Reproduce
1. Open a site dashboard
2. Select a site template (for example from editorial blueprint)
3. Click options and select "History"
4. From the popup, select a row and "View"
5. Notice that an error message is displayed

## Expected behavior

The template should be viewed normally

## Screenshots

![2021-07-13_09-45](https://user-images.githubusercontent.com/2996543/125382541-09a58300-e3c0-11eb-937b-c724e0911319.png)

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by jvega190** [comment]
@sumerjabri @rart Our current diff tool only supports xml files (and this tools is used to view the items), so we have a couple of options, removing the view option when the item is not `xml`, or adding back-end support to retrieve an item given a version, so we can display it with our preview dialog, like this:
![Screenshot from 2021-07-14 16-04-06](https://user-images.githubusercontent.com/18267471/125699426-3b82442b-b9bd-4ddb-97b7-b34928be9303.png)

**Comment by rart** [comment]
We need https://github.com/craftercms/craftercms/issues/4184 done in order to be able to do something useful with that "View" option for non-xml items.

**Comment by sumerjabri** [comment]
Prioritized https://github.com/craftercms/craftercms/issues/4184 up.

**Comment by phuongnq** [comment]
verify fixed
