### ISSUE TITLE
[studio] Rename component become folder

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4847]
## Describe the bug

When renaming a component, the popup display as rename a folder. And after rename, the component is displayed as a folder.

## To Reproduce
1. Create a site with Editorial blueprint
2. Go to Dashboard
3. Rename "Latest Articles Widget"
4. Notice that the popup is for renaming folder and after renaming, the component becomes a folder

## Expected behavior

A component should be renamable.

## Screenshots

https://user-images.githubusercontent.com/2996543/125402608-cdcde600-e3de-11eb-97b9-d3cc6170125a.mp4

![2021-07-13_13-33](https://user-images.githubusercontent.com/2996543/125402853-0ff72780-e3df-11eb-89c0-3ac8be5f2416.png)

![2021-07-13_13-34](https://user-images.githubusercontent.com/2996543/125402876-171e3580-e3df-11eb-8450-4459d5f1e898.png)

### Version
Crafter CMS v4.0.0-SNAPSHOT.

### OS
Ubuntu 20.04.1 LTS (fossa-varys X54.1)

### Browser
Chrome - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2652

**Comment by phuongnq** [comment]
Verified the option to rename content type is disabled.
