### ISSUE TITLE
[studio] Error message in log when an asset is uplaoded

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4852]
## Describe the bug
There is a error message in the log when an asset is uploaded to Studio. Even if the error says Label is null, the label is correctly set in the `item` table 

## To Reproduce
1. Upload an asset under `Static Assets`
2. See error in log

## Expected behavior
No error is logged. 

## Screenshots
N/A

## Logs
`[ERROR] 2021-07-15T15:52:47,715 [http-nio-8080-exec-1] [internal.ItemServiceInternalImpl] | Label = **null`

### Version
`4.0.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2660

**Comment by yacdaniel** [comment]
Verified fixed.
