### ISSUE TITLE
[studio-ui] Add RTE config to page builder

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4854]
# Feature Request

#### Is your feature request related to a problem? Please describe.
How can customers customize the toolbar(s) for page builder's RTE?

#### Describe the solution you'd like
- [x] Retrieve/use legacy config which powers the form engine RTE
- [x] Add new entries to the new ui.xml. Preferably use UM to set these entries to achieve consistency between form editor & PB editor.
- [x] Make it have the same configuration as the standard RTE configuration for the Form Engine based editing

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
{{Add any other context or screenshots about the feature request here.}}

**Comment by jvega190** [comment]
Configuration for ui.xml (may need updates)
https://gist.github.com/jvega190/0175fb256e2b9725a87dd572167660f0

**Comment by jvega190** [comment]
UM work pending

**Comment by jdrossl** [comment]
@sumerjabri given that 4.0 has not been released does it make sense to use the UM at this point or can we just change the default file that will be added to sites from 3.1?

**Comment by sumerjabri** [comment]
@jdrossl agreed, let's only add the new file and no need to invoke UM.

**Comment by rart** [comment]
@jvega190 the rte control is used for plain text too. in these instances, the controls should not show full rich-text-editing capabilities.
