### ISSUE TITLE
[studio-ui]  The date/time displayed for scheduled publish is  incorrect when approving a scheduled publish request 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4855]
## Describe the bug
When an author requests to publish  an item on a later date/time, then a publisher goes to approve the request, the requested date/time shown to the publisher is incorrect (It displays the current  date/time instead of the requested date/time)

## To Reproduce
1. Create a site using the website editorial bp,  publish the whole site and create a user `author`
2. Login  as user `author` then edit a page and request the page to be published at a later time (7/17/2021 3:49 PM)
<img width="868" alt="Screen Shot 2021-07-16 at 3 50 31 PM" src="https://user-images.githubusercontent.com/25483966/126153314-34626624-d59c-4834-b5fd-c91ffc8debf6.png">

3. Login as user `admin`, then open the dashboard to approve the request from user `author`
4. Notice the date displayed is the current date instead of the requested date in the dashboard
<img width="1497" alt="Screen Shot 2021-07-16 at 3 51 52 PM" src="https://user-images.githubusercontent.com/25483966/126153643-c8e8df79-e3e9-459e-80ec-a300b0d69a9c.png">
(in 3.1, the requested date/time for publish is displayed in the dashboard)

5. Put a checkmark on the page user `author` requested to be published later.  Notice the date is the current date and not the requested publish/date time.  The approver does not see when the author intended the page to be published.

## Expected behavior
When an approver goes to publish a request to publish an item at a later date, the publish dialog should display the date it was requested to be published.

The dashboard should also display the  requested date  for the  item to be published in the `Items Waiting for Approval` dashlet

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-be4b3d
Build Number:
be4b3dc2480bdec7712ad8920cc949080c5de9ed
Build Date:
7/16/2021, 3:21 PM

### OS
macOS

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@jvega190 also, I've noticed that opening that dialog, when switching to "later" it seems to put the date that isn't the current time. I've seen things like 1h back of current time. Please double check that too.

**Comment by alhambrav** [comment]
Hi!

The dates in the dashboard now looks okay.
When you approve a request to publish to a later date by putting a checkmark next to the item you want to approve then, clicking on `Publish` on the context nav, the date displayed in the publishing dialog  is correct.

Just one more thing regarding the publishing dialog when  a request to publish later is being approved:
When you approve a request to publish to a later date by clicking on the options (thee dots) next to the item you want to approve, the publish dialog does not display the date requested by the author and instead has `Now` selected.

<img width="1356" alt="Screen Shot 2021-08-03 at 10 51 50 AM" src="https://user-images.githubusercontent.com/25483966/128045193-c1a95b96-1843-46b3-bb81-eaa3cdaaba37.png">''

<img width="911" alt="Screen Shot 2021-08-03 at 10 51 58 AM" src="https://user-images.githubusercontent.com/25483966/128045456-30bdb257-999f-4f4a-a5c1-7f8fc196165e.png">

**Comment by alhambrav** [comment]
Hi @aachavarria 

When approving  a request for publish, if an approver goes to the dashboard then clicks on the three dots next to the page to be approved, the user is given the Approve option. If the user puts a checkmark on the page in the dashboard, the user is given  the Publish option.  If the user previews the page requesting for publish, the user is given the Approve option
<img width="1511" alt="Screen Shot 2021-08-16 at 3 24 00 PM" src="https://user-images.githubusercontent.com/25483966/129740662-2f5310fd-3dfc-4b25-a7ba-aff111e55dad.png">

Per a conversation in the slack #ui  thread, please use “Publish” across the board for the publishing actions (i.e. request publish, approve or publish per se) to make the action for the approver consistent. (I am not sure if I should  open a new ticket  or just tack it on here?  Thanks!)

**Comment by alhambrav** [comment]
Verified fixed.
