### ISSUE TITLE
[studio-ui] Add paste from MS Word to RTE 5

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4856]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Paste from MS Word only works on RTE 2, we'd like the same for 5.

#### Describe the solution you'd like
Ping me for ideas.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by sumerjabri** [comment]
@russdanner passed basic testing. Please validate and close.

**Comment by russdanner** [comment]
Confirmed
