### ISSUE TITLE
[studio-ui] Remove RTE 2 from Studio 4

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4857]
We won't be supporting `RTE 2` in Studio 4 and we will rename all RTE types to just `RTE`.

Please do this:
- [x] [UI] Remove `RTE 2` codebase
- [x] [UI] Remove all references to `RTE 2` from built-in BPs and external BPs
- [x] [UI] Rename `RTE 5` to `RTE` for the control and the form
- [x] [UI] Review the code to make sure there are no more references to `RTE 2` nor `RTE 5`
- [x] [BE] UM to switch the content types to the new control, `RTE` (no 2, no 5, just RTE)
- [x] [BE] UM removes the `RTE 2` config
- [x] [BE] UM removes `rte-setup.xml`
- [x] [BE] UM rename `rte-setup-tinymce5.xml` to `rte-config.xml`
- [x] [BE] UM rename `rte-setup...` sample to match the new name
- [x] [BE] UM updates the configuration file `config-list.xml` to remove `RTE 2`, rename `RTE 5` and update related samples and translation keys
- [x] Update v4 docs to remove `RTE 2` and switch all `RTE 5` to `RTE`
- [x] Test and validate

**Comment by jvega190** [comment]
This can be tested now, marketplace bps are pending for publishing.

**Comment by jvega190** [comment]
UM work pending

**Comment by sumerjabri** [comment]
Seems like we missed some stuff:
https://github.com/craftercms/studio-ui/blob/develop/ui/scss/src/forms-engine.scss#L79

**Comment by yacdaniel** [comment]
Verified.
