### ISSUE TITLE
[studio] DetailedItem.{staging,live}.publisher should be a username

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4859]
## Describe the bug
DetailedItem.{staging,live}.publisher is showing a concat of first + last instead of username

## To Reproduce
1. Call item_by_path of an item that has been published live
2. See the publisher prop of staging & live objects

## Expected behavior
Should be a username

## Screenshots
<img width="411" alt="image" src="https://user-images.githubusercontent.com/3928341/126329425-ab594782-42ec-464a-a177-1ba57b6e911b.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
{{Software version if applicable (copy paste from Help > About).}}

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2663

**Comment by sumerjabri** [comment]
@rart the PR is merged now.

**Comment by rart** [comment]
Verified
