### ISSUE TITLE
[studio] Reindexing Elasticsearch does not cause WebDAV documents to be reindexed

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4860]
## Describe the bug

When triggering a reindexing elasticsearch with a webdav remote asset, the document is not reindexed 

## To Reproduce
1. Create a site with any name Ex: `test`
2. Setup a webdav server and put some images to it
3. Use webdav datasource to include webdav image to a form
4. Search the image, notice that it is displayed.
5. Reindexing sites by deleting all indexes and reindex again:

```
# Remove items from index
curl "http://localhost:9201/test-authoring_v1/_doc/_delete_by_query" -H "Content-Type: application/json" -d '{ "query": { "match_all": {} } }'
curl "http://localhost:9201/test-preview_v1/_doc/_delete_by_query" -H "Content-Type: application/json" -d '{ "query": { "match_all": {} } }'

# Index all items
curl "http://localhost:9191/api/1/target/deploy/authoring/test" -X POST -H "Content-Type: application/json" -d '{ "reprocess_all_files": true }'
curl "http://localhost:9191/api/1/target/deploy/preview/test" -X POST -H "Content-Type: application/json" -d '{ "reprocess_all_files": true }'
```
6. Search with ES, notice that remote asset does not hit

## Expected behavior

Reindexing operation should also index webdav assets.

## Screenshots

![before_reindex](https://user-images.githubusercontent.com/2996543/126425373-93f8b65b-33c4-45db-8f12-a18706510236.png)

![after_reindex](https://user-images.githubusercontent.com/2996543/126425830-66c973f7-2ff7-47c5-ab52-140958211afb.png)

![after_reindex_es_direct_search](https://user-images.githubusercontent.com/2996543/126425837-1dc3d60b-b25e-4cde-b83a-3bc66c9a9b51.png)

### Version

3.1.x

### OS

Ubuntu

### Browser

Chrome

## Additional context

Note: If I delete the reference from webdav and save, then add back the asset, I can search it from ES.

**Comment by jdrossl** [comment]
@phuongnq I was not able to reproduce this issue in 3.1 or 4.0, the results are the same before & after delete & reindex

**Comment by jdrossl** [comment]
BTW this is my webdav configuration in case you can spot any differences:

```xml
<webdav>
    <webdav>
        <profile>
            <id>webdav-default</id>
            <baseUrl>http://localhost:9090/webdav</baseUrl>
            <username>wadmin</username>
            <password>wadmin</password>
            <preemptiveAuth>false</preemptiveAuth>
        </profile>
    </webdav>
</webdav>
```

**Comment by phuongnq** [comment]
Closed as cannot reproduce. 
Maybe some wrong configuration from my side. I cannot reproduce this now.
