### ISSUE TITLE
[studio] multiple environments setting value does not reflect to script which is created beforehand

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4861]
## Describe the bug

I create a script to read a tag from the environment config file beforehand.  After that, I actually add the tag to site-config.xml (via UI). The response from REST API is always null.

## To Reproduce
1. Create multiple environments and enable the environment other than `default`. Refer: https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-multi-environment-configuration.html. Sample of name: MY

2. Create a REST script to read a value from the environment site-config.xml which is not presented in the config file. Ex:

```
def results = [:]
def conf = siteConfig.getString("test")
results.conf = conf

return results
```

3. Add "test" tag to /config/engine/env/MY/site-config.xml via Studio:

```
<site>
    <version>2</version>
    <test>aaa</test>
</site> 
```

4. Call API to verify that result is null

```
{"conf": null}
```
5. Edit the script in step 2 again and click Update
6. Call API again, verify that conf is updated

```
{"conf": "aaa"}
```
## Expected behavior

In step 4, we should be able to get value from site-config.xml

## Screenshots

https://user-images.githubusercontent.com/2996543/126427659-877c0287-36d6-4edc-943e-9e238d680b98.mp4

### Version

3.1.x

### OS

Ubuntu

### Browser

Chrome

## Additional context

Note: If I create the config beforehand then create the script to read it, I can get the correct value.

**Comment by phuongnq** [comment]
Note: seems like when updating multiple environment config files, the deployer is not triggered that causes the issue. We can update any file (post, component, script) to trigger the deployer.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2681
https://github.com/craftercms/studio/pull/2682

**Comment by phuongnq** [comment]
verify fixed
