### ISSUE TITLE
[studio-ui] WebDAV assets in root folder is not selectable

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4862]
## Describe the bug

When adding images from WebDAV repositories, if the images are in the root folder of the WebDAV server, we cannot add the image as the URLs have double `//`

## To Reproduce
1. Create a WebDAV server and put images in root directory. Ex: http://localhost/airplane.png
2. From Studio, create a form to add the above image to WebDAV
3. Browse the repository and notice that the image is not viewable, response 500 as the URL is:

```
URL: /remote-assets/webdav/webdav-default//airplane.png
GET http://localhost:8080/remote-assets/webdav/webdav-default//airplane.png 500
```

## Expected behavior

There should be no `//` in the URL and the image is selectable.

## Screenshots

Profile setting:

![webdav_profile](https://user-images.githubusercontent.com/2996543/126428421-3a46cada-a0c3-45c7-aabd-2616ae1e52a3.png)

Datasource configuration:

![webdav_datasource_properties](https://user-images.githubusercontent.com/2996543/126428433-f3017a14-4129-4b8f-8afd-8d3b9ca1fec9.png)

Images are not visible if putted in root directory of WebDAV server:

![root_folder](https://user-images.githubusercontent.com/2996543/126428514-9f49cd27-4de4-4971-9933-04c8d377fc21.png)

Images are visible if putted in directory other than root of WebDAV server:

![not_root_folder](https://user-images.githubusercontent.com/2996543/126428440-b5973971-e8ae-4c52-8409-53f9348e39f7.png)

### Version

3.1.x

### OS

Ubuntu

### Browser

Chrome

## Additional context

If I put the image in folder other root of WebDAV server, there is no error

```
URL: /remote-assets/webdav/webdav-default/test/airplane.png
GET http://localhost:8080/remote-assets/webdav/webdav-default/test/airplane.png 200
```

**Comment by jvega190** [comment]
This seems to be a backend issue, the item path from response (in both upload and browse) comes with the extra `/`

**Comment by phuongnq** [comment]
I still have the issue.
After the fix, all images (root or nested directory) are not insertable. Images names are missing from the URL path

![webdav-issue](https://user-images.githubusercontent.com/2996543/127264253-fdd115cc-157a-4331-ba51-332fe94c00b5.png)

**Comment by phuongnq** [comment]
verified the fix
