### ISSUE TITLE
[studio] Requesting approval for Parent Item causes childs items on awaiting approval dashlet disappear

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4869]
## Describe the bug
When requesting approval for Parent Item, childs items on awaiting approval dashlet disappears

## To Reproduce
1. Go to Editorial
2. Request approval for Entertainment.
3. Request approval for Home
4. Go to the Dashboard
5. Check Home is in awaiting approval and Entertainment is gone.

## Expected behavior
Entertainment should be still on awaiting approval dashlet.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-aede43

Build Number:
aede4378487ea0f230c157c9c84ce237350c7d83

### OS
Max OS

### Browser
Any

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2678

**Comment by alhambrav** [comment]
Verified fixed.
