### ISSUE TITLE
[studio] Update dependency calculation to support CDATA

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4873]
# Feature Request

#### Is your feature request related to a problem? Please describe.
{{A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]}}
CDATA wrapped elements are not having their deps extracted.

#### Describe the solution you'd like
Update the rep-calc regex in:
- [x] built-in BPs
- [x] MP BPs (@jvega190 to help here)
- [x] via UM

#### Describe alternatives you've considered
Sticking with entity encoding.

#### Additional context
Design meeting took place with all stakeholders on 2021 07 21

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2667

**Comment by jvega190** [comment]
This can be tested now, marketplace bps are pending for publishing.
