### ISSUE TITLE
[studio-ui] Do not disable the URL bar when the guest cannot load or determine the item

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4878]
## Describe the bug
The sidebar and context nav plugins that are contextually aware of the active page in preview disable when the guest cannot load or cannot determine the content in the preview. However, other UI elements that are general also disable and should not. Specifically the "url" bar currently disables and should not.

## To Reproduce
1. go to preview for a site
2. manually enter a url into the url bar that does not exist for the site i.e. "/this-will-break"
3. Note that the preview complains about the guest and then the URL bar becomes disabled

## Expected behavior
The URL bar should NOT disable, the user should be able to fix the broken url manually if they like or use other functions like the drop down to select a working url.

Generally speaking if the widget/plugin is not contextually specific to the item in the preview it should not be disabled.  

### Version
4.0.0

### OS
Any

### Browser
All

**Comment by russdanner** [comment]
The back and forward and reload buttons should still work but don't

**Comment by rart** [comment]
Improved back button logic [(2669)](https://github.com/craftercms/studio-ui/pull/2669)
Forward button will always be disabled as the "broken" page is always the last to be visited.
Reload can't work on disconnected pages as things stand — this would be a separate R&D effort.

**Comment by russdanner** [comment]
Confirmed.
