### ISSUE TITLE
[studio-ui] do not show empty space in sidebar explorer widgets when no children exist

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4879]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Currently we show a large "notice" to the user in the sidebar explorer widget that no child items exist. This takes up a lot of real estate.

#### Describe the solution you'd like
Remove the message.  There's no need to provide this notice.

#### Describe alternatives you've considered
Make the message smaller/more discrete 

#### Additional context
<img width="443" alt="Screen Shot 2021-07-22 at 9 49 34 AM" src="https://user-images.githubusercontent.com/169432/126650373-323901d9-4a79-49c0-a8b8-dfe9ec28f954.png">

**Comment by russdanner** [comment]
It looks like the fix to this is not to allow a user to browse into an empty folder.
This is confusing to the user because it's not clear that the click on the folder just "didn't work"

**Comment by sumerjabri** [comment]
@jvega190 please roll it back to allow the user to go to an empty folder and it shows the error message "Empty folder" also get rid of the graphic.

**Comment by russdanner** [comment]
Confirmed
