### ISSUE TITLE
Cannot create a website: The required Deployer targets couldn't be created.

### ISSUE THREAD

**Issue by ArthurGenet** [craftercms/craftercms#4881]
## Describe the bug
When trying to create a website (any type):
![Capture d’écran 2021-07-22 à 16 44 27](https://user-images.githubusercontent.com/40146654/126658746-d89fecda-383a-40dc-9c2b-9ffb219492e1.png)

## To Reproduce
On MacOS, after downloading the bundle  and starting crafter
1. Connect to http://localhost/studio
2. Try to create a site (any type)

Using CATALINA_BASE:   /Users/arthurgenet/Desktop/crafter/bin/apache-tomcat
Using CATALINA_HOME:   /Users/arthurgenet/Desktop/crafter/bin/apache-tomcat
Using CATALINA_TMPDIR: /Users/arthurgenet/Desktop/crafter/temp/tomcat
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home
Using CLASSPATH:       /Users/arthurgenet/Desktop/crafter/bin/apache-tomcat/bin/bootstrap.jar:/Users/arthurgenet/Desktop/crafter/bin/apache-tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   -server -Xss1024K -Xms1G -Xmx4G -Dtomcat.host=localhost -Dtomcat.http.port=8080   -Dtomcat.https.port=8443 -Dtomcat.ajp.port=8009 -Dcrafter.home=/Users/arthurgenet/Desktop/crafter   -Dcrafter.bin.dir=/Users/arthurgenet/Desktop/crafter/bin -Dcrafter.data.dir=/Users/arthurgenet/Desktop/crafter/data -Dcrafter.logs.dir=/Users/arthurgenet/Desktop/crafter/logs   -Dcatalina.logs=/Users/arthurgenet/Desktop/crafter/logs/tomcat -Dapplication.logs=/Users/arthurgenet/Desktop/crafter/logs/tomcat -Djava.net.preferIPv4Stack=true 	-Dgrape.root=/Users/arthurgenet/Desktop/crafter/bin
Using CATALINA_PID:    /Users/arthurgenet/Desktop/crafter/bin/apache-tomcat/tomcat.pid

## Logs
https://gist.github.com/ArthurGenet/3725b9b31c90dad95143f2fb9794917d

### OS
macOS Big Sur v11.2.1

### Browser
Firefox, Safari

**Comment by sumerjabri** [comment]
@ArthurGenet you removed parts of the bug report, this makes it hard to help you. What version of Crafter CMS did you install? Please attach the whole Tomcat log if possible (via Gist like you did for the exception).

**Comment by ArthurGenet** [comment]
> @ArthurGenet you removed parts of the bug report, this makes it hard to help you. What version of Crafter CMS did you install? Please attach the whole Tomcat log if possible (via Gist like you did for the exception).

Hello, thanks for your reply, I downloaded the last version of Crafter CMS Bundles Authoring (3.1.16)
Here is the full Tomcat log from ./startup.sh to the failed creation of a site: https://gist.github.com/ArthurGenet/efdbd16eb514b6adc0f545dc122dd290

**Comment by jdrossl** [comment]
hi @ArthurGenet , please check the deployer log under `/logs/deployer/crafter-deployer.log` & elasticsearch log under `/logs/elasticsearch/elasticsearch.log` the real cause of the error should be in one of those

**Comment by ArthurGenet** [comment]
hello @jdrossl, thanks a lot, I checked elasticsearch.log and found this: https://gist.github.com/ArthurGenet/605419548164d75ba7af5edcb607a88d
I added the line `xpack.ml.enabled: false` to `elasticsearch/config/elasticsearch.yml` and it worked
Thank you all for your help!
