### ISSUE TITLE
[studio] Folder gets locked and there's no way of unlocking

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4882]
## Describe the bug
Though it doesn't make too much sense, (1) If you happen to call the `get-content.json` endpoint with the path of a folder and `edit=true`, the folder gets locked and (2) once locked, the available actions of the folder doesn't show the unlock action.

This issue got surfaced by a UI bug [which is being fixed](https://github.com/craftercms/studio-ui/pull/2455) so chances of this happening are much lower.

## To Reproduce
1. Call get-content.json with path={pathToFolder}&edit=true
2. See folder getting locked & available actions of the item not having unlock as available

## Expected behavior
1. Folders don't get locked (instruction is ignored) **and/or**
2. Unlock action gets turned on

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT 2021/07/22

### OS
Mac OS X

### Browser
Chrome (don't think it matters)

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2683

**Comment by rart** [comment]
Verified.
