### ISSUE TITLE
[studio-ui] Remove deprecated  RTE  property "Force p tags New Lines"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4883]
## Describe the issue
The RTE property `Force p tags New Lines` option is deprecated since version 3.5 of TinyMCE. (https://www.tiny.cloud/docs-4x/configure/content-filtering/#force_p_newlinesdeprecated)
Please remove the property from our RTE 5.  The option is not listed anymore in the current version of TinyMCE.  Here's the current available options: https://www.tiny.cloud/docs/configure/content-filtering/

<img width="1016" alt="Screen Shot 2021-07-22 at 10 08 18 AM" src="https://user-images.githubusercontent.com/25483966/126686877-c54a4047-f62a-432f-8cb3-a58a3837240f.png">

### Version
Studio Version Number:
4.0.0-SNAPSHOT-7574e7
Build Number:
7574e79d369ffeb9f893fd95f0254fbf33f72ad9
Build Date:
7/22/2021, 9:11 AM

### OS
macOS

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by rart** [comment]
@jvega190 is there a replacement for the deprecated config? Should UM do anything?

**Comment by jvega190** [comment]
It was replaced by `forced_root_blocks` (https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@forced_root_block/), and we have it already configurable in the control.

**Comment by sumerjabri** [comment]
@jvega190 what's the next step for this ticket?

**Comment by jvega190** [comment]
@sumerjabri can we remove it using the UM? Now it won't show on the content-type form and it won't read it in the content form, but it will be in the xml. (Also, maybe need to remove from our bps)

**Comment by sumerjabri** [comment]
Checked with @rart and it won't' break existing sites. Closing.
