### ISSUE TITLE
[studio] Move the `disabled` state flag into the state bitmap

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4887]
Please move the `disabled` boolean flag into the `state` bitmap. Please use bit #11 after `live`. Also, push the translation states to start at bit #24 and leave the bits 12-23 as reserved.

**Comment by rart** [comment]
Note: This applies to both SandboxItem & DetailedItem models.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2684
