### ISSUE TITLE
[studio] Mantory parent state doesn't change after publishing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4889]
## Describe the bug
When publishing a new child of a new item, the parent does get published but the state of the parent doesn't change.

## To Reproduce
1. Create a site from Editorial
2. Publish an article
3. Look at the homepage state, it's still New

## Expected behavior
The parent should also transition from New to Published (and not new)

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT 2021-07-23

### OS
Linux

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2675

**Comment by Euquimides** [comment]
Hi @sumerjabri! I updated, re-checked the issue and made a automated test for it, which was merged into the integrated test-suite. This issue is fixed. Closing the ticket.
