### ISSUE TITLE
[studio] Rejecting an item doesn't remove its dependencies from the queue

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4890]
## Describe the bug
Rejecting an item that's submitted for review doesn't remove its dependencies from the publishing queue.

## To Reproduce
1. Create a site from Editorial
2. Request publishing of an article
3. See the first dashboard
4. Reject the article
5. Note that its dependencies have not been removed from the dashboard

## Expected behavior
Rejecting the parent item should remove its dependencies from the workflow.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT 2021-07-23

### OS
Linux

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2673

**Comment by sumerjabri** [comment]
Verified.

@yacdaniel assigning to you for automation.

**Comment by Euquimides** [comment]
Updated and reviewed this issue. It is fixed now, closing this ticket. Following automated tests, ticket #5376.
