### ISSUE TITLE
[studio] Publish dialog shows self as a dependency

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4891]
## Describe the bug
When publishing an item and looking at its dependencies, the dependencies include the item itself and not just its dependencies.

## To Reproduce
1. Open the publish item dialog
2. Click on show dependencies
3. See the item itself listed as a dependency

## Expected behavior
The item dependencies shouldn't list the item itself as a dependency.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Linux

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Can not reproduce with:
```
Studio Version Number:
4.0.0-SNAPSHOT-7ba51f

Build Number:
7ba51fe86c275da05bfbc3429763fc42d87a6e97
```

**Comment by sumerjabri** [comment]
Verified.
