### ISSUE TITLE
[docs] Docker instruction can result in terribly slow performance

### ISSUE THREAD

**Issue by VadimKirilchuk** [craftercms/craftercms#4895]
## Describe the bug
https://github.com/craftercms/docker-compose
Crafter CMS docker docs are suggesting to map volume in the host machine, but that's incredibly slow for windows wsl2...
"c:/host/path/to/sites:/opt/crafter/data/repos/sites"
mapping to windows drives or using /mnt/c or any other mapping to windows folders doesn't work well if using docker with WSL2.

The suggested way is to install linux to the wls2 using Microsoft Store and start docker images from there.
https://github.com/microsoft/WSL/issues/4197
https://www.docker.com/blog/docker-desktop-wsl-2-best-practices/

## To Reproduce
1. Make sure you have a windows version with WSL2 installed and docker is using WSL2 and not "windows containers or WSL1"
2. Follow https://github.com/craftercms/docker-compose to start authoring environment with repos/sites mapped to host folder
3. Try to create new site
4. Going to take a significant amount of time comparing to the non-mapped volume for repos/sites

## Expected behavior
Comparable performance

### Version
Any version 

### OS
Windows 10 enterprise 1909
Build 18363.1500

### Browser
Any browser

## Additional context
The problem is not in the crafter itself, but rather a windows wsl2 <->docker specifics.
The point of this issue is to update documentation in order to warn the users of possibly slow performance if using wls2 and mapping volume to windows host folder.

**Comment by alhambrav** [comment]
Docs merged. Closing ticket.
