### ISSUE TITLE
[studio-ui] CRAFTERCMS-1693: Component/Page wizard

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#49]
Original JIRA Fix Versions:
2.6.0, Original JIRA Components:
Studio, 
----------
Original JIRA Description: User should easily be able to jump between

content type def
the content
the controller
the template:

----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1693
----------

**Comment by sumerjabri** [comment]
@russdanner: Please elaborate the ticket with the required UX and better description of what we want to do if possible.

Is this for 3.0.0 or 2.5.x?

**Comment by russdanner** [comment]
I think this is backlog, it's not 2.x and it's not a priority for 3.0.0 launch.
Unless we find the bandwidth it's a nice to have.
