### ISSUE TITLE
[studio] Available publishing targets API returns possibly cached result from previous site

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4903]
## Describe the bug
When reusing the site name of a previously deleted site, if the old site had staging enabled and the new site by default doesn't, the get-available-publishing-channels api still returns both targets.

## To Reproduce
1. Create editorial site
2. Enable staging
3. Delete site
4. Recreate site with the same name
5. Open publish dialog and notice there's staging despite blueprint having staging disabled by default. You may also simply call the API directly.

## Expected behavior
Staging not shown if disabled despite reusing same site name

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
MAC

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2691

**Comment by rart** [comment]
Verified.
