### ISSUE TITLE
[studio] Set Workflow Filters in Workflow States API to be AND not OR

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4906]
The API currently returns results if any of the state bits are set, we want to change it to return the items where _all_ the bits are set.

See the API https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/workflow

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2698

**Comment by sumerjabri** [comment]
Verified.
