### ISSUE TITLE
[studio] Item submitted to live comes up as submitted to staging

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4908]
## Describe the bug
Item submitted to live comes up as submitted to staging

## To Reproduce
1. Create empty bp based site
2. Enable staging
3. Create a page (child of home)
4. Submit the new item to be published "now" to "live" target
5. Check the value of the state bitmap. Value is 35, which yields destination bit as 0 (staging) instead of 1.

## Expected behavior
Correct destination is stored and conveyed

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Mac

### Browser
Chrome

## Additional context
- Workflow table is correct but item table state column isn't

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2690

**Comment by rart** [comment]
Verified
