### ISSUE TITLE
[studio] lockOwner should be null when item is not locked

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4911]
## Describe the bug
When creating a new content, lockOwner has the value of the user that created the content, but item is not locked.

## To Reproduce
1. Create a new site using website editorial bp
2. Navigate to one of the articles folder , for our example, navigate to /articles/2020/16 then click on the 3 dots next to the folder and select New Content, then click on Article.
3. Fill in the required fields for the new page article and save your changes
4. Open the item menu of the recently created item (in Site Explorer and see the `item_by_path` response)

`/studio/api/2/content/item_by_path`
![Screenshot from 2021-08-04 09-25-20](https://user-images.githubusercontent.com/18267471/128209633-a01141e4-1364-40fd-a9dc-73db3f081489.png)

5. Open the dashboard and see the `get-user-activities` response

`/studio/api/1/services/api/1/activity/get-user-activities`
![Screenshot from 2021-08-04 09-26-20](https://user-images.githubusercontent.com/18267471/128209930-bec3f167-0544-4b3e-a71c-d62cd57cf92b.png)

## Expected behavior
lockOwner should be null when item is not locked.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/jvega190/787cf0b1bc7a2975f34d018de377ebb9
https://gist.github.com/jvega190/f3c8e28f012d4c30dbca9d124631ca9f

### Version
4.0.0-SNAPSHOT-e0fc33 - Build Date: 8/4/2021, 11:18 AM

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2689

**Comment by jvega190** [comment]
Verified fixed
