### ISSUE TITLE
[plugin][analytics] Create a Google Analytics plugin

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4915]
Repository: https://github.com/craftercms/analytics-plugin
Start with a good design and a simple implementation with room to grow.

### Tasks
- [x] Design
- [x] Implement
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by sumerjabri** [comment]
Please update the screenshot and language to be Google Analytics specific.

**Comment by phuongnq** [comment]
Verified work.
Just a side note: The site configuration in README.md is "Engine Site Configuration", is it correct? May confuse with "Site Configuration" from the configuration list.

**Comment by sumerjabri** [comment]
Documentation updated.
