### ISSUE TITLE
[plugin][sitemap] Create a sitemap generator

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4917]
Repository: https://github.com/craftercms/sitemap-plugin

Start with a good design and a simple implementation with room to grow.

### Tasks
- [x] Design
- [x] Implement
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by sumerjabri** [comment]
https://marketplace.craftercms.org/blueprints/org.craftercms.plugin.sitemap

**Comment by phuongnq** [comment]
After installed to latest `develop` branch, I got the following errors:

xml content cannot displayed in Chrome.
`lastmod` value seems to be an object.

Tested on Editorial blueprint.

![sitemap_display_error](https://user-images.githubusercontent.com/2996543/128983726-ec9edcdf-db5a-400e-8e29-8503e6374138.png)
![sitemap_json](https://user-images.githubusercontent.com/2996543/128983731-f9d5bb5a-746b-4eab-aef2-8af1080fed44.png)
![sitemap_xml_error](https://user-images.githubusercontent.com/2996543/128983734-2e441ece-ca63-433f-a73f-03ccd2bdf578.png)

**Comment by phuongnq** [comment]
verified
