### ISSUE TITLE
[plugin][youtube] Create a YouTube plugin to allow authors to embed YouTube videos on pages

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4920]
Repo: https://github.com/craftercms/youtube-plugin
Start with a good design and a simple implementation with room to grow.

### Tasks
- [x] Design
- [x] Implement BE
- [x] Implement FE
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by rart** [comment]
@sumerjabri any available details/requirements on what to do on the UI? @jvega190 please follow up.

**Comment by sumerjabri** [comment]
@rart at a high level:
* Allow authors to embed videos on pages
* Support PB
* Ask @jdrossl any lower-level technical questions

**Comment by rart** [comment]
@phuongnq it appears that the UI build set up is not on the repo. Can you please add the artifacts (package.json, yarn.lock, etc) needed to generate the build output. A readme would be good too.

**Comment by sumerjabri** [comment]
@jvega190 similar bugs to the carousel. It can't be edited easily (registration issues), and all text fields are auto-populated incorrectly (should be fixed when we fix the main issue).
