### ISSUE TITLE
[studio] Publishing is broken on v4.0.0-SNAPSHOT 8/6/2021

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4928]
## Describe the bug
Publishing fails.

## To Reproduce
1. Create a site based on Editorial BP
2. Try to publish anything
3. See the logs

## Expected behavior
Publishing should work

## Screenshots
N/A

## Logs
https://gist.github.com/sumerjabri/2479669fc907db66bc47477997bf2262

### Version
v4.0.0-SNAPSHOT 8/6/2021

### OS
Linux

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2699

**Comment by sumerjabri** [comment]
Verified fixed.
