### ISSUE TITLE
[studio] Clearing staged or published states clears both

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4930]
## Describe the bug
In API https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/workflow/setItemStates clearing published bit or staged bit clears both.

## To Reproduce
1. Go to Workflow states and clear one of the two bits
2. See both get cleared

## Expected behavior
Clearing one bit shouldn't affect the other

## Screenshots
N/A

## Logs
N/A

### Version
4.0.0-SNAPSHOT 2021-08-09

### OS
Linux

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
This is a UI issue. It is sending `false` (clear state) for both staging  and live

**Comment by jvega190** [comment]
Per conversation the controller shouldn't convert non-sent values to false.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2702

**Comment by sumerjabri** [comment]
Verified.
