### ISSUE TITLE
[studio] Unable to create level descriptor

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4935]
## Describe the bug
Unable to create a level descriptor in Editorial BP.

## To Reproduce
1. Create a site using Editorial BP
2. Create a level descriptor under any item
3. See the logs

## Expected behavior
Successful creation of a level descriptor.

## Screenshots
N/A

## Logs
https://gist.github.com/sumerjabri/06d31689402a797c435d8757aef7211f

### Version
v4.0.0-SNAPSHOT 2021-08-10

### OS
Linux

### Browser
Chrome

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2701

**Comment by sumerjabri** [comment]
@dejan-brkic please also fix the issue where `.keep` is counted as a child.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2704

**Comment by sumerjabri** [comment]
@dejan-brkic LD must be counted as a child

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2705

**Comment by sumerjabri** [comment]
Verified.
