### ISSUE TITLE
[plugin][google-tag-manager] Create a Google Tag Manager plugin

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4936]
Repository: https://github.com/craftercms/google-tag-manager-plugin

### Tasks
- [x] Design
- [x] Implement BE
- [x] Implement FE
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by phuongnq** [comment]
Verified work.
Just a side note: The site configuration in README.md is "Engine Site Configuration", is it correct? May confuse with "Site Configuration" from the configuration list.

**Comment by sumerjabri** [comment]
Documentation was updated.
