### ISSUE TITLE
[studio] Can't change the page URL (basically rename)

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#494]
Using Editorial blueprint:

1. Create a new page.
2. Save the page.
3. Open for edit and change the page URL.
4. Save the page.

The page disappears from the sidebar. If you refresh the browser, it will appear again, but if you open it again for edit, the old URL will still be there.

**Comment by dejan-brkic** [comment]
Not issue anymore.
Fixed with cut/paste related issues
