### ISSUE TITLE
[plugin] Add a "Help block" in the plugin definition file (craftercms-plugin.yaml) to provide help to users

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4944]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Users have to read a README file in GitHub to learn how to use a plugin in their site.

#### Describe the solution you'd like
Studio and Marketplace should provide help to the user installing the plugin on how to use/configure the plugin. Consider using a block of Markdown within the plugin YAML configuration file.

#### Describe alternatives you've considered
A hyperlink to the README file.

#### Additional context
The proposed solution must be secure and not permit XSS or similar attacks.

### Tasks
- [x] Design and discuss
- [x] Implement
  - [x] Backend
  - [x] Plugins
  - [x] Frontend
- [x] Test
- [x] Document
- [x] Update all plugins with a help block

**Comment by sumerjabri** [comment]
Pending updates to https://docs.craftercms.org/en/4.0/developers/plugins/plugin-descriptor.html#craftercms-plugin-yaml-file

**Comment by alhambrav** [comment]
Marking documentation done.  Updates to  https://docs.craftercms.org/en/4.0/developers/plugins/plugin-descriptor.html#craftercms-plugin-yaml-file done with commit:
https://github.com/alhambrav/docs/commit/8400732c7e506d86cb1d32433219c97e711f0e40
