### ISSUE TITLE
[studio-ui] Hitting ctrl+z on a just-loaded config file, clears the whole file

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4947]
## Describe the bug
Hitting ctrl+z on a just-loaded config file, clears the whole file

## To Reproduce
1. Go to site tools > configuration > select any file
2. Press ctrl/cmd + z (undo)
3. File clears completely

## Expected behavior
Undo stack should be cleared as soon as each config is loaded on the editor

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Mac/Linux

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
Verified.
