### ISSUE TITLE
[studio]The user cannot create a site with a name of the site previously deleted. 

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#495]
1. Log in to Crafter Studio 3.0
2. Create a site with an "X" name, for example: test
3. Delete the site created in the previous step (step 2).
4. Create a site with an "X" name, for example: test

Current Result
In the step4, the site is not created.
The user cannot create a site with a name of the site previusly deleted. 
Video : https://www.screencast.com/t/ODshYykuI0

Expected Result
Studio should be create a site using the name of the site previusly deleted.

**Comment by dejan-brkic** [comment]
Fixed PR #544
