### ISSUE TITLE
[studio] Filtered publish queue results are displayed out of order

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4951]
## Describe the bug
User's viewing the publishing queue want to be able to view results ordered by date. Descending should be considered the default order. Today Filtered results are shown out of order

## To Reproduce
1. publish several packages
2. go to the site config/publishing tab
3. open the publishing queue and filter by completed

## Expected behavior
The publishing queue should display results ordered by date. Descending should be considered the default order. 

## Screenshots
<img width="1549" alt="Screen Shot 2021-08-18 at 1 33 20 PM" src="https://user-images.githubusercontent.com/169432/129948089-33632423-08ab-4e0c-bd81-198233857a55.png">

## Logs
N/a

### Version
3.1.15
Build Number: 09e6a0cd09c25ffe6f1664e02babd48b461c0e27
Build Date/Time: 06-18-2021 16:43:21 -0400

### OS
Any

### Browser
All

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2709
https://github.com/craftercms/studio/pull/2710

**Comment by russdanner** [comment]
<img width="1440" alt="A" src="https://user-images.githubusercontent.com/169432/141492733-15caa3a0-68d2-4307-aec3-d8925a63d561.png">
<img width="1440" alt="B" src="https://user-images.githubusercontent.com/169432/141492736-c077e31a-e052-44c2-a082-666ce56dfd58.png">

**Comment by russdanner** [comment]
Confirmed
