### ISSUE TITLE
[studio] Studio is retrying some git ops when an invalid siteId is sent to Content APIs

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4956]
## Describe the bug

When a site that doesn't exist is sent to Content API's, the API takes longer to response and by the errors in logs, look like GitRepoHelper is retrying getting the repo of a site that doesn't exist. 

## To Reproduce
1. Create a site `editorial123`
2. Call the API `content/sandbox_items_by_path` with a non existing siteId
3. See error in logs, compare response time to a success site in Studio. 

## Expected behavior
Git helper shouldn't retry?  @sumerjabri 
The response time shouldn't be more than the usual OK reponse. 

APIs identified with this behavior so far: 
- `POST content/sandbox_items_by_path`

## Screenshots
N/A

## Logs
https://gist.github.com/yacdaniel/dbe30f7a77ab3e80b151cac7ba0c5fb1

### Version
`4.0.0`

### OS
Ubuntu 21.04

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2713

**Comment by yacdaniel** [comment]
@dejan-brkic please check the following endpoints, the issue seems to be happening there too. 
- POST content/children_by_id
- POST content/children_by_path
- GET content/item_by_id
- GET content/item_by_path

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2714

**Comment by yacdaniel** [comment]
Verified fixed.
