### ISSUE TITLE
[studio] Improve performance of get-workflow-affected-paths API

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#4958]
API v1 implementation has performance issue caused by walking repository structure and calculating API v1 item objects
- [x] design data model and new API v2
- [x] implement BE
- [x] switch UI to use new API v2 instead
- [ ] Test new API

**Comment by sumerjabri** [comment]
@russdanner let's discuss if we want this in 3.1

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2716

**Comment by dejan-brkic** [comment]
@rart Please make a change in UI to use v2 API which returns SandboxItem objects. Old API 1 is deprecated.

**Comment by yacdaniel** [comment]
@dejan-brkic  API still returning empty results.

**Comment by dejan-brkic** [comment]
@yacdaniel can not reproduce empty results anymore

**Comment by sumerjabri** [comment]
@Euquimides please add to the automation test suite

**Comment by Euquimides** [comment]
Hi @sumerjabri! I added the respective test cases for the Workflow API in Kiwi and also added the automated tests for this API in the integration-tests repository. It has been approved and merged. I am closing the ticket.
