### ISSUE TITLE
[studio] When a file is saved, the Deployer API deploy endpoint should be called

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#496]
It seems studio is not doing a deploy when an item is saved. The following URL should be called:

POST .../api/1/target/deploy/:env/:site_name (e.g. /api/1/target/deploy/preview/editorial)

For more info on this call, please check http://docs.craftercms.org/en/latest/developers/projects/deployer/api/target-management/deploy-target.html

**Comment by dejan-brkic** [comment]
Fixed PR #543
