### ISSUE TITLE
[studio] Adjust plugin wiring 

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4962]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Current wiring makes assumptions about the structure new elements need to be injected at.

#### Describe the solution you'd like
Please adjust to allow specifying exactly where to insert

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
{{Add any other context or screenshots about the feature request here.}}

**Comment by rart** [comment]
@alhambrav please close if the changes successfully allowed injecting the pieces that were an issue (e.g. ToolsPanel > leftSection, etc)

**Comment by alhambrav** [comment]
Verified.
