### ISSUE TITLE
[studio] Different values of AA in Content APIs for same item

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4963]
## Describe the bug
Content APIs are returning different values of Available Actions for the same item. 

## To Reproduce
1. Create a site from Editorial BP.
2. Call the following APIs. 
   -  POST `/content/children_by_path`,  body  `{ "siteId": "editorial", "path": "/static-assets"}`, check the response children folder `css`: `"availableActions": 197474`. Also POST `content/children_by_id` with the id of `/static-assets` returns the same 197474. 
     - GET `/content/item_by_path?siteId=editorial&path=/static-assets/css`, the response contains `"availableActions": 198498`. Also GET `content/item_by_id?siteId=editorial&id=6742` using the id of the css folders returns the same 198498.
     - Same issue with the `content/sandbox_items_by_*`, available actions is returning `197474`

## Expected behavior
Consistency in `availableActions` value for the different content API's. 

## Screenshots
N/A

## Logs
N/A

### Version
`4.0.0-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2717

**Comment by yacdaniel** [comment]
Verified fixed.
