### ISSUE TITLE
[studio-ui] Components options panel of page builder should open on the right side 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4966]
## Describe the bug
The Components options panel of page builder opens on the left side taking over the `Sidebar` containing `Dashboard`, `Site Explorer` and `Site Tools`. 

## To Reproduce
1. Create a site using the website editorial blueprint
2. Open the page builder panel by toggling the `Edit Mode` switch to on
3. Click on `Components`, then pick one component and  click on the three dots next to it. 
4. Select from any of the three options ( `List in-page instances`, `Browse Existing`, List drop targets`)
5. Notice a panel opens on the left side

<img width="1223" alt="Screen Shot 2021-08-25 at 9 50 22 AM" src="https://user-images.githubusercontent.com/25483966/130811721-bc54981a-1025-42b6-8f45-3d27a1bff6a3.png">

## Expected behavior
Components options panel of page builder should open on the right side

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-f1e305

Build Number:
f1e3055c070b5c1fa26a9556254b01ca8873e9cc

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
Verified fixed

https://user-images.githubusercontent.com/6722074/133456352-e2b9cb4c-3e64-4898-9977-a7e255c4d3aa.mp4
