### ISSUE TITLE
[docs] Update plugin host docs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4967]
### Crafter 3.1.x (priority)
- [x] Create new repo for 3.1
- [ ] Add samples to new repo and make them work with 3.1
- [ ] Update docs page to point to the new repo
  - https://docs.craftercms.org/en/3.1/developers/plugins/studio/plugin-host-page-examples.html

### Crafter 4
- [x] Create 4.0 repository
- [ ] Create new installable plugin/repo with the different plugin host samples and make them work in 4
- [ ] Update docs page to point to the new repo(s)
  - https://docs.craftercms.org/en/4.0/developers/plugins/studio/plugin-host-page-examples.html

### Misc
- [ ] Kill craftercms-editorial-ice repo

**Comment by rart** [comment]
We must retire [this repo](https://github.com/craftercms/craftercms-editorial-ice) once this work is complete.

**Comment by sumerjabri** [comment]
All 4.0 examples are here: https://github.com/craftercms/authoring-ui-plugin-examples

3.1 example is still at Roy's and that' not good, but I'm ignoring for now.

4.0 docs for host plugin are here https://docs.craftercms.org/en/4.0/developers/extensions/plugin-host-page.html#plugin-host-page
