### ISSUE TITLE
[studio] Plugin installation requirements

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4968]
# Feature Request

#### Is your feature request related to a problem? Please describe.
Plugins, just like blueprints, may have certain configuration requirements to power them (e.g. google maps API key).

We need a way of determining at installation time if the plugin has config requirements and which so that we can inform the user and prompt for any necessary input.

#### Describe the solution you'd like
An API similar to blueprints that specify their requirements so the UI can build a form for it.

#### Additional context
Nevertheless, plugins should still handle missing or incorrect configuration gracefully.

**Comment by sumerjabri** [comment]
Completed.
