### ISSUE TITLE
[studio-ui] Implement submission comment requirements in rectified dialogs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4969]
#### Description

The following settings got lost in the rectification of dialogs/widgets
```xml
    <publishing>
        <comments>
            <!-- Global setting would apply to all -->
            <required>false</required>
            <!-- Additional (also optional) specific overrides -->
            <!-- <delete-required/> -->
            <!-- <bulk-publish-required/> -->
            <!-- <publish-by-commit-required/> -->
        </comments>
    </publishing>
```

#### Describe the solution you'd like
Apply the settings to the publishing dialog, delete dialog and publish on demand widget.

#### Additional context
There's no specific setting for the publishing dialog like there is for delete, publish by commit or bulk publish @russdanner

**Comment by yacdaniel** [comment]
Verified fixed.
