### ISSUE TITLE
[studio-ui] Hide files from nav tree if flagged as such

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#497]
Please change the nav tree listing of XML files to hide the files with the flag "hideInAuthoring = true" from the navigation tree.

To validate: Click on the homepage in any site, and see the file "crafter-component.xml," that file has "hideInAuthoring = true" and shouldn't show up.

Ping me if you have any questions.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/348
