### ISSUE TITLE
[studio-ui] Improve Search behavior in Browse Components tool of Page Builder

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4972]
## Describe the bug
As you type in the search word, it seems like it's trying to find a match every so many seconds and its interrupting me typing in my search term, such that the experience is not so pleasant.

Also, it's not obvious that the `Content Type` is mandatory when doing a search making the user think search is not working

## To Reproduce
1. Create a site using the website editorial  bp
2. Open  the Page  Builder panel then click on `Browse Components`
3. Type a word in the `Search` box, say `Feature`
4. Notice how your typing is interrupted and it feels like it is trying to do a search every so many seconds

Here's a short clip showing a search term being entered in the search box inside the Browse Components tool.
https://www.loom.com/share/6ec59a45e2fc48adad880f181990624d

According to @rart, this is a repaint bug in the tool.

5. After entering your search term, notice it displays at the bottom `Please Choose a Content Type` and it looks like it did not do a search at all. 
<img width="216" alt="Screen Shot 2021-08-27 at 9 08 51 AM" src="https://user-images.githubusercontent.com/25483966/131140952-564c14d0-51f5-472e-b5c1-f6640d4c8621.png">

## Expected behavior
Improve Search behavior in Browse Components tool of Page Builder.  
- The user should not be interrupted entering the search term. (Fix the repaint bug)
- Improve the search function if possible, from @rart "flip the filters around (required content type selection first)"

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-1e890d

Build Number:
1e890d92d55adf8750f855b082f495222a579f0d

Build Date:
8/26/2021, 7:22 AM

### OS
macOS 10.15.7

### Browser
Chrome Browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by yacdaniel** [comment]
@aachavarria looks like when there is the user enters a keyword and then changes  the `Content Type` filter, the new request is not going with the previous keyword. 


https://user-images.githubusercontent.com/6722074/133377241-f565b504-b3aa-4ce9-baa3-7352408d2ad8.mp4

**Comment by alhambrav** [comment]
Verified fixed.
