### ISSUE TITLE
[studio] Submitting then scheduling doesn't clear submitted flag

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4975]
## Describe the bug
Submitting (request approval) then scheduling (approve) doesn't clear submitted flag. The item keeps showing as submitted.

## To Reproduce
1. Login as admin, select "publish" option on an item menu
2. Select the request approval checkbox, schedule for a later date and submit
3. Repeat those same steps for the same item (this time, don't check request approval — check box shouldn't even show up).
4. Notice item still has the submitted flag

## Expected behavior
Once approved, the submitted flag is cleared

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT 2021-08-27T11:13:19-06:00

### OS
Mac

### Browser
Chrome

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2723

**Comment by rart** [comment]
@jvega190 please validate

**Comment by jvega190** [comment]
Verified fixed
