### ISSUE TITLE
[studio] Background tasks running before upgrades are ready

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4976]
## Describe the bug
When Studio is starting up the background tasks start running before the upgrade manager has completed the execution. In some cases like 3.1.x -> 4.0 that means the database is not ready for the queries executed.

## Expected behavior
All background tasks should wait until a `BootstrapFinishedEvent` is received to make sure the system is ready.
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/utils/spring/context/BootstrapManager.java#L64

## Logs
```
[ERROR] 2021-08-27T15:13:07,943 [pool-15-thread-4] [job.StudioClockExecutor] | Error executing Studio Clock Job 
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: (conn=19) Unknown column 'state' in 'where clause'
### The error may exist in org/craftercms/studio/api/v1/dal/SiteFeedMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT site_id FROM site WHERE state = ? AND deleted = 0 AND system = 0
### Cause: java.sql.SQLSyntaxErrorException: (conn=19) Unknown column 'state' in 'where clause'
```

### Version
4.0.0-SNAPSHOT

### OS
Ubuntu 20.04.3 LTS

**Comment by jdrossl** [comment]
@yacdaniel please help validate this fix

**Comment by yacdaniel** [comment]
Verified fixed.
