### ISSUE TITLE
Improvements for translation

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4980]
Perform the following updates for translation:
- [x]  UI: Make the field `localeCode` not required in Form Engine and don't add it by default to any page or component
- [x] Engine, Deployer: Add a flag to disable all translation features (default to disabled for now)
- [x] Blueprints: Update all blueprints to make sure the field `localeCode` is no inculded in any content-type or xml file
- [x] Test
- [x] Document

**Comment by jvega190** [comment]
@jdrossl UI work is done and merged, also updates for OOB bps are merged, @sumerjabri wordify blueprint needs to be merged and published for validation, we just need testing in OOB before publishing.

**Comment by jdrossl** [comment]
@yacdaniel please help validate

**Comment by yacdaniel** [comment]
@jvega190 please check the next console error, this should be removed too? 
```
[parseContentXML] Field "locale" was not found on "/component/feature" content type. "null" may have stale/outdated content properties.
```
From Editorial blueprint, go to `Components` and drag and drop `Feature`

https://user-images.githubusercontent.com/6722074/132710397-d3484f1d-2f00-4173-b43d-90a5b317c317.mp4

**Comment by jvega190** [comment]
> @jvega190 please check the next console error, this should be removed too?
> 
> ```
> [parseContentXML] Field "locale" was not found on "/component/feature" content type. "null" may have stale/outdated content properties.
> ```
> 
> From Editorial blueprint, go to `Components` and drag and drop `Feature`
> 
>  component.drag.and.drop.mp4

Hi @yacdaniel, the console error fix is done

**Comment by yacdaniel** [comment]
Verified fixed.
