### ISSUE TITLE
[studio-ui] Disabled pages have no indications it is disabled when previewing or in the dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4981]
## Describe the bug
When a page is disabled, there is no  indication on the page when it is previewed that it is disabled (a banner on top or something telling the user the  page is disabled.  Also, when you look at the dashboard, there is also no indication of the page being disabled (like the item name with a strike out or something) 

## To Reproduce
1. Create a site using the website editorial bp
2. Edit a page, then put a check mark next to the `Disable Page` field
<img width="1010" alt="Screen Shot 2021-08-30 at 12 36 19 PM" src="https://user-images.githubusercontent.com/25483966/131373500-745de22f-8e9a-492e-949d-d1285618512e.png">

3. Notice there is no indication on the page that it has been disabled
<img width="1044" alt="Screen Shot 2021-08-30 at 12 37 46 PM" src="https://user-images.githubusercontent.com/25483966/131373798-3d1fac92-d6e4-4ae0-872c-b6f4640a576d.png">

4. Open the dashboard, notice in the `My Recent Activity` dashlet that there is no indication the page we disabled is disabled
<img width="1007" alt="Screen Shot 2021-08-30 at 12 40 07 PM" src="https://user-images.githubusercontent.com/25483966/131374003-b160a2b3-62cc-4c79-a072-c999e1b6e852.png">

## Expected behavior
Disabled pages should have an indication that it is disabled when previewing or when listed in the dashboard

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number:
4.0.0-SNAPSHOT-fade4e

Build Number:
fade4e42db6056690dfdf6c10ffa5acd74908253

Build Date:
8/30/2021, 10:48 AM

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by alhambrav** [comment]
Hi!
After disabling a page, it used to have a banner/note up top of the page that a page is disabled.  It would be nice to have a note on the page itself that it is disabled
<img width="1129" alt="Screen Shot 2021-09-07 at 7 56 03 AM" src="https://user-images.githubusercontent.com/25483966/132341100-b28f8718-7715-464e-a51a-4374a3682036.png">

Also, after disabling the page, go to the Dashboard.  Notice that the icon next to the page you disabled in the `My Recent Activity` dashlet is not updated
<img width="1058" alt="Screen Shot 2021-09-07 at 7 55 47 AM" src="https://user-images.githubusercontent.com/25483966/132341235-8cbcb1f5-a4cd-4d92-9236-efb2725e21fe.png">

**Comment by jvega190** [comment]
@alhambrav I just sent the fix for the dashboard. For the banner, it will be discussed and if needed, we'll create a new ticket for it.

**Comment by alhambrav** [comment]
Verified fixed.
