### ISSUE TITLE
[craftercms] Update upgrade scripts

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4982]
Update the bundle upgrade scripts to support 3.1.x to 4.0.x:
- Run the db upgrade script
- Check if indexes need to be recreated to go from ES 6.8 to 7.x

**Comment by sumerjabri** [comment]
- Check if we must upgrade the DB one more time
- Check if ES needs a final upgrade before 4.0.0

**Comment by yacdaniel** [comment]
Verified in 4.0.
