### ISSUE TITLE
[studio] Editing templates or scripts doesn’t check workflow affected paths

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4984]
## Describe the bug

Editing templates or scripts doesn’t check for workflow affected paths.
Also, workflow affected paths check should show a loading indication while working (_minimised dialog_).

## To Reproduce
1. Go to preview
2. Click edit on script or template
3. No workflow affected check is issued

## Expected behavior
All asset/content edit should check

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
4.0.0-SNAPSHOT

### OS
Mac

### Browser
Chrome

## Additional context

Please check that taxonomies do too

craftercms/craftercms#4958
https://github.com/craftercms/craftercms/issues/4958#issuecomment-906698757

**Comment by yacdaniel** [comment]
Verified fixed.
