### ISSUE TITLE
[studio-ui] ICE is disabled for site with proxy point to SPA in port 3000

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4985]
## Describe the bug

When adding proxy to a SPA in port 3000, Studio ICE is disabled

## To Reproduce
1. Create a site from Empty blueprint
2. Run a SPA in port 3000, ex: https://github.com/phuongnq/react-shopping-cart
3. Configure proxy of Studio to http://localhost:3000
4. Go to preview
5. Notice that while the SPA is previewed, ICE icon is disabled.

## Expected behavior

ICE should be enabled and user could use ICE for SPA site in port 3000 while in preview mode

## Screenshots

![ice_disabled_preview_3000](https://user-images.githubusercontent.com/2996543/131505906-d4b85b5f-9a00-4b71-b481-58d3d2ef4d33.png)

### Version
4.0

### OS
Ubuntu

### Browser
Chrome

**Comment by rart** [comment]
@phuongnq I couldn't see anywhere in your app that you were actually registering the `guest`. That's also why you see the message shown on the bottom part of your screenshot.

ICE-enabled pages/apps must register with Studio — either via old (`@craftercms/ice`) or new mechanics (not published yet, only available through cloning and some local set up).

[Wordify](https://github.com/craftercms/wordify-blueprint) is an example of 3.1.x site with ice-enabled.
https://github.com/craftercms/wordify-blueprint/blob/master/sources/react-app/src/shared/DynamicRoute.js

[Wordify](https://github.com/craftercms/wordify-blueprint/tree/react) is an example of 4.0.0 site with ice-enabled. However this one requires special setup and packages aren't published yet. We would need to meet to set up if you're going this route.

**Comment by phuongnq** [comment]
I confirmed the Wordify worked. Some missing configurations from my side for this.
