### ISSUE TITLE
[studio-ui] Input mandatory fields should not be saved with space input only

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#4990]
# Feature Request

#### Is your feature request related to a problem? Please describe.

Currently user can save a textarea/input/rte with space only

#### Describe the solution you'd like

Add a checker to not enable users to save content with space only

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by phuongnq** [comment]
verified in support/3.1.x

**Comment by rart** [comment]
@jvega190 please port 3.1.x pr to develop

**Comment by phuongnq** [comment]
verified in 4.0
