### ISSUE TITLE
[studio-ui] Add ability to set site image in site edit dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4994]
#### Is your feature request related to a problem? Please describe.
After installing a blueprint and evolving a site an admin or power user will want to update their screenshot for the site.

#### Describe the solution you'd like
It should be very easy to set your screenshot for your site through the studio UI via the edit site details dialog.

**Comment by rart** [comment]
@jvega190 split the dialog into two columns: left column remains the current form and the right column would be displaying the current image and a button to "Edit" which would allow uploading a new image.

**Comment by russdanner** [comment]
Confirmed
