### ISSUE TITLE
[studio-ui] Preview: Last visible options on the left menu can't be clicked when a dialog is minimized. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4995]
#### Crafter CMS Version
`4.0.0-SNAPSHOT`

#### Describe the bug
If a user minimizes a dialog like `Content Form`, `Site Tools`, `Dashboard` and `Site Explorer` or `Site Tools`  is expanded, according to user current viewport, the last options in the left menu can't be clicked

#### To Reproduce
1. Create a site from Editorial
2. Expand `Site Explorer`
3. Click `Edit` on a page then `Save & Minimize`
4. Try to click left menu options that are at the same level of the Minimized dialog. 

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/6722074/132701926-66b891d6-19d6-498c-b705-acc354651c46.mp4

**Comment by rart** [comment]
This is fixed on the MUI upgrade branch. Just pending merge into develop.

**Comment by yacdaniel** [comment]
Verified fixed.
