### ISSUE TITLE
[studio] Add Remove Plugin capability to Studio

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5006]
#### Is your feature request related to a problem? Please describe.
Add the ability to remove a plugin.

#### Describe the solution you'd like
Remove Plugin
=========
- Compute dependencies against the plugin
  - Compute deps against the items listed in the plugin when installed
    - For inter-deps, deps on from plugin on the plugin, ignore
    - For deps on content types, figure this out or add it to the DB
  - Create a new service that does the above for the UI to call and notify the user
- Let the user decide if it is acceptable to remove the plugin
- Show the files that will be published upon removal of the plugin (delete is a publishing operation)
- Delete and publish as we do any ordinary item
- Validate that we didn't break GraphQL
- Remove from the plugin registry

##### Tasks
- [x] Design backend
- [x] Design UI
- [x] Implement backend
- [x] Implement UI
- [x] Test
- [x] Upate documentation where applicable

#### Describe alternatives you've considered
Manual deletion is possible, but laborious and error prone.

**Comment by sumerjabri** [comment]
UM doesn't seem to patch the regex in existing sites correctly, and therefore it's unable to catch embedded components during uninstall.

**Comment by jdrossl** [comment]
@sumerjabri I did find some missing configurations, but I was not able to reproduce the issue, it works as expected even creating a site from a 3.1 blueprint
