### ISSUE TITLE
[studio-ui] Change Rejection Reason string in reject dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5007]
Please change the string:
- "Rejection Reason" to be "Predefined Rejection Comments"

**Comment by rart** [comment]
@jvega190 
- make the dropdown's default value be "Type my own comment"
  - making/change the selection on the dropdown should not be required
- make the "rejection comment" field show as _required_ (add asterisk)

Related/ties to/into https://github.com/craftercms/craftercms/issues/4870. Will need to swap API calls once the other effort is ready.
