### ISSUE TITLE
[studio] Remove `reason` from Reject API and switch notification template

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5008]
### Tasks
- [x] Remove the `reason` field from the reject API https://github.com/craftercms/studio/blob/develop/src/main/api/2/studio-api-2.yaml#L6548
- [x] Switch the notification templates field `rejectionReason` to be populated by the rejection comment https://github.com/craftercms/studio/blob/develop/src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/config/studio/workflow/notification-config.xml#L193

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2751
