### ISSUE TITLE
[studio] The approve&publish process not working properly.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#501]
Steps:
1. Login to Crafter Studio 3.0
2. Create a valid content
3. Try to approve&publish the content created or any other content.

Current Result
The user only see the "Processing" icon in the menu, and the content isn't publish.
video: https://www.screencast.com/t/YU2ia7AkA3lV

Expected Result
The content should be publish and in the menu the "Live" icon should be display for the content previously publish.

**Comment by sumerjabri** [comment]
This works fine for me for me. The problem I see is recent activity is empty, and I'll file a ticket for that.
Please switch to the latest bundle using: https://github.com/craftercms/craftercms
Follow the instructions in the README.md file and ping me if you need any help.
