### ISSUE TITLE
[studio] Content API's return "NULL" string instead of null object for some properties of folder content.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5010]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-a066ae`

#### Describe the bug
Some properties in the responses of Content API's, when querying for a folder, are returned as `"NULL"` string instead of the `null` object

#### To Reproduce
1. Create a site based on Editorial BP
- POST `/content/children_by_id`  with id of `static-asset`  folder, response
```
"children": [
        {
            "id": 2010,
            "label": "css",
            "parentId": 2005,
            "contentTypeId": "NULL",
            "path": "/static-assets/css",
            "previewUrl": null,
            "systemType": "folder",
            "mimeType": "NULL",
            "state": 1,
            "lockOwner": null,
            "localeCode": "en_US",
            "translationSourceId": null,
            "creator": null,
            "dateCreated": "2021-09-22T14:39:51Z",
            "modifier": null,
            "dateModified": "2021-09-22T14:39:51Z",
            "commitId": "5db5d4fd878f767ab2074bd233fde2b08bdf19d8",
            "sizeInBytes": 0,
            "availableActions": 198498,
            "childrenCount": 3
        },
 ```
- POST `content/children_by_path` 
- GET `/content/item_by_id` 
- GET `content/item_by_path`
- POST `content/sandbox_items_by_id`

#### Logs
N/A

#### Screenshots
Issue cause a `NULL` to be displayed in UI for folders. 
![image](https://user-images.githubusercontent.com/6722074/134367478-9fca6d44-23c9-4727-88a5-6e4a2a64d6e9.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2752

**Comment by yacdaniel** [comment]
@rart please update UI to remove the `null` for folders 
![image](https://user-images.githubusercontent.com/6722074/134932843-032a75ee-447c-42c8-bdfd-afdbdc4bf28f.png)

**Comment by rart** [comment]
@jvega190 when mimeType is null, do not display the `- {mime}` piece of the tooltip.

**Comment by yacdaniel** [comment]
![image](https://user-images.githubusercontent.com/6722074/135111379-6846c52e-6134-4dc9-af41-459c5e9158f2.png)
Verified fixed.
