### ISSUE TITLE
[deployer] Create an API to recreate the index for a site

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#5011]
The process for [recreating the index of a site](https://docs.craftercms.org/en/3.1/system-administrators/activities/reindexing-content-in-prod.html#reindexing-content-in-prod) has become more complex with Elasticsearch and it can be easily automated with existing code. The deployer should provide an API to trigger it:

`http://localhost:9191/api/1/target/recreate/{env}/{site_name}`

Note: the doc for this new API must clearly indicate that it is only supported with ES

**Comment by sumerjabri** [comment]
@alhambrav please note the PRs that went into the docs in support of this:
* https://github.com/craftercms/docs/pull/1361
* https://github.com/craftercms/docs/pull/1360

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.22` and `4.0`
