### ISSUE TITLE
[studio-ui] Example HTML for FTL editor is dated

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5014]
#### Crafter CMS Version
v4.0.0-SNAPSHOT 9/30/2021

#### Describe the bug
The code samples used to insert code into FTL are dated and no longer valid.

#### To Reproduce
1. Go to edit an empty FTL page from the content type editor (THIS IS CRITICAL)
2. Click on Insert Code
3. Scroll down to HTML
4. Click insert
5. See dated code

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by rart** [comment]
@jvega190 this is a config change. please incorporate as part of the next batch of config updates.

**Comment by rart** [comment]
@jvega190 

```ftl
<#import "/templates/system/common/crafter.ftl" as crafter />
<!doctype html>
<html lang="en">
  <head>
    <#-- Insert your html head -->
    <@crafter.head />
  </head>
  <body>
    <@crafter.body_top />
    <#-- Insert your html body -->
    <@crafter.body_bottom />
  </body>
</html>
```

**Comment by rart** [comment]
@jvega190 other snippets are also out of date and there are several missing new snippets we could add.

**Comment by russdanner** [comment]
Confirmed
