### ISSUE TITLE
[studio] children_by_path and item_by_path return different values for lockOwner and availableActions

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5015]
#### Crafter CMS Version
4.0.0-SNAPSHOT-6c8e70

#### Describe the bug
`children_by_path` and `item_by_path` services return different values when editing a code template. The values that differ are lockOwner and availableActions

#### To Reproduce
1. Create a site based on editorial.
2. Open the network inspector
3. Go to templates, and edit a template.
4. Look at the `item_by_path` request and see the lockOwner and availableActions values. (for example, lockOwner is the current user that opened the template.
5. Wait a couple of minutes and see that the 'Save' button gets disabled, then, look at the `children_by_path` request and see that the lockOwner and availableActions differ from the other service (for example, lockOwner is null).

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2756

**Comment by jvega190** [comment]
Verified fixed
