### ISSUE TITLE
[studio-ui] Disabled state icon does not go away after re-enabling page

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5020]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-3a5c50

Build Number:
3a5c50b93370ab98c1a196e3ab94c89572927eea

#### Describe the bug
When a disabled page is re-enabled, the disabled state icon does not go away

#### To Reproduce
1. Create a site using the website editorial bp
2. Click on an article page and edit it.
3. Check `Disable Page` and save your changes
4. Notice the state icon for the page at the `Site Explorer` path navigator and the address bar at the top
5. Edit the page again and uncheck `Disable Page` then save your changes
6. Notice the state icon for the page still displays the disabled state

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
<img width="1050" alt="Screen Shot 2021-10-04 at 7 33 47 AM" src="https://user-images.githubusercontent.com/25483966/135844987-0d818e34-5fef-4590-b0e9-d61ec11d06c0.png">

**Comment by aachavarria** [comment]
Doing some testing after enabling the page again and getting the item it comes with disabled bit on true

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2763

**Comment by alhambrav** [comment]
Verified fixed.
