### ISSUE TITLE
[studio] Solr and Elasticsearch start up with multiple arguments when only one argument is listed

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5026]
#### Crafter CMS Version
v3.1.15E

#### Describe the bug
When modifying the Solr configuration in the crafter-setenv.sh to start up solr with Xms instead of the default Xmx, Solr starts up with both arguments. 

#### To Reproduce
1. Download the 3.1.15E bundle
2. Navigate to the CRAFTER_HOME/bin directory and modify the 'creafter-setenv.sh' file and change the SOLR_JAVA_OPTS variable to be `export SOLR_JAVA_OPTS=${SOLR_JAVA_OPTS:="-server -Xss1024K -Xms1G"}`
3. Start up Crafter
4. Run a `ps -ef | grep java` and see that the Solr process has been started up with both the -Xmx and -Xms flag.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/136121567-eac3bdd6-904a-498f-8269-d0223e856f61.png)

**Comment by sumerjabri** [comment]
@phuongnq if there is a smarter way to fix this, where admins can still edit `crafter-setenv.sh`, then that would be the best path forward.

Perhaps in solr.in.sh we can use the `SOLR_JAVA_OPTS` env var. Or even better to rename that to SOLR_JAVA_MEM and have Solr read that etc.

**Comment by AndyReiter** [comment]
Confirmed Fixed in 3.1.18. Closing now.
