### ISSUE TITLE
[studio] Using Item_by_path with config.xml is returning availableActions as 0

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#5032]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-70126d

Build Number:
70126d0540bf5db2d3650509180888178fd7856f

#### Describe the bug
Using item_by_path to get a config.xml like /config/studio/content-types/component/feature/config.xml , is returning availableActions: 0

#### To Reproduce
1. Create editorial site
2. Use item_by_path service to fetch /config/studio/content-types/component/feature/config.xml
3. Check availableActions

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by sumerjabri** [comment]
Fixed by https://github.com/craftercms/craftercms/issues/5476
