### ISSUE TITLE
[studio] Preview deploy is not triggered when doing a copy/paste.

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5043]
#### Crafter CMS Version
3.1.18-SNAPSHOT

#### Describe the bug
When doing a copy/paste of a page or component, the preview deploy is not triggered so the files are not indexed. Similarly, when doing a copy/paste of a script the preview deployer is not called so a context rebuild is not done.

#### To Reproduce
1. Create a site based on Editorial
2. Make sure you're tailing the `crafter-deployer.out`.
3. Copy an article from one folder to another.

You should not see any new entries in the Deployer log for the copy/paste operation. But if you open the page and then save it, new logs entry should appear. This means basically that the preview deployer is not called on copy/paste.

The same thing happens with scripts, which means that scripts changes are not going to loaded because the context is not rebuilt on copy/paste.

#### Logs
N/A

#### Screenshots
N/A

**Comment by avasquez614** [comment]
Verified in 3.1.x. @yacdaniel I need help with verifying this in 4.

**Comment by yacdaniel** [comment]
Verified fixed in 4.0.x
