### ISSUE TITLE
[studio] MariaDB Connection resets occur on occasion in logs

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5048]
#### Crafter CMS Version
3.1.9+

#### Describe the bug
Occasionally we see the following errors in the logs.  While the message is INFO and the no error conditions or mal effects occur as a result the message continues noise to the logs and raises a question as to why it occurs. 

```
[INFO] 2021-10-26T22:50:51,426 [Exec Stream Pumper] [exec.ManagedProcess] | mysqld: 2021-10-26 22:50:51 36 [Warning] Aborted connection 36 to db: 'crafter' user: 'crafter' host: 'localhost' (Got timeout reading communication packets)
```

#### To Reproduce
1. Start an instance to Crafter Studio
2. Perform typical editing and publishing activities
3. Let the environment sit for several hours. 
(Note: additional conditions are very likely to be required however these are not known at this time.)
4. grep the log for reset errors 

#### Logs
N/A

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
This may have been resolved with the database optimizations. Should be reviewed.

**Comment by russdanner** [comment]
Confirmed
