### ISSUE TITLE
[studio-ui] Clicking on Save & Close on a page or component very quickly can trigger no commit

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5050]
#### Crafter CMS Version
Current support/3.1.x (3.1.18)

#### Describe the bug
Clicking on Save & Close on a page or component very quickly can trigger no commit. Normally even when no change is done in the form at least the last edited date is changed so a commit is triggered. This is very noticeable on heavy forms and sites with a lot of commits

#### To Reproduce
1. Create a site based on Editorial
2. Create an article that includes a lot of text and images in its body
3. Click on Edit and as fast as possible click on the Save & Close button (hopefully in less the 1-2 seconds)

Occasionally, you will see that the Save & Close doesn't trigger an update (update doesn't appear in My Recent Activity, no new commit appears in the sandbox repository, the preview deployer log is not updated).

This is easier to reproduce in larger repositories with a lot of commits, so if it can't be reproduced well enough with Editorial, a site can be provided for testing.

#### Expectations
What's expected is that Save & Close is not enabled until the form is completely loaded.

**Comment by avasquez614** [comment]
@yacdaniel can you help me verify this? This should be easier to test with a big site with a lot of commits.

**Comment by yacdaniel** [comment]
Verified fixed in 4, a warning dialog appears when `Save & Close` is clicked and Form Engine isn't loaded. 

![save quick](https://user-images.githubusercontent.com/6722074/148248992-3dd0fd5f-51a8-4393-95d3-c2e434d8a2da.gif)
