### ISSUE TITLE
[studio][studio-ui] Switch to `write-content` API and stop using `asset-upload`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5051]
Frontend:
- Switch all write calls to use `write-content` in v3.1 and v4

Backend:
- Disable `asset-upload` in v4

Documentation:
- Note that `asset-upload` is deprecated in v3.1
- Remove `asset-upload` from the docs in v4

**Comment by jdrossl** [comment]
Nothing else to change in the backend

**Comment by alhambrav** [comment]
Nothing to change in the doc APIs, just some updates for some screens.

**Comment by sumerjabri** [comment]
@alhambrav just assign back to me when complete.
