### ISSUE TITLE
[search] Support querying more than one Elasticsearch index in a single query

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5055]
#### Is your feature request related to a problem? Please describe.
There is a need to query the site search index and additional external Elasticsearch indexes managed externally.

#### Describe the solution you'd like
Add the ability to specify a number of external indexes that a developer may query (join query) while maintaining security and segregation between sites.

##### Tasks
- [x]  Design the solution and review it
- [x] Implement
- [x] Test
- [x] Document

#### Describe alternatives you've considered
Ingest external sources into the site index. Gets messy fast.

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.18 and 4.0.1
