### ISSUE TITLE
[studio-ui] Deleting a file with a comma in the name fails

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5056]
#### Crafter CMS Version
3.1.11E 
Studio Version Number: 3.1.17E-75f857

#### Describe the bug
Trying to delete a file with a comment in its name results in a failure.

#### To Reproduce
1. Create a file and put a name with a comma on it (My test, file)
2. Upload the file into static-assets folder
3. Right click into uploaded file -> Delete
4. Check logs for the error `You don't have permission to perform this task, please contact your administrator`
5. Clicking on Delete button it doesn't do anything

#### Logs
https://gist.github.com/AndyReiter/05ac3cd974904328ac606679dbc20c76

**Comment by sumerjabri** [comment]
Note: in v4, Site Policy prevents having files with special chars.

**Comment by sumerjabri** [comment]
Since this is not an issue in v4, we will close it.
