### ISSUE TITLE
[studio-ui] When search is enabled for a DS and on the browse path the parentPath macro is used, an exception is thrown

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5061]
#### Crafter CMS Version
3.1.15 to latest

#### Describe the bug
When search is enabled for a DS and on the browse path the `parentPath` macro is used, an exception is thrown.

#### To Reproduce
1. Create a site based on Editorial
2. Add a folder under Components with name `us`, and another one called `left-rails` under it.
3. Go to the `Page - Article` content type, and in the Components Left Rail DS, uncheck `Enable Create New`, uncheck `Enable Browse Existing` and check `Enable Search Existing`. Leave `Repository Path` empty and set `Browse Path` to be `/site/components/{parentPath[0]}/left-rails/`.
4. Open an article for edit, click on the Add button of the Left Rail.

A search error appears as soon as the DS popup appears, and an exception in the logs (see logs section)

#### Logs
https://gist.github.com/avasquez614/b4d0f5c3562123331226f66c319668ee

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/139953346-8b0e18d4-d975-4719-888e-de6d348408e3.png)

**Comment by jvega190** [comment]
@avasquez614 this can be tested in 3.1.x

**Comment by avasquez614** [comment]
Verified in 3.1.x

**Comment by avasquez614** [comment]
@jvega190 this needs to be done in 4. After that, assign to @yacdaniel

**Comment by yacdaniel** [comment]
Verified fixed in 4.0.x
