### ISSUE TITLE
[studio-ui] Studio opens both DS when they're setup for search

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5062]
#### Crafter CMS Version
3.1.15 and latest

#### Describe the bug
Studio opens both DS when they're set up for search

#### To Reproduce
1. Create a site based on Editorial
2. Go to the `Page - Home` content type, and on the `Shared Features` content type, uncheck `Enable Create New`, uncheck `Enable Browse Existing` and check `Enable Search Existing`.
3. Create a copy of the DS but call it `Shared Features 2`, with the same properties except the paths point to `/site/components/features2`.
4. Make sure the `Features` field uses the `Shared Features 2` DS too.
5. Open the Home page for edit and click on the `Add` button of `Features`

You should see that instead of the little menu allowing you to choose the DS, both DS popups open up at the same time.

**Comment by avasquez614** [comment]
A fix has been tested in 3.1.x and seems to work, but there might be a better place to do the fix. The fix consist of replacing the code at this line: https://github.com/avasquez614/studio-ui/blob/support/3.1.x/static-assets/components/cstudio-forms/data-sources/shared-content.js#L176, with the following:

```
    if (this.browsePath) {
      var path = _self.processPathsForMacros(this.browsePath)
      searchContext.path = path.endsWith('/') ? `${path}.+` : `${path}/.+`;
      searchContext.externalPath = true;
    }
```

**Comment by avasquez614** [comment]
Verified in 3.1.x

**Comment by avasquez614** [comment]
@jvega190 this needs to be done in 4. After that, assign to @yacdaniel

**Comment by yacdaniel** [comment]
Verified fixed.
