### ISSUE TITLE
[studio-ui] RTE dialogs - data source issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5064]
#### Crafter CMS Version
```
Studio Version Number: 4.0.0-SNAPSHOT-7c6989
Build Number: 7c69897050e62b929364876f4f1cb0e6f9c191bc
Build  Date: 11/2/2021, 2:39 PM
```
#### Describe the bug
* The RTE is missing the save/close buttons when RTE menu bar options are open.
* In Preview, the data source picker is not visible for inserting Images, Link and Media
* RTE insert Link with `Upload from Desktop` data source not working

#### To Reproduce
1. Create a site from Empty
2. Setup the Image, Video, and File data sources for the RTE
3. Play with the menu options in Form Engine and Preview.

#### Logs
N/A

#### Screenshots
3.1
![image](https://user-images.githubusercontent.com/6722074/140072803-3de7072e-4491-4662-9fe0-e52ff2198f85.png)
4.0 - Missing Save - Close button
![image](https://user-images.githubusercontent.com/6722074/140083565-bba2fc79-db53-4598-8adf-706bbcd58ae5.png)

https://user-images.githubusercontent.com/6722074/140084061-723c4bb5-63a6-4478-83e6-5f6ee9b02987.mp4

https://user-images.githubusercontent.com/6722074/140084654-d88d866d-aabe-41b3-907e-79abb8d8f9f4.mp4

**Comment by yacdaniel** [comment]
Hi @jvega190 
The data source pick options is missing in Preview.
Form Engine
![image](https://user-images.githubusercontent.com/6722074/140764076-ad794a5b-3630-4d28-844a-d527f4d30435.png)

**Comment by jvega190** [comment]
Hi @yacdaniel, right now there's no support for datasources interactions from preview, so it's disabled.

**Comment by yacdaniel** [comment]
Thanks @jvega190 
@sumerjabri should I open a feature request for tracking this data source interactions from Preview?

**Comment by sumerjabri** [comment]
@rart we also need to support the video pickers (called Insert Media inside TinyMCE) in the same way.

Decision:
* Support image upload/select
* Support video upload/select

Both are support as we discussed.

**Comment by rart** [comment]
Latest discussion on data source support is that it will be limited to the following:

- image from repo:
  - [ ] highlight only image fields that have image from  repo when dragging from assets panel
- image from desktop:
  - [ ] highlight only image fields that support upload when dragging from desktop
  - [ ] use repository path to upload
    - [ ] parse path expressions

@jvega190 read data sources when parsing xml (i.e. `parseLegacyFormDefinitionFields`) and...
- [ ] add to ContentTypeField.validations.{ id: imagesFromRepo value: boolean }
- [ ] add to ContentTypeField.validations.{ id: updloadImages, value: uploadPath }

**Comment by sumerjabri** [comment]
@yacdaniel please assign to Russ once you're done with validation.

**Comment by yacdaniel** [comment]
looks good to me, please give it a try @russdanner

**Comment by russdanner** [comment]
Confirmed
