### ISSUE TITLE
[studio-ui] Site Dashboard stuck in processing when a scheduled publish is published in GMT Timezone

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5065]
## Describe the bug
When scheduling a publish in Studio when it is configured to be in GMT timezone and a scheduled publish is completed, the Site Dashboard gets stuck in processing. 

## To Reproduce
1. Modify your systems clock to be running in the GMT Timezone.
2. Create a site based on Editorial
3. Navigate to Site Config --> Configuration --> Site Configuration
4. Modify the Default Timezone to be `<default-timezone>GMT</default-timezone>`
5. Navigate back to the Site Dashboard. 
6. Make an edit to the home page
7. Approve & Publish the change, and schedule it to be published as soon as possible in the dialogue.
8. Wait until the Scheduled Published time and then refresh the site dashboard.
9. Notice the endless spinning

## Expected behavior
The spinning refresh should not be endlessly running in the site dashboard once a publish has been run.

## Screenshots
![image](https://user-images.githubusercontent.com/42217570/124145046-792f8000-da5a-11eb-89e1-664010e5dd5f.png)
![image](https://user-images.githubusercontent.com/42217570/124145111-8482ab80-da5a-11eb-93f6-04edc13648fb.png)

## Logs
N/A

### Version
Studio Version Number: 3.1.x

### OS
Any

### Browser
Any

## Additional context
Refer issue https://github.com/craftercms/craftercms/issues/4809
This happens because the time format is `2021-11-03Z`. That cause the parser does not work properly

**Comment by rart** [comment]
@jvega190 pls port to next

**Comment by jvega190** [comment]
@rart not an issue in next, should I move to complete in 4?

**Comment by jvega190** [comment]
@rart should I assign Phil or Yac for 4.0 validation?

**Comment by yacdaniel** [comment]
Verified fixed.
