### ISSUE TITLE
[studio-ui] Make dropTargets browse behave like the shared-content datasource

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5067]
#### Crafter CMS Version
4.0.0-SNAPSHOT-456e92

#### Describe the bug
Shared-content datasource has a `browsePath` that is used as the path that opens when browsing the content, but in dropTargets it adds an extra part to the path that may cause problems when accessing custom paths in the tree.

#### To Reproduce
1. Go Site explorer and create a folder `extraFeatures` under `/components`
2. Go to content-types editor - Home and add a node selector + dropTarget with `baseBrowsePath: /components/extraFeatures` and selecte `features` as the content-type for the dropTarget.
3. Edit home and browse in the added node-selector
4. See that an extra part is added to the browse path.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation, thanks!

**Comment by yacdaniel** [comment]
Verified fixed.

Before fix:
![image](https://user-images.githubusercontent.com/6722074/141322140-8c19dfb4-6fe7-4c80-bd5a-2b62e9e544a7.png)
Now:
![image](https://user-images.githubusercontent.com/6722074/141322191-d8bd4d90-b50e-43e4-b7dd-e3d3dc2c83ed.png)
