### ISSUE TITLE
[studio-ui] Use new reactified BrowseFilesDialog in shared-content/dropTarget

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5068]
### Feature Request

We have a new BrowseFilesDialog that replaces the old browse dialog used in shared-content and dropTarget datasources. Update them to use the new reactified component.

#### Is your feature request related to a problem? Please describe.
{{A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]}}

#### Describe the solution you'd like
{{A clear and concise description of what you want to happen.}}

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation, thanks!

**Comment by yacdaniel** [comment]
Hi @jvega190, could you please check the case when a `Shared Content` data source with both Repository and Browse repo paths are set to a non existing location, the Browse dialog shows like
 
![image](https://user-images.githubusercontent.com/6722074/142008635-af528af7-3da6-49c7-90f2-dd0740c8fc8e.png)

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/142932484-795bb00c-f3dd-4c4d-8aec-4f6f2d9e6f77.png)
