### ISSUE TITLE
[studio-ui] Add tooling around previewing REST scripts

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5070]
#### Is your feature request related to a problem? Please describe.
Developers want a quick and efficient way to test & preview their REST scripts.

#### Describe the solution you'd like
- Create a script runner dialog. Clicking on a REST script on the sidebar would open the dialog to preview.
- Out of habit, people may type a TEST script URL on the Preview address bar, make the address bar smart to open the script preview dialog.

**Comment by sumerjabri** [comment]
This can be a community plugin contribution.
