### ISSUE TITLE
[studio-ui] Remove error graphic from PathNavigator path not found case

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5072]
#### Is your feature request related to a problem? Please describe.
When upgrading to 4, many sites won't have the taxonomy folder and, though accurate and handled, the initial perception of having a broken sidebar is undesirable.

#### Describe the solution you'd like
Remove the error graphic from the "path not found" error message when the path doesn't exist on PathNav and PathNavTree.

#### Describe alternatives you've considered
Leave as is.

**Comment by sumerjabri** [comment]
Verified.
