### ISSUE TITLE
[studio-ui] Publishing Dashboard > Publish On Demand widget preselect publishing target if just one is available

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5073]
#### Is your feature request related to a problem? Please describe.
When there's a single option on the publishing target drop down the publish on the demand widget it's a bit pointless to force users into a selection when the selection-to-be is obvious.

#### Describe the solution you'd like
Pre-select the only available option.

#### Describe alternatives you've considered
Make it behave like the publishing dialog where `staging` is always pre-selected when both targets are present and select the only available target when only 1 is available.

**Comment by sumerjabri** [comment]
Verified.
