### ISSUE TITLE
[studio-ui] Remember user-preference for save button sub-action (close, mimize, etc)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5075]
#### Is your feature request related to a problem? Please describe.
It is desirable for the system to remember the choice of save button used.

#### Describe the solution you'd like
When selecting any of the save button variants, store a local storage item to remember the preference.

#### Describe alternatives you've considered
- Remember for all dialogs 
  - Makes sense for common actions and makes the system consistent and predictable
- Remember per dialog 
  - Some dialogs may not share the exact set of actions
  - Different behaviours might be desired on different task contexts

**Comment by rart** [comment]
@jvega190 

- Create a MultiChoiceSaveButton
  - Internally it uses SplitButton
  - This component should contain all the common save options and use props to turn them on/off
    - The `options` prop would be of type `Array<CommonSaveOptions | SplitButtonOption>`
      - By default, it has all the options
      - `type CommonSaveOptions = 'save' | 'saveAndClose' | etc...`
    -  The new button receives a single click handler of type `(e: event, type: CommonSaveOptions | T) => void`
      - e.g. `<MultiChoiceSaveButton onClick={(e, type) => ...} />` would have only but "save and save & close" options.
    - Also add a `additionalOptions` optional prop
- Move the preference storing/retrieving to SplitButton
  - The split button should have a `storageKey` prop which it checks to retrieve when it mounts and store when it changes. If no storage key is present, the button works without any storage (should not save to local storage).
  - Add `id` to `SplitButtonProps['options']` and use this as the selected option driver
  - `defaultSelected` too becomes of type string and it's default value would be `options[0].id`
  - If retrieving a storageKey produces a key that's not present on the option set, the key should be removed and fallback to `options[0]`.
  - Partition it all into SplitButton & SplitButtonUI
    - All logic and state goes to SplitButton
- Find any usages of SplitButton on the LegacyCode to make sure the new component is used with it's rightful options

**Comment by rart** [comment]
@aachavarria please validate & close if all good

**Comment by aachavarria** [comment]
verified
