### ISSUE TITLE
[studio] Capture publishing date/time user-intent in audit log

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5076]
#### Is your feature request related to a problem? Please describe.
When publishing, the user selects a date, time and timezone to publish. On the back, when this information is received it is stored in the back's timezone and the user-intent is lost. Though the publish date/time moment is stored correctly, we can't ever display back to users the exact date/time/zone as it was entered by the submitter.

#### Describe the solution you'd like
Capture this information at least on the audit log

#### Describe alternatives you've considered
Capture it all so the UI can show the information on the publish dialog and other relevant places.

**Comment by sumerjabri** [comment]
Won't pursue, the user's timezone is set and can be used to display the logs/audit in that timezone if required. The server will only store UTC.
