### ISSUE TITLE
[studio-ui] UI display issues

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5078]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-456e92

Build Number:
456e925a47b7c70116e813b0554aea82f6ee7996

Build Date:
11/4/2021, 8:06 AM

#### Describe the bug
- [x] Site name is not displayed in Navigation Menu 
- [x] Image upload text is cutoff
- [x] Social media links on header has large spaces in between when browser width is narrow

#### To Reproduce
1. Create a site using the website editorial blueprint.  Click on the `Navigation Menu` icon on the top right
2. Notice the site name is not displayed
<img width="1052" alt="Screen Shot 2021-11-04 at 2 41 58 PM" src="https://user-images.githubusercontent.com/25483966/140501995-e7ba19c7-9756-4eaf-a24b-070c8818fd6c.png">

3. Edit the `Home` page.  Scroll down to the Hero section
4. Click on the `Replace` button for the Hero Image
5. Depending on the width of your browser, the text is cutoff 

<img width="1048" alt="Screen Shot 2021-11-05 at 7 16 35 AM" src="https://user-images.githubusercontent.com/25483966/140503006-586a6734-8ef0-42b2-8547-bfba7e375943.png">

6. Notice the same cutoff text depending on browser width when replacing an image accessed via the ICE pencil, click on the image, then select `Edit`
 
<img width="1054" alt="Screen Shot 2021-11-05 at 7 16 00 AM" src="https://user-images.githubusercontent.com/25483966/140503328-3e5cec2d-76e8-4547-9367-8b531fce9179.png">

7. Depending on the width of your browser, the social media links has large spacing in between vertically
 
<img width="1203" alt="Screen Shot 2021-11-05 at 7 26 53 AM" src="https://user-images.githubusercontent.com/25483966/140504491-1142f734-a00e-4c13-86e8-b60cb9efa6c8.png">

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by rart** [comment]
Social media links on editorial issue relates to craftercms/craftercms/5078

**Comment by alhambrav** [comment]
Verified fixed.
