### ISSUE TITLE
[studio] [studio-ui] Studio search breaks when updating the search term while in a > 1 page

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5082]
#### Crafter CMS Version
3.1.15 and latest 3.1.18 build

#### Date of Build
11/08/2021

#### Describe the bug
Studio search breaks when updating the search term while in a > 1 page: no results are shown and in some instances the page becomes unresponsive.

#### To Reproduce
1. Create a site based on Editorial
2. Click on the magnifying glass to go to Studio search
3. Pick the last page in the results
4. Enter diet in the search terms

You'll notice that the UI says that there are 3 search results but none is displayed. In some client repos the page becomes unresponsive too.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/140815967-a71c6f50-19c9-4542-a6ca-a468e0e07301.png)

**Comment by avasquez614** [comment]
Verified in 3.1.x. @yacdaniel please help with verification in 4.

**Comment by yacdaniel** [comment]
Verified fixed in 4.0.x
