### ISSUE TITLE
[studio-ui] When making an edit using ICE, the timezone field of a date field is removed

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5083]
#### Crafter CMS Version
3.1.15 and latest 3.1.18 build

#### Date of Build
11/8/2021

#### Describe the bug
When making an edit using ICE, the timezone field of a date field is removed

#### To Reproduce
1. Create a site based on Editorial
2. Open the `article.ftl` filed and on line 36 (after the author), add the following line to output the timezone: `<h3>TZ: ${contentModel.date_dt_tz}</h3>`.
3. Open any article page from the sidebar and immediately save.
4. Preview the page. You should notice the `EST5EDT` timezone being shown.
5. Click on the pencil icon on the top bar to enable ICE. Then click on the pencil to edit the title. Click on save.

You should notice a `Show error` on the page and an exception in the logs saying the `date_dt_tz` field is null. You can fix the error by saving the entire page.

**Comment by rart** [comment]
@jvega190 

- add a method on the controls that have dynamic fields called `getAdditionalFields`
- on the content type editor, call that new method before saving
- store the additional fields as part of the `<field />` element definition in the content type xml.

For example:
```
<field>
    <type>checkbox</type>
    <id>flush_b</id>
    <title>Flush</title>
    ...
    <additionalFields>
      <id>additionalFieldIdThatTheControlCreates</id>
    </additionalFields>
</field>
```

**Comment by avasquez614** [comment]
Verified in 3.1.x

**Comment by Euquimides** [comment]
Hi! I updated and verified the issue also in version `4.0.0-SNAPSHOT-791897`
![date_error_ICE](https://user-images.githubusercontent.com/90878288/151221056-43450c26-f45b-4039-bc5b-e85742231981.PNG)

**Comment by Euquimides** [comment]
Hi! I rechecked, this is not an error per se. This issue appears if the content is not updated correctly or if a null check is not added. If it is updated, the issue is fixed.
