### ISSUE TITLE
[studio-ui] Long timezones get cut in the form UI

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5084]
#### Crafter CMS Version
Latest build of 3.1.18

#### Date of Build
11/08/2021

#### Describe the bug
Long but valid timezones (like `America/Los_Angeles`) get cut in the form UI.

#### To Reproduce
1. Create a site based on Editorial
2. Go to Site Configuration > Configuration and open Site Configuration
3. Change the `default-timezone` to `America/Los_Angeles`
4. Open the Page - Article content type
5. Add a new date field called `Date 2`. Make sure you have the `Show Time` checkbox selected
6. Open an Article page and Save and Close
7. Open a the page again,

You should notice the timezone being cut and just showing `Ame`.

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/140824239-fdbe8ef9-db29-4287-9347-cd8f65f42a49.png)

**Comment by avasquez614** [comment]
Verified in 3.1.x. @yacdaniel please help me verify it in 4.

**Comment by yacdaniel** [comment]
Verified fixed in 4.0 Issues found are reported here https://github.com/craftercms/craftercms/issues/5104
