### ISSUE TITLE
[studio-ui] Clicking through to a plugin/widget doesn't work in Expreience Builder when pressing `z`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5085]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021-11-08

#### Describe the bug
While in edit and working with a plugin like the YouTube plugin, pressing `z` to click-through to play the video doesn't work.

#### To Reproduce
1. Install the YouTube plugin
2. Drag it onto a page
3. Press `z` and try to click the video to play it

#### Logs
N/A

#### Screenshots
N/A

**Comment by rart** [comment]
I believe it was necessary to overlay the iframe with a div to be able to display XB menus and capture clicks. The bug is on the plugin side. @jvega190 please listen for the z key on the plugin (when in preview and ice mode) to hide the overlay.
