### ISSUE TITLE
[studio] Update the plugins system configuration management

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5086]
#### Is your feature request related to a problem? Please describe.
Plugins require configuration and it needs to be uniform, isolated, and as automated as possible.

#### Describe the solution you'd like
Configuration placeholders must be placed during installs, and allow for future addition of capture during install to configure the plugin during installation.
Additionally, the configuration must be isolated and uniform, consider this structure:
```
<plugins>
<plugin>
<id>
<config>
... custom area for the plugin ...
</config>
</plugin>
</plugins>
```

We may also consider limiting which files get modified depending on the purpose of the plugin (think delivery/engine plugins for now).

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by jdrossl** [comment]
@rart as part of this ticket the install plugin dialog needs to support parameters just like the create site, ping me for details on how to test it

**Comment by jdrossl** [comment]
@rart and there is also a new API for getting/writing the plugin configuration, it needs to be added in the plugin dialog as well
