### ISSUE TITLE
[studio-ui] Change the Content Type Preview Image mechanics

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#509]
Please allow the user to set/change a content type's preview image in the property editor of the content type.

Add a property to the base property sheet to allow the user to upload or select an image, make the user crop the image using our JS cropper, and save the image in the content type as "image.png"

Please check and see how the system loads the image, and adjust to make it work against the new "image.png" approach. Ping me for any backend work required to make this happen.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/277

**Comment by sumerjabri** [comment]
Please make it such that the cropper is invoked if either height or width is larger than expected.
Please make the text of the image name gray and readonly.
Please accept images that are smaller in size to your current minimum.

**Comment by vestrada** [comment]
Done
