### ISSUE TITLE
Add an option to file-name form control to enable edit without warning

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5090]
### Feature Request

Add an option to file-name form control to enable edit without showing the button and a warning popup.

#### Describe the solution you'd like

* "Allow Edit Without Warning" property
* Default: false (uncheck)

If the option is checked, the author will be able to edit file-name field without extra action to click the "Edit" button and "OK" on showing the warning.

![2021-11-10_09-57](https://user-images.githubusercontent.com/2996543/141041758-19d51fae-9241-4725-987a-d4d72f4ae93b.png)

**Comment by rart** [comment]
@russdanner @sumerjabri please confirm this feature.

**Comment by sumerjabri** [comment]
Feature confirmed.

**Comment by avasquez614** [comment]
Verified in 3.1.18. @yacdaniel please help verify in 4

**Comment by yacdaniel** [comment]
Verified fixed in 4.0
`Allow Edit Without Warning` set to `true`
![image](https://user-images.githubusercontent.com/6722074/148115105-febfe9c3-718e-427d-a9c1-b0f05b0f57f3.png)
`Allow Edit Without Warning` set to `false`
![image](https://user-images.githubusercontent.com/6722074/148115207-f0a75c6d-fd03-45e4-812c-7f8a87c187b1.png)

**Comment by yacdaniel** [comment]
@rart with Studio Dark Theme, the file-name control doesn't render with right colors in the form engine when  is unchecked(Default)

![image](https://user-images.githubusercontent.com/6722074/148116402-4956217d-eb93-4e27-96c5-bcd648c4c1ae.png)
Content types with the `Allow Edit Without Warning` checked are ok
![image](https://user-images.githubusercontent.com/6722074/148116517-9b81413a-a827-452f-838f-bb5b891695ba.png)

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/148288268-c85c495a-b3d2-48ae-935c-0be312292287.png)
