### ISSUE TITLE
[studio] Disable duplication of Home(/) page

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5091]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-84bdd0`
#### Date of Build
`11/8/2021, 8:24 AM`
#### Describe the bug
The option to `Duplicate` the `Home /` page of a site should be removed from all roles. 
#### To Reproduce
1. Create a site from Editorial
2. Click Sidebar options for `Home` item

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/6722074/141155693-20a353b0-f839-4468-bc27-5d63a60635ba.png)

**Comment by sumerjabri** [comment]
Remove Duplicate from AA for the root item.

**Comment by dejan-brkic** [comment]
BE fixed. It seems UI does not remove Duplicate action from menu although it is not AA

PR:
https://github.com/craftercms/studio/pull/2799

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2807

**Comment by aachavarria** [comment]
After doing testing looks like the issue was not BE. The Ticket was assigned to Yac for verification

**Comment by yacdaniel** [comment]
Verified fixed in 4.0
