### ISSUE TITLE
[studio] Publisher stops if any single item in package does not exist in blob store

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5099]
#### Crafter CMS Version
3.1.16E

#### Date of Build
Studio Version Number: 3.1.16E-20a403
Build Number: 20a40312300dddcb3b6d1394be3e149a3810eba3
Build Date/Time: 07-12-2021 19:22:02 -0400

#### Describe the bug
If a publishing package contains one or more reference(s) to an item that should exist but that does not exist in the blob store the publisher disables itself and blocks publishing.

- The user does not know what the publisher failed on or how to correct the issue The package could be very large and there is no indication of what failed.

- An issue with a single object/asset (assets are typically managed via blob store) are not typically worth blocking a publishing operation (and all future publishing)

#### To Reproduce
1. Create a site with a blob store
2. Add an image shadow file (pointer) directly to git inside the path mapped to the blob store
3. Publish multiple files including the image from step 2
4. See that the publisher disables 

#### Screenshots
N/A

**Comment by dejan-brkic** [comment]
The issue does not exist in the 4.0 branch.

Done
3.1.x:
https://github.com/craftercms/studio/pull/2798

**Comment by russdanner** [comment]
Confirmed
