### ISSUE TITLE
[studio-ui] Allow users to edit 'config.xml' for a content type

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#510]
Please add a property to the base property sheet for content types where the user will see a read-only path to 'config.xml' and a pencil for the user to edit this file.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/265

**Comment by sumerjabri** [comment]
config.xml field must be read-only as the user can't change that.

**Comment by jvega-crafter** [comment]
Input field changed to read-only 
https://github.com/craftercms/studio2-ui/pull/266
