### ISSUE TITLE
[studio-ui] Dashboard displays items as published to "staging" instead of "live"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5100]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-92f74e

Build Number:
92f74ef12c65d33525900eec9f4559ce026c5c9b

#### Date of Build
Build Date:
11/16/2021, 1:07 PM

#### Describe the bug
Dashboard displays items as published to `staging` instead of `live` even though `staging` is not configured and there is no option to publish to `staging` 

#### To Reproduce
1. From a fresh clone of Crafter CMS, create a site using website editorial
2. Publish the whole site to `live`
3. Open the Dashboard and scroll to the `Recently Published` dashlet
4. Notice all the items are published to `staging`

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}
<img width="1161" alt="Screen Shot 2021-11-16 at 11 45 38 AM" src="https://user-images.githubusercontent.com/25483966/142201422-c733e734-b8b0-4c17-b1d9-2598387a7c79.png">

**Comment by aachavarria** [comment]
Looks like the api /studio/api/2/publish/history.json is returning the items with submittedToEnvironment === null
 @dejan-brkic  Can you please check this?

**Comment by dejan-brkic** [comment]
@aachavarria This v2 API but response object is still API v1 format. That means you are checking the wrong property. Properties that show correct environment per dashboard are follwing:
Items waiting for approval -> `submittedToEnvironment`
Approved Scheduled items -> `environment`
Recently published -> `endpoint`

**Comment by sumerjabri** [comment]
The API will issue will be fixed with the new dashboard in the next iteration.

**Comment by alhambrav** [comment]
Verified fixed.
