### ISSUE TITLE
[studio-ui] Create site failure isn't handled properly

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#511]
Stop the search engine or the preview deployer to cause the failure.
Create a site.
Site creation will fail and the UI will show a 500 with little useful information. We need to change that experience to show the user an error message like:
"Site creation failed, please review the logs to address the issue."

**Comment by sumerjabri** [comment]
To reproduce:
After the system starts:

1. on the command line: kill `pgrep -f solr` <== this kills solr
2. now create a new site

You'll see the unstyled 500 error page.

**Comment by vestrada** [comment]
Studio - Master - Pull Request: https://github.com/craftercms/studio/pull/590

Studio-ui - Master  - Pull Request: https://github.com/craftercms/studio2-ui/pull/300

**Comment by vestrada** [comment]
Hi @sumerjabri ,

UI is done. Back end still needs to fix the create site service.
Although the service is failing always receives a code of status "200".
Please let me know everything is good. 

Thanks

**Comment by sumerjabri** [comment]
Please update the way to call the API to create site to conform with the API definition here:
http://docs.craftercms.org/en/latest/developers/projects/studio/api/site/create-site.html

That will get you the correct results back.

Also, please update the Create Site UI to request Site ID, Site Description and the Blueprint and get rid of "Site Name."

Please make Site Description optional.

Please note the new API is not implemented yet, we're working on it, see: https://github.com/craftercms/craftercms/issues/625

Ping if you have questions.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/302

studio - Master - PR: https://github.com/craftercms/studio/pull/598

**Comment by vestrada** [comment]
Above changes are done:
- The API is updated.
- The Create Site UI is updated.
- Site Description is optional.

@sumerjabri The Api stills getting 201 code although solr is down and the sites are not being created.

**Comment by sumerjabri** [comment]
@vestrada you're using the wrong API call, please use this one: http://docs.craftercms.org/en/latest/developers/projects/studio/api/site/create-site.html

You'll note the URL is different. We will delete the old call so it will break if someone uses the old API call.

**Comment by vestrada** [comment]
UI is using the correct API.

**Comment by sumerjabri** [comment]
Updated the API to return 500 with an exception.

When trying with the new API, I now see this:
![screen shot 2017-03-27 at 8 58 22 pm](https://cloud.githubusercontent.com/assets/3931908/24384200/1755fa9e-1330-11e7-853b-9da55e63728c.png)

This dialog can't be closed.

Let's change the dialog to say:
"Unable to create site. Please contact your system administrator.

Error: {EXCEPTION GOES HERE}"

Please change the button from `Cancel` to `Close` and make sure the dialog closes.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/321
