### ISSUE TITLE
[docs] Document how to use Crafter with WSL2

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5112]
#### Is your feature request related to a problem? Please describe.
Docker performance in Windows is not the best. WSL2 seems like a really good alternative to use Crafter in Windows

#### Describe the solution you'd like
Document how to use Crafter in WSL2:

- How to run the bundle
  - Point to MS docs on how to install WSL2
  - Document how to run the bundle with WSL2
- How to setup system for building CrafterCMS with WSL2
  - Point to MS docs on how to install WSL2
  - Document how to install the pre-requisites like git and Java
  - Document how to build CrafterCMS with WSL2

**Comment by sumerjabri** [comment]
@alhambrav please ping me to discuss the scope of this ticket.

**Comment by sumerjabri** [comment]
@alhambrav is this done and ready for validation?

**Comment by alhambrav** [comment]
Yes. Will move to validate.  Thanks!

**Comment by avasquez614** [comment]
Verified
