### ISSUE TITLE
[engine] Incorrect  HTTP GET request while using previewing proxy

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5116]
#### Crafter CMS Version
3.1.x

#### Date of Build
November 29, 2021

#### Describe the bug
While using preview proxy to another web application, the HTTP GET request is incorrect if the path has special characters %5B, %5D

#### To Reproduce
1. Create a site from any blueprint. Ex: Editorial
2. Configure proxy as follows:

```
      <server>
         <id>preview</id>
         <url>http://localhost:3000</url>
         <patterns>
            <pattern>.*</pattern>
         </patterns>
      </server>
```

3. Run another web application in port 3000 (local). Ex: https://www.npmjs.com/package/http-server
4. Open site in preview mode for site in step 1
5. Access URLs such as http://localhost:8080/abc/%5D/xyz
6. Using Wireshark or any HTTP requests capture to catch the above request
7. Notice that the request to localhost:3000 is:

```
GET http://localhost:3000/abc/]/xyz
host: localhost:3000
```

Expected request:

```
GET /abc/%5D/xyz
host: localhost:3000
```

#### Screenshots
![proxy_get_request](https://user-images.githubusercontent.com/2996543/143819385-9df9bdb9-f488-43df-b312-06b447f216fd.png)

#### Reference

This may due to the following issue: https://github.com/mitre/HTTP-Proxy-Servlet/issues/215

**Comment by sumerjabri** [comment]
Will consider forking the library and carrying our own version.

**Comment by sumerjabri** [comment]
Upgraded v4 as well. All ready for testing.

**Comment by phuongnq** [comment]
verified
