### ISSUE TITLE
[studio] Inject Site ID into REST scripts executed by the Studio plugin system

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5120]
#### Is your feature request related to a problem? Please describe.
Site ID is a common value that is required to acquire site-specific configuration and execute common Studio services. Plugin-based APIs should have easy access to the Site ID of the site they are executing within.

#### Describe the solution you'd like
Groovy-based REST controllers in Studio plugins should be able to easily access/determine the site they are running in.

#### Describe alternatives you've considered
Pass the site ID in on the URL

**Comment by sumerjabri** [comment]
@russdanner Something to think about: What do we do for global plugins? We have a global site ID to inject there as well. Must make sure we do that.

**Comment by russdanner** [comment]
Confirmed
