### ISSUE TITLE
[studio-ui] Site Explorer: pagination is not working.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5131]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-306178`
#### Date of Build
`12/1/2021, 5:26 PM`
#### Describe the bug
The pagination for items in Site Explorer is not working, the number per page selector shows but when the number is selected there aren't changes to items displayed. 
#### To Reproduce
1. Create a site from Editorial
2. Expan `Static Assets -> Images`
3. Change the pagination number to 25 items.  
4. Pagination is not applied. 

#### Logs
N/A
#### Screenshot
![Screenshot from 2021-12-06 08-55-18](https://user-images.githubusercontent.com/6722074/144869130-461acc58-6737-40ae-b827-ac517c68dd0c.png)

**Comment by yacdaniel** [comment]
Verified fixed.

**Comment by yacdaniel** [comment]
@aachavarria this issue happens in top item explorer
![image](https://user-images.githubusercontent.com/6722074/147610822-3914cbcf-da53-41bd-a79c-b05fd212f9f8.png)
Also in most of the dialogs where the user can chose from item explorer
History
![image](https://user-images.githubusercontent.com/6722074/147610838-e8345b2c-f980-474d-90d2-9c8ab36661d4.png)
New Folder
![image](https://user-images.githubusercontent.com/6722074/147610874-107b1303-330f-489f-b6c9-20cef5f1e7a8.png)
Dependencies
![image](https://user-images.githubusercontent.com/6722074/147610891-73237225-0b39-4f51-a7c8-81905c96747b.png)
Change Content Type
![image](https://user-images.githubusercontent.com/6722074/147610920-37b9bf6b-eb94-4877-8271-35b024b22e8d.png)
Create Content
![image](https://user-images.githubusercontent.com/6722074/147610978-ec0739d7-ddd9-42aa-aa28-19050d48aa33.png)

**Comment by yacdaniel** [comment]
@Euquimides please help us with a verification of this.

**Comment by Euquimides** [comment]
Hi @yacdaniel and @aachavarria! Pagination is working correctly except for the section Site Tools/Audit that still presents the issue (Rows per page doesnt' refresh, stays always at 10). 

Rows per page at 5:
![crafter-audit_pagination5](https://user-images.githubusercontent.com/90878288/148117894-7d9adf9d-d607-4969-ad37-07de2484e0de.PNG)
Rows per page at 15:
![crafter-audit_pagination15](https://user-images.githubusercontent.com/90878288/148118089-7c7c8617-5b6c-4b50-b368-1aa4bc704647.PNG)
.

**Comment by Euquimides** [comment]
Hi @yacdaniel and @aachavarria! I updated and re-checked the issue, pagination in audit is now working fine. Thank you!
