### ISSUE TITLE
[craftercms] Fix the crafter bundle folder name

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5132]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-306178`
#### Date of Build
`12/1/2021, 5:26 PM`

#### Describe the bug
Bundles should have a root folder called `crafter` instead of `crafter-$env` 
#### To Reproduce
1. `gradlew build deploy bundle`
2. Untar the bundle

#### Logs
N/A

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
Fixed by: https://github.com/craftercms/craftercms/commit/ef5fe5157b259612b68fb064fadd98e13ac4b270

**Comment by yacdaniel** [comment]
Verified fixed.
![image](https://user-images.githubusercontent.com/6722074/145062479-df277975-d868-4a49-a6d2-7a8e58245ff2.png)
