### ISSUE TITLE
[studio-ui] Workflow Jobs Screen contains some text in Spanish

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#514]
Open the Admin Console on a Site in Studio, then select 'Workflow Jobs'
Notice the 4th and 5th columns are displaying text in Spanish, instead of English:

Fecha de 
Creación

and

Fecha de 
Modificación

![workflowjobssometextinspanish](https://cloud.githubusercontent.com/assets/25483966/23566489/13fb3d1e-0020-11e7-89d2-6aaec659e7cb.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/289

**Comment by vestrada** [comment]
Done
