### ISSUE TITLE
[studio-ui] Undefined imageThumbnail showing in form definition when creating content-types

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5140]
#### Crafter CMS Version
v4.0.0-SNAPSHOT

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
When creating a new content-type, the form-definition.xml has `undefined` in imageThumbnail

#### To Reproduce
1. Create an editorial based site.
2. Go to Site Tools - Content Types
3. Create a new Type (page or component) and save.
4. When created, go to the new type's form-definition.xml file (/config/studio/content-types/...) and see `<imageThumbnail>undefined</imageThumbnail>`

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by yacdaniel** [comment]
Verified fixed.
