### ISSUE TITLE
Add a publishing report for each publishing queue activity

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5148]
#### Is your feature request related to a problem? Please describe.
Authors and administrators would like to be able to see a report of what happened to a package when it was processed in the publishing queue.

#### Describe the solution you'd like
- For each package processed in the publish queue provide a report that indicates for each item in the publishing package any relevant status or errors that occurred while processing it.

- Report should also provide an overall status (m of n items processed successfully/without error)

- Ideally, users could view this report any publishing queue related dashboard/console

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
This will be addressed by the new publisher in 4.2.
