### ISSUE TITLE
[studio] Rename database column `owned_by` to `locked_by`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5152]
#### Is your feature request related to a problem? Please describe.
The column is to hold the lock owner, not the item owner. The name of the column is misleading.

#### Describe the solution you'd like
Please rename the column.

#### Describe alternatives you've considered
Stay with the old name.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2800
