### ISSUE TITLE
[studio] API 2 content/sandbox_items_by_* should return 404 content not found when path doesn't exist

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5156]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-c6d6fb`
#### Date of Build
`12/10/2021, 9:32 AM`
#### Describe the bug
The API 2 `content/sandbox_items_by_path` and `content/sandbox_items_by_id` should return the 404 content not found response schema, like  
```
HTTP 404
{
    "response": {
        "code": 7000,
        "message": "Content not found",
        "remedialAction": "Check that path 'adipisicing pariatur cupidatat in' is correct and it exists in site 'ed123'",
        "documentationUrl": ""
    }
```
#### To Reproduce
1. Create a site from any BP
2. Call `content/sandbox_items_by_path` with a non existing path and `content/sandbox_items_by_id` with a non existing id. 
3. See that response comes with empty results. 
```
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "items": []
}
```
#### Logs
N/A
#### Screenshots
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2801

**Comment by yacdaniel** [comment]
Verified fixed.
