### ISSUE TITLE
[studio-ui] Edit Template/Controllers when no template is defined in content type. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5157]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-c6d6fb`
#### Date of Build
`12/10/2021, 9:32 AM`

#### Describe the bug
When selecting the item options `Edit Template` or `Edit Controller` and the templates/controller doesn't exist, the UI shows the message `Unable to verify affected workflows please try again momentary` because the path doesn't exist. 

#### To Reproduce
1. Create a site from any BP
2. Click the option `Edit Controller` for an article page.
3. See the error

#### Logs
N/A
#### Screenshots
![image](https://user-images.githubusercontent.com/6722074/145621796-7a1a38b4-40ec-4bd6-8447-9ef96793233c.png)

#### Solution/Task
We should show a user a warning that the template/controller doesn't exist and offer the user to create a new one if they'd like

- [ ] Design dialog
- [ ] Implement
- [ ] Test
- [ ] Update docs

**Comment by aachavarria** [comment]
The edit case was already fixed on my last PR, I found a issue when Delete controller and Delete template, working on fixing this

**Comment by yacdaniel** [comment]
@Euquimides please help with the verification on this one.

**Comment by Euquimides** [comment]
Hi @yac and @aachavarria. I re-checked the issue. A new empty editor shows up when clicking the option `Edit Controller` after deleting a controller (controller does not exist); but, this doesn't happen with template. If template is deleted (does not exist) and `Edit Template` is clicked, the UI shows the next error: `Unauthorized. You don't have permission to perform this task, please contact your administrator.` 
According to @rart comment, a new empy editor should show up in both cases.
![error2001_edittemplate](https://user-images.githubusercontent.com/90878288/148858061-e6f9933b-cc0a-46a0-b59d-1dbeb861cf1d.PNG)

**Comment by Euquimides** [comment]
Hi @aachavarria! I updated and re-checked the issue. The Edit Template/Controllers error is fixed. Thank you! I'm closing this ticket.
