### ISSUE TITLE
[studio] LDAP integration

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#516]
please allow crafter studio to authenticate users against LDAP.

ping me to design.

**Comment by sumerjabri** [comment]
Design:
Add LDAP parameters to studio-config.yaml:

- LDAP enabled/disabled
- LDAP connection information
- username regex
- email regex
- first name regex
- last name regex
NOTE: make sure to accept nulls/invalids as empty fields

Add the field `externally managed` to the user information table

Change login flow to login via LDAP, if enabled, first then local repo.

If login of the user doesn't result in a username and email, reject the login and log that we can't accept users without a valid username and email address and throw that exception back with HTTP 500 to the caller.

Upon a successful LDAP login, upsert the user to the user table with the extracted fields + `externally managed` flag.

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/639
