### ISSUE TITLE
[studio-ui] Installing a plugin with parameters is not  closing  the install dialog

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5170]
#### Crafter CMS Version
`4.0.0-SNAPSHOT`

#### Date of Build
N/A
#### Describe the bug
Search and Install a plugin with parameters(Maps), when installation completes the Install dialog should be closed

#### Logs
N/A

#### Screenshots
N/A

**Comment by yacdaniel** [comment]
Verified fixed. 
+
