### ISSUE TITLE
[studio-ui] Plugin Management: Install button of the plugin details section is not working with plugins that require parameters

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5171]
#### Crafter CMS Version
4.0.0-SNAPSHOT-eb3fd4

#### Date of Build
22/12/2021 7:26 p. m.

#### Describe the bug
The install button in the upper-right corner of the plugin details section doesn't work for plugins that require parameters. The plugin parameter form should display when pressing the install button.  

#### To Reproduce
1. Go to 'Plugin Management'
2. Click on 'Search & install'
3. Click on 'More...' in a Chatbot Plugin (Olark, Hubspot...)
4. Click on 'Install' in the upper-right corner

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/147498354-0182dcd7-1241-473e-821e-f4cb8ad778a8.mp4

**Comment by aachavarria** [comment]
Please re-test this, I handle this issue on this ticket https://github.com/craftercms/craftercms/issues/5170

**Comment by Euquimides** [comment]
Hi @aachavarria! I re-test it and now is working well. Issue fixed. Thank you!
