### ISSUE TITLE
[studio-ui] Plugin Management: Save button in installed plugin configuration freezes when adding invalid xml. 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5174]
#### Crafter CMS Version
4.0.0-SNAPSHOT-c3e0bc

#### Date of Build
22/12/2021 9:20 a. m.

#### Describe the bug
Save button inside installed plugin configuration freezes when user adds invalid xml. API returns HTTP method 500. 

#### To Reproduce
1. Go to 'Plugin Management'
2. Click on 'Plugin Configuration Editor' of an already installed plugin
3. Enter random input inside the xml editor  
4. Click on 'Save'
5. See the error

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/147506307-945b4969-8279-4731-98de-1ccb02fcdd1f.mp4

**Comment by yacdaniel** [comment]
Related to: https://github.com/craftercms/craftercms/issues/5183

**Comment by Euquimides** [comment]
Hi @yacdaniel and @aachavarria! Updated and re-rechecked the issue, it is working fine now, the button doesn't freeze. Thank you!
