### ISSUE TITLE
[studio-ui] Dropdown form control looks broken in dark theme

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5175]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/22

#### Describe the bug
Dropdown form control looks broken in dark theme

#### To Reproduce
1. Go to a form in darkmode
2. Click on a dropdown

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/147506476-242ccfb5-16a4-4b19-9881-6d20c2d41023.png)

**Comment by aachavarria** [comment]
Cannot reproduce it on Linux/Mac editing a editorial feature.

**Comment by rart** [comment]
@aachavarria the problem occurs when you open not the full form but just the little piece.

1. Go to editorial
2. On a feature click on the icon and hit edit
3. The form that opens with the icon drop down control only is the one with the issue

**Check other controls for this same behaviour** (opening the control by itself, not the full form)

**Comment by rart** [comment]
@aachavarria did you check other controls for the same issue?

**Comment by aachavarria** [comment]
yes, looks like all of them uses the same wrapper class

**Comment by russdanner** [comment]
Confirmed
