### ISSUE TITLE
[studio-ui] Changing number of items per page in Asset/Browse components browser doesn't work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5176]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/22

#### Describe the bug
Changing the number of items per page in the Asset/Browse components browser doesn't work

#### To Reproduce
Add a list of images > 10, change the pagination size to 25, nothing happens

#### Logs
N/A

#### Screenshots
N/A

**Comment by aachavarria** [comment]
I found the same behavior on Search Preview Panel, I will fix it on the same PR  https://github.com/craftercms/studio-ui/pull/2726

**Comment by sumerjabri** [comment]
Verified fixed.
