### ISSUE TITLE
[studio] UI Cut/Paste label is incorrect in case of collision

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5178]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/22

#### Describe the bug
If you cut a folder/item that has a name that collides with another, the label doesn't update correctly

#### To Reproduce
1. Create a site from Editorial BP
2. Copy `static-assets/css` and paste it under static-assets
3. Now copy the resulting `css-copy-1` and paste it under `css`
4. Now go back to `static-assets` and _cut_ `css-copy-1` again and paste it under `css` once again
5. Now look inside `css`, you'll see `css-copy-1` twice (not the `path` nor storage, but just the `label`)

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/147507648-bbf0d0e7-faf1-4366-bc30-5ff8ec6b70e9.png)

**Comment by jdrossl** [comment]
@sumerjabri I think this is a UI only ticket no?

**Comment by sumerjabri** [comment]
@jdrossl it's backend, ping me to demo

**Comment by jdrossl** [comment]
Cause of the issue:
- The move operation (cut - paste) doesn't update the label of the moved item(s) like the copy does

Other issues to take into account:
- For folders it's easy to update the label in the DB, for pages it is required to update both the DB & the XML at the same time

Will be moved to RC2 to find a better approach

**Comment by jmendeza** [comment]
Added fix for assets.
Solution for pages will need to consider several scenarios: folders into pages, pages into folders, etc.
