### ISSUE TITLE
[studio-ui] Component ID control wraps when too long (doesn't look good)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5182]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
The Component ID control wraps when too long and doesn't look good. We should try to have the fixed path piece be able to grow so it doesn't wrap, at least not so easily.

#### To Reproduce
1. See the form for `/components/left-rails/left-rail-with-related-articles`

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by alhambrav** [comment]
Verified fixed.
