### ISSUE TITLE
[deployer][studio] Fix log message about deprecated parameter in Elasticsearch

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5186]
#### Crafter CMS Version
`4.0.0-SNAPSHOT`
#### Date of Build
`2021/12/28`
#### Describe the bug
There is a log message about the use of a deprecated Elasticsearch parameter in Deployer/Studio when a site is created and content is added/modified. 

#### To Reproduce
1. Create a site from any BP
2. Edit the Home page
3. Check Studio and Deployer logs. 

#### Logs
```
2021-12-28 15:38:48.618  WARN 8204 --- [deployment-5] org.elasticsearch.client.RestClient      : request [POST http://localhost:9201/editorial-preview*/_search?typed_keys=true&max_concurrent_sh
ard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=
true] returned 1 warnings: [299 Elasticsearch-7.16.2-2b937c44140b6559905130a8650c64dbd0879cfb "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."] 
```
#### Screenshots
N/A

**Comment by jdrossl** [comment]
@sumerjabri it seems like the only option is to increase the log level to `ERROR` for that class to hide the messages, because the current client always sends the deprecated parameter. Is that ok or should we ignore this until we move to the new ES client?

**Comment by sumerjabri** [comment]
@jdrossl we will fix this by moving to the new ES client in RC2. Related to https://github.com/craftercms/craftercms/issues/5210
