### ISSUE TITLE
[craftercms] Place the Solr indexes in the data folder

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#519]
For the Authoring env: Please put the Solr indexes in data, like this:
data/indexes

For Delivery env: Please put the Solr indexes also in a new data folder:
data/indexes

**Comment by avasquez614** [comment]
Sumer, we have to put all core data under there, including core config, if not cores for old sites will be picked and there could be some conflicts when creating new cores. I would say we should have a directory like data/solr/cores.

**Comment by avasquez614** [comment]
@cortiz You have to do the following to move the cores to data/indexes: After Solr is downloaded, you have to go to SOLR_INST/server/solr and replace the solr.xml with the attached file. You also need to replace the {placeholder} with actual data dir.

[solr.xml.txt](https://github.com/craftercms/craftercms/files/821639/solr.xml.txt)
