### ISSUE TITLE
[studio] /api/2/content/paste returns an error when a tree is copied to a folder which no longer exist(renamed/deleted)

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5191]
#### Crafter CMS Version
`4.0.0-SNAPSHOT`
#### Date of Build
`12/29/2021`
#### Describe the bug
When an user copy a tree folder of items, the selected location to paste is also a tree folder and then the target path to pasted changes and no longer exist(another logged user renamed or deleted the target path folder)
#### To Reproduce
0. Set up two users in Studio `admin` and `admin2`
1. Create a site from https://github.com/crafter-qa/paste-tree-folder-removed 
2. With `admin` copy the folder `folder_to_copy`  and his page, open the options of `folder_top_1` 
3. With `admin2` user logged in another browser, rename `folder_top_1`
4. With `admin` select `Paste` in the preciously open `folder_top_1` options.
5. Paste API returns an error and Studio-UI still thinks the paste operation is going on.

#### Logs
[{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}
](https://gist.github.com/yacdaniel/716007c090d9dc753aef3bcb3209875f)
#### Screenshots
https://user-images.githubusercontent.com/6722074/147709968-0e3ab77c-47f3-481b-b7bd-64a7512aee0f.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2818

**Comment by Euquimides** [comment]
Hi @yac and @dejan-brkic! Updated an re-checked the issue. The copy and paste operation is now working fine. Thank you! I'm closing this issue.
