### ISSUE TITLE
[deployer] Add a Git gc processor

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5192]
#### Is your feature request related to a problem? Please describe.
Git operations on a Deployer Git repo clone, used to pull the published repo from Studio, can become very slow after a lot of publishes. Git gc seems to solve the issue.

#### Describe the solution you'd like
We need a processor that runs a `git gc `after a certain amount of time has passed from the last `git gc` (configurable). Also all Deployer target templates that pull from a Studio published repo should be updated with this processor.

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
Agreed to tackle via https://git-scm.com/docs/git-gc#Documentation/git-gc.txt-gcauto git configuration.
