### ISSUE TITLE
[studio-ui] Close content confirm form dialog does not support dark theme

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5193]
#### Crafter CMS Version
4.0.0.rc1

#### Date of Build
12/29/2021

#### Describe the bug
The **close content form confirm dialog** does not support dark theme

#### To Reproduce
1. Use dark theme
2. Open a content form
3. Click the X to close the form
4. See the error

#### Logs
N/a

#### Screenshots

<img width="1415" alt="Screen Shot 2021-12-30 at 3 34 53 PM" src="https://user-images.githubusercontent.com/169432/147788050-1516cca4-03da-4217-9eca-e21b713a4c74.png">

**Comment by rart** [comment]
@sumerjabri @russdanner I want us to freeze any missing dark mode on the legacy UI — including this one. Only fix bugs (e.g. unreadable text). As we replace legacy code, everything will automatically have a dark mode.

**Comment by sumerjabri** [comment]
Will be addressed in the new form engine.
