### ISSUE TITLE
gradlew build fails

### ISSUE THREAD

**Issue by deshantm** [craftercms/craftercms#5196]
./gradlew build deploy bundle
<-------------> 0% INITIALIZING [0s]
> settings
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/deshantm/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deshantm/development/craftercms/build.gradle' line: 526

* What went wrong:
Execution failed for task ':commons_clean'.
> java.io.IOException: Cannot run program "mvn" (in directory "./src/commons"): error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed

**Comment by sumerjabri** [comment]
Seems like you may have the wrong Java version. What branch are you building, what version of Java and Maven are you using. Can you post the logs you have of the build process?

It might be best to handle this via Slack, join us here: https://join.slack.com/t/craftercms/shared_invite/enQtNDg0NzI3NzA0NjMwLWZmMGQzMDViMzA5NDE1YjMzM2M1N2JlOWJlZDA1MjA2MGJlZjgzNDVlMmI5ODQxNmNjMWQ3NzA5ZWNkN2UxOWE

**Comment by deshantm** [comment]
I was able to download a binary. I was using the 3.x stable branch and java and maven installed from homebrew on Mac. I will try the 4.x branch next. I need a more modern feel. Thank you for sharing the slack information.
