### ISSUE TITLE
[blueprints] Update ToolbarSearch widget

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5198]
We need to change `<widget id="craftercms.components.EmbeddedSearchIframe" />` to `<widget id="craftercms.components.Search" />`

Replace the string `craftercms.components.EmbeddedSearchIframe` with `craftercms.components.Search` on `ui.xml` for all 4 blueprints.

**Comment by sumerjabri** [comment]
Done for all BPs, built-in and MP.

**Comment by rart** [comment]
@sumerjabri, we missed https://github.com/craftercms/wordify-blueprint/blob/react/config/studio/ui.xml#L324
