### ISSUE TITLE
[craftercms] Update Tomcat's context.xml

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#520]
Add `<Resources cachingAllowed="true" cacheMaxSize="100000" />` to Tomcat's `$CATALINA_BASE/conf/context.xml`

The number 100000 is a starting point until we gather more data and better understand what it should be.

**Comment by avasquez614** [comment]
This is from the Tomcat documentation:

cacheMaxSize	

The maximum size of the static resource cache in kilobytes. If not specified, the default value is 10240 (10 megabytes). This value may be changed while the web application is running (e.g. via JMX). If the cache is using more memory than the new limit the cache will attempt to reduce in size over time to meet the new limit. If necessary, cacheObjectMaxSize will be reduced to ensure that it is no larger than cacheMaxSize/20.

We could also just disable caching:

`<Resources cachingAllowed="false" />`

**Comment by cortiz** [comment]
@sumerjabri should we disable or max out ?
