### ISSUE TITLE
[studio-ui] There are errors when viewing an edited ftl file via left-click on the Site Explorer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5202]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-9e4304

#### Date of Build
Build Date:
1/4/2022, 7:35 AM

#### Describe the bug
When you edit an ftl file and try to view the file by left-clicking on it from the `Site Explorer`, it tries to preview the file showing lots of errors instead of opening a dialog displaying the file.

<img width="1308" alt="Screen Shot 2022-01-04 at 7 52 47 AM" src="https://user-images.githubusercontent.com/25483966/148062274-b11e7f2c-46da-437c-a53f-e0c010766efe.png">

1. Create a site using the Website Editorial bp
2. Navigate to `templates/web/pages and left click on one of the items there, say the `category-landing.ftl`
3. Notice that this opens a dialog displaying the contents of the ftl file
<img width="1311" alt="Screen Shot 2022-01-04 at 7 52 30 AM" src="https://user-images.githubusercontent.com/25483966/148062866-9b54b17d-53a0-4dd2-840e-db56ad465a11.png">

4. Edit one of the ftl files, say `article.ftl`
5. From the `Site Explorer`, left click on `article.ftl`.  Notice the errors on the screen and in the catalina log.  It looks like it tries to preview the file showing lots of errors instead of opening a dialog displaying the file.
<img width="1310" alt="Screen Shot 2022-01-04 at 8 16 48 AM" src="https://user-images.githubusercontent.com/25483966/148064779-eb11a046-7811-4206-b389-c374d1177777.png">

#### Logs
https://gist.github.com/alhambrav/937675230001f3dfdd0aabe75f98eafd

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by aachavarria** [comment]
Doing some testing after the flt is saved, the api "api/2/content/children_by_path" return the item with previewURL.
originally it came with a null value, after saved it comes with a path

**Comment by aachavarria** [comment]
Im assign it to you @sumerjabri maybe jose or dejan could check it

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2820

**Comment by alhambrav** [comment]
Verified fixed.
