### ISSUE TITLE
[studio-ui] Upload option is not working

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#5204]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-9e4304`

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
The upload option is not working

#### To Reproduce
![upload](https://user-images.githubusercontent.com/1236955/148114470-548801d7-3ec3-41b6-bc31-edd75c184dbc.gif)

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by aachavarria** [comment]
no able to reproduce, can you share additional steps

**Comment by jdrossl** [comment]
there are no additional steps, I just click the upload option for any folder

**Comment by avasquez614** [comment]
I'm seeing the same issue

**Comment by sumerjabri** [comment]
@rart this is now blocking several things

**Comment by rart** [comment]
@sumerjabri it's a problem with react-scripts v5.

I've opened an issue for the react team to address; but who knows when that might even be looked at, let alone fixed and published. https://github.com/facebook/react/issues/23071

We might have to downgrade back to v4 by rolling back [pull request # 2724](https://github.com/craftercms/studio-ui/pull/2724/files).

**Comment by sumerjabri** [comment]
@rart please roll back.

**Comment by jdrossl** [comment]
Verified
