### ISSUE TITLE
[studio-ui] Edit filename url warning doesn't open the dependencies dialog.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5205]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-f11899`
#### Date of Build
`1/4/2022`
#### Describe the bug
The dependencies dialog is not showing when an user clicks the option in the Edit filename warning dialog. 
#### To Reproduce
1. Create a site from Editorial bp and edit an article page.
2. Click `Edit` next to `Page URL`
3. Click the `here` link
4. See the error

#### Logs
```
state.ts:36 Uncaught TypeError: Cannot read properties of undefined (reading 'isNew')
    at u (VM674 main.f17c0813.js:2)
    at A (VM674 main.f17c0813.js:2)
    at Module.M (VM674 main.f17c0813.js:2)
    at Object.viewDependencies (VM678 common-api.js:916)
```
#### Screenshots
![edit page url dep warning](https://user-images.githubusercontent.com/6722074/148119799-d86f16e5-887e-48c1-bbb8-ed53e50ecb65.gif)

**Comment by aachavarria** [comment]
'here' was removed for RC 1.0

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/149016547-908a71f6-d576-480e-a289-e67faaa9acd9.png)
