### ISSUE TITLE
[studio][studio-ui] Optimize caching headers for static resources and add cache busters where needed

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5206]
#### Is your feature request related to a problem? Please describe.
Form JavaScript files, CSS files, and other static assets are loaded repeatedly and not cached by the browser.

#### Describe the solution you'd like
Add caching headers to speed this up. Make sure the cache headers include a cache buster, preferably the build number. Ping if stuck.

#### Describe alternatives you've considered
Blindly cache responses for a configurable time.
Build a bulk request API.

**Comment by jdrossl** [comment]
@sumerjabri static resources in studio are actually served by engine (because of the overlay) would it be ok to use the existing etag filter in engine to generate the caching headers?

**Comment by sumerjabri** [comment]
@jdrossl if we can make it work for the hosting Engine (not the Preview Engine), then I think we're fine.

**Comment by sumerjabri** [comment]
The UI seems to cache bust things like:
![image](https://user-images.githubusercontent.com/3931908/149840385-b3b1157b-bcfd-4dd0-8fd2-d545fbfe5b1b.png)

Let's discuss @rart

**Comment by rart** [comment]
@jvega190 remove the addition of the `nocache` argument and all the build-number-based busters from ftls too. See if you can find any other instance of UI-based cache busting and let me know if you find any.
