### ISSUE TITLE
[studio-ui] After clearing cookies: When Form Engine opens, it creates a new crafterSite cookie that conflicts with another crafterSite cookie. 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5208]
#### Crafter CMS Version
4.0.0-SNAPSHOT-f11899

#### Date of Build
4/1/2022 10:58

#### Describe the bug
The user is in Preview Mode of a site and then clears all cookies. When login again, a new crafterSite cookie with the server's domain is created. If the user then edits an "Article" (for example), when entering the Content Form (Form Engine) a new cookie is created with domain ".craftercms.org". Both cookies enter in conflict generating various kinds of errors.

#### To Reproduce
1. Go to "Preview Mode" of a site of choosing (Site A). 
2. Using Chrome DevTools, in Application Tab, click on ''Storage", then "Cookies", right-click "Clear". 
3. Refresh your browser.
4. Login to Crafter CMS Studio.
5. Crafter CMS will initialize in "Preview Mode" of the chosen site (Site A). 
6. Open Form Engine by editing an article inside "Pages". A new crafterSite cookie with domain "craftercms.org" will be created. 
7. If another site already exists (Site B), click on "Navigation Menu", click on "Sites", delete Site A. 
8.Click on Site B, see error. 

#### Logs
Logs in `tail -F /opt/crafter/craftercms/crafter-authoring/logs/tomcat/catalina.out` shows next observation: 

`[INFO] 2022-01-05T00:09:49,428 [http-nio-8080-exec-2] [libs.EnvironmentOverrides] | [EnvironmentOverrides] Attempt to visit ts2 site without the necessary roles`

In this case, "ts2" site represents Site B whire "ts1" represents Site A. 

#### Screenshots

https://user-images.githubusercontent.com/90878288/148142458-fe7aeaf3-f20b-4b77-a812-c634fd755545.mp4

**Comment by jvega190** [comment]
@Euquimides assigning it to you for validation

**Comment by Euquimides** [comment]
Hi @jvega190! I updated and re-checked the issue. There's no more duplication of cookies. Thank you!
