### ISSUE TITLE
[studio][studio-ui] Lock the items currently in XB edit mode

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5209]
#### Is your feature request related to a problem? Please describe.
Experience Builder (XB) doesn't clearly lock content items and in cases of multi-user edits of the same items, it can lead to issues.

#### Describe the solution you'd like
- [x] [BACKEND] Create API spec (OAS) to manage locks a set of items by path and review design
  - [x] item_lock_by_path
- [x] [BACKEND] Implement the APIs
- [ ] [UI] Lock the items the user is XB Edit/Move modes and unlock when the user exits the edit mode or exists the page in any way (whenever possible)
  - [ ] Phase 1: Lock the page for phase 1 and test in a group
  - [ ] Phase 1: Notify a user that tries to edit that the page/component is locked
  - [ ] Phase 2: Lock the page or component and inlined shared components and sub-components
  - [ ] Phase 2: If items within the main item (like shared components) are locked, don't allow editing those locked sub-items
  - [ ] Phase 2: Allow an admin to unlock a subcomponent
- [ ] [UI] If an item is unlocked by an admin, exit the edit mode. (This becomes easy with Websockets.)

#### Describe alternatives you've considered
Allow co-authoring and lock only optimistically. We're not ready for that yet.

**Comment by dejan-brkic** [comment]
BE Done
PR:
https://github.com/craftercms/studio/pull/2835

**Comment by sumerjabri** [comment]
Replaced by this https://github.com/craftercms/craftercms/issues/5301
