### ISSUE TITLE
[all] Upgrade to JGit 6

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5213]
Upgrade to JGit 6.0.0.202111291000-r for all packages and resolve issues.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/craftercms/pull/5242
https://github.com/craftercms/commons/pull/288
https://github.com/craftercms/studio/pull/2839

**Comment by sumerjabri** [comment]
Verified done.
