### ISSUE TITLE
[studio-ui] XB should provide an easy way to add new items in repeat groups

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5219]
#### Is your feature request related to a problem? Please describe.
It's hard to add new items to a Repeating Groups. You must open the form engine and add within before you can use XB.

#### Describe the solution you'd like
- [x] Design a new experience, perhaps a shortcut in Edit or Move or both (at the top title)
- [x] Review design
- [x] Implement
- [x] Test

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
I'm not able to make this work. I'm also seeing bugs with `move`, ping me to discuss.

**Comment by rart** [comment]
As discussed yesterday, these were [blueprint issues](https://github.com/craftercms/craftercms/issues/5318).
