### ISSUE TITLE
Remove Legacy Preview code from Studio UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5220]
Remove the old Legacy Preview code entirely:
- [ ] Remove the old Legacy Code
- [ ] Remove the ACE Append https://github.com/craftercms/studio-ui/blob/develop/ui/ace/src/ace-append.js
- [ ] Look for anything else related to this and remove it

**Comment by jvega190** [comment]
Legacy preview was removed in here https://github.com/craftercms/studio-ui/pull/3112. I'll remove ace-append and look for more legacy code that can be removed

**Comment by jvega190** [comment]
- Legacy ICE code to be removed
- Legacy site config to be removed after FE2 (curently in use by content-type editor)

**Comment by rart** [comment]
@jvega190 try giving another pass. Pay particular attention to all the "libs" folders.
