### ISSUE TITLE
[studio-ui] The Repository Path is not used to filter on search for both image and video browse datasources

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5221]
#### Crafter CMS Version
Latest build of 4.0

#### Date of Build
5/1/2022

#### Describe the bug
The `Repository Path` is not used to filter on search for both image and video browse datasources (this is how it works in 3.1.x)

#### To Reproduce
1. Create a simple site (like Editorial)
2. Configure a content type with an image browse data source and a video browse datasource. Both should use search and should have a `Repository Path` specified.
3. Create new content based on the content type and on the control select the datasource.

The search dialog appears but the items are not filtered by the `Repository Path`.

#### Screenshots
![Screenshot from 2022-01-05 19-26-26](https://user-images.githubusercontent.com/1598884/148310062-e1f8b4df-48c9-4739-bd93-9309a06c2bb1.png)
![Screenshot from 2022-01-05 19-27-22](https://user-images.githubusercontent.com/1598884/148310063-afcdf077-6712-4f19-8826-a9f50f50e8dc.png)
![Screenshot from 2022-01-05 19-35-32](https://user-images.githubusercontent.com/1598884/148310064-07f9c7c0-e499-41fe-9f27-66b094305cfa.png)
![Screenshot from 2022-01-05 19-36-21](https://user-images.githubusercontent.com/1598884/148310065-8b3fce68-9e78-495a-bbf1-af391f5bae35.png)

**Comment by Euquimides** [comment]
Hi @avasquez614 and @aachavarria! I updated and re-checked the issue. The repository path filter for the search content form in both video and image data sources is fixed. However an issue that might be somewhat related with this appears on issue #5270. I'm closing this ticket.
