### ISSUE TITLE
[studio-ui] Saved as Draft message forces top toolbar below making it difficult to use

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5225]
#### Crafter CMS Version
3.1.17

#### Describe the bug
When you save a page as draft in studio with a smaller browser window, the top navigation toolbar gets pushed below the "Saved as Draft" message and makes it difficult to click.

#### To Reproduce
1. Create a new site
2. Edit the home page and click Save as Draft.
3. Notice the "Content was saved as DRAFT. Some required fields may not be populated. This can cause errors when previewed or deployed." message at the top of the page. Now shrink the browser to be smaller and see the top navigation tool bar being forced below the message.

#### Logs
n/a

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/148582322-5f4433a0-2e16-4d01-9b0c-97054d2051e2.png)

**Comment by rart** [comment]
The `draft` (and disabled) messages are now floating and dismissible. The right tools jumping to the next line is a matter of screen size, though. They will wrap even without the notices is if the screen isn't big enough.

**Comment by AndyReiter** [comment]
Confirmed fixed in 3.1.18. Will close out now.
