### ISSUE TITLE
[studio-ui] Saved as Draft message displays over content in the top of a pages' content

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5226]
#### Crafter CMS Version
3.1.17

#### Describe the bug
When you save a page as a draft in studio and shrink the page down, the Saved as Draft message displays over content on the page that is placed at the top of the page.

To Reproduce

1. Create a new site
2. Edit the home page and click Save as Draft.
3. Notice the "Content was saved as DRAFT. Some required fields may not be populated. This can cause errors when previewed or deployed." message at the top of the page. Now shrink the browser to be very wide, but short, and see that the Saved as Draft message overlays on top of page content.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/148583308-6752f588-b51f-4331-80fb-54185d50519d.png)
![image](https://user-images.githubusercontent.com/42217570/148583380-9921f33f-b7f8-418e-bec9-94d28ec1eeb1.png)

**Comment by rart** [comment]
@jvega190 please port https://github.com/craftercms/studio-ui/pull/2751 to 4

**Comment by sumerjabri** [comment]
@AndyReiter please validate in 3.1.18

**Comment by AndyReiter** [comment]
Confirmed fixed in 3.1.18. Closing now.
