### ISSUE TITLE
[studio-ui] Dashboard for Items Waiting for Approval shows folders for assets rather than the assets

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5231]
#### Crafter CMS Version
4.0.0-rc1

#### Date of Build
1/7/2022

#### Describe the bug
[studio-ui] Dashboard for Items Waiting for Approval shows folders for assets rather than the assets

#### To Reproduce
1. Submit assets for review
2. Open Items waiting for approval dashboard, see folders

#### Logs
N/A

#### Screenshots
<img width="1015" alt="Screen Shot 2022-01-10 at 3 40 40 PM" src="https://user-images.githubusercontent.com/169432/148836720-b1a8876a-7327-40a4-8cd0-c6bdb5c281e2.png">

**Comment by rart** [comment]
@aachavarria please verify if this actually is a UI bug. Reassign to sumer for re-assignment otherwise.

**Comment by russdanner** [comment]
Confirmed
