### ISSUE TITLE
[studio] Items waiting for approval should have a sort order

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5232]
#### Is your feature request related to a problem? Please describe.
There does not seem to be any sort applied to the results in the Items Waiting for Approval dashboard

#### Describe the solution you'd like
Define a default sort so that results are predictable across refreshes

https://www.loom.com/share/548907462bc54cad9b0fc2615758b069

**Comment by jvega190** [comment]
Right now the items are sorted by last edited date. But if after creating a site the items are submitted (without editing them) all of the items will have the same last edited date, then, the request will retrieve the items in an inconsistent order.

**Comment by sumerjabri** [comment]
DB returns items in the order it has. We will look into it.

**Comment by sumerjabri** [comment]
@russdanner pushed this to rc-3 to avoid the distraction since this may not be an issue and you wanted to re-look at it.

**Comment by russdanner** [comment]
Dashboard has been replaced
