### ISSUE TITLE
[studio-ui] Add style_formats to RTE 5

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5237]
### Feature Request
Add the following `style_formats` config  to RTE and make it configurable via XML

```
tinyMCE.init({
    ...
    style_formats : [
        {title : 'Bold text', inline : 'b'},
        {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
        {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
        {title : 'Example 1', inline : 'span', classes : 'example1'},
        {title : 'Example 2', inline : 'span', classes : 'example2'},
        {title : 'Table styles'},
        {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
    ]
});
```

#### Is your feature request related to a problem? Please describe.
{{A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]}}

#### Describe the solution you'd like
{{A clear and concise description of what you want to happen.}}

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by avasquez614** [comment]
Verified in 3.1.x

**Comment by rart** [comment]
@sumerjabri @avasquez614 @phuongnq 

It just occurred to me the below line of code in this work is a vulnerability.
```js
Function(`"use strict"; return (${rteConfig.styleFormats})`)()
```
see https://github.com/craftercms/studio-ui/blob/support/3.1.x/static-assets/components/cstudio-forms/controls/rte-tinymce5.js#L315

To fix, we could require the new config to be JSON and and we parse the JSON — which wouldn’t be vulnerable to JavaScript code expressions. The limitation is people need to enter valid JSON so for example `{title : 'Bold text', inline : 'b'}` wouldn’t be accepted, it’d need to be transformed to `{“title“: “Bold text”, “inline”: “b”}`. Shouldn’t be an issue but wanted to raise the limitation.

**Comment by sumerjabri** [comment]
@avasquez614 please re-validate

**Comment by avasquez614** [comment]
@rart @sumerjabri @phuongnq  I'm fine with requiring the code to be valid JSON, as long a we add a comment indicating that and we throw a meaningful error if it's not valid

**Comment by avasquez614** [comment]
after a discussion with @sumerjabri and @rart, we decided we will output a an error when the configuration is read during RTE loading, in case the JSON is invalid

**Comment by phuongnq** [comment]
verified

**Comment by phuongnq** [comment]
Seem like in v4, we got an error:

Uncaught TypeError: Cannot read properties of undefined (reading 'styleFormatsParseErrorShown')
    at CStudioForms.Controls.RTE._initializeRte (rte.js:313:52)
    at Object.success (rte.js:82:30)
    at Object.success (rte-config-manager.js:77:20)
    at common-api.js:3335:22
    at Object.next (27.7552fe16.chunk.js:2:329774)
    at t._next (27.7552fe16.chunk.js:2:328990)
    at t.next (27.7552fe16.chunk.js:2:328607)
    at 27.7552fe16.chunk.js:2:77743
    at t.i._next (27.7552fe16.chunk.js:2:53018)
    at t.next (27.7552fe16.chunk.js:2:328607)

**Comment by rart** [comment]
Indeed, there was a bit of a commit mix up. Fixed.

**Comment by phuongnq** [comment]
Thank you. Verified in v4!
