### ISSUE TITLE
[studio-ui] Inserting a template in RTE through ICE does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5241]
#### Crafter CMS Version
4.0.0-SNAPSHOT-546e7e (4.0.0-rc1 binary)

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
When you try to insert a template in the RTE via ICE, it says ``No templates defined`` instead of opening a dialog containing a list of available templates configured in the RTE config

#### To Reproduce
1. Create a site using the Website Editorial bp
2. Configure templates in the RTE config
```
   <templates>
     <template>
       <title>Test template 1</title>
       <content>Test 1</content>
       <description>Test1 Description</description>
     </template>
     <template>
       <title>Test template 2</title>
       <content><![CDATA[
         <div class="test">
           <h1>This is a title</h1>
           <p>Look at this paragraph!</p>
         </div>
         ]]>
       </content>
       <description>Test 2 description</description>
     </template>
   </templates>

```
3. Preview the Home page or an article page
4. Turn on `Edit mode` to enable the ICE pencils
5. Click on an RTE on the page, then click on `Insert` -> `Insert template...`
6. Notice that you'll get a `No templates defined` message
<img width="836" alt="RTE-4-0-insert-template-via-ice" src="https://user-images.githubusercontent.com/25483966/149469407-30cde86a-3eb2-4d01-bed3-f3752c8ab044.png">

7. Now try to edit the same RTE via the `Edit` from the toolbar at the top of the page, (click on the three vertical dots (`Options`) then select `edit`
8. Scroll to the RTE you want to edit, then click on `Insert` -> `Insert template...`
9. Notice that this opens the dialog containing the configured templates in the RTE config
<img width="1231" alt="RTE-4-0-insert-template" src="https://user-images.githubusercontent.com/25483966/149469879-770e2a7d-067d-41c2-acec-9ffdeb7175d3.png">

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by jvega190** [comment]
Hi Vita, the ICE RTE control loads another configuration (ui.xml). So in order to make templates show in ICE, you need to add the templates configuration like this:
- Form RTE configuration: 
```
<templates>
     <template>
       <title>Test template 1</title>
       <content>Test 1</content>
       <description>Test1 Description</description>
     </template>
     <template>
       <title>Test template 2</title>
       <content><![CDATA[
         <div class="test">
           <h1>This is a title</h1>
           <p>Look at this paragraph!</p>
         </div>
         ]]>
       </content>
       <description>Test 2 description</description>
     </template>
   </templates>
```

- ICE RTE configuration (in ui.xml):
```
<widget id="craftercms.components.TinyMCE">
  <configuration>
    <setups>
       <setup id="...">
          ... 
          <tinymceOptions>
            <![CDATA[
              {
                "menubar": true,
                ...
                "templates" : [
                  {
                    "title": "Test template 1",
                    "content": "Test 1",
                    "description": "Test1 Description "
                   },
                   {
                      "title": "Test template 2",
                      "content": "<div class='test'><h1>This is a title</h1><p>Look at this paragraph!</p></div>",
                      "description": "Test 2 description"
                   }
                ]
             }
        ]]>                         
        ...
```
Note that when adding markup as content, is the same content that the other configuration has without CDATA, and all in one line, since it's a JSON object.

**Comment by alhambrav** [comment]
Verified RTE template plugin works through ICE with the configuration mentioned above.
Configuration documented: https://github.com/craftercms/docs/pull/1405
