### ISSUE TITLE
Turning on CORS in Crafter Author System breaks create

### ISSUE THREAD

**Issue by jball606** [craftercms/craftercms#5243]
#### Crafter CMS Version
4.0

#### Date of Build
craftercms/authoring_tomcat:4.0.0-rc1

#### Describe the bug
After running docker, system works and you can create a new site using the Create Site button.  But if you turn on CORS in the studio-config-override.yaml and restart docker, you can't create the site anymore.  You get this message 

```org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9191/api/1/target/create_if_not_exists": Connect to localhost:9191 [localhost/127.0.0.1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:9191 [localhost/127.0.0.1] failed: Connection refused (Connection refused)```

#### To Reproduce
Spin up new docker
Create Site it works
Create studio-config-override.yaml file with these settings

```
################################################################
##                             CORS                           ##
################################################################
# This is configured as permissive by default for ease of deployment
# Remember to tighten this up for production

# Disable CORS headers completely
 studio.cors.disable: false
# Value for the Access-Control-Allow-Origin header
 studio.cors.origins: 'only.one.I.changed'
# Value for the Access-Control-Allow-Headers header
# studio.cors.headers: '*'
# Value for the Access-Control-Allow-Methods header
# studio.cors.methods: '*'
# Value for the Access-Control-Allow-Credentials header
# studio.cors.credentials: true
# Value for the Access-Control-Max-Age header
# studio.cors.maxage: -1
```

now restart docker
go into system
click create site and fill out fields
hit submit, system fails and you get port block error

#### Logs
```org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9191/api/1/target/create_if_not_exists": Connect to localhost:9191 [localhost/127.0.0.1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:9191 [localhost/127.0.0.1] failed: Connection refused (Connection refused)```

**Comment by jball606** [comment]
I updated my CORS to allow localhost and still didn't work

```studio.cors.orgins: 'https://crafter.ascendify.net,http://localhost:9191' ```  I tried with and without the port

**Comment by avasquez614** [comment]
@jball606 from the logs it sounds more like the Deployer container didn't start correctly and that's why the site creation failed, instead of being a CORS issue. Do you have logs of the Deployer container? Can you also share the docker-compose configuration you are using (the full files please)

**Comment by jball606** [comment]
@avasquez614 here is my full crafter.yml file for docker.  Until I modify the CORS system, it does seems to work fine, but I am only changing CORS on the Author system.   I am just trying to create a new site or upload an image and it breaks.  But before I messed with CORS it worked perfectly.  Anything that needs localhost:9191 seems to break.
[crafter.txt](https://github.com/craftercms/craftercms/files/7878959/crafter.txt)
.

**Comment by jball606** [comment]
[image_error.txt](https://github.com/craftercms/craftercms/files/7878965/image_error.txt)
here is the error I get when trying to upload an image from the docker log

**Comment by avasquez614** [comment]
@jball606 I'm a little confused about how you're editing the studio-config-overrides.yaml. In Docker in order to make changes to that file and keep them during restarts you need to specify the file as a volume mount in the Docker compose file. I don't see that in the one you attached.

I think it will be best if you join our Community Slack or Discord and bring this issue there so we can help you better.
