### ISSUE TITLE
[studio] Add Group filtering capability to GET groups API 2

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5255]
#### Is your feature request related to a problem? Please describe.
With a very large number of groups, it's best to add filtering capability like GET users.

#### Describe the solution you'd like
Please add filtering by keyword as we have for users.

#### Describe alternatives you've considered
Filter at the caller's end.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2844

**Comment by sumerjabri** [comment]
@Euquimides please:
* Validate this ticket
* Add the test case/update the existing test case for getting groups

**Comment by Euquimides** [comment]
Hi @sumerjabri and @dejan-brkic! I updated and re-checked the issue. The GET Groups API 2 using keywords as query param is working fine. I have also automated the test for it and updated the test case in KIWI. 

@rart Please add the Filter search in groups, like we have in Users. Thank you!
