### ISSUE TITLE
[studio][deployer] Support  ECDSA-384, ECDSA-52 and ed25519 SSH keys

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5257]
#### Is your feature request related to a problem? Please describe.
Additional SSH Key support is required.

#### Describe the solution you'd like
Add additional SSH key support to Crafter Studio and Crafter Deployer

Support  ECDSA-384, ECDSA-52 and ed25519 SSH keys

**Comment by yacdaniel** [comment]
Verified.
