### ISSUE TITLE
[studio] Workflow states don't get updated after initial publish after approval

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5258]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2022/01/21

#### Describe the bug
Initial publishing doesn't seem to set the workflow states after review/approval.

#### To Reproduce
1. Create a site from any BP
2. Request publishing an item
3. From the Dashboard, review and approve all items
4. See the workflow states

#### Logs
N/A

#### Screenshots
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2849

**Comment by dejan-brkic** [comment]
Done
PR:
craftercms/studio#2849
