### ISSUE TITLE
[studio-ui] The "saved" notification appears a lot of times.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#526]
Steps:

1. log in to crafter 3.0
2. go to the dashboard
3. click on "admin console"
4. click on "content types"
5. click on "open existing type" and select any "content type"
6. click on "save" a lot of times.

[Current result]
The "saved" notification appears a lot of times.

Video: https://www.screencast.com/t/ukOGilw95BWV

[Expected result]
The "saved" notification should be appears only one chance.

**Comment by russdanner** [comment]
NOT A BUG.  This is the way the growl-like notification works.
