### ISSUE TITLE
[studio-ui] Add option preview_style to RTE5

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5260]
### Feature Request

Add the following option to RTE5:
https://www.tiny.cloud/docs/configure/editor-appearance/#preview_styles

#### Is your feature request related to a problem? Please describe.
{{A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]}}

#### Describe the solution you'd like
{{A clear and concise description of what you want to happen.}}

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
We will use https://github.com/craftercms/craftercms/issues/5261 instead to accomplish both requests.
