### ISSUE TITLE
[studio-ui] Make tinymce init function extensible

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5261]
### Feature Request

The following function should be extensible by XML config:

```
tinymce.init({
...
});
```

Create a JSON object to extend the default option so that developers can fully extend how the `init`  works.

#### Is your feature request related to a problem? Please describe.
{{A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]}}

#### Describe the solution you'd like
{{A clear and concise description of what you want to happen.}}

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by avasquez614** [comment]
Verified
