### ISSUE TITLE
[studio-ui] Workflow rejection canned reasons don't show up anymore

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5264]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2022/01/24

#### Describe the bug
Canned rejection reasons are not showing up.

#### To Reproduce
1. Create a site from Editorial BP
2. Submit an item for review
3. Try to reject it and select a canned response
4. See the error

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/150847734-49c05660-10dc-4c48-b130-d9b40c028506.png)

**Comment by jvega190** [comment]
The issue was happening due to this update https://github.com/craftercms/craftercms/issues/5117. Updated retrieval in ui

**Comment by sumerjabri** [comment]
Verified fixed.
