### ISSUE TITLE
[docs] Please document the new clustering system for v4

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5265]
Please work to replace this: https://docs.craftercms.org/en/4.0/system-administrators/activities/clustering.html with a new clustering document. We need this document in old and new IA.

**Comment by sumerjabri** [comment]
Must update the Kubernetes deployment instructions and diagrams. This depends on #5285.

**Comment by alhambrav** [comment]
Assigning to Alfonso for now while https://github.com/craftercms/craftercms/issues/5285 is being worked on
