### ISSUE TITLE
[studio]  Groups API 2: Creating a group always returns group.id = 1

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5267]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-476cad`

#### Date of Build
`24/1/2022`

#### Describe the bug
When sending a http POST request to the Groups API 2, the JSON response always returns groups.id = 1.

#### To Reproduce
Steps to reproduce the behavior (in case you are using Postman):
1. Go to 'Collections'
2. Click on 'groups' collection, then on 'POST Create Group'
3. Click on the 'Body' tab, and write a new "name" and "desc" to send as body in the POST request. 
4. See the error

#### Logs
Example: 
``{
    "response": {
        "code": 1,
        "message": "Created",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "group": {
        "id": 1,
        "name": "anim",
        "desc": "dolor et ex"
    }
}``

#### Screenshots

https://user-images.githubusercontent.com/90878288/150875991-f215847d-db00-4dc5-bcd3-7ac512108d60.mp4

https://user-images.githubusercontent.com/90878288/150876125-08bac41c-ffe9-4f5b-a21b-c803ae6e5912.mp4

#### Expected behaviour
The response for the POST groups API 2 request, should always return the ID of the newly created group.

**Comment by Euquimides** [comment]
Hi @dejan-brkic! This is also causing the next issue:

If the user creates a new group with only a name then saves, and immediately after adds a description and then saves, studio throws an error (http response 500) because it is trying to apply a PATCH request on "system_admin". 

https://user-images.githubusercontent.com/90878288/151427217-019f4daf-b61d-443a-a8e5-c5a84821a8e0.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2858

**Comment by Euquimides** [comment]
Hi @dejan-brkic! I updated and rechecked the issue, it is fixed now. Thank you!
