### ISSUE TITLE
[studio] A copy of a page is not being indexed because the generated dates are invalid

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5268]
#### Crafter CMS Version
3.1.18

#### Date of Build
N/A

#### Describe the bug
Generated dates, like createdDate and lastModifiedDate, are in the wrong format for a copy of a page and are causing indexing to fail.

#### To Reproduce
1. Create a site based on Editorial
2. Copy and paste and article from one folder to another (or in the same folder, the result is the same)

You should see indexing errors in the Deployer logs like the ones attached. If you inspect the XML of the page the `createdDate` and `lastModifiedDate` seem to be using the current timezone instead of UTC.

#### Logs
https://gist.github.com/avasquez614/36c7b5f57f954fde9265633d2967ea15

#### Screenshots
N/A

**Comment by avasquez614** [comment]
Verified

**Comment by yacdaniel** [comment]
Verified in `3.1.x`

**Comment by Euquimides** [comment]
Hi! I updated and re-checked the issue with various time zones, it is fixed. Also crafter-deployer log is not showing any errors. Thank you! I'm closing this ticket.
