### ISSUE TITLE
[studio] Lowercase files only for certain folders (pages/components) but nothing else

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#527]
Enforce lowercase on pages/components (make that configurable paths) but not on anything else. The point is to allow groovy code to be mixed-case files.

**Comment by sumerjabri** [comment]
@avasquez614 please update the path in the ticket per our conversation and I'll work with the Studio team to exclude this path from these rules.

**Comment by sumerjabri** [comment]
I also noticed that the current code changes spaces to - or _ (- for upload, and _ for bulk), and perhaps does similar things to special characters. Please remove that too so it's only done for pages and components.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/288

Removed UI side replacement
- on asset-updload.groovy there's a replacement of space and lowerCase to filename
- there's also a space replacement on ContentServiceImpl.java, on "writeContentAsset" method

**Comment by sumerjabri** [comment]
Fixed: https://github.com/craftercms/studio/pull/621
