### ISSUE TITLE
[studio-ui] Content Form doesn't show "Accept Selection" or "Cancel" buttons with either image or video data sources

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5270]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-791897`

#### Date of Build
2022/01/25

#### Describe the bug
When creating new content (for example a new article), if the Content-Type includes either image or video data sources and you select an image or video from the repository, the search content form won't show the "Accept Selection" or "Cancel" buttons.

#### To Reproduce
1. Create a simple site (like Editorial) and include an 'image from repository' data source, a 'video from repository' data source or both. 
2. Go to 'Quick Create Menu'
3. Click on 'Article'
4. Inside Content Form, scroll down to 'Image'.
5. Click on 'Add', then click on 'Existing Image'.
6. See error. 

#### Logs
N/A

#### Screenshots
![contentform_search_issue](https://user-images.githubusercontent.com/90878288/151041509-a84745a6-78b6-4711-8381-ee594fd63bac.PNG)

https://user-images.githubusercontent.com/90878288/151041904-28ac9578-1cbd-4a8c-beae-c468a7a2334f.mp4

#### Expected Behavior
The Search Content Form should show up options either for accepting selection or cancel the search.

**Comment by sumerjabri** [comment]
CC @rart

**Comment by Euquimides** [comment]
Hi @aachavarria! I updated and re-checked the issue, it is fixed now. Thank you!
