### ISSUE TITLE
[studio-ui] Make "Save & close" the default across the board

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5273]
Save & close should be the default button for all places where it's implemented.

**Comment by Euquimides** [comment]
Hi @rart and @jvega190! I re-checked this ticket, 'Save and Close' is now implemented in Content Types Form, Content Forms in general, Category Landing, the edits for groovy and ftl. Thank you! I'm closing this issue but please check out the ticket #5305 since it might be related with this.
