### ISSUE TITLE
[3.1] [studio-ui] Paste as Text option is not available

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5276]
#### Crafter CMS Version
3.1.x

#### Date of Build
Jan 27 2022

#### Describe the bug
When opening RTE editor, there is no "Paste as text" in "Edit" menu.

#### To Reproduce
1. Create a site. Ex: from Editorial BP
2. Click to edit an article and open RTE 
3. Click "Edit" menu
4. See that there is no "Paste as text" toggle button

#### Screenshots
![2022-01-27_17-11](https://user-images.githubusercontent.com/2996543/151338141-327efa55-866a-49cf-9a63-1f68093fa35e.png)

**Comment by phuongnq** [comment]
Will verify after this PR merged: https://github.com/craftercms/studio-ui/pull/2803

**Comment by russdanner** [comment]
Confirmed
