### ISSUE TITLE
[craftercms] Invoking update on a module updates all

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#528]
When invoking update like this:

`./gradlew -Penv=authoring -Pmodule=studio update`

All modules got updated instead of just studio.

**Comment by sumerjabri** [comment]
Just noticed the same behavior for `build` for `studio`, where even `social` was being built.

**Comment by cortiz** [comment]
@sumerjabri Property should be `-PmoduleName=studio` **not** `-Pmodule=studio` (as per Readme)

**Comment by sumerjabri** [comment]
roger that
