### ISSUE TITLE
[studio-ui] Editorial Blueprint: Text duplication when editing a @crafter tag that contains a string

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5282]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-19e0b1`

#### Date of Build
`1/2/2022 1:16 p. m.`

#### Describe the bug
When editing a text field with a `@crafter` tag that contains an string, for example in the `article.ftl` from editorial blueprint: 

```
<@crafter.h2 $field="author_s">
    by ${contentModel.author_s!""}
</@crafter.h2>
 ```
According to @rart the snippet above is used incorrectly, should be:
```
<h2>
  by <@crafter.span $field"author_s">${contentModel.author_s!""}</@crafter.span>
</h2>
```
We weren't able to locate other sections in our blueprints where this issue might be present. 
#### To Reproduce
1. Create a site from editorial blueprint.
2. Preview an article page
3. Edit the author text field.
4. See error.

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/152060079-2199f513-17f4-4bed-961b-4ff3460ba987.mp4

![ftl_crafter](https://user-images.githubusercontent.com/90878288/152060458-795c5728-f9fc-41c9-bc75-ece61a7292b9.PNG)

**Comment by rart** [comment]
That line shouldn't be an H2. Please improve the markup.

**Comment by Euquimides** [comment]
Hi @jvega190! I updated and re-checked the issue, it is fixed now. I'm closing the issue. Thank you!
