### ISSUE TITLE
[studio-ui] Change `Template Name:` to `Content Type:`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5286]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2022/02/02

#### Describe the bug
In the content type editor, change `Template Name:` to `Content Type:`

#### To Reproduce
1. Open the content type Site Tool

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/152392687-476776f0-735b-45a8-bd4b-ee38ee0d8329.png)

**Comment by rart** [comment]
Update the legacy translation files that power that label
