### ISSUE TITLE
[studio-ui] Add a spacer to the PathNavigator for items that are not in workflow

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5289]
#### Is your feature request related to a problem? Please describe.
When an item enters workflow, it gets a workflow icon and shifts the item to the right. This can mislead the user into thinking the item is a child of the item above it.

#### Describe the solution you'd like
Add a spacer/icon or similar to space things out, like this:
![image](https://user-images.githubusercontent.com/3931908/152396692-dcb0d66f-e5db-4329-a6ab-985f782b00b5.png)

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by rart** [comment]
Let's try the ModeStandbyIcon with a tooltip that reads "Not in workflow"
`import ModeStandbyIcon from '@mui/icons-material/ModeStandby';`
