### ISSUE TITLE
[studio-ui] Dashes are removed when typing them in the Page URL field

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5294]
#### Crafter CMS Version
3.1.20

#### Date of Build
N/A

#### Describe the bug
When you type a dash (`-`) inside the Page URL field, and the dash is at the end of the input text, it's immediately removed.

#### To Reproduce
1. Open a page for edit in a site
2. Start typing alphanumeric text in the Page URL field, then type a dash.

You should observe the dash is removed immediately.

**Comment by Euquimides** [comment]
Hi @jvega190 and @avasquez614! I rechecked the issue in version ` v3.1.21-SNAPSHOT`, it is working fine now. Thank you! I'm closing the issue.
