### ISSUE TITLE
[studio-ui] Improve filters on authoring search

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5297]
#### Is your feature request related to a problem? Please describe.
Improve the labels and the configure-ability of the date range filters.

#### Describe the solution you'd like
Make the following updates:
- [x] Add ... avoid wrap on all labels for all filters
- [x] **Mime type**: Names should be shortened to common graphic names
- [x] **Content Size**: Handle NaN scenarios in a more user-friendly way.   
- [x] **Width, Height**: Handle Null scenarios in a more user-friendly way.
- [x] **Last Edit Date**: Labels should be used rather than keys with `-` in them
- [ ] **Last Edit Date**:  Date ranges should escalate in order from least to most
- [x] **Last Edit Date**: Can date ranges be made to be configurable? This is a stretch goal.
		
#### Describe alternatives you've considered
N/A

**Comment by aachavarria** [comment]
It is no possible to add a order prop to the facets via studio-config.yaml was not possible to filter the facets.
The facets are dynamics so it is not possible to order them via UI

**Comment by russdanner** [comment]
confirmed
