### ISSUE TITLE
[studio-ui] Use the same icon for Site Tools in Sidebar and Navigation Menu

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5308]
#### Is your feature request related to a problem? Please describe.
The `Site Tools` icon used in the Sidebar and the Navigation Menu is different

<img width="1232" alt="Screen Shot 2022-02-11 at 12 03 55 PM" src="https://user-images.githubusercontent.com/25483966/153651491-54c3d872-ad16-4d3a-b319-7b0b887b6446.png">

The `Publish Status` icon used in the Main Menu and at the top right is different

<img width="1233" alt="Screen Shot 2022-02-11 at 1 52 54 PM" src="https://user-images.githubusercontent.com/25483966/153653933-4187a0b4-aec8-4272-a7f9-e866c2b8f6ea.png">

#### Describe the solution you'd like
Use the same icon for Site Tools in Sidebar and Navigation Menu
Maybe use the same tool for the `Publish Status` in the Main Menu and at the top right too?

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by rart** [comment]
The publishing status icon is the same. No change required there.

**Comment by sumerjabri** [comment]
Please use the light (outline only) icon for the launcher. Ping me with any questions.
