### ISSUE TITLE
[studio] Studio should not add the Node JS based .gitignore for every site

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5309]
#### Crafter CMS Version
3.1.21

#### Date of Build
N/A

#### Describe the bug
Right now Crafter is adding automatically a `.gitignore` in the root folder of the repository when creating or upgrading a site. This `.gitignore` is intended for Crafter sites that build JS code with Yarn/Node JS tools. Since it's in the root folder, it's causing issues when creating folders/files in the repo with certain names, like `coverage` or `public`.

#### To Reproduce
1. Create a site based on Editorial or Empty
2. Go into `static-assets/images` and create a folder with name `coverage`. The folder is created BUT the `./keep` is not committed to the repo so Studio can't see it.

#### Expectations

- For new sites, Studio should only create this `.gitignore` under the `sources` folder of the repository, only if the folder already exists. - For existing sites, Studio should not remove the `.gitignore` from the root. Instead, we should clearly document in the release notes that this problem exists and that if the `.gitignore` exists in the site and it has not been edited before or has the exact Node JS `.gitignore` content.

**Comment by avasquez614** [comment]
We should not completely removed the default `.gitignore`. It should have at least this lines:

```
*.iml
.idea/*
.gradle/*

# Mac ignore list
.DS_Store

# Maven
target/*
```

**Comment by yacdaniel** [comment]
Verified fixed.
