### ISSUE TITLE
[studio-ui] Code editor should indicate if you are in edit mode or not

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5312]
#### Is your feature request related to a problem? Please describe.
The only way to know if you are in edit mode at the moment is: Can I type or not?

#### Describe the solution you'd like
Add a visual indication that you are in edit mode.

#### Describe alternatives you've considered
N/A

**Comment by rart** [comment]
We added additional visual cues as part of https://github.com/craftercms/craftercms/issues/5287

Please retest on the latest.

**Comment by sumerjabri** [comment]
@rart please update this and the navigation tool highlights we discuss to be visible across different types of hardware

**Comment by russdanner** [comment]
Enhancement is confirmed. I think the contrast may need a bit of a bump but assigned to Sumer for a second opinion.

**Comment by russdanner** [comment]
Assigned to Roy for update based on Slack discussion

**Comment by russdanner** [comment]
Confirmed.
