### ISSUE TITLE
[studio-ui] The edit mode button should be responsive

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5313]
#### Is your feature request related to a problem? Please describe.
Today the edit mode button in the toolbar stacks in an unplanned way.
<img width="908" alt="Screen Shot 2022-01-25 at 1 16 01 PM" src="https://user-images.githubusercontent.com/169432/153917965-9cca22a5-6128-4775-af27-32044e9985f9.png">

#### Describe the solution you'd like
Create a specific responsive layout for the buttons

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
Verified with @russdanner
