### ISSUE TITLE
[studio-ui] Explorer folders on sidebar should start collapsed as the default

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5314]
#### Is your feature request related to a problem? Please describe.
It's very busy when a user opens a site for the first time and all the explorer folders are opened up.

#### Describe the solution you'd like
Explorer folders on sidebar should start collapsed as the default

#### Describe alternatives you've considered
N/A

**Comment by rart** [comment]
@russdanner remember to clean local storage before validation or creating a new project

**Comment by russdanner** [comment]
<img width="1285" alt="Screen Shot 2022-02-25 at 11 51 10 AM" src="https://user-images.githubusercontent.com/169432/155754976-af9439aa-81b2-4b97-a57c-3eec8f309fbf.png">

Code folders are still defaulted open.

**Comment by sumerjabri** [comment]
Verified fixed.
