### ISSUE TITLE
[docs] Update all Elasticsearch examples to use the new client

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#5317]
Since Engine now includes the new ES client we need to update all existing docs to use it and add a section about migrating from the previous one.

Some of the docs that need to be updated:
- https://docs.craftercms.org/en/4.0/developers/cook-books/content-queries/basic-query-mechanics.html
- https://docs.craftercms.org/en/4.0/developers/cook-books/how-tos/migrate-site-to-elasticsearch.html
- https://docs.craftercms.org/en/4.0/developers/search-elasticsearch.html

Related to https://github.com/craftercms/craftercms/issues/5210

**Comment by alhambrav** [comment]
Updated the examples from editorial.  Assigned to @jdrossl to update the other examples
