### ISSUE TITLE
[studio-ui] Editorial Blueprint: Social Media widget issues

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5318]
Please update the social media widget in the header:
- [x] Limit the selectable icons to actual social media networks (create a taxonomy for the networks)
- [x] Add meaningful defaults to the required fields including the icon and URL of the repeat group items

**Comment by rart** [comment]
@jvega190 
- for the "click to add content", flip the order of the fields in it's registration so that $field="icon, url" instead of "url, icon".
- Clicking on the icon and then "edit", it's opening a blank form for me. Please check
