### ISSUE TITLE
[Studio] Available Actions: Author and publisher roles available actions include edit and delete templates, controllers and scripts

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5323]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-67f75e`

#### Date of Build
`15/2/2022`

#### Describe the bug
Authors and publisher roles available actions include edition and deletion of controllers, templates and scripts. According to the documentation, Publisher Role "(...) has the ability to approve and reject workflow", while the Author Role "(...) has access to create, edit and submit content". This might represent a risk in case authors or publishers edit or delete accidentally either templates or controllers. To specify the available actions in the UI for each role that might generate conflict:

**Author**

- [x]  In Homepage: _Edit Controller, Edit Template._

- [x] In Content Landing: _Edit Controller, Edit Template._ 

- [x] In Articles: _Edit Controller, Edit Template._ 

- [x] In Components (articles-widget for example): _Edit Controller, Edit Template._ 

- [x] Some folders available actions in sections like Taxonomy, Templates and Script includes Copy but not Paste.

**Publisher** 

- [x] In Homepage: _Edit Controller, Edit Template._

- [x] In Category Landing: _Edit Controller, Delete Controller, Edit Template, Delete Template_

- [x] In Articles: _Edit Controller, Delete Controller, Edit Template, Delete Template_

- [x] In Components (articles-widget for example): _Edit Controller, Delete Controller, Edit Template, Delete Template_ 

#### To Reproduce
1. Create a user or log in as a user either with Author or Publisher role.
2. Go to 'Editorial Site' and then enable 'Site Explorer'
2. Click on 'Options' or right-click on 'Home', an article or on a component like 'articles-widget' to see the available actions.
4. See the error

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/154167217-4241b91f-0527-4276-a059-6b6ef1943e96.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2907

**Comment by sumerjabri** [comment]
@Euquimides please don't validate until the PR is merged, it may take a bit of time.

**Comment by jdrossl** [comment]
@Euquimides the fix is merged now, you can go ahead and verify it

**Comment by Euquimides** [comment]
Hi @jdrossl! I updated and re-checked the issue. Seems Author has now the correct available actions enabled, but Publisher still has access to Edit and Delete both Templates and Controllers. According to the documentation available, Publisher should not be able to access to code or admin features. Returning the ticket back to you. Thank you!

**Comment by Euquimides** [comment]
Hi! I updated and re-checked the issue. The Publisher role available actions is now correct. Thank you! Closing this ticket.
