### ISSUE TITLE
[studio] Workflow States: Error in filter regex of Workflow States when adding '*' or '[' characters

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5331]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-00a3b0`

#### Date of Build
`21/2/2022`

#### Describe the bug
When adding characters like '*' or '[' to the regex path filter of Workflow States inside Project Tools, a React error is shown and the Project Tools form stops working. You can still close the form with the dismiss button.

#### To Reproduce
1. Go to 'Project Tools' in a project (site) of your choosing.
2. Click on 'Workflow States'
3. Click on 'Filters' then in 'Path (regex)'
4. Input with your keyword either '*' or '['.
5. See the error

#### Logs
Browser debugger shows a HTTP 500 messag for the workflow/item-states API, along with the next response: 
``{
	"response": {
		"code": 1000,
		"message": "Internal system failure",
		"remedialAction": "Contact support",
		"documentationUrl": ""
	}
}``

#### Screenshots
![imagen](https://user-images.githubusercontent.com/90878288/155042037-7c490951-2631-4259-8f51-2866f7bb930d.png)

**Comment by Euquimides** [comment]
Hi @sumer! I was checking again, and this seems to be an API issue. The backend is not handling this chars correctly:

REQUEST: `GET http://qa-small.craftercms.org/studio/api/2/workflow/item_states?siteId=a1&path=*`

RESPONSE: ``{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}``

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2903

**Comment by Euquimides** [comment]
Hi @dejan-brkic! I was checking in Studio and the error is still presenting. Also, I noticed that the code is not merged. Could you check it out please. Thank you!

**Comment by sumerjabri** [comment]
@Euquimides we're still reviewing the PR, please check the above PR and when it turns merged it'll be ready to validate. Thanks.

**Comment by Euquimides** [comment]
Hi @rart! Please fix the UI when the `workflow/item_states` API is returning HTTP 400, after adding the `*` char as path regex. Thank you!

**Comment by Euquimides** [comment]
Hi! Updated and re-checked the issue in Crafter `4.0.0-SNAPSHOT-ac4cc8`, build date `3/18/2022`. Working fine now, thank you! Closing this ticket.
