### ISSUE TITLE
[studio-ui] [3.1] Preview Image upload failed

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5332]
#### Crafter CMS Version
 Crafter CMS v3.1.22-SNAPSHOT

#### Date of Build
Feb 22, 2022

#### Describe the bug
Upload preview image for content-type failed with an error in console. The message box showing that the image has been uploaded freezes 

#### To Reproduce
1. Create a site with any BP
2. Click a component content-type 
3. Click upload to "Preview Image" and select an image from the local machine
4. Notice that the screen is frozen and there is an error in the console:

#### Logs

```
[Uppy] [16:33:44] Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
```

#### Screenshots
![2022-02-22_16-34](https://user-images.githubusercontent.com/2996543/155104715-3426f1e9-b0fa-48ec-8a87-506681850f34.png)

**Comment by jvega190** [comment]
Only happens in 3.1.x, 4 is good

**Comment by phuongnq** [comment]
verified
