### ISSUE TITLE
[studio] Bulk publish on first publish issues

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5334]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-00a3b0`
#### Date of Build
`2022/02/22`
#### Describe the bug
There seems to be some inconsistency with the bulk publish on first publish

- [x] `published` repo is created, files added but no commit on the repo.
- ~~API `publish/status` doesn't seems to report anything when doing this first publish, status is always `ready`~~ No longer relevant and will be handled in a new ticket.

#### To Reproduce
1. Create a site from any bp
2. Publish Home page
3. ~~Immediately after publishing, keep calling the `/publish/status` API to notice a different response in the status.~~ No longer relevant and will be handled in a new ticket.

#### Logs
N/A
#### Screenshots
![image](https://user-images.githubusercontent.com/6722074/155232164-a40660d4-35a6-4239-b06c-d6f9082b904f.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2883

**Comment by yacdaniel** [comment]
Verified fixed.
