### ISSUE TITLE
[studio-ui] Add button in canned search is added twice

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5335]
#### Crafter CMS Version
3.1.21

#### Date of Build
N/A

#### Describe the bug
The `+add` button of a canned search is added twice when navigating in and out of search.

#### To Reproduce
1. Create a site base on Editorial
2. Go to the sidebar configuration and add the following canned search for `Pages` root folder:

```
                                        <cannedSearches>
                                            <cannedSearch>
                                                <path>/site/website/articles</path>
                                                <insertAs>replaceAllChildFolders</insertAs>
                                                <label>All Articles</label>
                                                <newPath>/site/website/articles</newPath>
                                                <style>search</style>
                                                <queryParams>
                                                    <queryParam><name>page</name><value>1</value></queryParam>
                                                    <queryParam><name>sortBy</name><value>last-edit-date</value></queryParam>
                                                    <queryParam><name>view</name><value>grid</value></queryParam>
                                                    <queryParam><name>mode</name><value>default</value></queryParam>
                                                    <queryParam><name>csf_content-type</name><value>/page/article</value></queryParam>
                                                    <queryParam><name>path</name><value>/site/website/articles/.+</value></queryParam>
                                                </queryParams>
                                            </cannedSearch>
                                        </cannedSearches>
```

3. Go back to the dashboard or preview
4. Expand the articles folder and click on the All Articles canned search. 
5. Click on one of the articles in the search result to open it in preview
6. Click on one of the menu categories (`Style`, `Health`, etc)
7. Click on one of the articles from the category to see it in preview

The article will be loaded and the sidebar will be refreshed. You should notice that the canned search now has the `+add` link twice.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/155234802-df28e07f-0efd-4b28-a230-9994d71ebb56.png)

**Comment by sumerjabri** [comment]
PR for 3.1 https://github.com/craftercms/studio-ui/pull/2845

**Comment by rart** [comment]
@jvega190 port to 4 once merged into 3.1.x

**Comment by avasquez614** [comment]
Verified in 3.1

**Comment by avasquez614** [comment]
Canned search is not used in 4. Closing this ticket.
