### ISSUE TITLE
[studio] Item locking APIs not working as expected

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#5338]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-2f46e7

#### Date of Build
Build Number:
2f46e7674fc93705dc03ce3ec08f56d8d8c12d7d

#### Describe the bug
- [x] Attempting to lock an item already locked by other user is not rejecting the request and _relocks_
  - If an item is already locked, response should be 409
  - Steps to reproduce the behavior:
      1. Using a Admin lock a item
      2. Using a Author try to lock the same item
      3. Check the response
      4. The item is locked for the last user
- [x] Switch API `items_unlock_by_*` to from bulk to single `item_unlock_by_*`
- [x] Attempting to unlock a path that doesn't exist should 404
- [x] Unlock should not unlock based on whether you have the unlock permission
- [x] Unlock should 404 if path doesn't exist
- [x] Unlock should 409 if the file isn't locked

#### Logs
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.26#/content/itemsLockByPath

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2885

**Comment by aachavarria** [comment]
verified
