### ISSUE TITLE
[studio-ui] add row table control in RTE adds row and duplicates inner markup

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#534]
When working on a table in the RTE and using the toolbar options to insert a row or column before/after, any hyperlink structure in the selected row/column are copied to the new row/column without the text. 

It's basically creating an empty <a href></a> tag.

to reproduce
1. Create a table
2. Create a row
3. Add text and hyper link it
4. Click add row below/above (add to RTE config if need be)
5. Enter HTML mode and note row was added along with structural markup

Note that this needs to be looked at carefully.  While duplicating an empty A tag is not useful other markup may be meaningful.

**Comment by sumerjabri** [comment]
Validate if this is fixed by #793

**Comment by sumerjabri** [comment]
@russdanner please see if this still happens in RTE 5.

**Comment by russdanner** [comment]
Confirmed
