### ISSUE TITLE
[studio-ui] Sidebar highlight color in dark mode is unusable

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5340]
#### Crafter CMS Version
4.0.rc2-snapshot

#### Date of Build
3/25/2022

#### Describe the bug
 Sidebar highlight color in dark mode is unusable

#### To Reproduce
N/a

#### Logs
N/A

#### Screenshots
<img width="1276" alt="Screen Shot 2022-02-25 at 11 56 50 AM" src="https://user-images.githubusercontent.com/169432/155755970-64fe2a1e-7c87-4e08-970e-d7add788a656.png">

**Comment by sumerjabri** [comment]
Fixed.
