### ISSUE TITLE
[studio-ui]Spinner spins continuously after selecting "Item Name" in the dashboard of a fresh site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#535]
Create a new site.
Open the dashboard, then select the checkbox next to "Item Name" under "Recently Published" or "My Recent Activity"
Spinner will keep on spinning and clicking on other items in the dashboard does not do anything

![empty-item-name-selection](https://cloud.githubusercontent.com/assets/25483966/23691349/dbe9438e-0395-11e7-9de8-c857a726f87b.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/287

**Comment by vestrada** [comment]
Done
