### ISSUE TITLE
[studio-ui] Studio UI shows the delete button to site admins

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5352]
#### Crafter CMS Version
3.1.22

#### Date of Build
N/A

#### Describe the bug
When you log into Studio as someone with the `site_admin` group, the delete button (trash icon) is available and you can try to delete the site

#### To Reproduce
1. Create a site
2. Login as a `site_admin`

You should see the delete site button, and you can click on it and try to delete the site. The delete popup just hangs and if you check the browser console you should see a 401 Unauthorized error.

**Comment by jdrossl** [comment]
@sumerjabri @rart 

This is not reproducible in 4.0

In 3.1 it is a UI issue, the backend checks if the user belongs to the `system_admin` group so the UI should do the same

**Comment by jvega190** [comment]
@dejan-brkic will update the upgrade manager to include `site_delete` permission in global config

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2893

**Comment by jvega190** [comment]
@sumerjabri I tested the upgrade manager update and it's working

**Comment by jvega190** [comment]
@sumerjabri removing from 4.0.x since is not reproducible due to different mechanics

**Comment by yacdaniel** [comment]
Verified fixed
![image](https://user-images.githubusercontent.com/6722074/165333342-853e0871-994e-4505-83c9-de794463094a.png)
