### ISSUE TITLE
[studio] Deleting content with new state shouldn't goes into publishing.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5353]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-581c77`
#### Date of Build
`03/03/22`

#### Describe the bug
When an user deletes content that has the new state, the content goes though the publishing system as a delete. Studio should not sent the new content that is deleted though publishing. 

#### To Reproduce
1. Create a site from Editorial BP
2. Delete a page
3. Check `Project Tools - Publishing - Publishing Queue` and filer by `All ` state
4. See the deleted content in the publishing queue. 

#### Logs
N/A

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
I discussed this with @russdanner and decided to address this via Recycle Bin when that feature is built out.
