### ISSUE TITLE
[studio] Cannot search for keywords in internal names

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5354]
#### Crafter CMS Version
3.1.22

#### Date of Build
N/A

#### Describe the bug
You can't search articles by keywords in internal names.

#### To Reproduce
1. Create a site based on Editorial
2. Create a new article. Add `SC 2019 Bouncer` as the internal name, then fill the rest of the article with anything except for the keywords in the internal name
3. Go to Studio search and search for `bouncer`

No results should appear

NOTE: This is only an issue for 3.1, 4.0 doesn't have this issue

**Comment by jdrossl** [comment]
@avasquez614 for existing sites the authoring index needs to be recreated

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is not present in v4.0. Closing this ticket.
