### ISSUE TITLE
[studio-ui] XB react - Sorting a component using the ZoneMarker drag icon not working properly

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5358]
#### Crafter CMS Version
4.0.0-SNAPSHOT-961edf

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
When moving/sorting a component on a react app with XB, using the drag icon that shows when highlighting a component, it finishes the action but the xb freezes

#### To Reproduce
4. See the error

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by rart** [comment]
Verified.
