### ISSUE TITLE
[studio-ui] Add a way to unselect/select all children when copying a page or folder

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5361]
#### Is your feature request related to a problem? Please describe.
When copying a page or folder with children, when the Copy popup appears, there's no way to just copy the actual page or folder without having to unselect every single child. This becomes a big problem when you have hundreds of children underneath the page/folder 

#### Describe the solution you'd like
Add a way to unselect/select all children when copying a page or folder. It's understandable that you can't unselect all the children by unselecting the parent because it can introduce issues by letting the user then select children to copy without having the parent selected. So maybe a link on the bottom to allow unselecting/selecting all children might be the best solution.

**Comment by sumerjabri** [comment]
@russdanner why not just have a single checkbox to select all children or not? This is a big deal for many reasons.

**Comment by Euquimides** [comment]
Hi! Updated and tested the new feature. It is working as an two actions `Copy`, which copy only the parent and `Copy with children`, which copy parent and children. So the feature request is done. Closing this ticket.
