### ISSUE TITLE
[studio-ui] Paste request is missing children when pasting an tree with more than 2 level depth

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5363]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-22d829`
#### Date of Build
`03/07/22/`

#### Describe the bug
When an user copy and paste a tree with more than 2 level of children, the request to paste is missing the last children. 

#### To Reproduce
1. Copy `Health` and paste it under `Technology`
2. Copy `Health ` again and paste it under `Technology - Health`
3. Copy `Technology`, select all the children and paste under `Style`
4. Expand `Style`

#### Logs
Local Storage
`craftercms.admin.clipboard.77996aab-0587-4017-b01c-c964f239912d` ->`{"type":"COPY","sourcePath":"/site/website/technology/index.xml","paths" ["/site/website/technology/index.xml","/site/website/technology/health/index.xml","/site/website/technology/health/health/index.xml"],"timestamp":1646666764896}`

Payload of Paste request.

 ```
{
    "siteId": "editorial",
    "operation": "COPY",
    "targetPath": "/site/website/style/health.xml",
    "item": {
        "path": "/site/website/technology/index.xml",
        "children": [
            {
                "path": "/site/website/technology/health/index.xml",
                "children": []
            }
        ]
    }
}
```

#### Screenshots
https://user-images.githubusercontent.com/6722074/157066816-42125d82-0cad-4c13-8379-2a98f0a2b857.mp4

**Comment by Euquimides** [comment]
Hi! Updated and re-checked the issue. Children are now appearing correctly in trees with more than 2 levels. Thank you! Closing this ticket.
