### ISSUE TITLE
[studio-ui] Disable the display of Folder states in the UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5367]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2022-03-08

#### Describe the Issue
Folder states are not tracked in the backend at this time, we need the UI to not display those. Please hide those.

Ping me with any questions.

**Comment by Euquimides** [comment]
Hi @sumerjabri! Important to take into consideration: folder states can be set through POST `workflow/item_states` API.

**Comment by rart** [comment]
@sumerjabri what's to do here? Last time we reviewed, everything looked correct and you took the ticket back. What's the latest development?

If we do this, is the idea to add an empty space on the workflow status icon slot? Like we considered and didn't like for the "not in workflow state".
