### ISSUE TITLE
[studio-ui] Page URL name can go outside the input field boundaries of the Content Form, through multiple copy and paste actions

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5373]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-bd1c0d`

#### Date of Build
`3/11/2022`

#### Describe the bug
If you create a tree by duplicating, copying and pasting content multiple times, you will reach a point were the Page URL go outside the input field boundaries, being unable to edit the Page URL anymore. 

#### To Reproduce
1. Create a Page Content Type (Page A) in a site of your choosing, give the Page URL a name with maximum length (50 characters).
2. Duplicate it (Page A (Copy - 1)), cut the new copied file and paste it inside the newly created content.

`Page A`
|_______`Page A (Copy - 1)`

4. Keep copy and pasting content, creating a tree. You will reach a point were the Page URL name inside the Content Form goes outside the input field boundaries. 

#### Logs
N/A

#### Screenshots
![Screenshot from 2022-03-11 17-17-44](https://user-images.githubusercontent.com/90878288/157987318-a28dcbb9-a81b-453b-8567-bb14b3340026.png)

**Comment by rart** [comment]
@jvega190 make sure the whole control click would place the focus on the input; not just the label inside the element that simulates an input but the element itself too.

**Comment by Euquimides** [comment]
Hi! I updated and re-checked the issue. It is fixed. Thank you! Closing this ticket.
