### ISSUE TITLE
[studio-ui] Add option to create site from single branch

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5374]
#### Is your feature request related to a problem? Please describe.
Creating a site from a single branch improves the performance of the Git repository when the repository has a lot of branches since only the cloned branch is fetched. Studio BE already supports it  (check the `single_branch` parameter in https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/create-site.html) in the create site API but the UI doesn't provide a way to select it.

#### Describe the solution you'd like
Add an option in the UI to create a site from a remote Git repository using a single branch.

**Comment by sumerjabri** [comment]
@avasquez614 we should validate this improves things.

**Comment by sumerjabri** [comment]
@avasquez614 is this still required?

**Comment by sumerjabri** [comment]
Duplicate project addressed the core issue.
