### ISSUE TITLE
[studio-ui] Allow specifying a prefix to use with the S3 datasource

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5377]
#### Is your feature request related to a problem? Please describe.
S3 datasources use the aws.xml configuration to connect to S3. The AWS configuration, unfortunately, doesn't allow to specify a root prefix where the datasources can start looking at, so currently the prefix is baked into the asset paths. This prevents being able to have different aws.xml configurations per environment or per publishing target

#### Describe the solution you'd like
Add a `<prefix>` configuration to allow to specify a root prefix for the AWS profile.

**Comment by yacdaniel** [comment]
@sumerjabri the prefix is working with `GET /aws/s3/list` but `POST/aws/s3/upload` is returning an error. 
https://gist.github.com/yacdaniel/5720b9f4a47fcd4f38e3cd6b72a25f05

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.1-SNAPSHOT`
