### ISSUE TITLE
Add email notification on successful publish within Studio

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5378]
#### Is your feature request related to a problem? Please describe.
Today it is possible to get an email notification on the following events:

1. From Studio, On Approval 
2. From Studio, On Reject
3. From Studio, On Publish failure
4. From Deployer, On deploy event

There is no email to notify a submitter that a publish within Studio was performed successfully.  This notification would be particularly useful to users waiting for a scheduled publish event.  Today they receive notice that the approval occurred but do not get a notice when the publish occurs.

#### Describe the solution you'd like
Add a publish operation success message to the notification service that is sent to the requester and approver at the time content is successfully published.

#### Describe alternatives you've considered
A basic workaround is to use the deployer processor pipeline to email publish notifications when successfully received. 
The limitation of this approach is the following:
-  the submitter is not known by the deployer component.  Notification must be sent to a list-style account or a list of accounts.
- One must take care to ensure that multiple deployers do not send a notification each.

**Comment by sumerjabri** [comment]
This will be handled by the end-to-end publishing visibility work.
