### ISSUE TITLE
[studio-ui] Remote Repositories section in Project Tools is force pushing to remote repositories by default

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5379]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-d07bf6`

#### Date of Build
`3/15/2022`

#### Describe the bug
In Crafter 4.0, on Remote Repositories, inside Project Tools, you con add, push and pull repositories. Right now, force push is enabled by default for remote repositories, which represents a risk since you can push to production branch something that is in a lower environment. 

#### To Reproduce
1. Create a non-empty repository in GitHub (a new repository with a README file for example).
2. Go to 'Project Tools'
3. Click on 'Remote Repositories'
4. Click on 'New Remote' and add the newly created non-empty repository to it.
5. Click on 'Push'.
6. Check your repository and see the changes. 

#### Logs
If you check the REQUEST of `repository/push_to_remote`API, you'll notice `force:true` which means force push is enabled:

```
{
  "siteId":"a1",
  "remoteName":"origin1",
  "remoteBranch":"master",
  "force":true
}
```

#### Screenshots
N/A

#### Solutions or Alternatives

Force push option should be `false` by default. Add to Studio's Remote Repositories UI, a checkbox that allows the user to set force push to remote repositories to true if he or she is entirely sure.

**Comment by sumerjabri** [comment]
@rart please add a checkbox to select `force push` or not and warn the user with "Force push will overwrite what's in the remote repository, are you sure?" or a similar mechanism.

**Comment by Euquimides** [comment]
Hi! Tested the new UI for remote repositories in Crafter `4.0.0-SNAPSHOT-ac4cc8`, build date `3/17/2022`, with GitLab and Github. It is working fine. Thank you! Closing this ticket.
