### ISSUE TITLE
[studio-ui] The browse window for pickers cuts out the tree when the tree is deep

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5384]
#### Crafter CMS Version
3.1.22

#### Date of Build
N/A

#### Describe the bug
The browse window for image pickers (and possible under pickers) cut's out the file tree when the tree is deep

#### To Reproduce
1. Create a site based in Editorial
2. Under the images folder of static assets create at least a folder hierarchy with 6 folders with very long names
3. Upload an image under the last folder
4. Open the Home page and replace the Hero image
5. Browse to the image you just uploaded

You should notice some of the names of the folders deep in the hierarchy are cut and there's no way to scroll to see their full names

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/158902432-156bdb40-34c7-4201-82a5-d50760a9e9ba.png)

**Comment by jvega190** [comment]
@avasquez614 ready for testing in 3.1.x

**Comment by Euquimides** [comment]
Hi! Updated and re-checked the issue v3.1. Assigning it back to @jvega190 update the left panel height styles per discussion in call.

**Comment by Euquimides** [comment]
Hi @jvega190 ! This issue is also present in v4.0.
![Screenshot from 2022-04-26 14-14-13](https://user-images.githubusercontent.com/90878288/165385348-2f91e565-7a27-4300-ab1b-c97f5b23ab8b.png)

**Comment by jvega190** [comment]
Hi @Euquimides, this is ready for testing in 3.1.x

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue in v3.1.x. It is fixed, thank you. Pending the fix for v4.0

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed. Thank you! Closing this ticket.
