### ISSUE TITLE
[studio-ui] Cancelling "Insert Desktop Images" from the RTE resizes the form

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#539]
In an RTE, click on the 'Insert Image' icon
Select 'Desktop Images'
![rte-select-desktop-image](https://cloud.githubusercontent.com/assets/25483966/23720454/b903f284-040c-11e7-9f9f-ea72849e61ef.png)

Select 'Cancel'
![rte-select-cancel](https://cloud.githubusercontent.com/assets/25483966/23720534/f2f3d64e-040c-11e7-8faa-75055ba3499a.png)

Notice the form was resized (smaller) instead of remaining the same size before trying to insert an image
![rte-select-desktop-image-cancelled](https://cloud.githubusercontent.com/assets/25483966/23720462/bd9b84e2-040c-11e7-90b5-eb8fb57729e0.png)

**Comment by alhambrav** [comment]
I am using Chrome for my browser.  I also tried it in Safari and same behavior, form is resized after canceling "Upload Images" from the "Insert Image" RTE tool.

Here's some updated screen captures of the form resized too small after cancelling an image upload from the RTE:

1. Click on the pencil shown in the image below:
![step1](https://cloud.githubusercontent.com/assets/25483966/24737472/f990ba60-1a5c-11e7-801f-c172af72b5d7.png)

2. Click on the Hero Text field to see the RTE toolbar.  Notice the size of the form:
![step2](https://cloud.githubusercontent.com/assets/25483966/24737510/49f06d2a-1a5d-11e7-807b-4986aff67110.png)

3. Click on "Insert Image" from the RTE toolbar, the select "Upload Images":
![step3](https://cloud.githubusercontent.com/assets/25483966/24737572/cbba30e8-1a5d-11e7-82f6-298b06865a24.png)

4. Click on "Cancel" on the Upload form:
![step4](https://cloud.githubusercontent.com/assets/25483966/24737602/ee13e652-1a5d-11e7-94f9-fb7be4c98e0a.png)

5. Notice the form size after cancelling the Image Upload from the RTE:
![step5](https://cloud.githubusercontent.com/assets/25483966/24737717/c2df768a-1a5e-11e7-8c6d-33a74f63b94a.png)

**Comment by jvega-crafter** [comment]
Now I'm able to reproduce it, thanks! It happens only when editing from in context edit, not regular page edit. Working on it now

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/341
