### ISSUE TITLE
[engine][studio] Sites served by an IPv6 address cannot store cookies

### ISSUE THREAD

**Issue by rakuten-akadric** [craftercms/craftercms#5395]
#### Crafter CMS Version
3.1.15

#### Date of Build
N/A

#### Describe the bug
If you have a site that is internally hosted on an IPv6 network without DNS resolution, the Set-Cookie Domain property will always be set to that IPv6 address which is not supported by the Set-Cookie specification. This will result in an invalid Domain error and the cookie not being stored.

I think this can be fixed if the logic here was updated to allow the user to force the Domain to not be set if the `crafter.engine.response.cookie.domain` is false or something similar: https://github.com/craftercms/engine/blob/ad1bf803d9fec75f9e23978a727fcf9966234cc6/src/main/java/org/craftercms/engine/servlet/interceptor/SiteCookieChangeInterceptor.java#L90

Set-Cookie specifciation: https://datatracker.ietf.org/doc/html/rfc6265#section-5.1.3

#### To Reproduce
1. Host a site on localhost
2. Load any site from the delivery service using [::1] address
3. Check the network tab in your browser and you will the cookie invalid domain error
4. However the same request will work if you use localhost or 127.0.0.1

#### Logs
N/A

#### Screenshots
<img width="749" alt="Screen Shot 2022-03-24 at 1 14 58" src="https://user-images.githubusercontent.com/85272273/159745915-bc82eb1e-2683-4b72-8087-59906fcbcb12.png">

**Comment by jdrossl** [comment]
@sumerjabri this is working as expected in 4.0
![Screenshot from 2022-04-06 11-07-13](https://user-images.githubusercontent.com/1236955/162029588-8a1e173b-f1a0-4e0a-a271-9fce52ef81b8.png)

**Comment by sumerjabri** [comment]
Works in v4 as shown above.
