### ISSUE TITLE
[studio-ui] get-items-tree.json API is called even use canned search with option replaceAllChildFolders

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5396]
#### Crafter CMS Version
3.1.22

#### Date of Build
Mar 24, 2022

#### Describe the bug

Sidebar tree view tries to fetch all children even if the node is used as canned search with `replaceAllChildFolders` option

#### To Reproduce
1. Create a new site
2. Setup a folder to use the canned search with `replaceAllChildFolders` option
3. Click to open folder in step 2
4. Notice that get-items-tree.json is called even we don't need to.

**Comment by sumerjabri** [comment]
Validated by @avasquez614
