### ISSUE TITLE
[studio-ui] Very large trees causes listed items in "Copy" dialog to go outside UI dialog bounds. 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5398]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-8218f7`

#### Date of Build
`3/24/2022`

#### Describe the bug
Creating large trees with lots of children causes listed items to go outside the dialog bounds, when selecting `Copy` action. The dialog functionality still works. 

#### To Reproduce
1. Create a project with any BP, can be Editorial BP. 
2. Enter the newly created site and create a really large tree by copy-pasting content and folders (50+ children). 
3. Click on `Copy` action on the respective content-folder tree. 
4. See the error

#### Logs
N/A

#### Screenshots
![Screenshot from 2022-03-24 14-39-37](https://user-images.githubusercontent.com/90878288/160006524-364dc27d-0128-4956-bf2d-4306ff3c6c26.png)
![Screenshot from 2022-03-24 14-40-12](https://user-images.githubusercontent.com/90878288/160006527-fba807cc-893b-4d26-bf6a-bfc36e15db24.png)
![Screenshot from 2022-03-24 14-39-08](https://user-images.githubusercontent.com/90878288/160006519-46e5df03-16d3-4461-846c-9010b9a5fc82.png)

**Comment by sumerjabri** [comment]
https://github.com/craftercms/craftercms/issues/5407 will fix this issue since it eliminates the dialog.

Related to: https://github.com/craftercms/craftercms/issues/5408
