### ISSUE TITLE
[studio] Users appear multiple time in get-all if present in multiple sites

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#540]
When using this API http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users.html

And the users are in multiple sites, I see the users repeated, like this:

`{
"users": [
{
"last_name": "admin",
"sites": [
{
"site_name": "Studio Root",
"site_id": "studio_root",
"groups": [
{
"group_name": "crafter-admin"
},
{
"group_name": "crafter-create-sites"
}
]
}
],
"first_name": "admin",
"email": "evaladmin@example.com",
"username": "admin"
},
{
"last_name": "Jabri",
"sites": [
{
"site_name": "123",
"site_id": "123",
"groups": [
{
"group_name": "Author"
}
]
}
],
"first_name": "Sumer",
"email": "sumer.jabri@gmail.com",
"username": "sumer"
},
{
"last_name": "admin",
"sites": [],
"first_name": "admin",
"email": "evaladmin@example.com",
"username": "admin"
},
{
"last_name": "Jabri",
"sites": [],
"first_name": "Sumer",
"email": "sumer.jabri@gmail.com",
"username": "sumer"
}
]
}`

**Comment by dejan-brkic** [comment]
fixed PR #568
