### ISSUE TITLE
[studio] Nested content is not being correctly deleted by content/delete API, returns HTTP 500

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5412]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-da14c7`

#### Date of Build
`3/28/2022`

#### Describe the bug
The `content/delete` API returns HTTP 500 when trying to delete nested content or content ordered in trees. After trying to delete the content, it will be transformed into a `folder`.

#### To Reproduce
1. Create a new project with a blueprint of your choice, it can be Editorial.
2. Create new content, in case you are using Editorial blueprint, choose `Category Landing`(Content A).
3. Inside the newly created `Category Landing` content, create another `Category Landing` content (Content B).

`Content A`
|__________`Content B`

5. Try deleting `Content A`.
6. See error.

#### Logs
The POST `content/delete` API returns HTTP 500:
```
{"response":{"code":1000,"message":"Internal system failure","remedialAction":"Contact support","documentationUrl":""}}
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/160456227-677d5a48-1071-4598-a8cf-c848dcd1ac3f.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2915

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now, thank you! Closing this ticket.
