### ISSUE TITLE
[studio] The content/write_content.json API 1 is returning HTTP 500, when uploading an image to new content after previously creating new content

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5414]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-7354ae`

#### Date of Build
`3/28/2022`

#### Describe the bug
If you upload an image through the `Content Form` to a new content, after previously creating a new content, the image won't be uploaded and the content/write_content.json API 1 will return HTTP 500 related to a null object. 

#### To Reproduce
1. Go to a site, preferably Editorial. 
2. Click on `Quick Create`, select `Article`.
3. Fill up the `Content Form`.
4. On `Image` upload an image of your choice.

**IMPORTANT**: You must repeat this process a second time to notice the error. 

#### Logs
Crafter Authoring `catalina.out` logs, show the next error:
```
[ERROR] 2022-03-28T17:03:53,099 [http-nio-8080-exec-1] [rest.RestScriptsController] | Error executing REST script at /scripts/rest/api/1/content/write-content.post.groovy 
org.craftercms.engine.exception.ScriptException: Cannot invoke method isDeleted() on null object
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/160502706-e287d031-786c-4d14-a726-8780525178d7.mp4

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2921

**Comment by Euquimides** [comment]
Hi! I updated and re-checked the issue. The API is not returning HTTP 500 and there is no more issues when uploading images to content. Thank you! Closing this ticket.
