### ISSUE TITLE
[studio] Rename of folders aren't published correctly

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5416]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-91f522`
#### Date of Build
`3/29/2022`
#### Describe the bug
When a folder is renamed in any section(Pages, Components, Scripts, Assets, Templates), the rename goes to `sandbox` but is not propagated to `published`
#### To Reproduce
1. Create a site from any BP
2. Bulk publish the site
3. Rename a folder from Studio UI
4. Publish the site again.

#### Logs
```
❯ ls crafter-authoring/data/repos/sites/ed/sandbox/scripts/
classes  components2  pages2  rest
❯ ls crafter-authoring/data/repos/sites/ed/published/scripts
classes  components  pages  rest
```
#### Screenshots
N/A

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2926
