### ISSUE TITLE
[studio-ui] UI doesn't refresh correctly when renaming a folder in Scripts/Templates

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5419]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-91f522`
#### Date of Build
`3/29/2022`
#### Describe the bug
When a folder in `Scripts` or `Templates` is renamed, the UI doesn't refresh correctly. 
#### To Reproduce
1. Create a site from any blueprint
2. Rename a folder under `Templates` or `Scripts`
3. See the error

#### Logs
N/A
#### Screenshots
https://user-images.githubusercontent.com/6722074/160892997-fc3d20c8-52c6-4434-aabe-02147b1e5695.mp4

**Comment by jvega190** [comment]
@yacdaniel ready for testing, please consider this issue https://github.com/craftercms/craftercms/issues/5427

**Comment by yacdaniel** [comment]
Verified fixed.
