### ISSUE TITLE
[studio] Compare versions not working

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#542]
Change a content item and compare with earlier version, you'll get a 500 error.

**Comment by dejan-brkic** [comment]
This is UI issue. It is sending wrong parameter values.

Compare with current request via icon on right-hand side in version list (works fine):
http://localhost:8080/studio/diff?site=mySite&path=/site/website/index.xml&version=368d67abf1b5903779d84e98da0fa3fa85ca1f5a&mode=iframe

Compare two versions via Compare button and two previous versions selected (500 error):
http://localhost:8080/studio/diff?site=mySite&path=/site/website/index.xml&version=3/22/2017T8:22:09PM&version=3/21/2017T10:47:26PM&mode=iframe

First request is sending commit id as version value. Second request is sending datetime as version value.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/304
