### ISSUE TITLE
[studio] Item available actions are including edit after publishing, even though item is locked

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5422]
#### Crafter CMS Version
4.0.0-SNAPSHOT-eab8f3

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
When an item has been published, if one user locks the item, another user will see that the item is locked but will still get the edit action as available for that item.

#### To Reproduce
1. In editorial blueprint, having two browsers with different users logged in, publish 'Style' and then edit it so the item will lock (with user1).
2. With user two, reload and open the item menu for 'Style'.
3. See how the item menu shows that the item is locked but still shows 'Edit'.

* For step 2, reload will no longer be needed after https://github.com/craftercms/craftercms/issues/5417 is merged.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2928

**Comment by jvega190** [comment]
Verified fixed
