### ISSUE TITLE
[studio-ui] Cleanup Studio configuration files that are not needed in v4. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5431]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-b97f5d`
#### Date of Build
`4/4/2022`
#### Describe the bug
There are some configuration files that are not needed because the functionality is now in the `User Interface Configuration`
Please review and make sure the unnecessary files are removed. So far I found:

 - [ ] Code Editor Configuration

#### Logs
N/A
#### Screenshots
N/A

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/5523
