### ISSUE TITLE
[studio-ui] After fetching DetailedItem, if there's a change on a request publishing date it won't update in another browser/user

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5433]
#### Crafter CMS Version
4.0.0-SNAPSHOT-b97f5d

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
After fetching DetailedItem, if there's a change on a request publishing date it won't update in another browser/user

#### To Reproduce
1. Having two browsers with different users logged in (in editorial site), go with user1 and request publish a page using a 'later' date.
2. With user2 (admin privileges), go and open the publish dialog for the requested page, see the set date.
3. Again with user1, request publish the same page but with a different date.
4. With user1 (do not reload), open again the publish dialog for that page. See how the old date still shows.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by sumerjabri** [comment]
@yacdaniel please help validate this ticket.

**Comment by yacdaniel** [comment]
Verified fixed.
