### ISSUE TITLE
[studio] Sending POST request with "staged":false as parameter to workflow/item_states API returning empty state

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5435]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-b97f5d`

#### Date of Build
`4/4/2022`

#### Describe the bug
When you send a POST request with `staged:false` as a parameter to `workflow/item_states` API, later a GET request to `/workflow/item_states` against the same item, returns the state `1024` which is an empty state. When you don't send this parameter or its value is true, the state is returned correctly. 

#### To Reproduce
Use a REST API tool:

1. Make a bulk publish in your site. 
2. Set up a request for the API, POST `http://localhost:8080/studio/api/2/workflow/item_states`
3. Fill up the request body following the API schema, setting `"staged:false"`:
```
{
  "items": [
    "/site/website/technology/index.xml"
  ],
  "siteId": "your_site_name_goes_here",
  "clearSystemProcessing": true,
  "clearUserLocked": false,
  "live": true,
  "staged": false
}
```
4. Send the request.
5. Set up a request for the API, GET `http://localhost:8080/studio/api/2/workflow/item_states`
6. Send the request.
7. See error.

#### Logs
Making a GET request to `http://localhost:8080/studio/api/2/workflow/item_states`, returns the next response:

```
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "total": 1,
    "offset": 0,
    "limit": 1,
    "items": [
        {
            "id": 715,
            "label": "Technology",
            "parentId": 694,
            "contentTypeId": "/page/category-landing",
            "path": "/site/website/technology/index.xml",
            "previewUrl": "/technology",
            "systemType": "page",
            "mimeType": "application/xml",
            "state": 1024,
            "lockOwner": null,
            "localeCode": "en_US",
            "translationSourceId": null,
            "creator": null,
            "dateCreated": "2022-04-04T09:44:11-06:00",
            "modifier": null,
            "dateModified": "2022-04-04T09:44:11-06:00",
            "commitId": "909bf9bc2388f24e4ddc374d53b2fee9062c7123",
            "sizeInBytes": 1599,
            "availableActions": 0,
            "childrenCount": 0
        }
    ]
}
```

#### Screenshots
N/A

**Comment by sumerjabri** [comment]
Items can't be live and staged at the same time. All live items are staged first.
