### ISSUE TITLE
[studio-ui] A list of attributes to keep while do cleanup on paste RTE

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5436]
### Feature Request

On RTE paste, we have a plugin ([craftercms_paste_extension](https://github.com/craftercms/studio-ui/tree/support/3.1.x/static-assets/js/tinymce-plugins/craftercms_paste_extension)) to do clean up along with `paste` plugin.

See line https://github.com/craftercms/studio-ui/blob/support/3.1.x/static-assets/js/tinymce-plugins/craftercms_paste_extension/plugin.js#L52

The function will select all nodes and remove all attributes.

I would like to have a list of attributes that should be kept during the clean-up. For example: `a` link `href` attribute.

#### Is your feature request related to a problem? Please describe.

Links are cleaned up `href` attribute during copy/paste step.

#### Describe the solution you'd like

A possible solution is a method that returns a list of attributes that should not be cleaned up. Developers can implement this method using paste hooks.

#### Describe alternatives you've considered
N/A

**Comment by russdanner** [comment]
@phuongnq, after discussing this further:
The new copy-paste clean-up MAY cover the needs this code was intended to address.
Given this, before adding this enhancement, we'd like to try and disable (and later remove) this code entirely.  

Please test to see if removing this code solves the issue tthis enhancement is intended to address (and that doesn't create new issues on paste from word).

@avasquez614 FYI
