### ISSUE TITLE
[studio-ui] Edit Tools hide when content is locked by another user

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5440]
#### Is your feature request related to a problem? Please describe.
When content is locked by another user, the hiding of the Edit Tools is too jarring.

#### Describe the solution you'd like
We need a smoother experience where the Edit Tools don't allow the user to perform any edits against a locked item, but we do so in a less jarring/animated manner.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
When reloading the browser, the Edit Tools animating is also jarring. We must consider having those stay open and disable/enable and have a hide/show button.

**Comment by rart** [comment]
Configuration changes required: Add configuration `<disabled>false</disabled>` to all top level ICEToolsPanel widget that shouldn't be disabled when item gets locked by another user.

Suggested: Audiences, devise simulator & settings
