### ISSUE TITLE
[search] The new ElasticsearchClient doesn't handle all date types

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#5445]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2022-04-05

#### Describe the bug
The Elasticsearch client is not properly serializing object from `java.time`

#### To Reproduce
1. Go to a site based on Editorial
2. Open `Project Tools / GraphQL`
3. Execute the following query:

```graphql
query MyQuery($gt: DateTime = "2021-01-01T00:00:00Z") {
  page_article(sortBy: "date_dt", sortOrder: DESC) {
    items {
      title_t
      date_dt(filter: {gt: $gt})
    }
  }
}
```

#### Logs
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
```

**Comment by jdrossl** [comment]
@yacdaniel please help validate this fix

**Comment by yacdaniel** [comment]
Verified fixed.
![image](https://user-images.githubusercontent.com/6722074/163056753-c4c53269-962a-4d98-a020-3d1fe20ec173.png)
