### ISSUE TITLE
[studio-ui] Extra / added to publish by commit ID input line

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5446]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
April 6, 2022

#### Describe the bug
There is an extra `/` at the beginning of the input line for publishing by commit ID that's added automatically and cannot be removed. This doesn't apply to this type of publishing

#### To Reproduce
1. Go to the Publishing tool in Project Tools
2. Click on Publish On Demand > second radio button
3. Try to type a commit ID
4. See the error

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/162035852-052bda4b-e09f-4006-871c-9bf19e6f3f45.png)

**Comment by rart** [comment]
@jvega190 only the commit id field should dismiss this behaviour. The path of the publish by path should preserve.

**Comment by yacdaniel** [comment]
Slash also affects the submission comment
![image](https://user-images.githubusercontent.com/6722074/162041885-b9755ef2-e948-4677-9331-dfbf3fc950d9.png)

**Comment by Euquimides** [comment]
Hi @rart! I noticed that the `Submission Comment` field in `Publish changes made in Studio via the UI` and `Publish changes made via direct git actions against the repository or pulled from a remote repository` isn't allowing spaces to be added. This might be related with this issue.

**Comment by Euquimides** [comment]
Hi! I updated and re-checked the issue. It is working fine now. Thank you! Closing the ticket.
