### ISSUE TITLE
[studio][studio-ui] Show the merge commit ID after a pull

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5447]
#### Is your feature request related to a problem? Please describe.
After pulling from a remote repository, a merge commit is produced within Studio's Git's git log. This merge can be very useful for publishing a set of commits that were pulled in, but it's not known to the user.

#### Describe the solution you'd like
- [x] Update the API to return the commit ID
- [x] Update the UI to show the commit ID upon a successful commit and allow the user to copy it to the clipboard
- [x] Update the UI to have a convenient publish this commit button so they can immediately publish this merge commit post pull

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by jdrossl** [comment]
@rart the API updates are ready

**Comment by rart** [comment]
@jdrossl please review the `commitsMerged` property value. It seems to be returning `2` always even if it's just 1 or more commits.

**Comment by jdrossl** [comment]
@rart the fix is merged

**Comment by rart** [comment]
Still tracking a couple of bugs:
- Opening the publish dialog for the merge commit id, at times seems not to populate the merge commit id
- At times, fetching with conflicts doesn't update the Repo Status component and need to go out and in of "Git" to view conflicts
- Pull dialog doesn't disable while pulling

**Comment by jdrossl** [comment]
Something I noticed while testing:
- We need to trigger a `REPOSITORY_EVENT` similar to when we sync so the UI can reload (this needs to be a super hard reload because the pull can bring a lot of changes at the same time)

**Comment by sumerjabri** [comment]
@alhambrav please update the docs.
