### ISSUE TITLE
[studio] Optimize getChildrenByPath

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5448]
#### Is your feature request related to a problem? Please describe.
The API getChildrenByPath and getChildrenByPathTotal need to be faster.

#### Describe the solution you'd like
Review and optimize the backing queries.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by jdrossl** [comment]
Before choosing the right path for optimizing the queries we need to check the following:
- [ ] Is it ok for the API to expect clients (including our own UI) to use the real path for pages? (`/site/website/index.xml` instead of `/site/website`)

**Comment by sumerjabri** [comment]
The decision is to try to update everything to ask specifically for folders or items. `/site/website/` is the folder (never an item), and `/site/website/index.xml` is the item.
