### ISSUE TITLE
[studio-ui] Rename `Project Tools` > `Remote Repositories` to `Git`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5450]
#### Is your feature request related to a problem? Please describe.
This tool does more now, we want it renamed.

#### Describe the solution you'd like
- [ ] UI to use the Git Icon
- [ ] UI to name it Git
- [ ] UM to change existing sites
- [ ] Docs: Update the docs to reflect this.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by rart** [comment]
@sumerjabri this is going to affect people on 4 already due to changes on `ui.xml`

**Comment by sumerjabri** [comment]
We will address it via UM, I added @jdrossl to help with that. @rart please provide @jdrossl with the necessary config updates.
