### ISSUE TITLE
[studio] /content/children_by_id returns a system error

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5456]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-ee7011`

#### Date of Build
`04/06/22`
#### Describe the bug
The API 2 ` /content/children_by_id` returns an error

#### To Reproduce
1. Call `/content/children_by_id` with a body like
```
{
  "siteId": "ed123",
  "id": 519
}
```
#### Logs
https://gist.github.com/yacdaniel/22084efe2b829a0083309ef82b016bcc
#### Screenshots
N/A

**Comment by sumerjabri** [comment]
We will be removing these unused API calls https://github.com/craftercms/craftercms/issues/5457
