### ISSUE TITLE
[studio-ui] CMIS data source dialogs do not support dark mode

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5466]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/7/2022

#### Describe the bug
CMIS data source dialogs do not support dark mode
- Upload Image
- Upload File
- Browse Image
- Browse File

#### To Reproduce
1. Configure CMIS data sources
2. Switch to Dark Mode
3. Exercise
4. See the error

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
<img width="1425" alt="Screen Shot 2022-04-07 at 4 06 52 PM" src="https://user-images.githubusercontent.com/169432/162472231-e66b99d4-2aa9-4c16-8595-dba2d0ac99e9.png">
<img width="1440" alt="Screen Shot 2022-04-07 at 4 35 05 PM" src="https://user-images.githubusercontent.com/169432/162472282-71f64686-ae1f-49cd-9ed8-dbd0863c31c1.png">

**Comment by sumerjabri** [comment]
CMIS is no longer supported.
