### ISSUE TITLE
[studio-ui] Use new API for Admin to set the password

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#547]
Please use this API to allow the admin to reset someone's password: http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/reset-password.html

Please also remember to change the admin's view of the user to allow them to set the password without that toggle and if the field is empty, you don't set it. Ping me if you have questions.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/280
