### ISSUE TITLE
[studio] Don't populate the file size for blob-store backed files

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5470]
#### Is your feature request related to a problem? Please describe.
Site creation or large git sync activities requires file metadata to be loaded during DB injection, this can slow down these activities.

#### Describe the solution you'd like
[studio] Don't populate the file size for blob-store backed files #5470

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
@phuongnq the idea is for the blob-store to simply return -1 for file size for performance reasons for now.

**Comment by jdrossl** [comment]
This can be changed [here](https://github.com/craftercms/studio/blob/da6e57742e30f84e2ac43c35ebbce9557d218ed9/src/main/java/org/craftercms/studio/impl/v2/repository/blob/BlobAwareContentRepository.java#L210)
