### ISSUE TITLE
[studio][studio-ui] Configuration files have no AA (Available Actions)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5476]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
April 11, 2022

#### Describe the bug
Configuration files accessed via the Dashboard My Recent Activity have no available actions.

#### To Reproduce
1. Edit a configuration
2. Go to My Recent Activity dashboard
3. Select the item or click the context menu
4. See no AA

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/162975964-27e5b4a0-8e1e-4655-a631-6831b5a2012b.png)

**Comment by jdrossl** [comment]
@rart I also found the following issues:

1. Sometimes the options are not loaded when using the checkbox, no errors or calls are shown in the browser

![dashboard](https://user-images.githubusercontent.com/1236955/164062570-ba037740-3235-4fec-8a6c-4c3f8e768449.gif)

2. All items have a `Preview` option, it should be added only for Pages & previewable assets

![Screenshot from 2022-04-19 10-33-08](https://user-images.githubusercontent.com/1236955/164062524-d3315a35-55bb-4ac8-b1e1-db04e6d7560b.png)

3. Some config files show the wrong icon in the contextual dialog

![Screenshot from 2022-04-19 11-24-18](https://user-images.githubusercontent.com/1236955/164062544-8f6b6250-fffa-416f-9d46-b54757f00c26.png)

Steps to reproduce:
1. Create a site from Editorial BP
2. Perform the Initial Publish
4. Edit a page, content-type & config file

**Comment by rart** [comment]
@jdrossl can't reproduce the different icons showing in the widget vs the item menu. Perhaps the other fixes took care of that. Reach out if you see it again 🤷🏻‍♂️

**Comment by sumerjabri** [comment]
This seems to be fixed with the latest build. Closing.
