### ISSUE TITLE
[studio-ui] Quick Create path form field is too short to hold long paths

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5479]
#### Is your feature request related to a problem? Please describe.
Quick Create path form field is too short for long paths making it very difficult to work

#### Describe the solution you'd like
Either lengthen the field width or make it a text area.

#### Describe alternatives you've considered
N/A

![image](https://user-images.githubusercontent.com/42217570/162977381-1617d203-a3b5-4b0a-af58-1a070f5b361d.png)
![image](https://user-images.githubusercontent.com/42217570/162977418-3e3fca91-7fcd-4119-985c-d70c5a4a3270.png)

**Comment by jvega190** [comment]
@jvega190 this happens with several fields in content-type editor. All of them need to be fixed

**Comment by AndyReiter** [comment]
Confirmed fixed in latest build: 

```Studio Version Number:
4.0.0-SNAPSHOT-9c5b68

Build Number:
9c5b6886826333b3a8ec5de29c824ebdd0b4d440

Build Date:
4/14/2022, 10:34 AM
