### ISSUE TITLE
[studio] 'RecentlyPublished' section in Dashboard not updating when using Firefox Browser

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5485]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-9c5b68`

#### Date of Build
`4/12/2022`

#### Describe the bug
When editing and publishing an item (after bulk publish), the `RecentlyPublished` section in `Dashboard` is not updating when using Firefox Browser. 

#### To Reproduce
1. Go to any site while using Firefox Browser
2. After bulk publish, edit and then publish content.
3. Go to `Dashboard`
4. See the error

#### Logs
 N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/163025661-5c405dc2-0805-40f8-89f0-ab5d9a0e83f6.mp4

**Comment by rart** [comment]
@sumerjabri this is a backend problem. The `api/2/history` is returning an invalid date where a date is expected. I've put logic in the UI to handle this so at least there's no crash. Firefox is less forgiving than Chrome in the misformatting of the date string which is why it works in Chrome.

```js
{
  response: { ... },
  total: 1,
    offset: 0,
  limit: 1,
  documents: [
  {
    internalName: '2022-04-13Z', /* <== Incorrect date format */
    numOfChildren: 1,
    children: [ ... ]
   ...
  }
}
```

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed. Thank you! Closing the ticket.
