### ISSUE TITLE
[studio-ui] Some XB actions (like sort) cause components to stay locked.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5487]
#### Crafter CMS Version
4.0.0-SNAPSHOT-9c5b68

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
After some actions in Experience Builder like sort, or dragging a new/existent component may cause components to stay locked after the action when moving shared components.

#### To Reproduce
1. Create an editorial based site.
2. Open components/features (see that smile is a shared component)
3. Enable 'move' mode and in features section, move `Download` before `Smile`
4. See that `Smile` stays locked.

When you do an action that moves a 'shared' component, it'll cause the shared component to stay locked.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
https://www.loom.com/share/77ad1f7546584dd9ad781882ab064114

**Comment by Euquimides** [comment]
Hi @jvega190 ! I updated and checked this issue. It seems that when moving a `Feature` item and leaving it in the same place, will lock the `Home` page. Please, view this issue.

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now. Thank you! Closing this ticket.
