### ISSUE TITLE
Add a 'last acted' indicator in the sidebar, to let users know the last modification events

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5488]
#### Is your feature request related to a problem? Please describe.
Sometimes when making changes in Studio, for example via duplication of content and copy-pasting, the users (specially if various are working at the same time) might lose track of the modifications or changes made. 

#### Describe the solution you'd like
A `last acted` indicator, in form of a `blue highlight` around the last affected content, might help. 

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
Will not pursue.
