### ISSUE TITLE
[studio-ui] The content/children_by_path API is returning HTTP 404 when deleting folders with children

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5489]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-9c5b68`

#### Date of Build
`4/12/2022`

#### Describe the bug
If you delete folders that contains children, Studio UI calls `content/children_by_path API` that returns an HTTP 404 response. 

#### To Reproduce
1. Go to a site of your choice, preferably Editorial.
2. Create a `folder`.
3. Add another `folder` or add `content` to that `folder`.
4. Delete the parent `folder`.
5. See the error

#### Logs
Crafter Authoring catalina.out logs shows the next error:
```
[ERROR] 2022-04-12T16:25:24,165 [http-nio-8080-exec-7] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/content/children_by_path failed with response: ApiResponse{code=7000, message='Content not found', remedialAction='Check that path '/site/website/articles-copy-1' is correct and it exists in site 'a8'', documentationUrl=''} 
org.craftercms.studio.api.v1.exception.ContentNotFoundException: Content not found at path /site/website/articles-copy-1 site a8
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/163065586-f7d4ae10-e818-494a-9146-31a72c08ad6e.mp4

**Comment by jdrossl** [comment]
@sumerjabri this seems to be an UI issue

**Comment by rart** [comment]
This is a no-issue. This relates to the socket sending many events for a single bulk operation and in the order the events come. Some recent updates to reduce the amount of refreshes actually improved this — I don't see it happening on the path navigator. The tree navigator may still present it but overall, as long as the UI doesn't crash, the 404s are ok if it just realises the path is gone, reflects the changes and continues to work well.

**Comment by sumerjabri** [comment]
Closing as a non-issue as it can happen that the UI will ask for something that has been deleted in the background, and it recovers without issue.
