### ISSUE TITLE
[studo-ui] Text consistency in the UI

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5491]
#### Crafter CMS Version
Studio Version Number:
4.0.0-SNAPSHOT-9c5b68

#### Date of Build
Build Date:
4/12/2022, 1:37 AM

#### Describe the bug
It would be nice to have consistency in the text/wording used in the UI (Workflow States and Dashboard) screens

#### To Reproduce
1. Create a project using the Website Editorial bp
2. Go to the `Project Tools` -> `Workflow States`
3. Should we make the title of the screen consistent with the name from Project Tools?  When you click on `Workflow States`, it opens up the screen saying `Item States`
4. Click on the `Filters` button
5. when Filters is expanded, I was wondering if it should be consistent with what is listed in the dashboard Icon Guide for Workflow States?  In the dashboard, we have `Submitted to staging`, `Submitted for live`, `Scheduled for staging` and `Scheduled for live`.  Notice in the Filters in the image below, we only have `Submitted` and `Scheduled`.
6. Click on an item to display the `Set State for ...` dialog
7. Should we make the wording consistent and say `Set as published to staging` and `Clear as published to staging`?
8. Open the `Dashboard` and scroll down to the `Icon Guide`
9. We have `Submitted to staging` and `Submitted for live` , maybe make both of them use `for` so we'll have `Submitted for staging` and `Submitted for live`?

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
<img width="1200" alt="Screen Shot 2022-04-12 at 2 16 07 PM" src="https://user-images.githubusercontent.com/25483966/163140589-db6bb875-bd82-4f9a-aa4e-989b400bf8b8.png">

<img width="1174" alt="Screen Shot 2022-04-12 at 2 53 29 PM" src="https://user-images.githubusercontent.com/25483966/163140671-e7ee09f4-d8c0-4e8f-93d9-4e625ce5dc16.png">

<img width="1073" alt="Screen Shot 2022-04-12 at 7 20 55 AM" src="https://user-images.githubusercontent.com/25483966/163146962-53c4e4b4-a3f0-46f1-84d3-064f4167cd6c.png">

**Comment by jvega190** [comment]
List of updates:

- [ ] `Workflow States` vs `Item States`, use `Workflow States`. (In project tools)
- [ ] Update Item States filters to have `Submitted to staging`, `Submitted to live`, `Scheduled to staging`, `Scheduled to live`.
- [ ] In Item States view, when setting state, update `Clear as published from stating` to be `Clear as published to stating`
- [ ] In Dashboard Icon Guide, use `to` in `Scheduled` and `Published` icons.

**Comment by jvega190** [comment]
@alhambrav according to conversation, the word `to` will be used in cases like `Clear as published from stating`

**Comment by jvega190** [comment]
@alhambrav can you please create a separate ticket for the addition of filters in workflow states? So we keep this ticket only for the wording updates. Thanks!

**Comment by alhambrav** [comment]
https://github.com/craftercms/craftercms/issues/5525

**Comment by alhambrav** [comment]
verified fixed
