### ISSUE TITLE
[studio-ui] Publishing by Commit ID dialogue does not allow for spaces in the comment section

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5492]
#### Crafter CMS Version
Studio Version Number:
4.0.0E-BETA-60dbd0

#### Date of Build
Build Number:
60dbd05827ffeb6a3410b4ff4b2af8763c1be16b
Build Date:
4/8/2022, 11:53 AM

#### Describe the bug
When publishing via commit ID, the publishing comment section does not allow for spaces to be in the comment.

#### To Reproduce
1. Create a site
2. Navigate to the Project Tools for the site
3. Click on Publishing
4. Select the bubble for "Publish changes made via direct git actions against the repository or pulled from a remote repository"
5. Attempt to add spaces in the "Submission Comment" text area.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/163196849-8724ac56-11bd-4d04-b059-d202a10cd811.png)

**Comment by sumerjabri** [comment]
This has already been fixed. Please try with a more recent build.
