### ISSUE TITLE
[studio-ui] Error in dashboard "My Recent Activity" when deleting a page 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5494]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
Build Date:
4/13/2022, 5:37 AM

#### Describe the bug
{{A clear and concise description of what the bug is.}}

#### To Reproduce
1. Create a project using the Website Editorial bp
2. Delete any article page
3. Open the `Dashboard` and scroll to the `My Recent Activity` dashlet.  Notice the error there
4. Check the catalina logs, there are no errors there.  Here's part the logs when the article page was deleted and then there were no other logs when the Dashboard was opened

```
[INFO] 2022-04-13T10:55:52,048 [studio.clockTaskExecutor-45] [job.StudioPublisherTask] | Starting publishing on environment live for site 4
[WARN] 2022-04-13T10:55:53,714 [studio.clockTaskExecutor-45] [lib.Repository] | close() called when useCnt is already zero for Repository[/Users/vita.alhambra/temp/test5/craftercms/crafter-authoring/data/repos/sites/4/published/.git]
[INFO] 2022-04-13T10:55:53,890 [studio.clockTaskExecutor-45] [repository.GitContentRepository] | Not able to find branch live for site 4. Creating new branch
[INFO] 2022-04-13T10:55:53,991 [studio.clockTaskExecutor-45] [job.StudioPublisherTask] | Finished publishing environment live for site 4
[WARN] 2022-04-13T10:56:03,589 [studio.clockTaskExecutor-1] [lib.Repository] | close() called when useCnt is already zero for Repository[/Users/vita.alhambra/temp/test5/craftercms/crafter-authoring/data/repos/sites/4/sandbox/.git]
```

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
<img width="1174" alt="Screen Shot 2022-04-13 at 10 32 06 AM" src="https://user-images.githubusercontent.com/25483966/163210574-9c494b22-5619-4578-87d5-bce46b156ef2.png">

**Comment by alhambrav** [comment]
Verified fixed.

**Comment by rart** [comment]
Fixed @ https://github.com/craftercms/studio-ui/pull/2936
