### ISSUE TITLE
[studio] Allow setting the new and modified states of an item from the workflow states screen

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5495]
#### Is your feature request related to a problem? Please describe.
For support purposes, sometimes a manual publish from git is needed. This then requires setting the workflow states of all items, to the following:

- Not new
- Not modified
- Not in system processing
- Not locked
- Published to live
- Published to staging

Right now the workflow states UI, you can't set items as not new and not modified.

#### Describe the solution you'd like

Add an option to set items as New (true/false) and Modified (true/false)

**Comment by sumerjabri** [comment]
@rart please add the necessary UI to the new bits.

**Comment by rart** [comment]
@jvega190 updated design (i.e. added "clear new" & "clear modified")

![image](https://user-images.githubusercontent.com/3928341/179211072-7022b046-b75e-4fae-b30a-9ff96350944c.png)

@avasquez614 @sumerjabri do we need to add "Set as new/modified" too or leave it to just clear?

**Comment by sumerjabri** [comment]
@avasquez614 I thought we needed to set/clear the new/modified. Please weigh in.

**Comment by rart** [comment]
Per @avasquez614 just will just do _clear_ for now

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3928341/179277540-28d20881-02e0-4297-b73b-1dab36b23878.png">

**Comment by Euquimides** [comment]
Hi! Verified and validated this feature in Crafter v4. It is working now. Thank you! Please refer to ticket #5689 for automation.
