### ISSUE TITLE
[studio] If there is no controller, saving & closing an empty controller will update the Content Type to the new controller

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5497]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-9c5b68`

#### Date of Build
`4/13/2022`

#### Describe the bug
If there is no controller, opening, saving and closing an empty controller either from XB or from Edit Controller Available Action, will update or set up the Content Type to the new empty controller. 

#### To Reproduce
1. Go to an Editorial Site.
2. With XB enabled, click-on `Edit Controller` of a `Feature` item.
3. Save and close the `Edit Controller` dialogue. 
4. Go to `Project Tools`/`Content Types`/`Feature` and see how the content type was updated. 

This also happens with Articles:
1, Go to `articles` folder
2. Then right-click `Edit Contoller` of an `article` of your choosing,
3. Save and close the `Edit Controller` dialogue. 
4. Go to `Project Tools`/`Content Types`/`Feature` and see how the content type was updated. 
5. Quick create a new `article.
6. See error. 

#### Logs
 N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/163247806-3bc936d4-86c7-40e2-a096-2b6c3bc719f5.mp4

**Comment by sumerjabri** [comment]
@Euquimides this is ready for testing now.

**Comment by Euquimides** [comment]
Hi! Updated and then re-checked the issue. It is fixed now. Thank you! Closing this ticket.
