### ISSUE TITLE
[studio-ui] There's no feedback when updating a workflow

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5499]
#### Crafter CMS Version
Latest 4.0.0 SNAPSHOT build

#### Date of Build
04/13

#### Describe the bug
After changing the item state of an item, there's little indication that something happened

#### To Reproduce
1. Create a site in Studio
2. Go to the workflow states screen
3. Select any item and set as published to live and set as published to staging
4. After this, it's visually not clear that something happened

It would be great if a popup appears indicating that the states have been applied.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket, I noticed that when selecting an item in `Workflow States` without activating the checkbox, will show `State for 0 items updated successfully` upon modifying the item state. Please check this out.

https://user-images.githubusercontent.com/90878288/178813091-21ca7340-d26b-45c0-bfe4-62a473559943.mp4
