### ISSUE TITLE
[studio-ui] editing a group doesn't populate the dialog with the group's info

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#550]
Create a group (or several)
Go to groups listing: http://localhost:8080/studio/#/admin/groups
Click on the pencil to edit a group, the dialog is empty.

**Comment by jvega-crafter** [comment]
Dialog is now being populated, description field is not because service returns "group_description" instead of "description". Issue created https://github.com/craftercms/craftercms/issues/555. That also happens for get-all groups service.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/276
