### ISSUE TITLE
XB should be enabled at components level with write permission

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5501]
### Feature Request

If users have `content_write` permission in some shared components but not the parent page, XB is not enabled.

To reproduce this:

* Create a site from Editorial BP
* Add a new role with the following content:

```
    <role name="componentsOnly">
        <rule regex="/site/components|/site/components/.*">
            <allowed-permissions>
                <permission>content_read</permission>
                <permission>content_copy</permission>
                <permission>content_write</permission>
                <permission>content_create</permission>
                <permission>folder_create</permission>
                <permission>list_cmis</permission>
                <permission>search_cmis</permission>
                <permission>clone_content_cmis</permission>
                <permission>upload_content_cmis</permission>
                <permission>get_children</permission>
            </allowed-permissions>
        </rule>
        <rule regex=".*">
            <allowed-permissions>
             <permission>upload_content_cmis</permission>
            </allowed-permissions>
        </rule>
    </role>
```
* Create a new user/user group with the above role
* Log in with the new user
* Notice that while *Contact Widget* is editable but there is no ICE enabled

![xb_component_level](https://user-images.githubusercontent.com/2996543/163312639-75700e14-3491-4643-bfd5-94c81b235ed4.png)

#### Is your feature request related to a problem? Please describe.

Users cannot use ICE while browsing components in pages.

#### Describe the solution you'd like

XB should be enabled for components with `content_write` permission even when the parent page does not.

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
@russdanner how would the experience be? You can enable edit mode, but not actually edit anything except that one component? Would that not confuse/frustrate users?

**Comment by sumerjabri** [comment]
Also, remember AA (Available Actions) will not allow the UI to edit the parent item.

**Comment by sumerjabri** [comment]
Already fixed.
