### ISSUE TITLE
[studio] When Git CLI is enabled, the first save after the repository is created takes several minutes in a big repo

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5503]
#### Crafter CMS Version
3.1.23 latest build

#### Date of Build
N/A

#### Describe the bug
When Git CLI is enabled, the first save after the repository is created takes several minutes (around 3-4 mins) in a big repo.

#### To Reproduce
0. Enable Git CLI
1. Create a site based on a big repo
2. After the site is created, edit the Home page and save
3. Observe the save operation takes several minutes, but subsequent saves take a couple of seconds

**Comment by sumerjabri** [comment]
Validated per @avasquez614
