### ISSUE TITLE
[studio-ui] Switch the Form Engine to use the TinyMCE configuration in `ui.xml`

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5505]
#### Describe the enhancement
The Form Engine should use the configuration in `ui.xml` same as XB for consistency and better control.

#### Tasks
- [x] Switch FE to use `ui.xml` Tiny MCE configuration instead of `rte-config.xml`
- [x] Test
- [x] Document

**Comment by russdanner** [comment]
This ticket needs to be corrected.
The config here is for the form engine but the test was done in XB.
XB and Form Engine RTEs are currently configured in different files. 
- XB is configured in UI.xml
- Form Engine is configured in RTE.xml

**Comment by AndyReiter** [comment]
Fixed and assigned back to Russ for further assignment.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/5523

**Comment by yacdaniel** [comment]
Verified, assigning @alhambrav for doc update

**Comment by sumerjabri** [comment]
@AndyReiter the docs are here: https://docs.craftercms.org/en/4.0/site-administrators/studio/rte-configuration.html

**Comment by AndyReiter** [comment]
Confirmed fix in 4.0 Snapshot. Closing now.
