### ISSUE TITLE
[docs] Review and update RTE 5 docs to correctly reflect the documentation of menubar and toolbar

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5506]
#### Is your feature request related to a problem? Please describe.
The RTE documentation for Crafter 4 confuses menubar and the toolbar in several places. It also indicates that menubar configuration is important and that functionality is neither described nor operational. These inconsistencies should be fixed.

https://docs.craftercms.org/en/4.0/site-administrators/studio/rte-configuration.html?highlight=menu

top is menubar
bottom is toolbar
![image](https://user-images.githubusercontent.com/42217570/163577503-773ca091-d492-4220-9c86-6ac79040d07d.png)

#### Describe the solution you'd like
Documentation should be consistent and in line with TinyMCE's documentation.

#### Describe alternatives you've considered
N/A

**Comment by alhambrav** [comment]
Hi @AndyReiter 
RTE docs updated via this PR: https://github.com/craftercms/docs/pull/1475
Please review the docs https://docs.craftercms.org/en/4.0/site-administrators/studio/rte-configuration.html#rte-configuration and let me know if I missed something.  Thank you.

**Comment by AndyReiter** [comment]
Docs look good to me. Closing this out now.
