### ISSUE TITLE
[studio-ui] Create new content does not recognize path limited content types

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5509]
#### Crafter CMS Version
v4.0.0 SNAPSHOT

#### Date of Build
4/14/2022

#### Describe the bug
When creating a new content type via right-clicking in the path navigator, I am prompted to select the content type. If I have configured my paths to NOT permit any other content types from being positioned in that location, I should not be prompted to choose the type.

#### To Reproduce
1. Create a site based on editorial
2. Navigate to Project Tools
3. Select content-types
4. Select the Section Defaults
5. Open the Config.xml and set the following configuration: 
`<paths>
		<excludes>
			<pattern>^HIDDEN</pattern>
		</excludes>
	</paths>`
6. Save the config file
7. Navigate to the home page and right-click create content under the home page
8. Notice that you are still presented with the Section Defaults content type

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/163596201-c889e435-2b3e-4d96-896b-173df441466d.png)
![image](https://user-images.githubusercontent.com/42217570/163596219-629f3a45-9227-409e-9954-e755c8882c04.png)

**Comment by sumerjabri** [comment]
Excluding "HIDDEN" doesn't really mean anything. Perhaps you should try:
```
<paths>
		<includes>
			<pattern>HIDDEN</pattern>
		</includes>
	</paths>
```

You will also need to hit "save" for it to invalidate the cache.

**Comment by russdanner** [comment]
CONFIRMED
