### ISSUE TITLE
[studio-ui] Don't show Launcher and logo in Studio's search tool

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5510]
#### Is your feature request related to a problem? Please describe.
The search tool shouldn't show the left logo or right Launcher.

#### Describe the solution you'd like
Remove from all sites.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by rart** [comment]
This is a blueprint update.

Must add the below snippet to the `PreviewToolbar`'s widget of id `craftercms.components.Search`
```xml
<configuration>
  <embedded>true</embedded>
</configuration>
```

**Comment by jvega190** [comment]
The last PR mentioned (2944) wasn't intented to be mentioned in this ticket. It's already fixed to point to the correct ticket
