### ISSUE TITLE
[studio-ui] Allow to edit the path in the image picker

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5513]
#### Is your feature request related to a problem? Please describe.
Authors want to be able to manually edit paths of images without having to use browse/search features to do it.
Example: Change /static-assets/**en**/my-images/myimage.jpg to /static-assets/**jp**/my-images/myimage.jpg

#### Describe the solution you'd like
1. Add to the image picker control a flag that allows you to edit the image path.
2. Make the image path that appears in the image picker form control an input that you can edit. 
3. When the author presses enter on the input, Studio checks if the path exists. If it does, the path is immediately saved. If it doesn't, an error is shown to indicate the path is invalid.

![Screenshot from 2022-04-18 10-54-05](https://user-images.githubusercontent.com/1598884/163828836-5b8769ae-8c21-4c33-9ba4-c2a630bf0cbc.png)

**Comment by sumerjabri** [comment]
Closing in favor of a plugin for the specific use-case.
