### ISSUE TITLE
[studio-ui] Form Control Help dialogs do not honor Dark Mode

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5516]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/18/2022

#### Describe the bug
Form Control Help dialogs do not honor Dark Mode

#### To Reproduce
1. Add help to various form controls
2. Enable dark mode in Studio
3. Open form and click help icons
4. See the error

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
<img width="613" alt="Screen Shot 2022-04-18 at 1 31 01 PM" src="https://user-images.githubusercontent.com/169432/163848249-9be2a774-fc94-4801-a7d1-b523b7e225a9.png">

**Comment by rart** [comment]
@sumerjabri @russdanner we agreed we won't be adding further support of dark mode to legacy UI. Only fix bug whereas the UI is unusable due to dark mode.

**Comment by sumerjabri** [comment]
@russdanner this is too expensive to fix vis-a-vis other priorities. We're going to close it, and we're happy to discuss further if required.
