### ISSUE TITLE
[studio] Duplicated content with the same internal name through copy-pasting and cutting operations

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5520]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-48b86d`

#### Date of Build
`4/18/2022`

#### Describe the bug
You are able to duplicate content with the same internal name as another one by copy-pasting content inside a folder or other content, then cutting and pasting the same content inside the folder or content. 

#### To Reproduce
1. Go to a site of your choosing. 
2. `Copy` and `Paste` any content inside a folder or content of your choosing.
3. `Cut` and `Paste` the previous selected content inside the same folder or content of your choosing. 
4. See the error

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/163857258-3cd7b7ba-8585-4849-91e7-ae714a6e6e66.mp4

**Comment by rart** [comment]
Tested on a recent 4.0.3-SNAPSHOT build and the paste results in `"{internalName} (Copy 1)"`. Perhaps addressed through the ticket linked above or some other?

**Comment by Euquimides** [comment]
Hi! Updated and rechecked the this issue and indeed it is not reproducible anymore. Closing this ticket.
