### ISSUE TITLE
[studio-ui] XB stuck in Rich Text Menu when closing Edit's Content Form either through Dismiss or Cancel buttons

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5526]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-54c6f0`

#### Date of Build
`4/19/2022`

#### Describe the bug
If a content contains in its structure a Rich Text Controller, this will enable the Rich Text menu. Activating the Rich Text menu through XB and selecting `Edit`, will open a Content Form. Closing that Content Form either through the Dismiss or Cancel button will make XB stuck in the Rich Text menu. You can only exit it either by clicking inside, changing from Edit to Move mode or re-entering the Content Form, then Saving and Closing. 

#### To Reproduce
1. Go to a site like Editorial.
2. Enable `Edit Mode`
3. Select a section with `Rich Text`.
4. In the `Rich Text` menu, click on `Edit`.
5. Close the Content Form through `Dismiss` or `Cancel` buttons.
6. See error. 

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/164067582-28013e2f-a701-445e-bb95-b70440c7c14f.mp4

**Comment by rart** [comment]
@jvega190 please remove the edit button from the RTE toolbar. It was added due to the lack of data source support and now we have it.

**Comment by rart** [comment]
@jvega190 side-task: please remove the "file" menu and "View > Preview" option from RTE
