### ISSUE TITLE
[studio-ui] Rich Text Edit's Content Form empty in `Articles` (Editorial) and `Post` (Wordify) 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5527]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-54c6f0`

#### Date of Build
`4/19/2022`

#### Describe the bug
When you open the Rich Text Edit's Content Form through XB inside `Articles` of Editorial BP or `Post` of Wordify BP, you'll notice that the Content Form will show up empty. This might be related either with XB or the Content Type structure. 

#### To Reproduce
1. Open a site based in 'Editorial' or `Wordify`
2. Go to an 'Article' or a `Post` of your choice. 
3. Enable XB Edit Mode.
4. Click on a section with Rich Text.
5. When the Rich Text menu open, click on Edit. 
6. The Content Form will show up empty. 

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/164072617-ee38d264-1385-4e26-8f43-5d672252ed4d.mp4

**Comment by jvega190** [comment]
Hi @Euquimides, I reassigned the ticket to you, this is no longer valid, so can you please re-verify and close if not valid? Thanks!

**Comment by Euquimides** [comment]
Hi! I rechecked this issue. Since the `Edit` button for Rich Text has been removed, this ticket is no longer valid, so this issue is not present anymore. Closing this ticket.
