### ISSUE TITLE
[studio-ui] Reverting a static asset doesn't refresh the dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#553]
Upload a static asset
Upload it again
Click history and revert to the first version, the dialog doesn't update/refresh

Also, if you close the dialog, the preview of the static asset doesn't reload to the updated/reverted asset.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/336
https://github.com/craftercms/studio2-ui/pull/338
