### ISSUE TITLE
[studio-ui] XB stacks error messages when character limits are exceeded

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5530]
#### Crafter CMS Version
4.0 SNAPSHOT

#### Date of Build
4/14/2022

#### Describe the bug
When a text input has a character limit, and that field is exposed through the XB, the "max length (xx) reached" message appears once per character. 

#### To Reproduce
1. Create a site based on Editorial
2. Navigate to project tools
3. Edit the home page content type and add a character limit to the RTE
4. Go back to the XB for the home page
5. Add multiple characters that exceed the set character limit
6. Notice the stacked error messages

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/164273996-4f38f9fd-28d8-421f-a5b7-71db07f2a0d1.png)

**Comment by russdanner** [comment]
CONFIRMED
