### ISSUE TITLE
[studio] Config files have a Preview URL even though they shouldn't

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5532]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
April 20, 2022

#### Describe the bug
When calling APIs to retrieve items, config files are being returned with a Preview URL when they shouldn't. This presents the user with the menu item "Preview" as an AA through the Dashboard, which is misleading as configuration files are not previewable.

#### To Reproduce
Invoke a `sandbox_items_by_path` or `item_by_path` against a config file and see the return

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
![image](https://user-images.githubusercontent.com/3931908/176258783-b86ab057-fba6-4afb-b9af-254844a7b3c4.png)

**Comment by phuongnq** [comment]
This happens because while writing config, preview_url is added. I sent a PR to set preview_url for config files pattern to `null`
