### ISSUE TITLE
Dedicated permission to delete item that causes broken dependency

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5534]
CI: 3109

#### Is your feature request related to a problem? Please describe.
Currently, there is no permission for Deleting an item that causes a broken dependency. There are many use cases where customers want users to be able to delete items but would like to block non-admins from deleting items that would result in broken dependencies.

#### Describe the solution you'd like
Dedicated permission that allows for users to delete content that causes broken dependencies.

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
Will not pursue.
