### ISSUE TITLE
[studio] GraphiQL Boolean Filter not working

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5535]
#### Crafter CMS Version
4.0SNAPSHOT

#### Date of Build
04/20/2022

#### Describe the bug
Using the GraphiQL explorer, when adding a boolean to a query the "filter" parameter is ignored. Customer needs to be able to rely on the parameter for queries to be working properly.

#### To Reproduce
1. Go to the GraphiQL Explorer
2. Create a new query
3. Create a query with a boolean and add a filter parameter. 
4. Attempt to run the query and see that the filter parameter is ignored

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/164489626-1daa3326-61ce-4d08-98c5-e69a9768c803.png)

**Comment by jdrossl** [comment]
The filter works as expected, on nested objects ES only looks for matches but doesn't remove other objects from the result

![filters](https://user-images.githubusercontent.com/1236955/164492166-fa14e261-b5a2-45fc-a5c7-a0e60ac05405.gif)
