### ISSUE TITLE
[studio-ui] CMIS upload dialog is sending the form data incorrectly

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5537]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-5e4fff`

#### Date of Build
`4/20/2022`

#### Describe the bug
The CMIS upload dialog is sending the form data request incorrectly, which causes the upload to fail
#### To Reproduce
1. Set up CMIS upload image datasource
2. Try to upload an asset. 
3. See the error

#### Logs
API returns `{"response":{"code":1001,"message":"Invalid parameter(s) : Invalid siteId","remedialAction":"Check API and make sure you're sending the correct parameters","documentationUrl":""}}`
#### Screenshots
Notice how the UI in 4 is sending a `contained-button-file: (binary)` which might be causing the issue. 
3.1
![image](https://user-images.githubusercontent.com/6722074/164521923-f9461b4f-5fe4-45b6-afe0-ba54399468d7.png)
4.0
![image](https://user-images.githubusercontent.com/6722074/164523806-607bf4fe-7da8-44b1-b231-3719a7090e87.png)

**Comment by jvega190** [comment]
Ready for validation, merged in 4.0.0

**Comment by yacdaniel** [comment]
Verified fixed.
