### ISSUE TITLE
[studio-ui] Clicking and Double clicking in an XB RTE sometimes triggers click events on the original element being edited

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5538]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/19/2022

#### Describe the bug
Clicking and double-clicking in an XB RTE sometimes triggers click events on the original element being edited. 
A good example of this is linked banner text that is RTE editable in XB. When a user double clicks the content to select all (presumably to replace the current text with new text), the underlying click handler intended to the end-user of the site fires.

 
#### To Reproduce
1. Create an RTE field to manage content inside an element with a click event tied to it 
```
                    <a href="https://google><@crafter.span   $field="bannerHeadline_s">
                             ${contentModel.bannerHeadline_s}
                        </@crafter.span></a>
 ```                   
2. click into the RTE
3. Double click to select all the content
4. See click event to redirect to google fire

#### Logs
N/A

#### Screenshots
N/A

**Comment by russdanner** [comment]
Internal: I have a "se-repo" example with this issue if you have trouble reproducing this. Just ask me for it.

**Comment by sumerjabri** [comment]
Verified with @russdanner
