### ISSUE TITLE
[studio-ui] XB reloads page due to background write event when only one user is in the system

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5539]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/19/2022

#### Describe the bug
XB reloads the page due to a background write event when only one user is in the system.  The problem is, there can be no background write if there is only one user.  This is clearly some kind of race condition where a user performs an action that causes a write and then performs a second action that performs a write but does so too quickly such that at the same time the second write action is about to queue the UI receives a WebSocket notification of the first write.

#### To Reproduce
1. Use XB to drag components into a drop target quickly
2. Repeat until the condition presents itself 
4. See the error

#### Logs
N/A

#### Screenshots
N/A

**Comment by rart** [comment]
The problem is performing an operation before the previous operation fully completes; which is the trigger to renew the commit id of the currently held item.

**Comment by russdanner** [comment]
Confirmed
