### ISSUE TITLE
[studio-ui] Clicking the pencil on a component that does not start with a crafter.xyz element opens a form that "spins"

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5541]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/19/2022

#### Describe the bug
Clicking the pencil on a component that does not start with a crafter.xyz element opens a form that "spins"
The system should do one of the following instead:
- Dont allow the pencil to be clicked
- Tell the user that the control is not properly registered and thus cannot be edited
- Or figure out what is needed and open the form properly (FTL and Groovy buttons open the proper file, why not edit?)

#### To Reproduce
1. Update the feature component's template so that there is not @crafter elements on the outside
2. Refresh the page
3. Now click on the feature element and then the pencil
5. See the form try to load and never finish.

#### Logs
N/A

#### Screenshots
N/A

**Comment by russdanner** [comment]
This is 4.0.1 because at this time, the key factor in recreating this has to do with weather or not all components on the page are properly marked with their outermost tag as <@crafter.div|xyz ....> and a reasonable workaround is simply to fix your implementation.

**Comment by rart** [comment]
@russdanner couldn't reproduce. Changed the feature template to be as below and still worked well.

```ftl
<#import "/templates/system/common/crafter.ftl" as crafter />

<!-- Feature Component -->
<article class="feature"><!-- CHANGE: changed to plain article instead of @crafter.article here -->
  <@crafter.span class="icon ${contentModel.icon_s}" $field="icon_s"/>
  <div class="content">
    <@crafter.h3 $field="title_t">
      ${contentModel.title_t}
    </@crafter.h3>
    <@crafter.div $field="body_html">
      ${contentModel.body_html}
    </@crafter.div>
  </div>
</article>
<!-- /Feature Component -->
```

**Comment by rart** [comment]
I'm not seeing the ever-spinning form, but I do see **embedded** components not opening a form when applying the above change to the template.

**Comment by rart** [comment]
Fixed the issue I did see. Please re-test; hopefully it was the same issue.

**Comment by sumerjabri** [comment]
Validated by @russdanner
