### ISSUE TITLE
[studio-ui] The `Add Component` spinner in XB should be centered vertically and horizontally

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5542]
#### Is your feature request related to a problem? Please describe.
Today `Add Component` spinner in XB renders itself in the upper left corner of the zone it's "adding" a component to. This looks unpolished.

#### Describe the solution you'd like
The `Add Component` spinner in XB should center itself vertically and horizontally in the space when you add a component.

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
@rart suggests pushing this to 4.0.2 to give us more time to test scenarios

**Comment by russdanner** [comment]
Confirmed with basic testing. 
Will continue to work with this one and will file followups if I see anything with advanced layout building
