### ISSUE TITLE
Improve the Add Components panel in XB 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5543]
#### Is your feature request related to a problem? Please describe.
Today all components are listed in the add components panel which makes it difficult to work with.

#### Describe the solution you'd like
- [x] Sort the components alphabetically
- [x] Clearly display what types are allowed to be dropped on the page
- [x] Use the Avatar to show a unique colour for each type
  - [x] Consistent use of content type colours on other panels
- [x] Display what types are accepted by each zone as you hover or focus on them on XB
- [x] Remove the type id from the component list item and display full type names
- [x] Highlight drop targets of a content type when using the "List drop targets" menu option
- [x] Display basic content type details on the type context menu
- [x] Display what modes (embedded, shared, shared existing) the component can be created under the current set of models
- [x] Update panel title strings and icons: "Add Components" to "Create Content", "Browse Components" to "Existing Content", "Component Drop Targets" to "Drop Targets"
    - [x] Upgrade manager (?)
    - [x] Blueprints
- [x] Apply same view-aware behaviours to Search and Existing Content panels

**Comment by rart** [comment]
@jvega190 please update blueprints. See updated xml below.

@sumerjabri if we make upgrade manager perform the title updates, here are the entries to update followed by their updated form. These changes change the sidebar as shown by the attached screen capture:
<img width="238" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/7100e334-4c4d-49b2-acd3-1a68687ccfad">


**Original**
```xml
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewComponentsPanel.title" defaultMessage="Add Components"/>
        <icon id="@mui/icons-material/ExtensionOutlined"/>
        <widgets>
            <widget id="craftercms.components.PreviewComponentsPanel"/>
        </widgets>
    </configuration>
</widget>
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewBrowseComponentsPanel.title" defaultMessage="Browse Components"/>
        <icon id="@mui/icons-material/ExtensionOutlined"/>
        <widgets>
            <widget id="craftercms.components.PreviewBrowseComponentsPanel"/>
        </widgets>
    </configuration>
</widget>
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewDropTargetsPanel.title" defaultMessage="Component Drop Targets"/>
        <icon id="@mui/icons-material/ExtensionOutlined"/>
        <widgets>
            <widget id="craftercms.components.PreviewDropTargetsPanel"/>
        </widgets>
    </configuration>
</widget>
```

**Updated**
```xml
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewComponentsPanelTitle" defaultMessage="Create Content"/>
        <icon id="craftercms.icons.AddComponents"/>
        <widgets>
            <widget id="craftercms.components.PreviewComponentsPanel"/>
        </widgets>
    </configuration>
</widget>
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewBrowseComponentsPanelTitle" defaultMessage="Existing Content"/>
        <icon id="craftercms.icons.BrowseComponents"/>
        <widgets>
            <widget id="craftercms.components.PreviewBrowseComponentsPanel"/>
        </widgets>
    </configuration>
</widget>
<widget id="craftercms.components.ToolsPanelPageButton">
    <configuration>
        <target id="icePanel"/>
        <title id="previewDropTargetsPanelTitle" defaultMessage="Drop Targets"/>
        <icon id="@mui/icons-material/MoveToInboxRounded"/>
        <widgets>
            <widget id="craftercms.components.PreviewDropTargetsPanel"/>
        </widgets>
    </configuration>
</widget>
```

**Diff**
![image](https://github.com/craftercms/craftercms/assets/3928341/c204d403-c0c2-4281-9b03-ba3eab2fcd91)

**Comment by sumerjabri** [comment]
@phuongnq please add to UM.

**Comment by rart** [comment]
@sumerjabri @russdanner it would make sense to apply these same view-aware behaviours to the "Existing Content" panel, and possibly to the Assets and or Search panels. 1. Agree? 2. Do we create a separate ticket or handle under this one provided the updates are closely related and similar in nature?

**Comment by sumerjabri** [comment]
@rart I'm good either way.

**Comment by rart** [comment]
@sumerjabri bringing this back to 4.2.0 since we already merged part of it. The remaining PR is needed and close to completion.

**Comment by russdanner** [comment]
@rart can we make this one small adjustment for this phase?
https://www.loom.com/share/9fd9fa64f0294bd1ae3492960adfe30e

**Comment by rart** [comment]
> [@rart](https://github.com/rart) can we make this one small adjustment for this phase? https://www.loom.com/share/9fd9fa64f0294bd1ae3492960adfe30e

No, sorry. That needs its own effort/design giving it proper time for development, etc.

**Comment by sumerjabri** [comment]
@rart will send a PR to add the missing icon from 4.1.x. Once done, @sumerjabri will update all BPs with the new icon and label while keeping 4.1.x compatibility, starting with 4.1.6.

Updating all BPs will happen _after_ 4.1.6 is released.
