### ISSUE TITLE
[studio-ui] XB issues when drag and dropping assets in certain empty spaces

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5547]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-3bf2fd`

#### Date of Build
`4/22/2022`

#### Describe the bug
When you drag and drop assets (images) in certain empty spaces with XB, the XB zone markers stays stuck in the UI and don't respond to other interactions (for example, drag n' dropping other assets,  clicking to open menu, etc.). You can escape from this issue either by changing mode, changing the page or refreshing the browser. 

#### To Reproduce
1. Go to any project blueprint that contains zone markers, but in `Editorial` the issue is easier to notice. 
2. Open `Assets` in the right sidebar.
3. Drag and drop an image into an empty space, but is better to do it in the spaces marked in the screenshots below.
4. See the error

#### Logs
The browser debugger or dev tools, shows in console error that `dropZone is null` or `iceId is null`: https://gist.github.com/Euquimides/bdfbc77354b7282125ee9733adaaa09f

#### Screenshots
![xbDropIssue1](https://user-images.githubusercontent.com/90878288/164758387-d8333fc6-8bd6-4abc-b3e9-2a1ef5dc6b72.png)
![xbDropIssue2](https://user-images.githubusercontent.com/90878288/164758399-c1412ac2-452d-4d47-90d4-9d59e3b2be60.png)
![xbDropIssue3](https://user-images.githubusercontent.com/90878288/164758405-c6517579-16d7-40e5-8b8e-607e92c18ce9.png)
![xbDropIssue4](https://user-images.githubusercontent.com/90878288/164758411-dcf5d635-874a-4f54-bca8-c10250de805c.png)
![xbDropIssue5](https://user-images.githubusercontent.com/90878288/164758421-217dfd67-460d-4437-a8f9-781d4c966154.png)

https://user-images.githubusercontent.com/90878288/164759401-ecc12ccc-b993-44a1-9c2c-f6cf7b5e53f3.mp4

**Comment by yacdaniel** [comment]
Also reproducible by dragging component to invalid sections, like this `Feature` to the Header section

https://user-images.githubusercontent.com/6722074/164761310-ac7b0b52-1a70-483c-9b8e-3aaec1f2c1af.mp4

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now. Thank you! Closing this ticket.
