### ISSUE TITLE
[studio-ui] Dependencies are not being calculated correctly in "View Dependencies" and when Deleting

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5549]
#### Crafter CMS Version
4.0 SNAPSHOT

#### Date of Build
Build Date:
4/22/2022, 12:22 PM

#### Describe the bug
Items that are "dependent" on each other are not listed as dependencies in the "View Dependencies" screen. Also, when deleting a content item that is referenced by another item, the UI does not warn you about the dependencies that are about to be broken.

#### To Reproduce
1. Create site based on Editorial
2. Navigate to a component in the left sidebar (components --> articles-widget).
3. Click View Dendencies of the Latest Articles Widget component
4. Notice that there are no dependencies listed when it is dependent on /site/components/left-rails/left-rail-with-latest-articles.xml
5. Attempt to delete the Latest Articles Widget and notice that there is no warning about the dependencies being broken.

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/165124420-37322c9e-3def-4361-bf49-7562cd018299.png)

**Comment by yacdaniel** [comment]
This was fixed recently in https://github.com/craftercms/craftercms/issues/5545
![image](https://user-images.githubusercontent.com/6722074/165133416-8351349f-b906-4ae6-8e39-b80cfb6243a0.png)
