### ISSUE TITLE
[studio] Group management - get-all and group services returning group_description field

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#555]
get-all.json and get.json services should return "description" field as in documentation, right now the field is "group_description".

http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-groups.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-group.html

**Comment by dejan-brkic** [comment]
PR #567
