### ISSUE TITLE
[studio-ui] There's no feedback when trying to open a folder with a lot of images in the image picker

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5550]
#### Crafter CMS Version
3.1.22

#### Date of Build
N/A

#### Describe the bug
There's no feedback when trying to open a folder with a lot of images in the image picker. I would be great if there was a spinner like in the sidebar

#### To Reproduce
1. Create a site based on Editorial
2. Create a `folder1` under `static-assets/images` and under that folder, a `folder2`
3. Copy the images under `static-assets/images` 30 times and put them under `static-assets/images/folder1/folder2` 
4. Git add and commit
5. From Studio, open the Home page for edit and then replace the Hero Image so you open the image picker.
6. Observe how if you navigate to `folder2`, nothing seems to happen, but if you wait some time the image preview will appear. Normally you would expect a spinner in the folder while it's being opened, like in the sidebar

https://user-images.githubusercontent.com/1598884/165143690-9d7c16ad-7c58-4f45-b87d-7e016c441516.mp4

**Comment by jvega190** [comment]
Not an issue in 4.0.x with new browse dialog

**Comment by jvega190** [comment]
@avasquez614 ready for testing in 3.1.x

**Comment by sumerjabri** [comment]
@Euquimides please help validate this issue

**Comment by jvega190** [comment]
works properly in 4 (even old browse dialogs for cmis, webdav, etc)
