### ISSUE TITLE
[studio-ui] Duplication/deletion using XB allowed event though there are min/max restrictions

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5552]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-d05035`

#### Date of Build
`4/26/2022`

#### Describe the bug
Social Media Widget allows duplication using XB even though it should only allow one instance or occurrence of the widget. 

#### To Reproduce
1. Go to a site based on 'Editorial' blueprint.
2. Enable XB 'Move mode' in the UI. 
3. Duplicate the 'Social Media Widget' using the duplicate option in the XB menu of the selection. 
4. Enable XB 'Edit mode' in the UI.
5. Select 'Social Media Widget' then 'Edit' in XB menu. 
6. See the error

#### Logs
N/A

#### Screenshots
![Screenshot from 2022-04-26 08-23-17](https://user-images.githubusercontent.com/90878288/165371919-79de18f5-4715-4784-903f-ef04f8943112.png)

https://user-images.githubusercontent.com/90878288/165371942-ebcdbf90-e3ce-433d-b169-80a9e68ab8cf.mp4

**Comment by jvega190** [comment]
Update the ticket name because is general and not only editorial. @Euquimides please let me know if you need any details when validating.

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed. Thank you! Closing this ticket.
