### ISSUE TITLE
[studio] Publishing Queue icon out of sync with with message and queueing item message should not override stopped message

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5553]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/25/2022

#### Describe the bug
Publishing queue icon/message not in sync when the queue is stopped and user publishes an item.
The color of the icon, the notice on the icon and the message should all be consistent.
Publishing an item into the queue should NOT override the stopped status.

#### To Reproduce
1. Stop the publisher. 
2. Note red icon and status says stopped by admin
3. Publish an item
4. Note green icon, red '!' and message says items are queued. 
5. The issue is the message should say the queue is stopped, and the icon should be red.

#### Logs
N/A

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/5578
