### ISSUE TITLE
[studio-ui] Studio Search and Search Dialogs have Path filter that limits to current path only

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5556]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4-27-2022

#### Describe the bug
Studio Search and Search Dialogs have a Path filter that limits to the current path only.
This does not allow you to search across children of a path.  

#### To Reproduce
1. Open Studio Search
2. Set Path to /static-assets/images
3. Enter Keyword `facebook` which is in subfolder of images, 
4. Note the image does not show in the result

#### Logs
N/A

#### Screenshots
N/A

**Comment by russdanner** [comment]
Cannot attempt this test case because path filter limits search to /site

**Comment by rart** [comment]
@jvega190 let's start with this as a first step to allow selecting other standard paths. Will enhance later as apis become available for non-standard paths or allowing more dynamic interface.

![Search](https://user-images.githubusercontent.com/3928341/178298164-daaa7676-b760-48bd-a77b-18e268488c8b.png)

**Comment by russdanner** [comment]
General search works great. Love it.

Search via existing image data source with search offers all paths (not ideal) but more importantly, I can't specify a path. Nothing happens when i click into the path field
<img width="1395" alt="Screen Shot 2022-07-15 at 1 02 55 PM" src="https://user-images.githubusercontent.com/169432/179273212-37ce3803-d220-472c-b14c-6a4bb8ab238d.png">

**Comment by rart** [comment]
@jvega190 ??

**Comment by jvega190** [comment]
@russdanner We're removing the base paths selector from the datasource mode. The disabled input for the datasources view is the original behavior (for it to show only the set path in the datasource). We removed the magnifier glass when the input is disabled, to avoid confusions.

**Comment by rart** [comment]
@jvega190 for the datasource case, let's try to leave the path selector & lookup open to select from what ever the data source root is onwards. DS would dictate root path and users can still constraint the search to inner paths of whatever root.

**Comment by rart** [comment]
> @jvega190 for the datasource case, let's try to leave the path selector & lookup open to select from what ever the data source root is onwards. DS would dictate root path and users can still constraint the search to inner paths of whatever root. Given this, we rollback the hiding of the mag glass on the path selector input.

Will take this as a future enhancement. The datasource case stays simply locked to the path chosen on the datasource definition for now.
