### ISSUE TITLE
[studio-ui] Browse dialog should use explore style browsing

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5557]
#### Is your feature request related to a problem? Please describe.
The new browse dialog uses a tree that can fall victim to many nested folders.

<img width="1314" alt="Screen Shot 2022-04-27 at 2 18 27 PM" src="https://user-images.githubusercontent.com/169432/165596589-82ad56e2-3645-4395-b778-bcf8f32bec07.png">

#### Describe the solution you'd like
Use an Side Bar explorer style ux with pagination and filtering

**Comment by jvega190** [comment]
Per discussion, let's add filtering to `getChildrenByPath`, so we can do filters like `only folders` and so.

**Comment by jdrossl** [comment]
@jvega190 a new `systemTypes` filter has been added and it is merged now

**Comment by jvega190** [comment]
@jdrossl per discussion, we need to consider the systemType filter in the childrenCount of each result

**Comment by jdrossl** [comment]
@jvega190 the fix is merged now

**Comment by sumerjabri** [comment]
Verified per Russ
