### ISSUE TITLE
[studio][studio-ui] Sidebar does not update via Websocket for Cut Paste operations

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5559]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
4/24/2022

#### Describe the bug
If a user cuts an item and pastes it elsewhere the sidebar in the target location is not updated by WebSocket for users who have that folder open.

#### To Reproduce
1. As user A browse to a sub-article folder in Editorial via sidebar
2. As user B cut a landing page and paste it into the article folder
3. Note user A sees no update

#### Logs
N/A

#### Screenshots
N/A

**Comment by rart** [comment]
@jdrossl when the cut occurs, all the socket sends is a REPO event. The UI can't do much with it's current level detail.

e.g.
```js
{
  type: 'REPOSITORY_EVENT',
  payload: {
    timestamp: 1651247455764,
    user: null,
    siteId: 'editorial-neue',
    eventType: 'REPOSITORY_EVENT'
  }
}
```

**Comment by jdrossl** [comment]
@rart that happens when there is an error and the operation doesn't finish but the commits are already in the repo

**Comment by rart** [comment]
When there's no error, we get CONTENT events (in fact 2 identical — why?).

```js
{
  type: 'CONTENT_EVENT',
  payload: {
    timestamp: 1651248942637,
    user: {
      id: 1,
      username: 'admin',
      firstName: 'John',
      lastName: 'Doe',
      avatar: null
    },
    siteId: 'editorial-neue',
    targetPath: '/site/website/style/index.xml',
    eventType: 'CONTENT_EVENT'
  }
}
```

Neither of the events have a target that pertains to the current path in the navigator which is why it doesn't reload.

**Comment by Euquimides** [comment]
Hi! I am seeing a HTTP 403 on cut & paste operations while working either as an `Author` or `Publisher` roles, that might be related with this issue:

`{"response":{"code":2001,"message":"Unauthorized","remedialAction":"You don't have permission to perform this task, please contact your administrator","documentationUrl":""}}`

![Screenshot from 2022-04-29 11-10-42](https://user-images.githubusercontent.com/90878288/165991401-7f589e8e-1a07-4137-8851-ee6cf2c255f8.png)

**Comment by Euquimides** [comment]
Hi @jdrossl ! Got it, I will make a new ticket.

**Comment by jdrossl** [comment]
This issue is caused because right now there is only one [ContentEvent](https://github.com/craftercms/studio/blob/09db00466a9dc99a36b5b8852e4c2b4253eab3b3/src/main/java/org/craftercms/studio/api/v2/event/content/ContentEvent.java#L29) for all operations, to fix it a new class `MoveContentEvent` needs to be added and include not only the target but the source path too. The new event needs to be used [here](https://github.com/craftercms/studio/blob/1883ae4476acebfc9f1e7dcf26f0aabf2bd04f22/src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java#L1015)

**Comment by sumerjabri** [comment]
@phuongnq you should also review the design document, I'll share that with you shortly.

**Comment by phuongnq** [comment]
Added PR to have event "MOVE_CONTENT_EVENT
![2022-05-31_16-21](https://user-images.githubusercontent.com/2996543/171140481-d827358d-6f41-42aa-b8b6-44a5d94f3070.png)
" with both `sourcePath` and `targetPath`

**Comment by jdrossl** [comment]
@phuongnq after the PR is merged this ticket needs to be assigned to Roy

@rart just a heads up, soon there will be a new websocket event

**Comment by rart** [comment]
Not sure if it's intended but right after receiving the `MOVE` event, a `CONTENT` event is also received. They overlap. It'd be best to get `MOVE` only. There's no need for the `CONTENT` and it might cause duplicate reloads on the UI.

The `MOVE` event:
```js
{
  type: 'MOVE_CONTENT_EVENT',
  payload: {
    timestamp: 1654262472784,
    user: { /* ... */ },
    siteId: 'editorial-neue',
    targetPath: '/templates/web/components', // <===
    sourcePath: '/templates/web/test.ftl',
    eventType: 'MOVE_CONTENT_EVENT'
  }
}
```

The `CONTENT` event:
```js
{
  type: 'CONTENT_EVENT',
  payload: {
    timestamp: 1654262472792,
    user: { /* ... */ },
    siteId: 'editorial-neue',
    targetPath: '/templates/web/components', // <===
    eventType: 'CONTENT_EVENT'
  }
}
```

**Comment by sumerjabri** [comment]
@phuongnq it would be best to send a single event for every action.
One way we can do this is to emit the event at a higher level in the call stack. Consider using the public service layer as the layer from which to emit the event to avoid emitting multiple smaller events in the lower layers.

Think about it and ping me with any questions or ideas.

**Comment by phuongnq** [comment]
Updated to have only `MOVE_CONTENT_EVENT`.

**Comment by russdanner** [comment]
Confirmed
