### ISSUE TITLE
[studio] Forgot password API doesn't return 404 if user is not found

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#556]
It seems to return 500. Please fix per API definition: http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/forgot-password.html

**Comment by dejan-brkic** [comment]
Seems like it works fine with latest code
![forgot-password](https://cloud.githubusercontent.com/assets/4053827/23806412/dbe861ac-05c1-11e7-94c1-9e0ae858f28f.png)
