### ISSUE TITLE
[studio-ui] Root folder in `static-assets` is being deleted when deleting last folder or item in it. Also, some folders aren't being deleted

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5562]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-801065`

#### Describe the bug
If `Static - Assets` folder has just one item or folder available, upon deletion of that item or folder, the root folder will also be deleted. Pre-defined folders in `Scripts` (like `rest` or `pages`) or `Templates` (like `js` or `css`) are not being deleted even though the available action is active.  

#### To Reproduce
1. As admin, go to either `Empty` BP or `Editorial` BP. 
2. If using `Empty` BP, delete the `image` folder in `Static Assets` to notice error. 
3. If using `Editorial` BP, try deleting either `js` or `css` folders to notice that this folders aren't being correctly deleted.
4. Click on the folder that you previously tried to delete. 
5. See the error

#### Logs
The error that is shown when trying to delete this folders, is the next one:
```
Error 7000
Content not found. None of the requested content paths were found in site 't2'.
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/165644886-2fa02b91-9115-4305-a358-f24eecec3312.mp4

![Screenshot from 2022-04-27 15-34-27](https://user-images.githubusercontent.com/90878288/165644910-64fc6715-2e38-4c3a-b82d-2b88ee82a813.png)

**Comment by jdrossl** [comment]
@sumerjabri @phuongnq after a lot of debugging I discovered that the issue was caused by missing .keep files, given the current code it is required for all folders that are visible in the sidebar to have a .keep for deletes to be processed as expected

**Comment by sumerjabri** [comment]
For future reference, it may make sense to add `.keep` at some point in case the blueprints developer, or through a pull, folders flow in without. Or refactor to not require this.

**Comment by Euquimides** [comment]
Hi @sumerjabri and @jdrossl ! After updating a re-checking this issue, I noticed that even though the root folder isn't deleted anymore, if you delete a folder and try to create a folder with the same as the deleted one, the UI will show a message that the folder already exists. This also happens with new content. You can override or ignore the UI message by pressing the `Enter` key and the content or folder will be created. Maybe the items aren't being correctly deleted or is it related with the .keep files? 

https://user-images.githubusercontent.com/90878288/172266770-57f1d662-4593-4f02-8b51-e17f513ab5de.mp4

**Comment by rart** [comment]
@sumerjabri item (1) yes, (2) it's a miss [from these fixes](https://github.com/craftercms/craftercms/issues/5593)

@jvega190 for (1), we need to delete the items from the state when deleting content. (2) should be fixed under 5593 branch.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
