### ISSUE TITLE
[studio][UM] Update incorrect id in ui.xml

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5566]
- [x] Have UM change `craftercms.components.ItemStatesManagement` to `craftercms.components.WorkflowStateManagement`
- [x] Update the built-in BP
- [x] Update all marketplace BPs

**Comment by jdrossl** [comment]
@rart should the text be replaced everywhere or in a specific location inside the file?

**Comment by rart** [comment]
@jdrossl anywhere in the `ui.xml` (there's only one instance, though)

**Comment by rart** [comment]
Confirmed UM performed upgrade to existing sites.
