### ISSUE TITLE
[studio-ui] Legacy studio admin code doesn't handle only one tool in site-config-tools.xml

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5568]
#### Crafter CMS Version
4.0.0-SNAPSHOT-b859e8

#### Date of Build
4/28/2022, 2:25 PM

#### Describe the bug
Now that the configuration from site-config-tools was updated and most of the tools were removed, we only have one tool (the content-types configuration). And the legacy code fails trying to read that only tool (since is not an array).

#### To Reproduce
1. Go to Project Tools > Content Type Editor Config
2. Check that the only tool available is the content-types config.
3. Open content-types
4. See the error (it won't load)

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue and compared it with previous build. It is working fine now. Thank you! Closing this ticket.
