### ISSUE TITLE
[studio-ui] Add option to image picker to disallow upload of SVG

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5569]
#### Is your feature request related to a problem? Please describe.
Some administrators what to disallow SVG upload in 3.1.x

#### Describe the solution you'd like
Add this an option in the image picker
Default the picker to disallow SVG

#### Describe alternatives you've considered
4.x has a policy engine for this purpose

**Comment by sumerjabri** [comment]
@rart we need the control to disallow `svg` files.
