### ISSUE TITLE
Add a permission that allows a user to create and manage other users and groups

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5570]
#### Is your feature request related to a problem? Please describe.
Today creation and management of users and groups are tied to the system-admin role.   Some organizations want to designate a user or a group of users that can manage other users and groups but do not want to make these individuals full system admins.

#### Describe the solution you'd like
Add permission that can be tied to a role that enables the creation and management of users

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
Will not pursue.
