### ISSUE TITLE
[studio-ui] `Display Template` field in `Content Types` still showing path after template deletion

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5575]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-572282`

#### Date of Build
`5/2/2022`

#### Describe the bug
When assigning a template to a content, upon deletion of that template, the field `Display Template` in `Content Types` will still show the path of that template.

#### To Reproduce
1. Go to any project. 
2. Go to `Project Tools`
3. Go to `Content Types`
4. Create a new content type.
5. Assign a template or create a new one through the `Display Template` field in properties.
6. Delete the assigned template. 
7. Go to the newly created content type. 
8. See error. 

#### Logs
When selecting edit button in the `Display Template` field inside `Content Types`, Studio will call the deleted path through `content/item_by_path` API, opening the UI Editor which stays loading:

REQUEST: GET `http://localhost:8080/studio/api/2/content/item_by_path?path=%2Ftemplates%2Fweb%2Ftest.ftl&preferContent=true&siteId=test`

```
path: /templates/web/test.ftl
preferContent: true
siteId: test
```
RESPONSE:
```
{"response":{"code":7000,"message":"Content not found","remedialAction":"Check that path '/templates/web/test.ftl' is correct and it exists in site 'test'","documentationUrl":""}}
```

#### Screenshots

https://user-images.githubusercontent.com/90878288/166340669-cddac3a4-9f7a-4cb2-84e8-39f85ee1cda6.mp4

**Comment by rart** [comment]
@sumerjabri 

This isn't a UI problem per se. The templates folder is detached from content types and so is the delete API — as opposed to when using the delete template action where things are contextually bound. 

Here's what we can do if we resolve this from the UI:
- We do keep content types loaded so what we can do is run a second process when delete template is performed that will iterate through the in-memory content types find if their template matches what's being deleted, dissociate the template from the type.
  - Maybe we check beforehand and warn the user about deleting a template associated with a type?
  - If an in-memory content type isn't up to date **on the client that performs the action** then, the issue would still happen.
- Have a background process listening for socket configuration or content events that looks for `/config/studio/content-types/*` to keep content types up to date on clients
  - FYI: The socket sends for a single content type update 4 different events instantly — 1 `CONTENT_EVENT` and 1 `CONFIG_EVENT` for `form-definition.xml` and `config.xml`. Will have to figure out a way to reload the type only once.

Doesn't feel like something we should solve on the UI alone but we can _walk_ with this.

**Comment by rart** [comment]
@jvega190 will _walk_ with creating the template file if it doesn't exist. Same handling we applied when "edit controller" was requested and there wasn't a controller.

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now, thank you! Closing this ticket.
