### ISSUE TITLE
[studio-ui] numeric input' field doesn't work in Firefox 99.0

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5576]
#### Crafter CMS Version
3.1.24-SNAPSHOT-7cd622

#### Date of Build
May 03, 2022

#### Describe the bug
Entering a number manually works but changing it with the up and down arrows doesn't work in Firefox 99.0.
The correct number is shown in the field, but it will not be saved after submitting the form.

#### To Reproduce
1. Create a site
2. Add a numeric field to a content type
3. Create a new item with content type from (2)
4. Open in Firefox 99 to edit the form
5. Using up/down arrows to change the numeric number value
6. Click "Save and Close"
7. Open the form again and notice that input for numeric does not change

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by jvega190** [comment]
@phuongnq ready for testing in 3.1.x

**Comment by phuongnq** [comment]
Verified fixed in 3.1.x. Thank you!

**Comment by jvega190** [comment]
Hi @phuongnq, this is ready for validation in 4.0.1

**Comment by phuongnq** [comment]
Verified in 4. Thank you!
