### ISSUE TITLE
[studio-ui]  Log console in dark theme is inconsistent

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5577]
#### Crafter CMS Version
`4.0.0-SNAPSHOT-448f33`

#### Date of Build
`5/3/2022`

#### Describe the bug
The Log Console in the Global menu shows a unreadable section when the user scroll downs. In the site local log console the color is a bit different `

#### To Reproduce
1. Create a site from any bp.
2. Populate some entries in the `Log Console`

#### Logs
N/A
#### Screenshots
![image](https://user-images.githubusercontent.com/6722074/166476369-1a78d902-dff7-42bc-bdfa-cbcec06e82c3.png)

https://user-images.githubusercontent.com/6722074/166476178-220d1afe-d3d7-482e-9b10-f84c05b85f15.mp4

**Comment by yacdaniel** [comment]
Verified fixed.

**Comment by rart** [comment]
@yacdaniel changed fix approach. please re-test.

**Comment by yacdaniel** [comment]
Verified fixed.
