### ISSUE TITLE
When trying to publish a blob file and it fails to publish, Studio stills sets the state of the blob as published

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5583]
#### Crafter CMS Version
3.1.23

#### Date of Build
05/04/2022

#### Describe the bug
When trying to publish a blob file and it fails to publish, Studio stills sets the state of the blob as published. This is a big problem if the error is based on a blob store mis-configuration or some S3 connection issue because even if you fix the underlying issue you can't re-publish unless you re-upload the image.

#### To Reproduce
1. Create a site based on Editorial
2. Go to the Site Config > Configuration > Blob Stores and copy/paste the sample blob store config and save (we're creating an invalid config on purpose).
3. From the command line or the OS file browse, got to `static-assets/s3` and create the `mountains.jpg.blob` file with the following content, then commit:

```
<blob>
  <storeId>s3-store</storeId>
  <hash>-1</hash>
</blob>
```

5. Bulk publish `/`

You should see an error in the `catalina.out` indicating that the bulk publish failed (which is expected). However, if you go to `Site Config > Workflow States` and look for the `mountains.jpg.blob` you'll see that the state is `EXISTING_UNEDITED_UNLOCKED`, which means Studio set the file as published when it wasn't

**Comment by avasquez614** [comment]
It seems actually ALL files are shown as published, even though the publisher still keeps them in the publishing queue and will retry to publish them next time publishing is enabled

**Comment by Euquimides** [comment]
This issue is also present in Crafter v4.0

**Comment by avasquez614** [comment]
It seems it's not just with blobs. If publishing fails (for example if you manually lock the published repo), everything that you try to publish is set as published, but the items are still in the publishing queue

**Comment by sumerjabri** [comment]
This should follow the Recycle Bin and Publish by Package tiickets.

**Comment by jmendeza** [comment]
This seems to happen to all items, not only blobs

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
