### ISSUE TITLE
[studio] [studio-ui] Renaming the URL of a page to an existing folder should make the page the index.xml of the folder

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5586]
#### Crafter CMS Version
3.1.23 and up

#### Date of Build
N/A

#### Describe the bug
Renaming the URL of a page to an existing folder should make the page the index.xml of the folder. This is to be consistent with how creating a page works (when you create a page and set the URL as the URL of an existing folder, it makes the page the index.xml of the folder).

#### To Reproduce
1. Create a site based on Editorial
2. Rename the `Style` category page to `/articles`

The rename seems to initially work but when inspecting the sidebar it looks like the folder and page are now broken (see screenshot). What's expected is that the `Style` page replaces the article folder and the article folder children appear under the `Style` page.

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/166954664-634ca817-49cb-4956-b187-785b101048b8.png)

**Comment by jdrossl** [comment]
In 3.1 there is also an error in the log:

```
[ERROR] 2022-05-09T10:45:33,044 [http-nio-8080-exec-5] [git.GitContentRepository] | Error while moving content for site: ed2 fromPath: /site/website/style toPath: /site/website/articles newName: null 
org.apache.commons.io.FileExistsException: Destination '/home/jose/github/3.1.x/crafter-authoring/data/repos/sites/ed2/sandbox/site/website/articles/.keep' already exists
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2825) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2871) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.moveToDirectory(FileUtils.java:2902) ~[commons-io-2.4.jar:2.4]
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.moveContent(GitContentRepository.java:530) [classes/:3.1.24-SNAPSHOT]

```

**Comment by jdrossl** [comment]
In 3.1.x the UI is capable of displaying the error

@sumerjabri in 4.x should we update the control to prevent the call?

**Comment by Euquimides** [comment]
Hi @jdrossl and @rart ! While validating this ticket I noticed this issue in v4.0 related with unlock. When you edit the Page URL of a page, for the Page URL of an existing folder or page, the UI will not allow the operation since the Page URL already exists. When canceling the form, the `item_unlock_by_path` API will request the path as if it the Page URL of the item was effectively edited, showing an HTTP 404. Here is the video:

https://user-images.githubusercontent.com/90878288/169337540-aaecace9-bc48-467b-b325-49149a5502b7.mp4

**Comment by Euquimides** [comment]
Hi! I updated an re-checked this issue. It is fixed now, thank you! Closing this ticket.
