### ISSUE TITLE
[deployer] If create index fails, the whole deployment pipeline is stopped and the error is not stored and an email notification is not sent

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5587]
#### Crafter CMS Version
3.1.23

#### Date of Build
N/A

#### Describe the bug
If create index fails, the whole deployment pipeline is stopped and the error is not stored in the deployments CSV and an email notification is not sent.

#### To Reproduce
1. Create any site
2. Stop ES
3. Make any change in Authoring

An error is thrown in the logs. Normally you would expect the deployments CSV to contain a `FAILURE` entry for the deployment but this is not the case. It seems to be because the code (https://github.com/craftercms/deployer/blob/support/3.1.x/src/main/java/org/craftercms/deployer/impl/processors/AbstractSearchIndexingProcessor.java#L201) that checks and creates the index when needed is executed without indicating a `FAILURE` in the pipeline and letting the pipeline continue so that the error can be processed by the output processors. It should do something like the following: https://github.com/craftercms/deployer/blob/support/3.1.x/src/main/java/org/craftercms/deployer/impl/processors/AbstractMainDeploymentProcessor.java#L63.

**Comment by jmendeza** [comment]
Moved the code that ensures index creation so it is part of the already existent error handling.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
