### ISSUE TITLE
[studio] Publishing error email notification enhancements

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5590]
#### Is your feature request related to a problem? Please describe.
Whenever an error occurs in publishing, an email is sent. The problem with these emails is that 1) the files that were attempted to be published are not indicated and 2) The full exception, with the stack trace, is not included.

#### Describe the solution you'd like
Files that were attempted to publish and the full stack trace of the error should be sent in the notification emails.

**Comment by avasquez614** [comment]
Validated in 3.1.x

**Comment by Euquimides** [comment]
Hi! Verified and validated this feature in Crafter v4. Thank you! Closing this ticket.
