### ISSUE TITLE
[studio] Add API to bulk publish all

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5591]
#### Is your feature request related to a problem? Please describe.
Bulk publish right now is a complicated API that needs refactoring, and a lot of the time developers just need a way of putting all changes in the sandbox into the published directory.

#### Describe the solution you'd like
Provide an API to bulk publish all changes in the sandbox (basically copy all the sandbox changes to the published repository).

**Comment by sumerjabri** [comment]
@avasquez614 please use OAS to spec out the API and share it for review prior to full impl

**Comment by sumerjabri** [comment]
@jdrossl please also update the API definition for v4, see https://github.com/craftercms/studio/pull/2977

**Comment by avasquez614** [comment]
Having some issues:

- Publish all fails if the published repo and the `live` branch doesn't exist.
- On publish all failure we're trying to do a `generalLocService.unlock` twice which ends up in exception.

Already discussed this issues with @jdrossl

**Comment by yacdaniel** [comment]
@jdrossl please check when an user publish to `staging` using `/publish/all` the workflow state is set to `EXISTING_UNEDITED_UNLOCKED`  when it should be 
- `NEW_UNPUBLISHED_UNLOCKED` for new items that are published all to `staging`
- `EXISTING_EDITED_UNLOCKED` for items that are in `live` then are edited and published all to `staging`

**Comment by sumerjabri** [comment]
@avasquez614 we need the same PR for v4

**Comment by avasquez614** [comment]
Verified
