### ISSUE TITLE
[studio][studio-ui] Prevent creating existing files, folders or content

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#5593]
As requested in https://github.com/craftercms/craftercms/issues/5586#issuecomment-1127679750

**Comment by sumerjabri** [comment]
The UI should check if the item/folder exists, if so, warn the user and disallow the action. Be careful not to check too often to not slow down the back.

The back should fail with a 409 if an item or a folder already exists. If a page is being created with the same name as a folder it should also fail, that was handled in #5586.

**Comment by jvega190** [comment]
@sumerjabri When creating a page with the same name as a folder it doesn't fail, the folder becomes a page and after that the children content of the original folder gets lost. Is this something that still need to be addressed?

**Comment by sumerjabri** [comment]
Yes, this is a bug. @phuongnq please see @jvega190 's comment above.

**Comment by phuongnq** [comment]
@sumerjabri @jvega190, that bug is what this PR https://github.com/craftercms/studio/pull/3009 is fixing. In this case, it would fail with status code 409.
Let me know if we have other cases that need to fix.

Thanks.

**Comment by jvega190** [comment]
Confirmed https://github.com/craftercms/studio/pull/3009 fix. UI is ready

**Comment by jdrossl** [comment]
Verified

**Comment by rart** [comment]
@jvega190 
- On create folder and file dialogs: 
  - Though the button is disabled, the form submission (via enter) is not.
  - When not all of the children of the target folder are loaded, the dialogs won't realise that the file exists. 
    - Add a pre-creation `fetchItem()` call to make sure the file doesn't exist in the back either
      - if it doesn't, `switchMap` to the creation
      - if it does, push to the state and the dialog should reflect that the item exists
- Create a ticket to implement pre-creation-check for files & folders on the back and, on the UI, remove pre-check and handle the backend rejection (per discussion with @sumerjabri).

**Comment by jvega190** [comment]
@Euquimides can you please help me validating the last comments of this ticket? Please let me know if you have questions.

**Comment by rart** [comment]
@jvega190  

> - Create a ticket to implement pre-creation-check for files & folders on the back and, on the UI, remove pre-check and handle the backend rejection

Was the ticket created?

**Comment by jvega190** [comment]
> @jvega190
> 
> > * Create a ticket to implement pre-creation-check for files & folders on the back and, on the UI, remove pre-check and handle the backend rejection
> 
> Was the ticket created?

yeah it was, here https://github.com/craftercms/craftercms/issues/5645

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
