### ISSUE TITLE
Indicate when gitlog commits are still being processed before publishing

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5594]
#### Is your feature request related to a problem? Please describe.
Right now when you do a big git pull and you want to try to bulk publish the files, the publishing might be missing a lot of files since not all commits in the `gitlog` are processed and the files added.

#### Describe the solution you'd like
Show a warning in the publishing console UI indicating that Studio still is processing files so a publish is not recommended yet, and if possible lock the publishing so no one can publish until the commits int the `gilog` are all processed.

**Comment by sumerjabri** [comment]
We want to indicate through the UI that the system is processing. We must disallow some actions, and continue to allow other. The UI can show that the system is processing, and we can use events, and we should scope it to the full ingestion not per file.

Let's discuss.

**Comment by sumerjabri** [comment]
We're not tracking in `gitlog` anymore; that table has been dropped. However, even though the processing is much faster now, it's still there. We must track that state however short it may be.

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
