### ISSUE TITLE
[studio] After creating a groovy controller on config folder using write-content API, it isn't added to the database

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5595]
#### Crafter CMS Version
4.0.1-SNAPSHOT-6189cf

#### Date of Build
5/16/2022, 10:59 AM

#### Describe the bug
When using the `write-content` API to create a groovy controller under `/config/studio/..` folder and then using the `item_by_path` API, the content returned is `null`, and when checking on the DB, the content is not there.

#### To Reproduce
1. Using this branch https://github.com/craftercms/studio-ui/pull/3003
2. Create a site based on editorial.
3. Manually delete/commit the controller of a page/component.
4. Go to content-types editor, and edit the content type related of the page/component that you deleted the controller from.
5. Look for the controller entry and click on the pencil to edit (when clicking on the edit button if the item doesn't exist will create a new file in that path).
6. See network for the `item_by_path` call of the recently created item, and see how the content is null.
7. If you check the DB, you'll see that the item is not there.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by sumerjabri** [comment]
CC @jdrossl FYI. This should help @phuongnq get more familiar with item processing and insertion into the database.

**Comment by phuongnq** [comment]
I cannot reproduce this as of the current `develop` branch.
See the screenshots below. The new controller is added to `item` table.
![2022-06-03_17-44](https://user-images.githubusercontent.com/2996543/171839651-fbc919b8-ba60-43c5-8ee9-1b6a5df8a664.png)
![2022-06-03_17-44_1](https://user-images.githubusercontent.com/2996543/171839657-398a74be-26f3-441a-aed1-4d24753a8dd7.png)
![2022-06-03_17-47](https://user-images.githubusercontent.com/2996543/171839832-2230acc1-f77e-4448-88eb-f8b79aad2fa6.png)

**Comment by jvega190** [comment]
Closing this issue as it is not reproducible anymore.
