### ISSUE TITLE
[studio-ui] Increase Audit Report Sites and User drop-down to display all sites and users

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5602]
#### Is your feature request related to a problem? Please describe.
Currently the Audit Report Sites drop-down only displays a maximum of 10 sites, and the User drop-down displays a maximum of 60 users.

#### Describe the solution you'd like
The respective drop-downs should not be limited, instead, they should display all users and sites (via the scrollbar display).

#### Describe alternatives you've considered
N/A

**Comment by russdanner** [comment]
@rart I believe this was addressed in 3.1.24. Confirming.

**Comment by AndyReiter** [comment]
Confirmed in 3.1.25-SNAPSHOT
