### ISSUE TITLE
[engine] Groovy filters should execute in forward, includes and errors

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5603]
#### Is your feature request related to a problem? Please describe.
Groovy filters sometimes are used to set up request attributes and other info used in error pages, like a locale attribute. If an error page needs these attributes, it can't use them because Groovy filters are only run on requests.

```
    <filter-mapping>
        <filter-name>crafter.scriptFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
    </filter-mapping>
```

#### Describe the solution you'd like
Groovy filters should be executed in all types of requests.

```
    <filter-mapping>
        <filter-name>crafter.scriptFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>FORWARD</dispatcher>
        <dispatcher>INCLUDE</dispatcher>
        <dispatcher>ERROR</dispatcher>
    </filter-mapping>
```

#### Steps to validate
- Create a site from Editorial BP
- Create a Groovy filter and set a request attribute in the filter, `foo=bar` (see this ticket for how to do that https://github.com/craftersoftware/craftercms/issues/346)
- Create an error page (404 FTL) in the FTL access `foo`
- If the attribute is visible, the feature has been implemented successfully

**Comment by sumerjabri** [comment]
CC @jdrossl

**Comment by Euquimides** [comment]
Hi! Verified. The feature has been added in both v3.1 and v4.0.
