### ISSUE TITLE
[studio-ui] Make the site cookie domain configurable as base or sub

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5604]
#### Is your feature request related to a problem? Please describe.
In some cases, it is desirable to set the crafter site cookie at the base domain instead of a subdomain to allow other applications to know the current site.

#### Describe the solution you'd like
- Create a flag in `studio-config-override.yaml` to indicate if the base domain is to be used instead of the default.
- If the flag is set, use the base domain, otherwise do what you do today

For example, if the domain is `sub.example.com`, use `example.com`. If the domain is `sub.sub.example.com` use `example.com`.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by jvega190** [comment]
Hi @alhambrav! We need to document that all users should clear their cookies after doing this change to avoid cookie collisions that can’t be cleaned up by the app due to web security restrictions.

**Comment by yacdaniel** [comment]
Verified fixed.
