### ISSUE TITLE
[studio] After a Git pull the changes are not added correctly to the DB

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5607]
#### Crafter CMS Version
3.1.23 and up

#### Date of Build
N/A

#### Describe the bug
After doing a Git pull, new files are not added to the DB and updates to existing files do not cause the status of the files to change to edited.

#### To Reproduce
1. Create a site based on Editorial and push it to a remote.
2. Create another site pulling from the remote.
3. Bulk publish the entire second site (`/`).
4. On the first site, create new articles or duplicate/copy the existing ones to generate new files. Also, update some existing articles.
5. Push the changes from the first site to the remote.
6. Pull the changes from the remote into the second site.
7. Go to workflow states.

No changes appear on the workflow states page. The new files don't seem to have been added to the DB and the state of the existing files with the updates is still `EXISTING_UNEDITED_UNLOCKED`.

**Comment by sumerjabri** [comment]
CC @phuongnq

**Comment by jdrossl** [comment]
@avasquez614 this is ready for testing in 3.1.x, let me know the result to port to 4.0

**Comment by avasquez614** [comment]
Validated in 3.1.x

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. It is fixed now. Thank you! Closing this ticket.

**Comment by avasquez614** [comment]
Re-opening since the fix is not in `develop` yet

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.1-SNAPSHOT`
