### ISSUE TITLE
[studio] Can't create new sites on Windows

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#561]
On new windows deployment ( no db, prior repo)  login as admin does not show up  the create site button

**Comment by jvega-crafter** [comment]
When calling the get-user permissions service (api/1/services/api/1/security/get-user-permissions.json?path=%2F&site=&user=admin) it's returning {"permissions":["read"]},
but it should return {permissions: ["create folder", "read", "publish", "create-site", "write", "delete"]}. Without proper permissions the "Create Site" button won't render.

**Comment by dejan-brkic** [comment]
Done
PR #588
