### ISSUE TITLE
[studio-ui] Update the Pull from Remote dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5610]
#### Is your feature request related to a problem? Please describe.
Pulling from a branch other than current can cause issues with multi-parent commits that flow in from different branches causing issues. The safest approach is to have these merged upstream and only pull from a single clean branch.

#### Describe the solution you'd like
- [x] Make the remote branch the same as the current branch and disable the dropdown so the user can no longer choose a different branch
- [x] Update any related documentation

#### Describe alternatives you've considered
None. This is related to multi-parent git sync issues.

Related to https://github.com/craftercms/craftercms/issues/5607

**Comment by rart** [comment]
<img width="475" alt="pull-dialog" src="https://user-images.githubusercontent.com/3928341/170758407-d1747bbf-4e1f-4314-b71b-c5f37a8e62c8.png">

**Comment by sumerjabri** [comment]
@alhambrav FYI this becomes a 4.0 thing only.

**Comment by rart** [comment]
Rolling back for 3 only? What's the strategy for 4? Wouldn't customers coming for 3 suffer from the same issue on 4 too? What are we doing in 4? @sumerjabri lets sync up.

**Comment by Euquimides** [comment]
Hi! Updated and checked the feature implementation in both 3.1 and 4.0. It is working correctly and the documentation is updated. Closing this ticket.
