### ISSUE TITLE
[studio] Default Studio Config is Read Instead of Environment Specific Config 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5612]
#### Crafter CMS Version
4.0.0

#### Date of Build
N/A

#### Describe the bug
Changing environment config has no impact on Studio. Changing the default configuration affects the installation.
This has been tested/proven for: 
- ui.xml

#### To Reproduce
1. Configure the studio server to be prod env
2. Modify the prod version of the ui.xml (change Pages label to Pages xyz)
3. Note the change is not reflected in the UI
4. Modify the default version of the ui.xml (change Pages label to Pages qps)
5. Note the change is reflected in the UI

#### Logs
N/A

#### Screenshots
N/A

**Comment by russdanner** [comment]
The workaround is to modify the default configuration to match the environment-specific needs.
We noticed that changing the default role-mapping.xml requires a server restart because of server-side caching.

**Comment by sumerjabri** [comment]
CC @phuongnq

**Comment by jdrossl** [comment]
@sumerjabri @russdanner  was this left out of 3.1 on purpose? I know `ui.xml` is new in 4 but the same will happen with any config file that the UI reads directly (like `site-config.xml`, @rart  please confirm if there are any more files)

**Comment by rart** [comment]
We read all files directly for the config management screen — where you edit config files. 

Operationally though, the ui loads:
- ui.xml
- site-config.xml
- config-list.xml
- notification-config.xml
- content type definition files

Not sure if related but there are other things which aren't loaded through the `get_configuration` api (like the above) that I don't know if they relate to all this:
- global menu
- canned messages
- "product available languages"

**Comment by jdrossl** [comment]
This is the existing API for reading & writing configuration files:
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.26#/configuration/writeConfiguration
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.26#/configuration/getConfiguration

When writing:
- if the environment is not provided then it writes to the default location
- if the environment is provided but the files doesn't exist yet it also writes to the default location
- if the environment is provided and the file exist then it is updated

This means the only way to create a file in an environment is directly in the repo, not via the UI

**Comment by sumerjabri** [comment]
@rart per our discussion, please switch the UI to always use the services with the `env` param.

**Comment by russdanner** [comment]
Confirmed
