### ISSUE TITLE
[studio] Commits are being added as unprocessed on site creation, even though all files has been processed

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5613]
#### Crafter CMS Version
3.1.23 and up

#### Date of Build
N/A

#### Describe the bug
After creating a site, all files have been added to the DB and in theory, all commits are processed. But the audit sync task is adding all commits unprocessed after that. These makes harder for pulls to be processed if the 

#### To Reproduce
1. Create a site from a repo with a lot of commits (I tested with a repo with ~120k commits, I can share it)
2. After you see the `Finish creating site` message, login into the MariaDB from CLIK
3. If you execute SQL query `select count(1) from gitlog where processed = 0;` every once in a while, you should see the number going up.

**Comment by sumerjabri** [comment]
CC @phuongnq

**Comment by jdrossl** [comment]
@avasquez614 this is ready for validation in 4.0 too

**Comment by yacdaniel** [comment]
Verified fixed.
