### ISSUE TITLE
[studio][studio-ui] Remove `Sandbox Branch` from the site creation dialog

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5615]
#### Is your feature request related to a problem? Please describe.
Now that we limited the branch that users can pull in (https://github.com/craftercms/craftercms/issues/5610), we need to make sure that the `Sandbox branch` has the same name as the remote `Git branch`.

#### Describe the solution you'd like
Remove the `Sandbox branch` input field from site creation, and use the `Git branch` to name the sandbox branch. Make sure that names like `feature/this-is-my-feature-1234` and `bug/this-is-my-bug-1234` can be used as sandbox branches and don't break any functionality.

**Comment by avasquez614** [comment]
@jvega190 can you add this description to the `Git Branch` field? `The name of the branch this project will track. Any pull operations from remotes will be done against this branch.`

**Comment by Euquimides** [comment]
Hi! Updated and checked this feature. It has been implemented successfully. Closing this ticket.
