### ISSUE TITLE
[studio-ui] Pushing to a remote branch pushes to a different branch

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5618]
#### Crafter CMS Version
3.1.23 and up

#### Date of Build
N/A

#### Describe the bug
When you have a remote with multiple branches and try to push to a specific branch, Studio instead pushes to a different branch.

#### To Reproduce
1. Create a site based on a remote with at least 2 branches, e.g. `code` and `content`. Pick the `content` branch for site creation.
2. Make some changes.
3. Push to the remote `content` branch.

If you check your remote, you should see that actually, the updated branch was `code`. This seems to be a problem from the UI. It's calling the push to remote API with the wrong branch (see screenshots attached)

#### Screenshots
![image](https://user-images.githubusercontent.com/1598884/171750761-fe1652f5-7328-4b3e-8c83-cb407f1bad74.png)
![image](https://user-images.githubusercontent.com/1598884/171750836-c07a9391-60de-4390-8eae-fc99809130bb.png)

**Comment by jvega190** [comment]
This works properly in 4.0.x, removing it from the ticket

**Comment by avasquez614** [comment]
Validated
