### ISSUE TITLE
[studio] Search doesn't work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#562]
Search at the top left doesn't work, please update the API to use the new API.

**Comment by sumerjabri** [comment]
path: studio/src/main/webapp/default-site/scripts/pages/search.groovy

needs to be followed and updated to use the latest API and tested.

**Comment by avasquez614** [comment]
Fix in PR #687

**Comment by sumerjabri** [comment]
Reference our conversation. Please rework and route back for testing.

**Comment by sumerjabri** [comment]
Search is still broken:
- It shows results before i enter queries
- If I search for `book` I get nothing (it should show things with `books`)
- If I search for `books` it doesn't show anything, it used to show

Below is a video that illustrates that. https://www.useloom.com/share/99246cb6f1ee4a22806ec345a7d2a3b2

**Comment by sumerjabri** [comment]
Jose/Vero

A few things remain here:

1. When the screen loads initially and there is nothing in the QSA to search for, the search results should be empty
2. Remove the words `(optional)` that's next to `Keywords` towards the top
3. Remove the word `WCM` from the top title `WCM Search` so it says `Search`
4. Remove `Show/Hide Descriptions` toggle
5. Make sure sorting works as expected

**Comment by vestrada** [comment]
studio-ui - PR: https://github.com/craftercms/studio2-ui/pull/443

**Comment by sumerjabri** [comment]
Some issues remain, please:
- Fix `Search Results (Showing 1-{1} of {2})`
-- {1} and {2} need to show `0 of 0` or the right values if results are present
- Make it such that it says "`No results found`" if the user clicks on search and nothing is found (but not when the page first loads)

**Comment by vestrada** [comment]
@sumerjabri , regarding to the first request I have changed the text to: "(0 results)".
The second request is done too.

Let me know if this is ok.

Thanks, Vero

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/456
