### ISSUE TITLE
[studio] Dashboard APIs `/dashboard/content/expiring` and `/dashboard/content/expired ` returning HTTP 500 response when setting either `limit` or `offset` to max value

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5622]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-cbb508`

#### Date of Build
`6/7/2022`

#### Describe the bug
When setting either `limit` or `offset` to integer max value, both the `/dashboard/content/expiring` and the `/dashboard/content/expired ` APIs, will return a HTTP 500 response. 

#### To Reproduce
Use a REST API tool:

1. Set up a request for the APIs, GET `/dashboard/content/expiring` or `/dashboard/content/expired `.
2. Fill up the required parameters. 
3. In the `offset` parameter, add `2147483647` which represents an integer's max value.
4. See the error

#### Logs
The response of the APIs will be the following:
```
{
    "response": {
        "code": 1000,
        "message": "Internal system failure: Error executing search in Elasticsearch",
        "remedialAction": "Contact support",
        "documentationUrl": ""
    }
}
```
#### Screenshots
N/A

#### Expected behavior
When sending a request with integer max value in `offset` parameter, the response should be HTTP 200 along with empty items. In case of sending max value to `limit` parameter, the response should include the items expiring or expired.

**Comment by Euquimides** [comment]
Hi @jmendeza ! While validating this ticket, I noticed that setting the `offset` query parameter to max int will still return the following response:
```
{
    "response": {
        "code": 1000,
        "message": "Internal system failure: Error executing search in Elasticsearch",
        "remedialAction": "Contact support",
        "documentationUrl": ""
    }
}
```
While `limit` query param to max int will return the correct response;
```
{
    "response": {
        "code": 1001,
        "message": "Invalid parameter(s) : Maximum supported result window (offset + limit) is 10000",
        "remedialAction": "Check API and make sure you're sending the correct parameters",
        "documentationUrl": ""
    }
}
```
Following the changes in the code:
```
   if ((params.getOffset() + params.getLimit()) > MAX_RESULT_WINDOW) {
            throw new InvalidParametersException("Maximum supported result window (offset + limit) is 10000");
        }
```
In theory `offset`  + `limit`should return that the maximum supported result window is 10K as response, but this is not the case, since setting both params to max int will throw an elasticsearch error:
```
[ERROR] 2022-06-17T10:16:52,428 [http-nio-8080-exec-6] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/dashboard/content/expiring?siteId=a1&dateFrom=2022-09-27T10:43:29.026Z&dateTo=2022-10-27T10:43:29.026Z&offset=2147483647&limit=2147483647 failed with response: ApiResponse{code=1000, message='Internal system failure: Error executing search in Elasticsearch', remedialAction='Contact support', documentationUrl=''} 
org.craftercms.studio.api.v1.exception.ServiceLayerException: Error executing search in Elasticsearch
``` 
Please check this out, thank you again!

**Comment by jmendeza** [comment]
Updated to handle the case where (offset + limit) overflows java integer

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
