### ISSUE TITLE
[studio-ui] `Reject` available action not working and affecting other elements in the UI

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5623]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-cbb508`

#### Date of Build
`6/7/2022`

#### Describe the bug
When setting any content to request publish, selecting then the `Reject` available action will not work. Also, other elements in the UI such as trying to open the `Navigation Menu` or other content `Options` will not work. For example, clicking on `Options` in any content after selecting `Reject`, will keep calling the `/content/sandbox_items` API and the available actions will not open.  

#### To Reproduce
1. Go to any project of your choice. 
2. Request publish of any content of your choice. 
3. Then `Reject` that content. 
4. See the error

#### Logs
N/A

#### Screenshots

https://user-images.githubusercontent.com/90878288/172496398-ad44b3f9-2027-4449-891b-a1f1bb7d15ed.mp4

**Comment by yacdaniel** [comment]
Closing as dup of #5632
