### ISSUE TITLE
[studio] Add cookieDomain property to accessTokenServiceInternal bean

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5624]
#### Is your feature request related to a problem? Please describe.
The domain property for access token management should be configurable

#### Describe the solution you'd like
Add **cookieDomain** property to accessTokenServiceInternal bean

Ideally, the default is null such that the bean's default behavior is in play and an overridden value is only used when absolutely necessary.

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

**Comment by sumerjabri** [comment]
CC @phuongnq

**Comment by russdanner** [comment]
Confirmed
