### ISSUE TITLE
[docker-images] Check folder ownership before doing a chown

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5625]
#### Is your feature request related to a problem? Please describe.
Right now, because Kubernetes volumes are most of the time set with root as the owner, the Docker entrypoint of most of our images is running `chown` on all folders that are used by Crafter before the actually main process takes over (see https://github.com/craftercms/docker-images/blob/develop/images/authoring/tomcat/docker-entrypoint.sh#L39).

This is making startup in volumes with lots of files take a long time.

#### Describe the solution you'd like
Check who's the owner of a folder before doing `chown`. If it's the `crafter` user, then `chown` shouldn't be run on it.

**Comment by phuongnq** [comment]
@avasquez614 I sent PRs for this. Note that this only checks the folder itself. If it is not `crafter:crafter`, then we recursively change the directory owner to `crafter:crafter` (including sub files/directories)

**Comment by avasquez614** [comment]
Verified in 3.1

**Comment by avasquez614** [comment]
Verified in 4.0
