### ISSUE TITLE
[studio] The Full path is considered in content_by_path API keyword parameter

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5627]
#### Crafter CMS Version
4.0.1-SNAPSHOT

#### Date of Build
6/5/2021

#### Describe the bug
The API get_content_by_path, when filtering by keyword, applies the filter to the whole path instead of the file name.

#### To Reproduce
1. Build a site with editorial
2. Under pages -> articles/2021 add folders (10, 11, 1, 2, 3, 4)
3. Call the API payload (by hand or via UI)
```
{siteId: "editorial", path: "/site/website/articles/2021", keyword: "1", limit: 10}
```
4. If you filter the sidebar for the value (aka keyword) 1 you will get a response that includes  10, 11, 1, 2, 3, and 4 because 1 is found in 2021

5. The user would expect the following response:
`10, 11, 1`

#### Logs
N/a

#### Screenshots
N/a

**Comment by sumerjabri** [comment]
@russdanner please verify. The commit is https://github.com/craftercms/studio/commit/d48ce2bddc28d3d3e2011fa4e0559fd9c6725380

**Comment by russdanner** [comment]
Confirmed
