### ISSUE TITLE
[studio-ui] Dragging and dropping a component with an ampersand fails

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5628]
#### Crafter CMS Version
Studio Version Number:
4.0.0E-29ecf4
Build Number:
29ecf48e02afeaa0ba09f301eacba54c4e4e48c9

#### Date of Build
5/12/2022, 4:59 PM

#### Describe the bug
When dragging and dropping a component that contains an ampersand in a default value, the operation fails.

#### To Reproduce
1. Create a page based on editorial
2. Navigate to Components/Features and modify the "Smile" Component
3. Modify the internal name of the component and name it "Smile &"
4. Navigate back to the homepage and drag/drop the new component from the right-hand sidebar into the "Erat Lacinia" section
5. Notice the insertion fails

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/172876692-ae581357-4492-40d0-82ed-ada18bf12f97.png)

**Comment by sumerjabri** [comment]
@russdanner should the policy engine handle this type of thing?

@yacdaniel FYI

**Comment by russdanner** [comment]
Confirmed
