### ISSUE TITLE
[studio] Rename folder socket event issues

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5629]
#### Crafter CMS Version
4.0.1-SNAPSHOT-6b1684

#### Date of Build
08/June/2022, 10:10 pm

#### Describe the bug
When renaming a folder, 
- Currently, the `CONTENT_EVENT` targetPath prop is the old name instead of the new one.
- The system emits a `CONTENT_EVENT`. It should **instead** emit a `MOVE_EVENT`.
  - If we manage to fix this part, the fix should apply to cut/paste too. Otherwise the inconsistency would make it changeling to handle the events properly on the UI.

#### To Reproduce
1. Go to sidebar > templates
2. Rename a folder
3. Look at the socket events produced

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by rart** [comment]
excellent, @phuongnq! I'll give it a test.

Did you manage to send only the move event or is it still the case that both content and move come through?

**Comment by phuongnq** [comment]
@rart It only sends `move` event.
