### ISSUE TITLE
[studio-ui] Reject dialog not showing

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5632]
#### Crafter CMS Version
4.0.1-SNAPSHOT-cbb508

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
Reject dialog doesn't show (tried on item menu and actions in dashboard actions).

#### To Reproduce
1. Go to an editorial based site
2. Do a publish with request approval
3. Try to reject the item
4. See that the dialog doesn't show, and the UI is left broken

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by yacdaniel** [comment]
As this is already prioritized, I'll close #5623 as dup

**Comment by jvega190** [comment]
@Euquimides can you please help me validating this ticket?

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now. Closing this ticket.
