### ISSUE TITLE
[studio] Paste of item with children getting flattened at the item table

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5635]
#### Crafter CMS Version
4.0.1-SNAPSHOT-cde410

#### Date of Build
14/June/2022, 1:02 pm

#### To Reproduce
1. Create an editorial site
2. Cut "Technology" and paste it into "Style"
3. Cut "Style" and paste it into "articles"
4. See that the navigator shows Style & Technology at the same level and Style as it had no children. At the file system level, things are correct.

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
Request payload:
![image](https://user-images.githubusercontent.com/3928341/173574052-51e7296d-6616-44cf-8309-dbac68b1db96.png)

Response payload:
![image](https://user-images.githubusercontent.com/3928341/173574103-ce2e8374-369a-4c47-bde5-f40e8fdf8dbb.png)

**Comment by sumerjabri** [comment]
CC @yacdaniel
