### ISSUE TITLE
[studio-ui] Repeating Group Description does not display on form

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5636]
#### Crafter CMS Version
Studio Version Number: 3.1.23E-70f937

#### Date of Build
Build Date/Time: 04-27-2022 17:07:12 -0400

#### Describe the bug
When adding a description to the Repeating Group Control, the description does not appear on the form control for the content type.

#### To Reproduce
1. Create a site based on editorial
2. Navigate to Site Config --> Content Types --> edit the Page - Article Content-Type
3. Scroll down and select the "Sections Repeating Group" 
4. Fill in a description on the right hand side under Form Basics
5. Save & Close
6. Navigate back to the Home Page
7. Under Home/Articles create new content based on the Page - Article content-type
8. Scroll down to the repeating group and see that the Description you have entered is not displayed

#### Logs
N/A

#### Screenshots
![image](https://user-images.githubusercontent.com/42217570/173587080-e181960f-ab99-4a09-b351-578c01598328.png)
![image](https://user-images.githubusercontent.com/42217570/173587181-5e8bec7b-9ce4-464d-a20f-0d95be5eab5d.png)

**Comment by russdanner** [comment]
Typically description goes at the bottom of fields. While this is a little awkward in a repeat group I suggest we keep it the same.

**Comment by AndyReiter** [comment]
Confirmed fixed in 4.0-SNAPSHOT.

**Comment by AndyReiter** [comment]
Confirmed fixed in 3.1-SNAPSHOT.
