### ISSUE TITLE
[studio] Remove the Go Delete API 1 since it's no longer used

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5640]
#### Crafter CMS Version
4.0.1-SNAPSHOT-3dc818

#### Date of Build
6/15/2022, 12:31 PM

#### Describe the bug
Even with a valid JWT token of admin, the following API is failed with 403 error:

https://docs.craftercms.org/en/4.0/developers/projects/studio/api/workflow/go-delete.html

```
curl --location --request POST 'http://localhost:8080/studio/api/1/services/api/1/workflow/go-delete.json?deletedep=true&site_id=ed' \
--header 'authorization: Bearer A_VALID_TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
    "items" : [
        "/site/website/articles/5-popular-diets-for-women/index.xml"
    ],
    "submissionComment": "my submission comment"
}'
```

Seem like this API require `delete_content` permission which is not available by default to admin. 
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/web/security/access/StudioWorkflowAPIAccessDecisionVoter.java#L59

#### To Reproduce
1. Create a site with Editorial BP
2. Login as admin and create a JWT token
3. Use JWT token and post above API
4. Notice that response code is 403 and item is not deleted

#### Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by rart** [comment]
> is this API being used by the UI?

The delete dialog uses `/studio/api/2/content/delete`.

**Comment by sumerjabri** [comment]
@jdrossl @jmendeza please deprecate the old API and remove it from the docs. This is a good task for @jmendeza to learn how to do that.

**Comment by phuongnq** [comment]
verified
