### ISSUE TITLE
[studio] Typo error in `remedialAction` field in DELETE `/users`, PATCH `users/enable` and `users/disable` API when sending a non-existent username

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5642]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When sending a non-existent username as query parameter in DELETE `/users` API, the `remedialAction` field returns `"Check if you're using the correct User ID"`, instead of `"Check if you're using the correct username"`.

Also, when sending a non-existent username as query parameter to PATCH `/users/disable`, `users/enable` APIs, the `remedialAction` field returns `"Check if you're using the correct User ID"`, instead of `"Check if you're using the correct username"`.

### Steps to reproduce

Use a REST API tool:

1. Set up a request for the APIs: DELETE `/users`, PATCH `users/disable` and `users/enable`.
2. Fill up the required parameters.
3. In the username query parameter and usernames body parameter, add a non-existent username

### Relevant log output

```shell
{
    "response": {
        "code": 6000,
        "message": "User not found",
        "remedialAction": "Check if you're using the correct User ID",
        "documentationUrl": ""
    }
}
```

### Screenshots and/or videos

N/A

**Comment by phuongnq** [comment]
Sent PR to change this to `Check if you're using the correct User ID or username`.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
