### ISSUE TITLE
Implement pre-creation-check for files & folders

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5645]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, when creating new files/folders, if the file already exists it still creates the `new` one and it shouldn't be allowed.

### Describe the solution you'd like

Implement a pre-creation check for files & folders to avoid creating already existing files.
For background see [here](https://github.com/craftercms/craftercms/issues/5593#issuecomment-1150192988).

**Comment by sumerjabri** [comment]
Currently, the backend will overwrite the file creating a new version. Checks can be done by the client.

We can reconsider adding a flag to indicate "overwrite" if present in API 2.

**Comment by sumerjabri** [comment]
Already fixed.
