### ISSUE TITLE
[studio] Add debug logging on each step of token validation

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5648]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A client is running into an issue where the password reset token expires immediately. Additional debug logging needs to be added to each step of the token validation to help debug the issue.

### Describe the solution you'd like

Add debug logging on each step of token validation

**Comment by AndyReiter** [comment]
Unable to confirm in the latest build of 4.0-SNAPSHOT.

**Comment by jmendeza** [comment]
Debug logging was added to the cases where the token is deemed invalid (token elements != 4, studio ID not matching, user not found, expired).
Let me know if more logging is needed.

**Comment by AndyReiter** [comment]
Confirmed. Will close this out now.
