### ISSUE TITLE
[studio-ui] `Git Branch` field allows white spaces and throws error when trying to create site from remote repository

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5649]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

The `Git Branch` field allows white spaces (which is not allowed by Git) when trying to create a site from remote. This will throw and error - `Remote repository not found` - since the white spaces seems to be taken into account by Studio for the branch name. 

### Steps to reproduce

Steps:

1. In `User Dashboard`, click on `Create a Project`
2. Click on `Remote Git Repository`
3. Fill up the form, in `Git Branch` field, add a git branch but add a white space before or after the git branch name. 
4. Click on `Review`
5. Click on `Create Project`
6. See issue

### Screenshots and/or videos

![Screenshot from 2022-06-20 17-28-49](https://user-images.githubusercontent.com/90878288/174828749-37810678-4826-46f5-8918-cebd332910cd.png)
![Screenshot from 2022-06-20 17-28-54](https://user-images.githubusercontent.com/90878288/174828779-b80d38f6-d74b-43bf-b9fa-abdbe62862ba.png)

**Comment by rart** [comment]
@jvega190 please check other fields for implementing similar validations.

This can help https://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name

**Comment by jvega190** [comment]
@Euquimides this is ready for validation in 3.1.x
