### ISSUE TITLE
[studio] Deleting the site doesn't delete the associated `audit_parameters` records from the database

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5656]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

When deleting a site, all records of the site are deleted except the DB records in `audi_parameters` that are associated with the `audit` records of the site.

### Steps to reproduce

1. Log in to the Studio database and run `SELECT count(1) from audit_parameters`
2. Create a site based on Editorial
3. Go to the database and run the select count statement again. The count should have changed.
4. Delete the Editorial site
5. Runs the select count again. The count hasn't changed after creation

**Comment by sumerjabri** [comment]
1. Update new databases being created to have the correct relationships
2. Add the correct relationships and make sure delete operations cascade moving forward
3. Delete any orphans in existing relationships

**Comment by jmendeza** [comment]
Added the FK constraint audit_parameters -> audit, cascade delete in both new dbs and upgrade scripts
Upgrade scripts will delete orphans before trying to add the FK.

**Comment by sumerjabri** [comment]
Must test:
- 3.1.23 -> 3.1.24
- 3.1.23 -> 4.0.1
- 3.1.24 -> 4.0.1

**Comment by yacdaniel** [comment]
@sumerjabri @jmendeza looks like upgrade pipeline/scripts are not updated to handle `3.1.24` to `4.0.1`
The db tables needed for v4 are missing, this is the startup log after the upgrade process, the upgrade went fine and didn't thrown errors. 
https://gist.github.com/yacdaniel/18adc023e7a06bd60a9bd26e09b06fa9
