### ISSUE TITLE
[studio-ui] Path Selection Input on Path Selection Dialog

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5657]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In search, the filters have a `Path` option. In the dialog, we had an input that worked in sync with the tree. This input was removed during recent refactor to reduce complexity.

To validate: 
1. Go to search
2. Use on the left sidebar of filter, use the path option all around

### Describe the solution you'd like

Add back the input

**Comment by Euquimides** [comment]
Hi! Updated and tested this feature. It has been successfully implemented.
