### ISSUE TITLE
[studio-ui] `content/item_unlock_by_path` API returning HTTP 409 when closing code editor after viewing and editing

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5659]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you `View`, then click on `Edit` and close the code editor via either `Close` or `Dismiss` buttons, will show a HTTP 409 response for the `content/item_unlock_by_path` API.  

### Steps to reproduce

Steps:

1. Create a new project. 
2. Open either a `Template` or `Script` via `View` available action.
3. Click on `Edit` in the code editor. 
4. Click on `Close` or dismiss the code editor.
5. See issue.

### Relevant log output

```shell
[ERROR] 2022-06-27T10:57:47,289 [http-nio-8080-exec-1] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/content/item_unlock_by_path failed with response: ApiResponse{code=7003, message='Content already unlocked', remedialAction='The item is already unlocked', documentationUrl=''} 
org.craftercms.studio.api.v2.exception.content.ContentAlreadyUnlockedException: null
```

### Screenshots and/or videos

![Screenshot from 2022-06-27 11-01-12](https://user-images.githubusercontent.com/90878288/175995923-559e1ef6-ad7d-4713-bcda-a1fca624f4f0.png)

**Comment by sumerjabri** [comment]
Is it possible the UI is unlocking twice?

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
