### ISSUE TITLE
[studio] POST `api/2/sites/{siteId}` API returning HTTP 200 with invalid parameter in body request

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5662]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `api/2/sites/{siteId}` API 2 (`POST http://localhost:8080/studio/api/2/sites/{siteId}`) is returning HTTP 200 with invalid parameter in body request. 

### Steps to reproduce

Steps:

Use a REST API tool (please refer to https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.26#/sites/updateSite for more information):

1. Set up a request for the API, `POST http://localhost:8080/studio/api/2/sites/{siteId}`.
2. In the body of the request add an invalid parameter:
```
{
  "name": "testUpdate",
  "invalidParam": "test",
  "description": "This is a API test"
}
```
3. Send the request.
4. See issue. 

### Relevant log output

```shell
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    }
}
```

**Comment by jmendeza** [comment]
Updated the json parsing config so it fails if an invalid parameter is sent in the body request

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
