### ISSUE TITLE
[studio] Problems when rendering content with current snippets; add CDATA to `User Interface Configuration`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5663]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The current snippets are using HTML symbols, which are causing problems when rendering content in sites the user builds. Adding CDATA to `User Interface Configuration` FreeMarker code snippets fixes the issue. 

### Steps to reproduce

Steps:

1. Go to any site. 
2. Edit a `Template`.
3. Insert a code snippet, you'll notice that its format is in HTML symbols, for example: 

`&lt;@crafter.h2 $field="title_t"&gt;${contentModel.title_t}&lt;/@crafter.h2&gt;` (this snippet was modified)

5. See the issue when rendering content. 

### Screenshots and/or videos

![Screenshot from 2022-06-29 11-04-30](https://user-images.githubusercontent.com/90878288/176513348-59f47f9c-615a-48cb-bd82-ed59540ee624.png)

**Comment by sumerjabri** [comment]
- Update builtin BPs
- Update existing sites using UM
- Update all external BPs (ask me)

**Comment by Euquimides** [comment]
Hi! After updating Studio the code snippets are working properly in both Firefox Browser and Google Chrome. So this issue is fixed. Closing this ticket.
