### ISSUE TITLE
[studio][studio-ui] Editing an item does not set its state to edited in the sidebar

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5664]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

when the user edits an item that is live it should immediately show as edited in the UI wherever status icons are shown upon saving (completing the edit.)

### Steps to reproduce

Steps:

1. Use editorial and publish everything
2. open the form and edit the home page  or edit a template
3. Note that the item shows live instead of the pencil in the sidebar until the user does a hard refresh or opens tap menu/right click for the item

**Comment by rart** [comment]
@phuongnq there's no socket event when updating templates or scripts

**Comment by russdanner** [comment]
Issue observed in today's build on edit template

Version Number:
4.0.1-SNAPSHOT-b3f030

Build Number:
b3f030fac48fe551a70fbdc9889611ec478d4ee4

Build Date:
7/8/2022, 10:41 AM

**Comment by phuongnq** [comment]
Attach screenshot shows that the socket event is triggered when there is an update on template
![2022-07-18_11-03](https://user-images.githubusercontent.com/2996543/179443706-362a4778-5e45-411a-ac14-7674d2ddff4a.png)
@russdanner Is the issue as mentioned in the ticket that the pencil does not appear upon an edit? I cannot reproduce this, please see my screen share: https://www.loom.com/share/d4024f3ba7164f4c9f1ae339a50dea78

**Comment by russdanner** [comment]
Confirmed
