### ISSUE TITLE
[studio] Asset filtering does not appear to operate based on filename

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Asset panel issues a keyword search that does not seem to relate to filenames.  The keyword search should include the filename and should operate as a contains type query

Example payload sent to search API from asset panel
````
{"keywords":"PL","offset":0,"limit":10,"filters":{"mime-type":["image/png","image/jpeg","image/gif","video/mp4","image/svg+xml"]}}
```

### Steps to reproduce

Steps:

1. Start with editorial
2. Open asset panel 
3. Search for gear
4. See the issue


### Relevant log output

_No response_

### Screenshots and/or videos

_No response_

**Comment by sumerjabri** [comment]
CC @avasquez614

**Comment by jmendeza** [comment]
@russdanner I've been unable to reproduce this issue. Please look at attached video demo.

[Kazam_screencast_00002.webm](https://user-images.githubusercontent.com/6042406/176779688-bb05927c-1978-41e6-9495-9c64d1c1fae1.webm)

**Comment by russdanner** [comment]
Both roy and I found in today's build, that

 if you search for 
**straw** you get the image of strawberries

 if you search for 
**berries** you get 0 results

**Comment by russdanner** [comment]
Confirmed
