### ISSUE TITLE
[studio-ui]  increase opacity on white circle around magnify glass on search/browse dialogs so that its visible on dark images

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5667]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Magnify glass in search/browse gets hidden on dark images

### Describe the solution you'd like

Increase opacity on disk under magnify glass icon

**Comment by rart** [comment]
@russdanner  Please clarify. Include screenshots and better description on where the issue is and how to reproduce.

**Comment by russdanner** [comment]
Solved by removing magnify glass and making image click pop the dialog.

Confirmed.
