### ISSUE TITLE
[studio] Update Policy Engine configuration to replace parenthesis with dashes

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5676]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://github.com/craftercms/craftercms/issues/5675 

### Describe the solution you'd like

The Policy Engine should switch any use of parenthesis to dashes in the file name for any assets added to a project.

**Comment by Euquimides** [comment]
Hi! Verified and validated this feature in Crafter v4. It is working correctly, thank you! Closing this ticket.
