### ISSUE TITLE
[engine] Deployment events watcher triggers multiple cache clears if there's already a cache clear/warmup in progress

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5677]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

When you have Engine configured in serverless mode, and you deploy 2 or more files one after another, the deployment watcher job that triggers cache clears is going to trigger a lot of cache clears if one is already in progress.

### Steps to reproduce

Steps:

1.Setup Engine in serverless mode
2. Configure that deployment watcher job in Delivery to run every 10 secs
3. Make sure you have in Delivery a very big site that takes several minutes to warm up.
4. Publish a file, then wait 10 secs to publish another, then wait another 10 secs to publish another.

The first file will trigger a deployment that the deployment watcher is going to detect and is going to issue a cache clear/warmup. Then the other 2 are going to trigger a lot more cache warmups because the deployment watcher doesn't really recognize that these 2 deployments are not new every 10 secs and that they haven't been processed because a long cache warmup is still in progress.

**Comment by avasquez614** [comment]
Verified in 3.1.x

**Comment by sumerjabri** [comment]
@jmendeza please port to v4
