### ISSUE TITLE
[studio-ui] Asset panel should show full path in hover or as part of card

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5678]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Authors may have the same image in different places. Picking the right image from the appropriate location is important. They need the path to ensure that they re picking the right image.

### Describe the solution you'd like

Show the full path of the asset on the card.

**Comment by sumerjabri** [comment]
@russdanner please add a screenshot

**Comment by russdanner** [comment]
Show path on asset card here:
<img width="1417" alt="Screen Shot 2022-07-14 at 3 47 10 PM" src="https://user-images.githubusercontent.com/169432/179271498-3b8d2c57-717f-4e27-8be8-f0ae42e81f8d.png">

Similar to how we show the path in a search result card here:
<img width="1374" alt="Screen Shot 2022-07-14 at 3 47 00 PM" src="https://user-images.githubusercontent.com/169432/179271743-63ccb34e-b88d-4bf7-8ff8-468fd2ceca6b.png">

**Comment by russdanner** [comment]
Also note that the value on the card is a tool tip so you can hover over it for the complete path.

**Comment by russdanner** [comment]
Confirmed
