### ISSUE TITLE
LDAP authentication broken after upgrading to version 4.0.0

### ISSUE THREAD

**Issue by rakuten-akadric** [craftercms/craftercms#5680]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

After upgrading our project to use the latest v4.0.0 version, our LDAP integration is no longer working. Also after going through the source code, I noticed it was removed. Has this been moved to a plugin that we need to also install? Or has it been completely removed?

### Steps to reproduce

Steps:

1. Install version 4.0.0
2. Configure LDAP as per documentation
3. Try to login using LDAP account
4. Password error occurs and checking logs only shows DB provider being triggered

**Comment by sumerjabri** [comment]
@rakuten-akadric starting v4, LDAP is an EE feature. Please see the article https://docs.craftercms.org/en/4.0/system-administrators/activities/security/configure-ldap.html
