### ISSUE TITLE
[studio] Creating content and Saving it with the "Save" option results in the content being stuck as locked

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5684]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating a new piece of content in Studio, saving the content via the "Save" option and not the "Save&Close" option results in the content being locked. After attempting to unlock the content, the lock on the file does not get removed. 

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Create a new piece of content
3. Fill out all required information
4. In the bottom right, select the dropdown next to "Save&Close" and select "Save" instead
5. Once you "Save" the content, close the form by clicking anywhere (or minimizing the form in the top right of the form)
6. Notice the content you just created is locked in the sidebar
7. Right click and unlock the content. 
8. Notice that the locked content does not get unlocked.

### Relevant log output

```shell
https://gist.github.com/AndyReiter/2c91630a106e88f0ad6501a5e9ec9db1
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/179552865-205abf95-1fa3-46cb-87d4-be3e8290de34.png)

**Comment by sumerjabri** [comment]
CC @rart

**Comment by jvega190** [comment]
@sumerjabri @rart after saving the form the `unlock` service is being called, but an error happens 
https://gist.github.com/jvega190/5eb7c7b1e19548ccfd89f2bf7f98e08e, the same error shows if you manually do an unlock to the item.
On the other side, the state of the newly created item is `11`, which matches the LOCKED mask.

**Comment by rart** [comment]
Indeed, looks like this is backend. 

When using "Save", the main difference is that the `write-content.json` api is called with `unlock=false`. When doing this with an existing content, it works fine, but in these cases (i.e. creating a new item) something stays stuck in the back.

**Comment by Euquimides** [comment]
Hi @rart and @jmendeza ! While validating this ticket I noticed that creating a new `Template` or `Controller` and immediately clicking outside the Code Editor without saving, will keep the newly created item as locked. Should this be allowed? The `write-content.json` API 1 will not update in this case.

https://user-images.githubusercontent.com/90878288/179860582-6dd83346-3480-431b-baa7-a25f55234439.mp4

**Comment by sumerjabri** [comment]
@Euquimides please close this ticket if this particular bug is fixed. Please file a new ticket for the locking issue to track that separately.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Since this particular bug is fixed, I'm closing the ticket. Please refer to ticket  #5691 since they might be related.
