### ISSUE TITLE
[studio-ui] Toolbar does not refresh when switching between pages

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5686]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

When switching between pages in the left-hand sidebar, the toolbar at the top of the page does not refresh.

### Steps to reproduce

Steps:

1. Create a new site
2. Create a new role that has permissions to write content in one folder, but only read content in other folders.
3. Restart studio.
4. Create a new user that has the new permission assigned to their account
5. Navigate to the folder with read-only permissions and left click a piece of content to preview it.
6. Now switch pages to a piece of content in the folder that you have write permissions for
7. See the toolbar does not refresh and you can not Edit nor In-Context Edit.
8. Refresh the page and see that you are now able to edit, and In-Context Edit

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/42217570/179567891-ecbde70a-85bb-400c-b32c-e1cdc493f5e4.mp4

**Comment by russdanner** [comment]
Work around: Refresh the browser when moving from read-only page to read-write page.

**Comment by AndyReiter** [comment]
Confirmed fix in 3.1.25-SNAPSHOT.
