### ISSUE TITLE
[studio-ui] XB Existing Videos DnD not working

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5687]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When dragging existing videos using XB available dropzones don't highlight due to a filter being applied to videos only.

### Steps to reproduce

Steps:

1. Add/register a video using crafter macros (for it to be registered in XB)
2. Upload a video and try to drag it to a video dropzone
3. See the issue

See filtering done in `https://github.com/craftercms/studio-ui/blob/develop/ui/guest/src/store/reducers/root.ts#L611`
Other filters done in those actions need to be verified.

**Comment by sumerjabri** [comment]
CC @rart

**Comment by russdanner** [comment]
Confirmed
