### ISSUE TITLE
[docs] "version_tag" is not rendering correctly in the docs

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5690]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`version_tag` is not rendering correctly in the docs

```
.. version_tag::
  :label: Since
  :version: 4.0.0
```

### Steps to reproduce

Steps:
Browse the docs for items with the `version_tag`.
For example:[https://docs.craftercms.org/en/4.0/developers/cook-books/how-tos/migrate-site-to-elasticsearch.html#migrating-a-site-from-[…]us-elasticsearch-client](https://docs.craftercms.org/en/4.0/developers/cook-books/how-tos/migrate-site-to-elasticsearch.html#migrating-a-site-from-the-previous-elasticsearch-client)

### Screenshots and/or videos

<img width="1282" alt="Screen Shot 2022-07-20 at 8 50 04 AM" src="https://user-images.githubusercontent.com/25483966/179997247-40c66b6f-dcbf-4a5b-a69b-825abf6cd421.png">

<img width="1282" alt="Screen Shot 2022-07-20 at 6 57 32 AM" src="https://user-images.githubusercontent.com/25483966/179997279-4e2c8667-8d8a-4689-a5ed-3465ba8f4382.png">

**Comment by jvega190** [comment]
@alhambrav this can be tested after docs are published

**Comment by sumerjabri** [comment]
@alhambrav docs should be live now, have a look

**Comment by alhambrav** [comment]
Verified.
