### ISSUE TITLE
[studio-ui] group checkboxes control breaks when multiple data sources are selected

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5695]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

group checkboxes control does not load in form when multiple data sources are selected

### Steps to reproduce

Steps:

1. Add a group check boxes control to any content type
2. Add multiple static key-value pair data sources to content type
3. Assign all  static key-value pair data sources to the grouped checkboxes control
4. Open the form and see that no control shows

### Screenshots and/or videos

<img width="1624" alt="Screen Shot 2022-07-21 at 11 52 30 AM" src="https://user-images.githubusercontent.com/169432/180259347-21c4146d-4312-4973-8bbc-c8d0cca9df42.png">

**Comment by russdanner** [comment]
I have looked at this a bit with @rart and we have concerns about allowing multiple data sources. At the end of the day the data is some kind of KVP but the issue is that the control has no way of dealing with sorting and duplicates.

Do we fix this "issue" with the control or do we disallow configuring multiple data sources?

**Comment by sumerjabri** [comment]
Let's disable this. Only a single data source can back these controls. If there is a need for more than one, an aggregating data source can be implemented to support that use case where issues like this, sorting, duplicates, value types, and similar can be addressed.

**Comment by rart** [comment]
@sumerjabri any thoughts on people who might have multiple DS' already?

**Comment by sumerjabri** [comment]
@rart it doesn't work, so it should be fine to disable.

**Comment by russdanner** [comment]
Confirmed, property sheet now uses radio buttons for the selection of datasource.
