### ISSUE TITLE
[studio-ui] Add tool tip or similar visual cue with path to item in item selector form control

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5696]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, it is not possible for an author to know WHERE a shared component/content item is stored when looking at an item selector control. Today they must open/edit the item to see its location. 

### Describe the solution you'd like

Add hover that shows the "path" of the item(s).

**Comment by sumerjabri** [comment]
CC @rart

**Comment by sumerjabri** [comment]
@rart it doesn't have to be a tooltip, so other more tablet-friendly options are welcome. Please review before @jvega190 builds it.

**Comment by rart** [comment]
@jvega190 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/3928341/180298100-a6aea2e6-7f98-4cce-8bb8-8d67a21553bd.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/3928341/180298422-bae52cee-9ce6-4dd8-b753-e80ef5ea17e5.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3928341/180298479-c7dc7b1d-0a1f-4553-b4da-732b4638408a.png">

**Comment by russdanner** [comment]
confirmed
