### ISSUE TITLE
[studio-ui] Obliterate legacy preview & dashboard 🙂 

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5697]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

- We made 3.x sites be able to run on UI 4
- Legacy dashboard has a 4 equivalent

### Describe the solution you'd like

Remove legacy preview and legacy dashboard

- [x] Remove FTLs
- [x] Remove specific JS files
- [x] Test legacy sites dnd and make sure UI4 adapter can handle that case too
- Remove the `useLegacyPreview` preference
  - [x] UI calls and handling of the option
  - [ ] UM to remove the setting
  - [ ] Update blueprints
- [ ] Update any/all related docs

**Comment by sumerjabri** [comment]
@rart hold any PR or keep in draft until 4.0.1 is out.

**Comment by jvega190** [comment]
@rart the config `usePreview3` (the one called `useLegacyPreview` in ui) was not in the blueprints, so no need to update.
