### ISSUE TITLE
[studio-ui] Refused to apply style error in console when using tinymce v2

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5702]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

We are getting the following error in Console when trying to edit or view a pape that has a Tiny MCE v2.

Refused to apply style from 'http://localhost:8080/studio/static-assets/modules/editors/tinymce/v2/tiny_mce/plugins/inlinepopups/skins/cstudio-rte/window.css?version=48fa93ebd08ecd70eec285dfcda197fa3fde2f73' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.trying

### Steps to reproduce

Steps:

1. Create a site within Crafter (let's say using a Website editorial blueprint)
2. Add a Tiny MCE v2 to the article form definition
3. Open browser inspect > Console tool
4. Right-click and edit or view any article page.
5. When the editor opens, you will see the error in the console 

### Screenshots and/or videos

![2022-07-25_15-59](https://user-images.githubusercontent.com/2996543/180739754-d5f51b6c-bdf0-4306-a188-ac4ad102ff39.png)
![2022-07-25_16-03](https://user-images.githubusercontent.com/2996543/180740141-3125cd05-3762-4974-9564-5b57f07ca8d3.png)
![2022-07-25_16-03_1](https://user-images.githubusercontent.com/2996543/180740156-6f5383d0-84fc-49ad-9cc4-4e4a4cdbd302.png)

**Comment by russdanner** [comment]
@phuongnq Let's try and identify a workaround if possible.

**Comment by phuongnq** [comment]
@russdanner Since we have `cs_inlinepopups` plugin (customized by CrafterCMS), there should be no impact caused by this. We can add an empty `window.css` file to `inlinepopups` plugin to fix the console error. See the PR.

**Comment by russdanner** [comment]
Confirmed
