### ISSUE TITLE
[studio-ui] Error message when creating a new content inside a 'quick create' form.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5705]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

There's an error message showing when trying to create new content inside a content being created using quick create option.

### Steps to reproduce

Steps:

1. Go to a site based on videocenter
2. Click on 'quick create menu', and create a new Stream
3. Scroll down to 'Origin' and click on `Add` -> `Create New - Origins`
4. See the issue

### Relevant log output

```shell
forms-engine.js:1096 TypeError: CStudioAuthoring.InContextEdit.getIceCallback(...)?.renderComplete is not a function
    at forms-engine.js:2052:68
    at Object._loadDatasources (forms-engine.js:2075:11)
    at Object._renderFormWithContent (forms-engine.js:1253:14)
    at forms-engine.js:1093:21
```

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.1-SNAPSHOT`
