### ISSUE TITLE
[studio] Upgrade from 3.1.24 to 4.0.1 removes the custom menu items from sidebar. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5706]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Studio upgrade is not taking into account the custom Sidebar entries while upgrading from 3.1.24 to 4.0.1
Sites from blueprints like video center, blog, store are affected.

### Steps to reproduce

Steps:

1. In 3.1.24 create a site from videocenter, store and blog blueprints.
2. Upgrade to latest 4.0.1
3. See missing items in sidebar menu

### Screenshots and/or videos

Video center 3.1.24
![image](https://user-images.githubusercontent.com/6722074/181300346-fe0543fd-6fe6-4dd5-9256-76ebd88849e6.png)
Video center 4.0.1
![image](https://user-images.githubusercontent.com/6722074/181300400-89736b5a-1fd6-49af-ba52-d121677fedae.png)

Blog 3.1.24
![image](https://user-images.githubusercontent.com/6722074/181300599-d915a91c-cbfc-4f6e-bbf8-5e96c8604997.png)
Blog 4.0.1
![image](https://user-images.githubusercontent.com/6722074/181300667-5eacec07-a85c-4086-8bbf-13492c5e14d7.png)

**Comment by sumerjabri** [comment]
we're unable to automatically map the old sidebar config to the new ui.xml at this time.
