### ISSUE TITLE
[docker-compose] Backup script having problems recognizing paths with spaces in Windows OS via Docker

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5707]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using a path that contains a space in it, lets say C:\Users\Juan Carlos\Documents\crafter-docker-tests , the backup script will have problems recognizing the path: 
```
C:\Users\Juan Carlos\Documents\docker-compose\scripts>backup.bat authoring C:\Users\Juan Carlos\Documents\crafter-docker-tests
Removing network authoring_default
Creating network "authoring_default" with the default driver
Creating authoring_tomcat_run ... error

ERROR: for authoring_tomcat_run  Cannot create container for service tomcat: mkdir C:\Users\Juan: Access denied.

ERROR: for tomcat  Cannot create container for service tomcat: mkdir C:\Users\Juan: Access denied.
```

Trying various combinations to bypass this issue either closing the path in double quotes or enclosing the section with "Juan Carlos" or adding backwards slash before the space, the result will be the same:
```
C:\Users\Juan Carlos\Documents\docker-compose\scripts>backup.bat authoring "C:\Users\Juan Carlos\Documents\crafter-docker-tests"
Carlos\Documents\crafter-docker-tests""=="" was not expected at this time
```
In case of using only a single quote: 
```
C:\Users\Juan Carlos\Documents\docker-compose\scripts>backup.bat authoring 'C:\Users\Juan\Carlos\Documents\crafter-docker-tests'
Removing network authoring_default
Creating network "authoring_default" with the default driver
Creating authoring_tomcat_run ... error

ERROR: for authoring_tomcat_run  Cannot create container for service tomcat: invalid mode: /opt/crafter/backups

ERROR: for tomcat  Cannot create container for service tomcat: invalid mode: /opt/crafter/backups
ERROR: Encountered errors while bringing up the project.
```
Only in the case that the designated path for the backup doesn´t contain spaces in its path, it will work alright. 

### Steps to reproduce

Steps:

1. On Windows OS, use docker-compose. 
2. Run the backup script and select a path that contains a space in it. 
3. Execute the script. 
4. See the issue

### Relevant log output

```shell
C:\Users\Juan Carlos\Documents\docker-compose\scripts>backup.bat authoring C:\Users\Juan Carlos\Documents\crafter-docker-tests
Removing network authoring_default
Creating network "authoring_default" with the default driver
Creating authoring_tomcat_run ... error

ERROR: for authoring_tomcat_run  Cannot create container for service tomcat: mkdir C:\Users\Juan: Access denied.

ERROR: for tomcat  Cannot create container for service tomcat: mkdir C:\Users\Juan: Access denied.
```

**Comment by Euquimides** [comment]
Hi @sumerjabri ! I updated and tested the updated scripts on a Crafter v4.0.1 image, still having the same issue on Windows.

**Comment by sumerjabri** [comment]
@Euquimides I updated the scripts again, but still have no means of testing it. Please try again and if it fails, please ping @avasquez614 to screen share.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The backup and restore scripts are working fine now in Windows. Only note: you must enclose in `" "` any path that contains spaces in it. The README.md file has been updated to include this detail. Closing the ticket.
