### ISSUE TITLE
[docker-images] docker-entrypoint.sh should create setup known_hosts with the BitBucket, GitLab and Github.com host keys

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5708]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In order to do Git clones and pulls against `bitbucket.com`, `gitlab.com` and `github.com`, their hosts keys should be in `/opt/crafter/data/ssh/known_hosts`.

### Describe the solution you'd like

In the `docker-entrypoin.sh` script for the Tomcat and the Deployer images, please run `ssh-keyscan {server url} >> /opt/crafter/data/ssh/known_hosts` for each one of `bitbucket.com`, `gitlab.com` and `github.com`

**Comment by phuongnq** [comment]
@avasquez614 PR is ready for review. I added for tomcat and deployer

**Comment by avasquez614** [comment]
Verified
