### ISSUE TITLE
Trying to login to a different session through tab in browser, redirects to events endpoint

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5709]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When logout from an active session in the browser using a different tab, and then login to another session, Studio will redirect the user to the endpoint: `http://localhost:8080/studio/events`. Seems there is a failure with the Websocket handshake. 

### Steps to reproduce

Steps:

1. Create to different users. 
2. Login to Crafter authoring using `user A`. 
3. Open a new tab in the browser.
4. Logout from Crafter authoring in that new browser tab. 
5. Login to Crafter authoring in that same tab using `user B`.
6. See issue

### Relevant log output

```shell
[INFO] 2022-08-01T16:07:01,630 [http-nio-8080-exec-7] [listener.AuditLogoutListener] | User admin logged out from IP: 127.0.0.1 
[INFO] 2022-08-01T16:07:10,918 [http-nio-8080-exec-10] [listener.AuditLoginListener] | User test logged in from IP: 127.0.0.1 
[ERROR] 2022-08-01T16:07:18,192 [http-nio-8080-exec-6] [support.DefaultHandshakeHandler] | "Handshake failed due to invalid Upgrade header: null"
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/182254727-a100d41d-9ae9-4c8a-984f-6374a13d6d08.mp4

**Comment by Euquimides** [comment]
This issue is reproducible, but only using Firefox browser WITHOUT incognito mode. To reproduce:

1. Create to different users.
2. Login to Crafter authoring using user A.
3. Open another tab by copying the current logged in tab. 
4. Logout from Crafter authoring in that new browser tab.
5. Login to Crafter authoring in that same tab using user B.
6. See issue

**Comment by jvega190** [comment]
Assigning to @jmendeza for him to take a look since it seems like it may be a backend issue

**Comment by Euquimides** [comment]
**IMPORTANT NOTE:** To replicate the issue, you must be logged in as user A in a project, while logging in another tab as user B.
