### ISSUE TITLE
[studio-ui] Image preview background color blends in with content on some transparent images

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5710]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Previewing images that are similar/match the background color for preview perfectly are displayed as invisible. 

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/182440570-2a7d4482-dc87-4004-8fe9-ae6f1fdaa195.png)
![image](https://user-images.githubusercontent.com/42217570/182440627-7cbd75b6-04d8-4952-ba1a-0136722a754e.png)
![Rectangle 3733](https://user-images.githubusercontent.com/42217570/182440663-b705f061-ff20-4208-84cc-cebd3c557a47.png)

**Comment by jvega190** [comment]
@AndyReiter we added a new icon/functionality (at the top right section of the dialog) to switch between background modes so you can switch and see what fits to properly see the image

**Comment by AndyReiter** [comment]
Confirmed fixed in 4.0.2-SNAPSHOT. Closing now.
