### ISSUE TITLE
[plugin] Outdated "Social Media Widget" plugin

### ISSUE THREAD

**Issue by lolo782374** [craftercms/craftercms#5715]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Social Media Widget Plugin is outdated in Plugin Management. The latest published Social Media Widget Plugin in the CrafterCMS marketplace has an out-of-date GitHub link and company name. The version to have the correct GitHub link and company name is [v2022031401](https://github.com/craftercms/social-media-plugin/blob/v2022031401/craftercms-plugin.yaml).

### Steps to reproduce

Steps:

1. Go to Plugin Management/CrafterCMS marketplace
2. Click on Social Media Widget
3. Read metadata/description

### Relevant log output

```shell
Correct  v2022031401
  description: A plugin to add social media links to a site
  documentation: "https://raw.githubusercontent.com/craftercms/social-media-plugin/master/readme.md"
  website:
    name: Social Media Widget
    url: https://github.com/craftercms/social-media-plugin
  media:
    screenshots:
      - title: Social Media Widget
        description: Social Media Widget Example
        url: https://raw.githubusercontent.com/craftercms/social-media-plugin/master/.crafter/cover.png
  developer:
    company:
      name: CrafterCMS
      email: info@craftercms.com
      url: https://craftercms.com
Incorrect latest v2022080203
  website:
    name: Social Media Widget
    url: https://github.com/craftercms/social-media-widget
  media:
    screenshots:
      - title: Social Media Widget
        description: Social Media Widget Example
        url: https://raw.githubusercontent.com/craftercms/social-media-plugin/master/.crafter/cover.png
  developer:
    company:
      name: Crafter Software
      email: info@craftersoftware.com
      url: https://craftersoftware.com
```

### Screenshots and/or videos

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/110685450/183120571-c0d1a0dc-5962-4242-bf14-b6e20bf4d083.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/110685450/183120853-f73d9e63-3686-4b92-b60a-b2c3fe14e1ea.png">

**Comment by sumerjabri** [comment]
CC @yacdaniel

**Comment by lolo782374** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/110685450/183697308-8ec6d830-a64a-4286-881a-e735be163f7d.png">

Verified fix in Studio.
