### ISSUE TITLE
[studio] POST `/sites/create_site_from_marketplace` API 2 returning HTTP 200 instead of 400 on invalid request and HTTP 200 instead of 201 on succesful creation of site

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5716]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

POST `/sites/create_site_from_marketplace` API 2 is returning HTTP 200 instead of 400 when sending a request with and invalid parameter. Also, on successful calls of the API, the response will be HTTP 200 instead of HTTP 201 corresponding to a newly created item. 

### Steps to reproduce

Steps:

Use a REST API tool (refer to https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.26#/sites/createSite for more information)

1. Set up a request for the API, POST http://localhost:8080/studio/api/2/sites/create_site_from_marketplace
2. In the request body add an invalid parameter, for example:
```
{
    "blueprintVersion": {
        "patch": 25,
        "major": 2,
        "minor": 0
    },
    "name": "wordify",
    "siteId": "wordify-site-test",
    "blueprintId": "org.craftercms.blueprint.wordify",
    "invalidPropertyBody": "invalid
}
```
4. Send the request
5. See the issue

### Relevant log output

```shell
{
    "response": {
        "code": 1,
        "message": "Created",
        "remedialAction": "",
        "documentationUrl": ""
    }
}
```

**Comment by sumerjabri** [comment]
CC @rart FYI on the 200 instead of 201 return code
