### ISSUE TITLE
[studio] Uploading a blob-store backed asset doesn't reflect in git history

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5719]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

For blob-store mapped files, when uploading a static asset with the same name as an existing asset, the write operation is not reflected in the Git History.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Set up your site to use blob-store for static-assets
3. Upload a test file
4. Upload a different file with the same exact name and extension
5. See that the new item overwrites the old one, but nothing shows in the Git History

### Relevant log output

```shell
N/A
```

**Comment by sumerjabri** [comment]
@jmendeza let's discuss. At a high level, we can add a date/time to the shadow files to make git understand that it has changed.

**Comment by jmendeza** [comment]
@AndyReiter we have been unable to reproduce this issue. The blob file gets modified (hash is updated) and user is able to publish new version of the asset.
![image](https://user-images.githubusercontent.com/6042406/184252348-83a01bfa-56f2-42fd-aaa3-19dd673fdadb.png)

**Comment by sumerjabri** [comment]
CC @russdanner this can't be reproduced in the latest version of CrafterCMS in 3.1 or 4.0.

@AndyReiter what version was this observed in?

**Comment by AndyReiter** [comment]
This was not reproducible in the latest build of studio by me or the customer who brought the issue to light. This can be closed out.
