### ISSUE TITLE
[studio-ui] Persona properties don't appear unless there's more than one

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#572]
Using the Editorial blueprint, if you open the Preview Tools and go to Targeting, the Anonymous, Guy and Gal personas should show a Segment property, but they aren't. If you then go to Admin Console > Configuration > Personas Configuration and add a property to each persona (e.g. Name), both Segment and Name properties will now appear in the Persona's picker under Preview Tools.

**Comment by vestrada** [comment]
Master PR: https://github.com/craftercms/studio2-ui/pull/299
