### ISSUE TITLE
[studio-ui] The dialogue for renaming an image in studio does not allow for file extensions

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5721]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When renaming an image in studio the dialogue prompts you to rename a "folder" instead of an "image". The prompt also does not allow you to change the image name without the extension being removed.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Scroll down to the Static-Assets/Images folder
3. Right-click and rename an image.
4. Notice that the dialogue prompts you for a folder rename
5. Also Notice that when you try to rename the file, but keep the .jpg, the dialogue removes it and does not allow for it to be re-added.

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/183655018-8b0d8b3d-9ff9-41a5-b4ed-2c9bb0b2ab5c.png)

**Comment by russdanner** [comment]
This is related to  this feature request which is still in the validation stage.
#5630
