### ISSUE TITLE
[studio] Duplicated pages are not referencing duplicated images

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5722]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

When content is duplicated, the images uploaded into an RTE field are duplicated (if they are created in one of the paths set on property studio.configuration.dependency.itemSpecificPatterns) but the duplicated image is not assigned to the duplicated content.

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Navigate to the Project Tools and edit the Article Content type
3. Create a datasource "Image Uploaded from Desktop" and set the repository path to "/static-assets/item/{objectId}"
4. Create a datasource "Image from Repository" and set the repository path to "/static-assets/item"
5. Assign the datasources as "Image Managers" to the RTE field
6. Save the Content Type Definition
7. Create a new article using this content type
8. Fill out all required fields and upload an image into the RTE field and save the content
9. Check and ensure the image was created in /static-assets/item/{objectId}
10. Duplicate the page
11. See that the duplicated image was also created under /static-assets/item/
12. Compare both pages, check they have included the same image, and see that the duplicated image was not assigned to the duplicated content

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

N/A

**Comment by sumerjabri** [comment]
@rart let's see if this is a UI issue while creating the duplicate XML or backend, in which case we'll relabel and push to @jmendeza

**Comment by jvega190** [comment]
@sumerjabri @rart @jmendeza what we do in the UI is calling the duplicate API with the path that needs to be duplicate. No XML handling for this action in UI.

**Comment by AndyReiter** [comment]
Confirmed fixed in 4.0.2-SNAPSHOT. Closing now.
