### ISSUE TITLE
[studio-ui] Remove/consolidate marketplace tabs on create site dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5724]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Today users have to between "collections" of blueprints by selecting a tab in the create site dialog. The options are "Private blueprints" and "public marketplace."  This makes it difficult for first-time users to find all available options. We want to simplify this experience.

### Describe the solution you'd like

Current experience:
<img width="1652" alt="Screen Shot 2022-08-11 at 10 32 58 AM" src="https://user-images.githubusercontent.com/169432/184158704-80e9a532-1bcf-4811-a09e-acd4dbb03266.png">

What we would like instead is:

Show the private blueprints and marketplace blueprints at the same time.

- [x] Create from Git should always be first
- [x] Show private (out of the box) blueprints second
- [ ] Consider making "empty"/hello world the only "private blueprint"
- [x] As long as there is connectivity, connect to the marketplace and show available blueprints, listed in the o
<img width="1652" alt="Screen Shot 2022-08-11 at 10 32 58 AM" src="https://user-images.githubusercontent.com/169432/184161503-d3c0818d-26ab-42fa-85e4-0fe34cf4746b.png">
rder returned.

**Comment by sumerjabri** [comment]
List the built-ins first, then the MP. Search/filtering can work against MP only if that's the easiest path.
If MP is unreachable, only show the built-ins.

**Comment by rart** [comment]
@jvega190 

![CreateProjectDialog--MarketplaceUnavailable](https://user-images.githubusercontent.com/3928341/187862619-0ca6c178-c561-47ea-8f1b-290d78cfb632.png)

![CreateProjectDialog](https://user-images.githubusercontent.com/3928341/187862625-99109a41-6e3c-483a-b224-69bbc0ecd826.png)

Use `@mui/icons-material/SignalWifiBadRounded` icon

**Comment by russdanner** [comment]
Confirmed
