### ISSUE TITLE
[docs] Update DevContentOps doc with improved detail on workflow

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5725]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Improve documentation with more specifics on best practices for DevConentOps

### Describe the solution you'd like

Update devContentOps doc with improved detail on workflow
https://docs.craftercms.org/en/4.0/developers/developer-workflow/implementation-prod-repo-sync.html
https://docs.craftercms.org/en/4.0/developers/developer-workflow/implementation-devops-workflow.html

**Comment by sumerjabri** [comment]
@alhambrav please base the new article on the document I shared with you.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/devcontentops.html
https://docs.craftercms.org/en/4.0/new-ia/by-role/developer/devcontentops/index.html

**Comment by russdanner** [comment]
confirmed
