### ISSUE TITLE
[studio-ui] Device simulator doesn't fit properly in tablet mode

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5727]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using the device simulator in tablet mode, it doesn't fit properly and parts of the preview are not viewable

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Click on 'Device Simulator' - 'Tablet'
3. Scroll up to the top of the preview window
4. See that the top section of the preview window cannot be scrolled.

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/18267471/184182606-35a07ae8-67d2-450d-a5ce-ecd14e908948.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
