### ISSUE TITLE
[studio-ui] Renaming items or editing Page URL via UI, returns HTTP 404 on `/content/item_by_path` call

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5733]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you rename an item or edit the Page URL of an article for example, via UI, the `/content/item_by_path` API 2 is called but the request is made to the old path (sourcePath) instead of the new path (targetPath), which returns HTTP 404 since the path has been changed.

In the case of editing the Page URL, when saving and closing the form, the UI will get stuck on that form until refresh of the browser. 

### Steps to reproduce

Steps:

1. Create a new site
2. Rename a folder, template or script or the Page URL of a content. 
4. See the issue

### Relevant log output

```shell
[ERROR] 2022-08-17T16:15:09,993 [http-nio-8080-exec-4] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/content/item_by_path?path=%2Ftemplates%2Fweb%2Fpages%2Ftest.ftl&preferContent=true&siteId=test2' failed with response 'ApiResponse{code=7000, message='Content not found', remedialAction='Check that path '/templates/web/pages/test.ftl' is correct and it exists in site 'test2'', documentationUrl=''}' 
org.craftercms.studio.api.v1.exception.ContentNotFoundException: Content not found at path /templates/web/pages/test.ftl site test2
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/185254575-41a8f54c-0067-4b60-8bfa-b4a8c1482f40.mp4

**Comment by jmendeza** [comment]
@sumerjabri I reviewed this issue with @jvega190 and it looks like a UI bug.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The fix is validated. Thank you! Closing this ticket.
