### ISSUE TITLE
FreeMarker template error in marketplace blueprint videoCenter

### ISSUE THREAD

**Issue by rm--** [craftercms/craftercms#5734]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The marketplace of the `org.craftercms.blueprint.videoCenter` plugin shows some Java stacktraces and Freemarker errors.
URL of the plugin: https://marketplace.craftercms.org/plugins/org.craftercms.blueprint.videoCenter

### Steps to reproduce

Steps:

1. Go to 'https://marketplace.craftercms.org/plugins/org.craftercms.blueprint.videoCenter'
2. See the issue

### Relevant log output

```shell
$FreeMarker template error:
The following has evaluated to null or missing:
==> blueprint  [in template "templates/web/plugin_details.ftl" at line 47, column 16]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${(blueprint.developer??)?then(bluepr...  [in template "templates/web/plugin_details.ftl" at line 47, column 13]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.(UnexpectedTypeException.java:48)
	at freemarker.core.NonHashException.(NonHashException.java:49)
	at freemarker.core.Dot._eval(Dot.java:48)
```

### Screenshots and/or videos

<img width="1910" alt="1" src="https://user-images.githubusercontent.com/3188382/185571246-917d31ee-440c-4272-88aa-fb42efb4d266.png">
<img width="1918" alt="2" src="https://user-images.githubusercontent.com/3188382/185571260-2b333cfd-45dd-442c-a462-aa7e982de544.png">
<img width="1916" alt="3" src="https://user-images.githubusercontent.com/3188382/185571270-cfb1dabc-ba48-461a-b561-4a40c1a60b9b.png">

**Comment by sumerjabri** [comment]
It might be that GitHub denied that request. We're unable to reproduce this issue.

**Comment by sumerjabri** [comment]
Was able to reproduce and fixing now. Thanks for reporting.
