### ISSUE TITLE
[studio-ui] PDF assets are not able to be previewed in Studio

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5735]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

PDF assets uploaded to studio are not able to be viewed.

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Navigate to the Static-assets folder
3. Upload a PDF document
4. After the successful upload, attempt to view the document. Notice it is not able to be previewed

### Relevant log output

```shell
N/a
```

### Screenshots and/or videos

N/a

**Comment by rart** [comment]
@jvega190 add a condition on the preview dialog for PDFs; the preview dialog would simply open an iframe and source it at the resource url. Include also other stuff that in 3.x opens in the Preview frame.

**Comment by AndyReiter** [comment]
Confirmed in the latest build of 4.0-SNAPSHOT.
