### ISSUE TITLE
[studio-ui] Enhance Group Management

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#574]
Please update group management to become two pages:
The first page lists the "Group Management" page, see screenshot. It allows the user to list, filter, edit, delete groups.

The second page allows editing the group name and description, add users. The lower portion lists the users, allows filtering of users in the list and allows removing a user from the group.
![edit group](https://cloud.githubusercontent.com/assets/3931908/23859964/d2b21198-07db-11e7-909f-285b0d315a08.png)
![group management](https://cloud.githubusercontent.com/assets/3931908/23859963/d2af23ac-07db-11e7-9a93-481c25c5e09d.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/304

**Comment by jvega-crafter** [comment]
This has to be added in /config/studio/administration/tools.xml in order to see the groups entry on the admin console
`<tool><name>groups</name><label>Groups</label></tool>`
