### ISSUE TITLE
[studio-ui] Disable Publish on Demand until an Initial Publish has been performed

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5744]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The user is currently able to do partial publishing through Publish on Demand.

### Describe the solution you'd like

The user must not use Publish on Demand features until an initial publish has been done. Please update this UI
![image](https://user-images.githubusercontent.com/3931908/186198989-1ca45bc9-bb3e-4a3d-bc8b-b87394ce193a.png)

to disable these features until an initial publish is performed. Allow the user to perform this within this dialog.

On the backend, any publish (by commit, bulk, publish all, etc.) will result in an initial publish.

**Comment by rart** [comment]
@sumerjabri @jmendeza the piece of data of whether a site has been published was embedded on to `/studio/api/2/publish/available_targets` api (don't ask me why). We need a devoted api for this please.

Something like `/studio/api/2/publish/has_initial_publish?siteId=craftercmscom` perhaps

**Comment by rart** [comment]
@jvega190 
- Design below
- Use word project instead of site, though
- Check for publishing permissions for showing the publish button
  - The publish button show invoke the publishing dialog. You can give it "Home" as the item.

![InitialPublishRequired](https://user-images.githubusercontent.com/3928341/187420111-1e9afebc-017a-485d-9cda-d59ebb1da54a.png)

**Comment by sumerjabri** [comment]
@rart please file a seperate ticket requesting that API

**Comment by rart** [comment]
> @rart please file a seperate ticket requesting that API

https://github.com/craftercms/craftercms/issues/5847
