### ISSUE TITLE
[docs] Update SAML2 docs to include multi-environment configuration steps

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5747]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, the multi-environment configuration based on an environment-specific folder does not work for SAML2. Per the docs the SAML2 configuration folder sits outside the environment folder.
https://docs.craftercms.org/en/4.0/site-administrators/engine/engine-saml2-configuration.html

### Describe the solution you'd like

Update the docs to explain that in your environment-specific site-config.xml files you can point to environment-specific saml2 files in the SAML2 folder

Specifically for any path/file configuration of SAML2
```
keystore.path | The path of the keystore file in the repo | /config/engine/saml2/keystore.jks
identityProviderDescriptor | The path of the identity provider metadata XML descriptor in the repo | /config/engine/saml2/idp.xml
serviceProviderDescriptor | The path of the service provider metadata XML descriptor in the repo
```

Example:
```
     <keystore>
        <defaultCredential>abc-crafter-saml</defaultCredential>
        <path>/config/engine/saml2/keystore-envx.jks</path>
        <password encrypted="true">${enc:value}</password>
        <credentials>
          <credential>
            <name>abc-crafter-saml</name>
            <password encrypted="true">${enc:value}</password>
          </credential>
        </credentials>
      </keystore>
      <identityProviderName>http://www.okta.com/abc</identityProviderName>
      <identityProviderDescriptor>/config/engine/saml2/idp-envx.xml</identityProviderDescriptor>
      <serviceProviderName>https://intranet.abc.org/saml/SSO</serviceProviderName>
      <serviceProviderDescription>/config/engine/saml2/sp-envx.xml</serviceProviderDescription>
    </saml2>
    ```

**Comment by russdanner** [comment]
I dont see the changes in the doc

**Comment by alhambrav** [comment]
Hi Russ! I added the changes here: https://docs.craftercms.org/en/4.0/site-administrators/engine/engine-multi-environment-configuration.html#saml2-multi-environment-configuration-enterpriseonly

**Comment by russdanner** [comment]
Confirmed
