### ISSUE TITLE
[studio] STUDIO_TOKEN_VALID_ISSUERS env variable not working

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5748]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Setting the env variable `STUDIO_TOKEN_VALID_ISSUERS` to a comma-separated list doesn't work

### Steps to reproduce

Steps:

1. Set `STUDIO_TOKEN_ISSUER` to `issuer1`
2. Set `STUDIO_TOKEN_VALID_ISSUERS` to `issuer1,issuer2`
3. Start Studio and log in

You will see a bunch of JWT-related errors in the logs, and the Studio UI just showing a spinner 

### Relevant log output

```shell
[WARN] 2022-08-29T15:39:58,335 [http-nio-8080-exec-9] [internal.AccessTokenServiceInternalImpl] | Detected usage of invalid JWT: JWT (claims->{"iss":"issuer1","iat": 1661787597,"sub":"admin","aud":"issuer1","exp":1661787897}) rejected due to invalid claims or other invalid content. Additional details: [[12] Issuer (iss) claim value (issuer1) doesn't match expected value of issuer1,issuer2]
```

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.2-SNAPSHOT`
