### ISSUE TITLE
Update SAML multi-env config to work like other multi-env config

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5749]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Today multi-env config for SAML2 works differently from other multi-env config
- Most multi-env config relies on an environment-specific folder and env  mapping
- SAML2 multi-env config uses a folder outside of the environment folder and uses environment=specific files in that single folder pointed to by name via the site-config.xml (found in the environment-specific folder.)

### Describe the solution you'd like

Update SAML2 configuration to work in the same fashion as other multi-environment configurations.

**Comment by sumerjabri** [comment]
The system has changed. Closing and can reopen if it's an issue with the new SAML implementation.
