### ISSUE TITLE
[studio] get-all users doesn't show all the sites the user is a member of

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#575]
Create a user
Create two sites
Add the user to both sites
Execute API: http://localhost:8080/studio/api/1/services/api/1/user/get-all.json
You'll note the user is a member of one of the sites, not both
-------
Delete user from one of the groups and the API will now show no membership in any group.
-------
Execute the API get-user.json and you'll see correct results.

**Comment by dejan-brkic** [comment]
Can not reproduce.
Tried removing user from each group (and adding it back before removing from next group)

**Comment by sumerjabri** [comment]
Per our conversation and screen share.

**Comment by dejan-brkic** [comment]
PR #579
