### ISSUE TITLE
[wordify] Console errors and disabled "Edit mode"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

- When loading the project, there's an error in the console: 

```    
  Model f4b2297e-af30-a288-6b54-1e838a0eadf5 was found in multiple parents (8d7f21fa-5e09-00aa-8340-853b7db302da and feb3f1e7-0c71-1275-d580-3e56b965eae0). Same model twice on a single page may have unexpected behaviours for in-context editing.
```

![wordify-error-on-load](https://user-images.githubusercontent.com/25483966/187293451-7b6781ef-16d3-4d55-b2db-176aa3a7c5a1.png)

- There are errors in the console when you view a post.  
   From the home page, click on a post to view.  Notice the errors in the console once you clicked on a post:
```
[ICERegistry] Field "headline_s" was not found on the "Post Container" content type. Please check the field name matches one of the content type field names (fileName, internalName, placeInNav, navLabel)
```
![wordify-error-loading-post](https://user-images.githubusercontent.com/25483966/187293816-6bb95a25-8d48-4c3c-808e-777475e1ebd5.png)

- `Edit mode` gets disabled
    In the post, enable `Edit mode` then click on the main image, now scroll down a little to the post container containing the title of the post and click on it... The green caption that says `Main Image` should disappear.  Click on the post container again and notice that the `Edit mode` at the top of the screen is disabled and the following message appears on the screen:
```
Communication with the preview application was interrupted. Studio will continue to retry the connection.
```
 Also, when you look in the console, there is an error:
```
TypeError: Cannot read properties of undefined (reading 'type')
    at ZoneMenu (craftercms-xb.umd.js:60482:57)
    at Uh (craftercms-xb.umd.js:4770:9)
    at Uk (craftercms-xb.umd.js:8442:13)
    at Tk (craftercms-xb.umd.js:8079:13)
    at Sk (craftercms-xb.umd.js:8071:27)
    at Hk (craftercms-xb.umd.js:8055:7)
    at Mk (craftercms-xb.umd.js:7718:9)
    at Dk (craftercms-xb.umd.js:7784:30)
    at ig (craftercms-xb.umd.js:3747:18)
    at Vk (craftercms-xb.umd.js:8191:5)
```

Notice that to get `Edit mode` or `Move mode` to work again, you'll have to reload the page.  Also, this seem to be happening only to the `Post (post container)` section

![wordify-edit-mode-disabled](https://user-images.githubusercontent.com/25483966/187296266-e2259a04-2f57-434e-af88-8f15cf1f1428.png)

### Steps to reproduce

Steps:

1. Open the console on your browser, then create a project using the `Wordify` blueprint from the marketplace
2. Notice the error in the console once your project loads
3. Click on a post in the page.  Notice the errors in the console once the post loads.
4. Enable `Edit mode` then click on the main image.  Now scroll down a little to the post container containing the title of the post and click on it... The green caption that says `Main Image` should disappear.  Click on the post container again and notice that the `Edit mode` at the top of the screen is disabled.
5. Notice the message that pops up  and the error in the console as noted above 

### Screenshots and/or videos

Here's a short clip showing the Edit mode disabled: https://www.loom.com/share/16ff328ba7de4f2f937ae597137051fa

**Comment by rart** [comment]
The "model of found in multiple parents" is not a big issue. Something to discuss whether we adjust the copy of the message or not print it at all, @sumerjabri. This would be something we do in studio.

The rest should be fixed (at the bp level).

**Comment by alhambrav** [comment]
Verified fixed.
