### ISSUE TITLE
[videocenter] Cursor does not change to pencil when in "Edit mode" and console errors

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5752]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

- When loading the project, there are errors in the console such as:
```
[parseContentXML] Field "boxVideo" was not found on "/component/youtube-video" content type. "/site/videos/goldbach-conjecture.xml" may have stale/outdated content properties. 
```
```
[parseContentXML] Field "date_dt_tz" was not found on "/component/youtube-video" content type. "/site/videos/goldbach-conjecture.xml" may have stale/outdated content properties.
```
![video-center-errors-on-load](https://user-images.githubusercontent.com/25483966/187300498-828d676c-950c-45b1-902b-a569d242b4aa.png)

- When `Edit mode` is enabled, notice when hovering on xb wired sections, the cursor does not change into a pencil like in other blueprints...  Should the cursor change into a pencil too?

### Steps to reproduce

Steps:

1. Open  your  browser console then create a project  using the `Video Center` blueprint from the marketplace in Studio
2. Once your project loads, notice the errors in the console as noted above
3. Enable `Edit mode` by clicking on the pencil at the top right
4. Notice when hovering on xb wired sections, the cursor does not change into a pencil like in other blueprints.  See the short clip below to see the  cursor not changing to a pencil

### Screenshots and/or videos

Here's a short clip showing the cursor not changing into a pencil when hovering on wired sections: https://www.loom.com/share/edad9566b3b543fc814ba7c35970d9b4

**Comment by jvega190** [comment]
@alhambrav the cursor issue is an XB issue, will be fixed in this [ticket](https://github.com/craftercms/craftercms/issues/5792)

**Comment by alhambrav** [comment]
Verified console error for box video fixed

**Comment by alhambrav** [comment]
Waiting on https://github.com/craftercms/craftercms/issues/5792

**Comment by alhambrav** [comment]
Verified fixed.
