### ISSUE TITLE
[studio] Upgrade manager doesn't update data sources to upgraded sites

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5755]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Upgrade manager doesn't add "Drop Targets" data source to upgraded sites. This disables them to easily begin migrating to XB - as XB component drag & drop depends upon the usage of the drop targets data source.

### Steps to reproduce

Steps:

1. Run a site from 3.x on 4
2. Go to any content type or create a new one
3. Add an item selector and feed it through a drop targets datasource
4. Notice drop targets is not an option of data source to add

**Comment by sumerjabri** [comment]
Related to/overlaps with https://github.com/craftercms/craftercms/issues/5785

**Comment by sumerjabri** [comment]
Duplicates https://github.com/craftercms/craftercms/issues/5785
