### ISSUE TITLE
[studio] User is given the option to publish items that are already in a live state

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The user is given an "Available action" to Publish when the item is in a Live state.

If the item is New, Edited, in Workflow, or Published to Stage, then Publish should be available as an action. 
However, if the item is in a Live state, there's no reason to give the user the Publish action.
Also, if the item is Locked OR in System Processing, the user should not be given the Publish action.

### Steps to reproduce

Steps:

1. Put the item in any state that the user should not be given the publish action
2. Check the options menu for the item
3. See that the user is given the publish (and in some cases the reject) action

### Screenshots and/or videos
**Simple Example:** 
Item is already Live, but the user is given Publish action
<img width="672" alt="Screen_Shot_2022-08-22_at_9 54 59_AM" src="https://user-images.githubusercontent.com/169432/187508784-20590d15-b3a6-49f2-b2e8-877764469343.png">

**More interesting example:**
Item is locked for edit, and user is given reject and publish

<img width="1656" alt="Screen Shot 2022-08-30 at 1 51 41 PM" src="https://user-images.githubusercontent.com/169432/187508781-5d416330-a662-4a1d-b80c-6445ab9649b5.png">

- Caveat in this case, the user canceled a workflow to make an edit.  
Thus a more simple form of this is to lock and edited an item or a new item. In this more simple case you would not see a Reject action.

**Comment by sumerjabri** [comment]
@russdanner are we good to close this one?
