### ISSUE TITLE
[studio] Content type preview images are not getting shown (`api/1/content/get-content-at-path.bin` returns a 406)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5759]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When looking at the content type list in the content type editor the "no screenshot set" image is displaying always.

Seems to be happening both in the new content dialog and the content type editor content type listing.

### Steps to reproduce

Steps:

1. Go to content type editor and/or new content dialog
2. Select a content type that has a preview image
3. See the issue

### Screenshots and/or videos

![dev-tools-headers-image](https://user-images.githubusercontent.com/3928341/187958969-2534ff5f-5596-4d02-a830-1c95a87fb190.png)
<img width="360" alt="dev-tools-response-preview-image" src="https://user-images.githubusercontent.com/3928341/187958974-e8964d48-2162-4f72-975f-8f2f908e3017.png">

**Comment by sumerjabri** [comment]
@phuongnq please create a new API under API v2 that returns the binary. The API should be something like:
https://app.swaggerhub.com/apis/craftercms/studio/4.0.1.0#/configuration/getContentTypeUsage but call it `/preview_image`

Please use similar mechanics as this API https://app.swaggerhub.com/apis/craftercms/studio/4.0.1.0#/plugin/getPluginFile to return the right MIME-type and headers.

**Comment by phuongnq** [comment]
Sample usage:

```
curl --location --request GET 'http://localhost:8080/studio/api/2/configuration/content-type/preview_image?siteId=test&contentType=page/article' \
--header 'authorization: Bearer <JWT_TOKEN>'
```

Sample response:
![2022-09-28_13-17](https://user-images.githubusercontent.com/2996543/192705721-21393793-797e-4f4b-ad79-ca43a08afb58.png)

**Comment by sumerjabri** [comment]
@phuongnq please add a unit test to this new API (check out Mockito and ping @jmendeza as needed to keep it simple).
@Euquimides please add a ticket to automate testing this API.
