### ISSUE TITLE
[studio] Upgrade Manager should not reformat config files needlessly

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#5762]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When the Crafter Upgrade Manager updates xml configuration files inside <sandbox>/config, whitespace changes, empty xml tag vs singleton, and line breaks are applied to the existing config files.  Recently, the upgrade manager seems to have handled this differently than how  (4.0.1E)

The format used also does not seem to be run through a format tool or generated consistently, because we see inconsistency in the files, and even trailing whitespaces.

Developers work with these files in their IDEs on a regular basis, so visual consistency and adherence to a standard (any standard - no need to turn this into a religious debate over spaces vs tabs) will greatly improve the developer experience.

A real problem arises though, when a developer has made changes to a file that is also reformatted. This results in automatic merge failures requiring manual intervention, and this can be tedious to address.

### Describe the solution you'd like

Please pick a single well-known standard for XML config file formatting.  When files are changed via Upgrade Manager, ensure that the XML is cleanly formatted, without excess whitespaces, or line breaks, and consistent indentation.  Then, please stick with that formatting as much pas possible going forward.

**Comment by sumerjabri** [comment]
this has been significantly improved (it's not perfect, but as you continue to edit what the machine produced with no reformatting, it'll become better).
