### ISSUE TITLE
[studio-ui] Audit: When the get parameters call fails, there's no feedback

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5764]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In "Audit" (project tools or global) when the get parameters call fails, there's no feedback of the failed called and it appears as if the button does nothing.

Also I'm running into a case where I a role view project tools, but can't view parameters. Not sure if this is valid, but if it is, the UI should check the permission and hide that column as otherwise he'll just see a 403 error message. This is in fact how I found this bug, except I didn't see any errors.

### Steps to reproduce

Steps:

1. Log in with a dev role user
2. Click on Project Tools > Audit
3. See the "parameters" of an entry
4. See the issue

Since the 403 might not exactly be the case anywhere, just fix the UI error handling of that call.

**Comment by jvega190** [comment]
This ticket was created for the 403 error in the audit api call as developer https://github.com/craftercms/craftercms/issues/5773

**Comment by rart** [comment]
Verified
