### ISSUE TITLE
[studio-ui] Dashboard issues

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5767]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

- Bulk actions don't seem to work (at least not the "Publish" option)
  - For publish an error appears on the browser console (something along the lines of item being null)
- After items are cleared, the actions bar remains checked/visible
  - Items that are cleared from the dashboard items should be cleared as selected too
  - After executing an action we should clear the selection

### Steps to reproduce

- Select multiple items on "awaiting approval" dashlet and try to publish them2. 

- Select 2 items in the queue and publish them individually (or bulk if you've fixed the above). The items should momentarily go away, yet the actions bar remains as if there was a selection.

**Comment by rart** [comment]
@jvega190 :

Selecting a single item doesn't show options other than clear — try/test/fix/retest in all widgets.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3928341/188850469-770fd290-8b15-48d2-815e-151c0c2d988e.png">

**Comment by jvega190** [comment]
We found that the selection issues mentioned above happen when items are not loaded in state (path nav trees closed)

**Comment by rart** [comment]
@Euquimides please give it a test
