### ISSUE TITLE
[studio-ui] webp images not showing in content type list in the content type editor

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5769]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`.webp` images are not previewable in the content type list in the content type editor.

### Steps to reproduce

Steps:

1. Go to project tools -> content-types
2. Assign a `.webp` image as the preview image of a content-type
3. Go back to the list of content-types
4. See the issue

**Comment by jvega190** [comment]
There's an issue with the api that returns the images, reported [here](https://github.com/craftercms/craftercms/issues/5759)

**Comment by sumerjabri** [comment]
We must switch to frontend cropper like this http://foliotek.github.io/Croppie/#documentation

**Comment by jvega190** [comment]
@sumerjabri now cropperjs is being used, and webp images are allowed in content-type editor. Should we close this ticket and if needed, create another one for crop library enhancements?
