### ISSUE TITLE
[studio] When performing an initial publish, a publish event should be triggered instead of a workflow event

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5770]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When performing an initial publish, the workflow event is triggered, which is not incorrect, but is a more general event than publish. Publish event should be triggered in this scenario.

### Describe the solution you'd like

Trigger publish event when performing an initial publish.

**Comment by sumerjabri** [comment]
This is also a chance to review all events. @russdanner @jmendeza let's discuss.

**Comment by jvega190** [comment]
Verified fixed
