### ISSUE TITLE
[studio] Requests to API 2 `/audit/:id` as developer, returns HTTP 403 instead of 200

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5773]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Developer roles have access to `Project Configuration` which includes `Audit`. Requesting parameters to `http://localhost:8080/studio/api/2/audit/:id` API 2 as a Developer role via project Audit Logs will return a 403 response. 

### Steps to reproduce

Steps:

1. Log in to Studio as a `Developer`
2. Go to a site of your choice
3. Go to `Project Tools` -> `Audit`
4. Click on `Show Parameters`
5. See issue

### Relevant log output

```shell
{
    "response": {
        "code": 2001,
        "message": "Unauthorized",
        "remedialAction": "You don't have permission to perform this task, please contact your administrator",
        "documentationUrl": ""
    }
}
```

**Comment by jmendeza** [comment]
PR changes include a new siteId param to getAuditLogEntry. Unless that parameter is sent (or user is system admin) and the user has audit_log permission to the site, the request will fail.
Pending for the UI to be updated to include siteId param.
cc @rart @sumerjabri

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified fix for Crafter v4. Thank you! Closing the ticket.
