### ISSUE TITLE
[studio-ui][studio] Cutting and pasting items in the same folder changes original item for copy

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5774]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Usually, when you cut and paste an item in the same directory. it creates a duplicate of the item in the selected directory. But right now, when cutting and pasting the item the duplicate is not being created but changed for the copy. 

### Steps to reproduce

Steps:

1. Go to a site of your choice. 
2. Right-click, select `Cut` on an item of your choice. 
3. Paste it in the same directory of the item. 
4. See the issue

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/188749954-ed4b085a-0ac5-4e3c-989b-c04b761bcbb1.mp4

**Comment by jmendeza** [comment]
PR https://github.com/craftercms/studio/pull/3121 includes updates to the API so a 400 status code is returned when the target paste is invalid.
UI can either handle that response, or prevent these requests from being issued at all (when the paste target is the same as the source, just clear the clipboard if the operation is CUT).
@sumerjabri @rart

**Comment by sumerjabri** [comment]
Assign to @rart when done with backend.

**Comment by jmendeza** [comment]
Assigning to @rart for front end updates

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified fix for Crafter v4. Thank you! Closing this ticket.
