### ISSUE TITLE
[studio] Scripts not appearing in `Items Waiting For Approval` dashlet when requesting publish

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5775]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you request publish a script, the selected script will not appear in the `Items Waiting for Approval` dashlet. 

### Steps to reproduce

Steps:

1. Go to a site of your choice.
2. Request publish a script of your choice. 
3. Open `Dashboard`
4. See the issue

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/188754964-b587afe6-54eb-47dc-882c-fdff4fda41ee.mp4

**Comment by sumerjabri** [comment]
@rart this might be a backend issue, let me know if it is.

**Comment by rart** [comment]
@sumerjabri yes, it must. the ui only displays.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Validated fix for Crafter v4. Thank you! Closing this ticket.
