### ISSUE TITLE
[studio-ui] While duplicating content, show a spinner or indicator that it is in progress

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5776]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In the case of duplicating content with images as dependencies uploading to S3, it could take time. My test for component with a 3MB image in S3 duplication took around 30s. While waiting, it is not clear whether the duplication is in progress or not.

### Describe the solution you'd like

Show a spinner or indicator that the duplication is in progress

**Comment by rart** [comment]
@jvega190 dispatch blockUI action and unblockUI when complete before proceeding.

**Comment by phuongnq** [comment]
confirmed
