### ISSUE TITLE
[studio] Change `site-policy-config.xml` default site policy to include `\s` regex for spaces

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5777]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The default site policy included in `site-policy-config.xml` does not include a regex for spaces, so any file that is uploaded with spaces in it will appear as is in Studio. Please change the `site-policy-config,xml` to include spaces in the source-regex statement. The regex is `\s`.

### Relevant log output

```shell
<site-policy>
   <statement>
      <target-path-pattern>/static-assets/.*</target-path-pattern>
      <permitted>
         <path>
            <source-regex>[\(\)\s]</source-regex>
            <target-regex>-</target-regex>
         </path>
      </permitted>
   </statement>
   <statement>
      <target-path-pattern>/.*</target-path-pattern>
      <permitted>
         <mime-types>*/*</mime-types>
      </permitted>
      <denied>
         <mime-types>image/png</mime-types>
         <mime-types>image/jpeg</mime-types>
         <mime-types>image/gif</mime-types>
      </denied>
   </statement>
</site-policy>
```

### Screenshots and/or videos

The expected behaviour is:

![Screenshot from 2022-09-08 10-34-50](https://user-images.githubusercontent.com/90878288/189193930-66b38f85-9c13-487b-9d04-75604d5d1130.png)
![Screenshot from 2022-09-08 10-38-36](https://user-images.githubusercontent.com/90878288/189193937-d5b6354d-b9dc-4efd-9fc1-3cfdaa0a2efa.png)

**Comment by sumerjabri** [comment]
Apply the same to all BPs.

**Comment by sumerjabri** [comment]
Depends on https://github.com/craftercms/craftercms/issues/5781

**Comment by sumerjabri** [comment]
All blueprints updated.

**Comment by Euquimides** [comment]
Hi! The changes to the policy configuration has been applied to the BPs. Validated this fix. Thank you! Closing this ticket.
