### ISSUE TITLE
[studio][studio-ui] Provide better logs 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5778]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current Log Console both present in the Studio Global dashboard and the Site Config are very limited and are not very useful:

- They display a very limited amount of entries
- You don't have any control over how far in the past you can get log entries
- Log entries don't include a stack trace when there's an exception
- The entire log entries go away on a restart

### Describe the solution you'd like

Provide a better log console, with the ability to indicate how many lines in the past you want to display, with a UI similar to an actual log file. A suggestion:

In the Global dashboard, in the Log Console section, present 2 tabs/screens, one tailing `studio.log` and another one tailing `engine.log` (standard log files in the server). You should be able to configure how many lines to display and possibly have the log auto-refresh every 10 secs

**Comment by sumerjabri** [comment]
Superseded by https://github.com/craftercms/craftercms/issues/5881
