### ISSUE TITLE
[studio-ui] Move "Saved" green notification to the top left of the current panel

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#578]
When editing a content item, hit save and you'll note the "Saved" notification at the bottom right. That's not very noticeable to end-users. Please move that to the top left area of the current panel.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/285

**Comment by vestrada** [comment]
Done

**Comment by sumerjabri** [comment]
It's working, mostly, but it's showing at the top left, not at the top left of the current panel.
What we want is something like the attached if possible (note we made the text bigger):
![Uploading Screen Shot 2017-03-20 at 3.42.11 PM.png…]()


Please ping me if you have any questions or concerns.

**Comment by sumerjabri** [comment]
Uploading attachment again
![screen shot 2017-03-20 at 3 42 11 pm](https://cloud.githubusercontent.com/assets/3931908/24118452/3ab997fe-0d84-11e7-9ae4-97c72f4718fd.png)

**Comment by vestrada** [comment]
Master PR: https://github.com/craftercms/studio2-ui/pull/301
