### ISSUE TITLE
[studio-ui] Projects - don't cancel the marketplace/search request when loading the page. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5780]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `marketplace/search` request is canceled on loading the `Projects` page. While using a throttling of `Fast 3G` the issue is not reproducible. 

### Steps to reproduce

Steps:

1. Open the `Users` page
2. Move to the `Projects` page
3. Check Studio log or browser Network/Console

### Relevant log output

```shell
[ERROR] 2022-09-09T12:50:57,370 [http-nio-8080-exec-5] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/marketplace/search?limit=1000&showIncompatible=true&type=blueprint' failed with response 'ApiResponse{code=1000, message='Internal system failure', remedialAction='Contact support', documentationUrl=''}' 
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353) ~[catalina.jar:9.0.64]
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:784) ~[catalina.jar:9.0.64]
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:689) ~[catalina.jar:9.0.64]
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388) ~[catalina.jar:9.0.64]
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/6722074/189409518-d5f866f6-bf8a-4a7c-9475-eceeb9159ac7.mp4

**Comment by rart** [comment]
@jvega190 
- Please refactor the CreateSiteDialog to have a container component with all the fetching and logic that is currently in the main component. This causes most of the dialog logic to run as soon as the users land on the project management view. 
- Double check the effect that fetches the marketplace blueprints. It might need a bit of split of responsibilities or something similar.

**Comment by yacdaniel** [comment]
Verified fixed.
