### ISSUE TITLE
[studio] Broken repository paths due to recursive actions of policy configuration

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5781]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When adding a small change to policy configuration, for example, adding `<target-regex caseTransform="uppercase"/>` as a permitted statement:
```
<site-policy>
    <statement>
        <target-path-pattern>/static-assets/.*</target-path-pattern>
        <permitted>
            <path>
                <source-regex>[\(\)]</source-regex>
                <target-regex>-</target-regex>
                <target-regex caseTransform="uppercase"/>
            </path>
        </permitted>
    </statement>
    <statement>
        <target-path-pattern>/.*</target-path-pattern>
        <permitted>
            <mime-types>*/*</mime-types>
        </permitted>
        <denied>
            <mime-types>image/svg+xml</mime-types>
        </denied>
    </statement>
</site-policy>
```
The change in theory will affect any new item that is uploaded, changing it's name to uppercase. But it will also apply the change to the current directory recursively, breaking directory paths by changing  `images` for `IMAGES` and `static-assets` to `STATIC-ASSETS`. This recursive action during validation should be evaluated since it can affect whole sections. 

### Steps to reproduce

Steps:

1. Go to any site based on Editorial BP.
2. Go to `Project Tools` -> `Configuration` -> `Project Policy Configuration`
3. Add `<target-regex caseTransform="uppercase"/>` as a permitted statement.
4. Save the new policy. 
5. Upload an item to `images` folder in `static-assets`. 
6. Accept the changes.
7. See issue. 

### Screenshots and/or videos

You will notice two things: if the project is fresh the write-content.json will fail with an error, failing to apply the changes and uploading the item, after the second time it will work but the paths will be affected recursively and since the name of the paths have changed, it will affect the whole section breaking the repository paths. 

https://user-images.githubusercontent.com/90878288/189418065-20fc107c-a278-462c-8aa0-bc189435bf81.mp4

**Comment by sumerjabri** [comment]
Key ideas:
* Policy Engine should only execute on `create`.
* Policy Engine should only execute on the item, not the full path to the item.

**Comment by sumerjabri** [comment]
Please make the Policy Engine execute on `create` (one time only when an object is created) and only against the item not the path to the item.

**Comment by sumerjabri** [comment]
@phuongnq the PR doesn't address the issue we have sufficiently

The Site Policy implementation activates on:
* Create
* Rename
* Move
* Copy

We want to limit the naming policy to `Create` and drop the support for other actions to avoid the issues listed in the ticket.

Additionally, in the `Create` path, we want to limit execution to the file name and not the full path, only where it makes sense (in some cases we have to look at the full path).

Note that the Site Policy engine does a lot more than just naming conventions. For this ticket, we're only interested in that aspect of it. Please see the design document to better understand the scope of this issue.

Ping me or @russdanner for more information.

**Comment by phuongnq** [comment]
@sumerjabri Updated PR as discussed.

**Comment by sumerjabri** [comment]
@Euquimides please validate and add to the test suite.

Please remember to validate things like:
* /static-assets/images/My Nice Image (1).jpg -> /static-assets/images/my-nice-image--1--.jpg
* /site/website/My Folder -> /site/website/my-folder
* Move, copy/paste, bulk-upload etc.

**Comment by Euquimides** [comment]
@sumerjabri I've updated and rechecked this issue. Related with the conversion to lowercase, this seems to be achieved when adding a target-regex statement to the site policy. I added a PR for this in https://github.com/craftercms/studio/pull/3098. Also the change might have affected how policy configuration works? Please check out this ticket: #5796

**Comment by sumerjabri** [comment]
Need to update all marketplace BPs

**Comment by sumerjabri** [comment]
All blueprints updated.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Validated fix for Crafter v4. Thank you! Closing this ticket.
