### ISSUE TITLE
[studio] Have UM migrate 3.1 form definitions to 4.0 definitions

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5785]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

UM needs to update 3.1, and <4.0.2 data sources to 4.0.2 data sources

### Describe the solution you'd like

Have UM migrate 3.1 form definitions to 4.0 definitions
- [x] [UI] Rename `Drop Targets` to `Components` in the UI code
- [x] [UI] Rename `Project Component` to `Simple Taxonomy` in the UI code
- [x] [UI] Remove the data source `child-content`
- [x] [UI] Update localization strings
- [x] [BE] UM `site-config-tools.xml` to switch `dropTargets` in `site-config-tools.xml` to `components` (the new control renamed above) -- the new name is `components`
- [x] [BE] UM `site-config-tools.xml` Remove `Child Content` data source from the list of visible data sources from `site-config-tools.xml`
- [x] [BE] UM `site-config-tools.xml` to switch `Project Component` to `Simple Taxonomy` -- the new name is `simpleTaxonomy`
- [x] [BE] UM *Content Types* in all Projects: change existing `Child Content` in content type definitions (in the project) to the new `components` -- the new name `components`
- [x] [BE] UM *Content Types* in all Projects: change existing `Drop Targets` in content type definitions (in the project) to the new `components` -- the new name `components`
- [x] [BE] UM *Content Types* in all Projects: change existing `Project Component` in content type definitions (in the project) to the new `simpleTaxonomy` -- the new name `simpleTaxonomy`
- [x] [BE] Update by hand all built-in blueprints
- [x] [BE] Update all MP blueprints

**Comment by phuongnq** [comment]
@sumerjabri @russdanner Confirmation of the requirement:

1. Rename “Drop Targets” to “Components”

AFAIK, a new site which is created in v4 also uses the term "Drop Targets". The label is set here: https://github.com/craftercms/studio-ui/blob/develop/ui/legacy/src/components/cstudio-forms/data-sources/dropTargets.js#L94
Shouldn't this be a UI update?

2. Remove “Child Content” from the list of visible data sources

This can be done via the UM, to rename "Child Content" to "Drop Targets". See the PR.

3. Rename “Project Component” to “Simple Taxonomy”

A new site that is created in v4 also uses the term "Project Component". The label is set here:
https://github.com/craftercms/studio-ui/blob/develop/ui/app/src/env/i18n-legacy.ts#L558
Shouldn't this be a UI update?

4.  Change Child Content to the new “Components” (the old “Drop Targets”)
Doesn't this overlap with (2) and (1)?
The PR updates the UM to change the Child Content to Drop Targets.
The term, however, need a UI update as mentioned in (1).

**Comment by phuongnq** [comment]
Old datasources:

```
<datasource>
    <name>dropTargets</name>
    <icon>
        <class>fa-object-group</class>
    </icon>
</datasource>
...
<datasource>
    <name>site-component</name>
    <icon>
        <class>fa-puzzle-piece</class>
    </icon>
</datasource>
```

New datasources:

```
<datasource>
    <name>components</name>
    <icon>
        <class>fa-puzzle-piece</class>
    </icon>
</datasource>
...
<datasource>
    <name>simpleTaxonomy</name>
    <icon>
        <class>fa-tags/class>
    </icon>
</datasource>
```

**Comment by sumerjabri** [comment]
@phuongnq yes, that's correct

**Comment by phuongnq** [comment]
@sumerjabri Updated PRs.
In the MP: PRs are for `next` branch, in `wordify-blueprint`, also added a PR for `react` branch.
[BP](https://github.com/craftercms/alexa-blueprint): This seems to be a 3.1 version so I'm not updating yet.

**Comment by russdanner** [comment]
The Site Component's label was changed to Site Taxonomy instead of Simple Taxonomy
<img width="1351" alt="Screen Shot 2022-10-13 at 5 10 23 PM" src="https://user-images.githubusercontent.com/169432/195711557-6cb197bc-d8a7-4f42-ad34-2bf0cdf35529.png">

**Comment by phuongnq** [comment]
@rart @jvega190 Please check Russ's above comment. I believe the label is from UI

**Comment by russdanner** [comment]
@sumer I reviewed the PR and am happy with the changes. This can be closed after the merge.
