### ISSUE TITLE
[studio] API `/studio/api/2/publish/history` doesn't show an asset published as a page/component hard dependency

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5786]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The API `/studio/api/2/publish/history` doesn't show an asset published as a page/component hard dependency.

### Steps to reproduce

Steps:

1. Create a site from the editorial blueprint.
2. Do the initial publish of the site
3. Create a new page article and upload a new image to this page
4. Publish this new article
5. Check the `Recently Published` widget on the Dashboard. 

### Screenshots and/or videos

Publish dialog
![image](https://user-images.githubusercontent.com/6722074/189929105-3d4bf8d5-3e59-4fb9-9f45-8cf1d32a924e.png)
Dashboard widget after publish
![image](https://user-images.githubusercontent.com/6722074/189930475-d5c52be2-81a3-493f-be25-006ecbb7a027.png)

**Comment by jmendeza** [comment]
Cannot reproduce this issue

**Comment by yacdaniel** [comment]
Verified not reproducible in 4.0.2
![image](https://user-images.githubusercontent.com/6722074/198147040-98988e45-746d-4ccb-b7ee-0316395b9121.png)
