### ISSUE TITLE
[studio] On a cluster setup, Studio only shows the primary node in the Cluster screen

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5788]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

On a cluster setup, Studio only shows the primary node in the Cluster screen

### Steps to reproduce

Steps:

1. Setup Studio as a cluster
2. Login to the primary
3. Go to the `Cluster` screen

You should see that only the primary's status is shown, when it should show the primary and replicas.

**Comment by sumerjabri** [comment]
@jmendeza let's discuss how to proceed with this given the new clustering mechanics.

**Comment by sumerjabri** [comment]
new API spec https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0

**Comment by avasquez614** [comment]
Validated
