### ISSUE TITLE
[studio-ui] XB - editing items inside repeating group opening an empty form

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5794]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When clicking on edit on an item inside a repeating group, the edit form opens but is empty.

### Steps to reproduce

Steps:

1. Go to a site with a repeating group using xb
2. Click on an item of the repeating group and click on the edit icon
3. See that the form opens with no content on it

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Validated for Crafter v4.
