### ISSUE TITLE
[studio-ui] Upload dialog should show new file name after applying policy configuration

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5795]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In the upload dialog, the dialog shows that the selected file will be renamed in accordance to the policy configuration, but once the file is uploaded, it doesn't show the new name in the dialog but the initial name. 

### Steps to reproduce

Steps:

1. Go to any site of your choice. 
2. Upload a file that isn't in accordance to the policy configuration. 
3. Accept the changes of the automatic renaming applied by Studio. 
4. See the issue

### Screenshots and/or videos

![Screenshot from 2022-09-22 10-19-35](https://user-images.githubusercontent.com/90878288/191811993-74bbb48f-0418-4705-88b3-3789a60f432a.png)
![Screenshot from 2022-09-22 10-19-43](https://user-images.githubusercontent.com/90878288/191812049-3486b732-04c0-45a0-8f41-4ef5b76d9aad.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While doing some tests with the policy configuration, I noticed a small bug related with this issue: upon uploading a file, if you don't click in the check button `Accept changes and upload` but instead immediately click on `Accept all changes`, the dialog will not get updated with the new name according policies. Please check this out. 

https://user-images.githubusercontent.com/90878288/194955247-df7cef34-02ba-41e8-a8d3-2a245dbaf18d.mp4

**Comment by sumerjabri** [comment]
CC @rart

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The uploaded file name is updating fine according to policies in both options `Accept changes and upload` and `Accept all changes`. Validated for Crafter v4. Closing this ticket.
