### ISSUE TITLE
[studio] Items that violate the site policy get uploaded to Webdav repo anyway

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5797]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you upload an item that contains spaces or other illegal chars according to URL standards (an image that contains spaces, for example `Screenshot from 2022-09-08 10-06-40.png`, will translate into a path that includes these spaces), the logs will show an error related with illegal chars BUT the item will still be uploaded to the Webdav repository. 

### Steps to reproduce

Steps:

1. Go to any site of your choice. 
2. Set up the site to use Webdav.
3. Add a Webdav contoller for uploading items or images to an existing Content Type. 
4. Upload an image or item that include spaces, for example `'This is a test.txt'`.
5. See issue.  

### Relevant log output

```shell
[ERROR] 2022-09-26T11:16:08,755 [http-nio-8080-exec-8] [a1] [impl.DefaultExceptionHandler] | GET http://localhost:8080/remote-assets/webdav/webdav-default/Shared/Screenshot%20from%202022-06-17%2010-00-26
.png failed                                                                                                                                                                                                
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Illegal character in path at index 59: http://xxx.xxx.xx.20:8080/al
fresco/webdav/Shared/Screenshot from 2022-06-17 10-00-26.png
```

**Comment by phuongnq** [comment]
Created PR to encode WebDAV resource with space => `%20`. https://github.com/craftercms/commons/pull/318

Regarding the project policy:

* The project policy is only applied to local assets. A remote asset such as WebDAV and S3 can be anything, including files with space. In the Project Policy Configuration, we also have the default value for `/static-assets` while remote assets start with `/remote-assets`

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The error is not shown anymore in the logs, so the fix is verified. Also closing this ticket, since Project Policy isn't being applied to remote assets such as WebDav and S3.
