### ISSUE TITLE
[studio][studio-ui] Item Selector Controller adding a duplicate with an additional `/` when uploading files

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5802]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When uploading files to a `Item Selector` controller with a `File Uploaded from Desktop` data source, the file along with a duplicate that includes an additional `/`. For example, uploading `lorem.doc` is adding the file to `/static-assets/lorem.doc` along with `/static-assets//lorem.doc`.

### Steps to reproduce

Steps:

1. Go to a project of your choice. 
2. Go to `Project Tools` -> `Content Types` and edit an existing `Content Type` to include a `Item Selector` controller with a `File Uploaded from Desktop` data source. 
3. Upload a file using the controller. 
4. In Crafter search, look up for the uploaded file.
5. See issue.

### Relevant log output

```shell
In the browser's console, the following error appears upon uploading the file:

14:38:44.784 [createModelMap] Content type with id null was not found. Unable to fully process model at '/static-assets//lorem.doc' with id lorem.doc content.ts:545:14
    k content.ts:545
    k content.ts:619
    k content.ts:617
    me PreviewConcierge.tsx:250
    RxJS 82
```

### Screenshots and/or videos

![Screenshot from 2022-09-29 15-38-34](https://user-images.githubusercontent.com/90878288/193146892-3ec4d427-57e7-4205-a7ac-bf665dc318cc.png)
![Screenshot from 2022-09-29 15-38-12](https://user-images.githubusercontent.com/90878288/193146903-b980cc66-9ce7-43f9-9c4b-1aacf944b633.png)

**Comment by jvega190** [comment]
Hi @Euquimides! The log showing in the console is due to a separate reason (not the path with multiple '/') and won't be removed yet. There is a pending conversation for that, and is due to the usage of node-selectors with file datasources. That is only a warning and currently not causing any issue.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The error is not appearing in the console anymore. Since the `/` is not not an error per se or causing any issue, this is not taken into account. Verified fix for Crafter v4. Thank you! Closing this ticket.
