### ISSUE TITLE
[studio-ui] Files uploaded via Item Selector controller, uploading to Webdav repo but not appearing in Studio UI

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5803]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you have a `Content Type` with an `Item Selector` controller, when uploading a file to a Webdav repository via the controller, the file will be uploaded to the Webdav repository but will not appear in the UI. 

### Steps to reproduce

Steps:

1. Go to a project of your choice.
2. Edit a `Content Type` to include a `Item Selector` controller and a `File Uploaded to Webdav Repository` data source.
3. Upload a file to Webdav repo via `Item Selector`
4. See the issue

### Relevant log output

```shell
In the browser's console:

16:07:30.589 [Uppy] [16:07:30] TypeError: fileName.split is not a function
    success form:85
    onComplete uploadWebDAV-dialog.js:166
    t SingleFileUpload.tsx:204
    emit index.js:131
    emit index.js:33
    value Uppy.js:256
    e Uppy.js:1786
    l runtime.js:63
    _invoke runtime.js:294
    S runtime.js:119
    Babel 8
    ue Uppy.js:1710
    value Uppy.js:1329
    promise callback*value Uppy.js:1312
    e SingleFileUpload.tsx:248
    RxJS 17
    e SingleFileUpload.tsx:240
    emit index.js:131
    emit index.js:33
    value Uppy.js:256
    value Uppy.js:606
loggers.js:14:11
    error loggers.js:14
    value Uppy.js:1196
    value Uppy.js:1332
    (Async: promise callback)
    value Uppy.js:1330
    e SingleFileUpload.tsx:248
    RxJS 17
    e SingleFileUpload.tsx:240
    emit index.js:131
    emit index.js:33
    value Uppy.js:256
    value Uppy.js:606
    onChange SingleFileUpload.tsx:287
    onChange SingleFileUpload.tsx:285
    React 16
    render codebase-bridge.tsx:189
    render codebase-bridge.tsx:187
    createDialog uploadWebDAV-dialog.js:150
    showDialog uploadWebDAV-dialog.js:48
    moduleLoaded common-api.js:2664
    requireModule common-api.js:469
    openWebDAVUploadDialog common-api.js:2686
    uploadWebDAVAsset common-api.js:2653
    add form:80
    jQuery 2
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/193153207-5aa1f483-38aa-4128-95ad-5ab7ce2766b2.mp4

**Comment by phuongnq** [comment]
I think this is a UI issue as the upload is completed and the response is as the description of API v2: https://app.swaggerhub.com/apis/craftercms/studio/4.0.1.0#/webdav/uploadItemWebdav

![2022-10-18_17-20](https://user-images.githubusercontent.com/2996543/196404450-d03f31e2-c7e6-43c8-9cec-d2eddfbfb44e.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified fix for Crafter v4. Thank you! Closing this ticket.
