### ISSUE TITLE
[studio-ui] Project policy messages

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5809]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

- When a policy for limiting image sizes/limiting what type of files can be uploaded, is configured, the user will get a message that says it doesn't comply with site policies and can't be uploaded.  Would it be possible to give the user a more explicit message of why the file cannot be uploaded?

- When a file does not comply with the configured project policy, the user is given a message that goes something like: `... requires changes to comply with site policies`.  Please change the message to say `project policies` instead of `site policies` to be consistent with the naming convention (Project policies are configured in the Project Policy Configuration file).

![project-policy-img-too-big copy](https://user-images.githubusercontent.com/25483966/194086880-a40d44f3-614d-4168-b28c-c89ba4e7744b.jpg)

### Describe the solution you'd like

- When a file cannot be uploaded, please give users, if possible, a more explicit message on why the file cannot be uploaded.
- Please change the message in the ui to say `project policies` instead of `site policies` when a file being uploaded does not comply with the configured project policies to be consistent with the naming convention (Project policies are configured in the Project Policy Configuration file).

**Comment by rart** [comment]
We can't currently show anymore information on why the file can't be uploaded as the service doesn't provide it.

**Comment by alhambrav** [comment]
Verified fixed
