### ISSUE TITLE
[studio-ui][studio] `Create Group` form allowing to create a group with empty space as name

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5814]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating a group via Studio UI, the `Create Group` form is allowing to create a group with empty space as name. 

### Steps to reproduce

Steps:

1. Go to `Groups`
2. Click on `Create Group`
3. In `Name` field, just add a space and then save. 
4. See the issue

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/194649966-9758610f-bd7f-489d-8aef-8088fee6ffbe.mp4

**Comment by sumerjabri** [comment]
usernames and group names should be trimmed to remove spaces before and after.

**Comment by sumerjabri** [comment]
Has this been fixed by the new validation framework?

**Comment by Euquimides** [comment]
> Has this been fixed by the new validation framework?

Hi @sumerjabri ! After testing, via Front-End the cited requirements has been applied for both `Create Users` and `Create Groups`. But in the case of the BE, the validation framework is only applying the requirements to `Create Groups`, but it seems not to `Create Users`, as shown in the following requests:

REQUEST 1
```
{
  "email": "test3@example.com",
  "enabled": true,
  "externallyManaged": false,
  "firstName": "hey-test",
  "lastName": "hey-test",
  "password": "test123Qwe!@#",
  "username": "t"
}
```
RESPONSE 1
```
{
    "response": {
        "code": 1,
        "message": "Created",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "user": {
        "id": 5,
        "username": "t",
        "firstName": "hey-test",
        "lastName": "hey-test",
        "externallyManaged": false,
        "email": "test3@example.com",
        "enabled": true
    }
}
```
REQUEST 2
```
{
  "email": "test4@example.com",
  "enabled": true,
  "externallyManaged": false,
  "firstName": "x",
  "lastName": "y",
  "password": "test123Qwe!@#",
  "username": "test4"
}
```
RESPONSE 2
```
{
    "response": {
        "code": 1,
        "message": "Created",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "user": {
        "id": 6,
        "username": "test4",
        "firstName": "x",
        "lastName": "y",
        "externallyManaged": false,
        "email": "test4@example.com",
        "enabled": true
    }
}
```
![Screenshot from 2023-01-13 09-15-17](https://user-images.githubusercontent.com/90878288/212358907-79a67259-6c50-4a64-af24-60b30f1a6995.png)

So in BE, only in the case of `Create Groups` the validation framework is activating, but not in `Create Users`.

**Comment by jmendeza** [comment]
@sumerjabri @Euquimides This should work for groups once this PR is merged: https://github.com/craftercms/studio/pull/3166
For Users, it will be fixed as part of https://github.com/craftersoftware/craftercms/issues/470 as well. Currently WIP

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
