### ISSUE TITLE
[engine] Security Context does not keep authentication on forward

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5818]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

On a `forward` request, `SecurityContextHolder.getContext().getAuthentication()` is null even there is an authenticated session, this cause `authToken` is null.

### Steps to reproduce

Steps:

1. Create a site with authentication such as SAML2
2. Create a filter and URL rewrite request as follows:

```
<filters>
        <filter>
            <script>/scripts/filters/authenticationFilter.groovy</script>
            <mapping>
                <include>/**</include>
            </mapping>
        </filter>
    </filters>
```

```
<urlrewrite>
    <rule>
        <from>^/profile</from>
        <to type="forward" last="true">/sample/account/edit-profile</to>
    </rule>
</urlrewrite>
```

/scripts/filters/authenticationFilter.groovy:

```
println "Requesting URL: " + request.getRequestURI()
println "authToken is: " + authToken
```

3. Publish the site to delivery and login
4. Verified that when accessing root URI `/` it prints the `authToken` NOT null which is CORRECT
5. While accessing page `/profile`, verified that it prints the `authToken` null which is INCORRECT:

```
Requesting URL: /sample/account/edit-profile
authToken is: null
```

**Comment by yacdaniel** [comment]
Verified fixed.
