### ISSUE TITLE
[studio-ui] Searching for an image in the form and then clicking on it causes it to expand instead of getting selected

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5819]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Users instinctively click on the image they want to select, only to have it expand, and then have to exit the modal dialog to try to figure out how to choose the image (clicking the name of the file). It would be much easier if clicking the image selects it. Another mechanism can be used to view it if necessary.

### Steps to reproduce

Steps:

1. Go to a form that lets you choose an image
2. Click on an image
3. See the issue

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/3931908/195426258-f25b9543-1cf9-42a5-baba-136acb1ba8d5.png)
![image](https://user-images.githubusercontent.com/3931908/195426306-e86371bc-b986-4271-a754-a0d5b727c59e.png)

**Comment by rart** [comment]
@jvega190 can we update **only** the browse to handle that click differently? That card component is used in multiple places that shouldn't be affected by this.
