### ISSUE TITLE
[craftercms] The `crafter.sh` script does not terminate the Elasticsearch process in RHEL environments

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5822]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

Running the `shutdown.sh` script, which calls specific methods in the `crafter.sh` script, does not successfully terminate the running Elasticsearch process in RHEL environments running CrafterCMS.

### Steps to reproduce

Steps:

1. Get access to a RHEL environment
2. Startup CrafterCMS using the `startup.sh` script
3. Once CrafterCMS is up and running, run the `shutdown.sh` script
4. Run a `ps -ef | grep java` and see that the Elasticsearch process has not been terminated

**Comment by sumerjabri** [comment]
Fixed by:
https://github.com/craftercms/craftercms/commit/9195e2483634a921bccb3592c97d48766816e787

**Comment by sumerjabri** [comment]
@russdanner I tested on RHEL and it seems to be working now. I'm assigning this ticket to you in case you want to do additional testing.

**Comment by sumerjabri** [comment]
Validated
