### ISSUE TITLE
[engine] Add cache control support to proxy configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5824]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Typically we want a reverse proxy to pass through whatever cache control headers are set by set by the origin.

However, in some cases, it is essential to be able to override cache control headers coming from the source with different settings. 

For example:
In the Crafter Studio preview, it's preferable that: we do not allow the browser to cache page and REST responses, whereas static asset responses may be cached for some (preferably a short amount of time.). By making it possible to override cache control, we can fine-tune the way the Studio Preview instructs the browser on caching preview artifacts and responses.

### Describe the solution you'd like

Please allow overriding the cache headers per proxy at a minimum. A stretch goal is to allow cache headers per proxy per URL regex to match.

The configuration would be:
```
<proxy-config>
   <version>4.0.1</version>
   <servers>
      <server>
         <id>static-assets</id>
         <url>https://example.com</url>
         <patterns>
            <pattern>/static-assets/.*</pattern>
         </patterns>
         <headersToServer>
		<header>
			<name>authorization</name>
			<value>Bearer eyJhbGciOiJQQkVTMi1IUzUxMit...</value>
		</header>
         </headersToServer>
         <headersToClient>
		<header>
			<name>Cache-Control</name>
			<value>no-cache</value>
		</header>
		<header>
			<name>Access-Control-Allow-Origin</name>
			<value>https://example.com</value>
		</header>
		<header>
			<name>Access-Control-Allow-Methods</name>
			<value>GET,PUT</value>
		</header>
         </headersToClient>
      </server>
  </servers>
</proxy-config>
```

The above should also be included in the `sample` file.

**Comment by sumerjabri** [comment]
@phuongnq please prioritize this task today ahead of `Trial` tasks (behind regular support)

**Comment by phuongnq** [comment]
Sent PRs to address this. Note that we need to escape `,` in the header values, for example:

```
<header>
  <name>Cache-Control</name>
  <value>no-cache\, no-store\, max-age=0\, must-revalidate</value>
</header>
<header>
  <name>Access-Control-Allow-Methods</name>
  <value>GET\, PUT</value>
</header>
```

**Comment by russdanner** [comment]
This did not seem to work for me testing against engine as the target server. I tried overriding headers to the client and adding a new header. I did not see either result.
```
<proxy-config>
   <version>4.0.1</version>
   <servers>
      <server>
         <id>static-assets</id>
         <url></url>
         <patterns>
            <pattern>/static-assets/.*</pattern>
         </patterns>
      </server>
      <server>
         <id>graphql</id>
         <url></url>
         <patterns>
            <pattern>/api/1/site/graphql.*</pattern>
         </patterns>
      </server>
      <server>
         <id>engine</id>
         <url></url>
         <patterns>
            <pattern>/api/.*</pattern>
         </patterns>
      </server>
      <server>
         <id>preview</id>
         <url></url>
         <patterns>
            <pattern>.*</pattern>
         </patterns>
        <headersToServer>
		<!--header>
			<name>authorization</name>
			<value>Bearer eyJhbGciOiJQQkVTMi1IUzUxMit...</value>
		</header-->
         </headersToServer>
         <headersToClient>
		<header>
			<name>X-Test</name>
			<value>somevalue</value>
		</header> 
<header>
  <name>Cache-Control</name>
  <value>no-cache\, no-store\, max-age=0\, must-revalidate</value>
</header>
<header>
  <name>Access-Control-Allow-Methods</name>
  <value>GET\, PUT</value>
</header>
         </headersToClient>
      </server>
   </servers>
</proxy-config>
```
https://www.loom.com/share/e146193a67bf4586941e49fedc583dcf

**Comment by phuongnq** [comment]
@russdanner As discussed, the proxy will only work when there is a valid `url`.
In the implementation, we will skip the proxy (use direct access) if it is empty.
Please let me know if we want to support the case to override headers with direct access.

**Comment by russdanner** [comment]
Confirmed
