### ISSUE TITLE
[studio-ui] `Site`, `Groups` and `Users` frontend should include maximum length indication of fields according to backend

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5827]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The description of `Site`, `Groups` and `Users` tables in the DB, includes a maximum length for fields. The `Create User` form in the UI for example, doesn't include this information. The frontend should be synchronized with the backend in this matter.

### Steps to reproduce

Steps:

1. Go to `Projects`, `Groups` or `Users` in the User Dashboard
2. Create a new Project, group or user
3. See the issue

### Screenshots and/or videos

![Screenshot from 2022-10-19 12-17-14](https://user-images.githubusercontent.com/90878288/196772510-bd526b96-f4e8-4d33-ac83-91e148bd6c2a.png)
![Screenshot from 2022-10-19 12-17-44](https://user-images.githubusercontent.com/90878288/196772517-edc71bca-0e40-4811-b0f6-18b0f94d12f9.png)
![Screenshot from 2022-10-19 12-17-59](https://user-images.githubusercontent.com/90878288/196772520-5eb27b75-d57b-45bd-a94e-eb32c20e755e.png)

**Comment by rart** [comment]
Adding all the visible tooltips makes the ui very crowded and its not critical context to fill the form. The constraints will be set in place so the max can't be exceed but max lengths won't be visible in all cases.

**Comment by sumerjabri** [comment]
@rart please have a look here https://heymichellemac.com/design-pattern-character-limits

This designer likes to:
1. Show the character limit right from the start of the interaction
2. Keep the user informed
3. Let the user know when they’ve reached or exceeded the character limit
4. Visualize the character limit for the user

**Comment by Euquimides** [comment]
Hi @jvega190 ! While reviewing this ticket I noticed the next issue that might be related: In case a user is created, if you edit the `First Name` or `Last Name` by pasting a large amount of chars, the UI will break. Please check this out, thanks!

https://user-images.githubusercontent.com/90878288/199831189-66bcab25-8b5b-48c2-b879-de8577eb1908.mp4

**Comment by jvega190** [comment]
@Euquimides the max length updates were missing for the EditUserDialog, those were added in [here](https://github.com/craftercms/craftercms/issues/5814). The PR is already merged. Can you please verify again?

**Comment by Euquimides** [comment]
Hi! Update and rechecked this issue. The problem with the EditUserDialog is fixed. Verified the fix of this ticket for Crafter v4. Closing the ticket.
