### ISSUE TITLE
[studio][studio-ui] Add a sort option to the sidebar path navigator component

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5830]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Today the only sort of sidebar path navigation component is alphabetical.

Some users would like to be able to sort by last update.

### Describe the solution you'd like

- [ ] Add the ability in the UI to pass a sort option when retrieving data for the Path Navigator component.
- [ ] The UI should remember the user's preference for the project
- [x] The backend should respect the sort order requested

**Comment by jmendeza** [comment]
Added sort strategy "lastUpdate" to get children by path API

**Comment by rart** [comment]
@jvega190 please check that the sort strategy is usable from config for Nav and TreeNav components

**Comment by Euquimides** [comment]
Hi! Verified this featured has been added to Crafter v4.1.2. Thank you! Closing this ticket.

**Comment by Euquimides** [comment]
Hi @russdanner @jmendeza and @jvega190 ! Reopened this ticket due to the following issue.

When setting the the `sortStrategy` to `lastUpdate` and the `order` from `DESC` to `ASC` as shown below:
```
              <widget id="craftercms.components.PathNavigatorTree">
                    <configuration>
                        <id>StaticAssets</id>
                        <label>Static Assets</label>
                        <icon id="@mui/icons-material/ImageOutlined"/>
                        <rootPath>/static-assets</rootPath>
                        <sortStrategy>lastUpdate</sortStrategy>
                        <order>DESC</order>
                        <locale>en</locale>
                    </configuration>
                </widget>
```

The sidebar will update, but when opening the section being sorted (in this case `Static Assets`), no item will load. Seems because there is a conflict with the new `/children` API:
```
REQUEST
`{"paths":[{"path":"/static-assets","limit":10,"sortStrategy":"lastUpdate","order":"DESC"}]}`

RESPONSE
`{"response":{"code":1001,"message":"Invalid parameter(s)","remedialAction":"Check API and make sure you're sending the correct parameters","documentationUrl":""},"validationErrors":[{"field":"paths[0].sortStrategy","message":"String doesn't match against whitelist or matches against blacklist"}]}`

https://github.com/craftercms/craftercms/assets/90878288/9a7b6101-efa6-420b-9de3-f0a97c7a8e66

Could you please check this out? Thanks!

**Comment by Euquimides** [comment]
The features added in this ticket lacks documentation. A new ticket for this has been created for following: https://github.com/craftercms/craftercms/issues/6570
