### ISSUE TITLE
[studio-ui] Page-URL field is calculated as 2 required fields

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5837]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

The field requirement helper at the top of the form section when creating a new piece of content miscalculates the number of required fields for the Page URL section, it counts it as 2 required fields.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Navigate to the content type definition for the Article content-type
3. Select the Internal-Name control, and un-check the checkbox that makes the field required
4. Save & close the content type definition
5. Navigate back to the home page
6. Under the Article folder, create new content based on the "Article" content-type
7. In the first section of the page properties, notice that it states "1 of 2 field requirements are invalid"
8. This is an incorrect calculation as we made the section have no required fields, other than the default Page URL being required
9. This can be noticed when creating any other piece of new content, the calculation will always count the Page URL as 2 required fields

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/197780837-90b57a7d-bc1d-4656-9eea-03c46aafb86a.png)

This screenshot shows the section-defaults. You can see that the Page URL has to be calculated as 2 required fields since the form says "3 of 4 requirements are invalid": 
![image](https://user-images.githubusercontent.com/42217570/197781366-e6204e4e-0c04-4840-a90a-b8ea698b7e26.png)

**Comment by sumerjabri** [comment]
The field, URL, has 2 requirements (within the same field itself). This will be better communicated by the new Form Engine.

**Comment by russdanner** [comment]
Consider changing the language to unfulfilled constraints. "Requirements" is causing confusion.

**Comment by rart** [comment]
@russdanner should we allow for internal name to not be required? cc @sumerjabri

**Comment by AndyReiter** [comment]
Confirmed fixed in the latest build:
Version Number:
4.1.0-SNAPSHOT-c1acb7
