### ISSUE TITLE
[studio] Create user API, response status incorrect for user already existing.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#584]
Steps:
1. Run the json for create a new user http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/create-user.html
2. Run again the same json of the step 1.

*Current reponse

Status: 500
{
"status": "Internal server error"
}

*Response in the documentation :
Status: 409

{ "message" : "User already exists" }

Evidence: https://www.screencast.com/t/jponEPLuyA

**Comment by sumerjabri** [comment]
Fixed.
