### ISSUE TITLE
[studio] The `/configuration/content-type/preview_image` API 2 responding HTTP 200 OK on request with invalid param

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5842]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `/configuration/content-type/preview_image` API 2 responding HTTP 200 OK when sending a request with and invalid extra parameter. The correct response should be 400 for invalid request. 

### Steps to reproduce

Steps:

Using a REST API tool:

1. Set up a request for the API, `GET http://localhost:8080/studio/api/2/configuration/content-type/preview_image`.
2. Fill up the request with an extra invalid param, for example: `http://localhost:8080/studio/api/2/configuration/content-type/preview_image?siteId=a1&invalid=invalid&contentTypeId=/page/article`
4. Send the request
5. See the issue

### Screenshots and/or videos

![Screenshot from 2022-10-27 13-21-59](https://user-images.githubusercontent.com/90878288/198379966-af828c3d-0d0e-4178-9a89-e476fb4b73d0.png)

**Comment by phuongnq** [comment]
Per discussed, we agreed that it's ok to send extra parameters in the GET requests' query string and we won't check this in the back end as long as the required parameters are set and valid.

**Comment by Euquimides** [comment]
Hi! Understood. Closing this ticket.
