### ISSUE TITLE
[studio] Quality: Optimize process of upload images for `Content Type Properties` -> `Preview Image`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5844]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Right now when uploading images in `Content Type Properties` -> `Preview Image` the uploaded image is saved in `/config/studio/content-types/page/article` directory of sandbox, filling up the directory with images. Preferably, the uploaded images should be saved in it's own directory such as `/config/studio/content-types/page/article/preview-images`,  for a better order of the directory.

### Steps to reproduce

Steps:

1. Go to a project of your choice. 
2. Go to `Site Tools` -> `Content Types` -> `Content Type Properties`
3. Upload an image to `Preview Image` field.
4. In your console go to `/sandbox/config/studio/content-types/page/article` of the project. 
5. Upload another image to `Preview Image` field.
6. See issue.

**Comment by sumerjabri** [comment]
This will be fixed by Form Engine 2 where the preview image will be a fixed name and type.

CC @rart
