### ISSUE TITLE
[studio-ui] Unable to preview history/prior versions of content in Studio

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5851]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

Studio fails to load previous versions of content when using the Version History form.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Right-click the home-page and select History
3. In the History form, you should see one Version. Click the Eye logo to view that specific version
4. Notice the UI fails to load the content. This happens for all content no matter the size of the history.

### Relevant log output

```shell
https://gist.github.com/AndyReiter/e662371133fd770b8c074d01c288dd51
```

### Screenshots and/or videos

https://www.loom.com/share/48e401af11064b7b8c6eadd3a7bfdcaf

**Comment by russdanner** [comment]
From the logs (for convenience) the error seems to be based on a dependency class not found exception 
```
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/cyberneko/html/LostText
```

**Comment by sumerjabri** [comment]
Can't reproduce in 3.1.29
![image](https://user-images.githubusercontent.com/3931908/220449401-b2a96e8d-bd6a-455b-857b-667b279e15a6.png)
