### ISSUE TITLE
[studio-ui] Moment timezone library returns wrong EST5EDT time from 2023

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5855]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

moment timezone library returns the wrong EST5EDT time from 2023 since the timezone data range is from 2012 to 2022:

```
/studio/static-assets/libs/momentjs/moment-timezone-with-data-2012-2022.min.js
``` 

### Steps to reproduce

Steps for 3.1:

1. Create a site from Editorial BP
2. Schedule the Home page to "06/01/2023 9 am" with the time zone GMT-05
3. Notice that it shows in the Go Live date "06/01/2023 09:00 am" which is incorrect as it should be "06/01/2023 10:00 am"

Alternatively, open the console and test with the following date:

```
var jun = moment('2023-06-01T14:00:00.000Z')
jun.tz('EST5EDT').format('YYYY-MM-DD hh:mm a z');
=> '2023-06-01 09:00 am EST'
```

The output is also incorrect as it should be 
```
var jun = moment('2023-06-01T14:00:00.000Z')
jun.tz('EST5EDT').format('YYYY-MM-DD hh:mm a z');
=> '2023-06-01 10:00 am EDT'
```

### Screenshots and/or videos

![2022-11-08_11-37](https://user-images.githubusercontent.com/2996543/200484429-5d62b5d3-246d-489e-8377-9fb216b2aa26.png)
![2022-11-08_11-37_1](https://user-images.githubusercontent.com/2996543/200484435-34e94a38-f3d7-4627-bcf3-2beb04e65fae.png)

**Comment by nmcneel** [comment]
I rebuilt the moment timezone JS version 0.5.13 that Crafter studio is using with a year range of 2000-2030 from https://github.com/moment/moment-timezone/tree/0.5.13 . Initial smoke test past and I have included it here 
[moment-timezone-with-data-2000-2030.min.js.zip](https://github.com/craftercms/craftercms/files/9973958/moment-timezone-with-data-2000-2030.min.js.zip)
