### ISSUE TITLE
[studio] The API 2 `/dashboard/activity/me` is returning HTTP 500 on requests with nonexistent `siteId` and erroneous values in `actions` params

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5857]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The API 2 `/dashboard/activity/me` is returning HTTP 500 on requests with nonexistent `siteId` param.

### Steps to reproduce

Steps:

Using a REST API tool:

1. Fill up a request for `GET http://localhost:8080/studio/api/2/dashboard/activity/me` (https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/dashboard/getDashboardMyActivities)
2. In the `siteId` parameter add a nonexistent site value. 
4. Send the request.
5. See the issue
6. Now, add a correct `siteId` but an erroneous value for `action` param. For example, `123456` as value. 
7. Send the request
8. See the issue

### Relevant log output

```shell
{
    "response": {
        "code": 1000,
        "message": "Internal system failure",
        "remedialAction": "Contact support",
        "documentationUrl": ""
    }
}
```

**Comment by phuongnq** [comment]
Seem like the API has been fixed in the recent validation update.


![2023-01-16_15-47](https://user-images.githubusercontent.com/2996543/212635911-aafe9628-451a-4a79-96ce-aed375c4ea08.png)

![2023-01-16_15-48](https://user-images.githubusercontent.com/2996543/212635976-27a0d647-d028-462d-8bf3-3254b75dfa2f.png)

**Comment by Euquimides** [comment]
Hi! Indeed after updated and testing, the validation framework update has been applied to this API. So the issue is fixed in this ticket. Fix verified for Crafter v4.
