### ISSUE TITLE
[studio] Bring API Add User to Group to compliance

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#586]
Please review all returned values and adjust the implementation to match the API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/add-user.html

Presently, it's returning 201 or 500 (201 is also wrong, must be 200. It's missing all the other returns.

**Comment by sumerjabri** [comment]
Please look at the User APIs to see the return at the bottom and the change from `result.status` to `result.message` etc.

**Comment by sumerjabri** [comment]
Please also remove all `;` from groovy files where they're not needed.

**Comment by dejan-brkic** [comment]
Fixed
