### ISSUE TITLE
[studio][studio-ui] Component and Shared Content Node Selectors show incorrect dialog

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5862]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The Shared content and Component node selectors browse dialog that is shown for embedded components is incorrect. It seems to be showing a file browse dialog instead of a content item browser. It also shows an upload button that allows users to upload arbitrary items into paths reserved for content items and results in items being unable to be deleted.

Also, when a file has been uploaded to a components/pages folder, there are some issues with the file:

1. When retrieving item it has a previewUrl, causingthe UI to try to preview it when clicked (shows a 404 page in preview)

2. If you already uploaded a file and you want to delete it, the item only has a couple of actions and can't be deleted.

The `write-content` service should be restricted to avoid such uploads in those folders, or return the correct set of props and actions for the items.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Navigate to Components and edit the Header Component
3. Scroll down to the Social Media Links section and Delete the Social Media Networks widget
4. Click add and then Browse existing Social media widgets
5. Notice that the dialogue is browsing for a file instead of a content item browse
6. Also see that there is an option to Upload. When you upload a file into this dialogue, you're unable to delete or view it in studio.

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

https://www.youtube.com/watch?v=dKVGPEWFGPI&ab_channel=TheKingswayDigitalCompany

**Comment by jvega190** [comment]
@sumerjabri @jmendeza UI is now updated not to show the upload button when not browsing files. Though we were noticing that when a file is already uploaded at least two things happen:
1. When retrieving item it has a `previewUrl`, causingthe UI to try to preview it when clicked (shows a 404 page in preview)
2. If you already uploaded a file and you want to delete it, the item only has a couple of actions and can't be deleted.

@jmendeza suggested that the `write-content` service can be restricted to avoid such uploads in those folders.

**Comment by sumerjabri** [comment]
@jmendeza let's meet and discuss this before we tackle it.

**Comment by jvega190** [comment]
UI part is merged, pending backend details with @jmendeza

**Comment by phuongnq** [comment]
I sent PR for the backend to validate the assets' path before uploading.
Regarding the front end, it seems like the option to upload while selecting components is visible again. @jvega190 

![2023-01-18_11-45](https://user-images.githubusercontent.com/2996543/213092461-8114dbc0-b7cc-4f54-8f28-9dd7cf41d711.png)

**Comment by sumerjabri** [comment]
@jvega190 BE is done

**Comment by AndyReiter** [comment]
Confirmed fixed in the latest build of 4.0-SNAPSHOT.
