### ISSUE TITLE
[studio-ui] sass files should be viewable and editable via Crafter Studio

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5865]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Sass files are not editable.

### Describe the solution you'd like

Sass files should be viewable and editable via Crafter Studio

**Comment by jvega190** [comment]
@rart scss/sass files are previewable, but available actions returned in item don't include edit

**Comment by russdanner** [comment]
Confiirmed
