### ISSUE TITLE
Make configuring an RTE easier

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5866]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

RTEs are very powerful, and in Crafter Studio, our RTEs can include style sheets and style options (syle select, format select, etc) that make it very easy for authors to apply styles to text, links, images and more.

The trouble is that setting up RTEs is a technical task that developers forget to do when creating sites. If it were easier to do it would be done more fully, more often.

### Describe the solution you'd like

Make RTEs easier to set up and configure
- Ship with great defaults per blueprint
- Move today's configuration in ui.xml to an Advanced mode and link tinyMCEs documentation.
- Create some kind of editor to make editing the most common elements of the configuration simple

**Comment by sumerjabri** [comment]
Completed in 4.0
