### ISSUE TITLE
[studio-ui] Allow `renderComponentCollection` inside repeats

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5869]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The `renderComponentCollection` macro doesn't support the `$index` prop required by XB for fields inside repeats

### Describe the solution you'd like

Add `$index`

**Comment by jvega190** [comment]
`renderComponentCollection` already has `indexCarryover` and `fieldCarryover` to support the case.
