### ISSUE TITLE
Javascript SDK's ContentInstance interface does not expose the orderDefault_f field used by pages

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#5871]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The Javascript SDK's ContentInstance interface does not expose the orderDefault_f field used by pages.  This is needed when manually constructing navigation structures.

The only way to access this field is to manually extract it from the DescriptorResponse object instead.

Ideally, when I retrieve a content item via the getItem rest call, I would like to be able to convert it directly into a ContentInstance object that is directly usable by my codebase.

It may make sense to define interfaces for Component and Page that extend ContentInstance.  Further, it may also be desirable to allow client libraries to define their own interfaces that extend Component and Page, and  their own parser/constructor that will construct these objects while still making use of the convenient work inside parseDescriptor.  This would cut down on boilerplate code in client codebases substantially.

See the "steps to reproduce" section for more details and examples of our workaround that we would like to retire.

### Steps to reproduce

We have worked around this issue by creating base objects that require DescriptorResponse objects instead of ContentInstance objects. 

Regular usage, however, results in having to manipulate both ContentInstance and DescriptorResponse ojbects interchangeably. This should not be necessary and also results in excessive use of parseDescriptor which is probably expensive.

Base component:
```ts
import { DescriptorResponse } from '@craftercms/models';

export class CrafterComponent {
  constructor(descriptorResponse: DescriptorResponse) {
    this.path = descriptorResponse.url;
    if (descriptorResponse.descriptorDom.component) {
      this.type = descriptorResponse.descriptorDom.component['content-type'];
      this.createdDate = CrafterComponent.crafterDateParse(descriptorResponse.descriptorDom.component.createdDate);
      this.modifiedDate = CrafterComponent.crafterDateParse(
        descriptorResponse.descriptorDom.component.lastModifiedDate,
      );
    } else {
      this.type = descriptorResponse.descriptorDom.page['content-type'];
      this.createdDate = CrafterComponent.crafterDateParse(descriptorResponse.descriptorDom.page.createdDate);
      this.modifiedDate = CrafterComponent.crafterDateParse(descriptorResponse.descriptorDom.page.lastModifiedDate);
    }
  }

  path!: string;
  type!: string;
  createdDate!: Date;
  modifiedDate!: Date;

  private static pad(str: string): string {
    if (str.length === 1) {
      return `0${str}`;
    }
    return str;
  }

  // work around DescriptorResponse date format bug
  private static crafterDateParse(str: string): Date {
    const datePart = str.substring(0, str.indexOf('T'));
    const parts = datePart.split('-');
    if (parts[1].length === 1 || parts[2].length === 1) {
      const fixedDatePart = `${parts[0]}-${CrafterComponent.pad(parts[1])}-${CrafterComponent.pad(parts[2])}`;
      const newDtStr = str.replace(datePart, fixedDatePart);
      return new Date(newDtStr);
    }
    return new Date(str);
  }
}
```

Base page:
```ts
import { DescriptorResponse } from '@craftercms/models';
import { CrafterComponent } from '~/modules/crafter_module/entities/component.entity';

export class CrafterPage extends CrafterComponent {
  constructor(descriptorResponse: DescriptorResponse) {
    super(descriptorResponse);
    this.navInclude = descriptorResponse.descriptorDom.page.placeInNav === 'true';
    this.navOrder = descriptorResponse.descriptorDom.page.orderDefault_f;
    this.navLabel = descriptorResponse.descriptorDom.page.navLabel;
  }

  navLabel?: string;
  navInclude!: boolean;
  navOrder!: number;
}
```

A common type:
```ts
import { parseDescriptor } from '@craftercms/content';
import { DescriptorResponse } from '@craftercms/models';

import { CrafterComponent } from '~/modules/crafter_module/entities/component.entity';

export class FeaturedImage extends CrafterComponent {
  constructor(descriptorResponse: DescriptorResponse) {
    super(descriptorResponse);
    const contentInstance = parseDescriptor(descriptorResponse);
    this.imageUrl500x500 = contentInstance.image_s;
  }

  imageUrl500x500!: string;
}

```

Some usage examples:
```ts
  async readContentItem(path: string): Promise<unknown> {
    const descriptorResponse = await this.crafterService.readContentItem("myCrafterSite", path);
    logger.debug(`descriptorResponse: ${JSON.stringify(descriptorResponse, null, ' ')}`);
    const contentInstance = parseDescriptor(descriptorResponse);
    switch (contentInstance.craftercms.contentTypeId) {
      case '/page/landingpage':
        return new LandingPage(descriptorResponse);
      case '/component/featuredimage':
        return new FeaturedImage(descriptorResponse);
      default:
        throw new Error(`Unsupported type: ${contentInstance.craftercms.contentTypeId}`);
    }
  }
```

**Comment by rart** [comment]
## 4.0.3

### All packages
- Switching sdk versioning to follow CrafterCMS release version 

### @craftercms/content
- Update `parseProps` (internally used by `parseDescriptor`) to include `orderDefault_f` (parsed as `orderInNav`) in the resulting ContentInstance.
- Update `parseProps` and `parseDescriptor` options to receive `systemPropMap`, `ignoredProps`, `systemProps` to be used during parsing.
  - Note: modifying these props will require you to _open_ the `ContentInstance` interface and extend it accordingly.
- Improve `parseDescriptor` signatures definitions
- Parse values of `orderInNav` and `disabled` to their target data types (float and boolean, respectively).
- Export `extractContent` and `extractChildren` functions.
- Export the default `systemPropMap`, `ignoredProps`, `systemProps`.
