### ISSUE TITLE
[studio-ui] Sidebar fails when content type folder does not match content type name in configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5873]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Sidebar navigator components remain in skeletonized mode due to an exception in the UI that occurs when the UI cannot locate and load a content type at the location described by the configuration.
- This can occur if someone renames an in-project content type folder
- This can occur if someone creates a plugin with a content type but does not properly place the content type within the plugin.

### Steps to reproduce

Steps:

1. Created a site based on editorial
2. rename and commit the following folder`config/studio/content-types/page/article` to `config/studio/content-types/page/article-x`
3. refresh the studio UI
4. See the issue

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos
Example of what happens in the UI and the console
<img width="1298" alt="Screen Shot 2022-11-17 at 12 57 36 PM" src="https://user-images.githubusercontent.com/169432/202756981-3fd45e69-3e99-4684-95a0-413bf076d783.png">

Example of a content type that has the issue
<img width="1331" alt="Screen Shot 2022-11-17 at 1 51 32 PM" src="https://user-images.githubusercontent.com/169432/202756074-0fa3fb11-2554-4fc2-9bbc-740121383c6a.png">

**Comment by sumerjabri** [comment]
@russdanner what's the expected behavior here? Someone/something broke the content model of the system, how and when will the system report issues/react to this?

**Comment by sumerjabri** [comment]
### Thoughts:
* On sync DB from Git:
  * If a content type has been deleted, emit that event and log it with WARN and in the logs inform that any content item of that type may be broken now
  * If a content type has been added, emit that event and log it with INFO
* On failing to load the Sidebar due to a broken/missing content type
  * Indicate the failure to the end-user but don't fail to load the Sidebar (indicate in the cabinet that failure)

**Comment by jvega190** [comment]
When getting the configuration of the renamed content type, the API responses a 200 with a null content

![Screenshot from 2022-12-08 10-24-01](https://user-images.githubusercontent.com/18267471/206505145-29cca40f-69ab-4b5b-88ec-411de577c396.png)

When there's an error response, the UI does show an error message

![Screenshot from 2022-12-08 10-26-42](https://user-images.githubusercontent.com/18267471/206506280-37cc84b9-bb86-4382-b543-e7e25cbd23c8.png)

**Comment by phuongnq** [comment]
I created PR to:

* Respond 404 if the configuration is not found (content is null)
* Change the log level to WARN for delete operation and INFO for create operation. Sample of output:

```
[INFO] 2023-01-04T16:50:38,982 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] | Sync the database with the repository in site 'ed' starting at commit ID '0f0a6d7954c35ad7aaf0243e8d3b6aa028b58295' 
[INFO] 2023-01-04T16:50:38,982 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'CREATE' path '/config/studio/content-types/page/article-x/config.xml' 
[INFO] 2023-01-04T16:50:38,982 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'CREATE' path '/config/studio/content-types/page/article-x/controller.groovy' 
[INFO] 2023-01-04T16:50:38,982 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'CREATE' path '/config/studio/content-types/page/article-x/form-definition.xml' 
[INFO] 2023-01-04T16:50:38,983 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'CREATE' path '/config/studio/content-types/page/article-x/page-article.png' 
[WARN] 2023-01-04T16:50:38,983 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'DELETE' path '/config/studio/content-types/page/article/config.xml' 
[WARN] 2023-01-04T16:50:38,983 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'DELETE' path '/config/studio/content-types/page/article/controller.groovy' 
[WARN] 2023-01-04T16:50:38,983 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'DELETE' path '/config/studio/content-types/page/article/form-definition.xml' 
[WARN] 2023-01-04T16:50:38,983 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] |   Site 'ed' Operation 'DELETE' path '/config/studio/content-types/page/article/page-article.png' 
[INFO] 2023-01-04T16:50:39,151 [studio.clockTaskExecutor-13] [site.SiteServiceImpl] | Done syncing the database with the git repository for site 'ed' starting at commit ID '0f0a6d7954c35ad7aaf0243e8d3b6aa028b58295' with a final result of 'true'
```

**Comment by russdanner** [comment]
confirmed
