### ISSUE TITLE
[docs] Add instructions for using AWS service roles

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5874]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Some users would like AWS access from CrafterCMS without using access/secret keys, which can be done by using roles.  We currently do not have instructions on how this is done.

### Describe the solution you'd like

Add instructions for using AWS service roles

**Comment by sumerjabri** [comment]
https://docs.craftercms.org/en/4.0/site-administrators/studio/blob-stores.html?highlight=aws%20roles#using-aws-service-roles
