### ISSUE TITLE
Upgrade to Groovy 4

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5876]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

CrafterCMS is presently using Groovy v3, and the language is now on v4.

### Describe the solution you'd like

Evaluate and upgrade if possible to v4.

**Comment by phuongnq** [comment]
@sumerjabri Spring Boot 2.x has a dependency on Groovy 3 (https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.11/spring-boot-dependencies-2.7.11.pom) which has the groupId `org.codehaus.groovy`
In Groovy 4, the groupId of the maven coordinates for Groovy have changed from `org.codehaus.groovy` to `org.apache.groovy`.
For that reason, we need to upgrade Groovy 4 along with the upgrade of Spring to 6/Spring Boot to 3.

**Comment by sumerjabri** [comment]
Depends on https://github.com/craftercms/craftercms/issues/5977
