### ISSUE TITLE
[studio] -Upgrade Manager- Project name not being rendered correctly in Navigation Menu for BPs of Marketplace

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5877]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The name of a project created with a BP via Marketplace, is not being rendered correctly in the `Navigation Menu`. This seems to be happening only with BPs of the Marketplace, not default BPs. 

### Steps to reproduce

Steps:

1. Create a new project using a BP from the Marketplace, for example Video Center or Wordify.
2. Click on `Navigation Menu`
3. See the issue

### Screenshots and/or videos

![Screenshot from 2022-11-30 11-10-57](https://user-images.githubusercontent.com/90878288/204880863-6118aa07-091d-41cf-aa4a-1c7cbfeb1b95.png)
![Screenshot from 2022-11-30 11-21-22](https://user-images.githubusercontent.com/90878288/204880868-fd30fded-227d-4312-ad43-833edde3e1c6.png)

**Comment by jvega190** [comment]
@jmendeza The issue is that UM is replacing the CDATA for the title field in the ui.xml, causing the title to render incorrectly

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified fix for Crafter v4. Thank you! Closing this ticket.
