### ISSUE TITLE
[studio-ui] Option to sort assets by Name/Recently uploaded

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5879]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When editing a page/component with an image, try to choose an image from the assets folder.
There is no option to sort assets by Name/Recently uploaded.
![Screenshot from 2022-12-02 10-32-33](https://user-images.githubusercontent.com/2996543/205208980-bdaa042a-73a1-4f30-a406-f9056abc6370.png)

### Describe the solution you'd like

Option to sort assets by Name/Recently uploaded

**Comment by phuongnq** [comment]
cc @russdanner

**Comment by phuongnq** [comment]
verified

**Comment by rart** [comment]
@jvega190 fix visuals

![image](https://user-images.githubusercontent.com/3928341/209105126-d1580120-20a7-494c-b16b-8ef82cc3e913.png)

![image](https://user-images.githubusercontent.com/3928341/209105402-27510acf-51d0-4982-be4a-107163cd79df.png)
