### ISSUE TITLE
[studio] Update Get All Users with Range Capabilities

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#588]
Please update to have start/end per API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users.html

and this API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-groups-per-site.html

and this API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-users.html

**Comment by dejan-brkic** [comment]
PR #584
