### ISSUE TITLE
[sdk-js] The Experience Builder SDK missing required dependencies

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#5880]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When adding the experience builder SDK dependencies to our react project, we are prompted to resolve an unmatched dependency on a crafter component that has not been published to npmjs.com. This should be resolved so that a build can be completed successfully.

If a fully-released version of the experience-builder codebase is available that would be preferable to running on a release candidate as well.

### Steps to reproduce

Add @craftercms/experience-builder to your project
Observe output

### Relevant log output

```shell
tony@Io:/Volumes/Projects/xxx/repositories/cms-e4s/sources/react-app git:(preview-app-security-fixes*) $ yarn add @craftercms/experience-builder
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@craftercms/studio-ui" that matches "1.0.0-rc.4"
? Please choose a version of "@craftercms/studio-ui" from this list: (Use arrow keys)
❯ 1.0.0-rc.3 
  1.0.0-rc.2 
  1.0.0-rc.1 
  1.0.0-rc 
  1.0.0-beta.2 
  1.0.0-beta.1 
  1.0.0-alpha.5 
  1.0.0-alpha.4 
  1.0.0-alpha.3 
  1.0.0-alpha.2 
  1.0.0-alpha.1 
warning @craftercms/experience-builder > @craftercms/search > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

```
```


### Screenshots and/or videos

_No response_

**Comment by rart** [comment]
Fixed.

`@craftercms/experience-builder` rc2 ended up pointing to the "future" version of `@craftercms/studio-ui`, which is now the current version that the latest package depends on. When using rc2, safest bet would be to use studio-ui@rc3.

When using CrafterCMS 4.0.3+, one should use XB@rc3 onwards.
