### ISSUE TITLE
[studio] Link remote git usernames with Studio users

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5885]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, working remotely and pulling things to the project via git doesn't link actions taken by a git user to a Studio user. This has several consequences, as an example, it complicates publishing and diminishes the utility of dashboards by disabling the continuity of concisely seeing your work on my recent activity.

### Describe the solution you'd like

Allow linking remote usernames to Studio users

**Comment by sumerjabri** [comment]
Ping me to discuss.
