### ISSUE TITLE
[studio] Write the output of the studio backup process to a log file

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5887]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, `crafter.sh backup` is outputting only to the console however, it would be helpful to administrators to capture this output in a log file.

### Describe the solution you'd like

Write the output of `crafter.sh backup` to a file.

**Comment by sumerjabri** [comment]
If env var is set to where to log, `cecho` a copy to that.

**Comment by sumerjabri** [comment]
Fixed in 45c34ed0969d09055f1c5be5f3dd2b5a701ad992 in craftercms.

The logfile is set with the command: `CRAFTERCMS_SCRIPT_LOG`

The `crafter.sh` command also documents this if invoked without any params.

**Comment by russdanner** [comment]
Tested. This is the output I got:
```
[96m------------------------------------------------------------------------
[0m[96mStarting backup
[0m[96m------------------------------------------------------------------------
[0m[96m------------------------------------------------------------------------
[0m[96mBacking up embedded DB
[0m[96m------------------------------------------------------------------------
[0m[96m------------------------------------------------------------------------
[0m[96mBacking up git repos
[0m[96m------------------------------------------------------------------------
[0m[96m------------------------------------------------------------------------
[0m[96mBacking up elasticsearch indexes
[0m[96m------------------------------------------------------------------------
[0m[96mAdding elasticsearch indexes
[0m[96m------------------------------------------------------------------------
[0m[96mBacking up Deployer data
[0m[96m------------------------------------------------------------------------
[0m[96m------------------------------------------------------------------------
[0m[96mBacking up SSH data
[0m[96m------------------------------------------------------------------------
[0m[96m------------------------------------------------------------------------
[0m[96mPackaging everything
[0m[96m------------------------------------------------------------------------
[0m[94m> Backup completed and saved to /Users/rdanner/crafter-installs/next/craftercms/crafter-authoring/backups/test.2023-02-09-15-55-12.tar.gz
```

Details outputted by the commands to not seem to get caught. Is that expected?

**Comment by sumerjabri** [comment]
This needs documentation when completed (for 3.1 and 4.0) @alhambrav

**Comment by sumerjabri** [comment]
@yacdaniel this changes a few things and requires full testing including backup and restore with logging and without logging for 3.1 and 4.0 to make sure it can backup and restore correctly.

**Comment by Euquimides** [comment]
Hi @sumerjabri ! Added a PR https://github.com/craftercms/craftercms/pull/5936 to this ticket. Just some details that I wanted to ask:

1. Shouldn't the user expect the output of the logs to also be printed in console, maybe use `tee` command or another command?
2. The default location for the logs is CRAFTER_LOGS_DIR to avoid any potential issues if the user changes the variable to a location that doesn't exist and then start Crafter.

**Comment by sumerjabri** [comment]
After thinking about this some more, I don't like the idea of adding this to `set env`. This is a mechanism for some clients/users to have the script run silently and log/review logs afterward as part of automation.

If we were to enhance this in the future, we can:
- Output to a known log location, much like `tomcat` or `deployer`
- Add this to log rotation and other parts of the system when deployed (including AMIs built, Gradle jobs, etc)

I'm against setenv in general, this would become just another log like other logs.

**Comment by sumerjabri** [comment]
Doc is here: https://docs.craftercms.org/en/4.0/system-administrators/activities/logging.html#crafter-sh-script-logging

**Comment by russdanner** [comment]
Confirmed
