### ISSUE TITLE
[studio-ui] Increase the maximum amount of user's and group's displayed in the Group/User Forms

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5897]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When attempting to add users to a group via the group membership dialogue, the displayed available users and searchable users cap at 100 users. This makes the addition of users to specific groups difficult when there are more than 100 users and groups.

See screenshot for examples:
![image](https://user-images.githubusercontent.com/42217570/209903482-387b0d85-9430-4912-b0b0-9a2d427a9fc8.png)

![image](https://user-images.githubusercontent.com/42217570/209903486-3500f267-b5e9-40d4-9f30-6c65897895e9.png)

### Describe the solution you'd like

Either make the limit adjustable based on specific client needs or have no limit at all.

**Comment by rart** [comment]
Let's aim for infinite scroll and server side filtering

**Comment by AndyReiter** [comment]
Confirmed fixed in latest build of 4.0-SNAPSHOT.
