### ISSUE TITLE
[blueprints] Update all blueprints to have correctly padded dates

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5898]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating a site based on the Editorial Blueprint in 4.0.2E, the content is created with the default createDates that do not follow the proper formats as they're not padded.

For example the createDate of the content in the editorial blueprint is:
`<createdDate>2017-1-31T16:18:14.000Z</createdDate>
<createdDate_dt>2017-1-31T16:18:14.000Z</createdDate_dt>`

The proper format would have the months be padded with a 0 and look like this: 
`<createdDate>2017-01-31T16:18:14.000Z</createdDate>
<createdDate_dt>2017-01-31T16:18:14.000Z</createdDate_dt>`

### Steps to reproduce

Steps:

1. Create a site based on the Editorial Blueprint
2. Cat the index.xml of the home page located at /Crafter-home/data/repos/<your-site>/sandbox/site/website/index.xml
3. See that the createDate's format is incorrect.

**Comment by sumerjabri** [comment]
Updated built-in blueprint and all marketplace blueprints.

**Comment by AndyReiter** [comment]
Confirmed fixed in the latest build of 4.0-SNAPSHOT.
