### ISSUE TITLE
CRAFTERCMS-1757: Cannot preview file page content

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#59]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: 1) Create a page content type with a proper page template
2) Update config.xml of the content type in Repository to set 'content-as-folder' to false
3) Create a content using the content type
4) Click on the content to see preview

The preview fails to load. :
----------
Original JIRA Comments:
only moving this out because it's specific to 1 use case.
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1757
----------

**Comment by vestrada** [comment]
Closed
