### ISSUE TITLE
[studio] Update user API, different response when the user is updated.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#590]
steps:
1. Authentication
2. Execute the json for create a user.
3. Execute the json for update the user created (http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/update-user.html)

*Current Response:
Status: 200
Location: http://localhost:8080/studio/api/1/services/api/1/user/get?username=testing1

{
"status": "OK"
}

Evidence: https://www.screencast.com/t/PPnVuHZpCF

*Response in the documentation:
Status: 200
Location: .../user/get.json?username=:username
{ "message" : "OK" }

**Comment by sumerjabri** [comment]
Fixed.
