### ISSUE TITLE
[studio-ui] Check user entry when creating a new Group in Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5902]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current Studio UI for creating a new group allows invalid characters and once you save those changes, it displays an error dialog like below:
![Screen Shot 2023-01-09 at 5 56 00 PM](https://user-images.githubusercontent.com/25483966/211881187-ec748d1c-239d-45e9-a81e-3123bea2af99.png)

### Describe the solution you'd like

It would be nice to do something like what is done when creating a new user, where, if an invalid character is entered, the input box turns red.  Also, I was thinking it would be helpful if a list of valid characters is listed beneath the Group name input box, just like when we're creating a new project.

![Screen Shot 2023-01-09 at 5 58 10 PM](https://user-images.githubusercontent.com/25483966/211881822-2929dd30-02b0-408f-908a-10612dbba1bc.png)

Here is how it looks like when an invalid character is entered in the `Username` field when creating a new user:
![Screen Shot 2023-01-09 at 5 57 17 PM](https://user-images.githubusercontent.com/25483966/211881488-84bca3f3-496b-4c5d-8519-01c7790b534d.png)

Here's how it looks like when you're creating a new project, note the `Project ID` field:
![Screen Shot 2023-01-11 at 12 55 17 PM](https://user-images.githubusercontent.com/25483966/211887713-882c515a-d615-457b-9470-97046f9bafb1.png)

**Comment by rart** [comment]
@jvega190 the group name rules are: `^[a-zA-Z0-9_\\.\\-]{3,512}$` (i.e. backend's `Validator.GROUP_NAME`)

**Comment by alhambrav** [comment]
Verified fixed
