### ISSUE TITLE
[studio] incorrect internal-name field extracted on save when embedded content data source is used

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5905]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

Crafter Studio extracts internal-name value on content items using an XPATH that includes all child nodes `//internal-name` fashion.

In some cases, Studio finds the first embedded component's internal name rather than the parent object's internal name.  

When the "proper" conditions are present the behavior can be observed in the page navigation on the sidebar. The internal name of the embedded component "replaces" the internal name of the parent object.

Conditions to required to induce the behavior:
In the top-level content object's XML, the field with the embedded content must be located above/before the top-level content object's internal-name field.

Example:

```
<page> 
  <features_o>
      <items>
          <item>
               ...
               <component>
                    <internal-name>This name will be extracted for the parent</internal-name>
                    ...
               </component>
       </items>
  </features_o>
  <internal-name>This field value will be ignored on save</internal-name>  
</page>
```

### Steps to reproduce

Steps:

1. In editorial configure featured components on the home page to use embedded components
2. Using the form, remove the existing references to objects in features from the home page
3. Add a new feature (embedded) via the form
4. Save the feature form.
5. Save the home page (parent) form.
6. Note that everything works correctly.
7. Open the homepage XML /site/website/index.xml
8. Move the internal-name tag of the home page below the features_o tag as shown above
9. Commit the content to the sandbox
10. Via studio open the homepage form, then the feature form
11. Note that everything looks correct on read.
12. Change the feature's internal name
13. Save the feature.
14. Save the parent home page
15. Note that the sidebar now shows the feature's internal name for the home page object.

### Relevant log output

```shell
N/A
```

**Comment by russdanner** [comment]
Looking at the write API it appears the content sent to the server is "correct"
This indicates to me that the issue is extraction logic on the back end:

Write API payload that presents the issue
```
<page>
	<content-type>/page/home</content-type>
	<display-template>/templates/web/pages/home.ftl</display-template>
	<no-template-required/>
	<merge-strategy>inherit-levels</merge-strategy>
	<objectGroupId>1f75</objectGroupId>
	<objectId>1f75bf80-0a21-d3d6-faea-020e2a041db1</objectId>
	<title_t>foo 2</title_t>
	<features_title_t>fff</features_title_t>
	<disabled>false</disabled>
	<header_o item-list="true"/>
	<left_rail_o item-list="true"/>
	<features_o item-list="true">	<item datasource="testFeature" inline="true">	<key>d0cbc220-fa8a-916b-1c29-50faad76c096</key>
	<value>This will break. I will usurp!</value>
<component id="d0cbc220-fa8a-916b-1c29-50faad76c096">
	<content-type>/component/feature</content-type>
	<display-template>/templates/web/components/feature.ftl</display-template>
	<no-template-required/>
	<merge-strategy>inherit-levels</merge-strategy>
	<objectGroupId>d0cb</objectGroupId>
	<objectId>d0cbc220-fa8a-916b-1c29-50faad76c096</objectId>
	<internal-name>This will break. I will usurp!</internal-name>
	<title_t>Feature Title</title_t>
	<disabled>false</disabled>
	<body_html>&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.&lt;/p&gt;</body_html>
	<file-name>d0cbc220-fa8a-916b-1c29-50faad76c096.xml</file-name>
	<folder-name/>
	<icon_s>fa-closed-captioning far</icon_s>
	<createdDate>2023-01-13T19:03:48.202Z</createdDate>
	<createdDate_dt>2023-01-13T19:03:48.202Z</createdDate_dt>
	<lastModifiedDate>2023-01-13T23:50:52.663Z</lastModifiedDate>
	<lastModifiedDate_dt>2023-01-13T23:50:52.663Z</lastModifiedDate_dt>
</component>
	</item></features_o>
	<internal-name>foo 1</internal-name>
	<hero_image_s/>
	<file-name>index.xml</file-name>
	<folder-name>foo</folder-name>
	<hero_title_html>&lt;p&gt;dddd&lt;/p&gt;</hero_title_html>
	<hero_text_html>&lt;p&gt;ddd&lt;/p&gt;</hero_text_html>
	<createdDate>2023-01-13T19:03:02.569Z</createdDate>
	<createdDate_dt>2023-01-13T19:03:02.569Z</createdDate_dt>
	<lastModifiedDate>2023-01-13T23:50:38.787Z</lastModifiedDate>
	<lastModifiedDate_dt>2023-01-13T23:50:38.787Z</lastModifiedDate_dt>
</page>
```

**Comment by russdanner** [comment]
This class and xpath expression looks like a likey suspect
https://github.com/craftercms/studio/blob/bf0e164b37b6831696408597c8eb0e7809273682/src/main/java/org/craftercms/studio/impl/v2/service/item/internal/ItemServiceInternalImpl.java#L63

This expression is used to extract a "label"
https://github.com/craftercms/studio/blob/bf0e164b37b6831696408597c8eb0e7809273682/src/main/java/org/craftercms/studio/impl/v2/service/item/internal/ItemServiceInternalImpl.java#L398

**Comment by sumerjabri** [comment]
We need to use a more precise xpath. Currently seems to be a global search match first.

**Comment by russdanner** [comment]
Please also review the following expressions for the same issue and correct as appropriate
```
    public final static String CONTENT_TYPE = "//content-type";
    public final static String DISABLED = "//disabled";
    public final static String LOCALE_CODE = "//locale-code";
```

**Comment by russdanner** [comment]
Confirmed

**Comment by phuongnq** [comment]
This could be a front-end issue since `_getPageName` function returns the first `internal-name` element of three:
![2023-02-10_12-09](https://user-images.githubusercontent.com/2996543/218006148-741af449-c4be-4436-a429-09285ab6476b.png)

**Comment by russdanner** [comment]
This issue has been re-identified on rename and copy operation workflows:
We msut always extract the "top most" internal name

ContentServiceImpl.java
```
Lines 1135-1142
                if (movePath.endsWith(DmConstants.XML_PATTERN)) {
                    InputStream movedContentStream = getContent(siteId, movePath);
                    movedDocument = ContentUtils.convertStreamToXml(movedContentStream);
                    if (movedDocument != null) {
                        Element root = movedDocument.getRootElement();
                        updateContentOnMove(root, moveFileName, movePathMap.fileFolder, movePathMap.modifier);
                        targetLabel = root.selectSingleNode(format("//%s", ELM_INTERNAL_NAME)).getText();
                    }
                }
```
Same pattern in helpers — updates / reads the wrong node whenever there are multiple matches
ContentServiceImpl.java
```
Lines 1525-1529
    private void updateSingleDocumentNode(final Element root, final String nodeName, final String value) {
        Node node = root.selectSingleNode(format("//%s", nodeName));
        if (node != null) {
            node.setText(value);
        }
    }
```
ContentServiceImpl.java
```
Lines 1546-1551
        if (StringUtils.isNotEmpty(modifier)) {
            Node internalNameNode = root.selectSingleNode("//" + ELM_INTERNAL_NAME);
            if (internalNameNode != null) {
                String internalNameValue = internalNameNode.getText().replaceFirst(INTERNAL_NAME_MODIFIER_PATTERN, "");
                internalNameNode.setText(format(INTERNAL_NAME_MODIFIER_FORMAT, internalNameValue, modifier));
            }
        }
```
(and similarly in updateContentOnCopy around 1576–1580.)

3. Contrast: item persistence after write uses a scoped path

ItemServiceInternalImpl uses a root-scoped XPath for the same field:
ItemServiceInternalImpl.java
```
Lines 53-54
    public final static String INTERNAL_NAME = "/*[1]/internal-name";
```

**Comment by russdanner** [comment]
Confirmed
