### ISSUE TITLE
[engine] Support configuring by URL patterns  headers on response

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5909]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

`Cache-Control` headers are extremely useful for indicating cache TTLs to CDNs and browsers on certain requests. Right now there's no way in Engine to configure this header or any others for specific URLs.

### Describe the solution you'd like

Provide a way to configure URL Ant-style patterns/header mappings in Engine. My recommendation is to add something like this to Engine's `site-config.xml`:

```
<headerMappings>
   <mapping>
      <urlPattern>/products/**</urlPattern>
      <headers>
         <header>
            <name>Cache-Control</name>
            <value>max-age=60, s-maxage=300</value>
         </header>
      <headers>
   </mapping>
   <mapping>
      <urlPattern>*.pdf</urlPattern>
      <headers>
         <header>
            <name>X-Crafter-Document</name>
            <value>true</value>
         </header>
      <headers>
   </mapping>
</headerMappings>
```

Have these configuration be read by a servlet filter that tries to match the request against these patterns, and sets the header if there's a match.

**Comment by phuongnq** [comment]
Sample usage correction as following:

```
<headerMappings>
        <mapping>
            <urlPattern>/products/**</urlPattern>
            <headers>
                <header>
                    <name>Cache-Control</name>
                    <value>max-age=60\, s-maxage=300</value>
                </header>
            </headers>
        </mapping>
        <mapping>
            <urlPattern>/**/*.pdf</urlPattern>
            <headers>
                <header>
                    <name>X-Crafter-Document</name>
                    <value>true</value>
                </header>
            </headers>
        </mapping>
    </headerMappings>
```

* Escape `\,` character for the configuration
* Update any pdf file URL pattern to `/**/*.pdf`

**Comment by Euquimides** [comment]
Hi @phuongnq ! I've been doing some tests on the new configuration for the URL pattern headers, and I noticed that in the case, for example, of the URL pattern that includes a file extension such as `/**/*.pdf` or `/**/*.jpg` the `Cache-Control` value is not changing in the headers. But adding a new value, it is recognized. Please check this out, thanks! 

CONFIGURATION:
```
 <headerMappings>
        <mapping>
            <urlPattern>/**/*.pdf</urlPattern>
            <headers>
                <header>
                    <name>Cache-Control</name>
                    <value>max-age=60\, s-maxage=300</value>
                </header>
                <header>
                    <name>TestHeader</name>
                    <value>success</value>
                </header>
            </headers>
        </mapping>
    </headerMappings>
```
![Screenshot from 2023-02-07 16-17-00](https://user-images.githubusercontent.com/90878288/217379577-ff969acf-fae2-454b-b7e9-cd617b44fdfe.png)

**Comment by phuongnq** [comment]
Hi @Euquimides 

I believe this is the current behavior for static assets. See: https://github.com/craftercms/engine/blob/develop/src/main/java/org/craftercms/engine/controller/StaticAssetsRequestHandler.java#L54

```
if (disableCaching) {
                // fully disable cache in the browser
                setCacheControl(CacheControl.noStore());
            } else {
                // make the browser check for changes before using a cached version
                setCacheControl(CacheControl.noCache());
            }
```

* In studio: Since caching is disabled, the header is `no-store`
* In engine: Cache-Control header is `no-cache`

And we use the `Etag` header to determine if the asset has been modified or not.
So even we add a `Cache-Control` header configuration for static assets, it will be modified with either `no-store` in Studio or `no-cache` in Engine.
CC @sumerjabri @avasquez614

**Comment by sumerjabri** [comment]
@phuongnq @Euquimides I changed the code to allow caching, see https://github.com/craftercms/engine/commit/9575268ae9ae55c57c35ef5adcdaf039694baf3d

@Euquimides please retest.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this ticket. Feature request has been added correctly to Crafter v4. Thank you! Waiting for merge of Doc PR to close this ticket.

**Comment by Euquimides** [comment]
The PR has been merged and the info about URL Patterns header configuration has been added to the docs. Closing this ticket.
