### ISSUE TITLE
[studio] Add support for upgrading from 3.1.29 to 4.0.3

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5912]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

CrafterCMS 3.1.29 is released and should be a viable upgrade path.

### Describe the solution you'd like

Add support for upgrading from 3.1.29 to 4.0.3.

**Comment by Euquimides** [comment]
Hi! Feature verified as implemented. Thank you! Closing this ticket.
