### ISSUE TITLE
Improve Studio application startup time when upgrading sites

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5914]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Today Studio startup time can be impacted by housekeeping activities run per site. The more sites that exist, the longer these jobs can take. This process prevents the application server from accepting requests for monitoring/status/health checks as well as other potential administrative functions.  

### Describe the solution you'd like

Refactor startup to move housekeeping activities outside of the web application startup and if necessary lock Studio access to administrators only until complete.

Consider adding a state for `project`s as `upgrading`, so the users can't get into a project/site, but an admin can do admin work.

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6545
