### ISSUE TITLE
[studio] Viewing page history results in an error

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5916]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

When a user attempts to view a specific version of a piece of content in the history, the ui throws an error and does not load the content.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Edit the home page a few times to build up the page's history
3. Right click the page and select "History"
4. In the Actions column, select the eyeball to view one of the versions from the history you just built up
5. Notice the error the UI throws and the version is not displayed.

### Relevant log output

```shell
https://gist.github.com/AndyReiter/7b22f7d51ed4a9daf7486bd08dfa0d3b
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/215541742-3a4f7a1d-9796-4e48-973d-906ed057da55.png)

**Comment by russdanner** [comment]
This appears to be missing JAR @sumerjabri

**Comment by sumerjabri** [comment]
Tested with 3.1.29 CE, 3.1.29 EE, and 3.1.30-SNAPSHOT build from source.
