### ISSUE TITLE
[studio][studio-ui] UI not handling correctly missing configuration files in `AWS Profiles`, `Engine URL Rewrite Configuration`, `Box Profiles`, `Blob Stores`, `WebDav Profiles` and `Asset Processing` 

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5919]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Trying to access the following configuration files: `AWS Profiles`, `Engine URL Rewrite Configuration`, `Box Profiles`, `Blob Stores`, `WebDav Profiles` and `Asset Processing` in `Project Tools -> Configuration`, will result in the UI not loading the XML configuration editor and a HTTP 404 for `GET | http://localhost:8080/studio/api/2/configuration/get_configuration`.

If the user creates the cited XML configuration files in the respective site sandbox directory, the UI will render correctly the configuration editor. There might be two ways to fix this issue:

1. Via the front-end adding an exception for these missing files.
2. Via back-end, creating an empty xml file associated with these configurations.

### Steps to reproduce

Steps:

1. Create a new project or site.
2. Go to `Project Tools -> Configuration -> WebDav Profiles` for example.
3. See the issue

### Relevant log output

```shell
[ERROR] 2023-01-30T14:22:50,031 [http-nio-8080-exec-9] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/configuration/get_configuration?environment=default&module=studio&path=webdav%2Fwebdav.xml&siteId=a1' failed with response 'ApiResponse{code=7000, message='Content not found', remedialAction='Check that path 'webdav/webdav.xml' is correct and it exists in site 'a1'', documentationUrl=''}' 
org.craftercms.studio.api.v1.exception.ContentNotFoundException: Configuration not found for site 'a1', module 'studio', path 'webdav/webdav.xml', environment 'default'
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/215587491-7cbbbf14-e0e2-43fa-9e25-95f79f70e76e.mp4

**Comment by rart** [comment]
@jvega190 add error handling to api calls, dismiss the loading state and show error state or dialog as appropriate

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
