### ISSUE TITLE
[studio] Build API: Validate Session

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#592]
Please build the API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/security/validate-session.html

**Comment by dejan-brkic** [comment]
Done

PR https://github.com/craftercms/studio/pull/612

**Comment by dejan-brkic** [comment]
Reopening found big problem

**Comment by dejan-brkic** [comment]
Done

UI:
https://github.com/craftercms/studio2-ui/pull/329

Backend:
https://github.com/craftercms/studio/pull/614
