### ISSUE TITLE
Warn user if bulk publish operation finds no eligible files under submitted path

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5921]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Users would like the system to indicate that no files are calculated for publishing if they request a publish and no files under the given path are eligible.

### Describe the solution you'd like

Inform the user during the submission.

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
