### ISSUE TITLE
[studio] Allow search characters in Studio search

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5925]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Permitted and required special characters used for authoring search are denied. These chars include: `"` and `.`

Please allow `"` and `.` (do we need to allow anything else?)

### Steps to reproduce

Steps:

1. Go to an Editorial site
2. Click on the search magnifying glass
3. Type "romantic-pic.jpg"
4. See the issue

Try searching for `"romantic"`, same thing.

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/3931908/217344119-37b30611-aafb-4c32-9d71-689154f9a59b.png)

**Comment by jmendeza** [comment]
We will also allow search keywords to include star (`*`) and underscore (`_`)

**Comment by sumerjabri** [comment]
@jmendeza and `-` (hyphen) too, please.
