### ISSUE TITLE
[engine] Setting CORS configurations for accessControlAllowHeaders does not appear to have an effect

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5926]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Steps to reproduce

Steps:

1. Create a site 
2. Configure CORS headers as follows
```
    <cors>
        <enable>true</enable>
        <accessControlMaxAge>3600</accessControlMaxAge>
        <accessControlAllowOrigin>*</accessControlAllowOrigin>
        <accessControlAllowMethods>*</accessControlAllowMethods>
        <accessControlAllowHeaders>X-Custom-Header, Content-Type</accessControlAllowHeaders>
        <accessControlAllowCredentials>true</accessControlAllowCredentials>
    </cors>
 ```
3. Attempt to set X-Custom-Heder or Content-Type and note that they are not sent.

**Comment by russdanner** [comment]
Work around:

1. In scripts/filters create a filter groovy called CustomHeaders.groovy
 ```
response.addHeader("Access-Control-Allow-Headers", "Content-Type")

filterChain.doFilter(request, response)
```

2. configure the filter to run every request in the Engine Project Config
``` 
<site> 
  <version>4.0.1</version> 
  
    <cors>
        <enable>true</enable>
        
        <accessControlMaxAge>3600</accessControlMaxAge>
        <accessControlAllowOrigin>*</accessControlAllowOrigin>
        <accessControlAllowMethods>*</accessControlAllowMethods>
        <accessControlAllowHeaders>X-Custom-Header, Upgrade-Insecure-Requests, Content-Type</accessControlAllowHeaders>
        <accessControlAllowCredentials>true</accessControlAllowCredentials>
    </cors>
    
    <filters>
        <filter>
            <script>/scripts/filters/CustomHeaders.groovy</script>
            <mapping>
                <include>/**</include>
                <exclude>/static-assets/**</exclude>
            </mapping>
        </filter>
    </filters>
</site>
```

**Comment by phuongnq** [comment]
@russdanner `accessControlAllowHeaders` is the list of headers which is set to the following method: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedHeaders(java.util.List)

> Set the list of headers that a pre-flight request can list as allowed for use during an actual request. 

I believe we need to escape the comma with `\,` here to read the configuration as a list.

Tested with the configuration:

```
<cors>
        <enable>true</enable>
        <accessControlMaxAge>3600</accessControlMaxAge>
        <accessControlAllowOrigin>*</accessControlAllowOrigin>
        <accessControlAllowMethods>*</accessControlAllowMethods>
        <accessControlAllowHeaders>X-Custom-Header\, Content-Type</accessControlAllowHeaders>
        <accessControlAllowCredentials>true</accessControlAllowCredentials>
    </cors>
```

And it works fine when we set both or one header:

* Request with only `Content-Type` header:

```
fetch('http://localhost:9080?crafterSite=ed', {
    headers: { 'Content-Type': 'application/json' }
}).then(data => data.json());
```

![2023-02-08_15-38_1](https://user-images.githubusercontent.com/2996543/217479865-4d69ce64-116f-434a-a081-63dc8facec3d.png)

* Request with both headers:
```
fetch('http://localhost:9080?crafterSite=ed', {
    headers: { 
        'X-Custom-Header': 'test',
        'Content-Type': 'application/json' 
    }
}).then(data => data.json());
```

![2023-02-08_15-38](https://user-images.githubusercontent.com/2996543/217479982-d68e518d-7c64-458a-905d-eccb7c7b9903.png)

**Comment by sumerjabri** [comment]
CC @avasquez614
