### ISSUE TITLE
[studio-ui] Create an empty configuration file if none are present

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5927]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Right now, when entering `Project Tools -> Configuration`, an error message will appear out of the box for missing configuration files.

Past versions of CrafterCMS dealt with this by showing a blank slate in the Configuration Editor. Also, notice that `Engine Project Configuration` includes an empty file in which the user can add his/her configuration.

### Describe the solution you'd like

Create an empty configuration file if none are present like in prior versions.

**Comment by rart** [comment]
Use similar approach to "edit controller", @jvega190

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this ticket. Feature request correctly added to Crafter v4. Thank you! Closing this ticket.
