### ISSUE TITLE
[studio-ui] Switch session checking from old to new API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#593]
Please switch the existing Studio code that uses validate-token to check for session validity to use the new API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/security/validate-session.html

Please note that validate-token is now only used to check forgot password tokens.

**Comment by sumerjabri** [comment]
Please also note that a non-200 return means the user is to be considered logged out. We can discuss further if needed.

**Comment by jvega-crafter** [comment]
Done, service return handlers will be worked on this ticket https://github.com/craftercms/craftercms/issues/594

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/293
