### ISSUE TITLE
Dashboard "Recently Published" dashlet not displaying items on initial publish

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#5932]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

After performing the initial publish of a project in Studio, nothing is listed in the `Recently Published` dashlet in the Dashboard

### Steps to reproduce

Steps:

1. Create a project using any of the out of the box blueprints
2. Click on `Project Tools` -> `Publishing` then click on the `Publish Entire Project` button under the `Publish on Demand` section and follow the instructions on the dialog
3. Open the Dashboard
4. Scroll to the `Recently Published` dashlet and notice that it is empty
![Screenshot 2023-02-10 at 11 31 54 AM](https://user-images.githubusercontent.com/25483966/218145057-d61dc12c-a8d7-434c-ac0f-3b74b02ea646.png)

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
