### ISSUE TITLE
[engine] Result from elasticsearch controller show ? for special characters

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5934]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The result from the elasticsearch controller show as `?` for special characters such as em-dash (`—`)

### Steps to reproduce

Steps:

1. Create a new site with Video Center BP
2. Browsing to the video "Gödel's Incompleteness Theorem"
3. Notice that the character `ö` is not displayed correctly
4. Alternatively, update a title to have an em-dash character —
5. Notice that the em-dash character is displayed as a question mark `?`

### Screenshots and/or videos

![2023-02-13_09-37](https://user-images.githubusercontent.com/2996543/218358116-2cfc7823-b224-40ba-bab3-96b3df5c7cb8.png)

**Comment by phuongnq** [comment]
The writer here is not using the UTF-8: https://github.com/craftercms/engine/blob/develop/src/main/java/org/craftercms/engine/controller/rest/SiteElasticsearchController.java#L64

Function `getWriter`: 

> Returns a PrintWriter object that can send character text to the client. The PrintWriter uses the character encoding returned by getCharacterEncoding. If the response's character encoding has not been specified as described in getCharacterEncoding (i.e., the method just returns the default value ISO-8859-1), getWriter updates it to ISO-8859-1.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
