### ISSUE TITLE
[studio-ui] Correct style for Video Transcode form control

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5935]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Some possible corrections for the current Video Transcode form control style:

* Button style seems not to align with other form control (has no padding, etc)
* There is no word break if the URLs are long to

### Steps to reproduce

Steps:

1. Create a new project from 'Editorial' BP
2. Setup Home page to have Video Transcode such as:

Add to form-definition.xml field and datasource
```
				<field>
					<type>transcoded-video-picker</type>
					<id>video_o</id>
					<iceId></iceId>
					<title>Video</title>
					<description></description>
					<defaultValue></defaultValue>
					<help></help>
					<properties>
						<property>
							<name>videoManager</name>
							<value>uploadAndTranscodeVideo</value>
							<type>datasource:transcoded-video</type>
						</property>
						<property>
							<name>readonly</name>
							<value></value>
							<type>boolean</type>
						</property>
					</properties>
					<constraints>
						<constraint>
							<name>required</name>
							<value><![CDATA[]]></value>
							<type>boolean</type>
						</constraint>
					</constraints>
				</field>
...
				<datasource>
					<type>video-S3-transcoding</type>
					<id>uploadAndTranscodeVideo</id>
					<title>Upload And Transcode Video</title>
					<interface>transcoded-video</interface>
					<properties>
						<property>
							<name>inputProfileId</name>
							<value>mediaconvert-default</value>
								<type>undefined</type>
						</property>
						<property>
							<name>outputProfileId</name>
							<value>s3-default</value>
								<type>undefined</type>
						</property>
					</properties>
				</datasource>
```

Update content with the above content type to have the following data:

```
	<video_o>
		<item>
			<url>/remote-assets/s3/s3-default/v1/static-assets/videos/compressed/this_is_a_test_video_url_with_underscore_a_b_c_d1.m3u8</url>
		</item>
		<item>
			<url>/remote-assets/s3/s3-default/v1/static-assets/videos/compressed/this_is_a_test_video_url_with_underscore_a_b_c_d2.m3u8</url>
		</item>
		<item>
			<url>/remote-assets/s3/s3-default/v1/static-assets/videos/compressed/this_is_a_test_video_url_with_underscore_a_b_c_d3.m3u8</url>
		</item>
	</video_o>
```

3. Open the content edit form
4. Notice that the buttons for video transcode control has an old style and the video box does not have word wrap.

### Screenshots and/or videos

![2023-02-13_10-06](https://user-images.githubusercontent.com/2996543/218361452-f8007dba-05d5-4162-9efa-6ca2ea7ab8ea.png)

**Comment by phuongnq** [comment]
@russdanner FYI

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
