### ISSUE TITLE
[studio] Make text files editable in Studio

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5939]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

YAML files are not editable because the backend says they are octet streams. If the MIME-type was `text/yaml` it would be editable.

### Describe the solution you'd like

Specifically:
- Please have Studio set the MIME-Type to `text/yaml` for YAML files and add "edit" as one of the available actions depending on permissions of course.
- Please do the same for `CSV` files.

Generally:
Please also do the same for:
`text/*`
and these items:
``` js
/^application\/(x-httpd-php|rtf|xhtml\+xml|xml|json|ld\+json|javascript|x-groovy|x-sh|x-yaml|ld+json|x-csh)$/
```

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
