### ISSUE TITLE
[studio-ui] Build a log-back-in dialog for expired sessions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#594]
Please build a modal dialog box that would pop-up whenever the user is timed-out to help the user log back in quickly without losing where they were in their workflow.

You'll know if a user is logged out via the API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/security/validate-session.html which is invoked currently on a period by Studio UI.

Ping me if you need help/detail.

**Comment by vestrada** [comment]
studio-ui - master -PR: https://github.com/craftercms/studio2-ui/pull/334

**Comment by sumerjabri** [comment]
The button labels aren't correct. Please change them to:
"Sign back in" "I'm done, signout"

Here is what i'm getting:

![screen shot 2017-04-06 at 2 07 54 pm](https://cloud.githubusercontent.com/assets/3931908/24770464/08c4372a-1ad8-11e7-81f1-3f54a5809fc7.png)

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/342
