### ISSUE TITLE
[studio][engine] Add install specific script for crafter-setenv.sh

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5941]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Admins currently configure settings in crafter-setenv.sh but this file can change from version to version during upgrades.
Admins would like a place to put their changes that is isolated from the platforms' changes.,

### Describe the solution you'd like

Have our crafter-setenv.sh call an empty install-specific crafter-setenv.sh that contains the administrators' customizations/overrides.

**Comment by sumerjabri** [comment]
@russdanner per our conversation. Environment variables can be used to override any of our params and param defaults without the need of changing the actual `crafter-setenv.sh` file.

**Comment by sumerjabri** [comment]
We may implement a `folder.d` approach that holds shell scripts to be executed in the future when we see clear requirements. For now, users can run scripts before/after they call our scripts. Parameters are overridden by environment vars.
