### ISSUE TITLE
[studio] Children by path API fails when the path contains spaces

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5945]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`{{baseUrl}}/content/children_by_path` fails with paths that contain spaces.

URL encoding doesn't make a difference.

### Steps to reproduce

Steps:

1. Invoke children_by_path with a post body like:
```json
{ "path": "/static-assets/folder 1", "siteId": "editorial" }
```

2. See error
```json
{
    "response": {
        "code": 1001,
        "message": "Invalid parameter(s)",
        "remedialAction": "Check API and make sure you're sending the correct parameters",
        "documentationUrl": ""
    },
    "validationErrors": [
        {
            "field": "path",
            "message": "Value is not a valid URI"
        }
    ]
}
```

**Comment by sumerjabri** [comment]
@jmendeza we should also consider things like `[-_ ]` because paths can have these and they're legal. Let's also track other APIs similar.

CC @yacdaniel @Euquimides

**Comment by Euquimides** [comment]
Hi @sumerjabri and @jmendeza ! The APIs:

- POST [/groups](https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/groups/createGroup) --> Is not accepting spaces in the group `name`
- POST [/users](https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/users/createUser) --> Is not accepting spaces and underscore in the `username`

This might have an impact in other APIs that requires params related with group `name` and `username`. Will update this comment in case I found other APIs with the same issue.

**Comment by Euquimides** [comment]
Hi @sumerjabri and @jmendeza ! The APIs:

- POST [/groups](https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/groups/createGroup) --> Is not accepting spaces in the group `name`
- POST [/users](https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/users/createUser) --> Is not accepting spaces and underscore in the `username`

This might have an impact in other APIs that requires params related with group `name` and `username`. 

In general, APIs that include the `path` parameter, are responding with HTTP 400 with a URI validation error in the response body. 

Will update this comment in case I found other APIs with the same issue.

**Comment by sumerjabri** [comment]
@jmendeza and I discussed things and we have agreed on a list of allowed chars for create/update and another for read.

**Comment by sumerjabri** [comment]
@alhambrav please update the docs to include the new configuration mechanism for validations
@Euquimides please make sure this is inline with validations

**Comment by sumerjabri** [comment]
@jmendeza please unassign yourself if this is done from your end

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.

@sumerjabri , since we added a new option in Global Configuration for changing the default regex pattern for Users or Groups, should we consider an update to the UI, so that the fields match the changes in the regex? Right now seems that User and Group forms have their own regex in UI, maybe we need them to synchronize? Thank you for your answer!

**Comment by sumerjabri** [comment]
@Euquimides please file a separate ticket for us to unify the regex used for checking in the UI and backend.

**Comment by Euquimides** [comment]
Hi @sumerjabri ! This is the ticket for tracking the changes to UI: https://github.com/craftercms/craftercms/issues/5974

**Comment by alhambrav** [comment]
Here's the docs for overriding the validations regex: 
https://docs.craftercms.org/en/4.0/system-administrators/studio/studio-configuration-overrides.html#validations-regex
