### ISSUE TITLE
[studio-ui] Indicate in the `Create Project` form that underscore is also allowed for `Project ID`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5948]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In the `Create Project` form, the `Project ID` fields indicates some requirements for `siteId` that says: `Max length: 50 characters, consisting of: lowercase letters, numbers & dash (-).` It should indicate that `_` underscore is also valid, since right now `siteId` is accepting underscore.

### Describe the solution you'd like

Indicate in the `Create Project` form that `_` underscore is also allowed for `Project ID`

**Comment by sumerjabri** [comment]
We don't want to support `_` in siteId, the docs are correct to prevent it.
