### ISSUE TITLE
[studio] Update range query parameters

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#596]
Please update range query parameters to use the new syntax as spec'd.
The update is to:
- Switch the parameter `end` to become `number`
- `number` will indicate the number of items to return

Affected APIs:
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users-per-site.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-groups.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-groups-per-site.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-users.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/audit/get-audit-log.html

**Comment by sumerjabri** [comment]
Please make sure the Total field in the response is always populated to indicate the total resultset size based on the query you're sent without regard to query range. Per our convo.

**Comment by dejan-brkic** [comment]
Updated all
PR #586
