### ISSUE TITLE
[studio-ui] Publishing queue - 'All' filter shouldn't uncheck options once they're all already checked.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5961]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In Publishing queue, when all filters are check, and you click on the 'All' filter again, it unchecks the filters. The filter behavior should only be to select all filters.
Also, 'all' filter should be the default selection

### Steps to reproduce

Steps:

1. Go to Publishing queque
2. Click on the 'All' filter
3. Click again
4. See the issue

**Comment by rart** [comment]
Verified
