### ISSUE TITLE
[studio] Update group API wrong property for group description

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5966]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When calling the update group API (https://app.swaggerhub.com/apis/craftercms/studio/4.0.3.0#/groups/updateGroup), the description field should be 'desc', but it is 'groupDescription'. That causes a mismatch between the GET and PATCH APIs (and it used to be 'desc').

### Steps to reproduce

Steps:

1. Make a request to this [API](https://app.swaggerhub.com/apis/craftercms/studio/4.0.3.0#/groups/updateGroup) using 'id' and 'desc'
2. See the issue.

**Comment by sumerjabri** [comment]
@jmendeza please remove the "name" property from the PATCH (update methods)

**Comment by jvega190** [comment]
@jmendeza please also add the "id" prop in the PATCH for users

**Comment by jvega190** [comment]
Verified fixed
