### ISSUE TITLE
[studio] Add the permission `get_publishing_queue` to authors

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5968]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Authors can't see the publishing queue.

### Describe the solution you'd like

Add the permission `get_publishing_queue` to authors using UM.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Feature added to Crafter v4. Thank you! Closing this ticket.
