### ISSUE TITLE
[studio-ui] RTE should have a list of attributes that is kept on paste post-processing by default

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5971]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When pasting a Word document with a link, the `<a>` tag is kept but the `href` attribute is cleaned up. This makes the `<a>` looks incorrect. 

### Describe the solution you'd like

Have a list of attributes that contains at least the `href` attribute which is kept when performing the default paste post-process cleanup.

**Comment by sumerjabri** [comment]
@russdanner let me know if @rart should try to tackle this for 4.0.3 or not. We do need guidance as to what to keep after the paste.

**Comment by sumerjabri** [comment]
@rart please keep the `href`

**Comment by phuongnq** [comment]
verified!
