### ISSUE TITLE
[studio-ui] Restrict drop-down menu dimensions in `Audit` -> `Filter by Operations`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5973]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The drop-down menu in `Audit` -> `Filter by Operations` is resizing according to the amount of operations selected for filtering. The drop-down size should be restricted for more aesthetically pleasing interface.

### Steps to reproduce

Steps:

1. Go to `Audit` in Global Menu
2. Click on the menu of `Operations` tab to open `Filter by Operations`
3. Click in the different operations that appear until reaching the screen's max width.
4. Click on the `Filter by Operations` drop-down button again.
5. See the issue

### Screenshots and/or videos

![Screenshot from 2023-03-03 14-08-48](https://user-images.githubusercontent.com/90878288/222816709-5b1320df-1b5b-4f11-9f13-76bec6eb7a5b.png)
![Screenshot from 2023-03-03 14-09-45](https://user-images.githubusercontent.com/90878288/222816798-2226864d-8146-45b5-885d-d47285c544de.png)
![Screenshot from 2023-03-03 14-10-27](https://user-images.githubusercontent.com/90878288/222816954-62155ee3-f7bf-4a50-b012-b491387c8dd5.png)
![Screenshot from 2023-03-03 14-09-13](https://user-images.githubusercontent.com/90878288/222816712-e62c9db7-ea35-404c-bda4-78e9577a4e96.png)

**Comment by rart** [comment]
@jvega190 the popovers shouldn't grow.
This case may be solves by avoiding the drop-down to grow, but check the rest of pop ups.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
