### ISSUE TITLE
[studio-ui] Update `Users` and `Groups` form to adapt to new validation framework regex properties

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5974]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

You are now able to change the default regex of the validation framework for group names and usernames according to your requirements, via Global Configuration properties. At this moment, the Groups and Users forms have their own regex for naming, we should adapt it to the default regex of the validation framework and the new properties of Global Configuration.

### Steps to reproduce

Steps:

1. Go to `Users` in Global menu.
2. Click on `Create User`
3. In the `username` field type `user-user`. The default regex accepts `-` but the UI is marking it as not allowed. You can see the difference by sending a request to POST [/users](https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/users/createUser).
4. See the issue

### Screenshots and/or videos

![Screenshot from 2023-03-03 16-24-31](https://user-images.githubusercontent.com/90878288/222842430-5aebb8af-0b18-4de2-bc04-78165947bf84.png)

**Comment by sumerjabri** [comment]
The front end and back end should use the same regex/configuration.

**Comment by alhambrav** [comment]
Here's some more notes to add... 
I am trying to create a user and for some reason I am getting an error that I have invalid parameters....  I couldn't tell from the UI what the invalid parameter was so  I checked the logs and it seems like my error is my username is not long enough...

<img width="1472" alt="Screenshot 2023-03-28 at 9 27 12 AM" src="https://user-images.githubusercontent.com/25483966/228285227-8647f682-21a5-40b7-8b32-eaab842c2726.png">


```
[ERROR] 2023-03-28T09:27:02,193 [http-nio-8080-exec-2] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/users' failed with response 'ApiResponse{code=1001, message='Invalid parameter(s)', remedialAction='Check API and make sure you're sending the correct parameters', documentationUrl=''}'
org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.craftercms.studio.model.rest.ResultOne<org.craftercms.studio.api.v2.dal.User> org.craftercms.studio.controller.rest.v2.UsersController.createUser(org.craftercms.studio.model.rest.CreateUserRequest) throws org.craftercms.studio.api.v1.exception.security.UserAlreadyExistsException,org.craftercms.studio.api.v1.exception.ServiceLayerException,org.craftercms.studio.api.v1.exception.security.AuthenticationException: [Field error in object 'createUserRequest' on field 'username': rejected value [jane]; codes [Size.createUserRequest.username,Size.username,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [createUserRequest.username,username]; arguments []; default message [username],255,5]; default message [size must be between 5 and 255]]
```
 The error dialog with the bug looks a little scary when one gets it while working in the UI.  It would be nice to display that message in the UI instead of the user having to check the logs to see which parameter was invalid...  Or not enabling the Submit button if one of the parameters does not meet the system's criteria if possible?

**Comment by rart** [comment]
@sumerjabri we need a way of communicating the _current_ regexes to the UI. FYI we must consider differences in regex engines here.

@jvega190 for now, just update the expressions to match the default while we work the back.

**Comment by sumerjabri** [comment]
@Euquimides please validate that they match right now. I'll then push this ticket out to a future release where we add a backend API for the UI to pull the rules.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The UI is now matching the default regex in the backend. Fix verified for Crafter v4. Thank you! Closing this ticket.
