### ISSUE TITLE
[studio-ui] Audit - Timestamp only sorts ASC

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5979]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When sorting the timestamp column in Audit Management, it sorts in ASC order, but if you click again, it doesn't sort in DESC

### Steps to reproduce

Steps:

1. Go to Audit Management screen
2. Click on timestamp to sort by that column
3. Sort again
4. See the issue

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
