### ISSUE TITLE
[UM] Support version 20 in permission-mappings.xml for 3.1.x < 3.1.23 

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5982]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Right now `permissions-mappings.xml` version 20 is not supported for upgrades in versions 3.1.x < 3.1.23

### Describe the solution you'd like

Review differences between versions 16 and 20 in `permissions-mappings.xml` and add support in Upgrade Manager

**Comment by jmendeza** [comment]
Version 20 is actually 4.0. Added an UM entry point so it can be updated to the new version scheme and continue to be upgraded properly

**Comment by jvega190** [comment]
Verified fixed
