### ISSUE TITLE
[studio] ElasticSearch returns HTTP 500 with chars of 1000+ chars

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Searching in Studio with a query of 1000 chars or more will return HTTP 500 and an ElasticSearch error. 

### Steps to reproduce

Steps:

1. Go to a project of your choice.
2. Go to Search and make a query that includes 1000+ chars.
3. See the issue.

### Relevant log output

```shell
[ERROR] 2023-03-08T16:12:31,556 [http-nio-8080-exec-7] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/search/search.json?siteId=3cl9q6sd7e' failed with response 'ApiResponse{code=1000, message='Internal system failure: Error executing search in Elasticsearch', remedialAction='Contact support', documentationUrl=''}' 
org.craftercms.studio.api.v1.exception.ServiceLayerException: Error executing search in Elasticsearch
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/90878288/223862970-a8067f22-969f-4ef7-bbec-95c4e13d469a.png)

**Comment by sumerjabri** [comment]
Fixed during the OpenSearch upgrade.
