### ISSUE TITLE
[studio-ui] `My Recent Activity` in `Dashboard` not updating the total of `Assets` correctly

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5989]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In `Dashboard` when you filter for `Assets`, it will show the items to show as total instead of the total items. 

### Steps to reproduce

Steps:

1. Go to a project of your choice. 
2. Make a first publish.
3. Upload some items.
4. Publish those items. 
5. Go to `Dashboard` -> `My Recent Activity`.
6. In the filter option, select `Assets`.
7. Change the number of items to show.
8. See the issue.

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/224426946-0820f06b-75e4-4c20-b0ba-8fcbc591b538.mp4

**Comment by sumerjabri** [comment]
4.1.0 replaces the dashboards. Will keep this for later review.

**Comment by sumerjabri** [comment]
Will close this ticket since we now have new dashboards.
