### ISSUE TITLE
[social][profile] Options `socialRequired` and `profileRequired` not working when building

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5992]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The options `socialRequired` and `profileRequired` seems not to be working when building Crafter to include social and profile. The only options working are `crafter.social` and `crafter.profile`.

### Steps to reproduce

Steps:

1. Clone CrafterCMS repository.
2. Run `./gradlew build deploy -PsocialRequired=true -PprofileRequired=true` 
3. Start Crafter
4. Try accessing `HOST:PORT/crafter-social-admin` for example
5. See issue

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.

**Comment by sumerjabri** [comment]
@Euquimides I also applied this to 4.0.x now.

**Comment by Euquimides** [comment]
@sumerjabri updated and tested. Verified that the fix has been applied to 4.0.x. Thank you!
