### ISSUE TITLE
[studio-ui] Adding new repeating group member caused pre-filled data for RTE fields

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5993]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When adding a new repeating group that has an RTE in each element, the new repeating group should be empty but got pre-filled with some content of other existing repeating group members.

### Steps to reproduce

Steps:

1. Create a new site from the following BP: https://github.com/russdanner/bug-repeat-group1
2. Edit the test or create a new content of content type `/component/standardfileupdates`  with one of the attached content (data.zip has 3 test cases)
3. Open the form editor and click "Add Another" for the Repeating Group to insert a new repeating group in the middle.
4. Notice that the new one is pre-filled with some content

[data.zip](https://github.com/craftercms/craftercms/files/11015079/data.zip)

This seems to happen when the RTE fields (fields with `_html` postfix) have line breaks such as:
```
<description_html>&lt;h2&gt;Standard file holiday processing&lt;/h2&gt;
			&lt;p&gt;This standard.&lt;/p&gt;</description_html>
```

Or have no HTML tag at all:
```
<description_html>1111111111</description_html>
```

If I remove the line break:
```
<description_html>&lt;h2&gt;Standard file holiday processing&lt;/h2&gt;&lt;p&gt;This standard.&lt;/p&gt;</description_html>
```
=> The issue is fixed for the first click to "Add Another", but the second one will have an issue again (`description_html` is pre-filled with content). And when I save the content, the line break is restored again when viewing the XML document.

### Screenshots and/or videos

![repeating_group](https://user-images.githubusercontent.com/2996543/226270332-88d7a6e7-947e-406b-a6df-44af3cbf3ff4.png)

**Comment by yacdaniel** [comment]
Verified fixed.
