### ISSUE TITLE
[studio-ui] Project tools publish does not allow the selection of Live target when Staging target is enabled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5996]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In 4.0.2, the project tools publish does not allow the selection of Live target when Staging target is enabled.

### Steps to reproduce

Steps:

1. Configure staging project settings
2. Go to publishing via project tools
3. Publish by commit id or path and attempt to select Live, this will not work
4. See the issue

**Comment by russdanner** [comment]
4.0.3-SNAPSHOT does not appear to exhibit this issue.

**Comment by sumerjabri** [comment]
Fixed in 4.0.3. Will patch older releases as needed.

**Comment by sumerjabri** [comment]
CC @yacdaniel this should be tested in the future by setting up staging and trying this.
