### ISSUE TITLE
CRAFTERCMS-1758: Dropdown field doesn't full render when it's the last item in the form

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#60]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: 1) Create a content type with the default fields only so 'Place In Nav' field is the last item in the form
2) Open the form to create or edit a content. 

See the screenshot for the style issue.:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1758
----------

**Comment by vestrada** [comment]
I can't reproduced this issue, I tested it in all browsers. Images are attached.

Chrome:
<img width="610" alt="chrome" src="https://cloud.githubusercontent.com/assets/11640613/22227110/2ccade58-e18f-11e6-8b71-a209e8cce780.png">

IE:
<img width="572" alt="ie" src="https://cloud.githubusercontent.com/assets/11640613/22227144/647cf7aa-e18f-11e6-9f79-00a4d77047af.png">

 Firefox:
<img width="566" alt="firefox" src="https://cloud.githubusercontent.com/assets/11640613/22227134/584eb630-e18f-11e6-8406-da5051087258.png">
