### ISSUE TITLE
[social] commentUrl is not accessible in notification email template

### ISSUE THREAD

**Issue by LorenzoRodriguezRivetlogic** [craftercms/craftercms#601]
DESCRIPTION: commentUrl is not accessible in notification email template when the change have id 'vote' or 'ugc.moderate'
PRECONDITIONS: A comment with the property commentUrl saved 
STEPS FOR REPRODUCE:
For all scenarios:
1. In Social Admin console go to "Notifications preferences"
2. Use attached file ([emailTemplate.txt](https://github.com/craftercms/craftercms/files/845917/emailTemplate.txt)) on the notification email template
3. Save 
4. Go to a page with social enable a make a comment

Scenario 1:
1. Go to the page an with a different user vote a comment.

Scenario 2:
1. Go to the social admin console
2. Go to moderation dahsboard
3. Search for the comment
4. Click on approve

CURRENT RESULT:

The email is not send and the console show the attached stacktrace [stacktrace.txt](https://github.com/craftercms/craftercms/files/845918/stacktrace.txt)

EXPECTED RESULT: 
The email is sent and the url in the email is functional

**Comment by cortiz** [comment]
Not an Issue, using the wrong attribute, it has to be `ugc.attributes.commentUrl`
