### ISSUE TITLE
[studio][studio-ui] Content can't be unlocked or edited after Save & Close and Save & Minimize action

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6011]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Content that is Save & Closed + a quick Save & Minimize before the content form closes results in the content being uneditable as well as unlockable. This behavior happens in larger sites and slower networks.

### Steps to reproduce

Steps:

1. Create a site based on Editorial Blueprint
2. Navigate to /site/website/articles and create a new Article
3. Fill out all the required fields and Save & Close the content
4. Now right click and edit the content, and open your developer tools
5. Throttle your network speed to be "Slow 3G"
6. Select Save & Close again, then immediately click the drop-down and select Save & Minimize instead
7. Notice the content goes into a locked state, and it can not be edited or unlocked
8. See logs for error when trying to unlock the content

### Relevant log output

```shell
https://gist.github.com/AndyReiter/dab677ab5c8e6f4e208ca8234aebffd0
```

### Screenshots and/or videos

https://www.loom.com/share/e4ab753616974f4f8e5a7158b063b465

**Comment by rart** [comment]
@jvega190 please review and fix the `isSubmitting` mechanics of this dialog. 
The buttons shouldn't be enabled while things are being saved.
Please identify what is it that happens to the file that after this can't get unlocked. There might be a backend thing we can address there too.

**Comment by jvega190** [comment]
@sumerjabri @rart when the item can't get unlocked, the item does have the unlock state, and when the unlock action is triggered, the payload seems correct 
```{"siteId":"some-site","path":"/site/website/articles/2021/3/test/index.xml"}```

Though I'm getting the same error that was shared in the description of the ticket; 
```[ERROR] 2023-04-12T15:36:05,882 [http-nio-8080-exec-6] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/content/item_unlock_by_path' failed with response 'ApiResponse{code=7003, message='Content already unlocked', remedialAction='The item is already unlocked', documentationUrl=''}' ```.

So it seems like needs to be addressed by the backend too.

**Comment by jmendeza** [comment]
The error preventing the user from unlocking the content is that the DB contains a locked state, but no `locked_by`.
This is happening because of the two requests to `write-content`:
1. The `Save & Close` params contain `unlock=true`, so locked bit and locked_by are cleared
1. Then the `Save & Minimize` params contain `unlock=false`. This sets the locked state bit on, but it does not set `locked_by`, assuming content was already locked.

Behavior has been updated so the locked state bit is not turned on when `unlock=false`, so the status of the content (either locked or unlocked) remains unchanged

**Comment by AndyReiter** [comment]
Confirmed fixed in the latest build: 
Version Number:
4.1.0-SNAPSHOT-c1acb7
