### ISSUE TITLE
[studio-ui] Websocket throws 302 error when session timeout

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6015]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When a user session timeout, the user gets logged out from Studio but the WebSocket connection is still opened and throws a 302 error interval.

### Steps to reproduce

Steps:

1. Create a new site with Editorial BP using the Chrome browser
2. Keep the preview open and wait until the session timeout
3. Open a new tab and enter: chrome://inspect/#workers
4. Select the Inspector and open
5. Notice that there are many WebSocket connection errors with status code 302. (In a normal case, it should be 101) 

### Screenshots and/or videos

![2023-04-17_19-15](https://user-images.githubusercontent.com/2996543/232481153-e30b787d-6bbd-4473-910b-1c73c5dcba81.png)

**Comment by rart** [comment]
@jvega190 the socket should reconnect upon successful session renewal and disconnect when session times out

**Comment by yacdaniel** [comment]
Verified fixed in 4.1.0-SNAPSHOT.
