### ISSUE TITLE
[engine] On multi-tenant (live) Engine mode, Engine shouldn't finish startup if site contexts fail to build

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#6017]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When Engine is configured in multi-tenant (aka live) mode, on startup, it tries to load all site contexts. Unfortunately, if a site context can't be loaded the first time because of a temporary issue (like a Groovy download failure), Engine continues startup. This causes healthchecks to say the server is OK when the sites are still not ready.

### Steps to reproduce

Steps:

1. Setup Delivery
1. In Studio, create a site that fails to build initially (in Kubernetes this can be reproduced easily by adding a Grapes dependency that needs to be downloaded. On the very first site context build this seems to always fail)
1. Publish the site and restart Delivery

Observe that the Delivery Tomcat is completely started up even when the site context failed to build.

Engine should try to re-load a site context on startup if the first time it fails, in a staggered manner, and fully fail if it can't do it after X tries. Eg:

- Load site context A fails.
- Wait 5 seconds
- Load site context A fails
- Wait 15 seconds
- Site context A loaded

OR

- Load site context B fails.
- Wait 5 seconds
- Load site context B fails
- Wait 15 seconds
- Load site context B fails
- Wait 30 seconds
- Load site context B fails. Won't continue

**Comment by sumerjabri** [comment]
The backoff (stagger) algorithm can look like this:
- Number of retries
- Base wait time
- Wait time multiplier

Algorithm:
- Attempt = 0
- Wait time = Base wait time
- Loop number of retries
  - Load site context
  - If fail
    - Wait(Wait time)
    - Wait time = Wait time * Wait time multiplier
    - Attempt++
  - else
    - done
- Failed to start

@avasquez614 should it just die if it fails to start?

**Comment by avasquez614** [comment]
@sumerjabri @phuongnq maybe we can make it configurable, and by default it just fails to start Tomcat completely if it failes after the max retries?

**Comment by avasquez614** [comment]
@phuongnq I discussed it with Sumer and Russ and we decided that after the max tries we'll let the Tomcat startup continue. So I think you just need fix the PR based on my feedback

**Comment by avasquez614** [comment]
This needs to be in 4.0 too, it's only on 4.1
