### ISSUE TITLE
Wrong userFirstName and userLastName in the API /studio/api/2/publish/history response

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6018]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The API https://docs.craftercms.org/en/4.0/_static/api/studio.html#tag/publishing/operation/getPublishingHistory response has the fields about the user:
* user
* userFirstName
* userLastName

The `user` field has the correct value to be the username of the publisher. However `userFirstName` and `userLastName` have the values of the last updated user.

### Steps to reproduce

Steps:

1. Create a new project with Editorial BP
2. Publish the whole site
3. Call the API: For example:
```
GET /studio/api/2/publish/history?siteId=ed&days=10&num=10
```
4. Notice that the userFirstName, userLastName have the values of the last edit user (Git)

### Screenshots and/or videos

![2023-04-19_09-01](https://user-images.githubusercontent.com/2996543/232947273-a6a040b5-6650-4a07-a0a0-bad6208f36b5.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fixed verified for Crafter v4. Thank you! Closing this ticket.
