### ISSUE TITLE
[studio-ui] Copy paste is not copying more than one level

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#602]
Using the copy feature in the Site Content menu for pages with multiple sub-sections, only the first sub-set is copied. For example if I were copying all of #1, only levels 1 & 2 would be pasted to the new location. Levels 3 & 4 wouldn't be copied.

**Comment by russdanner** [comment]
I did a test where I tried this and confirmed it's an issue.  To me looks like a UI issue.  
<img width="935" alt="screen shot 2017-03-16 at 1 07 44 pm" src="https://cloud.githubusercontent.com/assets/169432/24008931/add92206-0a49-11e7-89a8-2b4fbd47303f.png">

It looks like the Dialog request the child pages but then only displays 2 levels. 
`http://localhost:8080/studio/api/1/services/api/1/clipboard/get-items.json?site=globalintegrity&user=admin&nocache=Thu%20Mar%2016%202017%2013:03:59%20GMT-0400%20(EDT)
`
## Response
`{"item":{"name":"index.xml","internalName":"Contact us","contentType":"/page/contact-us","uri":"/site/website/contact-us/index.xml","path":"/site/website/contact-us","browserUri":"/contact-us","navigation":false,"floating":true,"hideInAuthoring":false,"previewable":true,"lockOwner":"","user":"admin","userFirstName":"admin","userLastName":"","nodeRef":null,"metaDescription":null,"site":"globalintegrity","page":true,"component":false,"document":false,"asset":false,"isContainer":true,"container":true,"disabled":false,"savedAsDraft":false,"submitted":false,"submittedForDeletion":false,"scheduled":false,"deleted":false,"inProgress":true,"live":false,"inFlight":false,"isDisabled":false,"isSavedAsDraft":false,"isInProgress":true,"isLive":false,"isSubmittedForDeletion":false,"isScheduled":false,"isNavigation":false,"isDeleted":false,"isNew":true,"isSubmitted":false,"isFloating":false,"isPage":true,"isPreviewable":true,"isComponent":false,"isDocument":false,"isAsset":false,"isInFlight":false,"eventDate":"2017-03-15T11:37:30-04:00","endpoint":null,"timezone":null,"numOfChildren":1,"scheduledDate":null,"mandatoryParent":null,"isLevelDescriptor":false,"categoryRoot":null,"lastEditDate":"2017-03-15T11:37:30-04:00","form":"/page/contact-us","formPagePath":"simple","renderingTemplates":[{"uri":"/templates/web/page-contact.ftl","name":"DEFAULT"}],"folder":false,"submissionComment":null,"components":null,"documents":null,"levelDescriptors":null,"pages":null,"parentPath":null,"orders":[{"name":null,"id":"default","order":-1.0,"disabled":null,"placeInNav":null}],"children":[{"name":"index.xml","internalName":"About ","contentType":"/page/article","uri":"/site/website/contact-us/about/index.xml","path":"/site/website/contact-us/about","browserUri":"/contact-us/about","navigation":true,"floating":false,"hideInAuthoring":false,"previewable":true,"lockOwner":"","user":"admin","userFirstName":"admin","userLastName":"","nodeRef":null,"metaDescription":null,"site":"globalintegrity","page":true,"component":false,"document":false,"asset":false,"isContainer":true,"container":true,"disabled":false,"savedAsDraft":false,"submitted":false,"submittedForDeletion":false,"scheduled":false,"deleted":false,"inProgress":true,"live":false,"inFlight":false,"isDisabled":false,"isSavedAsDraft":false,"isInProgress":true,"isLive":false,"isSubmittedForDeletion":false,"isScheduled":false,"isNavigation":false,"isDeleted":false,"isNew":true,"isSubmitted":false,"isFloating":false,"isPage":true,"isPreviewable":true,"isComponent":false,"isDocument":false,"isAsset":false,"isInFlight":false,"eventDate":"2017-03-16T13:02:20-04:00","endpoint":null,"timezone":null,"numOfChildren":1,"scheduledDate":null,"mandatoryParent":null,"isLevelDescriptor":false,"categoryRoot":null,"lastEditDate":"2017-03-16T13:02:20-04:00","form":"/page/article","formPagePath":"simple","renderingTemplates":[{"uri":"/templates/web/page-article.ftl","name":"DEFAULT"}],"folder":false,"submissionComment":null,"components":null,"documents":null,"levelDescriptors":null,"pages":null,"parentPath":null,"orders":[{"name":null,"id":"default","order":0.0,"disabled":null,"placeInNav":null}],"children":[],"new":true,"reference":false,"newFile":false,"levelDescriptor":false}],"new":true,"reference":false,"newFile":false,"levelDescriptor":false}}`

When it sends the copy command to the server, it's then only for 2 levels

**Comment by vestrada** [comment]
2.5.X PR: https://github.com/craftercms/studio2-ui/pull/294
MSTER PR: https://github.com/craftercms/studio2-ui/pull/295

**Comment by vestrada** [comment]
Fixed, Copy is copying more than 1 level. 
Paste is not pasting more than 1 level, the issue seems to be on back end. Please take a look.

**Comment by vestrada** [comment]
Styles:
2.5.X PR: https://github.com/craftercms/studio2-ui/pull/296
Master PR: https://github.com/craftercms/studio2-ui/pull/297

**Comment by russdanner** [comment]
Copy UI now sends all copy values

```
{"item":[{"uri":"/site/website/contact-us/about/index.xml","children":[{"uri":"/site/website/contact-us/about/contact-us/index.xml","children":[{"uri":"/site/website/contact-us/about/contact-us/search/index.xml","children":[{"uri":"/site/website/contact-us/about/contact-us/search/contact-us/index.xml"}]}]}]}]}```

**Comment by russdanner** [comment]
Client side sends paste command with proper parent
```http://localhost:8080/studio/api/1/services/api/1/clipboard/paste-item.json?site=globalintegrity&parentPath=/site/website/about/contact-us/index.xml&nocache=Fri%20Mar%2017%202017%2013:47:29%20GMT-0400%20(EDT)```

**Comment by russdanner** [comment]
Closed this as it was merged and fixed some time ago
