### ISSUE TITLE
[engine] Update the Status API to only report success when Engine has valid site contexts or no contexts

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6020]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Engine reports status using the API: https://docs.craftercms.org/en/4.0/_static/api/engine.html#tag/monitoring/operation/status

The API returns 200 and reports Engine is in good status when Engine is up and running. That means Engine can report it's ready when it has a single context that's broken resulting in broken site joining a load balancer.

### Describe the solution you'd like

Engine should report healthy if and only if:
- There are no contexts at all
- There is one or more valid contexts

**Comment by phuongnq** [comment]
@sumerjabri Is using another API endpoint such as `/api/1/monitoring/site/status` possible? 
We have a common API `/api/1/monitoring/status` [here](https://github.com/craftercms/commons/blob/develop/utilities/src/main/java/org/craftercms/commons/monitoring/rest/MonitoringRestControllerBase.java#L55) for Engine, Deployer, Profile, and Social. Rewriting this API is also possible but we will need to move it to the modules level to have the context for Engine. This will duplicate the same code for other modules including Deployer, Profile, and Social.

This is the same confirmation for https://github.com/craftercms/craftercms/issues/6021

**Comment by avasquez614** [comment]
@phuongnq you can always extend the Monitoring class for Engine, overwrite the method and map it to the same path. It will replaced the old monitoring API. We've done that a few times succesfully

**Comment by phuongnq** [comment]
@avasquez614 Got it! I created PRs for this. `commons` also need to modify to add the `site` parameter which is only used by the override method in Engine.

**Comment by avasquez614** [comment]
@phuongnq I think you misunderstood the purpose of the new API. We don't want an API that receives a site parameter and indicates if the site is healthy. We want an API that gets the list of sites and returns OK if:

- If the list of sites is empty
OR
- If at least one site from the list of sites has a valid site context

**Comment by sumerjabri** [comment]
@phuongnq it's fine to make the update to commons to allow the check for a specific site to help with the ticket https://github.com/craftercms/craftercms/issues/6021

It would be great to use overrides like AV said.

**Comment by yacdaniel** [comment]
Verified in `4.1.0-SNAPSHOT`
