### ISSUE TITLE
[engine] Engine should support health check per context

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6021]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The API https://docs.craftercms.org/en/4.0/_static/api/engine.html#tag/monitoring/operation/status reports general health checks across all contexts. It would be great if it supported checking the status for specific contexts (projects/sites)

### Describe the solution you'd like

Augment the API to accept an options parameter of the project/site to check the context of. Consider using the standard `site` parameter to report the status back.

**Comment by yacdaniel** [comment]
Verified in `4.1.0-SNAPSHOT`
