### ISSUE TITLE
[studio] Sites available to user do not respect multi environment configuration

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6025]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When Studio is in a multi-environment configuration, users cannot see a site even if they are assigned to a group in the active environment

### Steps to reproduce

Steps:

1. Start Studio with a custom active environment. Ex: research
2. Log in as an admin user
3. Create a new site `ed` from Editorial BP
4. Add a custom role mapping file at the location `env/research/role-mappings-config.xml` for `ed` site and commit the change:
```
<role-mappings>
    <version>4.0.1</version>
    <groups>
	    <group name="ed_site_admin">
		    <role>admin</role>
	    </group>
        <group name="site_admin">
            <role>admin</role>
        </group>
        <group name="site_developer">
            <role>developer</role>
        </group>
        <group name="site_author">
            <role>author</role>
        </group>
        <group name="site_publisher">
            <role>publisher</role>
        </group>
        <group name="site_reviewer">
            <role>reviewer</role>
        </group>
    </groups>
</role-mappings>
```
5. Create a new user and assign it to the group `ed_site_admin`
6. Log in as the user in step 4, notice that there is no site available from the Global menu

Note that if we update the above configuration to the default `role-mappings-config.xml`, then the user can see the site `ed`

### Screenshots and/or videos

Site configuration:

![2023-04-28_09-14](https://user-images.githubusercontent.com/2996543/235038094-08a287ec-f234-4d84-a25f-8de82f6d0606.png)
![2023-04-28_09-13_1](https://user-images.githubusercontent.com/2996543/235038096-2e592cc3-87fd-426d-9c3a-7e7fe7d69822.png)

User does not see the site:
![2023-04-28_09-13](https://user-images.githubusercontent.com/2996543/235038295-3ef057d7-e991-4642-817a-5a7eeb8f67d7.png)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
