### ISSUE TITLE
[studio-ui] XB - Inherited fields issues

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6028]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

There are several issues when dealing with inherited fields (for example fields from a level-descriptor).

- Fields are not properly registered (in react)
- When editing the fields using the zone menu (clicking on the pencil) it opens an incorrect form (not the form from where the field inherits)
- Inline edition/assets drag updates fails beause it uses an incorrect model (not the form from where the field inherits)
- Incorrect locked item.

So far those are the issues found, but more testing is needed.

### Steps to reproduce

Steps:

1. Go to editorial based site
2. In the content-type editor, add a field (for example an input field) to the level descriptor
3. Add some value to the field in the level-descriptor
4. Render the field in the homepage
5. In preview, using XB try to edit the field
6. See error, also see that the locked item is homepage and not the level descriptor

**Comment by rart** [comment]
The update works, but the image doesn't seem to update on the page without refresh.
