### ISSUE TITLE
[all] Upgrade to the latest GraphQL

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6030]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

GraphQL is outdated

### Describe the solution you'd like

Upgrade to 19.5 or later

**Comment by Euquimides** [comment]
Hi! Feature verified for both Crafter v3.1.x and Crafter v4. Thank you! Closing this ticket.
