### ISSUE TITLE
Enhance the Sidebar navigators

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6033]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The TreeNav has some limitations for search and pagination that we'd like to improve.

### Describe the solution you'd like

Please update the TreeNav
- TreeNav
  - [x] Update pagination to be configurable. Same as PathNav (with pagination) with a drop-down for the number of items per page.
  - [ ] ~Update the magnifying glass to be always visible, but, it's very faint when not hovered over and fully visible on hover~
- PathNav
  - [ ] ~Add a "back" or "up" button to allow the user to navigate up a level~

**Comment by jvega190** [comment]
Per conversation 'back' button won't be added to Path Navigator

**Comment by jvega190** [comment]
Per conversation, PathNavigatorTree pagination will be reverted and moved to another release.

**Comment by sumerjabri** [comment]
Consider a preferences mechanism to set the page size.

**Comment by sumerjabri** [comment]
@rart, let's keep the magnifying glass invisible until hover, as @russdanner indicated when checking with actual users.

**Comment by sumerjabri** [comment]
PathNav and PathNavTree config: https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/user-interface-configuration.html#limit

**Comment by sumerjabri** [comment]
For PathNav, the breadcrumb is now always expanded to help users go up a level or more.
