### ISSUE TITLE
[social] Incorrect baseUrl in notification email template

### ISSUE THREAD

**Issue by LorenzoRodriguezRivetlogic** [craftercms/craftercms#604]
DESCRIPTION: Incorrect baseUrl in notification email template, adds "/crafter-social" to url
PRECONDITIONS: A comment with the property commentUrl saved
STEPS FOR REPRODUCE:
1. Go to social admin console
2. Go to tenant preferences
3. Set a valid baseUrl (ex: http://localhost:9080)
4. Go to Notification preferences
5. Use the attached template on Notification email preferences: 
[emailTemplate.txt](https://github.com/craftercms/craftercms/files/845975/emailTemplate.txt)
6. Go to a page with social enabled
7. Add a comment with another user in a thread that you are watching
8. Wait for the email to be sent

CURRENT RESULT:
The baseUrl is http://localhost:9080/crafter-social

EXPECTED RESULT:
The baseUrl is http://localhost:9080

**Comment by cortiz** [comment]
https://github.com/craftercms/social/pull/324

https://github.com/craftercms/social/pull/323

Use `baseUrl` variable in the freemarker, the value is set in the configuration of each context.
