### ISSUE TITLE
[studio-ui][studio] The publishing queue in  the publishing dialog displays an error for user publisher

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6045]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The publishing queue in  the publishing dialog displays an error for a user  with the publisher role.

```
Unauthorized. You don't have permission to perform this task, please contact your administrator.  
```
<img width="1409" alt="Screenshot 2023-05-09 at 11 40 01 AM" src="https://github.com/craftercms/craftercms/assets/25483966/adb05777-18dd-4d10-8aaa-c0615633193b">

Please update permissions for users with the role publisher so the publishing queue will be available to those users
Also, please review the widget being shown if a user does not have permissions for  that widget. (A less scary image/message  would be nice for the  user to see)

### Steps to reproduce

Steps:

1. Create a user with the role `publisher`
2. Login to Studio  as the publisher
3. Open the `Publishing` dialog and scroll down to the `Publishing Queue` section
4. Notice the error message displayed

**Comment by rart** [comment]
@jvega190 for the publishing dashboard (project tools & tool bar quick access button), make sure we're using the right permissions to show the widget.

The error displayed is fine if the permission is absent, but we may not be using that same permission on the dashboard to even show the widget in the first place.

**Comment by jvega190** [comment]
The correct permission `get_publishing_queue` is already being checked and is present in the publisher user. Though the `/studio/api/2/publish/packages` returns an error.

**Comment by jmendeza** [comment]
Fixed permissions in the backend for 'publisher' role

**Comment by alhambrav** [comment]
Verified fixed
