### ISSUE TITLE
[studio] get audit logs service returning 10 items

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#605]
When calling '/api/1/services/api/1/audit/get.json?&site_id=editorial' (no start/number params) it returns only 10 items, and if sending start/number params '/api/1/services/api/1/audit/get.json?site_id=editorial&start=0&number=5' it also returns 10 params, even if number = 5.

**Comment by sumerjabri** [comment]
Already covered in https://github.com/craftercms/craftercms/issues/596
