### ISSUE TITLE
[Delivery] Enhance the Crafter Delivery image to be downloadable without unsolved dependencies

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6050]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Customers who are attempting to run Crafter Delivery in an EKS cluster with several security restrictions experience issues when we try to run the script `init-site.sh` to set up delivery. The script doesn't work because, for security reasons, the installer is not able to download the Groovy dependencies (grapes).

### Describe the solution you'd like

The request is to deliver the Crafter Delivery image ready without unsolved dependencies for cases where the security restrictions don't allow the download of additional libraries.

**Comment by sumerjabri** [comment]
Resolved since we pre-download Grape deps now.

CC @russdanner
