### ISSUE TITLE
[studio-ui] Dashboard enhancements

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6051]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

User `author` and `reviewer` only has the `Activity` widget available in their dashboard.

![Screenshot 2023-05-11 at 9 31 43 AM](https://github.com/craftercms/craftercms/assets/25483966/7a57c601-0168-479e-a890-5fa68e4b9193)

### Describe the solution you'd like

Previous versions  gives the  user author the `My Recent Activity` widget, which allows the user to request publish multiple items, view history, etc.  For the user reviewer, the dashboard is the same as a publisher/admin.

Update the dashboard for all users to have all the dashlets available

**Comment by sumerjabri** [comment]
The enhancement where a user can select from MyRecentActivity is pending a ticket from @rart

**Comment by alhambrav** [comment]
Verified all dashlets now available for all users

**Comment by alhambrav** [comment]
Enhancement to Facilitate Item Actions in New Dashboards: https://github.com/craftercms/craftercms/issues/6058

Closing ticket
