### ISSUE TITLE
[studio-ui] Publish action is not available for user author in the "Unpublished Works" dashlet in the Dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6053]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Publish action is not available for user author in the "Unpublished Works" dashlet in the Dashboard when only one item is selected

![Screenshot 2023-05-11 at 11 48 11 AM](https://github.com/craftercms/craftercms/assets/25483966/05a4bd20-91ab-4085-adf6-873ae434310b)

### Steps to reproduce

Steps:

1. Create a site using the Website Editorial BP
2. Create a user with the `author` role
3. Login as the author
4. Edit a few articles
5. Open the Dashboard and go to the `Unpublished Works` dashlet
6. Select one the article just edited.  Notice that the action for `Publish` is not available
7. Select two or more articles that were edited by the author and notice that the `Publish` action is now available
![Screenshot 2023-05-11 at 11 55 14 AM](https://github.com/craftercms/craftercms/assets/25483966/d06f373a-30ab-47be-b3db-201833eb978f)

**Comment by rart** [comment]
@jvega190 make sure we're generating the actions from permissions and not just a static hardcoded list

**Comment by sumerjabri** [comment]
@rart shouldn't the smarts be in the backend using Available Actions instead of the UI looking at permissions?
