### ISSUE TITLE
[studio-ui] Facilitate Item Actions in New Dashboards

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6058]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Depending on the state of the system/content, it's more difficult to perform actions over certain items on the new dashboards. Need to enable and facilitate performing actions over items with more ease.

### Describe the solution you'd like

Design and implement a mechanism to perform item actions at all stages with ease.

**Comment by rart** [comment]
@jvega190 please carry on the task. Start from my `enhancement/6058` branch.

Based on whether it is an item on the **My** Activiy feed, a checkbox is shown. Need to add selection logic.

Additionally, please enable item actions via "more" menu button on the package detail dialogs from the various dialogs. Hopefully it is the same dialog for all.

**Comment by alhambrav** [comment]
Verified
