### ISSUE TITLE
[studio][studio-ui] Preview Addressbar issues

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6060]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

- [ ] [studio] With the validations, `/` character is rejected, disabling url search
- [ ] [studio-ui] When an error occurs in the back, the ui is not handling and spins forever

### Steps to reproduce

Steps:

1. Go to the preview address bar
2. Type `/`
3. See the issue

### Screenshots and/or videos

<img width="470" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/b37b8e53-e080-4052-a41d-75fb6f7cb852">

**Comment by rart** [comment]
@sumerjabri we need to make a decision on how to support or drop support for url search on the address bar UI. Specifically, can we allow `/` as a valid char for that search to execute without exceptions.

**Comment by sumerjabri** [comment]
We have a workaround for now. This drops in priority.

**Comment by rart** [comment]
Verified
