### ISSUE TITLE
[studio] Switch git-based event audit to not process commit history

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6062]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Audit Log updates based on Git are no longer needed.

### Describe the solution you'd like

Don't process Git-based audit events after a `git pull` through the UI or syncDbFromRepo clock. Insert the merge commit ID into the audit table and indicate it was a pull for the auditor to see.

**Comment by jmendeza** [comment]
@sumerjabri this is already taken care of as part of https://github.com/craftercms/craftercms/issues/6126
The audit table will say some commits were ingested (from a pull or sync from repo), and audit params will contain the introduced commits
