### ISSUE TITLE
[deployer] Re-process servlet stops if an error is found on a single file

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#607]
Any item that has an issue with a process stops the entire process.  Shouldn't the deploy log issues and continue or at least support an option to force/continue on error?
Also: processing does not seem to log a start

## Example
When we are trying to reprocess the live server indexes, It is failing with following errors. We need to fix the error and need to initiate reprocess again.

How can we skip the errors and complete the reprocess ?

> 2017-03-16_13:09:15.216 [http-bio-9080-exec-2] INFO o.a.s.u.processor.LogUpdateProcessor - [crafterSearch] webapp=/solr-crafter path=/update params={waitSearcher=true&commit=true&wt=xml&version=2.2&softCommit=false} {commit=} 0 0 
> ERROR: org.craftercms.search.controller.SearchRestController - RESTful request /crafter-search/api/1/search/update-document failed 
> java.lang.IllegalArgumentException: Invalid format: "04/0|3/2012 00:00:00" is malformed at "|3/2012 00:00:00" 
> at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:866) 
> at org.craftercms.search.service.impl.SolrDocumentBuilder.convertToISODateTimeString(SolrDocumentBuilder.java:267)
> 
> 2017-03-16_14:08:34.201 [http-bio-9080-exec-2] INFO org.apache.solr.update.UpdateHandler - end_commit_flush 
> 2017-03-16_14:08:34.201 [http-bio-9080-exec-2] INFO o.a.s.u.processor.LogUpdateProcessor - [crafterSearch] webapp=/solr-crafter path=/update params={waitSearcher=true&commit=true&wt=xml&version=2.2&softCommit=false} {commit=} 0 0 
> ERROR: org.craftercms.search.controller.SearchRestController - RESTful request /crafter-search/api/1/search/update-document failed 
> java.lang.IllegalArgumentException: Invalid format: "7/30/2014| 18:37:7" is malformed at "| 18:37:7" 
> at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:866)
> 
> ERROR: org.craftercms.search.controller.SearchRestController - RESTful request /crafter-search/api/1/search/update-document failed 
> org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: ERROR: [doc=mysite:/static-assets/documents/committees/comm_wkgrps/relblty_comm/pwrsuppln_comm/mtrls/2009/jul92009/op4_historical_data_7_09_09.pdf] Error adding field 'normalizedFileSize_l'='23142|4' msg=For input string: "23142|4" 
> at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:554) 
> at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210) 
> at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206) 
> at org.craftercms.search.service.impl.SolrSearchService.updateDocument(SolrSearchService.java:266) 
> at org.craftercms.search.controller.SearchRestController.updateDocument(SearchRestController.java:126) 
> at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
> at java.lang.reflect.Method.invoke(Method.java:606) 
> at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213) 
> at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
> at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96) 
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617) 
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578) 
> at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) 
> at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923) 
> at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852) 
> at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882) 
> at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789) 
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)

**Comment by avasquez614** [comment]
Fixed on 2.5.5.1 of legacy-deployer, for old deprecated processors. Newer versions use new processors that already don't have this problem.
