### ISSUE TITLE
[studio-ui] Dashboard: My Recent Activity / Activity dashlets should display labels for PUBLISH_ALL action type

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6071]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `My Recent Activity` and `Activity` dashleats should displays labels for the `PUBLISH_ALL` action type

### Steps to reproduce

Steps:

1. Create a site from any BP
2. Do the site's initial publish
3. Do some edits or add content
4. Perform a `Publish Everything` from `Publishing Dashboard`

### Relevant log output

```shell
{
    ...
    ...
    "activities": [
        {
            "id": 788,
            "person": {
                "id": 0,
                "username": "admin2",
                "firstName": "Yacdaniel",
                "lastName": "Hurtado",
                "avatar": null
            },
            "actionType": "PUBLISH_ALL",
            "actionTimestamp": "2023-05-18T22:31:26Z",
            "item": null,
            "package": null
        },
    ...
    ...

```

### Screenshots and/or videos

Those actions are missing info becase are of type `PUBLISH_ALL`

![image](https://github.com/craftercms/craftercms/assets/6722074/db3563b6-8f8d-471b-9e8d-f8d6f08e9572)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
