### ISSUE TITLE
[studio-ui] Sidebar: 1 more item button not reloading correctly.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6072]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `...1 more item`  button that shows in sidebar is not refreshing the state correctly. This seems to only happen when new content is created/duplicated and with content that is under the Home page directly, if something is under a folder it works as expected.  Also seems that the `offset` parameter in the `children_by_path` API call  keeps increasing with each click to the `... 1 more item`

### Steps to reproduce

Steps:

1. Create a site from Editorial blueprint
2. Duplicate the `Entertainment`  page
3. Click the `...1 more item`
4. See the issue

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/6722074/3b294892-9b19-4134-8240-b7205f5b8945

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
