### ISSUE TITLE
[studio] Unpublished items API not returning items in a consistent order

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6076]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The unpublished items API is not returning the items in a consistent order. For exampe, it you retrieve items 5 by 5 until the last set of items available, it'll have a different order than if you retrieve all of the items at once.

### Steps to reproduce

Steps:

1. Fetch the last set of unpublished items, let say offset: 35, limit: 40 (considering you have 35 items).
2. Fetch all of the unpublished items (offset 0, limit: 40)
3. See how the last 5 items of the second call differ from the first one.

### Screenshots and/or videos

Subset of unpublished items:
![Screenshot from 2023-05-22 15-08-23-Unpublished](https://github.com/craftercms/craftercms/assets/18267471/87940773-74c5-457d-95f6-ac91c977a1d7)

All of the available unpublished items:
![Screenshot from 2023-05-22 15-08-51-Unpublished](https://github.com/craftercms/craftercms/assets/18267471/b63564fd-612e-4931-868d-8f46df2e3609)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
