### ISSUE TITLE
[studio] File selector with upload data source does not report file size

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#608]
The file selector component no longer receives the file size from the backend when uploading a file:

Data Source: file-desktop-upload.js 

Calls this operation:
`CStudioAuthoring.Operations.uploadAsset(site, path, isUploadOverwrite, callback); `

Which on success returns fileData
`success: function(fileData) { 
if (control) { 
   control.insertItem(path + "/" + fileData.fileName, path + "/" + fileData.fileName, fileData.fileExtension, fileData.size); 
   control._renderItems(); 
   } 
}`

fileData.size is returning undefined.

## To reproduce:
Create a simple form with a file-upload data source linked to a item selector, open form and upload file.

Note that call to service does NOT return size in response.  It should.
http://localhost:8080/studio/asset-upload?nocache=Fri%20Mar%2024%202017%2011:05:44%20GMT-0400%20(EDT)
`{   fileName: "research.jpg",
	fileExtension: "jpg"
}`

**Comment by sumerjabri** [comment]
@russdanner can you provide details on how to reach this state and more clearly indicate what's wrong?

**Comment by sumerjabri** [comment]
Closing this as we don't have enough detail.

**Comment by dejan-brkic** [comment]
Done 
studio:
PR #601 #602

studio-ui
PR #308 #309
