### ISSUE TITLE
[studio-ui] Disabled state has precedence over locked state

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6080]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Disabled state has precedence over locked state. This can cause UX issues when trying to edit a disabled item.

### Describe the solution you'd like

Locked to have precedence over disabled on the _Item Display_ and the _Item Megamenu_

**Comment by Euquimides** [comment]
Hi! Updated and checked this feature. Verified implementation to Crafter v4. Thank you!
