### ISSUE TITLE
[studio-ui] Give user feedback when missing required fields on create site dialog

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6082]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When creating a site, user might not notice required parameters are not fulfilled. Clicking `Review` button does nothing when required values are not populated.
![Screenshot from 2023-05-25 11-40-13](https://github.com/craftercms/craftercms/assets/6042406/11f14992-10d0-463e-8767-e1b9a3af1400)

![Screenshot from 2023-05-25 11-49-25](https://github.com/craftercms/craftercms/assets/6042406/63e02e17-b883-49eb-b17f-089e83edbee2)

### Describe the solution you'd like

- When `Review` button is clicked, scroll to the complaining parameters if none of them is in the current view.
- OR give the user some feedback to let them know they are missing some fields

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
