### ISSUE TITLE
Parent page is considered a hard dependency if the child page renamed from a different path

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When a new page is created (or copied), if the parent is in an edit state and the new page has a previous path (renaming path), the parent page is a hard dependency.

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Do the initial publish
3. Copy an article (Ex: /site/website/articles/2020/12/top-books-for-young-women/index.xml`) to a Category page (Ex: /site/website/entertainment/index.xml)
4. Update the Category page to make it in an edited state
5. Update the newly copied page to have a different path (Ex: /site/website/entertainment/top-books-for-young-women/index.xml => site/website/entertainment/top-books-for-young-women-test/index.xml)
6. Open the new page publish dialog and notice that `/site/website/entertainment/index.xml` is considered a hard dependency

### Screenshots and/or videos

![2023-05-26_15-35_1](https://github.com/craftercms/craftercms/assets/2996543/1cf806de-e9fb-4536-81f6-ed4cee0bcf74)
![2023-05-26_15-35](https://github.com/craftercms/craftercms/assets/2996543/3db08e5d-6fe3-4f96-8014-558711928531)
![2023-05-26_15-36](https://github.com/craftercms/craftercms/assets/2996543/c9b8c9a6-2b25-49e8-9881-dfdfd307cc91)

**Comment by sumerjabri** [comment]
@jmendeza we need a fix for 4.0 and 4.1 for this one.

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.4-SNAPSHOT` and `4.1-SNAPSHOT`
![image](https://github.com/craftercms/craftercms/assets/6722074/29bd70d3-58fb-4752-9648-b5614a0411e3)
