### ISSUE TITLE
[studio-ui] Scheduled publish date/time is not listed in the "Scheduled for Publish" and "Pending Approval" dashlet

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6088]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `Scheduled for Publish` dashlet shows the edited date/time instead of the scheduled date/time for publish.
The `Pending Approval` dashlet does not show the requested scheduled date/time for publish

UI
- [x] Please change the text for items in the `Scheduled for Publish` dashlet to say: `Approved by <username> for live at <scheduled date/time of publish>`
- [ ] Please sort the items in the `Scheduled for Publish` and `Pending Approval` dashlets in go live ascending date/time
- [x] Please change the text for items in the `Pending Approval` dashlet to say: `submitted by <username> for live on <requested date/time for publish>`

Backend
- [x] For the sorting of items in `Scheduled for Publish` and `Pending Approval` dashlets, please add sorting capabilities to the APIs.

<img width="1376" alt="Screenshot 2023-05-30 at 11 57 27 AM" src="https://github.com/craftercms/craftercms/assets/25483966/d03ebf53-4fab-4ab0-b297-cc7026a812b4">

Below is a screenshot of our previous dashboard which lists the publish date/time for scheduled items

<img width="973" alt="Screenshot 2023-05-30 at 7 40 12 AM" src="https://github.com/craftercms/craftercms/assets/25483966/75c46117-eb9f-4e34-b529-85fa61366a27">

### Steps to reproduce

Steps:

1. Create a project using the Website Editorial BP
2. Login as user author then edit an article and request for the article to be published at a later date
3. Login as user publisher/admin
4. Open the Dashboard.  Notice the item listed in the `Pending Approval` dashlet does not display the requested date/time for publish
5. Approve the request for publishing at a later date.  Make sure the scheduling in the publish dialog is set for publishing at a later time
6. Look at the Dashboard again, in the `Scheduled for Publish` dashlet and notice that the date displayed is not the requested date/time for publish

**Comment by jmendeza** [comment]
Added `itemType` parameter to filter pendingApproval, unpublished and scheduled endpoints.
Valid values are `asset` `component` `content type` `document` `file` `folder` `levelDescriptor` `page` `renderingTemplate` `script` `taxonomy`

cc @jvega190
