### ISSUE TITLE
[studio-ui] Update the site authoring UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#609]
Updated per attachment.

![studio3-ui-mock-site](https://cloud.githubusercontent.com/assets/3931908/24049219/c3fdac10-0b01-11e7-912d-f6098f0c74d4.png)

Ping with any questions.

**Comment by sumerjabri** [comment]
Attaching icons.
![dashboard](https://cloud.githubusercontent.com/assets/3931908/24087089/9242af54-0cf0-11e7-911d-85ad1f4f8cfc.png)
![spyglass](https://cloud.githubusercontent.com/assets/3931908/24087090/924623a0-0cf0-11e7-861f-c45382c3ebd6.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/318
