### ISSUE TITLE
[studio] Studio does not honor custom Global Permission Mappings

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6093]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating custom Global Permissions, Studio does not honor or reflect the permissions. Users can't create sites, view sites, or use any other functionality that should be granted.

### Steps to reproduce

Steps:

1. Create a new Custom Role Mapping under `/data/repos/global/configuration/global-role-mappings-config.xml` and map it to the `system_admin` role. 
2. Run a git add and git commit of the permission file
3. Start up studio
4. Log in as the admin user and create a new group that matches the group name of the role you created
5. Once the new group has been created, create a new user and add it to the new group
6. Log in as the new user
7. Attempt to create a site. Notice that the UI get stuck spinning and the network tab says that the user does not have permissions.

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/3af68fae-b461-4952-9987-aabfda8cfc4f)
[global-role-mappings-config.zip](https://github.com/craftercms/craftercms/files/11617000/global-role-mappings-config.zip)

**Comment by phuongnq** [comment]
@sumerjabri @russdanner  Regarding the issue, I updated the check from group `system_admin` to the role `system_admin` to determine whether a user is a system admin. 

For other roles, ex: site admin, developer, etc we still need to set at the site level. Any custom group in global permissions won't take effect. Is this expected or do we want to improve these roles mapping as well?

**Comment by phuongnq** [comment]
And we also have the API 2 migration in 4.2. 0 which will eventually remove the hard code `system_admin` group/role checking to actually use the permissions file as it is(?)
