### ISSUE TITLE
[bulkedit-plugin] Installing the plugin breaks the sidebar

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6096]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The sidebar fails to render after the plugin is installed

### Steps to reproduce

Steps:

1. Install the plugin
3. Refresh the screen (browser refresh)
4. See the issue (Sidebar does not render)

**Comment by phuongnq** [comment]
I fixed the build issue and also improved the dark mode view.
![2023-06-06_17-09](https://github.com/craftercms/craftercms/assets/2996543/f3384f2e-c1d2-43c9-b44b-39e22d9de05e)
