### ISSUE TITLE
CRAFTERCMS-1761: delete issues a publish even if the item is NEW and was never before published.  

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#61]
Original JIRA Fix Versions:
2.5.2, Original JIRA Components:
Studio, 
----------
Original JIRA Description: The issue is that could push out other dependencies :
----------
Original JIRA Comments:
simple test case:

In static assets
create a new folder
bulk upload some assets to new folder
delete folder

A deployment should not occur.  Nothing was deployed that has to be removed.
----------
Deletes are issued because new status sticks around until item is LIVE but may have been deployed to staging so we need a delete.  Improvement would make this smarter.  Will make that improvement later.
----------
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1761
----------

**Comment by dejan-brkic** [comment]
Already implemented improvement. Latest build 2.5.x has code that checks if content was ever deployed to environment before issuing delete.
