### ISSUE TITLE
Enforce `Project Policy Configuration` to all sections in the current sidebar

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6104]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

At the moment, the default policy configuration seems to apply only to `/static-assets/.*`. The must be changed to include other sections like `Pages`. 

Be wary of the regex to use since this might affect sections such as `Templates` and `Scripts`.

### Steps to reproduce

Steps:

1. Go to a project of your choice.
2. Go to `Project Tools` -> `Configuration` -> `Project Policy Configuration`
3. See the issue.

**Comment by Euquimides** [comment]
Hi @sumerjabri ! Regarding this ticket, I have a question: 

The added regex `/(?!scripts/.*|templates/.*|static-assets/app/.*).*` seems to match any string that does not contain any of the following substrings: - `scripts/` (followed by anything) - `templates/` (followed by anything) - `static-assets/app/` (followed by anything). 

Since the ticket indicates to enforce policy to all sections in the current sidebar, do we still expect the regex to apply to `/scripts` and `templates`? Thank you for your answer.

**Comment by sumerjabri** [comment]
@Euquimides We decided that the default site policy should lowercase everything except: `/scripts`, `/templates`, `/static-assets/app`.

The reason is that those paths are not renderable URLs for the most part, or they're code and developers expect to camelCase things.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.

**Comment by sumerjabri** [comment]
@phuongnq, please remove the UM portion of this ticket and related PR because we don't want this to change someone's existing policy. This means removing the UM stuff, the XSLT, and the XSLT unit tests. @russdanner has more detail. Thank you.

**Comment by sumerjabri** [comment]
@alhambrav, please update the 4.1.4 release notes to indicate the new recommended lower-casing policy detailed in this ticket. For more information, you can reach @russdanner or me.

**Comment by sumerjabri** [comment]
@phuongnq, please also update all community/marketplace blueprints to have the right configuration, just like you did the built-in blueprints. Make sure to update the BP's version number so we can publish them easily.

The list of BPs is as follows:

- https://github.com/craftercms/alexa-blueprint
- https://github.com/craftercms/commercetools-blueprint
- https://github.com/rivetlogic/craftercms-bp-artshowcase.git
- https://github.com/rivetlogic/craftercms-bp-companyshowcase
- https://github.com/rivetlogic/craftercms-bp-events.git
- https://github.com/rivetlogic/craftercms-bp-fitness.git
- https://github.com/rivetlogic/craftercms-bp-gardeners.git
- https://github.com/rivetlogic/craftercms-bp-hotelinfo.git
- https://github.com/rivetlogic/craftercms-bp-pizza.git
- https://github.com/rivetlogic/craftercms-bp-restaurant.git
- https://github.com/rivetlogic/craftercms-bp-singlepage-brochure.git
- https://github.com/rivetlogic/craftercms-bp-videogallery.git
- https://github.com/craftercms/nextjs-blueprint
- https://github.com/craftercms/react-blueprint.git
- https://github.com/craftercms/video-center-blueprint
- https://github.com/craftercms/wordify-blueprint

**Comment by phuongnq** [comment]
@sumerjabri Since the UM has already upgraded studio_version to 4.1.2 for some customers, I think we can keep the UM but update the XSLT to do nothing (just copy the origin file). I have updated the code and test case for this.
Let me know your thoughts on this!

**Comment by phuongnq** [comment]
@sumerjabri I also sent a PR for alexa-blueprint. Will perform the same for other BPs if this looks good.
Please note that the studio_version for this BP was `4.0.0.1` which is a bit behind the current `4.1.2` so I manually updated it to 4.1.2. The reason for this is that we cannot let the UM do the upgrade or it will add another policy statement like this:
```
<statement>
      <target-path-pattern>/static-assets/.*</target-path-pattern>
      <permitted>
         <path>
            <source-regex>[\(\)]</source-regex>
            <target-regex>-</target-regex>
         </path>
      </permitted>
   </statement>
```
(This is the result of an older site-policy XSLT upgrade from UM: https://github.com/craftercms/studio/blob/support/4.1.x/src/main/resources/crafter/studio/upgrade/pipelines.yaml#L735)
And we will end up have both policies:
```
<site-policy>
   <statement>
      <target-path-pattern>/static-assets/.*</target-path-pattern>
      <permitted>
         <path>
            <source-regex>[\(\)]</source-regex>
            <target-regex>-</target-regex>
         </path>
      </permitted>
   </statement>
   <statement>
      <target-path-pattern>/(?!scripts/.*|templates/.*|static-assets/app/.*).*</target-path-pattern>
      <permitted>
         <path>
            <source-regex>[\(\)\s]</source-regex>
            <target-regex caseTransform="lowercase">-</target-regex>
         </path>
      </permitted>
   </statement>
   <statement>
      <target-path-pattern>/.*</target-path-pattern>
      <permitted>
         <mime-types>*/*</mime-types>
      </permitted>
      <denied>
         <mime-types>image/svg+xml</mime-types>
      </denied>
   </statement>
</site-policy>
```

As we manually upgraded the BP to studio_version 4.1.2, there should be no such UM applied so we don't have the duplicated statements.

**Comment by sumerjabri** [comment]
@Euquimides please validate that this works as expected in built-in blueprints and marketplace blueprints.
