### ISSUE TITLE
[studio] The API 2 POST `/studio/api/2/sites/{siteId}/policy/validate` should validate the naming of items via DB Query

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6105]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The API 2 POST `/studio/api/2/sites/{siteId}/policy/validate`  should be able to validate naming of items via DB Query to avoid a confusing response. 

The API should first check in the DB that the item exists and with that specific name, then apply the `Project Policy Configuration`.

**Comment by jmendeza** [comment]
Please make folder name check and content name (pages and components) check case-insensitive. Please make sure static-assets, templates, sources and scripts remain case-sensitive.
Also, after receiving the policy engine suggestion, check again there's no name collision.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
