### ISSUE TITLE
[studio-ui][studio] Change the minimum number of characters in a user name to 2

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6106]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The current minimum is 4. This requirement excludes too many real world examples.

### Describe the solution you'd like

Change the minimum number of characters in a user name to 2

**Comment by jmendeza** [comment]
Updated minimum to be 2 characters.
UI needs to be updated to match the restriction

cc @sumerjabri @rart

**Comment by russdanner** [comment]
Confirmed
