### ISSUE TITLE
[docs] Update the Authoring Guide to use XB and Quick Create (modernize)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6109]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The current Authoring Guide is outdated.

### Describe the solution you'd like

Modernize and focus on XB and Quick Edit as the primary means of authoring. Form-based editing should still be there, but don't just focus on the Sidebar, also use the built-in address bar (it can searh/navigate/etc.).

Consolidate into a single article if possible.

**Comment by alhambrav** [comment]
- https://docs.craftercms.org/en/4.1/by-role/author/index.html#via-quick-create
- https://docs.craftercms.org/en/4.1/by-role/author/index.html#editing-a-page
- https://docs.craftercms.org/en/4.1/getting-started/your-first-project/templated.html#adding-a-new-article-page-to-the-project

**Comment by sumerjabri** [comment]
@alhambrav the first two seem to be missing the anchors
