### ISSUE TITLE
[studio] Get Users services - return total of users

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#611]
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/get-users-per-site.html

Add a field "total" that indicates the total of users returned, without "start" and "number" restrictions.

**Comment by sumerjabri** [comment]
Docs updated.

**Comment by dejan-brkic** [comment]
Done PR #588
