### ISSUE TITLE
[studio-ui] Datetime field causes JS console errors regarding missing _dt_tz

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6111]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The datetime control adds an extra field to the content's index.xml that stores it's timezone ({control-name}_dt_tz field). When loading a page with this control active, the JS console throws an error that the field was not found in the content-type definition. 

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Navigate to the Content-Type defintions
3. Modify the Home page content type
4. Add a DateTime Control
5. Go to the home page and modify it so it now has the datetime saved
6. Open developer tools and navigate to Console
7. See JS errors being thrown

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/38a36925-90c8-4ebb-a054-7c7c0be5dfb3)

**Comment by sumerjabri** [comment]
@rart the main issue it's red and scary. If can't be handled elegantly, perhaps a warning is best.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.2-SNAPSHOT`
