### ISSUE TITLE
[docs] Add how to pass parameters in plugins

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6114]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The docs is missing instructions on how to pass parameters to plugins that are installed and how these parameters are used

### Describe the solution you'd like

Add to the docs how to pass parameters to plugins and give an example on how to use those parameters

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/composable/extensions/plugins.html#passing-parameters-to-project-via-plugins

**Comment by russdanner** [comment]
confirmed
