### ISSUE TITLE
[craftercms][search] Improve logging during Upgrade process

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6115]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

While upgrading to version 4.1 there are some logging that came from OpenSearch that overlaps when the Upgrade prompts for user actions.  

Options:

- Delay the upgrade scripts a bit so the OpenSearch loggin happen first and then the upgrade process 

### Steps to reproduce

Steps:

1. Upgrade from 3.1 to 4.1
2. Check the upgrade promtps. 

### Screenshots and/or videos

![Screenshot from 2023-05-22 14-33-09](https://github.com/craftercms/craftercms/assets/6722074/ae3f6cea-6116-4bb9-ad86-ccc2382c8585)

**Comment by jmendeza** [comment]
Added 5s delay after starting Crafter so OpenSearch output don't get in the middle

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.x. Thank you! Closing this ticket.
