### ISSUE TITLE
[docs] The `search_plugins` permission is missing in the docs along with errors in permission variable names

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6117]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `search plugins` permission is not present in the documentation. Also, there has been some changes in the permission variable names such as:

1. `create-site` -> `create_site`
2. `S3 read` -> `s3_read`
3. `S3 write` -> `s3_write`

It is expected that the cited permission along with the changes to the permission variable names, to be present in the documentation.

### Steps to reproduce

Steps:

1. Go to `https://docs.craftercms.org/en/4.1/by-role/system-admin/installation-and-configuration/configuration/studio/global-permission-mappings-config.html#global-permission-mappings-config`
2. See the issue

**Comment by alhambrav** [comment]
- https://docs.craftercms.org/en/4.1/by-role/system-admin/installation-and-configuration/configuration/studio/global-permission-mappings-config.html
- https://docs.craftercms.org/en/4.1/reference/project-tools/studio/permission-mappings.html

**Comment by Euquimides** [comment]
Hi! Fix verified for Crafter v4. Thank you! Closing this ticket.
