### ISSUE TITLE
[engine] Add an alias to `search` from `elasticsearch`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6118]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The current search goes to /api/1/site/search/search, breaking older applications.

### Describe the solution you'd like

Add an alias from /api/1/site/elasticsearch/search to /api/1/site/search/search

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
