### ISSUE TITLE
[all] Upgrade OpenSearch to 2.8.0

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6119]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

OpenSearch has released version 2.8.0.

### Describe the solution you'd like

Please upgrade 4.1.0 to the latest OpenSearch.

- [x] Upgrade the core systems
- [x] Upgrade Docker Compose

**Comment by yacdaniel** [comment]
Verified in `4.1.0-SNAPSHOT`.
