### ISSUE TITLE
[studio] Get Groups services - return total of groups

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#612]
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-groups-per-site.html
http://docs.craftercms.org/en/latest/developers/projects/studio/api/group-management/get-users.html

Add a field "total" that indicates the total of groups/users returned, without "start" and "number" restrictions.

**Comment by sumerjabri** [comment]
Docs updated.

**Comment by dejan-brkic** [comment]
Done PR #588
