### ISSUE TITLE
[studio][studio-ui] Pending approval and schedule for publish showing info of the last modifier of the item instead of the current one

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6122]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When sending for either pending approval or schedule for publish an item, the dashlet will show the info of the last modifier of the item as the one that made the action instead of the current user who executed the action. 

The expected result is for the APIs `studio/api/2/dashboard/content/pending_approval` and `/studio/api/2/dashboard/publishing/scheduled` to include maybe a field that indicates the user who edited the item. 

### Steps to reproduce

Steps:

1. Create a new Project. 
2. Create two different users: `userA` and `userB`
3. Edit an item as `userA`
4. Log out as `userA`. 
5. Log in as `userB`.
6. Go to Dashboard and do a Request Publish of the item edited by `userA`.
7. See the issue

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/9d0ca081-d5cf-42df-a3de-3ce460715b53

**Comment by sumerjabri** [comment]
@jmendeza let's discuss the API design when you're ready to tackle this issue.

**Comment by jmendeza** [comment]
@sumerjabri we talked about also adding the submission date to the response, but I noticed we don't have that in the DB. We could discuss if it is worth it to add `submissionDate` to the `Workflow` table.

Added workflow submitter to `DetailedItem` and `SandboxItem`
Made creator, modifier and lockOwner Person objects instead of just the username

cc @rart @jvega190

**Comment by sumerjabri** [comment]
@jmendeza I think we should add the submission date to the DB.

**Comment by jmendeza** [comment]
Added `submitted_on` column to Workflow table.
It now maps to `dateSubmitted` in SandboxItem and DetailedItem responses

**Comment by jvega190** [comment]
@jmendeza the submitter field is returning null in the `Scheduled for Publish` dashlet when an admin user is the submitter. It does have a value in the `Pending Approval` dashlet.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
