### ISSUE TITLE
[studio] Restrict file formats for videos uploaded via the transcoded-video datasource

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6124]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Currently, the only way to restrict video formats into studio is via the Project Policy Configuration, but that only restricts videos uploaded into studio and not uploaded to connected S3 buckets.

### Describe the solution you'd like

The ability to limit the acceptable file formats for the data source "video-S3-transcoding" (transcoded-video).

**Comment by russdanner** [comment]
@sumerjabri @russdanner @rart Let's discuss this to determine how data sources should interact with the policy engine

**Comment by sumerjabri** [comment]
Form Engine 2 will handle this.
