### ISSUE TITLE
Add notes of how to run upgrade scripts in Docker

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6132]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The documentarion and the `docker-compose` project readme are missing docs on how to run the ugprade scripts, for example while upgrading from 4.0 to 4.1 the docs only mention to change the docker image tags but in this case the user still needs to call to the upgrade scripts to reindex and recreate the Deployer targets. 

### Describe the solution you'd like

Please document a few manual steps to cover those scenarios

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/system-admin/upgrade/upgrading-container.html
