### ISSUE TITLE
[docker-compose] Search in authoring container gets killed when delivery is started

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6133]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using docker-compose, and you start authoring, then start delivery, the search in authoring gets killed once the search in delivery is up.

### Steps to reproduce

Steps:

1. Clone [docker-compose](https://github.com/craftercms/docker-compose)
2. Start authoring
3. Start delivery
4. Notice in the logs that once delivery is started, the search for authoring has exited
```
authoring-search-1    | [2023-06-20T18:49:59,543][INFO ][o.o.i.i.MetadataService  ] [0f7426677f8f] Move metadata has finished.
authoring-search-1    | ./opensearch-docker-entrypoint.sh: line 70:   108 Killed                  "$@" "${opensearch_opts[@]}"
authoring-search-1 exited with code 137
```
![Screenshot 2023-06-20 at 2 55 08 PM](https://github.com/craftercms/craftercms/assets/25483966/5411f960-c53f-4ca7-a9f1-a06a2b4365d2)

**Comment by jmendeza** [comment]
@alhambrav This seems to be related to resources. I was able to reproduce when giving Docker 4GB of memory, but not when allocating more (12GB).

By default, we are setting the ` -Xmx` to
- Deployer: 1GB
- Search: 1GB
- Tomcat: 4GB

So 6GB should do for an environment.

@avasquez614 do those numbers look correct?

cc: @sumerjabri
