### ISSUE TITLE
[studio-ui] Recoloring Icons in the Left Nav Tree does not work in new versions

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6135]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Previously, users were able to recolor the icons located in the left tree navigation but are unable to anymore. https://docs.craftercms.org/en/4.0/site-administrators/studio/user-interface-configuration.html?highlight=color 

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Follow the documentation here to change the colors of the Icons in the Left Tree Nav https://docs.craftercms.org/en/4.0/site-administrators/studio/user-interface-configuration.html?highlight=color#navigator-widgets-styling-options 
3. See that the Icon color is not changed

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

N/A

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Please notice that the documentation needs some changes regarding the icon versions, as indicated in this ticket https://github.com/craftercms/craftercms/issues/6144.
