### ISSUE TITLE
[studio-ui] SVG images are not listed by default when using img-repository-upload data source with the search option enabled

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6136]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

SVG images are not listed by default when using `img-repository-upload` data source with the search option enabled.

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Update the Configuration Policy to enable SVG upload
3. Update `/page/home` content type to `Use Search` on `Existing Images` (`img-repository-upload` data source)
![2023-06-22_09-27](https://github.com/craftercms/craftercms/assets/2996543/029256fc-c28b-4f20-b25d-1c85de5e744e)

5. Upload an SVG file to `/static-assets/images` folder
6. Edit the `Home` page, replace `Hero Image` with the `Existing Images` option
7. See the issue: SVG files are not listed in the search result view
![2023-06-22_09-22](https://github.com/craftercms/craftercms/assets/2996543/1db61a55-da2b-4123-848b-6a03fd883efe)
8. If we open the MIME Types and click the Clear button, the SVG files are displayed
![2023-06-22_09-22_1](https://github.com/craftercms/craftercms/assets/2996543/ced10763-53dc-4716-9c7f-296a69d56f5b)

**Comment by sumerjabri** [comment]
Note:
SVG images are disallowed by many users/customers because they can carry code and allow for some attacks. That's the main reason why much of this is disabled by default.

**Comment by sumerjabri** [comment]
@russdanner when does this need to be looked at? 4.1.1 or 4.1.2 or a future version?

**Comment by jmendeza** [comment]
This is a front end issue. The list of accepted mime-types to search for comes from `img-repository-upload` datasource

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.2-SNAPSHOT`
