### ISSUE TITLE
[studio-ui] XB - item actions fail when performed over empty sections (not stored in model yet)

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6137]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When performing actions like insert component, or moving a component to a section that has just been added into the content-type (not stored in model), the action fails and the item is not added/moved/etc properly.

### Steps to reproduce

Steps:

1. Go to editorial blueprint and edit the feature content-type
2. Add an item selector with a components datasource and select the 'Social Media Widget' as the content type
3. Edit `feature.ftl` and add this: (it may go at the end of the div with class `content`
```
<@crafter.renderComponentCollection $field="{NODE_SELECTOR_FIELD}" />
```
4. Go to preview and select 'Add component' from the Preview tools bar
5. Add a social media widget into any of the features
6. See the issue

**Comment by jvega190** [comment]
@Euquimides assigning it to you for validation. Please let me know if you need any details.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
