### ISSUE TITLE
[studio][bps] Headless blog bp doesn't persist updated content via XB update

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6138]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In the headless blog bp, when dragging/dropping an image, or updating a piece of text using XB, and navigating in the bp (changing an author, or post for example) and coming back to the updated item, the image/text has an outdated value. If the preview page is refreshed, the items are properly updated.

### Steps to reproduce

Steps:

1. Go to a site based on headless blog bp
2. In preview, click on Authors > Joe Bloggs
3. Make an edition to the author, for example, drag an image into the `photo_s` field.
4. Navigate to Jane Doe
5. Go back to Joe Bloggs
6. See the image has the old value

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
