### ISSUE TITLE
[studio] Add a cache buster to studio plugin browser resources

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6139]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The browser sometimes caches plugin javascript, CSS, and other assets that comprise a Studio plugin. 

Example:
The following UI Config:
```
<widget id="org.rd.plugin.uigoodies.openContentUploadPanelButton">
    <plugin
      id="org.rd.plugin.uigoodies"
      site="{site}"
      type="apps"
      name="uigoodies"
      file="index.js"
    />
    <!-- optional parameters -->
    <configuration>
        <title>Upload Content</title>
        <icon id="@mui/icons-material/FileUploadRounded"/>
        <defaultPath>/site/components/headers</defaultPath>
        <allowPathSelection>true</allowPathSelection>
    </configuration>
</widget>
```
Generates the following resource request:
```
https://SOMESERVER/studio/1/plugin/file?siteId=ASITEID&type=apps&name=uigoodies&filename=index.js&pluginId=org.rd.plugin.uigoodies
```
This URL is the same no matter what revision is installed, which leads to browser caching issues when newer versions are installed on top of older ones.

### Describe the solution you'd like

The system should provide a plugin version-based cache-busting scheme and "framework" to ensure that the latest code for the plugin is always loaded after an upgrade of the plugin.

**Comment by russdanner** [comment]
Possible workaround (not advised unless necessary)

Change the filename attribute in the ui.xml plugin declaration to include a unique parameter and value as shown below:
`file="index.js&amp;pv=1"`

**Comment by jmendeza** [comment]
Fixed so PluginController does not set the default cache control headers.
Etag + headers from engine will handle caching
