### ISSUE TITLE
[studio-ui] Please remove site filtering on the user management view

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#614]
Please remove site filtering on the user management view as shown in this screenshot:
![screen shot 2017-03-20 at 11 14 09 am](https://cloud.githubusercontent.com/assets/3931908/24106511/72a0aa02-0d5e-11e7-9e1e-4cec84918762.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/304
