### ISSUE TITLE
[studio-ui] Browse Files Dialog not working properly with pages

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6140]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using Browse Files Dialog with pages paths, the left tree doesn't render properly.

### Steps to reproduce

Steps:

1. Go to an editorial based blueprint
2. Add an item selector to a content-type and use a shared-content datasource pointing to `/site/website`. Enable browse on the datasource.
3. Open a paged based on the edited content-type and click on Browse for the item selector
4. See the issue at the left tree (not rendering)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
