### ISSUE TITLE
[docs] Update `icon id` version in `User Interface Configuration` documentation sample

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6144]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Please update the `icon id` version in `User Interface Configuration` documentation sample. It should be `@mui/icons-material/InsertDriveFileOutlined` instead of `@material-ui/icons/InsertDriveFileOutlined`.

### Steps to reproduce

Steps:

1. Go to https://docs.craftercms.org/en/4.1/site-administrators/studio/user-interface-configuration.html?highlight=color
2. Go to a site or project of your choice.
3. Follow the example of the documentation.
4. See the issue
5. Now correct the `icon id` from `@material-ui/icons/InsertDriveFileOutlined` to `@mui/icons-material/InsertDriveFileOutlined`

### Screenshots and/or videos

![Screenshot from 2023-06-30 15-52-47](https://github.com/craftercms/craftercms/assets/90878288/b85122ad-ddd2-4f2d-8d51-68c7b6d7d8d3)

**Comment by alhambrav** [comment]
- https://docs.craftercms.org/en/4.0/site-administrators/studio/user-interface-configuration.html
- https://docs.craftercms.org/en/4.1/reference/project-tools/studio/user-interface-configuration.html

**Comment by Euquimides** [comment]
Hi @alhambrav ! While checking this ticket, I noticed that the the `widget id` in the Dashboard explanation of the `User Interface Configuration` page, `craftercms.components.Dashboard`:
```
<widget id="craftercms.components.ToolsPanel">
  <configuration>
    <widgets>
      <widget id="craftercms.components.ToolsPanelEmbeddedAppViewButton">
        <configuration>
          <title id="words.dashboard" defaultMessage="Dashboard"/>
          <icon id="@mui/icons-material/DashboardRounded"/>
          <widget id="craftercms.components.Dashboard"/>
        </configuration>
      </widget>
```
Is not updated to the current one being used by the `ui.xml`, which is `craftercms.components.SiteDashboard`:
```
<version>4.1.0</version>
    <widget id="craftercms.components.ToolsPanel">
        <configuration>
            <widgets>
                <widget id="craftercms.components.ToolsPanelEmbeddedAppViewButton">
                    <configuration>
                        <title id="words.dashboard" defaultMessage="Dashboard"/>
                        <icon id="@mui/icons-material/DashboardRounded"/>
                        <widget id="craftercms.components.SiteDashboard"/>
                    </configuration>
                </widget>
```
Please check this out. Thanks!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
