### ISSUE TITLE
[studio] Get users per site bug

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#615]
/studio/api/1/services/api/1/user/get-per-site.json for a site with a single user returns "total" : 5. It seems to return the number of groups instead of number of users.

`{
"users": [
  {
"last_name": "Jabri",
"groups": [
  {
"group_name": "Developer"
}
],
"first_name": "Sumer",
"email": "sumer.jabri@craftersoftware.com",
"username": "sumer"
}
],
"total": 5
}`

**Comment by dejan-brkic** [comment]
Done PR #589

**Comment by sumerjabri** [comment]
The number of users is now being returned correctly, but it's returning ALL the groups the user is in, and not just the groups in the site `site_id`.

To reproduce:
- Create several sites
- Create a user "joe"
- Add the user to one of the sites, say `asdff`
- Call the API with `site_id = asdff`

The result:
`{
"users": [
  {
"last_name": "admin",
"groups": [
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "crafter-admin"
},
  {
"group_name": "crafter-create-sites"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
},
  {
"group_name": "Admin"
}
],
"first_name": "admin",
"email": "evaladmin@example.com",
"username": "admin"
},
  {
"last_name": "Doe",
"groups": [
  {
"group_name": "Admin"
}
],
"first_name": "Jane",
"email": "jane@example.com",
"username": "joe.doe"
}
],
"total": 2
}`

You'll note the user `admin` is a member of the group `admin` in _all_ the site, and hence the groups are listed under admin are numerous. It should only list the one `admin` group in the site `asdff`.

**Comment by dejan-brkic** [comment]
Done PR #608
