### ISSUE TITLE
[studio-ui] Item treated as locked for me when sorting using XB

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6152]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When sorting an item using XB, after a couple of sorting actions the page gets locked (as when is it locked by someone else) and it causes a refresh ending up with a failed sort.

### Steps to reproduce

Steps:

1. Go to editorial based site
2. Go to the features sections and sort the features using XB
3. The second/third time you sort the preview will refresh and the sorting will fail

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4. Thank you! Closing this ticket.
