### ISSUE TITLE
[studio] Cut & Paste content does not carry over the content's history

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6153]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using the Cut & Paste functionality for content in studio, the history of the content is not carried over to the new location causing all history to be lost.

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Under `/site/website` create a new folder
3. Right-click edit the Entertainment landing and make a simple change to build up history (can repeat a few times to build up history)
4. Once the landing page has a built-up history, right-click and view the history to see all of your changes
5. Right-click cut the landing page and paste it in the new folder you created
6. Go into the folder you created and right-click view the history of the content
7. Notice your built-up history is not thereto 

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

Before Move: ![image](https://github.com/craftercms/craftercms/assets/42217570/57291cb2-e714-4d45-9954-5ce7fa09ef7c)

After Move: 
![image](https://github.com/craftercms/craftercms/assets/42217570/47d96251-0e17-46d3-a3df-a1c63a535307)

**Comment by jmendeza** [comment]
Added v2 content item history API: `/content/item_history`
It will follow content item renames and return a list of item versions:
```
        {
            "versionNumber": "ed556ab179b82dac75ef68d3412609b59b9f3aa2",
            "path": "site/website/test3/health/index.xml",
            "oldPath": "site/website/test3/health/index.xml",
            "author": "admin admin",
            "comment": "\"User admin wrote content /site/website/test3/health/index.xml\"\n",
            "reversible": true,
            "modifiedDate": "2023-08-11T18:51:00Z"
        },
```
Note that:
- oldPath might be different when the item version is a rename. This value should be used (if different) when displaying the diff page (/studio/diff), which now supports a new `oldPath` parameter.
- reversible indicates if a revert to the version would be allowed (currently we don't support reverting to a version before most recent rename)

UI to be updated to use this new API, use oldPath when necessary and block reverting to versions with `reversible`=false

**Comment by sumerjabri** [comment]
@rart heads up, the flag to indicate the version can be reverted to will become `revertable`

**Comment by jmendeza** [comment]
@sumerjabri as per last discussion, the flag will be `revertible` 
cc @rart

**Comment by sumerjabri** [comment]
All yours @rart

**Comment by rart** [comment]
@sumerjabri @jmendeza the `author` field, would it make sense for that to rather be the username? Or a person object. But overall, something more traceable to a user record? Name is nice a readable but hardly a localizer/identifier.

**Comment by sumerjabri** [comment]
```
{
            "versionNumber": "ed556ab179b82dac75ef68d3412609b59b9f3aa2",
            "path": "site/website/test3/health/index.xml",
            "oldPath": "site/website/test3/health/index.xml",
            "author": Person (object),
            "committer": "admin admin",
            "comment": "\"User admin wrote content /site/website/test3/health/index.xml\"\n",
            "reversible": true,
            "modifiedDate": "2023-08-11T18:51:00Z"
        },
```

**Comment by jmendeza** [comment]
Updated:
committer: author according to git log
author: Person object, corresponds to Studio user when available (when audit table contains the commitId AND the origin of the operation was Studio API)

**Comment by jvega190** [comment]
@jmendeza per conversation, let's update `get_configuration_history` API's reponse to be the same as the new `/content/item_history` API

**Comment by jmendeza** [comment]
@jvega190 PR sent to update `get_configuration_history` API to behave the same as item_history

**Comment by AndyReiter** [comment]
Confirmed fixed in latest build of Crafter Develop:
Version Number:
4.1.2-SNAPSHOT-f12253
Build Number:
f1225393a398158587ddf61b67e7c3778de2a09a
Build Date:
9/8/2023, 11:11 AM
