### ISSUE TITLE
[studio][all-bps] Update blueprints to display "Project" in the Navigation Menu Panel

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6157]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The Navigation Menu panel displays `Site` instead of `Project`

<img width="878" alt="Screenshot 2023-07-17 at 8 30 02 AM" src="https://github.com/craftercms/craftercms/assets/25483966/1f33c811-245c-467f-8b78-347bfe6e501c">

Please update all bps to display `Project` in the Navigation Menu panel

### Steps to reproduce

Steps:

1. Create a project using any blueprint (marketplace or otherwise)
2. Click on the Navigation Menu at the top right
3. Notice it says `Site`

<img width="868" alt="Screenshot 2023-07-17 at 7 23 23 AM" src="https://github.com/craftercms/craftercms/assets/25483966/9e73b0b4-e192-44a8-bba2-c61253467aef">

**Comment by jvega190** [comment]
@alhambrav PRs are merged, just need to verify that marketplace ones are published

**Comment by alhambrav** [comment]
Verified fixed
