### ISSUE TITLE
[studio-ui] Upload files from RTE insert link option throw an error

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6159]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Some users would like to upload documents such as MS Word, and Excel to the RTE via the Insert Links option but the feature is not available

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Update the `Home` content type to add a `file-desktop-upload` data source and use it for RTE File Manager

![2023-07-19_20-12](https://github.com/craftercms/craftercms/assets/2996543/c9d058a4-e234-459f-b887-e6e9d838b8d2)

3. Edit the Home page and choose to Insert Link > Documents
4. See the error that the user cannot upload files

![2023-07-19_20-13](https://github.com/craftercms/craftercms/assets/2996543/f167f3fd-aaad-49ac-9dee-1879e56dae5d)

**Comment by yacdaniel** [comment]
Hi @jvega190 

I'm still not able to upload a file through the RTE from the datasource `file-desktop-upload`

Please take a look.

**Comment by rart** [comment]
@jvega190 the PR doesn't seem to do any exception handling per se. Confirm you managed to reproduce and the PR indeed addresses it.

**Comment by jvega190** [comment]
@rart the issue was that the `file-desktop-upload` datasource was expecting a dropdown (the one the FE uses) to be in the dom, then creates an entry for the dropdown so when you click it shows the upload dialog. What the fix does it to check if the dropdown exists, if not then it proceeds to directly open the upload dialog.

**Comment by phuongnq** [comment]
verified!
