### ISSUE TITLE
[studio-ui] Add spinner to forgot password

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#616]
Please add a wait spinner and disable the "Submit" button to the forgot dialog UI where the user clicks on the "Submit" button of the "Recover" dialog because the API call is slow (it sends out the email before returning).

Right now if you click "Submit" the button is available for them to click again and the UI doesn't let the user know that action is being taken.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/346
