### ISSUE TITLE
[studio][deployer] Optimize Upgrade Manager configuration loading

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6160]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When there are many sites, Upgrade Manager increase boot time.
This is aggravated by the UM loading the `pipelines.yaml` file several times (per site, per pipeline)

See
https://github.com/craftercms/studio/blob/aa50a6f56358fa79ca3565cb2cd5eee2b2df5039/src/main/java/org/craftercms/studio/impl/v2/upgrade/StudioUpgradeManagerImpl.java#L298

https://github.com/craftercms/commons/blob/develop/upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java#L111

### Describe the solution you'd like

Extract the actual configuration file loading to an independent configuration provider shared by all the different components of UM process. This configuration provider will load and parse the `pipelines.yaml` file only once.

**Comment by yacdaniel** [comment]
Verified UM continues to work and boot time decresed around 40-60%.

With 10 sites time reduced in UM jobs from `2.8` to `1` seconds.

With 20 sites the UM boot time reduced from `5.8` to `2.3` seconds

And with 30 sites from `7.3` seconds to `4.5`
