### ISSUE TITLE
[studio-ui] Node selector UI not usable if options are too numerous

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6161]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Node selector UI is not usable if options are too numerous 

### Steps to reproduce

Steps:

1. Create a new site from the following BP: https://github.com/phuongnq/craftercms-node-selector-ui-not-usable (This BP is created from Editorial BP, in the Home page, we added data sources for the header to be created by more than 15 components from test1...test15)
2. Edit the Home page
3. Click `Add` to the Header element
4. Notice that the menu is cut-off, there is no way to display the full list

### Screenshots and/or videos

![2023-07-21_09-07](https://github.com/craftercms/craftercms/assets/2996543/adf24645-d509-473d-ac95-017b3bb80ca1)

**Comment by rart** [comment]
@jvega190 let's see if we can constraint the height of the drop down/up and for it to have a scroll; like mui dropdowns

**Comment by phuongnq** [comment]
verified
