### ISSUE TITLE
[studio] Crafter is not deleting the blob file when a published asset is deleted

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6163]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

We encountered an issue when deleting a published static asset from studio UI, it doesn't properly remove the related blob file from the published git repository. We were able to reproduce the error in the editorial site using Crafter 4.1.0

### Steps to reproduce

Steps:

1. Create a site using the editorial blueprint.
2. Edit the blobstore configuration file like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<blobStores>
    <blobStore>
        <id>s3-default</id>
        <type>s3BlobStore</type>
        <pattern>/static-assets/documents/.*</pattern>
        <mappings>
            <mapping>
                <publishingTarget>preview</publishingTarget>
                <storeTarget>your-authoring-bucket</storeTarget>
                <prefix>sandbox</prefix>
            </mapping>
            <mapping>
                <publishingTarget>live</publishingTarget>
                <storeTarget>your-delivery-bucket</storeTarget>
                <prefix>live</prefix>
            </mapping>
        </mappings>
        <configuration>
            <region>us-east-1</region>
            <pathStyleAccess>true</pathStyleAccess>
            <credentials>
                <accessKey>xxxxxxxx</accessKey>
                <secretKey>xxxxxxxx</secretKey>
            </credentials>
        </configuration>
    </blobStore>
</blobStores>
```

3. Create a folder called "documents" under "static-assets"
4. Upload a PDF file in the just created documents folder
5. Publish the PDF document
6. Check the published repo, it shows the related .blob file for the document
7. Check the S3 bucket, the file got uploaded under live/static-assets/documents
8. From Studio UI, delete the published document
9. Check the published repo, it still shows the related .blob file
10. Check the S3 bucket, the binary file is still in the live folder

The following log indicates that the publish is skipped by some checking condition:

### Relevant log output

```shell
[WARN] 2023-07-26T09:18:30,358 [studio.clockTaskExecutor-29] [deployment.PublishingManagerImpl] | Item in site 'ed' path '/static-assets/documents/sample.pdf' doesn't exist in the database nor the git repository. Skipping publishing of this item.
```

**Comment by jmendeza** [comment]
Updated to handle rename and cut-paste scenarios

**Comment by yacdaniel** [comment]
Verified fixed.
