### ISSUE TITLE
[studio-ui] XB buttons are not role aware

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6165]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Some of the buttons on XB's zone menu don't apply to all roles.

### Describe the solution you'd like

Buttons should be rendered based on permissions and AA

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1. Thank you! Closing this ticket.
