### ISSUE TITLE
[docs] Duplicated content in Architects Role documentation page

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6167]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In the Architects Role documentation page (https://docs.craftercms.org/en/4.1/by-role/architect/index.html) contains content that seems to be duplicated. For example, `Inheritance` and `Security` sections are duplicated. 

### Steps to reproduce

Steps:

1. Go to https://docs.craftercms.org/en/4.1/by-role/architect/index.html
2. Scroll down to `Inheritance`, then keep scrolling.
3. See the issue

**Comment by alhambrav** [comment]
Consolidated dupes into a general concept area:
https://docs.craftercms.org/en/4.1/by-role/architect/index.html#content-inheritance
https://docs.craftercms.org/en/4.1/by-role/architect/index.html#security

**Comment by Euquimides** [comment]
Hi! Fix verified for Crafter Docs v4.1.2. Thank you! Closing this ticket.
