### ISSUE TITLE
[studio] Save content error with users without unlock permission

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6168]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When logged in as a user without unlock permission (for example `author`), and editing content via form or XB, an error occurs when saving changes, but the content gets saved.

### Steps to reproduce

Steps:

1. Login as an author user (or any user with write permission and without unlock permission)
2. Go to a site based on editorial.
3. Right click on `Home` page and edit
4. Edit some content and save.
5. See the error. (If you reload you'll see the changes)

### Relevant log output

```shell
https://gist.github.com/jvega190/98acc3bcbffc6798719b2962b6e12673
```

**Comment by jmendeza** [comment]
Fixed PermissionOrOwnership permission

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified Crafter v4. Thank you! Closing this ticket.
