### ISSUE TITLE
[studio-ui] Publishing by commit ID dialogue is inconsistent

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6170]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When publishing recently pulled-in changes via the git tool in Studio, a dialogue appears asking whether or not we would like to publish the recently pulled-in Commit ID. When you select the "Yes" option (see screenshot), the publish by commit ID dialogue opens up with the proper commit ID auto-filled in but the Target option does not have an option auto-filled, unlike it does when normally selecting Publish by Commit ID. 

### Steps to reproduce

Steps:

1. Create an empty site
2. Navigate to Site Config and enable the Staging Environment
3. Navigate to the Git tool in Site Tools
4. Add a new repository
5. Pull in the changes from the repository, and notice the dialogue in the bottom left (see screenshot)
6. Click yes 
7. After clicking yes, the publish by commit ID dialogue pops up but notice the "Publishing Target" has no option selected
8. Click Publish
9. Notice the dialogue and page freezes

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/fb0b1773-7605-4ed9-9d67-928de7a9a193)

https://www.loom.com/share/390013cefd474178aa5918ac7feef183

**Comment by AndyReiter** [comment]
Looked at this with @jvega190 and we found that there was a missing step in the reproduction for this issue, the Staging environment must be enabled via Site Config.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The specific UI issue in the `Publishing Target` field of the `Publish Commit` dialogue is fixed (which was the theme of this ticket), but the issue with the freeze still persist. Since this might be related with the backend, I created an specific ticket for it. You can follow it in the ticket https://github.com/craftercms/craftercms/issues/6183.
