### ISSUE TITLE
[studio-ui] Allow new languages to be added and used globally (not site-specific)

### ISSUE THREAD

**Issue by faveg** [craftercms/craftercms#6171]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

version 4.1, trying to add localization, similar to 3.1 (https://github.com/craftercms/docs/blob/3.1/source/system-administrators/activities/language-support/add-new-language.rst) but nothing does not work, except for the language selection menu, but the choice does not affect anything.

**Comment by rart** [comment]
@faveg what language(s) were you trying to add?

**Comment by rart** [comment]
Currently, to add **new** languages in 4.x the process would be:
1. In Studio, [add language to the get available languages api](https://github.com/craftercms/docs/blob/3.1/source/system-administrators/activities/language-support/add-new-language.rst#3-add-the-new-language-to-the-get-available-languages-api).
2. In Studio UI, add your new locale files to `ui/app/src/translations`. You may start by copying `en.json` and translating it into your target language.
3. Open `ui/app/src/utils/i18n.ts` and add the locale code to `createIntlInstance` conditional statement, and add the switch statement case to `fetchLocale`.
4. Rebuild

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/common/adding-a-new-language.html
