### ISSUE TITLE
[studio-ui] Row and Column settings for Text Area field has no effect

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6173]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In older versions of Crafter, you were able to set the size of the Text Area by providing a desired size for the Row and Column. Now in current versions, setting these values has no effect.

### Steps to reproduce

Steps:

1. Create a site
2. Add a Text Area to a Content Type
3. Set values for the Rows and Columns
4. Edit the form in Studio
5. See the Text Area does not reflect desired settings

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/85725a9b-a509-46f0-bad6-fff5cc305ecc)

![image](https://github.com/craftercms/craftercms/assets/42217570/034edc6c-dc10-44fe-adc5-d2152d907271)

**Comment by rart** [comment]
@russdanner should we remove the width (cols) just like we did with the RTE. The meaningful one is the height (rows).

**Comment by sumerjabri** [comment]
@rart yes, let's do that.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.2-SNAPSHOT`
