### ISSUE TITLE
[docker] Proxy not working properly with Next.js

### ISSUE THREAD

**Issue by iagochaves-encoura** [craftercms/craftercms#6174]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

I've set up a new Next.js app on my crafter that is containerized. Due to docker networking, I'm facing some issues while trying to proxy the app. I can load the app, but I'm not being able to keep the proxy connection (hot reload not working). Crafter keeps saying that Communication with the preview application was interrupted.

This is how I set up my crafter docker:
```shell
...
  tomcat:
    container_name: tomcat-new
    image: craftercms/authoring_tomcat:4.1.1 # craftercms version flag
    depends_on:
      - search
      - deployer
    ports:
      - 8080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      # Search dirs needed for backup/restore
      - search_data:/opt/crafter/data/indexes
    environment:
      - DEPLOYER_HOST=deployer
      - DEPLOYER_PORT=9191
      - ES_HOST=search
      - ES_PORT=9200
    extra_hosts:
      - "host.docker.internal:host-gateway"
...
``` 

And the proxy config:
```html
...
 <server>
         <id>preview</id>
         <url>http://host.docker.internal:3000</url>
         <patterns>
            <pattern>.*</pattern>
         </patterns>
      </server>
...
``` 

What's interesting is that I tested this same setup with Vite.js and using react-scripts (CRA) and the proxy worked fine (hot reloading).

With Nextjs, I had to change the dev script to the following:
`"dev": "next dev -H 0.0.0.0"`
This doesn't make sense because 0.0.0.0 is the default for the hostname but I had to specify this otherwise the proxy wouldn't work.

I'm using WSL2 (Win 11) - Ubuntu

Also tried some suggestions in this old issue https://github.com/craftercms/craftercms/issues/4820

### Steps to reproduce

Steps:

1. Run crafter on docker
2. Create a sample next.js app
3. Set up the proxy config with next.js ( either with network IP or using `host.docker.internal`)
4. See that the app actually loads, but the connection is immediately lost and we need to refresh the page to see any changes on the app

**Comment by phuongnq** [comment]
This has been fixed with websocket proxy

**Comment by sumerjabri** [comment]
Superseded by https://github.com/craftercms/craftercms/issues/6292 which is targeted for 4.1.3 and 4.2.0.
