### ISSUE TITLE
[studio-ui] Remove the maximum width on the sidebar

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6175]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Users want near full control over how wide the sidebar is but today it has a hard limit on the maximum width.

### Describe the solution you'd like

Allow them to grow the sidebar to 80-90% of the preview screen.

**Comment by rart** [comment]
@jvega190 let's remove the hard limit and add a dynamic one. 
- The combined expanded width of the 2 sidebars should still leave the preview frame minimum width of 350px. 
- Consider:
  - If edit mode is off and the left sidebar is grown to the max, then edit mode recalculate factoring in the right sidebar. 
  - The left side bar is closed, the right sidebar is grown to the max, then open left side bar
  - If the window is resized

We need to proportionally recompute width of both sidebars on these scenarios.

**Comment by russdanner** [comment]
Confirmed
