### ISSUE TITLE
[studio-ui] Studio Search fails when searching with Special Characters

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6176]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When using the Search function in Studio and adding an input that contains special characters, such as `$ ' @ % ( ) ! # &`, the search fails making it not possible for users to search for content.

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. In the top right of your screen, click the Search
3. Attempt to search for a string with a Special Character, such as `Here's an example`
4. Notice the search fails

### Relevant log output

```shell
https://gist.github.com/AndyReiter/c02f9baaa2b85510d1e5707b88787d0f
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/146b1928-30d9-4026-8f1e-e7e9dfb1c676)

**Comment by russdanner** [comment]
Search terms should be URL encoded when call the API

**Comment by rart** [comment]
> Search terms should be URL encoded when call the API

The `keywords` param, is part of an `application/json` **POST body**. These are not QS args nor are we posting as `application/x-www-form-urlencoded`. Why would we url-encode here? @russdanner 

@jmendeza you can confirm any backend handling but I don't think this kind of POST body should be url encoded.

**Comment by jmendeza** [comment]
@rart I think you're right, I don't think there is a UI side for this issue

Updated default search keywords validation regex to allow:
```!@#$%&```

Also updated the default regex (and made it configurable) the search service use to split and extract the individual keywords. Default value will remove the special chars from above
```
studio.search.keyword.split.regex: "[!@#$%&\\*\\s\\(\\)\\'\\\"]+"
```

**Comment by AndyReiter** [comment]
Confirmed in latest build of Crafter Develop: 

Version Number:
4.1.2-SNAPSHOT-f12253
Build Number:
f1225393a398158587ddf61b67e7c3778de2a09a
Build Date:
9/8/2023, 11:11 AM
