### ISSUE TITLE
[studio-ui] Make the magnifying glass always 'active' in a given nav tree

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6179]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

While exploring in the site, it was noticed that the magnifying glass (from here on 'mag glass') only appeared when you open a dropdown item. However, when you CLOSE that dropdown item the mag glass remains. 

### Describe the solution you'd like

It could be nice to always have the mag glass as an option without needing to do the extra click of opening the dropdown item.

**Comment by rart** [comment]
@jvega190 the only change is for the mag glass to show even if the tree hasn't been opened. I believe this is legacy from when we didn't know if items had children but now we can simply see if the item has children from the SandboxItem prop before showing, but no need for prior expansion.

**Comment by russdanner** [comment]
The change is that you can start a filter before a child folder is open. It will open the child and begin filtering. 
Another way to say this is that an unopened node will show the mag glass. There is no need to perform an extra click (to open the node) in order to start filtering.

Confirmed.
