### ISSUE TITLE
[studio-ui] Add text to the Users screen

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#618]
Please add the text:

> To add a user to a group/site, please use the admin console for the site.

to the Users screen as shown in the screenshot:
![screen shot 2017-03-20 at 1 46 26 pm](https://cloud.githubusercontent.com/assets/3931908/24113945/d5747cd8-0d74-11e7-884d-1d6dae294b51.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/304
