### ISSUE TITLE
[studio] Bulk publish incorrectly calculates dependencies

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6181]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [x] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you bulk publish a path any and all dependencies regardless of direction are included in the publish if the state of the dependency is unpublished.

### Steps to reproduce

Steps:

1. Create a site based on editorial (in CrafterCMS 4.0.5+)
2. Publish everything
3. Duplicate a page and a template
4. Edit a page and a template
5. Bulk publish /templates and note that items under /site are included even though they should not be.

We did notice in one instance that an item that was marked in a live state was also included in the calculation but we are not able to reproduce this.

**Comment by russdanner** [comment]
This issue was seen in 4.0.5 and was not reproduced in 4.1.0 with basic use cases.

**Comment by sumerjabri** [comment]
@Euquimides please see if there is a way to reproduce this issue or similar in 4.1.

CC @yacdaniel

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/4566

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for both Crafter v4.0 and v4.1. Thank you! Closing this ticket.
