### ISSUE TITLE
[studio] Configuration for targeting with date-time control does not work

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6182]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The date-time control for targeting configuration does not work

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Update the ui.xml to have the following:

```
<widgets>
    <widget id="craftercms.components.PreviewAudiencesPanel">
        <configuration>
            <fields>
....
                <currentTime>
                    <id>currentTime</id>
                    <name>Date</name>
                    <description>A date sample</description>
                    <type>date-time</type>
                    <helpText>Date time helper text</helpText>
                </currentTime>
            </fields>
        </configuration>
    </widget>
</widgets>
```
3. Notice that the configuration does not work and there is an error in console

### Relevant log output

```shell
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'format')
    at DateTimePicker.tsx:114:47
    at Object.useMemo (react-dom.production.min.js:184:189)
    at n.useMemo (react.production.min.js:25:208)
    at i.Z (DateTimePicker.tsx:111:24)
    at qa (react-dom.production.min.js:167:137)
    at qc (react-dom.production.min.js:290:337)
    at As (react-dom.production.min.js:280:389)
    at Os (react-dom.production.min.js:280:320)
    at zs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
```

**Comment by phuongnq** [comment]
Hi @rart @jvega190 When I print the value in a Groovy script:

```
println profile.attributes.currentTime.getClass()
println profile.attributes.currentTime
```

It prints the following:
```
class java.lang.String
2023-09-20T01&#x3a;10&#x3a;00&#x2b;07&#x3a;00
```

If this is a string, does the value sound correct with characters such as `&#x3a`?

**Comment by rart** [comment]
No. Those chars are not correct they look like they are serializad or url encoded. Not sure if it's a profile/mongo thing something the UI is doing. @jvega190 ?

The value there should be an 8601 ISO string.

**Comment by jvega190** [comment]
@jmendeza we need to update the `setProfile` API to be POST, also, it seems like the values are being encoded causing the issue mentioned by Phil above.

**Comment by jvega190** [comment]
@jmendeza we need to update the [setProfile API](https://docs.craftercms.org/en/4.1/_static/api/engine.html#tag/other/operation/setProfile) to be a POST. Also, it seems like the values are being encoded causing the issue mentioned by Phil above

**Comment by jmendeza** [comment]
@jvega190 
Updated setProfile to use POST and fix escaping of the values.
Request sample: 
```
{
    "username": "Jonathan",
    "currentTime": "2023-10-04T00:00:01-06:00",
    "roles": "dev"
}
```

**Comment by phuongnq** [comment]
verified
