### ISSUE TITLE
[studio-ui] `Publish Commit` dialog freezes when selecting `Publish Target` as `Staging`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6183]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When enabling `Staging` environment in a project, then adding a remote repository via `Git` option in `Project Tools` and pulling from it; if you select `Staging` as `Publishing Target` and then click on `Publish` in the `Publish Commit` dialog, will show and environment related error and freeze the dialog. 

### Steps to reproduce

Steps:

1. Create a new project using Empty BP. 
2. Go to `Project Tools` -> `Configuration`.
3. Enable the `Staging` environment in `Project Configuration` by setting the value to true.
4. Go to `Project Tools` -> `Git`
5. Add a new repository that doesn't have `Staging` enabled. For example: https://github.com/Euquimides/test-empty
6. Pull from the repository, use `Accept Theirs` as `Merge Strategy`.
7. Click on yes in the dialogue with the Commit ID that appears.
8. In the `Publish Commit` dialogue, select `Staging` as `Publishing Target`.
9. Click on `Publish`
10. See the issue

### Screenshots and/or videos

![Screenshot from 2023-08-21 18-12-35](https://github.com/craftercms/craftercms/assets/90878288/e700e6f7-da76-47ed-8f5f-5fd911ac7373)

https://github.com/craftercms/craftercms/assets/90878288/22c65bc2-2cf7-42c4-acf6-0382991fde0a

**Comment by yacdaniel** [comment]
Hi @sumerjabri @jmendeza , we reviewed this and is an UI issue, the BE returns correctly a http 404 when the Environment (Staging) is not found

We are going to assing this to the UI team @rart

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1. Thank you! Closing this ticket.
