### ISSUE TITLE
[studio-ui] Able to click outside the `Publish Commit` dialogue

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6185]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When pulling from a remote repository, if you click on `Yes` in the dialogue with the commit id that appears, a `Publish Commit` dialogue will appear. The user is able to click outside this dialogue, which will close it.

### Steps to reproduce

Steps:

1. Create a new project.
2. Go to `Project Tools` -> `Git` and add a remote repository.
3. Pull from this remote repository selecting a merge strategy as needed.
4. A dialogue with a commit id asking if you want to publish now will appear. Click on `yes`.
5. When the `Publish Commit` dialogue appears, click outside this dialogue. 
6. See the issue

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/72b0e7b5-a846-4b63-bb8e-8602990c635b

**Comment by sumerjabri** [comment]
@rart what do you think we should do here? A click outside this dialog causes data loss from the user's perspective and they cannot get back to what they were doing. Is there a way that this dialog (or class of dialogs) is not dismissable by a click-out?

**Comment by rart** [comment]
@jvega190 the commit id comes as a prop so the data loss confirmation should go off the input value, not the prop. You're ok to dismiss without confirmation if commit id and comment are blank.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.0.8 and v4.1.2. Thank you! Closing this ticket.
