### ISSUE TITLE
[engine] Content elements with attributes and no value are returned as objects when marshaled to JSON in getItem call

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6186]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When an optional _t attribute has default text set, if you clear it, an attribute is added to the attribute in the stored XML document called no-default="true". The item.xml API returns this fine, but the item.json API returns this:
```
"subheadline_t": {
"no-default": "true"
}, 
```
The JSON API should not be returning objects where a string is expected.
If you take away the default text and re-save the item, the JSON API behaves properly.

### Steps to reproduce

Steps:

The issue arises when you have
1. an attribute that is not required
2. default text set
3. actual text value blank

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/926b5023-f09a-4066-9c7d-44401481a526)
![image](https://github.com/craftercms/craftercms/assets/42217570/460f1f25-b7f1-46de-957a-49fab6db243c)
![image](https://github.com/craftercms/craftercms/assets/42217570/cbe39f02-047c-4aa7-86e5-4f4161be6f81)

**Comment by yacdaniel** [comment]
Verified fixed in 4.1.2-SNAPSHOT

![image](https://github.com/craftercms/craftercms/assets/6722074/cdc52640-4a00-4de3-9c25-3b63b73936a1)

`item.json`
` "subheadline_t": null`
