### ISSUE TITLE
[mariadb4j] Upgrade to 10.4.31

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6188]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The MariaDB version is a bit old.

### Describe the solution you'd like

Please update the MariaDB Server to https://mariadb.com/kb/en/mariadb-10-4-31-release-notes/

**Comment by phuongnq** [comment]
Please merge in the following order:
1. Merge MariaDB: https://github.com/craftercms/MariaDB4j/pull/193 and publish to maven. 

To run in local:
```
cd DBs
mvn clean package install
cd ..
mvn clean package install
```
2. Merge https://github.com/craftercms/craftercms/pull/6195 and build new 4.1.2-SNAPSHOT
3. Merge https://github.com/craftercms/docker-images/pull/76 and test with docker image:
```
./gradlew buildAuthoringLocal -PauthoringBundle=/YOUR_CRAFTER/bundles/crafter-cms-authoring-4.1.2-SNAPSHOT-linux-x86_64.tar.gz -Ptag=4.1.2-SNAPSHOT
docker run -p 8080:8080 craftercms/authoring_local:4.1.2-SNAPSHOT
```

**Comment by sumerjabri** [comment]
@phuongnq we're upgraded to 10.4.31 for Linux. It seems we're still on 10.4.20 for Mac, can you see why? (we followed the steps of building the tarball and testing it was 10.4.31, we published that to Maven Central and built Mac from scratch several times.)
