### ISSUE TITLE
Add option to include soft dependencies in bulk publish

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6191]
### Latest version

- [x] The issue is in develop
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When an author publishes they have the option to include soft dependencies. When you use a bulk publish this option is not currently available but is needed in some use cases.,

### Describe the solution you'd like

Add an option to include soft dependencies when bulk publishing. Default the option to false.

**Comment by sumerjabri** [comment]
This needs to happen after we refactor the publisher.

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
