### ISSUE TITLE
[studio-ui] Drop down with simple taxonomy is illegible in dark mode

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6196]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

<img width="1110" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/4ee1cc3a-6741-4f5c-863e-8187c297af1d">

### Steps to reproduce

Steps:

1. Add a dropdown control with simple taxonomy DS and view the form in dark mode

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.2. Thank you! Closing this ticket.
