### ISSUE TITLE
[studio][studio-ui] Add an API to duplicate a project

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6199]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Some DevContentOps use cases would benefit from being able to Create a new project by copying the full state of another project. 

### Describe the solution you'd like

Create an API that creates a new project by copying the repository, index and database state of another project.

**Comment by sumerjabri** [comment]
@jmendeza Please use the very `duplicate` for the copy site API.

**Comment by sumerjabri** [comment]
Solution
=======
- Get Site Info (or similar existing API) return indicates if the site has a blob store
- The UI uses that data to offer the user a choice of using the existing S3 buckets as read-only or read-write with adequate warning on read-write
- Add a flag to the blob-store-config.xml to indicate whether a bucket/store is RO or RW
  - Update the blob store codebase to honor that flag
  - Update AA to remove write operations from blob-backed areas


@alhambrav for docs:
In Copy Site Documentation for Site Admin, indicate that one can copy the S3 bucket(s) and update the configuration if they do want to separate from the source site.

**Comment by sumerjabri** [comment]
Longer term, we want the solution to be:
Users choose:
  - Copy S3 buckets (either provide new buckets or Studio create them)
  - Use existing S3 buckets as read-only
  - Use existing S3 buckets as read-write

The copy S3 buckets will be:
  - Copy the site
  - Update the blob-store configuration to the new buckets
  - Copy the S3 artifacts to the new buckets (can be done by the S3 `sync` feature)
  - Algorithm:
    - Scan the blob-store config, pass that back to the UI the names of the buckets to capture user input
    - Either have the user create the buckets, or we create the new buckets
    - Sync the old buckets to the new buckets
    - Update the blob-store config for the new site

**Comment by sumerjabri** [comment]
@alhambrav This is a new feature we must document. It'll go under Site Admin. (the UI is still under development.)

**Comment by sumerjabri** [comment]
@yacdaniel we can start thinking about test cases for this. 4.1 is in, the UI is still being worked on. Let's also plan on adding this to the API testing suite.

**Comment by sumerjabri** [comment]
4.1 should be ready to test and play with.

**Comment by jmendeza** [comment]
@jvega190 fyi, PRs for 4.0.x backend updates are in place

**Comment by jmendeza** [comment]
Updated Duplicate site APIs (deployer and studio) to be more consistent with the other APIs and also the format we want going forward.
@yacdaniel we also updated deployer target configuration duplicate so yaml config files preserve key ordering

**Comment by russdanner** [comment]
![image](https://github.com/craftercms/craftercms/assets/169432/1083888d-9dbd-44ff-a353-5a140d5d7d1d)
Should we make the duplicate icon bigger? It seems small opposite the Git icon.
@sumerjabri @rart

**Comment by russdanner** [comment]
It looks like the duplicate site copies the workflow states but it should reset them to new
![image](https://github.com/craftercms/craftercms/assets/169432/1c4fd486-e9b1-442f-a6b9-7274b544f6ea)

**Comment by sumerjabri** [comment]
@russdanner please remove yourself from the ticket if happy with the design updates.

**Comment by alhambrav** [comment]
@rart @jvega190

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/modules/studio/administration.html#duplicate-project

**Comment by yacdaniel** [comment]
Verified in `4.1.2-SNAPSHOT` 

Creation Strategy now shows in the Review dialog



![Image](https://github.com/craftercms/craftercms/assets/6722074/a0fe5cd0-4346-4337-993b-201dcc04578f)
