### ISSUE TITLE
[studio-ui] Change site list screen

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#620]
Please change the site list screen to:

1. Use the new API: http://docs.craftercms.org/en/latest/developers/projects/studio/api/site/get-sites-per-user.html
2. Drop the Live Site column
3. Add a Description column where the Live Site link used to be

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/302

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/303
