### ISSUE TITLE
[studio-ui] Create a user preference cache-clearing UI

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6201]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Stored user preferences require advanced knowledge to clear when necessary.

### Describe the solution you'd like

Add a UI to manage/clear individual stored state and all at once.

**Comment by jvega190** [comment]
I'm thinking maybe a 'clear' setting under the `Account` section for the user, and add `removeItem` functions for all of the localStorage settings?

**Comment by sumerjabri** [comment]
Putting this under "Account" is fine by me.
