### ISSUE TITLE
[studio-ui] Make default Preview edit mode on/off configurable

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6203]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Some entities use base capabilities of CrafterCMS other than Preview, inline editing and XB. Defaulting edit mode to off is beneficial for these cases.

### Describe the solution you'd like

(...typing...)

**Comment by jvega190** [comment]
I added a configuration to the site-config.xml file `defaultEditMode`, and put it into the redux state. Then, validate, if there is no localStorage value then I use the default (if exists).
There is a detail, the localStorage for the editMode is global for all sites (`craftercms.${site}.editModeChoice`). So if I have a site with editMode true (stored in localStorage) and I create another one, and add a defaultEditMode, it'll still get the setting from the localStorage.
Should the localStorage key include the site id?

**Comment by sumerjabri** [comment]
2 notes:
- I think this might best be placed in `ui.xml` to continue to centralize most UI configurations there. Perhaps around the preview area.
- I think we *must* make this a project/site thing. Perhaps storing a tuple like: `site:defaultEditMode` or similar?

**Comment by sumerjabri** [comment]
@jmendeza please add this to UM. The elements to be added to `ui.xml` are:
```xml
<widget 
  id="craftercms.components.Preview" 
  initialEditModeOn="true"
  initialHighlightMode="all"
  xbDetectionTimeoutMs="5000"
/>
```

@rart can advise where to add this.

**Comment by russdanner** [comment]
In my current tests, even in a private/incongito browser, I note that the preview tools panel opens by default. This needs to be included in the test when a user's role does not have access to the editing tools.

**Comment by sumerjabri** [comment]
It seems Russ didn't apply the config. Focus on the UM for now.

**Comment by jmendeza** [comment]
Default configuration added to built-in blueprints, sample Ui.xml and UM

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/6217

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified feature was added to Crafter v4.1.2. Thank you! Closing this ticket.
