### ISSUE TITLE
[studio] Update the "sample-engine-site-config.xml" file

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6235]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The properties listed in the [sample-engine-site-config.xml](https://github.com/craftercms/studio/blob/develop/src/main/webapp/repo-bootstrap/global/configuration/samples/sample-engine-site-config.xml) file does not seem to match properties in the Engine  `server-config.properties` for `security.saml` 

<img width="1381" alt="Screenshot 2023-10-02 at 1 44 28 PM" src="https://github.com/craftercms/craftercms/assets/25483966/031f597c-03ad-4c5f-82b9-19e10237ef54">

### Describe the solution you'd like

Please review/update the `sample-engine-site-config.xml` to match current properties

**Properties listed in the sample-engine-site-config.xml file that needs a review/update**
```
 <security>
        <saml>
            <token/> (The expected value for the secure key request header)
            <groups>
                <group>
                    <name/> (The name of the group from the request header)
                    <role/> (The value to use for the role in the profile)
                </group>
            </groups>
            <attributes>
                <attribute>
                    <name/> (The name of the request header for the attribute)
                    <field/> (The name of the field to use in the profile)
                </attribute>
            </attributes>
        </saml/>
        ...
```

**Comment by phuongnq** [comment]
Since the SAML configuration is now per engine instance, I have removed the sample for sample-engine-site-config.xml

**Comment by alhambrav** [comment]
Verified
