### ISSUE TITLE
[studio-ui] Incorrect ICEToolsPanel plugin configuration ends up in infinite loading loop

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6239]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When adding an ICEToolsPanel plugin into the ui.xml configuration file, if the plugin url is incorrect (by setting an incorrect value like name or filename), when clicking on the plugin button it stays loading, and in the console you'll see an endless loop trying to load the plugin file.

### Steps to reproduce

Steps:

1. Go to a site based in editorial
2. Go to Project Tools -> Configuration -> User InterfaceConfiguration
3. Scroll down to the `<widget id="craftercms.components.ICEToolsPanel">` section and add this widget:
```
<widget id="craftercms.components.ToolsPanelPageButton">
  <configuration>
    <target id="icePanel"/>
    <title id="non.existing" defaultMessage="Non-existing plugin"/>
    <icon id="@mui/icons-material/PollOutlined"/>
    <widgets>
      <widget id="org.craftercms.testPlugin.components.test">
        <plugin id="org.craftercms.plugin"
            type="sidebar"
            name="test"
            file="index.modern.js"/>
      </widget>
    </widgets>
  </configuration>
</widget>
```
4. Save and click on the right sidebar button `Non-existing plugin`
5. See error.

**Comment by russdanner** [comment]
Confirmed
