### ISSUE TITLE
[studio-ui] Create projects in background does not refresh Projects screen when done.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6241]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When an user creates/duplciates a Project and send the create Dialog to the background, the UI should indicate or refresh the Projects screen when it received the socket message of finished. 

### Steps to reproduce

Steps:

0. Open Studio websocket . 
1. Create a Project or Duplciate an existing one. 
2. Send the dialog to the background. 
3. Wait until the websocket receives the new event for the project created/duplicated successfully. 
4. Notice that Project's screen do not update. 

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/6722074/5f26a9fa-2157-4f1c-974e-0cca97c606e2

**Comment by rart** [comment]
@jvega190 it looks like the `/create` request is getting cancelled. Probably there's destruction logic on an effect. That shouldn't happen that that we have background creation and the dialog is closable. Any further renders to the dialog should not occur when dismounted.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.2-SNAPSHOT`
