### ISSUE TITLE
Make sure all tests are executed on build

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6243]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When tests are executed, not all tests in the project are executed
e.g.:
```
mvn package test
```
or
```
./gradlew build -PunitTest=true
```

This might be related to https://github.com/craftercms/craftercms/issues/4220

### Describe the solution you'd like

Review all test classes and test methods to make sure the right annotations are being used, so gradle/maven pick the tests and execute them when asked to.
Fix any failing test and check they are still relevant.

**Comment by phuongnq** [comment]
The failed test case for `groovy-sandbox` module was fixed along with https://github.com/craftersoftware/craftercms/issues/604.

`./gradlew build -PunitTest=true -PquietBuild=false`:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.kohsuke.groovy.sandbox.no_exit.NoSystemExitTest
Look ma, I'm still alive
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.95 s - in org.kohsuke.groovy.sandbox.no_exit.NoSystemExitTest
[INFO] Running org.kohsuke.groovy.sandbox.StaticMethodSelectionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s - in org.kohsuke.groovy.sandbox.StaticMethodSelectionTest
[INFO] Running org.kohsuke.groovy.sandbox.FinalizerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.473 s - in org.kohsuke.groovy.sandbox.FinalizerTest
[INFO] Running org.kohsuke.groovy.sandbox.SandboxTransformerTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.664 s - in org.kohsuke.groovy.sandbox.SandboxTransformerTest
[INFO] Running org.kohsuke.groovy.sandbox.robot.RobotTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.145 s - in org.kohsuke.groovy.sandbox.robot.RobotTest
[INFO] Running org.kohsuke.groovy.sandbox.impl.GroovyCallSiteSelectorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.kohsuke.groovy.sandbox.impl.GroovyCallSiteSelectorTest
[INFO] Running org.kohsuke.groovy.sandbox.TheTest
null
null
null
null


null
null
[INFO] Tests run: 49, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.524 s - in org.kohsuke.groovy.sandbox.TheTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 75, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by phuongnq** [comment]
@jmendeza The test case has been fixed for the groovy-sandbox. Please let me know if we still have some failed test case or if some test cases are not executed.

**Comment by jmendeza** [comment]
@phuongnq this ticket is a more general request. 
There are Test classes in different modules that are not properly configured so when we execute something like `mvn test` the test methods don't run.
e.g.: [ContentServiceImplTest](https://github.com/craftercms/studio/blob/develop/src/test/java/org/craftercms/studio/impl/v2/service/content/ContentServiceImplTest.java)  (there are others in studio and more in other modules)
When `mvn test` is executed, logs show only some Test classes actually run ( see `ContentServiceImplTest` is missing):
```
[INFO] Running org.craftercms.studio.api.v2.utils.StudioUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.297 s - in org.craftercms.studio.api.v2.utils.StudioUtilsTest
[INFO] Running org.craftercms.studio.impl.v2.service.site.SitesServiceImplTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.409 s - in org.craftercms.studio.impl.v2.service.site.SitesServiceImplTest
[INFO] Running org.craftercms.studio.impl.v2.security.LoginAttemptManagerImplTest
...
...
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.02 s - in org.craftercms.studio.impl.v2.security.LoginAttemptManagerImplTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0
```

We need to check which test cases are not running and configure them properly.

**Comment by sumerjabri** [comment]
@phuongnq, please help me understand why the PRs moved us to use JUnit Vintage and TestNG Engine. Is that to allow older test cases to work today, or is there another reason? Also, is there a better way to refresh/refactor these test cases? Please share your thoughts.

**Comment by phuongnq** [comment]
@sumerjabri In the `studio` module, we are mixing test cases using:

* `org.junit.jupiter.api.Test` which is based on JUnit 5
* `org.junit.Test` which is JUnit 4 as of our current JUnit version
* `org.testng.annotations.Test` which is TestNG

By adding JUnit Vintage (this module allows backward compatibility with JUnit 4, https://www.baeldung.com/java-junit-vintage-engine-vs-junit-jupiter-engine) and TestNG engine (https://github.com/junit-team/testng-engine), it helps `maven-surefire-plugin` notice all of the above `@Test` annotations and pick them up for testing.

Another way could be migrating all of the test cases to use one library but it could be a long-term goal since we have 177 test cases and only 10 are using `or.junit.jupiter`.

**Comment by jmendeza** [comment]
@phuongnq please review/fix deployer and search modules.

**Comment by jmendeza** [comment]
Verified
