### ISSUE TITLE
[studio] Cleanup unused APIs in Studio API 1

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6247]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

There are some unused APIs in Studio API 1.  It would be nice to clean them up.

### Describe the solution you'd like

Please clean up the following APIs with their corresponding implementation:

- [ ] site/clear-configuration-cache.get.groovy
- [ ] site/get-available-blueprints.get.groovy
- [ ] site/get-configuration.get.groovy
- [ ] site/write-configuration.post.groovy
- [ ] repo/add-remote.post.groovy
- [ ] repo/list-remote-get.groovy
- [ ] repo/pull-from-remote.post.groovy
- [ ] repo/push-to-remote.post.groovy
- [ ] repo/rebuild-database.post.groovy
- [ ] repo/remove-remote.post.groovy
- [ ] audit/get.get.groovy
- [ ] publish/publish-items.post.groovy
- [ ] publish/status.get.groovy
- [ ] dependency/get-dependencies.post.groovy
- [ ] deployment/get-deployment-history.get.groovy
- [ ] deployment/get-scheduled-items.get.groovy
- [ ] content/crop-image.get.groovy
- [ ] content/set-item-state.post.groovy
- [ ] content/unlock-content.get.groovy
- [ ] server/get-ui-resource-override.get.groovy
- [ ] aws/elastictranscoder/transcode.post.groovy
- [ ] aws/s3/upload.post.groovy
- [ ] aws/mediaconvert/upload.post.groovy
- [ ] activity/get-user-activities.get.groovy
- [ ] activity/post-activity.post.groovy
- [ ] audit/get.get.groovy
- [ ] box/token.get.groovy?
- [ ] box/url.get.groovy?
- [ ] clipboard/copy-item.post.groovy
- [ ] clipboard/cut-item.post.groovy
- [ ] clipboard/get-items.get.groovy
- [ ] clipboard/paste-item.get.groovy
- [ ] security/get-user-permissions.get.groovy
- [ ] security/get-user-roles.get.groovy
- [ ] security/login.post.groovy
- [ ] security/logout.post.groovy
- [ ] webdav/list.get.groovy
- [ ] webdav/upload.post.groovy
- [ ] workflow/create-jobs.post.groovy
- [ ] workflow/get-go-live-items.get.groovy
- [ ] workflow/get-workflow-affected-paths.get.groovy
- [ ] workflow/go-delete.post.groovy
- [ ] workflow/go-live.post.groovy
- [ ] workflow/reject.post.groovy
- [ ] workflow/submit-to-go-live.post.groovy

**Comment by phuongnq** [comment]
@sumerjabri @alhambrav Some of the APIs have already been marked as 'deprecated' and some of them are not. Do we wish to completely remove these APIs from the source code?

**Comment by sumerjabri** [comment]
@phuongnq for 4.2, yes, let's remove them.

**Comment by phuongnq** [comment]
API `security/get-user-permissions.get.groovy` still in use in the Plugin Management:
![get-user-permissions-api](https://github.com/craftercms/craftercms/assets/2996543/046047cd-6d38-4721-a6d3-06687f339459)

**Comment by phuongnq** [comment]
* `box/url.get.groovy` still in use? https://github.com/craftercms/studio-ui/blob/develop/static-assets/components/cstudio-forms/controls/box-file-upload.js#L90
* `box/token.get.groovy` still in use? https://github.com/craftercms/studio-ui/blob/develop/static-assets/components/cstudio-forms/controls/box-file-upload.js#L187C5-L187C32

**Comment by alhambrav** [comment]
Noted. Thank you.
Added `content/crop-image.get.groovy` and `aws/elastictranscoder/transcode.post.groovy` to the list above

**Comment by phuongnq** [comment]
Added PR to remove the above: https://github.com/craftercms/studio/pull/3354

CC @rart I see that there is an API call for `transcode.json`. If we don't use this anymore, maybe remove it from the source code? https://github.com/craftercms/studio-ui/blob/develop/static-assets/components/cstudio-forms/controls/aws-video-upload.js#L113

**Comment by jmendeza** [comment]
Can we also remove/deprecate this API /api/1/services/api/1/dependency/calculate-dependencies.json ?

**Comment by alhambrav** [comment]
Hi @phuongnq ! Please see the comment from @jmendeza above. We'd like to have `calculate-dependencies.json` cleaned up too. Thank you!

**Comment by phuongnq** [comment]
I sent PR to remove the reference of API `calculate-dependencies.json` from the backend.
The UI is referring this API and should be evaluated for removal:
https://github.com/craftercms/studio-ui/blob/develop/static-assets/components/cstudio-common/common-api.js#L3344
cc @rart

**Comment by sumerjabri** [comment]
@jmendeza please see above.

**Comment by alhambrav** [comment]
Verified.
