### ISSUE TITLE
Form engine does not indicate that a field can be dropped into a section of the canvas

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#6256]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When I drag a new "input" field onto a new content type (component), there is no indicator that I can drop the field into that location.  However when I let go of it in the correct location, it works. 

This is confusing.

### Steps to reproduce

Steps:
Create a new content type
Drag an input field onto the form engine canvas
Note no change in cursor or background

**Comment by sumerjabri** [comment]
It will be addressed in FE2.
