### ISSUE TITLE
[studio-ui] Textarea input type ignores rows and columns configuration 

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#6259]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating a textarea field in a content type, the number of rows and columns is ignored by the UI.

The number of columns isn't that important - 100% width is fine.  But the  number of rows (especially initial rows) should be set - at LEAST to more than one line if the number of rows > 1.

### Steps to reproduce

Steps:

1. Create a new content type
2. Add a text field
3. Set the number of rows to anything not 1
4. Observe that when editing the field in the form editor, that only one line is done.

**Comment by rart** [comment]
@jvega190 like we've been doing with other controls, remove cols.

Rows should continue to work.

cc @russdanner

**Comment by jvega190** [comment]
Already fixed in here: https://github.com/craftercms/craftercms/issues/6173
