### ISSUE TITLE
[studio] Studio allows to delete the user with which it is connected.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#626]
Steps
1. Go to Crafter3.0
2. Login with user admin/admin
3. Delete the user admin/admin.

*Current Behavior
Allows to delete the user with which it is connected.

*Expected Behavior
Studio should not to delete the user admin/admin because I'm connected with this user.

**Comment by sumerjabri** [comment]
@dejan-brkic please don't allow the deletion of the root user `admin` and don't allow a user with admin rights to delete themselves.

**Comment by dejan-brkic** [comment]
done PR #594

**Comment by sumerjabri** [comment]
Per Gustavo:
Steps:

Create a user with the role admin.
Login with the user recently created.
Go to User tab
Delete the user currently connected.
Current behavior
Studio allows to delete the user currently connected.

Expected behavior
When the this user is deleted studio is crash, never should delete the user current connected.

**Comment by gortizcraftersoftware** [comment]
Please remove / hide this technical information of the validation message: 

Error: Internal server error: org.craftercms.studio.api.v1.exception.security.DeleteUserNotAllowedException

![screen shot 2017-05-04 at 3 53 14 pm](https://cloud.githubusercontent.com/assets/21205707/25726565/fd637bd2-30e1-11e7-8999-a33cae31673b.png)

**Comment by dejan-brkic** [comment]
Can not reproduce

Described use case is not correct.

1. It is not possible with current UI to add user to global admin group
2. If added manually (using API), newly added user does not have access to user management section
3. if you login as admin and try to delete admin user, system gives a internal server error (500)
