### ISSUE TITLE
[studio-ui] Session expired dialog - Log In button is disabled after entering an incorrect password.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6260]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When the user session expires and the UI shows the dialog to authenticate, if the user types an incorrect password and click `Log In` then the `Log In` button stays disabled and the user can't log in from there. 

### Steps to reproduce

Steps:

1. Log In to Studio
2. Wait for session expired dialog 
3. Type an incorrect password
4. Type a correct password and try to log in
5. See the issue

### Screenshots and/or videos

![session timeout](https://github.com/craftercms/craftercms/assets/6722074/53e0a8d6-8a80-496d-8a3e-75fec157e538)

**Comment by rart** [comment]
@sumerjabri @yacdaniel I don't see this issue on 4.0.x. Please make sure to tag branches only when the bug is confirmed in it.

**Comment by sumerjabri** [comment]
> @sumerjabri @yacdaniel I don't see this issue on 4.0.x. Please make sure to tag branches only when the bug is confirmed in it.

I added 4.0 for you to see if it's there or not.
