### ISSUE TITLE
[studio-ui] History dialogue unreadable when Studio is running in dark mode

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6262]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When comparing/viewing the item, the content of the dialogue will be unreadable when Studio is running in dark mode. What is expected from the fix is for this content to be readable for the user who is running Studio in dark mode. 

### Steps to reproduce

Steps:

1. Create a new project. 
2. Open an item's options and click on history.
3. Click on `View` or `Compare to`
4. See the issue

### Screenshots and/or videos
![Screenshot from 2023-10-26 16-46-26](https://github.com/craftercms/craftercms/assets/90878288/47ec4a99-51e9-4406-a33c-348f0dd6e7a6)
![Screenshot from 2023-10-26 16-46-35](https://github.com/craftercms/craftercms/assets/90878288/282017f1-dd3b-4d18-8c8d-ae4c0191c8c8)

**Comment by sumerjabri** [comment]
@rart we must also check 4.0

**Comment by rart** [comment]
The issue is not present in 4.0.x. Seems to be related to the order of insertion of styles which is likely due to updates in the mui version since.

**Comment by sumerjabri** [comment]
EE is synced as well.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v.4.1.2 CE and EE. Thank you! Closing this ticket.
