### ISSUE TITLE
[studio-ui]Remove unused Data Sources

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#627]
Go to the Admin Console, then click "Content Types"
Click on "Open existing type" , say Page-Article
In "Data Sources", remove the following since it's not used
(found in the Admin Tools configuration):
   -  "DAM Image Flickr"
    - "Flash Uploaded from Desktop"

<img width="358" alt="remove-flash-flickr-datasource" src="https://cloud.githubusercontent.com/assets/25483966/24171335/6d4c5004-0e5a-11e7-9dea-d40af5d23d7c.png">

**Comment by vestrada** [comment]
Studio - Master - PR: https://github.com/craftercms/studio/pull/600

**Comment by vestrada** [comment]
On new sites will be deleted unused Data Sources

**Comment by sumerjabri** [comment]
Please also remove from `Empty` bp.

**Comment by vestrada** [comment]
Studio - Master - PR: https://github.com/craftercms/studio/pull/604
