### ISSUE TITLE
[studio] Cancelling workflow for scheduled item must cancel workflow for the entire package

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6279]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When a scheduled item is edited, workflow is cancelled and publish request for the specific item is removed. This should happen for all items in the same publishing package

### Steps to reproduce

Steps:

1. Create a new site from editorial
1. Initial publish
1. Duplicate Style page
1. Copy Health page and paste under Style copy
1. Schedule Style Copy > Health page to go live. Style Copy is added as mandatory dependency.
1. Edit Style Copy (accept the workflow cancellation warning)
1. Notice Style Copy is no longer scheduled, but Health still is.

**Comment by sumerjabri** [comment]
CC @russdanner
