### ISSUE TITLE
[studio-ui]The displayed Persona when opening "Targeting" from the Preview Tools panel is not the current active persona

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#628]
The persona displayed is always the first persona from the list instead of the current active persona.

From the Preview Tools panel, click on "Targeting"
In the screen below, the current active persona is "Gal", when you click on targeting, the dialog that came up is displaying the persona "Anonymous"

<img width="1138" alt="persona-display" src="https://cloud.githubusercontent.com/assets/25483966/24171970/ec2f5d56-0e5c-11e7-9278-7812326d4109.png">

**Comment by vestrada** [comment]
Studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/332
