### ISSUE TITLE
Upgrade to the latest MariaDB4j from upstream and fix broken unit tests

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6284]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

MariaDB4j latest `develop` is failing unit tests and should be updated with upstream.

### Describe the solution you'd like

Sync up with the latest from upstream and correct broken unit tests.

We have updated the dependencies to keep up and avoid any vulns. We should try to keep the deps updated if possible. We may also consider sending PRs upstream.

**Comment by phuongnq** [comment]
@sumerjabri I don't see any test break in the `develop` branch. Our repo is in synced with the upstream as the latest for v2 is 2.6.0. The upsteam also has v3 but this will need Spring Boot version 3 and we may want to wait until CrafterCMS upgrades to Spring 6 to do this.

Attach the `mvn test` in my local: 
[mariadb4j_test.log](https://github.com/craftercms/craftercms/files/13435746/mariadb4j_test.log)

**Comment by sumerjabri** [comment]
Will pursue it if we decide to go to Spring Boot 3 for the main product. For now, no action is needed.

**Comment by sumerjabri** [comment]
Let's do this as part of the Spring upgrade.

**Comment by phuongnq** [comment]
@sumerjabri This is completed along with the Spring upgrade
