### ISSUE TITLE
[studio] Installing some plugins not copying files properly.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6287]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Installing plugins like `yoast` is not working properly due to files not being copied.

### Steps to reproduce

Steps:

1. Go to site based on editorial
2. Go to `Project Tools -> Plugin Management -> Search & Install` and install `Yoast plugin`
3. Go back to preview, and refresh
4. On the right panel, click on `Yoast SEO`
5. See the error.

* If you check the site repo, you won't see the plugin js files for authoring and delivery

**Comment by phuongnq** [comment]
@sumerjabri @jvega190 The files are not copied because we have the plugin id is `org.craftercms.plugin.yoast` but the plugin directory is missing the `yoast` for example:

```
authoring/static-assets/plugins/org/craftercms/plugin/sidebar/yoast-plugin/index.modern.js
```

Should be:

```
authoring/static-assets/plugins/org/craftercms/plugin/yoast/sidebar/yoast-plugin/index.modern.js
```

I put a PR for the Yoast plugin but we may want to review other plugins with same problem.

**Comment by jvega190** [comment]
@phuongnq thanks, how would the structure for the delivery files be? Right now we have this structure `/delivery/static-assets/plugins/org/craftercms/plugin/yoast/js/yoast-guest.js` and it's not being copied.

Just wondering, did something change when copying the plugin? That structure used to work and afaik it haven't changed

**Comment by phuongnq** [comment]
@jvega190 I think the `yoast-guest.js` is copied as of current:

![2023-11-16_09-06](https://github.com/craftercms/craftercms/assets/2996543/1e1361ff-8b59-4e71-afd5-d44bfbd1a0d1)

I believe we don't change anything about the structure. For this particular plugin, It could be because we changed the plugin ID: https://github.com/craftercms/yoast-plugin/commit/a57783ebed2056eaf6cf9d082dd5c9e581ec59e2

**Comment by jvega190** [comment]
Oh I see, things are working now, thanks @phuongnq! Closing ticket
