### ISSUE TITLE
[studio-ui] File-name control is removing the first char when renaming pages. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6288]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When an user tries to rename a page, the first char of the new name is cut off. Only happens when changing the first letters in the file name and with pages, rename of a component is working. 

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Rename a page, add two new letters at the beginning
3. See the issue

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/6722074/e480a627-ac1d-4138-9e23-227ff813eae6

**Comment by jvega190** [comment]
@yacdaniel please note that this also applies to 4.0.x

**Comment by jvega190** [comment]
Per conversation it'll be assigned to @Euquimides for testing. Please note comment above

**Comment by Euquimides** [comment]
Hi @jvega190 ! While testing this issue I noticed that Firefox browser isn't responding to renaming page file-name. Please check this out. Thank you!

**Comment by Euquimides** [comment]
Hi! Update and rechecked this issue. Fix verified for Crafter v4.0.x, v4.1.x, v4.2.0. Thank you! Closing this ticket.
