### ISSUE TITLE
[Studio] MariaDB won't start if path of Crafter CMS is too long 103 chars

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#629]
If Crafter Startup location path has more than 103 char's on MariaDB won't startup throwing.
` [ERROR] The socket file path is too long PATH` 

Socket path should be something short like `/tmp/Crafter-MariaDB.socket` or `C:\Windows\Temp\Crafter-MariaDB.socket` for Java easy one can use 
 ```java
System.getProperty("java.io.tmpdir")
```

**Comment by dejan-brkic** [comment]
Done PR #629
