### ISSUE TITLE
[engine] Add WebSocket support to Engine's proxy

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6292]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Crafter Engine's proxy works well for regular connections, but not for WebSockets. Those don't get proxied today. There is a growing need for that and we should add it.

### Describe the solution you'd like

Add WebSocket proxy capability to the existing proxy.

Note the options:
* Add that to the existing proxy library and submit a PR to them
* Add Spring's `spring-websocket` to implement this feature
  * Make sure to wrap that to allow for site-specific proxy config where it leads to different end-points depending on the site (the XML config for proxy would need a new <ws-server> element/section
  * The Spring implementation would need to be wrapped so the servlet filter checks for the site and its configuration before passing things forward to the implementation. The implementation might need to be further wrapped to allow dynamic change of proxy destinations/configuration

We need to support this without requiring a restart. If the configuration is presented dynamically and we wrap the right classes, we may be able to achieve this.

Ultimately, we should consider moving the entire proxy layer to Spring. I'll create a separate ticket to pursue that.

Note: this is related to this initial PR https://github.com/craftercms/engine/pull/682

**Comment by Euquimides** [comment]
Hi! Verified enhancement for Crafter v.4.1.3 and v4.2.0. Thank you! Closing this ticket.
