### ISSUE TITLE
[studio] Add the ability to disable the Audit History job

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6294]
### Latest version

- [ ] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The audit log job mines the Git history during Git pull operations to populate the audit table. This behavior is not required for all users in all environments. 

### Describe the solution you'd like

Admins want the ability to disable the job in specific environments.

**Comment by jmendeza** [comment]
The `StudioAuditLogProcessingTask` populates `gitlog` and `audit` tables
We are allowing to disable the `audit` table population. `gitlog` table population continues to be necessary for the `StudioSyncRepositoryTask`

New property, default to false:
```
# Disable the db audit log population
studio.clockJob.task.auditLogProcessing.disableAudit: false
```

Notice that server restart will be required for changes to take effect.

Consequence will be audit table not registering operations synced from git (not performed through Crafter Studio). 

@sumerjabri @russdanner

**Comment by Euquimides** [comment]
Hi! Verified feature added to v4.0.8 and v4.1.2. Thank you! Closing this ticket.
