### ISSUE TITLE
[social-ui] The feedback message displayed when the user try to upload an image of more than 10Mb is not correct.

### ISSUE THREAD

**Issue by LorenzoRodriguezRivetlogic** [craftercms/craftercms#630]
The feedback message displayed when the user try to upload an image of more than 10Mb is not correct. 

PRECONDITIONS: 
==================== 

REPRODUCIBILITY LEVEL: 
==================== 

Always 

STEPS: 
==================== 
Steps 
1. Log into the application with valid credentials 
2. Go to a page with social content enabled.  
3. Click on the “View and Comment” icon. 
4. “Post a Comment” eg. QA test Comment. 
5.Click on the Upload Photo(s) Link and select a photo of more than 10Mb. 
6.Review the feedback message 

CURRENT RESULT: 
==================== 
The photo is not uploaded, but the application displays an incorrect feedback message: “true Dismiss Message” 

EXPECTED RESULT: 
==================== 
The photo is not uploaded and the application should display a correct feedback message.

![screen shot 2017-03-22 at 1 38 06 pm](https://cloud.githubusercontent.com/assets/20914659/24217243/d30ed5a6-0f04-11e7-98c3-afe21ca5bb68.png)

**Comment by jvega-crafter** [comment]
Tested in 2.5.x and master, both are working showing the following message: "Unable to upload file due size limit is 10 MB and upload size is xx MB. Message".

**Comment by jvega-crafter** [comment]
<img width="594" alt="socia-ui upload photo" src="https://cloud.githubusercontent.com/assets/18267471/24473921/2434b4cc-1488-11e7-8064-aa1d2965507d.png">
