### ISSUE TITLE
[studio-ui]  Base repository path with macros not working when creating components using `components` datasource

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6305]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When setting up a components datasource, specifying /site/components/{parentPath[0]}/features in Base Browse Path works fine but not in Base Repository Path field.

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Click on 'Project Tools -> Content types -> Home' and open type
3. Edit the Features Components datasource and set both `Base Repository Path` and `Base Browse Path` to `/site/components/{parentPath[0]}/features`
4. Save & Close
5. Edit homepage
6. Go to Features and click on 'add -> Create new shared feature'
7. See error

**Comment by yacdaniel** [comment]
Verified fixed.
