### ISSUE TITLE
[studio] `get_configuration` API requests are slow

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6306]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`get_configuration` API requests can take up to 2.5 seconds per request in some cases.  
- Calls are 304 responses. Despite that, we were seeing ~2.5s per request.
- Requests have an etag 

There are some reports that this issue is seen when multiple environment configurations are in use and that the slow effect increases with the number of environments.

### Steps to reproduce

Steps:
This issue has not been reproduced in simple form yet

### Relevant log output

```shell
N/A
```

**Comment by rart** [comment]
@jvega190 please port [this work](https://github.com/craftercms/studio-ui/pull/3494/files) to develop and backport to 4.0.x

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Tested with more than 500+ and the response timing is looking well for both `get_configuration` and the new API `/studio/api/2/model/:id/definitions`. Fix verified for Crafter v4.0.8, v4.1.3 and v4.2.0. Thank you! Closing this ticket.
