### ISSUE TITLE
[social] The application is adding a wrong character when the user post a comment with some of the features.

### ISSUE THREAD

**Issue by LorenzoRodriguezRivetlogic** [craftercms/craftercms#631]
The application is adding a wrong character when the user post a comment with some of the features. 

PRECONDITIONS: 
==================== 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Log into the application with valid credentials 
2. Go to a page with social content enabled. 
3. Click on the “View and Comment” icon. 
4. In the “Post a Comment” input select the options as the next video. 
       https://www.screencast.com/t/unMaQRYkl 
5. Post the comment. 
6. Review the posted comment. 

CURRENT RESULT: 
==================== 
The posted comment contains an invalid character. 
â€‹QA4 
â€‹QA5 

EXPECTED RESULT: 
==================== 
The posted comment should not have any additional character, should be posted exactly how the user typed it. 
QA4 
€QA5 

![invalid character social content](https://cloud.githubusercontent.com/assets/20914659/24217916/072e544a-0f07-11e7-9333-1cef9f5731d3.png)

**Comment by cortiz** [comment]
This looks like an issue of the HTML page encoding, I'm unable to reproduce on vanilla sui.
