### ISSUE TITLE
[social-ui] The application is not updating the counter of comments of the “View and Comment” icon when the user delete a comment - user need to refresh the thread

### ISSUE THREAD

**Issue by LorenzoRodriguezRivetlogic** [craftercms/craftercms#632]
The application is not updating the counter of comments of the “View and Comment” icon when the user delete a comment - user need to refresh the page. 

PRECONDITIONS: 
==================== 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Log into the application with valid credentials 
2. Go to a page with social content enabled. 
3. Add a comment. 
4.Verify the counter of the "View and Comment" icon increase in 1. 
5.Delete the previous created comment. 

CURRENT RESULT: 
==================== 
The counter of the "View and Comment" icon does not decrease in 1. 

EXPECTED RESULT: 
==================== 
The counter of the "View and Comment" icon should decrease in 1.Only if the user reload the page or click in the refresh button.

**Comment by jvega-crafter** [comment]
2.5.x - https://github.com/craftercms/social/pull/307
master - https://github.com/craftercms/social/pull/306
