### ISSUE TITLE
[studio] Create User API, Invalid response when the user add the invalid parameters.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#635]
Steps:
1. Execute the json of "create user" with invalid parameters or empty
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/create-user.html

Current Behavior

The response always is :
Status: 500
Response Body: { "message" : "Internal server error" }

Expected Behavior

The response expected should be:
Status: 400
Response Body: { "message" : "Invalid parameter(s)" }

**Comment by gortizcrafter** [comment]
Related to: https://github.com/craftercms/craftercms/issues/595

**Comment by dejan-brkic** [comment]
Duplicate. Fix will be provided as part of #595
