### ISSUE TITLE
Dropdown tree getting stuck on collapse 

### ISSUE THREAD

**Issue by david-escalante** [craftercms/craftercms#636]
When the Dropdown got expanded it can not shrink again.
it start at this size
<img width="1093" alt="screen shot 2017-03-23 at 1 23 08 pm" src="https://cloud.githubusercontent.com/assets/5290296/24267084/b2eacd00-0fce-11e7-9bce-956a40cedeea.png">

 Then it get stuck at this size and it just move the preview under the Dropdown section

<img width="1005" alt="screen shot 2017-03-23 at 1 23 19 pm" src="https://cloud.githubusercontent.com/assets/5290296/24267039/932f4270-0fce-11e7-903e-f082ce4ca76f.png">

**Comment by vestrada** [comment]
studio-ui - 2.5.x - PR: https://github.com/craftercms/studio2-ui/pull/305
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/306
