### ISSUE TITLE
Experience Builder doesn't refresh items on edit screen after they are unlocked

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#6361]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When viewing a content item in XB, XB will indicate that it is locked with a message in the sidebar and by deactivating the toggle in the Studio title bar, if that item is locked by another user.

Other items on the same page may still be edited by XB without issue.

When the other user unlocks their item, XB removes the message in the sidebar and activates the controls again.  However, it does not reload that item to reflect any changes that have been made by another user. 

Therefore, when the current user modifies the item and saves their changes, the edits made by the other user are overwritten.

XB, upon noticing that an item on-screen has been unlocked, should reload that item in XB and present the user with the updated content prior to allowing the user to edit that content.

### Steps to reproduce

Two users are required to recreate this situation.

User 1: open a page that renders several items
User 1: start editing (via XB) one of the items on that page
User 2: open the same page in XB
User 2: attempt to edit the item currently being edited by User 1.  Notice that it is not editable.
User 1: make a change on the content instance and save it by clicking off the item.
User 2: notice that the item is now editable
User 2: notice that the changes made by user 1 are not reflected
User 2: make your own changes to the item and save it
Either user: Inspect the modified item. User 2's changes overwrite User 1's changes.

**Comment by rart** [comment]
@jvega190 please understand review/check https://github.com/craftercms/studio-ui/pull/3565 and port to develop.

**Comment by rart** [comment]
@yacdaniel this will need some multi-user testing. The idea is that XB will now inform more promptly (i.e. on hover) about subitems in Preview that are being edited (locked) and prevent you from editing anything that has been modified by someone else until you refresh and are seeing the latest content. Please review or reassign within your team.

**Comment by yacdaniel** [comment]
Verified fixed in 4.1.x and 4.2.x
![image](https://github.com/craftercms/craftercms/assets/6722074/6bfbfa44-3de1-4148-91d6-f07ef5c057c5)
