### ISSUE TITLE
[studio-ui] Update site listing screen

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#638]
In addition to adding pagination, please adjust the page to look like the attached and make sure the site IDs are left aligned.

Please note the left panel is now gone and we simply list the sites.

![new-site-listing](https://cloud.githubusercontent.com/assets/3931908/24328170/0f4d1f4c-11b1-11e7-8e69-ca25f03df894.png)

Ping me if you need help.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/322
