### ISSUE TITLE
[engine] Redirect responses don't return secure headers

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#6388]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you have the URL rewrite, the request that sends back the 301/302 doesn't send secure headers like:

- `Strict-Transport-Security: max-age=31536000 ; includeSubDomain`
- `X-Content-Type-Options: nosniff`
- `X-Frame-Options: DENY`
- `X-Xss-Protection: 1; mode=block`

### Steps to reproduce

Steps:

1. Configure an editorial site on an Engine with HTTPS configured (using CloudFront might make things easier)
2. Add the URL rewrite

```
    <rule>
        <from>^/fun(/)?</from>
        <to type="redirect">/entertainment$1</to>
    </rule>
```

3. Go to `https://DELIVERY_HOST/fun`, making sure you have the browser Developer Tools open
4. Check the Network requests. You should see the `/fun` redirect response not containing any of the secure headers, while `/entertainment` does.

### Screenshots and/or videos

Redirect response:

![image](https://github.com/craftercms/craftercms/assets/1598884/09453c1f-6e15-4d75-9a58-2a6dd13f80bb)

Actual response:

![image](https://github.com/craftercms/craftercms/assets/1598884/dea8de79-3ff2-4e0a-9675-34288e806efe)

**Comment by avasquez614** [comment]
@phuongnq seems like the HSTS is now not even sent at all when you have CF -> LB -> Engine. Check craftercms.com. Maybe moving the filter broke it?

**Comment by phuongnq** [comment]
@avasquez614 It's possible that CloudFrontFilter and ForwardHeaderFilter need to be set on top so that the secureHeaderWriterFilter understands the request is `https` and adds the HSTS header on it. I have sent a PR for 4.0.x, could you help verifying this?

**Comment by avasquez614** [comment]
@phuongnq thanks! that worked.
