### ISSUE TITLE
[studio-ui] Please make adjustments to site creation dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#639]
Please adjust:
1. change the text to be: `Site Id (Max length: 50 characters, lowercase, no spaces or special characters)`
2. Correctly set the tab order of the dialog
3. Set default action upon enter to create the site

<img width="600" alt="screen shot 2017-03-25 at 10 43 21 pm" src="https://cloud.githubusercontent.com/assets/3931908/24328223/c13ae5d6-11b1-11e7-8ac5-f5dc603d7898.png">
See attached.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/349
