### ISSUE TITLE
Improve XB Communication status and error experience

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6390]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Multiple types of XB communication error messages are displayed in XB/preview today. 
1. **Communication with the preview application** was interrupted. Studio will continue to retry the connection.
2. **Connection with the server** was interrupted. Studio will continue to retry the connection.

While these error conditions indicate two very different issues, the message text and visual treatment are so similar that they confuse users.  Further, in all cases, the corrective actions are out of the hands of most authoring users -- they must be able to leverage the UX/Commachieveons to achieve the following:
1. **Understand how they are impacted:** Without proper communication with the server and or host application, several editing and workflow features will be muted or disabled.
2. Know how to report the error: 
- In the case of error type 1, the usual cause of this error, as the message indicates, is a problem in the preview application or a timing issue. If the issue is an error in the preview application, a template developer must fix the issue. If the issue is a timing issue, it may be possible for an administrator to increase the timeout slightly to accommodate the application or environment.
- In the case of the error type 2, there's a server configuration or networking issue of some sort.  Systems and/or networking assistance is required.

### Describe the solution you'd like

We want to improve the user experience in how the UI reports XB communication status and errors.
Note that dealing with these errors requires some amount of triage. We should consider including a link to documentation for the technical staff that must resolve the issue.

**Comment by sumerjabri** [comment]
@rart please annotate with your UX ideas as we discussed.

**Comment by rart** [comment]
@jvega190 please back port to 4.1.x. 

Use the PR as guidance. Develop has some additional changes that are not meant to be ported. Ping me if in doubt.

**Comment by rart** [comment]
FYI. Tips to validators

- Preview communication issue: 
  - Open `home.ftl` on an editorial BP project 
  - Comment the `<@crafter.body_bottom/>` line towards the bottom of the file (i.e. `<#--<@crafter.body_bottom/>-->`)
  - Go back to XB and refresh (r) preview
- Socket connection issue: 
  - [Install redux dev](https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?pli=1) tools if you haven't
  - Open chrome dev tools, and go to Redux tab
  - Click on Show Dispatcher 
  - Execute the following action: `{ type: 'SITE_SOCKET_STATUS', payload: { connected: false } }`
  
<img width="761" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/083d60e3-2979-4b0f-98f4-0faa933e7257">

<img width="764" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/71d4e856-9b5d-4f6f-9366-d9cdb1477214">

@sumerjabri @russdanner

**Comment by rart** [comment]
@sumerjabri In regards to validation, the way the socket issue is shown has changed and I'm wondering if the latency of a non-local server could play a role in momentarily showing the socket snack when the app first loads. Can we set up a remote to test for this?

**Comment by sumerjabri** [comment]
@rart I can't disagree with Russ's findings. I think it's fine for the cycle to start over upon a refresh in the internal browser (context bar) or browser reload. Let us know your thoughts.

**Comment by rart** [comment]
Same here. 

It was previously not possible to refresh in that state; this was introduced by the enhancement of force-refreshing the iframe when the guest app is in an uncontrolled state. 

I just need to find the right implementation path because nothing changes host-side when refreshing and the refresh is a separate component.

**Comment by sumerjabri** [comment]
@russdanner, please create a new ticket for the enhancements, and we will prioritize those.

**Comment by russdanner** [comment]
Confirmed

**Comment by rart** [comment]
> @russdanner, please create a new ticket for the enhancements, and we will prioritize those.

@sumerjabri what enhancement is pending? They are already done.

**Comment by sumerjabri** [comment]
@rart we'll find out when @russdanner creates the ticket.

**Comment by rart** [comment]
@jvega190 we need a small timeout implemented in the new socket snack that's on Global Dialog Manager. Also, it should not show in framed windows like the content form on the type editor.

**Comment by russdanner** [comment]
Confirmed in 4.2
