### ISSUE TITLE
Improve cross-cutting concerns handling

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6397]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

There are multiple cross-cutting concerns affecting several Studio services and processes. Handing these concerns results in boilerplate code, many dependencies and in general extra complexity.
Some examples are:
- Tracing of service invocation
- Logging of tasks' execution times
- Checking site existence
- Checking content item existence

### Describe the solution you'd like

- [ ] Create the necessary aspects to handle these concerns via annotations.
- [ ] Update code across Studio layers/sub-modules to take advantage of the new annotations

**Comment by phuongnq** [comment]
@sumerjabri @jmendeza Please let me know if we have anything else left for this ticket that should be addressed!

**Comment by sumerjabri** [comment]
@jmendeza all yours

**Comment by jmendeza** [comment]
Looking great now. Thanks @phuongnq.
