### ISSUE TITLE
[studio-ui] Paste is grouped in wrong position on right-click on wcm-root-folder component.

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#640]
Paste option is wrong location.  It's hard for the user to find.  

<img width="589" alt="paste-in-wrong-place" src="https://cloud.githubusercontent.com/assets/169432/24359849/998f9e8c-12d3-11e7-96b0-e8a7d497dd46.png">

Please move Paste option in to the same area of the right click menu with Copy.

Use the following order:
Cut
Copy
Paste

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/347
