### ISSUE TITLE
Reduce log-level for preview cookie refresh

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6408]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

This log repeats and is not very useful:
```
[INFO] 2024-01-03T11:35:22,945 [http-nio-8080-exec-2] [internal.AccessTokenServiceInternalImpl] | Refreshed preview cookie for user 'admin' 
```

### Describe the solution you'd like

Please make it `debug` instead of `info`.

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
