### ISSUE TITLE
Delayed publishing of renamed content can lead to content deletion in published repo

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6410]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Renaming and publishing a non-new content item causes previous path to get deleted from `published` repository. This can lead to unintended content deletion when publishing is delayed and some other content is written to the renamed item original path.

### Steps to reproduce

Steps:

1. Create an editorial site
2. Initial publish
3. From Studio sidebar, navigate to static-assets/images
4. Rename an image, e.g.: `coffee-pic.jpg` -> `coffee-pic-2.jpg`
5. Rename another image to the original path of the previous image. e.g.: `castle-pic.jpg` -> `coffee-pic.jpg`
6. Publish `coffee-pic.jpg` => `coffee-pic.jpg` is replaced and `castle-pic.jpg` is removed from `published`
7. Publish `coffee-pic-2.jpg`  => `coffee-pic-2.jpg` is added and `coffee-pic.jpg` is removed from `published`

The published repository will now contain only one of the images, under the path `coffee-pic-2.jpg`.
Notice this can be reproduced for pages as well.

**Comment by jmendeza** [comment]
Should we just clear `previous_path` when it matches the path of items being published?
If publishing item `coffee-pic.jpg`, set `previous_path=null` for any item where it matches `previous_path='coffee-pic.jpg'`

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6766
