### ISSUE TITLE
Publishing dialog fails when current date values are supplied in non-offset format

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6412]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

On some browsers, date values supplied to the date time picker are supplied to the control in the following format: `"2024-01-05T16:36:00Z"` rather than the expected offset format: `2024-01-05T17:22:00+01:00`

### Steps to reproduce

Steps:

1. Create an empty blueprint
2. Attempt to publish
3. See error

### Relevant log output

```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'name')
at i.Z (DateTimePicker.tsx:113:50)
at qa (react-dom.production.min.js:167:137)
at qc (react-dom.production.min.js:290:337)
at As (react-dom.production.min.js:280:389)
at Os (react-dom.production.min.js:280:320)
at zs (react-dom.production.min.js:280:180)
at as (react-dom.production.min.js:271:88)
at is (react-dom.production.min.js:268:429)
at v (scheduler.production.min.js:13:203)
at MessagePort.E (scheduler.production.min.js:14:128)
du @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Fi @ react-dom.production.min.js:144
yc @ react-dom.production.min.js:261
Ac @ react-dom.production.min.js:260
Ac @ react-dom.production.min.js:260
Ac @ react-dom.production.min.js:260
hc @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
vs @ react-dom.production.min.js:281
is @ react-dom.production.min.js:270
v @ scheduler.production.min.js:13
E @ scheduler.production.min.js:14
Show 13 more frames
Show less
```
### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/169432/8300f1cb-ed99-42c6-a340-7773443931e3)

**Comment by russdanner** [comment]
Users in the UK detected this issue
The installation was a clean 4.1.2E, and the issue can be reproduced in an Empty, Editorial and other blueprints with no modifications to the configuration.

**Comment by sumerjabri** [comment]
@rart Russ is not certain this is in `develop`, but it's highly likely. Heads up.

**Comment by russdanner** [comment]
Confirmed in 4.2.0
