### ISSUE TITLE
[studio] UM fails to fully upgrade site search related code from 4.0.x

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6417]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When upgrading from 4.0.x, groovy scripts should be updated to replace common occurrences of elasticsearch bean and class names.
Not all common names are being updated properly.

### Steps to reproduce

- Create a site in Studio 4.0.x and add a groovy class script to `/script/classes`.
- Declare an Elasticsearch-related bean. e.g.:
```
class SearchService {

    ElasticsearchWrapper elasticsearchService
    
}
```

- Create a bean in engine application-context.xml
```
<bean id="searchService" class="SearchService">
    <property name="elasticsearchService" ref="crafter.elasticsearchService"/>
</bean>
```

Upgrade to 4.1.
Groovy scripts are not updated properly:
e.g.:
Groovy script import updated package but not the class name (it should read OpenSearchWrapper)
```
-import org.craftercms.search.elasticsearch.ElasticsearchWrapper
+import org.craftercms.search.opensearch.ElasticsearchWrapper
```
Fail to load application context:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'crafter.elasticsearchService' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:874) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1358) ~[spring-beans-5.3.31.jar:5.3.31]
```

**Comment by sumerjabri** [comment]
CC @yacdaniel @Euquimides

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://github.com/craftercms/craftercms/assets/6722074/a4addfa5-f348-43bb-945c-ba98df03cd31)
```
import org.craftercms.search.opensearch.client.OpenSearchClientWrapper
import org.craftercms.search.opensearch.impl.OpenSearchWrapper
import org.craftercms.search.opensearch.impl.OpenSearchAdminServiceImpl
```
