### ISSUE TITLE
[studio-ui] Changes to config.xml are lost when save a content type

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6418]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Update a content type config.xml is lost when save the content type.

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Open the Article Content-Type configuration
3. Click to update `config.xml`
4. Perform any update and save
5. Notice that the content is updated after a refresh
6. Open the Article Content-Type again and click Save and Close
7. Open the Article content type again and notice that the update to `config.xml` is lost

### Screenshots and/or videos

https://www.loom.com/share/65e0aa7accc042bfb2cb2de3da8bc750?sid=4aa24a60-9d1b-4f28-aa35-e1df9fb134fd

**Comment by sumerjabri** [comment]
@rart let's also check if this happens in 4.0.x

**Comment by rart** [comment]
@russdanner @sumerjabri the file in question — i.e. `config.xml` — is comprised of XML that, when the content type is saved, gets fully regenerated every time from a _template_ with a fixed list of properties that are known to belong to that file. The re/generation of the file is correctly done with the latest version of the file.

The code editor edits are persisted literally (i.e. string on the editor is submitted as the new content of the file), but when/if the type is saved, **comments**, or **unknown properties** not part of the _template_ are discarded when the content type itself is saved.

Modifying this behaviour to preserve comments or any other XML annotations and edits that fall outside of the original scope of this file isn't negligible. 

Should we still address this at this point? Does this change the priority or target release of this issue?

**Comment by russdanner** [comment]
Given that we have Form Engine 2 (FE2) in the works and that FE2 removes this separate file: I think we should close this ticket in favor of FE2.

**Comment by russdanner** [comment]
I cannot change this ticket at this point but the title should be 
`Commented out edits to config.xml are lost when saving a content type`
