### ISSUE TITLE
[studio-ui] Set persona calls broken in Studio

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#642]
Using the Editorial blueprint:

1. Got to the Home page
2. Open the Preview Tools sidebar
3. Pick Guy as the persona.

Studio should be sending a call to Engine to set the persona like this one:

GET http://localhost:8080/api/1/profile/set?username=Guy&name=John&segment=guy

Instead it sends this request:

GET http://localhost:8080/api/1/profile/set?username=Guy&Mon%20Mar%2027%202017%2010:52:33%20GMT-0400%20(EDT)

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/310

**Comment by sumerjabri** [comment]
Contact Alfonso for details.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/317

Validating "assume action" for person with one or none property.
