### ISSUE TITLE
[studio] Update "studio-api.yaml" file for 4.1.3

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6423]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The `studio-api.yaml` file needs an update

### Describe the solution you'd like

Update  "studio-api.yaml" file for 4.1.3 and add missing `items` for arrays

**Comment by alhambrav** [comment]
Done updating docs

**Comment by alhambrav** [comment]
Re-opening to fix version numbers in OAS file

**Comment by sumerjabri** [comment]
@alhambrav please make sure the OAS docs are consistent with the branch of Studio. For example, `support/4.1.x` must contain an OAS doc that corresponds to that release.
