### ISSUE TITLE
[studio-ui] Sidebar: handle case when sandboxItem.modifier is null

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6428]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Studio UI should handle the case when `content/sandbox_items_by_path` returns 
```
"items": [
        {
            ....        
            "modifier": null,
 ```

### Steps to reproduce

Steps:

1. Create a site from editorial
2. Connect to MariaDB. `./mysql -uroot -proot -S /tmp/MariaDB4j.33306.sock`
3. Set to null the modifier. `use crafter;update item set last_modified_by=null where path = '/site/website/health/index.xml';`. If more sites running in Studio, add the site id. 
4. Open Studio UI and click the options in the Sidebar for the item `Health`

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'username')
    at I (ItemMegaMenuUI.tsx:345:46)
    at qa (react-dom.production.min.js:167:137)
    at Wu (react-dom.production.min.js:197:258)
    at qc (react-dom.production.min.js:292:88)
    at As (react-dom.production.min.js:280:389)
    at Os (react-dom.production.min.js:280:320)
    at zs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at is (react-dom.production.min.js:268:429)
    at v (scheduler.production.min.js:13:203)
```

**Comment by russdanner** [comment]
@jmendeza, @AndyReiter and I confirmed that this is due to `lasted_modified_by` being null in the `item` table.  There should not be a case where this is a valid condition.  

on create the last_modified_by is the creator

We also noted that the creator is null although this does not appear to cause an issue.

**Comment by russdanner** [comment]
What do we do on pull? Is it always repo user at this point? Or do we try and map the username?

**Comment by sumerjabri** [comment]
We used to try to map the user. Starting 4.2, we indicate it's the system git_user.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/6447

**Comment by sumerjabri** [comment]
@yacdaniel, don't try to reproduce the `null`; just set it directly in the database if needed. We have another ticket for that.

**Comment by yacdaniel** [comment]
Verified fixed. Modifier is not required by the UI to render.

![image](https://github.com/craftercms/craftercms/assets/6722074/0e652bbc-f340-4b7a-8c94-02edc04670d9)
