### ISSUE TITLE
[studio-ui] Components panel for drag-drop is incorrectly pushed to the left of preview tools

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#643]
After the update to push site content to the left (to squeeze the preview canvas) when a user opens the preview tools the drag-drop panel started displaying incorrectly.   

The drag drop panel is intended to hide preview tools while it is open. 

 Unlike the content of the site, the components panel should not get pushed to the left.

This happens in 2.5 and presumably 3.x as well

<img width="1148" alt="screen shot 2017-03-28 at 9 35 51 am" src="https://cloud.githubusercontent.com/assets/169432/24408127/d164164a-139a-11e7-897e-cc9c4c602079.png">

**Comment by jvega-crafter** [comment]
2.5.x = https://github.com/craftercms/studio2-ui/pull/319
3.0 = https://github.com/craftercms/studio2-ui/pull/320
