### ISSUE TITLE
[studio-ui] Cannot disassociate video content item from parent content item via ICE on React app

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6433]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Articles (/component/xxxx-content) render a variety of content types including videos (/component/video). When trying to disassociate the video via the ICE trashcan button, very often (but not always, and not predictably), the delete will fail with an error message:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'children')
at T2 (vendor-Tx5gmFb0.js:563:16901)
at F2 (vendor-Tx5gmFb0.js:563:21196)
at Object.next (vendor-Tx5gmFb0.js:613:67510)
at e.next (vendor-Tx5gmFb0.js:19:3427)
at t._next (vendor-Tx5gmFb0.js:19:3029)
at t.next (vendor-Tx5gmFb0.js:19:2678)
at t._next (vendor-Tx5gmFb0.js:19:3029)
at t.next (vendor-Tx5gmFb0.js:19:2678)
at vendor-Tx5gmFb0.js:19:23201
at l._next (vendor-Tx5gmFb0.js:19:6081)
```

### Steps to reproduce

Steps:

1. Create a CrafterCMS project with React
2. Include a video component with the XB
3. Insert the video to a page
4. Try removing the video from that page with XB using the trash icon
5. Notice that the content could failed with the above error

**Comment by rart** [comment]
@jvega190 port to develop
