### ISSUE TITLE
[studio-ui] Opening Drag-Drop fails to initialize when URL has a query string value

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#644]
# Example of broken URL
http://localhost:8080/studio/preview/#/?page=/en?foo=yes&site=simplewebsite

It seems Studio tries to use the entire tire page= value (?page=/en?foo=yes) to look up the page object including an query string values when initializing drag-drop.  When a query string value exists on the URL the lookup of the object fails.  

Query strings are valid as part of the page= parameter, the just need to be ignored when looking up the page object during drag-drop initialization.

# Steps to reproduce
Browse to a drag-dropable page on a site
Open page components/drag drop mode, prove that it works
Open multi-channel preview, switch to iphone (This adds a query string)
Switch back to web
Open page components/drag drop mode, observe failure

**Comment by jvega-crafter** [comment]
2.5.x - https://github.com/craftercms/studio2-ui/pull/324
3.0 - https://github.com/craftercms/studio2-ui/pull/325
