### ISSUE TITLE
Make git pull branch configurable

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6445]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CrafterCMS 4.1 locks the branch you can pull from to a remote branch with the same name as the sandbox branch name.  This is to avoid mistakes.  However, some older installs were not born with this model. Migrating sandbox branch names requires entire environments.

### Describe the solution you'd like

Make the branch you pull from default to the same branch name as sandbox But allow this to be configured to something else.,

**Comment by rart** [comment]
@sumerjabri this is a somewhat 360º on a previous ticket that [explicitly changed the ability to pull from different branches](https://github.com/craftercms/craftercms/issues/5610).

Are we adding a specific place for this to be configured or literally add back on the dialogue the list of branches?

Please confirm.

**Comment by sumerjabri** [comment]
Let's use `Project Configuration` aka `site-config.xml`. Let's add the property:
```
<remoteGitBranch>not-master</remoteGitBranch>
```

This is not added by default, and if missing, we default to what we do today.

**Comment by russdanner** [comment]
Confirmed in 4.2.0
