### ISSUE TITLE
[studio-ui] Handle delete user API exceptions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#645]
When calling http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/delete-user.html

from the screen:
`http://localhost:8080/studio#/users`

to delete the user "admin" (which is not allowed), the system throws an exception:
`http status code 500` and `{
"message": "Internal server error: org.craftercms.studio.api.v1.exception.security.DeleteUserNotAllowedException"
}`

The UI needs to inform the user that user deletion failed and show the exception. Use the text:
`"Unable to delete user. Please contact your system administrator.

Error: {EXCEPTION GOES HERE}"`

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/339

**Comment by vestrada** [comment]
@dejan-brkic I changed the UI, but I'm getting html instead of a json with "message" tag from the service. Can you check it?

Thanks

**Comment by dejan-brkic** [comment]
Looks ok to me
