### ISSUE TITLE
[studio-ui] Make persona avatar clickable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#646]
Please make the persona avatar clickable and have it show the persona selection dialog.

See this screenshot:
![screen shot 2017-03-28 at 11 01 21 am](https://cloud.githubusercontent.com/assets/3931908/24412278/0e5da272-13a6-11e7-9798-c0f5e750c6f7.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/351
