### ISSUE TITLE
[studio] Add bucket to S3 upload API response

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6467]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Update the following API response to include the bucket name for the given profile
`/studio/api/2/aws/s3/upload.json`

### Describe the solution you'd like

Current Response:
```
{
    "response": { ... },
    "item": {
        "name": "005.jpeg",
        "url": "/remote-assets/s3/s3-image/005.jpeg",
        "folder": false
    }
}
```

Expected Response
```
 {
    "response": {  },
    "item": {
        "name": "my-image.jpeg",
        "url": "/remote-assets/s3/s3-image/my-image.jpeg",
        "folder": false,
        "bucketName": "my-bucket"
    }
}
```

**Comment by rart** [comment]
Related to https://github.com/craftercms/craftercms/issues/6453

**Comment by rart** [comment]
✅

**Comment by rart** [comment]
Updates verified: `prefix` is now included.

```
{
    "response": {
        "code": 0,
        "message": "OK",
        "remedialAction": "",
        "documentationUrl": ""
    },
    "item": {
        "name": "craftercms-0F172A.png",
        "url": "/remote-assets/s3/s3-image/craftercms-0F172A.png",
        "folder": false,
        "bucketName": "blob-store-test",
        "prefix": "preview"
    }
}
```
