### ISSUE TITLE
[studio-ui] Add back the legacy AWS S3 Upload control to `develop`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6468]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

AWS S3 File Upload has been removed from `develop` since it has been deprecated for a long time, however, some clients still use/need it.

### Describe the solution you'd like

Add the control `aws-file-upload.js` back into `develop`.

**Comment by rart** [comment]
FYI removed as part of https://github.com/craftercms/craftercms/issues/6247
