### ISSUE TITLE
[studio-ui] "components" datasource is not supporting the macro {parentPath}

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6470]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Using the parentPath macro for a datasource throws an error.

### Steps to reproduce

Steps:

1. Create sample site based on editorial blueprint
2. Go to Project Tools / Content Types and edit Home content type
3. In DataSources add a "shared-content" datasource and name it "Features Components 2"
4. Set as Default type /component/feature
5. Set as Repository path /site/components/{parentPath}
6. Go to field features_o and add "Features Components 2" as item manager
7. Save and close
8. Go back to the site in studio and edit home page
9. Go to Features section and click in "Add +" button
10. Select Create New - Features Components 2
11. You should be able to create a new instance of component feature.
12. Cancel this creation.
13. Click again in "Add +" button
14. Now select create new shared Feature.
15. You should be able to create a new instance of component feature.
16. Cancel this creation.
17. Go back to Project Tools / Content Types and edit Home content type again.
18. Go to Datasources and edit "Features Components" (this is a components datasource) by changing Base Repository Path to "/site/components/{parentPath}"
19. Save and close
20. Go back to the site in studio and edit home page
21. Go to Features section and click in "Add +" button
22. Select create new shared Feature again.
23. An error appear in the screen about Bad Request

### Relevant log output

```shell
https://gist.github.com/AndyReiter/386dc10cef50382c9ee81b155a4ba319
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/3e693531-2ebd-44b3-8ca1-faa66bb0b92d)

**Comment by russdanner** [comment]
@AndyReiter can you double check this I am seeing a different behavior.  I still think there's an minor issue with using parent path on the homepage but that use case is not likely to come up for most users

https://www.loom.com/share/b12711526d654ad9ab5ad968ca21ff73

**Comment by russdanner** [comment]
@AndyReiter, Can you double-check your steps? @phuongnq and I cannot reproduce this per the steps, and I don't want to miss something.
See my video here:
https://www.loom.com/share/8c6dc2c778aa4b6bb5ffbb05fd0c6bc2?sid=6e89e749-877b-4963-a013-821f73efe016

@phuongnq There is a small bug in the `Shared Components` and `Components` datasource, specifically under the home page. This is a much more narrow use case. The parentPath macro should return an empty string at the root. We should think about this and test for side effects. If we have to, I think that specific issue can be moved to a later release.

**Comment by AndyReiter** [comment]
@russdanner I was able to reproduce it by following the steps exactly in the ticket https://www.loom.com/share/37b4fcb7a604456fab9e2461d77a84d5.

**Comment by AndyReiter** [comment]
Confirmed that this is done in 4.1.3 and 4.2
