### ISSUE TITLE
lockOwner is null in `/studio/api/2/workflow/item_states`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6477]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The API response `lockOwner` for each item in the response is null

### Steps to reproduce

Steps:

1. Open an item for edit
2. Go to site tools
3. Filter for locked items and see that there are no users in the locked-by column

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/169432/cb6e55be-e6e9-4772-a53d-d29f0ec1f64b)

**Comment by russdanner** [comment]
Observed in develop as well.

**Comment by jmendeza** [comment]
Fixed the query so it returns the lock owner, if any.
Please notice this also affected creator and modifier.

**Comment by russdanner** [comment]
Confirmed in 4.2.0
