### ISSUE TITLE
[studio-ui] Update Dashboard link to point to Dashboard

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#649]
The dashboard link at the top left (see screenshot) is not point to dashboard, it's pointing to Sites. Please fix.

![screen shot 2017-03-29 at 10 19 53 am](https://cloud.githubusercontent.com/assets/3931908/24459344/4de37e44-1469-11e7-87ca-8a52763a2dd1.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/323
