### ISSUE TITLE
[studio-ui] Deleting all children of an expanded folder and then uploading an item, will set the folder into loading state

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6491]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If all the children of an expanded folder are deleted, that folder will maintain an expanded state. If you upload a file again to that folder, it'll try to expand (because of its state) but will stay in `loading` state. If you manually refresh the tree or the sidebar, then the uploaded file will properly show up.

### Steps to reproduce

Steps:

1. Create a new project. 
2. In `/static-assets` create a new folder.
3. Upload a file to that folder.
4. Expand the folder by clicking on it.
5. Delete the file in that folder.
6. Re-upload a file to that folder. 
7. See the issue. 

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/90878288/c19984b5-6208-4b2e-8409-eb855877bfb4)

**Comment by jvega190** [comment]
@Euquimides this can now be tested in 4.1 and develop

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket for other versions I noticed the following:

The UI allows for a folder to be expanded, even if it has no content. So if you expand a folder, delete all the children of an expanded folder and then upload a folder, it will cause the loading state issue. 

This are the steps to reproduce:
1. Create a new project
2. Create a new folder A in `/static-assets`
3. Upload an item into folder A.
4. Expand folder A and delete its content.
5. Then, expand folder A (watch its state to be sure) and then upload a folder.
6. See the issue.

![image](https://github.com/craftercms/craftercms/assets/90878288/221da8a9-a7e7-4caf-aba8-ad6056b2cc4e)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked the issue above in v4.1.3. Fix verified. Thank you! Will update once I finish verifying other versions.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.0.8, v4.1.3 and 4.2.0. Thank you! Closing this ticket.
