### ISSUE TITLE
Remove deprecated searchService references and beans

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6492]
### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

We have been moving away from the old SearchService and implemented a search service and APIs based on newer `org.opensearch.client.opensearch.OpenSearchClient`.

Related to https://github.com/craftercms/craftercms/issues/5210

### Describe the solution you'd like

Remove the legacy `SiteAwareOpenSearchService` and references in scripting context and model.
Migrate legacy services usages, if any.
This effort will affect Search, Engine, Studio and Deployer.

**Comment by phuongnq** [comment]
I sent the first PR to remove the references of `SiteAwareOpenSearchService` in Groovy scripts/templates. This should prevent developers from using `crafter.searchService` or `crafter.elasticsearchService`.

The remaining task is to completely remove the class `SiteAwareOpenSearchService` which is still in use in the Engine Search API. This API takes a raw query in JSON format and uses `SiteAwareOpenSearchService`. We should seek if the new client supports this type of searching raw JSON string as mentioned in `https://github.com/opensearch-project/opensearch-java/issues/257` Or we could try to parse the JSON by ourselves and form a `SearchRequest` object (like we did in `SiteAwareOpenSearchService`), which is not trivial with the current level of support in the new client.

**Comment by sumerjabri** [comment]
CC @jmendeza

**Comment by alhambrav** [comment]
Setting the documentation to test and validate for now until it has been published

**Comment by sumerjabri** [comment]
@jmendeza please validate the code part and if happy, advance to "done" in the project but leave the ticket until the docs are done done.

**Comment by jmendeza** [comment]
This seems fine for 4.2. Just opened [a new ticket](https://github.com/craftercms/craftercms/issues/7211) so we can discuss future steps.
