### ISSUE TITLE
[studio-ui] ChatGPT Plugin instructions via `Search and Install Plugin` broken reference errors

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6493]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In `v4.1.x` when checking the instructions of the ChatGPT Plugin via `Search and Install Plugin`, the images form the documentation appear broken. In the case of `4.2` an error appears: `Unable to render documentation`.

### Steps to reproduce

Steps:

1. Create a new project.
2. Go to `Project Tools` -> `Plugin Management` -> `Search and Install Plugin`
3. Look for `OpenAI ChatGPT Integration` Plugin.
4. Click on `More`.
5. See the issue.

### Screenshots and/or videos

![Screenshot from 2024-01-30 16-02-36](https://github.com/craftercms/craftercms/assets/90878288/e44b4944-d079-45a9-9d53-e449df3b804a)
![image](https://github.com/craftercms/craftercms/assets/90878288/cc450739-1e76-48ce-8846-fb104adcda19)

**Comment by jvega190** [comment]
@Euquimides 4.2 issue is fixed, the images issue will be ready after publishing the plugin

**Comment by jvega190** [comment]
@sumerjabri the PR for the chatgpt plugin is ready with the version update

**Comment by sumerjabri** [comment]
@jvega190 it's been published. Please update state and assign as needed.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.3 and v4.2.0. Thank you! Closing this ticket.
