### ISSUE TITLE
[studio-ui] Item selector in Preview Address Bar doesn't work properly with components previewed. 

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6509]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When rendering a component in the preview, the Item selector in the preview address bar fails to open.

### Steps to reproduce

Steps:

1. Go to a sited set up for a component to render in the preview
2. Preview a component
3. In the preview address bar, click on the Item Selector
4. See the issue

**Comment by rart** [comment]
Verified
