### ISSUE TITLE
Upgrade Open Search

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6512]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Open Search 2.9 has many issues.

### Describe the solution you'd like

Upgrade to the Open Search 2.11.

**Comment by phuongnq** [comment]
Duplicated of https://github.com/craftercms/craftercms/issues/6598
