### ISSUE TITLE
RTE: click the list button doesn't produce the list-unlist result in the Form Engine.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6514]
CI: 6514
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When an user is editing through Form Engine an RTE text area an creates a list (numbered or bullet) , then if the user clicks the list button to unlist the data, the text is not updated properly. 

### Steps to reproduce

Steps:

1. Create a site from Editorial
2. On the Home page, open the Edit form
3. Scroll down to 'Hero Text' section
4. Enter some text and created a list section
5. Save and close the form
6. Scroll down to the previous section
7. Select the list, click the list button to unlist-list the text.
8. See the issue

### Relevant log output

```shell
VM2963 plugin.min.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at N (VM2963 plugin.min.js:9:1849)
    at T (VM2963 plugin.min.js:9:1994)
    at Te (VM2963 plugin.min.js:9:8861)
    at VM2963 plugin.min.js:9:15251
    at Object.map (VM2963 plugin.min.js:9:905)
    at VM2963 plugin.min.js:9:15169
    at Object.fold (VM2963 plugin.min.js:9:297)
    at wn (VM2963 plugin.min.js:9:15059)
    at VM2963 plugin.min.js:9:15542
    at O (VM2963 plugin.min.js:9:1800)
```

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/6722074/7440e13b-4024-4d03-8402-a77b6c3ec32a

**Comment by sumerjabri** [comment]
Roy says:

> Please test this in many different blueprints

**Comment by rart** [comment]
@jvega190 The issue is still reproducible on the internal sample site. Please investigate further.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.3-SNAPSHOT`

**Comment by Euquimides** [comment]
Hi @rart ! While validating this ticket I noticed that in the `Gardeners` BP, the bullet list option is not working properly. Might it be something related with the BP, since it seems limited to certain sections? Could you please check this out? Thanks!

https://github.com/user-attachments/assets/0f7c0ed6-f4be-4b3f-aa71-90e2309d0ed6

**Comment by rart** [comment]
On detailed inspection of the blueprint and the behaviour, the RTE itself behaves correctly. The title edited on the video, is a h3 representing a title. The h3 should not contain lists but it does allow things like bold and italics which are fine and semantically appropriate. Other areas of the website that are rich body copy do allow for the list to be created but the site has specific styles to not show bullets.
