### ISSUE TITLE
Add a single item per line view to search and browse item selection dialogs

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6517]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Users would like a browse view that shows the full internal name of an object in browse dialogs for item data sources
![image](https://github.com/craftercms/craftercms/assets/169432/0e594491-803f-426f-9a29-a08848235fd3)

### Describe the solution you'd like

Add a view similar to the general search and the search dialog for item data sources:
![image](https://github.com/craftercms/craftercms/assets/169432/30334a79-1f56-45fa-8828-ce23c2b796bb)

**Comment by russdanner** [comment]
Confirmed in 4.2.0

**Comment by alhambrav** [comment]
Setting documentation status to test and validate, once published will change status again
