### ISSUE TITLE
[studio][studio-ui] Level Descriptor being counted as children, also `...X more items` button not working when publishing

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6518]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If the navigator tree is expanded and an item is published, the navigator tree will update or refresh, but the button `...X more items` will not work after that. 

Also, there seems to be an inconsistency in the `children` API. It returns the `levelDescriptor` as a separate object, but counts it as a children in the total of children.For example, let's say the UI shows there are  `...12 more items` and then you close the navigator tree, it will count `...13 more items`. 

### Steps to reproduce

Steps:

In the case of `...X more items` not working: 

1. Create a new project or site based on the Editorial BP.
2. Open `/static-assets/images`, so that it shows the button `...5 more items`.
3. Click in `...5 more items`, see that it is working.
4. Then, with the navigator tree opened, publish an item. 
5. See the issue.

In the case of the `levelDescriptor` being counted as children:

1. Create a new project or site based on the Editorial BP.
2. Duplicate a page various times, for example `Entertainment`, until a button `..X more item` appears.
3. Click on the button, see that it is working.
4. Close the path navigator tree.
5. Reopen the path navigator tree.
6. See that there is `...X+1 more item`, this is the issue.

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/06d7120a-ebea-47db-94c8-3b739ee4dbe2

**Comment by jvega190** [comment]
@Euquimides this can now be tested in 4.1.x

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
