### ISSUE TITLE
[craftercms] Add mongodb to the bundle

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#652]
Add mongodb to the bundle and wire it to Profile and Social for both Authoring and Delivery.

Think about having one or two mongodb (one authoring and one delivery) or using the same one but in a way that would work if someone built/started just one of them. Think about collisions of tenants/names. Once you have thought about it, ping me to discuss before you build.

**Comment by cortiz** [comment]
Fixed on PR #798
