### ISSUE TITLE
The config editor manages `site-policy-config.xml` as env specific but `site-policy-config.xml` is meant to be site wide

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6525]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Studio reacts/responds to the default `site-policy-config.xml` because it is meant to be site-wide (regardless of the environment); however, the config editor loads and saves an environment-specific copy of this file.

### Steps to reproduce

Steps:

1. Configure a site with an environment in Studio
2. Configure a policy in the default `site-policy-config.xml` and a different policy in a file under the env folder
3. Note that the editor loads and modifies the env-specific file
4. Note that Studio enforces the site-wide/default rules

**Comment by rart** [comment]
@sumerjabri, content types is a different module. It uses the same underlying API but it never sends an _environment_ or has any awareness of environments.

As I understand, this ticket is specific to the config editor (Project Tools > Configuration)? That module is environment aware and writes to the active environment. As stated on the info alert above the config item list.

<img width="500" alt="image" src="https://github.com/craftercms/craftercms/assets/3928341/e5ea7b05-cbbc-4cc5-a25f-c927d73846f5">

**Comment by rart** [comment]
@jvega190 will do option **a** for now.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/project-policy-configuration.html#project-policy-configuration

https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/index.html#studio-multi-environment-support

**Comment by russdanner** [comment]
Confirmed in 4.2.0
