### ISSUE TITLE
`/api/1/site/content_store/item.json` empty value behavior has changed

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6526]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In older versions, If a content item had a related object field that was empty, the field would exist:
`page.carousel_o` is a valid field
`page.carousel_o.item` is undefined

In the latest version, the field itself is committed
`page.carousel_o` is undefined.

This breaks consumer code that expects the field to exist

Example
if(page.carousel_o.item && page.carousel_o.item[0].include)

### Steps to reproduce

Steps:

1. See  4.0.3 response for Get Item API
2. See 4.1.x response for Get Item API
3. See the issue

**Comment by sumerjabri** [comment]
@jmendeza let's try to respond in a way that won't break new or old.

**Comment by russdanner** [comment]
Confirmed in 4.2.0
