### ISSUE TITLE
Cut/Paste via the Sidebar should warn users or allow them to act on broken dependencies caused by the move operation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6527]
CI: 4736

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

ZD:4966

Users can cut and paste pages and components in the sidebar (which is a move operation) and there is no warning or options given to the user regarding broken references.

### Describe the solution you'd like

If the object being moved by the user is a dependent of other objects
- warn the user
- allow them to act on the items that depend on the object being moved.

**Comment by yacdaniel** [comment]
@jvega190 please take a look at this path, user can't continue with the paste when the reference is removed using the `Edit` option.
- click the `Edit` button in the `Broken References Warning` dialog
![Image](https://github.com/craftercms/craftercms/assets/6722074/bbb94deb-569a-4b22-bfa8-9d941258ad86)

- remove the broken reference
- save content
![Image](https://github.com/craftercms/craftercms/assets/6722074/eb5b11e6-9cf3-424b-8f88-8493ad505ccc)

**Comment by sumerjabri** [comment]
@rart please fix for `develop`

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.5-SNAPSHOT`

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOPT` 

![image](https://github.com/craftercms/craftercms/assets/6722074/1cf377be-3db4-4dd4-a3a1-c8baf73f0a3e)
