### ISSUE TITLE
[studio] Update user management APIs to support externally managed users

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#653]
Update the APIs:

- Update User
- Enable User
- Disable User
- Forgot Password
- Validate Token
- Set Password
- Change Password
- Reset Password

to return 403 for externally managed users.

Detailed error messages and API updates are added to the docs, and the PR for that is here:
https://github.com/craftercms/docs/pull/218

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/639
