### ISSUE TITLE
XB `disableFlattening` flag always set to false regardless of content type config for item selectors

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6532]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When inserting components via XB dnd, the inserted items `disableFlattening` flag are always set to `false` despite the _Disable Flattening for Search_ content type config being on.

### Steps to reproduce

Steps:

1. Enable _Disable Flattening for Search_ on an item selector 
2. Drag/drop a new or existing shared component into that item selector
3. See `<disableFlattening>false</disableFlattening>` on the xml of the new `<item>`

**Comment by rart** [comment]
- @jvega190 
   - We need to port to develop
   - I could use some help in validating/testing that drag & drop continues to work without fault in all situations. I mostly tested editorial. Testing in React sites and other of our blueprints, creating new embedded components, dropping in shared components, moving components between 2 zones, etc
   
 - @alhambrav please include Changelog changes in release notes

**Comment by phuongnq** [comment]
CI: 4763
This appears to be a similar issue:

1. Create a site with Editorial blueprint
2. Go to sidebar and get Object Id for entertainment page (3 dots menu, history, view any version)
3. Query on Opensearch using object id, for example:

curl -X GET "$ES_URL/_search?pretty" -H 'Content-Type: application/json' -d'
{
"query": {
"query_string": {
"query": "(objectId:\"167e20e8-11c2-0f26-1802-b842a068c162\")"
}
}
}'

4. See how the header is part of the indexed document as attribute "header_o"
5. Go to Studio > Project Tools > Content Types and edit "Section Defaults"
6. Go to Header node selector field and check "Disable Flattening for Search" and save
7. Got back to the entertainment page, open, edit something and save.
8. Query the page document again in Opensearch and confirm your change is indexed.

Expected result:
As we marked the field as "Disable Flattening for Search" the attribute "header_o" shouldn't be present in this document.

Current result:
the attribute "header_o" is still present.

**Comment by sumerjabri** [comment]
@phuongnq @russdanner the steps above from Phil modify the Section Defaults (level-descriptor) content type to "Disable flattening for search," however, the steps then call for the modification of a page and NOT the section defaults. Therefore, nothing changes. If you modify the Section Defaults descriptor itself, the system will not flatten, which is the desired result.

If the above is unclear, ping me to explain.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
