### ISSUE TITLE
Node selector control should only provide the user with an `Edit` option for content items that are editable by Studio

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6533]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The node/item selector should not provide an edit button for content items that are not editable by Studio.
PDF: Crafter has no editor for PDF, so no edit option should be given.
TXT: Crafter supports an inline text editor, so edit should be shown.

CI: 4734

### Steps to reproduce

Steps:

1. Go to Studio, Create Editorial site
2. Go to Project Tools > Content Types and edit Article
3. Add 2 data sources "File Uploaded From Desktop" and "File Browse"
4. For the file uploaded from the desktop source, set the repository path to "static-assets/files"
5. For the File Browse source, set the repository path to "static-assets/"
6. Add control Item Selector to the Content Section, name it File and assign the previously created datasources.
7. Go to the sidebar> static assets and create a folder with name files
8. Upload a pdf file in static-assets/files for example test1.pdf
9. Edit any article, for example articles/2020/12/top-books-for-young-women and in the field File:
- 1. Browse and upload the file previously loaded (e.g test1.pdf)
- 2. Upload a new file for example test2.pdf
10. Now try clicking on the edit option of both files
11. Notice the edit of the node-selector's file that was uploaded via browse fails to be modified, and the warning/error is very quickly shown before it closes.

Example:
### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/d89dd3e8-0561-45f0-9104-69c105d58615)

example pdf's for testing purposes:
[test2.pdf](https://github.com/craftercms/craftercms/files/14267798/test2.pdf)
[test1.pdf](https://github.com/craftercms/craftercms/files/14267799/test1.pdf)

**Comment by russdanner** [comment]
The bug should be reported as "Do not show the edit option for non-editable assets."

Example:
PDF: Crafter has no editor for PDF, so no edit option should be given.
TXT: Crafter supports an inline text editor, so edit should be shown.

**Comment by AndyReiter** [comment]
Confirmed in the latest build of support/4.1.x branch. Closing this out now.

**Comment by Euquimides** [comment]
Hi @rart ! When validating this ticket I noticed that a .csv format files that can be edited (text based), doesn't appear as editable through the item selector. Do we expect .csv files to have this editable option enabled?

cc @sumerjabri

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Added the following feature request that might be related with this ticket https://github.com/craftercms/craftercms/issues/6980. Thank you! Closing this ticket.
