### ISSUE TITLE
[engine] Editorial and Wordify Blueprints not rendering other options in their respective menu navigation bars

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6534]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Both Editorial and Wordify Blueprints are not rendering options (such as other pages like Entertainment or Style) in their respective menu navigation bars. Either a new update in the dependencies or in the navigation service, might be affecting this blueprints. Older versions such as 4.1.x are not having this issue.

### Steps to reproduce

Steps:

1. Create a new project either with Editorial or Wordify BPs.
2. See the issue: the Menu in Editorial BP, for example, isn't rendering other pages such as `Entertainment`, `Style`, `Technology`...

### Screenshots and/or videos

![Screenshot from 2024-02-13 16-44-45](https://github.com/craftercms/craftercms/assets/90878288/4d4068e2-4a99-4f08-8604-95bd95b86bd7)
![Screenshot from 2024-02-13 16-44-54](https://github.com/craftercms/craftercms/assets/90878288/7d0508bb-7346-426b-8c1a-810bc49d70ac)

**Comment by rart** [comment]
@sumerjabri this was a change in the back. What's the idea? I would have thought this should have been routed to backend first.

**Comment by jvega190** [comment]
It also happens in bps using the navigation service from the SDK. For example in VideoCenter (in studio 4.2.x), when calling `/api/1/site/navigation/tree.json`, it is not returning the tree correctly as it does in 4.1.x where it returns `Channels` and `Live Events`

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Verified fix. Thank you! Closing this ticket.
