### ISSUE TITLE
[studio] Update User and Group API to have a new field for user (LDAP)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#654]
Please update the APIs

- group-management/get-groups-per-site    
- group-management/get-users    
- user-management/create-user    
- user-management/get-user    
- user-management/get-users-per-site    
- user-management/get-users    
- user-management/update-user    

to include the field: "externally_managed" in all returns per API spec.

Documentation was updated here: https://github.com/craftercms/docs/pull/219 and https://github.com/craftercms/docs/pull/220

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/639
