### ISSUE TITLE
Checkbox with default value in repeat group will affect items in the same group when "Add Another"

### ISSUE THREAD

**Issue by gemmay45** [craftercms/craftercms#6541]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When trigger "Add Another", the checkbox fields in the repeat group will be reset to the default value.

### Steps to reproduce

Steps:

1. Go to Content Form that has checkbox (default value set to true) in a repeat group
2. Click on one of the checkbox and uncheck it
3. Click Save & Close
4. Open the Content Form again and click "Add Another"
5. Note the checkbox that was unchecked now being checked

**Comment by yacdaniel** [comment]
Hi @gemmay45 thanks for the report. The fix should be available in the next release (`v4.1.3`)

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
