### ISSUE TITLE
Video control does not support `dark mode`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6547]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

![add-button-invisible-in-dark-mode](https://github.com/craftercms/craftercms/assets/169432/4e01f76d-f8a4-4701-a880-941170f643f3)

vs light mode
![add-button-invisible-in-dark-mode-2](https://github.com/craftercms/craftercms/assets/169432/e2d925ce-d2c1-4e04-be22-b22aa1ce1be9)

### Steps to reproduce

N/A

**Comment by jvega190** [comment]
@russdanner is that latest 4.1.x? I'm looking at that in 4.1.3 and it looks correct to me (there were some updated to that control styles some time ago).

![image](https://github.com/craftercms/craftercms/assets/18267471/40087513-f1b3-4612-a695-2ff24d2cca98)
![image](https://github.com/craftercms/craftercms/assets/18267471/09b003af-874c-4bd1-b3a1-81306e107062)

**Comment by russdanner** [comment]
Can't reproduce in 4.1.3. @russdanner will verify

**Comment by russdanner** [comment]
This seems to have been fixed.
