### ISSUE TITLE
[studio-ui] Support externally managed users

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#655]
Please review https://github.com/craftercms/craftercms/issues/654

Please update the `update user` dialog to support the new field `externally_managed`. The new field will show up in the dialog, and is read only.

The new field, if set to `true`, will make the whole dialog read-only and grayed out because the user cannot be edited in Studio.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/328
