### ISSUE TITLE
Enhance the audit system by logging the user's session timeout

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6552]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

We want to track the user's timeout as an audit event.

### Describe the solution you'd like

Upon a session timeout, add that to the audit.

**Comment by Euquimides** [comment]
Hi! Verified enhancement implementation. Thank you! Closing this ticket.
