### ISSUE TITLE
[studio-ui] XB inserting a link to RTE does not work with www

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6556]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

CI: 4775

When Experience Builder is enabled, inserting a link to RTE does not work if the link starts with `www.`

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. In the Home preview, click RTE text to show the menu
3. From the menu, select Insert link
4. Input www.craftercms.com to the popup and save
5. Notice that the link is not created. There is no prompt comes up asking if you want to prefix the URL (while there is a prompt while editing the Form)

### Screenshots and/or videos

Insert from Form Editor:
![2024-02-19_14-33](https://github.com/craftercms/craftercms/assets/2996543/c521130d-4d8d-4275-9eb4-fcacb5739c98)
![2024-02-19_14-32](https://github.com/craftercms/craftercms/assets/2996543/52beb85b-abaa-4390-b560-e2e9006618c8)

Insert from XB inline:
![2024-02-19_14-31](https://github.com/craftercms/craftercms/assets/2996543/3c73e66b-57cd-421c-9b0b-a5c4b67d0a5f)

**Comment by jvega190** [comment]
@rart seems like an issue with the tinymce version, updated to latest 5.x version and it works. I'd like some help for testing (after Phil validates) from qa.

**Comment by jvega190** [comment]
@phuongnq can you please validate in 4.2.x? It's a tinymce version issue, and 4.2.x is already in a newer version. I wasn't able to reproduce the issue in there.

**Comment by phuongnq** [comment]
@jvega190 In 4.2.0, Insert Link for RTE while XB is enabled does not work for me. Please review this screen share: https://www.loom.com/share/bc92d3c671af4380bd40d5a3e3f42d26?sid=acac9bb4-75fa-44e3-954a-5d7ac4f8aebd

**Comment by jvega190** [comment]
@phuongnq can you please verify that there's no ad-blocker in your browser? @Euquimides and me were being able to reproduce this and suddenly we're not. I'm haven't been able to reproduce in 4.2. Can you please share your browser+version and any other helpful detail?

**Comment by phuongnq** [comment]
Hi @jvega190 Recheck today, it appears to work for me now!
Attach the tinymce version:
![2024-02-22_08-36](https://github.com/craftercms/craftercms/assets/2996543/66bb513a-20ce-4166-a8b3-3e01825678e5)

**Comment by phuongnq** [comment]
Browser version: Chrome Version 122.0.6261.57 (Official Build) (64-bit) Ubuntu 22.04

**Comment by jvega190** [comment]
@phuongnq https://github.com/craftercms/studio-ui/pull/3715 and https://github.com/craftercms/studio-ui/pull/3716 also fixed the link issue, assigning to you for validation, thanks!

**Comment by phuongnq** [comment]
verified
