### ISSUE TITLE
Disable the add button in node-selector when item limit is reached

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6557]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When a node-selector has a specified limit that is reached, the button to "add" another item is still present. Upon clicking this button, an error is thrown in the UI saying that the limit is reached and an item needs to be removed to make room for the addition. 

1. Create a site with Editorial blueprint
2. Go and edit the homepage
3. Go to Left Rail node selector and click on add button
4. You will see a message saying "You can't add more items, Remove one and try again." This is correct.
5. But you also will see the options of the Add button available and you can click on them. See attached image.

![image](https://github.com/craftercms/craftercms/assets/42217570/1e971742-5725-4759-8e0c-60a6a3baeb1e)

### Describe the solution you'd like

The add button should not be enabled when the limit is hit.

**Comment by russdanner** [comment]
Duplicates #6711
