### ISSUE TITLE
[studio-ui] Label all externally managed users

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#656]
Whenever listing users in the system, add an indicator if the user is externally managed.

A user is externally managed when the field "externally_managed" is equal to  "true"

**Comment by sumerjabri** [comment]
@alhambrav please help validate this ticket.

**Comment by alhambrav** [comment]
Verified. 

<img width="906" alt="Screen Shot 2021-09-10 at 4 59 48 AM" src="https://user-images.githubusercontent.com/25483966/132828884-16893ca6-f116-45a0-9620-4563e07c6b6b.png">
