### ISSUE TITLE
[studio-ui] Table buttons tool for in-context editing does not work

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6561]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

CI: 4769
The table buttons tool for in-context editing does not work

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. Open Form Editor of the Home page to insert a table to any RTE
3. Save and open Home page in preview mode with XB enable
4. Click on the table to enable the table options menu
5. Click on any button
6. Notice that non of the buttons are functional

### Screenshots and/or videos

![2024-02-20_15-01](https://github.com/craftercms/craftercms/assets/2996543/012c82b5-9167-4743-9d53-bfb003f1c011)

**Comment by yacdaniel** [comment]
Hi @jvega190 can you please take a look at the difference between the same table in Engine Form and Preview. I used the Table Properties to tweak the style. 

Engine Form Table
![image](https://github.com/craftercms/craftercms/assets/6722074/01e79c6d-3cab-4c7d-901e-1c2a0e6509d7)


Preview 
![image](https://github.com/craftercms/craftercms/assets/6722074/c900ddce-b4c5-40f6-81b1-222650b77127)
Thanks!

**Comment by jvega190** [comment]
Hi @yacdaniel, the difference between the table in the form and in preview is because the blueprint has some styles that remove bordes, and adds opacity in the rows.

**Comment by yacdaniel** [comment]
Thanks @jvega190! I'll follow up in another ticket.

**Comment by phuongnq** [comment]
Hi @jvega190 I still see the issue. Please refer to this screen share: https://www.loom.com/share/466e0c52767c41b9baffcd04fe4018d2?sid=69e11cc1-64e5-4caf-9d99-9146e16e66b0

**Comment by phuongnq** [comment]
Hi @jvega190 Recheck today, it appears to work for me now in 4.1.3.

**Comment by jvega190** [comment]
@phuongnq reassigned to you for 4.2.x. validation, thanks!
