### ISSUE TITLE
Error with `children` API when editing `sortStrategy` to `lastUpdate` and `order` from `DESC` to `ASC`

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6570]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When setting the the sortStrategy to lastUpdate and the order from DESC to ASC as shown below:
```
              <widget id="craftercms.components.PathNavigatorTree">
                    <configuration>
                        <id>StaticAssets</id>
                        <label>Static Assets</label>
                        <icon id="@mui/icons-material/ImageOutlined"/>
                        <rootPath>/static-assets</rootPath>
                        <sortStrategy>lastUpdate</sortStrategy>
                        <order>DESC</order>
                        <locale>en</locale>
                    </configuration>
                </widget>
```
The sidebar will update, but when opening the section being sorted (in this case Static Assets), no item will load. Seems because there is a conflict with the new /children API (responding with HTTP 400).

This issue is related with https://github.com/craftercms/craftercms/issues/5830

Also, we need to add the `sortStrategy` and `order` features to docs. 

### Steps to reproduce

Steps:

1. Create a new project.
2. Go to `Project Tools` -> `Configuration` -> `User Interface Configuration`
3. Edit it to add `sortStrategy` and `order`, inside `Static Assets`, such as in the following example:
```
              <widget id="craftercms.components.PathNavigatorTree">
                    <configuration>
                        <id>StaticAssets</id>
                        <label>Static Assets</label>
                        <icon id="@mui/icons-material/ImageOutlined"/>
                        <rootPath>/static-assets</rootPath>
                        <sortStrategy>lastUpdate</sortStrategy>
                        <order>DESC</order>
                        <locale>en</locale>
                    </configuration>
                </widget>
```
Click on `Save`.
4. Then change again the configuration to change `order` to `ASC`. Then click on `Save`
5. See the issue: the `Static Assets` section will not load the children (will keep in a loading state)

### Relevant log output

```shell
REQUEST
{"paths":[{"path":"/static-assets","limit":10,"sortStrategy":"lastUpdate","order":"DESC"}]}

RESPONSE
{"response":{"code":1001,"message":"Invalid parameter(s)","remedialAction":"Check API and make sure you're sending the correct parameters","documentationUrl":""},"validationErrors":[{"field":"paths[0].sortStrategy","message":"String doesn't match against whitelist or matches against blacklist"}]}
```

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/af2c1123-e9b5-4bd4-b1ed-44e3bd7b7a69

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/user-interface-configuration.html#pathnavigatortree-and-pathnavigator-sidebar-widget
