### ISSUE TITLE
Templates or controllers scheduled or requested for publish, will result in `Workflow Cancellation` loading indefinitely or stuck

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6571]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If a user tries to edit a template or controller from a page option, and this template or controller is scheduled for publish or requested for publish, the `Workflow Cancellation` window will stay loading indefinitely or stuck. 

### Steps to reproduce

Steps:

1. Create a new project based on Editorial BP, for example.
2. Schedule for publish `home.ftl`.
3. Right click or open `Home` page options.
4. Click on `Edit Template` option.
5. See the issue: a `Workflow Cancellation` window will appear but it will stay in loading indefinitely or stuck

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/4878abfc-ef30-4b78-ac78-ab8a950ac53a

**Comment by Euquimides** [comment]
Hi @rart and @jvega190 ! While validating this ticket I noticed the following issue, that might be also related with this one. The issue is described in here https://github.com/craftercms/craftercms/issues/6616.

**Comment by rart** [comment]
@jvega190 please adjust the dialog so that if nothing is being loaded and no items are being provided, it would show some sort of empty state so the UI reflects more accurately what's going on.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
