### ISSUE TITLE
Parameter Type Casing in Plugins Documentation is incorrect

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6574]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x
- [x] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Plugins allow the creators to define parameters in the YAML:

https://docs.craftercms.org/en/4.1/by-role/developer/composable/extensions/plugins.html#how-do-i-make-my-own-plugin

The docs show an example of defining a parameter:

parameters:
- label: My Parameter Label
name: myParam
type: string
description: My parameter
required: true

Note the "type: string" line

In the "where" section below, it states:

type: Type of the parameter, possible values are STRING and PASSWORD. The default is STRING

It has been found that the case of the "type" value *must* be in all caps, as stated in the "where" section (e.g. it cannot be "string" but must be "STRING")

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

**Comment by alhambrav** [comment]
- https://docs.craftercms.org/en/4.0/developers/extensions/blueprints.html#passing-parameters-to-project-blueprints
- https://docs.craftercms.org/en/4.1/by-role/developer/composable/extensions/blueprints.html#passing-parameters-to-project-blueprints
- https://docs.craftercms.org/en/4.1/by-role/developer/composable/extensions/plugins.html#passing-parameters-to-project-via-plugins

**Comment by AndyReiter** [comment]
This is confirmed. I will close this now.
