### ISSUE TITLE
[studio-ui] Publish comment does not show in Recently Published section of Site Dashboard

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6575]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When a comment is added with a publish, that comment does not appear in the "Recently published" widget in the dashboard, it always says "Submission comment not provided"

### Steps to reproduce

Steps:

1. Create a site based on editorial
2. Perform an initial bulk publish of the site
3. Once the publish has been completed, make a simple edit to the home page
4. Publish the home page, and add a publish comment to it
5. Once the item has been published, navigate to the site dashboard and look for the recently published section
6. Notice that the item you recently published is present, but says "Submission comment not provided"

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/42217570/f48b5cd3-64b6-463d-9cec-3500c8e1b2aa)

![image](https://github.com/craftercms/craftercms/assets/42217570/de058695-8c78-489a-8076-506211e59373)

**Comment by russdanner** [comment]
Duplicates #5428
I will link this ticket there as well since it does a great job illustrating the issue.
