### ISSUE TITLE
[studio] Adding several roles to a menu item in Site Dropdown Configuration doesn't work

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#658]
E.g. After adding the `<role>developer</role> `after `<role>admin</role> `in modulehook admin-console, the Admin Console menu item disappears from the Sidebar.

**Comment by sumerjabri** [comment]
I'm still unsure if this is a bug in the UI or backend. @jvega-crafter please look into it.

**Comment by jvega-crafter** [comment]
I wasn't able to reproduce this issue. 
Followed steps:
- Go to admin console
- Click on "Configuration"
- Select "Role Mappings" on dropdown
- Add `<role>developer</role>` after `<role>admin</role>`
- Click on "Save"
- Click on "Clear Cache"
- Reload Page

After reloading the page the admin console shows correctly, and under permissions mapping I can see the change

**Comment by avasquez614** [comment]
Showed this issue to @jvega-crafter on a video call, he was able to see it happening and will work on the fix.

**Comment by jvega-crafter** [comment]
Now I'm able to reproduce it, working on it

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/328
