### ISSUE TITLE
[studio][studio-ui] Filters in Search such as `Content Size`, `Last Edit Date`, `Width` or `Height` not mantaining count of items persistent but changing to the current option count when clicking

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6586]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you go to `Search` in Preview and try to to filter items either by `Content Size`, `Last Edit Date`, `Width` or `Height`, the counting of items won't be persistent in the UI but will change for all other options when clicking in an specific option.

For example: if the user tries to filter for content by `Last Edit Date` then `Over a Month Ago` , and that content is listed that contains 14 items, it will set that 14 items for all other options (such as `In last week`) upon clicking (even if other options contains other counting).

### Steps to reproduce

Steps:

1. Create a new project that contains diversity of content with different metadata (edit dates, images with different size, etc.).
2. Go to `Search` in Preview.
3. If you have content with different dates of edition, filter the content by `Last Edit Date`, then click in any other option.
4. See the issue: the other options will change to the counting of the current option count when clicking.

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/f3cc0d34-99c4-4b0e-a8d7-68a3e5c883f6

**Comment by rart** [comment]
The count is dynamic based on the results, not on the full index. The count of items in each facet comes from the back. When a facet is selected, the results change and the counts reflect the totals in the new results.

For example if you select the content between 1Kb-25Kb, there are no matches in the rest of the facets so indeed their count is 0. Most — if not all — of the facet _buckets_ are actually exclusive to each other, meaning when you select one, all the other's counts will be 0.

I'm not a fan of this UX myself, but we'd need to have a bigger discussion to see what's possible and where we want to apply the change. For example, we could modify the UI to not display facets with a count of 0, or maybe the back shouldn't send them so the UI doesn't make those decisions? And even before, is that the right UX?

@sumerjabri @russdanner assigning back to you guys for re-triage.

**Comment by sumerjabri** [comment]
This is the right behavior
