### ISSUE TITLE
[studio] Recently Published widget in Dashboard is populated after creating a new site

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#659]
Recently Published widget in Dashboard is populated with 20 entries after creating a new site and no edits or publishing has been done.

<img width="1434" alt="screen shot 2017-03-30 at 11 33 14 am" src="https://cloud.githubusercontent.com/assets/25483966/24512625/1a6f9fd2-153d-11e7-8b2c-c1df67a75959.png">

**Comment by dejan-brkic** [comment]
Done
PR: https://github.com/craftercms/studio/pull/614
