### ISSUE TITLE
Revert to previous doesn't refresh the current item

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6597]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When a content item or config file is reverted using the `Revert to Previous` option, the UI is not refreshing to the new version correctly. I can see that a request to `item_by_path` fails because there is no path in the request.  

### Steps to reproduce

Steps:

1. Create a page from any site
2. Update a content item or config file
3. Click `History` -> `Revert to Previous`
4. See the issue

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/6722074/29f24c6f-4f77-4485-976c-93688828e144

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.4 and v4.2.0. Thank you! Closing this ticket.
