### ISSUE TITLE
Upgrade Opensearch to version 2.11

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6598]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Update OpenSearch to version 2.11

**Comment by sumerjabri** [comment]
AWS only supports 2.11 at this time, adjusted the ticket.

**Comment by phuongnq** [comment]
We upgraded to 2.13 per https://github.com/craftercms/craftercms/issues/6932

**Comment by sumerjabri** [comment]
Closing in favor of https://github.com/craftercms/craftercms/issues/6932
