### ISSUE TITLE
Document the `pathVars` variable that is available in Groovy based REST controllers 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6602]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Update the following documentation
https://docs.craftercms.org/en/4.1/reference/api/groovy-api.html#rest-scripts

To include the use and examples of `pathVars`
https://github.com/search?q=repo%3Acraftercms%2Fengine%20pathVars&type=code

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/api/groovy-api.html#path-variables

**Comment by russdanner** [comment]
Approved
