### ISSUE TITLE
Update cluster upgrade documentation to reflect the proper steps when upgrading between minor versions

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6607]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The `Copy DB folder` step that is required from  `3.1` to `4.1` upgrade is not required for minor versions, e.g. `4.1.2` to `4.1.3`.

CI: 4838

### Describe the solution you'd like

Update cluster upgrade documentation to reflect the proper steps when upgrading between minor versions
https://docs.craftercms.org/en/4.1/by-role/system-admin/upgrade/upgrading-cluster.html#add-a-new-node-to-cluster

**Comment by sumerjabri** [comment]
@alhambrav please add a link to the docs and assign to @russdanner to validate.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/system-admin/upgrade/upgrading-cluster.html#add-a-new-node-to-cluster
