### ISSUE TITLE
Studio UI not blocking when deploying Studio Server while server is running

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6615]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When deploying studio while the server is running, the `socket-connection-error` fetch fails and it doesn't get catched, causing the UI not to be blocked.

### Steps to reproduce

Steps:

1. Go to editorial based site.
2. While logged in and in preview, do a `./gradlew build deploy -Pmodules=studio`
3. When deploying, see how the `socket-connection-error` fetch fails
4. See how the UI is not being blocked.

**Comment by sumerjabri** [comment]
We should review the behavior once this is completed.
