### ISSUE TITLE
[studio] Remove authentication from RepositoryJob and subclasses

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#662]
Please remove the authentication mechanics from RepositoryJob and all subclasses and make it work without that.
Please remove the configuration items related to this from studio-config.yaml and the constants and related files.

**Comment by sumerjabri** [comment]
Please double-check that publishing is working.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/616
