### ISSUE TITLE
Update Dependencies 3/24

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6626]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Please process dependency updates mentioned below

### Describe the solution you'd like

https://github.com/craftercms/js-sdk/pull/81
https://github.com/craftercms/js-sdk/pull/84
https://github.com/craftercms/js-sdk/pull/85
https://github.com/craftercms/js-sdk/pull/88 - We must do this one on studio too. We need to pre-check compatibility with other libs like redux-toolkit and redux-observable

**Comment by jvega190** [comment]
@rart  https://github.com/craftercms/js-sdk/pull/81 this one was originally updated in this PR https://github.com/craftercms/js-sdk/pull/75 as part of the unit tests work. The version is already the latest one from the dependabot PR
