### ISSUE TITLE
When running in Serverless Delivery, don't indicate to the UI that there are blob-stores

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6630]
### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [x] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When duplicating a project today, the user is asked to choose if the blob stores are read-only or not:

![Image](https://github.com/craftercms/craftercms/assets/3931908/2ceedd82-9e4b-4b3c-9134-e99e8b46b28a)

In Serverless-mode, the S3 buckets are always duplicated and there is no point in making them read-only.

### Describe the solution you'd like

The API `/studio/api/1/services/api/1/site/get.json?site_id=` should not return blob-stores if running in Serverless mode.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.2-SNAPSHOT`

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
