### ISSUE TITLE
Make default error pages beautiful

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6631]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Today our default error pages are less than beautiful :)

![image](https://github.com/craftercms/craftercms/assets/169432/d956d2b8-557f-4990-82f7-f01faeb0bd56)

### Describe the solution you'd like

Make them beautiful.

**Comment by rart** [comment]
@jvega190 ping me for template design

**Comment by russdanner** [comment]
Confirmed in 4.2
