### ISSUE TITLE
XB should initialize properly on error pages when the underlying page with an error has a model

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6632]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Today when an error occurs on a page and an error template renders XB does not load
1. Default page templates do not contain XB markup (but should)
2. XB will not load because the model for the page is not sent into the template

### Describe the solution you'd like

1. Update default templates to include XB markup
2. Find the right way to include the page model in the error template when a page model exists.

**Comment by russdanner** [comment]
Additional details
https://www.loom.com/share/a98cfb08f0fb4b3495bedc6a626d7a0f

**Comment by jvega190** [comment]
@sumerjabri in the video Russ mentions that when an error happens, engine doesn't send the model of the page being previewed. We need a back-end update for engine to send the model so we can initialize XB

**Comment by jvega190** [comment]
I can take a look, I'll reach somebody if needed

**Comment by rart** [comment]
@jvega190 ping me to discuss.

**Comment by jvega190** [comment]
@rart maybe before merging I can demo it to you so we can check if the behavior is correct

**Comment by rart** [comment]
@russdanner we kept it simple. We didn't hack engine to conditionally add the original request's page model as that won't always work. Error pages simply check in with XB so it stops waiting for a page check in and it works normally.

**Comment by russdanner** [comment]
@roy Let's think about this use case:
1. Go to Editorial
2. Edit the template
3. Mangle the import for Crafter as follows: `<#import "/templates/system/common/crafter.ftl" as crafterX />`
4. Note this doesn't blow up the page to the point of an error page but the XB fails to load 

In a sense, we've created a scenario in which the user has not added the correct markup. 
In this case we have access to the model -- we probably could boot XB if we wanted to.

is the thinking that we can't count on the /site/website structure? I get that in the case of a detail page we would rather boot XB for the item in the detail page rather than the page -- but if no detail object is specified, assuming we can boot XB against the page isn't a bad assumption.

**Comment by rart** [comment]
@russdanner, XB needs to be imported and initialised. It is imported and initialised by the `crafter.ftl` (`ice.ftl`) `body_bottom` (`initExperienceBuilder`) macro, which is broken by the change on the suggested scenario.

What are you thinking in terms of how we could _boot up_ XB? We can have a discussion about potentially looking at the URL on the Host side, make an assumption and try to accommodate the existing mechanics (it is the Guest, the application itself, that reports who's being loaded) — though it is probably not very headless in nature to do so. In any case, I think this should go to a different ticket. This effort was focused on error pages checking in with the Host (i.e. Studio).

**Comment by russdanner** [comment]
It's an interesting case but a corner case. I would agree it does not warrant the complexity of injecting bootstrap code or having preview "guess"
