### ISSUE TITLE
RTE Insert link issues 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6635]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

ZD: 4817

### Describe the issue

Insert Link has several issues in the RTE:

- [ ] The RTE in XB does not show data sources even though they are connected
- [x] Inserting a link to a page (via RTE in content form) to a page generates a link in the form `/site/website/mypage/index.xml` rather that `/mypage` 
- [ ] The RTE control allows content type designers to select data sources that it cannot use

### Steps to reproduce

Steps:

1. Go to editorial site
2. Edit homepage
3. Go to the field Hero Text and click on insert a link button
4. Click in the URL button and it says "No datasources available"
5. Cancel the changes
6. Go to Project Tools / Content Types and edit Home
7. Follow the steps here for field Hero Text: https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/rte-configuration.html#inserting-links-to-pages-in-the-rich-text-editor-rte

8. Open the content type with the Rich Text Editor (RTE) to be setup. Open the Sidebar and click on projectTools and select Content Types. Select the content type with the RTE you’d like to setup, then click on the Open Type button.
9. Setup the data source to select a page from the site. From the content model definition, go to the Data Sources panel and drag File Browse to the the Data Sources section of the form and fill in the following properties:
-10Title : Data source title to show on the form e.g. Pages
11 Name : Name of variable to store the final result in e.g. pages
- Repository Path : Path where to browse the pages from e.g. /site/website
12. Bind the data source setup above to the RTE. From the content model definition, click on the RTE you want to be able to browse or search for pages and insert links to them. Next, go to the Properties Explorer panel and scroll to the File Manager property. Put a check mark on the box next to the data source previously setup to bind it to the RTE.
13 Click on the Save button to save your changes. The RTE is now setup to allow a user to browse or search for pages and insert links to them.

14. Go and edit homepage again.
15. Go to field Hero Text and click on insert a link button
16. Click in the URL button and now you see "Pages"
17. Select a page, for example technology
18. Check the result URL: /site/website/technology/index.xml

### Screenshots and/or videos

https://www.loom.com/share/3d1de8b131c74f80bea70e4248fa7dc1?sid=26611188-fe40-45f4-b4d1-baf32fe94520

**Comment by rart** [comment]
@russdanner form portion of the issue has bee fixed. We might need several tickets for each matter. Specially since some are larger efforts.

@jvega190 port to develop.

**Comment by sumerjabri** [comment]
@rart please explain to @Euquimides what's actually been fixed in this ticket since we won't be addressing XB yet.

**Comment by rart** [comment]
@Euquimides
- XB still has no visibility of datasources other than images which was added as a one-off some time ago
- Forms insert link should now work
- No updates done on the type editor so any datasources that were able to be associated with an RTE would still be available.

We might need to split this ticket into others to address the other matters. That's something to discuss with Sumer after 4.1.4.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.4. Will keep updating when fix for other versions is added.

**Comment by sumerjabri** [comment]
@russdanner please create another ticket for XB

**Comment by Euquimides** [comment]
Hi! Update and rechecked this issue. Fix verified. Thank you! Closing this ticket.
