### ISSUE TITLE
Valid email address should follow RFC rules

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6645]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CI: 4872
Today some email addresses with some special characters are invalid in Studio, for example, an apostrophe character but they are valid according to RFC: https://datatracker.ietf.org/doc/html/rfc3696#section-2
Ex: `crafter.D'studio@email.com` should be a valid email address.

### Describe the solution you'd like

Please extend the valid email address according to RFC: https://datatracker.ietf.org/doc/html/rfc3696#section-2

**Comment by jvega190** [comment]
@sumerjabri @jmendeza the backend needs to be updated too, as the user creation fails with some of the RFC valid emails

**Comment by sumerjabri** [comment]
@phuongnq please help with the backend part of this ticket. This should be ahead of 4.2 tickets.

**Comment by phuongnq** [comment]
@sumerjabri I used the regex from https://emailregex.com/ (similar to front-end):
```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```
 but have extending the group `[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f\\\]` (added `\` character, it the same with `\x5c` but ESAPI does not work with `\x5c`) to support the test case `"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com`.

Some test cases are from: https://en.wikipedia.org/wiki/Email_address

**Comment by sumerjabri** [comment]
@jmendeza I assigned you to this ticket for the Code Review step. Once you're done with the code review, assign me if approved. If not approved, bring back Phil to this ticket.

**Comment by jvega190** [comment]
@sumerjabri @rart @jmendeza there are some cases from https://en.wikipedia.org/wiki/Email_address that are not matching with current regexes (like the IPv6 as we discussed). But it seems like there are a couple of false positives in the backend regex from the invalid email addresses: `a@b@c@example.com` and `i.like.underscores@but_they_are_not_allowed_in_this_part`. They are being allowed by the backend (they're not allowed by the UI regex, which is correct).

I also tried with the original email provided in the ticket (`crafter.D'studio@email.com`) but the backend is failing. Can you please verify @phuongnq?

**Comment by jvega190** [comment]
@rart I didn't continue adjusting the backend regex due to the limitation mentioned above. Though this characters in the java regex don't seem to be working in javascript regexes (`[\x01-\x09\x0b\x0c\x0e-\x7f]`). I tried several options for those characters but I had no luck. Do you have an idea for those characters to work in js?

**Comment by phuongnq** [comment]
@jvega190 You are correct that the backend regex did not support the capital cases. I have fixed this.
I also added support to the case of Ipv6 and made it invalid for the case of underscore in the domain part.
Please check the details in the updated test cases.
cc @sumerjabri

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.

**Comment by Paul609** [comment]
This may not pertain to this but I got something I would like to say. For the last 16yrs  the IETF AND FBI AND GOOGLE AND OTHERS HAVE BEEN VIOLATING MY CIVIL RIGHTS.  I HAVE documents to prove it. I have also seen alot on github that shows it also. I see things about my account that has been done that isn't compliant and nobody does or says anything about it. WHY IS THAT?

**Comment by Paul609** [comment]
I have seen deleted files and changed files and ignored files. WHY IS THAT?

**Comment by Paul609** [comment]
I believe I have been abused by benchmarking for the last 16 yrs.Wait, I know I have.
