### ISSUE TITLE
[studio] Bulk publish doesn't work for `/`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#665]
Create a site, make massive updates in git. Run sync from repository. Do bulk publish. Database looks like this:

`MariaDB [crafter]> select * from cstudio_copytoenvironment where site='dejan';
+----+-------+-------------+------+---------+----------+---------------------+----------------+--------+------------------+-------------------------------+
| id | site  | environment | path | oldpath | username | scheduleddate       | state          | action | contenttypeclass | submissioncomment             |
+----+-------+-------------+------+---------+----------+---------------------+----------------+--------+------------------+-------------------------------+
| 96 | dejan | live        | /    | NULL    | admin    | 2017-03-31 19:55:44 | READY_FOR_LIVE | UPDATE | pages            | Bulk Go Live invoked by admin |
+----+-------+-------------+------+---------+----------+---------------------+----------------+--------+------------------+-------------------------------+
1 row in set (0.00 sec)`

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/626
