### ISSUE TITLE
Add more information to access token properties in the Studio override file

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6656]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

It would be nice to have more information on the access token properties in the Studio override file

### Describe the solution you'd like

Add more information to the properties listed in the Studio override file https://docs.craftercms.org/en/4.1/reference/modules/studio/security.html#access-tokens

**Comment by sumerjabri** [comment]
@russdanner bump

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/modules/studio/security.html#access-tokens
