### ISSUE TITLE
Add a section in the Deployer about asset jackets

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6657]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

CI: 4861

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

We do not have an article on asset jackets

### Describe the solution you'd like

Add a section in the Deployer about asset jackets. CrafterCMS supports the deployer's ability to index the content of a rich document (PDF, DOC, DOCX, PTT, etc.) along with metadata and content found in an associated descriptor item (the items reference the rich document). We call the item a Jacket.

**Comment by alhambrav** [comment]
@russdanner I was wondering if I can get a sample `jacket` file for the docs? Thank you!

**Comment by russdanner** [comment]
Jacket and video converting functionality delivered via Slack.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/modules/deployer/index.html#jacket
