### ISSUE TITLE
Update UM `ui.xml` template for sites coming into v4+

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6660]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When a project comes from a version prior to 4 into 4+, UM will add an `ui.xml`. It seems that template for `ui.xml` has fallen a bit behind. For example the string "Site Tools" was never updated to "Project Tools".

### Describe the solution you'd like

Identify the out of date content and update the template so projects coming to 4 have latest `ui.xml`.

`<title id="siteTools.title" defaultMessage="Site Tools"/>` should be `<title id="siteTools.title" defaultMessage="Project Tools"/>`

**Comment by sumerjabri** [comment]
@phuongnq here is the file https://github.com/craftercms/studio/blob/16ad28f104f51dd4cdd2b945c8568268fdf0d3e6/src/main/resources/crafter/studio/upgrade/4.0.x/config/ui/ui.xml#L87

To reproduce, you upgrade from 3.1 to 4.0/.1/.2

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.0.8, v4.1.4 and v4.2. Thank you! Closing this ticket.
