### ISSUE TITLE
Dependencies incorrectly showing for a recently created (empty) folder

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6665]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

After creating a folder called `a` under `/templates/web/pages`, if you try to delete the folder `a`, it'll show a lot of dependencies

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Create a folder called `a` under `/templates/web/pages`
3. Delete folder `a`
4. See how there are a lot of incorrect depentent items

**Note** It seems like it is matching `article` related items. It also happens with folders called `ar` or `arti`. Maybe something with a query?

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/18267471/cd0ef735-ea2f-4692-9c2d-edc694cad04b)

**Comment by jmendeza** [comment]
This can be fixed by sending a trailing slash (`/`) when requesting dependent items or delete package for a folder.
Checking if the given path is a folder in the backend might get expensive, specially when checking multiple items

cc @sumerjabri

**Comment by jmendeza** [comment]
Actually, I solved it by tweaking the query so it performs an exact match on the path or a like for the children ('/%')

**Comment by jvega190** [comment]
Verified fixed
