### ISSUE TITLE
Using requireModule or addJavascript with buildFileUrl creates incorrect url

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6667]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Using requireModule or addJavascript with buildFileUrl creates incorrect url.

Also, how to include plugin resources on form engine plugins is not documented.

CI: 4825

### Steps to reproduce

Steps:

1. Run the code below and observe that the request being made contains `/studio` twice

```js
CStudioAuthoring.Utils.addJavascript(
  craftercms.services.plugin.buildFileUrl(
    'YourProjectId', // e.g. editorial
    'YourPlugin"Type"', // e.g. form-engine
    'YourPlugin"Name"', // e.g. controls
    'YourFileName.js', // e.g. orgname-fe-common.js
    'YourPluginId' // e.g. com.orgname.plugin.foo
  )
);
```

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
