### ISSUE TITLE
[studio-ui] Add site name to the site editor

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#667]
Please add the site name to the site editor as shown below:

![screen shot 2017-03-31 at 4 56 32 pm](https://cloud.githubusercontent.com/assets/3931908/24569277/66363164-1633-11e7-9065-d5a00890f023.png)

Note: In the example above, the site name happens to be `111`

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/328
