### ISSUE TITLE
Add support for audio icons in Sidebar

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6677]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When an user upload audio files though the new audio datasource, the assets display an `?` icon instead of a proper audio icon

### Steps to reproduce

Steps:

1. Enable the audio datasource #6535 
2. Upload an audio file (mp3, ogg)
2. Verify the asset in the sidebar
3. See the issue

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/6722074/3ef3c7fb-f716-46fa-978f-49b2c135da16)

**Comment by rart** [comment]
@jvega190 we also need to extend the Preview dialog support for this kind.

**Comment by yacdaniel** [comment]
Verified fixed in `4.1.x` 


![Image](https://github.com/craftercms/craftercms/assets/6722074/7e9c1fd3-6aa4-4afb-9411-7609873be059)

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
