### ISSUE TITLE
UI does not handle failure on duplicate site request

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6683]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Duplicate site request failures (e.g.: status 400 or 500) on the backend, are not handled by the UI. When the request fails, the UI continue to create site wait dialog:
![Screenshot from 2024-04-15 12-11-41](https://github.com/craftercms/craftercms/assets/6042406/c54399ec-2835-4e70-9f77-b066ee9db0b5)

### Steps to reproduce

Steps:

1. Create a large site, so it takes long to duplicate
2. Go to the Projects list screen and duplicate the site.
3. Close the wait dialog
4. Try to create the same site once again
5. The backend will respond an error, since the origin site is not in READY state.
6. The UI will be stuck in the wait dialog.

Expected behavior:
The UI should somehow inform the user that an error has occurred

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
