### ISSUE TITLE
Activity dashboard - non admin users can't filter by username 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#6684]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Dashboard: When a non admin user try to filter usernames in the Activity dashlet, the user gets a Unauthorized response.

### Steps to reproduce

Steps:

1. Log in with an author user
2. Go to Dashboard -> Activity dashlet
3. Try to filter by username
4. See the issue

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/6722074/f3430350-6d4d-4f8b-bc95-d0021715cd71)

**Comment by sumerjabri** [comment]
@yacdaniel, we missed this in QA; please add it to the automation plan.

**Comment by jmendeza** [comment]
Activity dashlet make use of privileged `/users` API, which will be restricted to users with `read_users` permission.
To support filtering by username, activity API has been updated so it accepts the start of usernames for filtering (e.g.: `adm` will match `admin` user).

**Comment by sumerjabri** [comment]
@yacdaniel please validate this ticket as well.

**Comment by yacdaniel** [comment]
@rart I'm not able to get all the activities by removing the username filter, please take a look


https://github.com/craftercms/craftercms/assets/6722074/948fea6d-ebde-43b5-b1ea-209cc7c897df

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
