### ISSUE TITLE
Add default policy engine updates/behaviorial changes to 4.1.x breaking changes doc

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6685]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The policy for file naming introduced by the upgrade manager enforces behaviors for existing sites that may break existing process and integrations.

### Describe the solution you'd like

Update the breaking changes documentation in 4.1.x to indicate that the upgrade manager has introduced a project level policy updates that enforce file naming conventions.
- all non-alpha numeric characters are converted to -
- all characters are converted to lowercase

This naming convention policy is considered a best practice. Howvere, these rules can be modified via configuration or disabled for existing projects where these rules are not aligned. [LINK to relevant config documentation]

**Comment by sumerjabri** [comment]
This was a bug with the ticket https://github.com/craftercms/craftercms/issues/6104. Closing this ticket.
