### ISSUE TITLE
`disabled` flag is ignored by Content Item API but is respected by Search API

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6686]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

CI:4952

### Describe the issue

A disparity has been noticed between how /api/1/site/content_store/item.json treats content marked with the `disabled` flag vs how /api/1/site/search/search.json does. The former returns content when `disabled: true` while the latter filters these out. 

### Steps to reproduce

Steps:

1. Create site based on Editorial
2. Use the following to add the disable option to your Entertainment Category Landing content type: https://docs.craftercms.org/en/4.1/by-role/author/index.html#disabling-a-page
3. Content Item API:
GET http://localhost:8080/api/1/site/content_store/item.json\?crafterSite\=checkcheck\&url\=/site/website/entertainment/index.xml
---> Returns disabled item. The item data contains a field `"disabled": "true"`.
4. Run and add the path to the entertainment landing page into the body `POST http://localhost:8080/api/1/site/search/search.json\?crafterSite\=checkcheck\&flatten\=true`
5. See that this returns 0 results

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

N/A

**Comment by sumerjabri** [comment]
This is the correct behavior. I'll explain: When an item is disabled, it will be removed from search in Preview, Staging, and Live to help the rendering application that relies on search to "disappear" said item. However, Engine will continue to return the item if requested directly in Preview and will hide it in Staging and Live as if it doesn't exist. The reason Engine allows the retrieval of the disabled item in Preview only is to allow the authors to _see_ the disabled item, _know_ it's disabled, and enable it if they want to.

Based on the above, I'll close this ticket.
