### ISSUE TITLE
Document default `type` behavior change in `4.0.x` - `4.1.x` for items located under `/site`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6695]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [x] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

In CrafterCMS 3.x, all item types under `/site` were defaulted to type `item`.  In `4.0.x` - `4.1.x` the default is `file`

Items under known paths e.g. `/site/website` and `/site/component` the type is `item` as these are preconfigured in studio.xml

Non-standard paths / custom paths must be configured in the `studio-config.xml` prior to ingestion into the system in order to be classified correct

Any item that is misclassified can be corrected by updating the configuration and then editing and saving the misclassified item(s)
OR by modifying the type field for the item in the `item` table in the database.

### Describe the solution you'd like

Document the need to configure paths in the `studio-config.xml` in 4.0.x and 4.1.x

Note this behavior will be returned to the previous default in a future release:

CI: 851

**Comment by sumerjabri** [comment]
Perhaps this needs to flow into 4.0 and 4.1 breaking changes. In 4.2, we intend to treat all items in `/site` as `item`.

**Comment by sumerjabri** [comment]
@alhambrav, please add the links to the articles you updated. Once done, remove yourself from the assignees.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/release-notes/4-1-x-breaking-changes.html#breaking-changes-4-1-x
https://docs.craftercms.org/en/4.0/release-notes/4-0-x-breaking-changes.html#breaking-changes-4-0-x
