### ISSUE TITLE
Using File Upload from Desktop Datasource throws UI failure when Dialogue is open and closed

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6697]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

An issue has been found in the control/datasource to upload Files from desktop, if the user cancels the upload more than once and finally uploads an image or item successfully, then an error appears and confuses the author. The error appears in the dialog the same number of times that the upload was cancelled, and even when the upload was successful, the message is shown.

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Go to Project Tools > Content Types
3. Edit content type Home PAge
4. Add a datasource to upload files (File Uploaded from desktop)
5. Add an Item selector field and choose the previous created DS as file manager.
6. Save
7. Go to Sidebar and edit the Home Page
8. Choose upload a file and cancel the upload several times, take note of the number of times.
9. Then finally upload a file successfully, and you will see an error repeated times.

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

https://www.loom.com/share/77771684c65b41a0bdeb99556a568edb?sid=e41a12db-9845-498e-8165-5a50307f6870

**Comment by russdanner** [comment]
@rart it looks like the solution here was to remove the ability to "cancel" the dialog.  Is there a reason why that's the best solution? This could lead to the following scenario:
1. User clicks the upload dialog accidentally
2. They can't close the dialog to choose a different data source
3. They press escape trying to find a solution
4. The entire form closes

**Comment by AndyReiter** [comment]
@rart One other thing I noticed with this solution is that the `Choose File` button in the upload dialogue is grayed out/dimmed, but when you click it, the browse dialogue opens up to select a different file.

**Comment by jvega190** [comment]
Hi @russdanner @AndyReiter. Are you doing some different steps than the ones in the video? I just built, and I'm not seing the dialog's cancel ability disabled, and I don't see the button grayed out.
The solution was not to remove the 'cancel' ability in the dialog, so there may be another thing going on.
Please see the behavior that I see when following the steps:
https://www.loom.com/share/3c87fae6373d4da980ba485a7ddbc3dc

**Comment by AndyReiter** [comment]
@jvega190 My build was out of date. Upload looks good to me now. 

One other thing I noticed, which is probably a different conversation, is the "Choose File" button still has functionality when a file is being uploaded. I can reproduce with either a throttled browser or a large file.

https://www.loom.com/share/a7f595a4a6d647da83f2e34f66510500?sid=19c3ac06-692f-46e2-bc79-bc791364a768

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
