### ISSUE TITLE
Dropdown form control field should support values of type `_i` and `_f`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6704]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CI: N/A

Currently, admins must configure a value of type `_s` when using a drop-down. In many cases, storing the value as `_i` or `_f` would be useful. Currently, admins must configure a value of type `_s` when using a drop-down.

### Describe the solution you'd like

Allow variable types of `_i` and `_f` when using a dropdown control

**Comment by rart** [comment]
@jvega190 some things to bear in mind:
- Update any relevant tooltips on the type editor property sheets
- Check if any piece of the SDK (authoring or delivery parsers) needs updating due to this change

**Comment by jvega190** [comment]
> @jvega190 some things to bear in mind:
> 
> * Update any relevant tooltips on the type editor property sheets
> * Check if any piece of the SDK (authoring or delivery parsers) needs updating due to this change

In the SDK, the parseFieldValue validates the type using the suffix, so when `_i` or `_f` it'll parse float the value.
https://github.com/craftercms/js-sdk/blob/develop/packages/content/src/utils.ts#L206
Tested with the `parseFieldValueTypes` option set to true, and the value is properly parsed.

**Comment by russdanner** [comment]
Confirmed

**Comment by russdanner** [comment]
Confirmed in 4.2
