### ISSUE TITLE
Adding a non-existent or non-defined macros into `Destination Path Pattern` and using quick create, will launch an error form that can't be closed

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6705]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Adding a non-existent or non-defined macros into `Destination Path Pattern` and using quick create, will launch an error form that can't be closed. 

Expected from the fix: we need some way to validate macros in the Content-Type creation form, to avoid this kind of issues.

### Steps to reproduce

Steps:

1. Create a new project, it can be based in Editorial.
2. Go to Project Tools > Content Types > Article
3. On "Destination Path Pattern" add a non-existen or non-defined macro, such as `{blah}`.
4. Save the Content Type.
5. Refresh the Browser window.
6. Go to `Quick Create` and try to create a new `Article`, the form will show an error, and it can't be closed. 

### Relevant log output

```shell
HTTP Status 400 – Bad Request

Type Exception Report

Message Invalid character found in the request target [/studio/form?site=a1&form=/page/article&path=/site/website/articles/{blah}&isInclude=undefined&iceComponent=true&editorId=a790baff-a074-eac8-9512-d2634498fb81 ]. The valid characters are defined in RFC 7230 and RFC 3986

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Exception

java.lang.IllegalArgumentException: Invalid character found in the request target [/studio/form?site=a1&form=/page/article&path=/site/website/articles/{blah}&isInclude=undefined&iceComponent=true&editorId=a790baff-a074-eac8-9512-d2634498fb81 ]. The valid characters are defined in RFC 7230 and RFC 3986
	org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	java.base/java.lang.Thread.run(Thread.java:840)

Note The full stack trace of the root cause is available in the server logs.
```

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/90878288/9c98ffed-e862-40d0-befd-39abe9ee88cf

![Screenshot from 2024-04-23 12-55-09](https://github.com/craftercms/craftercms/assets/90878288/b001265b-ee3c-46a5-aef1-d142bfd1b8f8)

**Comment by rart** [comment]
@jvega190 the error is caused by unrecognised macros ending up on the url e.g. `/site/website/{mm}/{hello}` => `/site/website/04/{hello}`. Let's make the macro processor remove unrecognised macros so `/site/website/{mm}/{hello}` => `/site/website/04`

**Comment by Euquimides** [comment]
Hi @rart and @jvega190 ! While validating this ticket I noticed the following case:

If adding a macro with double `{ }` such as `{{test}}` will show up the HTTP 400 error window when quick creating an item (such as an article or a post). This window can now be closed, that's the difference. Should we consider adding the same fix as indicated here?

> @jvega190 the error is caused by unrecognised macros ending up on the url e.g. `/site/website/{mm}/{hello}` => `/site/website/04/{hello}`. Let's make the macro processor remove unrecognised macros so `/site/website/{mm}/{hello}` => `/site/website/04`

Please take a look at this. Thanks!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for 4.2.x.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket for v4.1.x I noticed that the recent regex change for rejecting non-existent macros with  `{{ }}` might have impacted unrecognized macros with `{ }`. For example, the destination path path `/site/website/{mm}/{hello}` will show up a HTTP 400 on `Quick Create` but the destination path  `/site/website/{mm}/{{hello}}` will be removed adequately by the macro processor. This seems to be present also in v4.2.

Could you please check this out? Thanks!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
