### ISSUE TITLE
Validate macros in Content Type form before saving

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#6707]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When creating Content Types, we are not validating if the macros being added (such as {year}, {month}, {objectId}) exists or not. We should validate that the macros being added is indeed supported, before saving and closing the edition or creation of the Content-Type. 

For example `objectId` and `parentPath` are macros that according to the documentation are supported, but are not working right now. 

### Steps to reproduce

Steps:

1. Create a new project based in `Editorial`
2. Go to Project Tools > Content Types > Article.
3. Edit "Destination Path Pattern" to include `{objectId}` macros. 
4. Save the Content Type. 
5. Go to quick create menu and create a new article.
6. See the issue: a folder named `-objectid-` is created, instead of the ID of the item. 

### Screenshots and/or videos

![Screenshot from 2024-04-23 11-50-50](https://github.com/craftercms/craftercms/assets/90878288/a69f1cb5-f037-493c-af85-978d662b0ae5)

**Comment by sumerjabri** [comment]
Some customers use custom macros. @rart, please think of a design that supports custom macros or does not prevent them from working.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While reviewing the fix for this ticket, I noticed that in the case of `{objectGroupId}`, `{objectGroupId2}`, `{parentPath[index]}` the validation is not working as with `{objectId}` and `{parentPath}`, since it still saves the macros in the Content Type form. Can you please check this out? Thank you!

**Comment by jvega190** [comment]
@Euquimides please note that for `{parentPath[index]}` macro, index is an actual number.
e.g: `parentPath[2]`.
For `objectGroupId/objectGroupId2`, I'll send an update to validate those too

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
