### ISSUE TITLE
[craftercms] Error when accessing delivery environment

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#671]
Error when accessing delivery environment.
I tried accessing the delivery environment through port 9080 and I get an error:

<img width="1436" alt="screen shot 2017-03-31 at 5 32 55 pm" src="https://cloud.githubusercontent.com/assets/25483966/24570212/4dca2946-1638-11e7-80b7-dd878e338d27.png">

**Comment by sumerjabri** [comment]
@cortiz this is after a vanilla build from craftercms bundle. Reach out to Vita if you have questions.

**Comment by cortiz** [comment]
Fixed on PR #798
