### ISSUE TITLE
Make the file size limit configurable for the `WriteConfigurationRequest` annotation

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6710]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CI: 4974

The size limit for `WriteConfigurationRequest` is not configurable.

### Describe the solution you'd like

Make the file size limit configurable for the `WriteConfigurationRequest` annotation

**Comment by sumerjabri** [comment]
@alhambrav, please document this new feature/configuration.

**Comment by russdanner** [comment]
Confirmed in 4.2.0
