### ISSUE TITLE
Capital letter rules in Rename dialog are not stated in the UI

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6715]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Rename dialog doesn't allow capital letters but there's no visibility or feedback around enforcing this rule

### Describe the solution you'd like

Display all constraints/requirements clearly, provide feedback on the matter. Also facilitate task completion by auto-lowercasing instead of blocking the upper case input.

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`


![image](https://github.com/craftercms/craftercms/assets/6722074/f083c508-7ddb-4c62-b978-82ebd07c59af)
