### ISSUE TITLE
[studio-ui] Editorial BP D&D doesn't work

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#674]
Create a site with Editorial BP
- Click on the wrench
- Click on Page Components
- Try to drag and drop, it won't let you drop

Delete all objects in D&D zone, then try again, it will then work.

**Comment by vestrada** [comment]
Hi!

The studio is validating that you can't drop one component that is already on the section.  
For example if you remove just one: "Portitor ullamcorper", and then you drop it using browse, it will work.

**Comment by sumerjabri** [comment]
@vestrada Would it be possible to check if the component is already added, and notify the user that the component is already in there and therefore cannot be added again?

**Comment by vestrada** [comment]
@sumerjabri: Yes, It is possible.
Should I work on it?

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/379
