### ISSUE TITLE
Files are overwritten when a read-only file-name is configured with a default value

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6744]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CI:5015

We have a particular use case where we want to allow no more than 1 file per directory of a particular content type, and that file name should always be "root" (so it ends in "/root.xml"). We set the file-name field to be read-only, and set a default value of "root" to enforce this. This works for the initial creation, however, if you try to add a second content item to the same directory, the field validation on the file-name field doesn't run and doesn't prevent duplicates like if the field weren't readonly. The form then successfully submits and the new file replaces the existing one. 

This can be reproduced with the following steps:
1. Create a new site from Editorial BP
2. Update the Header content type to have the `file-name` with a default `root` value and in `readonly` mode:
![edit_content_type](https://github.com/craftercms/craftercms/assets/2996543/3c591641-dc88-492e-b268-da7371b00cac)
3. Create a new Header content type, notice that the Component ID is `/components/headers/root` which is correct and in read-only mode
![root_header](https://github.com/craftercms/craftercms/assets/2996543/1c032d18-7e43-459c-b694-8bad13dcdf46)
4. After the component is created in step 3, create a new Header component:
![should_not_be_possible](https://github.com/craftercms/craftercms/assets/2996543/13168b11-f599-4be4-920f-a6655562655f)
5. Save the component in step 4, notice that it overrides the component in step 3 which is not an expected behavior
![2024-05-03_14-45_1](https://github.com/craftercms/craftercms/assets/2996543/d12f775e-71c8-47db-89e3-de15f0903e6c)

### Describe the solution you'd like

My expectation is the form would be prevented from submitting, or at the very least there'd be a warning that the file would be overwritten.

**Comment by phuongnq** [comment]
@sumerjabri What would be the expected behavior for this case? Should we block the new content creation? 
The backend does not know if we are creating new content or editing the old content (since they have the same path and we don't send any parameters to identify if we are editing or creating new content).
We should keep the existing content editable while blocking the creation of new content by using the 'Create New' option. This makes me think this should be a UI check to block the creation.

**Comment by sumerjabri** [comment]
@rart, the control should be in error, and the user shouldn't be able to save (clobber) an existing file. Ping Russ for more information.

Note sure what to do with XB yet. It should be the same thing, prevent clobbering existing content.

**Comment by phuongnq** [comment]
verified!
