### ISSUE TITLE
[studio-ui] 500 error page for logged out users

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#675]
Log out of studio or wait for it to timeout and go to this URL http://studio3.com/studio/site-dashboard

You'll see the screen below:
![screen shot 2017-04-04 at 9 48 35 am](https://cloud.githubusercontent.com/assets/3931908/24659855/ee76eb64-191b-11e7-868e-e0a0794621c4.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio/pull/633
