### ISSUE TITLE
Dependency management 5/24

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6789]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Various main dependencies have newer versions

### Describe the solution you'd like

Upgrade 
- yarn
- rollup
- graphiql
- prettier
- react-hotkeys-hook
- react-intl
- react-redux
- uppy
- @craftercms/*
- tinymce
- sass
- @mui/*
- rimraf
- @babel/cli
- @prettier/plugin-xml
- @reduxjs/toolkit
- @types/jquery
- @types/node
- tss-react

Downgrade:
- eslint

Run an audit and remove unneeded packages

**Comment by jvega190** [comment]
@prettier/plugin-xml was downgraded to v3.3.0 due to an issue introduced by version 3.3.1. Ticket was reported [here](https://github.com/prettier/plugin-xml/issues/784)
