### ISSUE TITLE
[studio]Published page does not appear in the "Recently Published" widget in admin dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#679]
Published page does not appear in the "Recently Published" widget in admin dashboard .

1. Log in to Studio as an author, create a new article page and request publish
2. Log in to Studio as admin, approve the publish request from author.
3. Open the dashboard (admin), the newly published page is not listed in the "Recently Published" widget, but the JPG file inside the newly published page is listed as published.

![screen shot 2017-04-04 at 9 57 12 am](https://cloud.githubusercontent.com/assets/25483966/24660791/7c0ff612-191e-11e7-9eaf-23e02ae8c0f5.png)

4. Open the dashboard (author), the published page does not list a "Publish Date" in the "My Recent Activity" widget after being published

![screen shot 2017-04-04 at 9 57 19 am](https://cloud.githubusercontent.com/assets/25483966/24661103/739e8358-191f-11e7-80a6-101014470bd3.png)

5. Notice too in the admin dashboard, that selecting "Pages" as content type filter still displays the JPG file in the Recently Published widget. ("My Recent Activity" widget content type filter works properly, just the "Recently Published" widget's content type filter is not working)
![screen shot 2017-04-04 at 10 15 51 am](https://cloud.githubusercontent.com/assets/25483966/24661310/103f9dbe-1920-11e7-8a0f-861f961a46d1.png)

**Comment by dejan-brkic** [comment]
Can not reproduce 3.

Steps 4. and 5. are reproduced.

**Comment by alhambrav** [comment]
I also cannot reproduce number 3 anymore.  Please ignore step 3.
Steps 4 and 5 are reproduced too.

**Comment by dejan-brkic** [comment]
Done
PR: https://github.com/craftercms/studio/pull/634
