### ISSUE TITLE
There is no README.txt file in the bundle created by Gradlew

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#680]
Follow the instruction in (README.md) https://github.com/craftercms/craftercms to create a bundle.
Copy the zip file to a folder and unzip, there is no README.txt file in the unzipped folder.

![screen shot 2017-04-04 at 10 28 27 am](https://cloud.githubusercontent.com/assets/25483966/24661832/7804d6ac-1921-11e7-9551-d6b2c3ed768f.png)

**Comment by sumerjabri** [comment]
Dupe of https://github.com/craftercms/craftercms/issues/676
