### ISSUE TITLE
Logout and Login APIs don't work correctly after the recent upgrades

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6807]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Logout API is giving a 403 response. Also, re-logging in after a timeout is giving a 403 response.

### Steps to reproduce

Steps:

1. Login into studio
2. Open the navigation menu and click on 'logout'
3. See the issue

* Re-logging
1. Login into studio
2. Wait for the session to expire and try to login again
3. See the issue

### Screenshots and/or videos

![Screenshot from 2024-05-14 12-26-58](https://github.com/craftercms/craftercms/assets/18267471/d03ce3c9-12ab-46e2-9c36-fd3afca5d707)

**Comment by phuongnq** [comment]
This is a spring security issue in v6 where it is expecting the csrf string to be encoded in base64, which is not the case for JavaScript applications: https://github.com/spring-projects/spring-security/issues/12869
The solution is to use a delegate to handle the raw csrf string.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket
