### ISSUE TITLE
Item stuck in read only mode if the lockedOwner value is not null

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6808]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

ZD:4846

Today there are two fields that the system uses to determine if an item is locked: the `locked_by` value and the `state`. In some cases, for example during an upgrade from 3.1.x to 4.1.x, the item state is unlocked but `locked_by` has a value. In this case, the item is stuck in read-only mode and there is no way to clear this mode other than directly updating DB `locked_by` to `NULL`, or letting the user with the ID of `locked_by` open the form to clear it.

`locked_by` is metadata for reference who is the locked owner but it should not be used to determine if an item is locked or not. We should only look for the `state` to determine if an item is locked.

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. After the site is created, manually update DB with `item.locked_by` to a user who is not currently logging user. Ex: `locked_by = 2`

![2024-05-15_09-32](https://github.com/craftercms/craftercms/assets/2996543/86253bad-c8f3-43e6-b3fa-e1a2e6951aee)

3. Open the Home page to edit and notice that the page is stuck in read-only mode which is not an expected behavior.

![2024-05-15_09-32_1](https://github.com/craftercms/craftercms/assets/2996543/30798025-6a66-434b-aaa4-e972682a4ecf)

**Comment by phuongnq** [comment]
@russdanner FYI

**Comment by phuongnq** [comment]
@sumerjabri I send PRs for the backend to fix the issue by checking the item state before checking the lockOwner. The item should not be considered locked if the item does not have the `locked` bit.

The front end should perform a similar update. For example, in https://github.com/craftercms/studio-ui/blob/develop/static-assets/components/cstudio-forms/forms-engine.js#L1101, we only check the `lockOwner` to mark the item as read-only. We should additionally check if the state is locked here.

**Comment by sumerjabri** [comment]
@rart please help with the UI portion of this.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
