### ISSUE TITLE
[studio-ui]Add a Cancel button to Targeting Form when changing persona

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#681]
It would be nice to have a Cancel button when changing persona in the targeting form.

1. Open the Preview Tools Panel
2. Click on Targeting
3. If I change my mind about changing the Persona, a Cancel button would be nice to have in the Targeting form.

![screen shot 2017-04-04 at 10 30 15 am](https://cloud.githubusercontent.com/assets/25483966/24662080/200a073c-1922-11e7-9c0f-e5adc9f9e5c9.png)

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/335
