### ISSUE TITLE
[studio-ui] If a file is an XML and doesn't have an internal name, use the file name when displaying in dashboard widgets

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#682]
Steps to reproduce the issue:

1. Create a site using Editorial.
2. Go to Admin Console and open a content type for edition.
3. Add any form control, like an input, and click on save.
4. In the filesystem, go to data/repos/{siteName}/published.
5. Run `git checkout -p live`.
6. Run git pull origin master.
7. Go back to Studio and refresh the dashboard.

The config.xml of the form appears in Recently Made Live, but it appears without Item Name. It should display the file name.

![screenshot from 2017-04-04 10-45-35](https://cloud.githubusercontent.com/assets/1598884/24663145/158a63d0-1925-11e7-8eaf-8219da2fb942.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/328
