### ISSUE TITLE
[studio-ui] XML extensions in Recently Made Live 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#683]
Steps to reproduce the issue:

1. Create a site using Editorial.
2. Go to Admin Console and open a content type for edition.
3. Add any form control, like an input, and click on save.
4. In the filesystem, go to data/repos/{siteName}/published.
5. Run `git checkout -p live`.
6. Run `git pull origin master`.
7. Go back to Studio and refresh the dashboard.

For some reason the path that appears in Recently Made Live for the config.xml is now changed to config.html.

![screenshot from 2017-04-04 10-45-35](https://cloud.githubusercontent.com/assets/1598884/24663412/d66c72d2-1925-11e7-8071-a2dcd9fd9486.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/328
