### ISSUE TITLE
Shared content data source incorrectly handles the display and selection of pages that have child pages

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#6844]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

A customer has noticed an inconsistency between the Node Selector's Search and Browse functionality. Currently, the Node Selector has issues selecting child pages when using the Browse option, but does not have this issue when using the Search option. 

CI: ZD 4699

### Steps to reproduce

Steps:

1. Go to Studio and select Editorial project
2. Go to project tools, content types and edit Category Landing page
3. Add a new datasource type "shared-content"
- Title Article
- Keep Enable Browse Existing and Enable Search Existing selected
- Set repository path and browse path as /site/website
4. Add a node-selector control under Articles
- Name Articles
- Select the Article datasource
- save
5. Go to side bar, Home/articles/2020/12 and create a new Article page under top-books-for-young-women. Use any content
6. Go to Entertainment Landing Page and edit
- Go to Articles , click en Add+ and select Browse for Existent Article
- In the tree at left side navigate to Home/articles/2020/12/Top Books For Young Women
- Notice the new Test Article is not shown in the center section. Instead it says "No items found."
- Try to select the new test article created from the tree.

### Screenshots and/or videos

https://github.com/craftercms/craftercms/assets/42217570/db0c1248-85e9-4658-864c-cb7b688d78b1

**Comment by jvega190** [comment]
@AndyReiter this is not happening anymore in versions 4.2.0 and 4.1.6. Can you please verify?

**Comment by AndyReiter** [comment]
@jvega190 I am still seeing this issue in my latest build of 4.2 as well as 4.1.6. Please let me know when you're available to look at this.

**Comment by AndyReiter** [comment]
This can be closed. I am not able to reproduce this in my latest build of 4.1.6 as well as 4.2 after discussing with @jvega190.

**Comment by rart** [comment]
@AndyReiter can you confirm what was the confusion or issue that seemed like the issue wasn't fixed? Did you somehow were still able to reproduce and required special handling to see it working?
