### ISSUE TITLE
[craftercms] Create backup/restore tasks

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#685]
Create backup and restore tasks in crafter.sh/bat.

This must work on *nix and Windows.

Backup process:

- mysqldump the database and zip
- zip data/repos with low compression
- zip data/indexes with low compression
- zip data/deployer
- zip the whole thing with no compression

Make sure to take the target path/filename from the caller to produce the backup.

Restore process:

- make sure the system is down
- check if data/repos exists, warn that you're going to delete it, ask user to accept
- check if data/indexes exists, warn that you're going to delete it, ask user to accept
- check if data/deployer exists, warn that you're going to delete it, ask user to accept
- start mariadb only
- restore database
- stop mariadb
- start the system
- for all sites (loop against folder in data/repos)
-- call http://docs.craftercms.org/en/latest/developers/projects/studio/api/repo/sync-from-repo.html

Ping me if you have any questions.

**Comment by cortiz** [comment]
On hold until https://github.com/vorburger/MariaDB4j/pull/71 is accepted and merged.

**Comment by vorburger** [comment]
Hello Crafter CMS community, it's cool to see you use MariaDB4j!  I've finally reviewed https://github.com/vorburger/MariaDB4j/pull/71 and will merge it ASAP after @cortiz has a chance to take some minor review feedback into account.

**Comment by cortiz** [comment]
PR with Requested changes was updated today.

**Comment by jdrossl** [comment]
@sumerjabri is the last step (sync from repo) really needed? if we include a dump from the db it should already match the state of the git repo right?

**Comment by vorburger** [comment]
@cortiz FYI I've finally merged your contributed to the MariaDB4j master (under https://github.com/vorburger/MariaDB4j/pull/81). -- Just FYI I'd like to get a few other contributions into MariaDB4j, and the perhaps can run a new release to Maven central (maybe week-end after next).

**Comment by jdrossl** [comment]
Waiting for new MariaDB4j release to close this ticket.

**Comment by jdrossl** [comment]
Hey @vorburger, I noticed in maven the platform specific packages are updated but not the parent pom, are you planning on updating it soon?

**Comment by jdrossl** [comment]
@luishernandezmonge backup/restore feature is fully functional now, please verify

**Comment by luishernandezmonge** [comment]
Tested all the backup/restore process and it is working OK.
Currently, all the sites are backed up and the user can access the site through the crafter studio
