### ISSUE TITLE
Review sync-from-repo task and its use of audit table

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#6856]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

New sync from repo algorithm in 4.2.x makes use of audit table to track processed commit IDs.
This adds to the audit table size and also makes it difficult to remove older records.

### Describe the solution you'd like

Consider adding a different table to keep track of the processed commits. This can be implemented in such a way that rows are automatically deleted when no longer needed (i.e.: all previous commits have been processed)

**Comment by jmendeza** [comment]
We can move the tracking of git commit ids to a new table:
```
CREATE TABLE IF NOT EXISTS `ingested_commits`
(
    `id`        BIGINT(20)      NOT NULL AUTO_INCREMENT,
    `site_id`   BIGINT(20)      NOT NULL,
    `commit_id` CHAR(40)        NOT NULL,
    PRIMARY KEY(`id`),
    UNIQUE INDEX `ingested_commits_commit_id_site_id` (`commit_id`, `site_id`),
    FOREIGN KEY `ingested_commits_site_id`(`site_id`) REFERENCES `site` (`id`) ON DELETE CASCADE
)
```
Once a sync has completed (meaning the site last commit id is the same as the last commit in the repo) we can delete old commits (the ones with id < last one)

@sumerjabri this is already an issue in 4.2: because the sync relies on the `audit` table, we will need to copy the `audit` records on site duplicate. Otherwise the sync task will kick in and reprocess all git commits, potentially corrupting the item states.
Copying the audit data is messy because of the columns in that table that might need to be translated based on the site (primary_target_id, primary_target_value)

**Comment by jmendeza** [comment]
Duplicate site will now duplicate `processed_commits`. `audit` table will not be duplicated.

**Comment by jmendeza** [comment]
Added new `processed_commits` table to keep track of git commits. Older records get deleted once db and repo get in sync

**Comment by jmendeza** [comment]
@yacdaniel, @Euquimides please test:
- Upgraded sites from 4.1.x
- Duplicate site feature
- Commits added directly to git repo
- Pull from remote
- More complex operations like moving/renaming large directories or pages with many children.

**Comment by jmendeza** [comment]
@sumerjabri @yacdaniel please notice the last PR updates Studio DB version. That is missing from previous PR.

**Comment by jmendeza** [comment]
I am taking this back to revisit the approach to repository locking

**Comment by jmendeza** [comment]
Added PR to fix issue with write global configuration throwing SiteNotFound

**Comment by sumerjabri** [comment]
@yacdaniel one of the test cases is to:
1. Make edits on disk and commit
2. Make edits through Studio UI
3. Delete the audit table
4. Make edits on disk and commit against the Studio UI edited items
5. See if it imports correctly

**Comment by yacdaniel** [comment]
Verified in `4.2.0-SNAPSHOT`
