### ISSUE TITLE
[studio-ui] Turn ICE Pencil off when enabling Page Components

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#686]
When enabling the Page Components (D&D), turn off the pencils so the GUI looks better.

Upon clicking "Done" to close Page Components, please revert the pencils back to ON if they were on, or keep them OFF if they were off.

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/337

**Comment by sumerjabri** [comment]
The top Pencil remains "lit" / "enabled" when you click on Page Components. You need to turn it off and back on if it was on before.

The pencils themselves are removed, which is correct.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/350
