### ISSUE TITLE
XB drops request parameters on page view

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6872]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

XB seems to 'redirect' on preview and "drops" request parameters in the redirect.

### Steps to reproduce

Steps:

1. Create a site based on Empty blueprint
2. Add the following to markup to the rich text editor `<p> <a href="/foo?param1=x&param2=y&param3=z">a link</a></p>`
3. Optional: Add the following markup to the template 
```
<#list requestParameters?keys as k>
          <li>${k} - ${requestParameters[k]}</li>
</#list>
```
4. Create a new page based on the entry type at /foo
5. Click on the link on the home page
6. Note that you are initially redirected to foo with all of the parameters `http://localhost:8080/foo?param1=x&param2=y&param3=z` and then redirects to `http://localhost:8080/foo?param1=x`
7. Note that you can go directly to the page without studio and no redirect occurs.

### Screenshots and/or videos

https://www.loom.com/share/9a997bd3e58849cc96e44b96caf40ed1

**Comment by rart** [comment]
@sumerjabri @russdanner do you guys know why this isn't in 4.2? 

This was released in 4.1.5 and would be a regression of a _CI_ issue to release 4.2 without it.

**Comment by sumerjabri** [comment]
@rart how risky of a merge is this?

@russdanner let's discuss either in this thread or on a call.

I moved it to 4.2 so we can review it on Monday.

**Comment by rart** [comment]
Low risk.

**Comment by russdanner** [comment]
Confirmed
