### ISSUE TITLE
Update bootstrap-blueprint to support v4

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6882]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CI:5088
The current bootstrap-blueprint is for 3.1.x
https://github.com/craftercms/bootstrap-blueprint

### Describe the solution you'd like

Please add a version to support configuration & Freemarker syntax if any in v4.1

**Comment by sumerjabri** [comment]
Let's not invest in this example repository. Instead, we can use other example repos/blueprints. The repo has been made private to reduce reliance on it.
