### ISSUE TITLE
Fix TypeScript compilation of Guest

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6889]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`getMoveComponentInfo` results in TypeScript errors

### Steps to reproduce

Steps:

1. Run `build:tsc` script on the guest module
2. See the issue

**Comment by rart** [comment]
@jvega190 there are some compilation issues in Guest that seem related to tinymce.

**Comment by sumerjabri** [comment]
@rart when done in all project, close the ticket. I'll close it now.
