### ISSUE TITLE
Update engine 'getItem' API documentation with preview mode behavior for `disabled` items

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6897]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Crafter Engine Get Item API returns 'disabled' items when Crafter Engine is in preview mode to support authoring reviews.

### Describe the solution you'd like

Note this behavior in the API documentation. 

CI: 4952

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/_static/api/engine.html#tag/content/operation/getItem
