### ISSUE TITLE
Please push the v4.1.5 tag in docker-images

### ISSUE THREAD

**Issue by rm--** [craftercms/craftercms#6907]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

hi,

the git tag v4.1.5 in the repository https://github.com/craftercms/docker-images is still missing.

(site note/beware: there is a commit with spring6/tomcat10 upgrades already merged into develop & master. are these changes are not part of v4.1.x?) https://github.com/craftercms/craftercms/issues/5977 got the v4.2.0 milestone.
I mention this just to be sure no invalid tag will be build. ;)

thanks in advance.
René

### Steps to reproduce

Steps:

1. Go to (https://github.com/craftercms/docker-images/tags)

**Comment by sumerjabri** [comment]
We're retiring that repository. To build Docker images, use the main project [craftercms](https://github.com/craftercms/craftercms). For instructions, see the [README](https://github.com/craftercms/craftercms/blob/develop/README.md).

To help you get started, you can try:
```
git clone -b v4.1.5 https://github.com/craftercms/craftercms v4.1.5
cd v4.1.5
./gradlew build deploy bundle buildMainImages
```

Join us on Slack to ask these types of questions. We're at https://craftercms.com/slack

**Comment by sumerjabri** [comment]
@russdanner I'll add a note to the Docker Images repo to communicate the above to help reduce confusion. We must then turn it off once enough time has passed.

**Comment by sumerjabri** [comment]
README updated https://github.com/craftercms/docker-images/blob/develop/README.md
