### ISSUE TITLE
[craftercms] The db folder under data should not contain the actual DB binaries

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#691]
Data directory should contain only data. The binaries and other non data directories of the embedded DB should be outside, under a db directory.

**Comment by cortiz** [comment]
@dejan-brkic is there any Config that I can use to change this behavior ?

**Comment by sumerjabri** [comment]
Dejan to help Carlos get a hold of relevant config. Carlos to implement.

**Comment by dejan-brkic** [comment]
Configuration properties updated:
```
# Base folder for the embedded database
studio.db.basePath: ./dbms
# Data folder for the embedded database
studio.db.dataPath: ./data/db
```

PR: https://github.com/craftercms/studio/pull/635
