### ISSUE TITLE
After a group is created, the Group members section doesn't load up correctly

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6916]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

After a group is created, the Group members section doesn't load up correctly

### Steps to reproduce

Steps:

1. Go to Group management
2. Click on Create Group and create a group
3. Notice 
    - The "_Group members are editable after creation_" text at the bottom section is gone, but group member UI doesn't show up. We should see the same UI that is presented when clicking an existing group from the main grid.
    - The "Save" button (without any changes made) is enabled. Unless there are changes to save, keep disabled.
    - The "Cancel" button works inconsistently with most dialogs. It works as a "Revert unsaved" rather than to dismiss the dialog as most cancel buttons do in the UI. Since it only reverts the description — which is the only editable text field — it isn't that valuable. Remove it.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket I noticed that the changes weren't reflected. Could you please check this out? Thanks!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.6 and v4.2.0. Thank you! Closing this ticket.
