### ISSUE TITLE
Upgrade 4.1.x to query-string@^7.1.3

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6917]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Delivery SDK 4.1.x is already on query-string@^7.1.3 but studio ui is still on ^6.14.1. We should have them synced up to avoid duplicity in client apps using both and to have a consistent SDK _ecosystem._.

### Describe the solution you'd like

Upgrade 4.1.x to query-string ^7.1.3

**Comment by jvega190** [comment]
This doesn't apply to 4.2.0
