### ISSUE TITLE
[studio-ui] Sync From Repo initiated popup should appear as soon as the repo sync is called

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#692]
Right now, the popup that indicates that the Sync From Repo was initiated only appears after the sync is almost finished.

**Comment by sumerjabri** [comment]
I'm not sure how we're going to fix this, but let's discuss. The idea is that: either we show a progress bar/spinner/etc. or it's an async call and you indicate that the job has started. This may require help from Dejan is making the API call return right away and do the work async.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio2-ui/pull/380
https://github.com/craftercms/studio/pull/665
