### ISSUE TITLE
SingleFileUpload component enhancements

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6921]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

- The SingleFileUpload component doesn't display its own errors
- On the form engine, image picker control, the SingleFileUpload errors are easily missed as they are displayed on a snack but the user focus is on the dialog which simply stops progress but remains in the same state.
- 403 bear a really vague message since the write-content API 1 doesn't provide a JSON response

### Describe the solution you'd like

- Update the "uploading file: xyz" message and display an error on the component itself. Ensure a coherent and recoverable state.
- Update usages of the component to consider this new internal error handling. Those that use the error callback simply to display an error can stop sending that prop altogether.
- Configure a role/user with write access only to feature components on the Editorial BP. Try to upload a file on the "Image" field of the Smile feature. Notice how the error is shown on a little snack and the error is quite vague. Given the write-content API limitation, make sure to inspect the status code to display a meaningful message. Try to break the API in other ways to hand 500s and 400s via status code too. This API possibly only responds with JSON on 200 responses.

**Comment by rart** [comment]
@jvega190 add handling for the 403 and  other known codes to show a relevant messages:

400: The server could not understand the request due to invalid syntax or arguments.
401: Unauthorized request. Your session may have timed out.
403: Upload forbidden. Insufficient permissions to upload.

**Comment by jvega190** [comment]
@rart the `getResponseError(responseText, xhr)` that uppy provides returns only a resposeText (that is the HTML error page) and the xhr param is undefined.
