### ISSUE TITLE
[studio] New Component - Feature form too small/cannot be resized when editing from the pencil in the features section

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#693]
It would be nice for the New Component - Feature form to be either resizable or bigger when using the pencil at the top of the features section in the home page of Editorial blue print.

Feature form too small/cannot be resized when editing from the pencil in the features section.
The "New Component - Feature" form is only too small if you edit it from the pencil at the top of the Features section.  Using the D&D or "Edit" from the context menu is okay.

1. On the home page of Website_Editorial, enable the pencils.  Click on the pencil at the top of the Features Section

![1](https://cloud.githubusercontent.com/assets/25483966/24723785/ce8ce802-1a16-11e7-909d-1925e921f5ea.png)

2. Click on "Add" --> "Create New - Features".  Notice the size of the current form.

![2](https://cloud.githubusercontent.com/assets/25483966/24723823/f21baa92-1a16-11e7-8a52-0e63e9edc891.png)

3.  The form for adding the new feature is too small and cannot be resized
![3](https://cloud.githubusercontent.com/assets/25483966/24723845/0a502c50-1a17-11e7-8d76-d7a594bc159a.png)

**Comment by vestrada** [comment]
studio-ui- master - PR:https://github.com/craftercms/studio2-ui/pull/403
