### ISSUE TITLE
PathNavigator ignores exclude list when searching

### ISSUE THREAD

**Issue by iagochaves-encoura** [craftercms/craftercms#6934]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

**Might relates to https://github.com/craftercms/craftercms/issues/6046**

We are using a custom plugin for the Experience Builder sidebar (right sidebar). This plugin utilizes the [PathNavigator component](https://github.com/craftercms/studio-ui/blob/fb8887e0e82b15a7c87d3ceb0f782ae90eb3dda6/ui/app/src/components/PathNavigator/PathNavigator.tsx) and passes a list of paths to exclude. Everything works as expected until we perform a search. 
For example, if we search for a folder that is on the exclusion list, the search results return the folder even though it should be excluded.

Tested on 4.1.5

### Steps to reproduce

Steps:

1. Create a custom plugin for ICE sidebar https://gist.github.com/iagochaves-encoura/324b476bdd529779ce72a4831360e797
2. Create `folder-test` and `folder-ok` under `/components`
3. Verify that initially, the plugin excludes the `folder-test` from the navigation
4. Search for **test**, see that now we can see `folder-test` which we shouldn't
5. Delete the search, and verify that `folder-test` is appearing in the navigation.

### Screenshots and/or videos

1. Components folder
![image](https://github.com/craftercms/craftercms/assets/111374420/f5f2d151-ddc7-4729-ab06-5465212d95f0)

2. Initial state for the ICE sidebar plugin
![image](https://github.com/craftercms/craftercms/assets/111374420/be384201-fe76-40df-9c1f-b12f01b5cf3c)

3. Searching test
![image](https://github.com/craftercms/craftercms/assets/111374420/6fe135d5-0d46-4764-bcc1-82bfd08270ef)

4. Finally, delete the search
![image](https://github.com/craftercms/craftercms/assets/111374420/2618501f-e2fe-4d84-91a4-563dafdd98b7)

**Comment by sumerjabri** [comment]
CC @russdanner

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket I noticed the following:

When setting the option in the UI configuration for excluding o hiding items in the sidebar (https://docs.craftercms.org/en/4.1/reference/modules/studio/configuration/user-interface-configuration.html#sidebar-excludes), a button for `X more items` will show up (depending on the amount of items being excluded). This button will not work when clicking on it. This happens in both 4.1.6 and 4.2

Could you please check this out? Thanks!

![image](https://github.com/craftercms/craftercms/assets/90878288/b2649a90-04d2-4dd6-8501-d8b1475cb17e)

**Comment by jvega190** [comment]
@Euquimides that's already reported [here](https://github.com/craftercms/craftercms/issues/6918)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.6 and v4.2.0. This might be a possible test case for automation, so added in the following ticket as task https://github.com/craftersoftware/craftercms/issues/926. Thank you! Closing this ticket.
