### ISSUE TITLE
Remove deprecated browse CMIS and related data sources

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#6944]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

CMIS APIs have been removed. Browse CMIS and its related data sources are non-functional.

### Describe the solution you'd like

Remove deprecated browse CMIS and related data sources

**Comment by rart** [comment]
@russdanner please note we're removing [these](https://github.com/craftercms/studio-ui/pull/3972/files) for 4.2.
