### ISSUE TITLE
[studio] Update sync from repo to populate activities

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#695]
Add a column to the `cstudio_activity` table called `source`.
Add constants to indicate various sources, we will start with:
- UI
- Repository

UI means the change came from the UI
Repository means the changed happened externally and we detected it in the repo during a sync.

Please update the sync from repo capability to populate the activities tables with what happened.

Please set the source for API calls as `UI` and from the sync process as `Repository`

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/641

Drop database or execute:
alter table cstudio_activity add column source VARCHAR(255) NOT NULL;
