### ISSUE TITLE
Update release 4.1.3 notes to include updates to Crafter Engine marshelling approach for fields with attributes

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6952]
### CI Number

N/A

### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Crafter Engine relies on a library that marshals objects to JSON. This dependency was updated in 4.1.0, and it introduced a change of behavior in Crafter Engine for `getItem` that affected a small subset of content items and fields.

The change was as follows:
If you set an attribute on the field (e.g., `tokenized`) then the library would marshal the field as an object where the attribute was a property of the object and the value was marshaled as a property called text
```
{
   ...
   "productName_s": {
      tokenized": "true",
      "text": "test"
   }
}
```

However, the correct response is as follows:
```
{
   ...
   "productName_s": "test"
}
```

We corrected this issue in 4.1.3, so all string and text fields, with or without attributes, are marshaled in a consistent fashion.

### Describe the solution you'd like

- [ ] Update the 4.1.3 release notes to indicate this: `Fix: Do not marshal single value fields with attributes as objects.` Link to #6526 
- [ ] Update the breaking changes to indicate that as of 4.1.3+ the change described above is in effect. Users of 4.1.0 - 4.1.2 may need to make minor changes to code that consumes Crafter Engine GetItem responses if they have fields that leverage the `tokenized` property.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/release-notes/index.html#craftercms-4-1-3
https://docs.craftercms.org/en/4.1/release-notes/4-1-x-breaking-changes.html#engine
