### ISSUE TITLE
XB does not show up added repeating group item and need a browser refresh

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6954]
### CI Number

5108

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Adding a new item in the repeated group through ICE does not show up on the screen and requires refreshing the page to see the changes

```
<RenderRepeat
          model={model}
          fieldId="bullets_o"
          component={"ul"}
          renderItem={(item: ContentInstance, index: number) => (
            <li>
              <RenderField
                model={model}
                fieldId="bullets_o.text_t" // That way the component knows that the field we are rendering is 'text_t' from 'bullets_o'
                index={index} // We also need to let the component know the index of the field inside the rep group being rendered
                render={() => {
                  return <div>{item.text_t}</div>;
                }}
              />
            </li>
          )}
        />
```

### Steps to reproduce

Steps:

1. Create a new site from the following BP: https://github.com/phuongnq/craftercms-sample-react-repeat-group
2. While the XB is enabled, select the repeating group at the top of the home page
![2024-06-10_09-59](https://github.com/craftercms/craftercms/assets/2996543/29b95de1-f467-4f08-adf6-75516cae0e93)
3. Add a new item for repeating group by clicking the + item
4. Notice that the item is added but it does not show reactively in the preview, which is not an expected behavior
![2024-06-10_09-59_1](https://github.com/craftercms/craftercms/assets/2996543/9360609c-b64e-4f52-95af-eeace4757f32)
5. Refresh the page and notice that the item is added
![2024-06-10_10-00](https://github.com/craftercms/craftercms/assets/2996543/689b0fb4-52a9-419b-879c-cf19a73e633f)

**Comment by phuongnq** [comment]
@rart @jvega190 I still see the same issue. I use the BP from https://github.com/phuongnq/craftercms-sample-react-repeat-group
Please review this screen share: https://www.loom.com/share/705ad2d8658846e0bb72aae0c5a79b6c?sid=8df691cc-00fc-4208-af4d-9251b03b95a6

**Comment by rart** [comment]
@phuongnq to get these updates you'd need to update the packages that are used on the BP. This is likely the reason for the error.

Nevertheless, @jvega190 let's re-validate using Phil's BP. Send a PR to Phil's so he sees the updates and he can also run validation.
Because this isn't published yet, send the `npm pack` zips and yarn add from them.

**Comment by jvega190** [comment]
Hi @phuongnq, I sent a PR to your BP's branch with the npm packages updates (as mentioned in previous comment, packages are not puslished yet). I sent the PR for 4.1.
Here's the link to the PR: https://github.com/phuongnq/craftercms-sample-react-repeat-group/pull/1

Here's a branch on my fork for the 4.2 branch
https://github.com/jvega190/craftercms-sample-react-repeat-group/tree/4.2.0

**Comment by phuongnq** [comment]
Thanks @jvega190 , @rart.
I verified this with new codes.
