### ISSUE TITLE
[studio] Published pages workflow icon appears as scheduled in Author's dashboard

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#696]
[studio]Published pages appears as scheduled in Author's dashboard

1. [Admin]Create a site using Website_Editorial and add a user-author for the newly created site.
2. [Author]Login as an author and edit one of the articles.  
![first](https://cloud.githubusercontent.com/assets/25483966/24760040/72c91da2-1ab5-11e7-8e07-b66082bd0d34.png)

Request Publish that "Items should go Live Now"  after modifying the article.
![second](https://cloud.githubusercontent.com/assets/25483966/24760058/81f3291c-1ab5-11e7-914a-72647870be2d.png)

![third](https://cloud.githubusercontent.com/assets/25483966/24760079/8ea49100-1ab5-11e7-8247-b4cd6f6e4ab0.png)

3. [Admin]Approve and Publish the request from the author.  
![fourth](https://cloud.githubusercontent.com/assets/25483966/24760089/96f3dbc2-1ab5-11e7-923b-49e50d6ade52.png)

Open the dashboard, the article is marked as published.
![fifth](https://cloud.githubusercontent.com/assets/25483966/24760110/a5733c60-1ab5-11e7-9b4b-66d832014441.png)

4.[Author]Open the author's dashboard, notice the published page in the "My Recent Activity" widget  has its workflow icon showing as scheduled.

![sixth](https://cloud.githubusercontent.com/assets/25483966/24760119/ad1d7d18-1ab5-11e7-9db2-5e98199e943f.png)

**Comment by dejan-brkic** [comment]
Done 

PR:
https://github.com/craftercms/studio2-ui/pull/340
https://github.com/craftercms/studio/pull/638
