### ISSUE TITLE
[studio] Change "Edit" button in Edit/Membership form to "Save"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#697]
Please change "Edit" button in Edit/Membership form to "Save".

1. Go to the Admin Console
2. Click on Groups
3. Click on Edit/Membership for one of the groups
![screen shot 2017-04-06 at 2 21 26 pm](https://cloud.githubusercontent.com/assets/25483966/24769562/f435e108-1ad4-11e7-874b-93cd86eb9422.png)

4. Notice the "Edit" button in the Edit/Membership form.  Please change the button text to "Save".
![screen shot 2017-04-06 at 2 17 33 pm](https://cloud.githubusercontent.com/assets/25483966/24769593/089df068-1ad5-11e7-995a-9b0d75684960.png)

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/339
