### ISSUE TITLE
Add note for initializing XB programmatically when having lazy-loaded content on templated projects

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6970]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

In templated projects, typically content is preloaded and pre-rendered on to the view. When the view loads, XB initialises normally. If content is loaded lazily, developers must undergo additional steps to enable XB on top of that content.

This is easily missed by developers thinking the typical initialisation would work despite race conditions.

This may also happen in simple JS applications. Lazy loaded content without a page refresh needs some programmatic management to notify XB about changes.

### Describe the solution you'd like

Add some sort of note and documentation

**Comment by rart** [comment]
See https://github.com/craftercms/craftercms/issues/6983#issuecomment-2239739956

We just need to figure if we publish the example blueprint or just the code and how.

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/common/experience-builder.html#lazy-loaded-content
