### ISSUE TITLE
Allow to build enterprise docker images for each module (again)

### ISSUE THREAD

**Issue by rm--** [craftercms/craftercms#6978]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

hej!
The requirement of our customer is that we are able to build the enterprise images by ourself to have full control about the dependencies. We have a CI job for each module in place that uses the [docker-images repository](https://github.com/craftercms/docker-images/).

The [new project description on develop](https://github.com/craftercms/docker-images/tree/develop?tab=readme-ov-file#craftercms-docker-images) references to use the [craftercms repo](https://github.com/craftercms/craftercms).
But the currrent gradle tasks don't consider to build enterprise docker images.

### Describe the solution you'd like

We would be very happy if the [old gradle tasks(including the distinction between enterprise or not enterprise](https://github.com/craftercms/docker-images/blob/master/build.gradle#L34) were integrated in this repository. 🥹

thanks in advance!

**Comment by sumerjabri** [comment]
@Euquimides please test with:
* Build normally and generate Docker images from the existing bundles (something like: `build deploy bundle buildAuthoringTomcat`
* After the previous build, try to do this: `buildAuthoringTomcat build deploy` (out of order to see if the `project.version` variable manipulation breaks things)
* Build Docker images from a local disk bundle (`.tar.gz` file)
* Build Docker images from a local expanded bundle (a local folder with an unzipped bundle)
* Build Docker images from a remote bundle URL (you can try an older release)

Ping me with any questions or concerns.

**Comment by Euquimides** [comment]
Hi! Updated and checked the implementation of this feature. This was tested for both CE and EE, under the test cases cited for both Authoring and Delivery bundles. Feature has been implemented for v4.1.6, will continue checking the rest of the versions. 

> @Euquimides please test with:
> 
>     * Build normally and generate Docker images from the existing bundles (something like: `build deploy bundle buildAuthoringTomcat`
> 
>     * After the previous build, try to do this: `buildAuthoringTomcat build deploy` (out of order to see if the `project.version` variable manipulation breaks things)
> 
>     * Build Docker images from a local disk bundle (`.tar.gz` file)
> 
>     * Build Docker images from a local expanded bundle (a local folder with an unzipped bundle)
> 
>     * Build Docker images from a remote bundle URL (you can try an older release)
> 
> 
> Ping me with any questions or concerns.
