### ISSUE TITLE
[studio] Disable In-Context Edit Pencil when the user is Reviewer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#698]
1. Log in to Studio as a user - Reviewer
2. Notice the In-Context Edit Pencil and the In-Context Editing in the Preview Tools Panel is still clickable and hides/unhides the pencils in the different sections in the page.  It would be nice if the In-Context Edit Pencil at the top and the In-Context Editing in the Preview Tools Panel is disabled when the user logged in is a Reviewer.
![screen shot 2017-04-06 at 2 28 41 pm](https://cloud.githubusercontent.com/assets/25483966/24769992/6f89664e-1ad6-11e7-9002-13195aa69b06.png)

**Comment by sumerjabri** [comment]
Let me know if this is too hard to tackle at this time.

**Comment by vestrada** [comment]
@sumerjabri as we talked: I checked the services and the code. It is possible to know if the user is member of "reviewer" (Good).
But we can't check group permissions. If the user create new group with only read permission, we will get the same issue.

On Hold.

**Comment by sumerjabri** [comment]
@vestrada Please go ahead and build it to work with the reviewer role member as you indicated and we'll figure out the rest in v4.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/379

@sumerjabri: I removed the buttons instead of disable them. Let me know if it is ok?

Thanks, Vero
