### ISSUE TITLE
Socket configuration event listener throws due to incorrect data structure traversing

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#6982]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When the socket dispatches a set of events, with one of them being a configuration event, a listener throws since it reads the data structure incorrectly

Related [6478](https://github.com/craftercms/craftercms/issues/6478)

### Steps to reproduce

Steps:

1. Go to Project tools > Content types
2. Open a content type and save it
3. See error on the browser console

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.2.0. Thank you! Closing this ticket.
