### ISSUE TITLE
headerMappings configuration does not work as expected in delivery

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [x] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Configured <headerMappings> to control cache header but it does not work as expectation. From my example, I set <urlPattern> to /style but it also affect to when I request to the /entertainment path (I checked on v4.1.2 and v4.1.4).

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Configure engine site-config.xml to have:
```
<site>
    <version>4.0.1</version>
    <headerMappings>
        <mapping>
            <urlPattern>/style</urlPattern>
            <headers>
                <header>
                    <name>Cache-Control</name>
                    <value>max-age=60\, s-maxage=300</value>
                </header>
                <header>
                    <name>X-Crafter-Content</name>
                    <value>test</value>
                </header>
            </headers>
        </mapping>
    </headerMappings>
</site>
```
3. Publish the site to delivery
4. In delivery, verify that accessing `/style` produces the correct headers
5. In delivery, access `/entertainment` and notice that it also produces the same headers which is not expected

### Screenshots and/or videos

![image](https://github.com/craftercms/craftercms/assets/2996543/147725d6-a3d2-4139-b0d6-b2d2bc526a9a)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
