### ISSUE TITLE
[deployer] Build APIs: monitor

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#699]
Please build the monitor API calls:
- Build the core functionality in `commons`
- Implement the APIs in `deployer` as specified here:
-- http://docs.craftercms.org/en/latest/developers/projects/deployer/api/monitor/version.html
-- http://docs.craftercms.org/en/latest/developers/projects/deployer/api/monitor/status.html
-- http://docs.craftercms.org/en/latest/developers/projects/deployer/api/monitor/memory.html

**Comment by cortiz** [comment]
PR https://github.com/craftercms/deployer/pull/28
and PR https://github.com/craftercms/commons/pull/91
