### ISSUE TITLE
Correct the documentation to initilize XB manually with JavaScript

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6996]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

We should update the doc here for the case manually add the XB with JavaScript apps: https://docs.craftercms.org/en/4.1/by-role/developer/common/experience-builder.html#angular-vue-and-other-js-applications
Here is the current code to manually add the XB:
```
import { fetchIsAuthoring, initExperienceBuilder } from '@craftercms/experience-builder';

// Check if we're in authoring
fetchIsAuthoring().then((isAuthoring) => {
   // If we're in authoring, initialize XB
   if (isAuthoring) {
      initExperienceBuilder()
   }
})
```

But we need an object parameter for the initExperienceBuilder function with the following keys/values:

```
initExperienceBuilder({ isAuthoring, path, modelId });
```

`modelId` seems to be an optional key/value.

### Steps to reproduce

Steps:

2. Click on '...'
3. Scroll down to '...'
4. See the issue

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/common/experience-builder.html#angular-vue-and-other-js-applications
