### ISSUE TITLE
[search] CRAFTERCMS-1309: Add ability to rank Crafter site search results by social rating

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7]
Original JIRA Fix Versions:
2.6.0, Original JIRA Components:
Search, Social, 
----------
Original JIRA Description: :
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1309
----------

**Comment by sumerjabri** [comment]
I'm sure this is not 2.5.4, but not sure what version it needs to be. Let's chat.
