### ISSUE TITLE
[studio-ui] Items in wrong workflow state

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#700]
Create a site
Upload a tree of files/folders into static-assets
You'll note items in scheduled state in my recent activities

If this is a UI issue, please change the title to [studio-ui] and route to Jose.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio2-ui/pull/340
https://github.com/craftercms/studio/pull/638
