### ISSUE TITLE
Setting an incorrect value in time field controls shows a notification that blocks the form

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#7000]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When setting a value in any of the time field controls (date-time or time), if the value is not a valid time, a notification will show up saying that the value is not valid, but after dismissing the notification, the form stays in a locked state.

### Steps to reproduce

Steps:

1. In any site's content type, add a Date-Time or Time field.
2. Save the content type
5. Open the form and enter an incorrect value in the recently added field (e.g. 'asd')
6. Note that a notification shows up, and after clicking 'OK' the dialog is dismissed but the form stays locked.

### Screenshots and/or videos

![Screenshot from 2024-07-02 10-49-56](https://github.com/craftercms/craftercms/assets/18267471/009afff2-e16f-450a-8465-972cbc95c530)
![Screenshot from 2024-07-02 10-50-07](https://github.com/craftercms/craftercms/assets/18267471/ebe17157-d493-4faf-85a4-ee29802bc281)
![Screenshot from 2024-07-02 10-50-17](https://github.com/craftercms/craftercms/assets/18267471/a1f917cd-5814-4e2c-bbf3-75b605dbc146)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for Crafter v4.1.6 and v4.2.0. Thank you! Closing this ticket.
