### ISSUE TITLE
Improve cluster info UI docs

### ISSUE THREAD

**Issue by rm--** [craftercms/craftercms#7004]
### Latest version

- [ ] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The docs contain a screenshot showing the cluster UI. https://docs.craftercms.org/en/4.1/by-role/system-admin/performance-and-scaling/clustering.html#changing-the-cluster-git-url

In this UI there are states of the cluster described with:

Sync Status
- _Initial repo sync_: **Not Completed**
- _Event handler setup_: **Completed**

DB Replication Threads
- _IO_: **Running**
- _SQL_: **Not running**

During working with a cluster for me it is not clear what does it really really mean.

For example I know about the IO/SQL thread in the MySQL cluster setup. But what are the desired state and how to reach it. To make it clear: should the primary and replica both have all sync status **Completed** or is it fine if _Initial repo sync_ is **Not Completed** ? I don't know.

Or what to do I something not in this desired state?

### Describe the solution you'd like

1) All aspects like:
- Sync Status
- DB Replication Threads
- Initial repo sync
- Event handler setup
"should" be defined.

2) All desired states like:
- Not Completed
- Completed
- Not running
- Running
should have a reference to the functionality that serves that state with its separate meaning in primary/replica.

3) Very cool would be a integration/combination with https://docs.craftercms.org/en/4.1/by-role/system-admin/performance-and-scaling/clustering.html#troubleshooting to help users to have a healthy CrafterCMS cluster .

thank you!

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/system-admin/performance-and-scaling/clustering.html#clustering-cluster-tool

**Comment by rm--** [comment]
thanks.
