### ISSUE TITLE
Timing issue with Guest check in when switching projects

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7009]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

An exception occurs when the guest hasn't checked in and the allowed content types are reported back to Host

### Steps to reproduce

Steps:

1. Create 2 Editorial projects
2. Once they're both ready go to site 1
3. Use site switcher on the preview toolbar to go to site 2
4. Notice error printed on the browser console. If error didn't occur on first try, repeat until you see the error.

**Comment by Euquimides** [comment]
Hi! Update and rechecked this issue. Fix verified. Thank you! Closing this ticket.
