### ISSUE TITLE
[studio] studio.security.forgotPassword.message.text property should be relative to Studio

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#701]
Please change the forgot password link URL in Studio's configuration to be relative and derive the domain automatically.

We may need to change the API so the caller (UI) sends the desired domain. Let me (Sumer) know if we need to update the API.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio2-ui/pull/353
https://github.com/craftercms/studio/pull/642

**Comment by sumerjabri** [comment]
@avasquez614 please validate and close/move to `completed`.

**Comment by avasquez614** [comment]
Tested, working as expected.
