### ISSUE TITLE
Custom contentWrite via content type controller does not trigger reindex on preview

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#7010]
### CI Number

5183

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Custom contentWrite via content type controller does not trigger reindex on the preview

### Steps to reproduce

Steps:

1. Create a new site from Editorial BP
2. In the Home content type controller, add the following:
```
import scripts.libs.CommonLifecycleApi;
import scripts.api.*
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.dom4j.Document;
import org.dom4j.Element;
import org.craftercms.studio.impl.v1.util.*

import java.text.SimpleDateFormat
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

def contentLifecycleParams =[:]
contentLifecycleParams.site = site
contentLifecycleParams.path = path
contentLifecycleParams.user = user
contentLifecycleParams.contentType = contentType
contentLifecycleParams.contentLifecycleOperation = contentLifecycleOperation
contentLifecycleParams.contentLoader = contentLoader
contentLifecycleParams.applicationContext = applicationContext

Document document = contentLoader.getContent(site,path)
Element ele = document.selectSingleNode("/page/title_t")
ele.setText("Updated title")

def documentStream = ContentUtils.convertDocumentToStream(document, "UTF-8")
def contentService = applicationContext.getBean("cstudioContentService")
contentService.writeContent(site, path, documentStream)


def controller = new CommonLifecycleApi(contentLifecycleParams)
controller.execute()
```

This code means to update the `title_t` to `Updated title` on save.
3. Open the Home page form and edit anything then save
4. Notice that while the content on disk is updated correctly, the value `title_t` in search does not updated to `Updated title`

**Comment by phuongnq** [comment]
A workaround it to manually trigger the ContentEvent after write:
```
contentService.writeContent(site, path, documentStream)
contentService.notifyContentEvent(site, path)
```

**Comment by phuongnq** [comment]
@sumerjabri The method `boolean writeContent(String site, String path, InputStream content) throws ServiceLayerException;` is designed to use internally. We don't send to ContentEvent in this method on purpose in order to not having duplicated ContentEvent while writing content.

I created a new interface that we can use in the Groovy script independently:
```
boolean writeContentAndNotify(String site, String path, InputStream content) throws ServiceLayerException;
```

This method writes content from an input stream and notifies the subscribers (including the preview indexing) about the ContentEvent.

If we are ok with this solution, we should document this somewhere.

**Comment by russdanner** [comment]
This method still results in 2 versions being created per save. Can this be corrected?

**Comment by phuongnq** [comment]
@sumerjabri @russdanner The issue with double commits is that we are using `writeContent` in the controller separately. And the controller script is run after the content is written in the processors' chain. 

To have only a single commit, we may need to design the pre-hook while writing content and trigger it to modify the stream before saving it to disk.

Will a design like this work?

1. In the controller, create a hook function such as `writeContentPreHook` and perform the necessary update:

```
InputStream writeContentPreHook(InputStream inputStream, XmlContentLoader contentLoader);
```

2. Before the content is processed, we call this hook function (if it exists) and return the new stream
3. The processors' chain then uses the new stream to write content

This will make sure there is only one commit per update.

A sample code looks like this:

```
import scripts.libs.CommonLifecycleApi
import scripts.api.*
import org.dom4j.Document
import org.dom4j.Element
import org.craftercms.studio.impl.v1.util.*

def contentLifecycleParams =[:]
contentLifecycleParams.site = site
contentLifecycleParams.path = path
contentLifecycleParams.user = user
contentLifecycleParams.contentType = contentType
contentLifecycleParams.contentLifecycleOperation = contentLifecycleOperation
contentLifecycleParams.contentLoader = contentLoader
contentLifecycleParams.applicationContext = applicationContext

def writeContentPreHook(inputStream, contentLoader) {
    Document document = contentLoader.getContent(inputStream)
    Element ele = document.selectSingleNode("/page/title_t")
    ele.setText("Updated title")
    
    return ContentUtils.convertDocumentToStream(document, "UTF-8")
}

def controller = new CommonLifecycleApi(contentLifecycleParams)
controller.execute()
```
I created a draft PR to discuss this: https://github.com/craftercms/studio/pull/3585.
Please note that in 2, we load the Groovy with a classloader and check if the function `writeContentPreHook` exists to invoke just that specific method. The controller itself is triggered as usual in the processors' chain.

**Comment by sumerjabri** [comment]
@russdanner please create a new ticket for the double commit for us to fix. That may get fixed differently as we evolve the API.

**Comment by sumerjabri** [comment]
@phuongnq we can discuss the design and approach in the new ticket. You may leave the PR open for now.

**Comment by russdanner** [comment]
Hi all, 
I opened a separate ticket for the "double-commits" issue.

I just noticed another defect related to the write behavior: If you edit via XB, any fields that are dynamically updated by the script are not shown in XB (see video.) 

While I know this is not directly related to the deployer/indexing, I am bringing it up here because it's likely event-related:
https://www.loom.com/share/1a54cc2e06a443048c11cbe115d9c1b9

**Comment by phuongnq** [comment]
@russdanner This could be an XB issue/behavior. If I update the controller to update the `internal-name`, I can see it right away in the sidebar without refreshing. This means the event is sent correctly. 

https://www.loom.com/share/949fccf044524c2aa8daf8502e04978a?sid=bda8f50f-11c0-44e2-b107-e9eda2fe0d7e

```
import scripts.libs.CommonLifecycleApi

import org.dom4j.Document;
import org.dom4j.Element;

import org.craftercms.studio.impl.v1.util.*



def contentLifecycleParams =[:]
contentLifecycleParams.site = site
contentLifecycleParams.path = path
contentLifecycleParams.user = user
contentLifecycleParams.contentType = contentType
contentLifecycleParams.contentLifecycleOperation = contentLifecycleOperation
contentLifecycleParams.contentLoader = contentLoader
contentLifecycleParams.applicationContext = applicationContext

def controller = new CommonLifecycleApi(contentLifecycleParams)
controller.execute()


Document document = contentLoader.getContent(site,path)
Element ele = document.selectSingleNode("/page/internal-name")
ele.setText("Updated Text"+new Date())

def documentStream = ContentUtils.convertDocumentToStream(document, "UTF-8")
def contentService = applicationContext.getBean("cstudioContentService")


contentService.writeContentAndNotify(site, path, documentStream)
```

Another test I have performed is that: I open two Chrome tabs with the same Home page. I edited in one tab but could not see the content update in the second tab (while other information such as the icon changed to the pencil updated in the second tab without refreshing the page). This makes me think that the preview does not update at all on ContentEvent.
https://www.loom.com/share/da29e14a02214d1b99d659e3636e7f0a?sid=004d7dfb-835e-43bd-92c6-c5218a7e4183

**Comment by sumerjabri** [comment]
@russdanner, perhaps one more ticket for the XB issue to pursue that case. Please prioritize the ticket into the release(s) required.

**Comment by russdanner** [comment]
Confirmed in 4.1.6 and 4.2.0
