### ISSUE TITLE
libncurses.so.5 is required by MariaDB4j but only libncurses6 is available in Ubuntu 24.04 repos.

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#7016]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In a server running Ubuntun 24.04 the library libncurses.so.5 is no longer available, only version 6.  MariaDB4j seems to require only version 5. 

### Steps to reproduce

Steps:

1. Create a VM from Ubuntu 24.04
2. Build craftercms project.
3. Start up Studio
4. See the issue

### Relevant log output

```shell
libncurses.so.5: cannot  open shared object file: No such file or directory
```

**Comment by sumerjabri** [comment]
Use CrafterCMS 4.2.x

**Comment by yacdaniel** [comment]
Same issue with RedHat (8,9) https://access.redhat.com/solutions/6907421

**Comment by phuongnq** [comment]
The workaround is to symlink the current library version:
```
cd /lib/x86_64-linux-gnu/
ln -s libncurses.so.6.4 libncurses.so.5
ln -s libtinfo.so.6.4 libtinfo.so.5
```

**Comment by sumerjabri** [comment]
@phuongnq, that symlink may have unintended consequences. Imagine other software that relies on `libncurses 6`; that symlink will break that software.

Other options:
1. Upgrade MariaDB? Is there no upgrade path?
2. Compile with `.so` hard linked
3. Have a copy of `libncurses 5` in a different path and use `LD_LIBRARY_PATH` to point the OS to that path

**Comment by phuongnq** [comment]
@sumerjabri 

The error `error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory` happens when we use `mariadb` client. This could happen on other Linux machines, not limit to Ubuntu 24.04.

1. Upgrade MariaDB: 

MariaDB has a new version 11.4.2, but the same issue occurred with this version.
This can be easily checked by downloading the binaries from https://mariadb.org/download/?t=mariadb&p=mariadb&r=11.4.2&os=Linux&cpu=x86_64&pkg=tar_gz&i=systemd&mirror=knownhost  and run `./bin/mariadb --version`. It would throw the same error.

So there is not an upgrade path for now for Linux in general.

2. and 3:

For Ubuntu, there is a manual way to install the libraries, which should be cover 2,3. A specific version or architecture can be found here: http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/.

A sample command that works with amd64:

```
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb

wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && sudo dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb

sudo apt install libncurses5 libncurses5-dev -y
```
After this, the `mariadb` client should work:

```
phil@phil-VirtualBox:~/craftercms/develop/craftercms/crafter-authoring/bin/dbms/bin$ ./mariadb --version
./mariadb from 11.3.2-MariaDB, client 15.2 for linux-systemd (x86_64) using readline 5.1
```

At this point, I would like to mention that the symlink solution is also quite valid since both ncurses5 or ncurses6 have the same version of 6.4:

```
phil@phil-VirtualBox:~$ dpkg -s libncurses5 | grep Version
Version: 6.4-2
phil@phil-VirtualBox:~$ dpkg -s libncurses6 | grep Version
Version: 6.4+20240113-1ubuntu2
```

**Comment by phuongnq** [comment]
For RHEL8 and RHEL9:
> The solution to this issue is to install the package ncurses-compat-libs which is available for RHEL8 and RHEL9 in the EPEL repository and provides the ncurses.so.5 library:

https://jira.mariadb.org/browse/MDEV-34562

**Comment by sumerjabri** [comment]
I'm not sure about being compatible on a binary level, and therefore I'm against the symlink path. See the release notes:

> Release Notes
> These notes are for ncurses 6.5, released April 27, 2024.
> 
> This release is designed to be source-compatible with ncurses 5.0 through 6.4; providing extensions to the application binary interface (ABI). Although the source can still be configured to support the ncurses 5 ABI, the reason for the release is to reflect improvements to the ncurses 6 ABI and the supporting utility programs.
> 
> There are, of course, numerous other improvements, listed in this announcement.
> 
> The most [important bug-fixes/improvements](https://invisible-island.net/ncurses/announce.html#h3-bug-fixes) dealt with robustness issues. The release notes also mention some other bug-fixes, but are focused on new features and improvements to existing features since ncurses 6.4 release.
> 

Source: https://invisible-island.net/ncurses/announce.html

The other paths of installing the library are fine and seem to be the best path moving forward until MariaDB fixes things.

**Comment by sumerjabri** [comment]
@alhambrav please document the following:
* `libncurses.so.5` is required by CrafterCMS due to the embedded MariaDB, and there is no other way at this time
* How to install that library on Ubuntu and RHEL (see the options above)

We already have `libncurses.so.5` as a hard requirement, this is merely to emphasize and help point people to how to install on new distros that don't have this library easily available.

**Comment by sumerjabri** [comment]
I'm assigning the ticket to @alhambrav while we wait for the release to merge the docs PR.

**Comment by sumerjabri** [comment]
The instructions no longer work:
```
$ wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb \
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && sudo dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb \
sudo apt install lib32ncurses5-dev libncurses5 libncurses5-dev -y

--2024-11-28 16:01:47--  http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 185.125.190.81, 91.189.91.82, 185.125.190.82, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|185.125.190.81|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-28 16:01:48 ERROR 404: Not Found.

--2024-11-28 16:01:48--  http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 185.125.190.82, 185.125.190.81, 91.189.91.81, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|185.125.190.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-28 16:01:48 ERROR 404: Not Found.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libncurses-dev' instead of 'libncurses5-dev'
E: Unable to locate package lib32ncurses5-dev
E: Unable to locate package libncurses5
```

**Comment by sumerjabri** [comment]
These seem to work, but feels unstable:

```
wget https://ftp.debian.org/debian/pool/main/n/ncurses/libtinfo5_6.4-4_amd64.deb && sudo dpkg -i libtinfo5_6.4-4_amd64.deb && rm -f libtinfo5_6.4-4_amd64.deb
wget https://ftp.debian.org/debian/pool/main/n/ncurses/libncurses5_6.4-4_amd64.deb && sudo dpkg -i libncurses5_6.4-4_amd64.deb && rm -f libncurses5_6.4-4_amd64.deb
```

The installs seem to fail.

**Comment by phuongnq** [comment]
This seems to be a stable solution to install the library in Ubuntu 24.04:
```
echo "deb http://security.ubuntu.com/ubuntu focal-security main universe" > /etc/apt/sources.list.d/ubuntu-focal-sources.list
sudo apt update
sudo apt install libncurses5
```

If the file `ubuntu-focal-sources.list` does not exist, please create it.
This will bring the 22.04 APT repository to 24.04 and we can install `libncurses5` within the system.

Source: https://askubuntu.com/questions/1531398/how-to-install-libncurses-so-5-for-ubuntu-24-04

**Comment by sumerjabri** [comment]
Updated AMI build tools.
