### ISSUE TITLE
Search feature issues on PathNavTree

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7017]
### CI Number

n/a

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Several issues present on search feature. See below.

### Steps to reproduce

Steps:

- Create an editorial site
- Issue 1:
  - Create a page called "Child" under Health page
  - Use the "Health" search feature and type "asdf" (something that doesn't match the child)
  - Notice how Loading state remains
- Issue 2:
  - Under articles, search for "asdf"
  - Notice the "...2 more items"
- Issue 3:
  - Under articles, search for "21"
  - Notice the "...1 more item" **and** the level descriptor, which doesn't match the query also shows

**Comment by jvega190** [comment]
About issue 3, bullet 2. The `children` API returns the level descriptor when filtering (e.g by keyword) even though it doesn't match the filter. Per conversation for now the filters will apply to the level descriptor too.

**Comment by jmendeza** [comment]
Updated children by path API so keyword filtering also applies to level descriptor

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
