### ISSUE TITLE
Item selector does not enforce its maximum count limit

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7018]
### CI Number

5196

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When the maximum count limit is set on the item selector, and the user exceeds it, they receive a warning, but the system allows them to continue and add additional items.

Users should not be able to exceed this limit.

### Steps to reproduce

Steps:

1. On any content type with an item selector, set a maximum limit.
2. Populate the item selector to the limit
3. Then add one additional item
4. See the issue

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/31ea925e-852f-4c60-9d32-9fb50aca177a)

**Comment by russdanner** [comment]
The system doesn't seem to be checking the max condition properly. 
https://www.loom.com/share/8fafa1221f2e4e6695fba1d32bf551e0

**Comment by Euquimides** [comment]
Hi @russdanner and @jvega190 ! While validating this ticket I am noticing that we aren't checking if the min value < max value in the item selector component, which confuses the form engine, adding a requirement that can't be fulfilled. We should have some way to check if the min value is less than the max value before saving the content type. 

https://github.com/user-attachments/assets/af038742-43ed-40fa-858b-4539c7516a62

Could you please check this out? Thanks!

**Comment by Euquimides** [comment]
Hi! Fix verified for v4.1.6. Thank you!

**Comment by Euquimides** [comment]
Hi! Fix verified for v4.2.0. Thank you! Closing this ticket.
