### ISSUE TITLE
[search] Log levels in Search are too high

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#702]
Please go through the logs in Search and tone down to more realistic/meaningful levels.

For example: [ERROR] 2017-04-07 18:43:48,392 [ajp-nio-8009-exec-7] [search.SearchServiceImpl] | Creating search index for site:123

Many logs with regard to insertion/deletion of elements are at INFO when perhaps they should be Debug.

Ping me to discuss details or adjust.

**Comment by avasquez614** [comment]
PR craftercms/search#76
