### ISSUE TITLE
`Add` and `Browse Components` sidebars should be sorted alphabeticaly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7020]
### CI Number

5195

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The add and browse components panels on the right side used to be sorted alphabetically but isn't sorted in this fashion any more.

### Steps to reproduce

Steps:

1. Open browse or add components panel in editorial
2. See issue

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/f6c03f29-c7c9-47ce-b294-cb5f0b542a15)

**Comment by russdanner** [comment]
![image](https://github.com/user-attachments/assets/4b1cdfe6-f8f7-4961-9505-cf046943b70c)
This appears to be corrected in 4.2.x (in addition to other improvements.)

**Comment by sumerjabri** [comment]
If it's not an issue in 4.2, then let's not add it to that project. Removing from the 4.2 project queue.

**Comment by rart** [comment]
In develop (4.2), this was addressed during [#5543](https://github.com/craftercms/craftercms/issues/5543)

**Comment by jvega190** [comment]
@sumerjabri @rart actually the sort in 4.2 is in the Add Components Panel, but not on the Browse. I created a PR for 4.2 and left it as draft. Please let me know if we want this in 4.2 too.

**Comment by russdanner** [comment]
Confirmed in 4.1.6

**Comment by russdanner** [comment]
Confirmed in 4.2.0
