### ISSUE TITLE
Uploading an image or file with invalid filename using `Image Uploaded to S3 Repository` or `File Uploaded to S3 Repository` datasources a window will show up that can't be closed or cancelled

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7032]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When uploading an image or file with a filename invalid by the current validator by using `Image Uploaded to S3 Repository` or `File Uploaded to S3 Repository` data sources, a window will show up that can't be closed or cancelled.

This only happens in the current `develop` branch or v4.2. 

### Steps to reproduce

Steps:

1. Create a new project.
2. Configure the AWS Profile for S3 buckets.
3. Go to `Content Types` and add a `Image Uploaded to S3 Repository` or `File Uploaded to S3 Repository` data source, and assign it to a controller either `Item Selector` or `Image Picker`. 
4. Try to upload an image with a name such as `image(1).png` which will be rejected by the validator of the upload API.
5. See the issue: a window will show up that cant be closed, only the option to refresh is active. 

### Relevant log output

```shell
[ERROR] 2024-07-16T13:20:23,632 [http-nio-8080-exec-3] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/aws/s3/upload.json?&_csrf=c86c1886-2c98-4640-8054-af07fbfc4c55?path=awscraftercms%2Fs3%2Ffile&site=a1' failed with response 'ApiResponse{code=1001, message='Invalid parameter(s)', remedialAction='Check API and make sure you're sending the correct parameters', documentationUrl=''}' 
org.craftercms.commons.validation.ValidationException: Validation failed for 'filename'; validation errors: {filename=validation.error.esapi.CONTENT_PATH_WRITE}
```

### Screenshots and/or videos

https://github.com/user-attachments/assets/cabdd9df-42e3-4c45-a6c6-03b438340eae

![Screenshot from 2024-07-16 13-21-54](https://github.com/user-attachments/assets/25e33cc2-b172-4069-b5d7-7f854964c47e)

**Comment by jvega190** [comment]
@sumerjabri @jmendeza there's a detail when the validator suggests a filename with the s3 upload.
For example, if the file being uploaded is `file (1).jpg`, the validator suggests `file--1-.jpg`. If you accept the filename, the upload fails with this error 

`[ERROR] 2024-07-18T10:31:58,704 [http-nio-8080-exec-2] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/aws/s3/upload.json?&_csrf={TOKEN}?path=%2Fimages&site=7032' failed with response 'ApiResponse{code=1001, message='Invalid parameter(s)', remedialAction='Check API and make sure you're sending the correct parameters', documentationUrl=''}' 
org.craftercms.commons.validation.ValidationException: Validation failed for 'filename'; validation errors: {filename=validation.error.esapi.CONTENT_PATH_WRITE}`

full log in [here](https://gist.github.com/jvega190/5d95fab971625efd4f41cc7c4a14e3ad)

Edit: I'll create a ticket for that, and link it here

**Comment by jvega190** [comment]
https://github.com/craftercms/craftercms/issues/7045

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
