### ISSUE TITLE
Upgrade to the latest MariaDB and MariaDB4j

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7044]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Keep MariaDB up to date

### Describe the solution you'd like

Upgrade to the latest MariaDB.

**Comment by phuongnq** [comment]
@alhambrav as discussed, please build new binaries for MacOS using manual `BUILD_MARIADB_OSX.md`.
Please send me the new binaries & any modified files to update the PR.

FYI, in 11.4.3 it seems MariaDB fixed the issue https://jira.mariadb.org/browse/MDEV-33581 so I have removed the logic to copy files fil0fil.cc and xtrabackup.cc . The file mysql.cc, I modified and added it to mysql-11.4.3.cc. You can confirm the diff from this commit: [https://github.com/craftercms/mariadb4j/pull/361/commits/a545efde387d2286eed25dd34bf6c30b7110e151#diff-9b7bd8714f2eb2cf8b[…]846b69d92397a0641fc506c9](https://github.com/craftercms/mariadb4j/pull/361/commits/a545efde387d2286eed25dd34bf6c30b7110e151#diff-9b7bd8714f2eb2cf8b54aa51596f68a649334f7e846b69d92397a0641fc506c9)
Let me know if you encounter any issues while building this!

**Comment by yacdaniel** [comment]
Verified!
