### ISSUE TITLE
[studio-ui] Change admin password, lose site listing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#705]
Login as admin
change the password
note that site listing doesn't have 'create site' anymore, as if the user is now logged out

If the user is indeed logged out, we need to let them know we're logging them out and ask them to login again using the new password.

Ping me if you need help.

**Comment by sumerjabri** [comment]
Please add the language: "Once your password has been successfully updated, you'll be required to login again." to the change password dialog/screen.

Once the user changes their password, please send them to the login screen.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/363
