### ISSUE TITLE
The `Art Showcase` BP is broken in v4.2

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7055]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `Art Showcase` BP is broken in v4.2, the video of the header doesn't load and also some image links are broken. 

### Steps to reproduce

Steps:

1. Create a new project using the `Art Showcase` BP.
2. See the issue: the header video doesn't load and also there are image links broken

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/2c8b3e98-2fa2-4d45-9ef7-6418ee62acd8)

![image](https://github.com/user-attachments/assets/d85e0ede-bb22-44f3-ab29-f300b3621a74)

![image](https://github.com/user-attachments/assets/ac5b36eb-ed77-4b05-a519-e802f14e5806)

**Comment by rart** [comment]
The issue is assets have names with spaces ( #7068 ).

@jvega190 please fix asset names on the BP and increment version.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. The BP is now loading correctly in 4.2. Fix verified! Thank you! Closing this ticket.
