### ISSUE TITLE
Expected components in `Create Content` Right Rail menu do not show

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7065]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Expected components in the `Create Content` Right Rail menu do not show.

### Steps to reproduce

Steps:

1. In the Fitness Blueprint, turn on editing mode and open the Create Content tool on the Right Rail
2. Note that expected components Overview, Newsletter, and others do not show up as available
3. In the Wordify blueprint, go to a blog page, turn on edit mode, and open the Create Content tool
4. Note that RTE and Responsive columns are not available
,

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/b0f7b784-e025-4c47-89d5-a7c5755ebfec)

**Comment by Euquimides** [comment]
Hi! Fix verified for `v4.2.0`. Thank you! Closing this ticket.
