### ISSUE TITLE
Access Denied in preview when multiple tabs to different sites are open

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7066]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

It's possible to get the XB preview to give the user an Access denied screen when multiple tabs to different sites are open in the same browser.

### Steps to reproduce

Steps:

1. Open a browser and go to an Editorial BP site within Studio
2. Open a second tab and go to the project screen
3. Enter a Fitness BP website
4. See the permission issue on the Fitness BP website
5. Note that the other tab, with Editorial BP shows the right message

It seems that Engine is handling the Fitness error and not Studio UI.

#### Editorial (right message)
![Image](https://github.com/user-attachments/assets/c0672c0e-af9a-41ea-84c9-6b54b664e33f)
#### Fitness (wrong message)
![Image](https://github.com/user-attachments/assets/9a9e84c6-67fc-44e4-b605-399a65137a9f)

#### Video of the whole process
https://www.loom.com/share/269549346c344787bbe84a15eb21863c?sid=9b992fe3-a160-4b8f-af16-85cfb8ea6132

**Comment by Euquimides** [comment]
Hi @jvega190 ! While verifying this ticket I noticed that there's another case where the `Access Denied` in preview appears. The steps to reproduce it are the following:

1. Have a tab opened in preview of any project.
2. Open a new tab to `Projects` in Global Menu
3. Create a new project based on any BP.
4. See the issue: `Access Denied` will appear after project creation. 

https://github.com/user-attachments/assets/103f153a-e1b3-494d-b750-8997ab8cc634

Could you check this out? Thanks!

**Comment by sumerjabri** [comment]
@Euquimides, I think your new finding overlaps with https://github.com/craftersoftware/craftercms/issues/991, which has been resolved. I'm assigning this back to you.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
