### ISSUE TITLE
Requests to assets with spaces in their names return 404

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7068]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If an asset has a space in its name. e.g.: `White and Black Vanity Table Near Wll.jpeg`, requests to it will return 404.

### Steps to reproduce

Steps:

1. Create a new site using `Art Showcase` blueprint from the public marketplace
2. Go to site preview
3. Notice the broken images
4. Open dev tools Network tab.
5. Notice how the paths containing spaces fail with 404.
![Screenshot from 2024-07-22 13-48-07](https://github.com/user-attachments/assets/46de2ffc-7d67-4cee-adc0-cea33ff247f3)

**Comment by jmendeza** [comment]
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/handler/AbstractHandlerMapping.html#setPatternParser(org.springframework.web.util.pattern.PathPatternParser)

> By default, as of 6.0, this is set to a [PathPatternParser](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/pattern/PathPatternParser.html) instance with default settings and therefore use of parsed patterns is enabled. Set this to null to switch to String path matching via [AntPathMatcher](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html) instead.

Setting `patternParser` to null for bean `crafter.mainHandlerMapping` should make it behave the same as previous version

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
