### ISSUE TITLE
Pressing the `?` key in the preview no longer shows the dialog of keyboard shortcuts

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7069]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Pressing the `?` key in the preview no longer shows the dialog of keyboard shortcuts

### Steps to reproduce

Steps:

1. Go to any preview an press '?'

**Comment by Euquimides** [comment]
Hi! Updated ante rechecked this issue. Fix verified. Thank you! Closing this ticket.
