### ISSUE TITLE
Publishing Dialog thows `includes error` related to `permitted roles` after certain actions

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7071]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Publishing Dialog thows `includes error` related to `permitted roles` after certain actions

### Steps to reproduce

Steps:

1. Go to the fitness site
2. Open project tools
3. Create a simple graphql query (see below) 
4. Execute the query
5. Click on publishing in the menu to the left
6. See the error
7. Click on the cloud icon in the upper right corner
8. See the same error

```
query MyQuery {
  component_component__header {
    items {
      companyName: gymName_t
    }
  }
}
```

### Screenshots and/or videos

https://www.loom.com/share/7408759e75984617a89767b24d2e21c1

**Comment by russdanner** [comment]
This is difficult to reproduce, which suggests some other factors like timing are involved.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
