### ISSUE TITLE
Pages folder opens and immediately closes when the only child is the level descriptor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7072]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Pages folder opens and immediately closes when the only child is the level descriptor.

### Steps to reproduce

Steps:
1. Create a new fitness site
2. Open the left side bar
3. click on pages
4. carefully click on the expand icon aside of hope to see it's children
5. Note that it expands and immediately closes
6. Note that clicking on it a second time causes it to act normally.

### Screenshots and/or videos

https://www.loom.com/share/904e37dcf0344e42a43bc4b6c48c2ffe

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
