### ISSUE TITLE
[studio-ui] Speed up Sidebar opening

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#708]
Currently, when you load the Sidebar, you see it animate as it loads and opens to where it was opened last time. This can take a while and that slow animation makes a fast user click on the wrong opens.

I'd like the sidebar to open to the right configuration quickly (instantly if possible) and not animate slowly as it reaches the final remembered state.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/356
