### ISSUE TITLE
XB Freemarker macro Auto-print breaks when vars have numbers

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Auto-print breaks when freemarker vars have numbers (e.g. `myVar1_s`)

### Steps to reproduce

Steps:

1. Create a var with a number
2. Try auto-print and notice browser console errors and lack of XB highlight

**Comment by Euquimides** [comment]
Hi @rart ! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
