### ISSUE TITLE
XB RTE ctrl+enter stopped working

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7085]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

XB RTE ctrl+enter save shortcut stopped working

### Steps to reproduce

Steps:

1. Click on an RTE on the guest app
2. Press ctrol|cmd+enter
4. Nothing happens

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
