### ISSUE TITLE
[studio-ui] Change "cancel" to "close" if a content-type has been saved

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#709]
If a user "saves" a content type, then the button called "cancel" should become "close" immediately.

If a user clicks on "close" or "cancel" and the content type has been modified, we need a warning dialog that tells the user:

"Content Type has been modified, are you sure you want to abandon your changes?" with a "Yes" and "No" buttons. If they press "Yes" they cancel/close out. If they chose "No" they go back to editing without a change.

**Comment by vestrada** [comment]
studio-ui - Master - PR: https://github.com/craftercms/studio2-ui/pull/378
