### ISSUE TITLE
Clean up old XML descriptors on blueprints

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7090]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

We've found blueprints with legacy properties on the XML descriptors 
e.g. `<descriptor-mapper>hierarchical-mapper</descriptor-mapper>` on the Fitness blueprint

### Describe the solution you'd like

Clean up blueprints

**Comment by sumerjabri** [comment]
Should be done with https://github.com/craftercms/craftercms/issues/5543
