### ISSUE TITLE
Remove `gosu` from Docker images

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7091]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

`gosu` triggers security issues due to unpatched Go Lang dependencies.

### Describe the solution you'd like

Remove `gosu` and use the built-in `su` instead.

**Comment by sumerjabri** [comment]
4.1.x is https://github.com/craftercms/craftercms/commit/e562016ec404fa8f3abbfd864c944ddbfa22be94

**Comment by Euquimides** [comment]
Hi! Enhancement implemented. Checked this in both v4.1.6 and v4.2.0 CE and EE. Thank you! Closing this ticket.
