### ISSUE TITLE
It's not possible to rename content twice in a row via the form engine

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7094]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Once you rename a content item in the form engine, the button for renaming disappears, making it impossible to adjust the rename.

### Steps to reproduce

Steps:

1. Open existing content via the form engine
2. Rename it
3. Note the edit button is removed 

### Screenshots and/or videos

See name control without edit button (post rename operation) below
![image](https://github.com/user-attachments/assets/87570dc9-0d6e-4209-8801-eeb8f8d60011)

**Comment by rart** [comment]
@russdanner We've corrected the disappearing button. There's a limitation to this dialog which is: renaming and then, trying to put the original name back. Because the new name is not saved, the dialog detects there's an existing item with that name and won't let you put it back. I'll create a follow up ticket for 4.3+ as it requires several code updates.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. 

Also:
> @russdanner We've corrected the disappearing button. There's a limitation to this dialog which is: renaming and then, trying to put the original name back. Because the new name is not saved, the dialog detects there's an existing item with that name and won't let you put it back. I'll create a follow up ticket for 4.3+ as it requires several code updates.

The reference ticket for this issue is here https://github.com/craftercms/craftercms/issues/7113

Thank you! Closing this ticket.
