### ISSUE TITLE
Add an option for cleaning up volumes before building images

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7101]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When building docker images using the `buildMainImages` or `buildAllImages` and then initializing this images using `docker compose`, existing past volumes with created sites might affect the initialization of Crafter via docker. Even though we have an option to stop the image and deleting the volumes, we don't have an option for deleting volumes before building the image. 

### Describe the solution you'd like

Add an option to clean up volumes before building docker images, as a sort or cleanup before the building process.

**Comment by sumerjabri** [comment]
The command is: `deleteDockerArtifacts`

**Comment by Euquimides** [comment]
Hi! Feature implementation verified. Thank you! Closing this ticket.
