### ISSUE TITLE
Reduce number of S3 calls while on serverless mode

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7102]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

RIght now, for every object that is retrieved from S3, 3 calls are done:

- One to check if it exists
- One to get the metadata
- One to get the content of the object

All of this can be retrieved in a single call

### Describe the solution you'd like

Reduce number of HTTP S3 calls needed to retrieve an object

**Comment by avasquez614** [comment]
Some test results for cache warming:

```
With 1000 items:

Old code: 183 secs
New code: 141 secs

With 10000 items:

Old code: 1679 secs
New code: 1291 secs
```

**Comment by sumerjabri** [comment]
To be verified in CC3.

**Comment by avasquez614** [comment]
Verified in 4.2
