### ISSUE TITLE
File name control rename dialog says there are pending changes after opening it clean for a second time

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7106]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

On the rename content dialog when used via the file name control (file name > LegacyFormDialog > RenameContentDialog), opening for a second time after having used the dialog, says there are pending changes when there are none.

### Steps to reproduce

Steps:

1. Go to a form
2. Click to edit the file name (url) field
3. Add some content to the name field and close/dismiss the dialog
4. Open the dialog again and without any changes try to close. Notice the pending changes dialog appears despite not having changed anything.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
