### ISSUE TITLE
[studio] Add an About Page to display Studio Version, etc

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#711]
Add an About Page to display Studio Version, etc

Please make "Help" at the top right of Studio a dropdown list with:
  1. Documentation - link to Crafter Documentation (What "Help" is doing right now)
  2. About - List information about the Studio Version running, etc.

**Comment by sumerjabri** [comment]
The About information should be:
Studio Version Number
Build Number
Build Date/Time

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/352

**Comment by vestrada** [comment]
@Sumer The dropdown, new options and documentation link are ready. 

Please let me know when the service is ready to work on about new page.

Thanks, Vero

**Comment by sumerjabri** [comment]
@vestrada please use these APIs to achieve the design we want:
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/version.html
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/status.html
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/memory.html

**Comment by vestrada** [comment]
On Hold. Carlos is checking the response of the version service. 
I'm not getting the correct info.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/410
