### ISSUE TITLE
Sidebar is breaks occasionally

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7116]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The sidebar breaks randomly when switching between sites or going to a site after a restart with the following error in the javascript console:

```
ErrorState-BB5OHA-Y.js:3934 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gi (ErrorState-BB5OHA-Y.js:5630:41)
    at Object.enqueueSetState (ErrorState-BB5OHA-Y.js:3864:19)
    at E$1.setState (ErrorState-BB5OHA-Y.js:86:16)
    at Transition2.updateStatus (ErrorState-BB5OHA-Y.js:13061:12)
    at Transition2.componentDidUpdate (ErrorState-BB5OHA-Y.js:13025:10)
    at kk (ErrorState-BB5OHA-Y.js:5461:18)
    at ik (ErrorState-BB5OHA-Y.js:5441:89)
    at ik (ErrorState-BB5OHA-Y.js:5435:41)
    at ik (ErrorState-BB5OHA-Y.js:5435:41)
    at hk (ErrorState-BB5OHA-Y.js:5422:3)
```

### Steps to reproduce

Steps:

No specific steps are known to reliably re-create this issue. It seems to occur randomly after a restart or after navigating between projects.

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/32f084e2-98c8-46d9-9f05-1676a5264f14)

**Comment by rart** [comment]
I've tried reproducing without success. Perhaps a specific plugin widget or combination of widget you have could help reproduce? That specific error would typically mean a render loop is occurring which could happen when setState is repeatedly called due to a defective effect design so plugins are a big suspect.

**Comment by sumerjabri** [comment]
@rart Russ confirms this happens with Editorial BP without any additional plugins. We must keep trying to reproduce this; it will happen; it just takes time.

**Comment by russdanner** [comment]
I will keep this open up until the release and monitor for occurrence.
