### ISSUE TITLE
[studio] Display the name of the Site to be removed in the Confirmation Dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#712]
Display the name of the Site to be removed in the Confirmation Dialog:

Click on the trash can icon to remove a site, notice the Confirmation dialog does not say which Site is it asking confirmation for, for removing.  It would be nice if the Site name is displayed in the Confirmation dialog.

![screen shot 2017-04-11 at 4 20 17 pm](https://cloud.githubusercontent.com/assets/25483966/24929156/0641b050-1ed3-11e7-9580-bb2ac6628a38.png)

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/358
