### ISSUE TITLE
[studio] Put cursor in the first input box (First Name) in the Create User dialog when the form is launched

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#713]
Put cursor in the first input box (First Name) in the Create User dialog when the form is launched.
It would be nice to have the cursor already in the first input box (First Name) in the Create User dialog when the form is launched.

<img width="639" alt="screen shot 2017-04-13 at 3 58 25 am" src="https://cloud.githubusercontent.com/assets/25483966/25008203/035036d2-2031-11e7-8aca-da42f4a870ae.png">

**Comment by sumerjabri** [comment]
Please also set the tab order to follow the fields logically and set the default button to Save.

**Comment by vestrada** [comment]
PR:  https://github.com/craftercms/studio2-ui/pull/354
