### ISSUE TITLE
[studio] Put cursor in "Display Label:" field in the Create Content Type dialog when the form is launched

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#715]
Put cursor in "Display Label:" field in the Create Content Type dialog when the form is launched.

It would be nice to have the cursor in the "Display Label:" field in the Create Content Type dialog when the form is launched so the user doesn't have to click on the field.

<img width="387" alt="screen shot 2017-04-13 at 4 10 29 am" src="https://cloud.githubusercontent.com/assets/25483966/25008823/d1f181c0-2032-11e7-98ba-c2573c85251c.png">

**Comment by sumerjabri** [comment]
Please also set the tab order to follow the fields logically and set the default button to Create.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/360
