### ISSUE TITLE
Duplicate Fails in XB

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7151]
### CI Number

5253

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Duplicate on repeat group through XB fails with Javascript error

### Steps to reproduce

Steps:

1. Start with an Editorial BP site
2. Remove Facebook icon from the header component
3. Using XB, attempt to duplicate the twitter icon
4. Duplicate fails due to javascript error 
5. Twitter icon should be duplicated and placed after the existing twitter icon

### Relevant log output

```shell
index-CERzyUzr.js:1243 DUPLICATE_ITEM_OPERATION failed TypeError: Cannot read properties of null (reading 'textContent')
    at :8080/studio/static-…3Rv_q3T.js:31997:56
    at :8080/studio/static-…i3Rv_q3T.js:4040:17
    at OperatorSubscriber2._this._next (:8080/studio/static-…BPT-Rc9p.js:20217:9)
    at Subscriber2.next (:8080/studio/static-…PT-Rc9p.js:20065:12)
    at :8080/studio/static-…PT-Rc9p.js:20256:18
    at OperatorSubscriber2._this._next (:8080/studio/static-…BPT-Rc9p.js:20217:9)
    at Subscriber2.next (:8080/studio/static-…PT-Rc9p.js:20065:12)
    at :8080/studio/static-…PT-Rc9p.js:20256:18
    at OperatorSubscriber2._this._next (:8080/studio/static-…BPT-Rc9p.js:20217:9)
    at Subscriber2.next (:8080/studio/static-…PT-Rc9p.js:20065:12)
```
```


### Screenshots and/or videos

https://www.loom.com/share/ea28cf2e20ae424cb217db509b564acb

**Comment by sumerjabri** [comment]
This might be a blueprint error in Editorial BP.

**Comment by russdanner** [comment]
Related: #7169

**Comment by russdanner** [comment]
Confirmed in 4.2.0
