### ISSUE TITLE
Update "Content type" controllers to "Page and Component Controllers"

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#7164]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

https://docs.craftercms.org/en/4.1/by-role/developer/common/content-type-controllers.html#index-0
It's really confusing to call page/component controllers "Content type" controllers.  I also can see why they are called that but it collides with the hooks in Studio.  IMO since they run only when rendered by freemarker they should probably just be called Page Controllers and Component Controllers.

### Describe the solution you'd like

Update `content type controllers` to `page and component controllers`

**Comment by sumerjabri** [comment]
@russdanner bump

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/common/page-and-component-controllers.html
https://docs.craftercms.org/en/4.1/by-role/developer/index.html#additional-concepts
