### ISSUE TITLE
[studio] Put cursor in the first input box in dialog when form launches

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#717]
It would be nice to have the cursor in the first input box in a dialog when a form launches.

In the image below, I am adding a new Category Landing Page.  It would be nice if the cursor is in the "Page URL" input box when the form launches

![screen shot 2017-04-13 at 4 15 50 am](https://cloud.githubusercontent.com/assets/25483966/25009167/cca74ed8-2033-11e7-9574-74097ffcb612.png)

Another example is when adding a new article page, it would be nice if the cursor is in the first input box in the dialog when the form launches, in this case, the "Page URL" input box

![screen shot 2017-04-13 at 10 31 00 am](https://cloud.githubusercontent.com/assets/25483966/25009431/a969a9e2-2034-11e7-9976-d50b09c247bc.png)

**Comment by sumerjabri** [comment]
Please also set the tab order to follow the fields logically.

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/357
