### ISSUE TITLE
Add the options menu to "Item" actions bar in XB that shows up when you click on an Item

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7177]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Users would like to get easy access to all of the actions available in the Options menu through XB.
Examples: See dependencies, See workflow status, see history/revert, unlock.

### Describe the solution you'd like

Add this menu
![image](https://github.com/user-attachments/assets/97fd13d9-0ff7-43ee-a9ba-69cd15ea22be)

To this menu 
![image](https://github.com/user-attachments/assets/ae64a3aa-8bd0-4ff2-a413-ea244a245fc7)

**Comment by rart** [comment]
Done-in/moved-to 4.2 to address [#7176](https://github.com/craftercms/craftercms/issues/7176)

**Comment by russdanner** [comment]
Confirmed
