### ISSUE TITLE
[studio] Tab order in "Create User" dialog is not as expected

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#718]
Tab order in "Create User" dialog is not as expected.
In most forms I have encountered, pressing the tab key moves the cursor in the editable fields of the active form only.  

1. In the "Create User" dialog, I put the cursor in the "First Name" field, and labeled it "1".
2. I then press the tab key, and the cursor moves on to the field labeled "2", I press the tab again, and it goes on...
3. After the cursor goes on to the field labeled "6" in the image (the "Cancel" button), if you press the tab key again, it goes to the address bar of the browser, labeled "7" in the image.  
4. Pressing the tab key again moves the cursor to the field labeled "8" (the Crafter CMS logo) and so on, 
5. When the cursor gets to the field labeled "12" (the search input box in the form behind the Create User dialog), pressing the tab key will finally return the cursor to the active dialog, the "Create User" dialog.

Normally, when the cursor reaches the field labelled "6" (the "Cancel" button), pressing the tab key, I expected the cursor to move to the field labelled "1" again and not go to fields outside the active dialog.

![screen shot 2017-04-13 at 10 39 37 am](https://cloud.githubusercontent.com/assets/25483966/25010428/19a0d714-2038-11e7-8734-1d1973f3128a.png)

**Comment by alhambrav** [comment]
Re-open issue to investigate if it's possible to easily fix the tab ordering (pressing TAB key should cycle through fields in active dialog only) in the current Studio version we have

**Comment by jvega-crafter** [comment]
Found a way of making it work, it works on users dialogs, we need another approach for groups or other dialogs that are into an iframe, the fix doesn't work there

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/360
