### ISSUE TITLE
[studio] Set focus on "Sign back in" button in login dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#719]
Set focus on "Sign back in" button in login dialog.

It would be nice to set the focus on the "Sign back in" button so when the user presses the "enter" key, the "Sign back in" button is clicked.

![screen shot 2017-04-12 at 4 45 14 pm](https://cloud.githubusercontent.com/assets/25483966/25007951/3104d200-2030-11e7-9117-1304fe00cc12.png)

**Comment by sumerjabri** [comment]
Please make sure the cursor is on Password to allow the user to type in the password right away and if they press enter, it does "sign back in".

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/354
