### ISSUE TITLE
Update XB article

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#7193]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Update the TODOs in the XB article

### Describe the solution you'd like

Update the following TODOs:

- [x] Update title L134 (Rules of XB)
- [x] In the ``Freemarker`` section, speak about the ice support classes, event capture overlay and special treatment for empty zones L362
- [x] Under the ``Freemarker Macros & Utilities`` section, add to the example? L394
  ```  
  eventCaptureOverlay $onlyInPreview=false $tag="div" $attributes={} attrs
  const editModeClass = 'craftercms-ice-on';
  const zKeyClass = 'craftercms-ice-bypass';
  ```
- [x] Under the ``initExperienceBuilder`` section, add context to the examples or find a way to make these look better/more meaningful when rendered L435
- [x] Review the description in the table for HTML Elements Tag Macros L470
- [x] Under the ``fetchIsAuthoring`` section, fix the TODO note that says: Internally it uses `crafterConf < add docs on readme and link to them >`_ L1624
- [x] Under the ``fetchIsAuthoring`` section, check the TODO question:Is addAuthoringSupport still needed? If used via npm, 
everything is imported from the package and, if imported as a script, everything is already loaded. L1652
- [x] Under ``Example Applications``, add an NPM section L1715

**Comment by alhambrav** [comment]
Adding @rart  for input

**Comment by sumerjabri** [comment]
@rart bump

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/by-role/developer/common/experience-builder.html#creating-experience-builder-xb-enabled-sites
