### ISSUE TITLE
[studio] Newly created content types are not visible in dialogs without a manual cache clear or restart

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#720]
When a user creates a new content type they are not able to create new content with it or access it to edit it because it is not visible in the dialogs.  

The user must first go to admin/configuration and click clear cache -- OR -- restart the server.

New types should automatically be available in dialogs without manual intervention from the user. 

## Steps to reproduce
1. Create a new component type
2. Save content type and go to dashboard
3. Open site panel -> Components and click new content (Note new content type is not visible.)
4. Go to admin console -> configuration
5. Click clear cache
6. go to dashboard
7. Open site panel -> Components and click new content (Note content type is now visible.)

**Comment by sumerjabri** [comment]
Please make sure you invalidate the cache or at least update it when a new content is created. We will need to figure this out in a clustering situation down the road.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/643
