### ISSUE TITLE
Socket connection not reestablished correctly after re-login

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7203]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Socket connection is not reestablished correctly after a session timeout and using the re-login dialog. Seems to have something to do with the XSRF token, so possibly related to the Spring upgrade.

### Steps to reproduce

Steps:

1. Login and leave the system alone until session times out and the login dialog up shows
2. Login from the dialog
3. Notice the "Connection with server interrupted" dialog and all the network traffic from the worker with failed attempts to reestablish connection.

**Comment by sumerjabri** [comment]
Please validate SSO.

**Comment by yacdaniel** [comment]
Verified fixed in `4.2.0-SNAPSHOT`
