### ISSUE TITLE
Migrate blueprints, plugins and other code to `OkHttp` library or other modern options

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7204]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The dependency `io.github.http-builder-ng` won't be usable in `v4.2.0` and above, since it has ended support as shown in their repository https://github.com/http-builder-ng/http-builder-ng?tab=readme-ov-file. This might affect blueprints (project creation), plugins and other dependable code in the future.

### Describe the solution you'd like

Migrate blueprints, plugins and other code to `OkHttp` library (https://github.com/square/okhttp) or other modern options to support `v4.2.0` and above.

**Comment by sumerjabri** [comment]
I wasn't able to find the package `http-builder-ng-core` in use.
