### ISSUE TITLE
[studio] get-ui-resource-override.get.groovy contains invalid class path

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#721]
Script: /scripts/rest/api/1/server/get-ui-resource-override.get.groovy contains invalid class path
class path in script is currently: crafter/cstudio/ui/, should be changed to crafter/**studio**/ui/

**Comment by russdanner** [comment]
This bug breaks the logo override.

**Comment by sumerjabri** [comment]
Please externalize all configuration, if not a config, at least must be a constant.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/644

**Comment by russdanner** [comment]
Verified
