### ISSUE TITLE
Increase the default font size for code and text editing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7210]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The default font size is too small for text and code editing (ACE?).

### Describe the solution you'd like

Please increase the default font size to be easier to read. Consider font size 18px and socialize internally with @russdanner and me for final review.

I tested by setting `body > div.MuiDialog-root.MuiModal-root.mui-126xj0f > div.MuiDialog-container.MuiDialog-scrollPaper.mui-ekeie0 > div > div.MuiDialogContent-root.craftercms-gezvjk-container.mui-1yb1f3e > div > pre` to `font-size = 18px` and it looked good:
![image](https://github.com/user-attachments/assets/dd47a7d2-6dc1-4ce3-a35b-caa7e7b71731)
![image](https://github.com/user-attachments/assets/6d3b4e69-0dd2-4b73-8eae-e527b6cc4eee)

**Comment by rart** [comment]
@sumerjabri,

Here are some popular code editors and their font size:
- GitHub 12px
- CodeSandbox 14px
- StackBlitz 12px
- Visual Studio Code 12px
- IntelliJ IDEA 13px
- Monaco editor 12px
- Ace editor 12px

Standards & convention dictate we keep default font size to 12-14 px. If we do increase it, I suggest a maximum of 14.

It could be more important to add the ability to control certain preferences, starting with font size. 

I can see value in being able to temporarily increase the font size with a UI preference control or to accommodate individual preferences but another reason to keep it on the _shorter_ size is that it has been seen in research (Arditi et al.) that monospaced character readability is better at small font sizes.

Code typically has many different colours and tokens which can seem very cluttered particularly above 16px.

@russdanner also curious if we have any external feedback supporting increasing the font size?

**Comment by sumerjabri** [comment]
Part of the problem was the font used on Linux, it was `Ubuntu Monospace` and that just didn't look big enough. Agreed to use `14px` with `monospace` font (seems to be closest to what we want).
