### ISSUE TITLE
[studio-ui]  Submit button is disabled on approve dialog when content is scheduled

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#722]
When an author submits content for approval with a schedule, and the publisher is reviewing it for approval via the publish dialog, the submit button is disabled.  The publisher must first touch the schedule controls to enable the submit button.

Because the form contains the (potentially) desired information, the button should already be enabled.   

## Steps to reproduce
1. As author submit content with schedule
2. As admin, select submitted item and click Approve and Publish
3. Note submit button is disabled (should not be)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/355
