### ISSUE TITLE
Improve the Groovy/Java API reference section

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7223]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The structure is not right, and not enough examples.

### Describe the solution you'd like

- Rename `Groovy Development` to `Groovy/Java API`
- Move the `Java API` section to become three examples under the Groovy API section (after the first table)
- Add a reference to the Java Doc from this section
- Move the JavaDoc section to the new `Groovy/Java API` article

**Comment by alhambrav** [comment]
https://docs.craftercms.org/en/4.1/reference/api/groovy-java-api.html
