### ISSUE TITLE
Rename does not issue a delete order to publisher

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#723]
2.4 environment

## Steps to reproduce:
1. Rename an existing page via form
2. Publish rename
3. Note: 
3.a: Renamed object is published to preview and preview solr index
       Old Object path is removed from preview and search index
3b. Renamed object is published to target (live) and target solr index
       Old Object path is NOT removed from target and search index.

**Comment by sumerjabri** [comment]
@dejan-brkic this is the next priority ticket (ahead of new development)

**Comment by sumerjabri** [comment]
This ticket is now second in priority to https://github.com/craftercms/craftercms/issues/661

**Comment by dejan-brkic** [comment]
Can not reproduce with steps described above
