### ISSUE TITLE
Images are uploaded with Content-Type binary/octet-stream to S3 

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#7230]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you have a blob store and an image is uploaded from Studio, Studio stores the image with a `Content-Type` metadata field of `binary/octet-stream`. This means that when it's published and served directly by CloudFront, CloudFront is going to include that `Content-Type` in the response and will cause the browser to download the file instead of displaying the image.

### Steps to reproduce

Steps:

1. Create a site based on empty
2. Configure the site to have an S3 blob store under `/static-assets/images`
3. Upload an image to `/static-assets/images`
4. In S3, navigate to the image path and click on it to open its properties. 

In the `Metadata` section of the properties, you should see the `Content-Type` set as `binary/octet-stream` instead of `	image/jpeg`

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/0c28f8ed-cee3-4752-9d77-09fbfd530cb4)

**Comment by avasquez614** [comment]
Just to clarify, this ONLY happens with blobs, which are uploaded by Studio. If the Deployer uploads the files to S3, the content types are set correctly

**Comment by sumerjabri** [comment]
This must be tested against S3. Ask for bucket access if you need one.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. This was tested both with Amazon s3 buckets and with MinIO bucket system. Fix verified for v4.2.0. Thank you! Closing this ticket.
