### ISSUE TITLE
[studio] Audit does not log changes made to content type

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#724]
Audit does not log changes made to content type

1. Go to Admin Console.
2. Open an existing content type.
3. Make some changes and save it
4. Open Audit, notice that changes made to the content type is not logged.

**Comment by dejan-brkic** [comment]
Completed, PR pending

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/899
(master https://github.com/craftercms/studio/pull/899)

**Comment by alhambrav** [comment]
Verified fixed.
