### ISSUE TITLE
clearS3BucketLifecycleHook does not delete the delete marker

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#7241]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When clearing the S3 bucket, we also delete the versions if the versioning is enabled for the bucket. In this case, the processor only removes the versions and keeps the delete markers which causes the bucket to be not empty and cannot be removed during the site delete process.

See https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html

### Steps to reproduce

Steps:

1. Update Studio for serverless deployment with the template `aws-cloudformed-s3` https://docs.craftercms.org/en/4.1/reference/modules/engine/configuration.html#step-3-configure-authoring-for-serverless-deployment
2. Update the site bucket to enable versioning
3. Create a site from Editorial BP and publish
4. Delete the site
5. Notice that the CloudFormation stack deletion failed with the error that the bucket is not empty

**Comment by phuongnq** [comment]
@avasquez614 FYI

**Comment by sumerjabri** [comment]
@yacdaniel FYI

**Comment by sumerjabri** [comment]
To be verified in CC3.

**Comment by avasquez614** [comment]
Verified
