### ISSUE TITLE
Audit database table entries contain wrong commit ID due to a race condition within the write operation APIs

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#7244]
### CI Number

5310

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

A race condition exists on write via the API such that when multiple write API calls (Create, Update, Rename etc) are made within a short amount of time, for some of those calls, the wrong commit ID is associated with the operation in the audit table.

The following query is expected to return 0 items in all cases:
`select count(*) as commitcount, id, commit_id, origin from audit where origin='API' group by commit_id having commitcount > 1;`

**Comment by sumerjabri** [comment]
Same as https://github.com/craftersoftware/craftercms/issues/1000

**Comment by yacdaniel** [comment]
Verified in 4.1.7-SNAPSHOT with 6 different users, doing copy-paste and writes at the same time in different locations, commit id duplicates aren't found in the db.

**Comment by yacdaniel** [comment]
Verified in `4.2.0-SNAPSHOT`.
