### ISSUE TITLE
[studio] Audit does not log changes made to config files

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#725]
Audit does not log changes made to config files under Configuration in the Admin Console.

Go to the Admin Console.
Go to Configuration.  
Select one of the config files there, say, "Site Dropdown Configuration"
Make some changes in the config file and save it.
Go to Audit, notice that changes made to the config file is not logged.

**Comment by dejan-brkic** [comment]
Completed, PR pending

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/899
(master https://github.com/craftercms/studio/pull/899)

**Comment by alhambrav** [comment]
Verified fixed.
