### ISSUE TITLE
[studio] Audit does not log changes to Users

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#726]
Audit does not log changes to Users

Click on "Users" at the top right of the browser
Add a user or remove one of the users 
Go to the Admin Console, then open Audit, notice that the changes made to users are not logged

**Comment by dejan-brkic** [comment]
Completed, PR pending

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/899
(master https://github.com/craftercms/studio/pull/899)

**Comment by alhambrav** [comment]
Verified. (Used the DB to verify)
