### ISSUE TITLE
[studio] Audit does not log changes to the Site Navigation Tree

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#727]
In the Website_Editorial, enable the Sidebar
Go to the Site Navigation Tree, say go to the folder "articles"
Right click and select New Folder, name the folder.

Go to the Admin Console
Click on Audit, notice that changes made to the Site Navigation Tree is not logged

**Comment by dejan-brkic** [comment]
Completed, PR pending

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/899
(master https://github.com/craftercms/studio/pull/899)

**Comment by alhambrav** [comment]
Verified fixed.
