### ISSUE TITLE
S3 Image/Video datasource filtering by Content-Type not work

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#7287]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

S3 Image/Video data source filtering by Content-Type (image, video) do not to work.
Our API uses the parameter type for this (https://github.com/craftercms/studio/blob/support/4.1.x/src/main/api/studio-api.yaml#L1558) but the UI is sending the parameter `filter`. Ex: `filter=image`.
As a result, the response for image/video selection includes all the assets.

We should send `type=image` or `type=video` instead.

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Update S3 Profile to add a profile
3. In a content type (Ex, Home), update the image to browse from S3 repo
4. Notice that the UI is sending the `filter=image` but all S3 objects are responded

### Screenshots and/or videos

![Screenshot from 2024-09-18 09-15-18](https://github.com/user-attachments/assets/f614d501-3071-4ea8-b7f2-c0aab32fb483)

**Comment by jvega190** [comment]
It's recommended to test all of the s3-browse datasources (Image/Video/File from s3 repo)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v4.1.9 and v4.2.0. Thank you! Closing this ticket.
