### ISSUE TITLE
[studio] Cut / Paste and Copy / Paste don't work.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#731]
Steps:
1. Login to craftercms 3
2. Create a site
3. Expand Pages
4. Expand Home
5. Create new content
6. Create new folder 
7. Try to copy the content created in the step 5 and paste it in the folder created in the step 6.
8. Try to cut the content created in the step 5 and paste it in the folder created in the step 6.

Current Behavior:
Cut / Paste and Copy / Paste don't work.

Evidence: https://www.screencast.com/t/21uvhiCdj8Jn

Expected Bahavior:
Both process should be work properly.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/653

**Comment by sumerjabri** [comment]
@gortizcrafter please validate and close/move to `completed` if it works.
