### ISSUE TITLE
Disabled Pages in Selection Tree

### ISSUE THREAD

**Issue by sandeepkadyan** [craftercms/craftercms#732]
The disabled pages are showing in the selection tree, we need to be removed disabled pages.

**Comment by cortiz** [comment]
To add more information:

When a page is disable, the Strike down on the name should persist in the Browse window

_**In the examples below, Sample page is disable.**_

![viewondashboardtree](https://cloud.githubusercontent.com/assets/574641/25201441/fcf07558-250e-11e7-8272-d302c0a25e62.png)
 View on dashboard

![strikedownmissingonbrowse](https://cloud.githubusercontent.com/assets/574641/25201448/0319e9dc-250f-11e7-88f0-b617c9a6db59.png) View when trying to select the page 

![strikedownmissingfromtree](https://cloud.githubusercontent.com/assets/574641/25201466/11733fd8-250f-11e7-8b46-f1e7007e30b9.png)
 View when trying to select a child of the page

In all cases when a page is disable it should keep the style consistent.

**Comment by sumerjabri** [comment]
We need the fix for 2 and 3.

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/365

**Comment by vestrada** [comment]
studio-ui - 2.5.x - PR: https://github.com/craftercms/studio2-ui/pull/366
