### ISSUE TITLE
[studio] Put cursor in "Email/Username" field in the login dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#733]
Open a browser and open studio (localhost:8080/studio) or if you already have studio open, sign out. 
Notice the Crafter Studio login dialog does not have the cursor on any of the fields.  It would be nice for the cursor to be in the Email/Username field when logging in.

<img width="316" alt="screen shot 2017-04-19 at 11 03 06 am" src="https://cloud.githubusercontent.com/assets/25483966/25187657/b276e038-24f1-11e7-9903-3529556e1728.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/361
