### ISSUE TITLE
Enhance RTE paste to support basic formatting

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7339]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Pasting text that has:
- Bold
- Italics
- Strikethrough
- Superscript
- Subscript
- Underline

Fails to carry these formatting options. Headings, bullets, numbering, and tables work well.

### Describe the solution you'd like

Support:
- Bold
- Italics
- Strikethrough
- Superscript
- Subscript
- Underline

**Comment by jvega190** [comment]
Supported formats: bold and italics.
Also lists (bullets and numbers) with the formats above are working.

\* Headings, bullets, numbering, and tables are still working properly.
\* Currently strikethrough and underline are not supported to avoid inline styles possibly overriding projects CSS

**Comment by Euquimides** [comment]
Hi! Verified enhancement implementation. Thank you! Closing this ticket.
