### ISSUE TITLE
[studio] The option duplicate not work.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#734]
Steps:
1.Login to craftercms 3
2.Create a site
3.Expand Pages
4.Expand Home
5.Create new content
6.Select the new content created and try to duplicate it using the option of the menu.

Current Behavior
The option to duplicate of the menu not work.

video: https://www.screencast.com/t/gD4RZx6Ny

Expected Bahavior
The content created should be duplicate properly.

**Comment by dejan-brkic** [comment]
Done 

PR
https://github.com/craftercms/studio/pull/653
