### ISSUE TITLE
Update the RTE configuration to work with TinyMCE 7 (from TinyMCE 5)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7340]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

TinyMCE 7 changes the configuration value `formatselect` to `blocks`, which breaks the RTE in v4.2.

### Describe the solution you'd like

Use the Upgrade Manager to replace `formatselect` in `ui.xml` if coming from 4.1 or older to become `blocks`. Use a regex replacement mechanism since this is JSON, not XML.

This might help: https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/upgrade/operations/site/FindAndReplaceUpgradeOperation.java

**Comment by rart** [comment]
Verified
