### ISSUE TITLE
[studio] Disable deletion of homepage via permissions

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#736]
Please update all blueprints to disable the deletion of the homepage in the permissions.

Possible approach: Add a ruleset without delete on /site/website/index.xml specifically, and allow delete on rest.

**Comment by alhambrav** [comment]
PR 673

**Comment by sumerjabri** [comment]
Please make sure it's in all blueprints.

**Comment by alhambrav** [comment]
Deletion of homepage is available only for the Crafter Admin but should be disabled for all Users created by Crafter Admin, including users in the Admin Group
