### ISSUE TITLE
MariaDB has the wrong version in Alpine

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7361]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

We are using MariaDB `11.3.2`.
However, Docker images (alpine) will contain `11.2.3`

### Steps to reproduce

Steps:

1. Build authoring image `./gradlew buildAuthoringTomcat`
1. Run a container using that image `docker run -d -p 8080:8080 craftercms/authoring_tomcat:4.2.0-SNAPSHOT`
1. Go to the container command line `docker exec -it <CONTAINER ID> bash`
1. Get the mariadb version: `/opt/crafter/bin/dbms/bin/mariadb --version`
```
/opt/crafter/bin/dbms/bin/mariadb from 11.2.3-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1
```

Notice it reports `11.2.3` instead of `11.3.2`

In ubuntu it shows the right version:
```
./bin/dbms/bin/mariadb from 11.3.2-MariaDB, client 15.2 for linux-systemd (x86_64) using readline 5.1
```

**Comment by phuongnq** [comment]
Relate to https://github.com/craftercms/craftercms/issues/7044

**Comment by yacdaniel** [comment]
Verified fixed 
```
a33827149d07:/opt/crafter/bin/dbms/bin$ ./mariadb --version
./mariadb from 11.4.3-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1
```
