### ISSUE TITLE
Search results not refreshing deleted items in view after delete action

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7363]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

In `Search` when selecting items and then clicking on the delete action, after the deletion, the search results don't refresh so the deleted items stay on view, all while the top snackbar stays on a loading state.

It is expected from this ticket for the search results to refresh after they've been selected for deletion. 

### Steps to reproduce

Steps:

1. Create a new project. 
2. Go to `Search`
3. Select one or more items by clicking in the checkbox. 
4. In the snackbar that appears, click in delete.
5. See the issue: the search results are not refreshed after the action and the snackbar appears empty. 

### Screenshots and/or videos

https://github.com/user-attachments/assets/b573b810-7316-4a6e-98e7-616a7396b959

**Comment by sumerjabri** [comment]
@rart LMK if safe for 4.2

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v4.2.0. Thank you! Closing this ticket.
