### ISSUE TITLE
Publishing various items inside `Search` will make menu bar enter loading state

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7372]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Publishing various items inside `Search` will make the menu bar flicker/skeletonize. This might be due to content events in the websockets. 

### Steps to reproduce

Steps:

1. Create a new project. 
2. Go to `Search`
3. Inside `Search` select various items by clicking in the checkbox.
4. In the options provided by the menu bar above, click on `Publish`.
5. See the issue: the snackbar flicker and skeletonize for each of the selected items. 

### Screenshots and/or videos

https://github.com/user-attachments/assets/ad0a854c-1a3b-4581-84fd-b545424895ba

**Comment by sumerjabri** [comment]
The behavior is correct. We're okay with this.
