### ISSUE TITLE
[studio-ui] Please move sync buttons to Admin Console

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#738]
Please move the two buttons:
`Preview Sync`
`Sync From Repository`

to the Admin Console instead of being in the Sidebar.

Ping me if you need help.

**Comment by vestrada** [comment]
studio - master - PR: https://github.com/craftercms/studio/pull/654

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/372

**Comment by sumerjabri** [comment]
The tools don't show up in the Site Config (aka Admin Console). See screenshot:
![screen shot 2017-04-24 at 9 57 50 pm](https://cloud.githubusercontent.com/assets/3931908/25365804/4e346126-2939-11e7-8ec5-e0bf3fa5c7e6.png)

**Comment by sumerjabri** [comment]
The names of the links are not pretty/spaced. What can we do to address that? Also, we need that localized into Spanish and Korean.

**Comment by sumerjabri** [comment]
Caching was an issue, after clearing cache, it worked.
