### ISSUE TITLE
Cannot select path outside /site in Shared Content Datasource

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#7381]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

The doc page that describes how to create a controller selector:

[Content Modeling --> Model](https://docs.craftercms.org/en/4.1/by-role/developer/common/content-modeling/content-modeling.html#id10)

indicates that it is possible to specify a directory path of `/scripts` as a Repository Path.  This is not possible - the `/site/` prefix is always prepended.

It should be possible to override the automatic prefix to allow this functionality to work.

### Steps to reproduce

Attempt to create the content model shown in the doc link above.

**Comment by sumerjabri** [comment]
FE2?

**Comment by sumerjabri** [comment]
@tfield please use the File Data Source in the near-term. We will make this easier/simpler in FE2.
