### ISSUE TITLE
RTE Cut/paste action not working

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#7396]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Doing cut/paste on an RTE is failing and the action can't be performed

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Click on an RTE field (also reproducible in form) and cut some content
3. See the issue

**Comment by sumerjabri** [comment]
@Euquimides please a QA ticket to automate this test via UI automation.

**Comment by Euquimides** [comment]
@sumerjabri here is the ticket https://github.com/orgs/craftersoftware/projects/16/views/1?pane=issue&itemId=83636147&issue=craftersoftware%7Ccraftercms%7C1027

**Comment by yacdaniel** [comment]
Verified fixed.
