### ISSUE TITLE
[studio] recent activity does not filter by basic type page | components | all

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#740]
On the right and side of the recent activity dashboard there is a drop down filter that is set to pages by default.  User can select this and filter to just pages or ask to show everything.

Currently the dashboard shows static assets even when the filter is set to pages
Component edits don't ever show up under any filter

## steps to reproduce
1. log in
2. go to dashboard, see my recent activity is set to pages
3. upload an image, see that image shows up in feed
4. change filter to all
5. edit a component, see that component edit does not show up

**Comment by sumerjabri** [comment]
Can't reproduce.
