### ISSUE TITLE
ESAPI policy causes project image upload to fail

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7405]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

ESAPI policy causes project image upload to fail

### Steps to reproduce

Steps:

1. Edit a project in Studio
2. Attempt to upload an image
3. See path validation error

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/7235e504-d0de-41d0-9f33-5e90cea4c87c)

**Comment by sumerjabri** [comment]
@Euquimides please create a QA ticket to add this test case.

**Comment by Euquimides** [comment]
Hi! Update and rechecked this issue. Fix verified for v4.2. 

Added this as a test case for automation https://github.com/craftersoftware/craftercms/issues/1031

Also there is a related enhancement request for this ticket https://github.com/craftercms/craftercms/issues/7413

Thank you! Closing this ticket.
