### ISSUE TITLE
Pages search ahead not showing the results in Preview address bar

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#7406]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

The pages search ahead functionality is not showing in the preview address bar

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Click on the 'Preview Address Bar' (studio's browser bar) and start typing `style`
3. See how the results that should show below the address bar is not showing.

\* The screenshot below is what should show:

![Screenshot from 2024-10-17 09-52-52](https://github.com/user-attachments/assets/d7325671-8ba4-467c-a9f3-6f54fb13e802)

**Comment by rart** [comment]
Confirmed
