### ISSUE TITLE
[studio] deployment history that contains very large deployment creates performance issues

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#742]
Publishing a large set (25K files, 90K+ files) in a single commit creates a performance problem due to publish history dashboard reporting / API call.

## setup steps
1. do a large commit in sandbox
2. publish to production (manual or via ui)

## reproduce the issue
1. perform setup
2. call dashboard history rest call /studio/api/1/services/api/1/deployment/get-deployment-history.json?site=SITEID&days=30&sort=eventDate&ascending=false&num=20&filterType=pages
2a. Note: The more you make the rest call (multiple users using dash) the worse things will get.

**Comment by dejan-brkic** [comment]
Initial improvement done

PR https://github.com/craftercms/studio/pull/647
