### ISSUE TITLE
History comparison update issues

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#7428]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

The compare switch is allowing you to compare things that only the new (not released) version of diff supports.

### Steps to reproduce

Steps:

1. Go to Templates and open the item menu of any template that has more than one history entry
2. Click on History
3. Compare two revisions
4. Notice the 500 error page shown

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/9ed78ad4-5437-4fdc-a433-4052c79c3ff3)

![image](https://github.com/user-attachments/assets/29f858f8-2184-46e2-a9b4-61cbea6a53a6)

**Comment by rart** [comment]
Related to https://github.com/craftercms/craftercms/issues/4768

**Comment by yacdaniel** [comment]
@jvega190 please take a look at the History in config files
Clicking the `History`  button is returning an error.

![image](https://github.com/user-attachments/assets/a82239ca-4082-4bfd-95d2-6a6dd7df0780)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v4.2.0. Thank you! Closing this ticket.
