### ISSUE TITLE
Copy and pasting content with embedded format hints in RTE is duplicated. Also, copy & paste not working in plain text fields in XB.

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7429]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Copy and pasting content either FTL, XML, HTML, Groovy or links inside an RTE is being duplicated. Also, copy and paste not working in Simple Text fields.

It is expected from this fix that copy and paste works in text fields that supports it. 

### Steps to reproduce

Steps:

For the duplicated copy and paste issue:

1. Create a new project based on Editorial
2. In an RTE field via XB, paste a URL or a link. 
3. See the issue: the URL text is duplicated. This also happens with FTL, XML, HTML and Groovy content. Doesn't happen with unstructured text. 

For the Simple Text fields copy and past issue:

1. Create a new project, can be based on Editorial.
2. Click on a Simple Text field using XB. 
3. Try to paste some content.
4. Notice it doesn't work: throws maximum length reached error. 

### Screenshots and/or videos

https://github.com/user-attachments/assets/1b3c1111-6359-4db2-9340-c4987fd9713a

**Comment by Euquimides** [comment]
Hi @rart and @jvega190 ! While validating this ticket I noticed that the user is able to bypass the limit of 50 chars in `Simple Text` field, by pasting content using XB, as shown in the video attached. 


https://github.com/user-attachments/assets/95070198-4f5f-4301-977f-7b755c63ddde

Could you please check this out? Thanks!

**Comment by rart** [comment]
@Euquimides please create separate tickets for issues not related to incorrect paste behaviour.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! 

The ticket for the mentioned bypass of character limit of `Simple Text` fields can be found here https://github.com/craftercms/craftercms/issues/7433

Closing this ticket.
