### ISSUE TITLE
[studio-ui] message bundle forces all labels to id format and returns id if message not found

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#743]
<img width="1342" alt="bundle-forces-id" src="https://cloud.githubusercontent.com/assets/169432/25282604/fe7302e4-267e-11e7-9357-c1b77c2e6f8a.png">

Note that the label provide by the configuration is human readable.
To create a bundle/string ID the code IDizes the label -- but in this case no matching ID is found in the message bundles.  

Can we return the original text in this case?

**Comment by vestrada** [comment]
studio-ui- master - PR: https://github.com/craftercms/studio2-ui/pull/369
