### ISSUE TITLE
[studio] Display name of User Logged In to Studio

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#744]
It would be nice to display the name of the user logged in to Studio.  We can maybe change "Account" at the top right of Studio to say `username`

![screen shot 2017-04-21 at 2 15 54 pm](https://cloud.githubusercontent.com/assets/25483966/25290762/54678d28-269d-11e7-8b07-76b010d12822.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/376
