### ISSUE TITLE
Forms Engine - Content locked after cancelling form with changes

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#7460]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

When cancelling the form with changes, sometimes the content is not properly unlocked, the network conditions affect on this (usually happens in slower networks)

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Open the edit form for the home page
3. Make an edition
4. On the developer tools of your browser, simulate a slow network (e.g. in google chrome, set to `Slow 4G`
5. Cancel the form, click on `Accept`.
6. See how the homepage stays locked.

\* This issue is not always reproducible, sometimes it does unlock properly

### Screenshots and/or videos

https://www.loom.com/share/c5cafc9228374fd8820fb4af17f779e1?focus_title=1&muted=1&from_recorder=1

**Comment by jvega190** [comment]
@rart assigned to you for code review

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
