### ISSUE TITLE
Studio cannot read nested folders with a single character names

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7462]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Studio fails read operations when nested folder names are a single character.

### Steps to reproduce

Steps:

1. Create a site from editorial blueprint
2. From Studio sidebar, go to pages and create a folder named `a`
3. Inside `a`, create a new folder named `b`
4. The UI shows an error:
![Screenshot from 2024-10-29 11-49-59](https://github.com/user-attachments/assets/a67dbd3e-feba-49b7-9dab-382de69fb909)

5. Create a folder named `b` under pages
6. Copy Health and paste it into `b`
7. Cut `b` and paste it into `a`
![Screenshot from 2024-10-29 11-54-40](https://github.com/user-attachments/assets/b652fb0d-6d56-4f57-a39a-c2bc8af1c5ab)

8. Expand `a` and then expand `b`
![Screenshot from 2024-10-29 11-55-40](https://github.com/user-attachments/assets/97afdc0d-852f-4280-adc7-b87a0ef40ed2)

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.
