### ISSUE TITLE
Make studio task executor thread pool configurable

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7464]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

New features have been added to Studio that rely more on asynchronous processing. Unavailability of threads might cause performance degradation and lost messages across the system. This will present specially in environments with multiple users updating content simultaneously in many sites.

https://github.com/craftercms/studio/blob/69cad98fbff44559e34a9ff4d10eec3db8c3abeb/src/main/resources/crafter/studio/studio-services-context.xml#L1358:L1361

### Describe the solution you'd like

Make `studioTaskExecutor` thread pool parameters configurable.
Consider increasing the max values

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Tested it against 30+ sites doing commits simultaneously. Also did a stress test against 300+ sites. The current configuration along with the possibility of configuring `studioTaskExecutor` for more capacity is working fine now. Thank you! Closing this ticket.
