### ISSUE TITLE
Review item table queries and update db indices

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7465]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Sometimes, when there are many (1M+) records in the `item` table, get content item operations are very slow.
Particularly getItemByPathPreferContent in `/content/item_by_path` is taking minutes to respond for a single item call.

### Describe the solution you'd like

- Review queries like [getItemByPathPreferContent](https://github.com/craftercms/studio/blob/develop/src/main/resources/org/craftercms/studio/api/v2/dal/ItemDAO.xml#L470).
- Consider adding an index on state column (or a combination of heavily queried columns)

**Comment by jvega190** [comment]
Per discussion with @jmendeza, some dashboard dashlets are calling the API's twice when opening the dashboard. Since `pending_approval` API uses `getDetailedItemsByStates`, this may cause performance issues

**Comment by avasquez614** [comment]
Verified
