### ISSUE TITLE
"Workflow Cancellation” prompt briefly flashes when editing an item from a node selector

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#7469]
### CI Number

5389

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x

### Describe the issue

When editing a content type that has a node selector and clicking on the edit icon of any of the items in the node selector a Workflow Cancellation popup is briefly shown.

![image](https://github.com/user-attachments/assets/a08f030c-89c7-44c5-8f15-5245d3545314)

### Steps to reproduce

Steps:

1. Create a site based on Editorial
2. Edit the "Search Results" page
3. Scroll down to the Categories section
4. Select the "Edit" button and notice that there is a dialogue box that briefly pops up before opening the content form

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/d566cbce-c57d-4398-be19-a76497466fb1)

https://github.com/user-attachments/assets/9aa2caec-a026-47f2-bb8f-aab57f118e9b

**Comment by rart** [comment]
FE2

**Comment by rart** [comment]
There might still be a _flash_ on fast systems but at least it'll be a spinner now. The system is indeed loading but fast systems will show and hide the intermediate loading state almost immediately.

**Comment by russdanner** [comment]
https://www.loom.com/share/75f74449f34d4186bf15a6e9bfe1707e

**Comment by rart** [comment]
@russdanner see my comment above. I do not want to remove the loader. Systems or moments with a higher latency require the feedback to indicate the system is working and their click had an effect. 

Long term, in general we want a mechanism that could be used to show a spinner only if things take longer than X ms, but we can't just remove the visibility of system status for this cosmetic improvement; thats happy path design and thinking.

**Comment by russdanner** [comment]
@rart I understand the thinking. It still appears more like a bug than not. Is it loading and closing so fast the spinner doesn't show (see video?)

**Comment by russdanner** [comment]
Roy and I spoke and came to an understanding. This will pass for now.

**Comment by russdanner** [comment]
Confirmed 4.1.9
