### ISSUE TITLE
[studio-ui] Studio flickers while left idle

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#747]
Why does Studio flicker when left idle? Please advise on how that can be fixed and let's discuss that fix before you build it.

**Comment by sumerjabri** [comment]
See Slack for the flicker video (I can't attach a video easily).

**Comment by vestrada** [comment]
I found a bug in the code, that will fix it.
PR: https://github.com/craftercms/studio2-ui/pull/374
