### ISSUE TITLE
Existing dependencies are all set to `0` / `invalid` despite the `VALID` column in dependency table being born with a default of `1` / `valid`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7471]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Existing dependencies are all set to `0` / `invalid` despite the `VALID` column in dependency table being born with a default of `1` / `valid`

### Steps to reproduce

Steps:
Unknown

**Comment by jmendeza** [comment]
Steps: 
1. Create a site. Check dependencies in the db (it is expected some mix of valid/invalid dependencies).
```
select site, valid, count(*)
from dependency
group by site, valid;
```
```
'ed1015', '0', '51'
'ed1015', '1', '163'
'ed1016', '0', '51'
'ed1016', '1', '163'
```

2. Create another site. Check dependencies in the db. All dependencies will be marked valid=0 except for the most recently created site:
```
'ed1016', '0', '214'
'ed1017', '0', '51'
'ed1017', '1', '163'
```

**Comment by yacdaniel** [comment]
Verified, found this bug during the validation 
https://github.com/craftercms/craftercms/issues/7477
