### ISSUE TITLE
Double hyphen not accepted in file name field or edit file name dialog

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#7474]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

File name field doesn't allow double hyphens when in file name field or edit file name dialog.

### Steps to reproduce

Steps:

1. Go to a site based on editorial
2. Edit 'Style', and click on 'Edit' in Page URL
3. Try to add two consecutive hyphens
4. See the issue

\* The same happens when creating new content, and trying to add two or more consecutive hyphens in Page URL

**Comment by russdanner** [comment]
@sumerjabri @jvega190 I added this to 4.2.0 and put it in progress because there's a draft pull request.

**Comment by sumerjabri** [comment]
Will not pursue this.
