### ISSUE TITLE
Workflow cancellation should cancel all items in a package and update the Workflow State

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#7482]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

When a user tries to edit a file that is part of a schedule package, the "Workflow Cancellation" dialog appears. This dialog does not display all files of that "schedule package".

### Steps to reproduce

Steps:

1. Create a site from Editorial
2. Do the initial publish
3. Modify the files `Home`, `/templates/web/pages/home.ftl`, `/scripts/pages/home.groovy` , `/templates/web/components/features.ftl` `/site/components/features/[Closed Captions - Smile]`
4. Do a Publish - Schedule Later
5. Try to Edit the scheduled files, notice how the `Workflow Cancellation` dialog doesn't display all the files from the scueduled package
6. If the user accepts the `Workflow Cancellation`, the Publish package is Cancelled, but the Workflow State of the items from the package isn't updated and remains in `Schedule` 

### Screenshots and/or videos
Publish package
![image](https://github.com/user-attachments/assets/dd6046eb-99a0-4909-86c5-d8e25fb20e1e)

Workflow Cancellation when editing Home page
![image](https://github.com/user-attachments/assets/8ccbc0a3-0b2b-43af-bd27-6a0e2444d8cb)

Package cancelled but items in `Schedule` state
![image](https://github.com/user-attachments/assets/b67a400b-c5c8-47c3-a737-e1a05866d42d)

_No response_

**Comment by jmendeza** [comment]
As discussed, workflow affected paths are:
- Edited path itself
- Any item that belong the same READY_FOR_LIVE packages as the edited path
- Any in-workflow hard dependency of the edited path

**Comment by yacdaniel** [comment]
Hi @jmendeza please take a look at the next case:

1. Initial publish of a Editorial project
2. Right click an Category page and `Edit Controller` save content in the controller, also Edit the Controller. 
3. Schedule a Publish of the Category page, verify that the controller is selected as dep to schedule. 
4. Edit the Category page or controller, Workflow Cancellation will shown, accept the dialog
5. Notice that workflow state and publish request is cancelled, as expected.
6. Send the same Category page to schedule publish
7. Edit the Category page or controller, Workflow Cancelletion will shown, accept the dialog
8. This time only the item that was edited is with the workflow state updated, the other item stays in Schedule state. 

Video is from a new content, but I notice that it also happens with existing content (steps are from existing content). 

https://github.com/user-attachments/assets/ad1ddd99-2e07-4aba-9294-88e2aad974b2

**Comment by yacdaniel** [comment]
previous issue is happening because of https://github.com/craftercms/craftercms/issues/7490

Closing this one as clompleted. Thanks!
