### ISSUE TITLE
Publishing a content item with shared hard dependencies can break existing publish packages

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7483]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

When scheduling a publish, if hard dependencies are already in the queue, they get updated to the new package.
This can cause items (from the previously submitted package) to be publishing with missing hard dependencies

### Steps to reproduce

Steps:

1. Create a site from editorial blueprint
2. Initial publish
3. Edit two different articles
4. Right click one of the articles and choose 'Edit Controller'
5. Write any comment into the controller groovy.
6. Save
7. Then schedule one of the articles for publishing (**date A**, e.g.: 11/20). Notice article.groovy is a hard dependency
![Screenshot from 2024-11-04 15-16-44](https://github.com/user-attachments/assets/ba64461c-c33f-4afd-8495-285aba3efb96)
8. Query the publish_request table:
```
SELECT site, path, scheduleddate, state, action
FROM crafter.publish_request
where state NOT IN ('CANCELLED', 'COMPLETED')
```
```
'ed107', '/scripts/pages/article.groovy', '2024-11-20 15:16:00', 'READY_FOR_LIVE', 'NEW'
'ed107', '/site/website/articles/2020/12/top-books-for-young-women/index.xml', '2024-11-20 15:16:00', 'READY_FOR_LIVE', 'UPDATE'
```
9. Publish the other article. Schedule for a date in the future of **date A** (e.g.: 11/30). Notice article.groovy is a hard dependency
![Screenshot from 2024-11-04 15-20-49](https://github.com/user-attachments/assets/a8d869b9-ad54-4320-a2da-266abe853a26)

10. Query the publish_request table:
```
SELECT site, path, scheduleddate, state, action
FROM crafter.publish_request
where state NOT IN ('CANCELLED', 'COMPLETED')
```
```
'ed107', '/site/website/articles/2020/12/top-books-for-young-women/index.xml', '2024-11-20 15:16:00', 'READY_FOR_LIVE', 'UPDATE'
'ed107', '/scripts/pages/article.groovy', '2024-11-30 15:20:00', 'READY_FOR_LIVE', 'NEW'
'ed107', '/site/website/articles/2020/6/coffee-is-good-for-your-health/index.xml', '2024-11-30 15:20:00', 'READY_FOR_LIVE', 'UPDATE'

```
11. Notice article.groovy is now scheduled to be published on the 30th. So `top-books-for-young-women` will be published on the 20th without its hard dependency

**Comment by yacdaniel** [comment]
Hi @jmendeza 
While validating this issue I notice that the `api/2/dashboard/publishing/schedule` is broken now, please take a look at the dashboard schedule dashlet after following the steps in the ticket

https://gist.github.com/yacdaniel/d603b6fc118593aa81814e7025f2df24

**Comment by jmendeza** [comment]
Fixed the query to get only one workflow entry per path

**Comment by yacdaniel** [comment]
Verified fixed.
