### ISSUE TITLE
Approving a workflow request does not include its hard dependencies

### ISSUE THREAD

**Issue by jmendeza** [craftercms/craftercms#7484]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

Workflow entries are reviewed individually, allowing content to be published without hard dependencies

### Steps to reproduce

Steps:

1. Create a site from editorial blueprint
2. Initial publish
3. Edit any article
4. Right click the article and choose 'Edit Controller'
5. Write any comment into the controller groovy. Save
6. Request approval to publish the article
7. Go to the Dashboard Pending Approval dashlet
8. Select and approve only the article
![Screenshot from 2024-11-04 16-03-59](https://github.com/user-attachments/assets/06437cb1-1a93-4dce-add4-32ed91f6c452)
9. The article has been published without its hard dependency.

**Comment by yacdaniel** [comment]
Verified fixed.
