### ISSUE TITLE
Change Workflow Cancellation Dialogue

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#7486]
### CI Number

5403

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The wording in the Workflow Cancellation dialogue is unclear to users what will occur when attempting to edit a scheduled item. There is a typo in the wording of the warning, "chose" should be "choose". Also, the items in the scheduled deployment batch are not canceled until an item is successfully saved & closed, simply opening the edit form for an item doesn't cancel the batch.

`Edit will cancel all items that are in the scheduled deployment batch. Please review the list of files below and chose “Continue” to cancel workflow and edit or “Cancel” to remain in your dashboard.`
![image](https://github.com/user-attachments/assets/534f80b3-45f5-4c24-80d8-ae614c19e95f)

### Describe the solution you'd like

The warning language could be updated to make it clear that saving changes and not opening the edit form will cancel the scheduled publishing. Or, have the Workflow Cancellation dialogue pop up once the user clicks save & close on the edit form.

**Comment by sumerjabri** [comment]
@rart please fix the language/typo.

**Comment by sumerjabri** [comment]
We will not cancel the publishing because of an open, only when a file is actually saved. That behavior will not change at this time.

**Comment by rart** [comment]
The language on this dialogue is overly complicated/technical. Also, the dialogue is shown in various places, not just the Dashboard.

I suggest we change to something like:
```
Publish Cancellation Warning
The item is part of a publishing package. Editing it will cancel the entire package.
```

![image](https://github.com/user-attachments/assets/57d8e7c2-8f1c-4e32-b33a-93ba3728b16f)

Note that FE2 does not show this dialog upfront.

**Comment by russdanner** [comment]
Confirmed
