### ISSUE TITLE
[studio-ui] Change the "view" user link

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#751]
Please move the "view" link from the "first name" to be the "username"

See screenshot:
![screen shot 2017-04-24 at 2 07 46 pm](https://cloud.githubusercontent.com/assets/3931908/25351844/e67dc892-28f7-11e7-9bc3-bca930a0156b.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/371
