### ISSUE TITLE
[deployer] Create site in Studio gets stuck on create deployer target

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#752]
1. In the bundle delete `crafter-auth-env/data/deployer/config/targets` folder
2. start authoring environment
3. create a site 

UI is stuck on create site screen with spinner spinning forever
Studio log:
```[INFO] 2017-04-24 20:31:10,674 [http-nio-8080-exec-4] [httpclient.HttpMethodBase] | 100 (continue) read timeout. Resume sending the request```
Deployer log:
```017-04-24 20:32:00.004  WARN 3050 --- [taskScheduler-3] o.c.deployer.impl.TargetServiceImpl      : Config folder <install_folder>/crafter-auth-env/crafter-deployer/../data/deployer/config/targets doesn't exist```

**Comment by avasquez614** [comment]
PR craftercms/deployer#26
