### ISSUE TITLE
[studio] No sites appear for LDAP user

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#753]
Added an LDAP user to the Admin group of a site. When logging in as that user nothing appears under site list. Checking the JS console the following 2 calls appear to be failing with 401 Unauthorized: 

`http://localhost:8080/studio/api/1/services/api/1/security/get-user-permissions.json?path=%2F&site=&user=LDAPUSERNAME`
`http://localhost:8080/studio/api/1/services/api/1/site/get-per-user.json?number=15&start=0&username=LDAPUSERNAME`

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/655
