### ISSUE TITLE
[studio] Studio fails to shutdown cleanly

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#754]
./gradlew -Penv=authoring start
wait for the system to come up
./gradlew -Penv=authoring stop

Tail catalina.out and note how Studio fails to shutdown, there are multiple logs indicating problems:
`26-Apr-2017 09:11:03.264 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [studio] registered the JDBC driver [org.mariadb.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.`

Lots of threads that don't stop, this is an example:
`6-Apr-2017 09:11:03.265 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [studio] appears to have started a thread named [org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] but has failed to stop it.`

The objective is to allow a complete shutdown of Tomcat, right now it stays up.

**Comment by dejan-brkic** [comment]
Done

PR: https://github.com/craftercms/studio/pull/662
