### ISSUE TITLE
Add an option to assign a user to a group in CLI 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#7548]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Currently CLI only supports adding users and groups, there is no option to add a user to a group.  This will help with the setup required by https://github.com/craftersoftware/craftercms/issues/1065 

### Describe the solution you'd like

Create a new API to assign a set of users to a group.

**Comment by Euquimides** [comment]
Hi! Enhancement completed.
