### ISSUE TITLE
[studio] Move components into separate folder and update pickers in Editorial BP

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#760]
In the Editorial Blueprint:
Please create folders under components to signify different component categories. For example:
`/components/headers` <== for header
and so on.

Then move the components into the proper folders so they're isolated from one another.

Then update the pickers in the content types such that the pickers for different components only pick from the correct root folder and the user experience is enhanced.

Ping Alfonso or me for more detail.

**Comment by alhambrav** [comment]
Done.
PR https://github.com/craftercms/studio/pull/705
