### ISSUE TITLE
Improve `sort` in `Shared Content data Source`

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7602]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Shared content data source opens Search features with Sort by Name as the default filter.

### Describe the solution you'd like

- [ ] The default sort should be a property of the data source
- [ ] The default value should be By Relevance

**Comment by rart** [comment]
See https://github.com/craftercms/craftercms/issues/5995

**Comment by sumerjabri** [comment]
Closing and reopening #5995
