### ISSUE TITLE
[studio-ui] Please put cursor on "Folder Name" input box in "Create a New Folder" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#761]
Please put cursor on "Folder Name" input box in "Create a New Folder" dialog

![screen shot 2017-04-28 at 10 02 58 am](https://cloud.githubusercontent.com/assets/25483966/25581789/dbfd1250-2e57-11e7-8bfb-acb923324a60.png)

**Comment by vestrada** [comment]
master - PR: https://github.com/craftercms/studio2-ui/pull/393
