### ISSUE TITLE
[studio-ui] Components have .html in My Recent Activities

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#762]
Component files must have `.xml`
![screen shot 2017-05-01 at 10 22 22 am](https://cloud.githubusercontent.com/assets/3931908/25581857/328e7c9e-2e58-11e7-921e-2c936a5d45ef.png)
 as extension.

**Comment by vestrada** [comment]
Per conversation with Sumer, this is on hold

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/389
