### ISSUE TITLE
[studio] Editorial BP: Switch taxonomy machinery to use new data source

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#763]
Please create the folder `taxonomy` directly under `site` alongside `components` and `website` and add it to the system. I used:

`mkdir taxonomy`
`cd taxonomy`
`cp ../components/configuration-lists/.keep .`
`git add .`
`git commit -m "Manual addition of taxonomy folder."`

Then you need to Sync from Repository in SiteConfig.

Then add the folder to the Sidebar using SiteConfig > Configuration > Site DropDown Configuration
`								<modulehook>
									<name>wcm-root-folder</name>
									<showDivider>true</showDivider>
									<params>
										<label>Taxonomy</label>
										<path>/site/taxonomy</path>
										<showRootItem>true</showRootItem>
									</params>
								</modulehook>`

Once done, you'll need to create the taxonomies for Editorial using the content model:
- repeat group: named `items`
- `key` String
- `value` String

Then you need to go through and add `site-component` Data Source in Site Config: SiteConfig > Configuration > Admin Tools > `<datasources>`

`                <datasource>site-component</datasource>`

and remove

`                <datasource>configured-list</datasource>`

- Create the new taxonomy files under the Taxonomy top level folder.
- Change the content model to use the new picker/taxonomy
- Edit all content items and re-choose all taxonomies
- Test :)

**Comment by sumerjabri** [comment]
Please note: In Editorial BP, there are several configured lists, including: Feature Icons Configured List, Segments Configured List, Categories Configured List.

**Comment by alhambrav** [comment]
Done.  PR craftercms/studio #696

**Comment by alhambrav** [comment]
Cleanup by removing the unused configured lists from the dropdown

**Comment by alhambrav** [comment]
Done. 
craftercms/studio PR#702
