### ISSUE TITLE
[studio-ui] Add ability to change Sidebar items icons

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#766]
Add ability to set two icons (open/closed) per Sidebar item. Icons are sourced by FontAwsome, for example:
http://fontawesome.io/3.2.1/icon/film/

The structure becomes:

```
	<modulehook>
		<name>wcm-root-folder</name>
		<showDivider>true</showDivider>
		<params>
			<label>Components</label>
			<path>/site/components</path>
			<showRootItem>true</showRootItem>
			<module-icon-open>icon-film</module-icon-open>
			<module-icon-closed>icon-film</module-icon-closed>
			<child-icon-open>icon-folder-open</child-icon-open>
			<child-icon-closed>icon-folder-closed</child-icon-closed>
		</params>
	</modulehook>
```

**Comment by jvega-crafter** [comment]
We'll be using latest font-awesome version `http://fontawesome.io/icons/`, for example `http://fontawesome.io/icon/film/`

**Comment by jvega-crafter** [comment]
If user only wants one icon (not open and close state), add only `<module-icon-closed>` or `<child-icon-close>` tag

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/394
