### ISSUE TITLE
[studio-ui] Remove "{site} Dashboard" from Dashboard

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#767]
Remove the `{site} Dashboard` title from the dashboard as shown on the screenshot.
![screen shot 2017-05-01 at 2 52 32 pm](https://cloud.githubusercontent.com/assets/3931908/25595781/1d2bf6a6-2e94-11e7-9ae6-772da467763a.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/386

**Comment by sumerjabri** [comment]
Please remove {site}, Dashboard and the line under them. Basically, remove everything in the red box I have in the screenshot.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/387
