### ISSUE TITLE
[studio] Editorial BP: Add screenshots to content types

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#770]
Update all content types to have a screenshot to help the author see the content type they're about to use or developer when editing a content type.

The screenshot/image for the content type can be anything you'd like that conveys the essence of the type they're about to create. Typically, people take a pretty screenshot of a representative page.

**Comment by alhambrav** [comment]
Done.

PR https://github.com/craftercms/studio/pull/704

**Comment by alhambrav** [comment]
Update the article widget image file

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/705
