### ISSUE TITLE
[studio] All BPs: Rename `site-dropdown` config to become `sidebar`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#771]
`/context-nav/site-dropdown.xml` is the filename currently for the Sidebar configuration file.

We need to change that to the new name `sidebar.xml` and change all references to site-dropdown to become sidebar.

We may also consider renaming the folder `context-nav` to something more meaningful for consistency if it has no impact to other blueprints.

This work needs to be done in Empty and Editorial.

**Comment by sumerjabri** [comment]
`        <file>
            <path>/context-nav/site-dropdown.xml</path>
            <title>confTabSiteDropdownConf</title>
            <description>confTabSiteDropdownConfDesc</description>
            <samplePath>/administration/samples/sample-site-dropdown.xml</samplePath>
        </file>`

This is configured in `SiteConfig` > `Configuration` > `AdminTools`

**Comment by alhambrav** [comment]
Done. 
craftercms/studio PR 697
craftercms/studio2-ui PR 404
