### ISSUE TITLE
[studio-ui] "Pages" Sidebar item doesn't show root

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#774]
Please fix the "Pages" Sidebar item to show root item if it's configured to show the root item.

```
<modulehook>
	<name>wcm-root-folder</name>
	<showDivider>true</showDivider>
	<params>
		<label>Pages</label>
		<path>/site/website</path>
		<showRootItem>true</showRootItem>
		<onClick>preview</onClick>
	</params>
</modulehook>
```

Note that in the example above we're asking to show the root item, but it's not.

Please ping me to show me the fix before sending a PR so we can agree on the experience.

**Comment by vestrada** [comment]
Per conversation with Sumer, this is on hold

**Comment by rart** [comment]
Already done.
