### ISSUE TITLE
[studio] dependency query uses improper case on table name and gets table does not exist error

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#778]
# Error in logs
```
Cause: java.sql.SQLSyntaxErrorException: (conn:12) Table 'crafter.cstudio_DEPENDENCY' doesn't exist
Query is: SELECT site, source_path, target_path, type
        FROM cstudio_DEPENDENCY
        WHERE target_path = ? AND site = ?, parameters ['/static-assets/images/compressed/deal/organizations/Pic-compressed.png','SITENAME']
### The error may exist in org/craftercms/studio/api/v1/dal/DependencyMapper.xml
```

# Query built by mapper is (which fails)
`SELECT site, source_path, target_path, type FROM crafter.cstudio_DEPENDENCY WHERE target_path = '/static-assets/images/compressed/deal/organizations/Pic-compressed.png' AND site = 'SITEID';`

# The same query works with a lower cased table name (because all tables have lower case names in database)
`SELECT site, source_path, target_path, type FROM crafter.cstudio_dependency WHERE target_path = '/static-assets/images/compressed/deal/organizations/Pic-compressed.png' AND site = 'SITEID';`

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/669

**Comment by sumerjabri** [comment]
@russdanner please validate.
