### ISSUE TITLE
[studio] Delete `studio-server-config.properties`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#780]
Please switch everything to the Yaml config and delete the old configuration files.

If there are other lingering configuration files, please identify and delete.

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/674

Still some clean up needed

**Comment by dejan-brkic** [comment]
Cleaned up
PR
https://github.com/craftercms/studio/pull/676
