### ISSUE TITLE
[studio-ui] Fix login calls to match the new REST Login API

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#781]
Calls from the UI to login should match the new Login API for Studio, found in /developers/projects/studio/api/security/login.html. The UI also has to display a `Invalid username or password` when 401 is returned and a generic error message like `A system error has occurred. Please wait a few minutes or contact and administrator` when 500 is returned.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/390
