### ISSUE TITLE
[studio-ui] Fix logout calls to match the new REST Logout API

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#782]
Calls from the UI to logout should match the new Logout API for Studio, found in /developers/projects/studio/api/security/logout.html.

**Comment by sumerjabri** [comment]
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/security/logout.html

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/390
