### ISSUE TITLE
[studio] Setting admin permissions through the Permissions Mapping Config file does not work

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#783]
1. Go to Site Config -> Configuration -> Permissions Mapping
2. Go to the admin role section and remove one of the permissions, say Create Folder
     Here's the config I have for admin with Publish permission removed:

```xml  
  <role name="admin">
      <rule regex="/.*">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
         <permission>Publish</permission>
          <permission>Delete</permission>          
          <permission>Create Content</permission>
          <permission>Change Content Type</permission>
        </allowed-permissions>
      </rule>
      
      <rule regex="~DASHBOARD~">
        <allowed-permissions>
          <permission>Read</permission>
          <permission>Write</permission>
          <permission>Delete</permission>
          <permission>Publish</permission>
        </allowed-permissions>
      </rule>
    </role>
```

3. Save the config file and click on Clear Cache
4. Right click on any Page in the sidebar, say Home, notice that 
"New Folder" still appears in the context menu

![screen shot 2017-05-04 at 2 48 34 pm](https://cloud.githubusercontent.com/assets/25483966/25719863/e073ca26-30d8-11e7-8d86-4be445fdb21f.png)

**Comment by dejan-brkic** [comment]
Can not reproduce.

Possible reason:
If using default admin, it is member of crafter-admin group which by default has all permission on all sites (including create folder). That is reason why "New Folder" is showing up.

Better use case is to create new user and add it to the site as admin. Than try to replicate issue and you will get expected behavior.

**Comment by alhambrav** [comment]
Yes, the user logged in for the issue listed above is the default admin.  Makes sense now.  Verified that the issue is not present when a new user is created and added to the site as admin.
