### ISSUE TITLE
[Studio] Studio allows to delete the user currently connected.

### ISSUE THREAD

**Issue by gortizcraftersoftware** [craftercms/craftercms#784]
Steps:
1. Create a user with the role admin.
2. Login with the user recently created.
3. Go to User tab
4. Delete the user currently connected.

Current behavior
Studio allows to delete the user currently connected.

Expected behavior
When the this user is deleted studio is crash, never should delete the user current connected.

**Comment by sumerjabri** [comment]
Duplicate of https://github.com/craftercms/craftercms/issues/626
