### ISSUE TITLE
[craftercms] Delivery environment is created with the wrong configuration

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#788]
When using the command `./gradlew deploy -Penv=delivery` the files in `apache-tomcat/shared/classes/crafter/engine/extension/` have the same values as authoring environment:

In server-config.properties:
```crafter.engine.site.default.rootFolder.path=file:./data/repos/sites/{siteName}/sandbox/```

In rendering-context.xml:
```<import resource="classpath*:crafter/engine/mode/preview/rendering-context.xml" />```

In services-context.xml:
```<import resource="classpath*:crafter/engine/mode/preview/services-context.xml" />```

**Comment by cortiz** [comment]
Fixed on PR #798
