### ISSUE TITLE
[studio] Switch to Notification Service 2 and remove the old

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#789]
Enable notification service 2 (@cortiz can help you find out how) and delete the old notification service and associated artifacts including the configurations.

Ping me if you need help.

**Comment by sumerjabri** [comment]
All that's left is testing that it works after the refactor. All yours @dejan-brkic!

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/680
