### ISSUE TITLE
CRAFTERCMS-1950: Add time zone picker to scheduling dialogs

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#79]
Original JIRA Fix Versions:
2.5.2, 2.5.1.1, Original JIRA Components:
Studio-Tests, 
----------
Original JIRA Description: Provide user with timezone picker (defaulted to the site's configured timezone) 

User can set time in their own timezone if they want but this helps them understand what time zone they are working in by default.

Make sure that time API is called with timezone value so that date time is stored properly in the backend as Zulu time.:
----------
Original JIRA Comments:
Original JIRA:
http://issues.craftercms.org/browse/CRAFTERCMS-1950
----------

**Comment by vestrada** [comment]
Closed
