### ISSUE TITLE
[studio] Change RTE configuration for subscripts and superscripts to sup and sub in all blueprints

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#790]
# current config (wrong)
<toolbarItems1>formatselect,styleselect,|,bold,italic,subscript,superscript,|outdent,indent,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,managedImage,link,unlink,anchor,|,insertLayout,channelSelect,insertComponent,|,code,|,undo,redo</toolbarItems1>

# correct config
 <toolbarItems1>formatselect,styleselect,|,bold,italic,sub,sup,|,outdent,indent,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,managedImage,link,unlink,anchor,|,insertLayout,channelSelect,insertComponent,|,code,|,undo,redo</toolbarItems1>

# also 
There is a missing , before outdent

**Comment by alhambrav** [comment]
Website_Editorial bp current config already has the corrections for superscript and subscript and the missing comma.  Here's the config for the toolbar from the RTE configurations in Studio(Site-Config-> Configurations -> RTE Configuration):

<toolbarItems1>formatselect,|,bold,italic,underline,strikethrough,|,sub,sup,|,outdent,indent,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,managedImage,link,unlink,anchor,|,code,|,undo,redo</toolbarItems1>


Empty bp current config already has the corrections for superscript and subscript and the missing comma.  Here's the config for the toolbar from the RTE configurations in Studio(Site-Config-> Configurations -> RTE Configuration):

<toolbarItems1>formatselect,|,bold,italic,underline,strikethrough,|,sub,sup,charmap,|,outdent,indent,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,managedImage,link,unlink,anchor,|,code,|,undo,redo</toolbarItems1>

Is there any other place that I need to update the rte config files?

**Comment by alhambrav** [comment]
As mentioned in my comment above, the current empty and website_editorial blueprints already has the superscript, subscript and missing comma fixed, from a previous clean up of the rte toolbar.
