### ISSUE TITLE
[studio-ui] Charmap plugin on RTE is not usable due to background/font color pair

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#791]
# To add char map: 
Add: ,charmap, in RTE toolbaritems1
 `<toolbarItems1>formatselect,styleselect,|,bold,italic,sub,sup,charmap,|,strikethrough,outdent,indent,blockquote,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,managedImage,link,unlink,anchor,|,insertLayout,channelSelect,insertComponent,|,code,|,undo,redo</toolbarItems1>`

# Note the tool in the toolbar
<img width="1420" alt="screen shot 2017-05-05 at 2 36 48 pm" src="https://cloud.githubusercontent.com/assets/169432/25759473/b0232f92-31a0-11e7-9200-4e0a7bdb338e.png">

# Unusable panel due to background/font color pair
<img width="1431" alt="screen shot 2017-05-05 at 2 36 51 pm" 
src="https://cloud.githubusercontent.com/assets/169432/25759505/d1a37abe-31a0-11e7-9b02-546b4e424375.png">

Update font color to be visible on panel

**Comment by russdanner** [comment]
The issue applies to a 2.5 install but applies to 3.x code base as well

**Comment by alhambrav** [comment]
studio2-ui PR 392 and studio PR 683
