### ISSUE TITLE
[studio] Empty blueprint does not have /site/components folder.

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#794]
Empty blueprint does not have /site/components folder so Users can not create components unless the folder is manually added. To fix this add a `.keep` file to each empty folder so git can keep a track of it  (remember to add the `.keep` file in git ) currently `/site/components/` is also missing from Studio main repo.

**Comment by sumerjabri** [comment]
Please update and send a PR. If too busy, let me know and I'll try to route elsewhere.

**Comment by cortiz** [comment]
Solve on https://github.com/craftercms/studio/pull/681
