### ISSUE TITLE
[studio] Preview Deployer Request should escape all unsafe chars like `\` 

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#795]
I'm unable to create a new site on windows since the request that Studio make's to preview deployer contains a invalid char in the request.
Here's an example:
```
"{ "env":"preview", "site_name":"we", "replace":true, "disable_deploy_cron":true, "template_name":"local", "repo_url":"C:\Users\cortiz\Documents\craftercms\crafter-auth-env\data\repos\sites\we\sandbox", "engine_url":"http://localhost:8666" }"
```
The invalid char is `\` , when deployer parse the `repo_url` it will try to find the escape char `\U` from `C:\U` which does not exist and throws a Json Parse exception 

``` 
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'U' (code 85)
 at [Source: java.io.PushbackInputStream@79f4702c; line: 1, column: 123]
```

When generating json string we should check and escape chars like:
```
 \"
           \\
           \/
           \b
           \f
           \n
           \r
           \t```

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/682
