### ISSUE TITLE
[studio] order of publishing channels is not respected

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#797]
Studio UI does not render the list of environments in the order listed or provide a way to configure order.  Configuration should control the order of environments in the user experience as this implies/communicates workflow to the user.
 
<img width="578" alt="order-not-respected" src="https://cloud.githubusercontent.com/assets/169432/25853529/1850ca0a-349b-11e7-9177-74037822c037.png">

**Comment by sumerjabri** [comment]
Please make the order of items in the UI the same as the order of items in the configuration.

**Comment by sumerjabri** [comment]
@dejan-brkic the backend needs to return the JSON in the order it was defined in config.

**Comment by russdanner** [comment]
# Additional notes:
List of channels comes from service call:
/studio/api/1/services/api/1/deployment/get-available-publishing-channels.json?site=SITEID

# Response
Each channel in the response contains an "order" value that is the same for all items and is a very large number.
`{"availableUpdateStatusChannels":[],"availablePublishChannels":[{"name":"QA","publish":true,"updateStatus":false,"order":2147483647},{"name":"Production","publish":false,"updateStatus":false,"order":2147483647}]}`

I do not know what "order" field in the response is used/intended for.  
If the intention is for the UI to sort based on the order: Not sure what value there is in returning the order to the UI for the UI to perform a sort.  Shouldn't the server just return the channels in the order as listed?

**Comment by dejan-brkic** [comment]
Publishing channels order is already implemented. Configuration should look like this:
```<publishing-channels>
        <channel-group>
            <label>Production</label>
            <channels>
                <channel>sample</channel>
            </channels>
           <order>1</order>
            <live-environment>true</live-environment>
        </channel-group>
        <channel-group>
            <label>Test</label>
            <channels>
                <channel>sample</channel>
            </channels>
            <order>2</order>
            <live-environment>false</live-environment>
        </channel-group>
    </publishing-channels>```

**Comment by russdanner** [comment]
Dejan, do you know what version this applies to?  I applied that config to a older 2.5 version and it had no effect.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/685
