### ISSUE TITLE
[studio] bulk rename operation fails due to incorrect function name

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#799]
1) go to admin console
2) go to bulk operations (enable this feature from the configuration if not already enabled)
3) enter source path and target path to rename

The service call fails due to the following reason:

in ContentService.java it's defined as 

`    boolean renameBulk(String var1, String var2, String var3, boolean var4);
`

while in SpringContentServices.groovy it calls 

`      def bulkRename(site, srcPath, targetPath, createFolder) {
        def springBackendService = this.context.applicationContext.get(CONTENT_SERVICES_BEAN);
        return springBackendService.bulkRename(site, srcPath, targetPath, createFolder);
    }
`

This issue in in 2.5.x

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/686
