### ISSUE TITLE
[studio] Sidebar not work on safari.

### ISSUE THREAD

**Issue by gortizcraftersoftware** [craftercms/craftercms#800]
1. Log In to crafter3(use safari browser).
2. Click on "sidebar" option.

Current Behavior
The sidebar not hide

video: https://www.useloom.com/share/701d88d84ab14089971689762c1d9771

Expected Behavior
The sidebar should hide properly.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/399
