### ISSUE TITLE
[studio] Disable Page Components Editing in  Preview Tools when the user is Reviewer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#801]
Log in as a Reviewer to Studio
Open the Preview Tools Panel by clicking on the wrench at the top
Click on Page Components
Notice that the user is able to drag and drop components into the features section of the page.  Please disable the Page Components in the Preview Tools Panel when the user is Reviewer.

![screen shot 2017-05-10 at 10 59 03 am](https://cloud.githubusercontent.com/assets/25483966/25905468/1ce958b8-3570-11e7-9238-000912c0d7d7.png)

**Comment by jvega-crafter** [comment]
"Page Components" now won't render if user is reviewer, according to discussion with Vita

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/401
