### ISSUE TITLE
[studio] Creating a duplicate user does not display a message in Studio of the request status

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#802]
It would be nice to display a notification that the request to create a user failed because the username (in this case) is a duplicate instead of no message at all on what happened.

1. Create a new user in Studio
2. Create another user with the same user name as the one created earlier
3. Nothing happens in Studio after clicking the "Save" button.

![screen shot 2017-05-10 at 4 04 39 pm](https://cloud.githubusercontent.com/assets/25483966/25919075/82cb787a-359b-11e7-922c-7ec09e5c7e70.png)

4. Check the catalina logs, the error is logged. 
```
[ERROR] 2017-05-10 14:54:10,707 [http-nio-8080-exec-5] [security.DbSecurityProvider] | Error creating group Anonymous
org.springframework.dao.DuplicateKeyException:
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:9) Duplicate entry 'Anonymous-2' for key 'uq_group_name_siteid'
Query is: INSERT INTO cstudio_group (name, description, site_id)
        VALUES (?, ?, ?), parameters ['Anonymous','Test anonymous dupe',2]
### The error may involve org.craftercms.studio.api.v1.dal.SecurityMapper.createGroup-Inline
### The error occurred while setting parameters
```

**Comment by dejan-brkic** [comment]
Added code to avoid DB exception

PR:
https://github.com/craftercms/studio/pull/688

**Comment by dejan-brkic** [comment]
There is a UI issues. It does not handle status 409 and message (as described in API) http://docs.craftercms.org/en/3.0/developers/projects/studio/api/user-management/create-user.html

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/402
