### ISSUE TITLE
[studio] Quality: Close Resources

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#803]
https://sonarqube.com/issues#issues=AVvqQaK7tgcYCvBl4x0y
https://sonarqube.com/issues#issues=AVm3Kh9UYbr9ugKeqG7t
https://sonarqube.com/issues#issues=AVjgdsMmbWj_GMDPWRyw
https://sonarqube.com/issues#issues=AVjM3m8jihRi3sRitk96
https://sonarqube.com/issues#issues=AVjM3m8kihRi3sRitk97
https://sonarqube.com/issues#issues=AVjM3nAPihRi3sRitlEo
https://sonarqube.com/issues#issues=AVjM3nAWihRi3sRitlFF

**Comment by dejan-brkic** [comment]
Done except https://sonarqube.com/issues#issues=AVjgdsMmbWj_GMDPWRyw (we can not close git repository because it is cached)

PR:
https://github.com/craftercms/studio/pull/690
