### ISSUE TITLE
[studio] Quality: EmailMessageSender.java, StudioSchedulerFactoryBean.java

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#808]
https://sonarqube.com/issues#issues=AVuxNGxU2tKHZcedhMD5
https://sonarqube.com/issues#issues=AVuxNGvg2tKHZcedhMD2

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/695
