### ISSUE TITLE
[studio] Quality: StudioGroupAPIAccessDecisionVoter.java, StudioUserAPIAccessDecisionVoter.java, SiteServiceImpl.java

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#809]
https://sonarqube.com/issues#issues=AVuSuwk5tpYg8Dj42fyq
https://sonarqube.com/issues#issues=AVuSuwk5tpYg8Dj42fyp
https://sonarqube.com/issues#issues=AVuSuwkvtpYg8Dj42fyU
https://sonarqube.com/issues#issues=AVuM5-L9tpYg8Dj42LoA

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/695
