### ISSUE TITLE
[studio] Creating a duplicate group does not display a message in Studio of the request status

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#812]
It would be nice to display a message/notification in studio that the request to create a new group failed because it is a duplicate instead of no message at all on what happend.

1. Create a new group in Studio
2. Create another group with the same name as the one created earlier
3. Nothing happens in Studio after clicking the "Create" button.

<img width="1155" alt="screen shot 2017-05-11 at 6 25 19 am" src="https://cloud.githubusercontent.com/assets/25483966/25944987/3ed8035e-3613-11e7-8b21-288558519a2e.png">

4. Check the catalina logs the error is logged there:
```
[ERROR] 2017-05-11 06:23:34,442 [http-nio-8080-exec-4] [security.DbSecurityProvider] | Error creating group Anonymous
org.springframework.dao.DuplicateKeyException:
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:16) Duplicate entry 'Anonymous-2' for key 'uq_group_name_siteid'
Query is: INSERT INTO cstudio_group (name, description, site_id)
```

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/402
