### ISSUE TITLE
[studio] Implement monitoring API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#813]
Please implement the monitoring APIs listed below and use the Commons/Monitoring libraries developed by Carlos for this (ping him for help).

Implement the APIs in deployer as specified here:
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/version.html
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/status.html
-- http://docs.craftercms.org/en/3.0/developers/projects/studio/api/monitor/memory.html

**Comment by cortiz** [comment]
@dejan-brkic Heres how it's done in Deployer https://github.com/craftercms/deployer/blob/master/src/main/java/org/craftercms/deployer/impl/rest/MonitorController.java

 should be straight forward.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/688
