### ISSUE TITLE
[studio] removes <paths> from Content Type's config.xml

### ISSUE THREAD

**Issue by efaj** [craftercms/craftercms#815]
Version: Crafter 3

**Issue** Studio removes the `<paths>` element (which contains `<includes|excludes>`) from the type's config.xml when a content type is edited. 

**Steps to reproduce**

1. Have a Page/Component with `<paths>` configuration within it's config.xml, similar to:
```
<paths> 
	<excludes>
		<pattern>^/.*</pattern> 
	</excludes>
</paths>

```

2. Make a change to the Content Type using Studio (for example, change page/component's title).

3. Check the config, `<paths>` won't be there and the page/component will no longer be path restricted.

**Expected result** That Studio doesn't delete the `<paths>` config

**Comment by alhambrav** [comment]
Here's the steps I did to reproduce:

1. Click on  Site Config -> Content Types -> Open Existing Type -> (Select a component or page).  For this example, I selected the content type taxonomy

2. In the properties explorer of the content type, scroll down to **Configuration** and click on the pencil icon next to "config.xml" to edit

![screen shot 2017-05-12 at 1 42 05 pm](https://cloud.githubusercontent.com/assets/25483966/26010271/45510264-371a-11e7-937e-e4a550656533.png)

3. Add the tag <path> to the config.xml and click on **Update**

![screen shot 2017-05-12 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/25483966/26010319/71554dac-371a-11e7-91bd-ecebae38ccb5.png)

4.  Once you're back to the content type dialog, click on **Save**

![screen shot 2017-05-12 at 1 46 49 pm](https://cloud.githubusercontent.com/assets/25483966/26010345/8c36d168-371a-11e7-9c0b-f4c1f7d02b1a.png)

5. Now, go back to the Properties Explorer panel, **Configuration** property and click on the pencil icon next to config.xml again to view the file.  Notice that the changes you saved earlier is gone.

![screen shot 2017-05-12 at 1 47 44 pm](https://cloud.githubusercontent.com/assets/25483966/26010381/b081a30e-371a-11e7-9eea-646011c39c25.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/407
