### ISSUE TITLE
[studio-ui] Please put cursor on "Display Name" input box in "Create Group" dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#816]
Please put cursor on "Display Name" input box  when "Create Group" dialog loads and Trigger "Create" button click when the "Enter" key is pressed.

![screen shot 2017-05-12 at 2 39 06 pm](https://cloud.githubusercontent.com/assets/25483966/26012241/e63603f8-3721-11e7-9a11-3d2fdccaff4e.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/409
