### ISSUE TITLE
[studio] Renaming a datasource causes the field to disappear from the form

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#817]
In Crafter 3.0 (probably all versions)

If you change the name for a datasource and then update the field to select the datasource the previous name is stored in the XML and when the form is rendered the field is missing.

```
<property>
  <name>datasource</name>
  <value>categories,categories_1</value>
  <type>datasource:item</type>
</property>
```

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/411

**Comment by sumerjabri** [comment]
@jdrossl Please test. If it passes your test, please close and move to "Completed."

**Comment by jdrossl** [comment]
The test was successful.
