### ISSUE TITLE
[craftercms] Create a script to setup everything for a site in delivery

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#822]
Create a bash script for a delivery bundle that will:

1. Create a Solr index.
2. Create a Deployer target.

The script will receive the environment, the name of the site, and the path to the Git repository where the published site content will be pulled from (by default crafter-auth-env/data/repos/sites/{sitename}/published).

**Comment by avasquez614** [comment]
@jdrossl I made some changes, try it and let me know if it works.

**Comment by jdrossl** [comment]
Verified, publishing to live is working with the default configs in the bundle.
