### ISSUE TITLE
[studio-ui] Cannot delete preview image of content type

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#828]
1. Go to Site Config -> Content Types then open an existing type
2. Go to the Properties Explorer of the content type and click on Form Basics -> Preview Image

![screen shot 2017-05-17 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/25483966/26170991/5fd3aa92-3b11-11e7-9088-01b5e55f849b.png)

Notice that you can add an image or replace the image already there by uploading an image(by clicking on the blue icon) but you cannot delete the image (unless you go to the xml file and remove it there I guess)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/414
