### ISSUE TITLE
[studio-ui] Make it possible for form controls/data source to display an icon in content editor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#830]
<img width="1224" alt="screen shot 2017-05-17 at 4 37 07 pm" src="https://cloud.githubusercontent.com/assets/169432/26175038/482aa4c8-3b1f-11e7-8186-6d83f687db06.png">

Having a unique icon associated with each control/data source would help the usability of the content type creation tool

# Example from NetBeans
![netbeans example](https://cloud.githubusercontent.com/assets/169432/26175104/8b2bba28-3b1f-11e7-9a84-33c2a1d9cac9.png)

**Comment by sumerjabri** [comment]
Replaced by this ticket: https://github.com/craftercms/craftercms/issues/868 in version 3.0. We will use FontAwesome + color.
