### ISSUE TITLE
[studio-ui] Page Components panel and Preview Tools Wrench get confused

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#831]
When page components panel is out and user turns on and off the wrench, the page components panel should hide and show.  Currently, the preview tools panel pushes out on the right.

See video.  
https://www.screencast.com/t/C23GInjCAhS

Note there was a previous bug for this but the issue does not seem to be completely resolved.

# Steps to Reproduce
1. open preview tools with wrench
2. open page components tool
3. click the wrench (page components should hide but does not), wrench now disabled
4. click the wrench (page components should show) preview tools panel pushes out rather that just showing page components.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/415
