### ISSUE TITLE
[studio]  Editing any component/mandatory publish dependency of an inflight workflow cancels only direct descendants

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#832]
Editing any component/mandatory publish dependency of an in-flight workflow cancels only direct descendants.

https://www.screencast.com/t/ZoyPvLFrGdqB

**Comment by russdanner** [comment]
Ignore the comment about why are items being calculated as new/unpublished.  That is correct, they are new.

**Comment by sumerjabri** [comment]
Will address as part of the new workflow engine/mechanics. Let's add to the product roadmap as a goal.
