### ISSUE TITLE
[studio-ui] Menu for adding component to form does not go away

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#834]
1. From the **Sidebar**, right click on one of the left-rails component and click on **Edit**

2. Click on the **Add** button to browse for existing components, notice the menu that appears below the **Add** button after clicking on it. 

![screen shot 2017-05-22 at 10 34 31 am](https://cloud.githubusercontent.com/assets/25483966/26313976/7ffab122-3eda-11e7-9515-2eeda66a2d6b.png)

3. Click on **Browse for Existing - Components**, then either select a component or cancel it.  

![screen shot 2017-05-22 at 10 42 18 am](https://cloud.githubusercontent.com/assets/25483966/26314351/b74486f2-3edb-11e7-9917-c1586564854f.png)

4. Notice that the menu below the **Add** button does not go away.

![screen shot 2017-05-22 at 10 34 49 am](https://cloud.githubusercontent.com/assets/25483966/26314203/3b2e1074-3edb-11e7-831a-e8e12c3dc869.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/417
