### ISSUE TITLE
[studio-ui] Build CMIS data source

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#836]
Please build CMIS Data Source:
`CMIS Content`

The data source allow the user to browse a CMIS repository looking for assets. This data source will use the configuration file located: `/config/studio/cmis/cmis-config.xml` please review that config.

**The data source remembers the last location the user browsed, and will always start there when they're first invoked.**

The data source can be configured to be (1) content reference or (2) content clone.

Once the user selects an item, the first mode returns a URL to the CMIS repository to that asset, whereas the second mode will download the asset from the CMIS repository and place it in Crafter CMS as it would with a `Image Upload`.

The reference URL will be constructed using the configuration `download-url-regex` where the `{item_id}` will be replaced with the actual item id.

Please use the APIs:
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/list.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/search.html

The Data Source should allow the user to browse or search a CMIS repository using the above APIs.

Please reach out to me with any questions and make sure to review the configuration file that will be in all blueprints shortly.

**Comment by sumerjabri** [comment]
New API to help with Clone: https://github.com/craftercms/craftercms/issues/1122

**Comment by sumerjabri** [comment]
@russdanner please test and validate.

**Comment by russdanner** [comment]
# Bug
If you point the data source to an empty folder and then click on that folder in the tree on the left it throws an error

# Issues
Data sources have basic types ITEM, IMAGE, VIDEO.  We need a CMIS Datasource for each type.  This is simple to address.  Change the current data source to a base class, create 3 sub classes and override the type property only.

# Other feedback
- Names of data sources (across all data sources) in the form builder are not consistent.  Repo, Repository, repository.  Also, sometimes repository means local, sometimes it means remote.  
- The clone or link functionality works well but I think we should also add a property to the data source where you decide if you want to allow both, only clones or only links.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/533 - Empty root folder bug

**Comment by russdanner** [comment]
Verified error message issue
