### ISSUE TITLE
[studio-ui] Rename `Site Config` configuration item to `Site Config Tools`

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#837]
Please rename the configuration file and menu item `Site Config` to `Site Config Tools`.

Please do this in _all_ blueprints. These are: empty, editorial, headless_blog, headless_store.

Please see screenshot for the config file in question.
![screen shot 2017-05-22 at 3 21 43 pm](https://cloud.githubusercontent.com/assets/3931908/26324860/8ded402e-3f02-11e7-9b87-70fbbc6c39ec.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/418
