### ISSUE TITLE
[studio] Don't publish a dependency if it's in a live state

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#839]
Please update the publishing code to not force publish a dependency if:
1. the dependency is already live (has been published at least once) and whether it is currently edited or not doesn't matter
2. the dependency is NOT a page-specific dependency

This is required in both 3.x and 2.5.x.

Please ping me or Russ if you need more detail or to discuss.

**Comment by dejan-brkic** [comment]
Done

PR:
2.5.x https://github.com/craftercms/studio/pull/709
master https://github.com/craftercms/studio/pull/710

**Comment by sumerjabri** [comment]
Please test and comment based on finding. Close if fixed.

**Comment by russdanner** [comment]
Verified
