### ISSUE TITLE
[docs] Update REST API documentation for several project

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#841]
Update APIs documentation for the following:

- Core
- Engine
- Profile
- Search

**Comment by alhambrav** [comment]
Please place the updated APIs here:

source/developers/projects/core/api/index.rst
source/developers/projects/engine/api/index.rst
source/developers/projects/profile/api/index.rst
source/developers/projects/search/api/index.rst

**Comment by sumerjabri** [comment]
@avasquez614 Please validate. If all is good, please close and put in state "Completed."

**Comment by avasquez614** [comment]
* Fix profile/change_password.rst example.
* POST parameters shouldn't be part of the URL. They should be presented as part of the request body.
