### ISSUE TITLE
[studio-ui] Make Dashboard and SiteConfig Sidebar items configurable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#848]
Please make Dashboard and SiteConfig Sidebar items configurable in Sidebar Config XML file much like we do for Pages/Components and so on.

Please ensure they also have FA icons that can be specified to help drive them. For these items, they are `links` and as such have a single icon.

Perhaps we do it as a new modulehook that's of type link and that has a single icon.

**Comment by jvega-crafter** [comment]
Done, configuration is the same as the config for pages/components/etc. Using `icon` tag

For example:

`<modulehook>
	<name>site-selector</name>
        <params>
		<icon>fa-bars</icon>
	</params>
</modulehook>`

Icons from http://fontawesome.io/icons/

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/419

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio/pull/714
