### ISSUE TITLE
[docs] Update APIs and Configuration documentation for Crafter Social

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#849]
Add/Update documentation on:

How to configure Crafter Social  here:
    source/developers/projects/social/index.rst

ReST APIs here:
    source/developers/projects/social/api/index.rst

**Comment by sumerjabri** [comment]
Please follow this as a template: http://docs.craftercms.org/en/3.0/developers/projects/studio/api/security/login.html

**Comment by jdrossl** [comment]
Configuration will be covered in craftercms/craftercms#1091

**Comment by alhambrav** [comment]
Verified.
