### ISSUE TITLE
[studio] dependencies are not deployed after move

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#855]
# steps to reproduce
1. create a page with a component or template dependency (never published)
2. move the page to a new location
3. publish the page
4. note that the dependency is not calculated/deployed with the item

**Comment by sumerjabri** [comment]
@russdanner is this 2.5 and 3.0 or 3.0 only?

@dejan-brkic we can discuss the approach so we can agree on a path even for 4.0.

**Comment by russdanner** [comment]
This one exists in both per my testing.  I think it's just a database update that is missing.

**Comment by dejan-brkic** [comment]
Done

PR:
2.5.x https://github.com/craftercms/studio/pull/717
master https://github.com/craftercms/studio/pull/718

**Comment by sumerjabri** [comment]
Please test and comment based on tests. Close if fixed.

**Comment by russdanner** [comment]
verified
