### ISSUE TITLE
[studio-ui] Add a "Cancel" button in the RTE link/unlink dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#858]
It would be nice to have a "Cancel" button in the RTE "insert/edit link" dialog to get out of the dialog instead of clicking on the white part of the form.

1. In the Empty or Website_Editorial bp, click on an RTE, then highlight a word and click on the "Insert/Edit Link" button on the toolbar

![screen shot 2017-05-24 at 11 16 13 am](https://cloud.githubusercontent.com/assets/25483966/26410969/b3ec57d0-4072-11e7-9002-2dd21306ed46.png)

2. Notice the **Insert** button but no **Cancel** button to get out of there if you change your mind.  To get out of the "Insert/Edit Link" dialog, I clicked on the white part in the form.

![screen shot 2017-05-24 at 11 07 53 am](https://cloud.githubusercontent.com/assets/25483966/26410665/f13a0d68-4071-11e7-98ce-55b6f77a5536.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/423
