### ISSUE TITLE
[studio-ui] Update base path for configurations in Site Config

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#859]
Please update the base-path for all configurations to be read from `/config` instead of `/config/studio`.

The reason for this is to allow us to add new types of config for Engine that will live in `/config/engine` as an example.

After updating the base path in the code/config, you'll need to update all blueprints (4 of them) to use the new path, for example:

```
        <file>
            <path>/administration/config-list.xml</path>
            <title>confTabConfigurations</title>
            <description>confTabConfDesc</description>
            <samplePath>/administration/samples/sample-config-list.xml</samplePath>
        </file>```

becomes

```
        <file>
            <path>/studio/administration/config-list.xml</path>
            <title>confTabConfigurations</title>
            <description>confTabConfDesc</description>
            <samplePath>/studio/administration/samples/sample-config-list.xml</samplePath>
        </file>```

Ping me if you have any questions.

**Comment by vestrada** [comment]
Studio - PR: https://github.com/craftercms/studio/pull/715
studio-ui - PR: https://github.com/craftercms/studio2-ui/pull/422
