### ISSUE TITLE
[studio-ui] Add "Save/Cancel" buttons in the RTE image editor dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#861]
It would be nice to have a "Save/Cancel" button in the RTE image editor dialog.  To exit the dialog, I clicked outside of the form.

In the Empty or Website_Editorial bp, go to an RTE and insert an image.  Double click on the image to open the image editor dialog.  Notice that there are no buttons to save or cancel changes made in the dialog or to just exit the dialog if you change your mind about editing.

![screen shot 2017-05-24 at 11 27 41 am](https://cloud.githubusercontent.com/assets/25483966/26412595/46ae2a72-4077-11e7-996f-d3a7a377093a.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/530

**Comment by alhambrav** [comment]
Verified fixed.
