### ISSUE TITLE
[studio] Implement CMIS APIs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#862]
Please implement the APIs:
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/list.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/cmis/search.html

Please note the configuration file for CMIS which helps you resolve the CMIS repo ID is called `cmis-config.xml` and lives under `/config/studio/data-sources/cmis-config.xml`.

The `cmis-config.xml` will be added to all blueprints shortly.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/727
