### ISSUE TITLE
[studio-ui] Add Cancel button to the RTE Edit HTML Source dialog

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#863]
It would be nice to have a **Cancel** button in the  RTE Edit HTML Source dialog.  

To reproduce:
1. In Empty or Website_Editorial bp, go to an RTE and click on the **Edit HTML Source** button on the RTE toolbar

![screen shot 2017-05-24 at 11 54 42 am](https://cloud.githubusercontent.com/assets/25483966/26413373/d37ae038-4079-11e7-9afe-f82ec296958e.png)

2. In the dialog that loads, notice that there is no **Cancel** button.  If you used the Empty bp, notice that you may not see the **Update** button since the dialog is small... Just expand the dialog down to see the **Update** button or click on the small icon at the top right of the dialog.  Again, notice there is no **Cancel** button there if you change your mind.

![screen shot 2017-05-24 at 12 10 29 pm](https://cloud.githubusercontent.com/assets/25483966/26413649/9dbf2ee4-407a-11e7-9ce3-d58ef2829557.png)

**Comment by jvega-crafter** [comment]
According to conversation to Sumer, we will use the plugin we used before, not as a modal but as another view, that can be toggled clicking the "</>" icon.
Documentation should be updated 

<img width="1511" alt="screen shot 2017-05-25 at 12 29 20 pm" src="https://cloud.githubusercontent.com/assets/18267471/26464693/eb442216-4145-11e7-8348-b3a0c10a5566.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/424
https://github.com/craftercms/studio/pull/719
