### ISSUE TITLE
[studio] Conflict between jQuery and other frameworks.

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#865]
When a site implements the UI using a framework like angular or react and the ICE tags are added there is possible issue:

If the attributes like `data-studio-ice-path` are changed by any other framework different than jQuery Studio will not be able to generate the ICE tags with the correct value because of an internal cache in jQuery.
The ICE tags will open the incorrect component even if the UI calls the method `studioICERepaint()`.

You can see the issue happening in the headless blog & store blueprints included in this PR: https://github.com/craftercms/studio/pull/716

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/426
