### ISSUE TITLE
[studio-ui] Change icons: pencil, magnifying glass, upload/delete image, etc.

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#870]
Please update the default icons as follows:

General
--------

- Pencil: http://fontawesome.io/icon/pencil/
- Dashboard: http://fontawesome.io/icon/tasks/
- Magnifying glass (search and everywhere we use the magnifying glass): http://fontawesome.io/icon/search/
- Wrench: http://fontawesome.io/icon/wrench/
- Trash: http://fontawesome.io/icon/trash-o/
- Download: http://fontawesome.io/icon/download/ (example, hover over image in the form engine)
- Zoom: http://fontawesome.io/icon/search-plus/ (example, hover over image in the form engine)

Sidebar
--------
- SiteConfig: http://fontawesome.io/icon/sliders/
- scripts: http://fontawesome.io/icon/code/
- static-assets: http://fontawesome.io/icon/file-image-o/
- pages: http://fontawesome.io/icon/file-text-o/
- components: http://fontawesome.io/icon/puzzle-piece/
- taxonomy: http://fontawesome.io/icon/tags/
- templates: http://fontawesome.io/icon/file-code-o/

- child icon open: http://fontawesome.io/icon/folder-open-o/
- child icon closed: http://fontawesome.io/icon/folder-o/

Content Types
---------------
- Add image (content type preview image): http://fontawesome.io/icon/plus/
- Remove image (content type preview image): http://fontawesome.io/icon/ban/

Site Config Tools (pending ticket to make this possible)
-------------------------------------------------------
- Preview Sync: http://fontawesome.io/icon/refresh/
- Sync from Repo: http://fontawesome.io/icon/refresh/
- Audit: http://fontawesome.io/icon/align-justify/
- Groups: users: http://fontawesome.io/icon/users/
- Content Types: http://fontawesome.io/icon/th-large/
- Bulk Operations: http://fontawesome.io/icon/arrows-alt/
- Workflow States: http://fontawesome.io/icon/cog/
- Logging Levels: http://fontawesome.io/icon/level-down/
- Log Console: http://fontawesome.io/icon/align-left/
- Configuration: http://fontawesome.io/icon/cog/

**Comment by vestrada** [comment]
I have updated zoom and download images in the hover over image in the form engine.

**Comment by vestrada** [comment]
We changed content types icons: 
Add image (content type preview image): http://fontawesome.io/icon/upload/
Remove image (content type preview image): http://fontawesome.io/icon/trash-o/

**Comment by vestrada** [comment]
master - PR: https://github.com/craftercms/studio2-ui/pull/451
