### ISSUE TITLE
[studio-ui] Can't close image dialog

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#880]
Steps to reproduce:
- Create a site based on Editorial BP
- Edit the homepage
- Scroll down to the strawberries image
- Hover over the image and click on the + sign
- Now you're stuck :)

At a minimum, `escape` should work. Ping me if you have smarter options.
![screen shot 2017-05-26 at 11 28 49 am](https://cloud.githubusercontent.com/assets/3931908/26501130/9a43ca8a-4206-11e7-93a1-87700a982005.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/431
