### ISSUE TITLE
[studio-ui] Update workflow and mime-type icons

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#881]
Please update workflow icons to become:

Workflow
----------
Workflow icons are overlays to the MIME-type of the item in a particular state. These are also color coded.

Overlays are done like the `Stacked` example here: http://fontawesome.io/examples/

- Live: http://fontawesome.io/icon/flag-checkered/ -- color: #73c438
- Processing: http://fontawesome.io/icon/spinner/ -- color: #4879db with `fa-spin`
- Locked: http://fontawesome.io/icon/lock/ -- color: #dd7e2c
- Never published: http://fontawesome.io/icon/plus/ -- color: #41ecfc
- Deleted: http://fontawesome.io/icon/ban/ -- color: #ce2d2d
- Scheduled: http://fontawesome.io/icon/clock-o/ -- color: #487c22
- In Workflow: http://fontawesome.io/icon/flag-o/ -- color: #245875
- Edited: http://fontawesome.io/icon/pencil-square-o/ -- color: #ede925

Please update MIME-type icons (ping me if you're not getting mime-types from API)

MIME-types (built-in)
---------------------
The default color for all MIME-type icons is: #4b4d5b

- Crafter Navigation Page: http://fontawesome.io/icon/file/
- Crafter Floating Page: http://fontawesome.io/icon/file-o/
- Crafter Component: http://fontawesome.io/icon/puzzle-piece/
- Unknown MIME-type: http://fontawesome.io/icon/file-text/
- Video: http://fontawesome.io/icon/file-video-o/
- Image: http://fontawesome.io/icon/file-image-o/
- PDF: http://fontawesome.io/icon/file-pdf-o/
- Powerpoint: http://fontawesome.io/icon/file-powerpoint-o/
- Word: http://fontawesome.io/icon/file-word-o/
- Excel: http://fontawesome.io/icon/file-excel-o/
- .zip: http://fontawesome.io/icon/file-archive-o/
- .js: http://fontawesome.io/icon/file-code-o/
- .groovy: http://fontawesome.io/icon/file-code-o/
- .css: http://fontawesome.io/icon/css3/
- .ftl: http://fontawesome.io/icon/file-code-o/

Please built the override mime-type mechanism and populate all 4 blueprints with commented out example.

MIME-types can be overridden
-------------------------------
- Allow override via the file mime-type.xml under `/config/studio/mime-type.xml`
- XML schema for that file is:
```
<mime-types>
	<mime-type>
		<type />
		<icon>
			<class>fa-something</class>
			<styles>
				<color>#ffffff</color> <!-- color will not be honored because of worklfow -->
				<font-size>24px</font-size>
				<border />
				<background-color />
			</styles>
		</icon>
	</mime-type>
</mime-types>
```

- Please create an commented out example shell for this file in all 4 blueprints.

**Comment by sumerjabri** [comment]
@jvega-crafter per our conversation, we no longer want to do this one:
- Live: http://fontawesome.io/icon/flag-checkered/ -- color: #73c438

Instead, live items have no emblems.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/448
