### ISSUE TITLE
[studio-ui] Move persona icon one step to the left in the top bar

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#883]
Please swap the location of the persona editor and the search spyglass. See screenshot:
![screen shot 2017-05-26 at 4 01 21 pm](https://cloud.githubusercontent.com/assets/3931908/26510718/aafa7664-422c-11e7-8cf5-8ba1a2df3f84.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/440
