### ISSUE TITLE
[studio-ui] Add bar between site functionality and global functionality in top bar

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#884]
Please add a separator between site specific top bar icons and global functionality. Please use this separator: http://fontawesome.io/icon/ellipsis-v/

Please choose a color that's grayish and works with the rest of the color scheme.

Screenshot:
![screen shot 2017-05-26 at 4 04 43 pm](https://cloud.githubusercontent.com/assets/3931908/26510893/60d0d29e-422d-11e7-9f16-c6a3fc6e6756.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/442

**Comment by sumerjabri** [comment]
Please change the separator to be a standard HTML vertical line. Please ping @russdanner for more detail if needed.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/453

**Comment by sumerjabri** [comment]
Let's change the color to the same color as the username per our conversation.

**Comment by vestrada** [comment]
master -> PR: https://github.com/craftercms/studio2-ui/pull/454
