### ISSUE TITLE
[studio-ui] Replace textual navs with icons

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#885]
Please replace the top navigation bar items with icons:
- users: http://fontawesome.io/icon/users/
- sites: http://fontawesome.io/icon/sitemap/
- help: http://fontawesome.io/icon/life-ring/

Please make it such that if the user hovers over the item you show tooltip with the old name. If you can animate the menu sideways and slide the text in to the right of the icon, that's better. Ping me for details.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/430

**Comment by sumerjabri** [comment]
Please do the same for:
- Search magnifying glass
- Persona (the persona editor)
- Preview Tools (the wrench)
- In-Context Edit (the pencil)

**Comment by vestrada** [comment]
master - PR: https://github.com/craftercms/studio2-ui/pull/451
