### ISSUE TITLE
[studio-ui] "Users" on top right of Studio is visible to site admin 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#888]
Please hide/remove "Users on the top right of Studio for site admin users as they are not supposed to be able to access that menu. Although, right now, when you click on "Users", it takes you to the "Sites" menu (list of sites), it would be nicer to just not have it visible at all to the user.

1. Create an admin user.
2. Login as the newly created admin user.  Notice that "Users" is visible on the top right of Crafter Studio.

![screen shot 2017-05-30 at 10 38 35 am](https://cloud.githubusercontent.com/assets/25483966/26589112/24493d84-4525-11e7-996b-17db42af2a69.png)

**Comment by sumerjabri** [comment]
Please hide the "Users" menu item for everyone that's not a global admin.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/432

**Comment by alhambrav** [comment]
Verified fixed.
