### ISSUE TITLE
[craftercms] "mongod" No such file or directory when Starting MongoDB

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#889]
Run
#./gradlew start

notice on the screen when starting MongoDB for both authoring and delivery that it says:

```
------------------------------------------------------------
Starting MongoDB
------------------------------------------------------------
./crafter.sh: line 146: /Users/me/temp/test2/craftercms/crafter-delivery-env/bin/mongodb/bin/mongod: No such file or directory
```

And if I check the MongoDB folder, it is indeed empty:
```
➜  craftercms git:(master) ls crafter-delivery-env/bin/mongodb
➜  craftercms git:(master)
```

**Comment by cortiz** [comment]
while we (I) work on a fix for this you can:
1 Go  to the `crafter-auth|dev-env` folder
2 Delete the mongodb folder
3. Run the `./startup.sh|bat ` script that will make all things work just fine.

**Comment by alhambrav** [comment]
Verified Fixed.
