### ISSUE TITLE
[studio-ui] Update controls and data sources in all blueprints

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#894]
Please update the icons for controls and data sources for all blueprints using FontAwesome as follows:

Controls
---------
- DropDown: `fa-sort-desc`
- Checkboxes: `fa-check-square-o`
- Input: `fa-pencil-square-o`
- Repeating Group: `fa-repeat `
- Rich Text Editor: `fa-code`
- Form Section: `fa-object-group`
- Text Area: `fa-paragraph`
- Date and Time: `fa-calendar` + `fa-clock-o` overlay
- Item Selector: `fa-crosshairs`
- Image: `fa-picture-o`
- Video: `fa-video-camera`
- Label: `fa-tag`
- Page Order: `fa-sort`
- File Name: `fa-file-o`
- Auto Filename: `fa-file-o` + `fa-magic` overlay
- File Desktop Upload: `fa-upload`

Data Sources
--------------
- Child Content: `fa-child`
- Image from Desktop: `fa-picture-o`
- Image from Repo: `fa-file-image-o`
- File Browse: `fa-hand-o-up`
- Video from Repo: `fa-file-video-o`
- Video from Desktop: `fa-video-camera`
- Static Key Value Pairs: `fa-key`
- Site Component: `fa-puzzle-piece`

**Comment by vestrada** [comment]
Hi @sumerjabri
We have one icon missing: file desktop upload.

**Comment by sumerjabri** [comment]
Added at the end of the list of controls.

**Comment by vestrada** [comment]
studio - PR: https://github.com/craftercms/studio/pull/723
