### ISSUE TITLE
[studio-ui] It would be nice to display a message when a user is not allowed to delete a group

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#895]
It would be nice to display a message that the user is not allowed/unauthorized to delete a group.  

1. Login as anybody except for the Crafter Admin user.  In the image below, user "noobadmin" is logged in. (noobadmin is a member of the admin group)
2. Go to Site Config -> Groups
3. Click on the trash can icon on any of the groups listed to delete.  Click "Yes" in the confirmation dialog.  Notice that nothing happens and it would be nice to have a message appear that the action is not allowed.

![screen shot 2017-05-31 at 10 21 30 am](https://cloud.githubusercontent.com/assets/25483966/26636573/3940579c-45eb-11e7-8ae0-173686020c63.png)

**Comment by sumerjabri** [comment]
Use the message: "Unauthorized. You don't have sufficient privileges to perform this action."

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/433

**Comment by alhambrav** [comment]
Verified fixed.
