### ISSUE TITLE
[craftercms] Add Profile/Social Admin Consoles to Delivery

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#896]
Please add the Crafter Profile/Social admin consoles to the delivery bundle and wire accordingly.

**Comment by cortiz** [comment]
Solve in #939

**Comment by sumerjabri** [comment]
Doesn't seem to work.

Steps I Used
-------------
- `./gradlew -Pcrafter.profile=true -Penv=delivery build deploy`
- `ls crafter-delivery-env/bin/apache-tomcat/webapps`

Result
```
~/code/crafter/craftercms (master ✔) ᐅ ls crafter-delivery-env/bin/apache-tomcat/webapps
ROOT.war            crafter-profile.war crafter-search.war  crafter-social.war
```

**Comment by cortiz** [comment]
I'm moving this back to test & validate, I'm unable to reproduce it on Linux/windows/macOS but it's possible could be related to the issue that artifacts sometimes are not copied #958

**Comment by cortiz** [comment]
Solve in #1022
