### ISSUE TITLE
[craftercms] Update `tail log` message in `start` task

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#903]
Please update the `tail log` message in the `start` task from:
`To follow the logs, please tail this log files in: [path]/logs/`

to:

`Log files live here: "[path]/logs/". To follow the main tomcat log, you can "tail -f [path]/logs/tomcat/catalina.out`

Please make sure to update for both delivery and authoring envs.

**Comment by cortiz** [comment]
PR #924
