### ISSUE TITLE
[studio-ui] Sorting breaks studio search

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#906]
When the `Alphabetical` option is selected the request has two fields for the `sortBy` parameter but the service is expecting only one:

![screen shot 2017-06-01 at 10 16 20 am](https://cloud.githubusercontent.com/assets/1236955/26697321/c549d1b2-46ce-11e7-8724-1ffe1dc4f98f.png)

**Comment by vestrada** [comment]
studio-ui - PR: https://github.com/craftercms/studio2-ui/pull/439
