### ISSUE TITLE
[studio-ui] Session timeout re-login fails

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#913]
Steps
------
- Login and go to a site
- Leave this browser overnight (or some large duration that's > 120mins)
- You'll see the new `Login` dialog that will let you in exactly where you left off
- Login using that dialog
- Wait a few mins and the dialog shows up again (because it seems that this login didn't really work)

It seems that leaving the system for a very long time causes the re-login via the new dialog not to work as intended.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/747
