### ISSUE TITLE
[studio-ui] Replace the +/- icons in the Sidebar tree with FA icons

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#915]
Please replace the +/- icons in the current tree in the Sidebar with FontAwesome icons:

- for `+` aka expand: `fa-plus-square-o`
- for `-` aka collapse: `fa-minus-square-o`

Please ping me if you have any questions.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/481
