### ISSUE TITLE
[studio-ui] Form engine does not resize properly for select type dialog

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#916]
<img width="1164" alt="screen shot 2017-06-05 at 8 02 45 am" src="https://cloud.githubusercontent.com/assets/169432/26783410/06618506-49c6-11e7-86b4-6aacb1fa2b0a.png">

# To reproduce:
1. Create a component type allows you to associate another component (item selector)
2. Create a component based on this type.  Using the item selector, create a new component of the same type.
3. Repeat step 2, note that each time you nest a form, the form gets a little smaller (that's the correct behavior.)  By the 3 layer of forms,  the open form is fairly small.  When the user hits add new, the dialog shows up but is cut off so that the choose and cancel buttons cannot be accessed.

# correction
The form engine should re-size to accommodate the dialog.

**Comment by russdanner** [comment]
Form can be resized manually until bug is corrected:
<img width="1164" alt="screen shot 2017-06-05 at 8 02 45 am" src="https://cloud.githubusercontent.com/assets/169432/26785981/e4d9cac6-49d2-11e7-86fd-96a4c44632e8.png">

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/441

**Comment by russdanner** [comment]
The issue must be addressed in 2.5

**Comment by sumerjabri** [comment]
@vestrada please fix in 2.5 too please

**Comment by vestrada** [comment]
2.5.x -> PR: https://github.com/craftercms/studio2-ui/pull/447

**Comment by russdanner** [comment]
Verified
