### ISSUE TITLE
[studio] ContentItemTO retrieved by ContentService is not setting the value for attribute getContentType properly

### ISSUE THREAD

**Issue by kmarcos** [craftercms/craftercms#917]
In crafter 2.5, I have following code:

```
ContentItemTO contentItem = contentService.getContentItem(site, fullPath);
String contentType = contentItem.getContentType();
logger.info(“checking content type: “+contentType);
```

I'm running this and the fullPath is of a component with:

	`<content-type>/component/document-content</content-type>`

I'm expecting to get 

`/component/document-content ` 

in the output but instead I'm getting

`pages`

I think the service is not setting the value for getContentType properly

**Comment by sumerjabri** [comment]
@dejan-brkic we need to also fix this in 3.x if it's an issue in there too.

**Comment by dejan-brkic** [comment]
Can not reproduce issue.
There is only one possible use case where it can get such value. It is if system is detecting item as deleted (can not find it). That would mean that actual method parameters are not assigned with proper values. site -> site id, path -> relative path to site content root (e.g. /site/website/index.xml or /site/components/component.xml

**Comment by russdanner** [comment]
I'll work with kmarcos to find out more details -- and if it's not a deleted item, what the steps are to reproduce it.

/R

**Comment by russdanner** [comment]
Closed due to insufficient details to reproduce.

**Comment by kmarcos** [comment]
Hello crafter team.

I found the cause of the error and it was in my code:

I assumed wrongly the call for following service methods required the same path value as input:

```
contentService.getContentAsDocument(path)
contentService.getContentItem(site, path)
```

and the path I was sending was previously completed with 

`expandRelativeSitePath(site, relativePath)`

As it was working fine with the first one I assumed it should be working with the second one, and as the service was returning a valid object I didn't realize the call was invalid.

Thanks @dejan-brkic  for the explanation, it helped me to find the error.
