### ISSUE TITLE
[studio] Update APIs to include the return of MIME type

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#920]
Please update the API:

`/studio/api/1/services/api/1/content/get-items-tree.json`
`/studio/api/1/services/api/1/activity/get-user-activities.json`
`/studio/api/1/services/api/1/deployment/get-scheduled-items.json`
`/studio/api/1/services/api/1/workflow/get-go-live-items.json`
`/studio/api/1/services/api/1/deployment/get-deployment-history.json`
`/studio/api/1/services/api/1/content/get-item.json`

to include in the return the MIME type of the item.

This is not to be confused with Crafter's content types, this is simply a new field `mimeType` in the response.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/729

**Comment by sumerjabri** [comment]
@jvega-crafter please validate and see if it works for you. If so, please close and move to `completed`.
