### ISSUE TITLE
[studio-ui] Clicking on an item in the dashboard displays a blank page only for home pages

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#926]
1. Create a new site using any out of the box blueprints.
2. Edit the home page to create an entry in the dashboard.
3. Go to the dashboard and in the **My Recent Activity** widget, click on the item you just edited (the home page link).  

![screen shot 2017-06-06 at 10 17 30 am](https://cloud.githubusercontent.com/assets/25483966/26833839/8bb7142e-4aa1-11e7-9943-653d4785ea8f.png)

Notice that clicking on the item takes you to a blank page.

![screen shot 2017-06-06 at 10 19 08 am](https://cloud.githubusercontent.com/assets/25483966/26833896/baa06de4-4aa1-11e7-9989-a913c29de547.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/444

**Comment by alhambrav** [comment]
Verified fixed.
