### ISSUE TITLE
ftl and groovy files mimetype incorrect - application/octet-stream

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#927]
Mimetype property on Freemarker (FTL) and Groovy files is being returned by APIs as `application/octet-stream`, please fix.

**Comment by dejan-brkic** [comment]
Done

Added mimetypes for .ftl (text/x-freemarker) and .groovy (text/x-groovy) files

PR:
https://github.com/craftercms/studio/pull/731

**Comment by sumerjabri** [comment]
@jvega-crafter please validate.

**Comment by jvega-crafter** [comment]
all good!
