### ISSUE TITLE
[studio-ui]  Update disabled content indication/notice text 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#928]
<img width="1324" alt="screen shot 2017-06-06 at 12 14 25 pm" src="https://user-images.githubusercontent.com/169432/26842060-8628d368-4ab9-11e7-94d9-f3df2502a3fc.png">

Change text to:
"This content is disabled"

**Comment by vestrada** [comment]
studio- ui -> PR: https://github.com/craftercms/studio2-ui/pull/445

**Comment by russdanner** [comment]
Please remove the . per the ticket instructions

**Comment by sumerjabri** [comment]
@vestrada please make it bigger also, it's too small right now.

While at this, please make the "Draft" notice also bigger.

Ping me if you need help.

**Comment by vestrada** [comment]
studio-ui - master - PR: https://github.com/craftercms/studio2-ui/pull/463
studio-ui - 2.5.x - PR: https://github.com/craftercms/studio2-ui/pull/464

**Comment by russdanner** [comment]
verified
