### ISSUE TITLE
[studio-ui] Firefox, only the top portion of an RTE (about 40px high) is clickable to activate that placeholder

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#929]
In Firefox only the top portion of an RTE (about 40px high) is clickable to activate that placeholder. If you click below that area, you can type in the placeholder but the editing toolbar is tied to the previously active placeholder.

# Steps to reproduce
1. Create a content type with multiple RTE fields
2. Create new content based on type
3. Observe stated behavior

**Comment by vestrada** [comment]
studio-ui -> PR: https://github.com/craftercms/craftercms/issues/929

**Comment by russdanner** [comment]
Ticket applies to 2.5 as well.

Verified in 3.x

**Comment by sumerjabri** [comment]
@vestrada please fix in 2.5 also.

**Comment by vestrada** [comment]
studio-ui -> 2.5 -> PR: https://github.com/craftercms/studio2-ui/pull/462

**Comment by russdanner** [comment]
verified
