### ISSUE TITLE
[studio] Add Disabled field to all page and component content types

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#930]
Please add the field `disabled` to all pages and component/item types

Control type: Check box
Label: "Disable (Page|Component|Article etc)"
Variable name must be "disabled"

**Comment by alhambrav** [comment]
Done.
PR https://github.com/craftercms/studio/pull/736

**Comment by russdanner** [comment]
Why does this say "Disable Page - Home", Why not just Disable Page?

Applies to other types as well.  I think this should just be kept simple.  Disable Page,  Disable Video (or Disable Component) etc. 
<img width="1347" alt="screen shot 2017-06-20 at 2 05 45 pm" src="https://user-images.githubusercontent.com/169432/27348325-a0dfafde-55c1-11e7-9bff-9e917f1861f5.png">

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/studio/pull/753

**Comment by russdanner** [comment]
Verified
