### ISSUE TITLE
[studio] All Blueprints, Section Defaults should have basic description at content type level

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#931]
Every content type can have a description.  Most content types are obvious, section defaults is not.

Add a description (found under basic content type properties) to the Section Default content type:

`Section Defaults provides inherited values to all children and sibling content items.  To learn more about content inheritance see docs.craftercms.org topic "Content Inheritance"`

**Comment by alhambrav** [comment]
Done.
PR https://github.com/craftercms/studio/pull/733

**Comment by russdanner** [comment]
Verified
