### ISSUE TITLE
[engine] Disabling a page in Studio results in a stack trace

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#936]
<img width="1429" alt="screen shot 2017-06-06 at 12 14 25 pm copy" src="https://user-images.githubusercontent.com/169432/26847769-3291f97e-4acc-11e7-8728-6e3d1bf024e1.png">

#expected behavior
- In authoring preview, page/component should render
- in delivery, page should 404, content should not be found

# step to reproduce
1. disable a page
2. preview page
3. observe

**Comment by jdrossl** [comment]
@sumerjabri should disabled pages only be available to render directly or also be listed in the site navigation (or any other template using SiteItemService.getSiteTree(...) ) ?

**Comment by sumerjabri** [comment]
@jdrossl the pages should not show up in search nor navigation. The page should render if requested directly in authoring and the warning "Disabled..." should show as it does now.

This means the author can see the page if they navigate to it, they *know* it's disabled and they can see the site without it (removed from nav and removed from search).

**Comment by russdanner** [comment]
Verified
