### ISSUE TITLE
[studio] Page URL field is required but the user cannot fill it because is "Only Read".

### ISSUE THREAD

**Issue by gortizcraftersoftware** [craftercms/craftercms#938]
Steps:
1. Go to Crafter 3 : http://localhost:8080/studio#/login
2. Create site with the blueprint "Empty".
3. Expand Pages.
4. Click on "New Content" for Home.
5. Select the content type "Entry" and click on OK.
6. See the field "Page URL".

Current Behavior:
The field "Page URL" cannot fill and it's requiered.

Video: https://www.useloom.com/share/2bf11e690d5b4bd7b519db6a15e10456
Ticket with this change mentioned: https://github.com/craftercms/craftercms/issues/918

Expected Bahavior:
1. The field "Page URL" should be not requiered.
or
2. The field "Page URL" should be fill properly.

**Comment by sumerjabri** [comment]
@alhambrav Not sure how we're going to tackle this. On the one hand we wanted the homepage URL to be read-only, but in the case of the Empty BP, it only has 1 page type and hence the problem. We can discuss and decide on what to do here.

**Comment by alhambrav** [comment]
Based on discussion, we decided to just let the user be able to change the URL for the empty bp.

PR https://github.com/craftercms/studio/pull/742
