### ISSUE TITLE
[docs] Update/move FTL documentation under Engine

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#948]
Please rename this article: http://docs.craftercms.org/en/3.0/developers/templating-api.html

to be FreeMarker (Templating) API and put under the API section of Crafter Engine.

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/269
Commit: https://github.com/craftercms/docs/pull/269/commits/beaf2c69a7fbd968400f4c4a8759b9f5f6cbe831
