### ISSUE TITLE
[studio-ui] Getting js error when loading site on authoring rendering view and live site

### ISSUE THREAD

**Issue by asotog** [craftercms/craftercms#950]
JS Error displayed in browser dev tools console

<img width="1399" alt="screen shot 2017-06-08 at 4 05 05 pm" src="https://user-images.githubusercontent.com/813023/26952814-4926efca-4c64-11e7-9988-e008d8415846.png">

Current
When looking any page on authoring preview, i see not error.
But when going to authoring rendering or live site i noticed the posted above js error

Environment: crafter cloud

**Comment by sumerjabri** [comment]
@asotog:
- what version of the software are you using?
- what do you mean by `authoring rendering`?
