### ISSUE TITLE
[studio-ui] Disable/hide "Duplicate" in context nav for /site/website/index.xml (home)

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#953]
It would be nice to disable/hide "Duplicate" in the context nav for the /site/website/index.xml (home page) since you can't duplicate them anyway (I get an error after saving)

![screen shot 2017-06-09 at 12 43 46 pm](https://user-images.githubusercontent.com/25483966/26985599-331ef94e-4d12-11e7-9b7b-0ad84975e532.png)

Here's the error message that you'll get after trying to duplicate the home page:

![screen shot 2017-06-09 at 12 43 30 pm](https://user-images.githubusercontent.com/25483966/26985635-67eaaae2-4d12-11e7-9f4b-61a16e735402.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/449

**Comment by alhambrav** [comment]
Verified fixed.
