### ISSUE TITLE
[studio] Search doesn't work with dots and hyphens when searching for filenames or internal names

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#954]
Queries for filenames like test.pdf and internal names like 2-3-4 Test don't work.

**Comment by avasquez614** [comment]
A possible solution is to do this query: "2-3-4 Test" OR *2-3-4 Test* OR (2-3-4 Test)

**Comment by jdrossl** [comment]
The search is working as expected in 3.0, I will test in 2.5.x

**Comment by jdrossl** [comment]
This is also working as expected in 2.5.x using file repo, the only limitation is that queries for `localId` & `internal-name` are case sensitive.

**Comment by avasquez614** [comment]
@jdrossl just make sure this has been completely verified both in 2.5.x and 3.0

**Comment by jdrossl** [comment]
@avasquez614 Verified with clean installs for both versions.
