### ISSUE TITLE
[studio-ui] Call invalidate cache after saving any configuration file / content type

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#957]
In order to make the system easier to use, please do the following:
- Automatically call cache invalidation after saving a configuration file in SiteConfig
- Automatically call cache invalidation after saving or creating a content type
- Remove cache invalidation link from the configuration section

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/485
