### ISSUE TITLE
[craftercms] No startup.sh and shutdown.sh in crafter-{env}-crafter-deployer

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#958]
There is a `startup.bat` and `shutdown.bat` file but no `startup.sh` and `shutdown.sh` in `crafter-{env}-crafter-deployer` (both authoring and delivery environments does not have shell scripts for deployer startup and shutdown)

**Comment by cortiz** [comment]
Solve on #1038

**Comment by alhambrav** [comment]
There's still no `startup.sh` and `shutdown.sh` file in the folder `crafter-auth-env/bin/crafter-deployer` or `crafter-delivery-env/bin/crafter-deployer`

I also looked at the resources and it's not there.

<img width="902" alt="screen shot 2017-06-28 at 2 45 22 am" src="https://user-images.githubusercontent.com/25483966/27624018-1269e4da-5bad-11e7-90b4-b83aa16748ad.png">

**Comment by cortiz** [comment]
PR #1044

**Comment by alhambrav** [comment]
Verified fixed.
