### ISSUE TITLE
[studio-ui] Change Studio's font to Open Sans

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#961]
Please change the UI's font to: https://fonts.google.com/specimen/Open+Sans

The font family should be: `font-family: 'Open Sans', sans-serif;`

Please make sure all existing dialogs and columns/rows still work well with the new font.

For instance:
![icon-guide-issues](https://user-images.githubusercontent.com/3931908/27751060-858c9ee2-5da8-11e7-9bf5-ebc759ef3c01.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/508
