### ISSUE TITLE
[studio-ui] Change UI colors/font size

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#962]
Please change:
- Color of section headings in Sidebar to look like SiteConfig color
- Color of icons of SiteConfig to look like Sidebar
- Font size of SiteConfig to be like Sidebar

See attachments:
![screen shot 2017-06-12 at 4 59 58 pm](https://user-images.githubusercontent.com/3931908/27057298-8d8e81f4-4f99-11e7-9b5c-114e6d4b052f.png)
![screen shot 2017-06-12 at 5 00 02 pm](https://user-images.githubusercontent.com/3931908/27057297-8d8dbfb2-4f99-11e7-8127-02b74c6262bc.png)

**Comment by vestrada** [comment]
master- PR: https://github.com/craftercms/studio2-ui/pull/452
