### ISSUE TITLE
[studio-ui] Changing the channel viewport loses the device frame, and it's hard to use

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#963]
Two issues with the channel configuration:
1. Per our conversation: When changing the channel viewport dimensions to be larger than the guest area under Preview Tools / Channels, the device boundary (smart phone, tablet graphic) is outside the view area and we can't scroll there to see it.
Screenshot:
![screen shot 2017-06-12 at 6 08 20 pm](https://user-images.githubusercontent.com/3931908/27057416-21d48ad4-4f9a-11e7-8bb5-ec6b5bda997f.png)

2. Clicking on the Dimensions input box and then pressing Control + A (Command + A) to select all, loses the selection after a second. This causes typos that then cause the screen to get way out of whack and sometimes causes the browser to try to render very large screens and die (for example, you select all, then paste a number, it will unselect while you're pasting and you end up with two pasted numbers that are very large.
We need the behavior to be:
- You can select all and it won't change a thing
- You can paste/edit and nothing happens for .5 seconds
- If a another change happens within .5 seconds, you reset the timer to .5 seconds
- If no change happens for .5 seconds and the field has changed, then re-render the guest

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/450
