### ISSUE TITLE
[studio-ui] Move site name and resize

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#964]
Please move the site name to the right of the string `Sidebar` and change the font size to 16px bold.

Please see this screenshot for an example:
![screen shot 2017-06-13 at 11 10 48 am](https://user-images.githubusercontent.com/3931908/27090071-2d4d2f66-502a-11e7-9810-9eb233067976.png)

for the screenshot above, I used:
```
    font-family: 'Open Sans', sans-serif;
    font: bold 16px/16px 'Open Sans';
```

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/510
