### ISSUE TITLE
[studio-ui] Implement targeting UI and drop Personas UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#971]
Per our conversation earlier today, please implement the targeting UI and drop the personas UI.

The targeting UI configuration is per blueprint and is in the file:
`/config/studio/targeting/targeting-config.xml`

Please look at the Editorial BP for a decent example of the configuration.

Please note that the UI will support three types of controls to help the authors change the values of the targeting properties: checkboxes, dropdown, and input field per the XML definition.

Please follow the steps in the screenshots below to implement:
![screen shot 2017-06-05 at 10 02 05 am](https://user-images.githubusercontent.com/3931908/27197513-7297409e-51dc-11e7-8619-43dbc8aec82b.png)

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/474
