### ISSUE TITLE
[studio] Add site publishing status flag

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#976]
Please add a flag to the site table indicating the publishing status:
- Idle
- Busy
- Blocked

We will add APIs on top of this in a following ticket. The APIs will request the status, and get `idle` meaning it's ready to work, `busy` means it's working, and `blocked` meaning it's in error and blocked on something.

Please consider adding a status string in addition to the flag that explains what the error is so that when an error occurs, that error message is right there when we poll for status.

**Comment by sumerjabri** [comment]
Per our conversation:
* Add two columns to the site table (change the names if you like): `publishing_enabled`, `publishing_status_message`
* The publisher algorithm will be
  * If publishing is not enabled, return
  * Set message to `Publishing file: {file name}" and change it with every new file being published
  * Set message to `Completed publishing file: {file name}` where that's the last file published
  * If something went wrong, set the message to `Failed to publish file: {file name}, reason: {exception}` and set `publishing_enabled` to false

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/756

**Comment by dejan-brkic** [comment]
Done
https://github.com/craftercms/studio/pull/758
