### ISSUE TITLE
[studio] Delete of a published page not working

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#978]
Using Editorial bp:

1. Create a new temp landing page (e.g. Health 2).
2. Publish the new page.
3. Delete the page.

Result: the page is never deleted. Same thing happens if you edit and existing page, publish and then try to delete it.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/750

**Comment by avasquez614** [comment]
Tested, fix works.
