### ISSUE TITLE
[studio] Implement Publishing APIs (status, start, stop)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#979]
Please implement the APIs as spec'd:
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/status.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/start.html
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/stop.html

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/756

**Comment by sumerjabri** [comment]
Execute the API: /api/1/services/api/1/publish/status.json without params and you get back 500 instead of 400. Also, the message doesn't comply with API spec.

**Comment by sumerjabri** [comment]
Please add logs: Debug for happy path and error for errors, etc.

**Comment by sumerjabri** [comment]
* Initialize publishing with a non-null message in upgrade script.
* Change code to warn on null and not fail if the message is null

**Comment by dejan-brkic** [comment]
Done
https://github.com/craftercms/studio/pull/758
