### ISSUE TITLE
[studio-ui] Add Publishing Status

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#980]
Please add an icon to the top row of icons while in site view mode to the right of Search. The icon class is: `fa-cloud-upload` with text description "Publishing Status"

The icon color is based on the return of this API call:
http://docs.craftercms.org/en/3.0/developers/projects/studio/api/publish/status.html

Color scheme, if the returned `"status"` is:
- `"idle"` icon color is unchanged / normal
- `"busy"` icon color is orange
- `"stopped"` icon color is red
- `"unknown"` icon color is black and message is the exception if 3xx, 4xx, 5xx or unreachable

The API will be invoked every 60 seconds (like ticket validation) and the UI is updated.

If the user clicks on the icon, please show the `"message"` field of the last returned API call.

Ping me if you have any questions.

![screen shot 2017-06-19 at 4 26 59 pm](https://user-images.githubusercontent.com/3931908/27304487-3e564e32-550c-11e7-8843-6887b880d5b8.png)

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/459

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/461

**Comment by vestrada** [comment]
studio -> PR: https://github.com/craftercms/studio/pull/760
