### ISSUE TITLE
[studio] auto create groups and assign users based on LDAP

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#981]
Please augment the LDAP user provisioning logic to:
- User is auth'd via LDAP, then upsert the user (already done)
- Upsert the user's usergroups
- Upsert the user into these groups

The purpose of this to allow the roles to be attached to LDAP groups and that allows LDAP managers to assign users to roles on sites.

One issue is that we don't remove users from groups if LDAP removes them, and that will remain a "known" issue for now. Longer term, we will have to address this.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/772

**Comment by sumerjabri** [comment]
@avasquez614 please test and validate

**Comment by avasquez614** [comment]
Verified, it's working.
