### ISSUE TITLE
[studio-ui] Make text next to icons in top navigation clickable

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#984]
To see the issue, create a site from a BP and visit the homepage, now mouse over the search icon and note the text `search` appear. Click on the word `search`, note that it doesn't work.

Do the same for the users menu to the right of the dividing bar, and the text `users` works as a link.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio2-ui/pull/455
