### ISSUE TITLE
[studio-ui] Refactor the icon guide

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#993]
Please refactor the icon-guide at the bottom of the Dashboard to look like the attached image
![screen shot 2017-06-20 at 11 44 41 am](https://user-images.githubusercontent.com/3931908/27342335-e3475476-55ad-11e7-9a41-050564c3adff.png)

Order of Icons
---------------
- Workflow States
-- Never Published
-- Edited
-- In Workflow
-- Scheduled
-- Processing
-- Disabled
-- Deleted
-- Locked for Editing
- Item Types
-- Navigation Page
-- Floating Page
-- Component
-- Template or Script/JS
-- Taxonomy
-- Image
-- Video
-- CSS
-- Font (see #992 )
-- ... add all other mime-types
-- Other Files

**Comment by jvega-crafter** [comment]
Font icon added in icon guide, #992 pending
