### ISSUE TITLE
[studio-ui] Add taxonomy icons to taxonomies

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#994]
Please make files under Taxonomy have the icon: fa-tag

Taxonomy items can be identified by the content of `content-type` returned by the backend as `taxonomy`.

Please wait until Dejan is done with this ticket: https://github.com/craftercms/craftercms/issues/1006

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/482
