### ISSUE TITLE
[studio-ui]  Browse dialog should list items in alphabetical order

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#995]
The current  implementation does not.  See attached image:
<img width="1425" alt="screen shot 2017-06-20 at 12 13 31 pm" src="https://user-images.githubusercontent.com/169432/27343824-25e34a70-55b2-11e7-9a38-341769d673e4.png">

**Comment by sumerjabri** [comment]
@jvega-crafter if this is a backend issue, ping me and I'll reassign.

**Comment by jvega-crafter** [comment]
Was an issue in UI, fixed. https://github.com/craftercms/studio2-ui/pull/480

**Comment by russdanner** [comment]
Please fix in 2.5 as well

**Comment by jvega-crafter** [comment]
2.5 fix - https://github.com/craftercms/studio2-ui/pull/505

**Comment by russdanner** [comment]
It seems the sorting is Descending but should be Ascending

<img width="1265" alt="screen shot 2017-07-21 at 4 24 27 pm" src="https://user-images.githubusercontent.com/169432/28481021-3a858d70-6e31-11e7-9cbe-65282cbe50d3.png">

**Comment by jvega-crafter** [comment]
Sorting is ascending, but when it has similar names it is not sorting properly, coming from the service (you can see it on the screenshot, acomponent, left rail..., ..., zcomponent)
<img width="629" alt="screen shot 2017-07-24 at 12 51 07 pm" src="https://user-images.githubusercontent.com/18267471/28539494-1619ab3e-706f-11e7-881a-03fa36bbcd51.png">

**Comment by jvega-crafter** [comment]
Not reproducible
