### ISSUE TITLE
[studio-ui]  Dashboard and sidebar do not render properly in firefox 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#996]
<img width="1361" alt="screen shot 2017-06-20 at 2 10 25 pm" src="https://user-images.githubusercontent.com/169432/27348534-65932d60-55c2-11e7-921a-37c51a793c58.png">

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/476

**Comment by russdanner** [comment]
verified
