### ISSUE TITLE
[studio-ui] Change icon colors

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#997]
Per my convo with Vero: Presently all icons in the sidebar and dashboard are a pale gray: #cecece and they're hard to see. Let's try: #80bfff color for all item colors in sidebar, dashboard, icon guide etc.

![screen shot 2017-06-20 at 2 18 37 pm](https://user-images.githubusercontent.com/3931908/27348849-69eaade2-55c3-11e7-980b-b196ce26f58e.png)

**Comment by vestrada** [comment]
@sumerjabri I used: #8fc6fd. Let me know if you like it.

studio-ui -> PR: https://github.com/craftercms/studio2-ui/pull/458
