### ISSUE TITLE
[studio-ui]  User gets feedback when clicking add new on node selector/child content when no types apply

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#998]
# Steps to reproduce
in editorial:
1. edit home page
2. go to widgets, select and edit Left Rail with Latest Articles
3. go to Widgets and click add
4. click create new
Nothing happens.

# Feedback
The ajax call for available types is []
User has no feedback that no types apply to the configure path

**Comment by vestrada** [comment]
studio-ui -> master -> PR: https://github.com/craftercms/studio2-ui/pull/468

**Comment by vestrada** [comment]
Per conversation with Russ the feedback dialog should say:
"There are no content types available that can be created at the configured path"

**Comment by russdanner** [comment]
verified
